### ISSUE TITLE
[OS X] Folder Icons throwing "File is ignore because it's hidden"

### ISSUE THREAD

**Issue by marbetschar** [owncloud/client#3992] opened 2015-10-23 09:04 UTC
### Steps to reproduce
1. Define a custom folder icon on OS X for a synced folder inside of the ownCloud directory
2. Wait for the sync to throwing the error "FolderName/Icon - File is ignored because it's hidden"

### Expected behavior
It would be very cool if the folder icons set on OS X will be synced to other devices! If this is not the intended behaviour, then at least no error should occur.

### Actual behavior
The sync client throws an error.

### Server configuration
**Operating system**:
OSX El Capitan v10.11

**Web server:**
NGINX

**Database:**
MySQL

**PHP version:**
5.6.14-1

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**

```
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'drive.mandelkind.pizza',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://owncloud.mandelkind.coffee',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => 'mandelkind'
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No - how to enable encryption?

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by guruz** [comment] 2015-10-23 13:04
You could change the client's settings ```Sync hidden files```?

**Comment by kaefert** [comment] 2015-11-10 17:49
aha! thanks for the hint that there is a new setting to make the client to sync hidden files. this was the default behavior previously I think and after updating my client stopped syncing them...

**Comment by ogoffart** [comment] 2016-01-18 17:25
Sort fo duplicate of #3688

**Closed by ogoffart** 2016-01-18 17:25 UTC
Labels: Needs info
