### ISSUE TITLE
[2.2.0] Upload progress bar displays confusing values for filesize and number of files

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4856] opened 2016-05-17 19:02 UTC
![upload-progress-error](https://cloud.githubusercontent.com/assets/214010/15334955/9ff5553c-1c70-11e6-87ad-a0f62950ad1c.gif)

### Expected behaviour
If I upload one 26MB file, the upload progress bar should display exactly "file 1 of 1" and "X MB of 26MB"

### Actual behaviour
The 2.2.0 client shows wrong values. (see animation)

It looks like the client sums up the filesizes and number of files of all files that already exist in my account.

### Steps to reproduce
1. Initial sync download of 25 items with 60MB in total
2. upload one 26 MB file with sync client ==> "X MB of 82 MB, file 25 of 25"
3. upload one more 26 MB file with sync client ==> "X MB of 107 MB, file 26 of 26"
4. upload one more 26 MB file with sync client ==> "X MB of 132 MB, file 27 of 27"

### Server configuration
Operating system:
Debian

Web server: 
Apache

Database:
SQLite

PHP version:
5

ownCloud version:
9.0.2

Storage backend:
local storage

### Client configuration
Client version:
ownCloud-2.2.0.3358.pkg

Operating system:
Mac OS X 10.11.1

OS language:
English

Installation path of client:
/Applications/owncloud.app

@dragotin What happens here? Maybe related: https://github.com/owncloud/client/issues/4832

00005496

**Comment by guruz** [comment] 2016-05-18 10:05
@michaelstingl There is no "Show package contents" in the right-mouse-button menu of that file on your desktop?

**Comment by michaelstingl** [comment] 2016-05-18 11:10
@guruz No, the [ownCloud-2.2.0.3358.pkg from our website](https://download.owncloud.com/desktop/stable/ownCloud-2.2.0.3358.pkg) is one compressed file, not a Mac OS X bundle.

**Comment by guruz** [comment] 2016-05-18 14:56
Similar https://github.com/owncloud/client/issues/4832

FYI @enoch85

**Comment by enoch85** [comment] 2016-05-18 15:50
@guruz Yes, I saw this issue before, and I can confirm this as well.

**Comment by ckamm** [comment] 2016-05-20 10:48
Pull request: #4872

**Comment by frank9999** [comment] 2016-05-23 08:47
This issue seems to be partially fixed. The counter seems to reset after uploads and doesn't sum everything together, which is good.
However the counter still starts with a random number (possibly failed uploads?).

For example:
If I upload 1 file, it says uploading 11 of 11 files.
If I upload 2 files, it says uploading 11 of 12 files.

On another test machine:
If I upload 1 file, it says uploading 5 of 5 files.
If I upload 2 files, it says uploading 5 of 6 files.

**Comment by michaelstingl** [comment] 2016-05-23 09:07
@frank9999 Thank you for your feedback!

**Comment by mcastroSG** [comment] 2016-05-23 09:22
@frank9999  which build are you using for testing ¿?

It´s working fine for me with:

ClientOS: W10
Client Version: 2.2.1-nightly20160523 (build 6108)

[Build for Windows](https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.1.6108-nightly20160523-setup.exe)

ClientOS : OS X El capitán 10.11.4
Client Version: Version 2.2.1-nightly20160523 (build 3390)

[Build for OS X ](https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.1.3390-nightly20160523.pkg)

**Comment by frank9999** [comment] 2016-05-23 09:38
I'm building from source, latest commit in the 2.2 branch. I get the same results from your nightly build.

ClientOS: W10

**Comment by mcastroSG** [comment] 2016-05-23 11:02
@frank9999  you are right, it´s not working properly, still testing to find a pattern

**Comment by mcastroSG** [comment] 2016-05-23 12:20
Hi hi:

@ckamm  I´ve made some test to discover something new, and i hope this could help to found a solution:

On a fresh Shared Sync folder:

 Step | Action |  X of Y shown  | Comments 
|:----:|:------------- |:-------------------|:-------------|
1 | Copy one file to Shared Sync root folder | 1 of 1 | OK 
2 | Copy two files to Shared Sync root folder | 2 of 2 | OK
3 | Create a folder | 1 of 1 | OK
4 | Copy one file to Shared Sync root folder  | 2 of 2 | NOK
5 | Copy one file to Shared Sync root folder  | 1 of 1 | OK
6 | Create a folder | 1 of 1 | OK
7 | Copy two file to Shared Sync root folder  | 3 of 3 | NOK


Step | Action | X of Y shown  | Comments 
|:----:|:------------- |:-------------------|:-------------|
1 | Create a folder1 | 1 of 1 | OK
2 | Copy one file to folder1 | 1 of 2 | NOK 


Step | Action | X of Y shown  | Comments 
|:----:|:------------- |:-------------------|:-------------|
1 | Copy one file to Shared Sync root folder | 1 of 1 | OK 
2 | Create a folder1 | 1 of 1 | OK
3 | Copy one file to folder1 | 1 of 3 | NOK 


Step | Action |  X of Y shown  | Comments 
|:----:|:------------- |:-------------------|:-------------|
1 | Create a folder1 | 1 of 1 | OK
2 | Copy one file to folder1 | 1 of 2 | NOK 
3 | Create a folder2 at folder1 | 1 of 1 | OK
4 | Copy one file to folder2 | 1 of 5 | NOK 
5 | Copy one file to folder2 | 1 of 3 | NOK 
6 | Copy one file to folder2 | 1 of 5 | NOK 
7 | Copy one file to folder2 | 1 of 3 | NOK 

Step | Action | X of Y shown  | Comments 
|:----:|:------------- |:-------------------|:-------------|
1 | Create a folder1 | 1 of 1 | OK
2 | Create a folder2  at folder1 | 1 of 1 | OK
3 | Copy one file to folder2 | 1 of 3 | NOK 
4 | Copy one file to folder2 | 1 of 3 | NOK 

Step | Action | X of Y shown  | Comments 
|:----:|:------------- |:-------------------|:-------------|
1 | Create a folder1 | 1 of 1 | OK
2 | Copy one file to folder1 | 1 of 2 | NOK 
3 | Create a folder2  at folder1 | 1 of 1 | OK
4 | Copy one file to folder2 | 1 of 5 | NOK
5 | Create a folder3  at folder2 | 1 of 1 | OK
6 | Copy one file to folder3 | 1 of 7 | NOK
7 | Create a folder4  at folder3 | 1 of 1 | OK
8 | Copy one file to folder4 | 1 of 9 | NOK
9 | Copy one file to folder4 | 1 of 3 | NOK
10 | Copy one file to folder4 | 1 of 9 | NOK

Results may vary due to I´ve checked that sometimes it returns 1 of 3 instead of 1 of 2 once you have created the first folder, but the pattern still remains.

**Comment by frank9999** [comment] 2016-05-25 10:51
Is there any progress on this issue? We are willing to test any new patches as soon as you have them

**Comment by danimo** [comment] 2016-05-25 11:06
@frank9999 Also here, you can help testing nightlies: https://download.owncloud.com/download/nightly/

**Comment by frank9999** [comment] 2016-05-25 11:41
@danimo I just tested the following nightly: https://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6112-nightly20160525-setup.exe.

Bug is still there.

**Comment by ckamm** [comment] 2016-05-25 14:04
I'll be able to look at this on Friday if it's still unresolved by then.

**Comment by ckamm** [comment] 2016-05-27 08:26
@mcastroSG Thanks for all that data. I've found the origin of the surprising counts. Pull request: https://github.com/owncloud/client/pull/4910

**Comment by ckamm** [comment] 2016-05-27 08:52
The patches have been merged and the next build should have correct file counts.

**Comment by frank9999** [comment] 2016-05-27 10:45
The fix seems to work for me! Thanks!

**Closed** 2016-05-27 11:01 UTC
Labels: blue-ticket, ReadyToTest
