### ISSUE TITLE
Notifications - OK button doesn't do anything

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7563] opened 2019-10-30 12:35 UTC
Client: 2.6.0rc2 (build 12577)
Server: 10.3.0 stable
macOS 10.15

Steps to recreate:
1) Install Custom Groups from the Marketplace
2) Create a new group on the server
3) Add a user
4) Change their role
5) Click OK in the Activity tab in the desktop client

Actual result: OK button doesn't work
Expected result: The button is not present at all 

Similar to https://github.com/owncloud/client/pull/7361

![Screenshot 2019-10-29 at 16 55 46](https://user-images.githubusercontent.com/49001702/67858637-fa15d600-fb19-11e9-8cc8-65b09913a108.png)

**Comment by ogoffart** [comment] 2019-10-30 13:08
Closing as duplicate of #7355
( #7361 was merged after the 2.6.0-rc2 was released)

**Closed by ogoffart** 2019-10-30 13:08 UTC
Labels: bug, p3-medium
