### ISSUE TITLE
[Qt < 5.4] About dialog: git build version information text chopped off

### ISSUE THREAD

**Issue by sudhirkhanger** [owncloud/client#3088] opened 2015-04-09 19:06 UTC
The text gets chopped off in default view.

![snapshot1](https://cloud.githubusercontent.com/assets/841656/7074615/80d83ee8-df19-11e4-9cea-7ced3a94dfef.png)

**Comment by danimo** [comment] 2015-04-09 19:10
It doesn't need a scrollview, it needs a layout fix :)

**Comment by ckamm** [comment] 2015-04-10 07:35
@donniezazen For me, the text becomes visible when I increase the size of the dialog. Does the same happen for you?

If so, I don't think anything needs to be done. When the dialog is to small for the 'General' tab, it's most noticeable on the 'About' section.

**Comment by donniezazen** [comment] 2015-04-10 08:41
@ckamm Yes, the text would not get chopped if I increase the height of the window. The text gets chopped off with the minimum height set by the ownCloud-client. Either the minimum height should be increased if you are looking for hardcoding a solution or you should add a ScrollView in About text so that  change in hardcoded height or text string doesn't chop off the text. Does that make sense?

**Comment by ckamm** [comment] 2015-04-10 09:25
Hm, it seems the problem is a bug with labels that have wrapped text, see https://bugreports.qt.io/browse/QTBUG-37673 . That's why I can resize the dialog freely.

**Comment by ckamm** [comment] 2015-04-10 09:54
I now spent some time trying to get the label to layout correctly with Qt 5.2.1. The only change that had a reasonable effect was setting the label's vertical size policy to Minimum. But that unreasonably increases the whole settingsdialog's minimum size.

I think this issue should be deferred for the time when target systems are expected to have Qt >=5.4 which has the fix for QTBUG-37673.

**Comment by guruz** [comment] 2015-04-14 09:53
Linking https://github.com/owncloud/client/issues/2558

**Comment by sudhirkhanger** [comment] 2015-09-16 11:44
Seems like fixed in `owncloud-client-2.0.1-3.1.x86_64`.

**Comment by sudhirkhanger** [comment] 2015-12-05 16:57
Problem came back in 2.x.x.

![snapshot6](https://cloud.githubusercontent.com/assets/841656/11608987/55923872-9b9f-11e5-808b-51792a3db2c8.png)

**Comment by SamuAlfageme** [comment] 2017-07-27 11:16
closing via https://github.com/owncloud/client/issues/5760

**Closed by SamuAlfageme** 2017-07-27 11:16 UTC
Labels: Known Issue / Workaround, ReadyToTest
