### ISSUE TITLE
Check checksums or file contents before assuming a file was moved (instead of just mtime+inode)

### ISSUE THREAD

**Issue by FlorentCoppint** [owncloud/client#2983] opened 2015-03-18 15:22 UTC
Hi everyone,

Today I upgraded my Owncloud server to 8.0.2.

Then I upgraded my client to 1.8. I'm on Ubuntu.

I didn't open my client for a few days so Owncloud Client synced a few files with server.

And in "Activity" I can see this line:
![owncloud-bug](https://cloud.githubusercontent.com/assets/7386692/6711986/944c5658-cd8a-11e4-8e7a-07b1bedda4b6.png)

Can someone explain me this ?! files are totally different (.cnf is a text file & .gpg is a private key).
AND .cnf file was deleted yesterday on client !!
Owncloud client didn't modify anything on client, but on server, .gpg got content of .cnf... absolutely absude :)

Is it an issue ?

Tell me if you need more information.

Thank you.

**Comment by ogoffart** [comment] 2015-03-22 09:07
Can you please provide the log.  The corresponding entry on the .owncloud.log file would be usefull.
Do you have more infrmation about the files?  What was the size in byte of each files? and what was the mtime of each files?

Here is my theory:  The .cnf file was removed, and the .gpg file was created a bit later but recieved the same inode as the previously deleted file. The size of the two files happen to be the same, and also the mtime was set to the same as the old one. And therefore the client tought it was a move.

**Comment by FlorentCoppint** [comment] 2015-03-23 08:30
I have this in logs:
15:04:16|695|git/mariadb-ansible/templates/my.cnf|INST_RENAME|Up|1426236634|55031d22b339a|0|00157393522e02bad1dfe|4||0|0|0|||INST_NONE|

Nothing about .gpg file.

That would be strange they had same size & same mtime...

.gpg file is 6714 bytes. I don't known exact size of .cnf file but it's around 5000-6000 ...

**Comment by ogoffart** [comment] 2015-03-24 08:52
If this is what I think, it is a quite unlikely event but that still can happen. The only way I see to solve this problem would be to use checksum in the database

**Comment by FlorentCoppint** [comment] 2015-03-24 09:00
I think this is a good solution, at least for files having same size.

**Comment by dragotin** [comment] 2015-04-08 15:46
We work on the checksum thing, but that wont make it to 1.8.1 any more. Moving.

**Comment by ckamm** [comment] 2015-10-02 13:29
@dragotin Am I understanding correctly that this ticket should be called "Check checksums before assuming a file was moved"?

**Comment by guruz** [comment] 2015-10-02 15:46
Note the whole move detection business is tricky
https://github.com/owncloud/client/blob/master/csync/src/csync_update.c#L277-l295

**Comment by ogoffart** [comment] 2015-10-22 09:11
@ckamm yes exactly.
@guruz move detection is trivial,  if the file is gone and there is a new file with the same inode and mtime and size, it is a move.  (the same fileid and etag on the remote).  The lines you pasted has nothing to do with moves, but maybe because the link is outdated.

The problem is that same inode, mtime, and size  might still not be a move and checking checksum in addition should solve the problem.

**Comment by guruz** [comment] 2015-11-03 14:48
Status: We now compute a checksum on download/upload and could use this info.
Still moving to 2.2 because the .eml problem is more important 
https://github.com/owncloud/client/issues/3235

**Comment by guruz** [comment] 2015-11-03 15:51
Slightly related: https://github.com/owncloud/client/issues/4034

**Comment by ckamm** [comment] 2016-01-20 12:22
The check is now implemented, but only works for files that have a content checksum (.eml files that were uploaded). See #4375 for details on enabling more checksumming.

**Comment by dragotin** [comment] 2016-02-29 13:34
@ckamm and @ogoffart do you think this should/could be added for all files? Once we have the checksum in the database we could use it, right?

**Comment by ckamm** [comment] 2016-02-29 13:35
@dragotin Yes, I think we should start creating content checksums for everything on download and then make use of them.

**Comment by mcastroSG** [comment] 2016-05-11 08:59
Hi hi:

### Test 1

**Steps Executed**

1.- Connect desktop client to a server that has cksum capabilities enabled
2.- Include file1.eml file to Shared sync folder
3.- Wait till sync ends
4.- Move file1.eml to file2.eml
5.- Wait till sync ends

**Results**

Desktop client check cksum to  discover if this case is a move.

`05-11 10:57:31:644 0x7f98d489e680 csync_walker: file: /Users/XXXX/ownCloud/file2.eml [inode=1261703 size=7]
05-11 10:57:31:645 0x7f98d489e680 _csync_detect_update: Checking for rename based on inode # 1261703
05-11 10:57:31:649 0x7f98d489e680 _csync_detect_update: checking checksum of potential rename file2.eml 54312ef83663ead54b89b1ed90e935239d8b2f74 <-> 54312ef83663ead54b89b1ed90e935239d8b2f74
05-11 10:57:31:649 0x7f98d489e680 _csync_detect_update: pot rename detected based on inode # 1261703
05-11 10:57:31:649 0x7f98d489e680 _csync_detect_update: file: file2.eml, instruction: INSTRUCTION_EVAL_RENAME <<=`

### Test 2

**Steps Executed**

1.- Connect desktop client to a server that has cksum capabilities enabled
2.- Include ppt file to Shared sync folder
3.- Wait till sync ends
4.- Move ppt file to change its name
5.- Wait till sync ends

**Results**

Desktop client check cksum to  discover if this case is a move.

`05-11 10:45:51:545 0x7f98d489e680 csync_walker: file: /Users/****/ownCloud/test3.ppt [inode=1256219 size=9] 
05-11 10:45:51:546 0x7f98d489e680 _csync_detect_update: Checking for rename based on inode # 1256219
05-11 10:45:51:549 0x7f98d489e680 _csync_detect_update: checking checksum of potential rename test3.ppt b847219a7bbdc39ae9a941ffcf3db2c58cdf52ff <-> b847219a7bbdc39ae9a941ffcf3db2c58cdf52ff
05-11 10:45:51:549 0x7f98d489e680 _csync_detect_update: pot rename detected based on inode # 1256219
05-11 10:45:51:549 0x7f98d489e680 _csync_detect_update: file: test3.ppt, instruction: INSTRUCTION_EVAL_RENAME <<=  `

**Closed by mcastroSG** 2016-05-11 08:59 UTC
Labels: bug, ReadyToTest, sev2-high
