### ISSUE TITLE
[Share with users, groups] if it is shared with a group and a user, you should only see a folder

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4124] opened 2015-11-12 10:41 UTC
### Steps to reproduce
1. Go to the Server web
2. Create a new users (e.g diana, diana1, diana2, diana3), and these users belong to the group "name"
3. Open your ownCloud desktop client, with user1
4. Go to Open Folder "user1"
5. Create a new folder, called aaa
4. Right click on the folder aaa
5. Select share with ownCloud 
6. Write the name for the group "name"
7. Click on Search
8. The folder Share with (e.g diana2)
9. Open your oC desktop client, with diana2
10. You can see the share folder (aaa)
![screen shot 2015-11-12 at 11 30 00](https://cloud.githubusercontent.com/assets/12032058/11116138/d49bd53c-8930-11e5-9b04-a62af729a833.png)
11. Go to the Desktop client with user1
 Right click on the folder aaa 
10. Select share with ownCloud
11. Write the name for the user "diana2"
12. Click on Search
13. Go to the Desktop client with diana2

### Expected behaviour
You should only see a folder

### Actual behaviour
You can see two folder with the same name
![screen shot 2015-11-12 at 11 35 16](https://cloud.githubusercontent.com/assets/12032058/11116242/97142e3e-8931-11e5-8954-a5274daba018.png)

### Server configuration
Desktop v ownCloud-2.1.0.2871-nightly20151111.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

related with #3737

**Comment by rullzer** [comment] 2015-11-13 10:20
This is actually not a client bug but is caused by how we handle sharing on the server. I think there is a bug report for that already. But can't find it currently.

**Comment by rullzer** [comment] 2015-11-19 11:05
@Dianafg76 could you verify that you see the same folders on the server?

**Comment by Dianafg76** [comment] 2015-11-19 12:38
@rullzer, @ogoffart I tested this issue.
if I follow the above steps:
1.- On Desktop client now I can see one folder
![screen shot 2015-11-19 at 13 35 29](https://cloud.githubusercontent.com/assets/12032058/11270846/8588a636-8ec2-11e5-84f3-4129d6ad5980.png)

2.- On Server Web, now I see two folders with the same name 
![screen shot 2015-11-19 at 13 37 16](https://cloud.githubusercontent.com/assets/12032058/11270870/b08ec32e-8ec2-11e5-95db-d7b21fc6442b.png)


### Server configuration
Desktop v 2.1.0 (build 2895)
Server {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by rullzer** [comment] 2015-11-20 07:38
mmm so it is very weird that you would see 1 folder on the desktop but multiple in the webinterface. They should provide the save view. Now I'm not so sure this is just a server bug.

**Comment by Dianafg76** [comment] 2015-11-20 07:57
I retested again today and on the Desktop Client I can see two folders also
![screen shot 2015-11-20 at 08 55 45](https://cloud.githubusercontent.com/assets/12032058/11294537/8b4b0f94-8f64-11e5-936e-cd71ed7cea44.png)

**Comment by rullzer** [comment] 2015-11-20 07:59
Aaah ok that at least make sense. Then this is nothing the client can solve. And we should fix on the server (which will happen once sharing 2.0 is fully implemented, https://github.com/owncloud/core/issues/19331). Closing this then.

**Closed by rullzer** 2015-11-20 07:59 UTC
Labels: bug, Server Involved, Sharing
