### ISSUE TITLE
[Windows] Primitive syncing mechanism locks files and makes them unusable

### ISSUE THREAD

**Issue by Steve06** [owncloud/client#2070] opened 2014-08-17 16:34 UTC
I am using the owncloud client 1.62 on my Windows 8.1 computer and whenever a file is being synced (which can takes a while depending on file size and upload speed), it is completely locked and cannot be altered, moved, deleted as long as the syncing (uploading) goes on. The process can only be interrupted by pausing the syncing or shutting down the client.

This is reminiscent of this issue https://github.com/owncloud/mirall/issues/1981 and further issues referenced therein. 

As it stands, this primitve syncing mechanism makes owncloud unusable in a professional environment. Owncloud developers should stop adding new features as well as revamping the interface and instead rather get the very basic things right. They should take the Dropbox client as a model in this respect, the best and most reliable syncing tool in the market.

A related issue is that sometimes while a file change has been detected by the client, the sync (upload) remains at 0 bytes and does not start until the client is restarted.

Until these issues are resolved we will use owncloud for experimentation only and rely on Dropbox for important work.

**Comment by ckamm** [comment] 2015-01-16 08:20
@lmaestro and others: it would be interesting to hear if the latest windows nightlies reduce or solve these kinds of problems (http://download.owncloud.com/desktop/daily/ >= 20150116). In particular: does working on a synced file with Word/Excel work better now?

**Comment by lmaestro** [comment] 2015-01-22 08:50
I works fine in version 1.8.0-nightly20150121 (build 4614) using WordPad on Windows 8.1

**Comment by danimo** [comment] 2015-01-22 08:56
@lmaestro Word and Wordpad are completely different code bases. Please test with a MS Word proper.

**Comment by lmaestro** [comment] 2015-01-22 10:05
@danimo @dragotin Can you please close it when you verify it using Word? Thx

**Comment by ckamm** [comment] 2015-01-22 13:25
@danimo @dragotin and me tried to reproduce the issue on Windows. Test cases:

* opened a file in MS Word and saved -> uploaded to sever while MS Word was running
* changed the file on the server -> the file was downloaded but could not be overwritten due to the lock by Word, there was a message about that on the client but no sync failure, nothing changed on the filesystem
* saved another version of the file -> nothing synced
* closed word -> the remote file was downloaded, the local file became a conflict

Another testcase:
* Copy a big file into the sync folder, wait for the upload to start
* Deleting or renaming of the file is possible

**Closed by ckamm** 2015-01-22 13:25 UTC
Labels: bug, enhancement - proposed, sev3-medium
