### ISSUE TITLE
Move and rename with delete permission 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7417] opened 2019-08-21 08:47 UTC
Related to: 
https://github.com/owncloud/client/issues/7293
https://github.com/owncloud/client/issues/7416
https://github.com/owncloud/client/issues/7294
https://github.com/owncloud/client/issues/7413

Windows 10
Client: 2.6.0daily20190820 (build 12286)
Server: 10.3.0 alpha, 10.2.1

Steps to recreate:

1. User A shares folder Test with user B, granting **delete** permissions.
2. User A creates folders Test/Sub, Test/testfolder and file Test/file.txt 
3. User B is connected with a desktop client, folder Test is synced.
4. User B **moves** testfolder into folder Sub

Actual result:
Linux: testfolder gets duplicated on the client.
Win10: moved folder on the client is no longer synced.
Expected result: 
Move not possible, folder structure not changed

5. User B **renames** Sub to subfolder

Actual result:
Linux: Sub gets duplicated on the client.
Win10: renamed folder on client is no longer synced.
Expected result:
Rename not allowed - not successful 

The same applies to files

**Comment by ckamm** [comment] 2019-08-27 08:52
When you say "Win10" do you mean Win10+vfs? I'm surprised there's a difference.

**Comment by ogoffart** [comment] 2019-10-14 10:55
When we restore, we download missing files, but we do not delete new files as this could lead to data-loss.

So I don't see what should be done to fix this.

**Comment by HanaGemela** [comment] 2019-10-15 10:49
@ogoffart do not allow renaming and moving without the change permissions

**Comment by ogoffart** [comment] 2019-10-15 12:10
We cannot forbid the user to do so on the file system. 
What we do usually if moving is not allowed is to restore the original. But here since we actually can do the change on the server, I see no reason why not.
This is a bit of a corner case, and I don't think it needs to be fixed

**Comment by TheOneRing** [comment] 2020-12-01 12:11
Duplicate of: https://github.com/owncloud/client/issues/7413

**Closed by TheOneRing** 2020-12-01 12:11 UTC
Labels: bug, sev3-medium
