### ISSUE TITLE
[QA] cannot log out

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10512] opened 2023-02-16 09:59 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with testpilot 3.2.0.10176

* connect client wit demo.owncloud.org
* Wait until sync completes. Wait several hours.
* open setings window, Account -> Log out. 

![image](https://user-images.githubusercontent.com/1108546/219329600-57a702e8-bb2d-4b13-aabf-de6cbcd4eff0.png)

* a requester appears, for entering the credentials, with buttons [log out] and [log in].
* As I want to log out. I try the log tu button. Te requester closes and reappears.
* Same when I try the log in button (without entering a password)
* Same when trying to close with the x.
* there seems no way to actually log out. 

Workaround: enter the password, then click log out again, then it works.

[tp320-log.zip](https://github.com/owncloud/client/files/10754582/tp320-log.zip)

### Steps to reproduce the issue

.

### Screenshots

Not reproducable. Sorry.

### Expected behavior

.

### Actual behavior

.

**Comment by TheOneRing** [comment] 2023-02-16 13:24
Duplicate of: https://github.com/owncloud/client/issues/10351

**Closed by TheOneRing** 2023-02-16 13:24 UTC
Labels: QA:team
