### ISSUE TITLE
Auto update: Client randomly fails to see updated client version

### ISSUE THREAD

**Issue by davedodo** [owncloud/client#6332] opened 2018-01-24 09:01 UTC
I have seen this issue occur randomly since I started using owncloud back in 2015. Sometimes, the client just doesn't see that an updated version is available, so you have to download the installer and upgrade manually. Since there is zero feedback from the client regarding the update check, I have no idea whats going on. An occasional outdated client was not a big issue in the past, so I didn't take time to report it. However, I just upgraded from OC 9 to 10 and now one of my users cannot log in, because she is using client 2.2.3 and the damn thing claims its the newest version.

Additionally, why not have a button in the client that allows the user to manually check for an updated version? Most software has this feature in some form or another.

### Expected behaviour
When an update is released, the client should see it and notify the user/install the update the the client is restarted.

### Actual behaviour
The client does not notice that an update is available and stays outdated.

### Steps to reproduce
Unknown.

### Client configuration
Client version:
2.2.3 (build 6307)

Operating system:
Windows 10 Home x64

OS language:
German

Installation path of client:
Default

**Comment by ogoffart** [comment] 2018-01-24 10:19
Can you open the client with the `--logwindow` command line argument?
You should see something like this in the log:

```
01-24 11:06:40:414 [ info gui.updater ]:	Checking for available update
01-24 11:06:40:414 [ info sync.accessmanager ]:	2 "" "https://updates.owncloud.com/client/?version=2.4.0.8723&platform=win32&oem=ownCloud&versionsuffix=-nightly20171123" has X-Request-ID "1f647884-bcb9-4d7c-bd7c-695f613a0f14"
01-24 11:06:40:622 [ info gui.updater ]:	Client is on latest version!
```

But indeed it seems it reproduced the problem myself, here with this rc version of the client.

Going to `https://updates.owncloud.com/client/?version=2.4.0.8723&platform=win32&oem=ownCloud&versionsuffix=-nightly20171123`  show indeed that there is no update.

Actually, it sometimes does.  I think that's because the updates.owncloud.com is set so the update only happens with a given probability. By doing the request 100 times, we see that the propability of getting an update seems to be about 10%
I think the reason is so that the userbase slowly updates and so if a critical bug is found by one of the few users that have updated, we can stop the update.

**Comment by davedodo** [comment] 2018-01-24 22:23
Thanks for the quick response. This is intriguing information. I asked my friend with the outdated client for the log output. I'll post it when it's available to me.

Does the client only check once for an update when it's first started?

**Comment by ogoffart** [comment] 2018-01-24 23:57
When it is started, and then every 10 hours.
We will change the probability to 100% soon.

**Comment by guruz** [comment] 2018-02-02 15:42
What we could do is to have a button that triggers the check with ```noThrottle=true``` URL parameter. (And only on button press...)

**Comment by ogoffart** [comment] 2018-02-13 08:28
I'm closing this issue here as it is not a client issue, but a simple configuration error on the updater server.
We'll try to keep in mind not to throttle for too long on the next update.

**Closed by ogoffart** 2018-02-13 08:28 UTC
Labels: Known Issue / Workaround, sev4-low

**Comment by guruz** [comment] 2018-02-13 13:42
It's a duplicate of https://github.com/owncloud/client/issues/3319

**Comment by davedodo** [comment] 2018-10-03 13:50
It's October now and I'm still experiencing this problem. I just realized that I am still running client 2.4.1. According to the change log, the next version was released in September. You said the client checks every 10 hours for an update. Despite the throttling, I find it odd that in over two months no update was discovered.

Anyway, I started the client with the logging argument. I can see the `Client is on latest version!` message, however, I can neither see `Checking for available update` nor any message containing `updates.owncloud.com`. The same goes for the current client 2.5.0, which I just manually installed. Is this normal?

**Comment by guruz** [comment] 2018-10-12 06:56
@davedodo You are sure you did not do https://doc.owncloud.org/desktop/1.8/autoupdate.html#preventing-automatic-updates-in-windows-environments ?

**Comment by guruz** [comment] 2018-10-12 07:04
@davedodo (I don't remember if you need ```--logdebug``` too to make the log more verbose)

**Comment by davedodo** [comment] 2018-10-18 20:21
@guruz No, I didn't turn updates off. Anyway, I enabled debug logging, now I can see the 3 messages. I guess I will have to wait for the next update and observe what happens then.

**Comment by davedodo** [comment] 2018-11-11 11:40
@guruz No, I didn't turn updates off. Anyway, I enabled debug logging, now I can see the 3 messages. I guess I will have to wait for the next update and observe what happens then.

**Comment by davedodo** [comment] 2018-11-11 11:50
@guruz Is there actually a `noThrottle` parameter or was that a suggestion to add one? If it already exists, it's not working.

Is it normal that the server response contains only empty tags when no update is available?

**Comment by guruz** [comment] 2018-11-20 19:48
The auto updater only engaged yesterday so that's why you didn't see anything :)
There is a `noThrottle=1` parameter that should work.


We need a manual button that uses `noThrottle=1`.. -> https://github.com/owncloud/client/issues/3319#issuecomment-365269912
