### ISSUE TITLE
[QA] Win10 new renamed folder remains in state sync in progress for some minutes

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8395] opened 2021-01-27 08:00 UTC
Installed: owncloud-client v2.7.5rc4
Connected: to demo.owmcloud.org
VFS for user 'admin' enabled

### Steps to reproduce
1. Create a new folder in Explorer for 'admin' 
2. Rename the folder
3. Check sync state 

### Result
The syn status remains in 'sync in progess'

Creating a new folder with default name works correctly.

![SyncInProgess](https://user-images.githubusercontent.com/75983861/105960527-a926c180-607d-11eb-8324-08aa5788fa66.PNG)

Logfile:
[20210127_0832_owncloud.log.0.gz](https://github.com/owncloud/client/files/5878537/20210127_0832_owncloud.log.0.gz)

**Comment by michaelstingl** [comment] 2021-01-27 08:11
You mean status is not updated? Does refresh/f5 in this folder helps? Navigate to other folder, then come back?

**Comment by gabi18** [comment] 2021-01-27 08:13
No, a refresh doesn't help.

**Comment by gabi18** [comment] 2021-01-27 08:39
Previous screenshot doesn't show correct user for folder.
![SyncinProgess2](https://user-images.githubusercontent.com/75983861/105965350-957e5980-6083-11eb-8afa-942deedd83e7.PNG)

**Comment by gabi18** [comment] 2021-01-27 08:55
After waiting for approx. 10 minutes correct state is shown.
![Syncyinprogress3](https://user-images.githubusercontent.com/75983861/105967047-b778db80-6085-11eb-9bf0-8b5259e7fc39.PNG)

**Comment by TheOneRing** [comment] 2021-02-01 12:53
Possibly a duplicate of https://github.com/owncloud/client/issues/8393

**Closed** 2022-07-12 09:43 UTC
Labels: p3-medium
