### ISSUE TITLE
push notifications - quickly discover new files

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#2988] opened 2015-03-19 07:55 UTC
say you have 2 computers. When you update a file on one, it uploads quite fast (after 5 seconds) to owncloud. But on the second computer it can take 30 seconds or more before it discovers that there is a new file. Why not as soon as it has been uploaded?
I don't know the sync protocol, but it seems to me that it depends on polling somewhere when push could  be much faster.
BTW. My use case is that the other computer has the printer and I want it printed quickly. But it could just as well be something that a partner should check out.

**Comment by nekoal** [comment] 2015-03-21 06:32
Possible scheme: client request server about changes in sync folder and pass wait_interval. If folder changed then server respond immediately else wait for changes until min (wait_interval, php_max_execution_time - time_to_form_answer). If no changes in interval server respond about it. This make shorter reaction time and don't increase number of requests. Of course scheme require requests for each sync folder in separate thread or setting asyncronous responce handlers. And require some changes in server behavior.

@pascalBokBok Is network sharing printer not option for some reason?

**Comment by ogoffart** [comment] 2015-03-22 09:00
Duplicate of #1075

**Closed by ogoffart** 2015-03-22 09:00 UTC
Labels: enhancement - proposed, Server Involved
