### ISSUE TITLE
Errors appear briefly and then are gone

### ISSUE THREAD

**Issue by dbolton** [owncloud/client#5516] opened 2017-02-05 22:30 UTC
### Expected behaviour
If there is an error that needs user attention, then the user should get a chance to read the error at their own pace (or copy the error to the clipboard if needed)

### Actual behaviour
The error message appears briefly as a Windows notification, but the notification/error message disappears before I get a chance to find the file location, or if I've stepped away from the computer when the sync happens, I never see the message. If there are multiple errors, the windows notification says the first error and then says something like "and 2 more errors" without details. 

If I open the error log with F12 it only shows logs starting from the moment I open the log window, not the errors in the last 10 minutes or so. 

Examples of these errors include:
 * Conflicting files (edited by two users at once)
 * File name conflicts (sometimes happens if I rename a file and only change a letter from upper to lowercase)

### Client configuration
Client version: Version 2.2.4 (build 6408). 

Operating system: Windows 10

OS language: US English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

**Comment by SamuAlfageme** [comment] 2017-02-06 08:54
@dbolton but you would still have info on the non-synced errors on the `Activity > Not Synced` tab, these include both error scenarios you pointed out, they also show in the account tab, right next to the folder sync connection that presents problems. 

True that the windows notifications could be linked to the first view or be persistent (not be closed automatically, until the user does). What's your opinion on this? 

Thanks for reporting! 😉

**Comment by dbolton** [comment] 2017-02-07 00:09
The Activity > Not Synced tab shows a list of ignored files (like Microsoft Word hidden temporary files), but it does not list file conflicts or file name conflicts. (I just created a file conflict to double check)

**Comment by hodyroff** [comment] 2017-02-08 08:40
Would not a 4th tab for errors make most sense? If I like to check for conflict files I would not want to go through all the ignored once and not go through all my activities, rather have them in one view: "conflict and errors" maybe? Lets collect/discuss ideas.

**Comment by dbolton** [comment] 2017-02-08 23:54
The ignore files list isn't very long on my computer so I'm fine with them there or in a separate fourth tab.  My main concern is that the errors are listed for longer than a moment so that the are available for reference when troubleshooting.

**Comment by pmaier1** [comment] 2017-03-10 11:22
So a 4th tab for errors definitely makes sense, some ideas:
- errors should stay permanently in a list until they are resolved
- would be nice to also provide some kind of error handling (e.g. ignore the file or similar)
- Error notification should pop-up once and need to be confirmed (not with every 'sync run' again and again)
- 'Account view' should then just say something like 'There were errors during sync. See error tab'
- Need to take care about overlaps between 'Not Synced' and 'Errors'
  a) Merge
  b) 'Not Synced' -> ignored files, 'Errors' -> errors and conflicts
-> probably b)

Real-world example that shows the need for error handling:

![client_errors](https://cloud.githubusercontent.com/assets/21193500/23793376/31bf1f58-058b-11e7-8726-d75e34204b37.png)

In this case I can only look for the files one-by-one and delete/reupload to make the errors disappear. Every 'sync run' shows the error notification again. Would be nice to be able to just dismiss/ignore those erroneous files, still see them in the error list in 'Activity' but have the client working smoothly.

Opinions/ideas? @guruz @ogoffart

**Comment by michaelstingl** [comment] 2017-03-30 20:07
More improvements:

- Files/folders excludes/blacklisted because of errors should be have **error icon** (not always consistent in 2.3.1, see screenshot)
- Column label "Action" is misleading (see screenshot)
- Add information to differentiate if the error is `Client > Server` or `Server > Client` (additional column or different icons? <img width="50" alt="client_state-error-128_png_at_master_ _owncloud_client" src="https://cloud.githubusercontent.com/assets/214010/24523859/cc8b1514-1594-11e7-9462-11cf2a683e12.png">)

<img width="699" alt="ie11_-_win8_1" src="https://cloud.githubusercontent.com/assets/214010/24523525/903c1bae-1593-11e7-83f1-9799a04ded5b.png">

**Comment by ckamm** [comment] 2017-06-27 09:50
@michaelstingl @pmaier1 @guruz An small incremental PR for better error display: https://github.com/owncloud/client/pull/5861

**Comment by ckamm** [comment] 2017-06-27 12:22
This one is about blacklisted errors looking like warnings: https://github.com/owncloud/client/pull/5865

**Comment by ckamm** [comment] 2017-09-12 10:12
I think the core issue of "errors appear briefly and are then gone" is fixed with the above PRs.

**Comment by SamuAlfageme** [comment] 2017-10-23 10:30
Indeed - 2.4 comes with @ckamm's great new error listing view: https://github.com/owncloud/client/pull/5861 

@dbolton you can try out the 2.4.0 alpha from https://owncloud.org/changelog/desktop/ 🎉

**Closed by SamuAlfageme** 2017-10-23 10:30 UTC
Labels: Design & UX, Feature, ReadyToTest
