### ISSUE TITLE
Issue: No download after upload via web

### ISSUE THREAD

**Issue by apg1980** [owncloud/client#3317] opened 2015-06-08 17:16 UTC
Hi,

i have a reproducable issue.
My environment is owncloud 8.0.3 on obunutu 14.04 with user_ldap user accounts.
MySQL to 5.5.39
PHP to 5.4.32
Apache to 2.4.10
Owncloud Client ownCloud-1.8.2.5166-setup.exe (same behaviour with ownCloud-1.8.1.5050-setup.exe).

Following share is shared with UserA from my account:
/sharing/usera/share-with-me

UserA is uploading via webinterface to the share. UserA client is unable to sync with the client.
Also my account can get the file via the webinterface but is not downloadet via the client.

UserA is copying a file into the local folder /share-with-me. The file is immediately uploading and i also get after some seconds.

this beaviour is strange, if some user are sharing files into folders i've shared with them. i did not get them to my local computer.

i figured out, if myself or the user is renaming a file that was recently uploaded via the webinterface, all web uploaded files are downloadet via the client to my local computer.

is there a solution?

**Comment by Dianafg76** [comment] 2015-06-09 09:23
@apg1980 For Windows, please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5167-nightly20150609-setup.exe. I can't reproduce the bug

**Comment by guruz** [comment] 2015-06-09 14:08
@Dianafg76 Which server version did you try with?

@PVince81 ^^ see share issue above?

**Comment by PVince81** [comment] 2015-06-09 14:22
This is fixed on 8.1, it's the "sharing etag propagation issue".

**Comment by guruz** [comment] 2015-06-09 16:12
@apg1980 OK, need to try 8.1 then

thanks @PVince81

**Closed by guruz** 2015-06-09 16:12 UTC
Labels: Needs info
