### ISSUE TITLE
[Windows] [1.7.0] causes windows file manager issues

### ISSUE THREAD

**Issue by texxasrulez** [owncloud/client#2696] opened 2015-01-13 17:53 UTC
The latest update to owncloud desktop client (1.7.0) causes (on 2 separate computers) Autocad to lock up whenever a "windows manager" is needed. When clicking on the "open" icon, it hangs when the file explorer come should come up. It also hangs when trying to insert blocks, again, the windows file explorer is supposed to open, but will not due to freezing. Once I uninstalled owncloud desktop client, my Autocad returned to normal on both computers.

 I love your software and have become addicted and dependent on it. Keep up the good work ...

**Comment by texxasrulez** [comment] 2015-01-13 18:59
Desktop Client 1.7.1 has the same issue.

**Comment by texxasrulez** [comment] 2015-01-13 21:42
To be a little more specific, the pc's in question has Windows 7 and Autocad2011. I have a 3rd pc running Windows 7 and Autocad2007 that has no issues with 1.7.1 desktop client.installed and running.

**Comment by texxasrulez** [comment] 2015-01-13 21:54
To be more specific. The 2 pc's in question are running Windows 7 and Autocad2011. I have a 3rd pc running Windows 7 and Autocad2007 with owncloud desktop client 1.7.1.4382 running with no problems with opening or inserting.

**Comment by danimo** [comment] 2015-01-13 22:00
@texxasrulez Does the PC that shows the problem have several people logged in at once?

**Comment by texxasrulez** [comment] 2015-01-13 22:39
Only I was logged in. As I say, it is 2 computers with the issue. Standalone license of Autocad for both. One is a Dell and the other is custom built. The only things that are the same is Windows 7 and Autocad 2011

**Comment by guruz** [comment] 2015-01-14 14:10
@ogoffart Does this smell like https://github.com/owncloud/client/issues/2576 ?

**Comment by texxasrulez** [comment] 2015-01-15 22:36
I would have to check when I get back to work. I have the owncloud desktop client installed on several pc's and the only issues I have seen or been told of is the Autocad situation. I will verify registry entry tomorrow.

**Comment by ogoffart** [comment] 2015-01-19 15:50
Closing as a duplicate of #2576

**Closed by ogoffart** 2015-01-19 15:50 UTC
Labels: bug, Needs info, sev3-medium
