### ISSUE TITLE
[Arch Linux] [2.1.0 beta] QNetworkReply::NetworkError(RemoteHostClosedError)

### ISSUE THREAD

**Issue by jesusvazquez** [owncloud/client#4388] opened 2016-01-24 17:18 UTC
Hello, 

I'm using arch and owncloud client 2.1.0. My server has https enabled with an untrusted cert, once I accept the warning message about the cert I enter my user and password and I get a "Connection closed" error message.

Running **owncloud --logwindow** I get this output:

```
01-24 18:08:53:495 13699 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://*****" + "/"
01-24 18:08:53:851 13699 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(RemoteHostClosedError) "Connection closed" QVariant(Invalid)
01-24 18:08:53:851 13699 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
```

Owncloud server version:

```
curl https://****/status.php --insecure | python -m json.tool 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    95    0    95    0     0    341      0 --:--:-- --:--:-- --:--:--   342
{
    "edition": "",
    "installed": true,
    "maintenance": false,
    "version": "8.2.2.2",
    "versionstring": "8.2.2"
}
```

I have iptables running in the server and I tried changing the default policy for both INPUT and OUTPUT chains in orther to test if it worked but it didnt... Maybe I'm missing something.

[Android client](https://play.google.com/store/apps/details?id=com.ocloud24.android) is working just fine.

Thanks for your time.

**Comment by guruz** [comment] 2016-01-25 06:04
I believe this is a duplicate of https://github.com/owncloud/client/issues/3888 or https://github.com/owncloud/client/issues/4051 with Qt Patches lacking.
It should work with the Patches or by switching to Qt 5.6..

**Closed** 2016-02-07 10:44 UTC
Labels: Needs info

**Comment by acidicrebel** [comment] 2017-09-13 10:45
i have this same problem and i cant find a fix in any of those post

**Comment by acidicrebel** [comment] 2017-09-13 10:53
this post is a problem there is no sulution for and this gunzu fuck closed it

**Comment by michaelstingl** [comment] 2017-09-13 13:05
Please test with the new 2.3.3 version with Qt 5.6

**Comment by acidicrebel** [comment] 2017-09-14 09:14
already did that its so fck wierd and peepz keep saying its the proxy or firewall but thats bs becaus we already have turned it all the way off and still nothing XD so pleas come to my post #6030 thanks
