### ISSUE TITLE
Feature Request: Increase the font Size of the Progress Display

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#6339] opened 2018-01-31 16:08 UTC
![size](https://user-images.githubusercontent.com/24212810/35633347-49479b08-06a9-11e8-9658-e52bf810708c.png)

A user in central informed us that the Text size in the progress bar is too small.

It would be nice if we could increase this.

Here is a link to the original post:

https://central.owncloud.org/t/text-size-of-the-progress-bar/11657/2

**Comment by SamuAlfageme** [comment] 2018-01-31 16:29
Duplicate of https://github.com/owncloud/client/issues/2519 - specific to _oldish_ versions/themes for Windows. Will continue asking on central. 

Thx @voroyam

**Closed by SamuAlfageme** 2018-01-31 16:29 UTC
Labels: Enhancement
