### ISSUE TITLE
[Feature Request] invalidate sync db for a given sync relationship and restart syncing

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#5130] opened 2016-08-22 18:57 UTC
For reason whatever, some folders of my synced environment were no longer there, but I was able to see them in the browser. They were there before, but from one day to another some folders were gone. I was not able to get them back into sync, pause and continue did not work nor stopping and restarting the sync service. The only thing that helped was breaking the sync and resetting it up.

The FR is, to create a mechanism (button, command) where you can invalidate the sync db while keeping the relationship and restart syncing.
### Server configuration

Operating system: Ubuntu 14.04

Web server: nginx

Database: mysql

PHP version: 5.5.9

ownCloud version: 9.1.0 stable

Storage backend (external storage):
### Client configuration

Client version: 2.2.3

Operating system: W7x64

OS language: German

Installation path of client: default

**Comment by ckamm** [comment] 2016-08-23 11:57
@mmattel If you have any extra information about these missing folders that'd be very interesting. This sounds like it'd potentially be an important bug to address!

About your proposal: This is nothing that regular users should ever need to do. At best we could add a hidden debug action to trigger this. You can get the same effect by closing the client, deleting the sync database (.csync_journal.db) and starting the client again.

**Comment by dragotin** [comment] 2016-08-23 13:38
Before doing that, it would be awesome if you could connect to the server with a normal webdav client and check if you can see the directory listed in the PROPFIND output of a propfind on the parent directory. Maybe you need to refresh the server file cache.

**Comment by davidjericho** [comment] 2016-10-06 00:44
@dragotin @ckamm We've had this issue occur a few times recently, and it was due to a dangling symlink for a user folder. 

In our case, the issue has been caused by  the following sequence:

/owncloud/data is a reliable storage mount, of course containing the relevant .ocdata file marking it as an ownCloud data directory.
Under this, was /owncloud/data/username, as a symlink to /remotestorage/username.

Unfortunately the /remotestorage mount failed, and failed in such a way that a file_exists check in PHP would return false, and ownCloud would promptly start flushing the filecache and shares table of any references. 

Fixing the /remotestorage mount, such that the symlink from the parent /owncloud/data was no longer dangling, resulted in file_exists now returning true, and the filecache being rebuilt in the usual manner. 

This has the obscure side effect of creating a weird partial state in the client where some files and directories aren't being synced. In a directory that isn't being synced, bumping the mtime by creating a sub-folder or file, has resulted in the sync that singular node to resume working properly, but it won't fix the overall sync. 

In every case, we've had to turn off the client, delete the .csync-journal.db file, and restart the client, with the sync then proceeding to work properly.

**Comment by ckamm** [comment] 2016-10-07 11:23
@davidjericho Thanks for the description! This sounds like something we might be able to reproduce! 

Minor: I've removed the mention of F5 from the documentation.

**Comment by ogoffart** [comment] 2016-10-13 09:22
Maybe the root cause of the bug is https://github.com/owncloud/client/issues/5190 ?

I guess that wil be fixed with https://github.com/owncloud/client/pull/5243 ?

**Comment by ckamm** [comment] 2016-10-17 05:57
Possibly, but I'm not sure yet how #5190 would apply to folders. Will think about it.

**Comment by ckamm** [comment] 2016-10-18 09:47
@davidjericho I've attempted to reproduce the problem, but I think I need your help.

After I've set up /data/username as a dangling symlink, how should I flush the filecache? I ran `occ files:scan` for the user, but don't think it wipes the cache. What do you do?

How can I produce files/folders that the client won't pick up on? When I run `files:scan` after restoring the symlink to working order, my client proceeds to download all the files and folders that were changed in the time the symlink was broken.

If I understand correctly, it sounds like you are able to produce a situation where the file content changes without the server etag changing. And I still can't reproduce that.

One guess I'm having is this one:
* Change data on the server, but don't sync it to the client yet.
* Break the symlink.
* Have the client attempt a sync. Propagation will fail and due to #5190, versions <2.3.0 will consider the parent directory synced.
* Restore the symlink.
* The client will not re-attempt to download the files that failed to download earlier.

This problem would be fixed in master (2.3.0 to-be).

**Comment by davidjericho** [comment] 2016-10-28 13:35
I only needed a sync client to access the site, for the metadata to be wiped out. No content change occurred either client or server side, no mtime change or any other change in the actual stored data. A tool like rsync would not do any transfer as mtimes, sizes and checksums were all identical. 

It might be worth mentioning that filesystem_check_changes on the server was set to 0. Just to be totally clear, there were no changes to the server side data store from either within or outside of ownCloud, and no changes to the client side local copy.

**Comment by ckamm** [comment] 2016-11-22 11:12
@davidjericho I couldn't reproduce the concrete behavior, so I attempted the following:

* Have a client sync all user data.
* Reset the owncloud instance's database and config.php
* Connect the client again
* Attempt whether local and remote changes propagate as expected

And that worked fine. At step 3, when the client connected to the new file database, the client updated all etags to be the new ones from the server, without redownloading anything. Subsequent file changes propagate in both directions.

Could you explain what "of creating a weird partial state in the client where some files and directories aren't being synced" means exactly? What I tried was:
* change a file in a subfolder on the server through the web interface, check that it gets propagated to the client
* change a file in a different subfolder on the client, check that it gets uploaded to the server

**Comment by davidjericho** [comment] 2016-11-24 00:13
Hello @ckamm, I've just had this occur again overnight in a big way, after we had updated to 8.2.9. This is with 2.2.4 clients. We had a storage subsystem crash, and it had to boot up again. 

Maybe a clue in the right direction, is that while a stat() on the server would reveal the presence of the file with all its attributes, the booting up state of the storage meant that all IO (i.e. fread()/fwrite()) would fail with an undetermined io error until at least one replica of the file was available. This resulted in the filecache being rebuilt in owncloud server side, and then the client would download all files again. In summary, directory listings were available, and we could stat files, but they were unable to be read() as the storage devices were still coming online.

If I stopped the client, deleted the .csync_journal.db and reconnected the client after the "Pending" state for the directory size for the folder in the owncloud server web interface went away (either by browsing the directory from the web interface, or doing a files:scan), no download occured and everything was working as expected client side.

**Comment by PVince81** [comment] 2016-11-24 10:40
Hmm, a partially unavailable storage you say ? Sounds tricky to detect...

**Comment by davidjericho** [comment] 2016-11-24 11:31
Of note, it only took one client connected at the time of a storage restart to trigger this event, which is why I suggest there's an issue with the way the client sequences the detection of such a change. I understand the difference between the FileID and ETag, however in this case the ETag has not changed. Nothing about the file other than the FileID has changed, which should be enough of an indication to examine further or ask for a confirmation. 

That we lose shares because of the FileID changing, is something for another ticket against the server. Amusingly @dragotin wrote about this in his blog in 2015. https://dragotin.wordpress.com/2015/03/13/owncloud-etags-and-fileids/

**Comment by ogoffart** [comment] 2017-04-28 09:42
That would be CTRL+F6  as implemented in 7c31da5a for issue #5666

**Closed by ogoffart** 2017-04-28 09:42 UTC
Labels: bug, Needs info, Server Involved

**Comment by mmattel** [comment] 2017-04-28 11:51
Question, is the key sequence documented and the documentation visible/accessible to users?

**Comment by ckamm** [comment] 2017-05-02 10:33
@mmattel No, it's an intentionally undocumented debug command, see https://github.com/owncloud/client/issues/5666#issuecomment-290457887 and https://github.com/owncloud/client/issues/5666#issuecomment-290345792 .

**Comment by guruz** [comment] 2017-05-03 08:28
@settermjd How do we not-document intentionally undocumented things?
:-)
