### ISSUE TITLE
LANG=C stops syncing on filename errors

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6986] opened 2019-01-17 12:47 UTC
## Tested 2.5.2rc1 on Mint 19

1) Wait until sync completes. Quit the client. Create locally a file or dir with UTF-8 glyphs, then start the client with LANG=C, an error message appears, and all sync activities are silently stopped. 

![image](https://user-images.githubusercontent.com/1108546/51319788-519cf680-1a5e-11e9-934b-504a8ce40051.png)

I'd expect that syncing of other files and folders would continue. 
In this example the folder sync-this gets synced only after the offending filename is fixed or removed.

2) When there is a filename on the server with UTF-8 characters, the client does not download the file, if running with LANG=C, even when (LC_ALL=en_US)

![image](https://user-images.githubusercontent.com/1108546/51319186-ac355300-1a5c-11e9-961b-3d779d640b6d.png)

3) My usual nit-pit here: A copy-tool should copy, whatever the name is. Garbage in, garbage out. 
I consider the owncloud-client a copy program, not spell checker.

**Comment by ogoffart** [comment] 2019-01-21 09:22
Less, usually, setting `LANG=C` means the FS should not have any non-ascii filenames. So errors are expected. However, the sync should continue.
But I was not able to reproduce this on master.  (I've set the milestone to 2.6 because is is a strange setup)


> My usual nit-pit here: A copy-tool should copy, whatever the name is. Garbage in, garbage out. I consider the owncloud-client a copy program, not spell checker.

I don't get what you mean here.  
If someone post a letter in a english mailbox with the address written in chinese, how is the postman supposed to deliver the mail?

The encoding of file names on the server is specified to be UTF-8.  You define the encoding of the filesystem to be 7 bit ASCII by setting `LANG=C`.  If the server contains filenames that have character that are not valid or cannot be encoded on the file system, we do not synchronize these files.
The alternative could be to try to escape or encode somehow the invalid characters, but that's making the sync much more difficult as we need to create some kind of a mapping, so we haven't done that.

**Comment by ogoffart** [comment] 2019-06-04 14:48
I cannot reproduce the problem. Probably fixed with 2.6.0

**Comment by ogoffart** [comment] 2019-10-21 13:04
Closing since there was no replies.

**Closed by ogoffart** 2019-10-21 13:04 UTC
Labels: ReadyToTest
