### ISSUE TITLE
[QA] windows client 2.9.0 crashes upon start, when sync root folder was removed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8801] opened 2021-07-02 11:48 UTC
Seen with ownCloud-2.9.0-daily20210701.4526.x64.GPO.msi on win10 20H2

* connect client to server, wait for initial sync to finish.
* stop client.
* remove the netire sync root folder
* start client. Immediate crash. 
Crash report "Sent! Many thanks. Please refer to crash e408b25c-f096-4914-b5d3-e1378a160277 (click to copy) in bug reports."

**Comment by jnweiger** [comment] 2021-07-02 11:51
PS: the crash dump window should allow copy paste and resizing.
I can copy the Sent! line as text, but the rest only allows a screenshot of a small portion.
![image](https://user-images.githubusercontent.com/1108546/124270418-7907b100-db3c-11eb-9eb8-d50f1e1aa905.png)

**Comment by jnweiger** [comment] 2021-07-02 11:51
not a regression, happens also with 2.8.2

**Comment by TheOneRing** [comment] 2021-07-02 11:55
Duplicate of https://github.com/owncloud/client/issues/8321

**Closed by TheOneRing** 2021-07-02 11:55 UTC
