### ISSUE TITLE
Previews for virtual files in File explorer on Windows 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7401] opened 2019-08-16 12:16 UTC
Make previews for virtual files available in File explorer on Windows 

Steps:
1) Turn on VFS
2) Go to File Explorer
3) View Large icons

<img width="147" alt="Screenshot 2019-08-16 at 14 11 05" src="https://user-images.githubusercontent.com/49001702/63166859-e20cdb00-c02f-11e9-920f-90231c8c3a64.png">

**Comment by michaelstingl** [comment] 2019-08-16 18:05
Related: https://github.com/owncloud/client/issues/7156

**Comment by ogoffart** [comment] 2019-10-14 11:00
Closing as duplicate of the two issues above

**Closed by ogoffart** 2019-10-14 11:00 UTC
Labels: Enhancement, Virtual Files
