### ISSUE TITLE
2.3.0-nightly (6228): Folder in exception list is still synced

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#5039] opened 2016-07-07 13:03 UTC
### Expected behaviour
In one of my ownCloud folders, I have a sub folder called "Festplatten-Images". Since it contains huge files that I do not want to sync, I previously added the exact folder name to the exception list. Until upgrading to 2.3.0-nightly (6228), the folder was never synced, as intended.

### Actual behaviour
With 2.3.0-nightly (6228), the client tried to upload a file from said folder. The folder name is still in my exception list.

### Client configuration
Client version: 2.3.0-nightly (6228)

Operating system: Windows 7

OS language: German

Installation path of client: Default

**Comment by sagamusix** [comment] 2016-07-07 13:14
Update: This revision seems to sync any file on my exception list happily. Exception list seems to be entirely broken.

**Comment by ckamm** [comment] 2016-07-08 05:16
Looking at it now.

**Comment by ckamm** [comment] 2016-07-08 05:21
@sagamusix I can't reproduce it with 2.2 or master. My steps:
* Add a new "myignore" pattern to the exception list in the user interface.
* Add a "/myignore" and "/subfolder/myignore" file to a sync folder
* Verify
  * No sync is triggered when the files are added
  * The files are not uploaded to the server
  * The files appear in the "Not Synced" tab

**Comment by sagamusix** [comment] 2016-07-08 10:10
That's pretty much what I did, just with a different ignore pattern name. Seeing the recent discussions about regex in ignore lists, maybe something in the full list of ignore patterns makes ownCloud break on the entire list? My ignore list has a couple of entries so it could be tripping over that.

**Comment by ckamm** [comment] 2016-07-08 11:20
@sagamusix @guruz patch https://github.com/owncloud/client/pull/4999 hasn't been merged yet, I doubt that's it. Do your patterns contain anything unusual or surprising? Can you check whether the pattern in question appears in the log file?

**Comment by sagamusix** [comment] 2016-07-08 11:26
I've uploaded my personal ignore list for you to check if there's anything unusual in it: http://sagagames.de/stuff/sync-exclude.lst
Apart from this, I have modified ownCloud's own ignore list to remove .htaccess from it as I need these files to be synced, but I doubt that could be the reason.

The log is also not very helpful, apart from seeing that ownCloud even tries to upload its own sync log, which it normally shouldn't:
```
# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=# Syncrun started 2016-07-08T11:25:34
#=#=#=# Syncrun started 2016-07-08T11:33:43
#=#=#=#=# Propagation starts 2016-07-08T12:08:16 (last step: 2072981 msec, total: 2072981 msec)
10:08:18|2267|.owncloudsync.log|INST_SYNC|Up|1467970404||248||4||204|477457|1467849479|94de3ff13dd0d2522fa9abae9648ba3e|01322523oc79c8z0bi2n|INST_NONE|
```
After that, the upload of a (normally ignored) huge disk image started, at which point I closed the client to prevent it from further uploading ignored files.

**Comment by sagamusix** [comment] 2016-07-13 21:29
After further investigating which disallowed sync data has been uploaded to my ownCloud server, it seems like the client even synced Windows' $RECYCLE.BIN, which it would normally never do "because the name contains characters which cannot be displayed on all systems" or something along those lines (and additionally, "just in case", I have this folder name in my personal exclude list). So it seems like the client simply uploaded all files and folders, no matter through which way they would normally be prevented from being updated.

**Comment by guruz** [comment] 2016-07-14 07:03
@sagamusix What does the log say? Can you start with a --logfile (see documentation) and check what is output for the exclude list?

**Comment by guruz** [comment] 2016-07-14 07:04
We can try to run your list http://sagagames.de/stuff/sync-exclude.lst here..

**Comment by sagamusix** [comment] 2016-07-14 11:08
I deleted the old installers and as mentioned in #5053 I'm now back to 2.2.2 to prevent these things from happening. http://download.owncloud.com/desktop/daily/ currently does not contain any 2.3.0 builds, is that intentional? Should I test this with the latest 2.2.3 build?

**Comment by ckamm** [comment] 2016-07-19 10:57
The way in which this breaks is still unclear. Thanks for sharing your exclude list, I'll try using it.

**Comment by ckamm** [comment] 2016-07-19 12:57
@jturcotte Spotted the problem, will be fixed soon.

**Comment by sagamusix** [comment] 2016-07-21 15:12
Using 2.2.3-nightly (6258), the problem seems to be fixed.

**Comment by mcastroSG** [comment] 2016-07-22 07:42
@sagamusix thanks a lot for testing

**Closed by mcastroSG** 2016-07-22 07:42 UTC
Labels: bug
