### ISSUE TITLE
Files containing a slash "/" are failing

### ISSUE THREAD

**Issue by marbetschar** [owncloud/client#3993] opened 2015-10-23 09:06 UTC
### Steps to reproduce
1. On OS X rename a file to "ABC 1/2.pdf" inside a synced folder of the ownCloud directory
2. Wait for the sync to throwing the error "Filename containing invalid characters"

### Expected behavior
Every filename which is allowed on the client's host os should be supported.

### Actual behavior
The sync client throws an error.

### Server configuration
**Operating system**:
OSX El Capitan v10.11

**Web server:**
NGINX

**Database:**
MySQL

**PHP version:**
5.6.14-1

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**

```
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'drive.mandelkind.pizza',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://owncloud.mandelkind.coffee',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => 'mandelkind'
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No - how to enable encryption?

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by dragotin** [comment] 2015-10-23 09:08
duplicate of #3965

**Closed by dragotin** 2015-10-23 09:08 UTC
