### ISSUE TITLE
[Windows] Shell Extensions not enabled if Client installed via Command Line (And possibly updater because that one is using silent install?)

### ISSUE THREAD

**Issue by tomswartz07** [owncloud/client#3285] opened 2015-05-26 19:18 UTC
Hi all,

I'm trying to figure out how to pass in the option to install the File Explorer options via the command line.

The [documentation](https://doc.owncloud.org/desktop/1.8/installing.html#installation) shows that the option is there.

The NSIS installer takes standard options already: if you run `owncloud-1.8.1.5050-setup.exe /S` it will 'silently' install/upgrade the client. However, the default option is to skip the File Explorer extensions.

Is there an option to include during the command line install to enable the File Explorer extensions?

If not, can the File Explorer options be made default-on?

Thanks!

**Comment by tomswartz07** [comment] 2015-05-26 19:33
I have found that there are some other options: `/launch` and `/noautoupdate` that do not appear to be documented, but are existing in the code. See [here](https://github.com/owncloud/client/blob/master/cmake/modules/NSIS.template.in#L721-L734)

Am I not seeing another section that has an option to define `OPTION_SECTION_SC_SHELL_EXT` so that the installer will take it?

**Comment by danimo** [comment] 2015-05-26 20:03
There is no documented way. But installing the new version of the shell extension should be the default. If it doesn't that's a bug.

**Comment by tomswartz07** [comment] 2015-05-26 20:08
@danimo Thanks for the quick reply.

In that case, I believe this is a bug.
Installing an upgrade; for example v1.7 to v1.8.1 via the command line does not enable the shell extensions.

#### Steps to reproduce:
1. install a pre-shell extensions version via the command line: `owncloud-1.7.0-setup.exe /S`
2. Upgrade the client via the same method: <quit the client if running> `start /wait owncloud-1.8.1-setup.exe /S`
3. Note File Explorer is missing the shell extensions.

**Comment by danimo** [comment] 2015-05-26 20:23
@tomswartz07 Did you reboot? Did you check the registry or is this just by observation?

**Comment by danimo** [comment] 2015-05-26 20:38
@tomswartz07 I cannot reproduce this. My test case: silent install 1.8.0, remove `shellext/` manually, silent install 1.8.1, and see `shellext/` return.


However, if files are locked (extensions are usually locked by explorer), they may not get replaced until after the next reboot.

**Comment by f-s** [comment] 2015-06-10 09:51
Same Issue here with 1.8.1 and silent install, we had to manually register the extension after upgrade to 1.8.1, e.g.:

regsvr32.exe /s ownCloud\shellext\OCContextMenu_x86.dll

Sad.

**Comment by danimo** [comment] 2015-06-12 13:34
@f-s Please try with https://download.owncloud.com/desktop/testing/ownCloud-1.8.3.5180rc1-setup.exe.

**Comment by ogoffart** [comment] 2016-01-18 16:59
Closing old issue. Please re-open if this is still hapenning with 2.1

**Comment by tomswartz07** [comment] 2016-02-11 13:23
@ogoffart Sorry: still seeing this issue with the 2.1.1 release.

The manual registration seems to work, however.

**Comment by tomswartz07** [comment] 2016-02-11 16:18
This bug is really bothersome.

Here's my testing method, I've been able to reproduce this with owncloud-2.1.1.5837-setup.exe.
Test unit was Windows 8.1 Pro. 

1. Uninstall any previous version of the client
2. Restart `Explorer.exe` for good measure
3. Run command prompt as admin
4. Run `owncloud-2.1.1.5837-setup.exe /S`, wait for the owncloud icon to appear on the desktop and the Windows installer process to complete.
5. Restart `Explorer.exe` again, assure that `owncloud.exe` is running by observing the icon in the system tray.
6. Inspect user's ownCloud folder and note that the overlays are missing.
7. Run `regsvc32.exe "%PROGRAMFILES(X86)\owncloud\shellext\OCOverlays_x64.dll"`
8. Restart `Explorer.exe`
9. Inspect user's ownCloud folder and note that overlays are now working.

You can repeat the process for the OCContextmenu.dll file as well, and observe the same results.


It seems as if the NSIS installer is not triggering the DLL registration by default, even though that option is selected during the normal GUI sequence. I would guess that, despite being a default option for the GUI installer, the [section here](https://github.com/owncloud/client/blob/639301e9e986aa7d12c178a486773ed9449e1361/cmake/modules/NSIS.template.in#L465-L492) is improperly detecting the `OPTION_SECTION_SC_SHELL_EXT` as undefined during a silent install, thus causing it to skip the registration of the shell extensions.

**Comment by TheOneRing** [comment] 2021-06-21 11:59
Closing this issue, since the issue was opened we switched from nsis installers to msi

**Closed by TheOneRing** 2021-06-21 11:59 UTC
Labels: bug, p3-medium
