### ISSUE TITLE
[OS X] [2.0 final] Mac does not show overlay icons in ~/Library sub-folders

### ISSUE THREAD

**Issue by dirkpape** [owncloud/client#3680] opened 2015-08-25 14:44 UTC
### Expected behaviour
When synching many folders with the owncloud client in MacOS X, for all of them the overlay icons should be shown in Finder.

### Actual behaviour
The finder shows the icons for some of the folder, but for others not (e. g. not for ~/Library/Application Support/iWork).

### Steps to reproduce
1. sync more than one folder on an owncloud server (in my case I have two accounts), but error appears with folders on the same account. E.g. sync ~/owncloud and ~/Library/Application Support/iWork.
2. view the folders in the Finder.
3. recognize difference.

### Server configuration
Operating system:
Ubuntu 12.04.5 LTS

Web server: 
Apache/2.2.22 (Ubuntu)

Database:
mysql  Ver 14.14 Distrib 5.5.44

PHP version:
PHP 5.4.44-1+deb.sury.org~precise+1

ownCloud version:
8.1.1.3

Storage backend:
local

### Client configuration
Client version:
2.0.0.2668 Mac

Operating system:
MacOS X 10.10.5

OS language:
German

Installation path of client:
/Applications

### screen shots

![voila_capture 2015-08-25_04-39-02_nachm](https://cloud.githubusercontent.com/assets/5426508/9469609/56fcece0-4b48-11e5-901a-3fbb4da493b5.png)
![voila_capture 2015-08-25_04-40-05_nachm](https://cloud.githubusercontent.com/assets/5426508/9469622/63cf54c6-4b48-11e5-9ac6-c9cec3a0b4d3.png)
![voila_capture 2015-08-25_04-41-09_nachm](https://cloud.githubusercontent.com/assets/5426508/9469636/6d7f4dd2-4b48-11e5-87ff-d7391776ca54.png)

**Comment by mcnesium** [comment] 2015-08-26 11:40
Confirm. Plus, when choosing the context menu item "share via owncloud" on a file in a directory that does not show the icons, the share window does not appear.

**Comment by stonerl** [comment] 2015-08-26 22:01
Just a wild guess, but you try to sync stuff from the Library Folder, which is a special System folder. Could it be that this is an OSX limitation.

**Comment by mcnesium** [comment] 2015-08-27 07:13
No sorry, I am trying to sync ~/Pictures/Screenshots

**Comment by dirkpape** [comment] 2015-08-27 08:41
Hi, for me - as stated - the sync works fine, only the icons are not shown.

**Comment by stonerl** [comment] 2015-08-27 09:06
@dirkpape You're using the native finder integration. I tried this on my System as well, sync works for all kind of folders (visible and hidden) also the icons appear all the time, but as soon as i try to sync the ~/Library folder or a folder that resides inside ~/Library the files are synced but no icons are shown. That's what I meant with the limitation. I would assume that this very folder is not intended to use in conjunction with the native finder integration, by design.

**Comment by jturcotte** [comment] 2015-08-28 14:17
Yes it doesn't work for me either, I get this message in Console for anything under ~/Library/Application Support:

    28/08/15 16:09:59,845 Finder[486]: Ignoring request from Finder Sync Extension to register for file:///Users/joce/Library/Application%20Support/.../

So sadly I don't think that we can support that scenario. I tried with multiple folders on multiple accounts and that seems to work well though. @mcnesium's problem is probably a different one, the icons are shown properly for me in ~/Pictures.

**Comment by stonerl** [comment] 2015-08-28 14:20
@mcnesium do you run owncloud 2.0.0 on OSX 10.10?

**Comment by mcnesium** [comment] 2015-08-31 09:12
yes, build 2666 on 10.10.5 - I had even more issues with the finder extension though, that I didn't get to report yet, so I just turned that thing off for now.

**Comment by jturcotte** [comment] 2015-09-09 13:53
I'm closing the ~/Library bug as a design choice of Apple, but if you see different issues that you can pin-point please open a new report.

**Closed by jturcotte** 2015-09-09 13:53 UTC
Labels: bug

**Comment by mcnesium** [comment] 2015-09-09 14:41
> a design choice of Apple

What do you mean by that?

**Comment by stonerl** [comment] 2015-09-09 14:43
@mcnesium Apple does not allow the use of overlay icons for the ~/Library folder and it's content.

**Comment by mcnesium** [comment] 2015-09-09 14:47
Ok thx for explaining. One more weird Apple issue *sigh*

I will try to post other issues soon…

**Comment by j2318** [comment] 2015-12-06 20:19
I don't think it is problem with ~/Library folder.  I do have two Macs running **OS X El Capitan 10.11.1** and I installed the client exactly the same way and, on one I can see the icons and on the other one I don't.  My owncloud folder is in ```/User/{user_name}/ownCloud``` not under Library - On the system on which I don't see the icons I removed the owncloud client. I "trashed" the app and ran (as root): ``` find . -name *owncloud*  -exec rm -r {} \; ``` from the Library to remove any traces for the configuration and I reinstalled the client. The same problem; no overlay icons.  
The Mac which has problem it is iMac (Retina 5K, 27-inch, Late 2014) and the mac without problems it is MacBook Air (13-inch, Early 2014) both running **OS X El Capitan 10.11.1**

**Comment by stonerl** [comment] 2015-12-06 20:32
The finder extension is enabled? Maybe disabling and enabling the extension might help.

**Comment by j2318** [comment] 2015-12-06 20:55
On 2015-12-06 12:32 PM, Toni Förster wrote:
>
> The finder extension is enabled? Maybe disabling and enabling the 
> extension might help.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/client/issues/3680#issuecomment-162345344>.
>
Yes, the finder extension is enabled - I disabled the extenstion - then 
I rebooted (just in case) - enabled the extension and nothing has 
changed - still no icons.  Everything else is working fine. As I said 
both Macs are running the same version of El Capitan 10.11.1 - The one 
with problem has much more software installed like Dropbox, Google 
Drive, iCloud Drive and much more - could be a conflict?
-- jacek

**Comment by j2318** [comment] 2015-12-07 16:15
On 2015-12-06 12:32 PM, Toni Förster wrote:
>
> The finder extension is enabled? Maybe disabling and enabling the 
> extension might help.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/client/issues/3680#issuecomment-162345344>.
>
I noticed similar problem with overlay icons in Windows where limit is 
15 slots - is there some limit of overlay icons slots on Mac?
-- jacek

**Comment by stonerl** [comment] 2015-12-07 17:47
No, on OSX ≥10.10 owncloud uses Finders native overlay icons.

But this issue here was about ~/Library/ I think you should open a new one.

**Comment by stonerl** [comment] 2015-12-07 18:48
@j2318 #3819
