### ISSUE TITLE
After multiple connection timeout, Uploaded is not reported in Activity log

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3416] opened 2015-07-07 12:11 UTC
### Expected behaviour
The activity log should have an entry showing when the file was successfully Uploaded.

### Actual behaviour
This morning there were authentication issues on the ownCloud server, so it was not responding for some time (an hour or so). I put a copy of an existing file into the Documents folder - "PhilDavisKeePass - Copy.kdbx". I got 2 activity log entries 6 minutes apart saying Connection Timeout - good and true.

Later when the server was working well again, I checked from the web interface and the file is on the server - good. Also the document shows with a "green tick" in the folder in Windows - good.

In the activity log there is no entry saying the file was Uploaded.
Somehow successful Uploaded activity logs can be missed.
Note that there was another file in the screenshot that shows a single Connection Timeout and then a successful Uploaded. So a successful upload can sometimes appear in the activity log after a previous Connection Timeout.

### Steps to reproduce
I have not reproduced it yet - need to induce Connection Timeout a few times and see if I can make it happen again :)

### Server configuration
ownCloud version: 8
### Client configuration
Client version: 1.8.3 (build 5213)

Operating system: Windows7

### Logs

![owncloudactivity-connectiontimeout](https://cloud.githubusercontent.com/assets/1535615/8545441/6bfb8da4-24ce-11e5-96ec-89742c39ed94.png)

**Comment by guruz** [comment] 2015-07-07 13:38
Hey, Could you update to a newer build?
https://download.owncloud.com/desktop/stable/ownCloud-1.8.3.5250-setup.exe

There were changes regarding network handling that could help here..
Thank you.

**Comment by phil-davis** [comment] 2015-07-07 14:50
Just an unrelated comment about versions. I got 1.8.3 (build 5213) on 1 July 2015 from https://owncloud.org/install/#install-clients which says 1.8.3 is the latest stable version. The change log https://owncloud.org/changelog/desktop/ says 23 June 2015.
It seems an odd definition of "stable" that now when I go to the same place to get the latest stable version, it is still called 1.8.3 but now gives build 5250. The change log is unchanged - or appears so. Thus it is rather difficult (without users looking in GitHub...) to see how these 2 (or more?) "stable releases" of 1.8.3 are different.
Personally I am happy to live on the edge - there seem to be bugs fixed every day, and it is nice to have those, assuming not too many regressions :) But other "business" users might not be so comfortable with "stable release 1.8.3" being a somewhat moveable feast.

**Comment by dragotin** [comment] 2015-07-07 15:17
@phil-davis yes, we replaced the build. But it does not contain any changes in the ownCloud code, so it is still 1.8.3. The patch to fix the network problems in Qt changed slightly, so we decided to recreate the build with *that* patch and still call it 1.8.3. But you're right, that is not the best practise, but in this case, we thought it's fine, because ownCloud was completely unchanged and new version numbers also confuse people.

**Comment by phil-davis** [comment] 2015-07-07 17:31
It is a bit tricky to reproduce. Take my own internet away completely and of course the ownCloud client knows and gives a different message straight away. I redirected the DNS for our ownCloud server name to a dud IP address - but that causes a timeout on getting any initial response from the server at all, a different error condition.
The root cause of our problem this morning was that the IMAP mail server that does authentication for our ownCloud was not responding (it had black-listed the ownCloud IP address for whatever reason), so the ownCloud server was waiting-waiting... for the mail server authentication response. And eventually there is a timeout.
I think on the mail server I can blacklist the ownCloud server IP again - that should reproduce the client-to-server timeout. Just need to do it at a controlled time :)

**Comment by ogoffart** [comment] 2015-08-31 16:04
maybe this has something to do with the error blacklist?
I mean, once something is in the blacklist, it is not retried, so it will not appear in the activity list  (or rather it will appear as being ignored because it is in the blacklist).  Could that be related?

**Comment by phil-davis** [comment] 2015-08-31 16:51
I had forgotten about this. I will play at work in the morning - now we have an in-house ownCloud server in testing that is using LDAP authentication. I am guessing that I can get similar effects by making the LDAP server not be responsive to the ownCloud server for a while...

**Comment by ckamm** [comment] 2016-01-19 13:15
Another guess: Maybe the server reported an error, or there was a timeout but the file actually uploaded correctly. I think the client would notice during the next discovery and not re-upload. This way you could get a synchronized file without an activity log entry saying "Uploaded".

**Comment by ckamm** [comment] 2016-01-20 08:52
@phil-davis I'm closing this for now. Feel free to reopen if you see the problem again or find a way to reproduce it.

**Closed by ckamm** 2016-01-20 08:52 UTC
Labels: bug
