### ISSUE TITLE
Client sometimes fails to open settings window, when doubleclicking the desktop icon

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7775] opened 2020-02-26 15:01 UTC
Seen on Windows10 with ownCloud 2.6.1 and damkencloud client 2.6.2

Have the ownCloud client stopped.
Double click on the desktop icon starts the client. No visible user feedback. That is okay, as it is a background process.
Double click the desktop icon while the client is (now) running. Nothing happens.
Wait 10 seconds. Then try double click. Now the settings dialog opens.

The second double click only works, if the user is patient for 10 seconds. This is unlikely, as there is no visible feedback, when the user clicks earlier.

Workaround: double click ca. 20 times slowly.

**Comment by TheOneRing** [comment] 2020-02-27 13:42
Duplicate of https://github.com/owncloud/client/issues/7018

**Closed by TheOneRing** 2020-02-27 13:42 UTC
Labels: Design & UX
