### ISSUE TITLE
v2.5.0 broke compatibility with Sandstorm Davros

### ISSUE THREAD

**Issue by xet7** [owncloud/client#6775] opened 2018-09-18 08:22 UTC
### Expected behaviour
Tell us what should happen

OwnCloud client works with Davros, as it did yesterday.

https://sandstorm.io is Open Source web app platform.

Davros is Sandstorm app that has been made compatible with OwnCloud client.

I also added this issue to Davros GitHub: https://github.com/mnutt/davros/issues/93

### Actual behaviour
OwnCloud client shows this error on Xubuntu 16.04:
![owncloud](https://user-images.githubusercontent.com/15545/45672676-75444480-bb31-11e8-95ce-bad7d03ef9c2.png)

![owncloud-error](https://user-images.githubusercontent.com/15545/45674127-154f9d00-bb35-11e8-9193-fbaebc89a7e8.png)

Files do still download to desktop, but uploading back to Davros does not work anymore. Yesterday uploading did work, and there were no errors.

### Steps to reproduce
1. At https://sandstorm.io create account, or use demo
2. Install Davros to from [Sandstorm App Market](https://apps.sandstorm.io/app/8aspz4sfjnp8u89000mh2v1xrdyx97ytn8hq71mdzv4p4d8n0n3h), if it's not already installed, as it usually is.
3. Create new Davros directory on Sandstorm web UI.
4. Install OwnCloud client to Xubuntu 16.04
5. Copy https address, username and password to OwnCloud.
6. OwnCloud client shows error above.

### Server configuration
Operating system:
Debian

Web server: 
Sandstorm SaaS https://sandstorm.io

Database:
Using 3rd party OwnCloud server implementation called Davros
https://github.com/mnutt/davros/

PHP version:
Unknown

ownCloud version:
Using 3rd party OwnCloud server implementation called Davros
https://github.com/mnutt/davros/

Storage backend (external storage):
Filesystem on Google Cloud

### Client configuration
Client version:
v2.5.0

Operating system:
Xubuntu 16.04 64bit

OS language:
Finnish

Qt version used by client package (Linux only, see also Settings dialog):

![owncloud-version](https://user-images.githubusercontent.com/15545/45672693-7ffed980-bb31-11e8-90ca-5c5cda58cbc0.png)

Client package (From ownCloud or distro) (Linux only):
Instructions at
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

Installation path of client:
Owncloud user files at /home/user/ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

[owncloud-client-log.txt](https://github.com/owncloud/client/files/2391769/owncloud-client-log.txt)

2. Web server error log:

[davros-server-log.txt](https://github.com/owncloud/client/files/2391772/davros-server-log.txt)

3. Server logfile: ownCloud log (data/owncloud.log):

[log.txt](https://github.com/owncloud/client/files/2391785/log.txt)

**Comment by ogoffart** [comment] 2018-09-18 14:45
Caused by 13eb64584f5f96647ced39dcd3252860ebec5a37.

The log shows

```
09-18 11:14:51:860 [ warning sync.discovery ]:	Missing properties: "Welcome to Davros.md" 0 1927 1537185404 "" "703fd00093167d52e9df9be48be51f5c" ""
```

The File ID and the permissions are empty.
These fields have been set for a long time in the owncloud server. And we now rely on them on the client.

**Comment by ogoffart** [comment] 2018-09-18 14:47
Note: as the warning say, Davros is not officially supported, we do not do any QA with this server and have no idea if an update will work or not.
Maybe there are more issues.

**Comment by xet7** [comment] 2018-09-18 16:05
@ogoffart 

Thanks! It helps a lot to know what change has caused it, so I can try to fix Davros by adding File ID and permissions.

**Comment by ogoffart** [comment] 2018-09-19 07:43
I'm closing this bug for now as we do not support this directly.

**Closed by ogoffart** 2018-09-19 07:43 UTC
