### ISSUE TITLE
Crash when moving file within shared folder

### ISSUE THREAD

**Issue by m0ritz3** [owncloud/client#7967] opened 2020-07-16 14:40 UTC
### Expected behaviour
I move a file with a shared folder and the shared folder is updated.

### Actual behaviour
The file is moved. Owncloud shows the error symbol with a message "MOVE: file move_location/file

### Steps to reproduce
1. Move file within shared folder.

ownCloud version 2.6.3 (build 2668)
Git revision f28dd972e941986edc3e1803a25cf067f520b7e3
Using Qt 5.12.7, built against Qt 5.12.7
Using 'OpenSSL 1.1.1  11 Sep 2018'

Operating system: Ubuntu 18.04.0 LTS

OS language: English

Terminal output on crash:

07-16 16:35:31:557 [ fatal default ]:	ENFORCE: "instruction == CSYNC_INSTRUCTION_REMOVE || ((*it)->_type == ItemTypeVirtualFile && instruction == CSYNC_INSTRUCTION_NEW) || ((*it)->_isRestoration && instruction == CSYNC_INSTRUCTION_NEW)" in file /usr/src/packages/BUILD/src/libsync/discoveryphase.cpp, line 175

For additional information please tell me how I can provide them.

**Comment by michaelstingl** [comment] 2020-07-17 11:15
@m0ritz3 could you post the ID from the crash report window?

**Comment by m0ritz3** [comment] 2020-07-17 11:35
@michaelstingl There was no crash report window after restarting owncloud. Or do I have to eplicitly report the crash? If yes, how can I do that?

I would like to share the log file, but there is a lot of sensitive information. Is there a way to easily anonymize the log file?

**Comment by TheOneRing** [comment] 2020-07-20 08:51
`
07-17 13:27:34:051 [ fatal default ]:	ENFORCE: "instruction == CSYNC_INSTRUCTION_REMOVE || ((*it)->_type == ItemTypeVirtualFile && instruction == CSYNC_INSTRUCTION_NEW) || ((*it)->_isRestoration && instruction == CSYNC_INSTRUCTION_NEW)" in file /usr/src/packages/BUILD/src/libsync/discoveryphase.cpp, line 175
`
I hate that crash

**Comment by TheOneRing** [comment] 2020-07-21 09:14
Hi are you able to reproduce the bug?
As the crash is bugging me, and the enforce is quite complex I added an extra level of verbosity. https://github.com/owncloud/client/commit/b8a4d0c3ff72b075609fe9fe20d1fe19d9c01535
So from tomorrow on the client should tell me more on what is happening here.
If you are not able to reproduce that one, I wish you the best of luck that it won't happen again to you 🙈

**Comment by TheOneRing** [comment] 2020-09-10 12:15
Please test:
https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.2072-v270beta4/
https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.0.2074-v270beta4/

**Comment by TheOneRing** [comment] 2020-09-16 12:16
Should be fixed

**Closed by TheOneRing** 2020-09-16 12:16 UTC

**Comment by m0ritz3** [comment] 2020-09-17 07:51
Sorry, for my late answer. 

I could not reproduce that bug anymore, but the permissions in the shared folder have changed in the mean time. When the bug occured, I was not allowed to delete files in the folder. Now I am allowed to do that. This could also be the reason, that the bug did not occur anymore. Thanks for your commitment @TheOneRing .

**Comment by TheOneRing** [comment] 2020-09-17 07:59
Yes the issue occurred in that scenario, to my knowledge only with newly added files or files that where moved multiple times.
That issue should be fixed now.

**Comment by jnweiger** [comment] 2020-10-19 22:59
## retested with testpilotcloud 2.7.0daily20201019 (build 2311)

Client downloads files from a folder Photos which was shared readonly with the user.
User renames a file locally using e.g. `mv Lake-Constance.jpg xxx.jpg`

The sync client recreates the original file Lake-Constance.jpg and complains 
   Photos/xxx.jpg,               testpilotcloud4,Not allowed because you don't have permission to add files in that folder

reanonable behaviour, no crashes. OK
