### ISSUE TITLE
Excludes: Further optimize also patterns with slash and add trailing slash to some of the items in existing sync-exclude.lst

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#5017] opened 2016-06-28 14:34 UTC
### Actual behaviour

Even after fixing #4967, ownCloud keeps eating an entire CPU core for me at times, which I think it already did in 2.1.1 from time to time, so it might be a problem not caught by the fix for #4967.
I'm running ownCloud on a dual-core CPU, so it becomes obvious that something is wrong as soon as another application maxes out the other core. ownCloud's scan thread (which I assume is responsible for this high CPU usage) should run with a rather low priority as it is essentially a background service. This way, "normal" threads should be able to take over the CPU when they need it, meaning that the applications that I actually intend to use would be more responsive.

As the question already came up in #4967, Explorer overlays are disabled.
### Client configuration

Client version: 2.2.2-6192

Operating system: Windows 7 x64

OS language: German

Installation path of client: Default

**Comment by guruz** [comment] 2016-06-28 16:56
The solutions are https://github.com/owncloud/client/issues/2297 and https://github.com/owncloud/client/pull/4999

Although I'm wondering if you're right about that we shut throttle the discovery a bit to not make the CPU go up so much and the CPU fan spin. Opinions @owncloud/desktop-developers ?

**Comment by sagamusix** [comment] 2016-06-28 18:58
I do think it would be a sensible modification. Naturally optimizing the code itself should be one important part of fixing performance-related problems. But on the other hand (unless there is any artificial throttling) it is just natural that ownCloud will consume an entire CPU core when scanning folders. This is exactly what you want (it is generally known that "race to idle" is a good power-saving strategy) when you are alone on the system, but when there are other threads, you are competing for resources.
Other threads will most likely include other end-user software that the user actually intends to interact with, while ownCloud is just a background thread. Hence, if a lower priority is assigned to this thread, it will run at full performance when there is nothing to do (and race to idle), but if the user actually works with their system, the ownCloud thread will get fewer time slices and the remaining software will work more smoothly.
I have verified this to work as intended by setting the entire ownCloud process' priority to "lower" in the Windows task manager - when doing so, my desktop becomes more usable again.

**Comment by ckamm** [comment] 2016-07-05 11:54
@sagamusix I've changed the discovery thread's priority to 'low' for 2.3.0.

**Comment by sagamusix** [comment] 2016-07-05 12:01
Thanks, looking forward to test it. :)

**Comment by guruz** [comment] 2016-07-06 07:01
@sagamusix http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.6228-nightly20160705-setup.exe :)

**Comment by guruz** [comment] 2016-07-12 14:00
@sagamusix Hey! How did it go?

**Comment by guruz** [comment] 2016-07-12 14:02
Woops, Just saw https://github.com/owncloud/client/issues/5053 .. heh

**Comment by sagamusix** [comment] 2016-07-12 14:18
Due to #5039 I sadly was not able to really test new the version yet, sorry!

**Comment by sagamusix** [comment] 2016-07-21 23:22
After using 2.2.3-nightly (6258) for a day, ownCloud CPU consumption generally seems to have gone down during rescans. So far the issue seems to be fixed.

**Comment by sagamusix** [comment] 2016-10-21 00:00
Using 2.3-nightly, I am afraid the problem may still persist. During the first scan after launch, the client generally only seems to consume a few percent of CPU, but a few hours in, it is back to consuming an entire CPU core.

**Comment by guruz** [comment] 2016-10-31 13:36
We need more data, profiling, measurements, log etc. :/

**Comment by sagamusix** [comment] 2016-10-31 13:42
Let me know how I can help. :)

**Comment by guruz** [comment] 2016-11-08 13:31
Are you using selective sync? Do you have many folders there unchecked?

**Comment by sagamusix** [comment] 2016-11-08 13:36
No, all folders are selected. I have several sync folders and a bunch of ignored file rules, though.
If there are PDB files available for nightly builds, I could throw Very Sleepy at the ownCloud process and check where all the CPU time is wasted.

**Comment by guruz** [comment] 2016-11-15 17:27
Summoning @ogoffart @jturcotte @ckamm if they have ideas..

**Comment by ckamm** [comment] 2017-01-10 12:49
No ideas unfortunately. Profiling data would be extremely useful.

@sagamusix If you can find out where CPU time is wasted, that'd be great! You said "it's back to consuming one full CPU after an hour" - is it consuming the CPU when idle or only when syncing? If it's only during sync: during which phase of the sync?

**Comment by sagamusix** [comment] 2017-01-10 13:01
According to my observations, it consumes CPU during syncing, but not during all sync runs. I think it always happens when looking for changes.

**Comment by ogoffart** [comment] 2017-04-28 09:36
Is there any news on this? We can't really do anything without more information. What is the client doing when using all this CPU? Does the log say anything?
It would be nice if we would have a way to reproduce the problem.

**Comment by guruz** [comment] 2017-09-25 14:20
@sagamusix We have some nice changes coming up for 2.4.0 alpha.
Are you interested in testing a nightly build in some days?

**Comment by sagamusix** [comment] 2017-09-25 18:44
@guruz that would be appreciated.

**Comment by guruz** [comment] 2017-10-06 16:56
@sagamusix https://central.owncloud.org/t/desktop-client-2-4-0-alpha1-released/9837

**Comment by sagamusix** [comment] 2017-10-11 18:25
Sadly it doesn't help, I'm still catching ownCloud consuming an entire CPU core for synchronizing a folder in which nothing has changed (the last change was already uploaded half an hour ago and nothing was changed on the server side either).

**Comment by ckamm** [comment] 2017-10-12 10:44
@sagamusix We really need profiling data to figure out what's going on. Could you get a profiler like http://www.codersnotes.com/sleepy/ and attach it to the ownCloud client while it's showing this behavior? I've just checked with the alpha, and I see symbol names for libowncloudsync and libocsync but unfortunately not for the owncloud binary itself. It's likely still useful!

**Comment by sagamusix** [comment] 2017-10-12 19:51
https://sagagames.de/stuff/oc.sleepy

**Comment by ckamm** [comment] 2017-10-13 10:15
@sagamusix Thank you; was the sync thread shown as high-cpu?

**Comment by sagamusix** [comment] 2017-10-13 11:10
Yes, I have quite a few custom excludes. All other threads consume virtually no CPU time.

Looking at the stack trace including PathFileExistsA, it seems like that function spends a lot of its time in an internal helper function, `CharUpperA`, probably to canonicalize the paths for internal usage. From what I understand, PathFileExistsA might be doing a lot of stuff that is not actually necessary and could possibly be replaced with a custom implementation? If this is a critical path that is hit often, it would make sense.

**Comment by ckamm** [comment] 2017-10-13 11:10
Since another person on mac had reported surprising cpu usage by checksum-computation threads, I've added better logging and a global environment variable to disable them to 2.4 for testing purposes.

Once a new 2.4 build is up, could you try with `OWNCLOUD_DISABLE_CHECKSUM_COMPUTATIONS=1` and see if that does anything? (if the traces above about fnmatch are correct, this shouldn't be the problem)

**Comment by sagamusix** [comment] 2017-10-13 11:11
Yeah I can do that. Let me know when the build is up.

**Comment by ckamm** [comment] 2017-10-13 11:12
@sagamusix Can you show us your excludes? (by email, if private) We only optimize a particular "simple" class of them to avoid going through PathFileExistsA for them.

**Comment by sagamusix** [comment] 2017-10-13 11:14
Sync excludes are here: https://sagagames.de/stuff/sync-exclude.lst
It's quite a long list, I know. :)

**Comment by ckamm** [comment] 2017-10-13 11:17
@sagamusix ^ That's the reason it is slow. We can't yet match excludes that contain a '/' with our custom regex-based logic.

**Comment by sagamusix** [comment] 2017-10-13 11:20
Most of these excludes could be removed if there was an option to never sync specific local sub folders of a synced folder. As far as I can see, this is currently only possible through exclude lists. If this was considered to be added as a new feature at some point, it would probably help me a lot.

**Comment by ckamm** [comment] 2017-10-13 11:33
(Looking at this, I think there's a win/posix inconsistency: the pattern "*/foo" would match "a/foo" and not match "a/b/foo" on posix (we use FNM_PATHNAME) - but your use of patterns suggests it matches both on windows)

**Comment by ckamm** [comment] 2017-10-13 11:35
@guruz how about we introduce a new prefix for full-regex matches? Then @sagamusix could use these for his custom patterns, probably speeding up the thing a lot while making it more flexible at the same time.

**Comment by ckamm** [comment] 2017-10-13 11:36
@sagamusix It sounds like the "selective sync, but keep the files!" issue would be something you want that could replace some of these excludes for you?

**Comment by sagamusix** [comment] 2017-10-13 11:39
Kind of, except that selective sync currently only shows folders which exist on the server. I have many folders in my sync folder that I would not like to upload (e.g. because they contain temporary or big data that does not need to be uploaded), but they do not (or at least really should not) exist on the server.

**Comment by sagamusix** [comment] 2017-10-13 11:49
I  think another question here is why ownCloud appears to do full re-scans of the local folder even if there have been no modifications. Doesn't it use directory change notifications for monitoring file system changes?

**Comment by ckamm** [comment] 2017-10-13 11:53
@sagamusix #6087 -> probably 2.5

**Comment by sagamusix** [comment] 2017-10-13 11:54
Ah, great to hear. :)

**Comment by ogoffart** [comment] 2017-10-13 12:05
We could optimize the patterns that starts with a slash and does not contain a star or other willcards. Theses could be just be put in a hash table.

This ignore list currently **is** the feature you want. The fact that it is slow can totally be optimized. Maybe we could even add a better UI to add easily a file or directory to this list.

**Comment by guruz** [comment] 2017-10-16 15:55
(Might not be so important if https://github.com/owncloud/client/issues/5017#issuecomment-336430884 is done and makes it "good enough"..)

**Comment by guruz** [comment] 2017-10-16 15:56
Can you keep https://sagagames.de/stuff/sync-exclude.lst alive (or paste it here) so we can use it for benchmarking?

**Comment by sagamusix** [comment] 2017-10-16 22:14
Yes, I'll keep the file up for now.

**Comment by ckamm** [comment] 2017-10-17 08:18
@sagamusix As a stopgap, you could try to convert as many of your patterns as possible to match directories only, i.e. end with a trailing /. Those patterns will only be matched against directories, not files, and that might speed up things significantly for you. It looks like most of your patterns could have a trailing /.

**Comment by sagamusix** [comment] 2017-10-17 09:58
Thanks, I will try that.

**Comment by ckamm** [comment] 2017-11-22 10:31
I've started work on further exclude simplification and improvement.

**Comment by ckamm** [comment] 2017-12-13 10:58
@sagamusix It'd be great if you could test a current master build again. Significant improvements to exclude path matching have been merged.

**Comment by sagamusix** [comment] 2017-12-13 12:08
Sure, let me know which version I should be testing.

**Comment by ckamm** [comment] 2017-12-13 16:13
@sagamusix The patch was merged 6d ago, so the 2.5.0 nightlies from http://download.owncloud.com/desktop/daily/ should have it.

**Comment by sagamusix** [comment] 2017-12-14 19:33
There appear to be some changes in the interpretation of certain patterns; for example my pattern `*/.svn/pristine/` no longer seems to work and ownCloud synchronizes these files now, while it shouldn't.

**Comment by ckamm** [comment] 2017-12-14 20:35
@sagamusix I hope that's not caused trouble - it's excellent feedback because that's not supposed to happen, I'll check it out.

**Comment by sagamusix** [comment] 2017-12-14 20:36
Luckily I noticed early enough that something was going wrong. ;)

**Comment by ckamm** [comment] 2017-12-14 20:38
@sagamusix So it's now syncing some folder `foo/.svn/pristine` and its contents?

**Comment by ckamm** [comment] 2018-01-11 08:26
@sagamusix said in https://github.com/owncloud/client/issues/6245#issuecomment-356652544:

> initial discovery still seems to have slowed down considerably. The discovery took almost exactly 5 hours, which used to be a matter of minutes. To make things worse, it ended with an "operation cancelled" error from the server. :)

**Comment by ckamm** [comment] 2018-01-11 08:29
@sagamusix Is https://sagagames.de/stuff/sync-exclude.lst the exclude list you're working with? I'll try profiling with exactly that.

**Comment by ckamm** [comment] 2018-01-11 08:34
Actually, I might know the issue:

```
AppData/Roaming/Mozilla/Firefox/Profiles/uckdykz5.default/extensions/https-everywhere-eff@eff.org/*
AppData/Roaming/Mozilla/Firefox/Profiles/uckdykz5.default/sessionstore-backups/*
```

These patterns use '*' for the bname matching. Thereby they break the optimization and make the 2.5 client always apply the full-path regex. I didn't think about this case :(

Could you verify by switching these two lines to:
```
AppData/Roaming/Mozilla/Firefox/Profiles/uckdykz5.default/extensions/https-everywhere-eff@eff.org
AppData/Roaming/Mozilla/Firefox/Profiles/uckdykz5.default/sessionstore-backups
```

**Comment by ckamm** [comment] 2018-01-11 09:10
@sagamusix In my profiles the version without these two lines is approximately 6x faster than the one that has them. However, 5 hours / 6 = 50 minutes - so that probably would still be slower than previously!

**Comment by sagamusix** [comment] 2018-01-11 12:10
I updated my exclusion list a while ago as per your recommendation to omit the star patterns.
In particular, the two patterns mentioned above were corrected to
```
AppData/Roaming/Mozilla/Firefox/Profiles/uckdykz5.default/extensions/https-everywhere-eff@eff.org/
AppData/Roaming/Mozilla/Firefox/Profiles/uckdykz5.default/sessionstore-backups/
```
I have re-uploaded my exclusion list at the same location as the old one, and it contains as little star patterns as possible. It now reflects the list that I used yesterday, when the scan took more than five hours to complete.

According to Explorer there are roughly 250.000 files in the sync folder, although a large part of them are ignored due to the .svn patterns, so 100.000 sounds like a realistic amount of actually synced files. Of the 30GB in the folder, only 13GB are actually synced.

Just in case it's useful, I also uploaded a new Very Sleepy trace while running this nightly version at https://sagagames.de/stuff/oc.sleepy

**Comment by ckamm** [comment] 2018-01-11 12:48
@sagamusix Thanks for the updates and the data!

**Comment by sagamusix** [comment] 2018-01-11 13:23
The trace is actually just about 2-3 minutes, not 30 minutes. I will look into recording a log later.

**Comment by ckamm** [comment] 2018-01-11 13:50
Thanks. It likely sums up the times between threads then.

**Comment by sagamusix** [comment] 2018-01-12 18:45
I have sent the log. I have observed that the log grew considerably faster in the first minute than it did in the second, so a potential issue here might be that the sync gets slower and slower over time for some reason.

**Comment by ckamm** [comment] 2018-01-13 11:58
@sagamusix I got it and will check it out!

**Comment by ckamm** [comment] 2018-01-13 13:02
@sagamusix Is the discovery fast on 2.4.0?

**Comment by sagamusix** [comment] 2018-01-13 13:14
Yes, these hour-long discovery runs are definitel a new issue in the current nightlies.
However, I just noticed something really strange that might be the key to the problem.
I closely watched the ownCloud window and your calculation of discovering all the files in about one minute is accurate: After one minute, ownCloud seems to start the discovery **start all over again**, just much more slowly (that slowdown can be noticed even in the UI).

Example from the new log obtained from this observation:
During the first minute:
```
01-13 14:07:27:806 [ debug sync.csync.updater ]	[ csync_walker ]:	file: C#/MD5-SHA1/MD5-SHA1/Form1.Designer.cs [inode=140 size=5297]
01-13 14:07:27:807 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 QVariant(qlonglong, -2905695774482572221)
01-13 14:07:27:807 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
01-13 14:07:27:807 [ info sync.csync.updater ]:	Database entry found, compare: 1279370295 <-> 1279370295, etag:  <-> 9ddb26eaeca31a2f31577640d4d7d065, inode: 140 <-> 140, size: 5297 <-> 5297, perms: 0 <-> 9f, ignore: 0
```
And then a minute later:
```
01-13 14:08:46:231 [ debug sync.csync.updater ]	[ csync_walker ]:	file: C#/MD5-SHA1/MD5-SHA1/Form1.Designer.cs [file_id=00118633oc79c8z0bi2n size=5297]
01-13 14:08:46:231 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 QVariant(qlonglong, -2905695774482572221)
01-13 14:08:46:231 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
01-13 14:08:46:231 [ info sync.csync.updater ]:	Database entry found, compare: 1279370295 <-> 1279370295, etag: 9ddb26eaeca31a2f31577640d4d7d065 <-> 9ddb26eaeca31a2f31577640d4d7d065, inode: 0 <-> 140, size: 5297 <-> 5297, perms: 9f <-> 9f, ignore: 0
01-13 14:08:46:231 [ info sync.csync.updater ]:	file: C#/MD5-SHA1/MD5-SHA1/Form1.Designer.cs, instruction: INSTRUCTION_NONE <<=
```

**Comment by ckamm** [comment] 2018-01-13 14:21
@sagamusix I assume the second discovery has a "Allowing local discovery to read from the database" line. How many entries are in the "local discovery paths:" line that follows that?

**Comment by sagamusix** [comment] 2018-01-13 14:29
I couldn't find such a line in the log. This is how the first discovery ends and the second starts:
```
01-13 15:23:26:608 [ debug sync.csync ]	[ csync_update ]:	Update detection for local replica took 77.21 seconds walking 200395 files.
01-13 15:23:26:608 [ debug sync.discovery ]	[ OCC::DiscoveryJob::remote_vio_opendir_hook ]:	OCC::DiscoveryJob(0x77f4f98)  Calling into main thread...
01-13 15:23:26:608 [ info sync.accessmanager ]:	6 "PROPFIND" "https://*******/remote.php/dav/files/johannes/Sources" has X-Request-ID "921fdbb0-ca3b-41c5-b7af-bf1fe05cc742"
01-13 15:23:26:608 [ debug sync.cookiejar ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://*******/remote.php/dav/files/johannes/Sources") requests: (QNetworkCookie("oc_sessionPassphrase=UhSJsMtkzk0%2BOgkmy4bWijQPF78%2FcfPH6e4a7hOvu6XWCEUJtA%2Fd9fnh0E84EK5sUXpncgeWdoNAOaAjUIBVkFi5z9ixiVSUy7kCqTEHkohQ07cMW%2FgSOP%2BLS%2BQm9ES6; secure; HttpOnly; domain=home.schultz.re; path=/wolke"), QNetworkCookie("oc79c8z0bi2n=qs3r32lr9d15k1l123n2u7mrb6; secure; HttpOnly; domain=home.schultz.re; path=/wolke"))
01-13 15:23:26:608 [ info sync.networkjob ]:	OCC::LsColJob created for "https://*******" + "/Sources" "OCC::DiscoverySingleDirectoryJob"
01-13 15:23:27:475 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://*******/remote.php/dav/files/johannes/Sources") FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) ""
01-13 15:23:27:476 [ debug sync.discovery ]	[ OCC::DiscoveryMainThread::singleDirectoryJobFirstDirectoryPermissionsSlot ]:	Permissions for root dir: "DNVCKR"
01-13 15:23:27:481 [ debug sync.engine ]	[ OCC::SyncEngine::slotRootEtagReceived ]:	Root etag: "\"5a33bb48440d2\""
01-13 15:23:27:481 [ info gui.folder ]:	Root etag from during sync: "\"5a33bb48440d2\""
01-13 15:23:27:481 [ debug sync.discovery ]	[ OCC::DiscoveryMainThread::singleDirectoryJobResultSlot ]:	Have 14 results for  "/Sources"
01-13 15:23:27:482 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::LsColJob finished for "/Sources"
01-13 15:23:27:482 [ debug sync.discovery ]	[ OCC::DiscoveryJob::remote_vio_opendir_hook ]:	OCC::DiscoveryJob(0x77f4f98)  ...Returned from main thread
01-13 15:23:27:482 [ debug sync.csync.updater ]	[ csync_walker ]:	directory: C# [file_id=00118624oc79c8z0bi2n]
01-13 15:23:27:483 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 QVariant(qlonglong, -6906474125601790833)
01-13 15:23:27:483 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
01-13 15:23:27:483 [ info sync.csync.updater ]:	Database entry found, compare: 1458847545 <-> 1458847545, etag: 56f43f3a90e07 <-> _invalid_, inode: 0 <-> 99, size: 0 <-> 0, perms: fd <-> fd, ignore: 0
01-13 15:23:27:483 [ info sync.csync.updater ]:	file: C#, instruction: INSTRUCTION_EVAL <<=
01-13 15:23:27:483 [ debug sync.discovery ]	[ OCC::DiscoveryJob::remote_vio_opendir_hook ]:	OCC::DiscoveryJob(0x77f4f98) C# Calling into main thread...
01-13 15:23:27:484 [ info sync.accessmanager ]:	6 "PROPFIND" "https://*******/remote.php/dav/files/johannes/Sources/C%23" has X-Request-ID "5f43b27f-ec2b-4231-b5fb-1d512acbb108"
01-13 15:23:27:484 [ debug sync.cookiejar ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://*******/remote.php/dav/files/johannes/Sources/C%23") requests: (QNetworkCookie("oc_sessionPassphrase=UhSJsMtkzk0%2BOgkmy4bWijQPF78%2FcfPH6e4a7hOvu6XWCEUJtA%2Fd9fnh0E84EK5sUXpncgeWdoNAOaAjUIBVkFi5z9ixiVSUy7kCqTEHkohQ07cMW%2FgSOP%2BLS%2BQm9ES6; secure; HttpOnly; domain=home.schultz.re; path=/wolke"), QNetworkCookie("oc79c8z0bi2n=qs3r32lr9d15k1l123n2u7mrb6; secure; HttpOnly; domain=home.schultz.re; path=/wolke"))
01-13 15:23:27:485 [ info sync.networkjob ]:	OCC::LsColJob created for "https://*******" + "/Sources/C#" "OCC::DiscoverySingleDirectoryJob"
01-13 15:23:28:136 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://*******/remote.php/dav/files/johannes/Sources/C%23") FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) ""
01-13 15:23:28:137 [ debug sync.discovery ]	[ OCC::DiscoveryMainThread::singleDirectoryJobResultSlot ]:	Have 2 results for  "/Sources/C#"
01-13 15:23:28:137 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::LsColJob finished for "/Sources/C#"
```

**Comment by ckamm** [comment] 2018-01-13 15:31
Oh, the second discovery is just the remote discovery. I thought a second sync was starting and that that was slow. The remote discovery is much slower than the local one since it has to request data from the server. It should however be done once and then only update directories that actually change on the server.

**Comment by sagamusix** [comment] 2018-01-13 15:35
Hmm... So it might be that something on the server side slowed down instead? I'm not sure if there were any ownCloud server updates at the time I noticed the slowdowns, and there were also no other changes to the server itself, as far as I can remember.

**Comment by ckamm** [comment] 2018-01-13 16:23
It's probably not a slowdown, I'd just expect that you typically don't see your clients doing full remote discoveries. It's not done at all unless absolutely necessary. If you set up a new 2.3.3 or 2.4.0 client with a new database it should take just as long. Maybe you could verify that this is correct by syncing a subset of your data (just a folder or so)?

**Comment by sagamusix** [comment] 2018-01-13 18:04
Alright, I'll see how it behaves with a smaller sync folder.

**Comment by sagamusix** [comment] 2018-01-13 20:25
With a smaller folder I could indeed observe that the full remote discovery only happened once and things were back to normal after that. It's still rather frustrating that the other remote discovery went on for five hours, was interrupted by a timeout or other error, and then restarted once again.

**Comment by ckamm** [comment] 2018-01-18 09:28
@sagamusix :(

Okay, so:
1) The exclude performance is fine.
2) Remote discovery is slow.
3) If the initial hour-long remote discovery is aborted, it has to be done again from scratch.
4) 503s can freeze the client.

@ogoffart

**Comment by michaelstingl** [comment] 2018-01-18 14:20
> 503s during propagation can freeze the client.

@SamuAlfageme please check. Related to https://github.com/owncloud/client/issues/5859 ?

**Comment by guruz** [comment] 2018-02-12 13:59
> It's still rather frustrating that the other remote discovery went on for five hours, was interrupted by a timeout or other error, and then restarted once again.

Ack, see https://github.com/owncloud/client/issues/2976

**Comment by ckamm** [comment] 2018-02-15 09:23
@guruz Good find. Let's do that for 2.5 if we can!

With that, I think this issue - the part about exclude performance - can be closed. @sagamusix If you get any more information about the client freeze please don't hesitate to open a new ticket. Thank you very much for all the data!

**Closed by ckamm** 2018-02-15 09:23 UTC
Labels: Performance
