### ISSUE TITLE
Feature request -> Possible to change the F12 to a different Key combination

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#5988] opened 2017-08-31 11:52 UTC
In many systems is the F12 used for other purposes.

My feature request is to make it easy for the end-user to change the F12 key to another that they like or can use.

I would be better to have it in the General Tab because most of the end-users can't edit the configuration file per hand.

@michaelstingl @SamuAlfageme

**Comment by ogoffart** [comment] 2017-09-06 07:34
An option for that is out of question. 
However we can assign a second shortcut which is less likely to be taken by something else. any suggestion? (Ctrl + L for example? L for Log)

**Comment by ogoffart** [comment] 2017-12-06 13:06
Duplicate of https://github.com/owncloud/client/issues/4098

**Closed by ogoffart** 2017-12-06 13:06 UTC
Labels: Design & UX, Enhancement
