### ISSUE TITLE
[Windows] sync a "protected" folder makes client report synced but really failed ?

### ISSUE THREAD

**Issue by mostolog** [owncloud/client#5291] opened 2016-11-01 22:28 UTC
Hi

Using latest client version, and trying to sync on Windows a folder located in **C:\Program Files**, client is not able to write on folder (probably a permission issue), but it still report "X files were downloaded" on tray balloon.

### Expected behaviour
If owncloud can't write those files, it should say it can't. 

### Actual behaviour
A notification balloon says files are downloaded/synced, but files doesn't appear on local folder.

### Possible fix
Client should check for files being written or API calls returning successfull operations, instead of not syncing at all, but notifying it did. Maybe requiring elevated permissions to work with an specific folder could work (altough it could become annoying if not done properly)

### Steps to reproduce
1. Install a program on C:\Program Files\Foo (or use any existing path)
2. Add folder to be synced on server/path
3. Copy a few files to folder from computer A (hence, files will be uploaded to server)
4. On computer B, try to configure the same folder to be synced (ie: 2 computers sharing C:\Program Files\Foo folder)
5. Files won't be written, altough owncloud client will report it did it.
6. Files created on A will be written on server, but won't be replicated to computer B
7. (the other way around)

Server: 9.1.0 (stable)
Client: windows 2.2.4.6408

Thanks!

**Comment by guruz** [comment] 2016-11-02 09:37
@proog128 @danimo would this be fixed by https://github.com/owncloud/client/pull/5285 ?

**Comment by proog128** [comment] 2016-11-02 19:54
I could reproduce this issue. The client reports success, although the files are not in the target folder. Instead, the client synced them into C:\Users\username\AppData\Local\VirtualStore\Program Files, as it is expected from UAC virtualization.

With the fix in #5285, syncing fails with "Unable to initialize a sync journal."

**Comment by guruz** [comment] 2016-11-03 11:23
> fails with "Unable to initialize a sync journal."

That's what you'd expect, right?
So #5285 is your fix for this issue?

**Comment by mostolog** [comment] 2016-11-03 11:38
IMHO that's message could be much improved, even redirecting to a known-issues page, apart from this being implemented/making owncloud to be able to write on protected folders.

**Comment by proog128** [comment] 2016-11-03 18:38
@guruz Yes, I expect it to fail. The error message could be improved, though.

**Comment by guruz** [comment] 2016-11-15 08:21
@mostolog Do you want to try this nightly build? http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.6510-nightly20161115-setup.exe

It should display an error when syncing.

**Comment by guruz** [comment] 2016-11-23 10:49
@mostolog Did you manage to try?

**Comment by mostolog** [comment] 2016-11-23 11:02
Sorry I wasn't able. It's on my never-ending-always-growing TODO list...
I just tested with today's nightly on another computer and it didn't failed (it downloaded properly), so I'm doubting it has the same permissions the other computer had...

**Comment by SamuAlfageme** [comment] 2016-11-30 17:02
@guruz @mostolog Just tried with both, a version pre- #5285 (the one used in this issue: 2.2.4.6408) and today's nightly. The sync is no longer shown as successful (`Unable to initialize a sync journal.` error as mentioned. I'm with @proog128 it could be more descriptive of the situation) the files in this folder not uploaded to the server nor the activity wrongly displayed in the tab like it did before. 

The overlays though, are still being all ✅-ish in the local folder and 🔁 when creating some new file in there.

**Comment by ogoffart** [comment] 2017-04-28 10:14
@SamuAlfageme  in  https://github.com/owncloud/client/pull/5734 , i changed the wording of the error message.

@jturcotte  Regarding the overlay icon: is it not by design, that the root icon shows a success even tough the sync cannot be done?

**Comment by jturcotte** [comment] 2017-05-09 07:56
The overlay will report issues with files, but if the problem is to write a file from the server, which file should get an error? The read-only directory isn't really a problem until you try to write to it, so I would think it's correct in this case that overlay icons show a success if that file was successfully synced **to** the server. For file **from** the server, the overlay icons seem to be the wrong place to report issues, what do you think?

**Comment by ckamm** [comment] 2017-09-13 09:07
What remains to be done? It sounds like the error reporting has improved and the overlay icon behavior is not obviously incorrect.

**Closed** 2018-11-29 16:57 UTC
Labels: Design & UX, p4-low
