### ISSUE TITLE
Check icon install on linux ensure the icon name matches the expectations

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9378] opened 2022-01-20 08:01 UTC
https://github.com/owncloud/client/blob/e8ddd54e03617452950b47ff684eee1fa74a0228/shell_integration/icons/CMakeLists.txt#L8-L11

**Comment by gabi18** [comment] 2022-01-20 08:28
Steps done:

* btr-client 2.9.2 installed on openSUSE 15.3
* updated to btr-client-2.10.0-6539 (executable name 'BtR')

```
localhost:~ # rpm -qv btr-client
btr-client-2.10.0-6539.x86_64
localhost:~ # rpm -ql btr-client
/etc/btr
/etc/btr/sync-exclude.lst
/etc/sysctl.d/99-BtR-inotify.conf
/opt
/opt/ownCloud
/opt/ownCloud/btr
/opt/ownCloud/btr/bin
/opt/ownCloud/btr/bin/BtR
/opt/ownCloud/btr/bin/BtRcmd
/opt/ownCloud/btr/include
/opt/ownCloud/btr/lib64
/opt/ownCloud/btr/lib64/libBtR_csync.so.0
/opt/ownCloud/btr/lib64/libBtR_csync.so.2.10.0
/opt/ownCloud/btr/lib64/libBtRsync.so.0
/opt/ownCloud/btr/lib64/libBtRsync.so.2.10.0
/opt/ownCloud/btr/lib64/plugins
/opt/ownCloud/btr/lib64/plugins/BtRsync_vfs_suffix.so
/usr/bin/BtR
/usr/bin/BtRcmd
/usr/share/applications/BtR.desktop
/usr/share/doc/packages/btr-client
/usr/share/doc/packages/btr-client/COPYING
/usr/share/doc/packages/btr-client/README.md
/usr/share/icons/hicolor
/usr/share/icons/hicolor/1024x1024
/usr/share/icons/hicolor/1024x1024/apps
/usr/share/icons/hicolor/1024x1024/apps/BtR.png
/usr/share/icons/hicolor/1024x1024/apps/btr.png
/usr/share/icons/hicolor/128x128
/usr/share/icons/hicolor/128x128/apps
/usr/share/icons/hicolor/128x128/apps/BtR.png
/usr/share/icons/hicolor/128x128/apps/btr.png
/usr/share/icons/hicolor/256x256
/usr/share/icons/hicolor/256x256/apps
/usr/share/icons/hicolor/256x256/apps/BtR.png
/usr/share/icons/hicolor/256x256/apps/btr.png
/usr/share/icons/hicolor/32x32
/usr/share/icons/hicolor/32x32/apps
/usr/share/icons/hicolor/32x32/apps/BtR.png
/usr/share/icons/hicolor/32x32/apps/btr.png
/usr/share/icons/hicolor/48x48
/usr/share/icons/hicolor/48x48/apps
/usr/share/icons/hicolor/48x48/apps/BtR.png
/usr/share/icons/hicolor/48x48/apps/btr.png
/usr/share/icons/hicolor/512x512
/usr/share/icons/hicolor/512x512/apps
/usr/share/icons/hicolor/512x512/apps/BtR.png
/usr/share/icons/hicolor/512x512/apps/btr.png
/usr/share/icons/hicolor/64x64
/usr/share/icons/hicolor/64x64/apps
/usr/share/icons/hicolor/64x64/apps/BtR.png
/usr/share/icons/hicolor/64x64/apps/btr.png
/usr/share/mime/packages/BtR.xml
localhost:/usr/share/icons/hicolor/512x512/apps # ll
total 1084
-rw-r--r-- 1 root root 434658 Jan 19 11:30 BtR.png
-rw-r--r-- 1 root root 434658 Jan 19 11:23 btr.png
-rw-r--r-- 1 root root      0 Jan 20 09:21 icons.txt
-rw-r--r-- 1 root root  45032 Jun  8  2020 kate.png
...
```

**Comment by fmoc** [comment] 2022-01-20 14:09
There was a workaround implemented in the packaging scripts that explicitly copied the files to `<APPLICATION_EXECUTABLE>.<ext>`, referring to https://github.com/owncloud/ownbrander/issues/322. As we use the shortname exclusively for all resources such as icons since 2.10 (and the deployment works, the files are there, as shown in the previous comments, and the `Icon` entry in the desktop file is also correct), I think we can remove this workaround safely.

Note that the issue is clearly a non-blocker. The workaround just added some bloat, but it's pretty harmless overall. Also, it just affects the openSUSE releases.

**Comment by fmoc** [comment] 2022-02-21 10:35
The issue has been fixed in the Linux build scripts. It has not been caused by code within this repository anyway. I think we can close this issue.

**Closed by fmoc** 2022-02-21 10:35 UTC
Labels: p2-high
