### ISSUE TITLE
Client does not upload changed file residing in folder with name "0"

### ISSUE THREAD

**Issue by powerpaul17** [owncloud/client#3351] opened 2015-06-16 15:57 UTC
### Expected behaviour
Client should upload changed file

### Actual behaviour
Client downloads previous version and saves new local version to .conflict file

### Steps to reproduce
1. Create a folder named "0"
2. Create a file inside this folder
3. Let the client upload the new file
4. Change contents of file
5. Watch the client restore the previous version and create a .conflict file

### Server configuration
Operating system: FreeBSD

Web server: Nginx

Database: MySQL

PHP version: 5.6

ownCloud version: 8.0.3

Storage backend: local

### Client configuration
Client version: 1.8.2

Operating system: Linux

OS language: German

Installation path of client: /usr/bin/owncloud

### Logs

coming soon..

**Comment by guruz** [comment] 2015-06-17 07:49
@icewind1991 @PVince81 Just wondering if this was one of the "0"-PHP issues..

**Comment by PVince81** [comment] 2015-06-17 08:06
I thought that one was ironed out a long time ago

**Comment by PVince81** [comment] 2015-06-17 09:07
Works for me with ownCloud 8.1 (git master 3898b8c9b89609a199b87d4d3ce1c7fe95026c1c)

Reproducible on stable8 (upcoming 8.0.5)

**Comment by PVince81** [comment] 2015-06-17 09:22
Hmm, 8.1 also has a problem.
I reset the sync client and then tried to make it redownload the file "0/test.txt", log says
```
{"reqId":"z0rC4QWjGTdwLUVM7Lxf","remoteAddr":"127.0.0.1","app":"files","message":"Could not get node for path: \\\"test.txt\\\" : File with name test.txt could not be located","level":2,"time":"2015-06-17T09:21:43+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/0"}
```

**Comment by PVince81** [comment] 2015-06-17 09:33
Here it is: the Sabre library strips off the "0" folder: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/Server.php#L851

I'll submit a patch upstream.

**Comment by PVince81** [comment] 2015-06-17 09:38
And that is not enough, uploading still doesn't work. After modifying the file 2-3 times the conflict behavior appears on 8.1 too.

**Comment by PVince81** [comment] 2015-06-17 10:04
Sabre patch submitted here: https://github.com/fruux/sabre-dav/pull/677.
But this is only about PROPFIND, unrelated to this issue here.

Let's have a look at the upload.

**Comment by PVince81** [comment] 2015-06-17 10:24
From what I see, the client does not even try and overwrite the remote version, and says that it's read-only.
Checking the local database:
```
phash|pathlen|path|inode|uid|gid|mode|modtime|type|md5|fileid|remotePerm|filesize
-8652850453875763580|13|abc/props.txt|6119788|0|0|0|1434533380|0|3bd3d0100a0034de54173fd4811aea71|00000026ocj313pya6ee|RDNVW|0
-7155887566424083901|3|abc|6119787|0|0|0|1434533380|2|55813e0438b5f|00000025ocj313pya6ee|RDNVCK|0
1962109525617788544|11|welcome.txt|6119789|0|0|0|1434532036|0|7bf80151b5ef6ec8b2dcf3a68fdbc79b|00000004ocj313pya6ee|RDNVW|163
-7267802101910404785|1|x|6119790|0|0|0|1434532801|0|841799410ad8a14cdd630ff6572f7aca|00000022ocj313pya6ee|RDNVW|0
3030533343647321160|10|0/test.txt|6121636|0|0|0|1434535957|0|cad65e5dc6aecb07002def7098b41113|00000037ocj313pya6ee|RDNVCK|5
8982665681616756341|1|0|6119785|0|0|0|1434536208|2|558138d7c6beb|00000008ocj313pya6ee|RDNVCK|0
```

If we pick a regular text file, the permissions are "RDNVW".
But for "0/test.txt" the permissions are "RDNVCK", it looks like the very first upload might have returned the wrong permissions. These permissions also look like folder permissions, so possibly at that moment the server truncated the path.

Next up: investigate the first upload and why the returned permissions are wrong.

**Comment by PVince81** [comment] 2015-06-17 10:28
I redid the steps and observed the database (with the Sabre patch mentionned above applied):
1. Create a new file "0/new.txt", wait for sync.
2. Local database says its permissions are "RDNVW" which is correct
3. Edit "0/new.txt" and change the contents, wait for sync.
4. Local database says its permissions have become "RDNVCK" !

From this point on, and update of the file will result in the "read-only" message and conflict files.

Now to find out while the first overwrite changes the file permissions.

**Comment by PVince81** [comment] 2015-06-17 10:34
Boah okay... that was after resetting the client / database.
Now if I create new files into that directory, even the first upload gets wrong permissions.

Debugging shows me that the first upload works fine, but there are no permissions returned.
@guruz where does the sync client get the permissions after upload ? Subsequent PROPFIND ?

**Comment by PVince81** [comment] 2015-06-17 10:40
@guruz I don't seem to see any subsequent PROPFIND call. After the PUT call, the database seems to be updated already.
Does the client derive the permissions from the parent folder "0" ? Maybe there's a bug there too ?

**Comment by PVince81** [comment] 2015-06-17 10:44
This is my client version: owncloud-client-1.8.3~rc1-2.1.x86_64

**Comment by PVince81** [comment] 2015-06-17 10:56
Assigning to @guruz to double check the client permissions logic with "0"

**Comment by powerpaul17** [comment] 2015-06-17 17:37
wow, that was quick.. thanks guys! do you still need my logs? it seems you have figured it out yourself already.. :)

**Comment by PVince81** [comment] 2015-06-17 18:12
No logs needed, thanks.

**Closed** 2015-07-28 11:29 UTC
Labels: Server Involved
