### ISSUE TITLE
[QA] Sync starts over after pausing

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10283] opened 2022-11-16 09:05 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Sync starts over after pausing instead of resuming where it stopped 

### Steps to reproduce the issue

Steps to reproduce:

1. Start uploading 1G file
2. Pause the sync
3. Resume the sync

### Screenshots

no screenshot

### Expected behavior

Synced resumed where it stopped

### Actual behavior

Sync has started over

**Comment by TheOneRing** [comment] 2022-11-16 09:13
Related: #10231

**Comment by TheOneRing** [comment] 2022-11-18 12:33
Duplicate of: https://github.com/owncloud/client/issues/10231

**Closed by TheOneRing** 2022-11-18 12:33 UTC
Labels: QA:team
