### ISSUE TITLE
owncloud client asks me for authentication after every restart

### ISSUE THREAD

**Issue by sqsmacz** [owncloud/client#7576] opened 2019-11-05 12:56 UTC
### Expected behaviour
After I authorize application it should be authorized permanently until I reinstall/uninstall it.

### Actual behaviour
I use 3 stations with owncloud client installed: Mac, Win, Win.
After I authorize my app on Mac, then on both Windows it's ok.
But after I restart any app on any my computer app becomes unauthorized and asking me again to authorize.

### Steps to reproduce
1. Install app on one computer
2. authorize app on the server
3. install app on another computer
4. Authorize app
5. restart app on first computer

### Server configuration
Operating system:
Mac OS X, Windows

Web server: 
apache

Database:
postgres or mysql

PHP version:
7.2

ownCloud version:
latest stable

Storage backend (external storage):
none

### Client configuration
Client version:
latest stable

Operating system:
Mac OS X, Windows 10 latest

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
NA

Client package (From ownCloud or distro) (Linux only):
NA

Installation path of client:
standard

### Logs
not attached

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ogoffart** [comment] 2019-11-08 08:59
What is the authorization mechanism? Are you using oauth2 (client open the browse), app password, or normal password?

So do i understand you correctly that as long as you stay with one computer, it remembers the password,  but if you use two computer it doesn't?

Is there any difference between platform?  (Does it work with one platform but not the other)

**Comment by soniqsoft** [comment] 2019-11-08 15:21
Hi @ogoffart,
Thanks for your message.
I use as follow:
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/55397971/68487434-5cba5080-0243-11ea-885a-1168eb4f61dc.png">
<img width="308" alt="image" src="https://user-images.githubusercontent.com/55397971/68487590-a5720980-0243-11ea-9cc8-d0557d68afd1.png">

_"So do i understand you correctly that as long as you stay with one computer, it remembers the password, but if you use two computer it doesn't?"_
It's not always true, it's my observation but sometimes it happens unexpected.
 
_"Is there any difference between platform? (Does it work with one platform but not the other)"_
No, it behaves the same on Mac and Win.

**Comment by ogoffart** [comment] 2019-11-11 09:28
Can you try to restart one of the computer without being connected with another computer and see if this works correctly? This could help eliminate the case where the client just forgets the refresh token.

This is maybe something wrong on the server which does not allow several client?
Having the http log would help debugging.  Does the client send a refresh token to the server while connecting? Why don't the server accepts it?

**Comment by soniqsoft** [comment] 2019-11-11 21:36
Hi @ogoffart,
I tried and it happened even for accounts that I use on one computer only.
I didn't realize it's like that for the other accounts.
Thanks!

**Comment by ogoffart** [comment] 2019-11-12 08:20
Could we get client or server logs that shows if the client sends a refresh token to the server?

**Comment by soniqsoft** [comment] 2019-11-12 08:54
Sure you can. Can you guide me what should I look for in server log and where is the client log on Mac OS X?

**Comment by ogoffart** [comment] 2019-11-12 08:57
I believe you can use --logwindow  or F12 to see the settings for logging on the client side.
On the server side, the logs should be in some files on the server. probably called owncloud.log

**Comment by michaelstingl** [comment] 2019-11-12 09:35
> Sure you can. Can you guide me what should I look for in server log and where is the client log on Mac OS X?

https://doc.owncloud.org/desktop/troubleshooting.html#log-files

**Comment by severalthings** [comment] 2019-12-01 19:56
I have the same experience with Ubuntu 18.04 LTS and Debian Buster using the repositories
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_10 / Ubuntu_18.04  respectively. Problems startes a few days ago.

The oc-client doesn't find the password and asks the user. Using seahorse, it shows that the password is in the passwordsafe.

Other are experiencing the same with XUbuntu 19.10:
https://central.owncloud.org/t/xubuntu-keychain-error/22825

**Comment by severalthings** [comment] 2019-12-01 20:12
The logfile:
12-01 20:52:10:004 [ info gui.application ]:    "################## ownCloud loc
ale:[de_DE] ui_lang:[] version:[2.6.0 (build 1714)] os:[Ubuntu 18.04.3 LTS]"
12-01 20:52:10:004 [ info gui.application ]:    Using "de_DE" translation
12-01 20:52:10:005 [ info gui.application ]:    Adding extra plugin search path:
 "/opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/ownCloud/plugins"
12-01 20:52:10:005 [ info gui.application ]:    VFS suffix plugin is available
12-01 20:52:10:005 [ info gui.socketapi ]:      server started, listening at  "/run/user/1000/ownCloud/socket"
12-01 20:52:10:005 [ info gui.folder.manager ]: setting remote poll timer interval to 30000 msec
12-01 20:52:10:217 [ info gui.application ]:    Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
12-01 20:52:10:219 [ info gui.folder.manager ]: Setup folders from settings file
12-01 20:52:10:219 [ info sync.configfile ]:    Adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
12-01 20:52:10:224 [ info sync.database ]:      sqlite3 version "3.29.0"
12-01 20:52:10:224 [ info sync.database ]:      sqlite3 locking_mode= "exclusive"
12-01 20:52:10:224 [ info sync.database ]:      sqlite3 journal_mode= "wal"
12-01 20:52:10:224 [ info sync.database ]:      sqlite3 synchronous= "NORMAL"
12-01 20:52:10:225 [ info gui.folder.manager ]: Adding folder to Folder Map  OCC::Folder(0x55946c498040) "1"
12-01 20:52:10:225 [ info gui.folder.manager ]: Schedule folder  "1"  to sync!
:

**Comment by hangfirew8** [comment] 2020-01-04 13:33
Hello, thank you for a fantastic product. I have been using it since v5.

I have been experiencing this bug since I upgraded to 2.6.0. I am running Mint 19.1 (essentially Ubuntu 18.04) as my client and the latest 10.3 on Ubuntu 18.04LTS as my server. Here is the client log:
<script src="https://gist.github.com/hangfirew8/0478d8c82704305b52099a4891408ce0.js"></script>

My server log /var/log/owncloud.log is still zero bytes with a creation date of the 10.3 upgrade date.

**Comment by hangfirew8** [comment] 2020-01-04 13:41
Thank you for a fantastic product, I have been using it since v5.

I am experiencing the same bug since upgrading to 2.6.0 on Mint 19.1 Cinnamon (essentially Ubuntu 18.04 with a different window manager). My server is Ubuntu 18.04LTS running the latest 10.3. The server log /var/log/owncloud.log is zero bytes with a creation date of the 10.3 upgrade. Below is the gist link. The result of clicking the link is ugly, but I followed the git instructions to a T. Well, I substituted "=log.txt" for "=FILE" since that didn't work at all.

https://gist.github.com/hangfirew8/0478d8c82704305b52099a4891408ce0.js?file=log.txt

**Comment by michaelstingl** [comment] 2020-01-05 11:10
I think this plain link is okay:
https://gist.github.com/hangfirew8/0478d8c82704305b52099a4891408ce0

**Comment by michaelstingl** [comment] 2020-01-05 11:16
Sounds related: https://github.com/owncloud/client/issues/7578 , https://github.com/owncloud/client/issues/7638 , https://github.com/owncloud/client/issues/7536

**Comment by SpacyNG** [comment] 2020-01-08 19:25
2.6.0 still produces this bug even without libgnome-keyring, but it seems to be fixed in the testing repo.
`http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing/Ubuntu_19.10`
Current version at the time of this writing is 2.6.1~sprint2+oc-1994 and this works nicely.

**Comment by MRudey** [comment] 2020-01-09 14:47
I had this issue with 2.6.0 when upgrading from Ubuntu 18.04 to 19.10 and I can confirm @SpacyNG 's 'fix' works. At least it did not appear again after using the testing repo. Although my version is (apparently) not the same. The output of `owncloud --version` is 
```
ownCloud version 2.6.0 (build 1714)
Git revision 90ac7941c54975e165b1bc6a5e2172e4dc499827
Using Qt 5.12.5, built against Qt 5.12.5
Using 'OpenSSL 1.1.1c  28 May 2019'
```

**Comment by SpacyNG** [comment] 2020-01-15 16:49
@MRudey Do you possibly have two versions of owncloud installed? 2.6.0 build 1714 is the one in the official, stable repository (http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_19.10/), while the testing and daily repositories have 2.6.1-sprint2 (build-2000). 
Maybe your desktop uses the testing version, while your command line uses the old one?

**Comment by ojsti** [comment] 2020-01-23 22:31
I also have the Issue with the macosx 10.15.2 catalina sync client. When I logout on my mac i have to reauthenticate and setup the owncloud connection everytime. Already updated the owncloud server, cleaned the keychain and the startupitems. Has anyone yet a solution?

**Comment by michaelstingl** [comment] 2020-01-24 09:57
@ojsti I don’t experience this on macOS. Could you open a new issue with all the relevant information? This issue got hijacked by Linux users, so it‘s harder to work on the macOS Problem in a focused way.

**Closed by michaelstingl** 2020-01-24 09:57 UTC

**Comment by SpacyNG** [comment] 2020-01-25 22:50
@ojsti: From the original bug report and my (linux) experience, I only was asked to reauthenticate. Not to add the account again.. The account was still in my owncloud client, it just couldn't connect.
Also did you try the daily I suggested in a few comments above? Something like "2.6.1~sprint2-xxx". Maybe this also fixes it on MacOS.
If this is not possible, 2.6.1 release seems quite close now, so maybe wait for it?

**Comment by soniqsoft** [comment] 2021-09-01 07:11
Hi,
I'm using client 2.8.2 build 4246 and still have to reauthorize my all accounts on MacOSX after even changing network. It's annoying and does not help on daily basis. Any advise?
Server is installed on Centos 7 latest build and latest owncloud server release.

**Comment by michaelstingl** [comment] 2021-09-01 07:18
@soniqsoft please check again with the 2.9.0-RC1:
https://download.owncloud.com/desktop/ownCloud/testing/2.9.0-rc1.5070/mac/

In case the issue still occurs, please open a new issue and provide the relevant information.

**Comment by dillfrescott** [comment] 2023-02-11 02:48
Still experiencing this issue with the Docker version. Please help

**Comment by michaelstingl** [comment] 2023-02-13 08:10
@dillfrescott please open a new issue and provide the relevant information. This one is an ancient issue about an ancient version.
