### ISSUE TITLE
[Feature Request] Implement support for git-like .ignore files

### ISSUE THREAD

**Issue by axelrindle** [owncloud/client#7893] opened 2020-06-08 16:01 UTC
Currently files and directories can be ignored by adding patterns to a global list in the client settings. This list eventually becomes very large and is hard to manage.

Ignoring files on a per-directory basis, similar to git's `.gitignore` files, would make this task a lot easier.

**Comment by michaelstingl** [comment] 2020-06-08 16:12
Thanks, duplicate of #1558

**Closed by michaelstingl** 2020-06-08 16:12 UTC
