### ISSUE TITLE
Client downloads the file correctly, but then doesn't rename it from the temporary name and says sync failed

### ISSUE THREAD

**Issue by Havenard** [owncloud/client#2789] opened 2015-02-06 16:47 UTC
I'm having an issue with some files where the ownCloud Client 1.7.1 (build 4382) on Windows 7 64-bits is downloading the files correctly from the server, but then it fails with message "File not found". It is happening in several machines with equivalent configuration syncing the same folders.

The temporary file it creates when downloading is there, and its complete. But it is not being renamed to its correct name.

The local absolute path of the files is quite long, about 260 characters, however I have much longer paths than this where I never had issues. I can rename the file to its correct name manually without issues, but I didnt do that with the Client running afraid it could create more problems.

If I tell it to retry syncing several times, it eventually suceeds for some files, but for others its just helpless. I could not determine why, but I do know the temporary file is suffixed with random characters that vary in length, so maybe its a specific path length that causes the problem.

**Comment by guruz** [comment] 2015-02-07 13:26
(Note to self: Could very well be related to the general long folder issues we have at the moment)
https://github.com/owncloud/client/issues/60

**Comment by edd--** [comment] 2015-02-14 10:23
exactly the same problem here, makes the solution unusable for my 75 windows users :( Been having this problem for several months now, please fix ...

**Comment by ckamm** [comment] 2015-02-26 12:03
@Havenard @edd-- Could you run the client with --logfile log.txt and upload the log file? (ideally you only sync a single folder with a single problematic file for the test, to keep the log size small) That would pinpoint where the error occurs and help with tracking down the cause.

**Comment by usrbin123** [comment] 2015-03-16 16:47
@ckamm : Having the same problem with my windows client here.
I cannot even say, which files are concerned. It happens randomly.
Refreshing the client database with F5 won't fix the problem. 

Using Mac Clients with the same files does not provoke an error.

### Server configuration
**Operating system**: Linux # 1 SMP Debian 3.2.65-1+deb7u1

**Machine Type:** x86_64

**vmsize:** 1GB

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.21
**PHP Integer Size:** 64 bits

**ownCloud version:** 8.0.2 (stable)
**Desktop Client Version:** 1.7.1 (Windows 7, x64)

**Updated from an older ownCloud or fresh install:** Update from 7.0.2

**List of activated apps:** 
- Files Move 0.7.3a

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => ‚DOMAIN.com‘,
    1 => 'www.DOMAIN.com',
  ),
  'datadirectory' => '/usr/www/users/USER/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.2.',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_domain' => ‚DOMAIN.com',
  'mail_from_address' => 'cloud',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => ‚HOST‘,
  'mail_smtpport' => '587',
  'mail_smtppassword' => '',
  'mail_smtpname' => 'cloud@DOMAIN.com',
  'forcessl' => true,
  'loglevel' => '0',
);

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

### Client configuration

**Operating system:**
Windows 7, x64

### Logs
#### Client Log
```

03-16 16:11:17:612 0x782eba8 _csync_merge_algorithm_visitor: INSTRUCTION_NEW      file: PATH/TO/FILE/FILENAME WITH - AND ().pdf

03-16 16:11:20:061 0x782eba8 _csync_merge_algorithm_visitor: INSTRUCTION_SYNC      dir: PATH/TO/FILE

03-16 16:11:21:576 0x782eba8 _csync_merge_algorithm_visitor: INSTRUCTION_NEW      file: PATH/TO/FILE/ANOTHER FILENAME WITH - AND ().pdf

03-16 16:11:26:455 0x782eba8 _csync_merge_algorithm_visitor: INSTRUCTION_NEW      file: PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 2.pdf


03-16 16:11:26:528 0x782eba8 _csync_merge_algorithm_visitor: INSTRUCTION_NEW      file: PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 3.pdf


03-16 16:11:30:235 0x782eba8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:C:\Users\USER\DIRECTORY\PATH\TO\FILE"

03-16 16:11:31:814 0x782eba8 socketapi.cpp:382 void Mirall::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, Mirall::SocketType*) "C:\Users\USER\DIRECTORY\PATH\TO\FILE"
03-16 16:11:31:817 0x782eba8 syncengine.cpp:1114 bool Mirall::SyncEngine::estimateState(QString, csync_ftw_type_e, Mirall::SyncFileStatus*) Setting "PATH/TO/FILE"  to STATUS_EVAL
03-16 16:11:31:818 0x782eba8 socketapi.cpp:539 Mirall::SyncFileStatus Mirall::SocketApi::fileStatus(Mirall::Folder*, const QString&, c_strlist_t*) Folder estimated status for "PATH/TO/FILE" to "SYNC"
03-16 16:11:31:819 0x782eba8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC+SWM:C:\Users\USER\DIRECTORY\PATH\TO\FILE"


03-16 16:11:34:229 0x782eba8 propagator_qnam.cpp:589 virtual void Mirall::PropagateDownloadFileQNAM::start() "PATH/TO/FILE/FILENAME WITH - AND ().pdf" 0
03-16 16:11:34:231 0x782eba8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:\Users\USER\DIRECTORY/PATH/TO/FILE/FILENAME WITH - AND ().pdf"
03-16 16:11:34:233 0x782eba8 syncjournaldb.cpp:756 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "PATH/TO/FILE/FILENAME WITH - AND ().pdf" "PATH/TO/FILE/.FILENAME WITH - AND ().pdf.~4e51" "6a4e3fa153e59d730a1ddf7991f8691a" 0
03-16 16:11:34:235 0x782eba8 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
03-16 16:11:34:237 0x782eba8 propagator_qnam.cpp:647 File is already complete, no need to download
03-16 16:11:34:239 0x782eba8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:\Users\USER\DIRECTORY/PATH/TO/FILE/FILENAME WITH - AND ().pdf"
03-16 16:11:34:240 0x782eba8 owncloudpropagator.cpp:93 This error is not blacklisted  0
03-16 16:11:34:241 0x782eba8 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "PATH/TO/FILE/FILENAME WITH - AND ().pdf" 2 "Das System kann den angegebenen Pfad nicht finden.
"
03-16 16:11:34:243 0x782eba8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:"
03-16 16:11:34:251 0x782eba8 propagator_qnam.cpp:589 virtual void Mirall::PropagateDownloadFileQNAM::start() "PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 2.pdf" 0
03-16 16:11:34:252 0x782eba8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:\Users\USER\DIRECTORY/PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 2.pdf"
03-16 16:11:34:254 0x782eba8 syncjournaldb.cpp:756 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 2.pdf" "PATH/TO/FILE/.ANOTHER FILENAME WITH - AND () 2.pdf.~7b4c" "4c04e0582015343d7ab49910388bca73" 0
03-16 16:11:34:256 0x782eba8 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
03-16 16:11:34:257 0x782eba8 propagator_qnam.cpp:647 File is already complete, no need to download
03-16 16:11:34:258 0x782eba8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:\Users\USER\DIRECTORY/PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 2.pdf"
03-16 16:11:34:259 0x782eba8 owncloudpropagator.cpp:93 This error is not blacklisted  0
03-16 16:11:34:260 0x782eba8 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 2.pdf" 2 "Das System kann den angegebenen Pfad nicht finden.
"
03-16 16:11:34:262 0x782eba8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:"
03-16 16:11:34:273 0x782eba8 propagator_qnam.cpp:589 virtual void Mirall::PropagateDownloadFileQNAM::start() "PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 3.pdf" 0
03-16 16:11:34:274 0x782eba8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:\Users\USER\DIRECTORY/PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 3.pdf"
03-16 16:11:34:276 0x782eba8 syncjournaldb.cpp:756 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 3.pdf" "PATH/TO/FILE/.ANOTHER FILENAME WITH - AND () 3.pdf.~7755" "2f35ee0f46388accbc9777d188f1cf9d" 0
03-16 16:11:34:277 0x782eba8 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
03-16 16:11:35:812 0x782eba8 propagator_qnam.cpp:647 File is already complete, no need to download
03-16 16:11:35:815 0x782eba8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:\Users\USER\DIRECTORY/PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 3.pdf"
03-16 16:11:35:819 0x782eba8 owncloudpropagator.cpp:93 This error is not blacklisted  0
03-16 16:11:35:821 0x782eba8 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 3.pdf" 2 "Das System kann den angegebenen Pfad nicht finden.
"
03-16 16:11:35:827 0x782eba8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:"
03-16 16:11:34:292 0x784e600 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/USER\DIRECTORY/.csync_journal.db-wal" action: 3
03-16 16:11:35:847 0x782eba8 folderwatcher.cpp:76 * Discarded as is hidden! "C:/Users/USER\DIRECTORY/.csync_journal.db-wal"
03-16 16:11:35:242 0x784e600 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/USER\DIRECTORY/.csync_journal.db" action: 3
03-16 16:11:35:854 0x782eba8 folderwatcher.cpp:76 * Discarded as is hidden! "C:/Users/USER\DIRECTORY/.csync_journal.db"
03-16 16:11:35:260 0x784e600 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/USER\DIRECTORY/.csync_journal.db" action: 3
03-16 16:11:35:891 0x782eba8 propagator_qnam.cpp:589 virtual void Mirall::PropagateDownloadFileQNAM::start() "PATH/TO/FILE/ANOTHER FILENAME WITH - AND ().pdf" 0
03-16 16:11:35:892 0x782eba8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:\Users\USER\DIRECTORY/PATH/TO/FILE/ANOTHER FILENAME WITH - AND ().pdf"
03-16 16:11:35:895 0x782eba8 syncjournaldb.cpp:756 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "PATH/TO/FILE/ANOTHER FILENAME WITH - AND ().pdf" "PATH/TO/FILE/.ANOTHER FILENAME WITH - AND ().pdf.~30ba" "042a21d6953717196c75b96ad1085351" 0
03-16 16:11:35:896 0x782eba8 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
03-16 16:11:35:958 0x782eba8 propagator_qnam.cpp:647 File is already complete, no need to download
03-16 16:11:35:961 0x782eba8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:\Users\USER\DIRECTORY/PATH/TO/FILE/ANOTHER FILENAME WITH - AND ().pdf"
03-16 16:11:35:965 0x782eba8 owncloudpropagator.cpp:93 This error is not blacklisted  0
03-16 16:11:35:967 0x782eba8 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "PATH/TO/FILE/ANOTHER FILENAME WITH - AND ().pdf" 2 "Das System kann den angegebenen Pfad nicht finden.
"
03-16 16:11:35:974 0x782eba8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:"
03-16 16:11:35:902 0x784e600 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/USER\DIRECTORY/.csync_journal.db-wal" action: 3
03-16 16:11:35:987 0x782eba8 folderwatcher.cpp:76 * Discarded as is hidden! "C:/Users/USER\DIRECTORY/.csync_journal.db-wal"


", "PATH/TO/FILE/FILENAME WITH - AND ().pdf: Das System kann den angegebenen Pfad nicht finden.
", "PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 2.pdf: Das System kann den angegebenen Pfad nicht finden.
", "PATH/TO/FILE/ANOTHER FILENAME WITH - AND () 3.pdf: Das System kann den angegebenen Pfad nicht finden.
", "PATH/TO/FILE/ANOTHER FILENAME WITH - AND ().pdf: Das System kann den angegebenen Pfad nicht finden.

03-16 16:11:45:261 0x782eba8 socketapi.cpp:382 void Mirall::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, Mirall::SocketType*) "C:\Users\USER\DIRECTORY\PATH\TO\FILE"
03-16 16:11:45:262 0x782eba8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:OK+SWM:C:\Users\USER\DIRECTORY\PATH\TO\FILE"
```

**Comment by ckamm** [comment] 2015-03-25 08:46
@guruz Just a thought: Maybe this happens when the path *for the download temporary* exceeds the 255 character limit and the original file doesn't?

**Comment by guruz** [comment] 2015-05-08 14:44
I pushed a fix for this. It will be in the nightly build coming tomorrow morning (as usual those nightly builds are not fully QAed..)

http://download.owncloud.com/desktop/daily/

**Comment by guruz** [comment] 2015-05-15 14:19
@nunomazer @christianrj FYI..
Feel free to report back if this works for you..

**Comment by Dianafg76** [comment] 2015-05-29 07:45
I tested the issue with DESKTOP v 1.8.2 (build 5122), and it is working fine.
I close the issue

**Closed by Dianafg76** 2015-05-29 07:45 UTC
Labels: bug, ReadyToTest

**Comment by harrypuru** [comment] 2019-01-09 05:31
I'm getting fatal logs and unable to sync files,
Path length(262) exceeds max path length(260):

Owncloud 8.0 on Xampp Windows Server 2008 r2
windows client 2.4.x 

Any suggestion

**Comment by michaelstingl** [comment] 2019-01-09 07:32
@harrypuru please update to ownCloud server 10.0.10 and client 2.5.1 then check again. If the issue is still there, please open an issue and provide all the requested information.
