### ISSUE TITLE
Rename duplicates local folder when shared with only change permissions

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7293] opened 2019-07-04 13:14 UTC
Tested with desktop client 2.6.0daily20190618 on Linux Mint. No virtual files. Server version 10.2.1RC3

User A shares folder Test with user B, granting **only** edit-change permission.
User A creates folder Test/Sub and file Test/file.txt

User B is connected with a desktop client, folder Test is synced.
User B renames Sub to subfolder using his local file browser.

Result is:
The sync protocol only logs the move actions:
![image](https://user-images.githubusercontent.com/1108546/60669216-0fca0600-9e6e-11e9-8ef7-0cc1698aaa5a.png)

After the sync run, User B now has both Sub and subfolder (all contents replicated).
![image](https://user-images.githubusercontent.com/1108546/60669373-77805100-9e6e-11e9-95af-8c2694c14a3a.png)

After a second sync run, User B gets an error message

![image](https://user-images.githubusercontent.com/1108546/60668957-74389580-9e6d-11e9-8726-82a62e1be792.png)
That is the end result.

PS: I've never seen that many overlay icons on a single file. This is contents of subfolder, as seen after the first sync run:
![image](https://user-images.githubusercontent.com/1108546/60668878-45baba80-9e6d-11e9-8db8-1129a2a42db5.png)

**Comment by jnweiger** [comment] 2019-07-04 13:37
Despite the odd local duplication of files, the rename succeeds. (The folder on the server changes name from Sub to subfolder.)

This rename would not succeed on the web-UI of 10.2.1RC3 with the given permissions.

Expected behaviour: web-UI and desktop should be consistent. No permanent error should remain in the client.

**Comment by jnweiger** [comment] 2019-07-04 13:46
Note: When user has only edit-change permission, renaming a file fails with
Error: Not allowed because you don't have permission to add files in that folder.

That is again the opposite behaviour of the web-UI.

**Comment by jnweiger** [comment] 2019-07-04 13:52
Note: When user has only edit-change permission, moving a file into a folder fails with
"Error: Not allowed because you don't have permission to add files in that folder."
The file gets duplicated.

**Comment by jnweiger** [comment] 2019-07-05 17:31
2.6.0daily on win10: folder gets renamed on the server, duplicated on the client. Same error message.

**Comment by HanaGemela** [comment] 2019-08-21 07:34
Same with Windows 10, client 2.6.0daily20190820 (build 12286), server 10.3.0 alpha

**Comment by HanaGemela** [comment] 2019-08-21 10:10
The same behaviour when renaming a folder with edit-**create** + edit-**delete** permissions.

**Comment by HanaGemela** [comment] 2019-08-21 14:52
Increasing the priority as this is regression - this used to work in 2.5.4 (Windows)
Needs to be fixed in 2.6.1.

**Comment by ogoffart** [comment] 2019-10-10 11:27
PR https://github.com/owncloud/client/pull/7514

**Comment by HanaGemela** [comment] 2019-12-03 10:20
2.6.1-daily20191127 (build 12791), macOS 10.15.1

Still broken:
1) Rename successes - the original resource has been renamed as well. Only local copy should be renamed
2) Rename without any permissions causes 'Not allowed because you don't have permissions to add subfolders to that folder' error and duplicates the content. It should just rename local copy without any errors

**Comment by jnweiger** [comment] 2019-12-10 14:23
I have not tested with 2.5.4 -- but if I recall correctly: back then, every move was implemented as delete and create. Not sure if it is really a regression. It is exctremly annoying though and still justifies p2. It has high potential of data loss, if the user does not recognize the duplicate early. E.g.: edit one, later look at the other, does not understand the problem, edit again, and then at some point delete ("the wong one") in an attempt to clean up.

**Comment by TheOneRing** [comment] 2019-12-10 14:31
As with the current implementation we can currently only detect the move when it was already executed, we can't really improve on this. 
Undoing the move could cause data loss.

As long as the move is done on the file system level we can't prevent it.
With a level in between, like a fuse we could prevent the move.

**Comment by HanaGemela** [comment] 2019-12-18 16:17
2.6.1sprint1 (build 12882), macOS 10.15.1
I'm not getting 'Not allowed because you don't have permissions to add subfolders to that folder' error  anymore
But renaming Test/Sub still succeeds

**Comment by ogoffart** [comment] 2020-02-06 15:49
I think the current behavior is the best we can do.
I don't think this is a regression, this has always been like that, or worse.

**Closed** 2021-03-17 15:15 UTC
Labels: Needs info, bug, p2-high, regression
