### ISSUE TITLE
Drop Qt 4 support?

### ISSUE THREAD

**Issue by guruz** [owncloud/client#4698] opened 2016-04-19 08:55 UTC
This would save us a lot of hassle when compiling all platforms.

It would also enable us to use nice Qt 5 features.

**Comment by dragotin** [comment] 2016-04-19 09:21
As we discussed: We can drop Qt4 support as soon as **all** of our supported distros have Qt5 in their standard repo.

An alternative would be that somebody maintains opt-packages such as this:
https://build.opensuse.org/package/show/isv:ownCloud:desktop/qt5-qtbase
for the distros in question.

I am closing this as a kind of dupe of #2558 if you allow.

**Closed by dragotin** 2016-04-19 09:21 UTC
Labels: technical debt
