### ISSUE TITLE
RunTime Error in owncloud

### ISSUE THREAD

**Issue by dannyeyres** [owncloud/client#6657] opened 2018-07-16 16:21 UTC
Hi there.
we have installed owncloud on one of our Domain Controllers for a customer and occasionally he gets the following error-

‘Runtime error ! program C:\Program Files (x86)\Owncloud\Owncloud.exe
The application has requested the runtime to terminate it in an unusual way.
Please contact the applications supports team for more information’

And then he gets an app crash. I have suggested re installing the program as this will take 5 mins max but the user won’t do this …
If someone could help on this matter and let me know of anything I can try without re installing the product that would be great

Danny

**Comment by ogoffart** [comment] 2018-07-17 06:59
Hi, thanks for your bug report.

We would need more information to be able to do anything.
What is the version of the client? How do you reproduce the problem?
Can you perhaps get the logs.
(Best would be a backtrace)

**Comment by dannyeyres** [comment] 2018-07-17 08:10
Thanks for coming back. the client versions shows as 2.4.1.9270 in the control panel. its difficult because I cannot recreate the issue my self but the client gets the error upon opening the program.. however this is intermittant. Is there any where specific I can get the logs from?

**Comment by dschmidt** [comment] 2018-10-28 09:40
Please test with 2.5.0 release or probably even better 2.5.1 nightlies.

If no crash reporter but this window used to come up, chances are that the crashreporter comes up now.

**Comment by ogoffart** [comment] 2019-03-15 10:04
Closing issue that we cannot reproduce.

**Closed by ogoffart** 2019-03-15 10:04 UTC
Labels: Needs info
