### ISSUE TITLE
[Windows] Client decides to delete many directories without apparent reason when updating server / bad connectivity

### ISSUE THREAD

**Issue by martinstutdgd** [owncloud/client#4575] opened 2016-03-17 07:18 UTC
### Expected behaviour

With the current user as the only user having write permission on the share, local files and directories should remain as they are, unless deliberately changed locally (or by another user via the server, which did not happen in this case),
even when the sync connection is slow and the client is shut down and/or hibernated
at any phase of the sync process,
even when the server is being updated using the OC provided Debian package, putting the server into maintenance mode,
even if Windows updates make the client reboot in the middle of a sync.
### Actual behaviour

6 hours after the first LAN sync after two weeks of slow, intermittent connectivity
(working from home or a distant branch), 2 hours after the server had been updated from 8.2.2 to 8.2.3, many directories disappeared from the client.
The client told the server to delete them, as can be seen in owncloudsync.log.1 and ssl_access.log.
Management starts thinking about an emergency move away from OC to a commercial cloud storage provider.
### Steps to reproduce

Uncertain, as it happens only once a year per OC server.
1. Move the client for two weeks to several locations with slow, intermittent connectivity, away from the server's LAN, connecting though VPN (client appears from different IP source address).
2. Locally change, add, move a few dozen files per day.
3. Shutdown/restart and hibernate/wake up at random times, not looking at the state of synchronization.
4. The day after patch Tuesday March 2016, return to the server's LAN (changes IP address), start client (possibly wake up from hibernation), sync
5. Upgrade server from 8.2.2.2 to 8.2.3.2, without notifying the client
6. Sync again, many directories get deleted.
### Server configuration

Operating system:
Debian Linux 7.9

Web server: 
Apache 2.2.22

Database:
MySQL 5.5.47

PHP version:
5.4.45

ownCloud version:
8.2.2.2 with upgrade to 8.2.3.2 possibly triggering the bug
obtained from http://download.owncloud.org/download/repositories/8.2/Debian_7.0/ using apt-get

Storage backend:
local file system on server-local physical disk (mdraid)
### Client configuration

Client version:
2.1.1

Operating system:
Windows 7 Pro

OS language:
German

Installation path of client:
C:\Program Files (x86)\ownCloud
### Logs

Client and Server are in timezone Europe/Berlin = UTC+1 .
1. F12 log (see https://doc.owncloud.org/desktop/2.1/troubleshooting.html#obtaining-the-client-log-file )
   No useful information , because the deletion event was several days ago and can't be reproduced, but the F12 log only shows current events.

1a. OC client log (owncloudsync.log.1)

```
# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=# Syncrun started 2016-03-10T14:40:53 until 2016-03-10T14:42:32 (98642 msec)
13:42:35|2007|stiftung-gemeinsam/DGD e.V/Unterstützung Lemförde/Budgets 2013|INST_REMOVE|Up|1457617218|56e17942d459f|0|001709955108d43ae0041|4||204|0|0|||INST_NONE|
|0|stiftung-gemeinsam/DGD e.V/Unterstützung Lemförde/Budgets 2013/JA 2013|INST_REMOVE|Up|1447757967|564b089b959b8|0|001710685108d43ae0041|0||0|0|0|||INST_NONE|
|0|stiftung-gemeinsam/DGD e.V/Unterstützung Lemförde/Budgets 2013/JA 2013/2014-03-28 JA_GuV_Haus Waldblick Lemförde_mit Markierung.pdf|INST_REMOVE|Up|1418166000|773b907d5b583e293271e2a25ab7fd0c|125942|001710715108d43ae0041|0||0|0|0|||INST_NONE|
...
```
1. Web server error log:

```
[Sun Mar 06 06:25:14 2016] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u2 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Wed Mar 09 12:37:18 2016] [notice] caught SIGTERM, shutting down
[Wed Mar 09 12:37:19 2016] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u2 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Wed Mar 09 12:45:32 2016] [notice] caught SIGTERM, shutting down
[Wed Mar 09 12:45:33 2016] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u2 mod_ssl/2.2.22 OpenSSL/1.0.1e configured -- resuming normal operations
[Sun Mar 13 06:25:13 2016] [notice] Graceful restart requested, doing restart
```

2a. Web server ssl_access log:

many harmless PROPFIND and occasional PUT commands starting around 09:30

```
192.168.1.193 - Dreher [10/Mar/2016:14:36:52 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1294 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
192.168.1.193 - Dreher [10/Mar/2016:14:37:06 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 30848 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
192.168.1.193 - Dreher [10/Mar/2016:14:37:07 +0100] "DELETE /owncloud/remote.php/webdav/AVR HTTP/1.1" 204 726 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
192.168.1.193 - Dreher [10/Mar/2016:14:37:14 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 30335 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
192.168.1.193 - Dreher [10/Mar/2016:14:37:15 +0100] "DELETE /owncloud/remote.php/webdav/FOM HTTP/1.1" 204 726 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
192.168.1.193 - Dreher [10/Mar/2016:14:37:15 +0100] "DELETE /owncloud/remote.php/webdav/DGD-Forum%202014 HTTP/1.1" 204 869 "-" "Mozilla/5.0 (Windows) mirall/2.1.1"
```

and many more fatal DELETEs.
1. ownCloud server log (data/owncloud.log):

```
{"reqId":"CK3yqFiMUXu9wWR9Vvdf","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.2.2 to 8.2.3.2","level":0,"time":"2016-03-09T11:45:33+00:00","method":"--","url":"--"}
{"reqId":"CK3yqFiMUXu9wWR9Vvdf","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"calendar_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(325): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('calendar_index', Array, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\Router->generate('calendar_index', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/helper.php(66): OC\\\\URLGenerator->linkToRoute('calendar_index', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/util.php(301): OC_Helper::linkToRoute('calendar_index', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/app.php(25): OCP\\\\Util::linkToRoute('calendar_index')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(160): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(141): OC_App::requireAppFile('calendar')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(1171): OC_App::loadApp('calendar', false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(222): OC_App::updateApp('calendar')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(252): OC_Installer::updateApp(Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(509): OC_Installer::updateAppByOCSId('168707')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(323): OC\\\\Updater->upgradeAppStoreApps(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.3.2', '8.2.2.2')\\n#13 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/upgrade.php(213): OC\\\\Updater->upgrade()\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Command\\\/Command.php(253): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(874): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(195): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#17 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(126): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(100): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#19 \\\/var\\\/www\\\/owncloud\\\/console.php(79): OC\\\\Console\\\\Application->run()\\n#20 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":3,"time":"2016-03-09T11:46:31+00:00","method":"--","url":"--"}
{"reqId":"ssJfkvwGTXlPiZhg0xFN","remoteAddr":"192.168.1.193","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"stiftung-gemeinsam\\\/DGD e.V\\\/Unterst\\u00fctzung Lemf\\u00f6rde\\\/Verwaltung\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OC\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('stiftung-gemein...')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":251}","level":4,"time":"2016-03-10T13:41:46+00:00"}
```

**Comment by dragotin** [comment] 2016-03-17 08:09
First, sorry for the trouble you're experiencing here. This is a strange case, and unfortunately very hard to debug.

Probably you do not have a logfile of this happening, or did break the deleting, so that you could restart with logging? 
Have you checked the client if the directories were still present there?

Our problem is: What we see from the logs so far looks like the files were simply deleted on the client. There are circumstances where that is not correct, but it is very hard to find out. Currently I can not think of what could have caused that.

**Comment by guruz** [comment] 2016-03-17 08:31
Are you saying the server-update is a necessary condition for this to happen?

**Comment by martinstutdgd** [comment] 2016-03-17 08:34
I do have the client side logfile, but it started at the very lines I posting, so there is not much to gain by sending the full logfile. I was away for a few days from the office when this happened, and by the time I returned, the log portions before this were gone.
I do have the complete server side logfiles, database, everything, in a backup version which I copied for long term storage in order to be able to restore missing files the lack of which might be detected later.
The user did not deliberately delete or move the directories. The directories were no longer present on the client. The user always uses the local files on the client, never the web interface. I got the emergency call when the user discovered that the files (entire directories) had disappeared on the client.

My idea for mitigating the issue is inspired by issue #4486 : The client will only delete masses of local files after a very clear, conscious, non-automatable confirmation by the user. With an "no" to that confirmation, or no answer, the client must re-send the local files to the server, in order to recover from the deletion, which has been confirmed to be accidental by some other user or a bug or a restore from backup.
The definition of "masses" could be configurable; currently I'd suggest a default of "a non-empty directory or more than one file at a time".

**Comment by martinstutdgd** [comment] 2016-03-17 08:40
I'm not saying that the server update is a neccessary condition. I only mentioned it, because the time of the deletion event and the time of the server update did correlate, so it /might/ have influenced the issue.

**Comment by ckamm** [comment] 2016-03-17 12:08
Note that the patch does not address the problem. It was merely something related we investigated.

**Comment by dragotin** [comment] 2016-09-15 13:24
@martinstutdgd if @ckamm 's suspicion is true, in `.owncloudsync.log` you would find two entries for a specific file or directory which was deleted: The first would have *"INST_REMOVE | Down"* for the file, and later a *"INST_REMOVE | Up"*.

Can you do a `grep INST_REMOVE` in `.owncloudsync.log` and check if you see the two entries for any file?

**Comment by martinstutdgd** [comment] 2016-09-20 09:45
I did a grep, but there were only "INST_REMOVE|Up" entries. There were no "INST_REMOVE|Down" entries.

**Comment by ogoffart** [comment] 2016-10-10 08:42
If this was involving moving directories on the server, it is possibly the same issue as the one fixed in  https://github.com/owncloud/client/pull/5195

Maybe you can try 2.2.4 and see if it still possible to reproduce.

**Closed** 2016-11-07 10:59 UTC
Labels: bug, Needs info, sev2-high
