### ISSUE TITLE
[Windows] Bad UX: "Delete all files" button

### ISSUE THREAD

**Issue by KRens** [owncloud/client#3824] opened 2015-09-13 21:51 UTC
So, my server hdd had crashed...
I got new disks, did a clean install of owncloud, all ok so far.

I then opened my already installed owncloud client (windows 10) and I re-added the new server configuration.
I used the same path as before, containing all my files (locally).
It then started the sync and it asked me whether I wanted to keep my local files or delete them.
I pressed over 15 times to keep my local files.
Then I started typing a message and right when I pressed the spacebar in a sentence, 
the owncloud pop-up appeared asking me whether I want to delete everything or keep my local files.

Sadly the default option was: Delete everything.
So... I lost all my data, on both owncloud and now also locally.
This is super painfull!!!

Suggestions:
- Do not default the question pop-up to delete all files, put the focus on a hidden field or something.
- Why did it ask me over 15 times whether I want to keep my files? Once should suffice.

Fyi: using the latest version of the client and server, updated right before the clean install.

**Comment by guruz** [comment] 2015-09-13 22:41
That sounds indeed bad :-|
We should not have any button default and possibly even add a [x] checkbox.

@ogoffart Why would it show the dialog so often?

@KRens how many sync folders inside the client settings dialog did you have configured?

**Comment by dragotin** [comment] 2015-09-14 10:01
The only thing I can think of is that the deletion of the `sync_journal.db` failed after the user answered "Yes, I want to keep the local data." If we do not detect that properly, that can lead to the delete commands on the server.

**Comment by guruz** [comment] 2015-09-14 11:41
@dragotin As I understand it this is only about the UX, not a bug. He knows he pressed the wrong button because it was marked as default.

**Comment by danimo** [comment] 2015-09-14 11:47
@guruz Read about the 15x part :)

**Comment by dragotin** [comment] 2015-09-14 12:50
@KRens how did you add the new sync folders? Did you use the ownCloud wizard dialog? What I am wondering is: Why did the sync as you if you wanna keep the local files if you went through the folder setup wizard? That one has the radio buttons to decide if you want to keep or remove all files.

**Comment by KRens** [comment] 2015-09-14 21:35
Hi,

The entire experience was very buggy.
I stopped ownclould client, I installed the server clean, 
then I started the owncloud client and he started asking in the pop-up whether I wanted to keep my files.
Then I deleted the account, as it kept on asking me whether I want to keep my files or not.
I then tried to add my account again, but in Windows 10, the entire tab on the left of Activity in settings was missing.
I had to close the app again and open it again and all of a sudden my account was there again, the one I deleted before.

It then started asking me again to keep my files or delete them and then after a few times I pressed spacebar, since it took a while to ask me again whether I want to keep my files.

So:
- small fix: ui
- big fix: fix deleting account, that it is really deleted and does not return after restarting the app
- bug fix: fix deleting account, that the tab does not dissapear and I can add my account again
- major bug fix: do not ask me 15 times whether I want to keep my local files or not. In case of doubt keep them... Do not keep on asking me.

Fyi: my owncloud contains 14 folders.
At first I thought it asked it per folder, but after the 15th time I just got frustrated.

**Comment by ogoffart** [comment] 2015-10-16 09:57
AFAIK it should only show the warning once per folder. Are you sure it asked several time per folders?

I just checked and the default is already "Keep".

I believe that the returning deleted account has been fixed already in 2.0.2

**Comment by ogoffart** [comment] 2015-10-19 08:41
It turns out the default is to delete on windows only.

**Comment by guruz** [comment] 2015-10-19 09:05
What @ogoffart wants to say here: It seems to be a Qt for Windows bug.

Thanks @cdamken for helping testing.

**Comment by ogoffart** [comment] 2015-10-23 15:41
I found one issue in which the SocketAPI kept the DB from being properly removed so the next sync would ask again.

Should be fixed now.

**Comment by guruz** [comment] 2015-10-25 17:35
@Dianafg76 This one needs to be tested on Windows

**Comment by Dianafg76** [comment] 2015-10-26 14:05
I tested this issue, and Is working OK
Desktop v ownCloud-2.1.0.5582-nightly20151026-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}
Closed

**Closed by Dianafg76** 2015-10-26 14:05 UTC
Labels: approved by QA, Design & UX
