### ISSUE TITLE
With certain Linux Desktops: Systray icon bug

### ISSUE THREAD

**Issue by markusbeck-owncloud** [owncloud/client#2123] opened 2014-08-28 17:42 UTC
Hi folks,

I'm using Debian package owncloud-client (1.6.2+dfsg-1) on an Debian Jessie System with XFCE.
Unfortunately I cannot see the systray icon.

Notification Area panel is installed (http://docs.xfce.org/xfce/xfce4-panel/systray). I can hide/unhide the icon there but nothing is visible in the systray.

When is start owncloud from the terminal there is no output. It's running fine.

Any ideas?

**Comment by jbiddy** [comment] 2015-03-27 01:54
I'm going to throw in my experience here. I'm trying to use the ownCloud Client on Bodhi Linux 3.0. It uses e19 with Xembed support removed (it will be gone from e20 entirely). My understanding is that Xembed is a dying protocol. Hopefully I'm not offending anyone by saying this, but might ownCloud be coded to use libappindicator instead sometime soon?

**Comment by jospoortvliet** [comment] 2015-03-27 11:18
@jbiddy Qt 5 supports this and it works. You might have to install qt-sni - depending on your distribution. Bodhi should offer that, if it doesn't - do a feature request to them.

So, if you have Qt 5 and ownCloud Client 1.8 and a up to date distribution, this works perfectly fine. I'd close this issue - if it doesn't work it is a distribution problem.

**Comment by hefee** [comment] 2015-03-28 11:40
>So, if you have Qt 5 and ownCloud Client 1.8 and a up to date distribution, this works perfectly fine. I'd close this issue - if it doesn't work it is a distribution problem.

@jospoortvliet: what you mean with with current qt5 and up to date distro?
Tried:
oCC 1.8.0 
Qt 5.4.1
that are IMO up to date but still no systray in GNOME [debian #781368](https://bugs.debian.org/781368#28)

**Comment by jospoortvliet** [comment] 2015-03-28 19:01
@hefee if you use GNOME 3.x, the 'old' systray should work, I'm quite certain the ownCloud Client supports that still as it works on my desktop too. It is possible that GNOME Shell has dropped that - no idea, to be honest.

There is also a new systray specification that is supported by Unity and Plasma 4 and 5 but unfortunately the GNOME developers invented a third wheel. Complain to them about supporting Status Notification Items...

http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/

**Comment by ogoffart** [comment] 2015-07-17 12:36
Qt 5.5 should now have support for the dbus protocol

**Comment by danimo** [comment] 2015-07-17 12:38
@ogoffart but that's not really helping, is it? It will be a solid two years before Qt 5.5 has arrived on a majority of Linux Desktops.

**Comment by guruz** [comment] 2015-07-20 10:59
@ogoffart Would it be an option to ship Qt with the oC client on Linux like it is done on Windows and OS X?

;-)

**Comment by ogoffart** [comment] 2015-07-20 12:23
@guruz why are you asking me that?

**Comment by jospoortvliet** [comment] 2015-07-20 13:39
@ogoffart he's screwing with you.

**Comment by voxspox** [comment] 2015-07-21 10:37
I'm using Linux Mint (Ubuntu based) with Cinnamon window manager (Gnome based). The ownclowd-client icon does not appear on startup, while the synchronization is running and I can see the process. Restarting owncloud is a workaround for me. Type into Terminal:

    $ killall owncloud
    $ owncloud &

**Comment by pecuna** [comment] 2015-09-17 16:31
Owncloud version 2.0.1
OS: Ubuntu 14.04.3 Gnome LiveCD with persistent file
The icon disappears after while and after that I have to open the client via menu but after closing the client via the Close button  the tray icon is gone too, again.

**Comment by RalfJung** [comment] 2015-10-06 17:40
I am having this issue as well: After logging in, there is no icon for the ownCloud client, just a window popping up informing me about the sync state. I just killed the owncloud process and started it again, which made the icon appear.

This is with Qt 5.5 on Debian testing, using Cinnamon as my desktop.

**Comment by jospoortvliet** [comment] 2015-10-26 16:02
@RalfJung sounds like a timing issue: cinnamon is too slow letting the systemtray be started, ownCloud is then already up and running. File a bug with Cinnamon to delay starting apps until they are sure the systemtray is available...

**Comment by jospoortvliet** [comment] 2015-10-26 16:02
GNOME also has a rather broken systemtray so that might be the problem, rather than anything in ownCloud @pecuna

**Comment by ogoffart** [comment] 2016-03-29 10:44
We are using the QSystemTrayIcon and it gets better with newer Qt version.

This particular bug report contains information about many desktop and many qt version and is old and no longer usefull.
Please reopen a new issue if there are still problem with Qt 5.6, but make sure that you specify the exact Qt version, the version of your window manager/shell, and what the problem is.

**Closed by ogoffart** 2016-03-29 10:44 UTC
Labels: bug

**Comment by adrianvg** [comment] 2016-05-16 11:13
This is still a problem. Using latest available Owncloud Desktop sync client v2.2.0 build 1605 on Ubuntu Desktop 14.04 x64 LTS.
Also using Mate DE, instead of the standard Unity.

**Comment by danimo** [comment] 2016-05-16 11:16
@adrianvg This is a regression in the v2.2.0 builds (as they have been build against Qt5 accidentially). We will fix this in the coming days.

**Comment by DamianAxiamo** [comment] 2016-05-17 05:47
Confirmed still a problem under Ubuntu 14.04 LTS with owncloud-client build 1605. Notification icon is on the left side. Maximized windows can not be closed since the icon covers the close button "X" of window manager.
Looking forward to the fix
