### ISSUE TITLE
[Gnome] Allow users to remove the tray icon

### ISSUE THREAD

**Issue by ainola** [owncloud/client#3089] opened 2015-04-10 02:08 UTC
Gnome 3.16 is trying to kill off the icon tray (for good reason). I don't use the tray and would prefer owncloud to not show up, as the inability to remove it has caused the temporary 'shelf' paradigm in Gnome 3.16 to show up.

In my use case, I don't need nor care about owncloud's icon and it provides nothing but a distraction to me. Of course there is some value to certain users having a quick glance to the status of owncloud... but it's sitting there as a daemon to sync my stuff. If it needs my attention, it sends a notification. So any extra information is just clutter.

**Comment by jsparber** [comment] 2015-04-10 20:55
+1

**Comment by Pwnd0you** [comment] 2015-04-11 17:12
+1

**Comment by pszypowicz** [comment] 2015-10-17 17:57
+1

**Comment by minils** [comment] 2015-11-06 13:11
+1

**Comment by guruz** [comment] 2015-11-09 14:12
Note that the major platforms (Windows, OS X, other Linux desktops) still use tray icons.

It would therefore be nice if you guys could clarify what Gnome uses as an alternative then and what application developers are supposed to do.
Bonus point if you come up with patches https://owncloud.org/contribute/

**Comment by jancborchardt** [comment] 2015-11-09 14:33
@allanday as we talked about this at GUADEC: Can you answer @guruz’s questions on this? How should we do it with the ownCloud sync client to make it compatible to GNOME?

**Comment by danimo** [comment] 2015-11-09 14:43
> Gnome 3.16 is trying to kill off the icon tray (for good reason)

So far nobody has convincingly explained to me as to why this is a good reason. Its a unilateral choice made by GNOME that users suffer from as it is being killed without offering good alternatives.

We do not have time to reinvent the GUI for every Window Manager. Just because GNOME decides to overthrow the UI without offering sensible alternatives doesn't mean we can adjust to it. Multiple UIs  result in more code. More code creates more liability.

That said, some KDE guys are working towards creating a desktop dependent UI (https://github.com/owncloud/client/pull/3975), which might allow to eventually use a more integrated approach, but that's not on our plate unless someone commits to actually doing it. For KDE we have volunteers. As long as noone steps up for GNOME, we will have to use the same UI as everwhere else.

**Comment by jancborchardt** [comment] 2015-11-09 14:53
> So far nobody has convincingly explained to me as to why this really is a good reason, outside of design ivory towers. Its a unilateral choice made by GNOME that users suffer from as it is being killed without offering good alternatives (exhibit a: every systray using currently installed on my machine, from Dropbox to Spotify).

Just to explain that, @ainola basically provided a good short reasoning: »If it needs my attention, it sends a notification.« Most of the time the green checkmark will show anyway.
And for Spotify and Skype etc the tray icons are mainly shortcuts to the apps, with some extra functionality (which in the case of GNOME is done via the dash).

The alternative for file sync mechanisms would be better integration into the desktop file manager. For example being able to filter Favorites, Shared files, Recent etc on the desktop, via entries in the sidebar of the file manager. I heard OS X and Dropbox are working on something like that already.

**Comment by danimo** [comment] 2015-11-09 14:56
@jancborchardt How would I notify the user that

* The server is unavailable
* There are some issues with the network preventing the client from sync

in a non-fire-and-forget fashion (as todays notification). An icon makes that absolutely clear, and many customers have stressed that they consider it absolutely vital that the status of sync process is visible in every moment. You might not have a file manager open, or visible, at any given point in time.

**Comment by danimo** [comment] 2015-11-09 15:07
Here is my problem: This ticket basically asks for a solution for a short-term problem by asking for long-term changes. So I need _realistic_ proposal. If we we can do "better" than a system tray.

I realize, and even to some extend agree, that removal of "clutter" is the eternal zen of design, but given that syncing can be unexpectedly surprising (even though this is improving a lot with 2.1 syncing more files than before in conjunction with 8.2), removing a permanent status indicator gets us back to more issues of type "WHY WERE MY FILES NOT SYNCED?!", which I think is much more desasterous to a file syncing solution.

**Comment by ainola** [comment] 2015-11-09 15:20
I know for me that I don't care about having any icon, simple as that. The tray in GNOME is only there for legacy comparability. If I need to use the owncloud dialogue I will call it up in the dash...

**Comment by jancborchardt** [comment] 2015-11-09 15:22
@danimo I’m only stating the message, not defending the solution.

I would recommend that we wait for @allanday’s answer on what @guruz asked above. Further discussion is mostly a waste of time.

**Comment by ainola** [comment] 2015-11-09 15:28
The notifications stick around if missed. 

But it's clear yiu don't give a fuck. Just close the bug already.

**Comment by suy** [comment] 2015-11-09 15:50
> But it's clear yiu don't give a fuck. Just close the bug already.

Please, be respectful if you want to be taken seriously.

I see the problem is this: Say that for whatever reason Apple removes tomorrow the icons in the menu bar (which is the equivalent feature). Application developers still have the possibility to make the application icon in the Dock to bounce, or show a progress bar or a badge (in addition to the notification system). You say the alternative on GNOME is the Dash, but what API it exposes?

**Comment by dragotin** [comment] 2015-11-09 16:07
@ainola I can not see why you need to come up with negative reaction here, yet it's not the first time I experienced this kind of reaction from people from the GNOME team, unfortunately.

I suspect, if you guys remove the tray icon because you decide that it's not useful any more, you come up with patches or at least suggestions on how to solve that for the projects that make use of it. 

FYI, we have never heard  from users that the tray icon is superfluous so far, but when we had the tray icon lost because of an error long time ago, people were speaking up massively.

**Comment by jancborchardt** [comment] 2015-11-09 16:16
@dragotin

> yet it's not the first time I experienced this kind of reaction from people from the GNOME team, unfortunately.

I suspect @ainola is simply a GNOME user. It’s completely uncalled for to badmouth the GNOME team here as we have a very good working relationship I’d hate to see tarnished by trifle such as this.

**Comment by dragotin** [comment] 2015-11-09 16:21
well, well, yes, of course.

**Comment by ainola** [comment] 2015-11-09 16:22
I had unsubscribed but just got pulled back in. Kindly don't call my name back in. 

I am both a gnome user and an i3 user. I don't want the icon on either of my environments. I'm just tired of danimo treating every request like it is moronic. The man is toxic.

**Comment by ainola** [comment] 2015-11-09 16:27
I will also point out that if you don't want to support the feature, fine. I don't care. Just close the bug stating that it's not in your design decision and we are too small a minority. That seems like a logical conclusion.

**Comment by guruz** [comment] 2015-11-09 16:28
@ainola I think @danimo is more intoxicating than toxic

![if-you-know-what-i-mean-127](https://cloud.githubusercontent.com/assets/959327/11039253/ffc772b0-8706-11e5-8c30-5523ada7dad4.png)

**Comment by ainola** [comment] 2015-11-09 16:37
That was very polite of you, @guruz. So does everyone that works on ownCloud behave like this? I happen to think that KDE is the most hideously designed piece of garbage on the planet yet I don't admonish users/devs solely because of their affiliation of the community. Does everyone routinely ridicule feature requests or even reports showcasing massive deficiencies in the program?

I'm amazed this project took off at all.

**Comment by LukasReschke** [comment] 2015-11-09 16:38
Be all nice guys. Just a friendly reminder of our Code of Conduct: https://owncloud.org/community/code-of-conduct/

**Comment by JumpingSpottedTiger** [comment] 2015-11-09 16:57
Hi, in your purging of all of my comments you didn't retain the fact that I'm an i3 user as well and don't want the icon.

I'm perfectly capable of managing my owncloud by myself without needing a win95-style icon. Notifications keep me aware of what's happening.

**Comment by danimo** [comment] 2015-11-09 17:45
@JumpingSpottedTiger Duely noted, and an important point. Unfortunately, everything in the client depends on the system tray representation right now. Changing that is requested in #2002, which would essentially mean creating a per-user daemon, which frontends could connect to. However, this is not on the short term agenda.

Also, as I mentioned notifications are difficult as they are purely informational, and cannot be dismissed. Alas, this could be solved once there's a separation between a daemon and the GUI. I'd therefore propose we close this ticket in favor of #2002.

**Closed by danimo** 2015-11-09 17:45 UTC
Labels: Design & UX, Needs info, Platform Specific

**Comment by allanday** [comment] 2015-11-10 11:01
> @allanday as we talked about this at GUADEC: Can you answer @guruz’s questions on this? How should we do it with the ownCloud sync client to make it compatible to GNOME?

Hey Jan, thanks for reaching out! Obviously you can display a status icon in GNOME 3 today. However, we consider this to be legacy functionality and encourage applications to port away from using a status icon wherever possible.

My design recommendations would be:

 * Use notifications to alert the user of relevant events (guidelines are here: https://developer.gnome.org/hig/stable/notifications.html.en).
 * Each time the ownCloud app launcher is activated, the window should be displayed (I think you do that already, which is great).
 * Ensure that it's possible to do everything that you could do through the status icon through the window also (I'd say this is good practice anyway, tbh).
 * The first time the window is dismissed, you might want to show a confirmation dialog, which asks if it's OK to keep running after the window is closed (again, probably good practice).
 * Don't show the status icon by default under GNOME.

In addition to this, we're also piloting a D-Bus API that will allow cloud providers to integrate more closely with the file manager (as well as open/save dialogs). We would love to hear your feedback on this, particularly if there is anything missing from the API that you think you'd need. More details can be found here:

https://wiki.gnome.org/Projects/GTK+/CloudProviders

Thanks again; let me know what you think in general!
