### ISSUE TITLE
Client  finds symlinks that do not exist

### ISSUE THREAD

**Issue by The9Cat** [owncloud/client#9421] opened 2022-02-05 16:11 UTC
Client reports symlinks that are **not** present.   These always take the form of: `directory/.#somename` where `somename` is a _real_ file in the directory.  There are no such symlinks.  See pasted image below for an example.

In fact, there are no symlinks in the entire owncloud directory checked with: `ls -lR ./ownCloud | grep '^l'` which produces no output.

![image](https://user-images.githubusercontent.com/25960766/152649302-3a7e857b-066d-4401-85da-35af9e7028fd.png)

### Server configuration
Operating system: Ubuntu 20.04

Web server: Server version: Apache/2.4.41 (Ubuntu)

Database: mysql

PHP version: 7.4.3

ownCloud version: 10.9.1.2

### Client configuration
Client version: 2.1.0 build 6519 Jan 22 2022

Operating system: Ubuntu 20.04 LTS

Qt version used by client package (Linux only, see also Settings dialog): 5.12.10

Client package (From ownCloud or distro) (Linux only): owncloud-client

Installation path of client: /usr

**Comment by The9Cat** [comment] 2022-03-08 00:52
This is not a problem that inhibits functionality, but there is something wrong here.  Perhaps it's not important enough for anyone.  Sigh.

**Comment by TheOneRing** [comment] 2022-03-08 09:30
We don't clear errors for non existing (removed) files, at the moment.

**Comment by The9Cat** [comment] 2022-03-08 17:43
Okay, thanks.  The strange thing is that those links _never_ existed.  They appear to be similarly named as emacs save files.  But: emacs save files are prefixed by # (not '.#') and emacs save files are not symbolic links.   The app is working correctly otherwise, I believe.

**Comment by TheOneRing** [comment] 2022-03-09 13:43
Duplicate of https://github.com/owncloud/client/issues/9236

**Closed by TheOneRing** 2022-03-09 13:43 UTC
Labels: bug
