### ISSUE TITLE
Linux/Ntfs: files with more than 12 characters are being ignored

### ISSUE THREAD

**Issue by chritallic** [owncloud/client#1143] opened 2013-11-05 22:53 UTC
It seems to me that whenever I am trying to upload files from a ntfs partition that have been created under Windows and that have more than 12 characters in their file name they are being ignored.

Steps to reproduce:
1. Create files on a ntfs partition with more than 12 characters on Windows
2. Mount the partition under linux 
3. Use it as the destination for the ownCloud sync

I have been testing the exact same directory under windows multiple times now and it always works. Basically, when I use Windows all the files are being uploaded and as soon as I switch to my linux distribution all the files with more than 12 characters are being ignored and removed from the database.

So for example, if I copy a file called St_Andrews.pdf to my sync folder, I get the following log results:
1. Windows (not the first commit):
10-25 14:16:31:520 csync_vio_stat: Win32: STAT-inode for D:\Documents/St_Andrews.pdf: 127727
10-25 14:16:31:520 csync_ftw: Uniq ID from Database: St_Andrews.pdf -> 5269d8c2f1878
10-25 14:16:31:520 csync_walker: file: D:\Documents/St_Andrews.pdf
10-25 14:16:31:520 _csync_detect_update: ==> file: St_Andrews.pdf - hash 10067475438630831692, mtime: 1330587053
10-25 14:16:31:520 _csync_detect_update: Database entry found, compare: 1330587053 <-> 1330587053, md5: 5269d8c2f1878 <-> 5269d8c2f1878, inode: 127727 <-> 127727
10-25 14:16:31:520 _csync_detect_update: file: St_Andrews.pdf, instruction: INSTRUCTION_NONE <<=
2. Linux: 
10-25 14:17:58:500 csync_ftw: Uniq ID from Database: St_Andrews.pdf -> 5269d8c2f1878
10-25 14:17:58:500 csync_walker: file: /home/chritallic/data/Documents/St_Andrews.pdf
10-25 14:17:58:500 _csync_detect_update: ==> file: St_Andrews.pdf - hash 10067475438630831692, mtime: 1330587053
10-25 14:17:58:500 _csync_detect_update: file: St_Andrews.pdf, instruction: INSTRUCTION_IGNORE <<=
3. Windows again: 
10-25 14:21:00:362 csync_vio_stat: Win32: STAT-inode for D:\Documents/St_Andrews.pdf: 127727
10-25 14:21:00:362 csync_ftw: Uniq ID from Database: St_Andrews.pdf -> <NULL>
10-25 14:21:00:362 csync_walker: file: D:\Documents/St_Andrews.pdf
10-25 14:21:00:362 _csync_detect_update: ==> file: St_Andrews.pdf - hash 10067475438630831692, mtime: 1330587053
10-25 14:21:00:362 csync_statedb_get_stat_by_hash: No result record found for phash = 10067475438630831692
10-25 14:21:00:362 _csync_detect_update: file: St_Andrews.pdf, instruction: INSTRUCTION_NEW <<=

I am using the ownCloud client 1.4.1 from the ownCloud opensuse.org repository under Fedora 19 (kernel 3.11.6-200.fc19.x86_64, selinux enabled, ntfs-3g 2013.1.13). I am also using the same ownCloud version under Windows.

**Comment by Morganlej** [comment] 2015-02-10 23:19
I experience this intermittently too, client 1.7.1 on Mageia5 when syncing to Win7 pro D: ntfs partition.  Damn!

This is with two files amongst many other different versions originally generated on a program running in WinXP on a VM on my workstation.  Short names, no strange characters (not even swedish ones).  
I detected it as i am syncing same folder from both linux and windows ( with a trick, forum.owncloud.org/viewtopic.php?f=14&t=19672&p=78867#p78867 )
## Tracking down...
**First, worth a read** : http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html#backgrounders and http://en.wikipedia.org/wiki/Hard_link

Initially the folders was empty on the affacrted computer, and the initial download from server was with the linux client.
I see in the logs that it say it downloaded those files like it downloaded the others, and no error.
When rebooted to Windows 7 i set up the client there and it verified all hundreds of files except two, that it downloaded.
Booting back to linux, the linux client now about those two files say it can not sync hard links.

And using ls - i see for these two files they have count=1
*(actually all normal "files" are hard links to their stored content, and when you say you make a hard link to a file you just make another pointer - a different name - to same content, and a counter at that content location get increased for each new pointer/name you label that data with.  All such pointers/hardlinks mean the same physical storage location on disk.  When you have deleted all pointers the count is zero and file get deleted.)*

So what happened here really??
I decided to look at windows side.  As normal not much tools are in standard install, but i found and installed this nifty utility: http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html

According to that add-on, the files in question are as seen from Windows not hard links (no link icon, so count=1 i presume; test: when i make a hard link toa test file both instances get an icon)
As a test i deleted one of the files using Explorer.  And rebooting to linux i saw it got deleted on linux side.  So obviously the windows ntfs driver was sure there was no other pointer to that data.   As another test i made a hard link using the named utility in explorer, and the file also on linux shows coint=2, so that works, and i see in log owncloud see both instances as hard links. After i deleted one of them (in Dolphin, linux) there are only one and OK with owncloud.

Another test: on the other file that owncloud and ln -l saw had count 2 ("a hard link") i let dolphin search for that file name in the whole ntfs file system but it only found one.
Now... theoretically the other link to that same content may have another name, so what i would really would like to do is to see if there exist another filename pointing to the same storage.  I am not wizard enough to do that.

I checked the ntfs using ntfsresize (with --no-action) and it did not find any problem.
Running windows online check from the properties dialog for D: also find nothing.

To me it looks like it is something about ntfs-3g.
But then there should be many reports of it spread on the 'net and i find nothing related.  Can you?
So maybe it get triggered by some special case, where one component is owncloud-client?

*Rant: Well i abandoned Windows years ago because XP fouled up its own ntfs several times, and now ntfs-3g seem to take over that role? There are still two old windows programs i really must run natively...  AAArgh!  /Rant*

## Workarounds
Avoid writing using ntfs-3g. Instead for the shared filesystem use:
### FAT32
Hope there is not another can of worms.  But at least there can not be links ;) *
### ext3
Mount it in windows using a driver microsoft neglect to ship with windows https://www.google.com/search?q=mount+ext4+partition+in+windows . reading th echangelogs it is safer to stay with ext3; extents are oftennot supported fully yet on what i found. In that case i need one extra partition (i have windows swap on D:) and no i do not want to expose my linux home partition to windows ecosystem of viruses and potential driver messups.   Long live gparted !  However FAT32 seem more safe for read/write from windows than some odd add-on driver - especially if that driver should behave with owncloud like ntfs-3g do.  ;)
## Track further!
It seem to be reproducible, so we should notice ntfs-3g developers, and maybe they can track further together with owncloud developers.
**I leave it to owncloud developers or someone else to push**
#### My set up
ntfs mount line in fstab: /dev/sda5 /media/win_d ntfs-3g soft,uid=myname,gid=users,umask=0022 0 0
ntfs-3g 2014.2.15-4.mga5  kernel-desktop-3.19.0-0.rc7.3.mga5
Disk is a modern SSD.  64 bit dual core intel (Thinkpad T61p)

**Comment by rienesl** [comment] 2015-02-11 08:30
I did extensive research in the last month and I can 100% reproduce it now:
Boot windows, create a file in your Owncloud-Folder (no owncloud-client instaled in windows), reboot to linux, let the sync run.
If your file was created in 8.3-Format, everything will run smooth.
If your file leaves the 8.3-Format in any way, the error will occure.
Move your problem-file to extX and back: the error is gone

**Comment by Morganlej** [comment] 2015-02-11 09:52
@rienesl in your owncloud log, can you see if it immediately see it as a hard link, or if it tries to up/download it first?

#### Looking at my log again i note:
* The two files that had the problem are the two last in a sync.  Coincidence or part of error trig?
* On next synk more files was downloaded, all got down OK (and more than hundred have long names)
* Following syncs run ok (still on linux) - it do not see any download (so it sees all files) nor "hard link" 
* Rebooting to windows, that client first sync thinks the two last files in first sync from linux client are missing.
* Following syncs from windows client are OK.
* Rebooting to linux, that client finds those files are "hard links"

So like your test show windows need to be part for the error to occur.
There seem to be two problems:
* windows do not see the file the linux client wrote and can see
* when windows write the file, linux see count=2 meaning it is a second link to same content and maybe that is true, depending on what windows actually did...

#### Testing without owncloud; clients not running;
On windows created a long name file -> on linux count=2
On Windows copied an existing long name file -> on linux count=2
Looking at my windows C: from linux i see all long filenames have count=2, while short without special characters have count=1 (except some windows programs such as notepad.exe have more count; true hard links i presume)

##### SO
ntfs-3g interpretes files with long names as being "hard links"
OH WAIT...! maybe that is not wrong?  IIRC microsoft ntfs have this hack that files with long name also have a short name? So when a windows app stores a file with long name, what happens under the hood is that it is stored as two names pointing to the same content?
But ntfs-3g only stores the long name?

##### So what to do about it ?
* can windows be set to only use long names ?
* can ntfs-3g be set to emulate count=0 ?
* can owncloud client be set to not test for hard link ?

... still it do not explain why windows did not see two of the fles that ntfs-3g wrote se there is yet another error anyhow...

*The system must go in production use today, so now i will format to FAT32 and so i end my tests.*

**Comment by rienesl** [comment] 2015-02-11 18:13
@Morganlej:
Yes, owncloud sees it imediately as a hardlink. No sync possible (retry, restart, whatever), until I moved them to an extX partition. I don't have a windows-ownclowd-client, so further testing about "waht if windows syncs" is not possible.
But downloading a file from the cloud to the computer never makes any problems (long or short names), only uploading makes trouble. But what you wrote is consistent with the therory above: Your windows-owncloud-client downloaded the files, so windows created them. Then you reboot to linux and voila: Problem as expected.

**Comment by jpandre** [comment] 2015-02-12 12:54
> ntfs-3g interpretes files with long names as being "hard links"

It actually interprets a file with a short name AND a long name as a file which has two names.

> OH WAIT...! maybe that is not wrong? IIRC microsoft ntfs have this hack that files
> with long name also have a short name? So when a windows app stores a file with
> long name, what happens under the hood is that it is stored as two names pointing
> to the same content?

Yes. For instance my "Program Files" directory is also named "PROGRA~1" :

[linux@precision ntfs]$ ls -ldi "/win10/Program Files" "/win10/PROGRA~1"
61 drwxr-xr-x 1 root root 4096 Dec  6 16:16 /win10/PROGRA~1
61 drwxr-xr-x 1 root root 4096 Dec  6 16:16 /win10/Program Files

Both names are associated with the directory whose inode is 61.

> But ntfs-3g only stores the long name?

Yes, it complies with Posix, and behaves like ext2/ext3/ext4

> can windows be set to only use long names ?

Yes, see http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_files/file-system-interoperability-in-multiple-boot/73992e8f-0810-4766-96e5-7634808fb97a

> can ntfs-3g be set to emulate count=1 ?

The short names were inserted on purpose and ntfs-3g is designed to report what is on disk.

> can owncloud client be set to not test for hard link ?

I would expect files with multiple names not to be ignored. On Windows 8 there are files which have up to eight names.

**Comment by jpandre** [comment] 2015-02-12 13:05
Sorry, wrong reference above for disabling the creation of short names. This should be :
http://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/fsutil.mspx?mfr=true

**Comment by Morganlej** [comment] 2015-02-12 14:26
Thank you @jpandre - great to have windows sawy people here :)
That link was for XP. Win7 have a tad more options: https://technet.microsoft.com/en-us/library/ff621566%28v=ws.10%29.aspx
I will read up and try again to dualboot sharing on same dir on ntfs soon.

**Comment by rienesl** [comment] 2015-02-12 19:12
@jpandre: Thank you for joining us here. So now we know, that this problem is not caused by NTFS-3G, but by the way owncloud handles the returned information. So I guess there is a need of change in that part of code.

**Comment by danimo** [comment] 2015-02-12 19:58
> @jpandre: Thank you for joining us here. So now we know, that this problem is not caused by NTFS-3G, but by the way owncloud handles the returned information.

It's not so simple really: hard links break the fundamental design of the sync algorithm: That one file is represented by exactly one inode. This is because a file name is not sufficient to uniquely identify its contents, and detect e.g. moves properly (inotify is not reliable enough, plus it does not track offline moves).

> This is why the client ignores all regular files with a link count > 1 (directories are an obvious exception). I would expect files with multiple names not to be ignored. On Windows 8 there are files which have up to eight names.

We can always optimize on Windows, if Win32 API exists. However, I don't see what we can do for POSIX (such as Linux) filesystems, for the reason explained above.

**Comment by Morganlej** [comment] 2015-02-12 20:21
I told windows7 not to create 8dit3 names, and it seem to work :)
I am now back on ntfs for dual boot sharing.  It need more tests but right now it seem OK...
I updated at the bottom of my post:
http://forum.owncloud.org/viewtopic.php?f=14&t=19672&p=78867#p78867

**Comment by rienesl** [comment] 2015-02-13 08:22
> hard links break the fundamental design of the sync algorithm: That one file is represented by exactly one inode. <
How about a solution like: If count=2, check if one of them is 8.3, if yes, take the other one (name) for sync, else behave like before? Switching off 8.3 names is one thing, but I can imagine, that there might be reasons, why this stoneage relict is still active.

**Comment by danimo** [comment] 2015-02-13 08:23
@rienesl and how would one reliably know that this is really the 8.3 representation?

**Comment by rienesl** [comment] 2015-02-13 08:28
For long filenames, the first 6 characters are equal to the file name, followed by a "~" and a number.
For files using spaces or non basic ASCII (7bit) characters in the first 6 of them, it might get difficult, that's right. But I guess, there exist a whitepaper from microsoft, how the short names are produced. I think it will be possible to create a filter based on those informations

**Comment by Morganlej** [comment] 2015-02-13 09:02
If we go just by the name, how can we be sure it is not a, program or user that happened to create two names which match that simlilarity?

How do we handle if a file is renamed?  I do not know the details - it probably virtually never happens, but i what if something renamed the 8dot3 name? 

This stoneage relict is needed on the MS windows system partition, but many recommend to shut it of for other partitions for performance reasons.

IMO we should not bother more than the error message could include a note about that possibly that partition use 8dot3 names. And leave it up to the admin to disable the stoneage compatibility and clear the files.

Files on the windows system partition can then not be synced from a linux client unless the admin turn off 8dot3 there too.  It is possible to do while keeping the already existing 8dot3 names, but it may brake future installs by stoneage installers or such.  But leave that to the local admin.

It is not up to owncloud to solve an old microsoft hack induced incompatibility. (I agree it would be convenient though)

**Comment by rienesl** [comment] 2015-02-13 09:24
Got the Whitepaper: http://www.osdever.net/documents/LongFileName.pdf
It it, the first 2 of your questions are answered - the guys of Microsoft hat had the same "problems" while creating this standard.
Showing an error message is nice for an intermediate solution, but the behaviour is no old hack for induced incompatibility, Microsoft defines this as part of the standard for long filenames!
Sadly I'm not that experienced in coding, so I'm not able to solve it myself. But maybe someone agrees with me and helps here. Maybe...

**Comment by ogoffart** [comment] 2015-07-01 12:32
Duplicate of #3241

the verision 2.0 of the client should bix this problem.

**Closed by ogoffart** 2015-07-01 12:32 UTC
Labels: Discussion
