### ISSUE TITLE
Sync failing, asking for permissions

### ISSUE THREAD

**Issue by puggan** [owncloud/client#2761] opened 2015-02-01 19:16 UTC
OS: gentoo
Client: net-misc/owncloud-client-1.7.1

After succesfully adding a file. (the file is both in my local folder, and on server).
The client started to complain about permissions:
![owncloud_sync_error](https://cloud.githubusercontent.com/assets/866668/5993357/4e479960-aa4e-11e4-8310-feac5cc55fb6.png)

Is it localy or remotly it complains about?

It may be related that the file is shared twise.
user "root" shares "Publika filer" with read only permissions,
and also shares "Publika filer/Utskott/KUT" with edit permissions to memeber in the group "KUT" (me included).

**Comment by ogoffart** [comment] 2015-02-02 15:40
Hi, this error normaly states that yuo are trying to add a directory within a read-only directory.
In other words, that you created (or copied) a directory on on the client within the shared directory that was supposed to be read only.  Of course in that case you are not allowed to do that, and to resolve the error you ened to remove that directory or move it somewhere else.

If that's not the case and you should be allowed to write in that directory, please provide the log so we can study what the problem is.

**Comment by puggan** [comment] 2015-02-02 18:45
a few rows that look relevant:

    02-02 19:37:15:662 0x147a5e0 _csync_merge_algorithm_visitor: INSTRUCTION_NEW       dir: Publika filer/Utskott/KUT/protokoll
    02-02 19:37:15:688 0x147a5e0 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "Publika filer/Utskott/KUT/protokoll" 2 "Not allowed because you don't have permission to add sub-directories in that directory" 
    02-02 19:37:15:705 0x147a5e0 -> SyncEngine finished without problem. 
    02-02 19:37:15:707 0x147a5e0   ** error Strings:  ("Publika filer/Utskott/KUT/protokoll: Not allowed because you don't have permission to add sub-directories in that directory") 
    02-02 19:37:15:708 0x147a5e0     * owncloud csync thread finished with error 
    02-02 19:37:15:708 0x147a5e0 the last 1 syncs failed 

complete log at http://pastebin.com/RsgwcTbA

**Comment by puggan** [comment] 2015-02-02 18:52
the folder
root:"Publika filer" is shared readonly, as puggan:"Publika filer"
root:"Publika filer/Utskott/KUT" is shared with edit permission, as puggan:"KUT"

I added the folder "protokoll" in one of thous locations:
puggan:"Publika filer/Utskott/KUT/protokoll" or puggan:"KUT/protokoll", can't remember now.
the folder was made at the server at root:"Publika filer/Utskott/KUT/protokoll", and syncked back to the other of 2 locations above, and the client started to complaing about the permission.

**Comment by ogoffart** [comment] 2015-05-21 12:58
Maybe related to owncloud/core#16492.

**Comment by ckamm** [comment] 2015-05-27 11:19
I can reproduce this:
* Share foo/ read-only and foo/bar/ read-write with user.
* As user, add folder fib to bar/.
* It gets synced correctly.
* It eventually gets downloaded again as foo/bar/fiib/
* The client complains that one does not have permission to add new folders there ("Not allowed because you don't have permission to add sub-directories")

It works fine with a new file.

**Comment by ckamm** [comment] 2015-06-04 12:50
This is what happens:

* In the first sync the new folder bar/fib/ is uploaded correctly.
* In the next sync, the new remote folder foo/bar/fib/ is detected and marked as EVAL_RENAME. But it gets reduced to NEW in csync_reconcile.c:183 (because !other).
* This leads to a local mkdir being run. But should_update_etag is false and the LocalMkdir propagator job does not touch the db - so the new folder isn't inserted into the database.
* A third sync tries to upload foo/bar/fib/ and (correctly) fails due to permissions.

@ogoffart I think we should set should_update_etag in the mentioned location of csync_reconcile. During update phase we do that for all dirs that are EVAL/NEW. Here we effectively add a new NEW directory without setting that flag.

An alternative would be to make PropagateLocalMkdir always update the database. What do you think?

**Comment by ogoffart** [comment] 2015-06-17 08:04
Yes, i'd say that the PropagateLocalMkdir should always update the database.

**Comment by ckamm** [comment] 2015-06-17 08:37
@ogoffart Thanks, I also prefer that. It's much easier to reason about than the long-range effect of should_update_etag.

**Comment by ogoffart** [comment] 2015-06-17 09:02
Sorry i was wrong, we must not write the etag in the PropagateLocalMkdir.
Otherwise, if the sync aborts before we downloaded everything, we will not recurse in that directorynext sync.

**Comment by ogoffart** [comment] 2015-06-17 09:19
The PropagateLocalMkdir could create the entry in the database with a dummy etag: (we use the '_invalid_' etag in other places too)

**Comment by ckamm** [comment] 2015-06-17 10:27
The main patch that fixes the issue is in master, I'll prepare a patch to implement @ogoffart's suggestion with the dummy etag later.

**Comment by Dianafg76** [comment] 2015-07-09 13:51
I tested this issue, and is working fine.
Desktop v ownCloud-2.0.0.5255-nightly20150709-setup.exe

**Closed by Dianafg76** 2015-07-09 13:51 UTC
Labels: bug, ReadyToTest

**Comment by rajohn96** [comment] 2016-11-10 23:40
Hello, I am having a similar problem with select files/folder experiencing this same sort of problem. The user has complete read/write to all file locations, but in some cases I am seeing errors of the form:

"Not allowed because you don't have permission to add subfolders ..."
"Not allowed because you don't have permission to add parent folder"
"Not allowed because you don't have permission to add files in that folder"

This is running latest client (Windows) against server build 9.1.1-1 for ReadyNAS.

Thanks!

**Comment by guruz** [comment] 2016-11-15 08:50
@rajohn96 Are you sure you didn't get that folder shared read-only to you?
I suggest to create a new bugreport with full info
