### ISSUE TITLE
Systray icon broken on Debian 8 (Jessie) after update to 2.2.0 

### ISSUE THREAD

**Issue by K0sme** [owncloud/client#4836] opened 2016-05-13 15:21 UTC
### Expected behaviour
Systray icon must be visible

### Actual behaviour
No icon at all

### Steps to reproduce
1. Install (or upgrade) to 2.2.0

### Client configuration
Client version: owncloud --version
ownCloud version 2.2.0%nil (build 1605)
Using Qt 5.3.2
Operating system: Debian 8 (amd64)
OS language: Spanish
Installation path of client: /usr/bin/owncloud

**Comment by RealRancor** [comment] 2016-05-13 17:12
Duplicate of https://github.com/owncloud/client/issues/4828

**Comment by dragotin** [comment] 2016-05-13 18:57
yes, duplicate, but which window manager/ desktop environment are we talking?

**Comment by K0sme** [comment] 2016-05-13 19:35
Mate 1.8.1 Desktop Environment

Sorry about the duplication.

**Comment by mcastroSG** [comment] 2016-05-16 16:19
Following up the issue at [#4828](https://github.com/owncloud/client/issues/4828)

**Closed by mcastroSG** 2016-05-16 16:19 UTC
