### ISSUE TITLE
[Linux] Support non-utf8 locale for filename

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5719] opened 2017-04-21 16:06 UTC
FYI @ogoffart @DeepDiver1975 

Related https://github.com/owncloud/client/issues/5676 ```[Feature] Filename encoding with gbk standard should be supported```

```
<ogoffart> There is no concept of fs encoding on linux
<ogoffart> Everything has to be encoded with the locale
<jturcotte> You'll also have to deal with chars that you can't convert to his encoding, and you want to make sure that if the user modifies that file that it's sent back to the server with the right name.
<jturcotte> And if the user sees blah???.png weird characters in the file, maybe he'll feel like he has to rename it too, so it shouldn't look too weird.
```

Challenges: How to handle invalid encodings?
https://github.com/owncloud/client/issues/4811#issuecomment-218076160

**Comment by ogoffart** [comment] 2017-04-22 11:40
(I changed the title because there is no need to involve the server, it's purely a client issue)

How to handle invalid encoding?:  The way we currently do it in SyncEngine::treewalkFile, for example.
https://github.com/owncloud/client/blob/e86499d9907f3bab5eac6e371eef772f8befd2e5/src/libsync/syncengine.cpp#L364
(however this has to happen at the time of conversion from the system locale, which has to happen in csync, before the reconcile phase.)

**Comment by guruz** [comment] 2017-11-06 12:37
Moving to 2.5 as https://github.com/owncloud/client/issues/5676 was moved too

**Comment by ogoffart** [comment] 2017-11-21 12:04
Duplicate of #5676

**Closed by ogoffart** 2017-11-21 12:04 UTC
Labels: Discussion
