### ISSUE TITLE
All account information lost (Ubuntu)

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/client#5628] opened 2017-03-18 04:06 UTC
Each time I start my machine, the owncloud client is asking me to set up a new account, a new server connection.

When I set that up, and restart my machine later, it's gone and have to set up over again. Every time.

After some inspections, it looks like something/someone has changed the contents of `owncloud.cfg` under `~/.local/share/data/ownCloud/folders` without my permission. Any clues why?

### Client configuration
Client version: 2.30
Operating system: Ubuntu 16.10
OS language: en-gb
Qt version used by client package (Linux only, see also Settings dialog): (not shown on Settings dialog, a bug?)
Client package (From ownCloud or distro) (Linux only): `deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.10/ /`

**Comment by binarykitchen** [comment] 2017-03-18 04:13
Btw this didn't happen few weeks earlier before my holidays. Guess apt-get must have installed a newer version of the client and then this happened.

**Comment by guruz** [comment] 2017-03-20 10:59
Could you please try our newer testing packages that use Qt 5.6.2 instead of the system Qt?
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by guruz** [comment] 2017-03-20 10:59
Also can you show a ```ls -l``` of your config directory?

**Comment by ckamm** [comment] 2017-03-20 11:52
@binarykitchen See above ^.

Also: You mean `~/.local/share/data/ownCloud/owncloud.cfg` right? Data in `ownCloud/folders` should be unused for many versions.

**Comment by mach-o** [comment] 2017-03-20 16:24
I'm having the same issue here, although I had the impression I wasn't losing the account info uniformly on every reboot, though definitely very often. I'm able to quit and restart the client without rebooting without losing the account info FWIW.

**Comment by mach-o** [comment] 2017-03-20 16:28
In case it helps in some way:

```
~ $ ls -l .local/share/data/ownCloud/
total 372
-rw-r--r-- 1 macho macho  126 Mar 20 12:22 cookies0.db
-rw-r--r-- 1 macho macho  243 Mar 20 12:22 cookies1.db
-rw-rw-r-- 1 macho macho    8 Nov 28 04:12 cookies.db
drwxrwxr-x 2 macho macho 4096 Nov 16  2015 folders
-rw-rw-r-- 1 macho macho 1223 Mar 20 12:22 owncloud.cfg
-rw-rw-r-- 1 macho macho 1477 Nov 21 11:00 owncloud.cfg.bG2407
-rw-rw-r-- 1 macho macho 1477 Nov 20 15:54 owncloud.cfg.Cl1878
-rw-rw-r-- 1 macho macho 1477 Nov 10 18:44 owncloud.cfg.cz2017
-rw-rw-r-- 1 macho macho 1477 Oct 19 17:51 owncloud.cfg.EE2297
-rw-rw-r-- 1 macho macho 1477 Oct 31 16:13 owncloud.cfg.ET2293
-rw-rw-r-- 1 macho macho 1477 Nov 11 17:11 owncloud.cfg.FF2102
-rw-rw-r-- 1 macho macho    0 Oct 19 09:00 owncloud.cfg.Gj2213
-rw-rw-r-- 1 macho macho 1477 Nov 18 20:54 owncloud.cfg.gP2166
-rw-rw-r-- 1 macho macho 1477 Oct 26 22:39 owncloud.cfg.Hb1984
-rw-rw-r-- 1 macho macho 1477 Nov 13 12:54 owncloud.cfg.jH1942
-rw-rw-r-- 1 macho macho 1477 Oct 20 18:37 owncloud.cfg.jm2029
-rw-rw-r-- 1 macho macho 1477 Oct 24 17:37 owncloud.cfg.Js2358
-rw-rw-r-- 1 macho macho 1477 Nov 25 15:25 owncloud.cfg.mA2230
-rw-rw-r-- 1 macho macho 1477 Nov 15 22:20 owncloud.cfg.Ol2235
-rw-rw-r-- 1 macho macho 1477 Oct 17 11:00 owncloud.cfg.oP2246
-rw-rw-r-- 1 macho macho 1477 Nov 21 08:41 owncloud.cfg.pH2292
-rw-rw-r-- 1 macho macho 1477 Oct 26 17:20 owncloud.cfg.pT2310
-rw-rw-r-- 1 macho macho 1477 Nov  4 22:04 owncloud.cfg.Rl2017
-rw-rw-r-- 1 macho macho 1477 Nov 14 00:15 owncloud.cfg.rR2108
-rw-rw-r-- 1 macho macho 1477 Nov 21 07:32 owncloud.cfg.ud2081
-rw-rw-r-- 1 macho macho 1477 Nov  6 10:12 owncloud.cfg.UO2657
-rw-rw-r-- 1 macho macho 1477 Nov 10 07:35 owncloud.cfg.Ux2118
-rw-rw-r-- 1 macho macho 1477 Nov 26 20:10 owncloud.cfg.vb2374
-rw-rw-r-- 1 macho macho 1477 Nov 20 17:04 owncloud.cfg.VK2073
-rw-rw-r-- 1 macho macho 1477 Oct 24 14:07 owncloud.cfg.XJ2090
-rw-rw-r-- 1 macho macho 1477 Oct 31 20:04 owncloud.cfg.xN2085
-rw-rw-r-- 1 macho macho 1477 Nov 18 06:16 owncloud.cfg.YZ2330
```

**Comment by binarykitchen** [comment] 2017-03-21 06:05
@guruz after a restart just lost all configs over again :(

here the current directory contents after that happened.

```
~/.l/s/d/ownCloud ❯❯❯ la
total 16K
-rw-r--r-- 1 michael-heuberger michael-heuberger  8 Mar 20 23:40 cookies0.db
-rw-rw-r-- 1 michael-heuberger michael-heuberger  8 Feb 11 11:05 cookies.db
-rw-rw-r-- 1 michael-heuberger michael-heuberger 44 Mar 21 19:00 owncloud.cfg
-rw-rw-r-- 1 michael-heuberger michael-heuberger 77 Mar 18 17:07 sync-exclude.lst
-rw------- 1 michael-heuberger michael-heuberger  0 Nov  9 22:31 .ZP6489
```

**Comment by binarykitchen** [comment] 2017-03-21 06:13
just have set up all over again. here the new `owncloud.cfg` contents
https://gist.github.com/binarykitchen/c18a92bb5fb91fde701c1eb38a45d625

**Comment by guruz** [comment] 2017-03-21 07:17
@ogoffart What are those odd config duplicates of @mach-o ? Although they are all from last year?

@mach-o @binarykitchen Are you sure you are using the Qt 5.6.2 based packages that I mentioned in https://github.com/owncloud/client/issues/5628#issuecomment-287728645 ? You should see the Qt version in the settings dialog ("General") of the client (please don't look at your system, look what the client says)

**Comment by binarykitchen** [comment] 2017-03-21 07:22
@guruz well, i cannot say what QT version it is. not shown in the settings tab, see screenshot

![selection_001](https://cloud.githubusercontent.com/assets/177641/24136521/0705a29a-0e74-11e7-8046-5d0c8ebc243e.png)

**Comment by mach-o** [comment] 2017-03-21 13:42
Sorry, @guruz, I had missed your earlier comment. I just now installed the alternative version you referenced.

Before doing so, however, I restarted without losing my account info, which seems to confirm that this problem was intermittent for me. I did lose the "Launch on System Startup" selection & had to launch manually, which seems to be another recurring symptom, though a less inconvenient one.

My configuration window looks the same as @binarykitchen's, except that I have "2.3.1git" rather than 2.3.0.

I will let you know whether these problems persist with this new version.

**Comment by ckamm** [comment] 2017-03-21 15:26
@guruz If the dev string is missing, I guess we didn't define GIT_SHA1? When would that happen? @binarykitchen says they installed from `deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.10/ /`

**Comment by ckamm** [comment] 2017-03-21 15:27
@binarykitchen @mach-o Could you run `owncloud --version`? That should always print the Qt version that's being used.

**Comment by ckamm** [comment] 2017-03-21 15:28
@binarykitchen The config file you posted is the one you see *after closing* the ownCloud client?

**Comment by ogoffart** [comment] 2017-03-21 15:56
the GIT_SHA1 is not defined if the build is not made in a git repository.

The cfg.xxxxx files are coming from QSaveFile which is used within QSettings in Qt5. But it's really strange that they stay around, they normaly should be removed. So that means that there was a crash or something while saving the config file.

**Comment by mach-o** [comment] 2017-03-21 17:01
```
~ $ owncloud --version
ownCloud version 2.3.1git
Using Qt 5.6.2, built against Qt 5.6.2
Using 'OpenSSL 1.0.2g  1 Mar 2016'
```

**Comment by mach-o** [comment] 2017-03-22 04:43
Since upgrading to 2.3.1git, all of the problems I reported earlier in this issue have disappeared. Issue resolved AFAIC.

**Comment by binarykitchen** [comment] 2017-03-22 05:12
```
~ ❯❯❯ owncloud --version
ownCloud version 2.3.0
Using Qt 4.8.7
```

**Comment by binarykitchen** [comment] 2017-03-22 05:13
@ckamm no, contents where like that when i left the client running.

**Comment by ckamm** [comment] 2017-03-22 07:46
@mach-o Thanks for testing.

@binarykitchen Could you also try 2.3.1 with Qt 5.6.2? Since we haven't changed any config file handing between 2.3.0 and 2.3.1 it's very likely the Qt version that makes the difference here.

**Comment by binarykitchen** [comment] 2017-03-22 21:13
@ckamm hmmm are these packages for developers with more debug information?

**Comment by ckamm** [comment] 2017-03-23 10:21
@binarykitchen It's a snapshot build of the oC generated package. It's different from your disto's package, but it'd be great to know whether your problem is resolved by it.

**Comment by binarykitchen** [comment] 2017-04-03 09:40
okay, i have switched to them a while ago and i am afraid, it is still happening with 2.3.1 with Qt 5.6.2 :(

i think the config file somehow gets corrupted? no idea

**Comment by ckamm** [comment] 2017-04-04 07:21
@ogoffart Do you have any ideas left?

**Comment by ogoffart** [comment] 2017-04-04 10:42
I don't have any idea.  with Qt 5.6 that should not happen. 

 @binarykitchen  are you sure that owncloud --version  shows Qt 5.6 ?

**Comment by binarykitchen** [comment] 2017-04-04 11:32
argh, looks like `apt-get` messed up something on my machine. after a reinstall having QT 5.6.2 again

**Comment by guruz** [comment] 2017-04-04 18:16
@binarykitchen I'll close this for now as @mach-o confirmed it was working for him.
But please speak up if it occurs again for you

**Closed by guruz** 2017-04-04 18:16 UTC
Labels: Needs info

**Comment by btittelbach** [comment] 2017-07-10 15:16
Same behaviour (Bug) started a few days ago for me.

system: Ubuntu 17.04
qt5: 5.7.1
qt4: 4.8.7
client: Version 2.3.2 (Built from Git revision 820899 on May 8 2017, 14:16:42 using Qt 4.8.7, built with OpenSSL 1.0.2g 1 Mar 2016)

### Bug Description:

When I login to Ubuntu and have no internet connection, the owncloud client creates a new 0byte owncloud.cfg on startup and asks for server address, login, etc. If I restart owncloud with an internet connection afterwards, the configuration is still gone.

However, when I login to Ubuntu with a working internet connection, everything is fine, the owncloud client starts as expected. (without asking for server url/login)

**Comment by michaelstingl** [comment] 2017-07-10 15:36
@btittelbach Please check my comment: https://github.com/owncloud/client/issues/945#issuecomment-314143440
