### ISSUE TITLE
Mac OS client - context menu for sharing

### ISSUE THREAD

**Issue by rdagher** [owncloud/client#4438] opened 2016-02-05 14:16 UTC
Hi,

I am using owncloud desktop client Version 2.1.0 (build 2944) on *Mac OS* el Capitan (10.11.3).
When I want to use the context menu "share with own cloud" it only allows share by link, no way to share with a list of users like in this [example](https://doc.owncloud.org/desktop/2.1/navigating.html#sharing-from-your-desktop). Note that the owncloud plugin is activated.

![screen shot 2016-02-05 at 15 15 34](https://cloud.githubusercontent.com/assets/11162310/12848610/5b845fc4-cc1b-11e5-9005-ce1b756dc32c.png)

Thanks a lot,
Roudy

**Comment by danimo** [comment] 2016-02-05 14:21
Any idea, @jturcotte?

**Comment by jturcotte** [comment] 2016-02-05 14:25
No idea, I never touched the inside of the share dialog. @ckamm or @rullzer might have a quick idea.

**Comment by rullzer** [comment] 2016-02-05 14:27
What is your server version?

**Comment by jfml** [comment] 2016-02-05 16:34
Does this link sharing work in OSX 10.9? I don't even get the green sync-buttons when I enable the desktop syn client. That would be amazing! Dreamed of this for years! (Should I make this a different issue?)

**Comment by jturcotte** [comment] 2016-02-05 16:39
@jfml The icons and menu entry should work in 10.9 if it was enabled when you installed the client.

It will probably work better in 10.10 though, since Apple added an official API for overlay icon that we can use with that version.

**Comment by jfml** [comment] 2016-02-05 16:47
@jturcotte Thanks! So in 10.9 I should be able to right-click in finder on a file in the OwnCloud dir and share the link (when the Desktop Syn Client (2.1.0) is running)? I can't seem to find anything on right-click. Or how do I get to that Sharing window/dialog in the photo above?

**Comment by jturcotte** [comment] 2016-02-05 16:54
@jfml I can't walk you through the steps to get this working, you should probably contact the ownCloud support for this.

Some info is also available in the [manual](https://doc.owncloud.org/desktop/2.1/ownCloudClientManual.pdf).

If you think that this is a bug and can identify if it did work in the past, or something that would allow us to reproduce the issue, please open a separate issue.

**Comment by jfml** [comment] 2016-02-05 16:56
@jturcotte Cool, thanks for the info!

**Comment by jfml** [comment] 2016-02-05 17:27
For some reason desktop sharing now works for me.

I can even share with groups or users like @rdagher asked:

![owncloudsharewithusersgroups](https://cloud.githubusercontent.com/assets/4312909/12853708/81e984fc-cc2d-11e5-96c0-a49fd29db2c5.jpg)

Weird that it works for 10.9 but apparently not 10.11 (haven't tested it on Capitan).

**Comment by danimo** [comment] 2016-02-05 17:29
@jfml works fine on 10.11. Make sure that you have the extension enabled, as per the docs.

**Comment by guruz** [comment] 2016-02-06 09:14
Closing as probably @rdagher has a too old server version.
Note that also re-login might be necessary after a client upgrade.

**Closed by guruz** 2016-02-06 09:14 UTC

**Comment by rdagher** [comment] 2016-02-06 13:24
@rullzer the version of my server is below (output from status.php request)

`{"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":""}
`
@guruz is this too old? Is there any required config or dependencies at client or server side for this to work?

**Comment by rullzer** [comment] 2016-02-06 14:17
@rdagher yes. user/group sharing requires a server of at least 8.2.0.
