### ISSUE TITLE
Create a Way to Disable Parallel Uploads

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2743] opened 2015-01-23 13:37 UTC
For various reasons we can not enable the parallel upload by default. We need to disable the parallel upload and only switch it on by a flag if admins decide that. Even if that results in a performance drop.

e.g. https://github.com/owncloud/client/issues/2724 https://github.com/owncloud/client/issues/1866#issuecomment-45924708 https://github.com/owncloud/client/issues/2401

**Comment by dragotin** [comment] 2015-01-23 13:38
This is not only about uploads but also all other operations. Disable parallelism by default.

**Comment by guruz** [comment] 2015-01-23 13:40
OK... check for status.php version to be >= 8.1 ?

**Comment by PVince81** [comment] 2015-01-23 13:53
As discussed on IRC we could add a new value "maxparallel" to that `capabilities` call with the following logic: if SQLite is used, "maxparallel" would be 1, else 0 (infinite)

**Comment by PVince81** [comment] 2015-01-23 13:54
In general I think we should start using this "capabilities" endpoint more often to share server info with clients.

**Comment by dragotin** [comment] 2015-01-23 14:01
agree with @PVince81

**Comment by guruz** [comment] 2015-01-23 17:12
We also had the idea to check all error messages for ```SQLSTATE``` and then force paralleism down to 1

**Comment by PeterPablo** [comment] 2015-01-23 17:28
Would disabling parallelism also prevent wrong/missing `ctime`s and  `mtime`s (confer the problem described in the referenced issue #2401).

**Comment by ogoffart** [comment] 2015-01-23 18:48
@PeterPablo: no, it would just make it less likely.

sqlite should be avoided on the server if possible.

**Comment by PeterPablo** [comment] 2015-01-24 08:31
In my opinion users should be made aware of this in a more pressing altert than described in the current documentation (confer https://github.com/owncloud/client/issues/2401#issuecomment-60518559). I still consider this loss of data and as such a bug that should be tackled.

**Comment by radry** [comment] 2015-01-25 18:11
I agree with this issue! On my low memory owncloud php runs out of memory when uploading many files with the windows client because of parallel uploads!! Uploading via a browser works perfectly fine. This is a major issue since there are no (free) alternative clients which can sync (instead of "mounting" the webdav which I don't want).

**Comment by dragotin** [comment] 2015-02-05 11:40
We need to know to which extend the server fixed the underlying problems to be able to decide what to do.

**Comment by PVince81** [comment] 2015-02-05 11:48
Parallel upload should work now on OC 8 RC 2, the major database is locked issues were fixed.
It worked fine in my various tests (and I had a slow HDD / VM where the issue could be reproduced consistently before the fix)

**Comment by PVince81** [comment] 2015-02-05 11:49
For OC 7, backports are still required:
- https://github.com/owncloud/core/pull/13832
- https://github.com/owncloud/core/pull/13831

**Comment by radry** [comment] 2015-02-05 14:52
@PVince81 

Great but what about php running out of memory on low end servers? I realize that is not the problem of owncloud per se but the parallel upload is still to blame, so there MUST be an option to disable parallel upload in the client or the server.

**Comment by guruz** [comment] 2015-02-05 16:28
@radry I believe that problem should be fixed because the 1.8 client only uses a chunk size of 5MB (vs 20MB in 1.7.x and 10 MB in 10.6.x)

**Comment by ogoffart** [comment] 2015-02-06 12:00
So according  @PVince81  in https://github.com/owncloud/client/issues/2724#issuecomment-73059419
recommand disabling parallelism for anything less than owncloud 8.0

Should we disable only parallel chunk upload (which is new in 1.8), or any kind of parallelism?
Don't we risk users complaining about preformence regression in 1.8?

Another option we could take is to disable the parallelism once we detect the 500 error.

**Comment by moscicki** [comment] 2015-02-06 12:14
I would like to say it again: what about that the server tells the client what kind of features it supports? In this way you may avoid any hardcoded assumptions and also avoid to manually re-adjust the client when the new versions of the server develop new capabilities (which is anyway impossible because you still have old versions of the servers around).

The same also for the size of the chunk. Changing from 10MB -> 20MB -> 5MB looks a bit like a random walk for me. I KNOW what is the averge file size in my service, so why would not you let me configure the server with the correct number for MY service.

And above all it all may be achieved by adding extending simple JSON reponse of status.php. Why make it any more complicated?

kuba

--

**Comment by ogoffart** [comment] 2015-02-06 12:34
@moscicki I agree with you, and that is already implemented by https://github.com/owncloud/client/commit/d7c2b664abf4c5b5862fe688df8d5a3d538f7600 for the amount of parallelism,  but the server do not expose this after all.

**Comment by PVince81** [comment] 2015-02-06 13:15
I'm fine with adding this back or making this configurable, but not sure if others agree: @karlitschek @DeepDiver1975 
The ticket for "max_parallels" was this one: https://github.com/owncloud/core/pull/13628

**Comment by lmaestro** [comment] 2015-02-19 10:15
It works fine version 1.8.0-beta1

**Closed by lmaestro** 2015-02-19 10:15 UTC
Labels: gold-ticket, Needs info, ReadyToTest
