### ISSUE TITLE
OwnCloud Desktop client - cant handle file path/name.

### ISSUE THREAD

**Issue by aliraxa** [owncloud/client#6242] opened 2017-12-14 10:22 UTC
Hi,

I am running owncloud desktop client version 2.3.4(build 8624) - I setup my account on it and while it was syncing data it gave me error while size issue(servers says it 1kb etc ..). Where as the actually issue was the file path/name(I have connected SMB share) - the name contains 4 spaces which desktop client is unable to handle.

File path:
/myfolder/04-2015\ -\ INL\ 15\ \ \ \ 1322\ -S.J.G.Woodhead.pdf

But owncloud just sees.. [ /myfolder/04-2015\ -\ INL\ 15 ] -- so its getting incorrect path and files don't get synced.

**Comment by SamuAlfageme** [comment] 2017-12-14 11:59
Hey @aliraxa, which OS are you running your client on? I'm guessing Windows, right? Can you paste here [some logs](https://doc.owncloud.org/desktop/2.3/advancedusage.html#options) when the error happens? 

@ogoffart as it's an SMB mount, this might be similar/related to what I tried while trying to reproduce @cdamken's problem last week (syncing a file with a `\` on a mounted drive on windows)

**Comment by ogoffart** [comment] 2018-03-27 09:41
I just tested files with lots of space with the master branch of the client on linux, and the server 10.0.4, and it works flawlessly.

It is possible that it is a limitation of the file system, in which case, file that are invalid on this file system cannot be sync'ed.

If it is a problem specific to a SMB mount on the server, then this should be reported in the core bug tracker.

But I'm going to close this bug now since we don't have ways to reproduce the problem.

**Closed by ogoffart** 2018-03-27 09:41 UTC
Labels: Needs info
