### ISSUE TITLE
[Windows Client] Files created upon version conflict not synching to server

### ISSUE THREAD

**Issue by CJR2** [owncloud/client#5856] opened 2017-06-23 19:16 UTC
### Expected behaviour
Upon the creation of a version conflict (2 users having edited file simultaneously and saving different versions), the file should sync back to the server so that all users can see the conflicted versions and manually resolve.

### Actual behaviour
The windows client recognizes that 2 users have opened a file (ex: test.txt) and both have saved different, conflicting versions of the file.  A conflicting version is saved (ex: Test_conflict-20170623-100411.txt), however, the file does not synch back to the server.

### Steps to reproduce
1. Create a text file (ex: test.txt) with some text inside
2.  Have 2 users, using windows and the windows notepad, open the text file and make different edits. Both save their files.
3.  Conflict will be saved on 1 users' drive. 
4. Look for synch of the conflcted version back to the server.

### Server configuration
Operating system: (not known / hosted by hostiso.cloud)

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: 2.3.1

Operating system: Windows 10 Pro

OS language: ?

Qt version used by client package (Linux only, see also Settings dialog): n/a

Client package (From ownCloud or distro) (Linux only): n/a

Installation path of client: h:\program files (x86)\Nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by hodyroff** [comment] 2017-06-26 05:55
Right now this is the expected behaviour. Conflict files reside on the clients only. There are some FRs and discussions in the other direction but this one is best for now. There is a case to be made that the conflicts should show up in the versions! Happy for further input/consolidation of this FR as I think we saw it before.

**Comment by michaelstingl** [comment] 2017-06-26 06:55
Looks like a duplicate for https://github.com/owncloud/client/issues/4557

**Comment by CJR2** [comment] 2017-06-26 10:23
Hody - from an end user perspective, everyone needs/must see that there is a conflicted version. Otherwise, folks will continue to work on their version of the document, rather than get with other document users to resolve the issue. 

The only way to see that conflicted version is to allow its propagation/sync to the server.
The alternative, if you don't think this should be the case, is to allow each server admin to choose the behavior. I think this should be done at the server level.

**Comment by guruz** [comment] 2017-07-13 13:08
@CJR2 how do you like the view in https://github.com/owncloud/client/pull/5894 ?
Maybe you want to test a nightly build? The nightlies should be ready tomorrow (in theory)..
https://owncloud.org/install/#testing-development

**Comment by CJR2** [comment] 2017-07-13 13:17
Thanks for pointing that out - I'll test the nightly build and let you know!
From the view in #5894, do other users know that there's a conflicted version? There's something about the conflicted file being uploaded that also alerts other team members who may get involved to reconcile the issue.
Think of your less motivated employees / team members. They might overlook the conflict for many days, unfortunately.

**Comment by ogoffart** [comment] 2018-04-23 09:45
The client 2.4 now allows to upload conflict files (using an environment varialble)
And 2.5 also upload conflicts file when a flag is set on the server.

I'm closing this issue now  as it is a closely related to #4557 and #5894

**Closed by ogoffart** 2018-04-23 09:45 UTC
Labels: Discussion, Needs info
