### ISSUE TITLE
[SHIB] Not possible to log in on a 1.8.4 desktop version with shib, server version 8.1.4

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#4005] opened 2015-10-26 13:30 UTC
STEPS TO REPRODUCE:

1.- Using the desktop client version 1.8.4 on mac
2.- Select to connect to an ownCloud server with Shib authentication  {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":"Enterprise"}
3.- Enter the server url

CURRENT BEHAVIOR:
A white web view is shown

EXPECTED BEHAVIOR:
A web view is shown where you are able to login

### DESKTOP LOGS
````
10-26 14:14:12:787 0x7ff243c65b20 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, "Enterprise") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.1.4.0") ) ( "versionstring" ,  QVariant(QString, "8.1.4 RC1") ) )    0  Reply:  QNetworkReplyHttpImpl(0x7ff2460e6e80)
10-26 14:14:12:788 0x7ff243c65b20 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "<font color="green">Successfully connected to https://XXXXX/oc-shib/status.php: res version 8.1.4 RC1 (8.1.4.0)</font><br/><br/>"
10-26 14:14:12:789 0x7ff243c65b20 OCC::OwncloudSetupWizard::slotOwnCloudFoundAuth: void OCC::OwncloudSetupWizard::slotOwnCloudFoundAuth(const QUrl &, const QVariantMap &)  was redirected to "https://XXXX/oc-shib"
10-26 14:14:12:790 0x7ff243c65b20 OCC::AbstractNetworkJob::start: !!! OCC::DetermineAuthTypeJob created for "https://XXXX" + ""
10-26 14:14:12:834 0x7ff243c65b20 OCC::DetermineAuthTypeJob::finished: virtual bool OCC::DetermineAuthTypeJob::finished() "https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO?SAMLRequest=jVJdT8IwFP0rS99Zt44RbBjJhAdJUAhDH3wxXXeBxtHO3s6Pf2%2FHMOIL8bXn656TTlAc64bnrTvoDby1gC74PNYa%2BQnISGs1NwIVci2OgNxJXuT3S87CiDfWOCNNTYIcEaxTRs%2BMxvYItgD7riQ8bpYZOTjXIKe0MvIVbGhkiKZW1R6EDb1jmrB4SIuDKktTgzuEiIZ2GYyuV8WWBHN%2FlNKis%2F81U1UTOg%2Bg14XG7rsH6g%2FaqRrO6g1UyoJ0tChWJFjMM%2FICu1E5jm6qHSRxwkYiHYuEScGqyCMpG3kaYgsLjU5olxEWxekgjgZstI0THg95lD6TYH3ufat0pfT%2B%2BkhlT0J%2Bt92uB32jJ7B4auMJZDrppuanYHsx%2FnVb8bM4mf5rXyMH3VQTehHWJzf8wbsv5msvkl9BXtfmY2ZBOMhITOi0l%2Fz9I9Nv&RelayState=ss%3Amem%3Ae85a35d516233af4e9088e6b2e918da66dd83aa3c6db3deeaf335b5c82fed336"
10-26 14:14:12:836 0x7ff243c65b20 unknown: QIODevice::read: device not open
10-26 14:14:12:972 0x7ff243c65b20 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  2
10-26 14:14:13:322 0x7ff2460f3130 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::SocketError( 13 ) QSslSocket(0x7ff2461c3bf0) QHttpNetworkReply(0x7ff2461cb2f0) 0 false 3 1 QAbstractSocket::ConnectedState
10-26 14:14:13:322 0x7ff2460f3130 unknown: ERRORING CURRENT QHttpNetworkReply(0x7ff2461cb2f0)  QUrl( "https://XXXX/oc-shib" ) 
10-26 14:14:13:324 0x7ff243c65b20 OCC::ShibbolethWebView::slotLoadFinished: void OCC::ShibbolethWebView::slotLoadFinished(bool) Could not load Shibboleth login page to log you in.
10-26 14:14:13:323 0x7ff2460f3130 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7ff2461c3bf0) QObject(0x0)  0 false 3 16
10-26 14:14:17:835 0x7ff2460e83d0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7ff243e69280) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
10-26 14:14:17:835 0x7ff2460e83d0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7ff243e69280) QObject(0x0)  0 false 3 0
10-26 14:14:20:114 0x7ff243c65b20 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
10-26 14:14:50:114 0x7ff243c65b20 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
```

### SERVER LOGS

owncloud.log --> nothing
access.log -> nothing
access.ssl.log -> nothing
error.log -> nothing
error.ssl.log -> nothing


NOTE:
Greater desktop versions works (2, 2.0.1 and 2.0.2) @Dianafg76 has checked it

**Comment by rperezb** [comment] 2015-10-26 13:31
Related to: https://github.com/owncloud/client/issues/3593#issuecomment-133318247

**Comment by DeepDiver1975** [comment] 2015-10-26 14:02
@rperezb other client versions are properly working against this instance?

**Comment by rperezb** [comment] 2015-10-26 14:11
@DeepDiver1975 yes, I have checked it and @Dianafg76

**Comment by Dianafg76** [comment] 2015-10-26 14:11
@rperezb, @DeepDiver1975, @cmonteroluque 

## Desktop v - Server V

| Desktop v | Server v  | Result |
|:------------- |:---------------:| -------------:|
| 1.8.4      | 8.1.4 |     Breaks (doesn't manage to open the testshib webside (stays blank) #3593  |
| 2.0.0| 8.1.4       |          Works |
| 2.0.1 | 8.1.4       |            Works|
| 2.0.2 | 8.1.4       |            Works|

Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":"Enterprise"}

**Comment by ogoffart** [comment] 2015-10-26 14:53
So if this works with newer version, that means the issue is fixed.  There will not be another 1.8.x release.

**Comment by cmonteroluque** [comment] 2015-10-26 14:56
Sorry, I wish I could be so lucky. This can't be closed until we know the impact on existing enterprise customers. Re-opening until I can tell otherwise.

**Comment by dragotin** [comment] 2015-10-26 15:07
I think this is not an issue, as the fix is in stable8 ( https://github.com/owncloud/core/pull/19051 ) and more recent versions of the client work.

**Comment by cmonteroluque** [comment] 2015-10-26 17:55
Actually, we have a big one with 1.8.4 and shibboleth, it needs to be fixed

**Comment by DeepDiver1975** [comment] 2015-10-26 20:31
@rperezb @Dianafg76 can we please have an 1.8.4 shibboleth test series against oc7, 8, 8.1 and 8.2? THX

**Comment by Dianafg76** [comment] 2015-10-27 08:00
@DeepDiver1975, @rperezb, @dragotin 
## Desktop v - Server V
| Desktop v | Server v  | Result |
|:------------- |:---------------:| -------------:|
| 1.8.4 | 7 | BREAKS (doesn't manage to open the testshib webside (stays blank)| 
| 1.8.4 | 8       | BREAKS (doesn't manage to open the testshib webside (stays blank) | 
| 1.8.4 | 8.1     | BREAKS (doesn't manage to open the testshib webside (stays blank)| 
| 1.8.4 | 8.2  | BREAKS (doesn't manage to open the testshib webside (stays blank) |

**Comment by DeepDiver1975** [comment] 2015-10-27 08:35
@cmonteroluque I honestly question that SurfNET is running 1.8.4 :speak_no_evil:

**Comment by DeepDiver1975** [comment] 2015-10-27 08:41
Okay - I was just chatting with Arnout from SurfNET and yes they are using 1.8.4.

Did we apply any special patches to the surfnet branded client?

@Dianafg76 @rperezb mind testing 1.8.4 plain against the surfnet test instance?

**Comment by Dianafg76** [comment] 2015-10-27 08:51
@DeepDiver1975, @rperezb, @cmonteroluque, @dragotin 
I tested 1.8.4 with SURFNET and it is working OK

**Comment by DeepDiver1975** [comment] 2015-10-27 08:53
@Dianafg76 I just made the same misstake to leak customer information publicly :see_no_evil: 

I copied your comment to https://github.com/owncloud/enterprise/issues/876

**Comment by DeepDiver1975** [comment] 2015-10-27 10:00
@dragotin @guruz is this indicating the self-signed cert issue which was fixed later in https://github.com/owncloud/client/commit/01855302a05303ba46e7e002d960c4ac61ff3695

THX

````
> 10-26 14:14:12:787 0x7ff243c65b20 OCC::CheckServerJob::finished: status.php returns: QMap(("edition", QVariant(QString, "Enterprise") ) ( "installed" , QVariant(bool, true) ) ( "maintenance" , QVariant(bool, false) ) ( "version" , QVariant(QString, "8.1.4.0") ) ( "versionstring" , QVariant(QString, "8.1.4 RC1") ) ) 0 Reply: QNetworkReplyHttpImpl(0x7ff2460e6e80) 10-26 14:14:12:788 0x7ff243c65b20 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log: "<font color="green">Successfully connected to https://XXXXX/oc-shib/status.php: res version 8.1.4 RC1 (8.1.4.0)</font><br/><br/>" 10-26 14:14:12:789 0x7ff243c65b20 OCC::OwncloudSetupWizard::slotOwnCloudFoundAuth: void OCC::OwncloudSetupWizard::slotOwnCloudFoundAuth(const QUrl &, const QVariantMap &) was redirected to "https://XXXX/oc-shib" 10-26 14:14:12:790 0x7ff243c65b20 OCC::AbstractNetworkJob::start: !!! OCC::DetermineAuthTypeJob created for "https://XXXX" + "" 10-26 14:14:12:834 0x7ff243c65b20 OCC::DetermineAuthTypeJob::finished: virtual bool OCC::DetermineAuthTypeJob::finished() "https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO?SAMLRequest=jVJdT8IwFP0rS99Zt44RbBjJhAdJUAhDH3wxXXeBxtHO3s6Pf2%2FHMOIL8bXn656TTlAc64bnrTvoDby1gC74PNYa%2BQnISGs1NwIVci2OgNxJXuT3S87CiDfWOCNNTYIcEaxTRs%2BMxvYItgD7riQ8bpYZOTjXIKe0MvIVbGhkiKZW1R6EDb1jmrB4SIuDKktTgzuEiIZ2GYyuV8WWBHN%2FlNKis%2F81U1UTOg%2Bg14XG7rsH6g%2FaqRrO6g1UyoJ0tChWJFjMM%2FICu1E5jm6qHSRxwkYiHYuEScGqyCMpG3kaYgsLjU5olxEWxekgjgZstI0THg95lD6TYH3ufat0pfT%2B%2BkhlT0J%2Bt92uB32jJ7B4auMJZDrppuanYHsx%2FnVb8bM4mf5rXyMH3VQTehHWJzf8wbsv5msvkl9BXtfmY2ZBOMhITOi0l%2Fz9I9Nv&RelayState=ss%3Amem%3Ae85a35d516233af4e9088e6b2e918da66dd83aa3c6db3deeaf335b5c82fed336" 10-26 14:14:12:836 0x7ff243c65b20 unknown: QIODevice::read: device not open 10-26 14:14:12:972 0x7ff243c65b20 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to 2 10-26 14:14:13:322 0x7ff2460f3130 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::SocketError( 13 ) QSslSocket(0x7ff2461c3bf0) QHttpNetworkReply(0x7ff2461cb2f0) 0 false 3 1 QAbstractSocket::ConnectedState 10-26 14:14:13:322 0x7ff2460f3130 unknown: ERRORING CURRENT QHttpNetworkReply(0x7ff2461cb2f0) QUrl( "https://XXXX/oc-shib" ) 10-26 14:14:13:324 0x7ff243c65b20 OCC::ShibbolethWebView::slotLoadFinished: void OCC::ShibbolethWebView::slotLoadFinished(bool) Could not load Shibboleth login page to log you in. 10-26 14:14:13:323 0x7ff2460f3130 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7ff2461c3bf0) QObject(0x0) 0 false 3 16 10-26 14:14:17:835 0x7ff2460e83d0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7ff243e69280) QObject(0x0) 0 false 3 0 QAbstractSocket::ConnectedState 10-26 14:14:17:835 0x7ff2460e83d0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7ff243e69280) QObject(0x0) 0 false 3 0 10-26 14:14:20:114 0x7ff243c65b20 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 10-26 14:14:50:114 0x7ff243c65b20 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag

**Comment by cmonteroluque** [comment] 2015-10-28 10:52
@DeepDiver1975 thanks, and thank for fixing the info leak too. I believe this can be closed due to the self-signed cert limitation in testing. Please correct if needed

**Closed by cmonteroluque** 2015-10-28 10:52 UTC
Labels: sev1-critical
