### ISSUE TITLE
Owncloud Win client [Version 2.2.2 (build 6192)] keeps asking for password but works

### ISSUE THREAD

**Issue by riverofjanuary** [owncloud/client#5010] opened 2016-06-28 02:01 UTC
Brand new install. Auth is working on website (via https://) and auth is working on other Windows machine clients. 

On this machine, app continuously asks for password. entering correct password allows syncing and everything to go on... Then 2 minutes later the password box pops up again, with PREFILLED password (but obfuscated). Clicking OK continues the sync. Clicking cancel clears the password and prevents login, howewever entering the program, clicking "Log in" re-fills the pssword field!. Rinse, repeat, 2 minutes later password is asked again.

EDIT: I tried UNINSTALLING and reinstalling and still that same awful issue. I have two other Win10 computers with exactly same setup and thats not coming up.

Server: 9
PHP 5.5
Client: Version 2.2.2 (build 6192)
OS: Win 10

**Comment by riverofjanuary** [comment] 2016-06-29 14:54
Any luck? Now its "infected" another Win10 computer! I'm going to have to stop using owncloud for now, its impossible to get any work done.

**Comment by mcastroSG** [comment] 2016-06-29 15:11
@riverofjanuary may you provide Desktop Client logs launching you client with --logwindow  or --logfile option in order to help you with this problem?

**Comment by riverofjanuary** [comment] 2016-06-29 15:20
Yes, right here (anonymized data): 
[owncloud.txt](https://github.com/owncloud/client/files/339589/owncloud.txt)

Note: this was a --logwindow, it asked for password THREE TIMES during a 1 minute window...

**Comment by mcastroSG** [comment] 2016-06-30 07:58
@guruz what do you think ¿? something related to the server side?¿

It seems that after solving a conflict login is not valid anymore

**Comment by dragotin** [comment] 2016-06-30 08:15
I wonder if the sessions are properly maintained on the  server side. But even if not, the password should be retrieved from the Windows Vault via our keychain library.

Can you check if your ownCloud passwd is stored in the Win Vault? See http://www.howtogeek.com/106906/how-to-add-credentials-to-the-windows-credential-manager-vault/ for some hints...

**Comment by riverofjanuary** [comment] 2016-06-30 12:40
Two questions:

1. Why did it just start exactly 4 days ago? I've had it for almost 2 years right now.

2. How do I help my web server/provider test what changed and how to change the sessions?

**Comment by riverofjanuary** [comment] 2016-07-02 15:17
Any thoughts?

**Comment by ckamm** [comment] 2016-07-06 09:43
@dragotin @riverofjanuary If I understand correctly the problem is that the dialog pops up at all - especially since the correct password is already filled in.

**Comment by ckamm** [comment] 2016-07-06 09:53
@riverofjanuary This is a key line from your log:
```
06-29 11:15:31:696 0x4937880 OCC::HttpCredentials::slotAuthentication: Stop request: Authentication failed for  "https://mysite.net/owncloud_directory/remote.php/webdav/apps/edit/sublime-text-3/Data/Cache/C%23"
```
That means the server said the credentials were invalid and will trigger the auth dialog on the client. Maybe something is up with that url? Can you retrieve that data with a program like `curl`?

**Comment by riverofjanuary** [comment] 2016-07-07 15:42
Server was not an issue until 1 week ago, as I mentioned, and it
still works on other computers, as well. It leads me to believe it is
the client.
 
How do I fix this error, and/or how do I use Windows credentials?
 
 
 
----- Original message -----

**Comment by riverofjanuary** [comment] 2016-07-15 16:43
Any thoughts? It now does not work on 3 different windows machines (it started one by one) even though no server config has changed in years. I just want to confirm before I shut down and switch to another service (unfortunately possibly hosted but it seems OC is not deploy-ready at this time).

**Comment by clmcavaney** [comment] 2016-07-19 06:26
I have observed the same issue on one machine I use with ownCloud, but not another.
I will have a look at the logging and see if I can provide further insights.

**Comment by spankit** [comment] 2016-09-18 02:01
Also having a similar issue on various computers with the latest owncloud client.

**Comment by riverofjanuary** [comment] 2016-09-18 12:00
@spankit I deleted synced dirs, 1 by 1, til i found the problem to be with my portable install of Sublime Text 3 and how it stored caching files. Something with permissions, or disk i/o, or something was screwing it up, but deleting that dir fixed the issue. Its a very vague and poorly worded error message,but thats all I can offer!

**Comment by dragotin** [comment] 2016-09-19 14:33
Ok, I am closing this than. If one of you has more helping info, please ping us to reopen. Thx.

**Closed by dragotin** 2016-09-19 14:33 UTC
Labels: bug, Needs info
