### ISSUE TITLE
[MSI] Provide a way to autoprovision credentials

### ISSUE THREAD

**Issue by finius** [owncloud/client#6188] opened 2017-11-24 07:28 UTC
If would be great to make the ownCloud client able to use a users integrated Windows credentials to authenticate against ownCloud server. As in a company most users are using Active Directory to authenticate, it would be great to use this tokens to authenticate against the ownCloud Server. In combination with adding some command line configuration options, this could enable admins to roll out and set up the ownCloud client on a client machine without having the user to set up his/her account manually.

**Comment by michaelstingl** [comment] 2017-11-24 14:08
On ownCloud I would recommend to try the OAuth 2.0 app on the server side. Then ownCloud desktop sync client opens default system for login. If your magic tokens work in system browser, then your clients are already logged in too. Could you test and provide feedback?

More Information:
- Webinar: https://owncloud.com/playback/secure-authorization-with-oauth2/
- Blog: https://owncloud.org/blog/introducing-oauth2-secure-authorization-flow/

**Comment by guruz** [comment] 2017-11-28 14:33
@finius I think this issue is a duplicate of either https://github.com/owncloud/client/issues/750 or https://github.com/owncloud/client/issues/2111 or both :-)

Can you confirm and then close this issue?

CC @pmaier1

**Comment by finius** [comment] 2017-11-28 16:12
@guruz Yes, I think it's both :-)
@michaelstingl  Thanks for the feedback - I will test on occasion.

**Closed** 2017-11-28 16:12 UTC
Labels: Enhancement, Needs info, research

**Comment by guruz** [comment] 2017-11-29 12:10
Nothing to test unfortunately :-(
Just can vote for the feature.
