### ISSUE TITLE
[QA] german locale shows '<no filter>' untranslated

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8594] opened 2021-05-04 22:05 UTC
Seen with 2.8.0RC1 on Ubuntu 20.04
Started as `env LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LANGUAGE=de_DE.UTF-8 owncloud`

![image](https://user-images.githubusercontent.com/1108546/117075596-64be5800-ad35-11eb-9e1e-86fec40beaac.png)

Expected behaviour: '<kein Filter>'

**Comment by TheOneRing** [comment] 2021-05-05 08:53
Duplicate of https://github.com/owncloud/client/issues/8212

**Closed by TheOneRing** 2021-05-05 08:53 UTC
