### ISSUE TITLE
KDE Plasma: Right-click on tray icon doesn't work

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6545] opened 2018-05-24 12:35 UTC
![kde-right-click](https://user-images.githubusercontent.com/214010/40485463-e6dc1c8c-5f5e-11e8-903a-1572e20d4310.gif)

You need to right-click tray icon very often. No effect. If it worked once, then it seems more likely to work again… (🤔sounds strange, I know)

### Steps to reproduce
1. Install 2.4.1 on Kubuntu 18.04
2. Right-click on tray icon

### Client configuration
Client version:
2.4.1

Operating system:
Kubuntu 18.04

OS language:
EN

Qt version used by client package (Linux only, see also Settings dialog):
5.6.2

Client package (From ownCloud or distro) (Linux only):
From ownCloud

Installation path of client:
???

[00009497](https://na56.salesforce.com/5000Z00000zHkAy)

**Comment by guruz** [comment] 2018-05-24 13:50
@michaelstingl Do you have a machine to reproduce this? If yes try the 2.5.0 nightlies with newer Qt?

**Comment by ogoffart** [comment] 2018-05-24 14:15
"Works for me" is all i can say.  (But i'm using Qt 5.10.1 on Archlinux)

This looks like a Qt or Plasma bug.

**Comment by michaelstingl** [comment] 2018-05-24 19:49
Same with 2.5.0 daily with Qt 5.10.1

![cursor_and_michaels_win_server](https://user-images.githubusercontent.com/214010/40510210-3c4e7f60-5f9c-11e8-8ef3-6c658445cc7b.png)

BTW Why does the "Close" button has the "X"?

**Comment by ckamm** [comment] 2018-05-25 06:09
I'm also on kubuntu 18.04 but haven't seen this issue. I was using my own builds with a different Qt version though. I'll see - at best we can find yet another tray icon workaround though. :/

**Comment by ckamm** [comment] 2018-05-25 06:52
I can reproduce with the kubuntu-18.04 iso

**Comment by ckamm** [comment] 2018-05-25 07:26
And I can confirm that my manually built version with Qt 5.9.1 using the system Qt 5.9.5 works as expected.

**Comment by ckamm** [comment] 2018-05-25 07:45
It seems to relate to some of our other tray workarounds - with `OWNCLOUD_MINIMAL_TRAY_MENU=1` it works.

**Comment by ckamm** [comment] 2018-05-25 08:18
@ogoffart I currently have no good guess as to why my 5.9 version would work when the 5.6 and 5.10 versions don't. Any ideas?

I don't want to enable the workaround we built for qdbusmenu because that triggered another set of tray bugs. :/

**Comment by ogoffart** [comment] 2018-05-25 08:51
Maybe because of a plugin that is only loaded with system's Qt (such as the KDE integration plugin). It might have a different systray implementation.

**Comment by SamuAlfageme** [comment] 2018-05-28 09:04
Reminds me somehow to https://github.com/owncloud/client/issues/5968 (see screenshot in https://github.com/owncloud/client/issues/5968#issuecomment-322803725)

**Comment by guruz** [comment] 2018-05-28 10:53
> Maybe because of a plugin that is only loaded with system's Qt (such as the KDE integration plugin).

https://unix.stackexchange.com/a/358500
https://unix.stackexchange.com/a/220110

**Comment by ogoffart** [comment] 2018-05-30 12:08
In my opinion, we should not ship Qt for distribution that have a Qt that is recent enough.
So distribution with Qt >5.6.1  (or 5.9.1?)  should simply use system Qt

**Comment by guruz** [comment] 2018-05-30 16:26
(but tray is more important than HTTP2 so @ogoffart is right)

**Comment by michaelstingl** [comment] 2018-06-07 21:08
adding @dschmidt to the discussion…

**Comment by ckamm** [comment] 2018-06-11 13:29
I've tried to verify that this is indeed about the platform plugins. Comparing the loaded libraries doesn't help unfortunately since both versions load things like `/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/org.kde.kwindowsystem.platforms/KF5WindowSystemX11Plugin.so` - though it could be that the distributed version discards it somehow. I haven't yet figured out how to tell what's actually happening with the tray.

**Comment by ckamm** [comment] 2018-06-11 13:36
What I could verify is that my self-build version also starts having a broken tray if I remove `/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/KDEPlasmaPlatformTheme.so`

**Comment by ckamm** [comment] 2018-06-13 09:57
So: Yes, using the system Qt for the distributions where it's new enough to not cause other issues would be the correct solution.

I'll also look for workarounds (the minimal tray menu works, after all), but those will likely need compromises with respect to features, or introduce new issues down the line.

**Comment by ckamm** [comment] 2018-06-14 13:00
Some debugging has shown me that `contextMenu->isVisible()` always returns false if the kde integration plugin isn't loaded. And building the context menu in `aboutToShow()` doesn't work either, similar to OSX.

**Comment by jnweiger** [comment] 2018-06-15 15:33
@michaelstingl here are linux packages built from ckamm' tray-workarounds branch. Can you try if this improves the situation on your kubuntu too. for me is seems to ease the pain.

https://download.owncloud.com/internal/repo/desktop:/testing/download/

**Comment by jnweiger** [comment] 2018-06-18 09:13
I am unhappy with my test environment: 
* The old 241 code now behaves acceptably well. The right click menu shows up on every second click.
* The new code from https://github.com/owncloud/client/pull/6586 seem to just behave the same :-(

**Comment by jnweiger** [comment] 2018-06-18 12:42
gna my tests were faulty, I'll recheck and keep an eye on KDEPlasmaPlatformTheme.so -- thanks for raising doubt :-)

**Comment by jnweiger** [comment] 2018-06-18 15:05
* cernbox 241 with qt562 is without KDEPlasmaPlatformTheme.so and right click on the tray icon is very hard. Reproducable.
* testpilotcloud 242-daily with qt562 is without KDEPlasmaPlatformTheme.so and right click on the tray icon is very hard. Reproducable.
* testpilotcloud 250-daily with qt5101 is without KDEPlasmaPlatformTheme.so and right click on the tray icon is very hard. Reproducable.
* owncloud 250-trayworkarounds with qt5101 is without KDEPlasmaPlatformTheme.so and right click on the tray icon works almost ever time. occasionally a second right click is needed, (seems to coincident with messages fading in or out)  

All of these done on one and the same VM in that order, with purge and autoremove in between. 
grepped for KDEPlasmaPlatfomTheme in ldd and lsof outpu using `grep -i pla`

there are some matches *only* for 

```
.../libcomposeplatforminputcontextplugin.so
.../platforms/libqxcb.so
.../plasmashellVr1298.4.slave-socket
```

**Comment by jnweiger** [comment] 2018-06-18 15:34
Reproduced the same behaviour after installing all pending ubuntu online updates. 

@ckamm, I now officially love your trayworkarounds branch!

**Comment by jnweiger** [comment] 2018-06-18 15:41
@ckamm, what would be the effort to backport this PR for 2.4.2 ?

**Comment by ckamm** [comment] 2018-06-19 10:54
@jnweiger Thanks for the elaborate testing! The patch applies cleanly to 2.4, would be no effort to backport.

**Comment by jnweiger** [comment] 2018-06-19 11:02
Great! Also for 2.4.* with Qt-5.6.2 ?

**Comment by ckamm** [comment] 2018-06-19 11:06
@jnweiger Backport PR is https://github.com/owncloud/client/pull/6594

**Comment by jnweiger** [comment] 2018-06-19 12:33
building test packages...
I was afraid Qt-5.6.2 might need other workarounds than 5.10.1 - if not, the better!

**Comment by jnweiger** [comment] 2018-06-19 12:52
* https://download.owncloud.com/internal/repo/ownbrander:/Qt5101:/testpilotcloud/download/
has 2.4.2 Linux builds from the backports branch trayworkaround-24 against Qt-5.10.1 
* https://download.owncloud.com/internal/repo/ownbrander:/Qt5101:/testpilotcloud/download/
has 2.4.2 Linux builds from the backports branch trayworkaround-24 against Qt-5.6.2

**Comment by jnweiger** [comment] 2018-06-19 15:48
Thumbs up for the backported PR! Approved from my side, but please doublecheck Olivier's comment.

**Comment by michaelstingl** [comment] 2018-07-02 16:42
@jnweiger @ogoffart close now

**Comment by jnweiger** [comment] 2018-07-11 10:19
Backport test done:
<pre>
#### Task

Install 242rc1 both testpilotcloud-client and owncloud-client on a ubuntu 18.04 plasma VM.

##### ubuntu
wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop:client-2.4.2rc1/Ubuntu_18.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/client-2.4.2rc1/Ubuntu_18.04/ /' > /etc/apt/sources.list.d/isv:ownCloud:desktop:client-2.4.2rc1.list"
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_18.04/ /' > /etc/apt/sources.list.d/isv:ownCloud:testpilot:testing.list"
sudo apt-get update
sudo apt purge -y owncloud-client libowncloudsync0
sudo apt purge -y testpilotcloud-client libtestpilotcloudsync0
sudo apt-get install -y owncloud-client
sudo apt-get install -y testpilotcloud-client
owncloudcmd --version
testpilotcloudcmd --version

##### leap
zypper addrepo https://download.opensuse.org/repositories/isv:ownCloud:desktop:client-2.4.2rc1/openSUSE_Leap_42.2/isv:ownCloud:desktop:client-2.4.2rc1.repo
zypper addrepo https://download.opensuse.org/repositories/isv:ownCloud:testpilot:testing/openSUSE_Leap_42.2/isv:ownCloud:testpilot:testing.repo
zypper refresh
zypper rm -y owncloud-client libowncloudsync0
zypper rm -y testpilotcloud-client libtestpilotcloudsync0
zypper install -y owncloud-client
zypper install -y testpilotcloud-client
owncloudcmd --version
testpilotcloudcmd --version


Both systems
* log in on the desktop
* left click the system menue: a dialog opens containing plasma search.
* run the installatin procedures above. the correct cliebt version numbers are printed at the end.
Both systems, both clients:
* right click the tray icon multople times. a dialog containing quit opens and closes
* left click the icon, the settings window opens.
* use right click -> quit to end the client.
</pre>
Success. Thank you all.Closing.

**Closed by jnweiger** 2018-07-11 10:19 UTC
Labels: Linux, Platform Specific, ReadyToTest, blue-ticket, packaging

**Comment by jnweiger** [comment] 2018-07-12 10:36
Backport test done:
<pre>
#### Task

Install 242rc1 both testpilotcloud-client and owncloud-client on a ubuntu 18.04 plasma VM.

##### ubuntu
wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop:client-2.4.2rc1/Ubuntu_18.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/client-2.4.2rc1/Ubuntu_18.04/ /' > /etc/apt/sources.list.d/isv:ownCloud:desktop:client-2.4.2rc1.list"
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_18.04/ /' > /etc/apt/sources.list.d/isv:ownCloud:testpilot:testing.list"
sudo apt-get update
sudo apt purge -y owncloud-client libowncloudsync0
sudo apt purge -y testpilotcloud-client libtestpilotcloudsync0
sudo apt-get install -y owncloud-client
sudo apt-get install -y testpilotcloud-client
owncloudcmd --version
testpilotcloudcmd --version

##### leap
zypper addrepo https://download.opensuse.org/repositories/isv:ownCloud:desktop:client-2.4.2rc1/openSUSE_Leap_42.2/isv:ownCloud:desktop:client-2.4.2rc1.repo
zypper addrepo https://download.opensuse.org/repositories/isv:ownCloud:testpilot:testing/openSUSE_Leap_42.2/isv:ownCloud:testpilot:testing.repo
zypper refresh
zypper rm -y owncloud-client libowncloudsync0
zypper rm -y testpilotcloud-client libtestpilotcloudsync0
zypper install -y owncloud-client
zypper install -y testpilotcloud-client
owncloudcmd --version
testpilotcloudcmd --version


Both systems
* log in on the desktop
* left click the system menue: a dialog opens containing plasma search.
* run the installatin procedures above. the correct cliebt version numbers are printed at the end.
Both systems, both clients:
* right click the tray icon multople times. a dialog containing quit opens and closes
* left click the icon, the settings window opens.
* use right click -> quit to end the client.
</pre>
Success. Thank you all.Closing.
