### ISSUE TITLE
[Client 1.6.4] Clean sync is not allowed for a user using the same server and same directory

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#2317] opened 2014-10-16 09:05 UTC
While using the modify account option of the client, if you changes the server address or the username, the option of making a clean sync appears, but it doesn't when those doesn't change.
If  everything went smoothly in the synced directory there is no point to download again every file in the server. This is ideally, but sometimes there could be errors, cancelled files or something went wrong because some reason, sometimes the user maybe just want to restart that synced directory, removing everything and redownloading from server.
I suggest to add the clean sync option for this case too.

**Comment by ogoffart** [comment] 2018-08-07 05:44
Now, we have multi account and we also check the sha-1 if the files already exist.
This is also a duplicate of https://github.com/owncloud/client/issues/1456 , it seems

**Closed by ogoffart** 2018-08-07 05:44 UTC
Labels: Enhancement
