### ISSUE TITLE
Lots of Documents folders added to Windows Explorer left bar

### ISSUE THREAD

**Issue by Yamakasi** [owncloud/client#4329] opened 2016-01-01 20:57 UTC
See the attachent what happens.

I have tested this at Stable 2.1 and Nightly 1 jan 2016, both the same.

Sometimes the links are removed and added again
![owncloud_lots_of_document_links](https://cloud.githubusercontent.com/assets/4869479/12072153/a9617ea2-b0d2-11e5-918c-191f4eb9cc17.PNG)

**Comment by guruz** [comment] 2016-01-04 12:19
Are you re-running the wizard?

**Comment by ogoffart** [comment] 2016-01-19 10:20
Please use the issue template when reporting: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

What are the steps to reproduce?

**Comment by fcharron** [comment] 2016-02-26 22:18
I also experience the same thing.

### Expected behaviour
The Documents entry should only be present once in the quick-access zone of Windows Explorer.

### Actual behaviour
It is displayed hundreds of times.

### Steps to reproduce
1. Relocate "Documents" to owncloud folder (by right-clicking the Documents folder, going in "Properties"->"Location", entering a path inside owncloud folder and pressing the "Move..." button.
2. Use Windows normally (saving documents to the Documents folder periodically).
3. The left section of Windows explorer gradually gets filled with copies of Documents.

### Server configuration (hosted by IT department, I don't have any information aside ownCloud version)
Operating system: ?
Web server: ?
Database: ?
PHP version: ?
ownCloud version: 8.2
Storage backend: ?

### Client configuration
Client version: 2.1.0 (build 5683)
Operating system: Windows 10 Pro 64-bit
OS language: English
Installation path of client: "C:\Program Files (x86)\ownCloud"

### Logs

Contains too much private information, will not provide them.

**Comment by fcharron** [comment] 2016-03-07 21:56
Do you still need more information about the issue? Is it still necessary to keep the "Needs Info" tag?

**Comment by ogoffart** [comment] 2016-03-16 15:49
I tried to reproduce this issue without success. I only see one "Documents" folder.

**Comment by guruz** [comment] 2016-04-19 12:34
@TerryHewitt has the same problem on https://github.com/owncloud/client/issues/4702

> 
Note: I have moved "Documents" (and Desktop, Downloads and Pictures) from c:\users\documents" to "D:\users\documents" etc. using the standard Windows 10 features to do this (right click on Documents, then properties, then Location and then click on move...

@Yamakasi @ogoffart Did you also do this ^^ like @TerryHewitt and @fcharron did?

**Comment by guruz** [comment] 2016-04-19 12:35
Please also see more information (open app) on https://github.com/owncloud/client/issues/4702

**Comment by joel6890** [comment] 2016-04-20 23:25
I have the same issue with Windows 10 Explorer -- see attached image. Running the latest version of the desktop sync client.

Server: Linux Mint 32-bit; Nginx; php-fpm; mariadb.

![owncloudbug](https://cloud.githubusercontent.com/assets/2159416/14693475/3c04cf2e-072d-11e6-92c4-dc612c30affc.PNG)

**Comment by guruz** [comment] 2016-04-21 06:53
@joel6890 Were you also doing what is described in the comment above? https://github.com/owncloud/client/issues/4329#issuecomment-211902744

**Comment by joel6890** [comment] 2016-04-22 14:21
@guruz  No, I have not moved the Documents folder from its default location. I simply added manual sync destinations instead of just rolling with the default owncloud root folder sync setup; and synced my local Documents folder with the OwnCloud Documents folder.

**Comment by apg1980** [comment] 2016-04-28 16:47
i got the same after moving the documents default location into the owncloud sync folder.

**Comment by MTRichards** [comment] 2016-05-20 14:59
Could not reproduce. I moved the documents and changed sync locations, I couldn't make it happen. Maybe I didn't do the same thing...missing a step?

**Comment by dragotin** [comment] 2016-05-20 15:00
@ckamm Can you check this?

**Comment by joel6890** [comment] 2016-05-25 20:24
To repro, once you have the default Windows Documents folder synced with the OwnCloud Documents folder, simply leave an Explorer window open; then open / edit a file within Documents, and save it. After the file is changed, the OwnCloud sync process begins; and that's when the multiple copies of the Documents shortcut appear in the Favorites bar.

Or just make folders within Documents... add files... rename them, and rename folders... And watch the behaviour in the left bar. When multiple copies of Documents appear, click on one of them to collapse the list back to one as it should be.

**Comment by mcastroSG** [comment] 2016-05-26 07:50
Hi hi:

Finally i was able to reproduce it. Just to add some light to this problem:

**Steps Executed**

1.- On a clear install of owncloud client set as Shared Sync folder  `C:\Users\nonen\Documents` that matches with the folder that is linked just behind This PC icon:

![capture](https://cloud.githubusercontent.com/assets/18436398/15567442/b5f0a2d0-2326-11e6-92de-c02ad23b19bf.PNG)

2.- Include a file or folder at shared sync folder

**Results

Several copies of Shared sync folder appears under This PC section:

![capture2](https://cloud.githubusercontent.com/assets/18436398/15567465/d1e6224e-2326-11e6-9af9-149bcae1e93f.PNG)

Is a bug that just appear under W10, I could not be able to reproduce it on W81 or W7, maybe because overlay icon does not appear over Shared sync root folder on those OS but W10 does.

**Comment by ckamm** [comment] 2016-06-06 09:00
I don't know how to approach this problem. I'd guess it relates to the Windows explorer integration and I'll check it out, but would prefer if someone who's already set up with Win10 and building the integration takes care of this.

@dragotin @jturcotte

**Comment by ckamm** [comment] 2016-06-06 09:25
I checked the code and don't see where the "This PC" entry comes from. @danimo, do you know?

**Comment by jturcotte** [comment] 2016-06-06 11:56
@mcastroSG But this only happens if you chose the builtin "Documents" folder as the one to sync, right?

This might actually be a bug in Windows that the client triggers, could be related to the desktop.ini file or something like that.

**Comment by mcastroSG** [comment] 2016-06-06 11:59
@jturcotte just in case you choose any location that appears under This PC Icon.

**Comment by dragotin** [comment] 2016-06-15 11:36
![favbroken](https://cloud.githubusercontent.com/assets/1070214/16078235/066ff4c2-32fe-11e6-928b-07365ac808c7.png)

... as observed by @cdamken this happens if the Windows Homedir is synced.

**Comment by joel6890** [comment] 2016-06-28 16:10
My OwnCloud client just updated yesterday to version 2.2.2 (build 6192) and this problem went away. There is no longer any overlay icon over files and folders showing sync status either, but I kind of prefer that anyhow; keeps the interface cleaner (and faster; those status icons seemed to slow down file or folder creation, making it freeze momentarily).

**Comment by mcastroSG** [comment] 2016-06-28 16:24
@joel6890 I was able to get overlay icons agains just restarting my computer after upgrade Desktop Client and I´m not able to reproduce this issue again. May you retest to be sure we can close this issue ¿?

**Comment by guruz** [comment] 2016-06-28 16:51
@mcastroSG Let's keep this open, there's several people reporting it still..

**Comment by joel6890** [comment] 2016-06-28 17:23
@mcastroSG [as I commented over in this issue](https://github.com/owncloud/client/issues/5015), after reboot the issue is back just as before. Overlay icons seem to be what is causing the trouble.

**Comment by jturcotte** [comment] 2016-06-28 18:30
@joel6890 Thanks for the info. If you prefer not having overlay icons for now as a workaround, you can get this by:

- uninstalling
- reinstalling and making sure that you disable the explorer integration option in the installer
- reboot

**Comment by pixelriot** [comment] 2016-11-10 08:39
Just for confirmation and to keep this one active :)

I'm running NC client version **2.2.4** (build 2) on Windows 10 and the problem still occurs. Overlay icons are activated.

![unbenannt](https://cloud.githubusercontent.com/assets/21098503/20169759/92b13b22-a729-11e6-869a-fabd8de72fa2.PNG)

**Comment by jturcotte** [comment] 2016-12-08 17:57
I couldn't reproduce the issue, but it looks like both OneDrive and Box show the same issue: https://answers.microsoft.com/en-us/windows/forum/windows_10-files/multiple-duplicate-folders-under-this-pc-in-file/43375406-e7fd-4789-92f8-ff4a8a403ed6

Somebody on page 2 proposes to enable "Show All Folders" in view options to work around the issue.

So I'm assuming that this is a Windows issue 😕

**Closed by jturcotte** 2016-12-08 17:57 UTC
Labels: bug, sev2-high
