### ISSUE TITLE
Make activity log filter

### ISSUE THREAD

**Issue by cloo** [owncloud/client#4067] opened 2015-11-03 17:52 UTC
Quite often you are only interested in error logs. Then in the client UI you need to scroll down the list endlessly and try not to miss them, and not to get confused. 
I suggest to make a filter (a switch, separate tabs, or any other kind), allowing to view errors only. Accordingly successful downloads and successful uploads should be viewable separately..

**Comment by guruz** [comment] 2015-11-03 21:39
FYI @dragotin @jancborchardt

**Comment by jancborchardt** [comment] 2015-11-04 12:53
This is a duplicate of `In »Activity«, keep errors at the top` #1745 – I set that to 2.2 now (as you did with this issue @guruz) and hope it will be done soon.

**Closed by jancborchardt** 2015-11-04 12:53 UTC
Labels: enhancement - proposed
