### ISSUE TITLE
owncloud Windows Client Randomly deleting files (while they stay on the server)

### ISSUE THREAD

**Issue by thavincinew** [owncloud/client#3182] opened 2015-05-04 10:17 UTC
### Expected behaviour
Tell us what should happen

### Actual behaviour
Randomly the client starts removing files.

### Steps to reproduce
Unknown

### Server configuration
Operating system:
FreeBSD 9.3-RELEASE-p13

Web server: 
Server version: Apache/2.4.12

Database:
mysql  Ver 14.14 Distrib 5.6.23

PHP version:
PHP 5.6.7

ownCloud version:
ownCloud 8.0.2 (stable) 

Storage backend:
ZFS

### Client configuration
Client version:
1.8.0 (build 4893)

Operating system:
Windows 7 x64 & windows 10 preview

OS language:
English

Installation path of client:
Default 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment] 2015-05-04 10:49
Are they still on the server?

We have a rc2 out soon which brings them back to the client.

**Comment by thavincinew** [comment] 2015-05-04 11:46
It seems the files are indeed still on the server!

**Comment by dragotin** [comment] 2015-05-04 11:50
ok, sounds like a duplicate of #3102 

@thavincinew pls. wait until we release 1.8.1 rc2 in a couple of minutes, install it and see that it all gets fixed for you.

**Comment by thavincinew** [comment] 2015-05-04 14:03
Appologies for the stupid question but where may i find the setup for this?

**Comment by danimo** [comment] 2015-05-04 14:05
https://owncloud.org/install/#testing (Click "testing packages").

**Comment by guruz** [comment] 2015-05-04 14:16
Does it bring the files back?

**Comment by guruz** [comment] 2015-05-05 15:19
@thavincinew Did you have any sucess?

**Comment by thavincinew** [comment] 2015-05-07 07:09
My apologies on the long waited response, there was 30G of data that needed to sync back.
For the most part it did seem to improve things and pull down the data.

There did appear to be some files missing entirely and i ingested a backup and so far so good. I cannot validate this comment yet in regards to what happened.

**Comment by dragotin** [comment] 2015-05-13 11:36
ok, thanks for letting us know. Closing.

**Closed by dragotin** 2015-05-13 11:36 UTC
Labels: bug, Needs info, ReadyToTest
