### ISSUE TITLE
client 252rc2 on macos 10.14 shows multible tabs in the settings windows

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6997] opened 2019-01-22 15:55 UTC
In a tabbed window pane, only one tab should be active at a time. 

here is a screenshot where two tabs are open
![image](https://user-images.githubusercontent.com/1108546/51547196-10458600-1e66-11e9-8438-c458954b5d57.png)

Reproduced by rapid clicking back and forth between 'Activity' and the sync account tab 'demo@demo.owncloud.org' while the client is in disovery phase. It works only once after starting the client.

Once this happens, the lower window contents can be changed by clicking on 'General' or 'Network'.
Klicking once more on 'Activity' resolves the issue.

**Comment by guruz** [comment] 2019-01-30 12:52
I remember you reported this one before.

**Comment by guruz** [comment] 2019-06-04 10:03
Moving this as I'm very sure this is not a regression and was always only reported by @jnweiger

**Comment by guruz** [comment] 2019-06-04 10:04
Well, it was also reported by @HanaGemela in https://github.com/owncloud/client/issues/7168 .. heh

**Comment by HanaGemela** [comment] 2019-07-15 15:17
Still occurs in 2.6.0 alpha2

![image](https://user-images.githubusercontent.com/49001702/61227361-7380e880-a724-11e9-9141-0ceda65734e1.png)

**Comment by HanaGemela** [comment] 2019-07-16 14:08
This looks like two Account tab are selected at the same time (2.6.0alpha2 (build 12128))

![image](https://user-images.githubusercontent.com/49001702/61301261-e1401980-a7e3-11e9-8c2b-3d2e3c54e033.png)

**Comment by TheOneRing** [comment] 2020-03-17 09:58
Should be fixed in latest builds

**Comment by HanaGemela** [comment] 2020-03-18 16:27
I can't recreate in 2.6.3. Last time it was reported from the build 2.6.0alpha2. Closing now but will keep an eye on it

**Closed by HanaGemela** 2020-03-18 16:27 UTC
Labels: Design & UX, macOS
