### ISSUE TITLE
[Windows 2.2.0] Translation issue in GUI

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#4886] opened 2016-05-22 08:46 UTC
### Expected behaviour
Use translated words in GUI

### Actual behaviour
Uses untranslatet words

### Steps to reproduce
1. open client gui
2. copy files to folder to start uploading from client to cloud
3. see untranslated "minute (s)", ...

### Client configuration
Client version: 2.2.0 Stable

Operating system: Windows 7 64 Bit

OS language: German

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Picture:
![2016-05-15 17_27_11-owncloud](https://cloud.githubusercontent.com/assets/2804301/15453153/78084cee-200a-11e6-85b5-d255e67d2936.jpg)

**Comment by RobinGeuze** [comment] 2016-05-25 07:14
Isn't this a duplicate of #4855 ?

**Comment by danimo** [comment] 2016-05-25 07:38
Indeed

**Closed by danimo** 2016-05-25 07:38 UTC
Labels: ReadyToTest
