### ISSUE TITLE
[OS X Yosemite 10.10.3 (Beta)] Install fails 

### ISSUE THREAD

**Issue by thedanielmatt** [owncloud/client#2948] opened 2015-03-11 16:22 UTC
Attempting to install OS X Desktop client on OS X 10.10.3 (beta).

Customizing the installation to omit the ownCloud package succeeds (installing the Finder plugin only).

sudo installer -verboseR -pkg ~/Downloads/ownCloud-1.8.0.2078beta2.pkg -target / -dumplog
installer: Package name is ownCloud Client
Mar 11 12:15:09 localhost installer[19850] <Debug>: Product archive /Users/daniel/Downloads/ownCloud-1.8.0.2078beta2.pkg trustLevel=202
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
Mar 11 12:15:10 localhost installer[19850] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: location = file://localhost
Mar 11 12:15:10 localhost installer[19850] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/daniel/Downloads/ownCloud-1.8.0.2078beta2.pkg#ownCloud.pkg
Mar 11 12:15:10 localhost installer[19850] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/daniel/Downloads/ownCloud-1.8.0.2078beta2.pkg#Finder_Plugin.pkg
Mar 11 12:15:10 localhost installer[19850] <Debug>: Set authorization level to root for session
Mar 11 12:15:10 localhost installer[19850] <Debug>: Will use PK session
Mar 11 12:15:10 localhost installer[19850] <Info>: Starting installation:
installer:PHASE:Preparing the disk…
Mar 11 12:15:10 localhost installer[19850] <Notice>: Configuring volume "Daniel HD"
Mar 11 12:15:10 localhost installer[19850] <Info>: Preparing disk for local booted install.
Mar 11 12:15:10 localhost installer[19850] <Notice>: Free space on "Daniel HD": 77.5 GB (77495320576 bytes).
Mar 11 12:15:10 localhost installer[19850] <Notice>: Create temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.19850bXRO5L"
installer:PHASE:Preparing ownCloud Client…
Mar 11 12:15:10 localhost installer[19850] <Notice>: IFPKInstallElement (2 packages)
Mar 11 12:15:10 localhost installer[19850] <Debug>: Using authorization level of root for IFPKInstallElement
installer:PHASE:Waiting for other installations to complete…
Mar 11 12:15:10 localhost installer[19850] <Notice>: PackageKit: Enqueuing install with framework-specified quality of service (utility)
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%27.377528
installer:PHASE:Writing files…
installer:PHASE:Validating packages…
Mar 11 12:15:11 localhost installer[19850] <Debug>: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “ownCloud-1.8.0.2078beta2.pkg”." UserInfo=0x7fdc82800470 {NSFilePath=./preinstall, NSURL=file://localhost/Users/daniel/Downloads/ownCloud-1.8.0.2078beta2.pkg#ownCloud.pkg, PKInstallPackageIdentifier=com.ownCloud.client, NSLocalizedDescription=An error occurred while running scripts from the package “ownCloud-1.8.0.2078beta2.pkg”.}
installer:%97.750000
Mar 11 12:15:12 localhost installer[19850] <Error>: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

**Comment by lmaestro** [comment] 2015-03-12 08:17
I can't reproduce on OS X 10.10.2

`````
➜  ~  sudo installer -verboseR -pkg ~/Downloads/ownCloud-1.8.0.2078beta2.pkg -target / -dumplog
Password:
installer: Package name is ownCloud Client
Mar 12 09:14:32 Lucias-Mac-mini.solidgear.prv installer[1212] <Debug>: Product archive /Users/lmaestro/Downloads/ownCloud-1.8.0.2078beta2.pkg trustLevel=202
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: location = file://localhost
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/lmaestro/Downloads/ownCloud-1.8.0.2078beta2.pkg#ownCloud.pkg
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/lmaestro/Downloads/ownCloud-1.8.0.2078beta2.pkg#Finder_Plugin.pkg
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Debug>: Set authorization level to root for session
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Debug>: Will use PK session
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Info>: Starting installation:
installer:PHASE:Preparing the disk…
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: Configuring volume "SSD Lucy"
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Info>: Preparing disk for local booted install.
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: Free space on "SSD Lucy": 12.59 GB (12585541632 bytes).
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: Create temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.1212K6n5JO"
installer:PHASE:Preparing ownCloud Client…
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: IFPKInstallElement (2 packages)
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Debug>: Using authorization level of root for IFPKInstallElement
installer:PHASE:Waiting for other installations to complete…
Mar 12 09:14:33 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: PackageKit: Enqueuing install with framework-specified quality of service (utility)
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%21.149738
installer:PHASE:Writing files…
installer:%54.448474
installer:PHASE:Moving items into place…
installer:%94.989102
installer:PHASE:Cleaning up…
installer:PHASE:Validating packages…
Mar 12 09:14:36 Lucias-Mac-mini.solidgear.prv installer[1212] <Debug>: LSExceptions [0x7ff2e0716c80] loaded
Mar 12 09:14:36 Lucias-Mac-mini.solidgear.prv installer[1212] <Info>: PackageKit: Registered bundle file:///Applications/owncloud.app/ for uid 0
Mar 12 09:14:36 Lucias-Mac-mini.solidgear.prv installer[1212] <Info>: PackageKit: Registered bundle file:///Applications/owncloud.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/ for uid 0
installer:%97.750000
installer:STATUS:Running installer actions…
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: Running install actions
installer:STATUS:
installer:PHASE:Finishing the Installation…
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: Removing temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.1212K6n5JO"
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: Finalize disk "SSD Lucy"
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: Notifying system of updated components
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: 
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: **** Summary Information ****
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>:   Operation      Elapsed time
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: -----------------------------
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>:        disk      0.05 seconds
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>:      script      0.00 seconds
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>:        zero      0.01 seconds
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>:     install      3.11 seconds
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>:     -total-      3.17 seconds
Mar 12 09:14:37 Lucias-Mac-mini.solidgear.prv installer[1212] <Notice>: 
installer:STATUS:
installer:%100.000000
installer:PHASE:The software was successfully installed.
installer: The upgrade was successful.

**Comment by guruz** [comment] 2015-03-13 15:44
@thedanielmatt Could you retry with download.owncloud.com/desktop/daily/ownCloud-1.8.0.2129-nightly20150313.pkg ? I changed the return code of the pre-install script to always return success (6c4b7f1479eff4b4c90bab0c82d3e6a7c1bfc8ed)

**Comment by thedanielmatt** [comment] 2015-03-13 16:01
Looks like you nailed it - installed and launched successfully:

```
11:29:30 Fri Mar 13 [daniel@Box-O-Daniel] ~
do this: sudo installer -verboseR -dumplog -pkg ~/Downloads/ownCloud-1.8.0.2129-nightly20150313.pkg -target /
Password:
Sorry, try again.
Password:
installer: Package name is ownCloud Client
Mar 13 11:56:02 Box-O-Daniel installer[6620] <Debug>: Product archive /Users/daniel/Downloads/ownCloud-1.8.0.2129-nightly20150313.pkg trustLevel=202
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: location = file://localhost
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/daniel/Downloads/ownCloud-1.8.0.2129-nightly20150313.pkg#ownCloud.pkg
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Debug>: -[IFDInstallController(Private) _buildInstallPlan]: file://localhost/Users/daniel/Downloads/ownCloud-1.8.0.2129-nightly20150313.pkg#Finder_Plugin.pkg
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Debug>: Set authorization level to root for session
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Debug>: Will use PK session
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Info>: Starting installation:
installer:PHASE:Preparing the disk…
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Notice>: Configuring volume "Daniel HD"
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Info>: Preparing disk for local booted install.
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Notice>: Free space on "Daniel HD": 75.87 GB (75867840512 bytes).
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Notice>: Create temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.6620OzTssm"
installer:PHASE:Preparing ownCloud Client…
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Notice>: IFPKInstallElement (2 packages)
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Debug>: Using authorization level of root for IFPKInstallElement
installer:PHASE:Waiting for other installations to complete…
Mar 13 11:56:03 Box-O-Daniel installer[6620] <Notice>: PackageKit: Enqueuing install with framework-specified quality of service (utility)
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%27.498125
installer:PHASE:Writing files…
installer:PHASE:Validating packages…
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Debug>: LSExceptions [0x7f98717b1b50] loaded
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Info>: PackageKit: Registered bundle file:///Applications/owncloud.app/ for uid 0
installer:%97.262500
installer:PHASE:Registering updated applications…
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Info>: PackageKit: Registered bundle file:///Applications/owncloud.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/ for uid 0
installer:%97.750000
installer:STATUS:Running installer actions…
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>: Running install actions
installer:STATUS:
installer:PHASE:Finishing the Installation…
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>: Removing temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.6620OzTssm"
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>: Finalize disk "Daniel HD"
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>: Notifying system of updated components
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>: 
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>: **** Summary Information ****
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>:   Operation      Elapsed time
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>: -----------------------------
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>:        disk      0.04 seconds
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>:      script      0.00 seconds
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>:        zero      0.01 seconds
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>:     install      2.09 seconds
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>:     -total-      2.14 seconds
Mar 13 11:56:05 Box-O-Daniel installer[6620] <Notice>: 
installer:STATUS:
installer:%100.000000
installer:PHASE:The software was successfully installed.
installer: The upgrade was successful.
```

**Comment by guruz** [comment] 2015-03-13 16:38
Great! :)

**Closed by guruz** 2015-03-13 16:39 UTC
Labels: bug, ReadyToTest
