### ISSUE TITLE
[Feature Request] Enhance Desktop Notifications

### ISSUE THREAD

**Issue by stkjj** [owncloud/client#5635] opened 2017-03-20 14:02 UTC
presently Desktop notifications on Mac/Win/Linux show activities of synced files/folders, with no further actions which can be taken. 

Enhancement could be to have an action button (configurable in Mac OS X) which takes one to the just updated file/folder in the Finder/Explorer to take a closer look what is new or changed.

**Comment by guruz** [comment] 2017-03-21 07:18
@michaelstingl Is this a dup?

**Comment by michaelstingl** [comment] 2017-03-21 16:58
more or less a duplicate of https://github.com/owncloud/client/issues/4410 - needs to be extended for other platforms…

**Closed by michaelstingl** 2017-03-21 16:58 UTC
Labels: Design & UX
