### ISSUE TITLE
Syncing only the content of a subdirectory not possible

### ISSUE THREAD

**Issue by polrus** [owncloud/client#6028] opened 2017-09-13 09:30 UTC
### Expected behaviour
Let's say I have a primary machine where I sync all my Documents directory with all files and sub-directories
I would like to replicate and sync a subdirectory Documents/Important on a secondary machine.
 
### Actual behaviour
Folder Documents/Important is replicated but also all files that are directly in Documents

### Steps to reproduce
1. Proceed with the expected behabiour scenario on primary machine
2. On the secondary machine set up new replication on the OC client for a subdirectory and start replication
3. You will see that apart from the subdirectory Important and it's content all files in Documents/* are synced - which is not desired

### Server configuration
Operating system:
OpenSuse 12.3
Web server: 
Apache 
Database:
Maria
PHP version:
5.6.1
ownCloud version:
10.0.2 (stable) 
Storage backend (external storage):
internal
### Client configuration
Client version:
2.3.3
Operating system:
Opensuse Leap 42.3
OS language:
Eng
Qt version used by client package (Linux only, see also Settings dialog):
5.6.2
Client package (From ownCloud or distro) (Linux only):
Opensuse 42.3 KDE/Extra
Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by SamuAlfageme** [comment] 2017-09-14 08:24
@polrus can you try to be more specific. e.g. include screenshots of what's expected and happening in your scenario? syncing subdirs should not collide with their parents (unless we're talking about the root dir; which is a well known current limitation of the client: https://github.com/owncloud/client/issues/3632)

**Comment by polrus** [comment] 2017-09-14 08:58
Ahh than its a duplicate report, sry

Dnia 14 września 2017 10:24:06 CEST, Samuel Alfageme <notifications@github.com> napisał(a):
>@polrus can you try to be more specific. e.g. include screenshots of
>what's expected and happening in your scenario? syncing subdirs should
>not collide with their parents (unless we're talking about the root
>dir; which is a well known current limitation of the client:
>https://github.com/owncloud/client/issues/3632)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/client/issues/6028#issuecomment-329410821

-- Wysłane za pomocą K-9 Mail.

**Comment by ogoffart** [comment] 2017-09-14 12:50
Closing as duplicate of https://github.com/owncloud/client/issues/3632

**Closed by ogoffart** 2017-09-14 12:50 UTC
Labels: Needs info
