### ISSUE TITLE
owncloudcmd: exit code <> 0 on error

### ISSUE THREAD

**Issue by schnidrig** [owncloud/client#4144] opened 2015-11-16 12:46 UTC
It would be very useful, if the exit code of owncloudcmd where <> 0 whenever an error occurred. 
That way it would be much easier to write test scrips that "sync until successful" with owncloudcmd. 

Currently one has to parse the log. Since there are lots of entirely different error messages to look for, that is not easy to do.

**Comment by nickvergessen** [comment] 2015-11-16 15:22
Duplicate of https://github.com/owncloud/client/issues/3936

**Closed by nickvergessen** 2015-11-16 15:22 UTC
