### ISSUE TITLE
[client/vista x64] Shell Overlay Icon handlers cause delay in verclsid.exe

### ISSUE THREAD

**Issue by gpbenton** [owncloud/client#2680] opened 2015-01-08 13:24 UTC
My computer started having delays when the current window would not respond for about 30s.

Looking through the task manager, I noticed that verclsid.exe was running whenever  a window was not responding.  Having determined that verclsid.exe was a windows program for checking shell extensions, I used autoruns to disable shell extensions, until the problem disappeared.

Disabling all the items like

OCError	Windows Shell Overlay Icon Handler	ownCloud Inc.	c:\program files (x86)\owncloud\shellext\ocoverlays_x64.dll

fixed the problem.  Re-enabling these caused the problem to re-occur.

**Comment by gpbenton** [comment] 2015-01-08 13:25
I currently have client version 1.7.1

**Comment by guruz** [comment] 2015-01-26 16:20
@gpbenton Do you want to try the nightly build http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4644-nightly20150126-setup.exe ? Does it fix the issue? 

I remember @ogoffart and @ckamm changing code there to have less locks..

**Comment by danimo** [comment] 2015-01-26 16:23
@gpbenton hang on, the code is not yet in the nightlies.

**Comment by gpbenton** [comment] 2015-01-26 16:36
I'm happy to test whenever something is available.

**Comment by guruz** [comment] 2015-01-30 09:18
Possibly related: https://github.com/owncloud/client/issues/2576

**Comment by guruz** [comment] 2015-01-30 12:45
We're about to release the beta1, please try with that..

**Comment by danimo** [comment] 2015-02-04 07:03
As beta1 is delaying for organizational reasons, could you try http://download.owncloud.com/desktop/daily/owncloud-1.8.0.4676-nightly20150204-setup.exe?

**Comment by gpbenton** [comment] 2015-02-04 11:12
The problem still occurs with this version.  Here is how I tested it.

1) Re-enable the overlay icons entries using autoruns and reboot.  The problem re-occurred as expected.

2) Install the above binary, using the uninstall previous versions option, and reboot.  The problem remained as before.  There was no discernible change from v 1.7.1  Every time I opened an existing file for the first time since reboot, versclid.exe ran for (at least) 30s before the file opened.

3)  I disabled the overlay icons using autoruns and rebooted.  As with v1.7.1 the problem went away.

4) Just for completeness, I uninstalled the test version and then re-installed v1.7.1 without the 'status icons for Windows Explorer' checked.  This has been working fine without alteration, presumably because the offending items are not installed.

I hope this helps.

**Comment by jturcotte** [comment] 2015-02-05 17:53
This gives an overview of the issue: http://searchwindowsserver.techtarget.com/tip/Windows-security-update-may-cause-shell-extensions-to-fail

Together with this which talks about the "Allow list": http://support.microsoft.com/kb/918165

We would need to add the following DWORD keys in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Cached:

{841A0AAD-AA11-4B50-84D9-7F8E727D77D7} {000214E6-0000-0000-C000-000000000046} 0x401
{0960F090-F328-48A3-B746-276B1E3C3722} {000214E6-0000-0000-C000-000000000046} 0x401

But the permissions don't allow even an administrator to modify those keys directly since to are limited to the TrustedInstaller user. So the real fix would be to go through our signed installer I guess.

Let me know what you think.

**Comment by gpbenton** [comment] 2015-02-05 18:26
I'm not sure if the last comment was asking for my opinion, but the fix seems to make sense to me.  

I don't think I can do anything without a new installer, but I'm happy to test again when its available.

**Comment by jturcotte** [comment] 2015-02-06 09:01
Ok, so according to this, an application or its installer isn't supposed to mess up with resources owned by the TrustedInstaller service, only the OS should: http://stackoverflow.com/questions/1551471/trustedinstaller-is-preventing-registry-writes-to-hkcr-directshow-mediaobjects-c

This gives a bit more details on the reason: https://technet.microsoft.com/en-gb/magazine/2007.06.acl.aspx

So that probably won't work, but I'm wondering why they were proposing this as a workaround in http://support.microsoft.com/kb/918165

It's possible that I don't have access to modify it on Windows8, but that it was possible on Vista (where it would matter). Could anybody with a Vista machine quickly check if they can add a simple key in <HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Cached>? Else I can try to setup a machine to try it out.

**Comment by gpbenton** [comment] 2015-02-06 10:40
I can indeed add keys to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Cached using regedit on Vista:-
![Uploading Screenshot 2015-02-06 10.24.12.png . . .](https://www.dropbox.com/s/ghzfl43eucl1nbn/Screenshot%202015-02-06%2010.24.12.png?dl=0)

Should I try adding these manually after re-installing the owncloud client, to see if this solves the problem?

**Comment by danimo** [comment] 2015-02-06 10:44
@gpbenton Please do

**Comment by gpbenton** [comment] 2015-02-06 12:34
No change I'm afraid.  I uninstalled then installed ownDrive with 'status icons' checked and then added the registry keys.  But the problem still occurred before and after a reboot.

I have uploaded a screenshot of the registry keys to dropbox, in case there is a problem, but I did a copy and paste.  I did set the value to 1 like the other keys.

https://www.dropbox.com/s/gtk2szt6qgjw3g4/Screenshot%202015-02-06%2012.13.07.png?dl=0

**Comment by jturcotte** [comment] 2015-02-06 13:23
Ok, thanks for trying it out. The keys names look OK so we'll have to fiddle a bit or try to find a different way.

**Comment by jturcotte** [comment] 2015-02-11 15:47
We still need to update the binaries in the repository before this ends in the nightly builds.

**Comment by lmaestro** [comment] 2015-02-16 08:18
@gpbenton Can try to reproduce it in the latest version https://owncloud.org/install/#testing ?

**Comment by gpbenton** [comment] 2015-02-18 17:24
ownCloud-1.8.0.4730beta1-setup seems to have fixed the problem.  I managed to reproduce the problem with v1.7.1, then installed this version and have not had any problems, with the overlay icons installed.  I did see versclid.exe appear briefly in the task manager list, but it disappeared quickly.

**Comment by lmaestro** [comment] 2015-02-18 17:29
@gpbenton Thaks to test it. I close this issue if anyone is able to reproduce, please reopen it. Thx

**Closed by lmaestro** 2015-02-18 17:29 UTC
Labels: bug, gold-ticket, Needs info, ReadyToTest, sev3-medium
