### ISSUE TITLE
Branded install should kick off login prompt after installation completes

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#2752] opened 2015-01-28 14:03 UTC
Challenge with not auto-initiating connection assistant after installing ownCloud client - in this case, in a branded client with URL pre-configred.

Expectation: Once the client is installed, the connection wizard pops up and starts the connection process for the user.

What happens:
For a fresh install, once the client is installed, it does not go directly to the connection assistant, prompting for the loggin/password but instead the user has to fins the icon in the task bar, reopen the GUI, Go to the update account menu and finally gets access to the connection assistant. I know our users will never go that far. This is particularly problematic since once the install is done, the user expects everything to be working and that the synchronization will start automatically while instead, the client just sits doing nothing. I know it’s not customization but rather development but it would be really helpful to us since we are planning to deploy the client with a script and our end-users will therefore have not direct hotline assistance.

**Comment by danimo** [comment] 2015-01-28 14:25
Which platform?

**Comment by MTRichards** [comment] 2015-01-28 14:26
@rperezb ?

**Comment by rperezb** [comment] 2015-01-28 18:26
Checking, in the meantime, I have reproduced it on MAC

**Comment by rperezb** [comment] 2015-01-29 08:22
Checked, both Windows and Mac; being more important on Windows. thx

**Comment by danimo** [comment] 2015-01-29 16:55
@rperezb On Windows, it should just work like that: Once the installer is done, the app starts up with a wizard.

OS X used to do that, but with the new installer this no longer the case.

**Comment by danimo** [comment] 2015-01-29 16:58
In that case, this issue would be a dupe of https://github.com/owncloud/client/issues/2410

**Comment by ogoffart** [comment] 2015-06-29 13:53
Closing as duplicate of  #2410

**Closed by ogoffart** 2015-06-29 13:53 UTC
Labels: enhancement - proposed
