### ISSUE TITLE
[XFCE] ownCloud starts before system tray is loaded -> no icon

### ISSUE THREAD

**Issue by RobinJ1995** [owncloud/client#2857] opened 2015-02-18 08:24 UTC
# Problem
On Manjaro with XFCE ownCloud starts before the system tray has been loaded, which results in ownCloud running but not showing a system tray icon, which means I have to kill the ownCloud client and restart it so the tray icon shows up in order to access the UI.

# Desired behaviour
The ownCloud client should detect when the system tray isn't ready yet and check again every few seconds or so whether it is ready yet, and when it is, show its tray icon.
Ideally the process of waiting for a system tray to be ready would be a non-blocking process, so processing of files can happen in the mean time.
Perhaps when a system tray has not been detected after a minute or so, the check should stop in order to not waste any system resources.

# System information
```
[robin@pingwing ~]$ uname -a
Linux pingwing 3.19.0-1-MANJARO #1 SMP PREEMPT Mon Feb 9 07:05:44 UTC 2015 x86_64 GNU/Linux
[robin@pingwing ~]$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	0.8.12
Codename:	Ascella
```
XFCE packages all seem to have a different version number, so if you tell me which one to look for I will provide it if necessary.

**Comment by ogoffart** [comment] 2015-02-18 11:52
What exact version of the owncloud client are you using?

**Comment by ogoffart** [comment] 2015-02-18 11:53
And what version of Qt?

**Comment by RobinJ1995** [comment] 2015-02-18 12:12
ownCloud client 1.7.1-3
Qt (`qt5-base`) 5.4.0-3

**Comment by bremenpl** [comment] 2015-03-01 14:21
Hello,
I am uwing Windows 7 x64 with the owncloud client version 1.7.1 (build 4382). In my situation, when owncloud is checked to start at windows startup, there is no tray icon when windows boots. I can see the process running in the background though. I then have to kill the process and turn owncloud client on again.

**Comment by cachitas** [comment] 2015-03-12 14:22
I also have this problem (Ubuntu 14.04). No tray icon though owncloud is running.
Versions:
`owncloud-client` 1.7.1
`qt5-default` 5.2.1+dfsg-1ubuntu14.2
I kill it and I run it again like `$ owncloud & exit`.

**Comment by guruz** [comment] 2015-03-13 16:08
@RobinJ1995 Did you try 1.8 rc1? I believe @ogoffart had added a timeout to wait for the tray

@bremenpl Where did you set ownCloud to start on startup?

@jturcotte Regarding the comment regarding Windows, can you reproduce this?

**Comment by bremenpl** [comment] 2015-03-13 17:15
I have set it in the application settings. I then tried turning that off 
and adding app to startup folder. But that worked the same.

**Comment by cooper-42** [comment] 2015-03-19 15:49
Hi, I have a similar Problem on my Win 7 x64 machine. I can see the process running, but there is no systray Icon. Restarting the process does not solve the problem. It started with client version 1.8.0. Currently testing nighlybuild 4850.
Is there any other way to access the UI?

**Comment by lchigami** [comment] 2015-03-20 10:38
Same problem with no systray icon showing. I'm using Windows 8.1 with client version 1.8 and OwnCloud 8.0.
The client process is running, but no icon and no sync is working...

**Comment by guruz** [comment] 2015-04-15 13:55
@cooper-42 @lchigami This sounds more like https://github.com/owncloud/client/issues/3079 ? Can you comment on there?

**Comment by cooper-42** [comment] 2015-04-15 16:44
Hi,
not the same problem. After installing the client, II can’t open it. No icon in thy system tray, so I can’t setup the client in the firstplace. 
 
 
 
 
Mit freundlichen Grüßen
 
 
i.A. Nicolai Neumann
 
  
 
Von: Markus Goetz [mailto:notifications@github.com] 
Gesendet: Mittwoch, 15. April 2015 15:55
An: owncloud/client
Cc: cooper-42
Betreff: Re: [client] ownCloud starts before system tray is loaded -> no icon (#2857)
 
@cooper-42 @lchigami This sounds more like #3079 ? Can you comment on there?

**Comment by guruz** [comment] 2015-04-20 14:34
@ogoffart has mentioned that Qt 5.5 (alpha available) has a lot of tray fixes.

**Comment by guruz** [comment] 2015-06-24 15:06
Did anyone of the Linux people try this with Qt 5.5?

**Comment by guruz** [comment] 2015-09-03 10:00
The workaround is https://github.com/owncloud/client/commit/d503221b2e22109eb9f2a3d875dcd247dd8b4cf9
Closing this for now..

**Closed by guruz** 2015-09-03 10:00 UTC
Labels: bug, Platform Specific

**Comment by mibadim** [comment] 2016-05-13 19:24
Still the same problem here with XFCE on Debian and the latest version of the client from the Debian repo (2.2.0). My Qt version is 5.3.2 (package qt-default, hope that's right). 

Looks like the workaround didn't solve the issue.

**Comment by TrueOsiris** [comment] 2016-06-27 09:34
In windows 7(+) cmd:

for /F "tokens=1,2" %i in ('tasklist /FI "IMAGENAME eq owncloud.exe" /fo table /nh') do taskkill /pid %j /f

in a batch script, u use %%i and %%j.
Restart_owncloud.bat:

for /F "tokens=1,2" %%i in ('tasklist /FI "IMAGENAME eq owncloud.exe" /fo table /nh') do taskkill /pid %%j /f
C:\Program Files (x86)\ownCloud\owncloud.exe

**Comment by moscicki** [comment] 2017-05-09 13:46
Same problem reported with 2.2.4 - Debian XFCE, no icon.

**Comment by guruz** [comment] 2017-05-10 13:35
Please try our packages that ship with **their own Qt** 5.6.2: https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client
