### ISSUE TITLE
Windows Client 1.8.0RC1 automatically closes explorer context window

### ISSUE THREAD

**Issue by Bridgesltd** [owncloud/client#2956] opened 2015-03-12 19:02 UTC
Ive just tried the 1.8.0 RC1 client and found my windows explorer menu is automatically closing itself when right clicking any folder within my owncloud data folder.
Any folder outside of that is fine.

For reference, I am using owncloud 8.0 (stable).

I have uploaded a video to show my issue:
https://www.youtube.com/watch?v=Ko5dJe621Og&list=UUuaj8bsITeLUSktm0NvGjFw

I have taken a screenshot in the split second the window is visible and can see the share with owncloud link.

**Comment by lmaestro** [comment] 2015-03-13 08:00
What windows are you using? XP?

**Comment by guruz** [comment] 2015-03-13 08:04
@jturcotte Is this a duplicate of https://github.com/owncloud/client/issues/2898 ?

**Comment by Bridgesltd** [comment] 2015-03-13 09:13
Using windows 8.1
Ive tested the same version on my work PC running windows 7 and it works perfectly.

I would say its the same issue as #2898 who is also using windows 8.1.
It looks like he's worded his issue exactly the same as mine! Atleast I've offered a video demonstration as well.

**Comment by ckamm** [comment] 2015-03-13 09:25
It also works for me on Win7.

**Comment by jturcotte** [comment] 2015-03-13 22:35
Thanks for the awesome video :)

Using that extra info I could reproduce and fix it. See #2898.

**Closed by jturcotte** 2015-03-13 22:35 UTC
Labels: bug

**Comment by Bridgesltd** [comment] 2015-03-15 11:48
works perfect for me, great stuff, thanks.
