### ISSUE TITLE
Zero size file crashes the client

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7984] opened 2020-07-23 13:12 UTC
Reproduce on ocis 1.0.0-beta8 with eos installed via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh

On a second hetzner cloud machine start an ubuntu desktop and install desktop client
Version 2.7.0 (build 1868) dated Jul 23 2020, 01:48:16

export QT_LOGGING_RULES=sync.httplogger=true
owncloud --logfile - | tee client-2.7.0-1868-daily-vs-ocis-1.0.0-beta8-$(date "+%Y%m%d%H%M").log

* connect the client, wait for initial sync
* place a zeor sized file into the local sync folder e.g. with `:> away.txt`
* the client crashes

```
gdb /usr/bin/owncloud core
Reading symbols from /usr/bin/owncloud...
Reading symbols from /usr/lib/debug/.build-id/f1/eb8a8432d4720f264dde3c7c76b85448c93a37.debug...
[New LWP 94254]
[New LWP 94270]
[New LWP 94271]
[New LWP 94276]
[New LWP 94258]
[New LWP 94259]
[New LWP 94265]
[New LWP 94267]
[New LWP 94257]
[New LWP 94294]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `owncloud --logfile -'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007f7932d8d615 in OCC::PropagateUploadFileTUS::startNextChunk (this=this@entry=0x5615d7274d70) at /opt/ownCloud/qt-5.12.9/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:150
150     /opt/ownCloud/qt-5.12.9/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h: No such file or directory.
[Current thread is 1 (Thread 0x7f792f3e1140 (LWP 94254))]
(gdb) where
#0  0x00007f7932d8d615 in OCC::PropagateUploadFileTUS::startNextChunk (this=this@entry=0x5615d7274d70) at /opt/ownCloud/qt-5.12.9/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:150
#1  0x00007f7932d8d873 in OCC::PropagateUploadFileTUS::doStartUpload (this=0x5615d7274d70) at ./src/libsync/propagateuploadtus.cpp:112
#2  0x00007f7932d757e0 in OCC::PropagateUploadFileCommon::slotStartUpload (this=0x5615d7274d70, transmissionChecksumType=..., transmissionChecksum=...) at ./src/libsync/propagateupload.cpp:331
#3  0x00007f7932744e78 in QMetaObject::activate(QObject*, int, int, void**) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f7932ac3a1b in OCC::ComputeChecksum::done (this=this@entry=0x5615d73fea10, _t1=..., _t2=...) at ./obj-x86_64-linux-gnu/src/csync/owncloud_csync_autogen/AAGGKE4ILT/moc_checksums.cpp:141
#5  0x00007f7932ac555b in OCC::ComputeChecksum::slotCalculationDone (this=0x5615d73fea10) at ./src/common/checksums.cpp:313
#6  0x00007f7932744e78 in QMetaObject::activate(QObject*, int, int, void**) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f793254d875 in QFutureWatcherBase::event(QEvent*) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f79334d1e46 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007f79334db4d0 in QApplication::notify(QObject*, QEvent*) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007f793271932a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f793271bfa8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f79327719f7 in ?? () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f7931855fbd in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f7931856240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f79318562e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f7932770ff5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f7932717ecb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f793271fc36 in QCoreApplication::exec() () from /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00005615d5e01757 in main (argc=<optimized out>, argv=<optimized out>) at ./src/gui/main.cpp:164
(gdb) 
```

* The client log ends with 

```
07-23 15:01:03:582 [ info sync.discovery ]:     STARTING "" OCC::ProcessDirectoryJob::NormalQuery "" OCC::ProcessDirectoryJob::NormalQuery
07-23 15:01:03:582 [ info sync.accessmanager ]: 6 "PROPFIND" "https://95.217.220.181:9200/remote.php/webdav/" has X-Request-ID "b253c9f4-6099-45e9-a860-0ab4056f9235"
07-23 15:01:03:582 [ info sync.networkjob ]:    OCC::LsColJob created for "https://95.217.220.181" + "/" "OCC::DiscoverySingleDirectoryJob"
07-23 15:01:03:692 [ info sync.networkjob.jsonapi ]:    JsonApiJob of QUrl("https://95.217.220.181:9200/ocs/v2.php/apps/notifications/api/v1/notifications?format=json") FINISHED WITH STATUS "OK"
07-23 15:01:03:692 [ warning sync.networkjob.jsonapi ]: invalid JSON! "" "illegal value"
07-23 15:01:03:692 [ warning gui.servernotification ]:  Notifications failed with status code  0
07-23 15:01:03:836 [ info sync.networkjob.lscol ]:      LSCOL of QUrl("https://95.217.220.181:9200/remote.php/webdav/") FINISHED WITH STATUS "OK"
07-23 15:01:03:836 [ info sync.discovery ]:     Processing "Portrait.jpg" | valid: true/true/true | mtime: 1595339299/1595339299/1595492319 | size: 1001379/1001379/1001379 | etag: "2415919104:98c5c
4da"//"2415919104:98c5c4da" | checksum: "SHA1:0ec827833ac7624f929aa2a8ad75c3fd64e26b4a"//"" | perm: WDNVCKR//WDNVCKR | fileid: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjI0MTU5MTkxMDQ="//"M
TI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjI0MTU5MTkxMDQ=" | inode: 261806/261806/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
07-23 15:01:03:836 [ info sync.discovery ]:     Discovered "Portrait.jpg" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     Processing "Shares" | valid: true/true/true | mtime: 1595506745/1595441043/1595506745 | size: 0/4096/0 | etag: "14:1595506745.142"//"14:1595506745.14
2" | checksum: ""//"" | perm: WDNVCKR//WDNVCKR | fileid: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjIw"//"MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjIw" | inode: 261782/261782/ | typ
e: CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeDirectory
07-23 15:01:03:837 [ info sync.discovery ]:     Discovered "Shares" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeDirectory
07-23 15:01:03:837 [ info sync.discovery ]:     Processing "Speech.ogg" | valid: true/true/true | mtime: 1595492319/1595492319/1595492319 | size: 784339/784339/784339 | etag: "2147483648:76d454fc"/
/"2147483648:76d454fc" | checksum: "SHA1:4264bb568c6d5606f85e2202ef8b0c99be663fd6"//"" | perm: WDNVCKR//WDNVCKR | fileid: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjIxNDc0ODM2NDg="//"MTI4NG
QyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjIxNDc0ODM2NDg=" | inode: 262269/262269/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     Discovered "Speech.ogg" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     Processing "away.txt" | valid: false/true/false | mtime: 0/1595509261/0 | size: 0/0/0 | etag: ""//"" | checksum: ""//"" | perm: // | fileid: ""//"" | inode: 0/262290/ | type: CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     Not a move, no item in db with inode 262290
07-23 15:01:03:837 [ info sync.discovery ]:     Discovered "away.txt" CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Up CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     Processing "init" | valid: true/true/true | mtime: 1595441174/1595441174/1595492317 | size: 0/4096/0 | etag: "10:0.000"//"10:0.000" | checksum: ""//"" | perm: WDNVCKR//WDNVCKR | fileid: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjE2"//"MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjE2" | inode: 261796/261796/ | type: CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeDirectory
07-23 15:01:03:837 [ info sync.discovery ]:     Discovered "init" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeDirectory
07-23 15:01:03:837 [ info sync.discovery ]:     Processing "jw" | valid: true/true/true | mtime: 1595442118/1595509128/1595509141 | size: 0/4096/0 | etag: "15:0.000"//"15:0.000" | checksum: ""//"" | perm: WDNVCKR//WDNVCKR | fileid: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjIx"//"MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjIx" | inode: 261805/261805/ | type: CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeDirectory
07-23 15:01:03:837 [ info sync.discovery ]:     Discovered "jw" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeDirectory
07-23 15:01:03:837 [ info sync.discovery ]:     STARTING "Shares" OCC::ProcessDirectoryJob::ParentNotChanged "Shares" OCC::ProcessDirectoryJob::NormalQuery
07-23 15:01:03:837 [ info sync.discovery ]:     STARTING "init" OCC::ProcessDirectoryJob::ParentNotChanged "init" OCC::ProcessDirectoryJob::NormalQuery
07-23 15:01:03:837 [ info sync.discovery ]:     Processing "init/make_machine.bashrc.md" | valid: true/db/db | mtime: 1595440969/0/0 | size: 6680/0/0 | etag: "2952790016:240e84ba"//"" | checksum: "SHA1:e60556c674487aabad56fc960fabef12cdef0c38"//"" | perm: WDNVCKR// | fileid: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjI5NTI3OTAwMTY="//"" | inode: 261798/0/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     Discovered "init/make_machine.bashrc.md" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     Processing "init/this-is-ocis-1.0.0-beta8.txt" | valid: true/db/db | mtime: 1595441103/0/0 | size: 452/0/0 | etag: "3221225472:cc7e7cbb"//"" | checksum: "SHA1:1719115a6d48053a6eb557e56e65a58eed2251cf"//"" | perm: WDNVCKR// | fileid: "MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU0OjMyMjEyMjU0NzI="//"" | inode: 261802/0/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     Discovered "init/this-is-ocis-1.0.0-beta8.txt" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
07-23 15:01:03:837 [ info sync.discovery ]:     STARTING "jw" OCC::ProcessDirectoryJob::ParentNotChanged "jw" OCC::ProcessDirectoryJob::NormalQuery
07-23 15:01:03:837 [ info sync.engine ]:        #### Discovery end ####################################################  255 ms
07-23 15:01:03:838 [ info sync.engine ]:        #### Reconcile (aboutToPropagate) ####################################################  256 ms
07-23 15:01:03:838 [ info sync.engine ]:        #### Reconcile (aboutToPropagate OK) ####################################################  256 ms
07-23 15:01:03:838 [ info sync.engine ]:        #### Post-Reconcile end ####################################################  256 ms
07-23 15:01:03:838 [ info gui.folder ]: #### Propagation start ####################################################
07-23 15:01:03:838 [ info gui.application ]:    Sync state changed for folder  "https://95.217.220.181:9200/remote.php/webdav/" :  "Sync Running"
07-23 15:01:03:842 [ info sync.propagator ]:    Starting CSyncEnums::CSYNC_INSTRUCTION_NEW propagation of "away.txt" by OCC::PropagateUploadFileTUS(0x5615d7274d70)
07-23 15:01:03:842 [ info sync.checksums ]:     Computing "SHA1" checksum of "/root/ownCloud2/away.txt" in a thread
07-23 15:01:03:843 [ info sync.checksums ]:     Computing "SHA256" checksum of "/root/ownCloud2/away.txt" in a thread
07-23 15:01:03:843 [ debug sync.propagator.upload.tus ] [ OCC::PropagateUploadFileTUS::startNextChunk ]:        Starting creation with upload: "away.txt"
07-23 15:01:03:843 [ info sync.accessmanager ]: 4 "" "https://95.217.220.181:9200/remote.php/dav/files/einstein/" has X-Request-ID "813d549b-15d2-4270-8330-3a860eb9f818"
07-23 15:01:03:843 [ info sync.networkjob ]:    OCC::SimpleNetworkJob created for "https://95.217.220.181" + "" ""
```

Expected behaviour

* The client should not crash.
* The 0-byte size file gets uploaded to the server (and also should not cause a crash there)

**Comment by HanaGemela** [comment] 2020-07-23 13:41
Sounds the same as https://github.com/owncloud/client/issues/7975#issuecomment-662493880
There were also empty files in the folder uploaded in the original description

**Comment by TheOneRing** [comment] 2020-07-24 10:17
Duplicate of https://github.com/owncloud/client/issues/7975

**Closed by TheOneRing** 2020-07-24 10:17 UTC
