### ISSUE TITLE
No tray icon on Gnome

### ISSUE THREAD

**Issue by RobinJ1995** [owncloud/client#2511] opened 2014-11-18 13:28 UTC
I've been running Arch Linux with KDE/Plasma 4 on my laptop for a few months, and ownCloud ran fine on it. Recently I wanted to try out the latest version of Gnome, so I installed it. The problem is that the ownCloud icon is not shown in the tray. It's just a blank space, but the main window does open when I click the right spot.

![capture d ecran de 2014-11-18 14 22 23](https://cloud.githubusercontent.com/assets/3089559/5087967/c0efda1e-6f2e-11e4-8275-aff66936335f.png)
![capture d ecran de 2014-11-18 14 22 25](https://cloud.githubusercontent.com/assets/3089559/5087968/c2300368-6f2e-11e4-88ce-d89ea2f64ca2.png)
(Never mind the French; that's just an attempt to get more familiar with the language and not fail the subject at school.)

Without the _Topicons_ Gnome extension;
![capture d ecran de 2014-11-18 14 23 10](https://cloud.githubusercontent.com/assets/3089559/5087979/f1a7c6f8-6f2e-11e4-920e-e654b39f3428.png)

Toggling between monochrome and regular icons in the ownCloud client's preferences makes no difference.

Possibly related: I read that version 1.7 of the client was supposed to show emblems about sync status in most file managers. I haven't seen them in either KDE/Dolphin or Gnome/Nautilus.

# System Information
Linux 3.17.3-1-ARCH
Gnome Shell 3.14.2-1
ownCloud (server) 7.0.3
ownCloud (client) 1.7.0

**Comment by crsqq** [comment] 2015-03-20 17:12
Same problem here with following setup:

Fedora 21: 3.18.9-200.fc21.x86_64
GNOME Shell 3.14.3
ownCloud version 1.8.0

**Comment by karolherbst** [comment] 2015-03-20 17:18
with 1.8.0 its fine for me on plasma5

**Comment by ogoffart** [comment] 2015-03-23 13:32
@crsqq what version of Qt?

**Comment by crsqq** [comment] 2015-03-27 21:47
Since I'm using the version from the repo mentioned above, I suppose that qt5 is used. But how can I specifically check  the version?

**Comment by hefee** [comment] 2015-03-28 09:04
It is still an issue for 1.8.0 and qt5 5.3.2 see (debian #781368)[https://bugs.debian.org/cgi-bin/781368]

**Comment by ckamm** [comment] 2015-04-09 08:55
That debian bug suggests it will be fixed with an upgrade to Qt 5.4. https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1311640.html

**Comment by hefee** [comment] 2015-04-09 15:47
The issue isn't solved with Qt 5.4. Actually the suggestion in the bugreport was because of some information flying around in the net.

**Comment by ckamm** [comment] 2015-04-10 07:12
I think the same issue might be discussed in #2123, this might even be a duplicate. It's said there that you might need to install qt-sni. Do you have that, @hefee?

**Comment by crsqq** [comment] 2015-04-10 18:42
Installing qt-sni didn't change anything for me, the tray icon is still broken.

**Comment by zeroepoch** [comment] 2015-05-08 05:12
Just updated to:
```
owncloud-client-1.8.1-5.1.x86_64
owncloud-client-l10n-1.8.1-5.1.x86_64
libowncloudsync0-1.8.1-5.1.x86_64
```

FYI, there is still no tray icon in gnome-shell on Fedora 21.  Installing `sni-qt.x86_64` makes no difference but suspect that's because it's for Qt4.

**Comment by m1rc0** [comment] 2015-05-21 07:21
On Fedora 22 there is also no tray icon in gnome-shell. 

   libowncloudsync0.x86_64 1.8.1-6.1         
   owncloud-client.x86_64 1.8.1-6.1    
   owncloud-client-l10n.x86_64 1.8.1-6.1

**Comment by hefee** [comment] 2015-05-26 12:10
Qt 5.4.2 will fix this problem [debian #781368](https://bugs.debian.org/781368) - For debian a backported version has entered experimental.

**Comment by zeroepoch** [comment] 2015-06-09 01:33
Just confirming what hefee said. On Fedora 22 I just updated qt5-qtbase to 5.4.2 and now I see the tray icon.  Strangely with qt5-qtbase 5.4.1 the very first time I started the ownclient client it showed up but never after that.  Work as expected now including the nautilus extension.

**Comment by seancallaway** [comment] 2015-06-09 22:00
Another confirmation that qt5-qtbase-5.4.2 resolves this issue.

**Comment by ogoffart** [comment] 2015-06-10 06:01
Glad to hear that this is fixed. Thanks  to everyone testing it.

**Closed by ogoffart** 2015-06-10 06:01 UTC
Labels: bug, Needs info
