### ISSUE TITLE
Desktop Sync - deleted files to recycle bin and no permanent delete

### ISSUE THREAD

**Issue by nemethstarproductions** [owncloud/client#11082] opened 2023-08-04 09:30 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Hello,
it would be great to have a setting in the OwnCloud Desktop Client that avoids the permanent deletion of files and moves them to the recycle bin.
For example: I delete a file via the owncloud webinterface. This will be synced to my desktop client. Currently the file is being removed from my hard drive without any trace. Instead of this and to avoid data lose it would be great if the Desktop client would move deleted files to the recycle bin, as the OS does when i delete a file via file explorer.

### Proposed solution

The Feature could be implemented in general or much better to give users a choice, realized with an option in the settings of the client.

**Comment by TheOneRing** [comment] 2023-08-04 09:43
Duplicate of : https://github.com/owncloud/client/issues/9001

**Closed by TheOneRing** 2023-08-04 09:43 UTC
