### ISSUE TITLE
deleted files locally (but still on server) after 2.4 update - Ubuntu

### ISSUE THREAD

**Issue by simogeo** [owncloud/client#6282] opened 2018-01-04 17:08 UTC
### Expected behaviour
Synchronised files / folders between my PC and the cloud server

### Actual behaviour
30 Gb of files just disappeared locally on my computer. After 2.4 client update I guess.
**It seems the issue is similar to #3102.** 

**Is there a way to downgrade owncloud client version on ubuntu ? I would be (very) happy to get back my files.**

### Steps to reproduce
1. Use Ubuntu 
2. update to 2.4 client version 
3. switch of the computer, go to bed, boot early morning, see  ... there is no files or just few !?

### Server configuration
Operating system: 

Web server: Apache 2

Database: MySQL 5

PHP version: 5.6

ownCloud version: 12.04

Storage backend (external storage):

### Client configuration
Client version:  Version 2.4.0 (build 8911)

Operating system: Ubuntu xenial

OS language: fr

Qt version used by client package (Linux only, see also Settings dialog):  
Qt 5.6.2

Client package (From ownCloud or distro) (Linux only): ownCloud

Installation path of client: 

### Logs

extract of server logs : 

`78.194.240.218 - simon [03/Jan/2018:19:02:22 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:02:35 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1601 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
90.12.217.113 - laurent [03/Jan/2018:19:02:51 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:02:52 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:03:21 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:03:22 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:03:51 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:03:52 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:04:21 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:04:22 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:04:51 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:04:52 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
78.194.240.218 - simon [03/Jan/2018:19:05:22 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 2863 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:05:23 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 2865 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
90.12.217.113 - laurent [03/Jan/2018:19:05:51 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:05:52 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:06:21 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:06:22 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
78.194.240.218 - simon [03/Jan/2018:19:06:37 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 884 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:06:51 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 884 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
90.12.217.113 - laurent [03/Jan/2018:19:06:51 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:06:52 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:07:21 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:07:22 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:07:51 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:07:52 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:08:21 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:08:22 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:08:51 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:08:52 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"
90.12.217.113 - laurent [03/Jan/2018:19:09:21 +0100] "PROPFIND /remote.php/dav/files/laurent/ HTTP/1.1" 207 1600 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 6928)"
78.194.240.218 - simon [03/Jan/2018:19:09:22 +0100] "PROPFIND /remote.php/dav/files/simon/ HTTP/1.1" 207 1598 "-" "Mozilla/5.0 (Linux) mirall/2.4.0 (build 8911)"`

**Comment by simogeo** [comment] 2018-01-05 08:38
even stranger,
My client starts to sync again but some files only ...  Most of them are not downloaded locally ....

**Comment by ogoffart** [comment] 2018-01-05 10:19
Hi,
Your problem sounds serious. But I doubt it is related to #3102 in any way.

I would need more information to be able to debug that problem. Like the full log of a sync, that show the discovery and the reconcile phase.
I need to understand why the files were suddenly gone.

**Comment by simogeo** [comment] 2018-01-05 10:37
hi @ogoffart : thanks for your support ! Here we go for full logs 
https://gist.github.com/simogeo/69a57034acb6db4957a6b5be1c3eb68f

 in the meantime, is there a way to downgrade client software ? I would appreciate to be able to work on good conditions again

**Comment by ckamm** [comment] 2018-01-05 12:17
@simogeo For downgrading, I presume you can use the `isv:/ownCloud:/desktop:/client-2.3.4/Ubuntu_16.04/` repository instead of `isv:/ownCloud:/desktop/Ubuntu_16.04/` to grab the 2.3.4 snapshot. Note I haven't tried that.

Could you give us (if necessary by email; mail at ckamm de) a client log file? You can generate it by starting the owncloud client with `--logfile mylog.txt`. That will allow us to see what your client is thinking about the various missing files. Also let us know about the name of a file that used to be on your computer but is no longer there.

**Comment by ogoffart** [comment] 2018-01-05 12:30
Thanks for that (server) log. 
On the webdav endpoint, It shows lots of PROPFIND which all seems successfull (http code 207)  and a couple of PUT and MOVE.  

Do you have the client log of a sync ?  (from --logfile)

Thanks for helping us investigate this issue.

In order to downgrade, you can just run the installer of the previous version [ https://download.owncloud.com/desktop/stable/ ]   Downgrading should somehow work altough it is not really supported (new created accounts or folder might not be imported).  And in particular, i doubt this will re-download all your files.

Also, what exact version did you upgrade from?

One theoryof what might be causing the bug is that the upgrade caused a full remote discovery  (We do that when upgrading from 2.2, but not from 2.3. However, maybe the remotePerm storage change might have changed the order of permission and we would still do a full discovery in that case)
The server might have missed some entries in the PROPFIND replies and the client would then delete them.
You can re-force a full discovery by pressing CTRL+F6,  or adding pattern in the ignore list.
Does the file re-appear then? 
Please save the log (with --logfile) when doing that.

I'd appreciate if you waited a bit before attempting to downgrade because it would be usefull to know what caused this issue.

**Comment by simogeo** [comment] 2018-01-05 13:10
@ckamm : Here is the right url it seems : http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/client-2.3.4/Ubuntu_16.04/. Not tested yet, since I will try to help you to debug this.

Not that when I stop and start again owncloud client with logfile option, it deleted some files ....
I sent you a link to download log

@ogoffart : If you send me your email, I'll forward you the ling to check logs

**Comment by ckamm** [comment] 2018-01-05 14:49
@simogeo Thanks for the log, will investigate from there!

**Comment by simogeo** [comment] 2018-01-05 16:53
I 've tried Ctrl-F6 ... Owncloud started to sync again but it seems, it did not restore all files / folders.
ALl this, is kind of scary ...

@ogoffart, @ckamm : I can give you access to the huge (more than 300MB) log file if needed.


I think I will try to downgrade before monday because the situation is really getting paralytic  ....

**Comment by simogeo** [comment] 2018-01-06 16:46
Here is where I am (not a really good news ...) : 
- I've downgraded my client to 2.3.3 from https://download.owncloud.com/repositories/desktop/download/ (see #6034 and #6267).
- I started the sync again.
- I was able to appreciate a new synchronisation and to believe everything want right. Let the computer work to sync my data.
- I came back again and observed the same trouble. All was downloaded and then most of the files were deleted  again .. :-( 

Here is the [owncloudsync.log file](https://gist.githubusercontent.com/simogeo/469156ad3de5de4fe3ff32cf16c5aa4b/raw/d2ea837308a53d07bc4468c29d735ece240d2ec0/gistfile1.txt) found in the local root folder. where I can see lots of `INST_REMOVE` instances. (I don't know nothing of owncloud, so I don't know if it helps or not).

What I am trying now : 
I removed the account, and created a new one downloading everything again to a new local folder.

I will let you know what will happen .... Thanks again for support.

**Comment by ogoffart** [comment] 2018-01-07 14:14
@simogeo  thanks for your investigations.

Wodering if this is a regression in 2.4 or a problem that existed before, also in 2.3.
The owncloudsync.log shows that the files are indeed deleted, but it does not tell why. Normaly this happens when the server does not report these files anymore, so this could be a server problem. I haven't had time to look at the log from --logfile yet, but it should tell us if there is anything fishy with the filesthat got removed, or if the client simply don't "see" them as the server don't report them.

If you create a new account or a new folder sync connection, and that the files does not get downloaded, that would shows that there is most likely something wrong with the server.
But if there is a difference between 2.3 and 2.4, that would be something odd that we need to investigate. 

(I was thinking maybe it is an encoding problem? the the log shows that there are also file in pure ascii that are also removed, so probably not)

**Comment by simogeo** [comment] 2018-01-07 18:20
> I haven't had time to look at the log from --logfile yet, but it should tell us if there is anything fishy with the filesthat got removed, or if the client simply don't "see" them as the server don't report them.

I guess is able to see them because it download them, and then only deleted them ...

Creating a new account and downloading everything again seems to work. I'm still using 2.3.3 client version and won't test upgrading again right now.

Still, I'd be happy to understand and to be able to upgrade again my client preventing a big mess. So please, let me know if you find something.

Thanks all for your support,

**Comment by ckamm** [comment] 2018-01-08 08:04
@ogoffart I looked at the client log file but it's not helpful since we forgot `--logdebug`. :(

@simogeo I'm very glad you managed to restore to a version that works! It would be incredibly helpful if you could try the update again for us. Here's what I suggest:
* Make a backup copy of your sync folder.
* Quit the 2.3.3 client and install 2.4.0
* Start with `--logfile log.txt --logdebug`.
* Wait for a sync where you observe file deletion.
* Quit 2.4.0 and downgrade to 2.3.3
* Restore the backup.
* Send us the log file (compress!).

If your sync folder is huge, an alternate approach would be to copy a subtree (like `02-En-cours`), remove the folder connection in 2.3.3 and set up a folder connection for this copied subtree only. Then upgrade and proceed as above. That way the new client would only ever work on this copied subtree and your actual data would be untouched.

I haven't yet seen other reports of this kind of issue with 2.4.0: further data would be *much* appreciated since there must be a critical issue here somewhere.

**Comment by simogeo** [comment] 2018-01-08 20:25
Hi @ckamm : I'd be happy to help but now my system is operational and since I was in trouble last days, my priority is to work again. I hope I can try this when I have more time.

**Comment by ogoffart** [comment] 2018-02-02 11:05
We still have no idea what could have caused this problem and so we can't do anything to fix it at the moment.

**Comment by simogeo** [comment] 2018-02-03 17:49
Hi,
I had no time to perform a new test ... and will probably not have in a near future ... I'll probably try to install the next release of owncloud client and let you know

**Comment by guruz** [comment] 2018-02-05 15:30
> Normaly this happens when the server does not report these files anymore, so this could be a server problem. 

Related https://github.com/owncloud/client/issues/6322 @sagamusix ?

> The only thing I can say is that the client very likely used fill_tree_from_db on all subfolders of the root: the remote discovery only sent a single LsCol.

So can #6322 also be a local problem @ckamm ?

**Comment by ckamm** [comment] 2018-02-06 12:44
I think this is as much as we know:
- There are `REMOVE` instructions with downwards direction for affected files.
- These can only appear when the remote tree doesn't have the file.
- The remote tree is taken from the database.
- So either the file wasn't in the database or it was filtered out when retrieving it.
- There are two possible filters: One is the exclude list, the other is `avoidReadFromDbOnNextSync()` setting `_invalid_` etags.

I'm currently wondering whether there might be cases when an aborted or otherwise partial sync might leave some of the `_invalid_` etags in place on deep folders while setting the parent folder's etags correctly.

**Comment by ckamm** [comment] 2018-02-06 13:15
No, the `_invalid_` etag reason can be ruled out: In @simogeo's log the local discovery prints valid etags for the files that will later be deleted and their parent directories. That also means the files are present in the database. The bug must me more obscure.

**Comment by ckamm** [comment] 2018-02-06 13:49
Possibly a hint: In the owncloudsynclog it looks like some files are removed in a sync run, a sync run without propagation happens 8s later, and the next sync run 35s later again removes some files in a different folder.

**Comment by ogoffart** [comment] 2018-02-06 16:38
I spend some time trying to analyse the log as well and find out what could go wrong, but i did not find anything interesting.
An entire directory is removed despite it is in the database (as the log from the local discovery shows)

Here are some hypotheses:

 * The server did not set the `<resourcetype><collection/>` tag, or we failed to parse it.  (this is rather unlikely)
 * There is a bug in `fill_tree_from_db`or in `SyncJournalDb::getFilesBelowPath`. For example, I realize that `SqlQuery::next` does not report errors, and if a database error happens there, we wouldn't know.

**Comment by guruz** [comment] 2018-02-12 16:22
I'll move this 2.5.0 then.
Maybe we can improve on the points mentioned by @ogoffart

**Comment by ogoffart** [comment] 2018-03-27 09:20
Is such problem still hapening with 2.4.1?
Without more information on how to reproduce the problem, we cannot do anything about the issue.

**Comment by simogeo** [comment] 2018-03-28 07:55
Hi,
I'll try to update next weeks. Right now, I need to have a secured environment to work.

I'll let you know.

**Comment by simogeo** [comment] 2018-03-31 10:46
I've just tried an update to 2.4.1 and restart owncloud client (with log option).
Till now, I have no problem. I will try a couple of days and then let you know again and hopefully close this ticket.

Thanks,

**Comment by guruz** [comment] 2018-04-03 13:12
Great...!

**Comment by simogeo** [comment] 2018-04-03 13:40
It is ! ;-)

Any idea why it is working well now ?

**Comment by ogoffart** [comment] 2018-04-12 11:53
Closing the issue since it cannot be reproduced.

**Closed by ogoffart** 2018-04-12 11:53 UTC
Labels: Needs info, bug
