### ISSUE TITLE
Files get 'Locked'

### ISSUE THREAD

**Issue by benblamey** [owncloud/client#2684] opened 2015-01-09 10:24 UTC
When owncloud is syncing files it seems to lock them -- this can make it frustrating for example, if I have a file open in an application with unsaved changes -- I cannot exit the application and close the file until owncloud has finished.

I haven't looked at the code -- but I'm guessing files are opened for read but deny writing from others?

An alternative would be to use the flag to specify that writing was allowed by processes -- and then use the file changed notification mechanism to nullify changes made subsequently by the files

http://msdn.microsoft.com/en-us/library/windows/desktop/aa365430%28v=vs.85%29.aspx

Dropbox seem to have some solution to this

**Comment by danimo** [comment] 2015-01-09 10:25
This is being addressed, see https://github.com/owncloud/client/pull/2597. @guruz ?

**Comment by dragotin** [comment] 2015-01-09 10:32
This is a duplicate of #2070

**Closed by dragotin** 2015-01-09 10:32 UTC
