### ISSUE TITLE
Synchronization Error while showing success - Not syncing files

### ISSUE THREAD

**Issue by schnaidar** [owncloud/client#3767] opened 2015-09-06 14:56 UTC
### Expected behaviour
All files should be synchronized. If there is an error, there should be a proper message.

### Actual behaviour
One local folder does not get synchronized. After exploring all available files the symbol of the folder changes to the error icon. The tooltip says "Synchronisationsfehler" (sync error) while the progress bar is still visible and the status label below the bar says "Erfolgreich" (success).
The changed or created files are not uploaded.

### Steps to reproduce
I really don't know since when the error occures. But now, everytime the clients wants to start a sync, this error comes up. Also when resetting the db (via F5).

### Server configuration
Operating system: Debian 7 

Web server: Apache/2.2.22 (Debian)

Database: mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (i686) using readline 6.2

PHP version: PHP 5.4.44-0+deb7u1

ownCloud version: ownCloud version 8.1.1

Storage backend: default

### Client configuration
Client version: Version 2.0.1 (build 5446)

Operating system: Windows 7

OS language: German

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
```
09-06 15:09:21:431 0x5b1ded8 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "Erfolgreich"
09-06 15:09:21:433 0x5b1ded8 OCC::SyncEngine::finalize: CSync run took  4065
09-06 15:09:21:439 0x5b1ded8 OCC::Folder::slotSyncFinished:  - client version 2.0.1 (build 5446)  Qt 5.4.0  SSL  OpenSSL 1.0.2d 9 Jul 2015
09-06 15:09:21:439 0x5b1ded8 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
09-06 15:09:21:440 0x5b1ded8 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  0  Milliseconds.
09-06 15:09:21:440 0x5b1ded8 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  2
09-06 15:09:21:440 0x5b1ded8 OCC::Folder::slotSyncFinished:   ** error Strings:  ("Erfolgreich")
09-06 15:09:21:440 0x5b1ded8 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
09-06 15:09:21:441 0x5b1ded8 OCC::Folder::slotSyncFinished: the last 5 syncs failed
```
There are no error related log entries in apache log and owncloud.log.

I tried removing the folder and adding again. Same with reinstalling.

I have two local folders, the second folder works without any error, so I actually don't think there is an error with the server.

![oc_error](https://cloud.githubusercontent.com/assets/12746670/9705025/b39d113c-54b7-11e5-9513-fdb8b21f651f.png)

**Comment by ls960** [comment] 2015-09-06 17:06
same issue for me with same OC configuration: linux clients, however, don't have any trouble.

**Comment by guruz** [comment] 2015-09-06 18:53
It would be nice to get the errors/lines before ```#### ERROR during  csync_update :  "Erfolgreich"``` since this is just the summary message of the preceeding..

Could you paste us the ```Accounts``` section of your ```owncloud.cfg```? Feel free to change the URL.

Did the error occur after upgrading from 1.8.4?

@dragotin etc: Wondering why one path starts with ```/``` the other one doesn't..

**Comment by schnaidar** [comment] 2015-09-06 19:06
I will add the requested lines tomorrow.

I don't exactly know, if it occurred after I upgraded, but it could be possible.

The leading slash came after I removed the directory in the client and added it again.
Another thing: is it an intended behavior, that in the log entries slashes and backslashes are combined in the path?  You will see an example tomorrow.

**Comment by schnaidar** [comment] 2015-09-07 18:28
```

**Comment by schnaidar** [comment] 2015-09-07 19:11
I tried removing the leading slash in the cfg file, but it didn't work. This is the unmodified part of the file:
```
[Accounts]
0\Folders\Pictures\localPath=C:\\Users\\myUser\\Pictures
0\url=https://example.com
0\Folders\Pictures\targetPath=photos
0\http_certificatePasswd=
0\Folders\Pictures\paused=false
0\http_certificatePath=
0\Folders\Pictures\ignoreHiddenFiles=true
0\http_user=myUser
0\user=myUser
0\authType=http
0\Folders\Documents\localPath=C:\\Users\\myUser\\Documents
0\Folders\Documents\targetPath=/Eigene Dokumente
0\Folders\Documents\paused=false
0\Folders\Documents\ignoreHiddenFiles=true
```

I changed the logging verbosity of the server (which I really should have done before) and discovered an connection error.
```
Exception : {
	"Message" : "HTTP\/1.1 401 No basic authentication headers were found",
	"Code" : 0,
	"Trace" : "#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#9 {main}",
	"File" : "\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php",
	"Line" : 70
}

```
As suggested in Issue owncloud/core#14510 I tried curl, which returned a HTTP 207 code. So it worked apparently.
But still there is a connection reset, which you can see in line 21 in the client log.
https://gist.github.com/schnaidar/dc48ee4edcbface2978a

(I hope the information is enough. There are 10thousands of lines after the gist of walking through the folder. There is neither the word 'error' nor 'fail', so I don't think there is an error. I would really like to not upload those log information, unless you really need it)

**Comment by fwr0** [comment] 2015-09-08 03:35
I encountered a similar error on my system, and it was caused by folder security in a tree being synced.

Here's a repro:
* Assume you are syncing C:\documents
* Create a folder C:\documents\testing
* Owncloud syncs successfully
* Edit security on C:\documents\testing, and deny yourself "Read+Execute", "List Folder Contents" and "Read"
* Save something in C:\documents to trigger a sync
* Owncloud will give the red X with status of "success" (logs below)
* Edit security on C:\documents\testing, and remove the "deny" entries
* Save something in C:\documents to trigger a sync
* Owncloud syncs successfully

The logfile contains:
```
09-07 22:58:42:651 0xafd98d0 csync_ftw: Uniq ID from Database: Testing -> _invalid_
09-07 22:58:42:651 0xafd98d0 csync_walker: directory: C:\Documents/Testing [inode=383374]
09-07 22:58:42:651 0xafd98d0 _csync_detect_update: Database entry found, compare: 1441680569 <-> 1441680571, etag: _invalid_ <-> _invalid_, inode: 383374 <-> 383374, size: 0 <-> 0, perms:  <-> RDNVCK, ignore: 0
09-07 22:58:42:651 0xafd98d0 _csync_detect_update: file: Testing, instruction: INSTRUCTION_EVAL <<=
09-07 22:58:42:651 0xafd98d0 csync_ftw: opendir failed for C:\Documents/Testing - errno 0
09-07 22:58:42:651 0xafd98d0 csync_statedb_close: sqlite3_close=0
09-07 22:58:43:109 0x386da8 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "Success."
09-07 22:58:43:109 0x386da8 OCC::SyncEngine::finalize: CSync run took  624
09-07 22:58:43:115 0x386da8 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QIODevice*) "C:\Documents\Visual Studio 2010"
09-07 22:58:43:115 0x386da8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Documents\Visual Studio 2010"
09-07 22:58:43:123 0x386da8 OCC::Folder::slotSyncFinished:  - client version 2.0.1 (build 5446)  Qt 5.4.0  SSL  OpenSSL 1.0.2d 9 Jul 2015
09-07 22:58:43:123 0x386da8 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
09-07 22:58:43:126 0x386da8 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  2  Milliseconds.
09-07 22:58:43:126 0x386da8 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  2
09-07 22:58:43:127 0x386da8 OCC::Folder::slotSyncFinished:   ** error Strings:  ("Success.")
09-07 22:58:43:127 0x386da8 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
09-07 22:58:43:127 0x386da8 OCC::Folder::slotSyncFinished: the last 1 syncs failed
```
It looks like csync_ftw is reporting a failure but errno is 0, which would explain the "Error: Success" message

In my case, it was the "My Music" and "My Pictures" symlinks causing the problem.   These links are normally created with the "List Folder/Read Data" permission denied.   (I deleted mine before I checked the exact settings, sorry).  

Excluding the folder (unchecking the box on the "Testing" folder) did not help.

I don't know when this first started.
Rolling back to client 2.0.0 did not help
I didn't try the 1.8 client.

Expected behavior:
* UI should show error indicating folder that could not be opened
* No error should be logged when folder is excluded

**Comment by heimdal31** [comment] 2015-09-08 16:01
I can confirm what fwr0 has found and add additional information:

I was syncing my c:\users\<username>\Documents\ folder on Windows 7 64 bit.

All was working fine until an upgrade from 1.8.4 to 2.1.

After the upgrade, I saw the same reported issues:

Red X with a status of success reported.

Deleting the hidden symlinked:

My Pictures
My Music
My Videos

fixed the issue and syncing completed.

Odder still, those three folders were on my ignore list in ownCloud and did show a yellow overlay icon.

**Comment by schnaidar** [comment] 2015-09-08 17:46
Well, that's weird. After I enabled system files in explorer, I could the three files mentioned by @heimdal31. 
The synchronization successfully finished, after I deleted the three files and now seems everything ok.

@owncloud-team: Please implement a proper error message to avoid such things in the future. Nonetheless great work with the whole software.

**Comment by FoxBJK** [comment] 2015-09-09 11:44
I'm also getting this error, but for a directory on Windows 10 (x64) that doesn't even exist anymore! What's odd is that I completely removed everything from the server in an attempt to fix this, so I'm not sure why it's still trying to sync a certain missing directory or what to do about it. Any way to "reset" the sync and/or force an upload from my PC of all files?

Here's what I'm seeing in the log:
    09-09 06:43:05:630 0xa9f21f0 csync_walker: directory: C:\Users\FoxBJK\Documents/My Music [inode=492]
    09-09 06:43:05:631 0xa9f21f0 _csync_detect_update: Checking for rename based on inode # 492
    09-09 06:43:05:631 0xa9f21f0 _csync_detect_update: file: My Music, instruction: INSTRUCTION_NEW <<=
    09-09 06:43:05:631 0xa9f21f0 csync_ftw: opendir failed for C:\Users\FoxBJK\Documents/My Music - errno 0

**Comment by itlte** [comment] 2015-09-11 09:44
Good Day. I did the above mentioned and it seemed to have worked, however this morning the RedCross error appeared again. Not sure what to do now> any thing else to delete?

**Comment by marksieklucki** [comment] 2015-09-12 03:49
Same problem as previous comments - client 2.0.1 displayed Error with "Success" message.

Rolled client back to 1.8.4 and sync completed successfully. Looks like some sort of regression from the 1.8.4 to the 2.0.1 client.

I did not do any deleting of files like other posters.

**Comment by guruz** [comment] 2015-09-13 21:42
Could you guys try to see if this is fixed with a nightly build with @dragotin 's fix above?

http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.5456-nightly20150912-setup.exe

**Comment by FoxBJK** [comment] 2015-09-13 23:52
Worked for me! Green checkmarks for all folders now

**Comment by itlte** [comment] 2015-09-14 07:16
Good Day Markus



Have installed the below update. Got Green Ticks everything looks good so 
far will monitor and let you know..

Thank you VERY Much for your Assistance.  Keep up the good work awesome 
response time.



thanks



Rudi Lombard | IT Administrator

TEL: +27 (0)21 361 5972 |CELL: +27 (0)82 776 2337 |SKYPE: itadmin-lte | 
E-MAIL:  <mailto:itadmin@learntoearn.co.za> itadmin@learntoearn.co.za | 
<http://www.learntoearn.org.za/> www.learntoearn.org.za

**Comment by heimdal31** [comment] 2015-09-14 12:09
@guruz 

I too can confirm this fixes the issue.  Thanks, @dragotin  !

**Comment by schnaidar** [comment] 2015-09-14 17:33
I can confirm this fix. Many thanks for this great work!

**Closed** 2015-09-15 10:48 UTC
Labels: ReadyToTest
