### ISSUE TITLE
[2.0.2] no support for symblic links on sync... anymore

### ISSUE THREAD

**Issue by RalfWW** [owncloud/client#4014] opened 2015-10-27 19:37 UTC
Updating from 2.0.1 to 2.0.2 and getting - in German - the message "no support for symbolic links on sync".

How stupid is that, do deactivate a functionality, that was available/running on the previous version, without showing this - in bold - at the release notes???

The goal is - for my understanding - to have support for symbolic links (not only folders but also for a single file) in the near future.
It is better to live with a not perfect functionality than having NO functionality!

Reg.
Ralf

**Comment by danimo** [comment] 2015-10-27 19:39
Duplicate of #4013

**Closed by danimo** 2015-10-27 19:39 UTC

**Comment by RealRancor** [comment] 2015-10-27 19:46
> How stupid is that

Thats the way to go :see_no_evil:
