### ISSUE TITLE
Improve error for missing data during discovery

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7112] opened 2019-03-26 10:02 UTC
"The server file discovery reply is missing data" errors are surprisingly frequent and often need our attention to diagnose.

1) Improve the error message to mention the file name and what data is missing. This will give users more hints for attempting to fix the error themselves.
2) Potentially continue syncing other items

**Comment by lazawan** [comment] 2019-05-27 13:28
@ckamm where should this Error-Message be shown and how could we reproduce this Error ?

**Comment by michaelstingl** [comment] 2019-05-27 14:19
I think you could remove the `etag` entry for file in the ownCloud server database manually. Not sure if this is a good issue for qa? /cc @HanaGemela @ckamm

**Comment by ckamm** [comment] 2019-05-28 09:02
Yes, this is not straightforward to QA. There's an autotest for the errors in testMissingData in testRemoteDiscovery.cpp and that's how I verified the new behavior works. It's a quality-of-life improvement for debugging a fairly rare error that we mostly see in enterprise contexts.

To test with a real server one would need to make it send replies that lack the size, permissions, etag or fileid. Manually adjusting the server db as suggested may work. Otherwise you'd need a proxy that filters replies.

Test cases:
1. If server doesn't send data for one of these properties, the sync errors with "server reported no X". The error should also be visible per affected file in the sync protocol.
2. Such an error does not abort the sync run: other files will be up/downloaded as normal.

**Comment by michaelstingl** [comment] 2019-05-28 09:38
> Otherwise you'd need a proxy that filters replies.

Yeah, you're right. "Faking" this in `mitmproxy` should be the recommended method. I think @jnweiger played with it before.

**Comment by lazawan** [comment] 2019-05-28 13:08
@ckamm I have just tried to remove Etag from Server response and  I didn't get an Error-Message, I got only in logs that Etag is invalid 

> 05-28 05:50:18:979 [ info gui.folder ]:	#### Propagation start ####################################################
05-28 05:50:18:994 [ info gui.application ]:	Sync state changed for folder  "https://demo.owncloud.org/remote.php/dav/files/demo/" :  "Sync Running"
05-28 05:50:18:994 [ info sync.propagator ]:	Starting INSTRUCTION_NEW propagation of "ldpaspdlapda+ldsad" by OCC::PropagateLocalMkdir(0x7a82af0)
05-28 05:50:18:994 [ info sync.database ]:	Updating file record for path: "ldpaspdlapda+ldsad" inode: 830 modtime: 1559047751 type: 2 etag: "_invalid_" fileId: "00000110oc4ufmy650o1" remotePerm: "DNVCKR" fileSize: 0 checksum: ""
05-28 05:50:19:009 [ info sync.propagator ]:	Completed propagation of "ldpaspdlapda+ldsad" by OCC::PropagateLocalMkdir(0x7a82af0) with status 4
05-28 05:50:19:009 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:OK:C:\\Users\\admin\\ownCloud8" to QLocalSocket(0x15fbc28)
05-28 05:50:19:025 [ info gui.folderwatcher ]:	Detected changes in paths: QSet("C:/Users/admin/ownCloud8/ldpaspdlapda+ldsad")
05-28 05:50:19:025 [ info sync.database ]:	Updating file record for path: "ldpaspdlapda+ldsad" inode: 830 modtime: 1559047751 type: 2 etag: "5ced2e47c786c" fileId: "00000110oc4ufmy650o1" remotePerm: "DNVCKR" fileSize: 0 checksum: ""
05-28 05:50:19:041 [ info sync.database ]:	Closing DB "C:/Users/admin/ownCloud8/._sync_f3502dd50375.db"
05-28 05:50:19:072 [ info sync.engine ]:	CSync run took  56877 ms
05-28 05:50:19:072 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:OK:C:\\Users\\admin\\ownCloud8" to QLocalSocket(0x15fbc28)
05-28 05:50:19:072 [ info gui.folder ]:	Client version 2.5.4 (build 11415)  Qt 5.11.2  SSL  OpenSSL 1.1.1  11 Sep 2018
05-28 05:50:19:089 [ info gui.folder ]:	SyncEngine finished without problem.
05-28 05:50:19:104 [ info gui.folder ]:	Folder sync result:  3
05-28 05:50:19:104 [ info sync.database ]:	sqlite3 version "3.26.0"
05-28 05:50:19:104 [ info sync.database ]:	sqlite3 locking_mode= "exclusive"
05-28 05:50:19:104 [ info sync.database ]:	sqlite3 journal_mode= "wal"
05-28 05:50:19:104 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:OK:C:\\Users\\admin\\ownCloud8" to QLocalSocket(0x15fbc28)
05-28 05:50:19:104 [ info gui.socketapi ]:	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\admin\\ownCloud8" to QLocalSocket(0x15fbc28)
05-28 05:50:19:104 [ info gui.application ]:	Sync state changed for folder  "https://demo.owncloud.org/remote.php/dav/files/demo/" :  "Success"
05-28 05:50:19:321 [ info gui.folder.manager ]:	<========== Sync finished for folder [ownCloud8] of account [demo@demo.owncloud.org] with remote [https://demo.owncloud.org/remote.php/dav/files/demo/]
05-28 05:50:19:321 [ info gui.folder ]:	Trying to check "https://demo.owncloud.org/remote.php/dav/files/demo/" for changes via ETag check. (time since last sync: 0 s)
05-28 05:50:19:321 [ info sync.accessmanager ]:	6 "PROPFIND" "https://demo.owncloud.org/remote.php/dav/files/demo/" has X-Request-ID "98f6a3c2-de5d-4b4a-af7d-6340fcd48ffd"
05-28 05:50:19:321 [ info sync.networkjob ]:	OCC::RequestEtagJob created for "https://demo.owncloud.org" + "/" "OCC::Folder"
05-28 05:50:20:543 [ info sync.networkjob.etag ]:	Request Etag of QUrl("https://demo.owncloud.org/remote.php/dav/files/demo/") FINISHED WITH STATUS "OK"
05-28 05:50:23:184 [ info sync.accessmanager ]:	6 "PROPFIND" "https://demo.owncloud.org/remote.php/dav/files/demo/" has X-Request-ID "4a545d84-eec6-4fbb-a296-f21905ed7669"

>

**Comment by michaelstingl** [comment] 2019-05-28 13:11
> @ckamm I have just tried to remove Etag from Server response using mitmproxy

Could you post the `mitmproxy` you were using?

**Comment by ckamm** [comment] 2019-05-28 14:12
@lazawan The `_invalid_` etag on new local directory creation is normal. Filter the etag for a file.

**Comment by HanaGemela** [comment] 2019-07-29 09:18
@ckamm I've uploaded Black.txt on the server and removed etag using mitm proxy. I don't see any message in the log complaining about missing etag. Log has been shared with you via owncloud please have a look

**Comment by ckamm** [comment] 2019-07-29 12:54
@HanaGemela The log shows the client receiving an etag for Black.txt. Double check that your filter works with something like
```
curl yoururl/remote.php/dav/files/youruser -XPROPFIND -u youruser | xmllint --format -
```

**Comment by HanaGemela** [comment] 2019-07-29 15:04
@ckamm it received OC-etag. What is the difference between just etag and OC-etag?

**Comment by ckamm** [comment] 2019-07-30 08:59
@HanaGemela "OC-ETag" and "ETag" from replies to uploads/downloads are used to make sure the etag stored in the database matches the one on the server. (e.g. if a new file is uploaded, the server reports the etag that was assigned to it immediately; if a download happens the server sends the etag along with the data, after all it may have changed since discovery)

This issue isn't about these headers at all. Instead it's about the "getetag" property in the xml response to PROPFIND requests used during discovery. If it's missing there, we assume something is wrong with the server.

**Comment by ckamm** [comment] 2019-07-30 09:02
There's no difference between OC-ETag and ETag, except that they should be identical if both are present. (though this is currently not an error, OC-ETag is preferred)

**Comment by jnweiger** [comment] 2019-07-30 16:36
@ckamm 'OC-ETag' and 'ETag' are headers. There is also `<d:getetag>` nodes in the response body, like e.g. in 
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/admin/</d:href>
    <d:propstat>
      <d:prop>
        <d:resourcetype><d:collection/></d:resourcetype>
        <d:getlastmodified>Tue, 30 Jul 2019 13:37:12 GMT</d:getlastmodified>
        <d:getetag>&quot;3442ff0769c271e17e2e21acd923b94f&quot;</d:getetag>
        <oc:id>00000003ocqpcovfmonr</oc:id>
        <oc:permissions>RDNVCK</oc:permissions>
        <oc:data-fingerprint></oc:data-fingerprint>
        <oc:share-types/>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
...
```

**Comment by ckamm** [comment] 2019-07-31 07:01
@jnweiger Yes, that's what I was attempting to say. This issue isn't about headers. it's about the data in PROPFIND replies.

**Comment by HanaGemela** [comment] 2019-07-31 09:50
```07-31 11:46:53:346 [ warning sync.propagator ]:	Could not complete propagation of "San Francisco.jpg" by OCC::PropagateIgnoreJob(0x600003a03b80) with status OCC::SyncFileItem::NormalError and error: "server reported no etag"```

![image](https://user-images.githubusercontent.com/49001702/62202156-0d819b80-b389-11e9-9046-3f4ca620b77e.png)

Works as expected, mac 10.14.6, client 2.6.0alpha2 (build 12128)

**Closed by HanaGemela** 2019-07-31 09:50 UTC
Labels: Enhancement, ReadyToTest
