### ISSUE TITLE
[macOS] client icon does not grey out on secondary monitors

### ISSUE THREAD

**Issue by carnott-snap** [owncloud/client#5379] opened 2016-12-13 00:22 UTC
### Expected behaviour
On non-primary monitors, desktop icons should grey out to indicate the non-primary/background status of that monitor 

### Actual behaviour
The icon stays white/full colour

### Steps to reproduce
0. Install client via homebrew on macOS
1. configure to use monochrome icon
2. connect second monitor
3. note that on non-primary monitor(s), all other icons darken to indicate that the monitor is not primary/selected, owncloud does not

### Client configuration
Client version: Version 2.2.4 (build 3709)

Operating system: macOS

OS language: English

Installation path of client: homebrew

### Screenshot
![menubar](https://cloud.githubusercontent.com/assets/23408377/21122395/c3363b8a-c0c9-11e6-9123-4a08bed60f2e.png)

**Comment by SamuAlfageme** [comment] 2016-12-13 08:16
@carnott-snap hmm... I've seen the same in a couple of apps after updating to macOS sierra. I'll try to find out what's going on. Thanks!

**Comment by guruz** [comment] 2016-12-13 11:19
(This might be fixed with a newer Qt version..)
FYI @tsparber

**Comment by tsparber** [comment] 2016-12-13 11:28
This should already be fixed by https://github.com/owncloud/client/pull/5227 and is scheduled for the 2.3.0 [milestone](https://github.com/owncloud/client/milestone/31). It also requires atleast Qt 5.6.0, which is also planned for 2.3.0 (as far as I know).

@carnott-snap: You could also try to build the latest client master with Qt >= 5.6.0 and see if the problem is also resolved for you.

**Comment by SamuAlfageme** [comment] 2016-12-13 11:58
@carnott-snap @tsparber We're actually already building nightlies with Qt 5.6.2 so you can try it without the trouble to build it: http://download.owncloud.com/desktop/daily/ 😊

**Comment by carnott-snap** [comment] 2016-12-13 19:37
that fix works for me; thanks for the quick response!

**Closed** 2016-12-13 20:51 UTC
Labels: Design & UX, ReadyToTest
