### ISSUE TITLE
Smashed icon in macOS Big Sur tray when using two displays

### ISSUE THREAD

**Issue by emersonmello** [owncloud/client#8227] opened 2020-11-15 18:44 UTC
### Expected behaviour

Normal icon on both displays.

### Actual behaviour
Normal icon on active display (display with keyboard and mouse focus) and a smashed icon on the other monitor.

![normal](https://user-images.githubusercontent.com/9929199/99193638-130b1c80-2759-11eb-95bc-578104b632a6.png)

<img width="417" alt="smashed" src="https://user-images.githubusercontent.com/9929199/99193637-10a8c280-2759-11eb-89d0-f81f930551d5.png">

### Steps to reproduce
1. Connect an external monitor to the macbook running macOS Big Sur
2. See what the tray icon looks like on both monitors.

### Client configuration
Client version: 2.6.3 (build 13765)

Operating system: macOS Big Sur 11.0.1

OS language: English

Installation path of client: /Applications

**Comment by TheOneRing** [comment] 2020-11-16 15:42
Duplicate of: #8226

**Closed by TheOneRing** 2020-11-16 15:42 UTC
