### ISSUE TITLE
Random files/directories deleted by Windows client v.1.8.0

### ISSUE THREAD

**Issue by markmasadit** [owncloud/client#3207] opened 2015-05-06 16:15 UTC
### Expected behaviour
File structure remains unchanged when no change is introduced 

### Actual behaviour
Random directories/files are deleted by the client
Client redownloads the files after discovering them on the server

### Steps to reproduce
1. Upload some files to the server
2. Wait and do nothing
3. Client deletes random directories and files from local storage

### Server configuration

* *NOTE: Bitnami ownCloud machine in Microsoft Azure VPS*

Operating system: Ubuntu 14.04.1 LTS x86_64

Web server: Apache 2.4.10 (mpm_event)

Database: MySQL 5.5.38

PHP version: PHP 5.4.31

ownCloud version: 7.0.1

Storage backend: local

### Client configuration
Client version: 1.8.0.4893

Operating system: Windows 7 Professional x64

OS language: Hebrew/English

Installation path of client: "c:\Program Files (x86)\ownCloud" 

### Logs

1. Client log

* *NOTE: nothing logged between 2015-05-05 17:47:56 and 2015-05-06 14:43:42*
```
#=#=#=# Syncrun started 2015-05-05T16:29:29 until 2015-05-05T16:29:36 (7229 msec)
#=#=#=# Syncrun started 2015-05-05T16:33:10 until 2015-05-05T16:55:09 (1318630 msec)
#=#=#=# Syncrun started 2015-05-05T16:56:06 until 2015-05-05T17:07:54 (707507 msec)
#=#=#=# Syncrun started 2015-05-05T17:08:36 until 2015-05-05T17:47:56 (2360144 msec)
14:43:42|15412|<directory>/UpdateInfo/<filename1>|INST_NEW|Down|1378968694|54e9d694f3e43|10989568|00404416occ4f0a27486|4||0|0|0|||INST_NONE|
14:43:42|9027|<directory>/UpdateInfo/<filename2>|INST_NEW|Down|1331457002|54e9d69ce69ab|308818|00404417occ4f0a27486|4||0|0|0|||INST_NONE|
14:43:42|10517|<directory>/UpdateInfo/<filename3>|INST_NEW|Down|1328108458|54e9d69eaba7b|296378|00404418occ4f0a27486|4||0|0|0|||INST_NONE|
14:43:51|8007|<directory>/UpdateInfo/<filename4>|INST_NEW|Down|1374745062|54e9d6f0ab5f5|7122944|00404424occ4f0a27486|4||0|0|0|||INST_NONE|
```
2. Web server error log:

No lines regarding this user

3. ownCloud log (data/owncloud.log):

No lines regarding this user

**Comment by danimo** [comment] 2015-05-06 16:17
Fixed in 1.8.1, due tomorrow. 1.8.1 will also return the files that got deleted locally. Duplicate of #3102.

**Comment by markmasadit** [comment] 2015-05-06 16:18
10x @danimo

**Closed by danimo** 2015-05-06 16:17 UTC

**Comment by moscicki** [comment] 2015-05-06 16:42
@danimo: could you please point me to the code that implements the logic to return the files which got deleted locally?

**Comment by dragotin** [comment] 2015-05-06 16:46
@moscicki its here: d63abef718ebab0717c496dca11a9ad363bf6965

Basically in case we detect that its the first run after an update from 1.8.0 we forbid to read the remote content from db, but instead query it one time from server again. With that information, missing files on local repo will be detected and downloaded.

**Comment by sleepysmurf** [comment] 2015-05-07 14:43
when is this set to release ?

**Comment by danimo** [comment] 2015-05-07 14:44
@sleepysmurf 2 hours ago: https://owncloud.org/install/#install-clients

**Comment by sleepysmurf** [comment] 2015-05-07 14:46
will the old clients auto update to this new version ?  Or does it need to be installed manually ?

**Comment by markmasadit** [comment] 2015-05-07 14:59
1.8.1 RC2 doesn't update to 1.8.1 stable automatically?

**Comment by danimo** [comment] 2015-05-07 15:02
The auto updater is now fed with the new information. You should get an update request eventually.

**Comment by danimo** [comment] 2015-05-07 15:02
(currently, this only works if you restart the client, on Windows you can track the download progress).

**Comment by sleepysmurf** [comment] 2015-05-14 02:18
Sorry to say but with the 1.8.1 client I just had a backup client call me today and say all of their files were deleted again... clearly there is still an underlying issue at hand.. any thoughts on the root cause of this ?  Deleting clients local folders is really causing a lot of problems for myself and my clients as you may imagine.. :(
