### ISSUE TITLE
[Linux] No connection to ... Access to the network is forbidden error

### ISSUE THREAD

**Issue by piratenpanda** [owncloud/client#4003] opened 2015-10-26 13:26 UTC
This appeared either while upgrading to oc 8.2 or to sync client 2.0.2, i don't know and I don't know how to prevent it. When closing the client and restarting it, everything is fine. It may also be related to the laptop going to suspend and waking up again frequently.

This is on Antergos Linux running latest client 2.0.2

Is there a way to debug this?

**Comment by guruz** [comment] 2015-10-26 13:29
```owncloud --logfile -```
on a shell might give you some info.

**Comment by piratenpanda** [comment] 2015-10-26 13:41
After the last successful sync this happens http://pastebin.com/tAUWmJHb

**Comment by piratenpanda** [comment] 2015-10-26 13:43
Ok, doesn't seem to be the problem as it works fine again, will test further

**Comment by piratenpanda** [comment] 2015-10-26 16:17
Funnily it happened all the time but now I used the logging once it doesn't want to reappear. I will close this for now

**Comment by piratenpanda** [comment] 2015-11-12 13:26
It now happens on my wife's laptop as well and seems to be related to suspend. Reopening this

**Comment by piratenpanda** [comment] 2015-11-12 13:32
Ok, managed to reproduce it. 

1. Suspend laptop
2. Wake from suspend, everything is fine
3. Put something in your owncloud folder
4. Syncing doesn't work, throws network access forbidden error
5. Restarting client starts syncing and sync finishes successfully

Expected result:
Sync should work after suspend without restarting the client.

Error message from the log:
11-12 14:28:46:544 757 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
11-12 14:28:46:544 757 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://owncloud.***.org" + "/"
11-12 14:28:46:544 757 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Der Zugriff auf das Netzwerk ist nicht gestattet." QVariant(Invalid)
11-12 14:28:46:544 757 unknown: QIODevice::read (QDisabledNetworkReply): device not open
11-12 14:28:46:544 757 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Connected" -> "Timeout"
11-12 14:28:46:544 757 OCC::AccountState::setState: AccountState state change:  "Verbunden" -> "Netzwerkfehler"
11-12 14:28:46:544 757 OCC::AccountSettings::showConnectionLabel: "Keine Verbindung zu ownCloud auf <a href=\"https://owncloud.***.org\">https://owncloud.***.org</a>\nDer Zugriff auf das Netzwerk ist nicht gestattet."
11-12 14:28:46:545 757 OCC::FolderMan::slotAccountStateChanged: Account "Benjamin_L@owncloud.***.org" disconnected, terminating or descheduling sync folders
11-12 14:28:46:545 757 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
11-12 14:28:46:718 757 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("/home/panda/ownCloud/Cu1_w420.txt")

**Comment by guruz** [comment] 2015-11-12 14:10
What does the log say about the "Qt" version used?

**Comment by piratenpanda** [comment] 2015-11-12 14:16
11-12 14:26:50:581 757 OCC::SyncEngine::startSync: =====Using Qt 5.5.1

**Comment by piratenpanda** [comment] 2015-11-12 14:18
Oh and btw sry for the german log, didn't notice it before posting

**Comment by guruz** [comment] 2015-11-12 14:24
Duplicate of https://github.com/owncloud/client/issues/4051#issuecomment-153491392
:-|

**Closed by guruz** 2015-11-12 14:24 UTC
