### ISSUE TITLE
Systray icon broken on Ubuntu 14.04 ater update to 2.2.0

### ISSUE THREAD

**Issue by etamme** [owncloud/client#4828] opened 2016-05-12 18:00 UTC
### Expected behaviour

The systray icon should be in the systray area with other systray Icons
### Actual behaviour

The Systray icon is in the very top left of my screen and appears to be "on top" of all other windows.  
### Steps to reproduce
1. Run the official upstream owncloud client on Ubuntu 14.04 LTS
2. Let updates run as seen in this apt history https://gist.github.com/etamme/9e547c536b44f7a3f2b0998b8765bd94
3. The systray icon is now in the wrong place

I believe the fix for #4693 might be related to this issue.
### Server configuration

Operating system: centos 7
Web server: apache
Database: mariadb

PHP version: 5.4.16

ownCloud version: 9.0.0 stable

Storage backend: ? disk
### Client configuration

Client version: 2.2.0

Operating system: ubuntu 14.04

OS language: English

Installation path of client:  /usr/bin/owncloud

**Comment by aslmx** [comment] 2016-05-12 18:31
Same for me on Mint 17.3 XFCE.

```
Version 2.2.0%nil (build 1605).
Built from Git revision 49a678 on May 12 2016, 13:14:45 using Qt 5.2.1, OpenSSL 1.0.1f 6 Jan 2014
```

notice the %nil which is shown in the about box....

**Comment by babs** [comment] 2016-05-12 20:24
Same issue except on XFCE, I don't see the icon on the top left of the screen, just no icon at all.
Ubuntu 14.04 64b / XFCE

```
ownCloud version 2.2.0%nil (build 1605)
Using Qt 5.2.1
```

**Comment by danimo** [comment] 2016-05-12 20:26
The 14.04 packages must not build against Qt 5. @jnweiger pls.

**Comment by DroWnThePoor** [comment] 2016-05-13 08:15
I'm having this problem on Elementary OS Freya with Pantheon Desktop(Gnome 3 based).
Started right after upgrade to ownCloud version 2.2.0%nil (build 1605)
This is through the OpenSuse PPA.
Except I have NO systray icon whatsoever.
Have tried purging, but my login credentials/config are retained after the re-install, any idea why?
Is it somehow stored in the local database file?
This is a laptop using HDMI out to an LED television.

Does anyone know how to revert to the version prior?
Because I was perfectly happy with it.

**Comment by etamme** [comment] 2016-05-13 13:31
This issue persists after recent updates - apt history log from latest update:

 owncloud-client:amd64 (2.2.0-1.1, 2.2.0-2.1)

**Comment by andreagrax** [comment] 2016-05-13 13:33
me too - no icon in the tray 
Xubuntu 14.04

`ownCloud version 2.2.0%nil (build 1605)`
`Using Qt 5.2.1`

**Comment by danimo** [comment] 2016-05-13 13:35
We are aware of the issue. We are looking into making it build with Qt4 again on Ubuntu 14.04, where that Problem does not exist.

**Comment by etamme** [comment] 2016-05-13 13:35
@danimo thanks for the update!

**Comment by babs** [comment] 2016-05-13 15:54
I installed this morning update (pkg version 2.2.0-2.1) but still the same issue.

**Comment by RealRancor** [comment] 2016-05-13 17:17
@babs Please read https://github.com/owncloud/client/issues/4828#issuecomment-219044270

As the issue is known and not fixed yet (this bugreport is still in the Open state) there is no need to post "still the same issue" or similar. To express that you're affected by this issue you can use the emoticon (+ smiliey) and the first post of this post at the top right. This avoids that the issue gets filled with comments not providing additional info for this issue.

**Comment by babs** [comment] 2016-05-13 17:42
@RealRancor I take good note.
As I already [reported](https://github.com/owncloud/client/issues/4828#issuecomment-218874827) the issue with yesterday's package and WM impacted, I just wanted to confirm that today's release hasn't changed the issue as I thought this morning update integrated what [damino's comment](https://github.com/owncloud/client/issues/4828#issuecomment-219044270) mention.

**Comment by awnz** [comment] 2016-05-13 20:27
This is a frustrating one as it constantly overlays other applications' "Close" icons when fullscreen. I'm also seeing much more "Operation cancelled" / "Connection closed" sync failures.

Can static binaries / deb packages of older versions of the sync client be made available? In my case it would help people get around both this and bug #4334 which in turn is blocking the workaround I was using for bug #9832. It's frustrating that we can't revert to an older version when major bugs happen in updates like this.

**Comment by aslmx** [comment] 2016-05-14 17:50
I updated today, seems fixed for me


`Version 2.2.0%nil (build 1605). For more information visit owncloud.com
Built from Git revision 49a678 on May 12 2016, 13:14:45 using Qt 5.2.1, OpenSSL 1.0.1f 6 Jan 2014`

**Comment by mibadim** [comment] 2016-05-14 18:23
Just updated. There is some improvement, but ...
![bildschirmfoto](https://cloud.githubusercontent.com/assets/5670523/15269998/02ce55a8-1a11-11e6-8a58-2326b35097d9.png)
Although space is reserved, the icon does not show up.

**Comment by gnocera** [comment] 2016-05-14 18:33
Hi, same issue here.  Ubuntu 14.04 LTS and last Owncloud client (v. 2.2.0%nil build 1605)
Built from Git revision 49a678 on May 14 2016, 13:16:24 using Qt 5.2.1, OpenSSL 1.0.1f 6 Jan 2014

Icon still appears on the upper-left side of the screen. 
Now this is very annoying because owncloud icon is located just over the closing icon of any opened application (Firefox, Libreoffice, etc.). Here is the picture.

![zzz owncloud problem](https://cloud.githubusercontent.com/assets/12708172/15270048/fd0330dc-19d7-11e6-90f1-adc4a4eb0060.png)

**Comment by awnz** [comment] 2016-05-14 18:54
Build 1605 does not resolve for me either. To get around both this and the longstanding bug #4334, I'd like to request that the last of the v2.0 Linux binaries and packages be made available for direct download (I've repeated this request in #4334).

**Comment by awnz** [comment] 2016-05-14 19:43
I got around this by compiling v2.0.2 myself (details in #4334).

**Comment by danimo** [comment] 2016-05-14 20:12
> I'd like to request that the last of the v2.0 Linux binaries and packages be made available for direct download

I have no idea what you mean. Binaries and packages are available for direct download, but that will change nothing over acquiring them through OBS.

**Comment by kmorgen1** [comment] 2016-05-14 20:53
Well,  a reasonable amount of googleing only ever gets you [here](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client)



What commands to I have to execute to install v2.0 from repository files?

This may be kind of obvious for the deeply

**Comment by DroWnThePoor** [comment] 2016-05-15 00:59
Elementary OS Freya (Ubuntu 14.04)

I installed the 3Rd update  today, I still have no icon at all.
Also since this update my Tomahawk music player will no longer open at all,
It also relies on qt and used to have a spot in my system tray.
I'm nearly certain today's Owncloud-Client update is what broke it,because that was my only update today.

**Comment by RealRancor** [comment] 2016-05-15 07:11
If i understand it correctly this won't be fixed as long as the Version of the client contains "using Qt 5.2.1" instead of something like "using Qt 4.x.x". So its not needed to post " it still doesn't work"

**Comment by almostearthling** [comment] 2016-05-15 15:15
One of the problems is that it's impossible to downgrade to a working version of the client: current version of the 2.1.1 release is 2.1.1-13.3 that links against qt5 just like 2.2.0; one possible workaround could be to be able to install `owncloud-client_2.1.1-1.1_(arch).deb` and temporarily suspend automatic updates from the repository, but it has disappeared from the repos (and apparently from the Internet!!!). If anyone knows about an archive still containing said package, which was built on Feb 9, could possibly mention it here.

**Comment by awnz** [comment] 2016-05-15 20:08
Hi @danimo can you please expand on that? Your link only goes to the latest v2.2.x version, with no access to packages for anything prior (ie v2.1.x, v2.0.x, v1.x)

Anyway I compiled my own (details [here](https://github.com/owncloud/client/issues/4334#issuecomment-219239393)).

**Comment by danimo** [comment] 2016-05-15 20:25
@awnz No, unfortunately not. OBS only keeps the latest version. We are going to fix this, but on an (extended) weekend that's a bit challenging, since most of the people involved are working on this on their day job.

**Comment by awnz** [comment] 2016-05-15 22:32
Ah - wasn't aware it was an extended weekend over there It's a normal work Monday morning in NZ :)

Anyway, I've linked to compile instructions for anyone who needs/wants it fixed fast by rolling back.

**Comment by mirams** [comment] 2016-05-16 09:55
Same problem here...

**Comment by dajare** [comment] 2016-05-16 10:05
I noted this on [Askubuntu.SE][a] before finding this issue.

It is possible to "force" a version downgrade using Synaptic (`Package > Force Version...`), but unfortunately it only gives `1.5.0+dfsg-4ubuntu1(trusty)` as an option:

![selection_558](https://cloud.githubusercontent.com/assets/40625/15286637/06887836-1b56-11e6-8cf0-51c354c24360.png)

Looking forward to getting a fix ... before the LTS-to-LTS upgrade comes!

[a]: http://askubuntu.com/q/771885/38585

**Comment by DmitriyLyalyuev** [comment] 2016-05-16 14:15
Same problem. Tray icon is not in tray. :(
![Screenshot](http://shrt.pp.ua/gj)

**Comment by RealRancor** [comment] 2016-05-16 14:28
@mirams @DmitriyLyalyuev https://github.com/owncloud/client/issues/4828#issuecomment-219104749

**Comment by DroWnThePoor** [comment] 2016-05-16 20:08
I have a working copy on another computer of an older version: probably 1.85 or so, Would it be possible to transfer this to my main machine/make it available to everyone else?

**Comment by EmersonFreire** [comment] 2016-05-16 22:14
Same problem:
![owncloud-client](https://cloud.githubusercontent.com/assets/19375134/15305595/55c6f17c-1b9a-11e6-8992-60d27e11d94a.png)

**Comment by keunes** [comment] 2016-05-16 22:25
PLEASE READ BEFORE POSTING ANY COMMENT:

> As the issue is known and not fixed yet (this bugreport is still in the Open state) there is *no need to post "still the same issue" or similar*. To express that you're affected by this issue *you can use the emoticon (+ smiliey) on the first post at the top right*. [https://github.com/owncloud/client/issues/4828#issuecomment-219104749]

After, you can subscribe to this issue, to get updated as soon as there's any development.
'Me too'-comments don't help but rather spam all of us. The problem has been identified and will hopefully see a fix soon.

**Comment by DroWnThePoor** [comment] 2016-05-16 22:44
Probably gonna get smacked for this, 
But couldn't we possibly just install QT-5? Isn't QT supposed to be backwards compatible for most all cases?
I ask because I have another program (Tomahawk-Player) which completely stopped working just after my last ownCloud-client update, not sure how it's related but that is the way it appears because my errors shown from it in the terminal and with gdb/strace seem to point to qt-4 and 5 issues.

**Comment by danimo** [comment] 2016-05-16 23:57
@DroWnThePoor Sorry, that comment made no sense at all. Qt is not binary compatible between version 4 and 5. Qt 5 systray applications are generally hosed in systray with Ubuntu 14.04, which is why we need to use Qt4 for that, but Qt5 for 16.04. Expressing that in Debian build files is harder than expected, and we want to get it right, so please bear with us.

**Comment by DougGerrard** [comment] 2016-05-17 00:26
Hi I have 2 pcs running Ubuntu 14.04LTS they are both updated as of 17/5/16 12:00 NZ time. They are both 64bit i5 processors one a desktop running an Asus motherboard and the other is an Acer Laptop interestingly only the Desktop has the owncloud icon problem the laptop still has the icon in the normal place. Could it be a graphics driver problem? Happy to give more detail if required.

**Comment by DougGerrard** [comment] 2016-05-17 00:32
Hi I have 2 pcs running Ubuntu 14.04LTS they are both updated as of 17/5/16 12:00 NZ time. They are both 64bit i5 processors one a desktop running an Asus motherboard and the other is an Acer Laptop interestingly only the Desktop has the owncloud icon problem the laptop still has the icon in the normal place. Could it be a graphics driver problem? Happy to give more detail if required.

**Comment by DougGerrard** [comment] 2016-05-17 00:34
Hi I for got to restart the desktup after update. I just restarted the desktop the icon has now disapeared completely but the sync is still running fine.

**Comment by danimo** [comment] 2016-05-17 00:51
@DougGerrard Please read the thread before posting: https://github.com/owncloud/client/issues/4828#issuecomment-219567013. I'll have to lock
 this thread for now :(

**Comment by guruz** [comment] 2016-05-18 08:40
For people that have no tray icon at all with Qt5 builds: Some people have reported that running the client with

```
QT_QPA_PLATFORMTHEME=generic /usr/bin/owncloud
```

works.

**Comment by danimo** [comment] 2016-05-27 09:28
This has been fixed in the meanwhile through updated packages.

**Comment by artem-sidorenko** [comment] 2016-05-27 10:23
The updated packages have a lower release version (I had 2.2.0-4.1 installed, current version is 2.2.0-2), so you have to remove owncloud-client and libowncloudsync0 and install them again

**Comment by rfc1459** [comment] 2016-05-27 10:23
The package version number is botched, though: it's `2.2.0-2` while the broken one (which has been pulled from OBS) is `2.2.0-2.2`, so apt considers the broken package *more recent* than the fixed one. This means that apt will *never* pick up the new package and users would be forced to "downgrade" owncloud-client and all related packages to that version, which is not that easy.

The best option (IMO) is yet another version bump to `2.2.0-3`, so that users can actually get the updated packages.

**Comment by emanuk** [comment] 2016-05-27 11:28
On Ubuntu 14.04 I get these errors:

```
owncloud-client: Depends: libc6 (>= 2.14) mais la version 2.19-0ubuntu6.9 va être installée
                 Depends: libgcc1 (>= 1:3.0) mais la version 1:4.9.3-0ubuntu4 va être installée
                 Depends: libowncloudsync0 (= 2.2.0-2) mais la version 2.2.0-2 va être installée
                 Depends: libqt5core5a (>= 5.5.0) mais la version 5.2.1+dfsg-1ubuntu14.3 va être installée
                 Depends: libqt5dbus5 (>= 5.0.2) mais la version 5.2.1+dfsg-1ubuntu14.3 va être installée
                 Depends: libqt5gui5-gles (>= 5.0.2) mais il ne va pas être installé
                 Depends: libqt5network5 (>= 5.0.2) mais la version 5.2.1+dfsg-1ubuntu14.3 va être installée
                 Depends: libqt5webkit5 (>= 5.0.2) mais la version 5.1.1-1ubuntu8 va être installée
                 Depends: libqt5widgets5 (>= 5.2.0) mais la version 5.2.1+dfsg-1ubuntu14.3 va être installée
                 Depends: libqt5xml5 (>= 5.0.2) mais la version 5.2.1+dfsg-1ubuntu14.3 va être installée
                 Depends: libstdc++6 (>= 5.2) mais la version 4.8.4-2ubuntu1~14.04.3 va être installée

```

**Comment by keunes** [comment] 2016-05-27 11:43
On Ubuntu 14.04 I get the following error:
`owncloud: symbol lookup error: /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0: undefined symbol: _xxxxKeychain15ReadPasswordJob6setKeyxxxxxString` where the xxx are seemingly random characters which I have no clue if they might represent a password/key or something.

Posting it here as I got this error at the same time the symbol thing popped up.

**Comment by danimo** [comment] 2016-05-27 11:54
Which repositories to you have set?

**Comment by artem-sidorenko** [comment] 2016-05-27 12:04
@danimo 
```bash
$ cat /etc/apt/sources.list.d/isv_ownCloud_desktop.list 
deb      "http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/"  /
```

**Comment by rfc1459** [comment] 2016-05-27 12:05
@danimo The OBS repos:
```
$ cat /etc/apt/sources.list.d/owncloud-client.list
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/ /
$ apt-cache policy owncloud-client owncloud-client-l10n libowncloudsync0 
owncloud-client:
  Installed: 2.2.0-2
  Candidate: 2.2.0-2
  Version table:
 *** 2.2.0-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/  Packages
        100 /var/lib/dpkg/status
     1.5.0+dfsg-4ubuntu1 0
        500 http://it.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
owncloud-client-l10n:
  Installed: 2.2.0-2
  Candidate: 2.2.0-2
  Version table:
 *** 2.2.0-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/  Packages
        100 /var/lib/dpkg/status
     1.5.0+dfsg-4ubuntu1 0
        500 http://it.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
libowncloudsync0:
  Installed: 2.2.0-2
  Candidate: 2.2.0-2
  Version table:
 *** 2.2.0-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/  Packages
        100 /var/lib/dpkg/status
     1.5.0+dfsg-4ubuntu1 0
        500 http://it.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

As you can see, the only version available is `2.2.0-2`, which is lower than the one previously installed (`2.2.0-2.2`), so "updating" requires a "downgrade" of those 3 packages to `2.2.0-2`.

**Comment by emanuk** [comment] 2016-05-27 12:12
@danimo 

deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/

**Comment by giancarlobi** [comment] 2016-05-27 13:02
@danimo @rfc1459 
I have same repo but:
apt-cache policy owncloud-client
owncloud-client:
  Installed: 2.2.0-2.2
  Candidate: 2.2.0-2.2
  Version table:
 *** 2.2.0-2.2 0
        100 /var/lib/dpkg/status
     2.2.0-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/  Packages
     1.5.0+dfsg-4ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages

and 2.2.0-2.2 is my current installation without recent patch.

**Comment by etamme** [comment] 2016-05-27 13:07
apt-get remove owncloud-client-l10n owncloud-client libowncloudsync0 && apt-get install owncloud-client-l10n owncloud-client libowncloudsync0


Fixes the issue for me - thanks

**Comment by fr00x** [comment] 2016-05-27 13:11
That's hardly a viable fix - I expect that this is resolved by a regular update cycle on 14.04.

**Comment by emanuk** [comment] 2016-05-27 13:22
etamme fix not working for me because I have a clean slate.

```
apt-cache policy owncloud-client owncloud-client-l10n libowncloudsync0
owncloud-client:
  Installé : (aucun)
  Candidat : 2.2.0-2
 Table de version :
     2.2.0-2.1 0
        100 /var/lib/dpkg/status
     2.2.0-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/  Packages
     1.5.0+dfsg-4ubuntu1 0
        500 http://ubuntu.bhs.mirrors.ovh.net/ftp.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
owncloud-client-l10n:
  Installé : (aucun)
  Candidat : 2.2.0-2
 Table de version :
     2.2.0-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/  Packages
     1.5.0+dfsg-4ubuntu1 0
        500 http://ubuntu.bhs.mirrors.ovh.net/ftp.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
libowncloudsync0:
  Installé : (aucun)
  Candidat : 2.2.0-2
 Table de version :
     2.2.0-2.1 0
        100 /var/lib/dpkg/status
     2.2.0-2 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/  Packages
     1.5.0+dfsg-4ubuntu1 0
        500 http://ubuntu.bhs.mirrors.ovh.net/ftp.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

**Comment by keunes** [comment] 2016-05-27 13:23
@etamme Erm. Might be a good idea to reopen the issue. Maybe it's fixed for you personally, but like @fr00x said: a proper update would be helpful for many of us:
- regular (noob) users probably don't know what's the problem/that they can solve it/how they can solve it
- reinstalling owncloud means losing a bunch of folder connections & settings :-1:

**Comment by etamme** [comment] 2016-05-27 13:24
It does not lose any settings when reinstalled.  My owncloud connected immediately as if nothing happened.  

I agree, a proper updated with a bumped version would be helpful.  I'll reopen and let the devs close as they see fit.

**Comment by keunes** [comment] 2016-05-27 13:34
> It does not lose any settings when reinstalled. My owncloud connected immediately as if nothing happened.

Had to enter my password again, but worked otherwise.

**Comment by gnocera** [comment] 2016-05-27 15:08
Thanks Etamme !!!

This worked for me

I executed:
**sudo su**

and then

**apt-get remove owncloud-client-l10n owncloud-client libowncloudsync0 && apt-get install owncloud-client-l10n owncloud-client libowncloudsync0**

I am running Ubuntu Desktop 14.04 LTS, here is the output of the terminal command to ckeck the exact version you have
lsb_release -a
______________________________________________________
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
_______________________________________________________________________

Regards.

**Comment by rfc1459** [comment] 2016-05-27 15:40
@giancarlobi That's the core of the packaging issue: apt considers `2.2.0-2` (from the OBS repo, priority 500) lower than `2.2.0-2.2` (from your current system, priority 100), so apt will not pick up the packages from the OBS repo unless their version is bumped (or you go out of your way and pin the OBS repo to priority 1000 or higher, but **never ever do that**).

My output is different because I had already (forcefully) installed the new packages, so all traces of `2.2.0-2.2` were gone.

**Comment by mibadim** [comment] 2016-05-27 17:13
The latest build works for me on Debian Stable and XFCE. Very happy now.
![bildschirmfoto - 27 05 2016 - 18 59 04](https://cloud.githubusercontent.com/assets/5670523/15615477/f7d6dbc4-243e-11e6-8a02-9954bae36629.png)

**Comment by silvain** [comment] 2016-05-29 16:10
Wonderful
This worked for me (also Ubuntu 14.04, owncloud icon was misplaced at the left...)

I tried a direct sudo su apt-get...
but I ended with an error message about rights into the personal folder, and no more 
owncloud client...

Then, I did it as suggested in two commands

  * *sudo su*
  * *apt-get remove owncloud-client-l10n owncloud-client libowncloudsync0 && apt-get
    install owncloud-client-l10n owncloud-client libowncloudsync0*

I just *restarted the session* and owncloud was there with its icon at the right place.
Configuration was intact, with my 3 different accounts, no need to reset passwords...

Many thanks
/Silvain Dupertuis/


Le 27. 05. 16 17:08, gnocera a écrit :
>
> Thanks Etamme !!!
>
> This worked for me
>
> I executed:
> *sudo su*
>
> and then
>
> *apt-get remove owncloud-client-l10n owncloud-client libowncloudsync0 && apt-get install 
> owncloud-client-l10n owncloud-client libowncloudsync0*
>
>
Silvain Dupertuis
Route de Lausanne 335
1293 Bellevue (Switzerland)
tél. +41-(0)22-774.20.67
portable +41-(0)79-604.87.52
web: Service Fraternel d'Entraide <http://www.afe-laos.org>

**Comment by Bazon** [comment] 2016-05-31 04:14
I got no tray icon on a arch linux system with owncloud-client 2.2.0, downgrading owncloud.client solved it. But the strange thing is: on two other similar systems owncloud-client 2.2.0 provides the tray icon! And even more strange: Even on the same computer where the problem appears, with another user-profile there's no problem at all. All systems run most recent arch linux with XFCE as DE. The system/usper-profile combination where the problem appears uses kwin_x11 as windowmanager. But even after switching back to xfwm4 as windowmananger and relogging in, the missing tray icon problem apppeared. 
So I don't really understand it, but just want to add that this problem with the very same packages installed can occur or not.

**Comment by fr00x** [comment] 2016-06-03 12:58
This is still not fixed through a regular update cycle. Remember, there are tons of average non-technical users also on Linux - and for them the last update broke the icon.

**Comment by dogsbody** [comment] 2016-06-06 09:12
Still no update for the general users of this package!? :-(

**Comment by danimo** [comment] 2016-06-06 09:15
We are releasing 2.2.1 today. Would be nice if someone could try the RC1 packages: https://owncloud.org/install/#testing-development

**Comment by pixelbrackets** [comment] 2016-06-08 13:21
Tested: Version 2.2.1 fixed the bug

**Comment by ad-m** [comment] 2016-06-15 20:37
I have this issue on Gnome 3.

I have tried ```QT_QPA_PLATFORMTHEME=generic /usr/bin/owncloud```. It help, but I don't think is a solution.
Next to I have tried ```sudo apt-get remove owncloud-client-l10n owncloud-client libowncloudsync0 && sudo apt-get install owncloud-client-l10n owncloud-client libowncloudsync0```. It doesn't help.

I use official repository package.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
$ owncloud --version
ownCloud version 2.2.1
Using Qt 5.5.1
$ dpkg -s owncloud-client
Package: owncloud-client
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 2490
Maintainer: Jürgen Weigert <jw@owncloud.com>
Architecture: amd64
Multi-Arch: same
Version: 2.2.1-13.1
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libowncloudsync0 (= 2.2.1-13.1), libqt5core5a (>= 5.5.0), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5keychain1, libqt5network5 (>= 5.0.2), libqt5webkit5 (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libqt5xml5 (>= 5.0.2), libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 5.2), owncloud-client-l10n, libqt4-sql-sqlite | libqt5sql5-sqlite
Conffiles:
 /etc/sysconf.d/100-owncloud-inotify.conf a4b015d9a5dc4ea142b9cee49b4830c9
 /etc/owncloud-client/sync-exclude.lst f390e941b0ac0e001c09667b19678554 obsolete
Description: The ownCloud sync client - github.com/owncloud/client
 .
 ownCloud client enables you to connect to your private
 ownCloud Server. With it you can create folders in your home
 directory, and keep the contents of those folders synced with your
 ownCloud server. Simply copy a file into the directory and the
 ownCloud Client does the rest.
 .
 ownCloud gives your employees anytime, anywhere access to the files
 they need to get the job done, whether through this desktop application,
 our mobile apps, the web interface, or other WebDAV clients. With it,
 your employees can easily view and share documents and information
 critical to the business, in a secure, flexible and controlled
 architecture. You can easily extend ownCloud with plug-ins from the
 community, or that you build yourself to meet the requirements of
 your infrastructure and business.
 .
 ownCloud - Your Cloud, Your Data, Your Way!  www.owncloud.com
 .
 Authors
 =======
 Duncan Mac-Vicar P. <duncan@kde.org>
 Klaas Freitag <freitag@owncloud.com>
 Daniel Molkentin <danimo@owncloud.com>
```

**Comment by oliwel** [comment] 2017-01-12 07:09
Looks like this was re-invented, I got an update this week and now the tray icon is again on the upper left corner, hiding the default window menu

 aptitude show owncloud-client
Paket: owncloud-client                          
Zustand: Installiert
Automatisch installiert: nein
Multi-Arch: same
Version: 2.2.4-9.1
Priorität: optional
Bereich: devel
Verwalter: Jürgen Weigert <jw@owncloud.com>
Architektur: amd64

**Comment by SamuAlfageme** [comment] 2017-01-12 07:47
@oliwel indeed, we've already received reports of this in #5432 and working on fixing the packages. 

Thanks for reporting!

**Comment by gmgrasso70** [comment] 2017-01-12 18:09
Ubuntu 14.04 same issue, with tray icon appearing on the top left corner of desktop. 
Recompiling latest owncloud-client 2.2.4-9.1 from sources against QT4 fixes the systray
position nicely.

**Comment by kkarpieszuk** [comment] 2017-01-20 10:44
@ghost could this be reopened? I came here to report this issue, as I am having it for last ~two weeks (after last client update). I read all comments and I see that you asked to not write "same issue for me" :) But this is closed since June 2016 and now I see there are 4 new reports in last days (including me)

Ubuntu 14.04 LTS

**Comment by BenoitDuffez** [comment] 2017-01-20 13:13
Same here (14.04 / 2.2.4-9.1). Please reopen.

**Comment by jnweiger** [comment] 2017-01-20 14:02
With Qt-5.2.1 there is no fix for this. We can either move forward to Qt-5.6.2 or revert to Qt-4.x

**Comment by BenoitDuffez** [comment] 2017-01-20 14:33
Thanks. Looking forward to this! Thanks guys.

**Comment by jonhrafe** [comment] 2017-01-23 09:36
BUMP. Ubuntu user 14.04 user with the same problem. Waiting for a solution.

**Comment by dadasoph** [comment] 2017-01-24 10:27
Same problem: Icon on left top corner...

owncloud 2.2.4-9.1
Linux 4.4.0-59-generic 
14.04.1-Ubuntu x86_64

Greetings!

**Comment by BenoitDuffez** [comment] 2017-01-24 10:36
Guys, they know the issue, these versions have already been reported, it's planned on the roadmap... No need to add more, I guess. Just subscribe to this issue and wait for the implementation.

**Comment by gnanet** [comment] 2017-01-24 18:29
But a "hello people we are working on it"

**Comment by Ustramator** [comment] 2017-02-07 13:21
I want to inform that, after the latest owncloud-client (2.2.4-10.1) update today, the icon returned to the original right position, after about a month hiding the X button of all maximized windows. 
Owncloud client version 2.2.4-10.1
Ubuntu 14.04 LTS
Thank you very much!

**Comment by jnweiger** [comment] 2017-02-07 14:25
@Ustramator Thanks for the report. So my fix is correct and already public. Good!

**Closed** 2017-02-07 14:28 UTC
Labels: bug, Needs info, packaging, sev2-high
