### ISSUE TITLE
After the upgrade version 1.7.1 Chinese characters not displaying properly

### ISSUE THREAD

**Issue by netcmcc** [owncloud/client#2968] opened 2015-03-17 03:00 UTC
![2015-03-17 10 58 08](https://cloud.githubusercontent.com/assets/11055649/6680609/c14fdef0-cc94-11e4-8a9d-c78aa02bc701.png)

**Comment by dragotin** [comment] 2015-03-17 06:50
Could you please try with our 1.8.0 rc1 that is available here: https://owncloud.org/install/#testing 

IIRC there was a fix for that... Please let us know.

**Comment by osos** [comment] 2015-03-17 13:30
This also applies to the final version 1.8.0 and danish charactors æøå

**Comment by dragotin** [comment] 2015-03-18 10:58
@osos issue was IIRC that the system locale was not utf8 and/or the server delivered the file names in different encoding. @ogoffart can elaborate.

**Comment by ogoffart** [comment] 2015-03-18 11:07
@osos  Your issue is different.  This issue is about rendering issue of some character in the UI.
Probably a font or Qt rendering issue.
Does that still happen with 1.8.0?

**Comment by ogoffart** [comment] 2015-03-18 11:08
Seems to be a duplicate of #2640 which is marked as fixed.

**Closed** 2015-03-23 14:24 UTC
Labels: Needs info
