### ISSUE TITLE
[Windows] Deskop client keeps crashing during every sync since update to 2.5.0

### ISSUE THREAD

**Issue by KittyHawk03** [owncloud/client#6801] opened 2018-10-09 11:24 UTC
Hi,
there is a similar bug report #6787 for MacOS, but this time the Windows version is affected.
Since I updated the destop client to 2.5.0, it keeps crashing at some point of every synchronization.
Usually, a high number a files is synced.
The bug report IDs are
bp-2bafb6d4-61ec-4046-8b69-d3e1a2181007
bp-ebe64648-b560-4445-ad20-c513b2181009

Server configuration
Operating system: Ubuntu 16.04
Web server: Apache 2.4
Database: MySql
PHP version: 7.0

ownCloud version: 10.0.10

Client configuration
Client version: 2.5.0
Operating system: Windows 8.1
OS language: English

**Comment by Dalis18** [comment] 2018-10-09 16:14
I have similar issue. Since upgrading to 2.5.0, everytime I try to creat a new Folder sync, the client crashes. (Latest bug report ID is bp-f984a948-1bb0-4d90-88c8-efa222181009)

Client configuration
Client version: 2.5.0
Operating system: Windows 7
OS language: English

**Comment by kiuru** [comment] 2018-10-10 06:21
I updated the desktop client today and then every folders' and files' icon changed to generic.

![image](https://user-images.githubusercontent.com/3456027/46716649-9221f280-cc6d-11e8-9e7b-174b9a2a24a4.png)

Client configuration
Client version: 2.5.0
Operating system: Windows 10
OS language: English

**Comment by ogoffart** [comment] 2018-10-11 10:35
Thanks for your bug report.

This might or might have not been fixed by https://github.com/owncloud/client/pull/6798

What would be useful would be a way to reproduce it.

Also useful, would be the log at the moment it crashes.  
You can get the log by pressing F12 to get the log window, and there you can check the box to save it (the tooltip tells in which directory the logs are saved)
Then you can provide the last ~20 lines of the log.

**Comment by Dalis18** [comment] 2018-10-11 16:32
OK, thx. I will wait for 2.5.1 update before upgrading. If problem repeats, I will report.

**Comment by guruz** [comment] 2018-10-12 06:28
@KittyHawk03 Can you already install a 2.5.1 daily build which contains the fix and report back if it actually fixes it :-) 
https://download.owncloud.com/desktop/daily/ownCloud-2.5.1.10474-daily20181012-setup.exe

**Comment by KittyHawk03** [comment] 2018-10-13 12:51
I installed the daily build and tried to reproduce the scenario with a forced build. 
2.5.1. does not crash any more. Nevertheless, I don't know if the scenario was representative because I already synced my files with an older version.

**Comment by Dalis18** [comment] 2018-10-15 00:06
Version 2.5.1.10806.10727-daily20181013 works for me. I can a new folder sync and it no longer crashes - thx.

**Comment by guruz** [comment] 2018-10-15 17:31
Great to hear.

**Comment by ogoffart** [comment] 2018-10-16 09:11
Assumed to be fixed then.  Thanks for testing.

**Closed by ogoffart** 2018-10-16 09:11 UTC
Labels: bug
