### ISSUE TITLE
desktop client authentication - webkit pop-up

### ISSUE THREAD

**Issue by pako81** [owncloud/client#3350] opened 2015-06-16 09:13 UTC
Customer is facing an issue with their desktop client and Shibboleth authentication. Specifically, when several programms or folders are opened the webkit pop-up shows up in the background, not being visible to the user.

Can this be changed somehow?

@MorrisJobke thanks

**Comment by dragotin** [comment] 2015-06-16 09:44
@jturcotte had some windows specific findings about that IIRC

**Comment by danimo** [comment] 2015-06-18 11:49
if there is no good generic solution, [`SetForegroundWindow`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633539(v=vs.85).aspx) will do.

**Comment by MTRichards** [comment] 2015-06-19 18:12
Tagging as this is a customer requested issue.

**Comment by danimo** [comment] 2015-07-29 09:40
@jturcotte are you looking into this?

**Comment by jturcotte** [comment] 2015-08-06 15:02
Having the popup appear without user action isn't possible, see https://github.com/owncloud/client/issues/3015 for a similar issue with the share dialog.

But in this case I find it also odd to just pop a dialog to the user if the account couldn't be signed in with known credentials, especially during Windows startup where a lot of stuff is going on. Would it also solve the issue to trigger the same behavior as right clicking on the tray icon and selecting "Sign out", and then show a desktop notification requesting the user to re-sign in?

**Comment by danimo** [comment] 2015-08-10 11:12
@MTRichards please.

**Comment by MTRichards** [comment] 2015-08-10 11:47
The original problem was that the shib login pop up shows up behind every other window, which is not the best experience, so we still have that problem?

The issue of a failed login set of credentials popping up a login window at startup is yet a different issue, though perhaps related. But it still pops up behind the windows on the server, right?

@jturcotte It makes sense to me to run through the logout/login if the credentials are known to be incorrect. For example, a password change in LDAP or AD. We don't want to lock the user out of their account by trying their wrong password three times, so the alternative is to log them out. Do we at least keep the server URL and username so we are just asking for the password? If so, then logout works fine for me.

**Comment by jturcotte** [comment] 2015-09-01 16:53
This was moved to 2.1, it won't be possible to test this until we branch the release, but I've put some testing ideas at https://github.com/owncloud/client/wiki/Testing-Scenarios-2.1

**Comment by jturcotte** [comment] 2015-09-01 18:34
I just tried to change the user password on the server and it pops the login dialog at startup, I need a few more changes.

**Comment by rperezb** [comment] 2015-10-01 11:08
@jturcotte is this possible to be tested? thx

**Comment by jturcotte** [comment] 2015-10-01 11:28
@rperezb I guess not as long as we dont have 2.1 builds :confused:

**Comment by rperezb** [comment] 2015-10-01 11:50
Thanks! Just curious from a QA POV :smile:

**Comment by Dianafg76** [comment] 2015-10-29 10:32
I tested this issue, and with Windows 2008 is working OK

Desktop v ownCloud-2.1.0.5586-nightly20151028-setup.exe

**Comment by Dianafg76** [comment] 2015-11-06 12:18
Is working with normal users
But is not working with SHIB
### Steps to reproduce
1. Install the Desktop v 2.1.0 with 2 differents users (user2, and the other user with SHIB (e.g Alterego))
2. Wait to sync
3. Go to the Server Web with Admin
4. Change the Password for Alterego user
5. Go to the Desktop client
6. Right click on oC icon
7. Click on Setting ... option
8. Go to Alterego user
9. The Alterego user is Closed
![screen shot 2015-11-06 at 13 01 56](https://cloud.githubusercontent.com/assets/12032058/10996712/ceae19bc-8487-11e5-840b-779f170d7802.png)


### Expected behaviour
The Alterego user should not be closed, because the authentication shib passes through a different source password

### Actual behaviour
I see the new (SING IN) button, if I click on this button nothing happens
![screen shot 2015-11-06 at 13 01 56](https://cloud.githubusercontent.com/assets/12032058/10996743/0dbac6be-8488-11e5-8bc1-6e33ca705e83.png)


### Server configuration
Desktop v:
Server v {"installed":true,"maintenance":false,"version":"8.2.1.0","versionstring":"8.2.1 RC1","edition":"Enterprise"}

**Comment by DeepDiver1975** [comment] 2015-11-06 13:46
> Go to the Server Web with Admin
> Change the Password for Alterego user

How is this related to Shibboleth? The password change in ownCloud is unrelated to the password in the IdP. Please elaborate on the scenario - this is confusing - THX

**Comment by rperezb** [comment] 2015-11-06 14:18
@DeepDiver1975 yes, this is an edge case, what it's reported here is how the client works after changing the password on ownCloud what it should not make any difference since you are logged in using shibboleth

**Comment by ogoffart** [comment] 2015-11-06 14:28
If the client logs out, it is probably because the autentication token has expired,  and therefore a new autentication is required.  The password change in ownCloud probably triggers the invalidation of the token.

I don't think this is a problem. And even if it is, it is not a client bug.

**Comment by DeepDiver1975** [comment] 2015-11-06 14:36
> And even if it is, it is not a client bug.

well displaying a button with 0 functionality is a bug - right? :wink:

**Comment by DeepDiver1975** [comment] 2015-11-06 14:37
@ogoffart what is the indicator for the client to detect a log out?

**Comment by ogoffart** [comment] 2015-11-06 14:48
> well displaying a button with 0 functionality is a bug - right? 

ah, i missed that part.  yes it's a bug

**Comment by guruz** [comment] 2015-11-29 15:09
@pako81 Could you make sure to test the popup with 2.1rc1 and then close the issue here?
@Dianafg76 Does the bug you mention still happen?

**Comment by Dianafg76** [comment] 2015-12-01 08:57
@guruz Does the error still happen that you mention? No, now is works OK
Desktop v ownCloud-2.1.0.2924-nightly20151201.pkg , ownCloud-2.1.0.5669-nightly20151201-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by ogoffart** [comment] 2015-12-02 15:40
The login action works well for me, even with shib. 
How can i reproduce the bug?

**Comment by ogoffart** [comment] 2015-12-02 15:41
Ah yes i can reproduce!

**Comment by ogoffart** [comment] 2015-12-02 16:14
I think this is because of the bearer Qt bug.
https://github.com/owncloud/client/issues/4097

It should be fixed in most recent build.

**Comment by dragotin** [comment] 2015-12-02 16:27
@pako81 please verify with the customer.

**Comment by pako81** [comment] 2015-12-02 16:48
@dragotin already done. Waiting for Customer's feedback.

**Comment by pako81** [comment] 2015-12-07 08:54
Customer just replied:

I installed the regular (not branded) version of ownCloud client 2.1.0 in win 10, started it and there's no pop up to authenticate. This should not happen. A pop up to our weblogin should appear. Now I have to manually search in the client for the login option. Please fix that.

**Comment by ogoffart** [comment] 2015-12-07 14:12
That's by design.
The account becomes in the log out state and there is a notification saying one should login.
And one should press the login button to log in and see the popup.

**Comment by pako81** [comment] 2015-12-07 15:00
Again another update from Customer:

I can't offer this client version to our customers. They're used to an automatic pop up to authenticate.
And the first time I'll start the client it won't work to authenticate. I have to click log in/log out several times in the client until the weblogin appears...

**Comment by jturcotte** [comment] 2015-12-07 15:18
He basically can't get both the automatic popup and it appearing in front of other windows all the time. It's because the popup is not triggered by a user action that the OS would not show it on top and the new behavior uses a tray notification instead for that reason and fix his original issue properly.
When they see the popup, they can then either sign in using the new "Sign In" button in the interface, or he can use the right-click context menu of the tray icon to sign in.

A few possible issues:
- The popup should already be automatic in the wizard when you create the account
- The weblogin window should appear by only clicking once on the button, if that's the only issue then this is what should be fixed.
- Are they having this popup every day? The authentication token between their shibboleth provider and the oC server should normally last a long time (a few weeks at least), is this something by design on their server? He's talking like the users need to deal with this popup very often.

**Comment by ogoffart** [comment] 2015-12-21 10:21
As far as we are concerned, the client is behaving as expected.
What exactly should we do here?
Maybe the "sign in" button could be put back in a separate button again to make it more visible?

**Comment by pako81** [comment] 2015-12-21 16:25
Customer replied:

"Our Shibboleth token is lasting for 8 hrs. max or as long as you have the same ip address.
We decided for the clients to authenticate via ldap because Shibboleth in clients/apps is not very user friendly and we're losing many users to commercial services."

I assume we can consider this case as closed.

**Comment by jturcotte** [comment] 2016-01-04 11:22
OK, thanks for the info. According to the fact that we can't have both:
- Show the popup automatically when the auth fails
- Make sure Windows shows our popup on top of other windows

I'd consider this issue as closed. I think that making sure it's on top is more important than it being automatic. If any user sees other issues with the sign in button please open another issue.

**Closed by jturcotte** 2016-01-04 11:22 UTC
Labels: bug, ReadyToTest, resolves-blue-ticket, sev2-high
