### ISSUE TITLE
Cannot restore deleted folders after deleting them with the desktop client.

### ISSUE THREAD

**Issue by tibmanus** [owncloud/client#3063] opened 2015-04-02 10:29 UTC
### Steps to reproduce
1. Delete a folder stored on the local computer, and let it sync with the desktop client.
2. Check "Deleted files" on the web interface.

Not reproducible with WebDAV and with the web interface, only with the client. Deleting single files works fine.
Was able to reproduce on the demo.owncloud.org server.

### Expected behaviour
The deleted folder and/or its content should appear in "Deleted files" section.

### Actual behaviour
The files and the folder are deleted, but they don't appear among the deleted files, thus they cannot be restored.

### Server configuration
**ownCloud version:** 8.0.2

### Client configuration
**Operating system:** Mac, reproducible both with 1.8.0 and 1.7.1.

**Comment by danimo** [comment] 2015-04-02 10:32
> Not reproducible with WebDAV

Can you be more specific? The client only uses WebDAV to delete files from the server, so there should be no difference.

**Comment by tibmanus** [comment] 2015-04-02 10:36
If I connect with my Mac using the provided WebDAV link, and I delete a folder, my Mac starts deleting the files one-by-one, therefore all the files appear in the "Deleted files" section.
If I delete a folder on the web interface, the folder is deleted and the whole folder appears in the "Deleted files" section.

If I delete a folder using the mac client, the folder just disappears forever. It appears in the Activity stream as deleted though.

**Comment by throker** [comment] 2015-04-02 18:53
@tibmanus I had the same question/issue when I first setup OwnCloud for my company a few weeks ago. I expected the same result b/c that is what I have been used to with Dropbox. I tried it with both Mac and PC clients and got the same result.

I did some looking around and didn't really find a concrete answer, but my feeling is that this is intentional. Files deleted on on a client computer *do not* go into the "Deleted Files" section of the OwnCloud web site. I guess this helps keep the space down on the server, besides the user has the Trash or Recycle bin on their computers. However, with shared folders, any deletions that occur on the client computer do in fact go into the "Deleted Files" section of the web site. 

If I am in correct, and this was an intentional design, it would be great if it was documented in the guide. Even better yet, have this as an setup option on the server to keep files deleted from the clients on the server.

**Comment by MTRichards** [comment] 2015-04-03 12:44
Good conversation, and I understand the ask - to consistently treat deleted files the same way. Tagging for tracking purposes.

**Comment by throker** [comment] 2015-04-03 14:57
I should have checked this again before commenting yesterday. It actually works the way we wanted it to. It works this way with OwnCloud Server 8.0.2 and Client 1.8.0 (Mac and PC). 

When I initially tested this I know I was on Server 8.0 and I may have been using the previous client version 1.7.1.

I will add that I am using the Open Suse build service for installation and updates to the server. I'd like to add that I got two updates for 8.0.2. The day it was initially available through apt-get I installed the update, and I think a day later there was another update, both were for version 8.0.2. @tibmanus , do you use the Open Suse Service to get updates? If so, did you experience two updates like me? If not it might be good to check to see if there is another 8.0.2 update.

If necessary, I can supply more information about install.

**Comment by greenvision** [comment] 2015-04-07 11:25
I am experiencing the same issue. Folders deleted on my local system and synchronised with the client just disappear including all their content. Single locally deleted files, however, go into the deleted files section in the webinterface. For me it is always reproducable with the client (not webdav, not webinterface). Using Server 8.0.2 with latest OpenSuse Build updates on Debian 7. Tested with clients 1.7.1 and 1.8.0 on Win8.1. I think it cannot be intended if single files do appear. It makes Owncloud unusable as a backup solution.

**Comment by kaplandani** [comment] 2015-04-09 20:50
Same here, deleting a folder in the client yields an empty folder in the trash bin. 
the find inside the folder cannot be restored.

**Comment by tibmanus** [comment] 2015-04-15 13:32
Every deleted file should be restorable. This is definitely a bug in the sync client.

**Comment by chiessilmb** [comment] 2015-04-20 17:05
I have the same here!  On my ownCloud Sync Client (v. 1.8.0 Build 4893 - Windows) I see info on activity tab that only folder was deleted, not the files into it.

**Comment by osborng** [comment] 2015-05-10 21:52
Having the same issue with version 1.8.1 Build 2335 on both Mac and Windows desktop clients.

**Comment by DeepDiver1975** [comment] 2015-05-11 12:02
this is an issue within core - just reproduced this

**Comment by DeepDiver1975** [comment] 2015-05-11 12:10
core issue: https://github.com/owncloud/core/issues/15009#issuecomment-100888073

**Comment by dragotin** [comment] 2015-05-11 12:12
Thanks @DeepDiver1975 you save the sky with all its own Clouds on it.

Closing here.

**Closed by dragotin** 2015-05-11 12:12 UTC
Labels: Discussion, Server Involved
