### ISSUE TITLE
Client overlay icons in Mac Column View are tiny

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/client#3177] opened 2015-04-29 21:05 UTC
@PVince81 @DeepDiver1975  @MorrisJobke @butonic 

You may already aware of Overlay icons in Mac Finder column view (v1.8.0) are tiny. The icon appears with the same proportions to the large icon view, but that makes the little green circle so small you can barely see it on a retina display. Comparing to Dropbox shows that they are using a much large icon in column view so that the proportions of overlay to regular icon are very different between the different views. 

This is intentional OR something that can be handled by changing the size OR do we have fix for that?

**Comment by MTRichards** [comment] 2015-04-29 21:08
@jancborchardt interested in your take of whether these were intentionally this small.

@iliyasbasir can you provide screen shots?

**Comment by jancborchardt** [comment] 2015-04-29 21:17
This is a duplicate of https://github.com/owncloud/client/issues/2257, let’s continue there.

**Closed by jancborchardt** 2015-04-29 21:17 UTC
