### ISSUE TITLE
[Linux] [2.2.0] text-/iconsize problems

### ISSUE THREAD

**Issue by hefee** [owncloud/client#4840] opened 2016-05-14 08:12 UTC
With v2.2.0 the texsize/iconsize is changed when moving the window from one screen to another. I have a multi screen setup (a laptop screen with a external monitor). This behaviour I only seen with owncloud-client.

My Desktop env is a plasma5/kf5/qt5 debian unstable.

![occ-resize](https://cloud.githubusercontent.com/assets/1238146/15267221/0b0f867e-19bc-11e6-9047-8511b48c8cf4.png)
![occ-resize2](https://cloud.githubusercontent.com/assets/1238146/15267222/0b346e44-19bc-11e6-93e3-a20db68a47c0.png)

**Comment by danimo** [comment] 2016-05-14 20:10
I guess that one screen has a different DPI count than the other? In that case, the problem is that the interface _does not_ change size.

**Comment by hefee** [comment] 2016-05-14 23:27
No OCC is changing its size itself. I can move the window half on the one screen half on the other. And if i come from the "small text" desktop the text is very small also on the other screen. And if I come from the other side the text is big also on the other screen. It only changed if i moved the window completly.

As I told before. OCC is the only application with that behaviour. All other applications have the same textsize on every screen.

**Comment by lckarssen** [comment] 2016-05-17 13:07
I observe something similar (but not identical). After upgrading my (Ubuntu) Linux client to v2.2.0, the buttons and icons 'have grown'. The font size seems OK (like it was before upgrading), but the buttons and icons appear as in @hefee's second screenshot.
Note that this is on a laptop with only a single screen. The screen isn't HiDPI: 1920x1080 in a 14" laptop. Other applications are fine.

**Comment by dennisheitmann** [comment] 2016-05-17 18:45
I can confirm @lckarssen 's observation. It is the same on XFCE 4.12 on xubuntu 16.04. The screen is a HDMI connected 1920x1080 monitor.

**Comment by dennisheitmann** [comment] 2016-05-17 18:47
![image](https://cloud.githubusercontent.com/assets/8471574/15334924/7b5ad01c-1c70-11e6-81f6-f26310f77256.png)

**Comment by guruz** [comment] 2016-05-18 14:07
Which Qt versions do you guys use? This kind of stuff is supposed to be better with 5.6

**Comment by piratenpanda** [comment] 2016-05-18 14:26
5.6.0 here and the same problem on arch

**Comment by lckarssen** [comment] 2016-05-18 15:34
Just upgraded the client from 2.1.1 to 2.2.0 on a different machine (this one runs Ubuntu 15.10 instead of 16.04). Here the size issue is not present. 

On this machine it says Qt v4.8.6. On the other (Ubuntu 16.04) machine I have Qt v5.5.1.

**Comment by maxxer** [comment] 2016-05-18 16:07
> Just upgraded the client from 2.1.1 to 2.2.0 on a different machine (this one
> runs Ubuntu 15.10 instead of 16.04). Here the size issue is not present.

I'm running 15.10 and at first I had no strings at all, now I don't have the Settings dialog anymore #4857

**Comment by guruz** [comment] 2016-05-19 08:21
@jturcotte @danimo  We think this is because of 9ea191f6 54c2c9ac

**Comment by nazar-pc** [comment] 2016-05-19 22:57
Ubuntu 16.10 x64.
qt version 5.5.1 (what comes with Ubuntu)
ownCloud 2.2.0-4.1 package from http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04

I have laptop (its display disabled completely) with 4k monitor. And UI is scaled ridiculously.
Yes, resolution is big, but pixels density is pretty normal (27'').

Here is how it looks comparing to Dropbox window (whose fonts are as they should normally be):

![2016-05-20 01-52-15](https://cloud.githubusercontent.com/assets/928965/15412113/bb9b0e80-1e2d-11e6-80da-ea3a2d55005b.png)

**Comment by PStokman** [comment] 2016-05-26 12:40
I have the same issue. Running the same environment and distro as @hefee (Debian Unstable/Sid). I also have Xfce available (currently running it) and it does the same thing there. Another thing that's happening, is that when I close the settings window on the middle or right monitor (I have 3 monitors, 1 19" 1680x1050, 1 24" FHD and the laptop itself being 14" FHD acting like it's hidpi), it then opens on the laptop monitor as a huge window, starting in the top left corner and spanning all the way to the middle monitor for a bit. I have to resize it back to a normal size in order to actually use it.

When I close it on the laptop monitor and open it again, it appears with normal size on the middle monitor. Closing and opening it again using the tray icon blows it up to extreme proportions on the laptop monitor again. In other words, it doesn't remember the window size and position as it should.

As mentioned here, the text is also absurd on the different monitors. When in hidpi mode, text is big, like 16 or 18, but when on the external monitors it appears to be like size 6, really tiny and almost impossible to read. The buttons appear to stay the same size, no matter how big the fonts are (they are as big as needed to fit the large 'hidpi' font size).
What's strange, is that in Xfce, you can set a custom DPI as a global setting. That's set to 96 in my case. Xfce doesn't really do anything special with the different DPI monitors, it all appears the same. Except the Owncloud Client, that acts as if I have bad eyesight, or really good one, depending on the monitor the window is on.

**Comment by ckamm** [comment] 2016-05-27 11:40
Could you try this test to check whether the theory @guruz mentioned above is correct? https://github.com/owncloud/client/issues/4861#issuecomment-222125106

**Comment by PStokman** [comment] 2016-05-27 12:04
@ckamm, that works for me, fonts stay readable on all monitors and it doesn't 'blow up' like it used to. It does show the interface on the middle monitor all the time, but that's a minor thing and may be caused by my desktop environment, placing the window where the mouse cursor is.

**Comment by ckamm** [comment] 2016-05-27 12:08
@danimo As I understand 9ea191f63de6e008cc0507f5e03881688434bff7 it was about improving behavior with Qt >=5.6. Maybe we can avoid these problems by not setting QT_DEVICE_PIXEL_RATIO for linux and Qt <5.6?

**Comment by hefee** [comment] 2016-05-29 10:03
It also happens for the dolphin integration - but fullily enough here it is to big for all screens. See the textsize of  dolphin in background (top left). This is the textsize i expect:

![occ-resize](https://cloud.githubusercontent.com/assets/1238146/15632523/e468479c-2594-11e6-984a-e99324c3ad4f.png)
Using qt 5.5.1

**Comment by hefee** [comment] 2016-05-29 10:14
@ckamm the workaround works for me too and fixing the issue. Additionally the bug with dolphin integration is solved, too.

(I only use sed on the owncloud binary not for any lib of the dolphin integration).

**Comment by danimo** [comment] 2016-05-29 14:46
@hefee what exacty did you do?

**Comment by hefee** [comment] 2016-05-29 22:06
* Find your "owncloud" binary
*Copy it to owncloud-test
* Run sed -i -e 's/QT_DEVICE_PIXEL_RATIO/DONTSETTHISVARIABLE__/' owncloud-test on it from the command line

like described in https://github.com/owncloud/client/issues/4861#issuecomment-222125106

**Comment by guruz** [comment] 2016-05-30 07:26
But @piratenpanda above mentioned he is on 5.6.0

**Comment by hefee** [comment] 2016-05-30 11:06
The problem for  @piratenpanda is a different issue, cause it uses an other #ifdef clause.

**Comment by guruz** [comment] 2016-05-31 12:59
Can you guys try the latest nightly and report back that it is Ok now?

**Comment by PStokman** [comment] 2016-05-31 13:39
I use the version provided by Debian and they don't do nightly builds of the client. For the time being, I'm using the 'patched' version I made with the sed command noted earlier.

**Comment by nazar-pc** [comment] 2016-06-01 05:14
@guruz, yes, Nightly on Ubuntu 16.10 looks good now.

**Comment by maxxer** [comment] 2016-06-01 07:20
I confirm *owncloud-client_2.2.1-nightly201661-1.1* works fine here as well (15.10)

**Comment by piratenpanda** [comment] 2016-06-07 06:12
still present with 2.2.1, shall i file another bug?

**Comment by paolostivanin** [comment] 2016-06-07 06:52
same here, with Archlinux testing and Gnome 3.20

**Comment by guruz** [comment] 2016-06-07 07:18
@piratenpanda @paolostivanin What's your Qt version reported by the settings dialog in "General"?

**Comment by ckamm** [comment] 2016-06-07 07:28
@piratenpanda @paolostivanin With the recent patches the behavior should be identical to 2.2.0. Are you testing with the 2.2.1 final version? If you do, the Qt version would be interesting (see @guruz comment)

**Comment by piratenpanda** [comment] 2016-06-07 08:34
@ckamm @guruz It's 5.6.0 on latest arch

**Comment by paolostivanin** [comment] 2016-06-07 08:34
Hi @ckamm ,
I am having this weird behavior since version 2.2.0.

```
pacman -Ss qt5|grep installed
extra/qt5-base 5.6.0-7 (qt qt5) [installed]
extra/qt5-declarative 5.6.0-1 (qt qt5) [installed]
extra/qt5-location 5.6.0-1 (qt qt5) [installed]
extra/qt5-sensors 5.6.0-1 (qt qt5) [installed]
extra/qt5-tools 5.6.0-2 (qt qt5) [installed]
extra/qt5-webchannel 5.6.0-1 (qt qt5) [installed]
extra/qt5-webkit 5.6.0-4 (qt qt5) [installed]
extra/qt5-xmlpatterns 5.6.0-1 (qt qt5) [installed]
community/qtkeychain 0.7.0-1 [installed]
```

```
pacman -Ss owncloud|grep installed
community/owncloud-client 2.2.1-1 [installed]
```

**Comment by ckamm** [comment] 2016-06-07 10:13
Okay, the problem here is that the problem with Qt >=5.6.0 was only addressed by @ogoffart's patch  	6ccd9e8, which did not make it into 2.2.1. @danimo fyi.

**Comment by jnweiger** [comment] 2016-06-07 11:55
Linux packages not yet released. Patch added just in time for 2.2.1:
https://github.com/owncloud/administration/commit/8c6da668f9b575c03b9f35d48a39f012db2c560c

**Comment by jnweiger** [comment] 2016-06-07 14:44
Patch is in. Publishing 2.2.1 Linux packages at https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client
This URL is already linked at https://owncloud.org/install/#install-clients
@Kawohl

**Comment by jnweiger** [comment] 2016-06-08 11:53
closing here. Please reopen if there is more...

**Closed by jnweiger** 2016-06-08 11:53 UTC
Labels: bug, ReadyToTest, sev2-high
