### ISSUE TITLE
Schedule sync times - scheduled bandwith

### ISSUE THREAD

**Issue by asuweb** [owncloud/client#4880] opened 2016-05-20 16:26 UTC
A very useful feature (in my opinion) would be the option in the network tab (Windows Client) to extend the bandwidth limit with timeframes, for example.  

Limit bandwidth between 0800 - 1700, and unlimited at other times

**Comment by guruz** [comment] 2016-05-23 07:03
Thanks, duplicate of https://github.com/owncloud/client/issues/1994

**Closed by guruz** 2016-05-23 07:03 UTC
