### ISSUE TITLE
unjustified download of a big file just after being uploaded

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#1425] opened 2014-02-14 15:27 UTC
Hello,

I have created a file (VERY-BIG.3GB) with dd inside the sync folder:

$ dd if=/dev/zero of=VERY-BIG.3GB bs=10M count=300
300+0 records in
300+0 records out
3145728000 bytes (3.1 GB) copied, 49.6872 s, 63.3 MB/s

The sync client started uploading while the file was being modified (looking at the behaviour of the progress bar I think it may have restarted the upload while the file was being created).

Eventually the file was uploaded ok.

But then it was downloaded twice for no reason.

I repeated the test with another file (MEGA-BIG.3GB) and this time it worked fine.

![client-screenshot](https://f.cloud.github.com/assets/621965/2171978/70502374-958c-11e3-9258-b19cc51242e4.png)

Is it possible to tell from this log if this is a race-condition in the client or a hickup with server's etags?

I notice a presence of a temporary file VERY-BIG.3GB.~1c69fb81

Here is the grep of VERY-BIG.3GB from the relevant client logs:

https://gist.github.com/moscicki/9002908

**Comment by MorrisJobke** [comment] 2015-01-05 09:19
@DeepDiver1975 @PVince81 @icewind1991 Is this (https://github.com/owncloud/client/issues/1425#issuecomment-67345476) how it looks if the file is changed on the server, but the folder that conatins the file isn't browsed by the web interface (read as: rescan of the file info from the file system didn't happened yet)?

**Comment by PVince81** [comment] 2015-01-07 11:54
Is there a date difference between the NFS server and the OC server ?
I think if the date returned by NFS doesn't match what OC stored it will be detected as a change.

**Comment by cdamken** [comment] 2015-01-26 11:49
@craigpg @markviens I need a solution here please.

**Comment by MorrisJobke** [comment] 2015-01-26 12:50
Is this still the problem described in the initial post or is this just https://github.com/owncloud/client/issues/1425#issuecomment-67345476 ? It is just this error message, isn't it?

**Comment by MorrisJobke** [comment] 2015-01-26 12:56
Maybe https://github.com/owncloud/client/issues/2116#issuecomment-56162780 fixes it.

**Comment by MorrisJobke** [comment] 2015-01-26 12:59
The linked PR is merged into 6.0.6. @cdamken Which version did they use?

**Comment by cdamken** [comment] 2015-01-27 07:45
@MorrisJobke https://github.com/owncloud/client/issues/1425#issuecomment-71456017 In my case only the comment, but the errors are similar as the initial post.

**Comment by cdamken** [comment] 2015-01-27 10:50
@PVince81 https://github.com/owncloud/client/issues/1425#issuecomment-69012424 Both servers have the same time.

@MorrisJobke https://github.com/owncloud/client/issues/1425#issuecomment-71457001 They use 6.0.5, I already told them to upgrade it at least to 6.0.6

**Comment by MorrisJobke** [comment] 2015-01-27 13:35
Nothing happened here with 6.0.5 and client 1.7.1:

```01-27 14:31:14:711 0x16b8018 csync_walker: file: owncloud://localhost/master/remote.php/webdav/VERY-BIG.3GB [file_id=00000007occfedce0b58 size=3145728000]
01-27 14:31:14:711 0x16b8018 _csync_detect_update: Database entry found, compare: 1422365198 <-> 1422365198, etag: 54c7929e7b964 <-> 54c7929e7b964, inode: 0 <-> 1708330, size: 3145728000 <-> 0, perms:  <-> 
01-27 14:31:14:712 0x16b8018 _csync_detect_update: file: VERY-BIG.3GB, instruction: INSTRUCTION_NONE <<=
```

It did several checks, but in the last 5 minutes there was not a single redownload. I will keep the client open and maybe it good redownloaded.

**Comment by MorrisJobke** [comment] 2015-01-27 13:57
20 minutes later. Nothing happened yet. I will have a look at the logs again.

**Comment by MorrisJobke** [comment] 2015-01-27 14:08
This message shows up repeatedly (3 is error):
```
{"app":"hook","message":"error while running hook (OC\\Preview::post_write): An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `parent`, `path_hash`, `path`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6-13cd79b7b4d3191ffaa9cb66cb3e7681' for key 'fs_storage_path_hash'","level":3,"time":"2014-11-07T16:16:17+09:00"}
```

I don't know that one, but it is just present at the beginning of the log and looks like a filter, that dodn't match anything:
```
{"app":"webdav","message":"Sabre_DAV_Exception_PreconditionFailed: An If-Match header was specified, but none of the specified the ETags matched.","level":4,"time":"2014-11-07T16:26:18+09:00"}
```

Something that is possibly just a notice (4 is warning):
```
{"app":"webdav","message":"Sabre_DAV_Exception_MethodNotAllowed: The resource you tried to create already exists","level":4,"time":"2014-11-11T13:26:28+09:00"}
```

And finally those: (last two ones have the same size but other expectations ... kinda weird, but maybe this is simply luck)
```
{"app":"webdav","message":"Sabre_DAV_Exception_BadRequest: expected filesize 10485760 got 1114112","level":4,"time":"2014-11-20T09:16:01+09:00"}{"app":"webdav","message":"Sabre_DAV_Exception_BadRequest: expected filesize 20971520 got 131072","level":4,"time":"2014-11-28T11:30:30+09:00"}
{"app":"webdav","message":"Sabre_DAV_Exception_BadRequest: expected filesize 8388607 got 131072","level":4,"time":"2014-11-28T11:30:31+09:00"}
```


That are simply too many possible problems in here. Can we have a clean setup that breaks with reproducible steps? @cdamken You said, that you can reproduce with a CentOS box? Is this the Inc. appliance? Where can I grab one with 6.0.5? Did you also notice the problem with 1.7.1?

**Comment by cdamken** [comment] 2015-01-28 08:34
@MorrisJobke 
>You said, that you can reproduce with a CentOS box? Is this the Inc. appliance? Where can I grab one with 6.0.5? Did you also notice the problem with 1.7.1?

I reproduced once, but my NFS was probably not synced on that time.

I try with 6.0.5, 6.0.6, 7.0.3 and 7.0.4  with 1.7.1 and I could not reproduce it anymore :disappointed:

**Comment by MorrisJobke** [comment] 2015-02-02 09:36
@moscicki @EmidioStani Can one of you reproduce this with a current client? Otherwise I tend to close this ticket as nobody can reproduce this.

**Comment by EmidioStani** [comment] 2015-02-02 09:39
Hello,

unfortunately I am not able to reproduce because I work for another
organization. Thanks for looking into it.

Best,

Emidio

On 2 February 2015 at 10:36, Morris Jobke <notifications@github.com> wrote:

> @moscicki <https://github.com/moscicki> @EmidioStani
> <https://github.com/EmidioStani> Can one of you reproduce this with a
> current client? Otherwise I tend to close this ticket as nobody can
> reproduce this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/1425#issuecomment-72428197>.
>



-- 

*Emidio Stani*
PwC | Senior Consultant
Direct: +32 2 7104162 | Mobile: +32 499 599823 | Fax: +32 2 7104069
Email: emidio.stani@be.pwc.com
PwC Enterprise Advisory cvba/scrl

**Comment by dragotin** [comment] 2015-02-17 14:15
Closing this as the problem obviously is solved. Please reopen if not.

**Closed by dragotin** 2015-02-17 14:15 UTC
Labels: blue-ticket, bug, Needs info, Server Involved
