### ISSUE TITLE
Files got deleted when same account is used by multiple client installed on different laptops 

### ISSUE THREAD

**Issue by hoho508** [owncloud/client#3217] opened 2015-05-08 10:23 UTC
Hi Guys , 

I have face this issue and it has cause me to lost a lot of valuable data . 

Steps to reproduce
1. Login UserA on LaptopA using ownCloud Client
2. Login UserA on LaptopB using ownCloud Client
3. Try to sync some files over to ownCloud Server via Client 
4. After a few sync you will get error on FolderA either on LaptopA and LaptopB .
5.Share the files to a UserC,UserD,UserE,UserF,UserG (5users)
6.Rename the FolderA and all your data inside FolderA will be deleted

### Expected behaviour
FolderA will be rename

### Actual behaviour
All Data Is Deleted and could not be retrieve !

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
PHP 5.5.9
**ownCloud version:** (see ownCloud admin page)
8.0.3
**Updated from an older ownCloud or fresh install:**
No
**List of activated apps:**

**The content of config/config.php:**

<?php
$CONFIG = array (

  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'ocsql803',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'loglevel' => 2,

);
<
**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration
Chrome

**Operating system:**

-No Logs Where Generated- 
Except for ownCloud Client

**Comment by ckamm** [comment] 2015-05-08 10:28
@hoho508 This sounds like an important bug, thanks for reporting it.

* Which client version are you using? Is the same version being used everywhere?
* Could you explain "4. After a few sync you will get error on FolderA either on LaptopA and LaptopB" some more? What kind of error do you see? Is there anything special about FolderA?
* What exactly is being shared in 5. and how? FolderA? Via the web interface?

If you can reproduce this, a client log file would be extremely useful. See https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly for how to generate one. Note that it contains, among other things, your server address and file names, which may be sensitive data.

**Comment by hoho508** [comment] 2015-05-08 10:50
1) i`m using ownCloud Windows Client 1.8.1 (5050) everywhere is using the same 
2) FolderA has the size of 50MB and some Child Folders , Other then that nothing special .
3) I will get this error Unknown error on my ownCloud Client 
4) FolderA is been shared by click the link at the right side and added individually , shared users were given full prillivge 

5) I have tried a few times and it will produce the same result . it has cause me to lost alot of data ... im unable to find it from thrash bin too

**Comment by ckamm** [comment] 2015-05-08 12:24
@hoho508 If you can reproduce it, a client log file would be helpful. I can't reproduce it because I don't see that 'Unknown error'.

**Comment by guruz** [comment] 2015-05-08 12:55
@hoho508 Is there anything useful in the owncloud log on the server?

FYI @icewind1991 @PVince81 files lost with regards to shared folder on server.

**Comment by hoho508** [comment] 2015-05-08 13:13
sure I will upload the information for the client error  
Sent from my Xiaomi
On ckamm <notifications@github.com>, 8 May 2015 20:25 wrote:@hoho508 If you can reproduce it, a client log file would be helpful. I can't reproduce it because I don't see that 'Unknown error'.

**Comment by hoho508** [comment] 2015-05-08 17:06
![step 1](https://cloud.githubusercontent.com/assets/10112234/7541351/4ef07ff0-f5e7-11e4-9946-b4d5e325b19a.png)
![step 2](https://cloud.githubusercontent.com/assets/10112234/7541352/4ef22f30-f5e7-11e4-9fbe-0bd89c4c9e4c.png)
9/5/2015 12:41 AMFolderA/SQLManagementStudio_x64_ENU(2008 R2).exe                ownCloud       Uploaded       163 MiB   
9/5/2015 12:41 AMFolderA/SQLEXPR_x64_ENU(2012).exe                               ownCloud       Uploaded       132 MiB   
9/5/2015 12:40 AMFolderA/SQLEXPR_x64_ENU(2008).exe                               ownCloud       Uploaded       83 MiB    
9/5/2015 12:40 AMFolderA/SQLEXPR_x64_ENU (2008 R2).exe                           ownCloud       Uploaded       122 MiB   
9/5/2015 12:39 AMFolderA/SQLManagementStudio_x64_ENU.exe                         ownCloud       Uploaded       163 MiB   
9/5/2015 12:38 AMFolderA/PHP53.exe                                               ownCloud       Uploaded       114 KiB   
9/5/2015 12:38 AMFolderA/SQLEXPR_x64_ENU (2008 R2).exe                           ownCloud       The process cannot access the file because it is being used by another process.122 MiB   
9/5/2015 12:38 AMFolderA/SQLManagementStudio_x64_ENU.exe                         ownCloud       The process cannot access the file because it is being used by another process.163 MiB   
9/5/2015 12:37 AMFolderA/Test/Firefox Setup Stub 37.0.2.exe                      ownCloud       Downloaded     238 KiB   
9/5/2015 12:37 AMFolderA/Test                                                    ownCloud       Downloaded     0 B       
9/5/2015 12:37 AMFolderA                                                         ownCloud       Downloaded     0 B       


![step 3](https://cloud.githubusercontent.com/assets/10112234/7541350/4ef02d7a-f5e7-11e4-8ec5-0cc95636dd51.png)
9/5/2015 12:44:31 AMFolderA/SQLManagementStudio_x64_ENU.exe                         ownCloud       Downloaded     163 MiB   
9/5/2015 12:44:19 AMFolderA/SQLManagementStudio_x64_ENU(2008 R2).exe                ownCloud       Downloaded     163 MiB   
9/5/2015 12:43:40 AMFolderA/SQLEXPR_x64_ENU(2012).exe                               ownCloud       Downloaded     132 MiB   
9/5/2015 12:43:31 AMFolderA/SQLEXPR_x64_ENU (2008 R2).exe                           ownCloud       Downloaded     122 MiB   
9/5/2015 12:42:58 AMFolderA/SQLEXPR_x64_ENU(2008).exe                               ownCloud       Downloaded     83 MiB    
9/5/2015 12:41:46 AMFolderA/PHP53.exe                                               ownCloud       Downloaded     114 KiB   

![step 4](https://cloud.githubusercontent.com/assets/10112234/7541353/4ef29d3a-f5e7-11e4-9cdf-0cc994771540.png)

![step 5](https://cloud.githubusercontent.com/assets/10112234/7541354/4f1fb07c-f5e7-11e4-8cdb-5ab2b9c86a06.png)
9/5/2015 12:52:10 AMFolderA/OC/ownCloud/owncloud-8.0.3.zip                          ownCloud       Uploaded       28 MiB    
9/5/2015 12:51:57 AMFolderA/OC/ownCloud/ownCloud Client/ownCloud-1.8.0.4893-setup.exeownCloud       Uploaded       37 MiB    
9/5/2015 12:51:55 AMFolderA/OC/ownCloud/owncloud-7.0.5.zip                          ownCloud       Uploaded       39 MiB    
9/5/2015 12:51:50 AMFolderA/OC/ownCloud/owncloud-8.0.2.zip                          ownCloud       Uploaded       28 MiB    
9/5/2015 12:51:20 AMFolderA/OC/WINSCP/WinSCP.exe                                    ownCloud       Uploaded       12 MiB    
9/5/2015 12:51:18 AMFolderA/OC/ownCloud/ownCloud Client                             ownCloud       Uploaded       0 B       
9/5/2015 12:51:17 AMFolderA/OC/WINSCP/readme.txt                                    ownCloud       Uploaded       358 B     
9/5/2015 12:51:16 AMFolderA/OC/WINSCP/license.txt                                   ownCloud       Uploaded       36 KiB    
9/5/2015 12:51:14 AMFolderA/OC/MySQL/mysql-workbench-community-6.3.3-winx64.msi     ownCloud       Uploaded       26 MiB    
9/5/2015 12:51:14 AMFolderA/OC/WINSCP/WinSCP.ini                                    ownCloud       Uploaded       13 KiB    
9/5/2015 12:51:11 AMFolderA/OC/WINSCP/WinSCP.com                                    ownCloud       Uploaded       268 KiB   
9/5/2015 12:51:08 AMFolderA/OC/ownCloud                                             ownCloud       Uploaded       4 KiB     
9/5/2015 12:51:08 AMFolderA/OC/WINSCP                                               ownCloud       Uploaded       0 B       
9/5/2015 12:50:33 AMFolderA/OC/MySQL/mysql-installer-community-5.6.24.0.msi         ownCloud       Uploaded       287 MiB   
9/5/2015 12:50:04 AMFolderA/OC/MySQL/mysql-5.6.24-winx64.zip                        ownCloud       Uploaded       349 MiB   
9/5/2015 12:46:51 AMFolderA/OC/vcredist_x86.exe                                     ownCloud       Uploaded       6.3 MiB   
9/5/2015 12:46:42 AMFolderA/OC/npp.6.7.7.Installer.exe                              ownCloud       Uploaded       7.9 MiB   
9/5/2015 12:46:30 AMFolderA/OC/mappedlocal.php                                      ownCloud       Uploaded       9.2 KiB   
9/5/2015 12:46:28 AMFolderA/OC/TeamViewer_Setup.exe                                 ownCloud       Uploaded       8.8 MiB   
9/5/2015 12:46:16 AMFolderA/OC/SEN-WTOS - Dual Monitor Reference Guide - V4- KB 15888.pdfownCloud       Uploaded       1.2 MiB   
9/5/2015 12:46:16 AMFolderA/OC/PHP53.exe                                            ownCloud       Uploaded       114 KiB   
9/5/2015 12:46:15 AMFolderA/OC/MySQL                                                ownCloud       Uploaded       0 B       
9/5/2015 12:46:14 AMFolderA/OC                                                      ownCloud       Uploaded       4 KiB     
9/5/2015 12:44:31 AMFolderA/SQLManagementStudio_x64_ENU.exe                         ownCloud       Downloaded     163 MiB   
9/5/2015 12:44:19 AMFolderA/SQLManagementStudio_x64_ENU(2008 R2).exe                ownCloud       Downloaded     163 MiB   
9/5/2015 12:43:40 AMFolderA/SQLEXPR_x64_ENU(2012).exe                               ownCloud       Downloaded     132 MiB   
9/5/2015 12:43:31 AMFolderA/SQLEXPR_x64_ENU (2008 R2).exe                           ownCloud       Downloaded     122 MiB   
9/5/2015 12:42:58 AMFolderA/SQLEXPR_x64_ENU(2008).exe                               ownCloud       Downloaded     83 MiB    
9/5/2015 12:41:46 AMFolderA/PHP53.exe                                               ownCloud       Downloaded     114 KiB   

![step 6](https://cloud.githubusercontent.com/assets/10112234/7541357/4f2373ec-f5e7-11e4-87d6-90b2b6b746dc.png)
9/5/2015 12:52 AMFolderA/OC/ownCloud/owncloud-8.0.3.zip                          ownCloud       Downloaded     28 MiB    
9/5/2015 12:52 AMFolderA/OC/ownCloud/owncloud-7.0.5.zip                          ownCloud       Downloaded     39 MiB    
9/5/2015 12:52 AMFolderA/OC/ownCloud/owncloud-8.0.2.zip                          ownCloud       Downloaded     28 MiB    
9/5/2015 12:52 AMFolderA/OC/ownCloud/ownCloud Client/ownCloud-1.8.0.4893-setup.exeownCloud       Downloaded     37 MiB    
9/5/2015 12:51 AMFolderA/OC/MySQL/mysql-workbench-community-6.3.3-winx64.msi     ownCloud       Downloaded     26 MiB    
9/5/2015 12:51 AMFolderA/OC/WINSCP/WinSCP.exe                                    ownCloud       Downloaded     12 MiB    
9/5/2015 12:51 AMFolderA/OC/ownCloud/ownCloud Client                             ownCloud       Downloaded     0 B       
9/5/2015 12:51 AMFolderA/OC/ownCloud                                             ownCloud       Downloaded     0 B       
9/5/2015 12:51 AMFolderA/OC/WINSCP/readme.txt                                    ownCloud       Downloaded     358 B     
9/5/2015 12:51 AMFolderA/OC/WINSCP/license.txt                                   ownCloud       Downloaded     36 KiB    
9/5/2015 12:51 AMFolderA/OC/WINSCP/WinSCP.ini                                    ownCloud       Downloaded     13 KiB    
9/5/2015 12:51 AMFolderA/OC/WINSCP/WinSCP.com                                    ownCloud       Downloaded     268 KiB   
9/5/2015 12:51 AMFolderA/OC/WINSCP                                               ownCloud       Downloaded     0 B       
9/5/2015 12:51 AMFolderA/OC/MySQL/mysql-5.6.24-winx64.zip                        ownCloud       Downloaded     349 MiB   
9/5/2015 12:50 AMFolderA/OC/MySQL/mysql-installer-community-5.6.24.0.msi         ownCloud       Downloaded     287 MiB   
9/5/2015 12:47 AMFolderA/OC/vcredist_x86.exe                                     ownCloud       Downloaded     6.3 MiB   
9/5/2015 12:47 AMFolderA/OC/npp.6.7.7.Installer.exe                              ownCloud       Downloaded     7.9 MiB   
9/5/2015 12:46 AMFolderA/OC/SEN-WTOS - Dual Monitor Reference Guide - V4- KB 15888.pdfownCloud       Downloaded     1.2 MiB   
9/5/2015 12:46 AMFolderA/OC/mappedlocal.php                                      ownCloud       Downloaded     9.2 KiB   
9/5/2015 12:46 AMFolderA/OC/TeamViewer_Setup.exe                                 ownCloud       Downloaded     8.8 MiB   
9/5/2015 12:46 AMFolderA/OC/PHP53.exe                                            ownCloud       Downloaded     114 KiB   
9/5/2015 12:46 AMFolderA/OC/MySQL                                                ownCloud       Downloaded     0 B       
9/5/2015 12:46 AMFolderA/OC                                                      ownCloud       Downloaded     0 B       
9/5/2015 12:41 AMFolderA/SQLManagementStudio_x64_ENU(2008 R2).exe                ownCloud       Uploaded       163 MiB   
9/5/2015 12:41 AMFolderA/SQLEXPR_x64_ENU(2012).exe                               ownCloud       Uploaded       132 MiB   
9/5/2015 12:40 AMFolderA/SQLEXPR_x64_ENU(2008).exe                               ownCloud       Uploaded       83 MiB    
9/5/2015 12:40 AMFolderA/SQLEXPR_x64_ENU (2008 R2).exe                           ownCloud       Uploaded       122 MiB   
9/5/2015 12:39 AMFolderA/SQLManagementStudio_x64_ENU.exe                         ownCloud       Uploaded       163 MiB   
9/5/2015 12:38 AMFolderA/PHP53.exe                                               ownCloud       Uploaded       114 KiB   
9/5/2015 12:38 AMFolderA/SQLEXPR_x64_ENU (2008 R2).exe                           ownCloud       The process cannot access the file because it is being used by another process.122 MiB   
9/5/2015 12:38 AMFolderA/SQLManagementStudio_x64_ENU.exe                         ownCloud       The process cannot access the file because it is being used by another process.163 MiB   
9/5/2015 12:37 AMFolderA/Test/Firefox Setup Stub 37.0.2.exe                      ownCloud       Downloaded     238 KiB   
9/5/2015 12:37 AMFolderA/Test                                                    ownCloud       Downloaded     0 B       
9/5/2015 12:37 AMFolderA                                                         ownCloud       Downloaded     0 B       

![step 7](https://cloud.githubusercontent.com/assets/10112234/7541355/4f1fb518-f5e7-11e4-81ff-8e009b1e7c7b.png)
![step 8](https://cloud.githubusercontent.com/assets/10112234/7541356/4f228720-f5e7-11e4-90ff-6513c7f15b99.png)


[{"reqId":"c7de6b9a933dec9dbe5eef21857bb2f4","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: \/var\/www\/owncloud\/data\/ocadmin\/files\/Folder    A at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-05-08T17:03:12+00:00"},{"reqId":"d3edb6cdb43dfd1fecb95ab2abf3db46","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: \/var\/www\/owncloud\/data\/ocadmin\/files\/Folder   A at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-05-08T17:02:55+00:00"},{"reqId":"c42096c81fad6ee104300356c91cb4a9","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: \/var\/www\/owncloud\/data\/ocadmin\/files\/FolderA at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-05-08T16:56:04+00:00"},{"reqId":"48e3e38a496929c94f6bfa509fb71833","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: \/var\/www\/owncloud\/data\/ocadmin\/files\/Q     at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-05-08T16:34:26+00:00"},{"reqId":"c085324dd6d4aa5e145b536de4e6570f","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: \/var\/www\/owncloud\/data\/ocadmin\/files\/test fdsafsad 324234%$^ at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-05-08T16:34:21+00:00"},{"reqId":"4e788d6825e3eda91b8f25b2e419c208","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: \/var\/www\/owncloud\/data\/ocadmin\/files\/Photos at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-05-08T16:34:18+00:00"},{"reqId":"2c424a048476b94344c1b6575eb83fd5","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: \/var\/www\/owncloud\/data\/ocadmin\/files\/Documents at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-05-08T16:34:16+00:00"},{"reqId":"10d65b1dfd67b1cb0e4942f39bc67e9e","remoteAddr":"192.168.1.1","app":"PHP","message":"Undefined index: \/var\/www\/owncloud\/data\/ocadmin\/files\/1# Error at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-05-08T16:33:11+00:00"}]

**Comment by hoho508** [comment] 2015-05-08 17:07
So ... i tried renaming and poof ... everything is gone . Logs shows no error

**Comment by hoho508** [comment] 2015-05-08 17:11
I tried to reproduce but , now i try to rename without owncloud client and it delete all my files ...

**Comment by hoho508** [comment] 2015-05-08 17:17
ok i found out the problem guys . Try renaming [space][space]12 and all the files are gone

**Comment by danimo** [comment] 2015-05-08 17:20
@hoho508 You mean on the web interface?

**Comment by hoho508** [comment] 2015-05-08 17:31
This was the initials test for using single account on 2 laptop running owncloud client . your data will be deleted even if you rename it to another folder name

**Comment by hoho508** [comment] 2015-05-08 17:32
Try doing the same test as given on the pictures to reproduce the error . this error is driving me nuts ... It doesn't show error or anything it just delete all my data in the folder

**Comment by danimo** [comment] 2015-05-08 17:44
The server error looks nastly.

 //cc @DeepDiver1975 @icewind1991 .

**Comment by hoho508** [comment] 2015-05-09 02:14
Yup , it deletes all my data and I have no idea where I can get it back now . single account , on multiple PC /laptops + renaming deletes everything ...

**Comment by moscicki** [comment] 2015-05-09 05:26
Could you wireshark or tcpdump the traffic? What is the PROPFIND response that causes the client to delete all files? Is this a legitimate response (e.g. server reporting no files due to a pure server problem so the client behaviour is correct) or is client also at fault here?

BTW. @danimo, @dragotin : could we add debug output which prints verbatim all HTTP requests and responses (like curl does in the verbose mode)? That would help debugging tremendously without needing to sniff the traffic (which is impossible for https anyway). Best if that could be enabled with a signal at runtime without restarting the client.

**Comment by hoho508** [comment] 2015-05-09 07:07
I can upload a wireshark dump for you guys to do a troubleshoot .... Its really a serious problem for owncloud as data is a priority for owncloud ..

**Comment by hoho508** [comment] 2015-05-09 14:14
Hi guys ,any progress on the bug?  I just look up the bug report and saw this and this problem looks similar not sure about it . 
https://github.com/owncloud/core/issues/13330#issuecomment-100494217

**Comment by hoho508** [comment] 2015-05-09 14:14
https://github.com/owncloud/core/issues/13330#issuecomment-100494217

Sorry

**Comment by moscicki** [comment] 2015-05-09 15:52
This looks like a pure owncloud server bug. On our cernbox it's OK. Here is the test you we use to verify that:  https://github.com/cernbox/smashbox/blob/master/lib/test_concurrentDirMove.py

**Comment by hoho508** [comment] 2015-05-09 16:27
This is bad ... Any solution for this issue ?  . BTW how can I run that python file ? :x

**Comment by hoho508** [comment] 2015-05-09 17:04
@mosciki , did you manage to produce the error ?

**Comment by dragotin** [comment] 2015-05-09 19:53
@PVince81 @DeepDiver1975 please

**Comment by hoho508** [comment] 2015-05-10 07:11
ok ... i think files are randomly .. getting deleted by itself . i tried to make a folders and share to 5users . then tried to sync using owncloud client with only 1 account on 1 owncloud client . however it gives a error 
10/5/2015 3:04:03 PMNS1000                                                          ownCloud       File contains invalid characters that can not be synced cross platform.          

And when i when back to see my files its all gone ... this is really frustrating

**Comment by hoho508** [comment] 2015-05-10 07:45
![image](https://cloud.githubusercontent.com/assets/10112234/7553439/8101934a-f72b-11e4-949d-ba0e754e9444.png)

No Idea why there is files on my webbased - account but Client keeps on saying that sync will delete all my files ..

**Comment by hoho508** [comment] 2015-05-10 14:35
ok guys , i happen to narrow down the problem and come to conclusion for 2 error that will cause data lost . 

1) Making paths too long around 260 characters and after renaming it will cause data lose ( with client in it ) 
2) Using !@#$%^ as folder name and rename it back to normal at ownCloud Client side will cause data lost too .

**Comment by moscicki** [comment] 2015-05-10 17:17
@jnfrmarks : if you can please help @hoho508  to setup the smashbox test. I am currently out of office.

**Comment by hoho508** [comment] 2015-05-11 13:31
Again ... i have got lost files , rename while ownClient Client is syncing .Client Version :  Version 1.8.1 (5050)

**Comment by dragotin** [comment] 2015-05-11 14:52
@PVince81 @DeepDiver1975 please

**Comment by hoho508** [comment] 2015-05-18 07:15
https://github.com/owncloud/core/issues/16389 

Found out the cause of this issue , its is caused by ownCloud web - showing that it has 0bytes of files in the folder causing , it to sync to ownCloud Client Side , as ownCloud Client side has issue on https://github.com/owncloud/core/commit/a97dae9065998e33a0bd47378bd9c7d437584add there for it removes everything from the ownCLoud

**Comment by danimo** [comment] 2015-05-18 07:23
Closing here then.

**Closed by danimo** 2015-05-18 07:23 UTC
Labels: bug, Needs info, Server Involved
