### ISSUE TITLE
If all the files are deleted in the server, keep files is duplicating the contents in the server

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5485] opened 2017-01-23 14:18 UTC
### Actual behavior
The client is prompted with the usual warning dialog regarding all the files were deleted: 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/22206981/98f7e65a-e17d-11e6-8e8b-dee57e42fb8b.png"/>
</p>

If `Keep files` is selected as resolution strategy, the files are restored in the server but they still appear in the `Deleted files` section (piling up every time this is carried out).
![screenshot 2017-01-23 15 05 45](https://cloud.githubusercontent.com/assets/2644445/22206978/9593a7ce-e17d-11e6-81d3-14716aec00c7.png)

### Expected behavior
One of the following options:
1. The server actions are seen as master -> the client should not prompt the warning dialog 
2. `Keep files` in the dialog should be seen as multiple `Restore` operations on the server

### Steps to reproduce
1. Select all the files in the web UI
2. Delete them

**Comment by hodyroff** [comment] 2017-01-24 07:55
Option one under expected is absolutely wrong and a no-go. We implemented this feature for the very reason ...
Restore does IMHO not yet have an API, so what we are currently doing is uploading the files to the server again - therefor they stay in the trashbin. Works as expected.
We expect a user to know what they are doing ... this was build in particullary to protect from storage connection errors which is different then actually really deleting things.
This doesn't sound like a real actual challenge and is not a bug as it works as designed.

**Comment by ogoffart** [comment] 2017-12-05 13:55
I'm closing this issue because I think the client is behaving properly.
The client is not supposed to know what is in the trash.

If anything, the server could find out that the files are duplicated based on the checksum.

**Closed by ogoffart** 2017-12-05 13:55 UTC
Labels: Design & UX, Discussion, Server Involved
