### ISSUE TITLE
Connection issue after wakeup on Ubuntu 16.04

### ISSUE THREAD

**Issue by TKLCZ** [owncloud/client#4908] opened 2016-05-26 19:30 UTC
### Expected behaviour
Automatic resume of synchronization after wakeup

### Actual behaviour
After wakeup from suspend the Owncloud client have not access to Internet so synchronization does not work.

### Steps to reproduce
1. Install owncloud-client 2.2.0 on Ubuntu 16.04
2. Go to sleep (suspend to RAM)
3. Wakeup

### Server configuration
This issue is not related to server

### Client configuration
Client version: 2.2.0

Operating system:
Ubuntu 16.04

OS language:
Czech

**Comment by RealRancor** [comment] 2016-05-26 20:52
@TKLCZ This is a duplicate of https://github.com/owncloud/client/issues/4720

**Closed** 2016-05-27 07:36 UTC
