### ISSUE TITLE
Choose what to sync - no folder names

### ISSUE THREAD

**Issue by togger** [owncloud/client#3053] opened 2015-03-31 09:11 UTC
On Ubuntu 14.04 with the client 1.8. there are no folder names when I click on "choose wht to sync"
![owncloud-sync-1 8](https://cloud.githubusercontent.com/assets/11734497/6915677/65d503fe-d796-11e4-88c2-c2ca3711fe01.png)

**Comment by danimo** [comment] 2015-03-31 09:22
Resize the columns. This is a duplicate of #3031

**Closed by danimo** 2015-03-31 09:22 UTC
