### ISSUE TITLE
2.3.3 Missing context menu text

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#6061] opened 2017-09-26 13:45 UTC
Compiled by my own

### Expected behaviour
See text "share via ..." in context menu

### Actual behaviour
Context menu is there but without text string

![unbenannt-3](https://user-images.githubusercontent.com/9192953/30863601-bb9d65b6-a2d1-11e7-875a-7e548a1ad86d.png)

Any ideas?

**Comment by SamuAlfageme** [comment] 2017-09-26 13:50
@pierrejochem which version of windows are you using? How did you install the client? (i.e. clean installation, update...)

Have you, by any chance, installed the nightly 2.4 version of the client before 2.3.3? It could leave the newer shell integration binaries upon uninstall and cause inconsistency. 

@jturcotte have you ever seen this one?

**Comment by jturcotte** [comment] 2017-09-26 14:06
"Compiled by my own" is going to be the cause if you've been changing some cmake variables and the Theme class.

**Comment by pierrejochem** [comment] 2017-09-26 14:32
Which one could cause this? I'm using a script since Version 1.8.0.0 for the compilation process.

**Comment by pierrejochem** [comment] 2017-09-26 14:34
The strange thing is that only the context menu is affected

**Comment by pierrejochem** [comment] 2017-09-26 14:35
Windows 10 Enterprise by the way

**Comment by jturcotte** [comment] 2017-09-26 14:51
This is where it gets sent to the shell extension: 

https://github.com/owncloud/client/blob/v2.3.3/src/gui/socketapi.cpp#L506

You might also run into issues if the shell extension DLL doesn't match the client version you're using (which is in the `binary` submodule).

**Comment by pierrejochem** [comment] 2017-09-26 14:57
I will check this and also the **appNameGUI()** prop. Maybe that is a hint to the cause

**Comment by pierrejochem** [comment] 2017-09-26 14:59
But there must be a change from Version 2.3.2 to 2.3.3. With 2.3.2 it works without problems

**Comment by jturcotte** [comment] 2017-09-26 15:57
Maybe, but this is not a supported API. If you play with this you are responsible to fix regressions when rebasing to a newer version.

Feel free to pass by #owncloud-client-dev on freenode if you want to ask for help with customization, but this isn't an actual issue unless you can reproduce it with our official builds or source package build instructions.

**Comment by jturcotte** [comment] 2017-09-26 16:01
One thing I know that changed is with 2.4, we now have a sub-menu and request strings a bit differently. So if you've been installing any nightly build, this might conflict with your 2.3 build trying to use the same shell extension binary.

**Comment by michaelstingl** [comment] 2017-09-26 16:28
@haukman showed me the same behaviour today. Maybe he can show @SamuAlfageme whats going on…

**Comment by SamuAlfageme** [comment] 2017-09-27 07:37
@haukman happy to take a look into your setup

**Comment by haukman** [comment] 2017-09-27 09:17
@SamuAlfageme perfect, just ping me in rocket!

**Comment by pierrejochem** [comment] 2017-10-05 15:03
@guruz: Do I understand it correct, that it will be fixed in Version 2.4.0?

**Comment by haukman** [comment] 2017-10-11 07:47
@pierrejochem @SamuAlfageme: Works fine with 2.4alpha for me - I have two accounts configured and can see the context menu again! Thx!

**Comment by pierrejochem** [comment] 2017-10-11 09:20
I have tried it with Version 2.4.0 alpha and I can see the context menu again too

**Comment by michaelstingl** [comment] 2017-10-11 16:57
I also got feedback from a user, that it is fixed in the 2.4.0 alpha1

**Closed by michaelstingl** 2017-10-11 16:57 UTC
Labels: Needs info
