### ISSUE TITLE
No right click on a file menu anymore?

### ISSUE THREAD

**Issue by kingcraftingnl** [owncloud/client#5639] opened 2017-03-21 11:27 UTC
No right click on a file menu anymore?

**Comment by SamuAlfageme** [comment] 2017-03-21 11:54
Hey @kingcraftingnl, can you report back [using the issue template](https://github.com/owncloud/client/blob/master/issue_template.md)? From your comment is kind of hard to grasp what do you mean. 

Thanks!

**Comment by AllanBChristensen** [comment] 2017-03-21 18:55
### Expected behaviour
In Windows, when right-cicking the context menu should appear with an option to "Share with Owncloud"

### Actual behaviour
In version 2.3.0 (build 6780) in WIndows 10, Owncloud is missing from the context menu.

### Steps to reproduce
1. Right-click on a sync'ed item
2. 
3. 

### Server configuration
Operating system: Windows 10

Web server: 

Database:

PHP version:

ownCloud version: Windows client 

Storage backend (external storage):

### Client configuration
Client version: 2.3.0

Operating system: Windows 10

OS language: Danish

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:C:\Program Files (x86)\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by AllanBChristensen** [comment] 2017-03-21 19:21
The issue seems to be resolved with Windows Client 2.3.1.

**Comment by hodyroff** [comment] 2017-03-22 06:08
Perfect, Closing.

**Closed by hodyroff** 2017-03-22 06:08 UTC
Labels: Needs info
