### ISSUE TITLE
[QA] Next button not enabled after pasting the password

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10321] opened 2022-11-25 13:47 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with ownCloud 3.0.0.9173-daily20221125

When connecting a new account the new wizard UI is used to query username and password.
While either username or password is blank, the Next button is grayed out. OK
I use a password manager, that provides my password into the paste buffer.
After pasting the password, the Next button remains disabled. BAD.

![grafik](https://user-images.githubusercontent.com/1108546/203998579-a92836b9-273e-46e5-ae53-1eb141c4f37d.png)

Workaround:
Type a space, and a backspace, then the button becomes enabled.

![grafik](https://user-images.githubusercontent.com/1108546/203998706-a43414d0-7e54-4f04-a188-e36adf84aa07.png)

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

Pasting should also enable the button.

### Actual behavior

It isn't.

**Comment by fmoc** [comment] 2022-12-01 14:29
Cannot reproduce on Ubuntu 22.04. More information required.

**Comment by fmoc** [comment] 2022-12-16 15:42
Can't be reproduced with 3.0 release and the current 3.1 daily build on Windows 10 either. I consider this a temporary issue. Closing as "cannot reproduce". Please don't hesitate to reopen if it happens again.

**Comment by jnweiger** [comment] 2022-12-17 01:19
100% reproducable with client 3.0.0.9215- on ubuntu 22.04

* start the client, 
* connect to server demo.owncloud.org
* type demo into the username field. 
* highlight the for letters of demo with the mouse, 
* right click on the highlghted text, select 'Copy'
* click into the password filed, 
* right click the empty password field, select 'Paste'
* four **** appear, but the 'Next' button remains grayed out.

**Comment by fmoc** [comment] 2022-12-19 15:23
How did you install the client?

**Comment by fmoc** [comment] 2022-12-19 15:47
These steps helped reproduce the issue on both Ubuntu 22.04.1 (live DVD) as well as xubuntu 22.04.1 (regular installation). `Ctrl+V` works absolutely fine. I would _never_ have thought of the context menu.

**Closed** 2023-01-04 13:40 UTC
Labels: Enhancement, Needs info, p3-medium, QA:team

**Comment by HanaGemela** [comment] 2023-01-16 11:42
Fixed in ownCloud 3.1.0.9784-daily20230115 mac
