### ISSUE TITLE
[1.8.0] Link to shared files is broken when entering passwords

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#2804] opened 2015-02-09 17:59 UTC
### Expected behavior
The link works fine

### Actual behavior
The link doesn't work 
Error: 
Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404

### Steps to reproduce
1. Click "Share with ownCloud" 
2. Click "Share link" 
3. Set password
4. URL is borked `http://localhost/core/public.php%3Fservice=files&t=0cY6l7bjV73SSUO`

### Client configuration
version1.8.0
**Operating system:**
OS X 10.10

**Comment by LukasReschke** [comment] 2015-02-09 17:59
The %3F shouldn't be there

**Comment by rullzer** [comment] 2015-02-09 19:01
@LukasReschke on which platform are you getting this? I can't reproduce it.

**Comment by rullzer** [comment] 2015-02-09 19:03
@LukasReschke also which version of Qt?

**Comment by LukasReschke** [comment] 2015-02-09 19:09
OS X 10.10, Qt 5.4.0, build 1987

**Comment by rullzer** [comment] 2015-02-10 11:35
Mmmm still can't repoduce... Maybe it is a mac issue

**Comment by lmaestro** [comment] 2015-02-10 12:03
I can reproduce it on OS X 10.10.1 version1.8.0- build (2001)
@guruz Can you try to reproduce it?

**Comment by dragotin** [comment] 2015-02-10 16:16
Fixed by above commit, test case is still todo.

**Comment by lmaestro** [comment] 2015-02-11 08:32
Fixed in version 1.8.0-nightly20150211 (build 2006)

**Closed by lmaestro** 2015-02-11 08:32 UTC
Labels: bug, gold-ticket, ReadyToTest
