### ISSUE TITLE
File can not be shared because it was saved without sharing permission 

### ISSUE THREAD

**Issue by AllanBChristensen** [owncloud/client#4694] opened 2016-04-17 09:46 UTC
### Expected behaviour
After saving an Excel sheet to a sync'ed directory on Windows, I should be able to right-click on the file, select "Share with owncloud" and get a link. 
### Actual behaviour
Instead, the link-window displays the message "File can not be shared because it was saved without sharing permission"

### Steps to reproduce
1. Save file through Windows interface
2. Right-click on file and select "Share with Owncloud"

If I go to OwnCloud using a browser, there is no problem getting the link, only in the Windows client.

NB: It doesn't happen always, and I am unable to tell any difference as to when it does and does not.

### Server configuration
OwnCube hosting
Web server: 
OwnCube hosting
Database:
OwnCube hosting
PHP version:
N/A - Windows client
ownCloud version:
9.0.0 
Storage backend:
?
### Client configuration
Client version:
Version 2.1.1 (build 5837)
Operating system:
Windows 10
OS language:
DANISH
Installation path of client:
C:\Program Files (x86)\ownCloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )
The Log Output window in the client is empty

2. Web server error log:
N/A
3. ownCloud log (data/owncloud.log):
N/A
![no sharing](https://cloud.githubusercontent.com/assets/18511650/14586217/7dfc729a-0491-11e6-8d0c-0c4e1332ee06.JPG)

**Comment by guruz** [comment] 2016-04-19 12:52
Could you try 9.0.1 too?

**Comment by rullzer** [comment] 2016-04-19 13:45
That error is from the server so it really seems that the server is now allowing you to edit. Since you are running 9.0 it is weird that the server does allow you to do this since the web UI is using the same API.

* Is the error persistent if you wait for the sync to complete?
* Is the sync actually to a shared folder?

**Comment by AllanBChristensen** [comment] 2016-04-19 13:55
Hi Roeland

I don't understand much from your comments, but like I said, the web 
interface allows me to fetch the link like it should. The problem is 
only in the Windows client.

And now, several days later, I am also able to get the link through 
Windows Explorer/client:


BR
Allan

On 19-04-2016 15:46, Roeland Douma wrote:
>
> That error is from the server so it really seems that the server is 
> now allowing you to edit. Since you are running 9.0 it is weird that 
> the server does allow you to do this since the web UI is using the 
> same API.
>
>   * Is the error persistent if you wait for the sync to complete?
>   * Is the sync actually to a shared folder?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/client/issues/4694#issuecomment-211928988>
>

-- 
*Allan B. Christensen*
Gantrupvej 14A
DK-8752 Østbirk
Tel.: +45 41 20 43 42
Email: allan@dansksquash.dk

**Comment by AllanBChristensen** [comment] 2016-04-19 13:57
PS: To be precise, I can now get the link for the same example document 
where the error occured. I don't know if the same error may again occur 
with at different document.

/Allan

On 19-04-2016 15:46, Roeland Douma wrote:
>
> That error is from the server so it really seems that the server is 
> now allowing you to edit. Since you are running 9.0 it is weird that 
> the server does allow you to do this since the web UI is using the 
> same API.
>
>   * Is the error persistent if you wait for the sync to complete?
>   * Is the sync actually to a shared folder?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/client/issues/4694#issuecomment-211928988>
>

-- 
*Allan B. Christensen*
Gantrupvej 14A
DK-8752 Østbirk
Tel.: +45 41 20 43 42
Email: allan@dansksquash.dk

**Comment by rullzer** [comment] 2016-04-19 14:04
@AllanBChristensen yeah that is what I found weird since they do the same calls.

But good that it is solved now. Let me close this then. Please reopen if you can reproduce with other files.

**Closed by rullzer** 2016-04-19 14:04 UTC
Labels: bug, Needs info, sev2-high

**Comment by AllanBChristensen** [comment] 2016-04-19 14:07
I did not say at all that it was solved. I just presented you with a 
fact about the behavior of the problem - and then you jump to 
conclusions. I can understand why you do that - but the issue might 
still be there!

On 19-04-2016 16:04, Roeland Douma wrote:
>
> Closed #4694 <https://github.com/owncloud/client/issues/4694>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/client/issues/4694#event-632981197>
>

-- 
*Allan B. Christensen*
Gantrupvej 14A
DK-8752 Østbirk
Tel.: +45 41 20 43 42
Email: allan@dansksquash.dk

**Comment by rullzer** [comment] 2016-04-19 14:11
As said. Please reopen if you can reproduce it again :)

**Comment by AllanBChristensen** [comment] 2016-04-19 14:18
OK, will do

On 19-04-2016 16:11, Roeland Douma wrote:
>
> As said. Please reopen if you can reproduce it again :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/client/issues/4694#issuecomment-211937769>
>

-- 
*Allan B. Christensen*
Gantrupvej 14A
DK-8752 Østbirk
Tel.: +45 41 20 43 42
Email: allan@dansksquash.dk
