### ISSUE TITLE
Edit Folder button needed

### ISSUE THREAD

**Issue by nexuswest** [owncloud/client#2603] opened 2014-12-10 03:52 UTC
Need an edit button on the sync folders list (Account tab) in the UI. At present, I have to delete and then add all over again for simple changes like renaming a source or destination directory.

**Comment by ogoffart** [comment] 2018-11-29 15:00
Duplicate of https://github.com/owncloud/client/issues/298

**Closed by ogoffart** 2018-11-29 15:00 UTC
Labels: Design & UX
