### ISSUE TITLE
OC client doesn't reconnect to network automatically

### ISSUE THREAD

**Issue by aproposnix** [owncloud/client#4869] opened 2016-05-20 05:31 UTC
### Expected behaviour
If the network drops, OC client should be able to reconnect once the network is back up. 

### Actual behaviour
If the network drops (on Wifi for example) the client never reconnects.  I have to close the client and reopen it for it to connect again. 

### Steps to reproduce
1. Disconnect wifi (esp., turn off the router) 
2. Wait for owncloud to disconnect automatically
3. reconnect wifi 
4. OC doesn't reconnect

### Client configuration
Client version: 2.2

Operating system: Ubuntu 16.04

OS language: English
Installation path of client: No idea, installed from deb using the suse build service.

**Comment by guruz** [comment] 2016-05-20 07:38
Duplicate of https://github.com/owncloud/client/issues/4720 (and the linked issues from there)

Ubuntu needs to add patches to their Qt5 / qtbase package, not much we can do currently.

**Closed by guruz** 2016-05-20 07:38 UTC

**Comment by guruz** [comment] 2016-05-20 07:40
(Also https://github.com/owncloud/client/issues/4839 )
