### ISSUE TITLE
mirral "ignore file" option deleted all the ignored files from my server

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/client#3172] opened 2015-04-28 15:58 UTC
Well, i have two computers, the first one i use in  daily basis, syncing files. The laptop i use on weekends, so every time it starts there are several files to sync from the server.
This time i was on a trip, using a WAN link, so i decided add "*.mp4" to the ignore list, so basically i would only sync some small PDFs to the laptop and when i get home i could sync the big mp4 files. The problem is that mirral DELETED all the MP4 files from the server !! Why ?? Is this the expected behaviour ? If it is, is this really safe for the end user ?

**Comment by danimo** [comment] 2015-04-28 18:23
Which version? Which OS? Please use https://raw.githubusercontent.com/owncloud/client/master/issue_template.md.

**Comment by jsalatiel** [comment] 2015-04-28 18:39
Sorry, my mistake !

### Expected behaviour
Tell us what should happen
If i choose to ignore some files, for example '*.mp4' inside the client config, it SHOULD NOT touch any local files or remote files that matches the regex.

### Actual behaviour
Tell us what happens instead
After add *.mp4 in the ignore list, all mp4 files on the client WERE deleted from the server !!! I noticed what  was happening and stopped the client before it finishes, so i dont know if it would also delete from the local filesystem, but it deleted 29GB of data from my server! (MP4 files)

### Steps to reproduce
1. Upload some mp4 files using the webinterface while keeping the desktop client offline
2. while still offline , edit ignore list and add "*.mp4"
3. connect the client to the internet, the client will start syncing process, DELETING all REMOTE mp4 previously synced from the servers

### Server configuration
Operating system: Ubuntu 14

Web server: apache 2.4

Database: mysql

PHP version: 5.5.9-1ubuntu4.9

ownCloud version: 8.0.2-8

Storage backend: disk

### Client configuration
Client version: 1.8.0-2

Operating system: Linux Mint 17.1 rebecca

OS language: English

Installation path of client: /usr/bin/owncloud

**Comment by nalt** [comment] 2015-05-18 03:00
The same happened to me. I guess the server kept a backup, but still, this is a SEVERE bug.

**Comment by jsalatiel** [comment] 2015-06-17 21:40
any news on this ?
What does the gold-ticket label mean ?

**Comment by dragotin** [comment] 2015-06-18 16:11
@jsalatiel gold ticket means that the release wont go out if this is not fixed. It's release blocking. Sorry for not seeing the severity here for so long.

**Comment by ckamm** [comment] 2015-06-19 07:45
So far I could not reproduce the problem. Adding an ignore pattern didn't delete files that were already synced for me. It also didn't change what happened if a file matching the pattern was new on the server. I'll experiment with it some more. Do you have any additional information @jsalatiel?

**Comment by jsalatiel** [comment] 2015-06-19 08:03
I will try to replicate it.

**Comment by dragotin** [comment] 2015-06-19 08:16
@jsalatiel make sure to switch on logging please.

**Comment by ckamm** [comment] 2015-06-19 08:18
@jsalatiel Did you enable the checkmark for the ignore pattern? Did the folders that had mp4 files that were deleted contain any other files?

**Comment by jsalatiel** [comment] 2015-06-19 08:22
@ckamm Yes, i selected the ignore pattern, and yes , the folder had other files.

Actually the structure was basically:
├── AULA.01
│   ├── curso1.pdf
│   ├── curso1-vid1.mp4
│   ├── curso1-vid2.mp4
│   └── curso1-vid3.mp4
├── AULA.03
│   └── curso3-vid1.mp4
├── AULA.05
│   ├── curso5.pdf
│   ├── curso5-vid1.mp4

When i get home i will try to replicate

**Comment by ckamm** [comment] 2015-06-19 08:25
@jsalatiel @dragotin I think I can replicate it.

* have foo/test.ignore synced to the client (root folder doesn't work)
* add *.ignore to the ignore pattern and enable the checkbox for delete-if-necessary-for-folder-removal
* on the next sync run foo/test.ignore will be deleted from the server - it stays on the local filesystem

**Comment by jsalatiel** [comment] 2015-06-19 08:29
Exactly! Just replicated here too.

**Comment by ckamm** [comment] 2015-06-19 08:31
The problem seems to be that files marked as CSYNC_FILE_EXCLUDE_AND_REMOVE are not even added to the tree during the update phase. So reconcile thinks the file was deleted locally and decides to propagate this action to the server.

**Comment by ckamm** [comment] 2015-06-19 08:37
@ogoffart The intention with CSYNC_FILE_EXCLUDE_AND_REMOVE was to allow removal of the *local* files if they'd otherwise prohibit the directory from being deleted, correct?

**Comment by ckamm** [comment] 2015-06-19 08:39
@jsalatiel You should be able to work around this issue by not enabling the checkmark on the ignore pattern. We'll fix the problem and the ui.

**Comment by jsalatiel** [comment] 2015-06-19 10:43
Hi guys, IMHO the ignore files editor really needs a change. I always thought that the checkbox was to enable the pattern. So if i wanted to temporarily disable that pattern i could just disable the checkbox.
For me, if i choose ignore, any file matching the pattern should not be touched, both local and remote.

**Comment by jsalatiel** [comment] 2015-06-19 10:44
@ckamm  thanks for the help! I also filled one "non-critical" bug that i found while trying to replicate this behaviour!

**Comment by ckamm** [comment] 2015-06-19 13:04
The behavior fix is in 1.8, the ui change needs some more work and will go into master.

**Comment by Dianafg76** [comment] 2015-07-02 11:54
@ckamm I can't reproduce the issue. In my tested is not deleted all the .MP4

**Closed** 2015-07-02 12:00 UTC
Labels: bug, gold-ticket, ReadyToTest, sev1-critical
