### ISSUE TITLE
GoogleDrive sync fails due to unsyncable "My Saved Places." file with files returning -2 as getcontentlength from ownCloud

### ISSUE THREAD

**Issue by atroxix** [owncloud/client#4573] opened 2016-03-16 07:40 UTC
### Expected behaviour
When some objects from GoogleDrive cannot be synced then the sync process should just ignore them, not abort.

### Actual behaviour
Only some files/folders are synced. The failure happens with files located at the root folder of GoogleDrive, so I cannot even sync one certain folder because the error occurs before sync gets there.

Interesting is that when client gives error about unsyncable things (Google Maps files, and conflicting names of folders and files) then it says it downloaded that one certain folder which I'm interested in, but I don't see it in my local disk.

### Steps to reproduce
1. Add GoogleDrive external storage.
2. Configure GoogleDrive folder in client. You can also specify certain sub-folder only, it doesn't actually matter.

### Server configuration
Operating system: FreeBSD

Web server: Apache 2.4

Database: MariaDB 10.0

PHP version: 5.6

ownCloud version: 9.0

Storage backend: normal directory

### Client configuration
Client version: 2.1.1

Operating system: OpenSUSE 42.1

OS language: English

Installation path of client: /usr/bin/owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

**Output of `owncloud --logfile -`**

About a failing file in root:

```
3-16 09:28:47:694 9561 OCC::Folder::slotSyncStarted: #### Propagation start #################################################### >>
03-16 09:28:47:694 9561 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "http://oc.kodu/remote.php/webdav/GoogleDrive" :  "Sync Running"
03-16 09:28:47:694 9561 OCC::PropagateDownloadFileQNAM::start: virtual void OCC::PropagateDownloadFileQNAM::start() "My Saved Places." 0
03-16 09:28:47:696 9561 OCC::SyncJournalDb::setDownloadInfo: "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "My Saved Places." ".My Saved Places..~1d5541ff" "56e8fb1dac33f" 0
03-16 09:28:47:697 9561 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
03-16 09:28:47:700 9561 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
03-16 09:28:47:700 9561 OCC::GETFileJob::start: virtual void OCC::GETFileJob::start() OCC::BandwidthManager(0x3893b38) false false
03-16 09:28:47:700 9561 OCC::AbstractNetworkJob::start: !!! OCC::GETFileJob created for "http://oc.kodu/" + "/GoogleDrive/My Saved Places." ""
...
03-16 09:28:50:766 9561 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(ServiceUnavailableError) "Error downloading http://oc.kodu/remote.php/webdav/GoogleDrive/My Saved Places. - server replied: Service Unavailable" QVariant(int, 503)
03-16 09:28:50:767 9561 OCC::PropagateDownloadFileQNAM::slotGetFinished: void OCC::PropagateDownloadFileQNAM::slotGetFinished() QUrl("http://oc.kodu/remote.php/webdav/GoogleDrive/My Saved Places.") FINISHED WITH STATUS QNetworkReply::NetworkError(ServiceUnavailableError) "Error downloading http://oc.kodu/remote.php/webdav/GoogleDrive/My Saved Places. - server replied: Service Unavailable" 0 0 18446744073709551614 0 "" "221"
03-16 09:28:50:769 9561 OCC::SyncJournalDb::setDownloadInfo: "DELETE FROM downloadinfo WHERE path=?1" "My Saved Places."
03-16 09:28:50:769 9561 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "My Saved Places." INSTRUCTION_NEW 1 "Error downloading http://oc.kodu/remote.php/webdav/GoogleDrive/My Saved Places. - server replied: Service Unavailable"
03-16 09:28:50:772 9561 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/home/silver/Downloads/GoogleDrive/.My Saved Places..~1d5541ff"
03-16 09:28:50:772 9561 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(OperationCanceledError) "Operation canceled" QVariant(Invalid)
```

About the folder of interest to me (and the only thing selected from the client):

```
03-16 09:29:30:012 0x38a5780 csync_walker: directory: owncloud://oc.kodu/remote.php/webdav/GoogleDrive/Siit [file_id=00259198occ40e4dc891]
03-16 09:29:30:012 0x38a5780 _csync_detect_update: file: Siit, instruction: INSTRUCTION_NEW <<=
03-16 09:29:30:012 0x38a5780 csync_ftw: URI without fuzz for owncloud://oc.kodu/remote.php/webdav/GoogleDrive/Siit is "Siit"
03-16 09:29:30:012 9603 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x255b640) Siit Calling into main thread...
03-16 09:29:30:012 9561 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "http://oc.kodu/" + "/GoogleDrive/Siit" "OCC::DiscoverySingleDirectoryJob"
03-16 09:29:30:013 9561 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
03-16 09:29:32:234 9561 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList<OCC::FileStatPointer>&) Have 8 results for  "/GoogleDrive/Siit"
03-16 09:29:32:234 9603 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x255b640) Siit ...Returned from main thread
```

**Web server error log:**

(Nothing)

**ownCloud log (data/owncloud.log):**

Not sure it's relevant:

```
{"reqId":"6gmdY3MAdenMMr4mhEWs","remoteAddr":"10.0.254.102","app":"PHP","message":"fread() expects parameter 1 to be resource, boolean given at \/srv\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php#812","level":3,"time":"2016-03-16T07:29:52+00:00"}
{"reqId":"6gmdY3MAdenMMr4mhEWs","remoteAddr":"10.0.254.102","app":"PHP","message":"fclose() expects parameter 1 to be resource, boolean given at \/srv\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php#813","level":3,"time":"2016-03-16T07:29:52+00:00"}
{"reqId":"6gmdY3MAdenMMr4mhEWs","remoteAddr":"10.0.254.102","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/srv\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/srv\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/srv\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/srv\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/srv\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/srv\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":306,\"User\":\"silver\"}","level":4,"time":"2016-03-16T07:29:52+00:00"}
```

**Comment by guruz** [comment] 2016-03-16 11:39
A directory returning 503 would have been ignored, but files not.
Can you open this in the core bugtracker? They should take care if there is something which really breaks usage of GoogleDrive.

Workaround: Put unsyncable filenames in the ignore/exclude file.

**Comment by atroxix** [comment] 2016-03-16 13:33
I added "My Saved Places" to exclude list, but it's still processed and reported.

**Comment by atroxix** [comment] 2016-03-17 07:54
How about this exclude list not taking effect in this case? I believe this is still purely a client issue?

**Comment by guruz** [comment] 2016-03-17 09:10
Do you have a log snippet for this? :)

FYI @ogoffart

**Comment by atroxix** [comment] 2016-03-17 09:14
Yes I do, but wouldn't like to post it publicly :)
Where do I send it?

**Comment by guruz** [comment] 2016-03-17 15:08
try My username here @owncloud.com :)
How do those lines in the exclude look like?

**Comment by atroxix** [comment] 2016-03-17 17:20
Sent logfile.

$ cat ~/.local/share/data/ownCloud/sync-exclude.lst
```
.*.wrk
My Saved Places
```

**Comment by guruz** [comment] 2016-03-21 14:14
Note that the file name is ```My Saved Places.``` with a dot at the end. :)

Could you give us the curl PROPFIND output of that filename so we see what ownCloud server returns as info for it?
https://stackoverflow.com/questions/26429904/list-files-folders-in-owncloud-with-php-curl/26676902#26676902

@LukasReschke @PVince81 Maybe google.php should ignore this weird ```My Saved Places.``` file?

**Comment by guruz** [comment] 2016-03-21 14:18
>  (Google Maps files, and conflicting names of folders and files) 

Can't say anything to the latter one, you might need to rename them on drive.google.com

**Comment by atroxix** [comment] 2016-03-22 06:47
> Note that the file name is My Saved Places. with a dot at the end.

If I look at my GoogleDrive then there is no dot at the end.

**Comment by atroxix** [comment] 2016-03-22 06:51
> Could you give us the curl PROPFIND output of that filename so we see what ownCloud server returns as info for it?

```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
 <d:response>
  <d:href>/remote.php/webdav/GoogleDrive/My%20Saved%20Places.</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Tue, 11 Nov 2014 15:21:19 GMT</d:getlastmodified>
    <d:getcontentlength>-2</d:getcontentlength>
    <d:resourcetype/>
    <d:getetag>&quot;56e8fb1dac33f&quot;</d:getetag>
    <d:getcontenttype>application/octet-stream</d:getcontenttype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

**Comment by atroxix** [comment] 2016-03-22 06:54
> > (Google Maps files, and conflicting names of folders and files)

> Can't say anything to the latter one, you might need to rename them on drive.google.com

In core/#23284 it was mentioned that OwnCloud should actually ignore files with the same names.

**Comment by guruz** [comment] 2016-03-22 09:01
> If I look at my GoogleDrive then there is no dot at the end, but in OwnCloud interface there is indeed.

I have that from your logfile. Does it work to exclude/ignore with dot? :)

```<d:getcontentlength>-2</d:getcontentlength>```

@icewind1991 @LukasReschke @PVince81 Is that a magic number? Should the client just ignore negative content lengths?

**Comment by guruz** [comment] 2016-03-22 09:03
@atroxix Do the other problematic files also return such a content length in PROPFIND?

**Comment by atroxix** [comment] 2016-03-22 09:06
> I have that from your logfile. Does it work to exclude/ignore with dot? :)

Yes, I'm just excluding problematic files one-by-one to get the share finally syncing with OwnCloud client. But it's a bit painful process as every change results in my other share being completely re-scanned again. Maybe I should remove it temporarily...

> Do the other problematic files also return such a content length in PROPFIND?

One more example of another problematic file:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
 <d:response>
  <d:href>/remote.php/webdav/GoogleDrive/kivi%20vs%20moodul200115.xls.ods</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Thu, 22 Jan 2015 18:57:01 GMT</d:getlastmodified>
    <d:getcontentlength>-2</d:getcontentlength>
    <d:resourcetype/>
    <d:getetag>&quot;56e8fb1da7a96&quot;</d:getetag>
    <d:getcontenttype>application/x-vnd.oasis.opendocument.spreadsheet</d:getcontenttype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

**Comment by atroxix** [comment] 2016-03-22 09:26
Also, there's one file that also has this contentlength -2, but it's listed in OwnCloud UI, it can be downloaded from there, it doesn't cause error on syncing it with OwnCloud client, but it just isn't downloaded either.

**Comment by PVince81** [comment] 2016-03-22 09:39
I tried creating a file "My Saves Places" directly on GDrive (without dot) and doing a PROPFIND with some properties gives me this:
```
  <d:href>/owncloud/remote.php/files/gdrive/My%20Saved%20Places.</d:href>
  <d:propstat>
   <d:prop>
    <oc:id>00000013ockbfur1449k</oc:id>
    <oc:fileid>13</oc:fileid>
    <oc:permissions>MDNVW</oc:permissions>
    <d:getlastmodified>Tue, 22 Mar 2016 09:38:13 GMT</d:getlastmodified>
    <d:getetag>&quot;56f1127a9055b&quot;</d:getetag>
    <d:getcontentlength>15</d:getcontentlength>
    <oc:downloadURL></oc:downloadURL>
    <oc:owner-id>admin</oc:owner-id>
    <oc:owner-display-name>admin</oc:owner-display-name>
    <oc:favorite></oc:favorite>
    <oc:tags/>
   </d:prop>
```

Maybe you're getting "-2" because Google isn't returning any size ?
Is that a magic file ?

**Comment by atroxix** [comment] 2016-03-22 09:41
Don't know about magic files, but there are other ordinary files (the previous one I mentioned is just an .odt document) which behave the same way.

**Comment by PVince81** [comment] 2016-03-22 09:44
Syncing also works, the desktop client downloaded that file for me.

@atroxix are these ODT files real ODT files or are they Google Documents that get converted to ODT on download ? (Google magic FTW!)

@atroxix did you try `./occ files:scan --all -v` ?

**Comment by atroxix** [comment] 2016-03-22 09:46
That certain file is a normal .odt file.

I have a cron job running every 15min:

> sudo -u www php /usr/local/www/owncloud/occ files:scan --path=silver/files/GoogleDrive

I guess that serves the same purpose?

**Comment by PVince81** [comment] 2016-03-22 09:47
Yes, correct.

Also check the `oc_storages` table to find the "numeric_id", then do `select * from oc_filecache where storage=$numeric_id` (replace accordingly)
That table should contain all your GDrive files except the duplicate ones. If it doesn't, then update detection failed somewhere.

**Comment by PVince81** [comment] 2016-03-22 09:56
Okay, I found the place where the "-2" comes from:
https://github.com/owncloud/core/blob/v9.0.0/apps/files_external/lib/google.php#L312

Whenever GDrive finds a file without extension, it tries to use mime type detection. Because the Google Docs files don't have an extension either.

**Comment by atroxix** [comment] 2016-03-22 09:58
But at least one such file has .odt and is really a normal file.

**Comment by PVince81** [comment] 2016-03-22 10:00
I created a google doc on my GDrive, then run occ files:scan. The code in question was triggered (no size returned).
This is the resulting PROPFIND:
```
   <d:prop>
    <oc:id>00000020ockbfur1449k</oc:id>
    <oc:fileid>20</oc:fileid>
    <oc:permissions>MDNVW</oc:permissions>
    <d:getlastmodified>Tue, 22 Mar 2016 09:57:14 GMT</d:getlastmodified>
    <d:getetag>&quot;56f11742914e4&quot;</d:getetag>
    <d:getcontentlength>-2</d:getcontentlength>
    <oc:downloadURL></oc:downloadURL>
    <oc:owner-id>admin</oc:owner-id>
    <oc:owner-display-name>admin</oc:owner-display-name>
    <oc:favorite></oc:favorite>
    <oc:tags/>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
```

I don't think all this is related to @atroxix's syncing problem if other files don't sync.

@guruz in general we could improve the webdav code to return an empty "contentlength" if the size is negative for files, if that helps in any way.

@atroxix try creating a local file in your local gdrive folder to force the sync client to upload a new file. Sometimes it helps unstuck the update detection.

**Comment by PVince81** [comment] 2016-03-22 10:02
Raised https://github.com/owncloud/core/issues/23468 to look into improving the Webdav response to not return negative sizes when the size is unknown.

**Comment by atroxix** [comment] 2016-03-22 10:03
> Also check the oc_storages table to find the "numeric_id", then do select * from oc_filecache where storage=$numeric_id (replace accordingly)

That list seems fine.

**Comment by atroxix** [comment] 2016-03-22 10:04
> try creating a local file in your local gdrive folder to force the sync client to upload a new file. Sometimes it helps unstuck the update detection.

Did that in that same folder, but that .odt file with -2 size is still not downloaded.

**Comment by PVince81** [comment] 2016-03-22 10:04
@atroxix ok, then maybe the etag hasn't changed so the sync client doesn't bother to try downloading the new files.

> {"reqId":"6gmdY3MAdenMMr4mhEWs","remoteAddr":"10.0.254.102","app":"PHP","message":"fread() expects parameter 1 to be resource, boolean given at \/srv\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php#812","level":3,"time":"2016-03-16T07:29:52+00:00"}

Do you have encryption enabled ? Maybe one of the files was encrypted already and could not be decrypted, and makes the sync abort ?

**Comment by atroxix** [comment] 2016-03-22 10:06
I don't have encryption enabled and I'm sure it's related to this -2 size as during the sync process I see many files being tried to be downloaded with messages like "getting ...KB from -2B". And none of those files are actually downloaded then.

**Comment by atroxix** [comment] 2016-03-22 10:12
I don't have encryption enabled and I'm sure it's related to this -2 size as during the sync process I see many files being tried to be downloaded with messages like "getting ...KB from -2B". And none of those files are actually downloaded then.

**Comment by atroxix** [comment] 2016-03-22 10:14
Oh, sorry, that file is in fact .ods, and in GoogleDrive extension isn't shown for that, but in OwnCloud UI there is.

**Comment by PVince81** [comment] 2016-03-22 10:17
> Oh, sorry, that file is in fact .ods, and in GoogleDrive extension isn't shown for that, but in OwnCloud UI there is.

Yes, the ownCloud code needs to "cheat" by adding the extension for you to see, and also to make the file appear as a real ODT inside ownCloud. Also, when we ask Google to download such file, we actually ask it to export it to ODT, because downloading Google Docs files isn't possible.
So for such files, a lot of magic is happening...

**Comment by atroxix** [comment] 2016-03-23 07:12
> ok, then maybe the etag hasn't changed so the sync client doesn't bother to try downloading the new files.

I guess that's it - tried with another table, and indeed - if I do a change in Google Docs then it isn't re-downloaded by OwnCloud client, even though the file is updated in OwnCloud itself.

**Comment by atroxix** [comment] 2016-03-23 07:20
Sorry, wrong information. That test table is updated fine by the client. But the other .ods (Google Docs format in GoogleDrive) is still ignored.

**Comment by PVince81** [comment] 2016-03-23 09:34
@atroxix I suspect that when creating/editing a new Google Docs file, GDrive doesn't update the folder's parent mtime, but regular files do. (just guessing, needs to be verified).
The update detection code relies on mtimes delivered by GDrive to find out whether there are new/modified files to rescan.

**Comment by atroxix** [comment] 2016-03-23 10:06
Well, those 2 files are in the same folder. The only difference i see is that the problematic filename contains spaces.

**Comment by guruz** [comment] 2016-04-13 13:57
@PVince82 do you have a recommendation for the client _now_? Just ignore files with negative content length?

**Comment by guruz** [comment] 2016-04-13 13:57
@PVince81 do you have a recommendation for the client _now_? Just ignore files with negative content length?

**Comment by PVince81** [comment] 2016-04-18 10:55
@guruz I'd say have the client still download the file and take the actual received size / the size returned by Content-Length.

**Comment by guruz** [comment] 2016-04-18 14:25
I can confirm what @ogoffart wrote on IRC: We already "ignore" the content length (it errornously gets treated as an unsigned number, e.g. for -2 I get ```size=18446744073709551614``` in discovery phase) and use the correct length at the download job. So this is OK for a Google Doc file = .odt file.

However I also get several Server errors for other files, e.g. a PDF file. But some PDF files work.. will dig into this.

**Comment by PVince81** [comment] 2016-04-18 14:41
@guruz is that PDF file on GDrive ? If yes, dark magic ?!

**Comment by guruz** [comment] 2016-04-19 14:11
Closing the issue here..
If there is more to be done, please check the server issue tracker..

https://github.com/owncloud/core

**Closed by guruz** 2016-04-19 14:11 UTC
Labels: Discussion, Server Involved
