### ISSUE TITLE
Client shows ask confirmation for files bigger than 1% .... 

### ISSUE THREAD

**Issue by Kawohl** [owncloud/client#3886] opened 2015-09-25 15:15 UTC
Host OSX Yosemite 10.10.5

![bildschirmfoto 2015-09-25 um 17 12 00](https://cloud.githubusercontent.com/assets/12275313/10104250/e6c43eb4-63a8-11e5-80c6-c53b36a038b3.png)

**Comment by phil-davis** [comment] 2015-09-25 15:31
Duplicate of https://github.com/owncloud/client/issues/3717
This is an issue with the German translation.

**Closed by phil-davis** 2015-09-25 15:31 UTC
Labels: Design & UX
