### ISSUE TITLE
[OS X] [1.8.0 nightly] Menu bar disappears on on initial click

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#2746] opened 2015-01-25 19:15 UTC
### Expected behaviour
Menu Icon should stay in the menu bar
![screen shot 2015-01-25 at 20 11 10](https://cloud.githubusercontent.com/assets/878997/5892849/547ed0ee-a4ce-11e4-955f-f9ec5d84c4b3.png)

### Actual behaviour
Menu Icon disappears:
![screen shot 2015-01-25 at 20 11 03](https://cloud.githubusercontent.com/assets/878997/5892850/5480afa4-a4ce-11e4-8033-e03db0207943.png)

### Steps to reproduce
1. Delete existing configuration of ownCloud client in `/Users/lreschke/Library/Application Support/owncloud/`
2. Install 1.8.0 nightly as of 75540e8a4c3d50cf2fb45973ff02d362f098e3b2
3. Configure it (for the record: configured against `localhost/core` with "admin" as username and password)
4. When clicking on "Settings" in the menu bar the icon disappears, when clicked on the empty place again it reappears

### Client configuration
Client version: 75540e8a4c3d50cf2fb45973ff02d362f098e3b2 (nightly) provided by @danimo 

Operating system: OS X 10.10.2 (Developer Preview)

OS language: English

Installation path of client: `/Applications/owncloud.app`

### Logs

I have no idea whether those log entries will be helpful or not, that appears in the log file when clicking on the "Settings" button:

```
01-25 20:14:34:754 0x7fe2f04529a0 :0 SocketApi:  New connection QLocalSocket(0x7fe2f2e34fa0)
01-25 20:14:34:755 0x7fe2f04529a0 :0 SocketApi:  Sending message:  "ICON_PATH:/Applications/owncloud.app/Contents/Resources/icons/"
01-25 20:14:34:756 0x7fe2f04529a0 :0 SocketApi:  Sending message:  "REGISTER_PATH:/Users/lreschke/ownCloud/"
01-25 20:14:34:763 0x7fe2f04529a0 :0 SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
01-25 20:14:41:646 0x7fe2f04529a0 :0 QPainter::begin: Paint device returned engine == 0, type: 3
01-25 20:14:41:647 0x7fe2f04529a0 :0 QPainter::setCompositionMode: Painter not active
01-25 20:14:41:648 0x7fe2f04529a0 :0 QPainter::end: Painter not active, aborted
01-25 20:14:41:652 0x7fe2f04529a0 :0 void OCC::ownCloudGui::slotShowSettings()
```

**Comment by danimo** [comment] 2015-01-25 19:16
@guruz Didn't we observe that as well, but couldn't reproduce?

**Comment by guruz** [comment] 2015-01-25 20:39
@danimo So is that nightly build with 5.4 yet?

**Comment by LukasReschke** [comment] 2015-01-25 20:52
Settings pages says yes:

![screen shot 2015-01-25 at 21 51 55](https://cloud.githubusercontent.com/assets/878997/5893244/68973c52-a4dc-11e4-970a-582d922bbb02.png)

**Comment by lmaestro** [comment] 2015-01-26 13:18
Using the same build I can't reproduce it with operating system: OS X 10.10.1

**Comment by lmaestro** [comment] 2015-01-26 15:59
I am able to reproduce it the first time that you install it and click on "Settings".

**Comment by guruz** [comment] 2015-01-29 19:14
I also manage to reproduce this on 10.9.5

This log message appears
```
01-29 20:09:12:816 0x7fd9d8d207b0 :0 QPainter::begin: Paint device returned engine == 0, type: 3
01-29 20:09:12:816 0x7fd9d8d207b0 :0 QPainter::setCompositionMode: Painter not active
01-29 20:09:12:816 0x7fd9d8d207b0 :0 QPainter::end: Painter not active, aborted
```
BUT it also can appear when everything is drawn fine.

I think I can reproduce this by start the client, then waiting until I get the green icon, then i click it, then i move the cursor away to somewhere outside the popup menu and the tray icon, then i click again -> icon gone/transparent.

**Comment by guruz** [comment] 2015-01-29 19:25
Upstream bug is https://bugreports.qt.io/browse/QTBUG-44113
Let's see, maybe we can easily fix it ourselves..

**Comment by lmaestro** [comment] 2015-02-19 07:46
@dragotin any news?

**Comment by jturcotte** [comment] 2015-02-20 15:50
I have a fix for Qt, I need to verify that it works on retina display. The actual bug is hidden by another bug that prevents the Selected mode of the QIcon to be used usually, where it would be overwritten by the Normal mode, thus showing the paintDevice == 0 error but still display fine.

The actual bug is that it tries to look at available sizes for a mode, but since we don't provide a Selected pixmap, it tries to use an empty QSize to resize the fallback pixmap.

**Comment by jturcotte** [comment] 2015-02-25 14:37
Qt fix uploaded at https://codereview.qt-project.org/107101

**Comment by dragotin** [comment] 2015-02-25 16:41
@jturcotte do we add this fix to our builds as well, or do we wait for a new upstream Qt release? @danimo

**Comment by jturcotte** [comment] 2015-02-25 16:50
I'm not sure what are your policy regarding this usually, but note that 5.4.1 just got released and we'll probably release 1.8 before 5.4.2 or 5.5.0.

The other question is if we pick it now, in time for the next beta, or if we wait until it get reviewed and merged in Qt.

**Comment by danimo** [comment] 2015-02-25 17:08
@jturcotte get me the patch, and I'll add it to the build machine for testing.

**Comment by dragotin** [comment] 2015-02-25 17:21
yes, which should happen before beta2

**Comment by jturcotte** [comment] 2015-02-25 17:32
Here's the raw patch: https://gist.githubusercontent.com/jturcotte/73bd3276fcbbea15a62c/raw/6b9d2906e4c4f203ab8874776d76c4509658b026/gistfile1.diff

You can also get it from gerrit in a qtbase clone by running:
git fetch https://codereview.qt-project.org/qt/qtbase refs/changes/01/107101/1 && git format-patch -1 --stdout FETCH_HEAD

**Comment by guruz** [comment] 2015-02-26 08:54
It is fixed in http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.2058-nightly20150226.pkg.tbz on 10.10

@LukasReschke Please test too.

**Closed by guruz** 2015-02-26 08:54 UTC
Labels: bug, gold-ticket

**Comment by LukasReschke** [comment] 2015-02-26 09:22
Confirmed on 10.10 for Retina and Non-Retina. Thanks :rocket:
