### ISSUE TITLE
owncloudcmd and unsyncedfolders

### ISSUE THREAD

**Issue by clemenlg** [owncloud/client#4690] opened 2016-04-15 15:15 UTC
Hi,
i'm trying to sync local folders (host: Windows 7), with my owncloud server, but I don't want to sync some folders.
I'm trying to use the --unsyncedfolders, but it seems that don't work. If I try to change the file that contains this folders, with any fake path, it works without problems (I hope maybe will be a warning message).
For example:
Content of D:
`D:\AAA\files`
`D:\somefolder\files`
`D:\somefolder2\files`
`...`

list_unsynced_folders.lst:
`AAA/`

My execution line:
`owncloudcmd.exe --unsyncedfolders C:\list_unsynced_folders.lst -u "xxx" -p "xxx" "D:" http://IP/OC/remote.php/webdav/folder`

If I try this configuration, always sync the "AAA" folder.
I've owncloud client 2.1.1.
I tried too with relative and absolute paths, as: _D:/AAA/, D:\AAA\, D:/AAA, D:\AAA, AAA\_ in the list_unsynced_folders.lst file.
What's wrong? I think maybe it's a bug.
Regards

**Comment by ogoffart** [comment] 2016-04-18 13:14
`--unsyncedfolders`  is for the selective sync blacklist  (not syncing folders FROM the server)    (altough it normaly should not upload them either, it should give error for them)

Maybe you wanted to specify an exclude list with `--exclude`

**Comment by clemenlg** [comment] 2016-04-18 15:24
Ho @ogoffart 
It's not syncing folder FROM the server, but TO the server.
I think too should give an error, but it's not any error.
I only want sync the PC TO the server, but excluding some local (pc) folders (subfolders).
Regards

**Comment by ogoffart** [comment] 2016-04-21 11:01
So the problem is that the selective sync list is not properly saved on the first run of owncloudcmd because the journal does not exist yet.  This should be fixed now by commit 7a82fac

Anyway,  --unsyncedfolders is for the selective sync blacklist (not syncing folders FROM the server).
What you want to do is --exclude

**Closed by ogoffart** 2016-04-21 11:01 UTC
Labels: bug, Design & UX, sev3-medium
