### ISSUE TITLE
Overlay icons problem on arch linux

### ISSUE THREAD

**Issue by lbayerlein** [owncloud/client#6406] opened 2018-03-26 15:27 UTC
### Expected behaviour
I am starting Nautilus, click on the folder and there are folders and files with a given state in it. This state would be shown by small icons extending the default icons.

### Actual behaviour
Nautilus does not show anything.

### Steps to reproduce
1. Install Nautilus and owncloud-client in the actual version. Nautilus via pacman, owncloud via aur (in my case yaourt)
2. Start owncloud client with a configured account
3. Start Nautilus from the system application (not from the terminal as user)

### Server configuration
Operating system: CentOS 7.15011

Web server: Apache2 (2.4)

Database: MariaDB

PHP version: 7.1

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: 2.4.1

Operating system: Arch Linux (Linux version 4.15.10-1-ARCH (builduser@heftig-18961) (gcc version 7.3.1 20180312 (GCC)) #1 SMP PREEMPT Thu Mar 15 12:24:34 UTC 2018)

OS language: DE

Qt version used by client package (Linux only, see also Settings dialog): 5.10.1

Client package (From ownCloud or distro) (Linux only): 

Installation path of client: default

**Comment by guruz** [comment] 2018-03-26 16:42
(See also discussion on #owncloud-client-dev on freenode:
```
<bigbalu> but what I have found: if I run nautilus from system tray - all icons are not shown. If I run it manually from terminal, everything works
<bigbalu> should I open a bug?
````
)

**Comment by ogoffart** [comment] 2018-03-27 08:37
Any umlaut in the file paths?  I suspect this is a duplicate of  #6393 Fixed by #6397

**Comment by ckamm** [comment] 2018-03-28 11:12
But why would the umlaut problem apply only to the nautilus that's started from the system tray? 

@lbayerlein Could you check if both are using the same nautilus binary (you're on arch, maybe one of them is using python3 and not having the encoding issues?)

```
ls -l /proc/`pgrep -n nautilus`/exe
```

Otherwise: Could you check what the system-tray started nautilus is saying?

```
strace -p`pgrep -n nautilus` -s9999 -e write
```

**Comment by lbayerlein** [comment] 2018-03-29 14:25
Hi @ckamm and @ogoffart ,

```
ls -l /proc/`pgrep -n nautilus`/exe
```
shows me:
```
lrwxrwxrwx 1 ludwig ludwig 0 29. Mär 09:01 /proc/9001/exe -> /usr/bin/nautilus
```
And for the `strace` command, I get many lines with these informations:
```
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
```

**Comment by ogoffart** [comment] 2018-04-04 14:46
What's the value of `$XDG_RUNTIME_DIR` Is it defined the same for the owncloud client and nautilus?
Do `$XDG_RUNTIME_DIR/ownCloud/socket` exists

What show in the console when starting nautilus?  (can you do `killall nautilus; nautilus`) It should show `Initializing ownCloud-client-nautilus extension` and then a few other messages.

**Comment by lbayerlein** [comment] 2018-04-04 15:01
Hi @ogoffart ,

here all things from my side:
```
ludwig@balu  ~   master  ls $XDG_RUNTIME_DIR/ownCloud/
socket
ludwig@balu  ~   master  echo $XDG_RUNTIME_DIR
/run/user/1000
ludwig@balu  ~   master  killall nautilus;nautilus
nautilus: Kein Prozess gefunden
Initializing ownCloud-client-nautilus extension
Socket File: /run/user/1000/ownCloud/socket
Setting connected to True.
Socket watch id: 15
Server response: REGISTER_PATH:/home/ludwig/ownCloud
Server response: GET_STRINGS:BEGIN
Server response: STRING:SHARE_MENU_TITLE:Teilen…
Server response: STRING:CONTEXT_MENU_TITLE:ownCloud
Server response: STRING:COPY_PRIVATE_LINK_MENU_TITLE:Privater Link in die Zwischenablage kopiert
Server response: STRING:EMAIL_PRIVATE_LINK_MENU_TITLE:Sende privaten Link per Email...
Server response: STRING::
Server response: GET_STRINGS:END
Server response: STATUS:OK:/home/ludwig/ownCloud

** (nautilus:14037): CRITICAL **: 16:57:38.426: nautilus_column_provider_get_columns: assertion 'iface->get_columns != NULL' failed
Nautilus-Share-Message: 16:57:38.571: Called "net usershare info" but it failed: »net usershare« gab den Fehler 1 zurück: Can't load /etc/samba/smb.conf - run testparm to debug it

Server response: STATUS:OK:/home/ludwig/ownCloud/
```
Seems that it is everything OK.

**Comment by lbayerlein** [comment] 2018-04-04 15:07
I have found further informations.

```
Apr 04 17:04:50 balu org.gnome.Nautilus[932]: Initializing ownCloud-client-nautilus extension
Apr 04 17:04:50 balu org.gnome.Nautilus[932]: Socket File: /run/user/1000/ownCloud/socket
Apr 04 17:04:50 balu org.gnome.Nautilus[932]: Setting connected to True.
Apr 04 17:04:50 balu org.gnome.Nautilus[932]: Socket watch id: 17
Apr 04 17:04:50 balu org.gnome.Nautilus[932]: Server response: REGISTER_PATH:/home/ludwig/ownCloud
Apr 04 17:04:50 balu org.gnome.Nautilus[932]: Server response: GET_STRINGS:BEGIN
Apr 04 17:04:50 balu org.gnome.Nautilus[932]: Traceback (most recent call last):
Apr 04 17:04:50 balu org.gnome.Nautilus[932]:   File "/usr/lib/python2.7/site-packages/gi/overrides/GLib.py", line 668, in <lambda>
Apr 04 17:04:50 balu org.gnome.Nautilus[932]:     func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
Apr 04 17:04:50 balu org.gnome.Nautilus[932]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 133, in _handle_notify
Apr 04 17:04:50 balu org.gnome.Nautilus[932]:     self._handle_server_response(l.decode('utf-8'))
Apr 04 17:04:50 balu org.gnome.Nautilus[932]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 140, in _handle_server_response
Apr 04 17:04:50 balu org.gnome.Nautilus[932]:     print("Server response: " + line)
Apr 04 17:04:50 balu org.gnome.Nautilus[932]: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 47: ordinal not in range(128)
```
To get this, I run nautilus from the desktop file (nautilus), not in the terminal. Hope it will get you further

**Comment by ogoffart** [comment] 2018-04-04 15:53
Do you have the arhclinux package `owncloud-client 2.4.1-2`   the `-2` is important because it has the fix.

Anyway, i think the problem here is that the print() tries to converet the string with an ascii codec, but it contains the `…` character

**Comment by lbayerlein** [comment] 2018-04-04 18:44
Yes, the actual version of owncloud-client is installed (with -2). I installed it via `yaourt`

```
ludwig@arch  ~   master  pacman -sQ | grep ownc
local/owncloud-client 2.4.1-2
 ludwig@arch  ~   master  yaourt -S owncloud-client
warning: owncloud-client-2.4.1-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) owncloud-client-2.4.1-2

Total Installed Size:  7.31 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
```

**Comment by lbayerlein** [comment] 2018-04-04 18:48
On my second pc, I reinstalled it via `yaourt` (answered Y to the question above), run `journalctl -f` after that and run nautilus again. This comes up:

```
Apr 04 20:46:25 arch.balu.lan org.gnome.Nautilus[8947]: Traceback (most recent call last):
Apr 04 20:46:25 arch.balu.lan org.gnome.Nautilus[8947]:   File "/usr/lib/python2.7/site-packages/gi/overrides/GLib.py", line 668, in <lambda>
Apr 04 20:46:25 arch.balu.lan org.gnome.Nautilus[8947]:     func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
Apr 04 20:46:25 arch.balu.lan org.gnome.Nautilus[8947]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 133, in _handle_notify
Apr 04 20:46:25 arch.balu.lan org.gnome.Nautilus[8947]:     self._handle_server_response(l.decode('utf-8'))
Apr 04 20:46:25 arch.balu.lan org.gnome.Nautilus[8947]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 140, in _handle_server_response
Apr 04 20:46:25 arch.balu.lan org.gnome.Nautilus[8947]:     print("Server response: " + line)
Apr 04 20:46:25 arch.balu.lan org.gnome.Nautilus[8947]: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 55: ordinal not in range(128)
```

**Comment by lbayerlein** [comment] 2018-04-04 18:53
I did some further testing and can recognize this error on my side. If there is an 'ä', 'ö' or 'ü' in the current view (in the folder), this traceback comes up.

**Comment by ckamm** [comment] 2018-04-06 08:14
Does look like an encoding issue that wasn't fixed by #6397. Possibly only reproducible with python3? (should add python version to initialization output)

**Comment by ogoffart** [comment] 2018-04-25 11:35
Hopefully fixed with  https://github.com/owncloud/client/pull/6490

@ckamm: from what i understand, python 2.7 is used there, the problem is not with filename with, but with the fact that the german translation of owncloud contains a unicode '…' in the strings.

**Comment by ckamm** [comment] 2018-04-25 17:11
@lbayerlein Could you test by replacing `/usr/share/nautilus-python/extensions/syncstate-ownCloud.py` with the up to date version from https://github.com/owncloud/client/blob/1ab3a9fc130bc028ff3246cb617a2cd893238b49/shell_integration/nautilus/syncstate.py ?

**Comment by ckamm** [comment] 2018-04-26 08:05
@lbayerlein Thank you for testing.

I'll close this here. The PR for the backport is also part of the 2.4.2 milestone.

**Closed by ckamm** 2018-04-26 08:05 UTC
Labels: bug
