### ISSUE TITLE
[2.3.*] [Windows] Inappropriate conflict resolution: Conflict even though I'm the only editor

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#5133] opened 2016-08-24 11:17 UTC
### Expected behaviour

When I'm the only client (and not doing any manual modifications on the server), the server should never overwrite any of my files.
### Actual behaviour

Sometimes - I suspect it mostly happens with frequently-edited files, in particular files that may be modified while they are being synced - the ownCloud client seems to detect that there is a new file version on the server, which is not possible because I currently only sync with one client. In this case, ownCloud replaces the on-disk file with the server version and renames the original file to "filename.conflict" (or similar). I find this very inappropriate, the client should keep **my** version, especially since it has the newer file modification date than the server version.

I don't know how ownCloud exactly implements the syncing mechanism, so I can only guess why it happens or what can be done to prevent it, but to me it sounds like the client should only hold an opportunistic lock on Windows (see e.g. https://blogs.msdn.microsoft.com/oldnewthing/20130415-00/?p=4663) so that if someone else modifies the file, the client just stops syncing it. Otherwise, I imagine that the client may see part of the original file and part of the modified file, which may or may not be the root cause of my problem.
### Steps to reproduce

Unsure. Probably happens by frequently updating a file. This happens very often e.g. when syncing my browser or instant messenger profiles, which get updated very often naturally.
### Client configuration

Client version: 2.3.0-nightly (but happened with any previous version as well)

Operating system: Windows 7 x64

OS language: German

Installation path of client: Default

**Comment by guruz** [comment] 2016-08-24 12:01
This should indeed not happen.
How big is the file?
Do you use server side encryption or external storages?

**Comment by sagamusix** [comment] 2016-08-24 12:04
Server files are encrypted, and the files in question are of varying file size, typically several MB in size though (so syncing takes a while on a typical home connection).

**Comment by dragotin** [comment] 2016-08-24 13:42
It would be good to see a client log file when this happens. Can you start the client with the `--logfile` option and try to reproduce the problem? Thanks.

**Comment by sagamusix** [comment] 2016-08-24 19:46
Running `owncloud.exe --logfile` starts the executable and then instantly closes it after a second. Are you sure it's the correct parameter?

**Comment by dragotin** [comment] 2016-08-25 10:43
Yes, it is, but you need to add a file name to where the logfile goes:
```
owncloud --logfile /tmp/mylogfile.log
```

**Comment by countupir** [comment] 2016-08-28 06:02
Don't feel too badly.  I have this same conflict problem and I am saving txt files that are around 1Kb each.  This is a buggy version from what I can tell. I use 2.2.3 OSX client

I constantly get error about the client not able to update or sync any particular file.  It is just all the time and about every 5 mins.

Does anyone know of a version I can just pay for.  I am not using owncloud so I can not pay for a working product.  I want to own my cloud and this free/opensource shit is annoying in this case.  Anyone have suggestions of what you use that isn't free/opensource?  Does anyone know of a client for owncloud that I can pay for?

**Comment by sagamusix** [comment] 2016-09-03 22:03
I just had a similar, but probably not identical occurrence to the described problem, but sadly I forgot to enable logging when this happened, so I cannot provide a log.
What I did was to rename a folder which contained an SVN working copy and was already synced, switched to another SVN branch in that folder, did some modifications, and sometime later the client decided that it needs to download all the original files (from before the folder was moved, i.e. from the previous SVN branch) and undo all my changes.

**Comment by sagamusix** [comment] 2016-09-05 12:33
I could reproduce the original bug, but now I have to somehow get the relevant files out of a 12GB log...

**Comment by sagamusix** [comment] 2016-09-23 22:13
Sorry for the long delay, but I hope I could isolate the relevant lines from the log now.
The log excerpt is available at http://sagagames.de/stuff/owncloud-conflict.7z

**Comment by sagamusix** [comment] 2016-09-27 22:20
Just had it happening again, the file was supposedly last modified a week ago on the server, while the local file was modified earlier today, and yet ownCloud still tried to download the server version.

**Comment by sagamusix** [comment] 2016-10-06 20:09
Does the log give any clues?

**Comment by ogoffart** [comment] 2016-10-12 08:37
The log only show the obvious: There is a conflict because the etag has changed on the server, and the mtime has changed localy.

Maybe we need to have the log for earlier upload of the file when the etag is saved in the database.

It could be that upload to the server fails, or is not rported correctly.

Is there any error in the "activity" tab?

**Comment by ckamm** [comment] 2016-10-12 11:55
This might possibly be related to #5242: If a local file wasn't properly up to date with the server version, a local edit should produce a conflict. 

@sagamusix You're using a 2.3.0 build right? Could you open the "Ignored Files" dialog and hit okay? That will force a full remote discovery and might find stale files like this. If this problem still happens afterwards, it's unrelated to that bug.

**Comment by ogoffart** [comment] 2016-10-12 13:00
@ckamm:  i don't think so.  Since the client "thinks" the server is up to date, it will just upload the file and not create a conflict.

**Comment by ckamm** [comment] 2016-10-12 13:52
@ogoffart Oh, yes. It doesn't double-check the server's etag... :/

**Comment by sagamusix** [comment] 2016-10-12 22:52
> Maybe we need to have the log for earlier upload of the file when the etag is saved in the database.

I guess server logs don't go back that far? It's been a while since this file was uploaded.
I couldn't spot any errors on the sync tab.

**Comment by guruz** [comment] 2016-12-05 17:44
@ogoffart @ckamm What is the action item on this? Is this handled by https://github.com/owncloud/client/issues/5242 or is there more to be done?
If yes what?

**Comment by ckamm** [comment] 2016-12-06 09:51
@guruz It's not #5242, as @ogoffart pointed out if that bug had hit, we'd silently overwrite the server file, not create a conflict. I think that currently we don't know. Investigation, possibly involving stress testing, is needed.

**Comment by phil-davis** [comment] 2016-12-06 13:36
I used to have this problem (maybe 6 months or more ago?) but have not noticed it recently. However I have changed to having a server on ownCube, which has been working well, so maybe some previous slowness in my other server response was somehow involved, or maybe Windows client 2.2.4 is working better than whatever version I had back then. Sorry, not very helpful for debugging!
I suspect that #5324 will turn out to be the same root cause - it also ends up with the real latest changes (made locally) being found in the "conflict" file, and an older version coming down from the server.

**Comment by sagamusix** [comment] 2016-12-06 14:17
I would also suspect that both Windows file locks and a relatively slow server (running on BananaPi) do at least contribute to the issue.

**Comment by hodyroff** [comment] 2017-03-10 11:00
Need a reproduction with logfiles to be able to act on it or better understand the issue.

**Comment by jturcotte** [comment] 2017-03-23 13:02
Could be the same issue: #5106

**Comment by ogoffart** [comment] 2017-04-28 10:22
This issue might also be a server problem. (if the etag changes)
I'm closing it here because we can't do anything without more information anyway.

**Closed by ogoffart** 2017-04-28 10:22 UTC
Labels: Needs info
