### ISSUE TITLE
Automatic dehydration when computer running low on disk space 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7470] opened 2019-09-11 14:19 UTC
Client should automatically dehydrate files that are not pinned when running low on disk space

Other automatic dehydration issues: 
https://github.com/owncloud/client/issues/7084 
https://github.com/owncloud/client/issues/7402

**Comment by TheOneRing** [comment] 2021-03-17 14:01
@michaelstingl we need to document storage sense

**Comment by TheOneRing** [comment] 2021-07-16 13:04
Duplicate of https://github.com/owncloud/client/issues/8586

**Closed by TheOneRing** 2021-07-16 13:04 UTC
Labels: Documentation, Enhancement
