### ISSUE TITLE
Selective sync dialog table cuts off folder names by default

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3031] opened 2015-03-27 09:27 UTC
Whenever I open the selective sync dialog, it looks like this:
![selective-sync](https://cloud.githubusercontent.com/assets/925062/6865191/afc345ee-d46b-11e4-8c3c-6c222b485b62.png)

Instead, the file size column should always be pushed to the far right and only take as much space as needed. cc @ogoffart

**Comment by ogoffart** [comment] 2015-03-27 14:26
That's because of Qt4

**Comment by jancborchardt** [comment] 2015-03-27 15:21
![](http://media.tumblr.com/1cbb5e2b072f273e0c976b37fa9a57e8/tumblr_inline_nhbqwkHNAy1rvhjhe.gif)

**Comment by ogoffart** [comment] 2015-04-06 13:00
Depends on #2558

Since the problem is only with the few linux binaries that are still compiled with Qt4, and that it is not a sever issues, I am closing this bug as i don't whish to add code for that specialy for Qt4 while the feature is done in Qt5.

**Closed by ogoffart** 2015-04-06 13:00 UTC
Labels: bug, Design
