### ISSUE TITLE
Cannot connect securely to oc.hostiso.cloud

### ISSUE THREAD

**Issue by lacostenycoder** [owncloud/client#7475] opened 2019-09-14 08:48 UTC
### Expected behaviour
To be able to use the desktop client and connect securely without certificate warning

### Actual behaviour
When I launch MacOS desktop client, I get the following warning with an option to trust anyway, but not sure if this can be considered safe.  Here is the notice I get:

Cannot connect securely to oc.hostiso.cloud:
The host name did not match any of the valid hosts for this certificate
with Certificate davestid.hostiso.cloud
Organization: <not specified>
Unit: <not specified>
Country: <not specified>
Fingerprint (MD5): 95:4a:11:38:49:ba:4a:cf:f5:de:39:32:77:dc:f1:77
Fingerprint (SHA1): b0:dc:ac:95:eb:27:c5:9c:9f:80:91:da:de:b9:12:07:e9:02:d7:08

Effective Date: Sun Aug 4 00:00:00 2019 GMT
Expiration Date: Sat Nov 2 23:59:59 2019 GMT
Issuer: cPanel, Inc. Certification Authority
Organization: cPanel, Inc.
Unit: 
Country: US

### Steps to reproduce
1. Download and install MacOS client Version 2.5.4 (build 11456)
2. Launch the desktop client.

### Server configuration
Not running a server but just trying to use the desktop client.

Operating system: n/a

Web server: n/a

Database: n/a

PHP version: n/a

ownCloud version: 

Storage backend (external storage):

### Client configuration
Client version:  2.5.4 (build 11456)

Operating system: MacOS 10.14.3 (18D109

OS language: English US

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: /Applications/owncloud.app 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by prsnbrg** [comment] 2019-09-14 16:03
I can’t see any login page on oc.hostiso.cloud for owncloud and I think davestid.hostiso.cloud work not correctly.

**Comment by michaelstingl** [comment] 2019-09-15 10:51
Maybe check server certs with https://www.ssllabs.com/ssltest/index.html

**Comment by jnweiger** [comment] 2019-09-17 08:49
The cert of oc.hostiso.cloud currently says it was issued for davestid.hostiso.cloud 
That cert should be changed to also include the name oc.hostiso.cloud -- to be done by the domain owner.

The owncloud client shows the correct diagnostics. From my perspective, this *is* the expected behaviour of the client. Closing here. Please reopen, if I am wrong.

**Closed by jnweiger** 2019-09-17 08:49 UTC

**Comment by lacostenycoder** [comment] 2019-09-17 11:23
@jnweiger how is anyone supposed to use the MacOS Desktop app if this is closed.  Do I have any control over this on my end?

**Comment by lacostenycoder** [comment] 2019-09-17 11:44
Also it appears when trying to visit https://oc.hostiso.cloud that there's a problem with the certificate which is showing as invalid.  What can be done about it?

**Comment by jnweiger** [comment] 2019-09-17 11:51
The issue is not limited to the MacOS desktop. The broken cert should be rejected by all clients and webbrowsers.
Please escalate to support@hostiso.com
