### ISSUE TITLE
Make selective sync tree view more obvious to user

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3585] opened 2015-08-11 11:24 UTC
ownCloud client 2.0.0.5388
If I double-click in the ownCloud sync status area of an account it does 2 things:
a) The folder used by the sync client opens - seems a good thing.
b) The folder tree of folders to sync switches state (opens or closes)
![doubleclick-does-2-things](https://cloud.githubusercontent.com/assets/1535615/9196484/85367a52-404b-11e5-887e-27c3ff1163b5.png)
Maybe that is not as intended?
Maybe only action (a) is supposed to happen?

**Comment by danimo** [comment] 2015-08-11 19:58
@jancborchardt please

**Comment by jancborchardt** [comment] 2015-08-11 20:22
Duplicate of one of the points I brought up in https://github.com/owncloud/client/issues/3567

> * The [-] minus/plus button to expand the selective sync is weirdly placed and you hardly notice it. Can we make the folder expand/close on single click of the row? Right now it does that on double click but that is not discoverable.

So I would say single click expands/closes it. Double click should not do anything as it’s not really discoverable anyway. It will only result in misclicks.

If we decide we want the folder to be openable, we should introduce a button for it so everyone will be able to do it without knowing it works via double click.

(As a general rule: We should never do something which relies on double click or right click. Exempt is of course the sharing dialog which can only be invoked via right-click menu, unfortunately.)

**Comment by phil-davis** [comment] 2015-08-12 01:05
Note that single click of the minus/plus (right/down arrow) button does open/close the drop down list of folders to sync.
So you think that single click of the "main area" should open the folder in the local OS file explorer? Seems a good way to go.
Then double-click is not needed.

**Comment by jancborchardt** [comment] 2015-08-12 06:10
No, single click of the main area should expand the selective sync tree. The minus/plus is not present enough.

**Comment by phil-davis** [comment] 2015-08-12 07:29
OK.
Then double-click is handy to open the client folder in the local OS file explorer.

**Comment by phil-davis** [comment] 2015-08-12 09:06
So is this a useful issue in which to put a specific (and I think easy) change to made? That would make some easy progress towards the list of issues in #3567 
Requirements:
a) Single click of the area shown above shall expand/minimize the selective sync tree.
b) Double click of the area shown above shall open the client folder in the local OS file explorer.

**Comment by jancborchardt** [comment] 2015-08-12 09:20
Well, as said we shouldn’t put two separate actions on the same element, where one is invoked by single- and one by double-click. That will result in confusion. We need a separate button in that row with a folder icon to open the local folder.

**Comment by ogoffart** [comment] 2015-08-13 09:53
Now double click no logner open in file browser.  But there is a new action for it

**Comment by jancborchardt** [comment] 2015-08-13 10:10
@ogoffart aweeeesome! :) Thanks a bunch

**Comment by Dianafg76** [comment] 2015-08-13 11:27
@ogoffart I tested this issue and it is working OK
Desktop vownCloud-2.0.0.2626-nightly20150813.pkg 
Closed

**Comment by phil-davis** [comment] 2015-08-13 11:49
Now we have "Open Folder" on the right-click menu and a button to drop down the the same options as in the right-click menu - good, and @Dianafg76 is reporting the graphic issues with the exact way that is rendered in the first try - https://github.com/owncloud/client/issues/3584#issuecomment-130627684

Double-click now just opens/closes the "folders to sync" tree.

@jancborchardt - did you want just a single click to open/close the "folders to sync" tree?

**Comment by jancborchardt** [comment] 2015-08-13 12:08
> did you want just a single click to open/close the "folders to sync" tree?

Yes. Double click should not do anything. _Single_ click should open the tree.
And right click should also be disabled ideally – it should just be the menu. If possible.

@ogoffart @guruz?

**Comment by ogoffart** [comment] 2015-08-14 12:34
> Double click should not do anything

Every other tree view expends on double click.
I would expect users to be annoyed if the tree view of owncloud behave differently that any other tree view.

> And right click should also be disabled ideally

**Comment by jancborchardt** [comment] 2015-08-14 12:55
> Every other tree view expends on double click.

Not really? It expands on single click of the plus/minus button.

**Comment by phil-davis** [comment] 2015-08-21 14:27
Personally I can cope with the way this is now:
a) plus/minus button expands and collapses the folders to sync list with a single click
b) double click in the general area expands and collapses the folders to sync list
c) "Open folder" is in the "..." menu

But if others would like item (b) to be a single-click then that is also fine.

But it seems odd to make 2.0-release with the double click behaviour and know that 2.0.1 will change it to single-click. Having intentional little UI changes pending for a point release "coming soon" just means that UI documentation has to be specific to each point release and users who get in the habit of one thing then find they have to re-learn after every little update.

But I also understand that there are risks of new bugs if the change has to have significant re-engineering under the hood and is close to release time.

**Comment by ogoffart** [comment] 2015-08-21 15:32
In my opinion, we should keep the double-click to expends because this is how native tree view are.

**Comment by jancborchardt** [comment] 2015-08-24 06:59
If we can make it expand on single-click, then please let’s do that. Believe me, it will be a lot more easy to discover and people will find out about the selective sync functionality much easier.

**Comment by dragotin** [comment] 2015-09-11 11:10
In Windows, the default behaviour of treeviews is to expand/collapse on **double** click, exactly as with our client. I assume we stay with the standard as usual.

**Comment by jancborchardt** [comment] 2015-09-11 12:41
:( @ogoffart @dragotin we talked about this at the conf, no? The issue still stands – no matter if it’s an OS standard or not, double click is incredibly hard to discover. People don’t look at this and think »ah this is a tree view, I will need to double click«.

**Comment by ogoffart** [comment] 2015-09-11 17:02
People don't need to double click, they can use the little [+]  on the left to expand the tree.

**Comment by jancborchardt** [comment] 2015-09-13 15:45
@ogoffart repeating myself from #3567 which I already quoted above:

> The [+] minus/plus button to expand the selective sync is weirdly placed and you hardly notice it. Can we make the folder expand/close on single click of the row? Right now it does that on double click but that is not discoverable.

**Comment by guruz** [comment] 2015-09-13 22:24
btw, There is other ways to improve this, e.g. we could have the tree view opened when the account is first added...
Changed title

**Comment by dragotin** [comment] 2015-09-14 09:55
Gents, sorry. Please come up with a *concrete* problem description here, and make @jancborchardt coming up with a also *concrete* proposal how to fix.

**Comment by phil-davis** [comment] 2015-09-14 12:50
My original issue report is resolved - I was reporting that a double-click did 2 things (see the very first post). Now it does just 1 thing - open/closes the folders to sync tree view.
Now there is discussion about single and/or double click to open the folders to sync tree view.
Why not do @jancborchardt request that it open/closes on single-click, and also leave the functionality that it open/closes on double-click also? That way it works whatever stuff the user does.
Since the original issue here is technically resolved, I suggest @jancborchardt create a new issue with the defined requirement.

**Comment by jancborchardt** [comment] 2015-09-14 13:06
> Gents, sorry. Please come up with a concrete problem description here, and make @jancborchardt coming up with a also concrete proposal how to fix.

I did that with https://github.com/owncloud/client/issues/3567

Problem description:
> The [-] minus/plus button to expand the selective sync is weirdly placed and you hardly notice it.

Concrete proposal:
> Can we make the folder expand/close on single click of the row? Right now it does that on double click but that is not discoverable.

**Comment by cburnard** [comment] 2015-09-15 18:32
This not really intuitive and customers are not finding it and when shown the location not happy. .  I was not able to easily locate it during as well.

@guruz Can we take a second look at this?

**Comment by guruz** [comment] 2015-09-15 18:47
I propose:
 * have it open by single click as Jan suggested
 * Additionally add something into the ```...``` button

**Comment by jancborchardt** [comment] 2015-09-15 22:01
@guruz good call!

**Comment by phil-davis** [comment] 2015-09-16 02:15
Version 2.0.2-nightly20150916 (build 5466)
1) Single-click opens the folder tree view - good stuff.

2) Single-click again does nothing - I was expecting the folder tree view to close, like I think previously if it was open then the double-click closed it. What is wanted for that?
The only way I found to close the folder tree view is to use the [+/-] button.

3) Choosing from "..." menu "Choose what to sync" opens the folder tree view - good, and also auto-expands all sub-folders.. in the view - was that intended?
It could be a big expand for people who have deep folder trees of "rubbish" created by an app (e.g. Thunderbird profile...) or have some development environment in there or...

**Comment by jancborchardt** [comment] 2015-09-16 07:19
> Single-click again does nothing - I was expecting the folder tree view to close

Yeah, I would also expect this to close it again.

> Choosing from "..." menu "Choose what to sync" opens the folder tree view - good, and also auto-expands all sub-folders.. in the view - was that intended?

No, that shouldn’t happen.

Can you fix accordingly @guruz? Thank you! :)

Btw, which entry is the »Choose what to sync« in the menu? Should be the one above »Pause sync«.

**Comment by phil-davis** [comment] 2015-09-16 07:28
Yes, the menu is:
```
Open folder
Choose What to Sync
Pause sync
Remove sync
```
While I notice it, the other 3 menu entries start with an uppercase letter then all following words are in lowercase.
But "Chose What to Sync" has the uppercase "W" and "S". That seems a bit odd.

**Comment by jancborchardt** [comment] 2015-09-16 07:54
Yeah, @guruz can you fix the capitalization to be »Choose what to sync« to be in line with the other entries? Thanks!

**Comment by guruz** [comment] 2015-09-16 15:04
I capitalized it like this to re-use the existing translations (it's too late for people to re-translate)

What you guys want is unfortunately tricky in this short time frame since the ```...```-button is hacked/painted inside the tree view so I get double ```clicked()``` and don't know whether to expand or collapse.
I'll move to 2.1

It should not expand all subfolders, it should expand 2 (accidently) levels. I'll change it to 1 level :)

**Comment by Dianafg76** [comment] 2015-10-22 13:59
I tested this issue, and now when you choosing from "..." menu "Choose what to sync" opens the folder tree view, it is only expand 1 level

Desktop v ownCloud-2.1.0.2821-nightly20151022.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}
Closed

**Closed by Dianafg76** 2015-10-22 13:59 UTC
Labels: approved by QA, blue-ticket, bug, Design & UX, green-ticket
