### ISSUE TITLE
[Overlays] Client folder error status not shown in higher-level icon status

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3634] opened 2015-08-17 09:40 UTC
### Expected behaviour
If a folder has a problem syncing from client to server then the problem status will be shown in the icons of parent folders and in the overall sync status icon in the icon box.

### Actual behaviour
If a folder has a problem syncing from client to server it (correctly) shows a little red "x" in the folder icon.
But any folders above it show green,
The overall client status icon shows green.

If the problem folder is several folders down in the folder tree then the user is unlikely to notice it and thus will not know to investigate.

It would be nice to show some non-green status for the folders above and the overall status icon.

### Steps to reproduce
1. On the client create FolderA.
2. Let it sync up to the server.
3. From the folders-to-sync dropdown, unselect FolderA and apply.
4. A sync starts, FolderA is deleted on the client - good - and remains on the server - good.
5. Create another FolderA in the same place.
FolderA is shown with red "x" icon - good.
Activity log says: Ignored because of the "choose what to sync" blacklist
That is also reasonable, because there is already FolderA on the server with some (presumably different) content, and it is not being synced to this client.

But the overall sync status is green.

There is the same sort of behaviour when FolderA is inside some other folder/s. The higher level folders all show green status.

### Server configuration
ownCloud version: 8.0

### Client configuration
Client version: Version 2.0.0-nightly20150817 (build 5403)

Operating system: Windows 10

OS language: English (US)

Installation path of client: default

**Comment by MTRichards** [comment] 2015-08-18 18:45
@guruz are you working on this now for 2.0, or does it slide to 2.0.1?

**Comment by jturcotte** [comment] 2015-08-18 19:42
I haven't investigated it yet but unless this is a regression from 1.8 (it's not, is it?) then we shouldn't put pressure on 2.0.0. If this requires bigger changes it might have to go in 2.1.

See also https://github.com/owncloud/client/issues/3171 for a glimpse of how error statuses aresn't preserved as long as they should. The moment that a file ends up in the black list, its status becomes invisible to the user. My knowledge of that area isn't quite good though, @ogoffart could prove me wrong if I am.

**Comment by jturcotte** [comment] 2015-08-18 19:59
Another question is: Is it correct to propagate anything else than the SYNC status to parent folders?

If I have the structure:
A
|- B
 |- C

And that C has an ignored or error status, should A also be marked as ignored/error? A isn't ignored completely, A isn't completely in error either. For SYNC, however we can say that "A isn't up-to-date", implied by C not being up-to-date.

I agree that there should be a way to see the error more easily than by inspecting the activity monitor, but I'm not sure if the status of parent directories is the right place to keep that information until the user decides to fix the situation (if he even knows how to fix it). It might handicap his ability to quickly judge if other files are up-to-date. Let me know how you see it.

**Comment by MTRichards** [comment] 2015-08-18 21:20
I thought we said that A should have a yellow, saying that it was non fatal, but there were problems in the directory below it. If the entire directory in C failed, C is red, otherwise if it is a partial fail C is yellow too, and that gets propagated up. I have to find the selective sync notes as it outlines it.

**Comment by MTRichards** [comment] 2015-08-18 21:22
Found it:
https://github.com/owncloud/client/issues/1818
That has the details on the design point for folders, including errors.

**Comment by phil-davis** [comment] 2015-08-19 01:50
Those requirements look good, with the addition of the "bubbling up with yellow" to parent folders that have red somewhere below but not all red, as @MTRichards has commented.

**Comment by dragotin** [comment] 2015-08-21 10:31
Moved to 2.1. This is not exactly how it is implemented today and as a result a bigger change.

**Comment by dragotin** [comment] 2015-08-21 10:33
This should be done together with #3171

**Comment by guruz** [comment] 2016-01-04 12:06
Related https://github.com/owncloud/client/issues/4026

**Comment by guruz** [comment] 2016-04-06 12:41
@phil-davis Can re-test this with a recent nightly as soon as the overlay binaries are rebuilt (https://github.com/owncloud/client/issues/4631)

**Comment by guruz** [comment] 2016-04-07 13:49
@phil-davis Would you re-test this? :)
http://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5976-nightly20160407-setup.exe

**Comment by guruz** [comment] 2016-04-19 12:50
@phil-davis Still alive? :-)
There's even newer nightlies now..

**Comment by mcastroSG** [comment] 2016-04-19 14:43
Hi hi:

@guruz I have made some test about this Issue using basically the same steps that @phil-davis put:

**Steps executed**

1. On the client create Folder1.
2. Inside Folder1 create Folder2
3. Let it sync up to the server.
4. From the folders-to-sync dropdown, unselect Folder2 and apply.
5. A sync starts, Folder2 is deleted on the client and still is on the server.
6. Create another Folder2 in the same place. 

**Results:**

Folder2 is shown with yellow icon and Activity log says: Ignored because of the "choose what to sync" blacklist, but Folder1 remains with a green icon.So it seems that sync error are not getting propagated up .

**IOS**
Client Version: Version 2.2.0-nightly20160419 (build 3282)
Client OS: IOS El Capitan 10.11.4
Server Version: 9.0.1
Server OS: Ubuntu

Unable to check it on windows due to [https://github.com/owncloud/client/issues/4701](url)

Regards

**Comment by jturcotte** [comment] 2016-04-19 15:17
Warning don't get propagated up, only errors. Else the root folder for example would never be green, there is always an ignored file somewhere in the tree (for example the .csync_journal db) and the user most likely won't want to change this. Errors on the other hand will usually need to be actioned by the user.

**Comment by jturcotte** [comment] 2016-04-19 15:19
Maybe the "ignored because of the choose what to sync blacklist" message should be an error though, it's not a normal use case.

**Comment by guruz** [comment] 2016-04-22 13:14
@mcastroSG BTW, the overlays are very OS-sensitive. So in this case you should test Windows (where @phil-davis is on).
The spec that @jturcotte mentions is https://github.com/owncloud/client/pull/4704/files ..

**Comment by mcastroSG** [comment] 2016-04-26 11:20
Blocked due to https://github.com/owncloud/client/issues/4737

**Comment by mcastroSG** [comment] 2016-05-05 12:58
Hi hi:


Test Case ID | Test case     | Steps   | Expected behaviour | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Overlay Icons - Folder hierarchy warning  | 1.- Generate a warning i.e a folder that could not be synced <br> | Overlay icon at parent folder is a "Green check" <br>  |  ✅
2 | Overlay Icons - Folder hierarchy error  | 1.- Generate an error i.e exceed quota allowed <br> | Overlay icon at parent folder is "Yellow warning" icon <br> | ✅
3 | Overlay Icons - Folder hierarchy error solved | 1.- Generate an error i.e exceed quota allowed <br> 2.- Wait till error is returned <br> 3.- Solve problem deleting problematic files  | Overlay icon at parent folder is updated from  "Yellow warning" icon to "Green Check" icon <br> | ✅

OSX:

Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0-nightly20160504 (build 3331)

OSW:

Client OS: W81
Client Version: Version 2.2.0-nightly20160505 (build 6054)
OSLinux

Client OS: Ubuntu 14.04 LTE
Client Version: Version 2.2.0nightly201654 (build 1587)

**Closed by mcastroSG** 2016-05-05 12:58 UTC
Labels: bug, ReadyToTest, sev2-high
