### ISSUE TITLE
[QA] Crash when removing an account 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11209] opened 2023-09-14 10:16 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

mac 
ownCloud 5.0.0.12103-daily20230912

### Steps to reproduce the issue

1. Add an account
2. Immediately (a few seconds delay) remove it just before the initial sync runs - correct timing is important 

### Screenshots

No screenshot 

### Expected behavior

Account successfully removed

### Actual behavior

Crashes:

d221224e-58cb-4ab6-9457-513e965e0086
85e9cf1c-5d90-41c0-b12e-cafb4a57ecd6
ac2dde30-82fd-4650-8a80-d50f5e633c9f
4ed3a2ae-ec2a-4d10-8504-ec0baa5c60e6
cc05c327-d465-4918-8076-877ad943cb8a

**Comment by TheOneRing** [comment] 2023-09-14 11:38
Duplicate of: https://github.com/owncloud/client/issues/11203

**Closed** 2023-09-19 11:33 UTC
Labels: bug, p3-medium, QA:team

**Comment by HanaGemela** [comment] 2023-09-25 09:22
Can't recreate in ownCloud 5.0.0.12187-rc.2 ✅
