### ISSUE TITLE
Client crashes on Windows XP

### ISSUE THREAD

**Issue by dahan1999** [owncloud/client#2731] opened 2015-01-21 13:55 UTC
I have thought this problem only occurs on XP virtual machine so I closed this issue last month. But I found this issue on both XP virtual machine and physical host, both the previous release and the latest one. I reopen it again with suggestion from tflidd.

Expected behaviour

Owncloud should synchronize files to servers without crash on Windows XP.

Actual behaviour

On Windows XP owncloud crashes after copy some files into owncloud home folder.

Steps to reproduce

On Windows XP install owncloud latest build(released on Dec 18th 2014)
Config your account and synchronize your files from server to local host. The owncloud home folder is C:\Documents and Settings\Administrator\ownCloud.
Copy some files into owncloud home folder. For example, copy 10 qm files from C:\Program Files\ownCloud into C:\Documents and Settings\Administrator\ownCloud.
owncloud.exe crashes.
Please repeat step 3 if owncloud does not crash. It is supposed that 6 in 10 times owncloud will crash. Or just drag and drop some files into the owncloud home folder will incur the crash.

Server configuration

This issue is supposed to have nothing to do with server. Because it does not happen with the same client on Windows 7, the same server.

Operating system:

Web server:

Database:

PHP version:

ownCloud version:

Storage backend:

Client configuration

Client version:
ownCloud-1.7.0.4162-setup

Operating system:
Windows XP SP3

OS language:
ZH_cn

Installation path of client:
None.

Logs

...
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_et.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_es_AR.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_eu.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_ca.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_el.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_fr.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_de.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_es.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_cs.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_fi.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_en.qm"
11-25 19:32:53:280 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_fa.qm"
11-25 19:32:53:280 0x5dd5d10 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit "post treewalk" and starting new transaction
11-25 19:32:53:280 0x5dd5d10 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit "post stale entry removal" and starting new transaction
11-25 19:32:53:280 0x5dd5d10 owncloudpropagator.cpp:305 Using QNAM/HTTP parallel code path
11-25 19:32:53:296 0x5dd5d10 folder.cpp:822 * csync thread started
11-25 19:32:53:296 0x5dd5d10 socketapi.cpp:270 Not sending UPDATE_VIEW for "ownCloud" because status() is 3
11-25 19:32:53:359 0x5dd5d10 owncloudgui.cpp:263 Folder in overallStatus Message: Mirall::Folder(0x6549128) with name "ownCloud"
11-25 19:32:53:359 0x5dd5d10 owncloudgui.cpp:180 Sync state changed for folder "ownCloud" : "Sync Running"
11-25 19:32:53:390 0x5dd5d10 socketapi.cpp:372 void Mirall::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, Mirall::SocketType) "C:\Documents and Settings\Administrator\ownCloud\mirall_ca.qm"
11-25 19:32:53:390 0x5dd5d10 syncengine.cpp:1095 bool Mirall::SyncEngine::estimateState(QString, csync_ftw_type_e, Mirall::SyncFileStatus) Setting "mirall_ca.qm" to STATUS_EVAL
11-25 19:32:53:390 0x5dd5d10 socketapi.cpp:527 Mirall::SyncFileStatus Mirall::SocketApi::fileStatus(Mirall::Folder, const QString&, c_strlist_t) Folder estimated status for "mirall_ca.qm" to "SYNC"
11-25 19:32:53:390 0x5dd5d10 socketapi.cpp:320 SocketApi: Sending message: "STATUS:SYNC:C:\Documents and Settings\Administrator\ownCloud\mirall_ca.qm"
11-25 19:32:53:390 0x5dd5d10 syncjournalfilerecord.cpp:80 Mirall::SyncJournalFileRecord::SyncJournalFileRecord(const Mirall::SyncFileItem&, const QString&) "C:/Documents and Settings/Administrator/ownCloud/32bits" Retrieved inode 20792 (previous item inode: 20792 )
11-25 19:32:53:390 0x5dd5d10 syncjournaldb.cpp:515 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7, ?8 , ?9 , ?10, ?11, ?12);" 263559720097868232 6 "32bits" 20792 0 "1416920387" "2" "54747d4406ea8" "00001036occaba3eb446" ""
11-25 19:32:53:390 0x5dd5d10 :0 QWindowsXPStylePrivate::buffer(w,h), failed to create dibsection ()

**Comment by dahan1999** [comment] 2015-01-22 00:22
I start a remote debug and saw the call stack of the crash codes. It seems that the code crashes in this line(raiseWidget->showNormal();):
"
void ownCloudGui::raiseDialog( QWidget *raiseWidget )
{
    if( raiseWidget && raiseWidget->parentWidget() == 0) {
        // Qt has a bug which causes parent-less dialogs to pop-under.
        raiseWidget->showNormal();
"
But I still have no idea of how to fix it.

Here is the call stack of the crash.
#0  0x7c92e4f4 in ?? ()
#1  0x7c92d50c in ?? ()
#2  0x7c93624a in ?? ()
#3  0x7c9364b3 in ?? ()
#4  0x7c801bbd in ?? ()
#5  0x7c801d72 in ?? ()
#6  0x769c7ade in ?? ()
#7  0x769c6be4 in ?? ()
#8  0x769c638e in ?? ()
#9  0x769c5d45 in ?? ()
#10 0x769c5c98 in ?? ()
#11 0x769e3d02 in ?? ()
#12 0x05a43256 in ?? ()
#13 0x05a4cf8e in ?? ()
#14 0x05a4ef9d in ?? ()
#15 0x029f7c3e in ?? ()
#16 0x66258835 in ?? ()
#17 0x66238894 in ?? ()
#18 0x6624198e in ?? ()
#19 0x663e1c92 in ?? ()
#20 0x6623f0a3 in ?? ()
#21 0x0044f5a8 in Mirall::ownCloudGui::raiseDialog (raiseWidget=0x5c5d2a8) at /home/yxy/mirall/src/mirall/owncloudgui.cpp:602
#22 0x0044f18a in Mirall::ownCloudGui::slotShowSettings (this=0x5c5c9d8) at /home/yxy/mirall/src/mirall/owncloudgui.cpp:554
#23 0x0044a0c3 in Mirall::ownCloudGui::slotOpenSettingsDialog (this=0x5c5c9d8, openSettings=true) at /home/yxy/mirall/src/mirall/owncloudgui.cpp:139
#24 0x0044a1e0 in Mirall::ownCloudGui::slotTrayClicked (this=0x5c5c9d8, reason=QSystemTrayIcon::Trigger) at /home/yxy/mirall/src/mirall/owncloudgui.cpp:156
#25 0x00468a50 in Mirall::ownCloudGui::qt_static_metacall (_o=0x5c5c9d8, _c=QMetaObject::InvokeMetaMethod, _id=14, _a=0x22dbe8) at /home/yxy/mirall-build/src/moc_owncloudgui.cpp:178
#26 0x669147e4 in ?? ()
#27 0x66514bd4 in ?? ()
#28 0x6652f856 in ?? ()
#29 0x77d18734 in ?? ()
#30 0x77d18816 in ?? ()
#31 0x77d28ea0 in ?? ()
#32 0x77d28eec in ?? ()
#33 0x7c92e453 in ?? ()
#34 0x77d19402 in ?? ()
#35 0x6693ebef in ?? ()
#36 0x05a6cd63 in ?? ()
#37 0x668ec418 in ?? ()
#38 0x668f3ae1 in ?? ()
#39 0x00401b47 in main (argc=1, argv=0x3e5e98) at /home/yxy/mirall/src/main.cpp:107

**Comment by dahan1999** [comment] 2015-01-22 00:52
I start a remote debug and found that segmentation fault occurs in Qt5Widgets.dll and there is only 1 item in the call stack.

**Comment by ogoffart** [comment] 2015-01-22 09:53
Thanks for your bug report.

This is a duplicate of https://github.com/owncloud/client/issues/2648

Because it has the same message:
```
QWindowsXPStylePrivate::buffer(w,h), failed to create dibsection ()
```

**Closed by ogoffart** 2015-01-22 09:53 UTC
