### ISSUE TITLE
Client leaks memory (Linux client)

### ISSUE THREAD

**Issue by FuturePilot** [owncloud/client#4929] opened 2016-05-31 19:53 UTC
### Expected behaviour
Tell us what should happen
Owncloud should not be leaking memory

### Actual behaviour
Tell us what happens instead
After a few hours the Owncloud client is using 1-2 GB of RAM

### Steps to reproduce
1. Start owncloud client
2. Wait
3. 

### Server configuration
Operating system:
Debian Stable 8.4

Web server: 
Apache 2.4.10

Database:
MySQL 5.6.30

PHP version:
PHP 5.6.20

ownCloud version:
9.0.2

Storage backend:

### Client configuration
Client version:
2.2.0

Operating system:
Kubuntu 16.04

OS language:
en_us

Installation path of client:
/usr/bin/

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

After just a few hours I noticed that owncloud was using 1.8 GB of RAM. Although I do have quite a few files and shares configured in the client this was never a problem before and not many files have been added recently prior to noticing this issue.

![screenshot_20160530_152922](https://cloud.githubusercontent.com/assets/4391536/15688479/4c31b688-2748-11e6-9557-0d996f0770dd.png)

**Comment by guruz** [comment] 2016-06-01 05:59
This should be fixed with 2.2.1rc1
https://owncloud.org/install/#testing-development

**Comment by FuturePilot** [comment] 2016-06-01 19:15
This still seems to be a problem with 2.2.1rc1. Though it seems to leak at a slower rate it is still leaking memory.

**Comment by guruz** [comment] 2016-06-02 05:17
Do you have absolute numbers for this or even a graph?
Over which time?
What / how much are you syncing?
Then we can have a look :)

**Comment by FuturePilot** [comment] 2016-06-03 02:14
It started around 30 or 40 MB and has steadily been increasing. I've tracked it for around 7 hours now and it's currently at 265 MB and it doesn't show any signs of leveling off. See graph I made below.

I have 14 sync connections configured totaling 23,645 files and 381 directories. The majority of these files are < 1MB

![owncloud-memlog](https://cloud.githubusercontent.com/assets/4391536/15766629/a2d7532c-290e-11e6-9079-80ebe9329fd9.png)

**Comment by danimo** [comment] 2016-06-03 02:19
Could you install the debug packages and run memcheck on the process?

**Comment by FuturePilot** [comment] 2016-06-03 02:25
Are there debug packages for Ubuntu? I don't see any in the owncloud repo.

**Comment by guruz** [comment] 2016-06-03 05:56
@jnweiger Maybe you can help quickly

**Comment by ckamm** [comment] 2016-06-23 10:31
@FuturePilot We've used various memory checkers and profilers locally but can't reproduce the problem. If we knew what caused this issue, it might be an easy fix. Would you be up for compiling the client manually and running a heap profiler on it? 

Basic instructions for compiling are at https://doc.owncloud.org/desktop/2.2/building.html . Ping me if you need help.

**Comment by FuturePilot** [comment] 2016-07-08 14:56
Just ack'ing this. I haven't had time to get around to this yet.

**Comment by ogoffart** [comment] 2016-08-03 13:30
the 2.2.3beta is released and has some memory improvement. Altough i don't remember if any leak was fixed.

**Comment by FuturePilot** [comment] 2016-08-12 03:30
2.2.3 seems to be a huge improvement. Though it still seems to be leaking somewhere. But it's not a constant leak like before. It will stay stable ~45-55MB until a sync takes place then it increases a few MB but doesn't seem to release that memory. After several syncs it can be back up in the hundreds of MBs. Prior to 2.2.3 it would leak regardless of whether there were any files being synced or not.

**Comment by guruz** [comment] 2016-08-16 17:04
Awesome :-) Thanks for testing and thanks for @jturcotte @ckamm @ogoffart for fixing..

**Closed by guruz** 2016-08-16 17:04 UTC
Labels: Needs info

**Comment by FuturePilot** [comment] 2016-08-16 18:51
Actually it's much better than what I said in my previous comment. After doing more testing, the memory usage has been very consistent staying around 65 MB. I've seen it go up but it will come back down. I'd say this is completely fixed. Thanks everyone!
