### ISSUE TITLE
Server Activity should match the other tabs

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7619] opened 2019-12-02 13:52 UTC
https://github.com/owncloud/client/issues/6728#issuecomment-432401762

Enhancements in Server Activity tab:

1. Proper columns and headers
2. Option to resize column width
3. Option to filter by account

**Comment by TheOneRing** [comment] 2020-03-16 15:01
@HanaGemela is this still an issue?

**Comment by HanaGemela** [comment] 2020-03-16 16:22
Yes

**Comment by TheOneRing** [comment] 2020-03-17 11:32
Duplicate of https://github.com/owncloud/client/issues/4350

**Closed by TheOneRing** 2020-03-17 11:32 UTC
Labels: Design & UX, Enhancement
