### ISSUE TITLE
Virtual filesystem does not rename file after download - file unavailable

### ISSUE THREAD

**Issue by lbayerlein** [owncloud/client#7231] opened 2019-06-07 08:51 UTC
### Expected behaviour
Double klick on file (or download via submenu) on the MAC downloads it and opens in the application. For example double klick a doc file opens it in Word.

### Actual behaviour
The owncloud client downloads it successfully. This is documented in the activity tab of the owncloud client itself. In the filesystem, there is still the .owncloud file extension and the size of 1B. I am unable to open the file, because it is "empty".

### Steps to reproduce
1. Install owncloud client in stable or unstable
2. Create a virtual filesystem
3. Open a file with double klick

It is not reproducable on every machine. But on one machine, this happens.

### Server configuration
Operating system: CentOS 7 actual patch level

Web server: apache 2.4

Database: mariadb

PHP version: 7.2

ownCloud version: 10.1.1.1

Storage backend (external storage): none

### Client configuration
Client version: macOS Mohave

Operating system: macOS

OS language: german

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: default

### Logs
I will post it as soon as possible

**Comment by ckamm** [comment] 2019-06-11 08:47
@lbayerlein Which client version were you using? Logs would be very helpful! https://doc.owncloud.org/desktop/2.5/troubleshooting.html#obtaining-the-client-log-file

**Comment by lbayerlein** [comment] 2019-06-11 09:18
Hi @ckamm 
we are using the actual stable for mac - downloaded last week (2.5.4).
What information do you need? I've got a log with about 330k lines.

```
06-07 10:56:53:757 [ info gui.application ]:    "################## ownCloud locale:[de_DE] ui_lang:[] version:[2.5.4 (build 11456)] os:[macOS Mojave (10.14)]"                                                                               06-07 10:56:53:757 [ info gui.application ]:    Using "de_DE" translation                                                                                                                                                                     
06-07 10:56:53:816 [ info gui.socketapi ]:  server started, listening at  "4AP2STM4H5.com.owncloud.desktopclient.socketApi"                                                                                                                   
06-07 10:56:53:816 [ info gui.folder.manager ]: setting remote poll timer interval to 30000 msec                                                                                                                                              06-07 10:56:54:477 [ info gui.account.manager ]:    Account for QUrl("https://cloud.mydomain.org") using auth type "http"                                                                                                                     
06-07 10:56:54:683 [ info gui.application ]:    Tray menu workarounds: noabouttoshow: true fakedoubleclick: false showhide: false manualvisibility: true                                                                                      06-07 10:56:54:711 [ info gui.folder.manager ]: Setup folders from settings file                                                                                                                                                              
06-07 10:56:54:711 [ info sync.configfile ]:    Adding system ignore list to csync: "/Applications/owncloud.app/Contents/Resources/sync-exclude.lst"                                                                                          
06-07 10:56:54:715 [ info gui.folder.manager ]: Adding folder to Folder Map  OCC::Folder(0x7f8c680c7800) "1"                                                                                                                                  06-07 10:56:54:716 [ info gui.folder.manager ]: Schedule folder  "1"  to sync!                                                                                                                                                                
06-07 10:56:54:716 [ info gui.folder.manager ]: Folder is not ready to sync, not scheduled!                                                                                                                                                   06-07 10:56:54:717 [ info gui.application ]:    Sync state changed for folder  "https://cloud.mydomain.org/remote.php/webdav/" :  "Not yet Started"                                                                                           06-07 10:56:54:889 [ info sync.database ]:  sqlite3 version "3.26.0"                                                                                                                                                                          06-07 10:56:54:889 [ info sync.database ]:  sqlite3 locking_mode= "exclusive"                                                                                                                                                                 06-07 10:56:54:889 [ info sync.database ]:  sqlite3 journal_mode= "wal"                                                                                                                                                                       06-07 10:56:54:893 [ info sync.clientproxy ]:   Set proxy configuration to use system configuration                                                                                                                                           
06-07 10:56:55:112 [ info gui.account.state ]:  Fetched credentials for "https://cloud.mydomain.org" attempting to connect                                                                                                                    06-07 10:56:55:120 [ info sync.connectionvalidator ]:   No system proxy set by OS                                                                                                                                                             
06-07 10:56:55:120 [ info sync.accessmanager ]: 2 "" "https://cloud.mydomain.org/status.php" has X-Request-ID "908cae04-ed18-405a-b0bb-099e9bebc224"                                                                                          06-07 10:56:55:121 [ info sync.networkjob ]:    OCC::CheckServerJob created for "https://cloud.mydomain.org" + "status.php" "OCC::ConnectionValidator"                                                                                        06-07 10:56:55:202 [ info gui.socketapi ]:  New connection SocketApiSocket(0x7f8c6aa3f8f0)                                                                                                                                                    06-07 10:56:55:203 [ info gui.socketapi ]:  Received SocketAPI message <-- "GET_STRINGS:" from SocketApiSocket(0x7f8c6aa3f8f0)                                                                                                                06-07 10:56:55:203 [ info gui.socketapi ]:  Sending SocketAPI message --> "GET_STRINGS:BEGIN" to SocketApiSocket(0x7f8c6aa3f8f0)                                                                                                              06-07 10:56:55:203 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING:SHARE_MENU_TITLE:Teilen…" to SocketApiSocket(0x7f8c6aa3f8f0)                                                                                                06-07 10:56:55:204 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING:CONTEXT_MENU_TITLE:ownCloud" to SocketApiSocket(0x7f8c6aa3f8f0)                                                                                             06-07 10:56:55:205 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING:COPY_PRIVATE_LINK_MENU_TITLE:Privater Link in die Zwischenablage kopiert" to SocketApiSocket(0x7f8c6aa3f8f0)                                                06-07 10:56:55:205 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING:EMAIL_PRIVATE_LINK_MENU_TITLE:Sende privaten Link per Email..." to SocketApiSocket(0x7f8c6aa3f8f0)                                                          06-07 10:56:55:206 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING::" to SocketApiSocket(0x7f8c6aa3f8f0)                                                                                                                       
06-07 10:56:55:207 [ info gui.socketapi ]:  Sending SocketAPI message --> "GET_STRINGS:END" to SocketApiSocket(0x7f8c6aa3f8f0)                                                                                                                06-07 10:56:55:268 [ info gui.socketapi ]:  New connection SocketApiSocket(0x7f8c6771c1d0)                                                                                                                                                    06-07 10:56:55:269 [ info gui.socketapi ]:  Received SocketAPI message <-- "GET_STRINGS:" from SocketApiSocket(0x7f8c6771c1d0)                                                                                                                06-07 10:56:55:269 [ info gui.socketapi ]:  Sending SocketAPI message --> "GET_STRINGS:BEGIN" to SocketApiSocket(0x7f8c6771c1d0)                                                                                                              06-07 10:56:55:270 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING:SHARE_MENU_TITLE:Teilen…" to SocketApiSocket(0x7f8c6771c1d0)                                                                                                06-07 10:56:55:271 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING:CONTEXT_MENU_TITLE:ownCloud" to SocketApiSocket(0x7f8c6771c1d0)                                                                                             
06-07 10:56:55:271 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING:COPY_PRIVATE_LINK_MENU_TITLE:Privater Link in die Zwischenablage kopiert" to SocketApiSocket(0x7f8c6771c1d0)                                                06-07 10:56:55:272 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING:EMAIL_PRIVATE_LINK_MENU_TITLE:Sende privaten Link per Email..." to SocketApiSocket(0x7f8c6771c1d0)                                                          06-07 10:56:55:272 [ info gui.socketapi ]:  Sending SocketAPI message --> "STRING::" to SocketApiSocket(0x7f8c6771c1d0)                                                                                                                       06-07 10:56:55:273 [ info gui.socketapi ]:  Sending SocketAPI message --> "GET_STRINGS:END" to SocketApiSocket(0x7f8c6771c1d0)                                                                                                                06-07 10:56:55:478 [ info sync.networkjob.checkserver ]:    status.php returns:  QJsonDocument({"edition":"Community","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"","version":"10.1.1.1","versionstring":"10.1.1"})   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x7f8c6aa2bc90)                                                                                                                                                                  06-07 10:56:55:478 [ info sync.connectionvalidator ]:   ** Application: ownCloud found:  QUrl("https://cloud.mydomain.org")  with version  "10.1.1" ( "10.1.1.1-" )                                                                           06-07 10:56:55:478 [ info sync.connectionvalidator ]:   QUrl("https://cloud.mydomain.org") has server version "10.1.1.1-"                                                                                                                     06-07 10:56:55:478 [ info sync.accessmanager ]: 6 "PROPFIND" "https://cloud.mydomain.org/remote.php/webdav/" has X-Request-ID "20980dd3-6161-4ef3-b213-d9d3d2c01eee"                                                                          06-07 10:56:55:478 [ info sync.networkjob ]:    OCC::PropfindJob created for "https://cloud.mydomain.org" + "/" "OCC::ConnectionValidator"                                                                                                    06-07 10:56:55:597 [ info sync.networkjob.propfind ]:   PROPFIND of QUrl("https://cloud.mydomain.org/remote.php/webdav/") FINISHED WITH STATUS "OK"                                                                                           06-07 10:56:55:597 [ info sync.accessmanager ]: 2 "" "https://cloud.mydomain.org/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "0e61f391-c6d0-4ff5-a7d8-f98bae9b9867"                                                           06-07 10:56:55:598 [ info sync.networkjob ]:    OCC::JsonApiJob created for "https://cloud.mydomain.org" + "ocs/v1.php/cloud/capabilities" "OCC::ConnectionValidator"                                                                         06-07 10:56:55:598 [ info sync.accessmanager ]: 2 "" "https://cloud.mydomain.org/ocs/v1.php/config?format=json" has X-Request-ID "6ae4c0fe-3663-4544-b63b-8511897e6652"                                                                       06-07 10:56:55:598 [ info sync.networkjob ]:    OCC::JsonApiJob created for "https://cloud.mydomain.org" + "ocs/v1.php/config" ""                                                                                                             06-07 10:56:55:711 [ info sync.networkjob.jsonapi ]:    JsonApiJob of QUrl("https://cloud.mydomain.org/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS "OK"                                                                  
```
This information of the logs, that are not synced correctly:
```
06-07 10:57:41:315 [ info sync.csync.updater ]: file: Katalogbeileger 2018, instruction: INSTRUCTION_EVAL <<=                                                                                       06-07 10:57:41:315 [ info sync.accessmanager ]: 6 "PROPFIND" "https://cloud.mydomain.org/remote.php/dav/files/user/Katalogbeileger 2018" has X-Request-ID "7ea2f712-c4b0-4226-9a54-3579b67833f5" 06-07 10:57:41:316 [ info sync.networkjob ]:    OCC::LsColJob created for "https://cloud.mydomain.org" + "/Katalogbeileger 2018" "OCC::DiscoverySingleDirectoryJob"                                 06-07 10:57:41:574 [ info sync.networkjob.lscol ]:  LSCOL of QUrl("https://cloud.mydomain.org/remote.php/dav/files/user/Katalogbeileger 2018") FINISHED WITH STATUS "OK"                         06-07 10:57:41:575 [ info sync.csync.updater ]: Katalogbeileger 2018/.DS_Store excluded  (2)                                                                                                        06-07 10:57:41:575 [ info sync.csync.updater ]: Checking for rename based on fileid 00124270oc948c3hbbu4                                                                                                                                      
06-07 10:57:41:575 [ info sync.csync.updater ]: remote rename detected based on fileid Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud --> Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud                                                                                                                                                                                         06-07 10:57:41:575 [ info sync.csync.updater ]: file: 180628 Artikelliste Neuheiten Katalog.xlsx.owncloud, instruction: INSTRUCTION_EVAL_RENAME <<=                            06-07 10:57:41:575 [ info sync.csync.updater ]: Database entry found, compare: 1558025085 <-> 1558025085, etag: 43675d269e5e4976a80670251099ca24 <-> 43675d269e5e4976a80670251099ca24, inode: 0 <-> 17295177, size: 35840 <-> 35840, perms: 19f <-> 19f, type: 4 <-> 4, checksum: SHA1:ebdc0465c7324dd3f7f9b6b8f976ecf29980f040 <-> , ignore: 0                                                                                                                                             06-07 10:57:41:575 [ info sync.csync.updater ]: file: Seitenplan Neuheiten_Beileger für Katalog 2018.doc.owncloud, instruction: INSTRUCTION_NONE <<=                           06-07 10:57:41:575 [ info sync.csync.updater ]:  <= Closing walk for Katalogbeileger 2018 with read_from_db 0                                                                                       06-07 10:57:41:575 [ info sync.csync.updater ]: Database entry found, compare: 1558358419 <-> 1558358419, etag: 5ce2a9aa9e261 <-> 5ce2a9aa9e261, inode: 0 <-> 17112354, size: 0 <-> 0, perms: 1fd <-> 1fd, type: 2 <-> 2, checksum:  <-> , ignore: 0                               
```
Thanks for your support

**Comment by ckamm** [comment] 2019-06-11 13:19
@lbayerlein Thanks for the log excerpt. It looks like the db marker for the file isn't set properly. Could you email me the full log at mail at ckamm de?

There have also been some fixes to vfs for 2.5.5 already - maybe you'd be up for trying one of the snapshot builds? From http://download.owncloud.com/desktop/daily/, like http://download.owncloud.com/desktop/daily/ownCloud-2.5.5.11903-daily20190611.pkg .

**Comment by ckamm** [comment] 2019-06-11 13:33
(the PR sanitizes an issue I found but shouldn't address the problem you're seeing)

**Comment by lbayerlein** [comment] 2019-06-11 13:55
@ckamm Unfortunately there is productive data in it, that I am not allowed to publish. If I anonymize the data, would it be helpfull, too?

Should I uninstall the ownCloud client or should I simply install the daily snapshot over it? Would it be better, if I install the ownCloud technic preview, or should I stay on the daily snapshot?

Thanks for your support :)

**Comment by ckamm** [comment] 2019-06-11 14:45
Ah, understood. 

What I'm particularly interested in is the messages after the line with "Download virtual file:". That's where the change to the database should have happened. Any other messages that contain the filename are also potentially relevant.

If you don't want to disrupt your existing setup you can download the installer for the "testcloud" edition - that will install in parallel and use a separate settings folder. Only replace your main client if you're ok using pre-release software. (though in my opinion 2.5.5 is safe, it only has bugfixes over 2.5.4)

**Comment by lbayerlein** [comment] 2019-06-11 15:06
Okay I have found this for "Download virtual file":
```
06-07 10:57:28:123 [ info gui.folder ]: Download virtual file:  "Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud"                                                         06-07 10:57:28:123 [ info sync.database ]:  Updating file record for path: "Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" inode: 17295176 modtime: 1558025085 type: 5 etag: "27b2a4c78848edc7186a3ca42bbcda1c" fileId: "00124270oc948c3hbbu4" remotePerm: "WDNVRS" fileSize: 36130 checksum: "SHA1:db428da7d63ec796a32772794d4900643f5116f5"                                                                        06-07 10:57:28:268 [ info gui.folder.manager ]: Schedule folder  "1"  to sync!                                                                                                                                                               06-07 10:57:28:268 [ info gui.application ]:    Sync state changed for folder  "https://cloud.mydomain.org/remote.php/dav/files/user/" :  "Not yet Started"                                                                    06-07 10:57:28:269 [ info sync.accessmanager ]: 2 "" "https://cloud.mydomain.org/ocs/v2.php/apps/notifications/api/v1/notifications?format=json" has X-Request-ID "88733743-34ac-47ef-a03b-73fe234a8f0f"                          06-07 10:57:28:269 [ info sync.networkjob ]:    OCC::JsonApiJob created for "https://cloud.mydomain.org" + "ocs/v2.php/apps/notifications/api/v1/notifications" "OCC::ServerNotificationHandler"                                  06-07 10:57:28:277 [ info sync.accessmanager ]: 6 "PROPFIND" "https://cloud.mydomain.org/remote.php/dav/files/user/" has X-Request-ID "ad3aefd5-2b1d-4eb7-9272-e83842e77021"                                                   06-07 10:57:28:277 [ info sync.networkjob ]:    OCC::PropfindJob created for "https://cloud.mydomain.org" + "/" "OCC::ConnectionValidator"
```
And this for do a "grep" for the file itself:

```
06-07 10:56:56:311 [ info gui.socketapi ]:  Received SocketAPI message <-- "RETRIEVE_FILE_STATUS:/Users/user/ownCloud/Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" from SocketApiSocket(0x7f8c6771c1d0)         06-07 10:56:56:311 [ info gui.socketapi ]:  Sending SocketAPI message --> "STATUS:OK+SWM:/Users/user/ownCloud/Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" to SocketApiSocket(0x7f8c6771c1d0)                   
06-07 10:57:03:278 [ info sync.csync.updater ]: 1 entries read below path Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud from db.                                                                                  06-07 10:57:07:548 [ info sync.csync.updater ]: 1 entries read below path Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud from db.                                                                                  
06-07 10:57:15:098 [ info gui.socketapi ]:  Received SocketAPI message <-- "RETRIEVE_FILE_STATUS:/Users/user/ownCloud/Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" from SocketApiSocket(0x7f8c6771c1d0)         
06-07 10:57:15:103 [ info gui.socketapi ]:  Sending SocketAPI message --> "STATUS:OK+SWM:/Users/user/ownCloud/Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" to SocketApiSocket(0x7f8c6771c1d0)                   
06-07 10:57:16:509 [ info gui.socketapi ]:  Received SocketAPI message <-- "GET_MENU_ITEMS:/Users/user/ownCloud/Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" from SocketApiSocket(0x7f8c6771c1d0)               
06-07 10:57:19:754 [ info gui.socketapi ]:  Received SocketAPI message <-- "GET_MENU_ITEMS:/Users/user/ownCloud/Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" from SocketApiSocket(0x7f8c6771c1d0)               
06-07 10:57:21:685 [ info gui.socketapi ]:  Received SocketAPI message <-- "GET_MENU_ITEMS:/Users/user/ownCloud/Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" from SocketApiSocket(0x7f8c6771c1d0)               
06-07 10:57:28:122 [ info gui.socketapi ]:  Received SocketAPI message <-- "DOWNLOAD_VIRTUAL_FILE:/Users/user/ownCloud/Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" from SocketApiSocket(0x7f8c6771c1d0)        
06-07 10:57:28:123 [ info gui.folder ]: Download virtual file:  "Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud"                                                                                                   06-07 10:57:28:123 [ info sync.database ]:  Updating file record for path: "Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud" inode: 17295176 modtime: 1558025085 type: 5 etag: "27b2a4c78848edc7186a3ca42bbcda1c" fileId: "00124270oc948c3hbbu4" remotePerm: "WDNVRS" fileSize: 36130 checksum: "SHA1:db428da7d63ec796a32772794d4900643f5116f5"                                                                                                                  06-07 10:57:41:575 [ info sync.csync.updater ]: remote rename detected based on fileid Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud --> Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud 06-07 10:57:41:575 [ info sync.csync.updater ]: file: Katalogbeileger 2018/180628 Artikelliste Neuheiten Katalog.xlsx.owncloud, instruction: INSTRUCTION_EVAL_RENAME <<=                                                                                                                                                                                          ```

**Comment by ckamm** [comment] 2019-06-12 11:02
@lbayerlein Thanks.

This shows that at `06-07 10:57:28:123` the right thing (type: 5) was written to the database. But when it's read from the database at `06-07 10:57:41:575` it seems to see type: 4 instead.

I don't see how that would happen.

**Comment by lbayerlein** [comment] 2019-06-12 12:18
@ckamm you are very welcome

How can I solve this behaviour? If I do a rename in the webinterface, it should be synced to, shouldn't it? 

But this would be a workaround. Maybe I can provide further informations? How can be detected, how this can happen?

Thanks in advance

**Comment by ckamm** [comment] 2019-06-14 13:08
@lbayerlein Is this a permanent failure? Double-clicking it again or choosing ownCloud->Download file in the context menu doesn't trigger a download even on a second attempt?

Renames on the server wouldn't trigger a local download, just a rename of the local placeholder file. Disabling the vfs feature may be a workaround - worst case you may need to re-setup the folder without vfs. (it's an experimental feature for a reason)

I'd be interested to hear whether you can reproduce the problem with the 2.5.5 dailies. There are also significant improvements to vfs and the sync discovery algorithm in 2.6.0 which you may want to try.

**Comment by lbayerlein** [comment] 2019-06-14 13:30
@ckamm yes unfortunately it was. I looked on the system again and it is gone :( Every seems to stay in sync now and looks good. But I can't tell, when it was fixed.

On a 8 terabyte of data, turn off and on again is not that easy. And yes, I am with you regarding the experimental feature. This was a well discussed decition and it works pretty good.

Yesterday, I tried to install the 2.5.5 daily on windows. Unfortunately I got multiple qt5 errors and I don't know why.

Now should we close because of missing testing options or can I provide more informations?

**Comment by ckamm** [comment] 2019-06-14 13:48
@lbayerlein I don't know what information you could provide unfortunately. The log excerps you've shown paint an impossible situation: writes to the db should always produce a `Updating file record for path` log entry. We see the "download requested" file getting a please-download tag. But the follow-up log messages would only be seen if the file didn't have the tag at all.

Furthermore the code is entirely different for 2.6.0, making it less useful to search for the mystery bug in the old implementation. I'd say we close this - feel free to reopen if you see the issue again with 2.6.0 or have new information!

**Closed by ckamm** 2019-06-14 13:48 UTC
Labels: Needs info, OSX, Virtual Files
