### ISSUE TITLE
selective sync status lost when local sync storage insufficient

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5357] opened 2016-12-06 10:21 UTC
I noticed at several occasions that a folder which is deselected from synchronization suddenly starts synchronizing. I now think it correlates with a situation when the sync client stops because of insufficient local disk space ("Only 0B are available, need at least 48MB to start").

Could it be that blacklisting table is not sufficiently protected in sqlite update when disk becomes full and it gets erased (effectively removing blacklisted entries)?

Of course in this particular case I remove folder from sync because of space issues. This bug causes the client to download even more stuff locally and make the local space situation even worse.

**Comment by moscicki** [comment] 2016-12-07 08:09
I can confirm that when disk space runs out the sqlite db becomes inconsistent (at least for selective sync but also maybe for other tables, this needs to be checked).

This query returns an empty set -- the tmp folder was removed from the table:

     sqlite> select * from selectivesync;

On top of it, the UI is inconsistent as well, because it shows wrong status for tmp:

![image](https://cloud.githubusercontent.com/assets/621965/20959705/afcb47f0-bc5c-11e6-90cc-8a0cdc48c89e.png)

**Comment by moscicki** [comment] 2016-12-07 08:10
The original state of the table was:

    sqlite> select * from selectivesync;
    tmp/|1

**Comment by guruz** [comment] 2016-12-07 13:29
Please note that the default sqlite shipped on OS X sometimes can't read our tables because we use our own version of sqlite shipped with the client.

What I don't understand: If there is still 48 MB free, how can it not save the DB? You mean because another process is filling the hd even more?

FYI @ogoffart

**Comment by moscicki** [comment] 2016-12-07 15:53
I think that this is not a problem of default sqlite from OS in my case. It can read it correctly and normally I do see the content of the table. But when this bug happens then the contents of the table is gone.

Yes, in my current setup I am very tight with the space and Chrome will eat the rest of the disk for caches. 

I think that somewhere the sqlite update is not sufficiently protected (at least for this table). It would be good to find out what is the origin of this problem to make sure it does not impact the metadata table.

I will check next time if other tables are affected.

**Comment by moscicki** [comment] 2016-12-08 08:00
I can confirm that the other tables seem fine, only the selective sync table is erased:

Normally:
```

select count(*) from blacklist;
0
select count(*) from downloadinfo;
0
select count(*) from poll;
0
select count(*) from uploadinfo;
0
select count(*) from checksumtype;
1
select count(*) from metadata;
10394
select count(*) from selectivesync;
1
select count(*) from version;
1

```
When space ran out, the client stopped, I freed some disk and the client started downloading the folder previously disabled from sync (selectivesync table).

```
select count(*) from blacklist;
1
select count(*) from downloadinfo;
1
select count(*) from poll;
0
select count(*) from uploadinfo;
0
select count(*) from checksumtype;
1
select count(*) from metadata;
10494
select count(*) from selectivesync;
0
select count(*) from version;
1

```

**Comment by ogoffart** [comment] 2016-12-08 11:26
when the selective sync is modified, we do
 1- DELETE all the entries that are in the database
 2- loop over each entry and INSERT it.

It is possible that the call to DELETE succeed, and the calls to INSERT fails.
Do you see error messages such as `SQL error when inserting into selective sync` in the log?

**Comment by moscicki** [comment] 2016-12-08 13:30
I tried to trigger this on purpose by filling the disk but it is not reproducible. 

Let's wait when this happens again. However, the problem may be that log files are wirtten to the same partition, so when it gets full it could be likely that they do are properly written either. 

If I open logwindow with F12 -- would it rotate the log in memory or would it consume all available memory after a longer while?

**Comment by ogoffart** [comment] 2016-12-08 14:18
> If I open logwindow with F12 -- would it rotate the log in memory or would it consume all available memory after a longer while?

It rotates (there is a limits the amount of lines.)

**Comment by moscicki** [comment] 2016-12-10 07:39
The database file is completely lost and the selectivesync information with it:

```
12-10 08:23:10:325 0x7ff8d9542f60 OCC::FolderMan::slotFolderSyncStarted: >===================================== sync started for  "https://example.org/mybox/desktop/remote.php/webdav/read-only-share"
12-10 08:23:10:330 0x7ff8d9542f60 OCC::SqlQuery::prepare: Sqlite prepare statement error: "unable to open database file" in "PRAGMA quick_check;"
12-10 08:23:10:331 0x7ff8d9542f60 OCC::SqlDatabase::checkDb: quick_check returned failure: ""
12-10 08:23:10:331 0x7ff8d9542f60 OCC::SqlDatabase::openOrCreateReadWrite: Consistency check failed, removing broken db "/Users/x/mybox.shares/mybox-read-only-share/.csync_journal.db"
12-10 08:23:10:482 0x7ff8d9542f60 OCC::SqlDatabase::openHelper: Error: "unable to open database file" for "/Users/x/mybox.shares/mybox-read-only-share/.csync_journal.db"
12-10 08:23:10:482 0x7ff8d9542f60 OCC::SyncJournalDb::checkConnect: Error opening the db:  "unable to open database file"
12-10 08:23:10:483 0x7ff8d9542f60 OCC::SyncEngine::startSync: There are 0 bytes available at "/Users/x/mybox.shares/mybox-read-only-share/" and at least 50000000 are required
12-10 08:23:10:483 0x7ff8d9542f60 OCC::SyncJournalDb::close: void OCC::SyncJournalDb::close() "/Users/x/mybox.shares/mybox-read-only-share/.csync_journal.db"
12-10 08:23:10:484 0x7ff8d9542f60 OCC::SyncJournalDb::commitTransaction: No database Transaction to commit
12-10 08:23:10:484 0x7ff8d9542f60 OCC::SyncEngine::finalize: CSync run took  0
12-10 08:23:10:485 0x7ff8d9542f60 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/x/mybox.shares/mybox-read-only-share/"
12-10 08:23:10:492 0x7ff8d9542f60 OCC::Folder::slotSyncFinished:  - client version 2.2.4 (build 1495)  Qt 5.4.0  SSL  OpenSSL 1.0.2h  3 May 2016
12-10 08:23:10:492 0x7ff8d9542f60 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
12-10 08:23:10:575 0x7ff8d9542f60 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  81  Milliseconds.
12-10 08:23:10:576 0x7ff8d9542f60 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  2
12-10 08:23:10:576 0x7ff8d9542f60 OCC::Folder::slotSyncFinished:   ** error Strings:  ("Only 0 B are available, need at least 48 MB to start")
12-10 08:23:10:577 0x7ff8d9542f60 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
12-10 08:23:10:577 0x7ff8d9542f60 OCC::Folder::slotSyncFinished: the last 2 syncs failed
12-10 08:23:10:577 0x7ff8d9542f60 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/x/mybox.shares/mybox-read-only-share"
12-10 08:23:10:578 0x7ff8d9542f60 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:/Users/x/mybox.shares/mybox-read-only-share"
12-10 08:23:10:581 0x7ff8d9542f60 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "https://example.org/mybox/desktop/remote.php/webdav/read-only-share" :  "Error"
12-10 08:23:10:804 0x7ff8d9542f60 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "https://example.org/mybox/desktop/remote.php/webdav/read-only-share"
12-10 08:23:22:287 0x7ff8d9542f60 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
12-10 08:23:22:287 0x7ff8d9542f60 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.org/mybox/desktop" + "/" "OCC::ConnectionValidator"
12-10 08:23:54:286 0x7ff8d9542f60 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
12-10 08:23:54:287 0x7ff8d9542f60 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.org/mybox/desktop" + "/" "OCC::ConnectionValidator"
```

The db file is recreated new:
```
select count(*) from blacklist;
0
select count(*) from downloadinfo;
0
select count(*) from poll;
0
select count(*) from uploadinfo;
0
select count(*) from checksumtype;
0
select count(*) from metadata;
0
select count(*) from selectivesync;
0
select count(*) from version;
1
```

The client rediscovers the whole remote tree and begins downloading the previously blacklisted folders.

**Comment by ckamm** [comment] 2016-12-13 12:15
@moscicki That looks bad. Maybe we can avoid db operations when disk space is that low, or at least move the disk space check before the db operations.

**Comment by ckamm** [comment] 2016-12-13 12:33
Maybe the problem is that we use WAL for the sqlite database and WAL doesn't support read-only databases. So when there's no more space on the device, opening the database might fail - and then we recreate it from scratch because we think it's broken?

**Comment by ckamm** [comment] 2016-12-13 12:59
@moscicki Would you be up for testing whether https://github.com/ckamm/owncloud-client/commit/9e82c88e658212c81469a59fa07c55c3557a77d7 already helps? If it makes it easier for you, I'd also be ok with merging this into master for testing since it only affects a rare edge case.

**Comment by ckamm** [comment] 2016-12-20 08:35
@moscicki I've merged the experimental fix to master, please test!

**Comment by ckamm** [comment] 2016-12-21 09:48
I've tested this by creating a ramdisk, adding a sync folder to it, quitting the client, filling up the disk space. The current behavior is that I get a crash:
```
12-21 10:47:43:963 17309 OCC::SqlQuery::prepare: Sqlite prepare statement error: "disk I/O error" in "PRAGMA quick_check;"
12-21 10:47:43:963 17309 unknown: ASSERT: "!"SQLITE Prepare error"" in file /home/kamm/dev/woboq/mirall/mirall/src/libsync/ownsql.cpp, line 224
```
with master.

**Comment by ckamm** [comment] 2016-12-21 10:10
Pull request fixing the assert error when disk space is low: https://github.com/owncloud/client/pull/5405

**Comment by guruz** [comment] 2016-12-21 13:55
@ckamm btw we don't crash in release mode. (which is bad IMHO).

**Comment by ckamm** [comment] 2017-01-03 09:44
@ogoffart See @guruz's comment above - was not crashing in release mode intentional for some reason?

**Comment by jturcotte** [comment] 2017-01-03 15:18
Why not try to recover or raise a fatal error to the user instead of using asserts? Asserts are a developper tool, not a replacement for exceptions.

**Comment by guruz** [comment] 2017-01-03 15:51
@jturcotte Agreed, the user visible error is in the patch above -> https://github.com/owncloud/client/commit/6835429a28996239c0cac29f751a9a5a271cceaa
The assert is just what @ckamm had seen previously.
And @moscicki would have seen the assert instead of myserterious behaviour if we have had https://github.com/owncloud/client/pull/5425 already..

**Comment by jturcotte** [comment] 2017-01-03 16:01
Alright, then we don't need to enable asserts in release, no? The problem is that this will impact users, it will result in crashes where not needed, increase the risk of entering inconsistent states, and all this with no benefits for users.

They haven't signed-up for beta testing and we shouldn't use them as a way to report potential issues by causing an actual crash.

**Comment by ckamm** [comment] 2017-01-04 13:57
@guruz @jturcotte Independently of enabling asserts in release builds, we agree that this specific case (sql prepare failing) should be a `qFatal`, correct?

**Comment by guruz** [comment] 2017-01-05 12:19
qFatal discussions in https://github.com/owncloud/client/issues/5429

**Comment by guruz** [comment] 2017-01-05 12:19
@moscicki Could you please help out testing this by trying the nightly build from today?

**Closed** 2017-01-25 18:07 UTC
Labels: bug, ReadyToTest, sev2-high

**Comment by moscicki** [comment] 2017-02-11 16:35
I haven't managed to test the new version. However, I managed to get a related problem (but not the same). When the 2.2.4 client ran out of disk space it ended up in the following state:

```
sqlite> select * from selectivesync;
tmp/|1
CS3Workshop2016/|1
CS3Workshop2016/|3
```

Note: there is a double entry for CS3Workshop with two different values. The net effect is now that checking and unchecking this folder on the gui does not make any difference (the folder is always reported as above 500) and when I check it to be synced it is reported back again on the client restart.

**Comment by moscicki** [comment] 2017-02-11 16:37
Actually, when I check the folder in for syncing the state becomes:

```
sqlite> select * from selectivesync;
tmp/|1
CS3Workshop2016/|2
```

**Comment by ogoffart** [comment] 2017-02-13 17:19
> CS3Workshop2016/|2

2 is the white list,  so it should be syncing, then.
