### ISSUE TITLE
Server activity tab - move activity missing

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7542] opened 2019-10-22 13:17 UTC
Server: 10.3.0 stable
Client: 2.6.0 rc2
Windows 10

Steps to recreate:
1. Create folders Documents/Empty and Photos/Empty2 
2. Run: move Documents/Empty ./ && move Photos/Empty2 ./ && move Documents Empty2/ && move Photos Empty/
3. Check the Server Activity tab

Expected result: Two entries - folders have been created and then moved
Actual result: Move is missing in Server Activity

<img width="882" alt="Screenshot 2019-10-22 at 14 43 00" src="https://user-images.githubusercontent.com/49001702/67289247-97e82000-f4de-11e9-96f0-be6a97ab6675.png">

**Comment by michaelstingl** [comment] 2019-10-23 08:29
> Actual result: Move is missing in Server Activity

Same in the web UI? I think this a known server limitation.

**Comment by ogoffart** [comment] 2019-10-23 13:12
Yeah, we just display what the server gives us. This should be moved to the server bug tracker, or closed as duplicate of there is already a server issue for it

**Comment by ogoffart** [comment] 2019-10-23 13:15
I've found the server issue: https://github.com/owncloud/activity/issues/375
Closing this one.

**Closed by ogoffart** 2019-10-23 13:15 UTC
Labels: Server Involved, bug, p3-medium
