### ISSUE TITLE
Allow to sync excluded sub folders 	separately

### ISSUE THREAD

**Issue by godfuture** [owncloud/client#2588] opened 2014-12-06 13:04 UTC
When a folder was exculded, it cant be synced as a new sync folder, because a parent is already in sync.

**Comment by MorrisJobke** [comment] 2015-08-15 13:17
cc @MTRichards @gig13 Because you requested this.

**Comment by bboule** [comment] 2016-01-05 16:41
@MorrisJobke @MTRichards Do we need to do anything with this? or can we simply close this out?

**Comment by MorrisJobke** [comment] 2016-01-05 17:30
I talked with @dragotin about this and he said, that there is a technical limitation for this and it's really hard to implement and nearly the whole sync algorithm needs to be redone to bring this feature in, which is a very special.

**Comment by MTRichards** [comment] 2016-01-05 18:03
This is by design as it works today, so not planning on updating this anytime soon.

**Comment by bboule** [comment] 2016-01-05 18:04
OK so it sounds like we can close this out as no action will be taken?

**Comment by MorrisJobke** [comment] 2016-01-06 06:57
> OK so it sounds like we can close this out as no action will be taken?

Correct.

**Comment by ogoffart** [comment] 2018-11-27 17:41
This is fixed in 2.5

**Closed by ogoffart** 2018-11-27 17:41 UTC
Labels: Feature
