### ISSUE TITLE
[Linux] File Watcher: Client does not error if inotify watches are exhausted

### ISSUE THREAD

**Issue by mscke** [owncloud/client#4107] opened 2015-11-10 13:42 UTC
Hi guys,

I've the fowlling problem my onwncloudClient on CentOS7 2.0.2 did not detect local changes on my filesystem. it's importent I sync over 200 000 files and 27000 Folders. I've found a solution. For the default settings of notifiyd is it not enough. I have these increased significantly now it is running smoothly again.
Unfortunately I can not say how many watches ownCloud actually needed. I took the number of directories plus the default value, but that is just a guess.

How can I calculate the notifyd max_user_watches for owncloudclient.
My system changes:

folders: 27176
defautl value: 8192

to test on a running system
echo 30368 > /proc/sys/fs/inotify/max_user_watches

to set in default after restart
vim /etc/sysctl.conf
fs.inotify.max_user_watches=30368

**Comment by danimo** [comment] 2015-11-10 14:02
We should not silently discard errors when setting up watches, but proactively offer to fix the offending parameters.

**Comment by guruz** [comment] 2016-01-04 12:03
@danimo has some WiP code for this.

**Comment by danimo** [comment] 2016-01-06 21:45
Workaround: Install a file called "100-owncloud-inotify.conf" in the packages. It should install to ``/etc/sysctl.d/`` and contain the following line:

 fs.inotify.max_user_watches = 524288

If someone hits that limit, there's not much we can do anyway.

@dragotin, @jnweiger please add that do the packages.

**Comment by dragotin** [comment] 2016-01-08 12:53
@danimo are you sure that is across all our supported platforms? my openSUSE TW has it tough.

**Comment by danimo** [comment] 2016-02-22 10:56
@dragotin Debian and Ubuntu have it, CentOS has it, so should Fedora.

**Comment by jnweiger** [comment] 2016-04-18 13:55
Defaults are low and inconsistent.

Mint:
> cat /proc/sys/fs/inotify/max_user_watches
> 8192

openSUSE-13.1::
> cat /proc/sys/fs/inotify/max_user_watches
> 65536

**Comment by jnweiger** [comment] 2016-04-18 20:56
Packaging draft submitted to isv:ownCloud:community:testing/owncloud-client

**Comment by jnweiger** [comment] 2016-04-18 21:51
@dragotin deploy for 2.2.0 (and 2.1.1 ?) when and where?

**Comment by dragotin** [comment] 2016-04-19 05:38
only 2.2.0 and ongoing. Old viking wisdom: Always work the direction where the arrows fly from ;-)

**Comment by dragotin** [comment] 2016-04-19 08:42
Confirmed: On openSUSE Leap (with updates) the file `/etc/sysctl.d/100-owncloud-inotify.conf` is existing.

Thanks.

**Comment by rldleblanc** [comment] 2016-05-20 18:45
install -m 0755 -D /usr/src/packages/SOURCES/100-owncloud-inotify.conf /home/rleblanc/code/owncloud-client-2.2.0/debian/owncloud-client/etc/sysconf.d/100-owncloud-inotify.conf
install: cannot stat '/usr/src/packages/SOURCES/100-owncloud-inotify.conf': No such file or directory
debian/rules:41: recipe for target 'override_dh_auto_install' failed
make[1]: *** [override_dh_auto_install] Error 1
make[1]: Leaving directory '/home/rleblanc/code/owncloud-client-2.2.0'
debian/rules:19: recipe for target 'binary' failed
make: *** [binary] Error 2

The file is not in either the original tar or the diff when downloaded from http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ using apt-get source owncloud-client. I'm trying to rebuild the package for Stretch since the name of the libssl package has changed.

I had to create /usr/src/packages/SOURCES/100-owncloud-inotify.conf as root with the contents specified above. The debian/rules also wanted to install the file at /etc/sysconf.d/ instead of /etc/sysctl.d/. I'm not sure why there are so many issues with this. I finally got it working, just wanted to submit my feedback.

**Comment by rldleblanc** [comment] 2016-06-09 17:42
I rebuilt 2.2.1 the same way as before and 100-owncloud-inotify.conf is still not in the Debian tarballs. In addition, now there is another 2 missing patch that I'll create an issue for (:sigh:). Why is '/usr/src/packages/SOURCES' even hard coded in debian/rules? This is not a good idea as users may not have the ability to write there.

**Comment by jnweiger** [comment] 2016-06-29 10:01
@rldleblanc hardcoded /usr/src/packages/SOURCE was an ugly hack, where series files failed for unknown reason. It is fixed in 2.2.3

I cannot find /etc/sysconf.d on any system. It should be be /etc/sysctl.d/ everywhere, not just on RPM systems. https://github.com/owncloud/administration/pull/87

**Comment by crrodriguez** [comment] 2016-08-18 05:31
It is my opinion that this problem should be documented ..If you do change the global max_user_watches.. you are putting user's systems  at risk nice D.o.S attack..that's why there is a low fixed size limit in the first place..  524288 watches will allow any app  (not just the owncloud client.. to use at least 512 MB of kernel memory...(if all watches are used of course)

**Comment by dragotin** [comment] 2021-08-19 07:23
There is a warning. Closing this as outdated.

**Closed by dragotin** 2021-08-19 07:23 UTC
Labels: Enhancement, packaging, p3-medium
