### ISSUE TITLE
Mac: Multiple password promts might block each other

### ISSUE THREAD

**Issue by bralandealmeida** [owncloud/client#8421] opened 2021-02-06 13:10 UTC
### Expected behaviour
Include the password or cancel the inclusion of the password in the dialog.

### Actual behaviour
I accidentally disconnected all my accounts from Owncloud Desktop, and when I open it again, it asks me to include the passwords for the accounts. However, it is not possible to type the password into the input or close the dialog that opens to enter the password. The application remains stuck on this screen without being able to take any action.

### Steps to reproduce
1. Disconnect all owncloud accounts
2. Open the owncloud app and try to include the account password

### Server configuration
Operating system:

### Client configuration
Client version: 2.7.5

Operating system:  MacOs Big Sur 11.1

OS language: Pt-br

Installation path of client: /Applications/owncloud

![image](https://user-images.githubusercontent.com/47180618/107119000-6cb84a00-6863-11eb-99b1-05d4b53f96a0.png)

**Comment by TheOneRing** [comment] 2021-02-08 09:54
Can be caused by selecting login in the system try, on multiple accounts.

**Comment by bralandealmeida** [comment] 2021-02-08 10:41
@TheOneRing The problem is that I'm stuck on that screen. I can't take any action no matter how much I restart the machine.

**Comment by TheOneRing** [comment] 2021-02-08 13:06
I prepared a fix for this issue in https://github.com/owncloud/client/pull/8422

Once it is merged, I'd recommend to use the 2.7 nightly.
A workaround would be to remove your configuration https://doc.owncloud.com/desktop/advanced_usage/configuration_file.html .

As 2.7 only receives fixes, it should be rather stable and using the nightly should be ok.

**Comment by bralandealmeida** [comment] 2021-02-08 22:29
Thank you. This solves the problem o/

**Comment by TheOneRing** [comment] 2021-03-01 13:37
Upstream issue: https://bugreports.qt.io/browse/QTBUG-91059

**Comment by TheOneRing** [comment] 2021-05-03 10:47
Adding a milestone to keep an eye on it and to keep the stale bot from closing it.

**Comment by TheOneRing** [comment] 2021-09-09 09:59
Fixed upstream https://bugreports.qt.io/browse/QTBUG-91059 2.9.1 will contain a backport

**Comment by TheOneRing** [comment] 2021-09-14 14:44
https://github.com/owncloud/client/commit/69e89e124fcccab48bbead9b087a4ebcce779db3

**Closed by TheOneRing** 2021-09-14 14:44 UTC
Labels: Upstream issue
