### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [owncloud/client#7095] opened 2019-03-16 13:43 UTC
Would you like to [wrap any pointer data members](https://github.com/owncloud/client/blob/421c0b447e4012750c5ecb006d20ebd8cc0c0ea1/src/gui/generalsettings.cpp#L123 "Update candidate: GeneralSettings class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")” (or “[QScopedPointer](https://doc.qt.io/qt-5/qscopedpointer.html#details "Description for the QScopedPointer class")”)?

**Comment by ogoffart** [comment] 2019-03-16 14:07
That would indeed make sense, to make the ownership more explicit.
(But we do not need exception safety because our code do not throw exceptions, and is not exception safe anyway. Qt itself is not)

**Comment by elfring** [comment] 2019-03-16 14:15
* How do you think about the possibility for an exception like “std::bad_alloc”?
* Would you like to [reconsider the resource management in affected source files](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”") once more?

**Comment by ogoffart** [comment] 2019-03-16 14:40
> How do you think about the possibility for an exception like “std::bad_alloc”?

This does not make sense in a GUI application. Because it is not possible to recover sanely for it, so terminating the app is the right option. Also because modern OS overcommit.  
If this happens because of a bug or a leak, one must fix this leak or bug.

> Would you like to reconsider the resource management in affected source files once more?

Sure, in new code, we try not to use raw delete / new. But this code is very old. (git blame tells this line you point out is 6 years old, but it may actually be even older than that)
I'd accept a pull request that changes this. 
But i'd still be careful trying to fix things that are not broken.

I am going to close this issue. This is not because the issue is invalid. But because this is a low priority for us and we will fix it as we refactor the code for other reason.

**Closed by ogoffart** 2019-03-16 14:40 UTC

**Comment by elfring** [comment] 2019-03-16 14:48
>This does not make sense in a GUI application.

Should the probability for the exception “std::bad_alloc” be taken better into account?


>Because it is not possible to recover sanely for it,

Such an error handling strategy might be too hard.


>so terminating the app is the right option.

I am unsure if the involved data structures will be still consistent for such an attempt.

**Comment by ogoffart** [comment] 2019-03-16 15:25
I'd like to point out that this is not relevant to the case in point, because doing the delete in the destructor is perfectly exception safe.

 But in general, Qt code (and so owncloud's client code) is not exception safe. This means that if an exception is thrown and is crossing Qt or owncloud client code, it can result in leaks. But that's fine because there is normally no exception thrown. If there is, this is because it is a critical error, and then the application will anyway be terminated with an error.

In particular, std::bad_alloc only happen in the out of memory condition, and when this happens, the exception will go up the stack and terminate the application with an error.

No recovery attempt is made because a recovery mechanism and exception safety is extremely hard.

Such exception can happen in any place in the program, leaving the program in a potentially bad state. Testing all these case is very difficult (and if it is not tested, it might not be working).

Terminating the application is the only option.

The sync engine is coded such a way that the application or computer can crash at any moment, and there shouldn't be data-loss.

**Comment by elfring** [comment] 2019-03-16 15:56
>…, because doing the delete in the destructor is perfectly exception safe.

I suggest to take another look at corresponding case distinctions.

The success of the possible object deletion depends on the validity of the provided pointer.


>…, and when this happens, the exception will go up the stack and terminate the application with an error.

This is a reasonable expectation in principle.


>The sync engine is coded such a way that the application or computer can crash at any moment, and there shouldn't be data-loss.

I have got doubts for the software behaviour after exceptional situations (according to this issue).

**Comment by guruz** [comment] 2019-03-20 10:34
> I have got doubts for the software behaviour after exceptional situations (according to this issue).

Please clarify :-)

I think crashing the application is good as this is what we expect at any time..

**Comment by elfring** [comment] 2019-03-20 11:38
* How much do you know if the involved data structures will be consistent after such a “[crash](https://en.wikipedia.org/wiki/Crash-only_software "Description for crash-only software")”?
* Do you care for [corresponding C++ core guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-summary-smartptrs "Smart pointer rule summary")?
