### ISSUE TITLE
Scenario `Filenames that are rejected by the server are reported` failed intermittently in nightly

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9782] opened 2022-06-09 07:09 UTC
Failed in: https://drone.owncloud.com/owncloud/client/12063/3/14
GUI report: https://cache.owncloud.com/public/owncloud/client/12063/guiReportUpload/index.html

![Screenshot from 2022-06-09 12-46-37](https://user-images.githubusercontent.com/27364813/172785142-49aa09c5-1ea6-48b2-ab40-f8dc96da8840.png)

Also, the log message `File is blacklisted` is misleading as the file is not actually blacklisted as per the failure. Need to fix that as well.

**Comment by sushmita56** [comment] 2022-07-11 07:10
Failed on step `And the user has waited for folder "Folder1" to be synced`  in CI with error `Exception: Expected folder '/tmp/client-bdd/Alice/Folder1' to be synced, but not.` 

Build: https://drone.owncloud.com/owncloud/client/12446/6/1
GUI log: https://cache.owncloud.com/public/owncloud/client/12446/guiReportUpload/index.html

![Screenshot from 2022-07-11 12-54-11](https://user-images.githubusercontent.com/66173400/178208188-a6b1f71c-c4db-4bc3-a8e5-1493da99032f.png)

**Comment by amrita-shrestha** [comment] 2022-07-29 04:33
Closing this issue because can't reproduce locally and seem stable in CI too.
Currently, we found that the sync step is 100% not reliable so we were looking for that separately. 

> Also, the log message `File is blacklisted` is misleading as the file is not actually blacklisted as per the failure. Need to fix that as well.

Log message is refactored in this PR: https://github.com/owncloud/client/pull/9949

**Closed by amrita-shrestha** 2022-07-29 04:33 UTC
Labels: QA:team
