### ISSUE TITLE
[UX] Possibility to go directly to "Permanently saved logs" folder

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/client#7087] opened 2019-03-15 07:56 UTC
**Possibility to go directly to "Permanently saved logs" folder**

### Expected behaviour
I desire an additional button that takes me directly to the appropriate folder. Let's say it's called "View" or "Saved Logs".

![image](https://user-images.githubusercontent.com/33026403/54416351-65cc3f80-46ff-11e9-801d-3c77900543a0.png)

### Actual behaviour
If you don't know where the permanent logs are saved, you have to move the mouse over the text "Permanently save logs" again and again. In addition the folder is hidden, which makes it harder to find. 

![image](https://user-images.githubusercontent.com/33026403/54413834-7082d680-46f7-11e9-87f7-580f77d7d51f.png)

@michaelstingl @ckamm Is this idea realizable?

**Comment by ckamm** [comment] 2019-03-15 07:57
Indeed!

**Comment by ckamm** [comment] 2019-03-15 08:21
This relates to #6475

**Comment by ckamm** [comment] 2019-03-15 10:19
Actually, upon rereading I'll close this as a duplicate of #6475

**Closed by ckamm** 2019-03-15 10:19 UTC
Labels: Design & UX, Enhancement
