### ISSUE TITLE
Sync error 'Destination file exists' with *.sparsebundle (Mac OS X)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#2949] opened 2015-03-11 18:07 UTC
User is experiencing 2 sync errors with the Mac OS X client, version 1.7.1.

1) The first error is 'Destination file exists' (screenshot + logfile). It looks like a file is unable to sync but it doesn't exactly say where it goes wrong (is it unable to upload a file, or download a file?). The sync client seems to be stuck at this file; rebooting and such doesn't help.

![screen shot 2015-03-11 at 10 16 58 _pixelated](https://cloud.githubusercontent.com/assets/214010/6603269/36f3c874-c821-11e4-9631-a497e3d25374.png)

2) The second error is a '403 Forbidden' error (see logfile).

### Expected behaviour
The sync client should smoothly sync all files

### Actual behaviour
The sync client seems to be stuck at this file; rebooting and such doesn't help.

**Logfile:**
S3-ownCloud/Shared/owncloud/support/github-issues/client/2949

@dragotin could this be related to *.sparsebundle files on Mac OS X? /cc @MorrisJobke 

00002706

**Comment by guruz** [comment] 2015-03-12 08:12
> The sync client seems to be stuck at this file

Do you mean it aborts the sync and does not continue?

> *.sparsebundle

Need to have a look what this exactly is, is it containing hard links?

**Comment by michaelstingl** [comment] 2015-03-12 08:51
@guruz I will ask the user if the client syncs other files while he stuck at this file.

**I created example file:**
S3-ownCloud/Shared/owncloud/support/github-issues/client/2949

I don't think the sparsebundle contain hard links. If you open the sparsebundle, then the mounted volume can contain hard links, created by TimeMachine for example. But this has nothing to do with the file structure of the sparsebundle in an ownCloud folder.

**Comment by michaelstingl** [comment] 2015-03-12 22:02
@guruz  The sync client continues to sync other files while he is stuck at this file. But the icon in the menu bar continues to show an X. So the user wouldn't know the sync continued until he opened the activity log. (Maybe that is desired behavior but it's still confusing ;-))

**Comment by MTRichards** [comment] 2015-03-12 22:04
Perhaps we can get a yellow warning label instead of a red x?

I have the same problem on my side, and while all of my ownCloud's now 
have a red x for status, they properly sync everything except 1 or 2 
files that have errors.
@janborchardt

**Comment by dragotin** [comment] 2015-03-13 07:36
The local path on the screenshot says */Volumes/MicroSD*. Does that mean we sync to a SD-Card here? Which file system does that have?

**Comment by michaelstingl** [comment] 2015-03-16 13:51
@dragotin Yes, the user syncs to SD-card. The filesystem is Mac OS Extended (Journaled).

**Comment by moscicki** [comment] 2015-03-19 13:43
Same problem with 1.7.1, see my comments here: https://github.com/owncloud/core/issues/12517#issuecomment-83581303

**Comment by Vindaomeo** [comment] 2015-04-09 06:40
I have the same problem - the sync fails if the subject is an "osx"-specific bundle. eg. OmniGraffle uses this - the mydrawing.graffle then gets a "bundle" which is a directory. Owncloud seems to fail to recognize this. On the "server"-side the "bundle" is stored as simple file and not as "folder".

**Comment by michaelstingl** [comment] 2015-04-09 10:25
@Vindaomeo I checked the *.sparsebundle. This is a folder with files and subfolders on the ownCloud website.

**Comment by bboule** [comment] 2015-06-23 00:56
So can we assume this issue will be addressed in 2.0?

**Comment by guruz** [comment] 2015-06-23 10:34
@bboule No time anymore for 2.0 but if you convince @MTRichards that we really need it for 2.1 https://github.com/owncloud/client/issues/3202

**Comment by bboule** [comment] 2015-06-23 10:54
@MTRichards  guys, more than anything I need to set an expectation given this is a blue ticket we have someone on the other end that we need to set an expectation with 2, 2.1, 2.2 is less which of these does not really matter but just making a commitment we can stick to regardless of when is what we need if possible?

**Comment by MTRichards** [comment] 2015-06-23 11:51
To be honest, I can't see that we even know what the problem is, there seem to be a few mixing here. We have an SD card, not an SD card, and a a bundled file. We will be groping in the dark a little without more information.

Can we confirm what the blue ticket issue is? I am not clear whether we have a bug or feature.

That said, I will slide it into 2.1 to make room to investigate, so it doesn't get lost.

**Comment by bboule** [comment] 2015-07-31 20:17
@michaelstingl can you clarify for @MTRichards here, it seems like there seems to be some confusion around this (SD Card vs Not to SD Card... I assume that matters?) it seems unclear to me how we make progress on this?

**Comment by cdamken** [comment] 2015-08-14 08:08
@bboule  @MTRichards  in my case  is with SD Card,

but  @moscicki  has the same behavior without it:

> Same problem with 1.7.1, see my comments here: owncloud/core#12517 (comment)
> 
> The user DOES NOT sync to the SD card.

But anyway, I will ask to test in a normal HD.

**Comment by cdamken** [comment] 2015-08-14 08:58
Problem sees that id does not appear anymore.

Please reopen if someone has still the problem.

Thanks Guys!

**Closed by cdamken** 2015-08-14 08:58 UTC
Labels: blue-ticket, sev2-high
