### ISSUE TITLE
Renaming at Web Interface while syncing cause data to be lost 

### ISSUE THREAD

**Issue by hoho508** [owncloud/client#3275] opened 2015-05-24 14:20 UTC
Hi guys , 
I was hounded by data lost issue from owncloud for weeks 
I discovered that when ownCloud Client is syncing and i keep on renaming folder that is been sync will cause Data in the folders to disappear .

I will have to delete and restore it to see the folders again

**Comment by danimo** [comment] 2015-05-25 05:42
Thanks for your report. However, we need details. Please fill in https://raw.githubusercontent.com/owncloud/client/master/issue_template.md.

**Comment by hoho508** [comment] 2015-05-25 06:24
Steps to reproduce
1. Keep on Renaming folders at web base while syncing using owncloud client
2. 
3.

Expected behaviour
Folder got renamed

Actual behaviour
Folders at web base become zero byte 
But can reappear when delete and restore at deleted files

Server configuration
Operating system:
Ubuntu 14.04
Web server:
Apache
Database:
MySQL
PHP version:
PHP 5.5.9
ownCloud version: (see ownCloud admin page)
8.0.3
Updated from an older ownCloud or fresh install:
Fresh Install
List of activated apps:

Activity 1.2.0
Deleted files 0.6.2
File Locking
Mail Template Editor 0.1
Provisioning API 0.2
Share Files 0.6.1
Versions 1.0.5

The content of config/config.php:

Insert your config.php content here
(Without the database password, passwordsalt and secret)
Are you using external storage, if yes which one: local/smb/sftp/...
No
Are you using encryption: yes/no
No
Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
No

LDAP configuration (delete this part if not used)
No

run: sqlite3 data/owncloud.db
then execute:  select * from oc_appconfig where appid='user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
Client configuration
Browser:
Chrome , IE , FireFox
Operating system:
Windows 7

**Comment by danimo** [comment] 2015-05-25 09:51
@hoho508 And which ownCloud Client version are you using?

**Comment by hoho508** [comment] 2015-05-25 16:12
@danimo im using Version 1.8.1 (5050) . it seems that by applying the update https://github.com/owncloud/core/pull/13948 , it becomes so fast that im unable to produce the issue ..

**Comment by moscicki** [comment] 2015-05-26 13:02
The question: is this a race condition in the client which is triggered more often when the server is slow?  If yes, then speeding up the server does not really solve the problem.

**Comment by ogoffart** [comment] 2015-05-26 13:32
Normaly, the client should handle that just fine. This is part of the test procedures [https://github.com/owncloud/client/wiki/Testing-Scenarios#modifying-files-when-the-sync-is-running] 

My intuition tells me that this is probably a bug on the server.

**Comment by PVince81** [comment] 2015-05-28 13:45
Duplicate of https://github.com/owncloud/core/issues/13391
See https://github.com/owncloud/core/issues/13391#issuecomment-105525369 for an explanation about what happens (and how to reproduce it)

**Comment by PVince81** [comment] 2015-05-28 13:46
and yes, https://github.com/owncloud/core/pull/13948 reduces the window of opportunity for the problem to occur. But only reduces it, it doesn't eliminate it completely...

**Closed by PVince81** 2015-05-28 13:45 UTC
Labels: Server Involved
