### ISSUE TITLE
ownCloud client icon not shown in Ubuntu 18.04

### ISSUE THREAD

**Issue by samiux** [owncloud/client#6518] opened 2018-05-12 00:11 UTC
### Expected behaviour
ownCloud client icon show on Ubuntu 18.04 panel when gnome-shell-extension-top-icons-plus is installed and enabled.

### Actual behaviour
ownCloud client is install from ownCloud official site via respo.  After enabled start when startup, the icon could not be shown on the panel in Ubuntu 18.04 even gnome-shell-extension-top-icons-plus is installed and enabled.

### Steps to reproduce
1. sudo apt install gnome-shell-extension-top-icons-plus
2. reboot and enable the extension
3. reboot but the ownCloud icon does not show on the panel

**Comment by michaelstingl** [comment] 2018-05-12 16:31
@samiux Thank you for reporting the issue. Which exact version of the ownCloud client are you using? Did you install from the [ownCloud repos](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) or from the Ubuntu repos?

**Comment by samiux** [comment] 2018-05-12 17:08
@michaelstingl 

The ownCloud client is from both ownCloud's Ubuntu repos and Ubuntu's official repos.  After several experiments, I confirmed that it cannot work with Gnome Shell Extension only.  Without Gnome Shell Extension, it is working flawless.

**Comment by ckamm** [comment] 2018-05-14 08:38
@samiux It seems like top-icons-plus isn't in development anymore and might not work with 18.04, see https://extensions.gnome.org/extension/1031/topicons/ https://github.com/phocean/TopIcons-plus - it's quite likely that this is not a ownCloud client issue.

**Comment by samiux** [comment] 2018-05-14 09:03
@ckamm 

I have tested ownCloud client without "top icons plus" but with other Gnome Shell Extensions.  When Gnome Shell Extensions are enabled, ownCloud client will not be displayed.

I need to disable Gnome Shell Extension feature in "Gnome Tweaks".

Any idea?

**Comment by ckamm** [comment] 2018-05-15 07:26
@samiux This really sounds like an issue with the software managing the icons. Are there other programs with not gnome-native tray icons that don't have this problem?

**Comment by samiux** [comment] 2018-05-15 07:49
@ckamm 

I use RadioTray-NG (https://github.com/ebruck/radiotray-ng) which works flawlessly with and without Gnome Shell Extension.  Sometimes, indicator-cpufreq works properly with Gnome Shell Extension.

**Comment by ckamm** [comment] 2018-05-16 09:11
Okay, hmm. RadioTray-NG uses gtk and appindicator. 

I don't know what that "Gnome Shell Extension" option does.

This looks like it's supposed to integrate the Unity AppIndicators and the KDE StatusNotifierItems into the shell, does that work for you? https://extensions.gnome.org/extension/615/appindicator-support/

Tray icons on linux are a complicated mess unfortunately. We do want to support ubuntu 18.04 though and it seems like we'll need to check it out directly to figure out what workarounds are necessary this time.

**Comment by samiux** [comment] 2018-05-16 10:04
@ckamm 

Ubuntu 18.04 installed "gnome-shell-exension-appindicator" and it is enabled by default.

The following are the list of available extensions that come with Ubuntu 18.04.

gnome-shell-extension-appindicator - App indicators for GNOME Shell
gnome-shell-extension-ubuntu-dock - Ubuntu Dock for GNOME Shell
gnome-shell-extension-autohidetopbar - GNOME shell automatic topbar hider
gnome-shell-extension-better-volume - GNOME Shell extension that improves volume control
gnome-shell-extension-caffeine - GNOME Shell extension to keep your computer awake
gnome-shell-extension-dash-to-panel - combines the dash and the GNOME main panel into a single panel
gnome-shell-extension-dashtodock - dash-to-dock extension for GNOME shell
gnome-shell-extension-disconnect-wifi - disconnect wifi extension for GNOME shell
gnome-shell-extension-hard-disk-led - Shows harddisk activity (IO speed read/write and LED) in GNOME Shell
gnome-shell-extension-hide-activities - GNOME shell extension that hides the activities button
gnome-shell-extension-hide-veth - hides veth devices typically used by docker and lxc
gnome-shell-extension-impatience - speed up the gnome-shell animation speed
gnome-shell-extension-log-out-button - Adds a log out button to the system action list in GNOME Shell
gnome-shell-extension-mediaplayer - GNOME Shell extension to control media players
gnome-shell-extension-move-clock - move clock extension for GNOME shell
gnome-shell-extension-multi-monitors - Better support for additional monitors in GNOME shell
gnome-shell-extension-no-annoyance - removes GNOME 'Window is ready' notifications
gnome-shell-extension-onboard - GNOME Shell extension for the on-screen keyboard Onboard
gnome-shell-extension-pixelsaver - pixel saver extension for GNOME shell
gnome-shell-extension-redshift - redshift extension for GNOME Shell
gnome-shell-extension-remove-dropdown-arrows - removes drop down arrows from panel on GNOME shell
gnome-shell-extension-shortcuts - Creates a shortcuts help pop-up in GNOME Shell
gnome-shell-extension-show-ip - Shows the current private or public IP address
gnome-shell-extension-suspend-button - Gnome-shell extension to modify the suspend/shutdown buttons
gnome-shell-extension-system-monitor - Display system information in GNOME Shell status bar
gnome-shell-extension-taskbar - TaskBar Extension for GNOME Shell
gnome-shell-extension-tilix-dropdown - launch tilix in quake-mode from gnome-shell
gnome-shell-extension-tilix-shortcut - Adds easy to use configurable keyboard shortcut for tilix
gnome-shell-extension-top-icons-plus - GNOME Shell extension to move system tray icons to top bar
gnome-shell-extension-trash - trash applet for GNOME shell
gnome-shell-extension-weather - weather extension for GNOME Shell
gnome-shell-extension-workspaces-to-dock - additional options for GNOME workspace switcher
gnome-shell-extensions - Extensions to extend functionality of GNOME Shell
gnome-shell-extensions-gpaste - GPaste extension for GNOME Shell

**Comment by ckamm** [comment] 2018-05-18 11:39
@samiux I've tried reproducing the behavior you describe, but haven't been successful yet. I installed 18.04 and `unity-desktop`. The owncloud icon appears in the top right indicator section no matter whether I switch "Extensions" on or off in "Gnome Tweaks".

Do I need to restart the shell for this to take effect? How do I reproduce? 

Also, does this problem appear in the ubuntu default configuration or only when changes are made?

**Comment by samiux** [comment] 2018-05-18 11:44
@ckamm 

Ubuntu 18.04 does not use unity-desktop any more.  It use ubuntu-desktop which is installed by default.

After the install, you need to logout and re-login or reboot.  The ownCloud client icone will disappear when Gnome Shell Extension is enabled in Gnome Tweaks.

**Comment by ckamm** [comment] 2018-05-21 10:58
@samiux I still cannot reproduce the problem. I have ubuntu-desktop installed, as well as gnome tweaks. I've tried various permutations of having the global on/off button on the "Extension" pane toggled, as well as the plugins individually (particularly appindicator), logging out/in after each change. But the owncloud icon always appears in the top-right area for me.

Does this happen with the "Ubuntu", "Ubuntu on Wayland" or "Gnome Classic" desktop env? For me, there were not tray icons on "Gnome Classic" no matter what setting I used for "Extensions".

Note: this is based on installing ubuntu-desktop on a kubuntu, I might be missing some packages to make this problem appear.

**Comment by ckamm** [comment] 2018-05-21 10:59
@samiux Oh, maybe this is related to the tray-startup issue? Does the icon appear if you kill the owncloud client and then restart it manually? I always started it manually in my tests.

**Comment by samiux** [comment] 2018-05-21 11:48
@ckamm 

I install official Ubuntu Desktop 18.04 LTS and selected "Ubuntu" when login.  I did not try other variants.

Gnome Tweaks is installed.  Gnome Shell Extension is enabled with some extensions such as gnome-shell-extension-appindicator, gnome-shell-extension-hard-disk-led, gnome-shell-extension-system-monitor, gnome-shell-extension-better-volume and radiotray-ng and indicator-cpufreq installed as well as enabled.

I reboot or re-login to test the ownCloud client icon.

**Comment by ckamm** [comment] 2018-05-22 08:26
@samiux Could you test what happens when you manually quit and restart the owncloud client?

**Comment by ckamm** [comment] 2018-05-22 12:56
I've tried again in a VM using the ubuntu live cd, but the icon always appears for me. Even when the top-icons-plus extension is installed. 

Currently I have to assume it's something on your end. If you can give me steps for reproducing the issue starting from a clean install of 18.04 and double check them yourself beforehand I'm up for trying again though.

Note that even if I can reproduce the problem it might end up being an upstream issue.

**Comment by samiux** [comment] 2018-05-22 14:23
@ckamm

I finally find the issue.

Before that I installed the following gnome-shell-extensions with owncloud-client, they are all installed from Ubuntu 18.04 respo and :

gnome-shell-extension-appindicator
gnome-shell-extension-better-volume
gnome-shell-extension-hard-disk-led
gnome-shell-extension-system-monitor 
gnome-shell-extension-top-icons-plus

However, owncloud-client is workable with the following gnome-shell-extensions only :

gnome-shell-extension-appindicator
gnome-shell-extension-hard-disk-led
gnome-shell-extension-top-icons-plus

When "gnome-shell-extension-top-icons-plus" is disabled, owncloud-client does not work with "gnome-shell-extension-hard-disk-led" alone.  In addition, owncloud-client works with gnome-shell-extension-appindicator.

By the way, the following indicators also work with owncloud-client even gnome-shell-extensions are enabled.  Others gnome-shell-extensions did not tested :

indicator-cpufreq
radiotray-NG

For your information, please.

**Comment by ckamm** [comment] 2018-05-23 07:54
If I enable extensions and switch on only "hard-disk-led" (so appindicator and top-icons-plus are disabled), the owncloud icon is still visible for me when I log out and back in.

In any case, it sounds like appindicator/top-icons-plus should be necessary to show the owncloud indicator (which is not gnome-native), so I'm more surprised about it continuing to work for me than about it disappearing for you.

**Comment by samiux** [comment] 2018-05-23 08:04
@ckamm 

I confirmed that "gnome-shell-extension-hard-disk-led" works with owncloud-client no matter "gnome-shell-extension-top-icons-plus" and/or "gnome-shell-extension-appindicator" is enabled or disabled or not.

**Comment by ckamm** [comment] 2018-05-23 08:56
@samiux When speaking about this with @ogoffart he pointed towards your `sudo owncloud` - do you usually start owncloud this way or just for this test? Prefer to run owncloud as the same user that the desktop session is running in, otherwise the tray might not show up because of that.

Regarding your other messages: I'm confused now. Previously I understood you as saying the tray icon would not show if both top-icons-plus and appindicator were disabled. Are you now saying it works no matter whether they are enabled or not? Which is the exact configuration to make the tray icon not show up?

**Comment by samiux** [comment] 2018-05-23 09:01
@ckamm 

The autostarter is running "owncloud" without "sudo".

"gnome-shell-extension-hard-disk-led" is compatible with owncloud-client but the other gnome-shell-extensions are not.

**Comment by samiux** [comment] 2018-05-29 04:32
@ckamm 

When the owncloud-client is the last installed, the icon can be displayed properly.

**Comment by vstokesjr** [comment] 2018-09-19 10:58
I am having the same issue. I use the owncloud.org repo. The owncloud client icon does not display in the top bar. I do have gnome extensions enabled. I tried to disabling gnome extensions (via Tweak tool), restart the owncloud client, and it didn't seem to make any difference.

**Comment by ckamm** [comment] 2018-09-26 07:50
@vstokesjr Are you also on ubuntu 18.04? I've not managed to reproduce any missing icons in my fresh-install vm, so any extra information you can provide could be helpful.

**Comment by gnanet** [comment] 2018-10-10 22:07
I am still looking for the right issue, but i have to note a similar issue, for starters the system data:

### System info
**System:** Ubuntu 14.04.5 LTS
**SESSION**=ubuntu
**GTK_MODULES**=overlay-scrollbar:unity-gtk-module
**SESSIONTYPE**=gnome-session
**XDG_CURRENT_DESKTOP**=Unity

#### installed "indicator" packages:
```
evolution-indicator 0.2.20-0ubuntu15
gir1.2-appindicator3-0.1 12.10.1+13.10.20130920-0ubuntu4.1
hamster-indicator 0.1+037dd2e-0ubuntu2
indicator-application 12.10.1+14.04.20140407-0ubuntu1
indicator-appmenu 13.01.0+14.04.20140404-0ubuntu1
indicator-bluetooth 0.0.6+14.04.20140207-0ubuntu2
indicator-datetime 13.10.0+14.04.20140415.3-0ubuntu1
indicator-keyboard 0.0.0+14.04.20140410.1-0ubuntu1
indicator-messages 13.10.1+14.04.20140410-0ubuntu1
indicator-power 12.10.6+14.04.20140411-0ubuntu1
indicator-printers 0.1.7+14.04.20140527-0ubuntu1
indicator-session 12.10.5+14.04.20151021.1-0ubuntu1
indicator-sound 12.10.2+14.04.20140401-0ubuntu1
libappindicator1 12.10.1+13.10.20130920-0ubuntu4.1
libappindicator3-1 12.10.1+13.10.20130920-0ubuntu4.1
libgtk2-appindicator-perl 0.15-1build1
libindicate5 12.10.1-0ubuntu3
libindicator3-7 12.10.2+14.04.20141007.1-0ubuntu1
libindicator7 12.10.2+14.04.20141007.1-0ubuntu1
python-appindicator 12.10.1+13.10.20130920-0ubuntu4.1
sni-qt:amd64 0.2.6-0ubuntu1
sni-qt:i386 0.2.6-0ubuntu1
telepathy-indicator 0.3.1+14.04.20140411-0ubuntu1
window-list 0.05~precise
```

#### installed owncloud packages:
```
libowncloudsync0:amd64 2.5.0.10650+oc-10213
owncloud-client:amd64 2.5.0.10650+oc-10213
owncloud-client-l10n 2.5.0.10650+oc-10213
owncloud-client-nautilus 2.5.0.10650+oc-10213
owncloud-client-overlays-icons 2.5.0.10650+oc-10213
```

### **Actual behaviour**
The actual behaviour is, that application indicatior icon for Dropbox, Viber, Skype, Caprine is shown if it is started, but since updating ownCloud client to 2.5.0 the indicatior icon does not show by its own power. (I am extremely satisfied with the optimised sync functionality anyway)

### WORKAROUND:
killing and starting  `/usr/lib/x86_64-linux-gnu/indicator-application/indicator-application-service` as the desktop session user (using an xterm console for example) seems to help most of the time:

```
killall indicator-application-service
/usr/lib/x86_64-linux-gnu/indicator-application/indicator-application-service & disown
```

**Comment by gnanet** [comment] 2018-10-10 22:13
I will try remove appmenu-qt5 which was installed too on my system
https://github.com/owncloud/client/issues/4693#issuecomment-214365805

**Comment by ogoffart** [comment] 2018-12-04 13:21
So what exactly is the problem in this issue? Where is the bug?

I guess in the log term, we will have to implement the cloud provider API

**Comment by tokup** [comment] 2019-02-21 07:46
I'd the same issue with ubuntu 18.4 (as samiux described).
My workaround: 
Delay the start of the owncloud client by a few seconds (e.g. 10s).
By adding "`X-GNOME-Autostart-Delay=10`" to the file "~/.config/autostart/ownCloud.desktop"

**Comment by gpothier** [comment] 2019-03-05 14:54
I have the same issue on 18.10. Active extensions:
Kstatusnotifieritem/appindicator support
Alternatetab
Cpufreq

The "X-GNOME-Autostart-Delay=10" workaround mentioned by @tokup works for me.

**Comment by ckamm** [comment] 2019-03-05 15:28
Since it seems to work for several people: let's add the autostart delay to the default desktop file.

**Comment by gpothier** [comment] 2019-03-05 15:38
As an additional information: without the delay, upon logging in, the OwnCloud window appears, but not the icon. With the delay, after the 10s only the icon appears, not the window. So there is probably something you can detect during startup, like some service that needs to be up.

**Comment by ckamm** [comment] 2019-03-06 09:32
@gpothier @tokup The .desktop file already has "X-GNOME-Autostart-Delay=3" since version 2.0.2. Are you saying you incremented the value to 10, or was your file missing that entry entirely?

**Comment by gpothier** [comment] 2019-03-06 12:27
In my case there was no X-GNOME-Autostart-Delay in the .desktop file. I'm on 2.5.3. I installed OwnCloud following these instructions: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

The .desktop file originally had this content:
[Desktop Entry]
Name=ownCloud
GenericName=File Synchronizer
Exec=/opt/ownCloud/ownCloud/bin/owncloud
Terminal=false
Icon=owncloud
Categories=Network
Type=Application
StartupNotify=false
X-GNOME-Autostart-enabled=true

**Comment by ckamm** [comment] 2019-03-06 13:35
@gpothier Thanks! Probably the .desktop file is set up during packaging then. The PR #7072 might make the workaround unnecessary. Would you be up for tesing it? I'll ping you once it's merged and has appeared in the dailies.

**Comment by gpothier** [comment] 2019-03-06 13:44
Yes of course!

**Comment by ckamm** [comment] 2019-03-11 08:40
@gpothier The linux dailies should now include the fix: https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client . Try removing the autostart delay, the client should retry on failure after 10s itself. (it's visible in the logs)

**Comment by guruz** [comment] 2019-03-11 14:19
Should also be in 2.5.4-rc1
https://download.owncloud.com/desktop/testing/owncloud-client-2.5.4.11614.484rc1.linux-repo.html

**Comment by gpothier** [comment] 2019-03-11 21:18
Hi, the problem persists with 2.5.4rc1 (build 484). The delay workaround is still needed. Do you know how I could provide a log of the autostarted owncloud instance?

**Comment by ckamm** [comment] 2019-03-12 08:38
@gpothier :(

Enable permanent logging, see https://doc.owncloud.org/desktop/2.5/troubleshooting.html#logging-to-a-temporary-directory

**Comment by gpothier** [comment] 2019-03-12 15:08
Here is what I get when it fails to setup the tray (with grep -i tray):
03-12 11:44:50:654 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
03-12 11:44:50:915 [ info gui.application ]:	System tray is not available, waiting...
03-12 11:44:51:916 [ info gui.application ]:	System tray still not available, showing window and trying again later
03-12 11:45:18:860 [ info gui.application ]:	Trying tray icon, tray available: false

And with the delay workaround (again with grep -i tray):
03-12 11:43:21:841 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
03-12 11:43:22:103 [ info gui.application ]:	System tray is not available, waiting...
03-12 11:43:23:104 [ info gui.application ]:	System tray still not available, showing window and trying again later

When enabling permanent logging OwnCloud mostly freezes when opening the logging window... I suspect it is due to the fact that this also enables debug logging and creates quite a large volume of logs.

**Comment by gpothier** [comment] 2019-03-12 23:39
I tried again, but logging out from all accounts before enabling logging, because with OwnCloud mostly frozen I suspect I got confused with which log was which attempt in my previous response. Now it is better ordered, and it makes more sense. The first attempt (20:29) was with the delay workaround, and the second one (20:30) without it.

gpothier@tadzim4:~$ ls -lt /tmp/ownCloud-logdir/
total 36
-rw-rw-r-- 1 gpothier gpothier  3923 mar 12 20:30 20190312_2030_owncloud.log.0.gz
-rw-rw-r-- 1 gpothier gpothier     0 mar 12 20:30 20190312_2030_owncloud.log.1
-rw-rw-r-- 1 gpothier gpothier 29941 mar 12 20:29 20190312_2029_owncloud.log.0

gpothier@tadzim4:~$ cat /tmp/ownCloud-logdir/20190312_2029_owncloud.log.0 |grep -i tray 
03-12 20:29:23:131 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false

gpothier@tadzim4:~$ zcat /tmp/ownCloud-logdir/20190312_2030_owncloud.log.0.gz |grep -i tray 
03-12 20:30:08:883 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
03-12 20:30:09:153 [ info gui.application ]:	System tray is not available, waiting...
03-12 20:30:10:154 [ info gui.application ]:	System tray still not available, showing window and trying again later
03-12 20:30:20:357 [ info gui.application ]:	Trying tray icon, tray available: false

**Comment by ckamm** [comment] 2019-03-13 09:38
@gpothier Thanks for the data! That means the client does try after 10s, but it has no effect. :/

I'll see about adding that autostart delay workaround.

**Comment by jnweiger** [comment] 2019-03-15 16:52
## tested on ubunut18.04
starting with 2.5.3 (to reproduce the problem)
Install Gnome Tweaks.
 Enable Gnomme Shell Extension with
  gnome-shell-extension-appindicator
  gnome-shell-extension-hard-disk-led
  gnome-shell-extension-system-monitor
  gnome-shell-extension-better-volume
  radiotray-ng
No such package. -> install 'radiotray' instead.
  indicator-cpufreq
    installed and enabled.
 reboot
 gnome-shell-extension-prefs
  -> check that they are enabled.

 install owncloud-2.5.3
 -> tray icon appears at the top right. No reboot needed.
cannot reproduce.

Also when disabling all these extensions or some combination of them  the owncloud tray icon always appear. 

CANNOT TEST

**Comment by ckamm** [comment] 2019-03-15 19:03
I've had similar trouble reproducing the issue in vms, but it seems to be fairly common in the wild :/

**Comment by gpothier** [comment] 2019-03-15 19:12
I just realized I never mentioned that I use the "vanilla" Gnome Shell, not the Ubuntu-customized one... I don't know about the original reporter.
Basically:
sudo apt install gnome-session
Also choosing the non-ubuntu css alternative, but probably not relevant:
sudo update-alternatives --config gdm3.css

And then select "Gnome on Xorg" when logging in.

**Comment by jbierkens** [comment] 2019-09-19 10:35
Hello I am not seeing the owncloud icon in Xubuntu 19.04. Not sure if it is related to the above. There is no package gnome-shell-extension-top-icons-plus available to install or remove. Let me know what I can do to help debug.

**Comment by floridop** [comment] 2019-11-11 12:58
Hi all
I am seeing the same issue on ubuntu-mate 18.04
This is what I get from the logs when starting manually:
```
owncloud --logwindow --logdebug --logfile -
11-11 13:49:03:119 [ info gui.application ]:	"################## ownCloud locale:[en_US] ui_lang:[] version:[2.6.0 (build 1714)] os:[Ubuntu 18.04.3 LTS]"
11-11 13:49:03:119 [ info gui.application ]:	Using "en_US" translation
```

**Comment by jnweiger** [comment] 2019-11-12 10:46
@floridop Can you try to launch the owncloud-client for a second time? That should bring you to the settings screen, so that you can see, what is going on. Connected or not, waiting for user confirmations, etc...

Glad you mention that you removed packages from your system. Having notififications is not a hard requirement. But there may be other things like tray-icon compatibility libraries, that may be critical to seeing the icon or not.

With or without the tray-icon visible. It should still happily sync. Seems we have two separate issues here.

**Comment by floridop** [comment] 2019-11-12 13:22
@jnweiger the process seems to be stuck, and producing no useful logs.
```shell
> owncloud --logwindow --logfile /tmp/owncloud.log --logdir /tmp/ownsyncs --logdebug
^Z
[1]  + 3621 suspended  owncloud --logwindow --logfile /tmp/owncloud.log --logdir /tmp/ownsyncs 
pflorido@tjatte:pts/9->/nfs/users/floridop (148) 
> bg
[1]  + 3621 continued  owncloud --logwindow --logfile /tmp/owncloud.log --logdir /tmp/ownsyncs 
pflorido@tjatte:pts/9->/nfs/users/floridop (0) 
> owncloud
gui.application: Already running, exiting...
pflorido@tjatte:pts/9->/nfs/users/floridop (255) 
> ps aux | grep owncloud
pflorido  3621  0.2  0.2 398204 25948 pts/9    Sl   14:20   0:00 owncloud --logwindow --logfile /tmp/owncloud.log --logdir /tmp/ownsyncs --logdebug
pflorido  3654  0.0  0.0  24296  1016 pts/9    S+   14:21   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn owncloud
```
As said I recently removed some default notification package that was basically killing all my other applications, I hope I can find it in the history.

The issue may be related to some other component like dbus. The fact that the icon does not show might not be related with any of the tray applets, that could explain why you have hard time reproducing.

**Comment by floridop** [comment] 2019-11-12 13:29
Found some removed packages
```sudo apt-get remove notify-osd kdebase-runtime notification-daemon```

**Comment by floridop** [comment] 2019-11-12 13:34
Forget about my comments. I had a stale `owncloud.cfg.lock` file in ~/.local/ownCloud/
This is probably due to my home being nfs-d
thanks for your support. Now the icon is back.

**Comment by jnweiger** [comment] 2019-11-12 14:02
good analysis. Yep, that explains it nicely. Thanks for clearing that up, :-)

@ckamm enhancement suggestion: have a line in the log and on stdout, when there is a lock.

**Closed** 2020-10-20 10:29 UTC
Labels: Linux, ReadyToTest, bug
