### ISSUE TITLE
`Login required` dialog appers automatically after removing account connection

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/client#11001] opened 2023-07-04 11:16 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

While removing connection to the account, the application automatically displays `Login required` dialog box after some time. Close button and `Log out` option of dialog box does not perform any function. But the application crashes when `Log in` button of the dialog box is clicked. 

### Expected behavior

I didn't expect to see the Login dialog to pop up after removing the connection to that account.

### Steps to reproduce the issue

1. Add an account
2. Remove connection to the account
3. `Login required` dialog appears automatically within the interval of one minute
4. Click `Log in` button
5. Desktop client app crashes

### Screenshots

![Screenshot from 2023-07-04 16-06-28](https://github.com/owncloud/client/assets/53458341/54121bac-0cdd-4427-bdbf-1cea4b65045c)

### Logs

[ownCloud.log](https://github.com/owncloud/client/files/11948011/ownCloud.log)

### Client version number

ownCloud 5.0.0.11377-daily20230704 [511b96](https://github.com/owncloud/client/commit/511b960805458aca4fbde6ac940002f22e445828)
Libraries Qt 6.4.3, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
ubuntu-5.19.0-46-generic

**Comment by TheOneRing** [comment] 2023-07-04 11:34
Duplicate of: https://github.com/owncloud/client/issues/10990

**Closed by TheOneRing** 2023-07-04 11:34 UTC
Labels: bug

**Comment by Salipa-Gurung** [comment] 2023-07-05 05:31
Do we need reopen https://github.com/owncloud/client/issues/10990 issue?

**Comment by TheOneRing** [comment] 2023-07-05 09:47
Only if it still occurs, the fix was merged yesterday, the build of this report is based on a commit 5 days ago.
