### ISSUE TITLE
[2.0.1] UI has unclear and contradicting messages with the new tree view widget.

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3754] opened 2015-09-04 13:46 UTC
2.0.1 has an additional Tree view widget [+] floating somewhat unaligned left of the progress bar.
clicking the widget adds two messages:
![s3-sync-screenshot-201-blackened](https://cloud.githubusercontent.com/assets/1108546/9684937/146ad6dc-531b-11e5-92ed-714121c029ea.png)
New messages are:
"Error while loading the list of folders from the server."
and
"Nicht markierte Ordner werden von ihrem lokalen Dateisystem entfernt und werden auch nicht mehr auf diesem Rechner synchronisiert"

Both are scary. The error seems to have little impact on the sync, but the other one indicates potential data loss, and asks for user actions. The button 'Add Folder to Synchronize' is greyed out, -- beyond that, it is unclear what a user should do to prevent data loss.

Hovering on the tree view [-] widget, shows "Warte, um mit der Synchronization zu beginnen" athough we are obviously busy with syncing, for quite a while already.

**Comment by phil-davis** [comment] 2015-09-04 15:04
The English of that text is "Unchecked folders will be removed from your local file system and will not be synchronized to this computer anymore".

"Error while loading the list of folders from the server." is a timeout when the client is waiting for the server to reply with the folder list. There is a known problem when the [some of] the folders on the server are mapped to an external storage. The server is taking too long to gather the folder list, and the client gives up waiting - https://github.com/owncloud/client/issues/3524

Do you have external storage/s on the server end?

**Comment by jancborchardt** [comment] 2015-09-08 10:42
The bottom section »Unchecked folders …« with the apply and cancel button should _only_ show as soon as action is taken on the list. That is, as soon as you check or uncheck any additional items which were previously differently checked.

**Comment by rienesl** [comment] 2015-09-23 06:43
I have similar problems on several clients. If you forget to uncheck the checkbox "Ask confirmation before downloading..." after update, it does NOT ask, it simply unchecks those folders! The worst thing is, though I use only external storage, I have no chance to check them again, because of the "Error while loading the list of folders from the server." Using 1.8.4 everything was OK.

**Comment by phil-davis** [comment] 2015-09-23 07:37
@riesnesl You are getting a Catch-22 due to https://github.com/owncloud/client/issues/3524 "Error while loading the list of folders from the server."
When a new folder is detected that is larger than the limit, then it is unchecked for you by default in the folder tree view. Then you can choose to check it if you like and then press Apply.
Since there is this timeout problem that results in you (and me) never seeing the folder tree, that makes it rather difficult to drive the UI as intended!
If the changes suggested here in this issue are done, then the message and the Apply button will also not be displayed until the folder tree is ready to display, which equals never in your case. So then you will be left in the dark completely.
Is there some way to solve this when the "Error while loading the list of folders from the server." problem happens?

**Comment by rienesl** [comment] 2015-09-23 11:06
@phil-davis 
The only, but very time consumptive workaround is to expand and minimize the tree several times. Using this method, you need between 1 and 10 Minutes for one level. If you count those time up for 4-5 level deep structures and this several times, you spend quite some time to get all the checkboxes checked...
PS: I started reading in #3524, but to be honest: I stopped, when I read, that it is the commercial version.

**Comment by phil-davis** [comment] 2015-09-23 11:11
In #3524 I was just referring to the fact that the server I was using happens to be on a commercially hosted provider, and thus I do not have deep-level access to mess with the underlying config settings. It is just running ordinary ownCloud and the bug is easy to reproduce - including on your own ownCloud server install, as you have experienced.

**Comment by guruz** [comment] 2015-11-10 16:01
Please note that 2.1 looks totally different in that area..

**Comment by jancborchardt** [comment] 2015-11-10 16:22
So we can close this?

**Closed** 2017-07-03 13:10 UTC
Labels: Design & UX
