### ISSUE TITLE
Win 2.0.1 (5446) - network UNC path broken (CSync error accessing \\SERVER\SHARE)

### ISSUE THREAD

**Issue by giobatta** [owncloud/client#3788] opened 2015-09-09 09:22 UTC
Latest version breaks UNC functionality in Win Client. I do not know if CSYNC patch of 5 days ago introduces or sorts the issue out.

**Comment by giobatta** [comment] 2015-09-09 09:23
I refer to : csync io: Fix UNC path conversion on Win #3748

**Comment by danimo** [comment] 2015-09-09 09:23
Duplicate of #3748

**Comment by danimo** [comment] 2015-09-09 09:24
@giobatta It fixes the issue

**Comment by giobatta** [comment] 2015-09-09 09:24
ok

**Closed by danimo** 2015-09-09 09:23 UTC
