### ISSUE TITLE
log window improvements

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3356] opened 2015-06-17 15:54 UTC
I was shown by @felixboehm a wonderful thing for user support: F12 to open the log window. 

However, there are two problems with that:
 - on MacOSX I first had to unbind the F12 key which is bound to some desktop functions by default (for a normal user it is a bit heavy) -> could not we simply have a button in Settings or so which opens the window?
 - the log window once opened is very heavy on the CPU: the client sort of "hangs" for a while on a laptop. If this cannot be easily fixed than at least could we have a logfile produced directly on disk, so a user may easily find where it was generated?

**Comment by dragotin** [comment] 2015-11-09 12:29
duplicate of #3518

**Closed by dragotin** 2015-11-09 12:29 UTC
Labels: Enhancement
