### ISSUE TITLE
[Regression] [Windows] Sync folder on UNC-symlinked network storage is not working anymore

### ISSUE THREAD

**Issue by bOOT-CoDe** [owncloud/client#5633] opened 2017-03-20 08:49 UTC
### Expected behaviour
Synchromize sync folder.

### Actual behaviour
An error about not accessible folder is repeated. 

### Steps to reproduce
1. set the sync folder to network drive
2. or set the sync folder to symlink on local drive, symlink's target is on the network drive (this worked in the client release 2.2.4.6408)
3. try to synchronize

### Client configuration
Client version:
2.3.0.6780
Operating system:
Windows Vista Home 32-bit
Windos 7 Enterprise 64-bit

**Comment by SamuAlfageme** [comment] 2017-03-20 09:46
Hey @bOOT-CoDe! thanks for reporting! 

I've just done a few tests with a similar setup (syncing my `Z:\\` drive, a network-mounted drive) with client version 2.3 and everything seemed to work properly: 

![smb](https://cloud.githubusercontent.com/assets/2644445/24094701/164bfda0-0d5a-11e7-9ad2-ebbef838797f.png)

Do you have any client logs or more info (e.g. which kind of filesystem runs, if the disk is encryped, etc.) to provide that could help us reproduce the issue you are running into? Thanks!

**Comment by bOOT-CoDe** [comment] 2017-04-05 15:27
Hi @SamuAlfageme,
my setup is little bit different, I have so many drive letters used therefore I am using UNC paths too. Because I was unabl to settup direct UNC path as the sync folder in ownCloud client I use symlink to folder on network drive, see the screenshot. There is another advantage, I can move sync folder to different path (e.g. another network storage) and then just update symlink to point to a new target.
![image](https://cloud.githubusercontent.com/assets/23643083/24712578/7aed026a-1a23-11e7-9ae8-61ad5e64e06c.png)
Target network disk is not encypted, it is some Synology NAS accessed over SAMBA, local and remote file systems are both NTFS. This setup is working with older ownCloud clients.

**Comment by SamuAlfageme** [comment] 2017-05-08 08:46
@bOOT-CoDe I see, that's a bit more complex scenario, I will try to reproduce. 

> An error about not accessible folder is repeated.

Can you provide some [client logs](https://doc.owncloud.org/desktop/2.3/troubleshooting.html#log-files) and the error string the client is displaying? 

Thanks a lot!

**Comment by NM78** [comment] 2017-05-15 10:18
I have excactly the same issue: https://central.owncloud.org/t/network-folder-wont-work-in-v2-3-0-v2-3-2-but-in-v2-2-4-win-desktop-client/7627/2

**Comment by SamuAlfageme** [comment] 2017-05-15 13:16
@bOOT-CoDe @NM78 I've tested different network shares (not SMB, though) using both Windows' shortcuts and `.symlinks` and so far I'm unable to reproduce with oC 10.0 nor 9.1.4. 

> Because I was unabl to settup direct UNC path as the sync folder in ownCloud client I use symlink to folder on network drive,

Also, I was able to use the UNC path directly in the setup wizard. Did you experience otherwise? 

Do you guys have any additional steps that could be leading to this issue?. Also, [client logs](https://doc.owncloud.org/desktop/2.3/troubleshooting.html#log-files) will be really helpful to track what's happening under the client's hood.

**Comment by NM78** [comment] 2017-05-15 13:38
@SamuAlfageme 

Thx 4 your fast answer! Here is my log:

`05-15 15:33:36:130 8200 OCC::FolderMan::slotScheduleFolderByTime: ** scheduling folder "1" , the last 1 syncs failed , anotherSyncNeeded 0 , last status: "Error" , time since last sync: 12916
05-15 15:33:36:132 8200 OCC::FolderMan::scheduleFolder: Schedule folder  "1"  to sync!
05-15 15:33:36:133 8200 OCC::SocketApi::slotUpdateFolderView: Not sending UPDATE_VIEW for "1" because status() is 1
05-15 15:33:36:135 8200 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "https://mydomain.net/owncloud/remote.php/dav/files/myuser/" :  "Not yet Started"
05-15 15:33:36:135 8200 OCC::ActivitySettings::slotRefresh: void OCC::ActivitySettings::slotRefresh(OCC::AccountState*) do not check as last check is only secs ago:  13
05-15 15:33:36:136 8200 OCC::FolderMan::startScheduledSyncSoon: Starting the next scheduled sync in 0 seconds
05-15 15:33:36:153 8200 OCC::FolderMan::slotStartScheduledFolderSync: XX slotScheduleFolderSync: folderQueue size:  1
05-15 15:33:36:155 8200 OCC::SocketListener::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:\\\\qnap-01\\Alle_Firmen\\Datenbanken\\OwnCloud"
05-15 15:33:36:158 8200 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "https://mydomain.net/owncloud/remote.php/dav/files/myuser/" :  "SyncPrepare"
05-15 15:33:36:158 8200 OCC::Folder::startSync: *** Start syncing  "https://mydomain.net/owncloud/remote.php/dav/files/myuser/"  - client version 2.3.2 (build 6928)
05-15 15:33:36:162 8200 OCC::Folder::setIgnoredFiles: ==== adding system ignore list to csync: "C:/Program Files (x86)/ownCloud/sync-exclude.lst"
05-15 15:33:36:163 8200 OCC::Folder::setIgnoredFiles: ==== adding user defined ignore list to csync: "C:/Users/nico/AppData/Local/ownCloud/sync-exclude.lst"
05-15 15:33:36:163 0x431dd78 csync_exclude_load: Adding entry: *~
05-15 15:33:36:163 0x431dd78 csync_exclude_load: Adding entry: ~$*
05-15 15:33:36:163 0x431dd78 csync_exclude_load: Adding entry: .~lock.*
05-15 15:33:36:164 0x431dd78 csync_exclude_load: Adding entry: ~*.tmp
05-15 15:33:36:164 0x431dd78 csync_exclude_load: Adding entry: ]*.~*
05-15 15:33:36:164 0x431dd78 csync_exclude_load: Adding entry: ]Icon
*
05-15 15:33:36:164 0x431dd78 csync_exclude_load: Adding entry: ].DS_Store
05-15 15:33:36:164 0x431dd78 csync_exclude_load: Adding entry: ].ds_store
05-15 15:33:36:164 0x431dd78 csync_exclude_load: Adding entry: ._*
05-15 15:33:36:164 0x431dd78 csync_exclude_load: Adding entry: ]Thumbs.db
05-15 15:33:36:165 0x431dd78 csync_exclude_load: Adding entry: desktop.ini
05-15 15:33:36:165 0x431dd78 csync_exclude_load: Adding entry: System Volume Information
05-15 15:33:36:165 0x431dd78 csync_exclude_load: Adding entry: .*.sw?
05-15 15:33:36:165 0x431dd78 csync_exclude_load: Adding entry: .*.*sw?
05-15 15:33:36:165 0x431dd78 csync_exclude_load: Adding entry: ].TemporaryItems
05-15 15:33:36:166 0x431dd78 csync_exclude_load: Adding entry: ].Trashes
05-15 15:33:36:166 0x431dd78 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
05-15 15:33:36:166 0x431dd78 csync_exclude_load: Adding entry: ].Trash-*
05-15 15:33:36:166 0x431dd78 csync_exclude_load: Adding entry: .fseventd
05-15 15:33:36:166 0x431dd78 csync_exclude_load: Adding entry: .apdisk
05-15 15:33:36:166 0x431dd78 csync_exclude_load: Adding entry: .htaccess
05-15 15:33:36:167 0x431dd78 csync_exclude_load: Adding entry: .directory
05-15 15:33:36:167 0x431dd78 csync_exclude_load: Adding entry: *.part
05-15 15:33:36:167 0x431dd78 csync_exclude_load: Adding entry: *.filepart
05-15 15:33:36:167 0x431dd78 csync_exclude_load: Adding entry: *.crdownload
05-15 15:33:36:167 0x431dd78 csync_exclude_load: Adding entry: *.kate-swp
05-15 15:33:36:167 0x431dd78 csync_exclude_load: Adding entry: *.gnucash.tmp-*
05-15 15:33:36:167 0x431dd78 csync_exclude_load: Adding entry: .synkron.*
05-15 15:33:36:168 0x431dd78 csync_exclude_load: Adding entry: .sync.ffs_db
05-15 15:33:36:168 0x431dd78 csync_exclude_load: Adding entry: .symform
05-15 15:33:36:168 0x431dd78 csync_exclude_load: Adding entry: .symform-store
05-15 15:33:36:168 0x431dd78 csync_exclude_load: Adding entry: .fuse_hidden*
05-15 15:33:36:168 0x431dd78 csync_exclude_load: Adding entry: *.unison
05-15 15:33:36:168 0x431dd78 csync_exclude_load: Adding entry: .nfs*
05-15 15:33:36:168 0x431dd78 csync_exclude_load: Adding entry: My Saved Places.
05-15 15:33:36:170 8200 OCC::FolderMan::slotFolderSyncStarted: >===================================== sync started for  "https://mydomain.net/owncloud/remote.php/dav/files/myuser/"
05-15 15:33:36:174 8200 OCC::SyncEngine::startSync: There are 2194728050688 bytes available at "//qnap-01/Alle_Firmen/Datenbanken/OwnCloud/" and at least 50000000 are required
05-15 15:33:36:174 8200 OCC::SyncEngine::startSync: ===== new sync (no sync journal exists)
05-15 15:33:36:174 8200 OCC::SyncEngine::startSync: "===== Using Qt 5.6.2 SSL library OpenSSL 1.0.2h  3 May 2016 on Windows 10"
05-15 15:33:36:175 8200 OCC::SqlDatabase::openHelper: Error: "unable to open database file" for "//qnap-01/Alle_Firmen/Datenbanken/OwnCloud/._sync_9e589af46803.db"
05-15 15:33:36:175 8200 OCC::SyncJournalDb::checkConnect: Error opening the db:  "unable to open database file"
05-15 15:33:36:176 8200 OCC::SyncEngine::startSync: No way to create a sync journal!
05-15 15:33:36:176 8200 OCC::SyncJournalDb::close: void OCC::SyncJournalDb::close() "//qnap-01/Alle_Firmen/Datenbanken/OwnCloud/._sync_9e589af46803.db"
05-15 15:33:36:176 8200 OCC::SyncJournalDb::commitTransaction: No database Transaction to commit
05-15 15:33:36:176 8200 OCC::SyncEngine::finalize: CSync run took  0
05-15 15:33:36:181 8200 OCC::Folder::slotSyncFinished:  - client version 2.3.2 (build 6928)  Qt 5.6.2  SSL  OpenSSL 1.0.2h  3 May 2016
05-15 15:33:36:181 8200 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR
05-15 15:33:36:183 8200 OCC::Folder::showSyncResultPopup: OO folder slotSyncFinished: result:  2
05-15 15:33:36:183 8200 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
05-15 15:33:36:183 8200 OCC::Folder::slotSyncFinished: the last 2 syncs failed
05-15 15:33:36:183 8200 OCC::SocketListener::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:\\\\qnap-01\\Alle_Firmen\\Datenbanken\\OwnCloud"
05-15 15:33:36:186 8200 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "https://mydomain.net/owncloud/remote.php/dav/files/myuser/" :  "Error"
05-15 15:33:36:189 8200 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "//qnap-01/Alle_Firmen/Datenbanken/OwnCloud/.owncloudsync.log"
05-15 15:33:36:387 8200 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "https://mydomain.net/owncloud/remote.php/dav/files/myuser/"
05-15 15:33:53:385 8200 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
05-15 15:33:53:385 8200 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://mydomain.net/owncloud" + "/" "OCC::ConnectionValidator"
05-15 15:33:55:387 8200 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://mydomain.net/owncloud" + "/" "OCC::QuotaInfo"`

The win 2.3.2 client shows a red message "Synchronisationsbericht konnte nicht initialisiert werden."

I know, we had a similar issue some years (maybe 2?) ago. But i could not find a link to this anywhere.

**Comment by SamuAlfageme** [comment] 2017-05-16 08:58
@NM78 thanks a lot for the logs! Is your network folder an SMB share as @bOOT-CoDe? maybe we can isolate the issue in those. However, even with that share I'm not being able to reproduce: 

1. Create a SMB share in a macOS 10.12 and a guest Windows 7 VM - **Grant write permissions to the user you'll use to connect.** 
2. Map it as Network Drive (`\\host\share`)
3. Create a `.symlink` on the desktop pointing to the UNC path of the share.
4. Use either, the drive letter or the symlink to set up the local sync folder.

### What are the logs saying: 

#### `OCC::SyncEngine::startSync: No way to create a sync journal!`:
 ([`syncengine.cpp`](https://github.com/owncloud/client/blob/master/src/libsync/syncengine.cpp#L780-L786))
```
qCWarning(lcEngine) << "No way to create a sync journal!";
emit csyncError(tr("Unable to open or create the local sync database. Make sure you have write access in the sync folder."));
```
So, first thing to check is whether **you have write permissions** on the network share. This also match the red message you're seeing on the client:

| Read & Write Permissions | Read-Only Permissions |
|--------------------------|-----------------------|
|  ![w_permissions](https://cloud.githubusercontent.com/assets/2644445/26096573/e8b17c2c-3a21-11e7-8806-788292f08c20.gif) |  ![wo_permissions](https://cloud.githubusercontent.com/assets/2644445/26096542/d0229664-3a21-11e7-82cf-00383e36fa78.gif) |

#### `OCC::SyncEngine::startSync: ===== new sync (no sync journal exists)`

Even though, this says otherwise, I have to ask if **there was an already existing and working (with client 2.2.4) sync folder on the shared drive? and the update started causing this problems?**. This could be a permissions issue on the `.db` file (the migration strategy: https://github.com/owncloud/client/blob/master/src/libsync/syncjournaldb.cpp#L64 might overlook windows-specific permissions)

#### Problems creating the sync journal: 
The stack trace mentions these 2 functions: 

- [`SyncJournalDb::getFileRecordCount()`](https://github.com/owncloud/client/blob/master/src/libsync/syncjournaldb.cpp#L1025-L1046)
- [`SqlDatabase::openHelper()`](https://github.com/owncloud/client/blob/master/src/libsync/ownsql.cpp#L50-L74)

... maybe we can include more debugging messages on the logs in a testing client to see what's going on there. cc/ @guruz @ckamm what do you guys think? 

### Some changes introduced in 2.3.0 that might relate:

* Updated the version of Sqlite3: https://github.com/owncloud/client/commit/76fde492823dd80a31d52f2659981a3958b64b0f
* Introduced a new naming convention for the sync journal (`._XXXXXX`) to support https://github.com/owncloud/client/issues/3764. Maybe the new "invisible" filename used can cause problems in some types of shared storages. Will look into it.

**Comment by guruz** [comment] 2017-05-16 09:36
@bOOT-CoDe Did you also use 2.2.x before and it worked?

I think @dragotin or me or @ckamm might have also changed something about canonical file system paths of sync folders?

@bOOT-CoDe @NM78 I'm wondering if you set the ```OWNCLOUD_SQLITE_JOURNAL_MODE``` environment variable to ```DELETE``` for the ownCloud process, does it behave differently?

**Comment by guruz** [comment] 2017-05-22 09:19
@bOOT-CoDe @NM78 Any news?

**Comment by ElpyDE** [comment] 2017-06-02 18:26
Unfortunately, I can confirm this bug.

Upgraded Windows Client to Version 2.3.1 (build 8) (supplied by Nextcloud), from some 2.2.x Version (not completely sure).

Previously, I had a "local" folder at a UNC-symlinked network storage like `\\fileserver\some further\path\` and it worked great. After upgrade, the client tells me "Unable to initialize a sync journal." (actually it tells me in German "Synchronisationsbericht konnte nicht initialisiert werden."

I tried and none of these worked...

1. recreating the folder sync.
2. syncing with a newly created UNC folder.
3. syncing with the complete folder (on server) instead of just a subdirectory.
4. connecting a network drive first and using this as local folder

What I found, however, was that the `.owncloudsync.log` is created and written into:

```
# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=# Syncrun started 2017-06-02T19:46:53
#=#=#=# Syncrun finished 2017-06-02T19:46:53 (last step: 7 msec, total: 7 msec)
#=#=#=# Syncrun started 2017-06-02T19:47:06
#=#=#=# Syncrun finished 2017-06-02T19:47:06 (last step: 7 msec, total: 7 msec)
... and so on ...
```

Client Log: [client-log-v2.3.1.txt](https://github.com/owncloud/client/files/1048613/client-log-v2.3.1.txt) (after click on "continue sync" for the non-working folder sync)

Syncing with local folders on my PC works as expected.

__Additional Info:__

Local: Windows 8.1
Server with network share: Some Windows Server Edition
Owncloud Server(s): [sciebo](https://www.sciebo.de/) (ownCloud 9.0.8, Enterprise Version) and Nextcloud 10.0.5 (stable)

**Comment by ckamm** [comment] 2017-06-06 09:35
I've tried reproducing again, but without success.
* Shared a folder
* Mapped it as a network drive
* Synced a server folder to that mapped network drive without problems.

Looking at the logs again, it seems it's sqlite3 that returns SQLITE_CANTOPEN. We did indeed update sqlite between 2.2.4 and 2.3.1. It seems we could use `sqlite3_system_errno` to get information about the underlying issue. 

@ElpyDE @bOOT-CoDe: Would you be up for testing with a 2.4 snapshot build that has additional logging in the sync journal creation code?

**Comment by NM78** [comment] 2017-06-06 09:49
> Mapped it as a network drive

My folder isnt mapped as network drive. Its a directly path like "\\QNAP-01\MyFiles\OwnCloud"

This is what works in earlyer versions and in 2.2.4.

**Comment by michaelstingl** [comment] 2017-06-06 10:25
@NM78 Could you provide or link a quick step-by-step guide how to configure the "directly path" thingy?

**Comment by ckamm** [comment] 2017-06-06 10:44
@NM78 I was testing @ElpyDE's setup, direct UNC paths had worked for me with 2.3 before. The underlying cause is likely the same.

**Comment by ckamm** [comment] 2017-06-06 10:47
@NM78 @ElpyDE @bOOT-CoDe What kind of filesystem is the network drive running? Maybe that helps for reproducing the problem.

**Comment by ElpyDE** [comment] 2017-06-06 11:41
Indeed, it worked on a network share on my local computer (Win 8.1, NTFS).

The non-working share is based on my institute's fileserver. My admin just told me it's some sort of Linux based OS. Filesystem there is ext4. Network share is via Samba (SMB).

**Comment by ckamm** [comment] 2017-06-06 12:14
@ElpyDE Thanks for checking with them. I've now tested a simple samba share of an ext4 directory, but it still works for me.

I hope that the extra logging added to master will allow us to pinpoint what exactly goes wrong with database creation in sqlite3. I'll ping here once a nightly with the code becomes available.

**Comment by guruz** [comment] 2017-06-07 08:57
@bOOT-CoDe @NM78 I'm wondering if you set the OWNCLOUD_SQLITE_JOURNAL_MODE environment variable to DELETE for the ownCloud client process, does it behave differently?

**Comment by ckamm** [comment] 2017-06-08 09:52
@guruz Setting the environment variable should have no effect since it already fails at `sqlite3_open_v2` - we only set the journal mode with a pragma afterwards.

**Comment by ElpyDE** [comment] 2017-06-14 10:55
More logs... downloaded, installed and tested with two nightly builds from https://download.owncloud.com/desktop/daily/ 

__Version 2.3.3-nightly20170612 (build 34)__

Log: [ownCloud--Version 2.3.3-nightly20170612 (build 34).log.txt](https://github.com/owncloud/client/files/1074337/ownCloud--Version.2.3.3-nightly20170612.build.34.log.txt)

__Version 2.4.0-nightly20170613 (build 20)__

Log: [ownCloud--Version 2.4.0-nightly20170613 (build 20).log.txt](https://github.com/owncloud/client/files/1074340/ownCloud--Version.2.4.0-nightly20170613.build.20.log.txt)

For both versions, I configured 3 folder syncs:

* :ok: ownCloud-test1 - local folder on my PC:  
  `C:/Users/mynamef/ownCloud-test1/`
* :ok: ownCloud-test2 - local folder an SMB share, but on my Win-PC:  
  `\\mylocalpc\ownCloud-test2`
* :x: ownCloud-test3 - local folder on the above mentioned Linux based fileserver  
  `\\FILESERVER\Some Path\Myname\ownCloud-test3`

The first and second syncs worked perfectly. The third did not.

*log files have been anonymized, hopefully in a meaningful way*

**Comment by ckamm** [comment] 2017-06-14 11:42
@ElpyDE Thank you!

Most relevant:
```
06-14 12:26:20:700 [ warning sync.database.sql ]:	CANTOPEN extended errcode:  14
06-14 12:26:20:700 [ warning sync.database.sql ]:	CANTOPEN system errno:  2
```

**Comment by guruz** [comment] 2017-06-14 19:29
@dschmidt Could you create a Windows build from the sqlite3_revert_3161 branch and paste the .exe link here? :)

**Comment by guruz** [comment] 2017-06-15 08:32
@ElpyDE @NM78 @bOOT-CoDe https://download.owncloud.com/desktop/daily/ownCloud-2.4.0.44git-setup.exe Should have the older sqlite3 version. Does it work better with that?

**Comment by ckamm** [comment] 2017-06-15 12:22
@guruz Note that as far as I can tell updating sqlite to 3.14.2 was also done for 2.3.0 (f6355e15a392293af87a83dcedf35cf4a8c0bdff)

**Comment by guruz** [comment] 2017-06-15 13:19
I need to revert one more commit, @ckamm is right. Will make a build..

**Comment by guruz** [comment] 2017-06-15 13:38
@ElpyDE @NM78 @bOOT-CoDe https://download.owncloud.com/desktop/daily/ownCloud-2.4.0.45git-setup.exe should be available in some minutes

**Comment by ElpyDE** [comment] 2017-06-15 14:03
Tested both builds linked by @guruz - with equal settings as above in https://github.com/owncloud/client/issues/5633#issuecomment-308396677

Unfortunately, the results are also equal: Local directory and share on Win-PC work. Share on Linux-Server (*ownCloud-test3*) fails.

__ownCloud-2.4.0.44git-setup.exe__

Log: [ownCloud--Version 2.4.0git (build 44).log.txt](https://github.com/owncloud/client/files/1077827/ownCloud--Version.2.4.0git.build.44.log.txt)

__ownCloud-2.4.0.45git-setup.exe__

Log: [ownCloud--Version 2.4.0git (build 45).log.txt](https://github.com/owncloud/client/files/1077830/ownCloud--Version.2.4.0git.build.45.log.txt)

Warnings like before in both builds alike, here from build 45:

```
06-15 15:42:39:167 [ warning sync.database.sql ]:	Error: "unable to open database file" for "//FILESERVER/Some Path/Myname/ownCloud-test3/._sync_c0ac7e6f6814.db"
06-15 15:42:39:168 [ warning sync.database.sql ]:	CANTOPEN extended errcode:  14
06-15 15:42:39:168 [ warning sync.database.sql ]:	CANTOPEN system errno:  2
06-15 15:42:39:168 [ warning sync.database ]:	Error opening the db:  "unable to open database file"
06-15 15:42:39:168 [ warning sync.engine ]:	No way to create a sync journal!
```

**Comment by ckamm** [comment] 2017-06-16 07:49
@ElpyDE Thanks again for the tests.

In that case my last suggestion would be that maybe the paths we pass to `sqlite3_open` differ in format between 2.2 and 2.3. It'd be surprising if that mattered, since 2.3 works for some network shares and mounted drives. I'll look at these and report here.

Besides that, the only other option I can imagine is that this particular path is somehow invalid for the network drive? @ElpyDE can you manually create a `//FILESERVER/Some Path/Myname/ownCloud-test3/._sync_c0ac7e6f6815.db` file?

**Comment by ckamm** [comment] 2017-06-16 08:06
@guruz I've now run 2.2.4 and a newer version on windows, and these paths get fed to sqlite3:
```
2.2.4: //mywin7/test/.csync_journal.db
2.3+ : //mywin7/test/._sync_142df90e8e0f.db
```
So there's no structural difference besides the different database file name.

@ElpyDE Is there anything else hidden in your "Some Path/Myname" component? Would you be up for also providing us with a log from a 2.2.4 client where it works? (you can get the 2.2.4 windows binaries from https://owncloud.org/changelog/desktop/) I assume mounting the path to a network drive leads to the same issue?

**Comment by ElpyDE** [comment] 2017-06-16 12:05
Version 2.2.4 works as expected:

Log: [ownCloud--Version 2.2.4 (build 6408).log.txt](https://github.com/owncloud/client/files/1080375/ownCloud--Version.2.2.4.build.6408.log.txt)

---

@ckamm was right estimating a problem with invalid path:

I __cannot__ create a file called `._sync_142df90e8e0f.db` on the remote fileserver. Tested several methods (including saving with Notepad++, Drag&Drop a File from my Desktop, `touch` or `mv` in the Git Bash, renaming within Windows Explorer)

Some further research showed, that it is about the "._" prefix: `._something.ext` cannot be created, too.

```shell
$ mv something.ext ._something.ext
mv: cannot move 'something.ext' to '._something.ext': No such file or directory
```

__File names that work__

* `.something.ext`
* `_something.ext`
* `.a_something.ext`
* `_.something.ext`
* `.csync_journal.db` and `.owncloudsync.log` (were left over from my last tests)

__File names that *don't* work__

* `._sync_142df90e8e0f.db`
* `._something.ext`
* `._.something.ext`

**Comment by guruz** [comment] 2017-06-16 12:09
TODO:
Is this something a file server admin would set?
Or a known Windows limitation?

**Comment by ElpyDE** [comment] 2017-06-16 12:18
PS: The "don't work" file names __do__ work on my local Windows PC.

**Comment by SamuAlfageme** [comment] 2017-06-16 12:21
@guruz 

> Is this something a file server admin would set?

https://www.lavalite.de/2008/10/12/disable-creation-of-_files-dot-underscore-files/

**Comment by guruz** [comment] 2017-06-16 12:24
@NM78 @bOOT-CoDe Can you please also try the above filenames on your setup and also ask your sysadmin if he/she knows about this? ^^

**Comment by ckamm** [comment] 2017-06-16 12:42
@ElpyDE Great, we found it!

The reason the journal file has the "._" prefix is to ensure that the new journal file won't be uploaded to the server if someone switches back from client version 2.3 to 2.2. For this reason we pick a filename that will be excluded by an ignore pattern that was already present in 2.2.

It looks like this particular prefix is often forbidden by samba configurations though. There are a couple of other ignore patterns, but is seems possible that if we called the journal `.sync_baaf.swp`, for example, this might equally be forbidden by some admins.

So maybe the most reasonable path open to us is to give up on the nice compatibility guarantee and use `.sync_baaf.db` as a journal name if the "._" name fails. (also suggested by @guruz in IRC)

**Comment by SamuAlfageme** [comment] 2017-06-16 12:54
@ckamm @ElpyDE Indeed, just tried with the veto (`veto files = /._*/.DS_Store/`) from the link in https://github.com/owncloud/client/issues/5633#issuecomment-309012411 and observed the exact same issue reproducing.

**Comment by ckamm** [comment] 2017-06-16 13:50
PR https://github.com/owncloud/client/pull/5844

**Comment by ckamm** [comment] 2017-06-16 13:58
@ElpyDE As a workaround, you could try opening your owncloud.cfg and changing the `journalPath` setting. Setting it to something like `.sync_142df90e8e0f.db.swp` might work.

**Comment by ElpyDE** [comment] 2017-06-16 14:14
@ckamm Thanks for the workaround. Works like a charm ✔️

Thank you all for your wonderful work!

**Comment by guruz** [comment] 2017-06-20 11:21
Closing in favour of PR. :)

**Closed by guruz** 2017-06-20 11:21 UTC
Labels: bug
