### ISSUE TITLE
Linux Client : Indicator Applet in the wrong place.

### ISSUE THREAD

**Issue by Tas-sos** [owncloud/client#5432] opened 2017-01-05 22:21 UTC
After a system update and a reboot of my computer, owncloud-client **indicator applet** appears in a completely wrong location.
(_In the past i had seen similar problems_)

### Expected behaviour
The indicator applet be at the right place with the rest indicators.

### Actual behaviour
The owcloud indicator applet appears at the top left.
![](http://i.imgur.com/i5wIU3q.png)

### Client configuration
Client version: 
```
owncloud --version 
ownCloud version 2.2.4 
Using Qt 5.2.1
```

Operating system:
```uname -a Linux user 3.13.0-59-generic #98-Ubuntu SMP Fri Jul 24 21:05:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

```
Distributor ID: Ubuntu 
Description: Ubuntu 14.04.5 LTS 
Release: 14.04 
Codename: trusty
```

### Installation path of client:
```
whereis owncloud
owncloud: /usr/bin/owncloud /usr/bin/X11/owncloud /usr/share/owncloud
```

### Logs
```
owncloud --logfile log.txt
Sys Info size:  364
int main(int, char**) Already running, exiting...
 
cat log.txt
01-06 00:06:12:156 0x1c33e40 application.cpp:363 "################## ownCloud el_GR (el_GR) 2.2.4"
01-06 00:06:12:156 0x1c33e40 application.cpp:386 Running for 167.812 sec
01-06 00:06:12:156 0x1c33e40 owncloudgui.cpp:782 void OCC::ownCloudGui::slotShowSettings()
```

**Comment by matlink** [comment] 2017-01-06 08:54
Got a quite similar problem (version 2.2.4-9.1), on Debian jessie with XFCE, the icon is invisible on the applet bar. Downgraded to 2.2.4-8.1 solves the problem for now.

**Comment by linkp** [comment] 2017-01-06 16:41
I expect that it's the same Qt5 problem on Ubuntu Trusty that has come up before.

**Comment by franzhartwig** [comment] 2017-01-06 17:31
I installed appmenu-qt5 nothing changed. I purged it, nothing changed.

**Comment by linkp** [comment] 2017-01-06 17:33
The solution in the past has been to keep the application on Qt4.

**Comment by Tas-sos** [comment] 2017-01-07 10:21
I did two more tests.

1. Again in another computer with **Ubuntu 14.04.5 LTS**

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

```
uname -a
Linux another-PC 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:28 UTC 2015 i686 i686 i686 GNU/Linux
```

```
owncloud --version
ownCloud version 2.2.4
Using Qt 5.2.1
```
The same problem occurred.




2. But I did a test on a **Ubuntu 16.04.1 LTS**.

### **But on this machine there is no problem!!**
**The client indicator applet, appears in the correct position!!**

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```
uname -a
Linux pc 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
owncloud --version
ownCloud version 2.2.4
Using Qt 5.5.1
```

**Comment by ogoffart** [comment] 2017-01-11 16:05
The problem is that unity uses its own protocol for the systemtray which has patches in Qt4, and ubuntu did not patch Qt5.
Qt 5.5 supports that out of the box.

In other words, we need at least Qt 5.5.

Qt 5.2 is way too old and we can't use it for it has many other bugs, including data corruptions ones.

Ideally, Qt should be part of the package for these distro

**Comment by guruz** [comment] 2017-01-20 14:05
Did you guys try to report this at Ubuntu too?

**Comment by samuelba** [comment] 2017-01-30 06:44
I have Ubuntu Trusty and Qt 5.5.1 but the icon is still in the left corner. As far as I know the same problem occurred a few months ago and was solved in the mean time, but now it's here again.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

```
owncloud --version
ownCloud version 2.2.4
Using Qt 5.5.1
```

**Comment by sghignone** [comment] 2017-01-30 10:58
I'm experiencing the same problem.
`Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04Codename:	trusty`

**Comment by franzhartwig** [comment] 2017-02-03 22:05
Fixed now.
 ```
uname -a
Linux HP-Ubuntu 4.4.0-62-generic #83~14.04.1-Ubuntu SMP Wed Jan 18 18:10:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
owncloud --version
ownCloud version 2.2.4
Using Qt 4.8.6
```
Thank you!

**Comment by iminternet** [comment] 2017-02-03 22:39
Thanks for the update, works fine again!
(And please keep the indicator that way :P )

**Comment by gnanet** [comment] 2017-02-05 04:57
Can confirm indicator is back on its place

```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

owncloud-client:amd64 (2.2.4-10.1) 
ownCloud version 2.2.4
Using Qt 4.8.6

Linux xxxxxxx 3.13.0-108-generic #155-Ubuntu SMP Wed Jan 11 16:58:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

**Closed** 2017-02-07 14:39 UTC
Labels: bug, packaging, sev2-high
