### ISSUE TITLE
Sync Stopped to work on desktop

### ISSUE THREAD

**Issue by Thomanji** [owncloud/client#3448] opened 2015-07-13 13:29 UTC
Hi,
I uprated to OC8.1 and now it does not sync any more to the desktop.
In the browser everything works fine, even on the Android it works but desctop gives issues.

In the browser admin I get this:
Exception: {"Message":"HTTP\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(82): OC\\Connector\\Sabre\\File->get()\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/html\/owncloud\/remote.php(132): require_once('\/var\/www\/html\/o...')\n#7 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":256}

in the desktop I get this:
13-Jul-15 09:14:13 PMInstantUpload/20140913_185724.jpg                               ownCloud       Operation canceled2.7 MiB   
13-Jul-15 09:14:13 PMInstantUpload/20140913_185654.jpg                               ownCloud       Continue blacklisting: Error downloading https://198.15.73.155/owncloud/remote.php/webdav/InstantUpload/20140913_185654.jpg - server replied: Service Unavailable3.1 MiB   
13-Jul-15 09:14:13 PMInstantUpload/20140913_185752.jpg                               ownCloud       Connection closed3.1 MiB   
13-Jul-15 09:14:12 PMInstantUpload/20140913_185431.jpg                               ownCloud       The item is not synced because of previous errors: Error downloading https://198.15.73.155/owncloud/remote.php/webdav/InstantUpload/20140913_185431.jpg - server replied: Service Unavailable          
13-Jul-15 09:14:06 PMInstantUpload/20140913_185654.jpg                               ownCloud       Connection closed3.1 MiB   
13-Jul-15 09:14:00 PMInstantUpload/20140913_185431.jpg                               ownCloud       Operation canceled4 MiB     
13-Jul-15 09:14:00 PMInstantUpload/20140913_185654.jpg                               ownCloud       Connection closed3.1 MiB   
13-Jul-15 09:13:54 PMInstantUpload/20140913_185431.jpg                               ownCloud       Connection closed4 MiB     
13-Jul-15 09:13:54 PMInstantUpload/20140913_185425.jpg                               ownCloud       Connection closed3.1 MiB   
13-Jul-15 09:13:47 PMInstantUpload/20140913_185331.jpg                               ownCloud       Operation canceled2.3 MiB   
13-Jul-15 09:13:47 PMInstantUpload/20140913_185425.jpg                               ownCloud       Connection closed3.1 MiB   
13-Jul-15 09:13:40 PMInstantUpload/20140913_185331.jpg                               ownCloud       Connection closed2.3 MiB   
13-Jul-15 09:13:40 PMInstantUpload/20140913_185324.jpg                               ownCloud       Connection closed3.7 MiB   
13-Jul-15 09:13:33 PMInstantUpload/20140913_185313.jpg                               ownCloud       Operation canceled3.2 MiB   
13-Jul-15 09:13:33 PMInstantUpload/20140913_185324.jpg                               ownCloud       Connection closed3.7 MiB   
13-Jul-15 09:13:27 PMInstantUpload/20140913_185237.jpg                               ownCloud       Operation canceled2.5 MiB   
13-Jul-15 09:13:27 PMInstantUpload/20140913_185313.jpg                               ownCloud       Connection closed3.2 MiB   
13-Jul-15 09:13:20 PMInstantUpload/20140910_111853.jpg                               ownCloud       Operation canceled1.7 MiB   
13-Jul-15 09:13:20 PMInstantUpload/20140913_185237.jpg                               ownCloud       Connection closed2.5 MiB   
13-Jul-15 09:13:13 PMInstantUpload/20140913_185237.jpg                               ownCloud       Operation canceled2.5 MiB   
13-Jul-15 09:13:13 PMInstantUpload/20140906_181924.jpg                               ownCloud       Operation canceled2.4 MiB   
13-Jul-15 09:13:13 PMInstantUpload/20140910_111853.jpg                               ownCloud       Connection closed1.7 MiB   
13-Jul-15 09:13:07 PMInstantUpload/20140906_181924.jpg                               ownCloud       Operation canceled2.4 MiB   
13-Jul-15 09:13:07 PMInstantUpload/20140910_111853.jpg                               ownCloud       Connection closed1.7 MiB   
13-Jul-15 09:13:00 PMInstantUpload/20140906_181924.jpg                               ownCloud       Connection closed2.4 MiB   
13-Jul-15 09:13:00 PMInstantUpload/20140906_181917.jpg                               ownCloud       Connection closed2.2 MiB   

I searched lots of things but I simply do not find a solution.
It happened after upgrading. The upgrate worked fine but than I had an error when I logged-in to the browser admin. It was telling me I have no permission. After researching I was told to deactivate webdav in the admin. I did this and could login fine to the browser admin. However the desktop did not work any more. Than I wanted to activate it again but the entry is now gone in the admin. I wonder if anyone can assist me a bit on the troubleshooting because I am out of ideas.

I run Centos 6.5 with PHP 5.4, MySql

Thank you all for the help I appreciate it.

Best wishes,
thom

**Comment by guruz** [comment] 2015-07-13 13:52
Regarding the "Connection Closed" part:
Can you configure your webserver to enable HTTP Keep-Alive and have KeepAliveRequests and KeepAliveTimeout at very high values?

**Comment by guruz** [comment] 2015-07-13 13:53
Regarding the encryption part maybe @schiesbn can help.

**Comment by RealRancor** [comment] 2015-07-14 20:08
Possible solution for the encryption thingy: https://github.com/owncloud/core/issues/17505#issuecomment-119709169

**Comment by Thomanji** [comment] 2015-07-16 13:21
Hi.
Thank you all for the assistance on this.
It seems like the 8.1 update was changing so many things that I am working already 2 days to get things to work again. This version is working since early version 6 and never had any issues after upgrades. So I guess 8.1 was major.

First at all I added
KeepAlive On
MaxKeepAliveRequests 0
KeepAliveTimeout 100

However I have a new issue. I researched a lot and because I used YUM to install, it installed it on the default http directory with an alias so all domains could access at domain.tlc/onecloud/ . But I thought it maybe created a issue with the SSL certificate. So I manually installed a fresh copy from source on a specific domain that has a valid SSL cert installed.I can login fine on the web admin and everything is there. But now I have the issue that I cant login at all using the desktop sync client.
So I get this error.
![oc1](https://cloud.githubusercontent.com/assets/8372096/8721785/6ce6ba30-2bf0-11e5-8b01-600897ee63b1.jpg)

On the YUM version I did get the update owncloud-server-8.1.0-13.1 update today which I installed but no change on the sync issue.

16-Jul-15 08:58:38 PMInstantUpload/20140910_111853.jpg                               ownCloud       Error downloading https://198.15.73.155/owncloud/remote.php/webdav/InstantUpload/20140910_111853.jpg - server replied: Service Unavailable1.7 MiB

I never had any encryption activated so I am not sure why it would have an issue with this.
I will see what you say but I need to stop on this if I can't figure it out I am on this for days and all other work is piling up. I hope we can find a solution.

Thank you all

**Comment by avrhack** [comment] 2015-07-18 05:42
I have a similar issue. 8.1 completely broke my OS X client sync. iOS and web interface are fine.....

**Comment by RealRancor** [comment] 2015-07-18 05:46
Make sure you're using the sync client in version 1.7+

**Comment by avrhack** [comment] 2015-07-18 05:57
I am always on the latest version. 1.8.4  in this case. Just sits there permanently 'discovering'.

**Comment by RealRancor** [comment] 2015-07-18 06:00
I think thats a completely different issue if your client is stuck in discovering.

**Comment by guruz** [comment] 2015-07-20 10:56
@avrhack @Thomanji if you are both confident that the _server_ update broke it and not the _client_ update, maybe @PVince81 knows what the log above mean.

@avrhack Do you have something interesting in your owncloud.log too?

**Comment by Thomanji** [comment] 2015-07-21 05:22
@guruz yes all was working perfect until the latest update. However, the problem was emerging after 2 incidents. I did update with YUM using the default repro as I always do. I than needed to create a new user and always got a message that the user already exists. I researched this issue and came to the following ticket, https://github.com/owncloud/core/issues/6572 it told me to deactivate webdav in the admin menu. I did this and I was able to create users. Then I noticed this sync issue with the client. So I am not 100% sure if this existed before deactivating webdav. I tried to reactivate it but now the item does not show any more in the admin area. I can't find anything any more mentioning the webdav in the admin. So the next thing I did was to check that I use the latest sync client, I noticed I had 1.8.1 so I downloaded the latest 1.8.4 and installed this but no change. Then I tried
 a clean environment so I installed a brand new version with new DB from the source file. All installed fine so i connected the sync client to this new install and I get exactly the same result. What is strange is that the sync with my Android phone works fine just not with the windows client. Also when logging-in using the web browser all is fine.

So to be specific to the question. It was broken with the server update that first gave a duplicate error when making users. The client was only updated after the error started.

**Comment by RealRancor** [comment] 2015-07-21 08:31
@Thomanji Just a note to the WebDAV thingy: Yoi don't disable WebDAV with this but the authentication against an external Webserver via WebDAV. The app description contains more info.

**Comment by Thomanji** [comment] 2015-07-22 04:27
Thank you for the info. It was just that after this I started having the issues and since the issue has to do with Webdav I thought it might be relevant.
I just uprated to version 8.1.0-16.1 but issue still happening.

here is the latest log message
Exception: {"Message":"HTTP\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(82): OC\\Connector\\Sabre\\File->get()\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/html\/owncloud\/remote.php(132): require_once('\/var\/www\/html\/o...')\n#7 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":256}

**Comment by Thomanji** [comment] 2015-07-22 04:30
I also have the error in the admin saying:

This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest enabling the Internet connection for this server.

I am not sure if this is connected. I will see to do some research on this since it is a strange message.

**Comment by RealRancor** [comment] 2015-07-22 04:56
I think for both messages matching issues should be available at the core issue tracker. Wondering why you're getting the first message as this is related to the encryption app.

**Comment by Thomanji** [comment] 2015-07-22 11:58
Hi, To give a quick update. I did go ahead and tryed the fix outlined here #17574 about the encription error. However, as I had mentioned before, I did never actually use the encryption and to use the fix outlined at #17574 shown that this is the case. So now I am totally stuck with this "HTTP\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist." error.

Here is what I get after doing the fix outlined in the ticket:
[root: owncloud]# ./occ encryption:migrate                                
  [InvalidArgumentException]                    
  Command "encryption:migrate" is not defined.  
  Did you mean one of these?                    
      encryption:status                         
      encryption:enable                         
      encryption:disable                        
      encryption:list-modules                   
      encryption:set-default-module             
[root owncloud]# ./occ encryption:status
 - enabled: false
 - defaultModule: 
[root owncloud]# 

So it is not activated but still gives an encryption error. 

However what is the worse is this "Server replied: forbidden" error in the desktop sync. 

Best wishes,
Thomas

**Comment by schiesbn** [comment] 2015-07-22 12:17
If you are sure that you never used the encryption, that you don't have any encrypted files you shouldn't enable it and run the migration.

If you sure that you don't have any encrypted files you can edit your database table oc_appconfig and delete all rows with the appid 'files_encryption'. This is used as the indicator that you come from the old encryption. Technically speaking this can only exits if you enabled encryption at one point in time. Even if you just clicked on "enable" and directly on "disable" again in the app menu. Maybe you did this at one point and doesn't remember?

Generally speaking that's not a client issue and I would suggest to shut down the client and resolve the issue with the web interface (nothing should happen but I would still close it just to avoid that the client upload/downloads a file by accident while the issue is not sorted out). If you can login with the web interface, download and upload files you can activate the sync client again and he should work correctly.

**Comment by Thomanji** [comment] 2015-07-22 12:46
@schiesbn its hard to say. I do not remember but since I use OC for several years I could have happened and if you say this is the only way I can have these DB entry's than I must have done it. 
In any case, I have followed the instructions and made a backup and deleted the 'files_encryption' entries in the oc_appconfig table. 
However, it looks like that my windows client issue and this encription issue was not related. The error "HTTP\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist." is not showing any more but the windows client still has the forbidden error:

22-Jul-15 08:39:41 PMInstantUpload/20141012_112913.jpg                               ownCloud       Operation canceled4.8 MiB   
22-Jul-15 08:39:41 PMInstantUpload/20141012_112912.jpg                               ownCloud       Operation canceled5 MiB     
22-Jul-15 08:39:41 PMInstantUpload/20141012_112910.jpg                               ownCloud       Operation canceled4.5 MiB   
22-Jul-15 08:39:41 PMInstantUpload/20141012_112908.jpg                               ownCloud       Error downloading https://198.15.73.155/owncloud/remote.php/webdav/InstantUpload/20141012_112908.jpg - server replied: Service Unavailable4.7 MiB   
22-Jul-15 08:39:41 PMInstantUpload/20141012_112907.jpg                               ownCloud       Error downloading https://198.15.73.155/owncloud/remote.php/webdav/InstantUpload/20141012_112907.jpg - server replied: Service Unavailable4.8 MiB   
etc.  

I am happy to troubleshoot further but if you tell me it is better to wait for 8.1.1 than I can do this. Its just weird because normally I would expect a permission error but I checked all file permissions and ownership and all seems to be fine.

Best wishes,
thomas

**Comment by schiesbn** [comment] 2015-07-22 12:48
Check your apps menu, is the "default encryption module" enabled? Also check your admin settings, is "server-side encryption enabled"? Don't enable it if it isn't

**Comment by Thomanji** [comment] 2015-07-22 13:30
Hi, both "default encryption module" and "server-side encryption enabled" is not enabled.

Interesting since now it gives a error in the webinterface as well:
"Can't read file
Module with id: OC_DEFAULT_MODULE does not exist. Please enable it in your apps settings or contact your administrator."

another one is that it does not show any thumbnail any more. However I uploaded a file from the android app and this shows a thumbnail and I can download this without issues.

files prior to the update are not accessible in the web-interface but files that were uploaded after, are fine.

**Comment by schiesbn** [comment] 2015-07-22 13:34
Can you look at the file directly on the server to see if the file was stored encrypted or not?

**Comment by Thomanji** [comment] 2015-07-23 02:27
@schiesbn Yes, you are right, they are encoded for some reason. Even though it says that nothing is encoded on the OC Server. However, I did download the data folder and checked it out. Non of the images files (Except new ones I uploaded after the upgrade) can be accessed. I checked the source and I see: 'HBEGIN:cipher:AES-256-CFB:HEND' in the start of the image source so it looks like they are encoded. I guess we now identified the issue which is most likely also the issue that the client can't access these files. 
However, as we mentioned in the above posts, non of the decrypt commands seems to work.

**Comment by Thomanji** [comment] 2015-07-23 10:02
Also just for info, here is the app:list

./occ app:list
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - contacts: 0.4.0.0
 - direct_menu: 0.3
 - documents: 0.9.0
 - external: 1.2
 - files: 1.1.9
 - files_antivirus: 0.7.0.1
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - templateeditor: 0.1
Disabled:
 - calendar
 - dashboard
 - encryption
 - files_external
 - files_locking
 - files_versions
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

the interesting part on the desktop client is that if  I try it on my fresh install it has the same issue.

**Comment by schiesbn** [comment] 2015-07-23 14:21
The header also indicates that the file was encrypted with 7.0.1 <= ownCloud < 8.1.0. So the files where already encrypted before the update. So you have basically two options:

If you want to continue to use encryption:
- go through this steps https://github.com/owncloud/core/issues/17574 or (if you didn't try yet to execute the migration, this means no ````files_encryption_backup_<timestamp>```` folders) wait for 8.1.1 and perform the migration with 8.1.1 which contain all the bug fixes

If you don't want to use encryption:
- go back to ownCloud 8.0.X
- make sure that the encryption app is disabled
- go to the users personal setting, there you should see a option to decrypt all files
- if this was successful you can again move to 8.1

Whatever path you take, first make a backup of your ownCloud installation and your data folder so that you can go back to the starting point at any time

**Comment by Thomanji** [comment] 2015-07-24 10:34
@schiesbn Hi, so yes all is working again, so the desktop client download issue was also due to the files that were still encoded. So I followed your steps and basically installed a 8.0.5 version manually on a different domain and just updated the config.php. Once I logged-in it immediately showed the message that encryption is off but some files are still encrypted. So I logged-in as each user and run the decrypt. All worked fine and once I did connect back to the 8.1 version all worked perfect.
So I am all sorted out. Please let me take this opportunity to give you a big thank you. I really appreciated that you took time and had the patience to guide me on this. Thank you very much and I also send a contribution bounty your way.

**Closed** 2015-07-24 21:44 UTC
Labels: Needs info, Server Involved

**Comment by maystar** [comment] 2015-08-11 11:09
I've have the exact same problem on my opensuse server with the owncloud rpm installation. I've never used the server encryption. After the upgrade from 8.1 to 8.1.1 the client synchronisation works, but after enabling the server apps I got the errors mentioned above. I use these apps:
```
occ app:list
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mozilla_sync: 1.4
 - music: 0.3.5
 - news: 5.3.9
 - tasks: 0.7.1
Disabled:
 - encryption
 - external
 - files_locking
 - files_sharing
 - files_videoviewer
 - galleryplus
 - jsxc.owncloud
 - provisioning_api
 - search_lucene
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth
```

Is there any other workaround? I can't login as each user since I do not know each password. Disabling the apps again does not help.

**Comment by guruz** [comment] 2015-08-11 11:11
@maystar Please create a new issue in the core repo: https://github.com/owncloud/core/issues/

**Comment by PVince81** [comment] 2015-08-11 11:13
@maystar if it worked before enabling third party apps then please disable the third party apps one by one until it works again to identify which app is causing trouble.
