### ISSUE TITLE
[Linux] ownCloud client does not notice connectivity changes, does not offer to re-connect

### ISSUE THREAD

**Issue by RalfJung** [owncloud/client#4137] opened 2015-11-13 12:15 UTC
I have the ownCloud client 2.0.2 (as packaged in Debian testing) running on my laptop. Is it is common with laptops, the connectivity frequently changes: I may be in a Wifi, switching to LAN, be entirely offline for some time, and go back to some Wifi. The ownCloud clients does not cope with this well. Here's what happens frequently:

* I boot up the machine while having connectivity. The ownCloud client starts, and it is happy and green.
* I suspend the laptop.
* I resume it, and it takes ~30sec to re-gain connectiviy (slow Wifi, slow, DHCP, whatever).
* During these 30sec, ownCloud goes to the "offline" state, having three dots in the systray icon and adding a red warning in the main window:
![screenshot from 2015-11-13 13-03-26](https://cloud.githubusercontent.com/assets/330628/11145679/feaa4c32-8a07-11e5-8573-04a5b49f78fc.png)
* Soon thereafter, I am online again.

The trouble is, ownCloud does not notice that I am back online. Of course network manage always knows the current connectivity, so ownCloud could listen to the appropriate event from network manager, and attempt to re-connect when I am back online. (Other programs do that successfully, so NM is working fine here.) But even if ownCloud for some reason does not want to talk to NM, it should somehow be able to notice that I am back online - maybe it checks every 30min, or whatever. Instead, I have seen ownCloud staying in this false offline state for hours. Furthermore, I was unable to find a button that says "Reconnect", or anything else to manually trigger another attempt of connecting to the ownCloud server. All I can do is re-start the client. I have to re-start the client twice a day just to be sure that I don't accidentally work on outdated data.

**Comment by simonbru** [comment] 2015-11-15 09:51
It has been weeks since I started having this issue on Archlinux.
I got used to do `pkill owncloud; setsid owncloud` in a terminal whenever I get out of sleep mode, but it is far from an ideal workaround.

**Comment by nenjordi** [comment] 2015-11-15 10:13
Same happens to me. A reconnect button would be more than enough as a fast solution.

**Comment by simonbru** [comment] 2015-11-15 12:57
I wrote a small script to restart the owncloud client when network manager is connected and owncloud was already open:
/etc/NetworkManager/dispatcher.d/owncloud-restart
```
#!/bin/bash

USER=<username>
IF=$1
STATUS=$2
 
if [[ "$IF" == "eth0" ]] && [[ "$STATUS" == "up" ]]; then
    if pgrep -u $USER owncloud
    then
        sudo -u $USER -i -- /bin/bash --login <<'EOF'
            killall owncloud
            export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus
            DISPLAY=:1 owncloud &
EOF
    fi
fi
```

It is pretty hacky but for what I tested it seems to work most of the time.
I don't know if it works on other distributions, maybe the dbus session address is different. I also had to enable the service NetworkManager-dispatcher.service and had to make sure that my script was owned by root and not writable by anyone else.

**Comment by nenjordi** [comment] 2015-11-15 20:50
Wonderful @simonbru 
I modified it a bit.
It kills all owncloud instances when disconnected and creates a file in /tmp/ that indicates that owncloud needs to be launched. Then with crontab that file is checked, owncloud launched and delete the file. I just didn't like having sudo around ;)

```bash
#!/bin/bash

case "$2" in
   up)
        touch /tmp/owncloud_need_restart.ERASEME
        chown putyouruserhere /tmp/owncloud_need_restart.ERASEME
        ;;
    down)
        killall owncloud
        ;;
esac
```

In crontab for the user:
```
*/10 * * * *    $HOME/bin/owncloud.sh
```

owncloud.sh
```bash
#!/bin/bash

if [ -e /tmp/owncloud_need_restart.ERASEME ]
then
    rm /tmp/owncloud_need_restart.ERASEME
    owncloud&
fi
```

**Comment by tflidd** [comment] 2015-11-16 08:39
Duplicate of https://github.com/owncloud/client/issues/4051

**Comment by guruz** [comment] 2015-11-16 13:26
@tflidd Thanks!

**Closed by guruz** 2015-11-16 13:26 UTC
