### ISSUE TITLE
Configuration on where to place the sync journal

### ISSUE THREAD

**Issue by gig13** [owncloud/client#2854] opened 2015-02-17 17:06 UTC
Either as a default or as an option - to store the sync journal somewhere under .local/share/owncloud instead of in the data directory.

This originated from an error message when using AFS. _csync_file_stat_from_metadata_table: WARN: Query results in 11 -> SQLite status code 11 means "database corrupted".

See also: 
http://stackoverflow.com/questions/5468349/sqlite-compatible-with-openafs-locking

As a workaround in the short term, there is probably no choice but to warn our users not to sync AFS folders with ownCloud.

**Comment by danimo** [comment] 2015-02-17 17:41
I need the exact use case. I.e. why should ownCloud's data be on an AFS partition? It's a local _per machine_ copy, so it may not be shared amongst different machines anyway.

**Comment by MTRichards** [comment] 2015-02-17 18:18
This should go back into the enhancement request queue in SFDC, as this is a feature request.

**Comment by gig13** [comment] 2015-02-17 18:31
@MTRichards 
It has been added in SFDC. Should I only create in SFDC and not in github?

**Comment by moscicki** [comment] 2015-02-17 18:39
@danimo: at least one use case for AFS is simple: in some environments your home directory is on AFS. Sometimes this is a configuration choice on the desktop but sometimes not (for central login services where you have login nodes behind a load balanced DNS, for example). But in that case there is no other choice but to keep the sync journal on AFS too.

**Comment by danimo** [comment] 2015-02-17 18:42
@moscicki The client can be customized to have the location outside the home, but I see your point.

**Comment by moscicki** [comment] 2015-02-17 18:47
For AFS you should also keep in mind that even if you put sync journal on a local partition, the inotify will not always be reliable. To be more precise, you will only get notifications about file operations performed on the same node as the sync client is running. If you create a file in the AFS data directory from another machine you will most likely never get a notification. If you want to cover that case you should assume some periodic scan of the whole tree (what we hope not to be needing for local disks and standard desktop/laptop environments with 1.8.0)....

**Comment by danimo** [comment] 2015-02-17 18:49
@moscicki Isn't that just another point for not supporting AFS in the first place? If we do periodic scans, I can see laptop users on Battery running in circles with Pitchforks and torches. :-)

**Comment by moscicki** [comment] 2015-02-17 18:58
Well, on my (personal) priority list I would very much prefer to vastly improve support for laptops and desktops on local disks (in terms of energy consumption and scalability to 100Ks files) in a sync folder. I don't mind if AFS support is somewhat crippled. I hope my colleagues agree (we have 20K home directories on AFS here)....

**Comment by guruz** [comment] 2015-02-25 13:30
@moscicki @gig13 Do you know if this is a regression?
We have changed the sqlite3 log-mode (for performance reasons) which however had regressed on VFAT on Windows. If this is a regression, then this is probably also a problem for AFS? Or the regression is related to us now using the DB in parallel from several threads (because of the overlay icons).

CC @ckamm

**Comment by ckamm** [comment] 2015-02-25 14:05
The discussion on stackoverflow indicates that DB locking doesn't work on AFS. It suggests we could special-case it by detecting AFS and then using the unix-dotfile locking mode.

That sounds different than the WAL+exFAT issues we've seen. It would nevertheless be worth to experiment with that. @moscicki If you can reproduce the issue, can you try with the environment variable OWNCLOUD_SQLITE_JOURNAL_MODE=DELETE set?

**Comment by gig13** [comment] 2015-04-17 19:12
@dragotin @MTRichards @cdamken 
Any updates here? Reaching out in regards to SF 2609

**Comment by cdamken** [comment] 2015-04-23 07:37
@gig13 SF 00002609 is closed

Should be done something here?

**Comment by gig13** [comment] 2015-04-23 11:23
@cdamken 
Yes SF is closed since it is a Feature Request. Please provide updates as needed, maybe with a Task.

See the last comment in the case:
"Might be possible not entirely sure.
But without that, we don't support AFS as a sync filesystem today."

**Comment by dragotin** [comment] 2015-04-23 12:05
@gig13: The update that you ask for was there from feb 25th where @ckamm asks for another test with an environment variable set. Any chance to test that?

**Comment by cdamken** [comment] 2015-05-26 11:35
@dragotin the solution is expected to work "OWNCLOUD_SQLITE_JOURNAL_MODE=DELETE "

I will provide more information if the problem still happens again

**Comment by dragotin** [comment] 2015-06-26 08:28
@cdamken ok to close this?

**Comment by guruz** [comment] 2015-08-03 15:20
> This originated from an error message when using AFS. _csync_file_stat_from_metadata_table: WARN: Query results in 11 -> SQLite status code 11 means "database corrupted".

@gig13 @moscicki Is this just the warning or does it fail the sync?
If it is the former: We need to fail the sync! Can't just warn and then do bogus things..

**Comment by cdamken** [comment] 2015-08-05 13:35
@guruz @dragotin From my side we can close this.

**Comment by guruz** [comment] 2015-08-06 15:47
Keeping this open a bit to verify that we abort the sync on ```WARN: Query results in 11```

**Closed** 2015-09-02 12:24 UTC
Labels: blue-ticket, enhancement - proposed, Needs info

**Comment by gig13** [comment] 2015-09-02 12:34
@dragotin @MTRichards 
Was this rejected -- This was a feature request -- Why is it closed?

**Comment by MTRichards** [comment] 2015-09-02 15:22
Not entirely sure, but probably because @cdamken said ok to close.

Net is: Some testing should be done as requested above, but right now, we don't support AFS. I don't have a plan to add this anytime soon.

**Comment by cdamken** [comment] 2015-09-11 20:03
@gig13 I received  this information long long time ago:
```
I'll try the with OWNCLOUD_SQLITE_JOURNAL_MODE=DELETE next week,
but if this forces the dotlock method, I guess that should work. 
```
And no more answer, I suppose it works. If there are more comments I'll reopen it.
