### ISSUE TITLE
leftover files in directory excluded from sync

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5248] opened 2016-10-12 18:17 UTC
I have managed to create a state on my sync client where "tmp" directory is excluded from sync however there files in "tmp" directory are not deleted by the client. This involved having a rule to ignore a subdirectory "tmp/X/" in the "Edit Ignore File" list. In the meantime I also updated from 2.1.1 to 2.2.4 and I am since a couple of days in a shaky network where sync operation is interrupted on a regular basis.

Here is the state:

![image](https://cloud.githubusercontent.com/assets/621965/19322024/3d2be82e-906c-11e6-912d-deac6ceb4a10.png)

    sqlite> select * from selectivesync;
    path|type
    2ARCHIVE.tmp.test2/|1
    ARCHIVE.tmp.test/|1
    tmp/|1

In the csync database there is no trace of "tmp" tree (there is just another unrelated top level directory called tmp.readonly):

    sqlite> select * from metadata where path like "tmp%" limit 10;
    phash|pathlen|path|inode|uid|gid|mode|modtime|type|md5|fileid|remotePerm|filesize|ignoredChildrenRemote|contentChecksum|contentChecksumTypeId
    -1276242458355704335|12|tmp.readonly|13084859|0|0|0|1469541384|2|b1db51:1469541384.613|11656017|RWCKNVD|0|0||0

In the meantime I removed the "tmp/X/" rule from ignored files (sync-exclude.lst  is empty) but it does not change anything in the system behaviour. I would expect that if I toggle selective sync back and forth it would take an action to remove the tmp files.

The files do exist on the file system (but only a subset, around 1GB not 2.3GB reported by the server):

    $ ls tmp | head
    1-MB
    100MB.zero2
    10M.dat
    10MB
    2.50-M.txt
    3.50-M.txt

 Note: when I toggle the button I do not wait to download all remaining 2.3 GB files because I am running out of space.

Actually, running out of space is also what happened to me recently so this may also have lead to this state.

Sorry for long description but I am not able to fully reproduce this exact state. However, if you play around with "tmp/X/" ignore rule and selective sync you will see that sometimes files are left over (depening on the order of these operartions and also whether the files existed before or after performing these operations).

**Comment by moscicki** [comment] 2016-10-12 18:45
There could also be another reason for this: is that probably I have some files which need to be uploaded. Hence the selective sync will not delete the entire directory.

I just did this test excluded from sync a directory while files were uploaded. It does not delete anything from the directory. This of course makes sense for data protection. On the other hand, the selective sync needs some love in general because there is a genuine 2 use-cases: excluding a local directory from synchronization without affecting local files and "archiving" a directory which is already synchronized (as it is currently attempted). These are two different purposes and affect either local or remote folders.

**Comment by ogoffart** [comment] 2016-10-13 07:38
In order to prevent data loss, we do not delete files which were not uploaded to the server.
That's the expected behavior

**Comment by ogoffart** [comment] 2016-10-20 08:23
I'm closing this issue because it works as expected.
I am pretty sure that the files that are still there were not uploaded to the server. (Or the client did not know they were uploaded because the connection broke before the server could send the etag)

**Closed by ogoffart** 2016-10-20 08:23 UTC
