### ISSUE TITLE
Files ignored for unknown reason

### ISSUE THREAD

**Issue by andergnet** [owncloud/client#2230] opened 2014-09-21 17:57 UTC
### Steps to reproduce
- Just a basic install of the client.

I have two folders to sync:
/home/usuario/ownCloud -> ownCloud/sync
/mnt/Documentos/Mis Documentos/Ander/Fotos -> ownCloud/Fotos

### Expected behaviour
The "Fotos" (photos) folder has many subfloders organized by year and event and in total there 14K files adding up 38GB (but no more than a cuple of hundred files in each subfolder.

I expected the client to sync with the server every picture in those folders.

### Actual behaviour
Most of the photos are being deliverately ignored by the client (as it can be read in the log, INSTRUCTION_IGNORE). However, I can't see any matching file excluding patterns and it doesn't seem to be any forbbiden characters.

### Server configuration
I don't know much about it since it's an external service but the status.php page says this:
{"installed":"true","version":"7.0.2.1","versionstring":"7.0.2","edition":""}

### Client configuration
I'm running the desktop client on Ubuntu 14.04 x64. 
The "Fotos" folder's drive has NTFS format since it was originally part of a Windows instalation.
The ownCloud sync client version is 1.6.3
I've not touched exclude file patterns, it's the default.

#### ownCloud log (Brief, the full log was 14MB in size, it didn't seem reasonable to copy/paste it in here, if you need it just ask me and I'll send you)

09-21 11:10:04:727 csync_walker: file: /mnt/Documentos/Mis Documentos/Ander/Fotos/2014/2014-Otras/20140627_001.jpg [file_id=]
09-21 11:10:04:727 _csync_detect_update: file: 2014/2014-Otras/20140627_001.jpg, instruction: INSTRUCTION_IGNORE <<=
09-21 11:10:04:727 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0
09-21 11:10:04:727 csync_walker: file: /mnt/Documentos/Mis Documentos/Ander/Fotos/2014/2014-Otras/20140718_001.jpg [file_id=]
09-21 11:10:04:727 _csync_detect_update: file: 2014/2014-Otras/20140718_001.jpg, instruction: INSTRUCTION_IGNORE <<=
09-21 11:10:04:727 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0
09-21 11:10:04:727 csync_walker: file: /mnt/Documentos/Mis Documentos/Ander/Fotos/2014/2014-Otras/20140818_001.jpg [file_id=]
09-21 11:10:04:728 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0
09-21 11:10:04:728 _csync_detect_update: Checking for rename based on inode # 59513
09-21 11:10:04:728 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE inode=?1: 0
09-21 11:10:04:728 _csync_detect_update: file: 2014/2014-Otras/20140818_001.jpg, instruction: INSTRUCTION_NEW <<=
09-21 11:10:04:728 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0

### Tests
I asked for help in the forums and I've already made some tests to try and solve the problem with no luck:
1) I tried to remove the whitespace in "Mis Documentos"
2) I tried to sync the files from multiple points. Example:
      · /mnt/Documentos/Mis Documentos/Ander/Fotos/
      · /mnt/Documentos/Mis Documentos/Ander/Fotos/2014/
      · /mnt/Documentos/Mis Documentos/Ander/Fotos/2014/2014-Otras/
3) I deleted the .csync_journal.db and re-run the client.

In any case it didn't work as expected.

I'm still unsure about this being a bug and not me doing some wired thing, I hope you can help me. If you need any further info please contact me.

**Comment by ogoffart** [comment] 2015-06-29 09:08
YEs that's NTFS.  And NTFS uses hard links internally.

This is a duplicate of #3241

**Closed by ogoffart** 2015-06-29 09:08 UTC
Labels: bug
