### ISSUE TITLE
Cannot start owncloud-client-2.1.0-1.1.x86_64 - CentOS Linux release 7.2.1511

### ISSUE THREAD

**Issue by pixel-paul** [owncloud/client#4292] opened 2015-12-16 10:48 UTC
$ owncloud
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: eglfs, kms, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

**Comment by jnweiger** [comment] 2015-12-16 15:37
@pixel-paul 
The error message list 'xcb' as both available and missing.  That is strange. Do you have a second machine where you can reproduce the issue?

**Comment by pixel-paul** [comment] 2015-12-16 16:00
@jnweiger - no machine set up currently. 

$ ldd /usr/bin/owncloud | grep xcb
$ 

any use?

**Comment by jnweiger** [comment] 2015-12-16 16:15
I'd say it is an indirect dependency via some qt library. I've never heared the name before, so it cannot be directly related to owncloud.

**Comment by pixel-paul** [comment] 2015-12-16 16:20
What reqs have changed since 2.0.2, as this was installed and working.

**Comment by pixel-paul** [comment] 2015-12-16 16:55
Looking at my yum install log I can see several qt libraries were updated.

Dec 15 13:03:34 Updated: 1:qt-4.8.5-11.el7.x86_64
Dec 15 13:04:56 Installed: opt-qt5-qtbase-5.4.2-3.1.x86_64
Dec 15 13:09:40 Installed: opt-libqt5keychain0-0.5-3.1.x86_64
Dec 15 13:15:08 Updated: 1:qt-x11-4.8.5-11.el7.x86_64
Dec 15 13:31:59 Installed: opt-qt5-qtbase-gui-5.4.2-3.1.x86_64
Dec 15 13:32:06 Installed: opt-qt5-qtwebkit-5.4.2-2.1.x86_64
Dec 15 13:57:38 Installed: compat-poppler022-qt-0.22.5-4.el7.x86_64
Dec 15 13:57:43 Updated: poppler-qt-0.26.5-5.el7.x86_64
Dec 15 14:00:17 Updated: 1:qt-mysql-4.8.5-11.el7.x86_64
Dec 15 14:02:54 Updated: 1:qt-4.8.5-11.el7.i686
Dec 15 14:03:24 Updated: 1:qt-x11-4.8.5-11.el7.i686

Perhaps associated?

**Comment by ogoffart** [comment] 2016-01-08 11:48
There seems to be a is a problem with  the Qt installation.  xcb is a plugin  (/usr/lib/qt/plugins/platforms/libqxcb.so on my system)  which is dynamically loaded.   It seems that Qt cannot load that plugin. Than could happen if the plugin is for a differnet version of qt for example if there are two qt installed on the system.   QT_PLUGIN_PATH should be set so it find the right plugin

**Comment by pixel-paul** [comment] 2016-01-08 12:54
I don't have that plugin in that location on my system. 

$ locate libqxcb.so
/home/pixel-paul/.dropbox-dist/dropbox-lnx.x86_64-3.12.5/plugins/platforms/libqxcb.so
/home/pixel-paul/VMImages/BlackBerry10Simulator-BB10_3_1-995/controllers/platforms/libqxcb.so
/opt/HipChat/lib/plugins/platforms/libqxcb.so

**Comment by ogoffart** [comment] 2016-01-08 14:24
nothing coming from opt-qt5-qtbase ?

**Comment by pixel-paul** [comment] 2016-01-08 16:15
ok, so I have reinstalled owncloud-client (I had cleaned everything up before) and there is now a

**Comment by pixel-paul** [comment] 2016-02-08 17:21
This is still an issue with owncloud-client.x86_64 0:2.1.0-11.1

**Comment by jnweiger** [comment] 2016-02-09 14:26
When testing the installation on CentOS7 here, I get libxcb-1.11-4.el7.x86_64 and friends installed:

<pre>
# rpm -qa | grep xcb
xcb-util-image-0.4.0-2.el7.x86_64
compat-libxcb-1.9-1.el7.x86_64
xcb-util-renderutil-0.3.9-3.el7.x86_64
xcb-util-keysyms-0.4.0-1.el7.x86_64
libxcb-1.11-4.el7.x86_64
xcb-util-0.4.0-2.el7.x86_64
xcb-util-wm-0.4.1-5.el7.x86_64
</pre>

Tested with owncloud-client-2.1.1-0.1.1.rc2.x86_64 - No issues here. Runs smooth.

**Comment by pixel-paul** [comment] 2016-02-09 14:34
Here is mine:

```
$ rpm -qa | grep xcb
libxcb-devel-1.11-4.el7.x86_64
xcb-util-keysyms-0.4.0-1.el7.x86_64
xcb-util-cursor-0.1.2-2.el7.x86_64
xcb-util-cursor-devel-0.1.2-2.el7.x86_64
xcb-util-renderutil-0.3.9-3.el7.x86_64
xcb-util-keysyms-devel-0.4.0-1.el7.x86_64
xcb-util-0.4.0-2.el7.x86_64
xcb-util-devel-0.4.0-2.el7.x86_64
xcb-util-renderutil-devel-0.3.9-3.el7.x86_64
libxcb-1.11-4.el7.i686
libxcb-1.11-4.el7.x86_64
xcb-util-image-0.4.0-2.el7.x86_64
xcb-util-image-devel-0.4.0-2.el7.x86_64
xcb-util-wm-0.4.1-5.el7.x86_64
xcb-util-wm-devel-0.4.1-5.el7.x86_64
```

So am missing  compat-libxcb-1.9-1.el7.x86_64 ?

**Comment by pixel-paul** [comment] 2016-02-09 14:35
And bingo. 

```
$ sudo yum install  compat-libxcb-1.9

Installed:
  compat-libxcb.x86_64 0:1.9-1.el7
```

Owncloud up and running.

**Comment by jnweiger** [comment] 2016-02-09 14:52
Ah, great you found this. 

compat-libxcb is no direct dependency of owncloud, but it provides 
libxcb-sync.so.0()(64bit) which is needed by (installed) opt-qt5-qtbase-gui-5.4.2-4.1.x86_64

Your log has 
Dec 15 13:31:59 Installed: opt-qt5-qtbase-gui-5.4.2-3.1.x86_64
-> this *should have* pulled compat-libxcb.

Closing here, as it looks like a local issue on your side.

**Closed by jnweiger** 2016-02-09 14:52 UTC
Labels: bug, packaging

**Comment by pixel-paul** [comment] 2016-02-09 14:54
Ok thanks for you help @jnweiger - nice to have it back up and running :+1:
