### ISSUE TITLE
Abuse of GET when showing picture galery

### ISSUE THREAD

**Issue by mnlipp** [owncloud/client#3042] opened 2015-03-30 08:57 UTC
When I start the picture gallery app and click on one of my folders, the spinner starts and nothing happens. The apache log shows:

> xxx.xxx.xxx.xxx - - [30/Mar/2015:09:14:14 +0200] "GET /owncloud/index.php/apps/gallery/ajax/thumbnail/batch?token=&image=...  414 709 "-" "-"

And indeed 414 is quite okay, because the URL hits apache's 8190 bytes limit (it is cut off in the log, so I don't know how long it really is). There are two problems with this.

1. Obviously the error code (414) of the ajax call is ignored.
2. GET shouldn't be used to pass this amount of data.

I never got quite familiar with PHP (IMHO ugly syntax) but it seems to be possible to issue the ajax call as POST as well, see http://stackoverflow.com/questions/5004233/jquery-ajax-post-example-with-php.

**Comment by LukasReschke** [comment] 2015-03-30 09:07
Dupe of https://github.com/owncloud/gallery/issues/172

**Closed by LukasReschke** 2015-03-30 09:07 UTC
