### ISSUE TITLE
Word 2013 "Strange/Ghost file" when syncing Word file with the file open.

### ISSUE THREAD

**Issue by alexthetester** [owncloud/client#3073] opened 2015-04-07 13:29 UTC
When I have a Word file that is opened in two locations, one changes,saves and closes the file while the other resyncs this file while still having it open will create a strange ghost file (see image) that has a random name and extension which is the actual new word file but has no word association nor is the original word file updated. When you manually remove the weird ghost file the sync updates the actual word file which is the only known fix as far as I know which is unacceptable.

Does anybody know a fix for this problem or am I missing something because this is a definite no go for our company and our clients if this issue isn't resolved.

Steps to reproduce:
1: Create Word 2013 file (2010 and 2007 should have this issue as well)
2: Let it sync to both sides
3: Open file on both sides
4: Edit, save & close file on one side
5: The side that still has the file opened gets a "ghost file" & goes into a sync loop, it constantly says it updated one file until you manually remove the "ghost file" after which the issue is resolved.
See picture for the "ghost file" : http://imgur.com/CvpMhG1

Expected behaviour:
Should not create the ghostfile.
Else it should remove ghostfile automatically to kick off proper resync (which is currently the manual work around) or wait with resync till word file is closed as I have a feeling this issue arises due to the file recovery file newer Office products create.

Server configuration:
**Operating system: Ubuntu 14.04
**Web server: Apache 2.4.7
**Database: Mysql 5.5.35
**PHP version: PHP 5.5.9
**ownCloud version: 8.02 
**Updated from an older ownCloud or fresh install: Fresh install
**List of activated apps: Default

Client configuration:
Windows 7: 1.8.0 (build 4847)
Windows 8.1: 1.8.0 (build 4893)
Both have the latest updates.

**Comment by guruz** [comment] 2015-04-08 10:03
> goes into a sync loop, it constantly says it updated one file until you manually remove the "ghost file" after which the issue is resolved.

Can you explain this sync loop a bit more in detail? How fast/often does it loop?

Also, what happens if you close Word? Does it rename the ghost file to the real filename?

**Comment by dragotin** [comment] 2015-04-08 11:44
The ghostfile is created by the sync client to store the received data of the file in during download. Once the download is finished, the file is moved to the final destination. If that works. In the word case with opened word, that does not work because word holds a lock on the target file on windows.

**Comment by alexthetester** [comment] 2015-04-08 13:18
@Guruz & Dragotin Thank you for the fast responses.

The loop on Windows 8.1:  There is a message that pops up in the systemtray area that shows Owncloud changed one file. This pops up about every 10-30 seconds, it seems a little random though as after another test when I check the activity log it shows 1 entry of "access denied", 3 entries of "process has no acces to the file because it is being used by another process" and then 1 entry that says "the file has been added to the ignore list" but a previous test shows several "process has no access.. .. used by another process".

Closing Word: I closed the word client on both sides and waited for a while because I assumed this was due to the word locking feature. I assumed that this would fix it but for some reason it does not delete/change/rename the ghostfile. The pop up seems less frequent after closing Word.
After closing Word the message pops up one more time and then seems to cease, I say seem because sometimes it does pop up once or twice after closing Word but then seem to cease completely. 
If I open the Word file again it does give another pop up but does not loop, after closing again it gives another final pop up saying Owncloud changed one file but it in fact did not change the Word file (if any). 

I just did another test and this issue happens differently on the W7 as the W8.1 client. The only difference being that on Windows 7 it pops up the message twice and does not loop when the word file is open like W8.1 does. Both had Word closed for about 10 minutes yet the Ghostfile is still there. As before, after deleting the ghostfile the document updates correctly, it does say it changed 2 files after doing this.

- The Ghostfile seems to have the correct file size so it does seem to transfer the data correctly, how ownCloud finalizes that process seems to have some problems.
- In ownCloud at the Activity part it does say (translation): The proces has no access to the file because it is being used by another process. These notifications seems to correlate to when the pop ups show up however Word is closed on both systems and I do not see it running under processes.
- There is also one entry after the ghostfile got created and after opening the Word file again that says (translation): "The file has been added to the ignore list" but this entry vanished after a few seconds from the activity log which is quite strange on its own in my opinion.

**Comment by ogoffart** [comment] 2015-04-08 15:00
This file is totally normal.  But it should be hidden. I suppose you are seeing it because you checked the option to see hidden file in your explorer.

**Comment by alexthetester** [comment] 2015-04-09 07:13
@ogoffart 

The file is not see trough however I believe you the file is totally normal but it is not finishing what it is for. It stays there, the word document that got changed stays the same on the client who has this file.

Only a manual delete of this file forces ownCloud to sync the file properly. I assume this behaviour is not normal.

**Comment by ogoffart** [comment] 2015-04-09 07:37
You mean it stays there even after the word was closed?
Then there is indeed a bug.

**Comment by alexthetester** [comment] 2015-04-09 07:42
@ogoffart 

Yep, for some reason the file stays there even when Word is closed on both sides.

Tested this on the Windows 7 and Windows 8.1 clients and both still have the file forever it seems.

The weird part is that I vaguely remember such a file popping up for a few seconds before disappearing when I first started ownCloud but this was not with Word files since I did not install Office on the test environment yet when that happened. So the function does seem to work and is purely related to Word (and probably other Office products as well).

**Comment by ckamm** [comment] 2015-04-09 12:20
It could be that the temporary file is not made use of right now because the file has been added to the temporary error blacklist because of all the errors. A successful sync should happen eventually - or if you press the 'retry sync' button in the 'Activity' tab.

**Comment by alexthetester** [comment] 2015-04-09 12:42
@ckamm 

I will do a longer test to see if the file disappears after a longer time and I will post the results here. It might be due to the blacklist but this will result in problems in a real life deployment because many users tend to keep certain documents open which will result in this issue and the ghostfile being blacklisted.

Pressing the resync button is not a solution for users if I am totally honest. "It just needs to work" to quote most of our users/clients.

**Comment by ogoffart** [comment] 2015-04-09 12:50
Normaly it should not be blacklisted because renaming it is a SoftError when renaming the temporary file fails. 
Also It needs a HTTP error code to be blacklisted.

**Comment by ckamm** [comment] 2015-04-09 12:56
@ogoffart Any normal error can be blacklisted. We changed that because blacklisting is always temporary now. If it's a soft error it will indeed not be blacklisted.

**Comment by ckamm** [comment] 2015-04-09 12:57
@ogoffart You were right it only affects things with http error codes, the code was not where I expected it to be.

**Comment by ckamm** [comment] 2015-04-10 08:46
@alexthetester Did the temporary file go away by now? If it didn't, does it go away if you click 'Retry Sync'?

I'm currently assuming the file will be used and deleted during the next sync run. Closing Word does not trigger a new sync run. Maybe the client should keep track of locked files, check whether they're still locked regularly and trigger a sync if the status changes.

**Comment by dragotin** [comment] 2015-04-10 09:50
Yes, tracking of the locked files would be awesome I guess. 

Here are some thoughts about that:
http://stackoverflow.com/questions/7621248/wait-for-file-to-be-unlocked-windows

However it might be easier to have a timer that checks frequently if the file can now be written or read.

**Comment by alexthetester** [comment] 2015-04-10 11:13
@ckamm 

I've left the systems on overnight to see if the temp file would go away by its own but after a 12+ hour test it did not go away when testing the windows 8.1 system. After the same test on the Windows 7 system the file is still there after 4 hours so it does not seem to go away on its own on either of the systems.

Pressing the resync button works on the Windows 8.1 client but for some reason it takes a while before it works on the Windows 7 client, the first few times of clicking the resync button resulted in the temp/ghost file disappearing for a second before coming back. After a few attempts/minutes it did work on the Windows 7 client as well.

Extra info: 
I have updated the W7 client to the latest ownCloud client (released 2 days ago?) so it is on the same build as the W8.1 client which received the update a little sooner. (build 4893)

On both sides when you restart the system it shows 4 resync messages in quick succession stating ownCloud modified one file, then the messages stop. I assume the file has been added to ignore list at that point.

**Comment by ckamm** [comment] 2015-04-10 11:23
@alexthetester I was wrong about the ignore list/blacklist, the file shouldn't be added to it. If you could provide a log of the desktop client that would be very helpful. If the temporary file doesn't go away on its own something must be going on that we're not aware of yet. 

See https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly for how to obtain log files.

**Comment by alexthetester** [comment] 2015-04-10 12:37
@ckamm 

What I did:
Opened same Word file on W7 & W8.1 clients.
Made a change, saved and closed the Word file on the W8.1 client
Kept the Word file open for a minute on the W7 client which results in the temp/ghost file.
Closed Word file on the W7 client after a few seconds and waited for aprox 3 min.
- Logs from the W7 client: http://www.filedropper.com/owncloudlogfromw7

I did the same thing but the other way around for the other system:
- Logs from the W8.1 client: http://www.filedropper.com/owncloudlogfromw81

The logs are from the system that has the temp/ghost file during the tests, I could also upload the logs of the systems that do not have the temp/ghost file during the tests if you prefer. I didn't because the activity log on those systems just show uploaded and nothing more, they seem fine.

Hopefully this helps!

**Comment by ckamm** [comment] 2015-04-10 13:03
@alexthetester Thanks for the data! Unfortunately the client doesn't yet know to try again once you've closed Word on W7. Could you, after you've done that, open the `Account` tab on the owncloud settings dialog and hit F6? That will immediately schedule a new sync. Quit it after it's done and upload the log file.

That should hopefully tell me why it doesn't rename the file after Word has unlocked it.

**Comment by alexthetester** [comment] 2015-04-10 13:17
@ckamm 

I did the same test making changes,saving,closing on the W8.1 and using the W7 as the recipient of the temp/ghost file.

- Logfile: http://www.filedropper.com/owncloudlogfromw7withf6

I might have scheduled an immediate resync twice or thrice because I did press the F6 button multiple times after the first time because I did not see anything happen right away, if this impacts the results please let me know and I will do the test again.

**Comment by ckamm** [comment] 2015-04-10 13:28
@alexthetester The owncloud client repeatedly tries to rename your testdocument.docx.~74ff to testdocument.docx but fails. The first time the error message is "Access denied" and then "The process can not access the file because it is being used by another process". Can you verify Word is fully closed?

If it is, who is locking the file? Could you try this? http://superuser.com/questions/117902/easy-way-to-find-out-which-process-is-locking-a-file-or-folder-in-windows

**Comment by alexthetester** [comment] 2015-04-10 14:00
I remember checking processes to see if I could see any Word processes open but I did not see any however I am not aware of every weird named process Word might use.

I restarted the W7 client and started ownCloud with logging to make sure Word was off
-Logfile: http://www.filedropper.com/owncloudlogfromw7afterrestart

I installed Sysinternals Process Explorer and went to Find > Find Handle or DLL > put in C:\users\a.aap\ownCloud\Bedrijf A\Notulen\testdocument.docx but it finds 0 matching items. 
I also restarted ownCloud to make it try to resync again (the 4 messages before nothing happens) but this also resulted in 0 matching items.
I also tried this for the temp/ghost file just to be sure which also resulted in 0 matching items.

Am I doing something wrong perhaps?

**Comment by alexthetester** [comment] 2015-04-15 11:48
@ckamm Did you guys find anything new yet or did I indeed make a mistake in my previous post or is this issue still a mystery? 

I am currently making a comparison "build" between Owncloud and another product so there is no rush for a fix, I'm happy enough that you guys jumped on it so fast :)

**Comment by ckamm** [comment] 2015-04-15 11:57
@alexthetester I don't know what's going on. The operating system reports to us that it can't rename the temporary file to its final name, but you say no process is locking the file. Why does that happen?

Can you edit the file with another program, like Wordpad? But I'm not sure what information we'd actually need to resolve this.

**Comment by alexthetester** [comment] 2015-04-15 14:08
@ckamm 

What I did:
- Opened the Word file with Wordpad on W7 & W8.
- Editted & saved the Word file with Wordpad on W7 (on W8 for second test)

No ghostfile appeared on the W8, the file was synced properly and after opening the file a second time (2 instances open) I saw the new/synced version had the changes. I still had the original file open at the same time.
Logs: http://www.filedropper.com/wordpadw8w7test1

Same thing but from other side
Logs: http://www.filedropper.com/wordpadw7w8test2

Using WordPad I did not see any locking in Sysinternals Process Explorer at any stage of the process.

With Word opened I do see locking:
W7: Process: WINWORD.EXE    PID: 3100   Type: File
W8: Process: <Non-existent Process>  PID: 3340   Type:File

Word closed after saving & editting on W7 but still open on W8:
W7: 0 Matching items
W8: Process: <Non-existent Process>  PID: 3340   Type:File

Word closed on all clients after temp/ghostfile arrived on W8:
W7: 0 Matching items
W8: 0 Matching items

So I guess it is 100% related to Office and I also think it is strange that the W8 client does not seem to realize it is Word that locks the file.. I used the same iso to install Office on the two test clients.

If you want I can upload the entire Linux server virtual harddrive somewhere and put a link here so you can take a look at that if you think that could be useful?

**Comment by ckamm** [comment] 2015-04-15 14:10
@alexthetester Thanks for the extra data! I don't have the time to look at it in detail right now (will be back in a week) - @jturcotte do you have any ideas?

**Comment by alexthetester** [comment] 2015-04-15 14:15
@ckamm no worries, take your time.

Btw I had to edit my post. Had to remove the < and > from the Non-existent Process since Github omits those parts of your post apparently. Not sure if you noticed/get notified.

**Comment by jturcotte** [comment] 2015-04-15 15:00
What I don't understand is that, if the problem is that Word (or something) is keeping the real file locked, why would deleting the temporary file and redownloading it help in any way?

Do we give up after a certain number of time of not being able to overwrite the original file?

**Comment by alexthetester** [comment] 2015-04-16 07:18
@jturcotte 

It seems like it, only a manual resync fixes it. Leaving it alone doesn't help, even after 12+ hours.

Deleting the temporary file somehow initiates a resync as well 

Wasn't sure if your comment was aimed to me or not, if it wasn't just ignore this comment :)

**Comment by jturcotte** [comment] 2015-04-17 11:27
@alexthetester Thanks :)

So is it possible that the problem is only that _propagator->_anotherSyncNeeded isn't set in https://github.com/owncloud/client/blob/458f336405e3b5e1837076cb53170db83dbf874a/src/libsync/propagatedownload.cpp#L543 ?

@ckamm Since Word is open on both side, is it possible that the earlier if (isConflict) is entered and that this prevents us from setting it? I don't know that code too well, and I can't open the logs anymore mentioned in earlier comments, so I'm a bit lost.

**Comment by alexthetester** [comment] 2015-04-21 14:06
@jturcotte It could be, I do not know, I have to admit I am not a Linux king.

Do you have any directions on how I would change this?

I had some extra time on my hands today so I just went ahead and uploaded the entire Linux server:
http://mab.to/6w90nwrX2

Not sure if you guys can use it or even want it but here it is anyway :)

In case you guys have to convert the VM since it is HyperV and don't have a tool this one is pretty nice: https://www.starwindsoftware.com/converter
Not many can convert HyperV to something else but this usually does the trick.

Please do not feel pressured into doing anything with the server just because I uploaded here, you guys know best how to handle these things so I'll leave it up to you whether you do anything with it or not :)

**Comment by ckamm** [comment] 2015-04-22 07:34
@jturcotte I don't think it's related to anotherSyncNeeded since alexthetester reported earlier that syncing after Word was closed did not fix the problem.

@alexthetester But now you said "It seems like it, only a manual resync fixes it." - clicking the "Retry Sync" button fixes it after all?

**Comment by alexthetester** [comment] 2015-04-22 07:51
@ckamm Yes, it did but I did say that earlier however looking back it was in the middle of a wall of text so I can understand why you did not notice it.

However I cannot propose this as a solution for possible clients, a workaround maybe but not a solution. I am also afraid that possible adopters of the product would refrain from doing so if it comes with a workaround from day one.

**Comment by ckamm** [comment] 2015-04-22 08:06
@alexthetester Okay, I must have missed that. This is a confusing issue, could I ask you to run the following test again to narrow down the problem and make sure we're looking at the right thing?

Right now it sounds like, after closing Word, the problem persists if the client tries a regular sync, but goes away with the explicit 'Retry Sync' action. There's only a small difference between the two, so that could be helpful information.

Could you:
* Launch owncloud with --logfile log.txt
* Produce the problem state. Close MS Word.
* Go to the 'Account' tab. Select the sync folder that contains the bad file in the tab. Make a note of the current system time. Hit F6. This triggers a normal sync run (verify that the progress bar briefly pops up) and should not resolve the problem (verify that the temporary file still exists once the sync run finished).
* Go to the 'Activity' tab and click 'Retry Sync'. Verify that this resolved the problem.
* Upload the log file.

The two things 'Retry Sync' does that a regular sync does not is to wipe the error blacklist and delete all download temporaries. The error blacklist should not be involved here since you're seeing no sever errors. Maybe deleting the download temporary and redownloading the file helps somehow...

**Comment by alexthetester** [comment] 2015-04-22 08:46
What happened:
- Made changes to the file on W7
- The temp/ghost file appeared on W8.1
- Went to 'Account', clicked the link and pressed F6, this showed a resync but did not fix it.
- Went to 'Activity' and clicked 'Retry Sync', this removed the temp/ghost file and correctly synced/updated the file.

It went exactly as you expected.

Log W7: http://www.filedropper.com/owncloudw7loglog
Log W8: http://www.filedropper.com/owncloudw8loglog

Note:
At the Account tab + F6, the pop-up message stated it made changes to 1 file.
At the Activity tab + Retry Sync, the pop-up stated it made changes to 2 files

**Comment by ckamm** [comment] 2015-04-22 09:40
@alexthetester Thanks for the test. The log confirms that we first download the file and can't rename it because of "Toegang geweigerd" ("Access denied", Word still open, presumably). Then I see 5 syncs afterwards which all get "Het proces heeft geen toegang tot het bestand omdat het door een ander proces wordt gebruikt" ("The process can not access the file because it is being used by another process").

Once you clicked 'Retry sync' the temporary was deleted. The file was downloaded anew and the rename succeeded.

Maybe it's not the target file but rather the temporary file that is being locked by some process. Could you check with process explorer? Do you have any kinds of Antivirus or other monitoring programs running?

**Comment by alexthetester** [comment] 2015-04-22 10:02
@ckamm I did close Word normally but maybe some other Word related process stays running (for a while)? 

Did the exact same test but using Process Explorer on the temp file to see what is locking it:

Log W7: http://www.filedropper.com/owncloudpexpw7log
Log W8: http://www.filedropper.com/owncloudpexpw8log

Sadly the Process Explorer did not see anything locked on the temp file.. So I am afraid these logs won't be very different. I copied the location and filename with extension into the find handle/dll bit so I don't think I made a type-o or something.

The only thing installed on these two systems is Windows, Office, WinCDEmu and .NET.
They are both VM's created for testing Owncloud so they are (should be) clean and they are updated.

**Comment by ckamm** [comment] 2015-04-22 11:21
Thanks! Here's what we know:

* The target file is probably not locked: Moving another file over it (after 'retry sync') works just fine.
* The temporary file shouldn't be locked: No one should lock it in the first place and the Process Explorer doesn't show a lock.
* We can't move the temporary file to the target file because "The process can not access the file because it is being used by another process".
* We can delete the temporary file.
* We can move another temporary file to the target file just fine.

My current best guess is that someone, maybe even the owncloud client itself, has a lock on the initial temporary file. @alexthetester did we already test whether rebooting Windows or restarting the oC client helps?

Since the reason for the problem is still unclear, I'll look at getting more information about the file locks in the client when a rename fails.

**Comment by ckamm** [comment] 2015-04-22 12:48
@alexthetester It turns out the owncloud client itself had the file open in this particular case! The issue should be fixed in tomorrow's build of 1.8, please test http://download.owncloud.com/desktop/daily/

**Comment by alexthetester** [comment] 2015-04-22 13:40
@ckamm 

- I installed the ownCloud-1.8.1.4962-nightly20150421-setup.exe on both clients.
- I opened Word on both clients
- Made a change on the W7 side and closed Word.
- When I got the temp file on W8.1 I closed Word on that system.

The temp file is still there but there was one difference. I did see the ghost file disappear for half a second before I closed Word but it came back and when I closed Word it did not fix itself. I have a feeling the 'action' that the new client does is too quick since it deleted the Temp file before I closed Word.

I did the same test the other way around but did not see the temp file disappear for a second here. This might be because Windows 7 is slower in syncing across the network than Windows 8.1 for some reason. (Noticed this in other cloud software as well)

Maybe having the same action occur once an hour is an option?

Or should I do a longer test to see if it fixes itself after a longer time?

Sidenote: I could not uninstall OwnCloud normally, the uninstall tool does not seem to shutdown the OwnCloud client and I had to shut it down manually and delete the files again after that. The funny thing is that the uninstall seemed to be succesful. This is a minor issue but thought I'd bring it up anyway since you guys might be interested.

**Comment by ckamm** [comment] 2015-04-22 13:50
@alexthetester The fix will only be in tomorrow's build! I'll check whether we can trigger a new windows build for you now.

**Comment by alexthetester** [comment] 2015-04-22 13:51
@ckamm 

Doh! Sorry, I must've read too quickly!

Don't worry, I will gladly wait until tomorrow :)

**Comment by ckamm** [comment] 2015-04-23 07:42
@alexthetester Unfortunately the Windows build server is broken right now so there's no new build yet. @danimo is actively working on making it work again.

**Comment by alexthetester** [comment] 2015-04-23 08:03
@ckamm Ah, that explains it! Thank you for letting me know :)

I will check again later.

**Comment by alexthetester** [comment] 2015-04-28 07:30
@ckamm the new version isn't added yet right? or is the build server still broken? :)

**Comment by ckamm** [comment] 2015-05-06 07:41
@alexthetester The server is back up and working and you can get a recent build at http://download.owncloud.com/desktop/daily/ . The fix is also included in the 1.8.1 release candidates. Sorry for the delay.

**Comment by alexthetester** [comment] 2015-05-06 07:42
@ckamm No problem! Thanks for the heads up 

I'll give it a try now, I'll let you know what happens.

**Comment by alexthetester** [comment] 2015-05-06 11:18
@ckamm I just performed some tests on both sides and it looks like it is fixed!

It was quite the journey but it was a pleasure working with you guys and educational at the same time!

I assume you don't want logs but if you do I'll gladly provide some.

Thanks a lot and good luck with any future issues you guys have to solve :)

Friendly greetings,
Alex

**Comment by ckamm** [comment] 2015-05-06 11:20
@alexthetester Thanks for the patience and the good info! :)

**Closed by ckamm** 2015-05-06 11:20 UTC
Labels: bug, ReadyToTest
