### ISSUE TITLE
Ability to copy link from activity tab / sync protocol

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#6741] opened 2018-08-27 13:40 UTC
### Steps

1. Open a website containing for example a PDF file
1. Save the PDF file into a subfolder inside of OC
1. Open the desktop client sync protocol
1. Right click on the file

### Expected
Context menu just like for desktop integration, with ability to copy private link or create public links

### Actual
Nothing happens

### Version
2.4.3

@pmaier1 @michaelstingl

**Comment by ckamm** [comment] 2018-10-17 12:53
Duplicate of #6710, merging

**Closed by ckamm** 2018-10-17 12:53 UTC
Labels: Design & UX, Enhancement
