### ISSUE TITLE
Loosing settings after reboot and not syncing correctly

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/client#4086] opened 2015-11-07 14:40 UTC
Since the upgrade to 2.0 client i started loosing all my settings after a  few reboots.
After a few reboots, owncloud client wants me to configure the server/user/password again.
Another thing i have noticed it is that , also after 2.0 , sometimes files are not synchronized at all, until i restart the machine. The blue arrow icon appears to be running forever but not syncing at all.

The only thing that is not usual on my system is that my home folder uses encfs. Though i dont have any other problems in any other applications. And owncloud < 2 works just fine. 

Owncloud server 8.1.4
Owncloud client 2.0.2

**Comment by RealRancor** [comment] 2015-11-07 16:20
@jsalatiel Did that happen after the auto-update from 2.0.0/2.0.1 to 2.0.2? If yes then this is a known issue and a duplicate of https://github.com/owncloud/client/issues/4015

**Comment by guruz** [comment] 2015-11-09 13:54
You did not mention which OS you are on. I assume linux because you mention encfs?
If the password dialog shows up again, there could also be a problem with the keychain? (e.g. gnome-keychain or kwallet..?)

**Comment by ogoffart** [comment] 2015-11-09 14:15
If linux, then you should also mention the version of Qt.

**Comment by jsalatiel** [comment] 2015-11-09 21:38
It is linux mint 17.2 rafaella (from ubuntu 14.04.3) 
# dpkg -l | grep -i libqtcore
ii  libqtcore4:amd64                            4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1             amd64        Qt 4 core module

I really cant be sure if it was from 2.0.0/2.0.1 to 2.0.2 or just 2.0. 
Right now i  am on 2.0.2, and every few reboots i am prompted to configure everything again.
btw, my filesystem is not corrupted, though it is encrypted with encfs.

**Comment by FreeMinded** [comment] 2015-11-22 20:29
I'm experiencing the same issue with Kubuntu 15.10 and oC 2.0.2. Every time my notebook shuts off because of empty battery I have to re-enter server/user/password.
I'm not sure with which version this behaviour started (probably 2.0.0). It was definitely not present in older ones.

dpkg -l | grep -i libqtcore
libqtcore4:amd64   4:4.8.6+git64-g5dc8b2b+dfsg-3~ubuntu8

I'm happily provider further information or run some tests!

**Comment by ogoffart** [comment] 2015-11-22 22:19
Qt 5.4.2 contains a fix to avoid loosing the settings.
With Qt 4 on might loose the settings because it rewrite the setting file each time owncloud changes it (for example if you change the geometry of the settings window). And if the computer crash before the file is flushed to the disk, the settings will be empty.  Qt 5.4 is smarter and use some atomic update with a rename that makes sure this does not happen.

**Comment by FreeMinded** [comment] 2015-11-23 10:32
@ogoffart Is there a simple way to use the Qt version you mentioned? Or is the client still built on Qt 4?

**Comment by ogoffart** [comment] 2015-11-23 10:42
Which package do you use?

If you compile it yourself, you can use Qt5 (recommended)

I think we still use Qt4 on some of our packages because we still support distributions that did not have a good version of Qt 5.

**Comment by FreeMinded** [comment] 2015-11-23 10:53
I use the one from the openSuse Build Service
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_15.10

**Comment by ogoffart** [comment] 2016-01-18 17:31
Closing the issue as this was fixed with more recent Qt.

**Closed by ogoffart** 2016-01-18 17:31 UTC
Labels: Needs info
