### ISSUE TITLE
Space is not well used in sharing dialog

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#4380] opened 2016-01-21 12:03 UTC
## Observed behaviour

There are three checkboxes, enough space to allocate all of them and still button [...] appears.

![sharing_doesnt_put_checkboxes_in_the_right_place](https://cloud.githubusercontent.com/assets/9048796/12479979/2faa88ac-c03f-11e5-9bbc-96c9ea3b740a.png)

Client 2.2.1beta1 for Windows 10

**Comment by ogoffart** [comment] 2016-01-21 12:29
It used to be different but we had to change it probably for a reason.
@jancborchardt : suggestions?

**Comment by jancborchardt** [comment] 2016-01-21 13:59
The problem is that this whole dialog is way too wide. It should be about 60% of the width, then it will make way more sense.

Also, the […] is less about the use of space and more about hiding stuff people will probably not always need.

**Comment by jancborchardt** [comment] 2016-01-21 14:00
Also – why is the preview sooo giant? About 60% here is enough as well. This looks different to what we designed, and off-balance. The thumbnail should also be left-aligned with the boxes below it. And filename as well as folder nicely balanced in the middle.

**Comment by guruz** [comment] 2016-04-15 15:10
If you fix this fix also https://github.com/owncloud/client/issues/4668

**Comment by guruz** [comment] 2017-03-29 16:00
FYI @ckamm

**Comment by SamuAlfageme** [comment] 2017-03-29 16:13
- `[...]` button was addressed in https://github.com/ckamm/owncloud-client/commit/3d92c2c05d24ff2c59ed951d94dc30ce9bd67c9e 
- Thumbnail size in https://github.com/ckamm/owncloud-client/commit/b3a897548bf55b29c4a7478f62eea19daf57bff8

Once those are merged, we can close here 🎉

**Comment by ckamm** [comment] 2017-03-29 17:20
Yes, mostly addressed now. I am keeping the "..." button to hide the detailed edit permissions for directories though.

**Closed by ckamm** 2017-03-29 17:20 UTC
Labels: bug, Design & UX, sev3-medium

**Comment by jancborchardt** [comment] 2017-03-29 18:29
Awesome, thanks a lot @ckamm! :)
