### ISSUE TITLE
Zsync Not found

### ISSUE THREAD

**Issue by thalst** [owncloud/client#6971] opened 2019-01-14 13:01 UTC
When cross compiling from OpenSUSE, I get this error message 

Cannot find source file:

    ../3rdparty/zsync/c/libzsync/zsyncfile.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

I already downloaded zsync from git and placed it under  ../3rdparty/zsync/, but it seems that zsyncfile.c doesnt come with it

How to install zsync?

**Comment by dschmidt** [comment] 2019-01-14 13:37
This is a duplicate of your other issue. As I told you there, you need to checkout submodules.

**Closed by dschmidt** 2019-01-14 13:37 UTC

**Comment by dschmidt** [comment] 2019-01-14 13:39
Ah my bad. It wasn't you in https://github.com/owncloud/client/issues/6967. But the comment @guruz gave in your other ticket still stands: this is the wrong place to ask such questions.

**Comment by thalst** [comment] 2019-01-14 13:55
My bad too. Sorry for the inconvenience. Anyway, it still won`t work. Where should I ask for help?

**Comment by dschmidt** [comment] 2019-01-14 13:57
https://github.com/owncloud/client/issues/6970#issuecomment-453984788

**Comment by thalst** [comment] 2019-01-14 13:59
Yeah, that is solved. Your submodule tip was also helpful. I'm still facing some problems.
