### ISSUE TITLE
owncloud-client 2.0 packages for Fedora 22 are obsoleting themselves

### ISSUE THREAD

**Issue by urbenlegend** [owncloud/client#3842] opened 2015-09-16 06:49 UTC
In Fedora 22, the owncloud-client packages are shown as obsoleting themselves:

```
$ sudo dnf list obsoletes
Last metadata expiration check performed 3:47:36 ago on Tue Sep 15 19:54:29 2015.
Obsoleting Packages
owncloud-client.i686                  2.0.1-3.1             isv_ownCloud_desktop
    owncloud-client.x86_64            2.0.1-3.1             @System             
owncloud-client.x86_64                2.0.1-3.1             @System             
    owncloud-client.x86_64            2.0.1-3.1             @System             
owncloud-client.x86_64                2.0.1-3.1             isv_ownCloud_desktop
    owncloud-client.x86_64            2.0.1-3.1             @System
```

This causes owncloud-client to appear in yumex-dnf updates even though the package is already up to date:

![screenshot from 2015-09-15 23-46-35](https://cloud.githubusercontent.com/assets/241316/9898062/0aa6d42e-5c04-11e5-98d1-307016f961f7.png)

Selecting those "updates" and trying to install them causes a "Errors in dependency search" message.

This issue started happening with the release of owncloud-client version 2.0 and above

**Comment by dragotin** [comment] 2016-01-08 12:57
duplicate of #4256

**Closed by dragotin** 2016-01-08 12:57 UTC
Labels: packaging
