### ISSUE TITLE
client should resume uploads of big files after restarting the client

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#10207] opened 2022-10-20 09:46 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

It would be good if the client would not only resume unfinished uploads where they stopped after loosing connection but also when the client was ~~stopped~~ shut down and restarted.

### Proposed solution

don't keep the data for resuming the upload in memory but persist it

**Comment by TheOneRing** [comment] 2022-10-20 11:23
Duplicate of https://github.com/owncloud/client/issues/8126

**Closed by TheOneRing** 2022-10-20 11:23 UTC

**Comment by HanaGemela** [comment] 2023-03-16 12:34
Passed in ownCloud 4.0.0.10422-daily20230316, mac
