### ISSUE TITLE
Remove SyncFileItem::log

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3213] opened 2015-05-07 12:40 UTC
The `log` member of `SyncFileItem` holds information about a sync item as found by the local and remote discovery phase.

It has the following problems:
- **Almost unused**: Only the .owncloudsync.log file generation and the download propagation read it. 
- **Large memory footprint**: We have a lot of SyncFileItems in memory and the `log` values contribute significantly to that struct's size without pulling their weight. (see #2929)
- **Unclear contents**: Whether log._other_size is the local or remote size depends on the SyncFileItem.

It should be removed. It would need a change to how owncloudsync.log is generated (see #3108) and data needed for propagation would need to become regular members of SyncFileItem.

**Comment by dragotin** [comment] 2015-05-07 13:57
The intend of the it was to be able to write .owncloudsync.log. That is a steady taken logfile which gives us important information about the reason why some action was taken.

Apart from that, we [c|sh]ould use it to persist the activity log over restarts.

I decided to store the data in the struct to avoid opening and closing the log file all the time. We might be able to fix that otherwise, ie. by keeping the file open or similar.

Bottomline: No, please do not kill it. Thanks.

**Comment by ckamm** [comment] 2015-05-08 07:38
@dragotin If we split the logfile into a discovery log and a propagation log, the discovery log could be written directly from the treewalk visitors. The propagation log would only have information about things that are relevant for propagation and could be used to rebuild the "Activity" tab. #3108 is for reworking how owncloudsync.log is generated, also for other reasons.

Are you saying that you want to keep `SyncFileItem::log` even if we don't need it for the log file?

**Comment by dragotin** [comment] 2015-05-08 12:56
No, we do not keep something that we do not need of course. If we can save the log section in SyncFileItem, even better. All I want to keep is the logfile that tells us what happened in the history.

**Comment by guruz** [comment] 2015-05-08 12:57
^^ @jturcotte FYI

**Comment by jturcotte** [comment] 2017-01-20 19:34
@cdamken @michaelstingl Hi, could you let us know:

1. In which kind of situation do you use `.owncloudsync.log` (if any)?
2. What information is useful for you in it?

**Comment by cdamken** [comment] 2017-01-21 19:33
@jturcotte  Some customers provide us the `.owncloudsync.log` instead the one created with `F12`

To be honest, that log is not so human friendly 😄 

```
# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=# Syncrun started  until  (0 msec)
|0|Uli|INST_REMOVE|Down|1483800216||0||4||0|0|0|||INST_NONE|
|0|Uli/Lan_Intel_12.12.218.0_W10x64|INST_REMOVE|Down|1438660367||0||0||0|0|0|||INST_NONE|
|0|Uli/Lan_Intel_12.12.218.0_W10x64/APPS|INST_REMOVE|Down|1438655277||0||0||0|0|0|||INST_NONE|
|0|Uli/Lan_Intel_12.12.218.0_W10x64/APPS/BootUtil|INST_REMOVE|Down|1438655266||0||0||0|0|0|||INST_NONE|
```
I don't know exactly why have to be kept. but if you ask my opinion:

1.- I expect a log that can be more easy to understand

2.- at least a few syncs where the user and us can get the information when a problem occurs and can't be reproduced again (not everybody start the client with --log-file)

3.- if the client syncs in different servers it would be AWESOME to have separated logs (but I think is for the normal log and not for the `.owncloudsync.log` )

 if @pmaier1 and @hodyroff does have anything against it  I could say that and at the end of the day you know better what and how can be improved.

**Comment by dragotin** [comment] 2017-01-21 20:59
The purpose of this is pretty easy: It is a sync history. It tells when what was synced from where to where, and why. It is not supposed to be human friendly. It was supposed to be read by the client to display the recent syncs in the sync list. That was just never finished, but I would say that would still be a useful feature.

**Comment by cdamken** [comment] 2017-01-21 22:52
> It was supposed to be read by the client to display the recent syncs in the sync list. That was just never finished, but I would say that would still be a useful feature.

Probably that is the answer @jturcotte was looking for 👍

**Comment by dragotin** [comment] 2017-01-22 11:23
Yes, however, there might be a more elegant solution to achieve that, not sure.

**Comment by jturcotte** [comment] 2017-01-24 11:07
The thing is that the extra data we need to log this at the end of propagation means that we carry each byte in memory for the whole sync. With one ETAG and one file ID, this needs 120 bytes, so if we want to support a sync of 1M files, just the extra data will take 120 MB of RAM.

I don't know what the "why" part should look like for a user (which this log is aiming to solve), do they care at all? Isn't the detail pane of the server UI already solving that use case better by putting user names in addition?

For developers I'm not aware of any developer actually using that log, do you? And in what kind of situation? I'd like to split SyncFileItem into "task" and "result" structures and I'm not convinced that this feature is worth its cost. Removing it would make this refactoring easier to achieve and save memory.

**Closed** 2017-09-18 09:46 UTC
Labels: Peak Memory, technical debt
