### ISSUE TITLE
[Windows] Owncloud client marks synchronization folder as "hidden folder"

### ISSUE THREAD

**Issue by mghansen256** [owncloud/client#7201] opened 2019-05-22 14:06 UTC
### Expected behaviour
When I choose a folder to be the root folder to be synchronized with owncloud, the owncloud client should not change the folder to a hidden folder.

### Actual behaviour
The owncloud client marks the folder as a hidden folder. This causes the folder to be invisible on the terminal and in double commander by default. In windows explorer, it can still be seen, with the owncloud icon on it. I guess the folder is presented in windows explorer in some other way.

### Steps to reproduce
1. Create a local folder.
2. Select it as a synchronization folder for owncloud client.
3. Try to see the folder in the terminal using "dir" or in double commander.

### Server configuration

Web server: sciebo.de

### Client configuration
Client version: 2.5.4 (build 11415), installed via chocolatey

Operating system: Windows 10 64bit

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.11.2

Client package (From ownCloud or distro) (Linux only):

Virtual file system options are off.

**Comment by guruz** [comment] 2019-05-23 10:30
I've never seen this before. Do you have screenshots?
Is this some odd local admin policy?

**Comment by Helios07** [comment] 2019-07-23 10:45
I found a way to explain this behavior. If you select an already existing folder to be synced, owncloud changes the icon and creates a link in the left bar. During this process, the directory becomes a system directory. Have a look for the folder "test_directory" in the attached screenshot (here with the elephant icon instead of the cloud due to the usage of a branded client). 
The problem is that these system files/folders are normally excluded from backups so that the important files won't get into the backup anymore.

![screenshot_system_folder](https://user-images.githubusercontent.com/3447175/61705960-367dad00-ad47-11e9-993b-4c72ccddb6c7.png)

**Comment by ChrisEdS** [comment] 2019-07-31 07:26
@guruz Do you need additional information?

**Comment by michaelstingl** [comment] 2019-08-07 12:30
@TheOneRing Could you have a look?

**Comment by TheOneRing** [comment] 2019-08-07 13:34
In order to add the folder as a cloud storage provider to the explorer pane, the folder gets marked as a read only system file. https://docs.microsoft.com/en-us/windows/win32/shell/integrate-cloud-storage

The folder is still accessible by its full path.
In order to list the folder in cmd you need to provide the `/A` flag to dir `dir /A` to list system files.
In Double Commander you need to display system files `Show -> Show Hidden/System Files`.

**Comment by michaelstingl** [comment] 2019-08-07 15:38
Adding sync folders as Cloud Storage Provider became necessary with Win 10. Without, it was nearly impossible to find your ownCloud sync directory.

Related issue: https://github.com/owncloud/client/issues/5295
PR for implementation: https://github.com/owncloud/client/pull/6113

**Closed by michaelstingl** 2019-08-07 15:38 UTC
Labels: Needs info, blue-ticket
