### ISSUE TITLE
[QA] 3.0.0. wizard doesn't work correctly for 'Configure synchronization manually'

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9819] opened 2022-06-23 13:49 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

After choosing 'Configure synchronization manually' in wizard and clicking 'Finish' the popup 'Add Folder Sync Connection' appears immediately.
It suggests as local folder 'demo@demo.owncloud.org2' (no folder exists before).

![suggest-2](https://user-images.githubusercontent.com/75983861/175312855-2fc97830-198f-4abf-830e-42fb0cdbcbdd.png)

The sync folder 'demo@demo.owncloud.org' is created despite 'Cancel' is clicked.

![folder-root](https://user-images.githubusercontent.com/75983861/175313877-e07faef9-892a-41cb-973f-78e179ef762a.png)

### Expected behavior

No popup 'Add Folder Sync Connection' appears immediately, no sync root created.

### Steps to reproduce the issue

1. Start the client and add an account
2. Choose 'Configure synchronization manually' from 'Advanced configuration'
3. click button 'Finish'

### Client version number

owncloud-client-3.0.0~daily20220617-7822.x86_64

### Desktop environment (Linux only)

openSUSE 15.3

**Comment by gabi18** [comment] 2022-06-23 13:50
[add-account.log.gz](https://github.com/owncloud/client/files/8967845/add-account.log.gz)

**Comment by gabi18** [comment] 2022-06-23 13:54
Suggestion for the local folder if 2 sync folder are already existing:

![suggest-22](https://user-images.githubusercontent.com/75983861/175316394-3dfe0b04-a78e-4b62-bde6-369e2d714464.png)

**Comment by TheOneRing** [comment] 2022-06-24 09:56
Duplicate of : https://github.com/owncloud/client/issues/9797

**Closed by TheOneRing** 2022-06-24 09:56 UTC
Labels: bug
