### ISSUE TITLE
Feature request: explorer integration - send link by e-mail.

### ISSUE THREAD

**Issue by sirio81** [owncloud/client#3186] opened 2015-05-04 13:15 UTC
Hi, I see that, by right click it's possible to share a folder by owncloud.
It generates a link that has to be copy/paste in a mail.

May you add a button "Send by-mail" so it will open the default mail client with the link already pasted in?

Thank you.

**Comment by Kawohl** [comment] 2016-05-04 09:33
dupe of: https://github.com/owncloud/client/issues/3261 

I suggest we follow it there.

**Closed by Kawohl** 2016-05-04 09:33 UTC
Labels: Enhancement
