### ISSUE TITLE
socorro crash reporter broken?

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5791] opened 2017-05-24 15:57 UTC
https://socorro.owncloud.com/
- the website prints 'not found'
- the certidicates are mixed between int.owncloud.com and external names

/var/log/socorro/crontabber.log errors are
<pre>
2017-05-22 13:50:04,206 ERROR - MainThread -  - MainThread - Exception raised during socorro.external.postgresql.connection_context tra
nsaction
Traceback (most recent call last):
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/crontabber/transaction_executor.py", line 46, in __call__
    result = function(connection, *args, **kwargs)
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/socorro-master-py2.6.egg/socorro/cron/jobs/matviews.py", line 52, 
in run
    self.run_proc(connection, [target_date])
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/socorro-master-py2.6.egg/socorro/cron/jobs/matviews.py", line 28, 
in run_proc
    cursor.callproc(self.get_proc_name(), signature)
InternalError: raw_adi has not been updated for 2017-05-21

2017-05-22 13:50:04,206 DEBUG - MainThread -  - MainThread - error when running <class 'socorro.cron.jobs.matviews.BuildADUCronApp'> on
 None
Traceback (most recent call last):
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/crontabber/app.py", line 974, in _run_one
    for last_success in self._run_job(job_class, config, info):
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/crontabber/base.py", line 163, in main
    function(now)
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/crontabber/mixins.py", line 165, in _run_proxy
    **kwargs
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/crontabber/transaction_executor.py", line 46, in __call__
    result = function(connection, *args, **kwargs)
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/socorro-master-py2.6.egg/socorro/cron/jobs/matviews.py", line 52, 
in run
    self.run_proc(connection, [target_date])
  File "/data/socorro/socorro-virtualenv/lib/python2.6/site-packages/socorro-master-py2.6.egg/socorro/cron/jobs/matviews.py", line 28, 
in run_proc
    cursor.callproc(self.get_proc_name(), signature)
InternalError: raw_adi has not been updated for 2017-05-21

2017-05-22 13:50:04,223 DEBUG - MainThread -  - MainThread - skipping <class 'socorro.cron.jobs.matviews.CrashesByUserBuildCronApp'> dependencies aren't met ['build-adu-matview' errored last time it ran]

</pre>

**Comment by ogoffart** [comment] 2017-05-29 09:09
The crash reporter seem to still work.  We got crash reports today and the whole weekend.

I don't know what socorro is or what this backtrace is supposed to mean.

**Comment by jturcotte** [comment] 2017-05-29 11:44
I don't know anything about soccoro other than the fact that we only use the part that accepts crash reporter HTTP pushes. So if you can keep that part running (and see that you can still push a new crash from the client) then you can remove/fix/change anything else.

**Comment by guruz** [comment] 2017-07-11 11:18
Since we seem to be still getting crash reports in sentry, it seems to be all good still.
I'll move the issue and @dschmidt can evaluate in next milestone when he has time

**Comment by jnweiger** [comment] 2017-07-18 15:08
@mrlinux1 FYI this is the soccoro issue I recently mentioned....

**Comment by michaelstingl** [comment] 2017-07-18 15:11
https://crash-reports.owncloud.com/

==> Valid SSL, expires end of August

https://socorro.owncloud.com/

==> There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).

**Comment by ogoffart** [comment] 2017-07-21 06:39
This is not a bug in the client so i'll close this issue. 
The crash reporter is still working

**Closed by ogoffart** 2017-07-21 06:39 UTC
Labels: gold-ticket

**Comment by guruz** [comment] 2017-07-21 11:47
I just re-checked, the two domains mentioned above now seem to have good SSL that expires in October.
