### ISSUE TITLE
Windows Roaming Profile Support

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#4340] opened 2016-01-08 16:24 UTC
Opening this as a placeholder for discussing the support of windows roaming profiles, and defining requirements. At the outset, the user story looks like this:

As an admin, I want to be able to support roaming profiles with the desktop sync client so that my users can access their files when they log in even if they are roaming onto a different PC.

Acceptance Criteria:
- Specify a path (in ownBrander?) that is not the default path, so that the files can be synced to the user's roaming profile storage, rather than to this specific pc. Path should include variables.
- Not entirely sure...?

**Comment by MTRichards** [comment] 2016-01-08 16:25
Need to flesh this out for 2.2.0.

**Comment by guruz** [comment] 2016-01-08 17:38
https://github.com/owncloud/client/search?utf8=%E2%9C%93&q=roaming&type=Issues

**Comment by dragotin** [comment] 2016-02-23 10:59
duplicate of #684

**Closed by dragotin** 2016-02-23 10:59 UTC
Labels: gold-ticket, research
