### ISSUE TITLE
[macOS] Overlay icon missed in folder after renaming to other existing folder but not synced

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5257] opened 2016-10-17 12:02 UTC
1. In the OC server, create a folder named 'ama' and other named 'Ama' and add info inside them
2. In the desktop client, select sync selective only one folder e.g. ama
3. Rename in the desktop folder 'ama' to 'Ama'

Current behaviour

The folder has no longer an overlay icon and the files inside have a conflic related to 'what to sync' blacklist

![screen shot 2016-10-17 at 14 01 57](https://cloud.githubusercontent.com/assets/10596560/19436751/4b0e1ef8-9472-11e6-9b68-7cc4702ae3a9.png)

![screen shot 2016-10-17 at 14 00 07](https://cloud.githubusercontent.com/assets/10596560/19436737/3b3e0dbc-9472-11e6-8452-f510529b9377.png)

![screen shot 2016-10-17 at 14 00 34](https://cloud.githubusercontent.com/assets/10596560/19436721/29cc28f2-9472-11e6-9060-29c89015c2d0.png)

![synchange](https://cloud.githubusercontent.com/assets/10596560/19436604/6d0067c4-9471-11e6-8669-c566d1799bc0.gif)

Desktop Client OSX Version 2.3.0-nightly20160929 (build 3715).

**Comment by ogoffart** [comment] 2017-04-28 09:17
It is expected that the folder cannot be sync'ed because it is on the blacklist.
This is a bug that you don't see overlay icon, but can you reproduce the problem with the 2.3 client?
I have tried on linux and i can clearly see the error icon on both the folder and the files.

**Comment by guruz** [comment] 2017-05-09 07:38
@davitol @SamuAlfageme Please try with 2.3.2

**Comment by SamuAlfageme** [comment] 2017-05-09 08:24
@guruz @ogoffart @davitol Yup, still happening, the icon is missing until you force a sync/one is scheduled and turns ✅. Then, if the folder is opened, it goes missing again.

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/25841676/57c56834-34a1-11e7-8c5a-4ae24fb78e73.gif"/>
</p>

> It is expected that the folder cannot be sync'ed because it is on the blacklist.

However the original folder appears checked in the selective sync list but it's not re-downloaded (it can't because of the case-unsensitive FS). For consistency I'd uncheck it there.

**Comment by SamuAlfageme** [comment] 2017-11-28 15:43
**Overlays seem to be fixed for this case**; however case-resolution handling is rather edgy and there's many stuff happening under the hood; let's recap:

Start with a clean client: 

1. Create 2 folders with the same name but different case on the webUI
2. Sync with the client - case sensitivity clash error raised, **the 2 folders appear checked on the selective sync list and its contents are not refreshed over time** while the error lasts (size changes on the folders, new folders created on the server side...)
3. Error overlay for the folder that caused the clash (contents get sync'ed)
4. Rename the uncased folder - Files are transferred from the first location into this one in the server (sync propagates and merges the 2 folders) and **the cased folder is deleted in server**

I'll go with dynamically unchecking the folder not downloaded on the selective-sync list to avoid the error on the client side - display a warning about the collision instead. I think the problem with the selective sync list not being updated while there's errors was reported somewhere; @ogoffart @guruz any clue? ~> will dump this comment in https://github.com/owncloud/client/issues/5870

**Closed by SamuAlfageme** 2017-11-28 15:43 UTC
Labels: bug, ReadyToTest
