### ISSUE TITLE
Windows Explorer sidebar navigation menu integration

### ISSUE THREAD

**Issue by maxibanki** [owncloud/client#5794] opened 2017-05-28 17:07 UTC
So it looks like in the windows explorer sidebar.
![image](https://cloud.githubusercontent.com/assets/17984549/26530622/ba460c2a-43d8-11e7-8407-3a662b96b505.png)

How it works?
https://gist.github.com/realslacker/d4901a8295baf979c29dbb55d4e6e034

Maybe is somebody able to integrate it into the client.

**Comment by guruz** [comment] 2017-05-29 05:56
@remixtj Is this something you'd want to do?

@maxibanki thanks for the .reg file.
I'm closing this as duplicate of https://github.com/owncloud/client/issues/455

**Closed by guruz** 2017-05-29 05:56 UTC

**Comment by remixtj** [comment] 2017-05-29 07:39
@guruz i never imported a reg file with c++, i'll wait for someone more skilled in this area

**Comment by maxibanki** [comment] 2017-05-29 07:48
To get the Icon in the sidebar you have 2 possibilities. A favicon.ico which isn't already included in the client or you get the icon from the client executable. Refering to [this ](https://help.nextcloud.com/t/shortcut-in-windows-file-explorer-similar-to-one-drive/5521/3) post in the Nextcloud forum.
