### ISSUE TITLE
[Virtual Filesystem] Add option on folder level for downloading and deleting files

### ISSUE THREAD

**Issue by DangerSchwob** [owncloud/client#6815] opened 2018-10-16 11:31 UTC
Please add a option how the client handle files in different folders.

The default currently is, download the file if the user download it and from than update the file also.

Please also add 2 other options that can be set on folder level:
1.) Always download files in this folder
2.) Temporary files, if the file is not used for X days or it is updated on the server, replace file with virtual file

**Comment by michaelstingl** [comment] 2018-10-16 21:10
@DangerSchwob Thanks for your feedback!

Workaround for "1.) Always download …" could be multiple sync folders. (related: https://github.com/owncloud/client/pull/6744, planned for 2.5.1)

**Comment by michaelstingl** [comment] 2018-11-12 19:33
First implementation for `1)` planned for next client release…

**Comment by ckamm** [comment] 2018-11-14 10:46
Baseline proposal:
- Each directory can have a pin state: unspecified (propagates parent), available-locally, on-demand
- When vfs is enabled the folder sync root defaults to on-demand
- If a new remote file is propagated check the parents for the closest set pin state: Make it virtual if it's on-demand. Download it if the state is available-locally.
- Pin state can be set via context menu actions on folders

Further suggestions:
- Pin state is visible via icons on folders
- Prettier context menu ui (probably want submenus, checked items, icons etc, which necessitate changes in all shell integrations - ideally would be generic, similar to the current action list)

**Comment by michaelstingl** [comment] 2018-11-14 19:09
Did some brainstorming with @pmaier1 this afternoon… (no conflicts with @ckamm 's proposal from @ckamm except the wording my pov)

### VFS-options for a folder that contains only "Online only" files

![folder - online only](https://user-images.githubusercontent.com/214010/48505274-f32d7f00-e846-11e8-89b3-6903db3d5708.png)

### VFS-options for a folder that contains downloaded and "Online only" files

![folder - mixed](https://user-images.githubusercontent.com/214010/48505275-f32d7f00-e846-11e8-8563-aca152665ee1.png)

### VFS-options for multiple files that are all downloaded

![files - multi synced](https://user-images.githubusercontent.com/214010/48505278-f3c61580-e846-11e8-84c2-68d9b59b3449.png)

### VFS-options for multiple files that are all "Online only"

![files - multi online only](https://user-images.githubusercontent.com/214010/48505279-f3c61580-e846-11e8-8627-331059a71fb7.png)

### VFS-options for multiple files where some are downloaded and others are "Online only" files

![files - multi mixed](https://user-images.githubusercontent.com/214010/48505280-f45eac00-e846-11e8-89cb-c664ddebcce2.png)

Keep a folder in sync could be step 1, Auto-"Online only" could follow at a later stage. Changes in the overlay icons weren't visualised yet.

We played with a prototype in Figma.com:
https://www.figma.com/file/RZYJkGnuhMbudzz7no2wokBi/ownCloud-macOS-desktop-sync-client-UI-elements?node-id=12%3A3392

**Comment by ckamm** [comment] 2018-11-15 06:47
Thanks for the mock, that aligns well with what I had in mind. 

This uses two new elements in the shell integration menu: menu entries with a checkmark and a menu separator. That adds a good amount of work to this issue since all shell integrations will need to be modified (and I propose we allow for submenus as well while we're at it).

**Comment by ckamm** [comment] 2018-12-19 13:35
@michaelstingl The PR was now merged to master.

I'm not at all happy with the ui and'd like your feedback. 

**Current state**

Currently for a folder there are two context menu options:
- "Keep updated locally, download if necessary": Hydrates contents recursively, new files shall be hydrated
- "Make available on demand, clear local data": Dehydrates contents recursively, new files shall be dehydrated

Both actions are always shown.


**Suggestions**

There are two states for items:
- available locally (pinned)
- available online only (unpinned)

These need icons.

The shell extension context menu has a submenu where one can choose among the two options. The currently active one is checked. (For extensions where checked items are not supported (nautilus), have a disabled item "Currently available locally" and then "Make available online only" as a clickable item)

The semantics are:
-  if "available locally" is selected, the folder is marked as such and marks on any subfolders are cleared. All contained items are downloaded.
- if "available online only" is selected, the folder is maked as such and marks on any subfolders are cleared. All contained items are dehydrated.
- New remote files in an "available locally" folder start out hydrated. And dehydrated in an "online only" folder.

Over time "online only" folders will accumulate locally available files and subfolders. That is fine and doesn't change the overall "online only" state. It is also ok to mark a subfolder of a locally available folder as online only (even though that might confuse some users).

**Comment by DangerSchwob** [comment] 2018-12-19 14:43
Regarding the "online only" state

What happens when the content of a local file that is marked as "online only" will be changed on a different system? Will the file updated or replaced with a virtual file? I would prefer to replace the file with a virtual file, because it is marked as "online only"

**Comment by ckamm** [comment] 2018-12-20 08:19
@DangerSchwob That's a good point. The client should be free to dehydrate files that were implicitly hydrated by usage, and not explicitly pinned.

**Comment by ckamm** [comment] 2018-12-21 09:47
The PR #6938 implements the semantics and adds the menu actions. Should already be nicer. I used the "disabled menu item" workaround to signal which availability a file or folder currently has.

What is not implemented:
- shell integration icons: Do we replace our existing icon use? Retain "syncing" and "error" icons. Add at least "available locally" and "online only" icons - possibly reusing the checkmark for "available locally" and adding a cloud icon for "online only". Potentially there could be "mixed availability" icons for when contained files and folders differ in state.
- shell integration submenu. depends on @ogoffart's work in #6921 and more for other shell extensions
- dehydration of downloaded but online-only files that have updated remotely

**Comment by ckamm** [comment] 2019-03-13 13:49
The unimplemented parts will move to a new ticket

**Comment by yannlossouarn** [comment] 2019-06-17 21:32
Hello,
Thanks for the work on VFS, which is a great improvement.
I have a question: will it be possible to manually and immediately "dehydrate" a file or a folder from the context menu ?

**Comment by ckamm** [comment] 2019-06-18 08:06
@yannlossouarn There's indeed a "Free up space" context menu action that'll dehydrate the file. On windows the action will be immediate. With the "suffix-file" based implementation the action will only take effect during the next synchronization run (which is triggered immediately).

**Comment by HanaGemela** [comment] 2019-07-17 11:49
@ckamm @michaelstingl Could someone sum up what was agreed and implemented in this issue? The options in the submenu do not match anymore

**Comment by ckamm** [comment] 2019-07-17 13:11
@HanaGemela I can try:
- on WinCfAPI there are extra "Free up space" / "Always keep on this device" context menu options that we don't control on the top level of the menu, the other options in the "ownCloud" submenu are available everywhere.
- There is a disabled "Currently..." entry in that menu when vfs is enabled with the following states:
"Currently always available locally" (aka "pinned" and available), "Currently available locally" (available, not pinned), "Currently some available online only" (at least one selected file or item inside a folder isn't available), "Currently available online only" (nothing is available)
- There's a menu action "Make always available locally" that downloads and pins the file
- There's a menu action "Free up local space" that frees up space
- New remote items in folders that are pinned initially show up as hydrated, otherwise they start dehydrated.

**Comment by ckamm** [comment] 2019-07-17 13:17
I didn't like the strings and have a PR to improve them here: https://github.com/owncloud/client/pull/7319 -- sorry.

**Comment by HanaGemela** [comment] 2019-08-08 09:28
Wording tested in https://github.com/owncloud/client/issues/7111 and verified based on expected behaviour in that issue

Menu actions present as required on macOS 10.14.6, client 2.6.0beta1 (build 12261) and Windows 10, client 2.6.0beta1 (build 12201) and also the pin state of a new file matches the pin state of the directory

**Closed by HanaGemela** 2019-08-08 09:28 UTC
Labels: Feature, ReadyToTest, Virtual Files, blue-ticket, p2-high
