### ISSUE TITLE
[owncloudcmd] Allow hiding server data in the output 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5586] opened 2017-03-07 15:51 UTC
When using the command line sync client to perform public tests with servers, some flag could be included to avoid echoing the server URL in the output of the program. Just in case the address is meant only for testing purposes and not to be exposed in the output of e.g. CI services. 

### Update:
This doesn't happen after version `2.3`:

> When using `owncloudcmd` with the `username:password` format in the server URL, the user data on the client output should be hidden. e.g.:

```
csync_walker:  file: ownclouds://USER:PASSWORD@SERVER/remote.php/webdav/examples.desktop [file_id=00000022ocih6wkrtnrj size=8980]
```

**Comment by ogoffart** [comment] 2017-03-08 15:06
What version is that?  we don't use ownclouds:// for a long time

**Comment by SamuAlfageme** [comment] 2017-03-08 21:36
@ogoffart this actually came up while creating the installation tests for qt5.6.2 on Linux, so version is the one in the repo set for doing #5470 (`2.3.0beta1`)

**Comment by ogoffart** [comment] 2017-03-09 08:34
I cannot reproduce this issue.
This should have been fixed long ago (i think the last occurence was fixed with commit 109056e676489a457511f8092ba0164f290e00cf )

**Comment by SamuAlfageme** [comment] 2017-03-09 11:11
@ogoffart you are right, I just found out that the `ownclouds://` URL comes from `2.2.4` logs (that precede https://github.com/owncloud/client/commit/109056e676489a457511f8092ba0164f290e00cf on time)

I'll edit the original issue (the original idea was to include a flag not-to echo the server URL on `owncloudcmd` output for CI servers, etc.)

**Comment by ogoffart** [comment] 2017-03-09 14:19
That would be `--silent`

**Comment by SamuAlfageme** [comment] 2017-03-09 14:35
@ogoffart `--silent` is *too silent* 😓 

I want to have the client logs for troubleshooting but not to reveal private server URLs the tests could be pointing to...

**Comment by ogoffart** [comment] 2017-03-09 14:46
The log contains some sensitive information such as the URL and the file names. I don't think we want to sanitize the log. The URL is important for debugging when several accounts are involved.
What you can do is simply pipe it so sed

`owncloudcmd .... |& sed "s/secret.url/[MASKED]/g"

**Comment by hodyroff** [comment] 2017-03-10 10:18
Yes. I thought passwords are logged, so I remove security. Samuel, can you close if all is fine?

**Closed** 2017-03-10 10:18 UTC
Labels: Design & UX, Feature

**Comment by SamuAlfageme** [comment] 2017-03-10 10:26
@hodyroff  sure, it wasn't meant to be a bug ticket, **but a placeholder issue following a discussion on #desktop** to work on this on the future because it makes testing and CI workflow cleaner.

@ogoffart yup, I'm replacing all the occurrences on the output via a env. variable, but wanted to abstract that.
