### ISSUE TITLE
When overlay icons disappear, the share by link option disappear with them 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2776] opened 2015-02-04 12:06 UTC
### Expected behavior
Overlay icons and share dialog never disappear
 
### Actual behavior
When overlay icons disappear in windows, the share by link option disappear with them 

### Steps to reproduce
--> When you have two ownCloud clients that are running at the same time only one shows overlay icons https://github.com/owncloud/client/issues/2505

--> In windows:
1. Launch the app the first time
2. Restart 
3. Overlay icons and share dialog are shown
4. Quit the client and launch it again 

### Client configuration
Version 1.8.0-nightly20150204 (build 4678)

Operating system: Windows 8.1

**Comment by dragotin** [comment] 2015-02-05 11:23
@lmaestro what do you mean by "quit the client and launch it again"? Neither the overlays nor the sharing are available without a running client. That is as-designed behaviour.

**Comment by lmaestro** [comment] 2015-02-05 11:30
I mean that if you decide to quit the client and then you open the client again, the client is running but without overlay icons either share link option

**Comment by dragotin** [comment] 2015-02-05 11:47
Ok, that sounds as if the explorer plugin does not reconnect.

**Comment by jturcotte** [comment] 2015-02-06 09:40
@lmaestro Hello, could you confirm if, after having restarted the client, changing directory in explorer and coming back shows the icons again? Is restarting the computer the only way you can get them back?

**Comment by lmaestro** [comment] 2015-02-06 10:03
Yes, the only way that I have the overlay icons back is to restart the computer (in my case the virtual machine)

**Comment by jturcotte** [comment] 2015-02-12 10:38
I tried a few things and I cannot get it reproduced (with the 4687 nightly build):

- Tried putting 150MB of stuff in the share directory to try getting the client busy when it restarts
- Tried cleaning the data or leaving it there
- Tried navigating in a lower directory in the structure in an explorer Window, or to have the root directory on the desktop directly
- Tried restarting the client right after restart, or a bit later when it starts syncing

Anything else I could try? I hava a Windows 8.1 VM.

**Comment by lmaestro** [comment] 2015-02-12 15:18
Overlay icons work fine in Windows 8, I have tested version 1.8.0 (build 4714).
But it is still a problem when you use two ownCloud clients

**Comment by dragotin** [comment] 2015-02-17 14:07
Two ownCloud clients on the same machine are not supposed to work flawlessly, that is a known issue. I am removing the gold ticket as this issue is not blocking a release.

**Comment by dragotin** [comment] 2015-02-23 11:33
This is basically a duplicate of https://github.com/owncloud/client/issues/2505

**Closed by dragotin** 2015-02-23 11:33 UTC
Labels: bug
