### ISSUE TITLE
OAuth account wizard breaks when back button is used

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6574] opened 2018-06-11 10:01 UTC
Steps:
* Add a new oauth account
* In the advanced setup page hit "Back"
* Click "Re-open browser" and "Authorize" in the browser
* The browser will show "Login Error, Error returned from the server: invalid_request"

Note that the back button starts out as disabled but can be enabled by changing the folder sync type.

@ogoffart @SamuAlfageme

**Comment by SamuAlfageme** [comment] 2018-06-11 11:35
> Note that the back button starts out as disabled but can be enabled by changing the folder sync type.

Great catch @ckamm - disabling some navigation options was part of https://github.com/owncloud/client/issues/5813 but since the wizard rework happened this might have emerged

**Comment by ckamm** [comment] 2018-06-11 11:40
Huh. I cannot reproduce it anymore. :/

**Comment by ogoffart** [comment] 2018-06-18 09:04
I can reproduce!   It gets re-enabled when there is an error at the last step.

**Comment by ogoffart** [comment] 2018-06-18 10:10
When there is an error,  OwncloudAdvancedSetupPage::updateStatus and others call completeChanged() , which is connected to QWizardPrivate::_q_updateButtonStates which will re-enable the back button

We re-open the browser, but the account's credentials already have a oauth token set. So the call to the API to get a new token fails because we use the previous token instead of using the client's secret_id.

**Comment by guruz** [comment] 2018-07-23 14:21
2.5.0 beta1 is out :-)
https://central.owncloud.org/t/desktop-sync-client-2-5-0-beta1-released/14667
Everyone, please comment here if we can close this issue. Thank you.

**Comment by jnweiger** [comment] 2018-08-08 11:49
### linux mint tara

testpilotcloud version 2.5.0daily20180801 (build 9974)


    Add a new oauth account
    In the advanced setup page hit "Back"
    Click "Re-open browser" and "Authorize" in the browser
    The browser will show "Login Error, Error returned from the server: invalid_request"

The client window disappears when the browser is shown. Left-Click on the tray icon brings it back.

The first backbutton is always enabled
clicking there, visit the url again and press next, opens another browser window,

OK: login works.

Choose what to sync. Select one folder, visit the web interface, and rename that folder
change the sync folder to some folder that has contents, ignore the warnings, press cancel.
(some other error may be needed too, to enable the second back button. It worked only once for me)

Switch to 'Manually create folder sync connections" -> the second back button gets enabled.
 -> click re-open browser and auhtorize,

OK: connect successful.

**Closed by jnweiger** 2018-08-08 11:49 UTC
Labels: ReadyToTest, bug
