### ISSUE TITLE
Local file changed during sync

### ISSUE THREAD

**Issue by 123tomek** [owncloud/client#2981] opened 2015-03-18 10:28 UTC
I had problem with "Local file changed during sync". 
The cause was a bad file modification date. Modification date was earlier than the date the file was created. I think the client should be protected against this problem or at least the message should say exactly what is the cause.

Reason of my problem was:
"Gigabyte's AppCenter has one setting (on by default) to Auto Sync time.
 For an unknown reason, it decides from time to time to go back a century or so.
 Below is the evidence from the Windows Security Log (changing the date to 31/12/1899 !!!):"

Solved on:
http://www.tomshardware.co.uk/answers/id-2168294/windows-system-reverts-back-1900.html

**Comment by nekoal** [comment] 2015-03-18 18:34
For information: 31/12/1899 is aproximately zero time for Microsoft 'Date' type. It's fixed point type (length integer part and length fractional part fixed). Integer part store day difference between value and 30/12/1899. Fractional part store seconds from midnight divided 86400. There is bug in some implementations (29.02.1900 valid or not valid date) and sometimes zero time shifted to 31/12/1899. Used in Microsoft Office, Access, VBA etc. It look for me as 'Date'-typed variable was equal zero when AppCenter convert it to other type to set system time.

**Comment by RealRancor** [comment] 2015-03-18 23:39
AFAIK OC is using the milliseconds since 1.1.1970. So every date before this is invalid.

**Comment by ckamm** [comment] 2015-03-19 09:09
@123tomek Dates before 1970 are going to cause various problems for the sync client as it uses unix-epoch timestamps everywhere. The specific 'changed during sync' problem should be fixed in 1.8.0 with the fix to #2880 . Could you test with that version?

**Comment by 123tomek** [comment] 2015-03-20 18:45
Yes, for version 1.8 it is still the same problem.

**Comment by ckamm** [comment] 2015-03-25 09:03
@123tomek You're seeing 'changed during sync' messages with 1.8 for files with a very old mtime? Odd.

**Comment by ckamm** [comment] 2015-03-26 11:14
@123tomek I tried changing the mtime of an existing file to sometime in 1900 and that worked. Copying a new file into the folder that had an mtime in 1910 did also work. 

The 1910 file even retained that timestamp after it was downloaded again. The 1900 file now has a timestamp in 2036...

In general timestamps before 1970 are not going to be supported well, but the files should still upload. I could not reproduce any problems with that.

**Comment by ckamm** [comment] 2015-04-08 07:16
Please reopen if this is still an issue.

**Closed by ckamm** 2015-04-08 07:16 UTC
Labels: bug, Needs info
