### ISSUE TITLE
Ubuntu Linux Tray Icon Disappears

### ISSUE THREAD

**Issue by feisar** [owncloud/client#659] opened 2013-06-01 09:41 UTC
In Ubuntu 12.04 (Unity and XFCE) the tray icon seems to disappear after a period of time but then flash back into view when the client goes into it's '...' icon state (as opposed to the tick or cross).

I have just upgraded another desktop to Ubuntu 13.04 and the icon is never consistently present, it only appears when the icon is in the ... state or blue syncing state.

This is all using the 1.2.5 client and includes the stable v4 and v5 server versions.

Issue found in the forum here:

http://forum.owncloud.org/viewtopic.php?f=14&t=11546

**Comment by nazar-pc** [comment] 2015-01-29 15:58
via https://github.com/tux3/qTox/issues/541#issuecomment-72004515

> In order to use the tray in Ubuntu, an app seems to have to support Unity's appindicator protocol.

> https://unity.ubuntu.com/projects/appindicators/

> For APIs and code examples, see also
https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators

**Comment by lmaestro** [comment] 2015-02-19 10:21
It works fine for me  on Ubuntu 14.04 so I close this issue.
If anyone is able to reproduce, please reopen it. Thx

**Comment by nazar-pc** [comment] 2015-02-20 18:09
@lmaestro, did you updated something to make it working, or just closed issue that affects me and many others?
I'm on Ubuntu 15.04 now, didn't work for me on Ubuntu 14.10 either.

**Comment by lmaestro** [comment] 2015-02-20 18:15
what version are you using? do you want to try the beta version https://owncloud.org/install/#testing?

**Comment by nazar-pc** [comment] 2015-02-20 18:27
I had 1.7.1, updated to 1.8.0 beta testing - nothing changed, I do not see it anywhere.
Moreover, some applications when you try to open it when it is already running just opens main window, which is not the case with ownCloud. I've pointed solution from qTox project, they've fixed this issue successfully.

**Comment by manuel-uberti** [comment] 2015-03-05 14:19
Still an issue on Debian unstable with XFCE 4.10.

**Comment by nazar-pc** [comment] 2015-03-12 11:13
OK, with 8.0.0-rc1 if client already running and I'm trying to run it again - main window appears, this is really HUGE progress, but still no icon:(

**Comment by ogoffart** [comment] 2015-03-23 13:06
@nazar-pc can you describe precisely the problem again please. What version of the client, what version of Qt, which platform/desktop? And when is the icon visible or hiden?  Is it not with all the other hidden icons available with a little arrow?

**Comment by nazar-pc** [comment] 2015-03-23 15:19
@ogoffart, I have latest version of client from testing repository (1.8.0~rc1-0 right now):
> http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.10/

OS Ubuntu 15.04 x64, Desktop, installed Qt versions:
* 4.8.6+git64+g5dc8b2b+dfsg-3~ubuntu6
* 5.4.1+dfsg-2ubuntu3

Icon is never visible, at all. qTox project fixed such issue and I've already mentioned their solution above.

And I do not have little arrow, this is not Windows)

**Comment by nazar-pc** [comment] 2015-05-08 19:09
Well, another update, 1.8.1+gfsg-1 (from Ubuntu 15.10, wily-proposed), I can see icon again in top left corner (there was some new dependencies installed as well, don't know why it differs so much from opensuse.org's builds.

**Comment by nazar-pc** [comment] 2015-05-22 18:22
UNBELIVABLE!
ownCloud client 1.8.2-beta1 works, I finally have icon in tray as it should be!

**Comment by dragotin** [comment] 2015-05-23 08:17
Great! Thanks for letting us know! @danimo do we actually understand why?

**Comment by danimo** [comment] 2015-05-23 08:20
@dragotin Yes, because it seems Ubuntu builds this against Qt5, without proper systray integration. As a consequence, the icon is positioned at position 0,0 on the first physical screen. A typical Ubuntu non-solution :(

**Comment by dragotin** [comment] 2015-05-23 08:24
Ah ok. Good news anyhow.

**Comment by hefee** [comment] 2015-05-26 12:10
The relavant change is that, Qt 5.4.2 is available. At least for GNOME, LXDE and others it is solved). [debian #781368](https://bugs.debian.org/781368)

**Closed** 2015-08-05 12:54 UTC
Labels: blue-ticket

**Comment by hzprky** [comment] 2015-10-05 18:32
in an earlier comment someone stated the option that his dual screen setup is causing the OC icon to disappear from the tray.
i have a probable similar setup in operating system (linux mint 17.2), which is based on Ubuntu 14.04, and also a dual screen system.
The tray icon is not showing after reboot. When i kill the process and restart it sometimes shows up in the tray but after next boot it'S gone again. Could not find any solution since.

So i am assuming that the dual screen setup i at least part of the problem.

**Comment by incogjag** [comment] 2015-12-22 16:09
@hzprky I can't say the dual screen setup is directly related. I am using Xubuntu 14.04 with a dual screen setup and never ran into this issue. Then I moved from a standard rotating SATA hard drive to an SSD and started seeing this issue (same owncloud client version and packages on the system). It seems that there is a race condition where the icon isn't available for some reason (this is what the log file shows).

I solved it by creating a script to insert a delay before running owncloud. See this post:
https://forum.owncloud.org/viewtopic.php?f=14&t=4958

**Comment by nazar-pc** [comment] 2015-12-22 21:01
Lately I don't see icon anymore with 2.1.0-1.1, it is built with Qt 4.8.6.
I'm on Ubuntu 16.04 using repository for 15.10:
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.10

**Comment by scroom** [comment] 2016-04-22 10:01
Same here. Updated Ubuntu from 15.10 to 16.04 and the tray icon is no longer visible.

**Comment by RealRancor** [comment] 2016-04-22 10:09
@scroom https://github.com/owncloud/client/issues/4693

**Comment by Michaelvilleneuve** [comment] 2016-04-23 17:11
Same problem on 16.04. And sync is no longer working. It says in French "network access is disabled"

**Comment by danimo** [comment] 2016-04-23 19:12
@Michaelvilleneuve Using the native packages or ours for 15.10?

**Comment by Michaelvilleneuve** [comment] 2016-04-23 19:55
I've tried both, it seems to be the same. But when I remove and purge the packet and then reinstall it, it keeps the config and everything. I feel like it does not completely reinstall.

**Comment by danimo** [comment] 2016-04-23 20:44
Of course. purging never purges settings in `$HOME` for individual users. See https://doc.owncloud.org/desktop/2.1/advancedusage.html#configuration-file about where to find the per-user config-files.

**Comment by Michaelvilleneuve** [comment] 2016-04-23 21:01
Oh ok, thanks. But still I don't know how to fix this issue :/

**Comment by Bastelbursche** [comment] 2016-04-24 17:20
@Michaelvilleneuve Stupid question: Have you tried to reboot Ubuntu? After that owncloud-client asked me again for my cloud password and started to work fine.

**Comment by Michaelvilleneuve** [comment] 2016-04-24 17:44
I just did and it is the same :(. But I have noticed that when I delete my local account and then reconnect to it, it syncs again and works while I leave the app open, but no tray icon, only the app.

**Comment by nazar-pc** [comment] 2016-04-24 17:51
What is the point of asking additional questions? Just install regular Ubuntu 16.04 and regular ownCloud client and you'll 100% reproduce an issue. I do not think there is any need to write that it affects anyone because it certainly does. As well as asking whether reboot helps, because it doesn't.

Just go to #4693, press :+1: on the first message and click to "Subscribe" in the right sidebar.

And please, don't post any different issues here either, open new issue for discussion.

**Comment by gvazqu1** [comment] 2016-04-26 15:47
Same here ubuntu client 2.1.1+dfsg-1ubuntu1 disappeared from system tray after upgrade from 15.10 to 16.04.

**Comment by RealRancor** [comment] 2016-04-26 15:50
@gvazqu1 Please see one post above yours.

**Comment by Arrakeen** [comment] 2016-04-26 15:53
If you really want to get the ownCloud client icon on Ubuntu 16.04, a simple `sudo apt-get remove appmenu-qt5 ` does the trick. You're just gonna miss the themed app menus.

There is probably an environment variable that could resolve this, I haven't checked yet.

**Comment by ogoffart** [comment] 2016-04-26 15:59
The Ubuntu 16.04 issue is there. https://github.com/owncloud/client/issues/4693
