### ISSUE TITLE
Windows installer asking for admin user -> Update NSIS UAC plugin to latest version

### ISSUE THREAD

**Issue by dryo** [owncloud/client#2935] opened 2015-03-09 10:33 UTC
When I try to run the installer of the client (ownCloud-1.7.1.4382-setup.exe) it shows me this dialogue instead of the UAC prompt:
![](https://i.imgur.com/7FJMJPi.png)

The filezilla installer showed the same behaviour and [after a short discussion on the filezilla forums](https://forum.filezilla-project.org/viewtopic.php?p=132185) a solution was found: The [NSIS UAC plugin](http://nsis.sourceforge.net/UAC_plug-in) was outdated and after updating the problem was gone.

Changelog of UAC plugin says that with Version v0.2.4 (20111123) the IsAdmin detection was changed. I think this is it. I could not find out which version of UAC plugin is used in the oC client installer but at least it seems not be the latest one.

**Comment by nekoal** [comment] 2015-03-09 15:56
It seems related to #2616. May be it already updated on 1.8.0.

**Comment by danimo** [comment] 2015-03-09 16:04
Nope, no update has been performed so far.

**Comment by danimo** [comment] 2015-05-28 15:47
Approaching this in https://github.com/owncloud/client/tree/new_nsis_modules

**Comment by danimo** [comment] 2015-05-28 15:49
Installers built with that branch fail to elevate currently. I'll check as to why tomorrow.

**Comment by danimo** [comment] 2015-06-01 08:09
Duplicate of https://github.com/owncloud/client/issues/2935

**Closed by danimo** 2015-06-01 08:09 UTC
Labels: bug, Platform Specific
