### ISSUE TITLE
Confirmation before deleting a local file in the ownCloud client

### ISSUE THREAD

**Issue by jjmazur** [owncloud/client#3821] opened 2015-09-13 09:33 UTC
Hey
It happened to me that the server was deleted a very important file.
Could use a function to confirm the deletion of the local file in the ownCloud client.
As for protection before deleting important files by another person.
You might also be protected against overwriting local files.
Regards
Jan

**Comment by danimo** [comment] 2015-09-13 10:03
For accidential server deletes, there's the trashbin app. On the client side, this is a duplicate of #1069.

**Closed by danimo** 2015-09-13 10:03 UTC
