### ISSUE TITLE
Can't install on Ubuntu 16.04 (latest)

### ISSUE THREAD

**Issue by priestoferis** [owncloud/client#6034] opened 2017-09-15 05:49 UTC
### Expected behaviour
sudo apt-get install owncloud-client should install it (an upgrade removed it, that's why I even tried)

### Actual behaviour
Does not install.

```
>> sudo apt-get install owncloud-client
owncloud-client : Depends: ocqt562-libqt5webkit5 but it is not going to be installed

>> sudo apt-get install ocqt562-libqt5webkit5
ocqt562-libqt5webkit5 : Depends: ocqt562-libqt5opengl5 but it is not installable

>> sudo apt-get install ocqt562-libqt5opengl5
Package ocqt562-libqt5opengl5 is not available, but is referred to by another package.

```
### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:
Ubuntu 16.04.3 LTS
Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by Phlos** [comment] 2017-09-15 07:04
Same issue -- also commented in the Qt5 issue - has to do with that? #5470

**Comment by bytepan** [comment] 2017-09-15 08:00
Same issue -- please fix it ASAP.
Thanks !

**Comment by m3asmi** [comment] 2017-09-15 09:15
same issue

**Comment by tipichris** [comment] 2017-09-15 09:29
Also on 14.04. An upgrade failed. A 'partial upgrade' to fix things removed owncloud-client. Can't reinstall. 

`The following packages have unmet dependencies.
 owncloud-client : Depends: ocqt562-libqt5webkit5 but it is not going to be installed`

Attempting to install ocqt562-libqt5webkit5 gives
`The following packages have unmet dependencies.
 ocqt562-libqt5webkit5 : Depends: ocqt562-libqt5opengl5 but it is not installable`

```
# apt-cache policy ocqt562-libqt5opengl5
ocqt562-libqt5opengl5:
  Installed: (none)
  Candidate: (none)
  Version table:
```

Another machine that somehow survived the upgrade reports
```
$ apt-cache policy ocqt562-libqt5opengl5
ocqt562-libqt5opengl5:
  Installed: 5.6.2-1+14.1
  Candidate: 5.6.2-1+14.1
  Version table:
 *** 5.6.2-1+14.1 0
        100 /var/lib/dpkg/status
```
So it's still there, but there are no sources for it.

**Comment by SamuAlfageme** [comment] 2017-09-15 10:08
@priestoferis @Phlos @bytepan @m3asmi @tipichris we found some problems with the packages distribution and working on a fix. 

On the meantime, you guys can try the alternative mirror in: https://download.owncloud.com/repositories/desktop/download

**Comment by Phlos** [comment] 2017-09-15 10:40
Thanks @SamuAlfageme . That worked!

**Comment by priestoferis** [comment] 2017-09-15 11:07
Following the instruction on the given page I got the following errors:

```
>> sudo apt-get install owncloud-client
Err:1 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5webkit5 5.6.2-1
Protocol "http" not supported or disabled in libcurl
```
As far as I know, this error can be fixed by changing the https to http, but I can't see where.

And error for installing the recommended package `ocqt562-libqt5svg5`
```
>> sudo apt-get install ocqt562-libqt5svg5
`E: Package 'ocqt562-libqt5svg5' has no installation candidate`
```

**Comment by SamuAlfageme** [comment] 2017-09-15 11:14
@priestoferis if you properly replaced the repository URL in your `/etc/apt/sources.list.d/owncloud.list`, you should not be hitting https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04 still. Seems like openSUSE download servers are having some problems with their SSL configuration. 

If you got an incomplete installation previously try wiping out those before reinstalling from the new mirrors:

```
# apt-get purge owncloud-client
# apt-get autoremove
# apt-get autoclean
# apt-get install owncloud-client
```

**Comment by priestoferis** [comment] 2017-09-15 11:28
Ok, the issue was, that my original source list was `owncloud-client.list` while the above link's intstruction create an `owncloud.list` Thanks!

**Comment by ThroneNeNe** [comment] 2017-09-15 12:35
Thanks！ That worked!

**Comment by jnweiger** [comment] 2017-09-15 13:31
the rebuilds are ongoing. I expect the packages to be all back in ca 1h from now.

**Comment by jnweiger** [comment] 2017-09-15 15:01
I've just tested the install on ubuntu 16.04 from the official repo st
https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client

Works again, as before. Phew.

**Comment by bytepan** [comment] 2017-09-15 16:40
sudo apt-get install owncloud-client
...
The following packages have unmet dependencies:
 owncloud-client : Depends: ocqt562-libqt5webkit5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Sorry it still doesn't work.

**Comment by TimTim2017** [comment] 2017-09-15 17:42
I tried it again just now and it seems to work. I was finally able to install owncloud-client on Mint 18.2 from the official repo without unmet dependencies.

**Comment by bytepan** [comment] 2017-09-17 16:43
Solved, but I had to rename /etc/X11/Xsession.d/91ocqt562-qt5-opengl/90qt5-opengl to /etc/X11/Xsession.d/91ocqt562-qt5-opengl/90qt5-opengl.bak because it was giving error when installing ocqt562-libqt5gui5

`dpkg: error processing archive /var/cache/apt/archives/ocqt562-libqt5gui5_5.6.2-1+22.1_amd64.deb (--unpack):
 trying to overwrite shared '/etc/X11/Xsession.d/91ocqt562-qt5-opengl/90qt5-opengl', which is different from other instances of package ocqt562-libqt5gui5:amd64`

**Comment by smasherppk** [comment] 2017-09-18 15:24
Does not work on ubuntu 17.04:
Redirection from https to 'http://ftp.gwdg.de/pub/opensuse/repositories/isv:/ownCloud:/desktop/Ubuntu_17.04/amd64/owncloud-client_2.3.3-8338_amd64.deb' is forbidden

**Comment by jnweiger** [comment] 2017-09-18 20:21
@smasherppk as a workaround, please check the files
/etc/apt/sources.list.d/owncloud-client.list and /etc/apt/sources.list.d/owncloud.list

Only one of them should exist, and the URLs in there need to be all https:// URLs in your case.
Please edit if needed.

**Comment by bee272** [comment] 2017-09-21 10:45
Thanks jnweiger, using your http link and changing version to 16.04 solved the issue on my 16.04 as well.

**Comment by ernstki** [comment] 2017-09-22 17:55
I think this issue needs to be reopened, because the "download" links from everywhere else on the web site point to the openSuSE site.

Which as of today still produces the errors described by the reporter.

There is also [mention of this problem](https://central.owncloud.org/t/repository-bug-on-ubuntu-16-04/9546) in the forums (which I'm going to go reply to in a minute, to point them here).

**Comment by kdslkdsaldsal** [comment] 2017-09-22 21:17
Probably solved anyway once https://github.com/owncloud/owncloud.org/pull/1277 is accepted / merged and the new links are published. So probably no need to re-open this.

**Comment by kemoc** [comment] 2017-09-25 21:13
I have the same problem, 
maybe this will help for devs 
[stack-curl-problem](https://stackoverflow.com/questions/6684235/perl-curl-1-protocol-http-not-supported-or-disabled-in-libcurl)
i know there is about problem with cURL  on windows but maybe we have the same pb on linux.

**Comment by michaelstingl** [comment] 2017-09-26 06:36
OBS issue has been reported: https://bugzilla.opensuse.org/show_bug.cgi?id=1060231

**Comment by jnweiger** [comment] 2017-09-26 19:18
Fixed by the friendly openSUSE admins as discussed in https://github.com/openSUSE/software-o-o/issues/123
Our downloads there should now work again!

**Comment by kemoc** [comment] 2017-09-27 18:23
@jnweiger i confirm, on ubuntu 16.04 works, thanks.

**Comment by atanasantonov** [comment] 2017-09-29 09:09
@SamuAlfageme Thank You!!!

**Comment by shaneonabike** [comment] 2017-09-29 14:30
The solution by @SamuAlfageme was really the only solution that worked thanks so much bro!

**Comment by shaneonabike** [comment] 2017-10-25 12:27
Sigh on another machine this is not working for me anymore :/

I'm getting

`The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.3.3-8338) but it is not going to be installed
                   Depends: ocqt562-libqt5core5a but it is not going to be installed
                   Depends: ocqt562-libqt5dbus5 but it is not going to be installed
                   Depends: ocqt562-libqt5gui5 but it is not going to be installed
                   Depends: ocqt562-libqt5keychain1 but it is not going to be installed
                   Depends: ocqt562-libqt5network5 but it is not going to be installed
                   Depends: ocqt562-libqt5webkit5 but it is not going to be installed
                   Depends: ocqt562-libqt5widgets5 but it is not going to be installed
                   Depends: ocqt562-libqt5xml5 but it is not going to be installed
                   Depends: owncloud-client-l10n but it is not going to be installed
                   Depends: ocqt562-libqt5sql5-sqlite but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by jnweiger** [comment] 2017-10-25 12:35
@shaneonabike do you have multiple repostories in the system?
It is a very frustrating message from apt to say 'is not going to be installed' for all the dependencies that should be installed. Can you try an explicit

```
apt-get install -f
apt-get install libowncloudsync0 
```

maybe that gives us a hint why it decides not to install the needed packages...

**Comment by shaneonabike** [comment] 2017-10-25 15:13
I don't think so @jnweiger ... how would I determine that. Obviously Ubuntu would have it's own right?
When I tried your solution I get the same issue...

`The following information may help resolve the situation:

The following packages have unmet dependencies:
 libowncloudsync0 : Depends: ocqt562-libqt5core5a but it is not going to be installed
                    Depends: ocqt562-libqt5gui5 but it is not going to be installed
                    Depends: ocqt562-libqt5keychain1 but it is not going to be installed
                    Depends: ocqt562-libqt5network5 but it is not going to be installed
                    Depends: ocqt562-libqt5widgets5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by guruz** [comment] 2017-10-30 17:07
@shaneonabike Please double-check your sources.list (and similar files)..

**Comment by shaneonabike** [comment] 2017-10-30 17:21
Well it's grabbing it from here which I believe is correct non?

`owncloud-client.list:# deb http://download.owncloud.com/repositories/desktop/Ubuntu_16.04/ /
owncloud-client.list.save:# deb http://download.owncloud.com/repositories/desktop/Ubuntu_16.04/ /
`

**Comment by jdcrecur** [comment] 2017-11-01 10:13
Same issue on linux mint (ubuntu 16.1 underneath) 

```
/ # apt-get install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 owncloud-client : Depends: libowncloudsync0 (= 2.3.3-8338) but it is not going to be installed
                   Depends: ocqt562-libqt5core5a but it is not going to be installed
                   Depends: ocqt562-libqt5dbus5 but it is not going to be installed
                   Depends: ocqt562-libqt5gui5 but it is not going to be installed
                   Depends: ocqt562-libqt5keychain1 but it is not going to be installed
                   Depends: ocqt562-libqt5network5 but it is not going to be installed
                   Depends: ocqt562-libqt5webkit5 but it is not going to be installed
                   Depends: ocqt562-libqt5widgets5 but it is not going to be installed
                   Depends: ocqt562-libqt5xml5 but it is not going to be installed
                   Depends: owncloud-client-l10n but it is not going to be installed
                   Depends: ocqt562-libqt5sql5-sqlite but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by jnweiger** [comment] 2017-11-02 11:06
I am still stuck understanding the  '.. but it is not going to be installed' part. For me it just means, that
something is in a bad state. I cannot reproduce the issue. Neither with fresh installs, nor with the upgrades I tried. 

@shaneonabike @jdcrecur can you please post the output of

```
apt policy owncloud-client ocqt562-libqt5core5a

**Comment by jdcrecur** [comment] 2017-11-02 11:20
```
# apt policy owncloud-client ocqt562-libqt5core5a
owncloud-client:
  Installed: (none)
  Candidate: 2.3.3-8338
  Version table:
     2.3.3-8338 500
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.10  Packages
     2.1.1+dfsg-1ubuntu1.1 500
        500 http://ftp.hosteurope.de/mirror/archive.ubuntu.com xenial-updates/universe amd64 Packages
     2.1.1+dfsg-1ubuntu1 500
        500 http://ftp.hosteurope.de/mirror/archive.ubuntu.com xenial/universe amd64 Packages
ocqt562-libqt5core5a:
  Installed: (none)
  Candidate: 5.6.2-1+22.1
  Version table:
     5.6.2-1+22.1 500
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.10  Packages

```

**Comment by jdcrecur** [comment] 2017-11-02 11:33
```
$ apt-get install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 owncloud-client : Depends: libowncloudsync0 (= 2.3.3-8338) but it is not going to be installed
                   Depends: ocqt562-libqt5core5a but it is not going to be installed
                   Depends: ocqt562-libqt5dbus5 but it is not going to be installed
                   Depends: ocqt562-libqt5gui5 but it is not going to be installed
                   Depends: ocqt562-libqt5keychain1 but it is not going to be installed
                   Depends: ocqt562-libqt5network5 but it is not going to be installed
                   Depends: ocqt562-libqt5webkit5 but it is not going to be installed
                   Depends: ocqt562-libqt5widgets5 but it is not going to be installed
                   Depends: ocqt562-libqt5xml5 but it is not going to be installed
                   Depends: owncloud-client-l10n but it is not going to be installed
                   Depends: ocqt562-libqt5sql5-sqlite but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

john-  / # libowncloudsync0
libowncloudsync0: command not found

john- / # apt-get install libowncloudsync0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libowncloudsync0 : Depends: libsqlite3-0 (>= 3.12.0) but 3.11.0-1ubuntu1 is to be installed
                    Depends: ocqt562-libqt5core5a but it is not going to be installed
                    Depends: ocqt562-libqt5gui5 but it is not going to be installed
                    Depends: ocqt562-libqt5keychain1 but it is not going to be installed
                    Depends: ocqt562-libqt5network5 but it is not going to be installed
                    Depends: ocqt562-libqt5widgets5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

It looks like if libowncloudsync0 is the issue then the this could be sqlite:
> Depends: libsqlite3-0 (>= 3.12.0) but 3.11.0-1ubuntu1 is to be installed

**Comment by shaneonabike** [comment] 2017-11-02 12:50
owncloud-client:
  Installed: (none)
  Candidate: 2.3.3-8338
  Version table:
     2.3.3-8338 500
        500 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  Packages
     2.2.2+dfsg-1ubuntu0.2 500
        500 http://ca.archive.ubuntu.com/ubuntu yakkety-updates/universe amd64 Packages
     2.2.2+dfsg-1 500
        500 http://ca.archive.ubuntu.com/ubuntu yakkety/universe amd64 Packages
ocqt562-libqt5core5a:
  Installed: (none)
  Candidate: 5.6.2-1+22.1
  Version table:
     5.6.2-1+22.1 500
        500 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  Packages

**Comment by shaneonabike** [comment] 2017-11-02 12:53
Furthermore, when I dig deeper it looks like it goes beyond libowncloudsync0. When I trace it down to the core problem I //believe// that it's related to no install candidate for libicu55 :/

`The following packages have unmet dependencies:
 libowncloudsync0 : Depends: ocqt562-libqt5core5a but it is not going to be installed
                    Depends: ocqt562-libqt5gui5 but it is not going to be installed
                    Depends: ocqt562-libqt5keychain1 but it is not going to be installed
                    Depends: ocqt562-libqt5network5 but it is not going to be installed
                    Depends: ocqt562-libqt5widgets5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
shaneonabike@local:~$ sudo apt-get install ocqt562-libqt5core5a
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 ocqt562-libqt5core5a : Depends: libicu55 (>= 55.1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
shaneonabike@local:~$ sudo apt-get install libicu55
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libicu55 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu55' has no installation candidate
`

**Comment by jnweiger** [comment] 2017-11-02 16:38
apt policy libicu55
libicu55:
  Installed: (none)
  Candidate: 55.1-7ubuntu0.3
  Version table:
     55.1-7ubuntu0.3 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     55.1-7 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

No?

**Comment by jdcrecur** [comment] 2017-11-02 16:53
```
$ apt policy libicu55
libicu55:
  Installed: 55.1-7ubuntu0.3
  Candidate: 55.1-7ubuntu0.3
  Version table:
 *** 55.1-7ubuntu0.3 500
        500 http://ftp.hosteurope.de/mirror/archive.ubuntu.com xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     55.1-7 500
        500 http://ftp.hosteurope.de/mirror/archive.ubuntu.com xenial/main amd64 Packages
```

**Comment by jnweiger** [comment] 2017-11-02 17:39
@jdcrecur you are one ahead of @shaneonabike regarding libicu55.

**Comment by shaneonabike** [comment] 2017-11-02 17:48
I was on Ubuntu 16.10 so I added that additional package which is _super halloween_ weird that it was not there. I checked and there are no other remaining strange packages. Also, adding that package does not seem to make the system aware of that package. Looking in synaptic I can see that there is a **libicu57** but not a libicu55?

**Comment by jnweiger** [comment] 2017-11-02 18:19
@shaneonabike there is confusion with 16.10 and 16.04 in your system.

source /etc/os-release
echo $VERSION_ID
echo $UBUNTU_CODENAME

search for everyhting in /etc/apt/sources.list and /etc/apt/sources.list.d/* that has a different version_id or a different codename.

**Comment by shaneonabike** [comment] 2017-11-02 18:27
That! is so strange. But you were totally right and after I switched the owncloud it was happy as a clam. I apologize for all the false positive and I appreciate you helping me out @jnweiger

**Comment by jnweiger** [comment] 2017-11-03 18:06
I guess, we can close here for now. This second round did not have much in common with the first round anyway.

**Closed by jnweiger** 2017-11-03 18:06 UTC
Labels: Known Issue / Workaround, packaging

**Comment by jdcrecur** [comment] 2017-11-03 18:13
Any idea on how to fix the sqlite issue?

> Depends: libsqlite3-0 (>= 3.12.0) but 3.11.0-1ubuntu1 is to be installed

**Comment by kdslkdsaldsal** [comment] 2017-11-03 18:20
@jdcrecur You're using the Ubuntu 16.10 repository:

> 500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.10  Packages

but your base system is 16.04:

> Depends: libsqlite3-0 (>= 3.12.0) but 3.11.0-1ubuntu1 is to be installed

https://packages.ubuntu.com/search?keywords=libsqlite3-0

If you add a 3rdparty repository to your system make sure that it is matching your OS.

**Comment by jdcrecur** [comment] 2017-11-05 23:32
@kdslkdsaldsal 
Thanks! Switching to 16.04 fixed the issue, i just assumed Linux Mint Cinnamon was based on the desktop distro of ubuntu. Thanks for the tip! It now works.

There must have been something recent that changed as on another linux mint machine half a year ago the install with the desktop owncloud-client apt repo worked from 16.10. 

Thanks again!

**Comment by socrat3000** [comment] 2017-12-27 06:36
Hi guys,
It seems it got broken again after owncloud-client 2.4 is released:

sudo apt install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.4.0-8911) but it is not going to be installed
                   Depends: ocqt562+240-libqt5core5a but it is not installable
                   Depends: ocqt562+240-libqt5dbus5 but it is not installable
                   Depends: ocqt562+240-libqt5gui5 but it is not installable
                   Depends: ocqt562+240-libqt5keychain1 but it is not installable
                   Depends: ocqt562+240-libqt5network5 but it is not installable
                   Depends: ocqt562+240-libqt5webkit5 but it is not installable
                   Depends: ocqt562+240-libqt5widgets5 but it is not installable
                   Depends: ocqt562+240-libqt5xml5 but it is not installable
                   Depends: owncloud-client-l10n but it is not going to be installed
                   Depends: ocqt562+240-libqt5sql5-sqlite but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by michaelstingl** [comment] 2017-12-27 11:21
@socrat3000 work is going on in https://github.com/owncloud/client/issues/6267

**Comment by jnweiger** [comment] 2017-12-27 11:29
@socrat3000 fixed. Please try again.

**Comment by socrat3000** [comment] 2017-12-30 19:07
Works perfectly, I fell in love with it instantly!

Kind Regards,

Ahmad Amr

**Comment by tdeuling** [comment] 2018-02-13 11:21
Hi,
is it broken again?
I receive the same error on Linux Mint 18.1 Cinnamon 64-bit.
```
sudo apt-get install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.4.0-8911) but 2.1.1+dfsg-1ubuntu1.1 is to be installed
                   Depends: ocqt562+240-libqt5core5a but it is not going to be installed
                   Depends: ocqt562+240-libqt5dbus5 but it is not going to be installed
                   Depends: ocqt562+240-libqt5gui5 but it is not going to be installed
                   Depends: ocqt562+240-libqt5keychain1 but it is not going to be installed
                   Depends: ocqt562+240-libqt5network5 but it is not going to be installed
                   Depends: ocqt562+240-libqt5webkit5 but it is not going to be installed
                   Depends: ocqt562+240-libqt5widgets5 but it is not going to be installed
                   Depends: ocqt562+240-libqt5xml5 but it is not going to be installed
                   Depends: ocqt562+240-libqt5sql5-sqlite but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I'm using this URL:
```
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.10/ /
```

**Comment by guruz** [comment] 2018-02-13 13:36
@tdeuling `2.1.1+dfsg-1ubuntu1.1` is something from upstream Ubuntu, not from owncloud.org..
Maybe check /etc/apt/sources.list and /etc/apt/sources.list.d/*  ?

**Comment by tdeuling** [comment] 2018-02-14 06:48
Yesterday I performed a distribution update. Now I'm running 18.3 and the current version of owncloud-client works well.
Version 2.1.1 wasn't new enough for communicating with Server version 10.0.6.

**Comment by guruz** [comment] 2018-02-14 11:52
@tdeuling 2.1.1 is the one from the Mint/Ubuntu/idontknowwhat:-) repositories.
You need the client from ownCloud's repositories which are on download.opensuse.org (yes, confusing hostname, @jnweiger is working on changing that).

**Comment by typoworx-de** [comment] 2021-02-16 14:18
Also can't install. An AppImage or Snap would have been nice to avoid dependency problems for users with older distributions (same here).

**Comment by TheOneRing** [comment] 2021-02-16 14:45
We are working on an official AppImage
