### ISSUE TITLE
"Are you sure to delete all files?" warning broken?

### ISSUE THREAD

**Issue by leipert** [owncloud/client#3066] opened 2015-04-03 10:37 UTC
The following scenario happened to me today and it is more than less my fault, but as a result I want to propose some changes to the client which would have saved my ass.

I had OC7 installed on my Synology NAS with a third party package by synocommunity. This package made an automatic update to OC8, deleted everything except the config.php and the database. My files now only contained the default owncloud folders Documents, Pictures & the howto.pdf.

My Computer connected to the updated OC8, showed "Deleted Archive and 8954 files" and 18 GB of data vanished without warning. I suppose (#2483) only triggers if the synced folder would be completely empty.

As OC is also for consumers, it would be nice if:

1. Users should be warned before a significant portion of their files will be deleted. If you have 18GB of files and 17GB are gonna be deleted, a warning would be nice. Same goes if you have 5000 files and 4000 are deleted. Maybe the percentage should not be linear, but some sort of adjusted scale, so if you only have 10 files and delete 6, you get no warning. This warnings are adjustable for pro-users so that you can turn them off if needed.

2. Move deleted files to trash (#1874, #1069).

Both of those would have made my day (besides having backups on my machine or NAS)

**Comment by guruz** [comment] 2015-04-03 10:55
This sounds weird. Are you sure those _third party_ packages are not to be blamed? Maybe your data is on another folder on the NAS?

In any case, I think #2483 works also for not-empty cases (CC @ogoffart can you look at that?)

**Comment by nekoal** [comment] 2015-04-04 04:43
I can confirm about new account with default owncloud folders Documents, Pictures & the howto.pdf. Client or web interface show warning only when last file can be deleted. May be client need detect root folder with only default files and show warning too.

**Comment by ogoffart** [comment] 2015-04-04 09:55
Normaly, even if there is an "hello.pdf" that is common, it should still have been seen as modified since the etag is most likely not the same as it is generated as random. and therefore it should have shown the warning.

But there might be a bug anyway.  It would be nice if I could get the logs.

**Comment by leipert** [comment] 2015-04-04 17:13
As far as I can see there are no logs on the client. The logwindow just shows logs from right now.
I could only try to reproduce the problems and save the logs. Would that help you?

**Comment by ogoffart** [comment] 2015-04-04 18:19
Yes, that would help me.

**Comment by nekoal** [comment] 2015-04-05 02:58
.owncloud.log (tests with new account)
Local database and log were rewritten. Is it designed?
When selected "Save files" in warning client don't show any fileid or etag in log file record about uploading. Will file get new fileid?
https://gist.github.com/nekoal/2210e991fa74a4e3b0a7

@leipert Are your owncloud data folder was configured by default into owncloud web directory? Install guide for OC 8 recomend to select other location and/or backup data folder before major updates (such as OC7 to OC8). It may be main reason of data deletion, so for this case you need reconfigure location of data folder to prevent data loss in future updates.

**Comment by leipert** [comment] 2015-04-05 13:20
Yes. The package of the synocommunity seems to be configured this way.
I will ask them to add a warning during the upgrade process.

As for now I setup a backup solution on my NAS watching the owncloud data folder and also on my Computer. I will have a look into moving it on the NAS

I will try to reproduce the log within the next two weeks as I will get a new NAS where I can test it with a fresh install.

**Comment by ogoffart** [comment] 2015-04-06 12:16
the .owncloud.log is not so usefull actually,  the log from --logwindow or --logfile would be more helpfull

**Comment by ogoffart** [comment] 2015-08-17 14:00
Closing this bug because I have not enough information.

**Closed by ogoffart** 2015-08-17 14:00 UTC
Labels: bug, Needs info, ReadyToTest, sev3-medium

**Comment by leipert** [comment] 2015-08-17 14:02
@ogoffart. Sorry, I never answered. I suppose it was some problem with synology.
I just migrated to syncthing, sorry that I didn't report more details.
