### ISSUE TITLE
Starting client while already running sometimes doesn't show settings window

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#7018] opened 2019-02-06 13:35 UTC
steps to reproduce : 
after client-configuration and client runs properly : 
- go to  tray-icon in taskbar and quit owncloud
- doppel-click on owncloud-icon on Desktop >> nothing opens just owncloud-client is started in background and tray-icon in taskbar appears again
- again doppel-click >> nothing happens
- again doppel-click >> now owncloud-window opens 

regards

windows 10 client 2.5.3rc1

**Comment by ckamm** [comment] 2019-03-07 10:40
It's intentional that starting the client usually doesn't lead to a window popping up. We don't want the settings window to be shown every windows startup.

What's odd is that the second time you start the client nothing happens. The intended behavior is that starting the client while it's already running will lead to the settings window popping up.

**Comment by guruz** [comment] 2019-06-04 07:41
Maybe some windows popup protection?
Moving to 2.6.1 though

**Comment by ogoffart** [comment] 2019-06-04 12:08
There is a 10 second delay from startup for which we won't show the settings:

https://github.com/owncloud/client/blob/e82dc141f7696b208102324750a052f55a5e7ccf/src/gui/application.cpp#L523-L529


The reason is that some auto-start script tends to start the application twice :-/

**Comment by guruz** [comment] 2019-06-04 12:20
> session restore and auto start

That's a linux thing though?
Or I heard that Windows might do this too?

In general, our auto start setting could in theory launch the client with something like  `--from-autostart` and then adjust behaviour somehow?
But maybe this is all not worth the trouble.

**Comment by HanaGemela** [comment] 2020-01-08 13:22
@TheOneRing is this issue fixed? There isn't `ReadyToTest` label
If it is fixed, could you specify the expected result here? When should settings dialog open?

**Comment by TheOneRing** [comment] 2020-01-08 13:27
I don't think so it would probably require changes to the installer to invoke the client with a -s

**Comment by TheOneRing** [comment] 2020-02-27 13:43
Adopt desktop files and windows shortcuts to pass -s to the client.

**Comment by jnweiger** [comment] 2020-03-03 16:51
PR #7784 fixes this issue for me.
It nicely implements the general UX-rule that every user interaction should have an immediate reaction.
Regarding Windows and Mac: do we do the same there?

**Comment by HanaGemela** [comment] 2020-05-04 13:32
What is the expected results for macOS? 

Windows - setting window opens on every double click
macOS - setting window never opens on double click
Linux  - setting window opens on every double click

**Comment by michaelstingl** [comment] 2020-05-11 12:19
> macOS - setting window never opens on double click

Okay for now 👍

**Closed** 2020-05-11 12:24 UTC
Labels: Design & UX, sev3-medium
