### ISSUE TITLE
[Windows] in Option Settings, the URL does not look good

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3832] opened 2015-09-15 08:24 UTC
### Steps to reproduce
1. Install the version 2.0.2
2. Create two accounts (e.g: user1@docker.oc......, user2@docker.oc.....)
3. Right click to icon oC
4. Click on Settings...

### Expected behaviour
You should see the entire URL address

### Actual behaviour
It does not look good at URL
![screen shot 2015-09-15 at 10 16 06](https://cloud.githubusercontent.com/assets/12032058/9871295/f229bd7e-5b92-11e5-95f5-3435d7e17685.png)

### Server configuration
Desktop v ownCloud-2.0.2.5463-nightly20150915-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.1.1.3","versionstring":"8.1.1","edition":"Enterprise"}

**Comment by phil-davis** [comment] 2015-09-15 09:30
Version 2.0.2-nightly20150915 (build 5463)
If I make the window wider then the ellipsized name works:
![e1](https://cloud.githubusercontent.com/assets/1535615/9872932/35971880-5bbc-11e5-9f7d-3c9feb77e60a.png)
If I make the winodw more narrow, then the beginning and end of the account name and/or URL is chopped off:
![e2](https://cloud.githubusercontent.com/assets/1535615/9872982/8aaa504e-5bbc-11e5-8172-62db2f7c7c9e.png)

**Comment by dragotin** [comment] 2015-09-15 13:01
The problem is: The code in `QString AccountState::shortDisplayNameForSettings(int width) const` elides the text to width. However, in `SettingsDialog::accountAdded(AccountState *s)` the parameter width is set to `height * 1.618`.

That is fine if there is enough space, however, if the width of a tab is smaller than `height*1.618`  because the dialog is not wide enough, the eliding does not help.

**Comment by ogoffart** [comment] 2015-10-23 14:24
The ellipsis is by design.  When the text is too big, we ellide the URL in the middle. It's the expected behaviour.

The problem found by @phil-davis should be fixed now.

**Comment by phil-davis** [comment] 2015-10-23 15:54
I will try tomorrow morning with the overnight 2.1 build...

**Comment by phil-davis** [comment] 2015-10-24 09:08
Version 2.1.0-nightly20151024 (build 5579)
The text of user name or server host name no longer gets cut off at the left or right edge when the window width is made smaller - fixed.
![owncloud21](https://cloud.githubusercontent.com/assets/1535615/10709910/0497e19e-7a5f-11e5-93de-70064f80e098.png)

**Closed** 2015-10-26 08:55 UTC
Labels: bug, Platform Specific, ReadyToTest
