### ISSUE TITLE
Help Connection Failed

### ISSUE THREAD

**Issue by westlounge** [owncloud/client#3415] opened 2015-07-07 09:39 UTC
Hello,

I've a connection problem with 2 acount to my readynas with owncloud 8.0.4
Log error in server => Nothing
In owncloud client sync i've message "une erreur est survenue lors de l'ouverture d'un dossier. Connexion fermée"
And with another computer i've message "la poignée de main SSL à échouée".

I've 6 other acount which run correctly.

Do you have an idea ?

**Comment by ogoffart** [comment] 2015-07-07 13:05
What's your version of the owncloud client? (and the build number)
It sounds like a duplicate of https://github.com/owncloud/client/issues/3373
In that case, there is a new build of the 1.8.3 client that should fix this problem.

> "la poignée de main SSL à échouée"

Is that really what the message says.  If so there is two grammar mistake in the translation.  ("à échouée" -> "a échoué").  But i could not find this message in the mirall's translation.

**Comment by westlounge** [comment] 2015-07-07 18:08
i join a picture with the error
![file php](https://cloud.githubusercontent.com/assets/13217091/8553469/dd4ceb00-24e3-11e5-842e-1e434e21d57b.png)

**Comment by ogoffart** [comment] 2015-07-08 15:13
What version of the client is this? What's the build number?  
Can you try with at least 1.8.3.5250 ?

**Closed** 2015-07-29 15:36 UTC
Labels: Needs info
