### ISSUE TITLE
Missing toolbar after vanilla upgrade (`openSUSE 15.4`) to 5.0

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11188] opened 2023-09-07 07:55 UTC
Vanilla upgrade (`openSUSE 15.4`):

After the upgrade from 4.2, desktop-client doesn't have toolbar. Any missing packages that I have to install?

![Screenshot from 2023-09-06 17-02-26](https://github.com/owncloud/client/assets/52366632/fe3ec2f6-2be9-4615-96f1-a105d0910c06) | ![Screenshot from 2023-09-06 16-40-45](https://github.com/owncloud/client/assets/52366632/9e1cf1e1-1646-440d-b0e3-d83a82d4be66)
--|--
4.2 | 5.0

_Originally posted by @saw-jan in https://github.com/owncloud/client/issues/11171#issuecomment-1708154811_

**Comment by TheOneRing** [comment] 2023-09-07 08:09
Duplicate of https://github.com/owncloud/client/issues/11163

**Closed by TheOneRing** 2023-09-07 08:09 UTC
