### ISSUE TITLE
[macOS][Overlays] Large number of files to sync freezes the application when sending the status to Finder

### ISSUE THREAD

**Issue by Joshuasony** [owncloud/client#5361] opened 2016-12-06 17:05 UTC
### Expected behaviour
OwnCloud should run normally and sync my files.

### Actual behaviour
OwnCloud puts MacBook under heavy load and the application freezes (fans go wild).

### Steps to reproduce
1. Start OwnCloud Application
2. Wait for files to be synced
3. Wait for application to freeze

### Client configuration
Client version: 2.2.4 (build 3709)

Operating system: macOS Sierra 10.12.1

OS language: German

Installation path of client: Harddisk/Applications/

### Logs
Analysis of owncloud process:
https://gist.github.com/Joshuasony/375ce7815d53a700a3fb757f26710433
Spindump of owncloud process:
https://gist.github.com/Joshuasony/a35054e33d50147f3ccee10a19ca9b9e

**Comment by jturcotte** [comment] 2016-12-07 12:55
The process seems stuck sending overlay icon status to Finder. I'm wondering if this is because too many statuses are sent, or because Finder is slow to respond for some reason.

Could you provide the client log file as described at https://doc.owncloud.org/desktop/2.2/troubleshooting.html#obtaining-the-client-log-file ?

It would also be nice to know what kind of sync you are attempting:
- Is it the first sync? If no, approximately how many files do you expect need to be uploaded to the server? How many to be downloaded?
- How many files in total are in your client directory?
- Is there any particular condition that you think helps reproducing the issue?

**Comment by guruz** [comment] 2016-12-07 13:01
* Do you have a lot of folders unselected from syncing? (in the client folder view)

**Comment by Joshuasony** [comment] 2016-12-07 14:48
Thanks for the fast reply! 

@jturcotte 
* It is not the first sync. I'm not sure about the amount of files, but probably between 1 -100 downloaded and/or uploaded. Sometimes more, depending on what the teammembers upload. 
* 373494 Files, 59.16GB
* I was thinking about Sierra being the problem, because other teammembers did not upgrade and do not encounter this issue.
I'll try to obtain the client log file.

@guruz 
* yes, I've unselected a lot of subfolders. 
Also i noticed that it takes owncloud a very long time to scan for changes...

**Comment by guruz** [comment] 2016-12-07 16:02
Do you see a lot of
```
File is listed on the ignore list.
```
or
```
File/Folder is ignored because it's hidden.
```
together with ```OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:IGNORE:```? 

Also interesting would be the amount of individual sendMessage with the same parameters in a batch of them.

Because I felt this causes a lot of load for me but I have not verified this.

**Comment by guruz** [comment] 2016-12-07 16:09
@jturcotte From the trace: 
```
986  OCC::SyncFileStatusTracker::slotAboutToPropagate(QVector<QSharedPointer<OCC::SyncFileItem> >&) + 809 (libowncloudsync.2.2.4.dylib + 504937) [0x10ee0d469]
```

My guess is we could improve this by something like https://github.com/owncloud/client/issues/5356 ... One could shard the vector in multiple parts and process those parts incrementally

(Another solution could be if SocketApiSocket or somewhere before would batch messages together instead of sending them indivdually)

**Comment by Joshuasony** [comment] 2016-12-07 17:21
I've got 112 items on the list of ignored or corrupt files.

**Comment by Joshuasony** [comment] 2016-12-07 17:25
Also, it always says, there there are 28GB to sync, but 0 seconds left to sync:

<img width="303" alt="screenshot 2016-12-07 18 23 37" src="https://cloud.githubusercontent.com/assets/7139459/20978770/67d4c324-bcaa-11e6-983a-2c0b436c2725.png">

**Comment by Joshuasony** [comment] 2016-12-08 08:24
Here is the requested logfile: https://www.dropbox.com/s/2euu1ujpnvgujty/logfile.txt?dl=0
I hope it helps.

**Comment by jturcotte** [comment] 2016-12-08 11:28
Alright, looks like you're adding a large number of files in `ux owncloud`, and we have to tell Finder for all of those files that it's now going to be in the sync (🔄) state. It's actually a lot of wasted resources and we should try to find a way to only push file statuses of what is already in the overlay icon plugin cache.

Meanwhile, I think that disabling the overlay icon plugin in **System Preferences / Extensions** should allow you to get through that sync and you can re-enable them afterward to see the status of syncs involving less files in the sync state.

**Comment by Joshuasony** [comment] 2016-12-08 14:04
nice, thanks @jturcotte, this seems to be a workaround for the issue. 
What does this option in the System Preferences actually do?
I shall activate it after a few days to see if something is different.

**Comment by jturcotte** [comment] 2016-12-08 14:17
Thanks for confirming!

The option tells Finder and other macOS apps showing file dialogs to load our plugin which connects to the ownCloud client and subscribes to file status changes to be displayed. Disabling it will remove the ✅- and 🔄-looking icons on files of a synchronized directory in Finder, so you might want to re-enable it if you'd like to know if a file you're working on is currently being downloaded or uploaded to the ownCloud server.

**Comment by guruz** [comment] 2017-01-02 07:29
@jturcotte is working on bloom filters to improve performance for the Finder plugin communication.

**Comment by jturcotte** [comment] 2017-01-18 13:28
# Testing recommendations (e.g. for @SamuAlfageme)

The patch now avoid sending status that are unlikely to be even visible in Finder, explorer, etc. The logic is that we remember all directories that had the status of at least one of its file requested since the connection to the SocketAPI. It remembers through a bloom filter which means that we get ~3% false positives (status sent even if not requested) until the user navigated in 100 directories.

That the number of status push is decreased works, but this change risks introducing cases where the status is *not* pushed, even though it's currently displayed to the user (meaning it might show as OK even though it's still waiting to be synced, or resulted in an error). This can happen for example if the cache on Finder's side is not reset when we shutdown the client, or remove a sync folder connection (which results in an UNREGISTER_PATH message).

**Comment by guruz** [comment] 2017-01-20 14:45
@Joshuasony Are you willing to test a 2.3 pre-release with @jturcotte 's optimizations?
http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.3979pre1.pkg
Thanks!

**Comment by Joshuasony** [comment] 2017-01-20 15:11
Hi @guruz, thanks and sure, I will test it and let you know about my results.

**Comment by SamuAlfageme** [comment] 2017-02-15 16:33
I stressed this a bit by uploading with quite large file batches (~4000 files & folders) and the `ownCloud Extensions` process is always under 1% CPU usage while keeping the overlay status "on sync" with what's being reflected on the `Sync Protocol` tab. So I'm closing here as I believe it's fixed; @Joshuasony if you see something odd, feel free to reopen. Thanks!

**Closed by SamuAlfageme** 2017-02-15 16:33 UTC
Labels: Performance, ReadyToTest
