### ISSUE TITLE
owncloud-client since 2.2.x doesn't reconnect after waking up from suspend

### ISSUE THREAD

**Issue by joysfera** [owncloud/client#4839] opened 2016-05-14 06:23 UTC
### Expected behaviour
when computer wakes up from suspend the owncloud client should reconnect to server. Please note that this has been working correctly in the last few weeks when I was using the nightlies to test issue with dot files not being synchronized. It had been working correctly since I started using ownCloud half a year ago. It has just stopped working few days ago, like since May 12 when the version 2016512 arrived.

### Actual behaviour
owncloud client shows "No connection to ownCloud at [MyServer]. Network access is disabled."
Restarting the owncloud client helps, i.e. it connects to server immediately (so it's not a server issue).

### Steps to reproduce
1. suspend your computer (put to sleep)
2. wake up your computer

### Client configuration
Client version: 2.2.0~nightly2016512-1.1 (DEB package for xUbuntu 15.10)

Operating system: Ubuntu 16.04 64-bit

### Logs
Computer woke at 08:30:00
```
05-14 08:30:03:472 3365 unknown: "Žádné rozhraní „org.freedesktop.DBus.Properties“ neexistuje na objektu na cestě /"
05-14 08:30:14:304 3360 OCC::Folder::slotRunEtagJob: * Trying to check "http://aspire/owncloud/remote.php/webdav/" for changes via ETag check. (time since last sync: 139 s)
05-14 08:30:14:305 3360 OCC::FolderMan::slotRunOneEtagJob: Scheduling "http://aspire/owncloud/remote.php/webdav/" to check remote ETag
05-14 08:30:14:305 3360 OCC::RequestEtagJob::start: getting etag: request network error:  "Network access is disabled."
05-14 08:30:14:305 3360 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "http://aspire/owncloud" + "/" "OCC::Folder"
05-14 08:30:14:305 3360 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Network access is disabled." QVariant(Invalid)
05-14 08:30:25:305 3360 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
05-14 08:30:25:305 3360 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "http://aspire/owncloud" + "/" "OCC::ConnectionValidator"
05-14 08:30:25:305 3360 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Network access is disabled." QVariant(Invalid)
05-14 08:30:25:305 3360 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
05-14 08:30:25:305 3360 unknown: QIODevice::read (QDisabledNetworkReply): device not open
05-14 08:30:25:305 3360 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Connected" -> "Timeout"
05-14 08:30:25:305 3360 OCC::AccountState::setState: AccountState state change:  "Connected" -> "Network error"
05-14 08:30:25:305 3360 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href="http://aspire/owncloud">http://aspire/owncloud</a>.
Network access is disabled."
05-14 08:30:25:306 3360 OCC::FolderMan::slotAccountStateChanged: Account "pstehlik@aspire" disconnected or paused, terminating or descheduling sync folders
```

This network check repeats roughly each 30 seconds and always fails the same way. Yet the network connection works -  I can, for example, use the "Open ownCloud in browser" menu entry of owncloud icon in the tray and connect to owncloud server properly (in the browser).
```
05-14 08:30:57:305 3360 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
05-14 08:30:57:306 3360 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "http://aspire/owncloud" + "status.php" "OCC::ConnectionValidator"
05-14 08:30:57:306 3360 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Network access is disabled." QVariant(Invalid)
05-14 08:30:57:306 3360 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply*) 99 "Network access is disabled."
05-14 08:30:57:306 3360 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Timeout" -> "Status not found"
05-14 08:30:57:306 3360 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href="http://aspire/owncloud">http://aspire/owncloud</a>.
Network access is disabled."
05-14 08:30:57:308 3360 OCC::FolderMan::slotAccountStateChanged: Account "pstehlik@aspire" disconnected or paused, terminating or descheduling sync folders
05-14 08:30:57:308 3360 unknown: QIODevice::read (QDisabledNetworkReply): device not open
05-14 08:30:57:308 3360 OCC::CheckServerJob::finished: error: status.php replied  0 ""
```

**Comment by dragotin** [comment] 2016-05-14 08:49
Can you check in the general option tab which Qt Version your client uses? The reason for that might again be that it is built against a buggy version of Qt5 :-/ @jnweiger we need to revert back to Qt4 - @danimo FYI

**Comment by joysfera** [comment] 2016-05-14 08:53
@dragotin I have since installed a nightly package for 16.04 (previously I've been using nightlies for 15.10 as the 16.04 nightlies didn't install). The 16.04 is "Built from Git revision 7b0231 on May 12 2016, 01:38:35 using Qt 5.5.1, OpenSSL 1.0.2g-fips 1 Mar 2016" and exhibits the same issue with "No connection to ownCloud" as described above.

**Comment by joysfera** [comment] 2016-05-14 09:34
And now I'm testing the stable build of 2.2.0 for xUbuntu 16.04 from your repositories - it's "Verze 2.2.0%nil (build 1605) Git revizi 49a678 na May 13 2016, 09:02:16 s použitím Qt 5.5.1, OpenSSL 1.0.2g-fips 1 Mar 2016" (so basically the same Qt) but it seems to work OK (i.e. the client is online after waking up computer from suspend).

**Comment by ovidiub13** [comment] 2016-05-14 10:37
I'm running on Kubuntu 16.04 and I have the owncloud client Version 2.2.0%nil (build 1605).
I also have this issue.

Yesterday I got some updates, since then the DPI for the owncloud client UI is messed up. All the elements of the interface are HUGE.

Built from Git revision 49a678 on May 12 2016, 13:19:43 using Qt 5.4.2, OpenSSL 1.0.2d 9 Jul 2015

**Comment by ovidiub13** [comment] 2016-05-14 10:47
Just updated. Same issues:

Version 2.2.0%nil (build 1605).
Built from Git revision 49a678 on May 13 2016, 09:02:16 using Qt 5.5.1, OpenSSL 1.0.2g-fips 1 Mar 2016

**Comment by RealRancor** [comment] 2016-05-14 16:22
Hi,

> Yesterday I got some updates, since then the DPI for the owncloud client UI is messed up. All the elements of the interface are HUGE.

it should be avoided to mix several issues within one bugreport. For this specific issue a bugreport exists hier: https://github.com/owncloud/client/issues/4833

Furthermore its advised to use the "thumbs up" emoticon at the first post of this issue to show that you're also affected by this issue. This avoids having the issue filled with "i have the same issue" comments not providing additional infos about the issue.

**Comment by joysfera** [comment] 2016-05-14 18:35
Please note that 9 hours ago I reported above that the stable build works OK. That was wrong (and I have just edited the entry) - apparently if the computer is suspended for a few minutes only then it manages to reconnect (like if the TCP connection survived or something) but if it sleeps longer then after waking up it's not connected. So beware when trying to reproduce this - make sure the computer is suspended for say 30 minutes at least.

**Comment by stonerl** [comment] 2016-05-15 07:12
I don't know whether the issue I have has the same cause, but I'm facing the same problem.

The only difference is that I put my server in maintenance mode/shutdown my server for about 2 hours. The client did never reconnect after the server was up again and I had to restart the client to connect to the server again.

Client-Version: 2.2.0
OS: OSX 10.11.5

Server: Ubuntu 14.04
oC-Version: 9.0.2 & 8.2.5

**Comment by joysfera** [comment] 2016-05-15 18:32
I _think_ that version 2.2.0nightly2016510 (build 1599) is OK. There's no information about the Qt library. If it's indeed working OK (will continue testing for a few days to be 100% sure) then the issue appeared in nightlies made after May 10 and before May 13.

**Comment by joysfera** [comment] 2016-05-17 09:24
I _believe_ that version 2.2.0nightly2016512 (build1603) **with Qt 5.4.2** (from revision 7b0231) **is OK**. So it indeed points to the difference between Qt 5.4.x and Qt 5.5.x.
Please note that three days ago I reported above that 2.2.0nightly2016512 = the same version built from the same git revision but linked **with Qt 5.5.1 does NOT work** (=does not reconnect). So do not bother looking for changes in ownCloud code, it might indeed be just a Qt issue.

**Comment by blackandcold** [comment] 2016-05-17 09:59
I can confirm that Bug. 

OC Client 2.1.1+dfsg-1ubuntu1.1

Package: qt5-default
Version: 5.5.1+dfsg-16ubuntu7

KUbuntu 16.04

Closing and opening the client - then it syncs again.

**Comment by matthiasmengel** [comment] 2016-05-19 21:15
+1

**Comment by f0rdprefect** [comment] 2016-05-20 06:06
Actually logout and login is sufficient. Have this bug for quite some time on manjaro (aur)

**Comment by stonerl** [comment] 2016-05-20 06:10
I just digged through the existing open bug reports. And  I think those two cover the same issue:
#3888 #4051

**Comment by guruz** [comment] 2016-05-20 07:42
Thanks, closing as duplicate of https://github.com/owncloud/client/issues/4720

$SOMEONE needs to get Ubuntu to update their Qt packages to check if there is a need to add any of the patches listed in https://github.com/owncloud/client/tree/2.2/admin/qt/patches

**Closed by guruz** 2016-05-20 07:42 UTC
Labels: bug, sev3-medium
