### ISSUE TITLE
[macOS] Emojis in file name fatally interrupts complete sync

### ISSUE THREAD

**Issue by strugee** [owncloud/client#5231] opened 2016-10-08 02:58 UTC
### Steps to reproduce
1. Create a file with some invalid characters. I believe `something🎲.txt` will trigger the problem, although I'm not sure.
2. Wait until the sync client UI shows the "please rename this file with invalid characters" error
3. Make some other changes
### Expected behaviour

Sync should pick up the changes made in step 3
### Actual behaviour

Sync stops completely and refuses to continue uploading and downloading
### Server configuration

Operating system: Debian 8

Web server: Apache 2.4

Database: MySQL

PHP version: PHP 5.6.24-0+deb8u1

ownCloud version: 9.0.4

Storage backend (external storage): local filesystem
### Client configuration

Client version: 2.2.3 (will test with the latest ASAP)

Operating system: Mac OS X

OS language: English

Installation path of client: `/Applications/ownCloud.app`

I can share my logs if necessary, but I'd rather not as it seems like this should be reproducible/solvable without them.

**Comment by guruz** [comment] 2016-10-09 17:34
At the moment this is by design.
We're thinking to make those kind of situations less fatal, but nothing is decided yet.

**Comment by jnweiger** [comment] 2016-10-20 14:42
If my copy/paste serves my right, the UTF-8 code of that glyph is a 4-byte code "f0 9f 8e b2"
This cannot work in any mariadb database, unless 
a) local admin dares to experiment with CHARACTER SET utf8mb4  
or 
b) we do a bold step and start storing filenames as binary blobs without any enforced semantics.

**Comment by ckamm** [comment] 2016-10-28 11:50
This happens because the client considers the "400 Bad Request" that it gets from the server a fatal error which should abort the sync.

**Comment by strugee** [comment] 2016-10-28 23:59
@ckamm I can't reproduce. Creating a new file _does_ trigger a new sync, but it gets interrupted by the bad filename before uploading the new file.

**Comment by SamuAlfageme** [comment] 2017-03-16 13:49
This should be fixed after ownCloud v10.0 make its release \o/

**Comment by guruz** [comment] 2017-04-19 18:54
It's not fixed by server only unfortunately, there's also an issue with UTF-8-MAC and iconv..
https://github.com/owncloud/client/issues/5661#issuecomment-295299024

**Comment by guruz** [comment] 2017-04-19 19:17
Let's track this in https://github.com/owncloud/client/issues/5661

**Closed by guruz** 2017-04-19 19:17 UTC
Labels: Design & UX, Server Involved
