### ISSUE TITLE
cannot access tray icon, when there is no tray in e.g. gnome

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6607] opened 2018-06-21 15:58 UTC
installed 2.4.2 daily build as of 20180621 on openSUSE Leap 42.2 with Gnome 3.20.2 Desktop.

![grafik](https://user-images.githubusercontent.com/1108546/41730904-484fe49c-757d-11e8-9ebe-84e3b05b92fc.png)

This desktop has no tray (at least I cannot find one). How do we access the settings page of owncloud there?

**Comment by guruz** [comment] 2018-06-22 11:53
@jnweiger please set milestone when creating issue if it looks important :) Do you remember what was the state before @ckamm 's tray patches and your changed on-top-tray-patches? or I guess that's unrelated?

**Comment by guruz** [comment] 2018-06-22 11:54
Is there a taskbar or something like that in Gnome? Does it show up there?

**Comment by ckamm** [comment] 2018-06-25 14:02
I'm pretty sure this is not a regression. If the desktop doesn't show tray icons there's little the client can do. I think executing `owncloud` a second time will bring the settings dialog to the front?

Users might need to install an extension (like https://github.com/ubuntu/gnome-shell-extension-appindicator but I don't know whether that's a current or up to date one) to show AppIndicators and KStatusNotifierItems.

**Comment by ckamm** [comment] 2018-06-25 14:34
I'm removing this from 2.4.2 since anything that actually circumvents the tray would be too big for a patch release anyway. I'm not convinced it's sensible to do anything about this in the client.

**Comment by jnweiger** [comment] 2018-06-26 10:48
It is not a regression, afaik. Gnome 3 wants to educate the world that a task bar is bad. Ubuntu's response was to add a task bar back, so that the world does not fall apart. SuSE does not seem to offer that workaround. SuSE-only -> thus maybe not so critical....

**Comment by guruz** [comment] 2018-06-26 12:12
@dragotin can you help here?

**Comment by jnweiger** [comment] 2018-06-27 21:08
The mentioned packages are `gnome-tweaks gnome-shell-extension-appindicator` but leap15.0 does not seem to offer these. The code seems to be maintained at https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by dragotin** [comment] 2018-07-02 07:18
@jnweiger what do I know about GNOME?

But the great @vuntz advised me that this extensions are installed "through the internet" from inside GNOME somehow. (see explain on how to do here; https://itsfoss.com/gnome-shell-extensions/ )

So I guess depending on gnome-tweeks should be enough (the package should exist) and from there on, the user should be able to install the extension via webbrowser.

**Comment by vuntz** [comment] 2018-07-03 07:43
For full background, see https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

Note that it does point to https://gitlab.gnome.org/World/libcloudproviders which "allows cloud storage sync clients to expose their services" (sounds like what you need here).

In the meantime, this extension is the one that is desired: https://extensions.gnome.org/extension/495/topicons/

Any proper distribution will have the extension mechanism work out of the box, with the right plugins for the browsers.

**Comment by guruz** [comment] 2018-07-23 14:22
@ckamm @jnweiger @dragotin What do we do here for 2.5? The libcloudproviders sounds more like 2.6.

**Comment by michaelstingl** [comment] 2018-07-23 15:17
libcloudproviders sounds like a nice project for future releases (low prio)

**Comment by dragotin** [comment] 2018-07-23 15:31
I had a look to it over Hackweek but did not get far.

**Comment by jnweiger** [comment] 2018-11-06 14:04
fedora-28 also shows no tray icon. Default desktop is gnome 3.2 with evolution.

`yum install gnome-tweaks`
is not sufficent to make the icon visible.

Package gnome-shell-extension-appindicator does not exist on fedora 28.

**Comment by ckamm** [comment] 2019-06-05 12:30
The hope here is that the libcloudproviders support added for #7209 would allow the oC settings to be opened from nautilus, by right-clicking the sync folder in the locations sidebar. It'd be interesting to see that tested once #7210 is merged!

**Comment by ckamm** [comment] 2019-06-14 13:22
#7210 is merged, testing still needs builds that include the new dependency. Continues to be tracked by #7209

**Comment by jnweiger** [comment] 2019-07-24 16:36
For the records: gnome 3.32 as seen in Ubuntu 19.04 shows a nice owncloud icon in the top bar.
![image](https://user-images.githubusercontent.com/1108546/61811561-fd763300-ae41-11e9-994c-af28780be62c.png)

**Comment by skewty** [comment] 2019-07-24 20:07
Ubuntu 19.04 uses a customized gnome-shell which brings back some depricated features and additionally tries to make gnome-shell look and act more like Unity did.

+Scott

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by HanaGemela** [comment] 2019-12-02 16:36
Closing this issue as the progress will be tracked in https://github.com/owncloud/client/issues/7547

**Closed by HanaGemela** 2019-12-02 16:36 UTC
Labels: Enhancement, ReadyToTest, Upstream issue, bug
