### ISSUE TITLE
linux client (appimage) sync in pause

### ISSUE THREAD

**Issue by mgatwwgmx** [owncloud/client#11455] opened 2024-01-01 21:14 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

After 1-3 days sync is paused and never comes back to normal.
Deleting account and reconnecting works for 1-3 days - after that sync is paused.
Problem started some weeks ago.
Log says: ([ warning gui.account.state ]: Failed to load QNetworkInformation)

windows clients work as expected

### Expected behavior

Expected to sync again

### Steps to reproduce the issue

1. start owncloud appimage
2. waiting - client pauses sync

### Logs

```
ownCloud 5.2.0.12726 f6cca1 Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023 Using virtual files plugin: suffix OS: linuxmint-6.2.0-39-generic QPA: xcb ownCloud
24-01-01 21:46:06:428 [ info gui.main ]:	################## "ownCloud" locale: "de_AT" version: "ownCloud 5.2.0.12726 f6cca1 Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023 Using virtual files plugin: suffix OS: linuxmint-6.2.0-39-generic QPA: xcb"
24-01-01 21:46:06:428 [ info gui.main ]:	Arguments: QList("/tmp/.mount_ownCloiZc4pD/AppRun.wrapped")
24-01-01 21:46:06:430 [ debug default ]	[ unknown ]:	m_crashReporterChar:  /tmp/.mount_ownCloiZc4pD/usr/bin/owncloud_crash_reporter
24-01-01 21:46:06:436 [ debug sync.credentials.http ]	[ OCC::HttpCredentials::fetchUser ]:	user not set, populating from settings
24-01-01 21:46:06:439 [ debug sync.account ]	[ OCC::Account::setCredentials ]:	Cache location for account OCC::Account("username@domain.com") set to "/home/user/.cache/ownCloud/accounts/2cebc-b638-41c8-9c4c70410/network/"
24-01-01 21:46:06:440 [ info gui.account.manager ]:	Restored:  0  unknown certs.
24-01-01 21:46:06:449 [ warning gui.account.state ]:	Failed to load QNetworkInformation
24-01-01 21:46:06:449 [ info gui.folder.manager ]:	Setup folders from settings file
24-01-01 21:46:06:449 [ info gui.folder.manager ]:	void OCC::FolderMan::setSyncEnabled(bool) true

```
https://gist.github.com/mgatwwgmx/8fbb3d338dabcda91c3eb209e7e4dde7

### Client version number

```
ownCloud 5.2.0.12726 [f6cca1](https://github.com/owncloud/client/commit/f6cca1968d4fda84c01bd239b46371d7b0131278)
Qt Bibliotheken 6.4.3, OpenSSL 3.1.2 1 Aug 2023
verwenden das Virtual Files plugin: suffix
OS: linuxmint-6.2.0-39-generic
QPA: xcb
```
ALSO TRIED:
```
ownCloud 5.1.2.12600 [9a0beb](https://github.com/owncloud/client/commit/9a0bebd8dc0bfd4099940e982eb6d84f2c08a904)
Qt Bibliotheken 6.4.3, OpenSSL 3.1.2 1 Aug 2023
verwenden das Virtual Files plugin: suffix
OS: linuxmint-6.2.0-39-generic
QPA: xcb
```

### Desktop environment (Linux only)

```
Kernel: 6.2.0-39-generic x86_64
bits: 64
compiler: N/A
Desktop: Cinnamon 5.8.4
tk: GTK 3.24.33
wm: muffin
dm: LightDM
Distro: Linux Mint 21.2 Victoria
base: Ubuntu 22.04 jammy
```

### Client package version and origin (Linux only)

https://owncloud.com/desktop-app/

**Comment by marc-IG** [comment] 2024-01-02 07:45
Hi everybody, (and happy new year !)
I have the same issue with the same version of the appimage (5.2.0.12726 f6cca).
My system is linux mint 21.
Many people seems to have the same trouble : https://central.owncloud.org/t/sync-problem-recurring/46126/6.
If you need extra information for debug, I could send information about logs and behaviors.
Lots of love <3
Marc

**Comment by TheOneRing** [comment] 2024-01-02 08:52
Is it really paused or did the client lose its only sycn connection?
Are there any folders displayed like here?
![image](https://github.com/owncloud/client/assets/200626/04aa154a-eae0-4a6c-b2a9-7e556ee1046b)

**Comment by mgatwwgmx** [comment] 2024-01-02 10:29
Yes it is the same issue. Sorry, I really checked for similar issues, but the title "sync folder lost from settings" (https://github.com/owncloud/client/issues/11411) did not seem appropriate.

The proposed workaround in this post also did the trick:
Copied the lost lines (see below) from owncloud.cfg.backup_2023XXXXX into the current config owncloud.cfg:
(Linux: $HOME/.config/ownCloud/owncloud.cfg)

0\Folders\8f02e9dd-3ad931c080bf\davUrl=@Variant(\0\0\0\x11\0\0\0Xhttps://domain.com/remote.php/dav/files/4B7BA3-40/)
0\Folders\8f02e9dd-3ad931c080bf\deployed=false
0\Folders\8f02e9dd-3ad931c080bf\displayString=ownCloud
0\Folders\8f02e9dd-3ad931c080bf\ignoreHiddenFiles=true
0\Folders\8f02e9dd-3ad931c080bf\journalPath=.sync_journal.db
0\Folders\8f02e9dd-3ad931c080bf\localPath=/home/username/ownCloud/
0\Folders\8f02e9dd-3ad931c080bf\paused=false
0\Folders\8f02e9dd-3ad931c080bf\priority=0
0\Folders\8f02e9dd-3ad931c080bf\targetPath=/
0\Folders\8f02e9dd-3ad931c080bf\version=5
0\Folders\8f02e9dd-3ad931c080bf\virtualFilesMode=off

**Comment by TheOneRing** [comment] 2024-01-02 11:00
Duplicate of: https://github.com/owncloud/client/issues/11411

**Closed by TheOneRing** 2024-01-02 11:00 UTC
Labels: bug
