### ISSUE TITLE
Client doesn't recover from maintenance mode

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11447] opened 2023-12-19 15:56 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When oC10 server ends maintenance mode, desktop client doesn't recover. Stays "Connecting"

### Expected behavior

Client should continue sync operation when server becomes available again.

### Steps to reproduce the issue

1. `occ maintenance:mode --on`
2. `occ maintenance:mode --off`

### Screenshots

![CleanShot 2023-12-19 at 16 35 39](https://github.com/owncloud/client/assets/214010/ad648ab1-9144-49ce-beab-fdc1dae97e0c) | ![CleanShot 2023-12-19 at 16 37 35](https://github.com/owncloud/client/assets/214010/1169d597-3fbc-4a3a-b275-264d062d2bc5)
-- | --
`occ maintenance:mode --on` ✅  | `occ maintenance:mode --off` ⚠️ 

### Logs

- [`testpilotcloud.log`](https://github.com/owncloud/client/files/13717672/testpilotcloud.log)

### Client version number

```
testpilotcloud 6.0.0.12868-alpha.1 7aea4b
Libraries Qt 6.6.0, OpenSSL 3.1.4 24 Oct 2023
Using virtual files plugin: suffix
OS: macos-23.2.0 (build arch: arm64, CPU arch: arm64)
QPA: cocoa
```

### Server information

```
curl -s "http://10.42.17.145:18080/status.php" | jq           
{
  "installed": true,
  "maintenance": true,
  "needsDbUpgrade": false,
  "version": "10.13.4.1",
  "versionstring": "10.13.4",
  "edition": "Community",
  "productname": "ownCloud",
  "product": "ownCloud"
}
```

### Additional context

Similar issue:
- https://github.com/owncloud/client/issues/11274

**Comment by cdamken** [comment] 2023-12-28 14:41
Actually, not so reliable :D , how often do we do maintenance mode on and off?

But this is a good begining

**Comment by TheOneRing** [comment] 2024-01-02 10:46
Duplicate off: https://github.com/owncloud/client/issues/11274

**Closed by TheOneRing** 2024-01-02 10:46 UTC
Labels: bug, p2-high

**Comment by michaelstingl** [comment] 2024-01-03 08:54
You can test-drive the fix with the latest 5.x dailies:
- https://download.owncloud.com/desktop/ownCloud/daily/5.2/?sort=time&order=desc
- https://download.owncloud.com/desktop/testpilotcloud/daily/5.2/?sort=time&order=desc

Final 5.2.1 planned the next few days…
