### ISSUE TITLE
wincfapi: resuming sync after an network error ignores some files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7145] opened 2019-04-12 15:27 UTC
## tested ownCloud-2.6.0.11775.11588-daily20190411.GPO.msi with vfs enabled on win10

![grafik](https://user-images.githubusercontent.com/1108546/56047254-50b9ef00-5d45-11e9-914e-ee1acd18a524.png)

ownCloudManual.pdf (without a whitespace) had a sync error. The file was virtual, network was disconected, then user tried to acces the file. That produced a sync error. OK.

After network got connected again, the file is flagged ignored in the owncloud client, and the status in explorer shows a state of being synced. 

Choosing sync now in the client, does not start syncing. it hangs "Waiting".
Disconnect the server and reconnect, also hangs "Waiting"

![grafik](https://user-images.githubusercontent.com/1108546/56048623-303f6400-5d48-11e9-86be-078e384c2531.png)

This screenshot was taken after double clicking on ood.pdf while the client is hanging. That is why we see an additional "0%" download popup. This popup eventually vanishes and a "semaphore timeout error" appears.

Fehler 080070079: Das Zeitlimit für die Semaphore wurde erreicht.

**Comment by jnweiger** [comment] 2019-04-12 16:11
[oc260_wincfapi_logs.zip](https://github.com/owncloud/client/files/3074136/oc260_wincfapi_logs.zip)
logfiles obtained after a kill and restart. Maybe unrelated....

**Comment by ckamm** [comment] 2019-04-15 11:05
> ownCloudManual.pdf (without a whitespace) had a sync error. The file was virtual, network was disconected, then user tried to acces the file. That produced a sync error. OK.

@jnweiger What kind of sync error did it have initially? (error on download or upload?) Or is the description that follows the explanation of how the sync error happened?

**Comment by jnweiger** [comment] 2019-04-15 12:05
with sync error I meant, what is explained right there: Disconnected network and user tries to access.

**Comment by ckamm** [comment] 2019-04-15 15:02
I've been trying to reproduce by trying to open a dehydrated txt file, but haven't yet been successful:
- If I sneakily disable my server, I'll get the windows hydration error dialog. Clicking cancel seems to abort the operation without anything showing up in the client. Ignore too.
- If the network is down and windows already noticed, it tells me the operation is not possible without internet and whether I want to cancel or hydrate later. That works alright. 
- If I'm quick and disconnect just before double-clicking the file, it takes a while until the failure dialog comes up, but behavior turns out alright in the end.

**Comment by ckamm** [comment] 2019-04-25 13:48
@jnweiger Can you reproduce the problem? So far I haven't been able to see it live and don't yet know how to approach the problem.

**Comment by TheOneRing** [comment] 2021-03-17 13:17
Closing as the issue was in needs info for more than a year

**Closed by TheOneRing** 2021-03-17 13:17 UTC
Labels: Needs info, bug, feature:vfs
