### ISSUE TITLE
Client icon on macOS Big Sur top menu bar

### ISSUE THREAD

**Issue by frankaellen** [owncloud/client#8378] opened 2021-01-19 13:55 UTC
Hey folks, 

I just updated my mac to Big Sur and couldn't help noticing the icon of the ownCloud app in the top menu bar is bigger than other icons. It would be nice if it would have a similar top & bottom padding/margin as the rest of the icons. (See screenshot)

ownCloud for MacOS Version 2.7.4 (build 2934)
macOS Big Sur 11.1

<img width="482" alt="Screenshot 2021-01-19 at 14 53 12" src="https://user-images.githubusercontent.com/4892549/105043681-1a56eb00-5a66-11eb-904a-635257ead9a2.png">

Thank you very much in advance!

All the best,
Franka

**Comment by TheOneRing** [comment] 2021-01-19 13:59
Thx for reporting.
Duplicate of: https://github.com/owncloud/client/issues/8149

**Closed by TheOneRing** 2021-01-19 13:59 UTC
Labels: Design & UX, Enhancement
