### ISSUE TITLE
[QA] `Scenario: sharing a folder by public link with "Uploader" role and check if file can be downloaded` failed in CI

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9854] opened 2022-07-04 11:20 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The scenario `sharing a folder by public link with "Uploader" role and check if file can be downloaded` from `tst_sharing` suite is failing in CI on step `When the user creates a new public link for folder "simple-folder" using the client-UI with these details:`

```
Scenario: sharing a folder by public link with "Uploader" role and check if file can be downloaded
        Given user "Alice" has created folder "simple-folder" on the server
        And user "Alice" has created file "simple-folder/lorem.txt" on the server
        And user "Alice" has set up a client with default settings
        When the user creates a new public link for folder "simple-folder" using the client-UI with these details:
            | role | Contributor |
        Then user "Alice" on the server should have a share with these details:
            | field       | value          |
            | share_type  | public_link    |
            | uid_owner   | Alice          |
            | permissions | create         |
            | path        | /simple-folder |
            | name        | Public link    |
        And the public should not be able to download the file "lorem.txt" from the last created public link by "Alice" on the server
```

### Screenshots

AUT
![Screenshot from 2022-07-04 17-00-46](https://user-images.githubusercontent.com/66173400/177143934-f7cf817b-e096-401d-85dd-733ce5a4e1b3.png)

The error message in GUI log
![Screenshot from 2022-07-04 17-02-50](https://user-images.githubusercontent.com/66173400/177144220-e2f683e6-f237-4f0a-b10f-8012fdb9844f.png)

### Log
The issue is referenced from https://github.com/owncloud/client/pull/9853#issuecomment-1173673817
>Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12319/6/1
>
>:boom: The GUI tests failed.
>
>GUI Logs: https://cache.owncloud.com/public/owncloud/client/12319/guiReportUpload/index.html
>
><details>
>
>Server Logs: https://cache.owncloud.com/public/owncloud/client/12319/guiReportUpload/serverlog.log
>
>Screenshots:
>- [change_collaborator_permissions_of_a_file_&_folder.png](https://cache.owncloud.com/public/owncloud/client/12319/guiReportUpload/screenshots/change_collaborator_permissions_of_a_file_&_folder.png)
>- [sharing_a_folder_by_public_link_with_"Uploader"_role_and_check_if_file_can_be_downloaded.png](https://cache.owncloud.com/public/owncloud/client/12319/guiReportUpload/screenshots/sharing_a_folder_by_public_link_with_"Uploader"_role_and_check_if_file_can_be_downloaded.png)
>
></details>
>
>
>

**Comment by saw-jan** [comment] 2022-07-21 07:05
This test seems to be stable by now. Couldn't reproduce locally and hasn't appeared lately.

**Comment by saw-jan** [comment] 2022-07-25 04:29
This test is runnig OK as for now, I will close this.

**Closed by saw-jan** 2022-07-25 04:29 UTC
Labels: QA:team
