### ISSUE TITLE
Time column too narrow with German locale

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#4721] opened 2016-04-23 13:07 UTC
### Expected behaviour
Using any locale, the default column sizes for time display should always be wide enough to be readable.

### Actual behaviour
The time column in the activity tab is too narrow at least when using the German locale on Windows, leading to a shortened display like "22.04....40:19" rather than "22.04.2016 23:40:19".
Note that in the following screenshot, you do NOT see a timestamp that is 44 minutes past midnight, so it's really confusing, and you have to resize the column everytime you start the client.

![sync_time](https://cloud.githubusercontent.com/assets/875883/14761561/df61d30e-0964-11e6-97e5-60baf8cbe787.png)

### Steps to reproduce
1. Run ownCloud Client with German locale
2. Check the sync protocol lists

### Client configuration
Client version: 2.1.1 (build 5837)

Operating system: Windows 7

OS language: German

**Comment by mcastroSG** [comment] 2016-05-04 16:16
Stil having the same issue on a fresh install:

Client OS: W7
Client Version: Version 2.2.0-nightly20160504 (build 6052)

**Comment by dragotin** [comment] 2016-05-09 11:16
moving to next milestone.

**Comment by ckamm** [comment] 2016-05-10 05:38
It could be that the problem is again the broken font metrics on Windows. If so, we can't make the column exactly the right width - it'll either be too wide or too narrow. We had a similar issue in #4562 (https://bugreports.qt.io/browse/QTBUG-15974, https://bugreports.qt.io/browse/QTBUG-51024) and there we changed the layout to avoid the problem.

I added code to adjust the size and it works on Linux. There seems to be no good workaround for Windows and it's not critical - so I'm tempted to close the issue. @dragotin?

**Comment by dragotin** [comment] 2016-05-10 07:46
do we remember the width if the users adjusted it once?

**Comment by sagamusix** [comment] 2016-05-10 11:40
No you don't, which is why this problem is so annoying. I have to re-adjust the column with every single time I restart the client. How about making the column just a few pixels wider by default on Windows? That way, the user would at least get a sensible display out of the box, even if it takes up more pixels than necessary - which IMHO is better than having an insensible display by default. The number of extra pixels could either be static or calculated from the locale's format string.
There might also be a way to make the column auto-sizing - I know that the native Windows lists have auto-sizing columns (starting with Vista, I believe?), so Qt might offer this feature as well.

**Comment by ckamm** [comment] 2016-05-12 08:25
@sagamusix I've added some extra width to that column and tested it with the German and English locale on Windows. I hope that improves the experience for you!

**Comment by sagamusix** [comment] 2016-05-12 10:39
Thanks :)

**Closed** 2016-05-19 10:19 UTC
Labels: Design & UX, ReadyToTest
