### ISSUE TITLE
[Windows 7] Client 1.7.1 - 1.8beta1 - Font: UI rendering bug!

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2845] opened 2015-02-16 10:58 UTC
The client under windows 7 is having an ugly rendering bug. In version 1.7.1 everything looks ok:
![](http://i.imgur.com/BCZ46R7.png)

But in version 1.8beta of the windowsclient the "." and "," are awful misplaced (specialy after "r"):

![](http://i.imgur.com/yJdfIt5.png)

**Comment by danimo** [comment] 2015-02-16 11:05
Probably related to the switch from Qt 5.3.2 to Qt 5.4.0. @jturcotte: any idea how to tell the difference? Did they switch the default renderer? Any way we can switch back to the old one?

**Comment by jturcotte** [comment] 2015-02-16 11:26
It looks like kerning doesn't work for some reason. You can see it between the 'V' and 'e' of Verbunden, too.

Humm I didn't hear of any significant change in text shaping, it might just be a plain bug that introduced with 5.4.0.

**Comment by jturcotte** [comment] 2015-02-16 11:31
Humm seems like they switched to harfbuzz-ng in 5.4, is that what you were talking about?

Discussion here: https://bugreports.qt.io/browse/QTBUG-41931

**Comment by jturcotte** [comment] 2015-02-16 11:33
According to them, it's not a bug it's a feature, since other Windows application don't apply kerning in that case. Sadly I don't think we can do much about it then.

**Comment by MegaV0lt** [comment] 2015-02-16 12:01
Well, back to C64-Times...
I do not know any other app that renders Text so ugly

**Comment by MegaV0lt** [comment] 2015-02-16 12:09
why is it nessesary to use that qt crap? I also use the latest Dropbox, whitch renders text ok, What are they donig different?

![uascidd](https://cloud.githubusercontent.com/assets/2804301/6211675/f1b4ee92-b5dc-11e4-97ea-d5e8fd033ba0.png)

**Comment by dragotin** [comment] 2015-02-16 12:19
@MegaV0lt they do maaaagiiiick of course. Thanks for the valuable input. Please come up with a pull request for a client not doing Qt any more if you are interested ;-)

**Comment by MegaV0lt** [comment] 2015-02-16 12:20
Don't understand what you mean. My english is basic only...

**Comment by danimo** [comment] 2015-02-16 12:21
First of all: Please calm your tone. We're not enemies here, Fonts are simply not my core competence. I've meanwhile spoken to some people and looked into the Qt code. We use Qt because it allows us to do cross platform programming and don't have to start from square one on every platform (fun fact: Drobox also recently switched to Qt for their UI, but they're probably still on an older version).

There is a bug in the newest Qt version, which we adopted for the 1.8 release. I think I have identified the bug. In case you care for the details:

1. The old Qt was using font hinting where it shouldn't, because Microsoft does not do what's called _kerning_ when the font sets a flag that it does not want to be kerned. Kerning is the process of e.g. moving the , slightly into the r, so you don't see a "false" white space. So kerning fonts that don't want to be kerned was disabled for Qt 5.4 to emulate the correct behavior.

2. Without kerning, `MS Shell Dlg` looks hideous. But Microsoft actually uses a font substitution table which tells apps to use "Microsoft Sans Serif" instead of "MS Shell Dialog" on practically all versions newer than Windows NT. This font still looks good without kerning in the case of an r followed by an inter-punctuation.

The bug is that Qt fails to evaluate the font substitution table in 5.4 and I have identified the relevant code. Will report back with more progress later.

**Comment by MegaV0lt** [comment] 2015-02-16 12:22
can we not use the patch mentioned:
```
--- a/src/gui/text/qtextengine.cpp
+++ b/src/gui/text/qtextengine.cpp
@@ -1244,6 +1244,9 @@ int QTextEngine::shapeTextWithHarfbuzzNG(const QScriptItem &si, const ushort *st
                 g.glyphs[i] |= (engineIdx << 24);
         }

+        if (kerningEnabled)
+            actualFontEngine->doKerning(&g, option.useDesignMetrics() ? QFontEngine::DesignMetrics : QFontEngine::ShaperFlags(0));
+
 #ifdef Q_OS_MAC
         if (actualFontEngine->fontDef.styleStrategy & QFont::ForceIntegerMetrics) {
             for (uint i = 0; i < num_glyphs; ++i)
```
or setting that variable: Setting "QT_HARFBUZZ" to "old" works around the issue, Qt 5.3.2 and 5.4 look the same.

**Comment by MegaV0lt** [comment] 2015-02-16 12:29
Sorry if i was to crude. I was reading that this should be a feature... Am i the only one who is misliking that kind of "textformating"?

Thanks @danimo for the long explanation. I think i understand. It is a bug and hopefully it will be fixed.
On the other side, can we not use a font that does not set that flag? Or use a font that works.

**Comment by danimo** [comment] 2015-02-16 12:33
@MegaV0lt that would be a last resort patch, but I prefer a fix that exactly emulates a native Windows app behavior, and I think it's doable without setting an extra font.

@MegaV0lt hardcoding fonts means that font substitution breaks, and the font substition table is important because in other language regions, the default fonts are not good enough (think e.g. Chinese). So this bug is actually worse than "just" kerning errors in those places, because the original font might not even contain certain code points ('characters').

**Comment by danimo** [comment] 2015-02-16 12:45
> Am i the only one who is misliking that kind of "textformating"?

No, but we're mostly dealing with "Oh my Explorer crashes" or "syncing stops randomly" type of issues, which you might agree are more severe, and more important to our user base. A pretty app that crashes tends to annoy a lot more users  :). Of course that shouldn't keep us from attending to detail where possible.

(btw: there is a new installer for windows out there which should keep explorer from crashing)

**Comment by MegaV0lt** [comment] 2015-02-16 13:07
Of course the priorities are to fix crashes first. As long the ui is not forgotten i do not have a problem. it is a beta and therefore it can have errors... I will propably stay at 1.7.1 for a few more days, becaus i also had many problems with crashing explorer, sidebar, freecommander, firefox... had to uninstall that msvcc thing and reapir an older one to get my system working again.

But i will try for sure, because i was long time waiting for the "desktop sharing" feature.

**Comment by MegaV0lt** [comment] 2015-02-19 11:22
Why not go back to the last "working as expected" version of qt? What is teh benefit of using the new one (except of destroyed rendering)

**Comment by danimo** [comment] 2015-02-19 11:40
Qt 5.4 has vital improvements in terms of network management. Going back is not an option.

**Comment by dragotin** [comment] 2015-02-25 14:42
Closing this as "wontfix" for now, as that will go away automatically with the next upstream version of Qt.

**Closed by dragotin** 2015-02-25 14:42 UTC
