### ISSUE TITLE
Known server issue with workaround: "ocs api error code 404" Can't use client to share folders and files after update (without password)

### ISSUE THREAD

**Issue by romeor** [owncloud/client#3760] opened 2015-09-05 00:23 UTC
Hi, 

before the update it was ok. Now I can't use OC Win client to share files and folders from Windows Explorer. When I choose a file or a dir to share, I get the error:
"ocs api error code 404"
thats it. Meanwhile files and folders are synchronized.

UPD:
Win7.
Tried on 2 pc-s, both have same issue. right after update I can't set the share via the client.

**Comment by tangix** [comment] 2015-09-06 06:49
Same error here :-/
Server version 8.1.1 (stable) running the official Debian packages. Nothing being logged in /var/log/owncloud.log or apache logs.

**Comment by tangix** [comment] 2015-09-06 07:10
I'm on Windows 8.1 64-bit Swedish. Most of the options in the share window (expiration, password etc) are disabled.
Checking with Fiddler I see the following requests going to `/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares/0?format=json`:

First when right-click on a folder that has been synced and select "Share with owncloud":
`{"ocs":{"meta":{"status":"failure","statuscode":404,"message":"share doesn't exist"},"data":[]}}`

and when I then click the "Share Link" ("Dela länk" in Swedish) button in the share window:
`{"ocs":{"meta":{"status":"failure","statuscode":404,"message":"wrong share ID, share doesn't exist."},"data":[]}}`

**Comment by romeor** [comment] 2015-09-06 19:26
"Glad" it is not only my problem. Looking at the logic tangix described we do have same issue. So it's client bug.

**Comment by rullzer** [comment] 2015-09-07 06:43
Mmmm requesting the share with id 0 is invalid indeed.
I'll look into this.

**Comment by dnichk** [comment] 2015-09-08 17:56
I had this too. I think the issue is that until the folder is synced to the server, it cannot find the folder when making the API request to share the folder.

Basically wait until the data is synced up (folder any ways) - then share. Worked for me.

**Comment by tangix** [comment] 2015-09-09 07:23
All my folders are synced, showing green dots. 
I can successfully manage folders that were already shared (like extending the shared period etc) without any problem.

**Comment by guruz** [comment] 2015-09-11 00:15
Have you tried the workaround described in https://github.com/owncloud/client/issues/3703#issuecomment-136152864 ?

**Comment by cluelessperson** [comment] 2015-09-11 13:46
I think this is the same bug as https://github.com/owncloud/client/issues/3762

It works if you set the password, otherwise you just get 404.

So it's shared across the Windows client AND Mac client.

Sounds like core to me.

**Comment by romeor** [comment] 2015-09-12 18:52
yes, toggling all the settings for api works fine. confirmed.

2015-09-11 16:46 GMT+03:00 Clueless <notifications@github.com>:

> I think this is the same bug as #3762
> <https://github.com/owncloud/client/issues/3762>
>
> It works if you set the password, otherwise you just get 404.
>
> So it's shared across the Windows client AND Mac client.
>
> Sounds like core to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/3760#issuecomment-139551399>.
>



-- 
Best regards,
Roman.

**Comment by guruz** [comment] 2015-09-13 21:37
Let's keep this issue here open then so people find the workaround https://github.com/owncloud/client/issues/3703#issuecomment-136152864 easier..

**Comment by rullzer** [comment] 2016-02-23 10:38
Lets close this. There have been new server versions that fix it.

**Closed by rullzer** 2016-02-23 10:38 UTC
Labels: Known Issue / Workaround, Server Involved
