### ISSUE TITLE
[QA] newline missing at the end of --version output

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8154] opened 2020-10-12 18:52 UTC
## Seen on Ubuntu 20.04

```
[testy:~] $ 
[testy:~] $ 
[testy:~] $ owncloud --version
ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
https://github.com/owncloud/client/commit/ec4341372eb026bb21e38a246e6698f6a684270c
Libraries Qt 5.12.9, OpenSSL 1.1.1  11 Sep 2018
Using virtual files plugin: off[testy:~] $ 
[testy:~] $ 
[testy:~] $ 
```

The last line of the output is `Using virtual files plugin: off`
The shell prompt should be in the next line.

**Comment by jnweiger** [comment] 2020-11-23 15:43
Seen again with 2.7.1:
```
[root@cd1386ccd51c /]# owncloudcmd --version
ownCloud 2.7.1 (build 2560) Nov 18 2020 08:46:25
https://github.com/owncloud/client/commit/afe5732722f5303889933f7baab0014f661d4d93
Libraries Qt 5.12.9, OpenSSL 1.1.1g FIPS  21 Apr 2020
Using virtual files plugin: off[root@cd1386ccd51c /]# 
[root@cd1386ccd51c /]# 
[root@cd1386ccd51c /]# 
[root@cd1386ccd51c /]# 
```

please try harder :-)

**Comment by fmoc** [comment] 2021-05-12 13:58
Cannot reproduce in latest master. @jnweiger could you please re-check whether the issue has been fixed in the meantime?

**Closed** 2022-02-18 12:29 UTC
Labels: good first issue
