### ISSUE TITLE
Duplicates created when moving data within ownCloud to read-only shared folder

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#8266] opened 2020-11-30 17:31 UTC
### (A) Move from outside ownCloud to read-only shared folder ✅ 

![ScreenFlow1](https://user-images.githubusercontent.com/214010/100639860-ff091280-3335-11eb-82a5-3ada590cf60d.gif)

### (B) Move within ownCloud to read-only shared folder 🤔 

![ScreenFlow2](https://user-images.githubusercontent.com/214010/100639961-219b2b80-3336-11eb-9903-7a3e73c75879.gif)

### Expected behaviour
Move folder + file within ownCloud to read-only shared folder should not create duplicate/restore at origin location (only if origin location would we read-only)

### Actual behaviour
Move folder + file within ownCloud to read-only shared folder creates duplicate/restore at origin location.

### Steps to reproduce
1. Create users "alice" + "bob"
2. "alice" shares folder "alice2bob" read-only with user "bob"
3. (A) Bob moves folder + file from outside ownCloud to read-only shared folder "alice2bob"
4. (B) Bob moves folder + file within ownCloud to read-only shared folder

### Server configuration
```
% docker run --rm -d \
  --name owncloud \
  -p 18080:8080 \
  -e ADMIN_USERNAME=admin \
  -e ADMIN_PASSWORD=admin \
  owncloud/server:latest
```

ownCloud version:
```
{
"installed": true,
"maintenance": false,
"needsDbUpgrade": false,
"version": "10.5.0.10",
"versionstring": "10.5.0",
"edition": "Community",
"productname": "ownCloud"
}
```

### Client configuration

Client version:
![CleanShot 2020-11-30 at 18 02 37](https://user-images.githubusercontent.com/214010/100640060-41325400-3336-11eb-9d4d-bccb9bac7baf.png)

Operating system:
![CleanShot 2020-11-30 at 18 03 35](https://user-images.githubusercontent.com/214010/100640167-61faa980-3336-11eb-8217-151bec48edd4.png)

**Comment by TheOneRing** [comment] 2020-12-01 12:08
Duplicate of: https://github.com/owncloud/client/issues/7413

**Closed by TheOneRing** 2020-12-01 12:08 UTC
