### ISSUE TITLE
SSL Problem in Win11 (ARM Tech Preview)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9562] opened 2022-04-05 10:59 UTC
![CleanShot 2022-04-05 at 12 57 13](https://user-images.githubusercontent.com/214010/161739387-486b9216-d0e5-462c-8eec-e7c9e397b0ac.png)

```
ownCloud 2.11.0.7178-daily20220405 Apr 4 2022 18:00:38
Libraries Qt 5.15.2, OpenSSL 1.1.1l 24 Aug 2021
Using virtual files plugin: wincfapi
windows-10.0.22000
```

```
04-05 12:41:11:659 [ info gui.application ]:    No configured folders yet, starting setup wizard
04-05 12:41:14:674 [ info gui.updater ]:        Checking for available update
04-05 12:41:14:674 [ info sync.accessmanager ]: 2 "" "https://updates.owncloud.com/client/?version=2.11.0.7178&platform=win32&oem=ownCloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=daily20220405&msi=true" has X-Request-ID "94786750-332d-4612-9ca4-9fdaf8309bc7"
04-05 12:41:14:674 [ debug sync.cookiejar ]     [ OCC::CookieJar::cookiesForUrl ]:      QUrl("https://updates.owncloud.com/client/?version=2.11.0.7178&platform=win32&oem=ownCloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=daily20220405&msi=true") requests: ()
04-05 12:41:14:923 [ warning gui.updater ]:     Failed to reach version check url:  "SSL handshake failed"
04-05 12:41:14:923 [ info gui.updater ]:        Retrying update check in 10 minutes
04-05 12:41:32:243 [ warning wizard.resolveurl ]:       "Failed to resolve the url https://demo.owncloud.org/, error: SSL handshake failed"
```

**Comment by michaelstingl** [comment] 2022-04-14 11:59
Works fine on macOS Monterey 12.3.1.

**Comment by fmoc** [comment] 2022-04-14 12:02
Same goes for the AppImages, tested on Ubuntu 20.04. Must be some certificate chain issue specific to Windows.

**Comment by fmoc** [comment] 2022-04-19 09:32
Cannot be reproduced in the latest Windows 11 evaluation VM (x64). It looks like a problem within the tech preview setup.

**Comment by TheOneRing** [comment] 2022-04-25 08:18
Not sure but we probably use the system cert store, which isn't up to date after the initial install of Windows.
Windows can update the certs on the fly, if the website is visited or through Windows updates.
Closing for now.

**Closed by TheOneRing** 2022-04-25 08:18 UTC
