### ISSUE TITLE
Do not save login password (feature request)

### ISSUE THREAD

**Issue by disy-mk** [owncloud/client#2631] opened 2014-12-19 14:47 UTC
For others a bug (c.f #1902), for me a feature that I would like to see.

Background: I would like to use an encrypted container, containing all my cloud files.

Two things to consider:
1. OC client does not commit (binary) diffs on changes, so on every change my whole container would be uploaded (around 600 gigs)
2. I also want my files to be accessible within OC's webinterface; so even IF oc client would commit diffs, I only would have a big container file accessible via webinterface

To circumvent the above issues I have a container, which I mount after system start. AFTER that I start the desktop client which then takes care of sync.

_BUT_: having an encrypted container makes no sense if instead of providing the client with the mounted container, but instead give it an empty directory and get asked, wether to delete all the oc files, or to resync everything.

Both options are _NOT_ acceptable fot me :-(

So having a checkmark in the client options to optinally NOT save the password would be great!

**Comment by ignacioinnovo** [comment] 2016-01-12 13:08
Dear ownCloud team,

Let me congratulate you all for the job done! OwnCloud is getting better release by release.

I´m now testing the 7 version and the last version of the sync client for Windows.

I´ve posted a message in the forum and RealRancor ask me to post it here. So, I find this and another thread for the same thing. The other one is this: https://github.com/owncloud/client/issues/2238

Let me explain my situation:

What I need is that the client asks for password in every reboot. In some previous versions there were a checkbox that specified if we wanted to store or not the pass. But as you have encrypt it now it stores it everytime. Except in the case where yo Exit the client. I´ve seen that the password is erased from the owncloud.cfg. But, if the computer restarts the password remain there.

What I want to do is to store the ownCloud contents in an encrypted volume (by TrueCrypt) and when the user restarts the PC she has to enter the password of the encrypted container and then the password for the owncloud client in order to synchronize. In that way I keep the data safe in each computer. In the owncloud server (my own server) the files stay unencrypted because I want to access them by web and is more easy if they are not contained in an encrypted volume. The security issu comes in the Windows clients where the files can be stored in a notebook or desktop PC.

I´m a C# developer, do you think I can help in any way? I saw that the client is developed in C++...

Thank you very much in advanced,
Ignacio.

**Comment by ignacioinnovo** [comment] 2017-02-28 16:23
Hi there!

Any update on this?

Thanks in advanced!

**Comment by valintinr** [comment] 2017-03-29 09:12
Hello,
I'm also interested in this feature. Would you be so kind to inform us when this will be implemetned.

**Comment by ImTheLe** [comment] 2017-06-26 23:39
Bumping the issue as this feature is still not implemented and is very important from a security viewpoint

**Comment by ignacioinnovo** [comment] 2017-06-27 14:16
As ImTheLe said, I think this is an important security feature. Thank you very much Nextcloud Team!

**Comment by ckamm** [comment] 2017-06-28 09:35
A manually-addable configuration switch for this should be straightforward to add, but it's currently not scheduled.

**Comment by guruz** [comment] 2017-07-03 12:58
How does this relate to https://github.com/owncloud/client/issues/2238 ?

**Comment by ImTheLe** [comment] 2017-07-03 13:07
Both issues are requesting the same feature - the ability to not save the password on login and thus require it with every start of the client.

**Comment by ignacioinnovo** [comment] 2017-07-03 13:11
Guruz, this is related to #2238 because if you ask for password at owncloud´s client start is because you haven´t saved it. The problem is that the only way the client ask for password is when you exit the client from systray with right click but not if you shutdown the OS without manually closing the client. Am I making myself clear?

**Comment by DeepDiver1975** [comment] 2024-10-21 12:12
I don't see this happening

**Closed by DeepDiver1975** 2024-10-21 12:12 UTC
Labels: Enhancement, good first issue
