### ISSUE TITLE
Sync error when you try to sync files with large name 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#1990] opened 2014-07-21 10:22 UTC
### Expected behavior
You can sync files with larges names 

### Actual behavior
You can't sync files with large names inside folder with large names

### Steps to reproduce
1. Create the folder "Longfolderfile" and inside it the folder GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyV

2. Inside it upload files with large names

 
### Server configuration
{"installed":"true","version":"7.0.0.3","versionstring":"7.0 beta 1","edition":""}

### Client configuration
Version 1.6.2rc1 

Operating system: Windows 7
### Logs
```
C:/Users/solidgear/Desktop/Serves/oc5local/Longfolderfile [file_id=]
07-21 11:19:09:157 _csync_detect_update: Checking for rename based on inode # 505880
07-21 11:19:09:158 _csync_detect_update: file: Longfolderfile, instruction: INSTRUCTION_NEW <<=
07-21 11:19:09:158 csync_walker: directory: C:/Users/solidgear/Desktop/Serves/oc5local/Longfolderfile/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX [file_id=]
07-21 11:19:09:159 _csync_detect_update: Checking for rename based on inode # 505881
07-21 11:19:09:159 _csync_detect_update: file: Longfolderfile/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX, instruction: INSTRUCTION_NEW <<=
07-21 11:19:09:160 csync_vio_local_stat: CreateFileW failed on C:/Users/solidgear/Desktop/Serves/oc5local/Longfolderfile/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX/.sbIvPFKIc33Rd1G3mFWTtGwAVK09YL9Co38a4JL8Q4KmZrcfhiA924yMyIKJy5z9Py4XWQssfYnAOMRmbn5J5bqB4BPen2j3JMTR.txt.~1da0
07-21 11:19:09:160 csync_vio_stat: Local stat failed, errno 3
07-21 11:19:09:160 csync_vio_local_stat: CreateFileW failed on C:/Users/solidgear/Desktop/Serves/oc5local/Longfolderfile/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX/.testtttttjdhfjdhjfhdhfdhfdhfjhjdhfjhdjshfjdhfjdhjfhjdhfjdhfjdhfjdhfjdhjfhdsjfhjdshfjhdsfjhdjfjdfjfhhfhfhfhfhfhhfhffhhf.txt.~3a9c
07-21 11:19:09:160 csync_vio_stat: Local stat failed, errno 3
07-21 11:19:09:161 csync_ftw: Uniq ID from Database: Longfolderfile/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX/Photo-2013-10-16-12-50-29_1166.JPG -> 53cccf7aca609
07-21 11:19:09:161 csync_walker: file: C:/Users/solidgear/Desktop/Serves/oc5local/Longfolderfile/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX/Photo-2013-10-16-12-50-29_1166.JPG [file_id=]
07-21 11:19:09:162 _csync_detect_update: Database entry found, compare: 1405926273 <-> 1405926273, etag: 53cccf7aca609 <-> 53cccf7aca609, inode: 505882 <-> 505882
07-21 11:19:09:162 _csync_detect_update: file: Longfolderfile/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX/Photo-2013-10-16-12-50-29_1166.JPG, instruction: INSTRUCTION_NONE <<=
07-21 11:19:09:162 csync_ftw:  <= Closing walk for C:/Users/solidgear/Desktop/Serves/oc5local/Longfolderfile/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX with read_from_db 0
07-21 11:19:09:162 csync_ftw:  <= Closing walk for C:/Users/solidgear/Desktop/Serves/oc5local/Longfolderfile with read_from_db 0
07-21 11:19:09:162 csync_ftw: Uniq ID from Database: Longfoldername -> 53cccf92c69e4
07-21 11:19:09:162 csync_walker: directory: C:/Users/solidgear/Desktop/Serves/oc5local/Longfoldername [file_id=]
07-21 11:19:09:163 _csync_detect_update: Database entry found, compare: 1405934105 <-> 1405931387, etag: 53cccf92c69e4 <-> 53cccf92c69e4, inode: 505884 <-> 505884
07-21 11:19:09:163 _csync_detect_update: file: Longfoldername, instruction: INSTRUCTION_EVAL <<=
07-21 11:19:09:163 csync_ftw: Uniq ID from Database: Longfoldername/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX -> 53cccf7b47c67
07-21 11:19:09:163 csync_walker: directory: C:/Users/solidgear/Desktop/Serves/oc5local/Longfoldername/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX [file_id=]
07-21 11:19:09:164 _csync_detect_update: Database entry found, compare: 1405934104 <-> 1405931387, etag: 53cccf7b47c67 <-> 53cccf7b47c67, inode: 505885 <-> 505885
07-21 11:19:09:164 _csync_detect_update: file: Longfoldername/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX, instruction: INSTRUCTION_EVAL <<=
07-21 11:19:09:164 csync_ftw:  <= Closing walk for C:/Users/solidgear/Desktop/Serves/oc5local/Longfoldername/GxSqAJVd5BrMaL0nAy2SQ1eUgQfw4aizBgD0xUfJnW7SQBRkQQWFpjz6boaDcBNMI8zSbcgJoHY9ogQcEtJjFvxhzv4KKyVSs4FX with read_from_db 0
07-21 11:19:09:164 csync_ftw: Uniq ID from Database: Longfoldername/Photo-2014-06-30-11-47-31_3669.JPG -> 53cccf7bb2b9f
07-21 11:19:09:165 csync_walker: file: C:/Users/solidgear/Desktop/Serves/oc5local/Longfoldername/Photo-2014-06-30-11-47-31_3669.JPG [file_id=]
07-21 11:19:09:165 _csync_detect_update: Database entry found, compare: 1405926210 <-> 1405926210, etag: 53cccf7bb2b9f <-> 53cccf7bb2b9f, inode: 505887 <-> 505887
07-21 11:19:09:165 _csync_detect_update: file: Longfoldername/Photo-2014-06-30-11-47-31_3669.JPG, instruction: INSTRUCTION_NONE <<=
07-21 11:19:09:165 csync_ftw:  <= Closing walk for C:/Users/solidgear/Desktop/Serves/oc5local/Longfoldername with read_from_db 0
07-21 11:19:09:165 csync_ftw: Uniq ID from Database: ownCloud-1.6.1.3267-setup.exe -> 53c66b742afda
07-21 11:19:09:165 csync_walker: file: C:/Users/solidgear/Desktop/Serves/oc5local/ownCloud-1.6.1.3267-setup.exe [file_id=]
07-21 11:19:09:166 _csync_detect_update: Database entry found, compare: 1405512564 <-> 1405512564, etag: 53c66b742afda <-> 53c66b742afda, inode: 505929 <-> 505929
07-21 11:19:09:166 _csync_detect_update: file: ownCloud-1.6.1.3267-setup.exe, instruction: INSTRUCTION_NONE <<=
07-21 11:19:09:166 csync_ftw: Uniq ID from Database: ownCloudUserManual.pdf -> 53c66a24b90a5
07-21 11:19:09:166 csync_walker: file: C:/Users/solidgear/Desktop/Serves/oc5local/ownCloudUserManual.pdf [file_id=]
07-21 11:19:09:167 _csync_detect_update: Database entry found, compare: 1405512228 <-> 1405512228, etag: 53c66a24b90a5 <-> 53c66a24b90a5, inode: 505930 <-> 505930
07-21 11:19:09:167 _csync_detect_update: file: ownCloudUserManual.pdf, instruction: INSTRUCTION_NONE <<=
07-21 11:19:09:167 csync_ftw: Uniq ID from Database: sbIvPFKIc33Rd1G3mFWTtGwAVK09YL9Co38a4JL8Q4KmZrcfhiA924yMyIKJy5z9Py4XWQssfYnAOMRmbn5J5bqB4BPen2j3JMTR.txt -> 53c7becbb3fcc
07-21 11:19:09:167 csync_walker: file: C:/Users/solidgear/Desktop/Serves/oc5local/sbIvPFKIc33Rd1G3mFWTtGwAVK09YL9Co38a4JL8Q4KmZrcfhiA924yMyIKJy5z9Py4XWQssfYnAOMRmbn5J5bqB4BPen2j3JMTR.txt [file_id=]
07-21 11:19:09:168 _csync_detect_update: Database entry found, compare: 1405599435 <-> 1405599435, etag: 53c7becbb3fcc <-> 53c7becbb3fcc, inode: 505931 <-> 505931
07-21 11:19:09:168 _csync_detect_update: file: sbIvPFKIc33Rd1G3mFWTtGwAVK09YL9Co38a4JL8Q4KmZrcfhiA924yMyIKJy5z9Py4XWQssfYnAOMRmbn5J5bqB4BPen2j3JMTR.txt, instruction: INSTRUCTION_NONE <<=
07-21 11:19:09:168 csync_ftw: Uniq ID from Database: Shared -> 53c7988469c5b
07-21 11:19:09:168 csync_walker: directory: C:/Users/solidgear/Desktop/Serves/oc5local/Shared [file_id=]
07-21 11:19:09:168 _csync_detect_update: Database entry found, compare: 1405934105 <-> 1405588699, etag: 53c7988469c5b <-> 53c7988469c5b, inode: 505888 <-> 505888
07-21 11:19:09:168 _csync_detect_update: file: Shared, instruction: INSTRUCTION_EVAL <<=
```

**Comment by ogoffart** [comment] 2015-03-23 13:13
Closed as duplicate of #60 0

**Closed by ogoffart** 2015-03-23 13:13 UTC
Labels: bug
