### ISSUE TITLE
deleting .lnk files X'ed out with an "acces denied"

### ISSUE THREAD

**Issue by GaBMaN777** [owncloud/client#7480] opened 2019-09-19 16:32 UTC
### Expected behaviour
renaming .lnk files to be shared
deleting .lnk files to be shared

### Actual behaviour
renaming .lnk files is shared
deleting .lnk files X'ed out with an "acces denied" on shared people account 

### Steps to reproduce
1. Connect ownCloud Desktop on the "sharing" account and on the "being shared" account
2. In Explorer, on the "sharing" folder, delete a .lnk file (or, in ownCloudX, on the "sharing" folder, delete a .lnk file)
3. In Exploer, on the "being shared" folder, the .lnk file will X'ed out
4. Delete the file or get rid of the "read only" attribute to get the new shared .lnk file

### Server configuration
ownCloud version: ownCloud 10.0.10 (production)

### Client configuration
Client version: version 2.5.4 (build 11415)

Operating system: Windows 10 Professionnel 64 bits (10.0, version 17763)

OS language: French

Installation path of client: "C:\Program Files (x86)\ownCloud\owncloud.exe"

### Logs

Client logfile: 

```09-19 12:15:29:300 [ info sync.csync.reconciler ]:	INSTRUCTION_REMOVE             client file: Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk
09-19 12:15:31:120 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 QVariant(QString, "Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk")
09-19 12:15:31:153 [ debug sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotAboutToPropagate ]:	Investigating "Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk" 0 2
09-19 12:15:31:908 [ info sync.propagator ]:	Starting INSTRUCTION_REMOVE propagation of "Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk" by OCC::PropagateLocalRemove(0xae2af28)
09-19 12:15:31:908 [ debug sync.propagator.localremove ]	[ OCC::PropagateLocalRemove::start ]:	"C:/Users/public/ownCloud/Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk"
09-19 12:15:31:908 [ debug sync.propagator ]	[ OCC::OwncloudPropagator::localFileNameClash ]:	CaseClashCheck for  "C:/Users/public/ownCloud/Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk"
09-19 12:15:31:910 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 QVariant(QString, "Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk")
09-19 12:15:31:911 [ warning sync.propagator ]:	Could not complete propagation of "Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk" by OCC::PropagateLocalRemove(0xae2af28) with status 2 and error: "Accès refusé."
09-19 12:15:31:914 [ debug sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotItemCompleted ]:	Item completed "Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk" 2 2
09-19 12:15:31:925 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::slotItemCompleted ]:	inserted error item "Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk"
09-19 12:15:48:071 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::startSyncPartialDiscovery ]:	partial discovery with paths:  ("Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk")
09-19 12:15:48:141 [ debug sync.csync.updater ]	[ csync_walker ]:	file: Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk [inode=35611 size=1981]
09-19 12:15:48:141 [ info sync.csync.updater ]:	file: Partage_techniciens/Patch_enteliWEB/Packages/Boite a outils techniques 413/InstallFiles/DBTransfer.lnk, instruction: INSTRUCTION_NONE <<=```

**Comment by GaBMaN777** [comment] 2019-09-19 16:46
Changelog:
version 2.5.4 (2019-03-19) > nothing about .lnk files after version 2.1.1 fixed the Bug https://github.com/owncloud/client/issues/4300
version 2.1.1 (release 2016-02-10) > Sync Engine: .lnk files
version 1.5.1 (release 2014-02-13 ) > Handle windows lnk files correctly (Bug #1307)

**Comment by ogoffart** [comment] 2019-10-15 12:25
I suppose the file was somehow marked Read-Only on your local file system. In this case we indeed can't remove the file.
(Although we could set the file as read-write before trying to remove it)

**Comment by GaBMaN777** [comment] 2019-10-15 14:03
I have both account connected to my owncloud desktop, the "Sharer" and the "Shared".
When I do an "ATTRIB" cmd in the "Sharer" folder, only the "A" attribute shows up.
When I do an "ATTRIB" cmd in the "Shared" folder, both "A and R" attribute show up as "Sharing is not allowed" for that account. Actually, all files are marked as "Read-Only" but somehow get deleted/replace by an owncloud sync except for .lnk files

**Comment by TheOneRing** [comment] 2023-08-24 15:10
Closing the issue, can't reproduce.
If the issue still occurs please reopen.

**Closed by TheOneRing** 2023-08-24 15:10 UTC
