### ISSUE TITLE
[1.6.4] MS word  file locking issue

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#2428] opened 2014-10-29 18:15 UTC
### Expected behavior
Open Same file in to different Windows/Mac (any combination) computer with Microsoft Word (any version). Modify the file in both computers... and both files should be uploaded with the 2 different modifications. e.g.: test1.doc test2.doc

### Actual behavior
Open Same file in to different Windows/Mac (any combination) computer with Microsoft Word (any version). Modify the file in both computers...  and both files are different in each computer with different names, then the file will be deleted from the server and 1st computer. In the second computer is only a conflict file.

### Steps to reproduce
1.- Create a file
2.- Sync both computers
3.- Open the file in both computers
4.- Modify the file in both computer 
5.- Save file in computer 1
6.- Wait a few second until it got synced.

Messages in computer 2:

First appears this messages:

![2files1](https://cloud.githubusercontent.com/assets/7264495/4831521/1c44572c-5f95-11e4-87a0-b64131603745.png)

A few seconds later after a second try:

![2files2](https://cloud.githubusercontent.com/assets/7264495/4831524/21d0c414-5f95-11e4-80c2-95b7f2715547.png)

Temporally will be the file blacklisted:

![2files3](https://cloud.githubusercontent.com/assets/7264495/4831533/32a40cce-5f95-11e4-973d-f5cb3e425385.png)

7.- Save file in computer 2

![2files6](https://cloud.githubusercontent.com/assets/7264495/4831559/647e5cc2-5f95-11e4-9859-a0d0a034bf76.png)

8.- Wait
9.- See file in folder

Computer 1:

![2files4](https://cloud.githubusercontent.com/assets/7264495/4831570/74fe0d4a-5f95-11e4-923e-014a2172cb5f.png)

Computer 2:

![2files5](https://cloud.githubusercontent.com/assets/7264495/4831578/7cb99b94-5f95-11e4-9cc3-b462d32f576f.png)

10.- Wait to sync again

Computer 1:

![2files8](https://cloud.githubusercontent.com/assets/7264495/4831588/a5ce0998-5f95-11e4-8c3f-2bf4c0afbe33.png)

Computer 2:

![2files6](https://cloud.githubusercontent.com/assets/7264495/4831593/ac698016-5f95-11e4-9b61-10fb8872d446.png)

11.- See the files in server

![2files7](https://cloud.githubusercontent.com/assets/7264495/4831597/b526e5ea-5f95-11e4-914e-a4d866e0e8f4.png)

12.- File in computer 1 is also deleted!
13.- File in computer 2 is kept but not synced!

### Server configuration
**Operating system**:
CentOS

**ownCloud version:** (see ownCloud admin page)
6.0.5
**Updated from an older ownCloud or fresh install:**
Updated from every previous versions

**Are you using encryption:** yes/no
No
### Client configuration
**Browser:**
Mirall 6.0.4
**Operating system:**
Windows/Mac Windows/Windows and Mac/Mac
(This test was Windows/Windows)

#### Browser logs
Computer 1:
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2428\2files1.log
Computer 2:
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2428\2files2.log

@dragotin @danimo 

00001953

**Comment by cdamken** [comment] 2015-01-08 18:44
@ckamm @lmaestro I've just tested the word-file delete issue: while using 1.7.1 on windows and 1.7.0 on Mac.
When I edit a file on the Mac, while begin open on windows as well
I get a sync error on the window machine: "cannot remove source file"
The sync client gives a big red cross and I see that I have on both computers a different word-file and after I pause-resume the sync client on windows, I get the same file as the Mac.

**Comment by ckamm** [comment] 2015-01-14 07:36
@cdamken Sounds like the bug from the original report (file gets deleted) is solved.

You're reporting that
* syncing fails on windows while the file is open in Word (I think there is an issue for this, will check)
* after you're done, the file is restored to the Mac's version (is there a conflict file?)

**Comment by ckamm** [comment] 2015-01-14 08:05
The 'sync fail' issue is related to #2070, though the other way around. In your report the sync client can't read the file while MSWord has it locked. The proposed fixes to the strength of the requested lock could also help with this problem.

**Comment by ckamm** [comment] 2015-01-16 08:23
@cdamken It's a long shot, but we made some progress on #2070. Could you check if the behavior changed with the latest nightlies? (http://download.owncloud.com/desktop/daily/ >= 20150116)

**Comment by dragotin** [comment] 2015-01-16 09:12
The original issue of loosing the file is fixed. The other problem with blacklisting is handled in another issue, hence closing this.

**Comment by cdamken** [comment] 2015-01-16 15:02
@dragotin https://github.com/owncloud/client/issues/2428#issuecomment-70226646 Which issue are you talking about? Please reference it to follow it up.

**Comment by cdamken** [comment] 2015-01-19 15:45
@dragotin I double checked, the original issue is not fixed: the file is not uploaded, and the blacklisted file is not synced (maybe if you provide the reference of that issue here) and that means information lost for some users.

**Comment by ckamm** [comment] 2015-01-22 08:18
@cdamken The problem with a file being deleted should be solved, as lucia confirmed.

The issue now seems to be something very close to #2070, where syncing doesn't work correctly for files opened in MS Office in various ways. We've recently tried to address that issue - have you tried to reproduce it with a recent nightly (>=20150116)?

Also, when the file on Windows is restored to the Mac's version, do you get a conflict file on Windows?

Finally, where did the blacklisting you and dragotin mentioned come in?

**Comment by cdamken** [comment] 2015-02-02 13:40
@ckamm  in this case some flies can not be deleted, probably related to https://github.com/owncloud/enterprise/issues/455

Additionaly, what happens with the conflict files? We need to inform the end-user somehow that he has to deal (rename, compare, delete or else) with them.

```
-08 23:06:13:938 0x796a180 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/user/syncfolder/testsync/.TESTdoc.docx.~299b" action: 1
01-08 23:06:13:946 0x78e19f8 folderwatcher.cpp:76 * Discarded as is hidden! "C:/Users/user/syncfolder/testsync/.TESTdoc.docx.~299b"
01-08 23:06:13:946 0x78e19f8 syncjournalfilerecord.cpp:80 Mirall::SyncJournalFileRecord::SyncJournalFileRecord(const Mirall::SyncFileItem&, const QString&) "C:/Users/user/syncfolder/testsync/testsync" Retrieved inode  276099 (previous item inode:  276099 )
01-08 23:06:13:947 0x78e19f8 syncjournaldb.cpp:515 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12);" -2337121347187170560 8 "testsync" 276099 0 "1413406159" "2" "543eddcfa6330" "19243406ocff17e49795" ""
01-08 23:06:13:947 0x78e19f8 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "~$ESTdoc.docx" 6 "File is listed on the ignore list."
01-08 23:06:13:950 0x78e19f8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\user\syncfolder\testsync\~$ESTdoc.docx"
01-08 23:06:14:061 0x78e19f8 propagator_qnam.cpp:696 void Mirall::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://SERVERNAME/files/remote.php/webdav/TESTdoc.docx" )  FINISHED WITH STATUS 0 ""
01-08 23:06:14:062 0x78e19f8 owncloudpropagator.cpp:388 CaseClashCheck for  "C:/Users/user/syncfolder/testsync/TESTdoc.docx"
01-08 23:06:14:065 0x78e19f8 owncloudpropagator.cpp:93 This error is not blacklisted  0
01-08 23:06:14:065 0x78e19f8 syncengine.cpp:778 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "TESTdoc.docx" 2 "Cannot remove source file"
01-08 23:06:14:067 0x78e19f8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\user\syncfolder\testsync\TESTdoc.docx"
01-08 23:06:14:062 0x796a180 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/user/syncfolder/testsync/.TESTdoc.docx.~299b" action: 3
01-08 23:06:14:064 0x796a180 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/user/syncfolder/testsync/TESTdoc_conflict-20150108-230422.docx" action: 1
01-08 23:06:14:071 0x78e19f8 folderwatcher.cpp:101 * Discarded by component ignore pattern  "TESTdoc_conflict-20150108-230422.docx"
01-08 23:06:14:065 0x796a180 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/user/syncfolder/testsync/TESTdoc_conflict-20150108-230422.docx" action: 3
01-08 23:06:14:065 0x796a180 folderwatcher_win.cpp:83 void Mirall::WatcherThread::watchChanges(size_t, bool*) Error converting file name to full length, keeping original name.
01-08 23:06:14:065 0x796a180 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/user/syncfolder/testsync/TESTdoc_conflict-20150108-230422.docx" action: 3
01-08 23:06:14:065 0x796a180 folderwatcher_win.cpp:83 void Mirall::WatcherThread::watchChanges(size_t, bool*) Error converting file name to full length, keeping original name.
01-08 23:06:14:065 0x796a180 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/user/syncfolder/testsync/TESTdoc_conflict-20150108-230422.docx" action: 3
01-08 23:06:14:065 0x796a180 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/user/syncfolder/testsync/TESTdoc_conflict-20150108-230422.docx" action: 2
01-08 23:06:14:074 0x78e19f8 syncjournaldb.cpp:68 void Mirall::SyncJournalDb::walCheckpoint() took 0 msec
01-08 23:06:14:074 0x78e19f8 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished." 
01-08 23:06:14:075 0x78e19f8 syncengine.cpp:824 CSync run took  624
01-08 23:06:14:081 0x78e19f8 folder.cpp:838 -> SyncEngine finished without problem.
01-08 23:06:14:082 0x78e19f8 folder.cpp:418 Processing result list and logging took  0  Milliseconds.
01-08 23:06:14:099 0x78e19f8 folder.cpp:438 OO folder slotSyncFinished: result:  3
01-08 23:06:14:099 0x78e19f8 folder.cpp:857   ** error Strings:  ("TESTdoc.docx: Cannot remove source file")
01-08 23:06:14:099 0x78e19f8 folder.cpp:859     * owncloud csync thread finished with error
01-08 23:06:14:100 0x78e19f8 folder.cpp:879 the last 3 syncs failed
```

Full log  S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2428\word-file_error.txt

**Comment by cdamken** [comment] 2015-02-09 14:31
@ckamm Any news?

**Comment by dragotin** [comment] 2015-02-09 14:57
@cdamken this is supposed to be fixed in 1.8.0 Please test with the latest nightly build from 
http://download.owncloud.com/desktop/daily/ and reopen if not. Thx.

**Comment by cdamken** [comment] 2015-03-17 15:42
I've tested the scenario again.

Under mac and windows. I was using 1.8.0

When opening a word-file under window and Mac on the same time. I first
changed the word-file om my mac. Then I got a conflict file. So works
now as expected.

However when I changed the scenario by writing first under Windows, I
get an issue om my Mac. It's impossible om my Mac to save/write under
Word to the same document. Every time I try to exit word I get the
notification "do you want to save?" Whatever I try it won't save and
generate a conflict file.

So it doesn't look like it's completely solved.

**Comment by ckamm** [comment] 2015-03-25 09:13
@cdamken Could you elaborate on the failing case?

* You open the file on Win and Mac
* Edit on Win, save and sync Win
* Sync Mac, edit on Mac, saving fails?

What happens exactly when you press 'Save' on Mac? Does it generate a conflict file or not (ambiguous sentence)?

**Comment by ckamm** [comment] 2015-04-08 07:48
@cdamken ^

**Comment by cdamken** [comment] 2015-04-10 07:21
@ckamm  Sorry about the delay:

When opening a word-file under window and Mac on the same time. I first changed the word-file om my mac. Then I got a conflict file. So works now as expected.

However when I changed the scenario by writing first under Windows, I get an issue on my Mac. It's impossible on my Mac to save/write under Word to the same document. Every time I try to exit word I get the notification "do you want to save?" Whatever I try it won't save and generate a conflict file.

So it doesn't look like it's completely solved.

**Comment by ckamm** [comment] 2015-04-10 07:29
@cdamken You say you:
* Open the file on Windows and Mac, make edits.
* Save the file on Windows, sync it to the server. 
* Saving on Mac is impossible.

Do you get an error message? 

@guruz Could you try to reproduce on Mac? Any server side change of the Word file should do...

**Comment by cdamken** [comment] 2015-04-15 12:06
@ckamm Every time I try to exit word I get the notification "do you want to save?" Whatever I try it won't save and generate a conflict file.

**Comment by ckamm** [comment] 2015-04-15 12:10
@cdamken "it saves the file but does not generate a conflict file" or "it does not save the file and does not generate a conflict file"?

**Comment by cdamken** [comment] 2015-04-15 12:56
@ckamm I don't have a mac to reproduce it again, as far as I remember no conflict file and it could not be saved with the original name.

**Comment by ckamm** [comment] 2015-04-22 07:43
This really needs someone with a Mac. :)

**Comment by cdamken** [comment] 2015-04-22 14:38
@ckamm I think @dragotin has a mac :+1:

**Comment by dragotin** [comment] 2015-04-23 09:58
I spent reasonable  time to test this again with the upcoming 1.8.1 client. 

It's a bit tricky. What happens is:
On windows, Word locks the file it has opened. So the client has no way to update the file while it is open, and thus there are warnings if there are conflict cases, ie. somebody changed the file on the server. These are resolved once Word is ended and the file is accessible again. 

If the windows Word user saves the file, however, the file is nicely synced up. 

On Mac, its different. If there is a conflict case on Mac, the client moves the word doc into a conflict file. That works, and Word **realizes** the move and continues to work on the moved file. That means that the filename has changed! That might be confusing for users, but actually that is a very consistent behaviour. Once a user *knows* that, it is very clear what happens. 

Under our assumption that the server always wins, I think that all is reasonable behaviour and I can not reproduce any errors.

@cdamken please explain that to the customer and close the bug if you agree.

**Comment by Dianafg76** [comment] 2015-06-09 12:04
@cdamken this issue can be closed

**Comment by moscicki** [comment] 2015-06-09 13:28
@dragotin: yes, you are right that the behaviour is technically consistent on Mac but there is a drawback: the file the user is working on is not anymore synchronized (so the data is not "backed up" on the server). I bet that 90% of users will not notice this until they lose the access to the file when they are away from their local computer (or when they the file itself when the local disk crashes).

I think this is a general problem with the current handling of conflict files in this respect.

**Comment by ogoffart** [comment] 2015-07-29 15:15
@moscicki  This is due to the fact that on mac, locking does not work the same way.  There are some system calls we could do. But this is another issue than the original one which has already 35 comments about differnet things.
I am closing this issue and a new issue can be openned with the exact problem so it will be easier to track.

**Closed** 2015-07-29 15:15 UTC
Labels: blue-ticket, bug
