### ISSUE TITLE
Icons in top menu bar on macOS Big Sur get squeezed together when connected to an external monitor

### ISSUE THREAD

**Issue by viktorx69** [owncloud/client#8226] opened 2020-11-15 18:29 UTC
### Expected behaviour
No change in size of icons.

### Actual behaviour
Icon size changes..

### Steps to reproduce
1. Install macOS Big Sur
2. Use ownCloud or sciebo
3. Connect to an external monitor
4. Work on either display and check the icon on the other one

### Client configuration
Client version: 2.6.3

Operating system: macOS Big Sur 11.0.1

![photo_2020-11-15_19-30-09](https://user-images.githubusercontent.com/51529903/99193429-10b8ba80-2779-11eb-8de1-d9b26c6eccf0.jpg)

**Comment by TheOneRing** [comment] 2020-11-16 15:43
Could you retry with a 2.7 testpilotcloud installer ? https://download.owncloud.com/desktop/testpilotcloud/daily/2.7/mac/?sort=time&order=desc

**Comment by emersonmello** [comment] 2020-11-25 12:32
Hi @TheOneRing , 

Same problem with client version: 2.7.1 (build 2560).

**Comment by TheOneRing** [comment] 2020-12-02 12:00
Upstream issue https://bugreports.qt.io/browse/QTBUG-88600

**Comment by TheOneRing** [comment] 2020-12-02 12:05
Duplicate of: https://github.com/owncloud/client/issues/8149

**Closed by TheOneRing** 2020-12-02 12:05 UTC
Labels: Qt 5.12.11, Upstream issue
