### ISSUE TITLE
[QA] Cannot quit welcome to owncloud dialog

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11465] opened 2024-01-08 15:25 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud-6.0.0.13051-daily20240106

### Steps to reproduce the issue

1. Start the client without any account -> welcome to owncloud dialog gets open
2. Click Cancel 

### Screenshots

No screenshot

### Expected behavior

Dialog cancelled 

### Actual behavior

Client becomes unresponsive

**Comment by TheOneRing** [comment] 2024-01-09 08:45
Duplicate of: https://github.com/owncloud/client/issues/11032

**Closed by TheOneRing** 2024-01-09 08:45 UTC
Labels: bug, p3-medium, QA:team
