### ISSUE TITLE
does not start/core dump on Ubuntu 20.04 – incorrect LD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by TentativeConvert** [owncloud/client#11329] opened 2023-11-02 20:08 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When I try to start owncloud from the launcher, nothing happens.
When I start owncloud from the terminal (by typing `owncloud`), I get the following error message:
````
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, wayland, xcb.

Aborted (core dumped)
````

### Expected behavior

I expect the GUI to appear.

### Client version number

`owncloudcmd --version gives the following output:`
````
owncloudcmd ownCloud 4.2.0.11670
https://github.com/owncloud/client/commit/f5a29bc3446734c565b106c1bdddc09ec03f76eb
Libraries Qt 5.15.2, OpenSSL 1.1.1f  31 Mar 2020
Using virtual files plugin: suffix
ubuntu-5.15.0-88-generic
````

### Desktop environment (Linux only)

Ubuntu 20.04.6 with GNOME Version 3.36.8

### Client package version and origin (Linux only)

Fresh install according to instructions at https://attic.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

### Additional context

The client work until a few days ago. I don't know what changed.  I did a fresh install and that did not help.  I have another computer with the same OS on which it still works.  I simply don't know what to try and how to get to the root of this problem.

**Comment by TheOneRing** [comment] 2023-11-03 14:36
Are you running the client in a normal desktop session or a ssh session or something like that?

**Comment by TentativeConvert** [comment] 2023-11-03 18:12
I'm running the client in a normal desktop session.

**Comment by TentativeConvert** [comment] 2023-11-04 09:55
Some more details:

1. As I said, I'm running the client in a normal desktop session.  More specifically, I'm using the standard X display server (not Wayland). 
1. Reinstalling from Ubuntu's universe repository rather than from the custom PPA described at https://attic.owncloud.com/desktop/ownCloud/stable/latest/linux/download/ (which I removed) did not change anything.  Same problem.  The owncloud version in the universe repository appears to be identical to the one in the custom PPA, or at least the output of 'owncloudcmd --version' is identical to the one included above.
1. Starting owncloud with `env QT_DEBUG_PLUGINS=1 owncloud` yields the following more specific error message:
````
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/opt/ownCloud/ownCloud/bin/platforms" ...
Cannot load library /opt/ownCloud/qt-5.15.2/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN20QPlatformIntegration16openGLModuleTypeEv, version Qt_5_PRIVATE_API)
QLibraryPrivate::loadPlugin failed on "/opt/ownCloud/qt-5.15.2/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so" : "Cannot load library /opt/ownCloud/qt-5.15.2/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: _ZN20QPlatformIntegration16openGLModuleTypeEv, version Qt_5_PRIVATE_API)"
... 
````
So the problem appears to be an error in a library called 'libqxcb.so'.

**Comment by TentativeConvert** [comment] 2023-11-04 10:10
I've managed to start the client with the following command:

    env LD_LIBRARY_PATH="/opt/ownCloud/qt-5.15.2/lib/x86_64-linux-gnu/qt5/plugins/platforms" owncloud

Does anyone now have an idea what's going on?  This was never necessary before.  And if it is necessary, shouldn't the desktop launcher set the correct environment variables automatically?

**Comment by fmoc** [comment] 2023-11-06 11:28
`LD_LIBRARY_PATH` should only be set if necessary. It takes precedence over the link information we configure inside the binaries already (namely `DT_RUNPATH`, also known as `rpath`). You basically force the client to use your system Qt which cannot work since we ship our own Qt.

**Comment by fmoc** [comment] 2023-11-07 11:34
Closing as this is a user error, not a bug in the software.

**Closed by fmoc** 2023-11-07 11:34 UTC
Labels: Won't fix, Linux
