### ISSUE TITLE
Feature request: allow periodic client synchronisation

### ISSUE THREAD

**Issue by tomdereub** [owncloud/client#4524] opened 2016-03-01 10:01 UTC
I would be great to have a periodic synchronisation mode in the client.
For the moment, it is constantly synchronising. So when you're working on a synchronized file, every time you save the file it will be copied by owncloud.

So a periodic configurable synchronisation (15 min, 1h... depend of your needs) could save file transfer, especially if your connection is slow.

**Comment by dragotin** [comment] 2016-03-01 10:05
Do you see that only for the one file or for the entire sync connection to that account?

**Comment by tomdereub** [comment] 2016-03-01 10:23
I see that for the entire sync connection, just as if the client were disconnected, and it connects every x minutes, make a full synchronisation and disconnects.
I'm often doing it manually, I start owncloud only when I'm working on synchronized files, (once before, once after work). For people using owncloud with very low resources (yunohost on a raspberry Pi for example), I think such a feature could be very interesting.

**Comment by guruz** [comment] 2016-03-01 13:52
@tomdereub I think the question is if there were actual file changes that trigger the sync? (remote or local). Because only then a synchronization is attempted.

**Comment by tomdereub** [comment] 2016-03-01 15:53
Of course, when I say full synchronisation, I mean full check for files changes and synchronization if needed. The idea is to avoid synchronizing many times the same files because you're working on them. For example, you can manipulate photos, resizing and other stuff, if owncloud is on it will synchronize it at each step of modification.

**Comment by guruz** [comment] 2016-03-02 08:12
@tomdereub OK, so there were actual changes of files? Then this is a duplicate of https://github.com/owncloud/client/issues/3935 :)
thanks

**Closed by guruz** 2016-03-02 08:12 UTC
Labels: Enhancement
