### ISSUE TITLE
Inconsistent look of Quit button

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7639] opened 2019-12-06 09:48 UTC
Windows 10, 2.6.1-daily20191205 (build 12825)
Ubuntu 19.10, 2.6.1daily20191205 (build 1838)

When making the dialog smaller, the button either disappears completely or only a half is visible

<img width="506" alt="Screenshot 2019-12-05 at 10 15 30" src="https://user-images.githubusercontent.com/49001702/70311635-4edff700-1812-11ea-86c2-f7c88a3c60c6.png">

<img width="511" alt="Screenshot 2019-12-05 at 10 15 14" src="https://user-images.githubusercontent.com/49001702/70311636-4edff700-1812-11ea-93e1-33aab471ff77.png">

**Comment by guruz** [comment] 2019-12-07 08:46
@TheOneRing Why do you show the button at all on Windows and macOS?
I thought this is a problem of a specific Linux desktop?

**Comment by TheOneRing** [comment] 2019-12-09 08:21
I think we should always aim for a unified ui experience across all platforms.

**Comment by ogoffart** [comment] 2020-03-05 10:16
Duplicate of https://github.com/owncloud/client/issues/7744 which was fixed.

**Closed by ogoffart** 2020-03-05 10:16 UTC
Labels: Design & UX, bug
