### ISSUE TITLE
[Mac OS X] "Untrusted Certificate" "mitmproxy-ca-cert.pem"

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4128] opened 2015-11-12 17:00 UTC
### Expected behaviour

ownCloud desktop sync client should connect with certificates marked as "trusted for all users" in "Keychain Access"

![os_x_10_11](https://cloud.githubusercontent.com/assets/214010/11124429/4b948736-8965-11e5-80b8-a1f81b0cd2ef.png)

### Actual behaviour

The ownCloud desktop sync client "Cannot connect securely"

![cursor_and_os_x_10_11](https://cloud.githubusercontent.com/assets/214010/11124478/86360748-8965-11e5-8d21-dac3fe49cfda.png)

The same certificate works in Safari:

![cursor_and_os_x_10_11_and_new_issue_ _owncloud_client](https://cloud.githubusercontent.com/assets/214010/11124517/bd304f4c-8965-11e5-8845-f32ddf4655e3.png)

### Steps to reproduce
1. install ownCloud desktop sync client
2. install and run mitmproxy
3. add "mitmproxy-ca-cert.pem" to "System" Keychain in "Keychain Access"
4. set Trust "When using this certificate"  to "Always Trust"
5. run ownCloud desktop sync client and connect to server

![cursor_and_os_x_10_11 2](https://cloud.githubusercontent.com/assets/214010/11124819/1db77718-8967-11e5-9a63-45c922202981.png)

### Client configuration
Client version:

Operating system:
Mac OS X 10.11 (El Capitan)

OS language:
English

Installation path of client:
/Applications/owncloud.app

**Comment by danimo** [comment] 2015-11-12 17:09
Qt upstream bug: https://bugreports.qt.io/browse/QTBUG-32898

**Comment by danimo** [comment] 2015-11-17 12:11
Duplicate of #2964.

**Closed by danimo** 2015-11-17 12:11 UTC
