### ISSUE TITLE
client hanging: MacOSX, 1.7.0

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2306] opened 2014-10-12 18:13 UTC
After several network changes and closed lid I eventually got the client hanging and the mac ball spinning on it. I think it is hard to reproduce but here is the process sample:

https://gist.github.com/moscicki/528a8a3f70bb0990121e

kuba

--

**Comment by moscicki** [comment] 2015-01-06 16:30
Hello,

We will try to reproduce with 1.7.1 however 1.7.0 is definitely suffering from this problem. Here is another trace:

https://gist.github.com/moscicki/771e1475274b6667510a

For the logs, we will extract them at the next opportunity.

kuba

--

**Comment by geez0x1** [comment] 2015-01-12 09:26
I am able to reproduce this bug on 3 systems using the same owncloud server. One system is running Debian Jessie (testing), one is running Ubuntu 14.10, one is running Ubuntu 14.04. The first two use the same ownCloud account, the last a different account (although accessing a folder shared by the first account). Server is running OC 7.0.4, all clients are running client 1.7.1. The problem also occurred on client 1.7.0.

In all cases the GUI remains responsive, however I cannot quit the client or pause/resume the sync. The tray icon will occasionally display a 'pause' state when this happens (even though I did not pause it?). After 'killall owncloud' and restarting the client the sync is fine, until it happens again a while later. 

This is annoying/dangerous because it can happen without me knowing, resulting in me finishing work on one machine, going home to one of the other machines and having missing/outdated files.

Please let me know if/how I can provide any logs for this.

To me this appears to be the same issue as in:
https://github.com/owncloud/client/issues/2651
http://forum.owncloud.org/viewtopic.php?f=14&t=25550

**Comment by guruz** [comment] 2015-01-19 17:21
@moscicki @geez0x1 How many files in that sync folder?

**Comment by geez0x1** [comment] 2015-01-20 17:37
The shared folder across al these devices is currently 5,814 items, totalling 9.4 GB. The entire folder is 8,735 items, totalling 12.1 GB.

**Comment by guruz** [comment] 2015-01-26 15:55
I'm closing this issue, the 1.8/master codebase has a different way of traversing the remote directories and should not get stuck anymore.
If you're brave and have backups, please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.1940-nightly20150126.pkg

**Closed by guruz** 2015-01-26 15:55 UTC
Labels: bug, Needs info, Platform Specific, sev3-medium

**Comment by geez0x1** [comment] 2015-03-11 08:45
Let's see if I can still comment here. This bug still occurs for me, with the latest version of server and client. Since the problem is (temporarily) solved by restarting clients, can't the problem be in the client? I've had this issue for a while on 3 separate systems now (see my earlier post), it's becoming a rather unreliable experience.

**Comment by guruz** [comment] 2015-03-11 08:48
> with the latest version of server and client. 

Which ones?

**Comment by geez0x1** [comment] 2015-03-11 08:51
Clients are 1.7.1, server is 8.0.0.

**Comment by guruz** [comment] 2015-03-11 08:55
The latest released client version is 1.8.0beta2.
See https://github.com/owncloud/client/issues/2306#issuecomment-71482724

You can also use a newer nightly build:
 http://download.owncloud.com/desktop/daily/

**Comment by geez0x1** [comment] 2015-03-11 08:57
I see; I mistakenly read your older post as being about the beta for server 8.0, since released. I will be trying that client beta release then and I'll post my results. Thanks.

**Comment by geez0x1** [comment] 2015-03-13 16:27
I installed the 1.8 builds. First on one machine, then the others. I started with beta2, and upgraded to rc1 as it came out. No problems thusfar :) :+1:

**Comment by geez0x1** [comment] 2015-03-17 22:15
P.S. I see the build for Debian has not been updated yet to rc1, but is still at beta2. No problems with beta2 either though.
