### ISSUE TITLE
[Windows] Tray Icon Disappears from time to time

### ISSUE THREAD

**Issue by madmoneymike5** [owncloud/client#3079] opened 2015-04-08 13:36 UTC
### Steps to reproduce

Note: Not sure you'll be able to reproduce the bug by following the steps below, but this is the sequence of events I just did and how this issue happened.

1. Download and install client.
2. Begin syncing content already in the ownCloud folder.
3. Leave running for a long time (in my case, it was left running over 24 hours); client is uploading the entire time.
4. Come back next day.

### Expected behaviour
I should be able to find the ownCloud client icon in my system tray (near date and time). Also, when I click "Close" in the client or the "x" at the top right, it should minimize to the system tray.

### Actual behaviour
Application disappears, but continues running in the background. No icon in the system tray nor in the task bar. The only way to bring it back is to click on the icon in the Start Menu or on the Desktop as if it wasn't already running and you're just opening it normally.

### Server configuration
**Operating system**: Linux Ubuntu 14.04LTS

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) 8.0.2

**Updated from an older ownCloud or fresh install:** Fresh Install

**List of activated apps:** Default apps, nothing else.

**The content of config/config.php:**

```
Not relevant.
```

**Are you using external storage, if yes which one:** local/smb/sftp/... None

**Are you using encryption:** yes/no Yes, SSL SHA2

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No.

### Client configuration
**Browser:** Chrome 41.0.2272.118 m

**Operating system:** Windows 7 Home Premium

**Client Version:** 1.8.0 (build 4847)

#### Web server error log
```
Not relevant.
```

#### ownCloud log (data/owncloud.log)
```
Not relevant.
```

#### Browser log
```
Insert your browser log here, this could for example include:
Not relevant.

**Comment by madmoneymike5** [comment] 2015-04-08 13:58
Additional Info: Client is configured to use monochrome icons. However, issue is persisting even after unchecking the box. Whether or not having the option checked in the first place has anything to do with it, I don't know.

**Comment by JeffZwolle** [comment] 2015-04-08 18:08
Same problem here.
Windows Vista

**Comment by ckamm** [comment] 2015-04-09 09:13
@madmoneymike5 @JeffZwolle Did you see a tray icon initially that vanished after a while or was there no tray icon from the start?

**Comment by JeffZwolle** [comment] 2015-04-09 09:49
Yes, I saw the trayicon after the install. It was gone after a reboot.
The client does function however. And the symbols in the icons of the files to sync also function.

Jeff


Op 9 apr. 2015 om 11:13 heeft ckamm <notifications@github.com> het volgende geschreven:

@madmoneymike5 @JeffZwolle Did you see a tray icon initially that vanished after a while or was there no tray icon from the start?

**Comment by madmoneymike5** [comment] 2015-04-09 10:31
Yes, it was there initially. While I reported that they disappear after a
while of having the computer up and running, and Jeff just reported it as
after a reboot, I, too, can confirm that sometimes (but not always) the
icon isn't there after a reboot. I had forgotten about that. Both issues
exist.

**Comment by ckamm** [comment] 2015-04-10 08:39
@JeffZwolle @madmoneymike5 Just to confirm, you have clicked 'Customize' on the tray arrow and checked whether owncloud.exe's behavior is set to "Show icon and notifications"? It was set to "Only show notifications" for me by default.

**Comment by madmoneymike5** [comment] 2015-04-10 13:09
Yes, I've checked this.

The intention of that setting in Windows is to prevent the icon from
showing all the time. When enabled, the icon will be hidden, but it is
still supposed to be visible in the tray when you click the arrow to view
all the 'hidden' icons. In my case, it is still missing even after clicking
this arrow. Additionally, I have the ownCloud icon set to show all the
time, so it should never not be visible.

**Comment by JeffZwolle** [comment] 2015-04-10 17:21
After the install and before the reboot I found out that the standard behaviour of the tray-icon is to "show notifications only". I changed this to "Show icon and notifications".
After the reboot the tray-icon does not show in the regular and hidden tray-icons-area.

**Comment by JeffZwolle** [comment] 2015-04-10 22:39
Seems to be an intermittent problem:
This evening I checked the laptop again: tray-icon is back and fully funtioning.
No changes in configuration had been made.

(The laptop (Windows Vista) is used by my girlfriend. She is the only client connecting to my OwnCloud. I wanted this solution to automate her backups, because she keeps forgetting it.)

**Comment by nekoal** [comment] 2015-04-11 07:28
I'm not sure this relevant but I had simular issue with other application tray icons. For example, Winamp player. As multiplatform application I presume occlient also has this weak point. When explorer crashes for any reason and windows auto-restore explorer (default setting) some applications not receive/handle "Shell restart" event and not update/recreate tray icon. And when application update icon (for example after disable-enable tray icon) icon appear again. May be your explorer was restarted and client don't change icon since it. And after syncronization icon changes and appears. Are your system log have for some records about explorer crash or others shell events?

Are you still can see client window when icon disappears? If you can see client in process list is it run under your username?

**Comment by madmoneymike5** [comment] 2015-04-12 12:51
I'm able to access the client once the icon disappears only by clicking on the shortcut in the start menu as if I'm trying to launch the application. This somehow forces the app to reappear, but the icon still does not. The client is always in the process list. I don't know which username it's under; I'm away from that computer right now.

No explorer or other shell crashes have occurred. Everything is operating normally except this.

**Comment by Tuumke** [comment] 2015-04-13 13:21
@danimo maybe the same, but i dont get to see the icon anymore. Not after a reboot, not after re-starting or starting the 2nd time.

**Comment by guruz** [comment] 2015-04-15 10:52
@Tuumke Afaik starting the client twice will make it show the settings dialog. does that happen?

**Comment by madmoneymike5** [comment] 2015-04-15 10:57
Not for me it doesn't...It just makes the client finally reappear.

**Comment by guruz** [comment] 2015-04-15 13:58
On https://github.com/owncloud/client/issues/2857#issuecomment-83983484 @Ichigami mentions that he does not have this with 1.7.1 but does with 1.8.0 ..
Just wondering if you ever try that?

**Comment by Tuumke** [comment] 2015-04-15 14:25
@guruz Nope, its just 2x in the task manager but no screen or anyhting :(

**Comment by guruz** [comment] 2015-04-20 14:32
@ogoffart has mentioned that Qt 5.5 (alpha available) has a lot of tray fixes.

**Comment by ckamm** [comment] 2015-04-22 07:30
This sounds like an unfortunate tray integration bug in Qt. @nekoal Thanks for the hint about it possibly being related to explorer crashes, I'll try to reproduce that.

**Comment by ckamm** [comment] 2015-04-22 07:51
I couldn't reproduce the problem by killing and restarting explorer.exe on Win7.

**Comment by nekoal** [comment] 2015-04-22 09:05
As I wrote above I'm not sure this relevant. In any case I think this behavior hard to reproduce. And I think in case of manual start explorer.exe Windows generate different events than on automatic restart by winlogon process. Also there isn't garantee client don't change icon in this moment on another event.
May be good idea make screenshots (with Process Explorer help) of properties of run occlient process and explorer process when icon disappear. If explorer was restarted it can be detected by start time. If occlient don't has interactive flag or run under other username it also can be seen.Two clients in task manager are also interesting sample to see screenshots of properties and open handles.

**Comment by ckamm** [comment] 2015-04-23 08:02
I don't see any Windows tray icon fixes in Qt between 5.3 and 5.5 or on Qt's gerrit instance. The only interesting Qt bug on windows system trays I found is https://bugreports.qt.io/browse/QTBUG-5078 - but that shouldn't prevent the tray icon from showing.

@JeffZwolle @madmoneymike5 Do you use 64bit or 32bit Windows? Do you have a multi-monitor setup?

**Comment by ckamm** [comment] 2015-04-23 09:28
I also looked at the qsystemtrayicon_win code and its history. I found a couple of spots that look odd (https://codereview.qt-project.org/#/c/111058/) but I don't think any of them cause this problem. They would have been present since Qt 5.0 too.

**Comment by ckamm** [comment] 2015-04-23 09:33
@JeffZwolle @madmoneymike5 How reliably can you reproduce this problem? If you had a test build that might fix the problem, could you determine whether it worked or not?

**Comment by Tuumke** [comment] 2015-04-23 09:36
@nekoal The icon also doesnt appear for me from boot/logon. I just doenst show up.
I do have multiple monitor setup on my laptop, at home laptop with W10, same build, it works fine.

**Comment by ckamm** [comment] 2015-04-23 09:45
@Tuumke Could you start the client with --logfile log.txt from the command line and then upload the log? Maybe there are interesting warnings or messages that help illuminate your problem. See https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly for detailed instructions.

**Comment by Tuumke** [comment] 2015-04-23 10:43
Logfile: http://pastebin.com/J8USwRNJ
Could not initialize EGL display: error 0x3001

**Comment by madmoneymike5** [comment] 2015-04-23 12:00
Windows 7 Home Premium 64bit on all my machines. One has multiple monitors,
but the icon there has yet to have a problem. It's my laptop that's having
the most trouble.

**Comment by jturcotte** [comment] 2015-04-23 13:42
"static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available"

We don't use OpenGL, but we do ship a Qt ANGLE build without that Direct3D dll, we might have to either make sure that nothing tries to use OpenGL (i.e. QtWebKit might try by itself depending on what the shibboleth login contains) or build Qt with QT_NO_OPENGL or just ship that dll.

That said, I can't see how that error would result in the tray icon not showing. The error message might just be caused by the same problem than the tray issue, without it being the source of the issue.

**Comment by JeffZwolle** [comment] 2015-04-23 15:01
@ckamm 
The only time I saw this problem was on the first day of use. After that the systemtrayicon was visible. As I mentioned, I installed it on my girlfriends laptop. The times I looked at her screen the icon was still there.

I cannot reproduce the problem, because I only saw the problem on the first day of use. Even after multiple powercycles.

My girlfriends laptop has Windows Vista 32bit installed.
I also installed it on 2 other laptops, both have Windows 7 64bit.
I have not seen the problem on those laptops yet. Not even in the beginning like the laptop that runs Windows Vista.

All three laptops do not have multiple monitors.
On one laptop (Windows 7) there is a docking-station attached with a monitor. But it is not used in a multimonitor-setup.

**Comment by nekoal** [comment] 2015-04-23 17:34
I saw some errors about EGL in log since first use of occlient and tray icon was visible. I don't think errors related tray icon issue. Also d3dcompiler dll shiped with almost all versions of web browsers. For example, latest versions of Chrome and Firefox use d3dcompiler_47.dll You can test if missing this dll is reason with simple copy this dll from browser directory to owncloud directory. If errors no more shown in log after this but icon still missing it'll prove no connection between issues.

**Comment by sisu4u** [comment] 2015-05-06 12:13
I'm having the same issue. Suddenly the tray icon disappeared and it's not coming back. I tried restarting, reinstalling owncloud (1.8.0 & 1.8.1.rc1.5006) but none of them works. There is no GUI, no tray icon and no possibility to interact with owncloud. There is only the owncloud.exe process in the taskamanager. If I start owncloud with --logfile  no file is created at all.

I'm on Windows 8.1 x64.

Is this problem here related to mine?

**Comment by guruz** [comment] 2015-05-08 13:53
Guys, could you try if deleting this lock file makes it work again:
https://github.com/owncloud/client/issues/3175#issuecomment-100211636

Please also report back here..

**Comment by ckamm** [comment] 2015-06-03 07:16
This ticket has a confusing mixture of symptoms by now. I'll close this and ask anyone who still suffers from this to open a new issue so we can try to narrow down the possible causes. 

The most common cause is probably #3175 - please check that one first.

**Closed by ckamm** 2015-06-03 07:16 UTC
Labels: bug, Needs info
