### ISSUE TITLE
Mismatch of domains containing punycode during SSL certificate comparison

### ISSUE THREAD

**Issue by moontan** [owncloud/client#5530] opened 2017-02-12 18:57 UTC
![owncloud-client-letsencrypt-error](https://cloud.githubusercontent.com/assets/1488038/22865067/7153ff10-f197-11e6-8c8f-c0bb7b67794e.png)

### Expected behaviour
The domain name of the owncloud/nextcloud instance is supposed to be recognised as matching with the domain name provided by the certificate.

### Actual behaviour
When connecting to an owncloud/nextcloud server via https:// the domain name isn't recognised as the domain provided by the certificate because it contains punycode.

### Steps to reproduce
1. Connect to owncloud/nextcloud server via https://  
2. (As an alternative way: Embed Nextcloud WebDAV in Dolphin, creates the same error — Possibly problem with system's SSL library?)
3. x

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:
Nextcloud
Storage backend (external storage):

### Client configuration
Client version:
owncloud-client 2.1.1+dfsg-1ubuntu1.1
Operating system:
Kubuntu 16.04
OS language:
en-GB
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment] 2017-02-13 16:10
> owncloud-client 2.1.1+dfsg-1ubuntu1.1

Please don't use outdated distro packages, the 2.3.0 beta1 client can be downloaded from https://owncloud.org/changelog/desktop/

**Comment by ogoffart** [comment] 2017-02-16 08:36
Also what is the Qt version?

**Comment by ogoffart** [comment] 2017-02-16 08:51
I tried to reproduce, but https://☁.crypt.pl does not seem accessible from the internet.
So I tried to find another https url with punicode, and when i enter https://❤❤❤.ws/ in the wizard, the certificate is correctly accepted.

What happens for you if you use  https://❤❤❤.ws/ ?

I suspect it might be because older version of Qt did not support it

**Comment by ogoffart** [comment] 2017-03-02 15:44
Closing as a duplicate of https://github.com/owncloud/client/issues/5572 which has more information to reproduce.

**Closed by ogoffart** 2017-03-02 15:44 UTC
Labels: Needs info

**Comment by moontan** [comment] 2017-07-25 09:54
Oh, the domain is not `crypt.pl`, it's `cryp.pl`. I'm trying with version 2.2.4.1 build 1 on MacOS X 10.12 now (The download page said 2.3.1 was the latest stable, but the download button gave me only this package) — I still get "untrusted certificate" notifications. Unicode character "☁" and the corresponding punycode `xn--l3h` aren't recognised as the same.

**Comment by ogoffart** [comment] 2017-07-25 10:01
This is fixed in Qt 5.9. (But our packages still ship with Qt 5.6)
