### ISSUE TITLE
Improve automatic update message

### ISSUE THREAD

**Issue by kalwados** [owncloud/client#3075] opened 2015-04-07 18:22 UTC
The current message when a new windows client update is available doesn't mention that it is related to ownCloud:
![owncloud updates](https://cloud.githubusercontent.com/assets/11840444/7030252/8be89e84-dd63-11e4-8f75-5d0de231a126.png)
Please add "owncloud" to the window title or to the message.

**Comment by danimo** [comment] 2015-04-07 18:27
Duplicate of #3040, already fixed!

**Closed by danimo** 2015-04-07 18:27 UTC
