### ISSUE TITLE
Firefox crashes when opening Explorer due to ownCloud dll

### ISSUE THREAD

**Issue by annavanharmelen** [owncloud/client#11691] opened 2024-06-10 16:21 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Since the 5.3.0 release of the ownCloud desktop app on Windows, the following started happening: When opening the Explorer from Firefox, e.g. for selecting a file for an upload input or saving a file (from the print dialog or just the entire web page), Firefox crashed. The crash reports mention a ownCloud dll (OCOverlays.dll) and removing the desktop app did solve the issue.

### Expected behavior

I expected to be able to open Explorer when trying to save or upload a file from Firefox.

### Steps to reproduce the issue

1. Have ownCloud installed, in this case logged in with an Enterprise account (from my university)
2. Have Firefox installed (version 126.0.1/127 beta doesn't matter, troubleshoot mode doesn't matter)
3. Open Firefox
4. Press Ctrl+S to save any open page
5. Firefox crashes 

### Logs

I don't have ownCloud specific logs, but I do have some Firefox crash reports:
- https://crash-stats.mozilla.org/report/index/8ff5e1db-fdc4-46c5-99fe-f6db00240610
- https://crash-stats.mozilla.org/report/index/42902b22-e938-466f-ba89-a81ae0240610
- https://crash-stats.mozilla.org/report/index/e7cf502a-827c-4f62-8712-b42ba0240607
Can provide more if needed.

### Client version number

ownCloud 5.3.0.13987 [bda4a9](https://github.com/owncloud/client/commit/bda4a92d8021d4a17c7be353efea07cc93447475)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.22631
QPA: windows

### Installation path (Windows only)

C:\Program Files\ownCloud

### Additional context

I tried:
- Troubleshoot mode of Firefox
- Edge (worked)
- Refreshing and reinstalling Firefox

**Comment by TheOneRing** [comment] 2024-06-10 16:36
https://central.owncloud.org/t/owncloud-client-5-2-1-13040-owncloud-client-explorer-exe-crash-loop/48472/17

**Comment by TheOneRing** [comment] 2024-06-10 17:11
The issue is related to https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html#variable:CMAKE_MSVC_RUNTIME_LIBRARY
Which causes https://github.com/owncloud/client/blob/master/shell_integration/windows/CMakeLists.txt#L10 to have no effect.

**Comment by jmairboeck** [comment] 2024-06-11 07:15
For the record: I noticed the same problem also in Visual Studio 2022: https://developercommunity.visualstudio.com/t/Visual-Studio-crashes-after-opening-any-/10679034

**Comment by TheOneRing** [comment] 2024-06-11 13:05
Fixed in https://github.com/owncloud/client/releases/tag/v5.3.1

**Closed by TheOneRing** 2024-06-11 13:05 UTC
Labels: bug, p1-urgent

**Comment by annavanharmelen** [comment] 2024-06-11 19:07
Wow! Thanks for the quick solution 🤩 I've downloaded the new version and it works like a charm!
