### ISSUE TITLE
If using Shibboleth authentication on Owncloud the client always reopens the login window after discovery process

### ISSUE THREAD

**Issue by e-alfred** [owncloud/client#4974] opened 2016-06-16 11:44 UTC
### Expected behavior

Owncloud Client should stay logged in and start sync process if necessary.
### Actual behavior

The authentication window opens and after entering the login information the discovery process starts again, after finishing the authentication window opens again.
### Steps to reproduce
1. Set up an account in the Owncloud client using Shibboleth authentication.
2. Let the discovery process start and run until it finishes.
3. The login window shows up again.
### Server configuration

ownCloud version: 8.2.3
### Client configuration

Client version: 2.2.1

Operating system: Debian 8 Jessie

OS language: EN

Installation path of client: /usr/bin/owncloud /usr/share/owncloud
### Logs

06-16 13:29:27:550 0x1d231e0 void OCC::ShibbolethCredentials::slotReplyFinished(QNetworkReply_) detected redirect, will open Login Window 
06-16 13:29:27:551 0x1d231e0 AccountState state change:  "Connected" -> "Configuration error" 
06-16 13:29:27:551 0x1d231e0 Account "user@server" disconnected or paused, terminating or descheduling sync folders 
06-16 13:29:27:552 0x1d231e0 folder  "1"  Terminating! 
06-16 13:29:27:552 0x1d231e0 void OCC::SyncEngine::abort() OCC::DiscoveryMainThread(0x471a030) 
06-16 13:29:27:552 0x1d231e0 void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply_) "Unknown error" 302 0 
06-16 13:29:27:552 0x2058f48 OCC::DiscoveryJob(0x65823e0) git/FreeCodeCamp/common/app ...Returned from main thread 
06-16 13:29:27:552 0x2058f48 5 when opening git/FreeCodeCamp/common/app msg= "Aborted by the user" 
06-16 13:29:27:552 0x2058f48 csync_ftw: Aborted!
06-16 13:29:27:552 0x2058f48 static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t_, void_) OCC::DiscoveryJob(0x65823e0) "/git/FreeCodeCamp/common" 
06-16 13:29:27:552 0x2058f48 static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t_, void_) OCC::DiscoveryJob(0x65823e0) "/git/FreeCodeCamp" 
06-16 13:29:27:552 0x2058f48 static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t_, void_) OCC::DiscoveryJob(0x65823e0) "/git" 
06-16 13:29:27:552 0x2058f48 static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t_, void_) OCC::DiscoveryJob(0x65823e0) "" 
06-16 13:29:27:552 0x2058f48 csync_statedb_close: sqlite3_close=0
06-16 13:29:27:562 0x1d231e0  #### ERROR during  csync_update :  "Aborted by the user Aborted by the user" 
06-16 13:29:27:563 0x1d231e0 Update phase was aborted by user! 
06-16 13:29:27:563 0x1d231e0 void OCC::SyncJournalDb::close() "/home/alfred/ocmyfiles/.csync_journal.db" 
06-16 13:29:27:563 0x1d231e0 No database Transaction to commit 
06-16 13:29:27:563 0x1d231e0 CSync run took  3253 
06-16 13:29:27:564 0x1d231e0  - client version 2.2.1  Qt 4.8.6 
06-16 13:29:27:565 0x1d231e0 -> SyncEngine finished without problem. 
06-16 13:29:27:565 0x1d231e0 Processing result list and logging took  0  Milliseconds. 
06-16 13:29:27:565 0x1d231e0 OO folder slotSyncFinished: result:  4 
06-16 13:29:27:565 0x1d231e0 Sync state changed for folder  "https://server/remote.php/webdav/" :  "Success" 
06-16 13:29:27:771 0x1d231e0 <===================================== sync finished for  "https://server/remote.php/webdav/" 
06-16 13:29:40:107 0x1d231e0 AccountState state change:  "Configuration error" -> "Signed out" 
06-16 13:29:40:110 0x1d231e0 Account "user@server" disconnected or paused, terminating or descheduling sync folders

**Comment by guruz** [comment] 2016-06-16 12:16
Is this a regression to a previous version?

```
06-16 13:29:27:552 0x1d231e0 void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply) "Unknown error" 302 0 
```

302 is a HTTP redirect. It looks like your server is not configured properly.

Please close this issue and try on https://owncloud.org/support/ if you agree. Thanks.

**Comment by e-alfred** [comment] 2016-06-16 12:50
I will have to tell my organization, as I am not administering the server. I will send them a link to this report.

**Closed** 2016-11-07 11:02 UTC
Labels: Needs info
