### ISSUE TITLE
Error code 404 when trying to share a folder before it has synced

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3527] opened 2015-07-31 10:02 UTC
### Steps to reproduce
1. Dump some big stuff into your client folders so there will be a sync in progress
2. Create a new folder called 111
3. Right click on the folder 111 and select Share with ownCloud

### Expected behaviour
There could be some sort of nice message to the user saying something like "Folder cannot be shared until it has synced to the server".

### Actual behaviour
The ownCloud Sharing dialog has "OCS API error code: 404"
![owncloud-try-to-share-before-sync](https://cloud.githubusercontent.com/assets/1535615/9005110/151b609c-379b-11e5-9756-b709b584de46.png)

### Server configuration

ownCloud version: 8.0

### Client configuration
Client version: 2.0.0-nightly 20150731 (build 5317)

Operating system: Windows7

OS language: English (US)

Installation path of client: Windows default

**Comment by rullzer** [comment] 2015-07-31 14:49
This is most likely a duplicate of #2775

**Comment by phil-davis** [comment] 2015-07-31 14:58
Yes, I agree - duplicate. I had read that one before but couldn't find it - I guess it has words in the title that come at it from a different perspective.

**Comment by rullzer** [comment] 2015-07-31 15:05
I'll close this issue then.

**Closed by rullzer** 2015-07-31 15:05 UTC
Labels: bug, Duplicate
