### ISSUE TITLE
[QA] Multiple scenarios failed in CI because of AUT crash

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9869] opened 2022-07-06 09:20 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The following scenarios are failing on the step `And user "userName" has set up a client with default settings`
```
Scenario: try to reshare a file/folder shared without share permission
Scenario: unshare a shared file and folder
Scenario: Share files/folders with special characters in their name
Scenario: try to share a file/folder with a user to whom the file has already been shared
Scenario: try to self share a file/folder
Scenario: search for users with minimum autocomplete characters
Scenario: share file and folder to a group
Scenario: sharee edits content of files shared by sharer

```
 failed in CI with error 
```
ERROR12:41:03            Script Error                          RuntimeError: startApplication() failed
```
This issue is referenced from https://github.com/owncloud/client/pull/9816#issuecomment-1164171671
>Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12351/6/1
>
>:boom: The GUI tests failed.
>
>GUI Logs: https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/index.html
>
><details>
>
>Server Logs: https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/serverlog.log
>
>Screenshots:
>- [change_collaborator_permissions_of_a_file_&_folder.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/change_collaborator_permissions_of_a_file_&_folder.png)
>- [share_a_file_with_many_users.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/share_a_file_with_many_users.png)
>- [sharing_a_folder_by_public_link_with_"Uploader"_role_and_check_if_file_can_be_downloaded.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/sharing_a_folder_by_public_link_with_"Uploader"_role_and_check_if_file_can_be_downloaded.png)
>- [sharing_of_a_file_by_public_link_and_deleting_the_link.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/sharing_of_a_file_by_public_link_and_deleting_the_link.png)
>- [sharing_of_a_file_by_public_link_with_password_and_changing_the_password.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/sharing_of_a_file_by_public_link_with_password_and_changing_the_password.png)
>- [simple_sharing_of_a_file_by_public_link_with_default_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/simple_sharing_of_a_file_by_public_link_with_default_expiration_date.png)
>- [simple_sharing_of_a_file_by_public_link_with_password_and_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/simple_sharing_of_a_file_by_public_link_with_password_and_expiration_date.png)
>- [simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png)
>- [simple_sharing_of_file_and_folder_by_public_link_with_password.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_with_password.png)
>- [simple_sharing_of_file_and_folder_by_public_link_without_password.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_without_password.png)
>- [simple_sharing_of_folder_by_public_link_with_different_roles.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/simple_sharing_of_folder_by_public_link_with_different_roles.png)
>- [unshare_a_reshared_file.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/unshare_a_reshared_file.png)
>- [unshare_a_shared_file_and_folder.png](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/screenshots/unshare_a_shared_file_and_folder.png)
>
></details>
>
>
>

The above-mentioned first two scenarios are failing on two builds, the log is provided below, while the rest of the scenarios are failing on the first build(first log) only.
1. [GUI log1](https://cache.owncloud.com/public/owncloud/client/12335/guiReportUpload/index.html)
2. [GUI lolg2](https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/index.html)

### Screenshots

![Screenshot from 2022-07-06 14-50-54](https://user-images.githubusercontent.com/66173400/177513762-363f7e41-fcc1-4937-85f3-89184bbc3380.png)

**Comment by TheOneRing** [comment] 2022-07-06 09:51
Probably caused by the issue fixed in https://github.com/owncloud/client/pull/9867

**Comment by sushmita56** [comment] 2022-07-07 04:02
On observing the following logs, I intuited that the AUT crash is the direct result of the failure of the first scenario. This means, that once a scenario gets failed in CI then that impacts the rest of the scenarios, as a result following scenarios failed with the error of `RuntimeError: startApplication() failed`.

https://cache.owncloud.com/public/owncloud/client/12368/guiReportUpload/index.html
https://cache.owncloud.com/public/owncloud/client/12351/guiReportUpload/index.html
https://cache.owncloud.com/public/owncloud/client/12335/guiReportUpload/index.html

**Comment by saw-jan** [comment] 2022-07-29 09:21
This might have probably been caused due to script error (screenshot file not found: _has been fixed_) in the after hook which prevents the cleanup script from running. I will try to reproduce and close this one that's the case.

**Closed** 2022-07-29 09:45 UTC
Labels: QA:team
