### ISSUE TITLE
[1.8.0] C++ Error

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#3003] opened 2015-03-23 10:22 UTC
Testing the 1.8.0 Client I receive the following error:

![client error](https://cloud.githubusercontent.com/assets/7264495/6777949/a35380f0-d14e-11e4-856a-57e186f7439e.png)

Let me know if you need the log files when I was testing.

@MorrisJobke @jturcotte

**Comment by ogoffart** [comment] 2015-03-23 12:54
looks like #2995

**Comment by jturcotte** [comment] 2015-03-23 13:00
Closing as duplicate of #2995

**Closed by jturcotte** 2015-03-23 13:00 UTC
Labels: blue-ticket
