### ISSUE TITLE
2.7.4 build failure at cmake generate stage: multiple cmake errors for Qt5::DBus not found

### ISSUE THREAD

**Issue by GvMariani** [owncloud/client#8335] opened 2020-12-29 19:58 UTC
Trying to build ownCloud client 2.7.4, to create an updated rpm package for the future release of Rosa Linux (Fresh R12), using cmake 3.19.2 and extra-cmake-modules 5.75.0.

### Expected behaviour
Successful build of ownCloud client.

### Actual behaviour
The build fails while doing the cmake generate step, in a number of places.
The majority of them(31) is related to tests, eg:
`CMake Error at /usr/share/ECM/modules/ECMAddTests.cmake:89 (add_executable):
  Target "OAuthTest" links to target "Qt5::DBus" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?`
Then there are 5 errors involving various client components: src/libsync/CMakeLists.txt, src/libsync/vfs/suffix/CMakeLists.txt, src/gui/CMakeLists.txt (2 times) and src/cmd/CMakeLists.txt.

Since cmake is finding the installed Qt5DBus library, something is missing elsewhere...
See the full log for all the gory details.

### Steps to reproduce
1. Install the sources
2. Run cmake (see the log for the command line used)
3. Watch the errors

### Server configuration
N/A

### Client configuration
Client version: 2.7.4.2934
Operating system: Linux - Rosa Linux Fresh R12 x86_64
OS language: english
Qt version used by client package (Linux only, see also Settings dialog): 5.15.2
Client package (From ownCloud or distro) (Linux only): distro
Installation path of client: /usr/bin

### Logs
Full log of a failed build: https://gist.github.com/GvMariani/ec1bd291b4fa4f861b4fcf3eb51f6150

**Comment by TheOneRing** [comment] 2021-01-04 11:55
Will be fixed with https://github.com/owncloud/client/issues/8335 but in general it looks like you are missing a dependency.

**Comment by GvMariani** [comment] 2021-01-04 13:19
> Will be fixed with #8335 but in general it looks like you are missing a dependency.
What one?
As I already wrote, Qt5DBus devel files (and all the other qt5 dev files AFAICT) are installed on the system...

**Comment by TheOneRing** [comment] 2021-01-13 14:26
Can you share your CMakeCache.txt

**Comment by GvMariani** [comment] 2021-01-13 18:02
Sure...
[CMakeCache.txt](https://github.com/owncloud/client/files/5810320/CMakeCache.txt)

**Comment by fmoc** [comment] 2021-03-12 15:45
I can kind of "reproduce" this issue on an Ubuntu 18.04 machine that:

1. has Qt 5.14.2 installed from the `beineri/opt-qt-5.14.2-bionic` PPA
2. has an up-to-date ECM installation (I used the Debian buster package, https://packages.debian.org/buster/extra-cmake-modules)

I activated the Qt 5.14 environment, configured the build and observed the same messages you get to see. I tracked down the issue a bit, and it seems like what happens is that CMake mixes the libraries from the system and the Qt 5.14 installation.

To exclude the "my machine" part, I tried to reproduce the issue in an Ubuntu 18.04 Docker container. I set it up as follows:

```sh
apt update
apt install -y cmake build-essential make git qt5-default zlib1g-dev libsqlite3-dev wget

wget https://ftp.fau.de/debian/pool/main/e/extra-cmake-modules/extra-cmake-modules_5.54.0-1_amd64.deb
echo "1b865365e46f5cc889b78af38af7c0f6be99cc07434e6ee1f0204d554eff3e58  extra-cmake-modules_5.54.0-1_amd64.deb" | sha256sum -c
dpkg -i extra-cmake-modules_5.54.0-1_amd64.deb
apt install -f -y

apt install -y software-properties-common
add-apt-repository ppa:beineri/opt-qt-5.14.2-bionic -y
apt update
apt install -y qt514-meta-full

git clone https://github.com/owncloud/client
cd client
mkdir build
cmake ..
```

Here, I noticed that the PPAs don't provide the Qt5 keychain lib. I think the issue on my other machine is that the CMake scripts mix both system and Qt PPA libraries. I can reproduce the messages by installing `qt5keychain-dev` in the container, then re-running CMake:

```sh
> apt install -y qt5keychain-dev
[...]
> cmake ..
-- Using Qt 5.14.2 (/opt/qt514/bin/qmake)
[...]
-- The following OPTIONAL packages have been found:

 * Qt5DBus
 * Qt5LinguistTools
 *  * SharedMimeInfo, A database of common MIME types, <http://freedesktop.org/wiki/Software/shared-mime-info/>

-- The following REQUIRED packages have been found:

 * ECM (required version >= 5.50.0), Extra CMake Modules., <https://projects.kde.org/projects/kdesupport/extra-cmake-modules>
 * Inotify
 * ZLIB
 * SQLite3 (required version >= 3.9.0)
 * Qt5Concurrent
 * Qt5Keychain
 * Qt5Gui (required version >= 5.14.2)
 * Qt5Widgets
 * Qt5Core
 * Qt5Test
 * Qt5Xml
 * Qt5Network
 * Qt5

[...]

-- Configuring done
CMake Error at src/libsync/CMakeLists.txt:79 (add_library):
  Target "libsync" links to target "Qt5::DBus" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at src/libsync/vfs/suffix/CMakeLists.txt:1 (add_library):
  Target "owncloud_vfs_suffix" links to target "Qt5::DBus" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

[... a lot more of these ...]

-- Generating done
-- Build files have been written to: /client/build
```

Looking at my `CMakeCache.txt`, I could confirm this in both the container and on the machine:

```sh
# Docker container
root@21ad021cb325:/client/build# cat CMakeCache.txt | grep -Ei 'qt5(keychain|dbus)_DIR'
Qt5DBus_DIR:PATH=/opt/qt514/lib/cmake/Qt5DBus
Qt5Keychain_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Keychain

# other machine
>  cat CMakeCache.txt | grep -Ei 'qt5(keychain|dbus)_DIR'
Qt5DBus_DIR:PATH=/opt/qt514/lib/cmake/Qt5DBus
Qt5Keychain_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5Keychain
```

This means that the issue isn't created by the DBus library, at least on my machine, but by using an incompatible Qt5Keychain library. 

_______

I had a look at your CMake log, and it also looks like CMake wrote a `Makefile`, but exited with a non-zero return code. It's the same in my setup. I can build, but it'll fail with:

```sh
[ 18%] Linking CXX shared library ../../bin/libowncloudsync.so
/usr/bin/ld: cannot find -lQt5::DBus
collect2: error: ld returned 1 exit status
src/libsync/CMakeFiles/libsync.dir/build.make:1084: recipe for target 'bin/libowncloudsync.so.2.8.0' failed
make[2]: *** [bin/libowncloudsync.so.2.8.0] Error 1
CMakeFiles/Makefile2:1164: recipe for target 'src/libsync/CMakeFiles/libsync.dir/all' failed
make[1]: *** [src/libsync/CMakeFiles/libsync.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I checked your `CMakeCache.txt` using the same `grep` command listed above:

```sh
> wget -qO- https://github.com/owncloud/client/files/5810320/CMakeCache.txt | grep -Ei 'qt5(keychain|dbus)_DIR'
Qt5DBus_DIR:PATH=/usr/lib64/cmake/Qt5DBus
Qt5Keychain_DIR:PATH=/usr/lib64/cmake/Qt5Keychain
```

There's nothing obviously wrong with those two entries. I guess it's alright. I have no experience with Rosa Linux (honestly, I just heard of it for the first time). Your logs and your issue description lack some information, so I can't even guess what's going on there. I suspect it's an issue with _some_ Qt5 library and CMake's Qt dependency lookup system. Please provide more information on how you install Qt 5, and maybe provide your RPM build script, otherwise I can't test it myself.

_______

As a reference, I set up an Ubuntu 20.04 Docker container to make sure manual building (i.e., without craft) works there:

```sh
apt update
apt install -y cmake build-essential make git qt5-default extra-cmake-modules zlib1g-dev libsqlite3-dev qt5keychain-dev
git clone https://github.com/owncloud/client
cd client
mkdir build
cmake ..
make -j"$(nproc --ignore=1)"
```

**Comment by GvMariani** [comment] 2021-03-13 11:27
> I have no experience with Rosa Linux (honestly, I just heard of it for the first time).
> 
Yes, when Mandriva collapsed, the most of users did go with Mageia or with the then-new OpenMandriva, so ROSA is really marginal everywhere but in Russia, where the company is rooted. I'm helping with packaging for it mainly for affect reason, because a couple of friends at the MIB (mib.pianetalinux.org) started to collaborate with it and we found them more responsive than the guys from Mageia...

Anyway: rpm-based distribution; the current LTS relase use rpm5 and rpm/urpmi, while the next one will use rpm4 and rpm/dnf.
The libraries for 32 bit go in /usr/lib and are named "lib$somestuff" and "lib$somestuff-devel", while the ones for x86_64 go in /usr/lib64 and are named lib64$somestuff" and "lib64$somestuff-devel. To avoid bothering with the name changes, we use pkgconfig to find the right one according to the build arch; when a library does not provide a .pc file, we add to the package a "virtual name", good for both arches: in the case of the above example, the virtual name provided by the lib[64]$somestuff-devel packages would be "$somestuff-devel".

> Please provide more information on how you install Qt 5
By using the rpm manager provided by the distribution (dnf)...
1) You need firstly to prepare the build system and the rpm support; do "(sudo) dnf install" for all the packages below:
- task-c-devel and task-c++-devel (they should take care of the bulk of the build system);
- cmake and extra-cmake-modules;
- rpm-build, rpm-helper, rpmlint (with its config files: rpmlint-distro-policy and rpmlint-rosa-policy) and the setup files (rpm-openmandriva-setup and rpm-openmandriva-setup-build);
- the various packages of macro to be used by rpmbuild: kde5-macros, qt5-macros, cmake-rpm-generators, devel-rpm-generators, order-rpm-generators and qml-rpm-generators.

2) The simpler way to install what is needed from Qt5/KF5 for owncloud-client is to do "(sudo) dnf builddep --spec" and passing it the file name of the spec file (owncloud-client.spec... see below): dnf will resolve all the needed dependencies and will happiliy download and install them.
Otherwise, you can use dnfdragora, a GUI interface to dnf: search for "qt5" and "kf5" and install what you want/need from the resulting list. This is useful to install dependencies when the specfile becomes outdated: the packagers always try to keep its requirements in sync with the sources, by looking at the release notes, by inspecting CMakeLists.txt, or whatever build files are used, and by looking at the build output, but sometimes something goes unnoticed and the "simple pass" above is not enough.

3) Create a directory "owncloud-client", copy into it the specfile and do "rpmbuild -ba $specfile": it should download the sources and then do install sources, patches... -> configure and make -> make install in a "faked" root system -> packaging and package linting...
You can also start every phase one at time to inspect the results; it's done by using "rpmbuild -bp" (prepare), "rpmbuild -bc" (compile), "rpmbuild -bi" (install in the fake root) and (obviously) "rpmbuild -ba" (all, packaging included).
This is the specfile I'm using (rename it to .spec):
[owncloud-client.spec.txt](https://github.com/owncloud/client/files/6134668/owncloud-client.spec.txt)
In reading the macros keep in mind that usually a %{stuff} macro represents a value (eg. %{_libdir} == "/usr/lib" or "usr/lib64" according to the build arch), while a %stuff macro is usually a statement to be executed. If you want to know what a %stuff macro does, you can use "rpm --eval %stuff" and it will tell you what the macro means....

BTW I did another try with the latest 2.7.6 release in a local VM, with the same results as before:
[Build2.7.6Failed.txt](https://github.com/owncloud/client/files/6134671/Build2.7.6Failed.txt)
[CMakeCache.txt](https://github.com/owncloud/client/files/6134672/CMakeCache.txt)

If you need some other infos, please ask...

**Comment by GvMariani** [comment] 2021-03-14 12:58
> This means that the issue isn't created by the DBus library, at least on my machine, but by using an incompatible Qt5Keychain library.
This finding made me going in the right direction...
I verified that indeed we are still using a very old 0.7.0 release of qt5keychain (from 2016!): packaging and installing the latest 0.12.0 release of that library solves the issue at hand and makes the build to proceed further (well, it now fails with some "error: template with C linkage" while processing src/gui/libcloudproviders/libcloudproviders.cpp, but this is another bug...).

To avoid it forever, then, you will only need to instruct cmake to request a recent enough release of qt5keychain (in src/gui/CMakelists.txt file, I guess...); somethings as "find_package(Qt5Keychain $version_you_choose REQUIRED)" should be enough....
I don't know what "a recent enough release of qt5keychain" should be, though.

**Comment by fmoc** [comment] 2021-04-13 16:25
> I don't know what "a recent enough release of qt5keychain" should be

The issue appears to be a mix of a Qt5Keychain library built against a different Qt base with your main Qt base.

In any case, I'm not sure how to help you. ownCloud is working on an AppImage, which users of Rosa Linux should be able to use as well. If you have concrete questions, I'll try to answer them, though.

**Closed** 2021-09-10 12:47 UTC
Labels: Linux
