### ISSUE TITLE
Discover path progress font too little

### ISSUE THREAD

**Issue by MarceloSaied** [owncloud/client#4050] opened 2015-10-31 12:56 UTC
### Expected behavior
Discover path progress font too little. is very difficult to read. and also , personally, I prefer to have a full path, so I can see the progress , and to see the progress

### Actual behavior
Discover path progress font too little.

### Steps to reproduce
1. at discover of files, at the main tab at settings
2. 
3. 

### Server configuration
Operating system: Winsows 2012

Web server: apache (xampp)

Database:Mysql 5.6.16

PHP version: 5.5.11

ownCloud version: ownCloud 7.0.2 (stable) 

Storage backend: local  on server

### Client configuration
Client version:Version 2.0.2 (build 5569). 

Operating system:win 7

OS language:eng

Installation path of client:
c:\Program Files (x86)\ownCloud\
### Logs
not relevant

**Comment by LukeOwncloud** [comment] 2015-11-14 12:59
Seems to be a duplicate of https://github.com/owncloud/client/issues/2519.

**Comment by deftoner** [comment] 2015-12-03 23:40
I had this same issue for month!. I have 2 Owncloud servers. One 7 on win 2008 server and one on ubuntu on lastest 8. The problem is on the clients of course. I Uninstaled it and reinstaled. Same problem

I guess some registry entry or something. Start happening from and update almost 8 months ago.

![image-2015-12-03-1449185958](https://cloud.githubusercontent.com/assets/5200414/11577650/59b647a8-99ed-11e5-9e06-e928f58acf94.png)

**Comment by guruz** [comment] 2016-01-11 11:36
Dup of https://github.com/owncloud/client/issues/2519

**Closed by guruz** 2016-01-11 11:36 UTC
Labels: Design & UX
