### ISSUE TITLE
[Client/XP] Crash when syncing folders "failed to create dibsection"

### ISSUE THREAD

**Issue by StephaneDupont** [owncloud/client#2648] opened 2014-12-27 16:00 UTC
Hello,

I've tried to sync my owncloud installation on a XP laptop, and even if I try to sync only a small folder, the client crashes.

Here's the log file when I tried to sync a folder with 5 files in it:

...
12-27 16:14:38:140 0x5da6128 csync_reconcile: Reconciliation for remote replica took 0.00 seconds visiting 5 files.
12-27 16:14:38:140 0x5da6128 csync_statedb_close: sqlite3_close=0
12-27 16:14:38:140 0x5da6128 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:"
12-27 16:14:38:140 0x5da6128 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:"
12-27 16:14:38:140 0x5da6128 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:"
12-27 16:14:38:140 0x5da6128 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:"
12-27 16:14:38:140 0x5da6128 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:SYNC:"
12-27 16:14:38:156 0x5da6128 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post treewalk" and starting new transaction
12-27 16:14:38:156 0x5da6128 syncjournaldb.cpp:1157 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post stale entry removal" and starting new transaction
12-27 16:14:38:156 0x5da6128 owncloudpropagator.cpp:315 Using QNAM/HTTP parallel code path
12-27 16:14:38:156 0x5da6128 folder.cpp:823     * csync thread started
12-27 16:14:38:156 0x5da6128 socketapi.cpp:275 Not sending UPDATE_VIEW for "Home" because status() is 3
12-27 16:14:38:906 0x5da6128 owncloudgui.cpp:264 Folder in overallStatus Message:  Mirall::Folder(0x668c730)  with name  "Home"
12-27 16:14:38:906 0x5da6128 owncloudgui.cpp:180 Sync state changed for folder  "Home" :  "Sync Running"
12-27 16:14:38:906 0x5da6128 :0 QWindowsXPStylePrivate::buffer(w,h), failed to create dibsection ()

No problem on my desktop Windows Seven computer.

I think it might be the same issue than this closed one: https://github.com/owncloud/client/issues/2541 (I didn't find how to reopen it, so I opened a new one, but let me know if I must move this one to the old one)

**Comment by danimo** [comment] 2015-01-19 16:21
https://bugreports.qt.io/browse/QTBUG-18057 related?

**Comment by guruz** [comment] 2015-01-19 16:26
@danimo yes that's the reason I was asking for the video memory. But I doubt this is the real cause.

**Comment by guruz** [comment] 2015-01-19 16:26
@danimo won't Qt 5.4 possibly select a different rendering backend or so? Which could influence this?

**Comment by ogoffart** [comment] 2015-01-22 09:57
What is the memory usage of the application?  Maybe we have another leak on XP or something?

**Comment by StephaneDupont** [comment] 2015-01-22 09:58
I don't remember exactly, but it was small, something like 30Mo.

**Comment by dahan1999** [comment] 2015-01-22 10:39
My mem usage is bout 50M. Not high. I start a remote debug and try to locate the bug but it is very strange that there is only one item in the call stack of the crash: Qt5Widgets.dll. I suspect that this is a Qt5 bug and I am going to test with Qt5 of different versions.

**Comment by dahan1999** [comment] 2015-01-24 21:46
I debug the issue for some days and found an interesting thing:
the application only crashes when "Account" tab is displayed on the main GUI and files to be synced in the explorer are displayed. I suspect that some pointer are deleted by accident but are referenced later that results in the crash. Still working on it.

**Comment by dahan1999** [comment] 2015-01-25 15:43
I did a test that commented out the following lines in settingsdialog.cpp and it seems that the crash does not happen.
/*  
  connect( ProgressDispatcher::instance(), SIGNAL(progressInfo(QString, Progress::Info)),
             _accountSettings, SLOT(slotSetProgress(QString, Progress::Info)) );
*/

**Comment by k3cco90** [comment] 2015-02-03 13:53
Hi dahan,
i didn't understand how to solve the problem. How can I add these 4 lines? In which file? Can you please be more specific? thank you!

**Comment by dahan1999** [comment] 2015-02-03 14:07
Hello k3cco90,

The file is mirall/src/mirall/AccountSettings.cpp. Here is the function that I modified(the 4 lines that I added are almost at the end of the function):

void AccountSettings::slotSetProgress(const QString& folder, const Progress::Info &progress )
{
    QStandardItem *item = itemForFolder( folder );
    if( !item ) return;

    // switch on extra space.
    item->setData( QVariant(true), FolderStatusDelegate::AddProgressSpace );

    if (!progress._currentDiscoveredFolder.isEmpty()) {
        item->setData( tr("Discovering '%1'").arg(progress._currentDiscoveredFolder) , FolderStatusDelegate::SyncProgressItemString );
        return;
    }

    if(!progress._lastCompletedItem.isEmpty()
            && Progress::isWarningKind(progress._lastCompletedItem._status)) {
        int warnCount = item->data(FolderStatusDelegate::WarningCount).toInt();
        warnCount++;
        item->setData( QVariant(warnCount), FolderStatusDelegate::WarningCount );
    }

    // find the single item to display:  This is going to be the bigger item, or the last completed
    // item if no items are in progress.
    SyncFileItem curItem = progress._lastCompletedItem;
    qint64 curItemProgress = -1; // -1 means finished
    quint64 biggerItemSize = -1;
    foreach(const Progress::Info::ProgressItem &citm, progress._currentItems) {
        if (curItemProgress == -1 || (Progress::isSizeDependent(citm._item._instruction)
                                      && biggerItemSize < citm._item._size)) {
            curItemProgress = citm._completedSize;
            curItem = citm._item;
            biggerItemSize = citm._item._size;
        }
    }
    if (curItemProgress == -1) {
        curItemProgress = curItem._size;
    }

    QString itemFileName = shortenFilename(folder, curItem._file);
    QString kindString = Progress::asActionString(curItem);



    QString fileProgressString;
    if (Progress::isSizeDependent(curItem._instruction)) {
        QString s1 = Utility::octetsToString( curItemProgress );
        QString s2 = Utility::octetsToString( curItem._size );
        quint64 estimatedBw = progress.getFileEstimate(curItem).getEstimatedBandwidth();
        if (estimatedBw) {
            //: Example text: "uploading foobar.png (1MB of 2MB) time left 2 minutes at a rate of 24Kb/s"
            fileProgressString = tr("%1 %2 (%3 of %4) %5 left at a rate of %6/s")
                .arg(kindString, itemFileName, s1, s2,
                    Utility::timeToDescriptiveString(progress.getFileEstimate(curItem).getEtaEstimate(), 3, " ", true),
                    Utility::octetsToString(estimatedBw) );
        } else {
            //: Example text: "uploading foobar.png (2MB of 2MB)"
            fileProgressString = tr("%1 %2 (%3 of %4)") .arg(kindString, itemFileName, s1, s2);
        }
    } else if (!kindString.isEmpty()) {
        //: Example text: "uploading foobar.png"
        fileProgressString = tr("%1 %2").arg(kindString, itemFileName);
    }
    item->setData( fileProgressString,FolderStatusDelegate::SyncProgressItemString);

    // overall progress
    quint64 completedSize = progress.completedSize();
    quint64 currentFile =  progress._completedFileCount + progress._currentItems.count();
    QString overallSyncString;
    if (progress._totalSize > 0) {
        QString s1 = Utility::octetsToString( completedSize );
        QString s2 = Utility::octetsToString( progress._totalSize );
        overallSyncString = tr("%1 of %2, file %3 of %4\nTotal time left %5")
            .arg(s1, s2)
            .arg(currentFile).arg(progress._totalFileCount)
            .arg( Utility::timeToDescriptiveString(progress.totalEstimate().getEtaEstimate(), 3, " ", true) );
    } else if (progress._totalFileCount > 0) {
        // Don't attemt to estimate the time left if there is no kb to transfer.
        overallSyncString = tr("file %1 of %2") .arg(currentFile).arg(progress._totalFileCount);
    }

    item->setData( overallSyncString, FolderStatusDelegate::SyncProgressOverallString );

    int overallPercent = 0;
    if( progress._totalFileCount > 0 ) {
        // Add one 'byte' for each files so the percentage is moving when deleting or renaming files
        overallPercent = qRound(double(completedSize + progress._completedFileCount)/double(progress._totalSize + progress._totalFileCount) * 100.0);
    }
    if (overallPercent < 0)
	overallPercent = 0;
    if (overallPercent > 100)
	overallPercent = 100;
    item->setData( overallPercent, FolderStatusDelegate::SyncProgressOverallPercent);
}

**Comment by guruz** [comment] 2015-02-05 16:04
I pushed a commit that does not do the progress update when the dialog is not visible.

Do you want to try a 1.8 nightly build?
http://download.owncloud.com/desktop/daily/owncloud-1.8.0.4688-nightly20150205-setup.exe

**Comment by k3cco90** [comment] 2015-02-05 16:18
Really thank you! I will try tomorrow!







Da: Markus Goetz
Data invio: ‎giovedì‎ ‎5‎ ‎febbraio‎ ‎2015 ‎17‎:‎04
A: owncloud/client
Cc: k3cco90





I pushed a commit that does not do the progress update when the dialog is not visible.

Do you want to try a 1.8 nightly build?
http://download.owncloud.com/desktop/daily/owncloud-1.8.0.4688-nightly20150205-setup.exe

**Comment by ckamm** [comment] 2015-02-12 09:14
@dahan1999 I applied a variant of your change.

@k3cco90 @nekoal Could you test again with tomorrow's daily build? (http://download.owncloud.com/desktop/daily/ >=20150213)

**Comment by dahan1999** [comment] 2015-02-12 14:00
@k3cco90 sorry for late respond. @ckamm I will test it tomorrow.

**Comment by k3cco90** [comment] 2015-02-12 16:45
I tried the old version, it was OK! I will try this tomorrow if I can.
Thank you!
 Il 12/feb/2015 10:14 "ckamm" <notifications@github.com> ha scritto:

**Comment by nekoal** [comment] 2015-02-13 07:49
1.8.0-nightly20150213 (4715) Sorry, I can't say it solved. On Windows XP client crashes when AddFolder dialog shown (folder tree control?). Now fails msvcr120.dll
 Two times I couldn't add folder. Third time new folder added then crashed
Unknown software exception (0xe06d7363) in application on address 0x7c812afb. After client new start works ok until AddFolder dialog shown.  I can't reproduce error on Win 7.

Text shown by tray icon on Win 7 and Win XP for paused folders contains %! and in logs more records about missing arguments.
![oc_tray_text](https://cloud.githubusercontent.com/assets/10899904/6183391/9a7d16f8-b38f-11e4-93ee-4d2f78ec8bf3.png)

**Comment by dahan1999** [comment] 2015-02-13 13:49
@nekoal can you describe your steps to reproduce the crash?

**Comment by dahan1999** [comment] 2015-02-13 14:40
@ckamm I tested and the crash did not occur. nekoal mentioned another crash but I suspect that the crash has nothing to do with this one.

**Comment by nekoal** [comment] 2015-02-13 14:51
Sorry, I was wrong. It's separate issue. Same crash occurs in others applications then I tried uninstall client and install without shell integration. On Win 7 shell integration already was disabled 'cause explorer crash.
Without shell integration AddFolder don't show any errors and syncrun started successfully. Pause/resume test also passed.

**Comment by danimo** [comment] 2015-02-17 13:25
This is done then?

**Comment by lmaestro** [comment] 2015-02-18 09:46
If the crash did not occur as @dahan1999 said I close this issue.
And if anyone is able to reproduce it please reopen it, thx.

**Closed by lmaestro** 2015-02-18 09:46 UTC
Labels: bug, Needs info, ReadyToTest
