### ISSUE TITLE
When user changed password in web, client still can use

### ISSUE THREAD

**Issue by f4111222** [owncloud/client#4371] opened 2016-01-19 10:05 UTC
I'm running Owncloud client v2.1.0. I found when I change my password from web, I still can use client to upload/download/sync files. It seems a little strange. The user should be logged out and ask for re-typing their new password for checking their auth?

**Comment by LukasReschke** [comment] 2016-01-19 10:07
Kinda a dupe of https://github.com/owncloud/core/pull/21592

**Closed by LukasReschke** 2016-01-19 10:07 UTC
