### ISSUE TITLE
Subdirectories of directories moved into a synced directory sometimes do not sync on 2.5.0

### ISSUE THREAD

**Issue by cdhowie** [owncloud/client#6804] opened 2018-10-10 11:16 UTC
### Expected behaviour
When moving a directory with subdirectories into a directory that is being synced with ownCloud, all (unignored) files in the tree are uploaded to the server.

### Actual behaviour
When moving a directory with subdirectories into a directory that is being synced with ownCloud, sometimes the subdirectories do not get synced to the server.  No error is given and the files are not listed as ignored; it's as though the client does not see them at all.

The subdirectories themselves appear on the server, but are empty.

"Force sync now" does not resolve the problem. Restarting the client _does_ resolve the problem, and is an effective (though tedious and annoying) workaround.

### Steps to reproduce
1. Move a directory containing subdirectories with files into the directory structure of a directory being synced with ownCloud.
2. Somewhat randomly (my tests show between 25%-50% of the time) files in at least one subdirectory do not sync until the client is restarted.  If a specific directory exhibits this issue, its parent directory can be moved out of the synced directory tree and back into the tree and the problem will recur with that directory 100% of the time.

### Server configuration
Operating system: Debian Stretch

Web server: nginx + php7.0-fpm

Database: PostgreSQL 9.6.10

PHP version: 7.0

ownCloud version: 10.0.10

Storage backend (external storage): N/A

### Client configuration
Client version: 2.5.0

Operating system: Windows 10

OS language: US English

Qt version used by client package (Linux only, see also Settings dialog): N/A

Client package (From ownCloud or distro) (Linux only): N/A

Installation path of client: `C:\Program Files (x86)\ownCloud`

### Logs

1. Client logfile: I have captured the relevant log entries but, as they contain details about my private installation, I do not want to disclose them on a public issue tracker.  Due to the size of the snippet, it would take some effort to sanitize them.  If the log entries are required, I would prefer to disclose them privately.
2. Web server error log: No errors reported
3. Server logfile: No new entries in the log during the broken sync operation

**Comment by ogoffart** [comment] 2018-10-11 10:28
Thanks for the bug report.  This is going to be fixed with PR #6806 .
It is caused by the thanges to rely more on the file system watcher in 2.5.0.

Note that there is a one hour timeout for which we would anyway do a full discovery.

You can work around the problem by decreasing the timeout using the `OWNCLOUD_FULL_LOCAL_DISCOVERY_INTERVAL` environement variable, or the `fullLocalDiscoveryInterval` config entry in the fonfig file  (value in ms)

If you set this value to 1ms, this means the full local discovery will be done for every sync

**Comment by cdhowie** [comment] 2018-10-11 20:41
Thanks for the quick turnaround + workaround.  I fully expected this to be one of those issues that's difficult to reproduce and I'd have to come up with a more reliable list of steps to reproduce it.

**Comment by jnweiger** [comment] 2018-10-17 13:30
tested as part of #6808 -- Result: GOOD.

**Closed** 2018-10-17 13:59 UTC
Labels: ReadyToTest, bug

**Comment by guruz** [comment] 2018-10-25 11:04
@cdhowie Feel free to test this with a current daily build
https://download.owncloud.com/desktop/daily/ownCloud-2.5.1.10890.10790-daily20181024.en-US.msi
