### ISSUE TITLE
Expand symbol should not be displayed (no sub folder)

### ISSUE THREAD

**Issue by ldmpub** [owncloud/client#6209] opened 2017-12-03 11:12 UTC
### Expected behaviour
Don't display ">" symbol in front of a folder when it has no sub-folders.

### Actual behaviour
See screen video (unzip then open with a Flash Player).

### Note
Once Owncloud realized that there are no subfolder (ie user tried to expand without result) if user closes the window and reopens it: the problem is not present anymore (Owncloud memories the folder "state" ... until next quit and restart of the client app).

### Configuration
Operating system: Windows 10
OwnCloud desktop client: 2.3.4

**Comment by ldmpub** [comment] 2017-12-03 11:12
The zipped video [Expand_symbol_should_not_be_displayed.zip](https://github.com/owncloud/client/files/1524684/Expand_symbol_should_not_be_displayed.zip)

**Comment by ogoffart** [comment] 2017-12-04 06:59
The problem here is that we would need to do lots of network requests (one PROPFIND on each folder) to know if there are sufolder.

It would be nice if there was a webdav property that tells weather a folder has sub-folders. (@DeepDiver1975 : is there?)

**Comment by guruz** [comment] 2017-12-04 11:40
(Also @PVince81 )

**Comment by ogoffart** [comment] 2017-12-05 11:02
Created server issue https://github.com/owncloud/core/issues/29758

**Comment by ogoffart** [comment] 2017-12-05 11:10
Actually, duplicate of https://github.com/owncloud/client/issues/4232

**Closed by ogoffart** 2017-12-05 11:10 UTC
Labels: Design & UX
