### ISSUE TITLE
[Qt 5.5.0 Arch Linux] segfault after resuming from hibernation

### ISSUE THREAD

**Issue by j0hannes** [owncloud/client#3532] opened 2015-08-01 11:59 UTC
Hi!

Recently, I was missing the owncloud client after resuming from hibernation mode. Looking at dmesg I found:

> owncloud[8791]: segfault at 8 ip 00007f516933ee70 sp 00007ffc12aa8c58 error 4 in libQt5Gui.so.5.5.0[7f516920c000+546000]

I'm running 1.8.4 (from the repository) on 4.1.2-2-ARCH.

**Comment by guruz** [comment] 2015-08-03 08:44
Have you looked if this exists already in https://bugreports.qt.io/ ?

**Comment by j0hannes** [comment] 2015-08-04 06:42
I searched the owncloud client bugtracker for an error message like that. I can't find anything at the Qt bugtracker either.

**Comment by dragotin** [comment] 2015-09-01 10:33
Most probably a dupe of #3672

**Closed by dragotin** 2015-09-01 10:33 UTC
Labels: bug, Platform Specific
