### ISSUE TITLE
No Desktop Client updates for CentOS 6?

### ISSUE THREAD

**Issue by adrianvg** [owncloud/client#4365] opened 2016-01-18 07:04 UTC
@jnweigner:
OC Desktop Client for CentOS 6 isn't updating from the repo.

Upon check in the repo folder on
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/CentOS_6/
in both the 32 and 64b-folders, I see only the older 2.0.2 client.

Did somebody forget about us CentOS 6-users? 8-)

**Comment by wa7qzr** [comment] 2016-01-28 04:05
I have this same issue. It's annoying.

**Comment by adrianvg** [comment] 2016-01-28 07:20
New rpm-packages, nice!

But... Instead we now have som kind of dependency problems?
The machine I'm running this on is a plain-vanilla CentOS 6.7 x64.
What gives?

```
root@mach219 ~/ [0]# yum update
Loaded plugins: fastestmirror, priorities, refresh-packagekit, security
Setting up Update Process
Loading mirror speeds from cached hostfile
 * base: ftp.lysator.liu.se
 * extras: ftp.lysator.liu.se
 * updates: ftp.lysator.liu.se
2 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package libowncloudsync0.x86_64 0:2.0.2-11.1 will be updated
---> Package libowncloudsync0.x86_64 0:2.1.0-7.1 will be an update
---> Package owncloud-client.x86_64 0:2.0.2-11.1 will be obsoleted
---> Package owncloud-client.x86_64 0:2.1.0-7.1 will be obsoleting
--> Processing Dependency: opt-qt5-qtbase-gui for package: owncloud-client-2.1.0-7.1.x86_64
--> Processing Dependency: opt-qt5-qtbase for package: owncloud-client-2.1.0-7.1.x86_64
--> Processing Dependency: opt-qt5-qtwebkit for package: owncloud-client-2.1.0-7.1.x86_64
---> Package owncloud-client-l10n.x86_64 0:2.0.2-11.1 will be updated
---> Package owncloud-client-l10n.x86_64 0:2.1.0-7.1 will be an update
--> Finished Dependency Resolution
Error: Package: owncloud-client-2.1.0-7.1.x86_64 (isv_ownCloud_desktop)
           Requires: opt-qt5-qtbase
Error: Package: owncloud-client-2.1.0-7.1.x86_64 (isv_ownCloud_desktop)
           Requires: opt-qt5-qtwebkit
Error: Package: owncloud-client-2.1.0-7.1.x86_64 (isv_ownCloud_desktop)
           Requires: opt-qt5-qtbase-gui
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
root@mach219 ~/ [0]#
```

**Comment by wa7qzr** [comment] 2016-01-28 23:04
The problem is owncloud expects the qt5 packages to be in /opt (opt-qt5-qtbase,opt-qt5-qtwebkit,   opt-qt5-qtbase-gui), whilst Centos 6 qt5 from epel installs in /usr.

**Comment by adrianvg** [comment] 2016-01-29 06:25
So, how to workaround?
Uninstalling the qt5-package and hope yum update is able to figure the dependency-stuff out when updating the Owncloud-client?

**Comment by dragotin** [comment] 2016-01-29 09:40
dupe of #4400

**Closed by dragotin** 2016-01-29 09:40 UTC
Labels: packaging

**Comment by jnweiger** [comment] 2016-01-29 18:05
The first batch of CentOS_6 packages was bad. (requesting some qt5 deps, which we did not intend).
Todays reroll should be fine. Look for build release  owncloud-client-2.1.0-11.1
