### ISSUE TITLE
desktop share function: Nginx redirect issue.

### ISSUE THREAD

**Issue by esquad18** [owncloud/client#2881] opened 2015-02-23 10:53 UTC
hi,

a problem with desktop 1.8 client and the "share with owncloud" function : it does'nt work when owncloud server is used with a URL redirection ( nginx redirect to the owncloud server 7.04 ).
it displays after right clic on share : 
error code ocs api : 0  or error code ocs api : 404

thx

**Comment by lmaestro** [comment] 2015-02-23 14:21
I can reproduce it using a server with nginx redirect if you try to share a file which is inside a folder with special characters . (Ex: OC-local-folder/ $%&Ç¨^_/photo1.jpg )
@esquad18 Can you add your steps to reproduce?
https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

**Comment by danimo** [comment] 2015-02-25 14:05
By "redirection", do you mean "reverse proxy"?

**Comment by esquad18** [comment] 2015-02-25 16:59
yes, reverse proxy listen port 443 and redirect to the server owncloud url location

**Comment by ckamm** [comment] 2015-02-26 07:35
@esquad18 I have attempted to reproduce it with a simple reverse proxy setup and it works for me. Maybe the problem is related to your nginx config, could you share it? Does it fail for all files?

@lmaestro I can reproduce your issue with the special characters folder -- but it's unrelated to using a reverse proxy. I'll make a different issue for that.

**Comment by dragotin** [comment] 2015-02-26 14:27
Verified that folder names that contain "&" now works with the current 1.8 branch. @esquad18 pls check with  beta2 once it's out.

Closing this as a duplicate of #2892

**Closed by dragotin** 2015-02-26 14:27 UTC
Labels: bug, Needs info
