### ISSUE TITLE
[Linux] Hitting enter key appends an additional character in login dialog 

### ISSUE THREAD

**Issue by onrubia** [owncloud/client#5943] opened 2017-08-07 09:30 UTC
### Expected behaviour
The client should log in when I introduce the password.

### Actual behaviour
If I write in the textbox, the password is always incorrect (Enter introduces a new character). If I write the password somewhere, I copy&paste it, and then I click Ok, then it works.

### Steps to reproduce
1. I boot my computer.
2. The log in dialogue appears:
![imagen](https://user-images.githubusercontent.com/26143307/29019534-172851e2-7b5f-11e7-9b58-756a37b692eb.png)

### Server configuration
Operating system: ubuntu server 12.04

Web server: Apache/2.2.22

Database: Ver 14.14 Distrib 5.5.54

PHP version: PHP 5.4.45-4

ownCloud version: 8.1.9 

Storage backend (external storage): no.

### Client configuration
Client version: 2.3.2

Operating system: ubuntu 17.04

OS language: spanish

Qt version used by client package (Linux only, see also Settings dialog): RevisiÃ³n Git 820899 en Jul 11 2017, 14:46:13 compilada usando Qt 5.7.1, OpenSSL 1.0.2g 1 Mar 2016

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

https://pastebin.com/WRQtYKX5

2. Web server error log : no errors at the moment of the test, errors of the day, this is from yesterday
[Sun Aug 06 07:50:39 2017] [warn] RSA server certificate CommonName (CN) `ubuntu' does NOT match server name!?
[Sun Aug 06 07:50:39 2017] [notice] Apache/2.2.22 (Ubuntu) PHP/5.4.45-4+deprecated+dontuse+deb.sury.org~precise+1 mod_ssl/2.2.22 OpenSSL/1.0.1 configured -- resuming normal operations

3. Server logfile: ownCloud log (data/owncloud.log):
https://pastebin.com/gpiDfBz2

**Comment by guruz** [comment] 2017-08-08 06:43
Could be an issue related to window manager / desktop environment

**Comment by onrubia** [comment] 2017-08-08 08:03
Even if I only write the password and click ok, it still doesn't work, it is not only the issue with Enter.

**Comment by ogoffart** [comment] 2018-11-29 16:54
That would probably be a Qt problem.
This is not something I can reproduce.
Probably not a bug in the client.
I'm closing this bug report because this is probably not a bug in the client.

**Closed by ogoffart** 2018-11-29 16:54 UTC
Labels: Design & UX
