### ISSUE TITLE
[1.7.0] windows installer runs client as admin user

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2508] opened 2014-11-17 17:44 UTC
If the installer runs with an unprevilidged user, and the user decides let the installer start owncloud.exe, it is started as the admin user rather than the unprivileged user. For the user, that looks like as if the client does not sync anything any more. 

Restarting fixes that of course.

**Comment by dryo** [comment] 2015-03-06 15:35
Isn't this a duplicate of #2568?

**Comment by danimo** [comment] 2015-03-06 15:36
Indeed.

**Closed by danimo** 2015-03-06 15:36 UTC
