### ISSUE TITLE
Client crashes Fedora 22 Plasma 5

### ISSUE THREAD

**Issue by shieldfire** [owncloud/client#3746] opened 2015-09-04 05:09 UTC
### Expected behaviour
Sync client should start

### Actual behaviour
In KDE 5 Plasma, when starting the OwnCloud sync client I get a message
to the effect that the application crashed and do I wish to restart it.
When opting to restart I get the same behaviour.

### Steps to reproduce
Start sync client under Plasma 5/ Fedora 22

### Server configuration
Operating system: Debian 8.1

Web server:  Apache/2.4.10 (Debian) 

Database: MySQL

PHP version: 5.6.9-0+deb8u1 

ownCloud version: ownCloud 8.1.0 (stable) 

Storage backend: MySQL

### Client configuration
Client version: 
2.0.2-git
Operating system: Fedora 22

OS language: English

Installation path of client:/usr/bin/owncloud

### Logs

tail -f /var/log/messages 

produces

Sep  3 10:37:56 localhost /usr/libexec/gdm-x-session: QXcbConnection:
XCB error: 3 (BadWindow), sequence: 4934, resource id: 67108868, major
code: 18 (ChangeProperty), minor code: 0
Sep  3 10:37:56 localhost audit: <audit-1701> auid=1001 uid=1001
gid=1001 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0
-s0:c0.c1023 pid=4063 comm="owncloud" exe="/usr/bin/owncloud" sig=11
Sep  3 10:37:56 localhost kernel: owncloud[4063]: segfault at 0 ip     
      (null) sp 00007ffdbf33bfc8 error 14 in owncloud[400000+1ba000]
Sep  3 10:37:56 localhost abrt-hook-ccpp: Failed to create
core_backtrace: dwfl_getthread_frames failed: No DWARF information
found
Sep  3 10:37:56 localhost gdb: detected unhandled Python exception
Sep  3 10:37:57 localhost abrt-server: Deleting problem directory ccpp
-2015-09-03-10:37:56-4063 (dup of ccpp-2015-09-02-17:42:59-3393)

Crash occurs before connecting to server (?)

**Comment by guruz** [comment] 2015-09-04 07:19
Can you check if this is a duplicate of https://github.com/owncloud/client/issues/3672 ?

**Comment by ckamm** [comment] 2015-09-04 07:24
This is very likely to be a duplicate. Please try the new kf5-frameworkintegration package when it becomes available (https://bugzilla.redhat.com/show_bug.cgi?id=1255902) and don't hesitate to reopen the issue should the bug still exist afterwards.

**Closed by ckamm** 2015-09-04 07:24 UTC
Labels: Needs info
