### ISSUE TITLE
cant login in on windows client

### ISSUE THREAD

**Issue by acidicrebel** [owncloud/client#6030] opened 2017-09-13 12:03 UTC
![screenshot_4](https://user-images.githubusercontent.com/31736892/30422173-6b083e46-993f-11e7-8db4-7cb5f3f6c197.png)

### Expected behaviour
you should be able to login

### Actual behaviour
when login in on the client it says (im 100% sure its the right password and stuff)
connection closed
### Steps to reproduce
1. launch client (windows)
2. login 
3. there is the problem

### Server configuration
Operating system: linux

Web server:  im doing this for my boss idk

Database: mysql 

PHP version: 5.6

ownCloud version: latest

### Client configuration
Client version: 2.3.3

Operating system: windows 10

OS language: english/dutch

Installation path of client: "C:\Program Files (x86)\ownCloud\owncloud.exe"

### Logs

OCC::OwncloudSetupWizard::slotConnectToOCUrl: Connect to url:  "http://theurlofthewebsite/owncloud"
09-13 16:53:07:286 11316 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "Trying to connect to ownCloud at "http://theurlofthewebsite/owncloud"..."
09-13 16:53:07:286 11316 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "http://theurlofthewebsite/owncloud"" + "/" "OCC::OwncloudSetupWizard"
09-13 16:53:12:974 11316 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(RemoteHostClosedError) "Connection closed" QVariant(Invalid)
09-13 16:53:12:976 11316 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""

**Comment by glannes31** [comment] 2017-09-13 12:47
Hello, please fill the template issue . It's more easy to the dev for helping you.

**Comment by acidicrebel** [comment] 2017-09-13 14:58
@glannes31 i did it

**Comment by SamuAlfageme** [comment] 2017-09-14 07:00
@acidicrebel Make sure that your ownCloud client is not behind any system proxy or firewall that does not allow to receive external connections. Also, could you ask your ownCloud admin for the server access logs? there might be some more clues about your requests in there. Thanks for reporting!

**Comment by acidicrebel** [comment] 2017-09-14 08:07
these are the server logs and we already turned off firewall and we already looked into proxy that isnt the problem

**Comment by SamuAlfageme** [comment] 2017-09-14 08:18
@acidicrebel the ones in https://github.com/owncloud/client/issues/6030#issue-257355522 are client logs. Server should contain more info about the requests hitting it. 

Can you manually set-up a proxy to act as an interceptor of your requests (e.g. [mitmproxy](https://mitmproxy.org/)) and send us the contents of the failed `PROPFIND`? It'll look like this: https://asciinema.org/a/1hSDt87ylHJTOAkCN7n4SNFbl

**Comment by acidicrebel** [comment] 2017-09-14 08:57
like i sayed it hasnt to do anything with the proxxy becaus we are running already diffrent websites so there is no proxy problem or firewall problem like i sayed before @SamuAlfageme

**Comment by acidicrebel** [comment] 2017-09-14 08:59
and the cloud is working we can login on chrome to it but not with the client so it isnt the proxy or firewall....

**Comment by acidicrebel** [comment] 2017-09-14 09:09
look this is what we all get in the client even if we turn down proxy or turn the firewall off it still says the same stuff and there isnt a problem with the server becaus we already are running a lot like radio station www.teamfm.nl www.audistreamen.nl and www.uniekhost.nl thats already what we are hosting so there isnt a problem in the server its a pure owncloud problem or php setting so pleas dont say againg its the proxy or firewall
![screenshot_4](https://user-images.githubusercontent.com/31736892/30421453-181d0baa-993d-11e7-91da-b1ef41f57b82.png)

**Comment by SamuAlfageme** [comment] 2017-09-14 09:15
@acidicrebel 
> so pleas dont say againg its the proxy or firewall 

I'm trying to help you debug the causes that might be causing your client not to connect. I mentioned **explicitly using an intermediate proxy** to capture the network flows so I can analyze them and collect information that the server is returning. Quoting mitmproxy's website, it's:

> An interactive console program that allows traffic flows to be intercepted, inspected, modified and replayed. 

If you are not able to attach server logs nor network traces, I'm sorry but I can't help you debug your problem. A "connection closed" problem can have hundreds of causes, the screenshot is not enough.

**Comment by acidicrebel** [comment] 2017-09-14 09:19
it should be enough and the funny thing nobody knows shit about it look to #4388 so maybe you could get more info there becaus its the exact same problem and he got send to post that arent about sooo maybe just maybe there is someone out there that knows how to fix it.... and thanks for trying to help @SamuAlfageme

**Comment by Kawohl** [comment] 2017-09-14 09:34
dear @acidicrebel , 

http://docs.mitmproxy.org/en/stable/install.html#installation-on-windows

Since your unwilling to provide more information, and the kind people of ownCloud actually tried to help you, I'll close this, please reopen when you are able to provide the information asked for by the maintainers. 

To keep this straight: no logs, no help.

**Closed by Kawohl** 2017-09-14 09:34 UTC
Labels: Needs info
