### ISSUE TITLE
[Windows] [2.0.1] [build 5446] Changes in ignored files trigger full discovery and sync.

### ISSUE THREAD

**Issue by cluelessperson** [owncloud/client#3805] opened 2015-09-10 21:07 UTC
#### Issue:

When ignored files or directories are modified, discovery and synchronization is triggered.

#### Example Case:

Hexchat portable application in ownCloud directory is run, updating scrollback, logs, and conf files constantly as new messages are received.  This directory has been marked as ignore.
Hexchat is exitted.  ownCloud returns to normal expected behavior. 

![owncloud](https://cloud.githubusercontent.com/assets/5635253/9800851/fc9669ea-57d4-11e5-8306-bdabb14f3231.PNG)

**Comment by guruz** [comment] 2015-09-10 22:54
https://github.com/owncloud/client/blob/master/src/gui/folderwatcher.cpp#L95

@ckamm @dragotin Would this be fixed by using the sped-up csync_exclude (the version which supports full directories)?

**Comment by ckamm** [comment] 2015-09-11 04:56
@guruz Yes, using csync_exclude there would be good and make folderwatcher ignore handling consistent with the sync ignore handling.

**Comment by Dianafg76** [comment] 2015-10-23 07:07
@ckamm What are the steps to reproduce this issue ?

**Comment by ckamm** [comment] 2015-10-28 08:16
@Dianafg76 Touch a file in a sync folder that's being ignored, such as a file ending in '~'. No new sync should be triggered.

This should already have worked before, but there are some pattern - I don't know exactly which - that were treated inconsistently (ignored but still triggered a sync when touched). These inconsistencies are now gone because it uses the same codepath.

**Comment by Dianafg76** [comment] 2015-10-28 08:24
@ckamm, Thanks for the information

**Comment by Dianafg76** [comment] 2015-10-28 08:42
@ckamm I tested this issue, and is working OK for my

Desktop v  ownCloud-2.1.0.5586-nightly20151028-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed

**Closed by Dianafg76** 2015-10-28 08:42 UTC
Labels: approved by QA, bug

**Comment by cluelessperson** [comment] 2015-10-28 17:42
Thank you all!
