### ISSUE TITLE
client and server should agree on the  disk usage 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7220] opened 2019-06-04 14:47 UTC
With selective sync or virtual files enabled the client could report less disk usage,
But I do not see a plausable explanation, why the client would report more

![grafik](https://user-images.githubusercontent.com/1108546/58888957-754c9a80-86e8-11e9-9059-e5b919a08fe1.png)

**Comment by guruz** [comment] 2019-06-05 09:14
Isn't that the remote disk usage?!

**Comment by ckamm** [comment] 2019-06-07 07:40
Yes, what's reported is the remote quota. That value is the "quota-used-bytes" response from the server. Possibly the webui computes the used quota differently?

**Comment by ckamm** [comment] 2019-06-07 07:41
@jnweiger Any particular ideas on how to reproduce?

**Comment by jnweiger** [comment] 2019-06-07 09:34
@ckamm  It is probably a large folder shared with me. Which is not accounted for by the web ui, but accounted for in the client, even if not syncing (selective sync)

@guruz if that is the remote usage, I find it confusing. Can we make a mouse over tooltip explain that some more...

**Comment by ckamm** [comment] 2019-06-14 13:51
Relates to the other quota issue #7193

**Comment by ogoffart** [comment] 2020-02-11 09:11
duplicate of #7193 : this is not something we can fix

**Closed by ogoffart** 2020-02-11 09:11 UTC
Labels: Server Involved, bug, p4-low
