### ISSUE TITLE
CSync failed to load or create the journal file - SQlite error?

### ISSUE THREAD

**Issue by rudo54** [owncloud/client#2673] opened 2015-01-07 14:04 UTC
Hello,

I can not sync my tablet with Windows 8.1, the following error message appears:

![owncloud](https://cloud.githubusercontent.com/assets/10435363/5646490/31f368dc-967d-11e4-8900-ecc7cf24a0c7.jpg)

that means: CSync failed to load or create the journal file. Make sure you have read and write permissions in the local sync directory. 

The error occurred since the update to version 1.7.1, so far everything has worked.

I have a total of four folders to sync. Two of them on the hard drive C: and two on drive D:, wich is on a SD card.

The error only occurs with the two folders on the SD card, with the folders on drive C: owncloud-sync works.

I've tried multiple what I found on the forum:
- client deleted and reinstalled,
- client and server are on the latest version,
- delete folder and recreate,
- The drive D: through C: integrated,
- The permissions newly allocated, etc.

When I create a new sync folder with ownCloud, the new folder is created on the drive and the files 
.csync_journal.db
.csync_journal.db-shm
.csync_journal.db Whale
.owncloudsync.log
are stored there. I think,  missing r/w permissions can not cause this issue.

There may be a connection with the problem discussed here:
https://github.com/owncloud/client/issues/2547

My log file:

https://gist.github.com/0f9f84a34c415a2a6ea9.git

The issue was discussed here (in german):
http://forum.owncloud.org/viewtopic.php?f=21&t=25545

I hope, there is some help,
sorry for my bad english,

Regards, Lothar

**Comment by ogoffart** [comment] 2015-01-08 16:42
It looks like the database is corrupted

```
12-30 13:01:48:322 0x8e21664 csync_statedb_query: sqlite3_compile error: disk I/O error - on query PRAGMA quick_check;
12-30 13:01:48:322 0x8e21664 csync_statedb_load: ERR: sqlite3 integrity check failed - bail out: disk I/O error.
```

Now the question is how and why did that happen?

**Comment by ogoffart** [comment] 2015-01-15 10:38
It appears that the local database is corrupted.
I have made a commit so 1.8 will explixitly say that the database is corrupted.

Maybe we should have some mechanisms to automatically recover from corrupted journal?

**Comment by craigpg** [comment] 2015-01-19 14:56
What is the workaround when the database gets corrupted?

**Comment by guruz** [comment] 2015-01-19 16:04
@craigp I don't think it is corrupted. I think the problem is https://github.com/owncloud/client/issues/2701

**Comment by dragotin** [comment] 2015-01-19 16:05
lets close this one as a duplicate of #2701 This one is about SD-Card which probably also uses FAT file system.

**Closed by dragotin** 2015-01-19 16:05 UTC
Labels: bug, Needs info, sev3-medium

**Comment by guruz** [comment] 2015-01-20 11:46
@rudo54 Could you find out the exact file system on the SD?

**Comment by rudo54** [comment] 2015-01-20 20:41
Hi,
the filesystem was exFAT.
I bought a new card and formatted it with NTFS. Now my owncloud is 
working again.

But I don't understand, why the old card worked for 2 years.


------ Originalnachricht ------
Von: "Markus Goetz" <notifications@github.com>
An: "owncloud/client" <client@noreply.github.com>
Cc: "rudo54" <lo.franke@posteo.de>
Gesendet: 20.01.2015 12:46:59
Betreff: Re: [client] CSync failed to load or create the journal file - 
SQlite error? (#2673)
