### ISSUE TITLE
Activity cluttered with useless information on Server Rename

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#9983] opened 2022-08-01 12:25 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

With the test setup described below, the Activity tab is cluttered with useless and wrong information, as in the screen shot here:
![grafik](https://user-images.githubusercontent.com/1070214/182146583-3173797d-b673-40c0-b49e-59c4f882ab82.png)
While the first line is correct and good, the subsequent lines do not make sense. They are all children of the rename in the first line. Also, both the (expected) original name and the new name are the same. 

This happens with oCIS and oC10 backend.

Data on the local repo is properly renamed and looks fine. No loss.

### Expected behavior

Actually the first line would be sufficient. It is IMHO not needed to print an activity line for each item underneath the renamed directory.

### Steps to reproduce the issue

1. Create a folder with some content on the server
2. Wait until it is synchronized to the client
3. Rename the folder on the server to a new name
4. Wait until the change is propagated to the local repo
5. Check the Activity tab for useless messages 

### Logs

Logs are available.

### Client version number

Current master 3.0.0.0-git - commit 8f59224e6cc622de073cbeb18a3c35a4aa548809

### Desktop environment (Linux only)

Linux, KDE, openSUSE Tumbleweed

**Comment by TheOneRing** [comment] 2022-08-02 07:09
This is the sync log and we log everything we do.
(We also emit multiple signals per item...)

**Comment by jnweiger** [comment] 2022-08-02 07:34
I checked for similar issues :stuck_out_tongue: 
Its a duplicate of of https://github.com/owncloud/client/issues/7270

**Comment by TheOneRing** [comment] 2022-08-02 07:36
You are right.
Duplicate of: https://github.com/owncloud/client/issues/7270

**Closed by TheOneRing** 2022-08-02 07:36 UTC
Labels: bug

**Comment by jnweiger** [comment] 2022-08-02 07:42
Related to https://github.com/owncloud/client/issues/9238
There I asked for both, source and destination name. What we got instead is aparently the same name 3 times.
