### ISSUE TITLE
Elements of "Recent changes" appear three times in system tray menu

### ISSUE THREAD

**Issue by godfuture** [owncloud/client#5256] opened 2016-10-17 09:28 UTC
![oc_client_not_working](https://cloud.githubusercontent.com/assets/4669278/19432495/0fc8a300-945d-11e6-866d-967a214533b4.png)
### Expected behaviour

One changes means one entry in the "recent changes" menu of system tray.
### Actual behaviour

One change means three entries in "recent changes" menu of system tray.
### Steps to reproduce
1. Sync a folder
2. Make changes on server side or external to the synced folder
3. Check the system tray menu
### Server configuration

Operating system: Ubuntu 16.04
Web server: Apache 2.3
Database: MySQL 5.7
PHP version: 7
ownCloud version: Nextcloud 10 (it also happend to Owncloud 9.1)
Storage backend (external storage):
### Client configuration

Client version: 2.2.4
Operating system: Windows 10 SP1
OS language: German
Installation path of client: C:\Program Files (x86)
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

Did not work. Only the client settings page open up with both commands.
2. Web server error log:
1. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ckamm** [comment] 2016-10-18 10:25
@godfuture I can reproduce this. It seems that there is one entry after the sync that downloads a file from the server. But then during the next sync several spurious entries appear.

**Comment by guruz** [comment] 2016-10-19 15:09
Sorry, still happening for me.
OS X, uploading a single file.
I get several (5?) entries in the tray menu.

**Comment by ckamm** [comment] 2016-10-24 13:50
Huh, I'll try to reproduce again then.

**Comment by ckamm** [comment] 2016-10-25 07:49
@guruz I'm having trouble reproducing the problem. Uploads of existing and new files only show up once in the recent actions menu. Can you tell me how exactly you make that happen?

**Comment by guruz** [comment] 2016-11-08 10:29
I can't reproduce this anymore with current master branch.
Odd..

**Comment by CorneelDragon** [comment] 2016-11-08 15:33
My colleague Jean-Marie has an idea about the conditions on which appears:

From doing some testing, it appears to be related to how deep a file is nested; it does not seem to happen with files in the root, and the deeper a file is nested, the more often the line is duplicated. However that is not 100% consistent. I have not seen duplicates at the root level, but I cannot guarantee it never happens...

See: https://github.com/owncloud/client/issues/5301

**Comment by guruz** [comment] 2016-11-08 16:13
@CorneelDragon Please try to reproduce with a current nightly build. http://download.owncloud.com/desktop/daily/
And report back if it is fixed..

**Comment by SamuAlfageme** [comment] 2017-02-15 11:59
The `Recent Changes` section on the tray menu is displaying duplicate information:

### Actual behavior
- **Duplicated messages**: only for single files, not folders (uploads, moves, deletions...)
![screenshot 2017-02-15 10 53 50](https://cloud.githubusercontent.com/assets/2644445/22968998/0eefccaa-f36d-11e6-8d69-ac03a0e61b7e.png)
- If you open the tray menu while pushing changes, these doesn't appear until you push some more changes with the menu closed (maybe this is an OS limitation of being reactive to async changes)

**Client version: `2.3.0 beta1`** -- I still have to check if this only reproduces on OS X

**Comment by ckamm** [comment] 2017-02-16 13:58
@SamuAlfageme I can reproduce it and will investigate.

**Comment by ckamm** [comment] 2017-02-16 14:02
It looks like `SyncEngine::finished` emits `transmissionProgress` with progress info that still contains the final file that was uploaded.

**Comment by ckamm** [comment] 2017-02-16 14:11
Fixed in 2.3 branch.

**Comment by SamuAlfageme** [comment] 2017-02-17 09:36
👍 in `Version 2.3.0-nightly20170217 (build 4057)`

**Closed by SamuAlfageme** 2017-02-17 09:36 UTC
Labels: bug, ReadyToTest, sev2-high
