### ISSUE TITLE
[OS X] 1.8.2-rc1: sharing window is stuck behind other windows

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3322] opened 2015-06-10 12:05 UTC
When right-clicking "share with owncloud" the sharing window does not appear on top of the current finder window but it is stuck somewhere in the back (and does not belong to the Finder group of windows). It is almost impossible to find if you don't know it is somewhere theer.

I would expect to see it on top instead:

![image](https://cloud.githubusercontent.com/assets/621965/8081901/2f18126e-0f79-11e5-96b0-841852ef2d88.png)

**Comment by moscicki** [comment] 2015-06-10 12:05
MacOSX 10.8.5

**Comment by Kawohl** [comment] 2015-06-10 12:13
I was not able to reproduce this on 10.10.3

**Comment by jturcotte** [comment] 2016-01-04 11:06
According to #3015 this should be fixed on OS X but I haven't tried. Closing here in order to follow the issue there.

**Closed by jturcotte** 2016-01-04 11:06 UTC
Labels: bug
