### ISSUE TITLE
Syncing large accounts in VFS mode leads to "Not responding" in UI

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7439] opened 2019-08-29 09:36 UTC
OS: Windows 7, Windows 10
Client: 2.5.4, 2.6 daily
VFS on

Steps to recreate:
1) Add a new large account to your desktop client
2) Turn on VFS before initial sync
3) Run initial sync

Actual result: Client not responding, connection times out, client freezes 
Expected result: Account has been synced 

<img width="714" alt="Screenshot 2019-08-29 at 10 21 25" src="https://user-images.githubusercontent.com/49001702/63929058-0ebdeb00-ca51-11e9-82f8-22218ee64339.png">
<img width="709" alt="Screenshot 2019-08-29 at 10 30 53" src="https://user-images.githubusercontent.com/49001702/63929062-1087ae80-ca51-11e9-9107-dc9411afabb2.png">

**Comment by guruz** [comment] 2019-08-29 09:38
Also spotted by @lefherz

**Comment by guruz** [comment] 2019-08-29 09:39
I'm putting this into 2.6.0 in case it's an easy fix.

**Comment by HanaGemela** [comment] 2019-08-29 10:37
I can't rename the shared log file
In 20190828_1936_owncloud.log.6 "Not responding" happened around 11:21

**Comment by guruz** [comment] 2019-08-29 11:17
I don't see a timestamp stall there, only a lot of DB activity.

**Comment by guruz** [comment] 2019-08-29 11:46
@ogoffart @ckamm I wonder if `OwncloudPropagator::scheduleNextJob()` is good like that?
It will directly create job after job (with a 0 single shot timer), and one job in this initial sync case for the virtual files is created quite fast (incl DB write).

This is the 'loop':
```
08-29 11:21:00:096 [ debug sync.database ]      [ OCC::SyncJournalDb::commitInternal ]: Transaction commit  "download file start2" and starting new transaction
08-29 11:21:00:096 [ info sync.propagator ]:    Completed propagation of "test/1015066234.
wem.owncloud" by OCC::PropagateDownloadFile(0x15a56a98) with status 4
08-29 11:21:00:096 [ debug sync.statustracker ] [ OCC::SyncFileStatusTracker::slotItemCompleted ]:      Item completed "test/1015066234.wem.owncloud" 4 8
08-29 11:21:00:111 [ info sync.propagator ]:    Starting INSTRUCTION_NEW propagation of "test/101507196.wem.owncloud" by OCC::PropagateDownloadFile(0x15a56c00)
08-29 11:21:00:111 [ debug sync.propagator.download ]   [ OCC::PropagateDownloadFile::start ]:  "test.wem.owncloud" 0
08-29 11:21:00:111 [ debug sync.propagator.download ]   [ OCC::PropagateDownloadFile::start ]:  creating virtual file "C:/..../test/101507196.wem.owncloud"
08-29 11:21:00:111 [ debug sync.fileitem ]      [ OCC::SyncFileItem::toSyncJournalFileRecordWithInode ]:        "C:/..../test/101507196.wem.owncloud" Retrieved inode  0 (previous item inode:  0 )
08-29 11:21:00:111 [ info sync.database ]:      Updating file record for path: ".....101507196.wem.owncloud" inode: 229612 modtime: 1455008338 type: 4 etag: "d5e6fda729820b40a7629dd6e04e6abd" fileId: "00127471ocyjcpub7drj" remotePerm: "WNVRS" fileSize: 28099 checksum: ""
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 1 QVariant(qlonglong, -8062882912762356484)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 2 QVariant(int, 115)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 3 QVariant(QByteArray, "test101507196.wem.owncloud")
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 4 QVariant(qulonglong, 229612)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 5 QVariant(int, 0)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 6 QVariant(int, 0)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 7 QVariant(int, 0)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 8 QVariant(qlonglong, 1455008338)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 9 QVariant(int, 4)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 10 QVariant(QByteArray, "d5e6fda729820b40a7629dd6e04e6abd")
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 11 QVariant(QByteArray, "00127471ocyjcpub7drj")
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 12 QVariant(QByteArray, "WNVRS")
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 13 QVariant(qlonglong, 28099)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 14 QVariant(int, 0)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 15 QVariant(QByteArray, "")
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 16 QVariant(int, 0)
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::exec ]:        SQL exec "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);"
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::exec ]:        Last exec affected 1 rows.
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 1 QVariant(QString, "test/101507196.wem.owncloud")
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::exec ]:        SQL exec "DELETE FROM downloadinfo WHERE path=?1"
08-29 11:21:00:111 [ debug sync.database.sql ]  [ OCC::SqlQuery::exec ]:        Last exec affected 0 rows.
```

@ogoffart When are single-shot-0-timers executed? Before or after other event loop contents?

**Comment by guruz** [comment] 2019-08-29 11:47
@ogoffart It's a queued invocation: https://code.woboq.org/qt5/qtbase/src/corelib/kernel/qtimer.cpp.html#435

**Comment by guruz** [comment] 2019-08-29 11:58
https://code.woboq.org/qt5/qtbase/src/corelib/kernel/qmetaobject.cpp.html#2347
https://code.woboq.org/qt5/qtbase/src/corelib/kernel/qeventdispatcher_win.cpp.html#496
^^ Is this then the cause of the 'Not responding'?

**Comment by guruz** [comment] 2019-08-29 12:07
@HanaGemela I am creating different build https://jenkins.int.owncloud.com/job/client-trigger/3331/
I'm curious in how it changes the situation on your windows 7.

**Comment by ogoffart** [comment] 2019-08-29 12:48
I'm not 100% sure, but i believe when windows shows "Not Responding"  This simply means that the application freeze because it is in a (potentially infinite) big loop. It is just taking too much CPU.
Maybe there is a O(n^2) or exponential algorithm using all the CPU.  One can find out by looking at the backtrace when the application freeze.

**Comment by ogoffart** [comment] 2019-08-29 12:49
It could also means that one of the sytem function we call is blocking.

But I would not think this is because of the jobs, because the jobs still let the eventloop run. that's the whole point.

**Comment by guruz** [comment] 2019-08-29 13:18
@ogoffart I tried to find out by looking at @HanaGemela 's log (and i think it might be doing that even though event loop runs)

@HanaGemela Do you want to try https://download.owncloud.com/desktop/testing/ownCloud-2.6.0.12635.12383-26_propagator_delay.GPO.msi ?

**Comment by HanaGemela** [comment] 2019-08-29 14:26
@guruz trying right now. So far no timeout error, no 'No responding'... but it is stuck at file 54 of almost 200k and it doesn't do anything. I can't click on other tabs or display logs 

<img width="685" alt="Screenshot 2019-08-29 at 16 25 39" src="https://user-images.githubusercontent.com/49001702/63948833-af280580-ca79-11e9-9312-6e7fca801005.png">

**Comment by HanaGemela** [comment] 2019-08-29 14:44
Got the timeout error after like 20 minutes and so far the client has not reconnected

**Comment by guruz** [comment] 2019-08-30 06:49
@HanaGemela Are you saying with the new build ownCloud-2.6.0.12635.12383-26_propagator_delay.GPO.msi you didn't get the "Not responding" issue anymore at all? 
I'm thinking the timeout and "Not responding" are two different things and "not responding" would be fixed with 404b0c207b39bdf2f0627b616a2ccf926c7d1c96

**Comment by guruz** [comment] 2019-08-30 07:00
From the new log new_build_20190829_0713_owncloud.log.1:

```
08-29 07:20:37:906 [ warning sync.networkjob ]:	Network job timeout QUrl("https://oc2.EXAMPLE.org/remote.php/dav/files/commons/")
08-29 07:20:37:906 [ warning sync.networkjob ]:	QNetworkReply::OperationCanceledError "Connection timed out" QVariant(Invalid)
08-29 07:20:37:906 [ info sync.networkjob.propfind ]:	PROPFIND of QUrl("https://oc2.EXAMPLE.org/remote.php/dav/files/commons/") FINISHED WITH STATUS "OperationCanceledError Connection timed out"
08-29 07:20:37:906 [ warning sync.networkjob.propfind ]:	*not* successful, http result code is 0 ""
08-29 07:20:37:906 [ warning default ]:	QIODevice::read (QNetworkReplyHttpImpl): device not open
08-29 07:20:37:906 [ info gui.account.state ]:	AccountState connection status change:  OCC::ConnectionValidator::Connected -> OCC::ConnectionValidator::Timeout
08-29 07:20:37:906 [ info gui.account.state ]:	AccountState state change:  "Connected" -> "Network error"
```

This is actually the connection validator disconnecting the account, not the sync.
The stuff that happens before that timeout is all the SQL from the "virtual" file creation loop (e.g. https://github.com/owncloud/client/issues/7439#issuecomment-526149506)

So somehow that code might have starved the network IO? Or might have created so much load that network was not handled?

**Comment by guruz** [comment] 2019-08-30 07:06
A bit later the notification call times out too:
```
08-29 07:25:10:358 [ warning sync.networkjob ]:	Network job timeout QUrl("https://oc2.EXAMPLE.org/ocs/v2.php/apps/notifications/api/v1/notifications?format=json")
```

**Comment by HanaGemela** [comment] 2019-08-30 12:21
Got Not responding when 300 files were remaining to sync. Client recovered and finished the sync. Then I got errors about permissions and file name clashes. Then the client was not responding again but recovered

**Comment by guruz** [comment] 2019-09-06 04:55
> This is actually the connection validator disconnecting the account, not the sync.

It looks like the ConnectionValidator stalling is NOT fixed:
https://github.com/owncloud/client/issues/7456
(thanks @jnweiger )

**Comment by guruz** [comment] 2019-09-17 11:13
This should be much better with current 2.6 daily.

**Comment by jnweiger** [comment] 2019-09-19 22:56
Retesting on Ubuntu-18.04 with client 2.6.0daily20190917 and 600.000 files on the server

The client takes a while to count the files, it reaches 2.2GB RSS when counted to 100.000

**Comment by jnweiger** [comment] 2019-09-20 07:02
Looks good to me! Closing.

**Closed by jnweiger** 2019-09-20 07:02 UTC
Labels: bug, p2-high

**Comment by jnweiger** [comment] 2019-09-20 09:09
Testing the same with client2.6.0daily20190921 on windows 10, I can still reproduce timeouts.

![image](https://user-images.githubusercontent.com/1108546/65314584-df555680-db96-11e9-8f1a-9341f6c15602.png)

But, I cannot clearly attribute that to client misbehaviour. There are server issues, and VM-host networking also has issues here.

**Comment by jnweiger** [comment] 2019-09-20 14:12
On a second testrun, I ran into a potential data loss issue https://github.com/owncloud/client/issues/7555

On a second testrun, (avoiding suspended VMs and network issues), the windows client too syncs down the placeholders just fine....
