### ISSUE TITLE
[OS X] Can't open log window via command line to already running client

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#4098] opened 2015-11-09 21:47 UTC
## Reproduce
1. Start OS X Client (from start menu)
2. Execute `/Applications/owncloud.app/Contents/MacOS/owncloud --logwindow` in console
## Expected

Log window opens. See note in blue box: https://doc.owncloud.org/desktop/2.0/troubleshooting.html#obtaining-the-client-log-file
## what happens:

Client window comes to the front. No log-window is opened.

System: OS X 10.9.5
Client 2.0.2
## Workaround:

Use logfile:
`/Applications/owncloud.app/Contents/MacOS/owncloud --logfile <filename>`

edit: would be nice to have short cut as well, or a button to open log-window.

**Comment by guruz** [comment] 2015-11-10 11:46
Possibly the log window is behind _all_ other application windows (of other applications)?

**Comment by tflidd** [comment] 2015-11-10 13:43
I didn't see anything hidden under the actual owncloud window. I closed 
other programs on the desktop, I tried to switch to a different window 
with apple+tab, nothing works.
Now I started the client with logging to a logfile (--logfile), and I 
tried the --logwindow command again, this shows up in the logfile:
````
11-10 14:38:05:835 0x60800000e8c0 OCC::Application::setupLogging: 
"################## ownCloud en_US (en) 2.0.2 (build 2818)"
11-10 14:38:05:836 0x60800000e8c0 OCC::Application::slotParseMessage: 
Running for 319.943 sec
11-10 14:38:05:836 0x60800000e8c0 OCC::ownCloudGui::slotShowSettings: 
void OCC::ownCloudGui::slotShowSettings()
````

**Comment by stonerl** [comment] 2015-12-12 15:49
@tflidd The Problem is that you started the owncloud client already. You should get this message on the cmd
```
int main(int, char **) Already running, exiting...
```

If you want to run the client with the logwindow you need to close it first and then start it from the commandline with:

```
./owncloud --logwindow```

**Comment by stonerl** [comment] 2015-12-12 16:03
If you want to open the log window while ownCloud is already, running open the openCloud-client and press ```F12```

**Comment by tflidd** [comment] 2015-12-13 12:18
> If you want to open the log window while ownCloud is already running, open the openCloud-client and press F12

It is OS X, not Windows !

**Comment by stonerl** [comment] 2015-12-13 12:25
@tflidd when I press F12 on my mac it opens the log window.

**Comment by stonerl** [comment] 2015-12-13 12:28
usually F12 is assigned to open the Dashboard by default:

![screen shot 2015-12-13 at 13 27 54](https://cloud.githubusercontent.com/assets/2091312/11766974/5e52d9e0-a19d-11e5-943a-4d8ccfdb3155.png)

**Comment by ogoffart** [comment] 2017-12-06 13:08
We can have an second key combinason that would work better on OSX

**Comment by HanaGemela** [comment] 2019-06-03 10:52
@guruz @ogoffart How has this been resolved?
Should '/Applications/owncloud.app/Contents/MacOS/owncloud --logwindow' work now?

**Comment by guruz** [comment] 2019-06-04 07:45
Works for me on macOS. Opened client in one terminal tab:
`./bin/owncloud.app/Contents/MacOS/owncloud  `
Then this in second terminal tab opens log window:
` ./bin/owncloud.app/Contents/MacOS/owncloud --logwindow`

**Closed by guruz** 2019-06-04 07:45 UTC
Labels: Feature, PR available, ReadyToTest, p2-high, p4-low

**Comment by HanaGemela** [comment] 2019-06-04 08:22
@guruz 
When I run: /Applications/owncloud.app/Contents/MacOS/owncloud --logwindow

I can see the below line in the terminal and it also opens webUI and asks for login. Is that right?
m_crashReporterChar:  /Applications/owncloud.app/Contents/MacOS/owncloud_crash_reporter

**Comment by guruz** [comment] 2019-06-04 08:24
You mean you run this after the client is already running from another tab?

Or as first run? As first run - yes. But second run should be just opening the first instance

**Comment by HanaGemela** [comment] 2019-06-04 08:30
@guruz 
When I run the command for the first time, it opens the webUI, I log in and then I can see Log Output window.
When I run the command (/Applications/owncloud.app/Contents/MacOS/owncloud --logwindow) for the second time in another tab, it exists:

/Applications/owncloud.app/Contents/MacOS/owncloud --logwindow
gui.application: Already running, exiting...

**Comment by guruz** [comment] 2019-06-04 08:36
Yes, it is supposed to open the log window and exit..

**Comment by HanaGemela** [comment] 2019-06-04 08:38
@guruz  Oh, I see! Then it works as expected

**Comment by guruz** [comment] 2019-06-04 10:30
Great :-)
