### ISSUE TITLE
Add account wizard "choose what to sync" option also syncs the root without choice

### ISSUE THREAD

**Issue by icawebdesign** [owncloud/client#3632] opened 2015-08-15 14:18 UTC
When selecting a directory to sync, the client also downloads all files in the root directory too without an option to change this behaviour. This can result in a lot of files and MB being downloaded and sync'd that aren't required.

This is on Windows 8.1 Pro.

ownCloud client 1.8.x works as expected adn will only sync the directories selected.

**Comment by icawebdesign** [comment] 2015-08-16 12:39
Upon further investigation, this isn't restricted to the root path, but in fact a selected directories _parent_ dir, for example:

I want to sync 'baz':
/foo/bar/baz

Everything in 'baz' gets sync'd as expected, but also everything in 'bar' will too, which is undesired.

**Comment by ogoffart** [comment] 2015-08-17 06:54
There is no differences with 1.8.x.  Could you elaborate on what is the expected behaviour and what do you use to select directories.

**Comment by MTRichards** [comment] 2015-08-17 14:12
If I am understanding correctly, this is an issue where selective sync pulls in all the files in the parent directory of the selected folder, rather than just the folder itself.

So if I selectively sync only /root/pictures the sync algorithm pulls in all of the files in root, and also all of the files in pictures. It does not pull in any other directories in /root/.

If this is the comment, it is the designed behavior in ownCloud. We follow the same approach as Dropbox in this case, where the files in all parent folders of a selected directory down in the file tree are synced.

**Comment by icawebdesign** [comment] 2015-08-17 14:24
@MTRichards that's correct in what I'm seeing (apologies, not had time to follow up with screenshots as I had planned today).

This is different behaviour to 1.8.x. Is there any particular reason for this? Using your example of /root/pictures, if I wanted /root files, I'd check the /root box and uncheck the pictures box if I only wanted the files in the root dir sync'd. By selecting /root/pictures, surely this indicates that I want the pictures directory sync'd and the mere fact I haven't specifically selected the root dir, should indicate that I'm not interested in the contents of that.

If you're going for a dropbox replacement (I've never used any other cloud service for the very reason owncloud exists, I value the fact I can host it in-house but I understand where you're coming from in this respect), could this possibly be an option somewhere to enable / disable this feature?

For example, I wanted to sync some ebooks (~5GB in a 'dev' directory) but I ended up syncing nearer 20GB as there was some "uncategorised" books in the parent directory that I had no interest in syncing with my laptop.

Or is it now a case that we always have to create dirs and subdirs to try and keep the syncing in control, eg: /ebooks, /ebooks/uncategorised, /ebooks/dev etc just to be able to sync the dirs that I specifically ask for?

This approach seems a bit more cumbersome to organisation of directories just for syncing purposes.

**Comment by phil-davis** [comment] 2015-08-17 14:28
And I guess the reasoning for this is that if I have
FolderA/FolderB
selected for sync
then at least an empty FolderA must be created on the client, to contain FolderB.
That means there will be a FolderA visible to the client user. They will be tempted to put files in it. Then what does the client do? Delete the files that the user dumped there? Ignore them?
So the easy way out is to say that if any folder below FolderA is synced, then all files in FolderA get synced also.

Of course with some more thought and work there could be an option not to sync the files in FolderA.

**Comment by MTRichards** [comment] 2015-08-17 14:37
@phil-davis you are spot on, that use case becomes a real problem! If you sync a sub folder, and create a parent folder to hold a sub folder, you have to sync the parent folder files too or you end up deleting or not syncing files in a folder that indicates that all the files are synced. And suffice it to say that we have lived through similar problems in the past. Consistent and simple.

If that is a problem, it is currently possible to only sync a sub folder - that is the way around the problem. Simply remove the complete server root folder sync to the desktop, and instead sync a sub folder on the server directly with a sub folder on the client. That solves the problem, and doesn't lead to more complex issues.

@icawebdesign my concern is that you say it changes. It was not supposed to change, as @ogoffart said, so do you have any more information on this, as if it is a change in behavior it would be a bug as that was not intended.

**Comment by icawebdesign** [comment] 2015-08-17 14:37
@phil-davis Right... that does make sense regarding hierarchy. I guess this is a difference in approach between 1.x and 2.x where it would appear that there's not so much of a hierarchy structure in 1.x ('pictures' would just end up in whatever dir you defined on your local box and there wouldn't be a 'root' path per-se) but with 2.x it looks like the syncing is actually mirroring the cloud structure hierarchy.

Your explanation is actually good and I'm now leaning towards this being good default behaviour despite the fact it means I'd personally need to reorganise some of my directories (this is mainly an issue with SMB shares more than anything within owncloud itself).

Perhaps adding an option for this would ultimately just become more confusing to the end user, plus more of a nightmare for any support of owncloud itself (be it corporate in-house or owncloud dev / community).

**Comment by icawebdesign** [comment] 2015-08-17 14:38
@MTRichards when I get home from work tonight, I'll do a test / screenshot of what I see between 1.8 and 2.0.

**Comment by ogoffart** [comment] 2015-08-17 14:46
@icawebdesign perhaps you are confusing the "choose what to sync" feature, which allow to unselect folders, with the the "add folder" feature.
If you click on the "add folder" button and choose to sync /root/pictures, it will only sync pictures, and nothing else from root.

**Comment by phil-davis** [comment] 2015-08-17 14:47
I tried this sub-folder selection stuff with 1.8.4 client this afternoon and it seemed to behave the same as 2.0 client.

**Comment by tflidd** [comment] 2015-08-19 06:11
I just wondered about the "add folder to synchronize"-button (https://github.com/owncloud/client/issues/3645) when I found out about the new behavior. I don't really know if it has changed since 1.8.4 but I use the old scheme (perhaps conserved during updates).
Currently I have the following structure on my owncloud:
/sync-folder/...
directly synced to e.g. C:\owncloud
with the new scheme, I would just add an additional folder, so everything will be in:
C:\owncloud\sync-folder\...

I was getting used to the old structure, so for example on a mobile device, I could only sync the latest picture gallery without the whole file-tree:
/sync-folder/pictures/2015/italy
-> c:\owncloud\...
now it would be in c:\owncloud\sync-folder\pictures\2015\italy\...

**Comment by ogoffart** [comment] 2015-08-19 08:08
Nothing is different between 1.8 and 2.0 in that respect. Only the position of the buttons has changed in the interface.

**Comment by tflidd** [comment] 2015-08-19 10:30
Sorry, everything still works you only have to know where to click, tooltip-menu: https://github.com/owncloud/client/issues/3645#issuecomment-132467293

**Comment by icawebdesign** [comment] 2015-08-20 22:34
My apologies once again for delayed response.. but indeed.. this hasn't changed since 1.x.

I guess with the 'add folder' being the prominent button (top one at least), I have always selected that back since 1.4.x I think, never even tried the 'choose what to sync' option, but after testing both, they do function in the same way between 1.x and 2.x just that the prominence of the options (add folder / sync stuff) has reversed.. so in short, no bug, just different priorities in UX.

**Comment by ogoffart** [comment] 2017-12-06 12:33
Duplicate of  #3664

**Closed by ogoffart** 2017-12-06 12:33 UTC
Labels: Discussion
