### ISSUE TITLE
Segmentation fault with the 2.0.0 client (Fedora22 / KDE5)

### ISSUE THREAD

**Issue by Ryux** [owncloud/client#3700] opened 2015-08-29 09:59 UTC
Hi,

since the upgrade with the 2.0.0 client, I have a segmentation fault at startup.

The log :
08-29 11:42:21:671 0x8206a0 :0 QDir::mkpath: Empty or null file name
08-29 11:42:27:771 0x8206a0 :0 QDir::mkpath: Empty or null file name

And a link to the gdb backtrace : https://gist.github.com/Ryux/a16e1e14fd3ba63d694b

Thanks for your help

Ryu

**Comment by dragotin** [comment] 2015-08-29 10:08
This is a dupe of #3672

**Closed by dragotin** 2015-08-29 10:08 UTC
