### ISSUE TITLE
Client rescans all the files after a decryp-all

### ISSUE THREAD

**Issue by brunodegoyrans** [owncloud/client#5686] opened 2017-04-07 12:39 UTC
### Expected behaviour
The occ decrypt-all is used to decrypt all the files of user(s). It is mostly used when an admin want to deactivate server-side encryption.
decryp-all only decrypts the files but they shall be seen has unchanged by the user.
So after a decrypt-all, the client shall not reload all the files.

### Actual behaviour
After having occ decryp-all users, the client reloads ALL the files.

### Steps to reproduce
1. Files encrypted on the server
2. Start à procedure to decrypt-all (single-user mode, etc.) 
3. During the decrypt-all procedure, the client can't have access to the server. This is normal due to single-user mode.
4. When decrypt-all is finished, deactivate encryption, then cancel single-user mode.
5. Client starts to sync ALL the files, whatever they have changed or not.

### Server configuration
Operating system: DEBIAN 7

Web server: APACHE 2

Database: MYSQL

PHP version: 5.4

ownCloud version: 9.1.4

Storage backend (external storage): NONE

### Client configuration
Client version: 2.3.0 build 6780

Operating system: WINDOWS 10

OS language: FR

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log: 

3. Server logfile: ownCloud log (data/owncloud.log): NO errors since server has came out single-user mode.

**Comment by guruz** [comment] 2017-04-10 13:32
In future this should not happen anymore since we use checksums and compare before transfering..

FYI @IljaN

**Comment by ckamm** [comment] 2017-04-12 13:03
@guruz Not for downloads: there we validate the transfer with a checksum, but don't skip the download if the checksum is unchanged.

I assume decrypt-all changes the etags on the server and thus requires the client to download the files again.

**Comment by guruz** [comment] 2017-04-12 13:28
@ckamm Close as duplicate of https://github.com/owncloud/client/issues/4755 then?

**Comment by ckamm** [comment] 2017-04-12 13:31
@guruz I'm not certain. @ogoffart isn't the etag of a file already supporsed to change if and only if the content changes?

**Comment by guruz** [comment] 2017-04-12 13:54
@ckamm Server-side encryption is transparent to the client. In theory you're right, in practice the checksum should be stronger?
(For metadata changes, we said we would change the ETag of the parent directory and then have the metadata changes in the directory listing)

**Comment by hodyroff** [comment] 2017-04-13 08:11
"@guruz Not for downloads: there we validate the transfer with a checksum, but don't skip the download if the checksum is unchanged."
Is this something we should do the other way around? Or a challenge, why?

**Comment by ckamm** [comment] 2017-04-13 08:34
@hodyroff Doing this would also mean computing a hash of a file before each download. And if the etag changes if and only if the file contents change, this should be completely superfluous. It's not clear that adding this check wouldn't on balance be a waste of resources.

From an implementation point of view, the server would need to maintain a good collision-safe hash, and we'd need to start querying it before triggering the actual download. It's related to #5589 and I did some preliminary work there.

**Comment by guruz** [comment] 2017-04-13 09:31
@ckamm The server 10.0 is by default computing a hash and sending it (maybe not on first download, but then on second one).
https://github.com/owncloud/documentation/issues/2964

**Comment by ogoffart** [comment] 2017-04-13 10:08
This is mostly a bug in the server, so please report it in the core component. The client obey the etag change.  

Of course a comparison of the 'content hashes' would help, but we're not there yet.  (Don't say 'checksum', these are not appripriate for knowing if we should download a file or not as there could be collision. (for instance, doing that with adler32 would be a terrible idea))

**Comment by guruz** [comment] 2018-04-19 17:36
@ckamm @ogoffart This should be fixed in 2.5 right? We're checking checksums before re-downloading?

FYI @IljaN

**Comment by ckamm** [comment] 2018-04-20 13:04
Yes, if hashes and sizes are equal, we'll skip the download

**Closed** 2018-04-20 13:25 UTC
Labels: Performance, Server Involved, sev4-low
