### ISSUE TITLE
Cinnamon applet using 90% CPU

### ISSUE THREAD

**Issue by mlda065** [owncloud/client#4990] opened 2016-06-21 07:11 UTC
I've recently noticed that my computer has been quite slow recently. My System Monitor often shows CPU usage up near 90% when I'm doing nothing but writing emails and reading pdfs.
I initially thought this was a Cinnamon issue ([comment thread in cinnamon repo](https://github.com/linuxmint/Cinnamon/issues/1154#issuecomment-227053785)), since the System Monitor attributes the high CPU usage to cinnamon. However now I'm pretty certain it's Owncloud. Specifically I think it's an issue with the panel applet, because that would explain why it's being counted towards Cinnamon's CPU usage and not owncloud.

### Symptoms
 * My CPU is often running at 90% (as shown with `top` and the *System Monitor* GUI) when I'm not anything intensive (reading pdfs, browsing facebook, etc). Both tools attribute the high CPU usage to cinnamon.
* I cannot watch videos or animated GIFs without visual stuttering
* when I type, what I see on the screen is often several characters behind what I've pressed
* Scrolling through pdfs is not smooth
* switching between windows is laggy
* etc

### Why I blame OC
I realise that 'my computer is slow' is a really vague claim, which is hard to address.

I tried the following things to figure out the cause:
 * Removing cinnamon panel widgets
 * Resetting all Cinnamon settings to default
 * Using one monitor instead of two
 * Not using a VPN
 * Quitting background programs (dropbox, syncthing, bitmeter OS, KDE Connect, etc)

The only thing which made the lag go away was quitting the owncloud client.
I even did a clean install. It didn't lag when the system was clean. Then I installed owncloud and it got laggy again.

### Other Info

 * I have 15 different folders synced through Owncloud, which might be an unusually high number.
 * This issue only started a few weeks ago
 * My laptop is fairly high end, so client hardware performance is not an issue.

### Server configuration
Operating system: Debian 8.5 Jessie

Web server: Apache 2

Database: MySQL

PHP version: PHP 5.6.20-0+deb8u1

ownCloud version: 9.0

Storage backend: USB Hard drive

### Client configuration
Client version: 2.2.1

Operating system: Mint 17.3, Cinnamon

OS language: English (AU)

Installation path of client: /usr/bin/owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Output of `owncloud --logfile log.txt`: [here](https://gist.github.com/mlda065/ea06fb17535e11ee47d9985d823ffa2d). It's a 12MB file. Is that normal? That seems large.

2. Web server error log: I don't know where to find that

3. ownCloud log (data/owncloud.log):
```
{"reqId":"tNyWXOgPjLh9TcY4h31E","remoteAddr":"10.1.1.2","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-02-07T10:01:44+00:00"}
{"reqId":"tNyWXOgPjLh9TcY4h31E","remoteAddr":"10.1.1.2","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2016-02-07T10:01:46+00:00"}
{"reqId":"bGtnGf30MR0XctpWoy0c","remoteAddr":"10.1.1.2","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-02-07T10:04:02+00:00"}
{"reqId":"PgUCF3KMcARqC+gyrFi5","remoteAddr":"10.1.1.2","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-02-07T10:06:21+00:00"}
{"reqId":"UXTOFkw7kQlJfxGObX0O","remoteAddr":"10.1.1.2","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-02-07T10:07:04+00:00"}
```

**Comment by ckamm** [comment] 2016-06-21 11:29
Thanks for the report! This may be related to #4985. Do you also see the "Enabled QDBusPlatformMenu workaround" string in your owncloud client logs? Which version of Qt are you using (try `owncloud --version`)?

**Comment by ckamm** [comment] 2016-06-21 11:37
Please also try running the owncloud client with `XDG_CURRENT_DESKTOP` set to `xfce` to check whether that's a workaround.

**Comment by mlda065** [comment] 2016-06-21 13:09
"Enabled QDBusPlatformMenu workaround" doesn't appear in my log.

Qt 4.8.6

In #4985 
> when I click on icon and wait few seconds, menu will be closed on menu re-rendering, so it is not always easy to even open settings.
I've noticed that too.

> Please also try running the owncloud client with XDG_CURRENT_DESKTOP set to xfce to check whether that's a workaround.

Do you mean this?

    matthew@Kira2 ~ $ XDG_CURRENT_DESKTOP="xfce"
    matthew@Kira2 ~ $ owncloud --logfile OClog.txt

Unfortunately it's still happening when I do that.

**Comment by guruz** [comment] 2016-06-22 16:28
@mlda065 ... in one line.

**Comment by mlda065** [comment] 2016-06-23 03:49
Is there meant to be a semicolon in that single line version? I don't know much about terminal variables, but I don't think it's actually being saved

```
matthew@Kira2 ~ $ XDG_CURRENT_DESKTOP="xfce" owncloud --logfile OClog.txt
```
Then I quit owncloud, then in the same terminal:
```
matthew@Kira2 ~ $ echo $XDG_CURRENT_DESKTOP
X-Cinnamon
matthew@Kira2 ~ $ XDG_CURRENT_DESKTOP="xfce" owncloud --logfile OClog.txt &
[1] 4381
matthew@Kira2 ~ $ echo $XDG_CURRENT_DESKTOP
X-Cinnamon
matthew@Kira2 ~ $ XDG_CURRENT_DESKTOP="xfce"; owncloud --logfile OClog.txt &
[2] 4399
[1]   Done                    XDG_CURRENT_DESKTOP="xfce" owncloud --logfile OClog.txt
matthew@Kira2 ~ $ echo $XDG_CURRENT_DESKTOP
xfce
```

**Comment by mlda065** [comment] 2016-06-23 04:08
Hmm.
With the semicolon, I think it's better. Now it's only rising to 30% (still causes visual lag), every 20 seconds. (30% of one core)

It peaks when OC polls for folder changes (every 20 seconds)
Which, in the log is:

    06-23 14:03:56:252 0x2357460 Scheduling "https://www.mdavis.xyz/owncloud/remote.php/webdav/Documents/BBB" to check remote ETag 
    06-23 14:03:56:252 0x2357460 !!! OCC::RequestEtagJob created for "https://www.mdavis.xyz/owncloud" + "/Documents/BBB" "OCC::Folder" 

In the log (with XDG_CURRENT_DESKTOP set, with semicolon) now I'm seeing lots of lines like this

    06-23 14:01:27:049 0x2357460 [31mQVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const[0m: Condition failed: action

There are about 20 lines like that for every folder, preceded (for each folder) by:

    06-23 14:03:26:876 0x2357460 Scheduling "https://www.mdavis.xyz/owncloud/remote.php/webdav/Documents/jobs" to check remote ETag 
    06-23 14:03:26:877 0x2357460 !!! OCC::RequestEtagJob created for "https://www.mdavis.xyz/owncloud" + "/Documents/jobs" "OCC::Folder" 


Is there a way to run the OC client as a background daemon without displaying the applet? I'm wondering whether that may be a temporary workaround until we solve the issue. (Currently I have to start OC to sync files, then quit it when I want to be productive.)

**Comment by ckamm** [comment] 2016-06-23 08:03
@mlda065 Thanks for testing. There currently is no option for disabling the tray menu and its updates.

My current guess is that adjusting the tray menu (the "Recent Changes" submenu during a sync or the full thing in setupContextMenu) causes significant load in cinnamon. I don't know why yet.

Maybe it's related to the older Qt version? It's not using the QDBusPlatformMenu integration plugin that was new in Qt 5.

**Comment by ckamm** [comment] 2016-06-23 08:34
@mlda065 I've added a "minimal tray" mode that can be enabled with the by setting the `OWNCLOUD_MINIMAL_TRAY_MENU` environment variable. I suspect the symptoms will go away when it is set. You need to either compile the `2.2` branch or wait for a new nightly to test it https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client

In the end, this is probably a bug in cinnamon. Yes, the client re-setups the tray menu several times per minute (to work around *other* tray menu bugs...) but doing so shouldn't cause excessive CPU use.

**Comment by mlda065** [comment] 2016-06-29 00:47
What should I set that variable to? `1`?

**Comment by cweiske** [comment] 2016-06-29 04:03
Either export the variable, or set it without semicolon:

    $ XDG_CURRENT_DESKTOP="xfce" owncloud --logfile OClog.txt

or

    $ export XDG_CURRENT_DESKTOP="xfce"
    $ owncloud --logfile OClog.txt

Using a semicolon in there does not change anything internally.

**Comment by wvandelli** [comment] 2016-06-29 10:27
Same problem here with Cinnamon. Makes the desktop pretty much unusable (or very annoying at the very least).

With:

`$  XDG_CURRENT_DESKTOP=xfce owncloud &
`
the problem is not solved for me. Maybe the hiccup frequency is lower, but I cannot guarantee.

On the other hand

> I've added a "minimal tray" mode that can be enabled with the by setting the OWNCLOUD_MINIMAL_TRAY_MENU environment variable. I suspect the symptoms will go away when it is set.

Indeed compiling the 2.2 branch and

`$ OWNCLOUD_MINIMAL_TRAY_MENU=1 owncloud &`

does eliminate all the symptoms, as well as the context menu.  :smile: 

Let me know if I can help in any way.

**Comment by ckamm** [comment] 2016-07-05 08:49
@wvandelli Thanks for testing!

That means we have confirmed the problem is related to the tray menu. However, the owncloud client doesn't do anything very special with the tray: it just uses the standard Qt API to adjust the context menu regularly.

* This might be a bug with how Cinnamon handles tray icons and menus
* This might be an issue with how Qt talks with Cinnamon
* This might be an issue with the particular pattern the client uses when updating the tray

It seems like there's little the client can do beyond detecting Cinnamon and switching on the minimal tray menu workaround. Maybe we'll figure out something for #4985 that'll also help here.

**Comment by danimo** [comment] 2016-07-05 08:54
@wvandelli Additionally, I think it would be good if you could raise a bug with the Cinnamon team and post the Bug number here.

**Comment by wvandelli** [comment] 2016-07-08 12:59
@ckamm and @danimo thank you for looking into this.

For completeness, and before submitting the bug to Cinnamon, it is maybe worth mentioning that I experience the problem only on my laptop and not on the desktop.

Nominally they have the same software installed, but I cannot guarantee the configuration to be same.
In any case, the style of the owncloud tray menus are very different. 

Desktop (no flickering)
![desktop_owncloud_client_tray_menu](https://cloud.githubusercontent.com/assets/1121642/16687875/5f868ae2-451b-11e6-9bf9-4a82047447b1.png)

Laptop (flickering)
![laptop_owncloud_client_tray_menu](https://cloud.githubusercontent.com/assets/1121642/16687876/5f9eb766-451b-11e6-8ebd-b44957b677dd.png)

I'm not sure what defines the menu style and if this actually plays a role in the issue. But, if it does, I can see that it could be a nicer workaround than disabling the menu entirely.

Thanks again.

**Comment by bartoffw** [comment] 2016-07-19 08:54
I had the same problem in Cinnamon in Linux Mint 17.3, but since I upgraded to Mint 18 (Cinnamon 3) the problem disappeared. I don't see the any processor usage from the OwnCloud client.
I use OC client 2.1.1

**Comment by ckamm** [comment] 2016-07-21 12:05
@bartoffw Thank you for the comment, I'm glad the problem resolved itself with an upgrade. Which version of Cinnamon are you using exactly now? @wvandelli is using 3.0.5 and gets the problem there.

@wvandelli If it only happens in some configurations that makes it even more likely that the problem is outside of the ownCloud client. Did you get around to playing with the style a bit? I'm also surprised that the ownCloud icon in the tray menu looks so different in the two screenshots given that you say it should be the same software.

In general I think https://github.com/owncloud/client/issues/4990#issuecomment-230421826 still applies: it's probably an issue in Cinnamon or with the Qt-Cinnamon interaction. We could automatically enable the minimal-tray workaround if we figure out under which conditions this problem occurs and can detect it reliably but I'm not sure what to do beyond that.

**Comment by ckamm** [comment] 2016-07-21 13:52
Possible workaround: https://github.com/owncloud/client/pull/5072

Note that it does not fix the underlying issue, but should make it less apparent by updating the context menu less often.

**Comment by bartoffw** [comment] 2016-07-21 15:03
@ckamm I'm using Cinnamon 3.0.7. Before the upgrade the CPU usage went to 100% for a few seconds exactly every 30 seconds. Now I don't see such behavior anymore.
I have the "Use Monochrome Icons" checked in my ownCloud client if it makes any difference.

**Comment by wvandelli** [comment] 2016-07-21 20:14
@ckamm I do not disagree with you. Unfortunately my bug with Cinnamon did not attract much attention so far. Anyway, to keep the status up to date, I moved to 3.0.7 too. The owncloud client icon in the tray try still flickers. However the desktop does not seem to freeze so badly anymore.

And, yes, I finally understood the nature of the different styles. The fancier, problematic style is activated by enabling support for "indicators" in the Cinnamon General settings.

![cinnamon_general_settings](https://cloud.githubusercontent.com/assets/1121642/17037155/cbb220f4-4f8f-11e6-8082-e8217de3b0c5.png)

**Comment by ckamm** [comment] 2016-08-15 11:44
Even though this is an upstream bug, the problem should be significantly reduced with the latest master (2.3.x) builds.

**Comment by guruz** [comment] 2016-08-24 09:58
Guys/Girls, did you try to confirm this with a 2.3 nightly?
https://owncloud.org/install/#testing-development

**Comment by guruz** [comment] 2016-08-31 08:39
Tomorrow's Linux nightlies should be based on 2.3
Please try with those.

**Comment by ehartmann** [comment] 2016-09-15 11:27
The 2.3-rc1 fixes the issue on my side.

**Closed** 2016-09-15 12:28 UTC
Labels: bug, ReadyToTest

**Comment by lestcape** [comment] 2016-10-19 18:06
Hi, I was who added the indicator support on cinnamon.
I will explain what i think that could be the cause of the flicker.

The indicators use the DbusMenuItems ids to find an id of an item between all updates cycles and the unmatching id items will be destroyed also if they exist in the next cycle, but with a different id.

So, if in some indicator client after perform an update cycle, we read differents ids for the same items we are forced to destroy it and then they will create again with a different identification. If they have the same id we don't need to destroy it.

In cinnamon/gnome shell we used Clutter. In clutter you can not paint any component if are not visible and are not in the stage, all menu creation and destruction will occurs when the menu it's visible to the user and this will create that menu boxes change his size constantly and this cause the sensation of a flicker.

Will be good then if the indicators clients will avoid the unnecesary updates and if his ids will not be reassign, to not force cinnamon to destroy it and create it again when they are visibles by the users.

Regards.
