### ISSUE TITLE
Conflict files

### ISSUE THREAD

**Issue by sasagit** [owncloud/client#4173] opened 2015-11-20 18:01 UTC
After client update to version 2.0.2 sync items were removed. After adding sync items and syncing with server some conflict files were created. The problem is that older files were downloaded from server and newer were renamed to conflict.

**Server info:**
ubuntu 10.10, Apache/2.2.16, mysql 5.1.61, PHP 5.6.8
ownCloud 8.1.1 (stable)

**Client:**
Version 2.0.2 (build 5569)

**Log from client (part involving one of the conflict files):**
```
11-20 18:29:01:599 0x8bb9728 csync_walker: file: C:/file.txt [inode=77464 size=48128]
11-20 18:29:01:599 0x8bb9728 _csync_detect_update: Checking for rename based on inode # 77464
11-20 18:29:01:599 0x8bb9728 _csync_detect_update: file: file.txt, instruction: INSTRUCTION_NEW <<=

11-20 18:29:04:009 0x8bb9728 csync_walker: file: ownclouds://owncloudserver.com/remote.php/webdav/backup_dir/file.txt [file_id=00245604oc003a2ceea4 size=47616]
11-20 18:29:04:009 0x8bb9728 _csync_detect_update: file: file.txt, instruction: INSTRUCTION_NEW <<=

11-20 18:29:06:388 0x5c60e20 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     client file: file.txt

11-20 18:29:06:624 0x5c60e20 _csync_merge_algorithm_visitor: INSTRUCTION_CONFLICT server file: file.txt

11-20 18:29:07:252 0x5c60e20 OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" -9140714609822354211 30 "racuni/2010/racun-019-2010.pdf" 221233 0 "1291811505" "0" "54724846f1d8e" "00152931oc003a2ceea4" "RDNVW" 78090 0
11-20 18:29:07:252 0x5c60e20 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:C:\file.txt"

11-20 18:29:07:881 0x5c60e20 OCC::PropagateDownloadFileQNAM::start: virtual void OCC::PropagateDownloadFileQNAM::start() "file.txt" 0
11-20 18:29:07:881 0x5c60e20 OCC::OwncloudPropagator::localFileNameClash: CaseClashCheck for  "C:/file.txt"
11-20 18:29:07:882 0x5c60e20 OCC::SyncJournalDb::setDownloadInfo: "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "file.txt" ".file.txt.~19c8" "a3f470acdf0e51dc7c3d57e7d5316a7d" 0
11-20 18:29:07:882 0x5c60e20 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction
11-20 18:29:07:883 0x5c60e20 OCC::GETFileJob::start: virtual void OCC::GETFileJob::start() OCC::BandwidthManager(0xd812c38) false false
11-20 18:29:07:883 0x5c60e20 OCC::AbstractNetworkJob::start: !!! OCC::GETFileJob created for "https://owncloudserver.com" + "/backup_dir/file.txt"
11-20 18:29:07:884 0x5c60e20 OCC::FolderWatcher::pathIsIgnored: * Discarded as is hidden! "C:/backup_dir/.file.txt.~19c8"

11-20 18:29:08:089 0x5c60e20 OCC::PropagateDownloadFileQNAM::slotGetFinished: void OCC::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://owncloudserver.com/remote.php/webdav/backup_dir/file.txt" )  FINISHED WITH STATUS 0 "" 0 47616 47616 0 "" "47616"
11-20 18:29:08:101 0x5c60e20 OCC::OwncloudPropagator::localFileNameClash: CaseClashCheck for  "C:/file.txt"
11-20 18:29:08:104 0x5c60e20 OCC::PropagateDownloadFileQNAM::downloadFinished: Created conflict file "C:/file.txt" -> "C:/file.txt_conflict-20151105-105352.txt"
11-20 18:29:08:139 0x5c60e20 OCC::SyncJournalFileRecord::SyncJournalFileRecord: OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "C:/file.txt" Retrieved inode  229691 (previous item inode:  0 )
11-20 18:29:08:139 0x5c60e20 OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" -9137562609134246323 29 "file.txt" 229691 0 "1446717232" "0" "a3f470acdf0e51dc7c3d57e7d5316a7d" "00245604oc003a2ceea4" "RDNVW" 47616 0
11-20 18:29:08:140 0x5c60e20 OCC::SyncJournalDb::setDownloadInfo: "DELETE FROM downloadinfo WHERE path=?1" "file.txt"
11-20 18:29:08:141 0x5c60e20 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start2" and starting new transaction
11-20 18:29:08:141 0x5c60e20 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "file.txt" INSTRUCTION_CONFLICT 5 ""
11-20 18:29:08:142 0x5c60e20 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\file.txt"
11-20 18:29:08:145 0x5c60e20 OCC::FolderWatcher::pathIsIgnored: * Discarded by component ignore pattern  ".file.txt.~19c8"
11-20 18:29:08:149 0x5c60e20 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/file.txt")
11-20 18:29:08:149 0x5c60e20 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) Sync running, IGNORE event for  "C:/file.txt"
11-20 18:29:08:151 0x5c60e20 OCC::FolderWatcher::pathIsIgnored: * Discarded by component ignore pattern  "file_conflict-20151105-105352.txt"
11-20 18:29:08:152 0x5c60e20 OCC::FolderWatcher::pathIsIgnored: * Discarded by component ignore pattern  ".file.txt.~19c8"
11-20 18:29:08:154 0x5c60e20 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/file.txt")
11-20 18:29:08:155 0x5c60e20 OCC::Folder::watcherSlot: void OCC::Folder::watcherSlot(QString) Sync running, IGNORE event for  "C:/file.txt"
```

**Comment by guruz** [comment] 2015-11-23 14:33
When downloading a file, the client will compare it with the locally existing file.
It will only create a conflict if the files differ.

Since it is a txt file: please ```diff -u``` the file and the conflict file and check yourself if it was maybe not a bug after all?

**Comment by sasagit** [comment] 2015-11-24 23:41
I am sorry but I am not sure how to do that on windows

**Comment by ckamm** [comment] 2015-12-10 08:52
@sasagit Could you elaborate more on how the situation happened? Which files were removed? How did you re-add them?

The client should only create conflict files if it detects a concurrent local and remote change. In this scenario we keep the server's version and move the local version to a conflict file. That's somewhat arbitrary because the client has no way of knowing which is 'newer'.

**Comment by sasagit** [comment] 2015-12-10 15:04
The problem is that the older file from server is being copied to client and replacing newer file on client marking it as conflict file.
![client](https://cloud.githubusercontent.com/assets/3532767/11718704/95c014da-9f57-11e5-9094-914e1d082389.png)
![server](https://cloud.githubusercontent.com/assets/3532767/11718705/95c56bce-9f57-11e5-922b-6f0f6dd86769.png)

**Comment by stonerl** [comment] 2015-12-12 15:57
@sasagit Apparently your local files have not been synced to the server for almost two weeks, as you can see from the timestamp.

**Comment by sasagit** [comment] 2015-12-13 20:22
OK but why is then newer file being replaced by older?! And it happened only after client update.

**Comment by stonerl** [comment] 2015-12-13 20:32
Well, it has not been replaced, the client just had to resolve a conflict: Old file from server, and newer/different file on the client with the same name. As far as I can recall, in such cases the server file wins and the local gets renamed to ``` _conflict*```.

Maybe you were hitting a bug which prevented your client from syncing some files to the server and this one got resolved with the update.

Btw. the latest client is 2.1.0

**Comment by ogoffart** [comment] 2015-12-21 14:46
maybe the file is read only on the server?  In that case the cient recover by marking the file as a conflict. But in that case client 2.1 should solve the problem by making the files impossible to change.

Please try again with 2.1


In the log file you provide, the file was added both on the client or on the server.  Maybe the database was removed?

**Comment by guruz** [comment] 2016-01-05 16:53
Closing until there is new info with 2.1

**Closed by guruz** 2016-01-05 16:53 UTC
Labels: Needs info
