### ISSUE TITLE
Issues with Google Drive

### ISSUE THREAD

**Issue by jab416171** [owncloud/client#3295] opened 2015-05-31 22:17 UTC
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. Add Google Drive via the web interface
2. Create a text file in the GoogleDrive folder from the desktop client
3. Modify this file, wait for it to sync, and then modify it again
4. You'll eventually end up with an empty file with the filename you chose, and a conflict file. It should only take one or two attempts.

### Server configuration
Operating system: CentOS 7

Web server: Apache

Database: MySQL

PHP version: 5.4.16

ownCloud version: 8.0.3.4

Storage backend: local disk

### Client configuration
Client version: 1.8.1 (build 5050), commit ee7102

Operating system: Windows 8

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
https://gist.github.com/jab416171/3b323e60fd5a189e1d2f

2. Web server access log:
```
x.x.x.2 - jab416171 [31/May/2015:16:00:11 -0600] "PROPFIND /remote.php/webdav/GoogleDrive/computers HTTP/1.1" 207 3306
x.x.x.2 - jab416171 [31/May/2015:16:00:13 -0600] "PUT /remote.php/webdav/GoogleDrive/computers/windowsthree.txt HTTP/1.1" 500 8247
x.x.x.2 - jab416171 [31/May/2015:16:01:17 -0600] "PROPFIND /remote.php/webdav/GoogleDrive/computers HTTP/1.1" 207 3306
x.x.x.2 - jab416171 [31/May/2015:16:01:19 -0600] "GET /remote.php/webdav/GoogleDrive/computers/windowsthree.txt HTTP/1.1" 200 -
x.x.x.2 - jab416171 [31/May/2015:16:01:30 -0600] "PROPFIND /remote.php/webdav/GoogleDrive/computers HTTP/1.1" 207 3306
```

3. ownCloud log (data/owncloud.log):
```
"Error calling PATCH https:\/\/www.googleapis.com\/drive\/v2\/files\/abcd?setModifiedDate=true: (404) File not found: abcd"
```
4. Client log (located in the ownCloud directory)
```
#=#=#=# Syncrun started 2015-05-31T16:00:16 until 2015-05-31T16:00:34 (18205 msec)
|0|GoogleDrive/computers/windowsthree.txt|INST_SYNC|Up|1433109614|556b818101a84|139||2|Error downloading https://x.x.x/remote.php/webdav/GoogleDrive/computers/windowsthree.txt - server replied: Internal Server Error|0|120|1433108097|556b818101a84|00000167ocyjxgsbqy4u|INST_NONE|
#=#=#=# Syncrun started 2015-05-31T16:01:22 until 2015-05-31T16:01:31 (9013 msec)
#=#=#=# Syncrun started 2015-05-31T16:01:36 until 2015-05-31T16:01:40 (3618 msec)
```

**Comment by jab416171** [comment] 2015-06-01 01:52
It looks like this is a duplicate of owncloud/core#15092. If that's the case, feel free to close this out.

**Comment by LukasReschke** [comment] 2015-06-01 05:37
This seems indeed to be a duplicate of said issue. Generally speaking in case of rxternal storage problems it's more likely to be a server issue :)

Anyways, thanks for reporting this issue back to us. As it is linked now to the other issue I will close this.

**Closed by LukasReschke** 2015-06-01 05:37 UTC
