### ISSUE TITLE
[testpilotcloud] [Windows] Logo looks strange in installer

### ISSUE THREAD

**Issue by haukman** [owncloud/client#6006] opened 2017-09-08 06:55 UTC
I just tried the latest nightly for the desktop client 2.4 on my Win 10 and discovered that the ownCloud logo looks a bit strange during install process:

![grafik](https://user-images.githubusercontent.com/25486818/30199509-567fc44c-9473-11e7-90b9-fa6038b65891.png)

**Comment by michaelstingl** [comment] 2017-09-08 07:15
No change for a long time: https://github.com/owncloud/client/commits/master/admin/win/nsi/page_header.bmp

What is "but strange"?

**Comment by michaelstingl** [comment] 2017-09-08 07:18
Oh, this is testpilotcloud theming. @jnweiger Do we have a testpilotcloud header image for the NSIS installer?

**Comment by haukman** [comment] 2017-09-08 07:18
The cloud is in front of the "ownCloud" text. Looks somehow incorrect.

Thought it might be a formating issue or so - if not, it´s fine for me :) Just wanted to share my impression

**Comment by ogoffart** [comment] 2017-10-17 10:47
Cloçsing as duplicate of #6010

**Closed by ogoffart** 2017-10-17 10:47 UTC
Labels: bug, sev3-medium
