### ISSUE TITLE
[QA] 2.9 doesn't respect local settings (LANG)

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8740] opened 2021-06-16 08:12 UTC
Seen with ownCloud-2.9.0-daily20210607.4309.AppImage on openSUSE 15.2

Steps done:
- set env var LANG=de_DE.UTF-8
- start the AppImage

Result:
Client language remains english.

**Comment by TheOneRing** [comment] 2021-06-16 08:32
@fmoc shouldn't the system report deDe and we load that? I assume the reported issue is caused by our locale override?

**Comment by TheOneRing** [comment] 2021-06-23 12:25
@gabi18 could you retest since https://github.com/owncloud/client/commit/a27addb699a1dd431ffaed70b4c7ebeb078823cf was merged?
Also are translations available in the new lang picker in the settings ui?

**Comment by gabi18** [comment] 2021-06-23 15:22
Confirmed that the locale settings (e.g. LANG=de_DE.UTF-8) are respected with 2.9 compiled from master.

The translations for the language picker are missing:

![Screenshot_20210623_172108](https://user-images.githubusercontent.com/75983861/123123870-796ec080-d447-11eb-8104-72e7c174ff20.png)

**Comment by TheOneRing** [comment] 2021-08-13 14:26
Needs fixing on transifex

**Closed by TheOneRing** 2021-08-13 14:26 UTC

**Comment by fmoc** [comment] 2021-08-13 14:29
I tested the daily 2.9 and 2.10 AppImages recently. Should be working now. See also #8839.
