### ISSUE TITLE
Abusive CPU Usage

### ISSUE THREAD

**Issue by theonlydoo** [owncloud/client#4915] opened 2016-05-27 15:05 UTC
### Expected behaviour
Not using 100% CPU from 2 cores all the time while there is no sync

### Actual behaviour
The exact opposite

### Steps to reproduce
1. Fedora 23
2.  Owncloud client latest
3.  htop

### Server configuration
Operating system:
Fedora23
Web server: 
Nginx
Database:
Mariadb
PHP version:
5.6
ownCloud version:
Latest
Storage backend:
filesystem
### Client configuration
Client version:
```
libowncloudsync0-2.2.0-9.1.x86_64
owncloud-client-2.2.0-9.1.x86_64
owncloud-client-l10n-2.2.0-9.1.x86_64
```
Operating system:
Fedora23
OS language:
Fr
Installation path of client:
/usr/bin/owncloud
![selection_294](https://cloud.githubusercontent.com/assets/1903124/15611996/3d3f4870-242d-11e6-931c-b9691a4f6fab.png)

**Comment by FlorentCoppint** [comment] 2016-05-27 15:18
same thing on Ubuntu 16.04, owncloud process taking 100% of 1 core...

**Comment by bhcopeland** [comment] 2016-05-27 18:26
yup, same issue here.

Arch Linux
2.2.0

**Comment by prairietree** [comment] 2016-05-28 17:00
I do not want to abuse this comment, but I typed up all this information before I found this similar issue open. In addition to what is mentioned here I am also having excessive ram usage after a while of running ownCloud client.

## Expected behaviour
OwnCloud Linux client maintains it cpu and ram usage so as to keep the system responsive.

### Actual behaviour
On a large new sync 40 GB of mostly pictures cpu usage stayed at 90+%, and ram usage will eventually start climbing tell the system is unresponsive.

### Steps to reproduce
1. Install the latest linux owncloud client on Kubuntu 16.04 or 14.04.
2. Try to sync 40 or so GB of mostly pictures.
3. 

### Server configuration
Operating system: Ubuntu server 14.04

Web server: Apache

Database: MySql

PHP version: 

ownCloud version: 9.0.1

Storage backend:

### Client configuration
Client version: "Version 2.2.0%nil (build 1605)."

Operating system: Linux Kubuntu 16.04

OS language: English

Installation path of client: /usr/bin/owncloud

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

```I will try to rerun it latter with logging enabled. I did not know I needed to enable it.```

2. Web server error log:

3. ownCloud log (data/owncloud.log):

### The story

I am having trouble with high cpu usage when running own cloud client on Kubuntu. I was having the same trouble with Kubuntu 14.04 so I upgraded to Kubuntu 16.04 last week, and installed the latest ownCloud client. After I added two syncs, one of less then 30 MB and one of about 40 GB. I noticed right away the system became very unresponsive. I looked at the processes cpu usage and did not see anything very high so I tried to do some other stuff my system and it locked up and I had to force a restart. A few minutes later the system locked up again but I had a terminal open and was able to shut it down from there. This morning I started the computer up again and let it set for 10 minutes or so and then looked at it. The ownCloud process was only using 8-12 percent of the cpu and nothing else in the system monitor was using much. But when I looked at the System Load tab three cpu threads where stuck at 100 percent and the fourth was jumping between 60 and a 100 percent. So I am not sure why the discrepancy. During that time the system was really slow. It took 3 to 5 minutes to load fire fox. There was also lots of disk activity. I paused both syncs in ownCloud but that did not help, so I stopped the ownCloud process and the cpu usage dropped down to basically zero over the next few seconds.

After that I tried to restart ownCloud client but it would not come up. The icon appeared on the system try and would say in a pop up that syncing was disabled but clicking on it or ownCloud in the start menu would do nothing.

I then restarted Kubuntu and ownCloud client popped right up on the screen, both syncs were paused. I waited a minute, then started the smaller sync. Most of the cpu's hit 60-80 percent but then went right back down. I waited a few minutes and then started the large sync. It quickly jumped up to one cpu running about a 100 percent (not always the same one), but the others were low. After a minute or so two cpu's hit 100% and basically stayed there. In about an about another minute we had three cpu's at 100%. It varied a little bit after that. Some times they would all be 100% and other times only one would be 100% and the rest would be less. But for the most part they stayed maxed out. The ownCloud process itself seemed to only take about 15% most of the time according to the process monitor. The system stayed responsive for a few minutes more. At some point all network traffic dropped off, but the cpu usage stayed maxed out. The outbound network traffic eventually came back but at a fairly slow rate.

After about ten minutes of this the ram usage suddenly started climbing so I switch to the process tab and it was the ownCloud process that was using most of it. The system has four GB of ram and had been running just under one including ownCloud client. By the time ownCloud client hit three GB the system was mostly unresponsive. It made it up to 3,39x,xxx KB before even the screen would not refresh. I could not get to another console, so I had to hold the power button to force it down. When it restarted I paused the large sync. 

The smaller sync of 30 MB or less seems to be working.

**Comment by guruz** [comment] 2016-05-30 06:07
2.2.0 has a known bug with memory and possibly CPU.
2.1.1 does fix this.
Did you try a nightly build?

**Comment by FlorentCoppint** [comment] 2016-05-31 10:45
2.2.1~nightly2016531-1.1 seems to solve the problem on Ubuntu 16.04.
Available here : http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/xUbuntu_16.04/amd64/

**Comment by FlorentCoppint** [comment] 2016-05-31 11:10
2.2.1~nightly2016531-1.1 seems to solve the problem on Ubuntu 16.04 but CPU usage is always very high sometimes (using 100% of 1 core for a few minutes, then falls to 0%...).

**Comment by prairietree** [comment] 2016-05-31 13:31
Where can I download the nightly builds?

**Comment by FlorentCoppint** [comment] 2016-05-31 13:33
@prairietree http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/

**Comment by prairietree** [comment] 2016-05-31 13:38
Thanks, that was fast. I downloaded owncloud-client_2.2.1~nightly2016531-1.1_amd64.deb and will give it a try and let you know what happens.

**Comment by prairietree** [comment] 2016-05-31 15:01
Installed build Version 2.2.1nightly2016531 (build 1660), and monitored the same large sync for 30 minutes. Most of the time cpu usage is very little but ram usage has been climbing very slowly. However nothing like it was before. I will monitor the ram usage and let you know if it climbs to some unreasonable amount, but at this point it looks like it is fixed in this build.

A big thanks to who ever fixed that and all the other developers of this client.

**Comment by guruz** [comment] 2016-06-01 06:20
Great to hear!

**Closed by guruz** 2016-06-01 06:20 UTC
Labels: Needs info

**Comment by simopal6** [comment] 2016-06-17 08:23
Using 2.2.1 (compiled from git) I get 100% CPU usage while the client scans the filesystem for updates--which is also strange, by the way, since I enabled libinotify, but apparently what it does is that when it detects a file change, it starts a full directory tree scan.

**Comment by theonlydoo** [comment] 2016-06-17 08:25
this was fixed on the latests releases on the repos, check the 2.2.1-13

**Comment by simopal6** [comment] 2016-06-17 08:26
I will, thanks! (I also noticed that there is a recent issue about this, https://github.com/owncloud/client/issues/4967)

**Comment by jabdoa2** [comment] 2016-06-17 08:48
@theonlydoo Where was the problem in 2.2.1 fixed? Which commit?

**Comment by theonlydoo** [comment] 2016-06-17 09:12
Dont know rly but i don't have it anymore on f23 package

**Comment by guruz** [comment] 2016-06-21 10:08
2.2.2 which is coming out today has more improvements..

@simopal6 Can you try 2.2 git branch?

**Comment by simopal6** [comment] 2016-06-21 10:41
I compiled 2.2.2 from git, and it seems better. What happens is:
* I add/modify/delete a file.
* OwnCloud detects the change, and starts scanning the filesystem. At this point the CPU goes to 100%. Before 2.2.2, I have a feeling this step would take much longer, now it's 5-10 seconds.
* OwnCloud finds the changed file, and syncs with the server.
* CPU usage goes back to 0.

It still seems unnecessary to me that OwnCloud scans the filesystem instead of just synchronizing the file for which it received the change notification.

**Comment by guruz** [comment] 2016-06-21 12:18
@simopal6 Great to hear it is improved. We have it planned on https://github.com/owncloud/client/issues/2297

FYI @ckamm

**Comment by Dominique-M** [comment] 2016-11-13 22:00
Since upgrade to Ubuntu 16.10 (using gnome-session-flashback as desktop), with ownCloud client 2.2.2+dsfg-1 (yakkety), ownCloud goes regularly around 100% CPU, and then indicator-applet goes still higher, making the system little responsive. This didn’t happen with Ubuntu 16.04.

**Comment by guruz** [comment] 2016-11-15 08:37
@Dominique-M the current client version is 2.2.4, downloadable from owncloud.org
You could also install a nightly build of 2.3 if you dare to (please be cautious and have backups etc.) https://owncloud.org/install/#testing-development

In any case, I'd report this to Ubuntu if I was you. Maybe their indicator-applet has some inefficiencies?

**Comment by Dominique-M** [comment] 2016-11-15 18:36
Le 15/11/16 à 09:37, Markus Goetz a écrit :
>
> @Dominique-M <https://github.com/Dominique-M> the current client 
> version is 2.2.4, downloadable from owncloud.org
>
Done just now, thanks a lot! looks much better. ownCloud client 2.2.4 
keeping an eye in the background using usually 0.7 % CPU (says top). Not 
much more if I edit a file.
>
> You could also install a nightly build of 2.3 if you dare to (please 
> be cautious and have backups etc.) 
> https://owncloud.org/install/#testing-development
>
Am OK with 2.2.4 apparently.
>
> In any case, I'd report this to Ubuntu if I was you. Maybe their 
> indicator-applet has some inefficiencies?
>
Was already done.

**Comment by lemmy04** [comment] 2016-12-29 07:53
I'm experiencing 100% usage on one CPU core ever so often, running the 2.2.4 client on openSUSE.

**Comment by ShamimIslam** [comment] 2017-01-29 17:23
Fedora 24, Oc sync 2.2.4, KDE plasma.

OC sync continues to use 2 cores at 100%.

Runs my cpus at 92 degrees. Fan runs constantly. I have 3 repos. Even with zero changes being made, the client runs for hours and hours. The high cpu stops once i shut down the client.

This is insane.

**Comment by lemmy04** [comment] 2017-02-07 15:10
I didn't think the linux client did overlay icons... if so, for which filemanager on which desktop?
