### ISSUE TITLE
Windows XP Client: shortcut file (extension .lnk) has wrong size/corrupted

### ISSUE THREAD

**Issue by nekoal** [owncloud/client#2792] opened 2015-02-07 19:57 UTC
### Expected behaviour
Shortcut files (extension .lnk) syncronized without checking its contents as others files.
Or
Shortcut files excludes from syncronization.

### Actual behaviour
Activity log shows size of object, not size of shortcut file. This cause shortcut to folders has 0 bytes and corrupted on server. Shortcut with cyrillic characters in filename detects as missed/changed on server and syncronized again and again.

### Steps to reproduce
1. Create shortcut for folder/file with standart Windows ways and place in sync folder. Watch size of shortcut.
2. Wait for syncronization. In activity log watch size of chortcut.
3. Shortcut with cyrillic characters in filename syncronized again and again.
4. When downloads folder shortcut from server it has zero size and not exist in desctination folder.
Shortcut with cyrillic characters in filename normally downloads.

### Server configuration
Operating system: Windows XP SP3

Web server: Apache 2.0 

Database: MySQL

PHP version: 5.3.5

ownCloud version: 7.0.4

Storage backend: NTFS

### Client configuration
Client version: 1.8.0-nigntly20150205

Operating system: Windows XP SP3

OS language: Russian

Installation path of client: D:\Program Files\ownCloud

### Logs
2. Apache error log has no records at this time.
1. Output of `owncloud --logwindow`:
3. ownCloud log (data/owncloud.log):

Folder shortcut:

02-08 04:33:49:746 0x60afb1c csync_ftw: Uniq ID from Database: Trav.lnk -> 54d6460436061
02-08 04:33:49:746 0x60afb1c csync_walker: file: E:\dbases/Trav.lnk [inode=36961 size=388]
02-08 04:33:49:746 0x60afb1c _csync_detect_update: Database entry found, compare: 1382081681 <-> 1382081681, etag: 54d6460436061 <-> 54d6460436061, inode: 36961 <-> 36961, size: 388 <-> 0, perms:  <-> RDNVW
02-08 04:33:49:746 0x60afb1c _csync_detect_update: file: Trav.lnk, instruction: INSTRUCTION_NONE <<=

{"reqId":"54d6460437a3b","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/dbases\/Trav.lnk' !!! \ncache: Array\n(\n    [fileid] => 67\n    [storage] => home::bertix\n    [path] => files\/dbases\/Trav.lnk\n    [parent] => 33\n    [name] => Trav.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 0\n    [mtime] => 1423328771\n    [storage_mtime] => 1423328771\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54d64603ea2e7\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1382081681\n    [size] => 0\n    [etag] => 54d6460436061\n    [storage_mtime] => 1382081681\n    [permissions] => 27\n    [parent] => 33\n)\n","level":0,"time":"2015-02-07T17:06:12+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/dbases\/Trav.lnk"}

File shortcut:

02-08 04:33:49:809 0x60afb1c csync_ftw: Uniq ID from Database: - ODBC.lnk -> 54d67682ac06f
02-08 04:33:49:809 0x60afb1c csync_walker: file: E:\dbases/- ODBC.lnk [inode=36988 size=1578]
02-08 04:33:49:809 0x60afb1c _csync_detect_update: Database entry found, compare: 1274707019 <-> 1274707019, etag: 54d67682ac06f <-> 54d67682ac06f, inode: 36988 <-> 36988, size: 1578 <-> 53248, perms:  <-> RDNVCK
02-08 04:33:49:809 0x60afb1c _csync_detect_update: file: Источники ODBC.lnk, instruction: INSTRUCTION_EVAL <<=

{"reqId":"54d674a4a26ab","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/dbases\/\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438 ODBC.lnk' !!! \ncache: Array\n(\n    [fileid] => 364\n    [storage] => home::bertix\n    [path] => files\/dbases\/\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438 ODBC.lnk\n    [parent] => 33\n    [name] => \u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438 ODBC.lnk\n    [mimetype] => application\/octet-stream\n    [mimepart] => application\n    [size] => 1578\n    [mtime] => 1274707019\n    [storage_mtime] => 1274707019\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54d674659cc4a\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => application\/octet-stream\n    [mtime] => 1423340708\n    [size] => 1578\n    [etag] => 54d674a4a05f3\n    [storage_mtime] => 1423340708\n    [permissions] => 27\n    [parent] => 33\n)\n","level":0,"time":"2015-02-07T20:25:08+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/dbases\/%D0%98%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B8%20ODBC.lnk"}

**Comment by danimo** [comment] 2015-02-07 20:11
The template has all those fields for a reason. We at least need to know the client version.

**Comment by nekoal** [comment] 2015-02-07 21:19
Updated. I know it is not stable version - also localization and shell extention don't work, installer and temporary file present in ownCloud\shellext. But issue https://github.com/owncloud/client/issues/2648 seems fixed.

**Comment by danimo** [comment] 2015-02-08 00:06
Please retry with http://download.owncloud.com/desktop/daily/owncloud-1.8.0.4697-nightly20150207-setup.exe. Translations should work again, as should icon (windows restart may be required). Looking into the temp files.

**Comment by danimo** [comment] 2015-02-08 03:41
Temp files are related to the context menu not registering (NSIS then tries twice to register those on startup using said file, then deletes it).

It seems that the symbols required by `regsvr32` do not get exported despite being specified in the .def file. This needs investigation

//cc @jturcotte

**Comment by nekoal** [comment] 2015-02-08 18:23
I wonder.. When 1.8.0-nigntly20150205 uninstalls it tried unregister x64, but files and OS x86. Also OCOverlays_x86.dll and OCUtil_x86.dll present in shellext after uninstall.
![ownc_del0205_1](https://cloud.githubusercontent.com/assets/10899904/6097631/350ed618-b000-11e4-898d-31f12d3e6c21.PNG)
![ownc_del0205_2](https://cloud.githubusercontent.com/assets/10899904/6097632/351885dc-b000-11e4-8738-a92bca18d47a.PNG)
regsvr32 /u for this files failed.
![ownc_del0205_3](https://cloud.githubusercontent.com/assets/10899904/6097630/34fe6828-b000-11e4-94f1-a717f1da324b.PNG)
1.8.0-20150207 translations works.

**Comment by danimo** [comment] 2015-02-09 12:55
@ogoffart can you take a look at the lnk issue itself? Hypothesis: Qt treats lnk files as links (which we usually do not sync).

**Comment by ckamm** [comment] 2015-02-12 09:25
I can reproduce this issue. Csync seems to see the correct file size (about 1k) but later we try to upload my shortcut file in several chunks (progress bar shows 22 mb) and fail with "Unknown error".

**Comment by ckamm** [comment] 2015-02-12 09:33
While the Qt documentation says

> On Windows, symlinks (shortcuts) are .lnk files. The reported size() is that of the symlink (not the link's target)

QFileInfo::size() on lnk files actually gives the target's size due to https://bugreports.qt.io/browse/QTBUG-24831.

**Comment by nekoal** [comment] 2015-02-13 05:02
Tested 1.8.0-20150213(4715). Shortcuts to folder syncronized with real size of lnk files. Conflicted shortcut file was not syncronized. It was downloaded but not renamed from temporary name. 
Create new, syncronizing then deleting shortcut file on other side tested in both directions - ok. Create new, syncronizing then deleting shortcut file on the first side - problem

Also other Windows symlink (.url .pif and so on) may be also need tests.

**Comment by nekoal** [comment] 2015-02-13 07:12
@danimo 1.8.0-nightly20150213(4715) on Win7 cause crashes if shell extention enabled. Explorer crashes when any syncronize status icon visible in folder and client works. May be connected with yesterday icon changes.
Also all run processes yesterday and today on some condition show same error:

![oc_c_142](https://cloud.githubusercontent.com/assets/10899904/6183390/9a673a04-b38f-11e4-8c2c-04bb0c6f9350.png)
It seems connected with shell extention too.

**Comment by ckamm** [comment] 2015-02-13 08:27
@nekoal I tried these two cases and could not find any issues:

Case 1:
* Put a shortcut file into a sync folder
* Wait for it to upload, then disable the client
* Manually upload a different shortcut file to the server
* Change the local shortcut file in a different way
* Start the client again
* Result: conflict file, as expected

Case 2:
* Put a shortcut file into a sync folder
* Wait for it to upload
* Delete it from the server
* Result: shortcut is deleted locally

Could you describe how to reproduce your issues in detail?

The other file types you mentioned should not be a problem because Qt does not treat them in a special way.

**Comment by nekoal** [comment] 2015-02-13 10:35
My story: I have 2 clients and server now. In "manually syncronized" (it was no full mirror because .mdb files was modified by Microsoft Access on open) folder on both clients was .lnk file to ODBC Control Panel (with cyrillic characters in filename). Both files has same filename but linked to different places. First to ".cpl" (less size, opens slow), Second to "%SystemRoot%\system32\odbcad32.exe" (more size, opens fast).
6 days ago only one client was connected to server and tried upload this .lnk file again and again (reported at issue start). I added .lnk file in exclude list to stop spaming activity log. It seems originally loaded .lnk files (this and zero-size .lnk to folder) on server was not deleted.
In 2 days I connect second client with same exclude list to server. Some .mdb files shows conflicts which was resolved manually. Of course, .lnk files were not syncronized.
Today I install latest nightly build on second client and remove .lnk from exclude list. Syncronization downloads zero-size folders .lnk (they were not present in second client and not deleted on server) and normal .lnk to file. Then it can't syncronize this ODBC Control Panel shortcut. Copy from server (and first client) was downloaded to temporary file. Then activity log show "source file not exist" error repeated on each syncrun.
Then I rename orignal .lnk file on second client adding "_" character. File from server was downloaded successfully on next syncrun but renamed "_" file got "File moved" verdict repeated on each syncrun and was not uploaded to server. It's hard to say in detail next actions with "_" file.
I deleted zero-size folder shortcuts on second client, it was syncronized to server, created backup of .lnk on first client, install latest nightly build remove .lnk from exclude list on first client . Then folder shortcuts from first client successfully uploaded to server and second client.
Then tested #1938 schemes.
create on first client, sync, delete on second client = ok
create on second client, sync, delete on first client = ok
create on second client, sync, delete on second client = first client don't really delete file, then simular to my case "File moved." message.

**Comment by ckamm** [comment] 2015-02-13 11:30
@nekoal 

It looks to me like the .lnk files were still on the server when you removed the *.lnk pattern from the exclude list. That's why the client then started downloaded them.

If you suspect that the file names may be an issue, please try whether the same happens with regular files (i.e. use X.txt instead of X.lnk).

Regarding your last point: I can't reproduce the issue. When I have two clients and delete a lnk on one of them, it shows up as 'Deleted' in the activity log, is deleted from the server and the second client and never comes back. It'd be interesting to see the log here. Could you start your client with "--logfile log.txt" and upload or send the log file?

**Comment by nekoal** [comment] 2015-02-13 13:31
I agree about zero-size folder shortcuts. But I don't know reason why original file Odbc.lnk on second client was not renamed to "_conflict". May it be in rename/delete functions in some way using target path and fails?

Logfile
https://gist.github.com/nekoal/90e3217b4a2b94d35e78
I reproduce issue again. incorr.mdb.lnk - previous experiment, News.mdb.lnk - current expirement. Screenshot shows 'Deleted' file really present in folder.
![oc_news](https://cloud.githubusercontent.com/assets/10899904/6187776/e6f11d28-b3c5-11e4-9dc4-b36b468e102c.PNG)
Forced syncronization over pause/resume.
![oc_news2](https://cloud.githubusercontent.com/assets/10899904/6187777/e7158320-b3c5-11e4-92e9-4f29a5d99bfe.PNG)

**Comment by nekoal** [comment] 2015-02-13 21:46
@ckamm Insight about incorr.mdb.lnk and News.mdb.lnk:
Shortcut target from sync folder. On one client sync folder has path E:\dbases, on second D:\dbases. Summary, create on first client, sync, delete on second client = manually deleted shortcut which target not exists, client deleted file which target exists.
 create on second client, sync, delete on first client = manually deleted shortcut which target not exists, client deleted file which target exists.
 create on second client, sync, delete on second client = manually deleted shortcut which target exists, client can't delete file which target not exists.
May be you can't reproduce issue because your folder path same on both clients or target present on both clients.

Some experiments:
use X.txt instead of X.lnk: 
  create standart named empty text file, wait for sync, rename to X.txt, modify, wait for sync^, pause one client, modify both files = conflict file created as expected
  ^no renaming empty text file on other side, empty file deleted then renamed non-empty file downloaded = unexpected, but no error
create shortcut to object "My Computer" = don't syncronized to server
create shortcut to object "Network" = don't syncronized to server
copy shortcut to my ADSL connection = don't syncronized to server
copy shortcut to my VPN connection = don't syncronized to server
copy shortcut to Microsoft Lync Attendant (guid as target) = syncronized to server and other client
Client behavior depends from shortcut content.

**Comment by nekoal** [comment] 2015-02-14 08:22
New experiment with same result:
pause client, create 2 shortcuts, rename target of one shortcut = shortcut which target not renamed successfully upload to server, shortcut which target renamed show error
02-14 16:11:51:883 0x5807fc8 syncengine.cpp:794 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "120330wv__.rar.lnk" 3 "Файл Перемещён"

**Comment by ckamm** [comment] 2015-02-14 09:04
Thanks @nekoal, the shortcut I made did indeed have a valid target on both machines. I'm not around next week but will try to reproduce the week after.

**Comment by ckamm** [comment] 2015-02-25 09:22
@nekoal I can reproduce that links to nonexistant targets and objects like 'My Computer' don't upload correctly. Thanks for the extra details! I will look at it now.

**Comment by nekoal** [comment] 2015-03-01 16:00
Unfortunately, I can't try latest nightly builds (4788,4789,4791) on Windows XP 'cause it fails to run client after installation. I still use build 4715 on Win XP computer. I'll create 2 new tickets about it.
Tests on Win7 client (1.8.0.4791-nightly20150301):
shortcut to object "My Computer" = sync ok, delete it from other side = sync ok (really deleted)
shortcut to object "Network" = sync ok
shortcut to my ADSL connection = sync ok
shortcut to my VPN connection =  sync ok
shortcut to Microsoft Lync Attendant (guid as target) = sync ok
#1938 schemes = ok, ok (really deleted)
upload two shortcuts with 1) existent target, 2) non-existent target = ok, ok
then delete it =ok, ok
create conflict with shortcut with invalid target = need some time to design test as it was in my story

**Comment by lmaestro** [comment] 2015-03-06 07:31
@nekoal Are you able to reproduce this problem with the latest version?

**Comment by nekoal** [comment] 2015-03-06 09:17
Yes, I can reproduce different behavior of client dependent on shortcut target with 1.8.0.4812-nightly20150306. 
I just tried complex test about 4 conflicted shortcuts:
c1 - client 1 (Win 7), c2 - client 2 (Win XP)
Steps to reproduce:
1) create 4 shortcuts on c1
2) wait for syncrun complete
3) pause clients on c1 and c2
4) modify shortcuts on c1 and c2:
a) on c1 set target not exist on c1 and exist on c2; on c2 set target not exist on c1 and exist on c2
b) on c1 set target exist on c1 and not exist on c2; on c2 set target not exist on c1 and exist on c2
c) on c1 set target not exist on c1 and not exist on c2; on c2 set target not exist on c1 and exist on c2
d) on c1 set target exist on c1 and exist on c2; on c2 set target not exist on c1 and exist on c2
5) start c1 client
6) wait for syncrun complete on c1
7) start c2 client
Expected behavior: 4 confilct files on c2
Actual behavior: shortcut b) conflict file created, no repeat download after pause/resume; shortcut a) confilct file created, but downloaded again on next syncrun, then no repeat downloading; shortcut c) and shortcut d): temporary file downloded from server but client can't rename shortcut from c2 to conflict file and then rename temporary file  to normal name.

**Comment by ckamm** [comment] 2015-03-11 09:55
@nekoal Thanks for your test case! I could reproduce and fix the problem. All four conflict combinations work for me now; I'll mark this as readytotest once the patch is merged.

**Comment by dragotin** [comment] 2015-03-11 13:28
Well, yes, the screenshot does not really indicate an error, because all the entries reference different files. The upload was probably triggered by the DST bug.

**Comment by nekoal** [comment] 2015-03-12 05:06
@ckamm Thank you. Tested 1.8.0.4826-nightly20150311 and 1.8.0.4827-nightly20150312. For all 4 files made conflict files in both directions. Other tests schemes also work for me. I'm out of ideas how to test it more.
This issue can be closed. As well as #1938 (I can't reproduce it with client builds 4764 and later, so it fixed before 1.8.0-beta2).

P.S. About empty lines - it's lines when conflict file sucessfully created. It don't bother me much. I'm not sure may be this is bug in translations. I rather worry about seconds not showing in activity log on Windows 7. Previous screenshot was from Windows XP, new screenshot from Windows 7.
![oc_4shortcut_4827](https://cloud.githubusercontent.com/assets/10899904/6612467/99b7a5b6-c8b7-11e4-946e-86da3bdd1286.png)

**Comment by ckamm** [comment] 2015-03-12 05:27
@nekoal Thanks, that sounds good!

I'll look at the other issues you mentioned.

**Closed by ckamm** 2015-03-12 05:27 UTC
Labels: bug, ReadyToTest

**Comment by nekoal** [comment] 2015-03-12 18:37
About seconds. I check Control Panel on both Windows. Windows XP has only one format string for time and 2 strings for date (full and short). Windows 7 has 2 strings for date and 2 strings fo time. It seems client select by default short string for date and short string for time (without seconds). I see some logic but client ignored changing format in Control Panel.

**Comment by VincentvgNn** [comment] 2015-04-16 18:35
@nekoal 
The issue of the missing seconds in the client's Sync Activity log has recently been solved since client version 1.8.0.4938-nightly20150411. See issue #2535.
In the client seconds are added to the Windows short time format.

**Comment by nekoal** [comment] 2015-04-20 06:52
@VincentvgNn Thank you for information. Well, now on my Win 7 computer still 1.8.0.4827 and I think bug with seconds better than bug with deletion of files in 1.8.0.4893. I already test updating on other computer.. When client already show 4893 as possible update then after manual install builds 49xx starts automatic update (or rather rollback) to 4893 which I want to avoid. So I'll test it later.

**Comment by nekoal** [comment] 2015-09-20 09:48
OK
