### ISSUE TITLE
Contradicting download status messages

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2521] opened 2014-11-20 07:42 UTC
During syncing in the "Account" tab the download status is displayed. It shows two estimated times till completion. Not sure what the left time (below progress bar) is for but the right time is denoted with "Total time left". It should thus always be >= than the other one. Correct?

![contradiction](https://cloud.githubusercontent.com/assets/2737900/5121289/a1491cd0-7090-11e4-9999-2714714257a6.png)
Here the time on the left is 4m18s while total time is 3m10s.

Using 1.7.0 build 4162 on Windows7 32bit.

**Comment by ckamm** [comment] 2015-03-27 08:12
It's a duplicate of #2328. I have a patch that's in review.

**Closed by ckamm** 2015-03-27 08:12 UTC
Labels: bug
