### ISSUE TITLE
windows sync client crashes if attached file is in sync folder

### ISSUE THREAD

**Issue by mistay** [owncloud/client#7308] opened 2019-07-11 22:01 UTC
syncing a file w/ the filename below results in crashing windows sync client. testsed on current win sync client v2.5.4 build 11415 

logs attached

file is not accepted by github and cannot be put into zip file. anyways this is a standard text from ebay austria, so saving an e-mail from ebay generates that special chars in filesys.

[windows_client_v2.5.4_build_11415_log.txt](https://github.com/owncloud/client/files/3384137/windows_client_v2.5.4_build_11415_log.txt)
[server.log](https://github.com/owncloud/client/files/3384138/server.log)

✅ Thinkpad E590 ist online! 🛎️ Prüfen Sie Ihre Sonderaktionen und verdienen Sie mehr!.eml

**Comment by ckamm** [comment] 2019-07-12 11:43
Thanks for the report. Possibly it's already fixed for 2.6.0, I'll try to reproduce.

**Comment by ckamm** [comment] 2019-07-12 11:56
@mistay I cannot reproduce the problem with 2.5.5 or 2.6.0. Could you try whether the problem is fixed in either of these for you? You can get daily snapshots from http://download.owncloud.com/desktop/daily/ and the "testpilotcloud" versions are suitable for installing in parallel to your existing installation.

**Comment by TheOneRing** [comment] 2020-03-17 09:11
The issue has been in Needs info for quite some time.
Please reopen the issue if it still exists.

**Closed by TheOneRing** 2020-03-17 09:11 UTC
Labels: Needs info, Windows, bug, p3-medium
