### ISSUE TITLE
Don't sync hidden files for Windows and OS X.

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2086] opened 2014-08-21 14:23 UTC
For a customer for OS X, we're currently implementing that (```UF_HIDDEN``` files for temp files created by MS Word) hidden files (not the ```.``` dot hidden files) .

Find out if we want to do that for Windows too.

CC @MTRichards @karlitschek @dragotin

**Comment by cdamken** [comment] 2015-03-16 11:30
:+1:

**Comment by guruz** [comment] 2015-07-09 10:55
There is a pull request here for the Windows part: https://github.com/owncloud/client/pull/3428

CC @dragotin

**Comment by moscicki** [comment] 2015-07-09 15:45
@MTRichards: it would be really great to understand where we are heading with hidden files (and similar sync issues such as *.tmp files going back and forth the ignored file patterns etc). as @guruz says, on Linux this is an entirely different use-case for hidden files and it would be good to make a clever distinction.

It would be great to be able to summarise the sync behaviour on a sheet of A4 paper, so anyone could understand what to expect from the system. My worry is that as the system evolves and change subtly the semantics we are potentially breaking user's expectations (either explicit or implied by their usage experience).

**Comment by dragotin** [comment] 2015-07-10 09:46
@moscicki I agree, we should have this one-pager describing the sync rules.

Concerning the hidden files, we always had the strategy to *not* sync them. However, there was a mistake in the implementation that made them sync under some circumstances.

I work on this problem currently. And I think the best solution is to give the user a choice, with a checkbox in the same dialog where we allow the user to edit the ignored files pattern. Default should be to *not* sync hidden files, but if people want, they can switch on.

@moscicki @MTRichards does that match your thoughts?

**Comment by moscicki** [comment] 2015-07-10 10:01
Is the reason not to sync certain hidden files (especially on Windows) because of data integrity protection (e.g. not to corrupt some temporary hidden cache of applications due to possible conflicts) or is it purely not to sync uselessly files which we think user are not interested to sync anyway? In the first case we cannot really leave it to the user (but I would suggest to have a special handling of this: a specific list of hidden file patterns which match specific applications -- which unfortunately would need to be kept updated somehow), in the second case it is an option indeed.

In the second case my only worry is that users assume that they sync a directory and everything there is "safe" because it is synced to cloud storage. In reality it may be not true because some stuff is not synced.

**Comment by dragotin** [comment] 2015-07-10 10:20
some information about the extra files word is creating: https://support.microsoft.com/en-us/kb/211632

I am not sure however if these files are really hidden.

**Comment by moscicki** [comment] 2015-07-10 11:46
I do not have enough knowledge on how sync client currently handles Word files on windows but my (maybe naive) thinking goes like this:
 - this logic should only apply on Windows (and Mac), you exclude ~wrxxxxxx.tmp and other patterns described in the document from sync
 - as long as the abc.doc file is locked by Word you do not touch it (the locking mechanism is Windows specific, you may need to use other means on Mac to see if the file is in use by word process)

This means that any update from the server is not propagated to the client until the file is closed. 
One needs to check if abc.doc move/rename would be permitted while the file is in use by Word and what happens to temporary file when abc.doc is moved.

**Comment by MTRichards** [comment] 2015-07-18 16:45
I concur with @moscicki in how it should operate. Windows / Office lock files (and many other apps) are quite a nightmare to manage for a sync, and a hidden file is a hidden file. So a switch with default to not sync hidden files (just like the windows explorer by the way, to not show / show hidden files) that can be changes works well for me.

**Comment by dragotin** [comment] 2015-07-23 09:18
Ok, so this is done, @Dianafg76 please verify. Thanks!

**Comment by Dianafg76** [comment] 2015-07-28 14:00
I tested this issue.

### Steps to reproduce
In Windows, 
1. I create a new file (e.g. file number2.txt) 
2. go to the properties of file
3. select the Hidden option
4. Open the Server oC.
5. Wait for sync

### Expected behaviour
It should not be synchronized, the file has the option of hidden

### Actual behaviour
I looking the file (call file number2.txt) in the Server
![screen shot 2015-07-28 at 15 55 13](https://cloud.githubusercontent.com/assets/12032058/8933082/43cfa576-3541-11e5-9d95-d63b9727c3d6.png)
In the server:
![screen shot 2015-07-28 at 15 58 10](https://cloud.githubusercontent.com/assets/12032058/8933143/86e85646-3541-11e5-9ce4-20b849111429.png)



### Server configuration
Desktop v ownCloud-2.0.0.5306-nightly20150728-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by guruz** [comment] 2015-07-29 15:13
@dragotin Is this really implemented for Windows?

**Comment by dragotin** [comment] 2015-07-29 15:22
So the  problem is that a file that was hidden on the client is not longer hidden on the server. That is how it is, the server does not support a special metadata for hidden files. It just considers a file hidden if it starts with a dot, for example ```.I_am_hidden```.

**Comment by guruz** [comment] 2015-08-06 14:25
I can confirm that this does not work on Windows with a _new_ file that is set to hidden.

```
08-06 16:20:56:490 0x876bbf0 csync_walker: file: C:/Users/woboq/ownCloud/HIDDEN.dll [inode=186203 size=84524]
08-06 16:20:56:490 0x876bbf0 _csync_detect_update: Checking for rename based on inode # 186203
08-06 16:20:56:490 0x876bbf0 _csync_detect_update: file: HIDDEN.dll, instruction: INSTRUCTION_NEW <<=
```
...
```
08-06 16:20:57:803 0x327440 _csync_merge_algorithm_visitor: INSTRUCTION_NEW      client file: HIDDEN.dll
```

**Comment by cdamken** [comment] 2015-08-07 07:26
@guruz  Windows handles the hidden file with the ```attrib.exe``` program:
```
C:\Users\carlos>attrib
A            C:\Users\carlos\.bash_history
A            C:\Users\carlos\.csp_ovftool_settings.js
A   H        C:\Users\carlos\.DS_Store
A            C:\Users\carlos\.gitconfig
A            C:\Users\carlos\Downloads - Shortcut.lnk
A            C:\Users\carlos\mercurial.ini
A  SH   I    C:\Users\carlos\NTUSER.DAT
A  SH        C:\Users\carlos\ntuser.dat.LOG1
A  SH        C:\Users\carlos\ntuser.dat.LOG2
A  SH        C:\Users\carlos\NTUSER.DAT{bbed3e3b-0b41-11e3-8249-d6927d06400b}.TM.blf
A  SH        C:\Users\carlos\NTUSER.DAT{bbed3e3b-0b41-11e3-8249-d6927d06400b}.TMContainer00000000000000000001.regtrans-ms
A  SH        C:\Users\carlos\NTUSER.DAT{bbed3e3b-0b41-11e3-8249-d6927d06400b}.TMContainer00000000000000000002.regtrans-ms
   SH        C:\Users\carlos\ntuser.ini
A            C:\Users\carlos\State machine issue.log
A  SH   I    C:\Users\carlos\Thumbs.db
A            C:\Users\carlos\xy.log
A            C:\Users\carlos\xy2.log
A            C:\Users\carlos\xy3.log
```
With + and - and : 
A= Archive
R= Read Only
S= System
H= Hidden 
you can change the attributes over the command line.

**Comment by ckamm** [comment] 2015-08-10 08:01
@Dianafg76 @guruz I tried to reproduce it on windows according to Diana's description. When I create the new file in a sync folder it's not hidden initially and gets synced directly. When it's made hidden then, it'll start to be ignored. It will not trigger a removal of the already uploaded file.

When I make a file hidden and copy it into the sync folder, it's not uploaded.

**Comment by phil-davis** [comment] 2015-08-10 08:11
So it is really a matter of defining the requirement. When an existing file has its attributes changed to "hidden" then what is the required action:
a) No longer sync the file, leave the existing version on the server. The local version might change but will from now be ignored for sync. or;
b) Delete the file from the server and do not sync it any more (i.e. put the file sync state into the same state that it would be if the file was newly added to the folder with the "hidden" attribute already set.

(a) seems a bit confusing to me, because then there will be "orphaned" files on the server that users might wonder why they are there (because they see they have them hidden on the client), and also wonder why the version on the server is "out-of_date" with respect to the client.

**Comment by moscicki** [comment] 2015-08-10 08:25
@phil-davis: I think both scenarios are suboptimal because they may lead to silent data loss with scenario b) being out of scope of any reasonable behaviour (change in metadata of a file results in a deletion on a server). IMO it is better to a bit too much than a bit too little to avoid data loss.

To me the issue looks like this:
 * syncing or not syncing hidden files is a matter of policy in the first place (and this could be an option left for the user with a centrally set default by the admin of the service)
 * if syncing of hidden files was initially enabled and then becomes disabled because the user explicitly chose so -- scenario a) looks fine to me -- this is I guess no different from adding a pattern to the ignored patterns list (or should be no different!)
 * in certain situations syncing of hidden files should be always disabled: this is when a sync client knows that these are temporary hidden files of the Office or other well-known app. Of course this should be smart (following a special pattern, possibly having the corresponding master file in the same directory, OS dependant etc). If it is possible to get this detection "smart enough" -- I do not know

How does dropbox handle this?

**Comment by guruz** [comment] 2015-08-10 08:41
Thanks @ckamm this indeed works as expected for now.
I'm changing the issue to a discussion how we want to continue with regards to what @moscicki @phil-davis mentioned above.

**Comment by ckamm** [comment] 2015-08-10 09:17
@guruz had a hunch that there might still be a bug with this setting for migrated folders. I looked at it and that was indeed the case. Folders created by the OC setup wizard also always defaulted to syncing hidden files. That's now fixed in the 2.0 branch.

**Comment by guruz** [comment] 2015-08-10 09:37
...and folders migrated from the 1.8 config.. thanks @ckamm for fixing this.

**Comment by guruz** [comment] 2015-08-10 10:15
@Dianafg76 Can you re-test with ownCloud-2.0.0.5381-nightly20150810-setup.exe ?

**Comment by Dianafg76** [comment] 2015-08-10 10:51
@guruz I tested this issue and it is the same, I see the file in the server
Desktop v ownCloud-2.0.0.5381-nightly20150810-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1","edition":"Enterprise"}
![screen shot 2015-08-10 at 12 50 44](https://cloud.githubusercontent.com/assets/12032058/9169884/8401c9ea-3f5e-11e5-983d-540931f24eaf.png)

![screen shot 2015-08-10 at 12 50 57](https://cloud.githubusercontent.com/assets/12032058/9169889/893f2e5c-3f5e-11e5-8cf0-8331cf216a4c.png)

**Comment by ckamm** [comment] 2015-08-10 10:55
@Dianafg76 Do you test by moving the already hidden number3.txt into the sync folder?

Did you re-setup the client configuration? My patch does not change existing migrated or oc-setup-wizard folders that might be set to sync hidden files. (You can fix folder settings by opening the ignore list editor, disabling 'sync hidden files' (if necessary) and pressing ok)

**Comment by Dianafg76** [comment] 2015-08-10 11:10
@ckamm Hello, If turning off " sync hidden files" it is working well. I can not see the file on the server
However , the icon is blue - blue - to-be syn
![screen shot 2015-08-10 at 13 09 06](https://cloud.githubusercontent.com/assets/12032058/9170206/315b81ec-3f61-11e5-98b7-cb77d0d5758f.png)

**Comment by ckamm** [comment] 2015-08-10 11:32
@Dianafg76 Nice find, that's a different but easy to fix bug.

**Comment by MTRichards** [comment] 2015-08-10 11:57
A thought:
What about not syncing hidden files, but update the ignored file pattern template to allow you to uncheck some of the file types, and to add a sync hidden files option. 

The system would not sync hidden files by default - what one would expect 75% of the time. Certain templates for hidden files could be unchecked (today some can't be unchecked, perhaps a few of them can be unchecked in the future), to allow them to be synced, but a user has to actively opt to sync them. In the same menu add a "sync hidden folders" check that is turned off by default.

**Comment by Dianafg76** [comment] 2015-08-11 14:20
@ckamm, i tested this issue with Desktop v 2.0.0 (build5388) and it is working OK I can not see the file on the server. And the icon is yellow.

**Comment by Dianafg76** [comment] 2015-08-11 14:21
But this "In the same menu add a "sync hidden folders" check that is turned off by default" no appears

**Comment by guruz** [comment] 2015-08-11 17:42
@Dianafg76 What do you mean by that?

**Comment by Dianafg76** [comment] 2015-08-12 06:11
I got confused , sorry
Closed

**Closed by Dianafg76** 2015-08-12 06:11 UTC
Labels: Discussion, Enhancement
