### ISSUE TITLE
Linux Mint client fails with segmentation fault after site was moved from http to https

### ISSUE THREAD

**Issue by studersi** [owncloud/client#3226] opened 2015-05-12 08:54 UTC
### Short overview
After a change in the proxy's config to force https connection when connecting to http, the owncloud client fails with a segmentation fault.
A workaround is to manually edit the config and directly connect to https.

### Expected behaviour
Desktop client should start and show the window to manage account

### Actual behaviour
Nothing happens after desktop launcher icon is clicked.
When started in terminal with the command ```owncloud```, it prints 'Segmentation fault'.

### Server configuration
Operating system: Debian GNU/Linux 7 \n \l
Web server (hosting owncloud): Apache/2.2.22
Proxy server (delivering owncloud): nginx/1.2.1
ownCloud version: ownCloud 8.0.2 (stable)

Proxy redirect config to force https:  
```
server {
        listen 80;
        server_name owncloud.mydomain.com;
        return 301 https://$server_name$request_uri;
}
```

### Client configuration
Client version: ownCloud version 1.5.0 (from official repositories)
Operating system: Linux Mint 17.1 Rebecca \n \l
OS language: de_CH.UTF-8

### Logs
1. client log: [owncloud.log](https://gist.github.com/studersi/e813608ae7c6bf8e9716)
2. client dbg output for ```dbg owncloud```: [owncloud-gdb.log](https://gist.github.com/studersi/d6b14c98d7f4a42e67ab)
3. client valgrind output for ```valgrind --undef-value-errors=no owncloud```: [owncloud-valgrind.log](https://gist.github.com/studersi/099672812b0d6da108aa)

### Workaround
Edit the client config (~/.local/share/data/ownCloud/owncloud.cfg), changing ```http://owncloud.mydomain.com``` to ```https://owncloud.mydomain.com```.
The client then starts up as usual.

**Comment by guruz** [comment] 2015-05-12 15:56
FYI @danimo @ckamm

**Comment by ckamm** [comment] 2015-05-12 17:11
@studersi Thank you for the great bug report, it's so nice to see the backtrace and valgrind log included. You are using a very old client version -- could I ask you to try to reproduce it with 1.8.1? We've made improvements to how redirects are handled and there's a very good chance the problem is already solved.

**Comment by studersi** [comment] 2015-05-13 11:44
@ckamm I didn't realize that the client from the official Linux Mint repositories was so much out of date.

I installed version 1.8.1 from the openSUSE repositories (as described in the [installation instructions for Ubuntu](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client)) and it seems the problem had already been fixed. The segmentation fault doesn't appear anymore.

After moving the site from http to https the client starts up as usual and simply shows the icon with the dots, indicating that the connection couldn't be established. Is this the correct behavior or should the client also redirect to https like the website?

**Comment by LukasReschke** [comment] 2015-05-13 11:47
> @ckamm I didn't realize that the client from the official Linux Mint repositories was so much out of date.

http://www.pcworld.com/article/2845072/ubuntu-owncloud-and-a-hidden-dark-side-of-linux-software-repositories.html – nice read if you want to learn why distributions sometimes too more hurt than well :see_no_evil: 

*/me hides again in his cave*

**Comment by studersi** [comment] 2015-05-13 12:13
@LukasReschke Interesting article, I'll definitely keep that in mind when using software which is not in the Main repository.

**Comment by guruz** [comment] 2015-05-13 13:01
> Is this the correct behavior or should the client also redirect to https like the website?

^^
FYI @danimo

**Comment by ckamm** [comment] 2015-05-20 07:31
I'm closing this since the bug from the title is no more. I'll move the enhancement suggestion for redirecting http to https to a separate issue.

**Closed by ckamm** 2015-05-20 07:31 UTC
Labels: bug

**Comment by studersi** [comment] 2015-05-20 09:03
Ok, thank you for the help!
