### ISSUE TITLE
[QA] client repeats asking for password of disabled user

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8982] opened 2021-09-07 14:06 UTC
Seen with 2.9.0-rc2 (and earlier)

* connect to a server with basic auth
* wait for initial sync
* ssh into the server and use `occ user:disable` to block the user.
* the desktop client will pop up a password dialog
![image](https://user-images.githubusercontent.com/1108546/132358517-b62c36bb-cd28-4977-95bf-a45ba7f60995.png)

This does not help, as the stored password is not wrong.

Expected behaviour: A different text "user is disabled" should be shown, to make clear that nothing is wrong with the password.

That is what the Web UI does:
![image](https://user-images.githubusercontent.com/1108546/132358892-bc4bbaa4-4d20-416a-9461-8dcc2117a594.png)

**Comment by TheOneRing** [comment] 2021-09-07 14:45
Duplicate of https://github.com/owncloud/client/issues/8850

**Closed by TheOneRing** 2021-09-07 14:45 UTC
Labels: Enhancement
