### ISSUE TITLE
Overlays Icons issue on Ubuntu 17.10

### ISSUE THREAD

**Issue by sagitariozod** [owncloud/client#6395] opened 2018-03-20 08:50 UTC
Hello, I have installed owncloud-client 2.4.1 build 9083 on Ubuntu 17.10, with the latest update some icons of overlays are not displayed. I have observed that it occurs only in those files and folders that have some special character in the name, for example accents, the letter ñ, etc.

When the overlay icon is not displayed, I do not get the option in the context menu to share folders and files. It only happens with the folders and files that the overlay does not come out, in which the overlay works correctly.

In the previous version it worked correctly, but when updating to this latest version I have this problem.

I hope you can help me.

Thank you very much.

**Comment by ogoffart** [comment] 2018-03-20 10:25
I could not reproduce the problem.

Are you using nautilus?
Is that a regression compared to earlier versions?
What is your locale?  (You can find out by typing `echo $LANG;`)
Is there anything in the owncloud log. (press F12 to  open the log console, make sure to enable the debug, and then refresh in nautilus.)

**Comment by ogoffart** [comment] 2018-03-20 10:59
Ah, maybe related to issue #6393

**Comment by sagitariozod** [comment] 2018-03-21 09:45
Hello, yes, it's a similar issue, but in my case I use nautilus, my locale is Spanish (es_ES.UTF-8), the previous version was 2.4.0

After pressing F12, activate debug and update F5 in a folder with content that affects the issue, in the log no reference to the folder or file with problems appears.

Greetings.

**Comment by sagitariozod** [comment] 2018-03-21 13:08
Hello, after reading on github, I have solved the problem by replacing the file of the version 2.4.1
/usr/share/nautilus-python/extensions/**syncstate-ownCloud.py**

with that of version 2.4.0, included in the package nautilus-owncloud_2.4.0+dfsg-1_all.deb.

I have also deleted the file.
/usr/share/nautilus-python/extensions/**syncstate-ownCloud.pyc**

After restarting, in this way everything works normally again.

Thank you very much.

**Comment by ogoffart** [comment] 2018-03-27 09:11
This is a duplicate of issue #6393 so I'm closing this one.

Thanks for the report.

**Closed by ogoffart** 2018-03-27 09:11 UTC
Labels: Needs info
