### ISSUE TITLE
Moving folder causes conflict with identical files if 503 is encountered during sync

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#6435] opened 2018-04-06 20:30 UTC
### Expected behaviour
Moving a folder inside my sync folder should not cause any problems.

### Actual behaviour
I moved a folder into a different folder in my sync folder. Around the same time, I made another copy of a rather large folder in the same sync folder, which probably kept ownCloud a bit busy, ultimately causing a 503 error.

A little while after, I got a message that there was a problem with the moved folder (I don't remember which exact error message it was but I guess it was a conflict notification). I noticed that ownCloud downloaded conflict files of almost each file in the moved folder. The conflict files had exactly the same hash as the original files, so how can they possibly be confliciting?

### Steps to reproduce
1. Move folder
2. Copy another large folder in the same sync folder to another location, causing a 503 timeout
3. Observe issues with the folder from step 1.

### Server configuration
Operating system: Debian Jessie (Bananian)

Web server: Apache 2.4

Database: MySQL

PHP version: 5.6

ownCloud version: 10.0.7

Storage backend (external storage): Local

### Client configuration
Client version: 2.5.0-daily20180216 (builds 9245)

Operating system: Windows 7

OS language: German

Installation path of client: Default

### Logs

The run that ultimately timed out.  "UpdateSmart - Kopie" is the duplicated folder, "ghg_coding_challenge_name_score_2" is the moved folder.
```
#=#=#=#=# Propagation starts 2018-04-06T20:00:13Z (last step: 38336 msec, total: 38336 msec)
20:00:12||VC++/UpdateSmart - Kopie|INST_NEW|Up|1523044771||4096|02055475oc79c8z0bi2n|4||201|0|0||||
20:00:12||VC++/OpenMPT/mptrack/View_pat.h|INST_SYNC|Up|1523044749|4a99d33474e4ef026fcb3f26c2411c20|22634|00332195oc79c8z0bi2n|4||204|22666|1523044654||||
20:00:15||VC++/UpdateSmart - Kopie/.svn|INST_NEW|Up|1523044771||4096|02055477oc79c8z0bi2n|4||201|0|0||||
20:00:15||VC++/UpdateSmart - Kopie/.travis.yml|INST_NEW|Up|1490300487|ef16dceaed5c9c1499b29a1bfd527e95|931|02055478oc79c8z0bi2n|4||201|0|0||||
20:00:15||VC++/UpdateSmart - Kopie/.gitignore|INST_NEW|Up|1519421975|82f188feabb2d33fdb52cda02607e19f|12349|02055479oc79c8z0bi2n|4||201|0|0||||
20:00:17||VC++/UpdateSmart - Kopie/LICENSE|INST_NEW|Up|1514896754|256fb12a43259c335ab2dc50d46f0549|1611|02055480oc79c8z0bi2n|4||201|0|0||||
20:00:18||VC++/UpdateSmart - Kopie/.svn/entries|INST_NEW|Up|1454547867|d1d938e6e29e24df62f277b9ab8cb2fd|3|02055481oc79c8z0bi2n|4||201|0|0||||
20:00:19||VC++/UpdateSmart - Kopie/.svn/format|INST_NEW|Up|1454547867|7709123172521e59588413273a9610fd|3|02055482oc79c8z0bi2n|4||201|0|0||||
20:00:21||VC++/UpdateSmart - Kopie/.svn/wc.db-journal|INST_NEW|Up|1522941479|5065f883bdfa4793af3f6b5bf7258a93|0|02055483oc79c8z0bi2n|4||201|0|0||||
20:00:23||VC++/UpdateSmart - Kopie/Makefile|INST_NEW|Up|1521980010|50360a978fb46813bde93cac7eef3c75|59033|02055484oc79c8z0bi2n|4||201|0|0||||
20:00:24||VC++/UpdateSmart - Kopie/README.md|INST_NEW|Up|1520266947|ec3416eaec871787daeb8e74442d8052|8243|02055485oc79c8z0bi2n|4||201|0|0||||
20:00:26||VC++/UpdateSmart - Kopie/appveyor.yml|INST_NEW|Up|1518958573|4c8ff9785cdb6871f80f3a6caf276051|658|02055486oc79c8z0bi2n|4||201|0|0||||
20:00:20||VC++/UpdateSmart - Kopie/.svn/wc.db|INST_NEW|Up|1522941502|c6d73fb6c15df20eb672363d1476b102|2464768|02055487oc79c8z0bi2n|4||201|0|0||||
||VC++/ghg_coding_challenge_name_score_2 -> VC++/tools/ghg_coding_challenge_name_score_2|INST_RENAME|Up|1521123146|5aaa7f4abec99|0|02037483oc79c8z0bi2n|1|Server hat "503 Service Unavailable" auf "MOVE https://home.schultz.re/wolke/remote.php/dav/files/johannes/Sources/VC++/ghg_coding_challenge_name_score_2" geantwortet|503|0|0||||
#=#=#=# Syncrun finished 2018-04-06T20:05:19Z (last step: 306225 msec, total: 344562 msec)
```

In a second run immediately afterwards:
```
||VC++/tools/ghg_coding_challenge_name_score_2/.git/hooks|INST_NEW|Down|1520943588|5aa7c1e44dd76|0|02037485oc79c8z0bi2n|4||0|0|0||||
20:19:01||VC++/AsyncDraw/soundlib|INST_NEW|Up|1523044866||49152|02055827oc79c8z0bi2n|4||201|0|0||||
20:19:03||VC++/tools/ghg_coding_challenge_name_score_2/.git/hooks/applypatch-msg.sample|INST_NEW|Down|1520943507|6d64df9e82884ed32bea7a4d605bc135|478|02037491oc79c8z0bi2n|3|Datei ist seit der Entdeckung geändert worden|0|0|0||||
20:19:03||VC++/tools/ghg_coding_challenge_name_score_2/.git/hooks/commit-msg.sample|INST_NEW|Down|1520943507|f69dc7533392d0ccbeb6351974d8bc5e|896|02037492oc79c8z0bi2n|3|Datei ist seit der Entdeckung geändert worden|0|0|0||||
20:19:05||VC++/tools/ghg_coding_challenge_name_score_2/.git/hooks/fsmonitor-watchman.sample|INST_NEW|Down|1520943507|e35fcb79e5d05b9c9f73c4f8b25c921f|3327|02037493oc79c8z0bi2n|3|Datei ist seit der Entdeckung geändert worden|0|0|0||||
20:19:06||VC++/tools/ghg_coding_challenge_name_score_2/.git/hooks/pre-applypatch.sample|INST_NEW|Down|1520943507|7e112c70b540462089e9fc4a6b16e560|424|02037495oc79c8z0bi2n|3|Datei ist seit der Entdeckung geändert worden|0|0|0||||
20:19:06||VC++/tools/ghg_coding_challenge_name_score_2/.git/hooks/pre-commit.sample|INST_NEW|Down|1520943507|649efe27a2737f77ee1fbd6995bd1a14|1642|02037496oc79c8z0bi2n|3|Datei ist seit der Entdeckung geändert worden|0|0|0||||
20:19:05||VC++/tools/ghg_coding_challenge_name_score_2/.git/hooks/post-update.sample|INST_NEW|Down|1520943507|25dc7d2c6da5f3e4b3256679d7b016a8|189|02037494oc79c8z0bi2n|3|Datei ist seit der Entdeckung geändert worden|0|0|0||||
(...)
```

**Comment by sagamusix** [comment] 2018-04-06 20:37
As far as I understand this means that the client tells the server that the folder moved to a different place, the server times out during the move, and the client forgets about the new location and is surprised when the server tells it to download those files in the new place where they would conflict with the that are already present?

**Comment by ogoffart** [comment] 2018-04-09 07:02
My guess is that the error `503` which is classified as a Fatal Error, aborts the sync. This aborts the Move job in progress. We then don't write in the database that the move succeed. However, since the move succeeded on the server, it sees that both local and remote have changed.

This is something that https://github.com/owncloud/client/pull/5953 was meant to fix, but apparently did not.

But still, no conflict files should be created. ideally, the conflict should be resolved without any downloads.

**Comment by ogoffart** [comment] 2018-04-09 12:43
I could not reproduce the problem. 

Even when moving the files on both the server and the local, the client uses the checksum to find out that the files were indeed the same.

Were the file marked as conflicted not actual conflicts?  Were there not modified locally or on the server?

**Comment by sagamusix** [comment] 2018-04-09 12:45
The files were not modified recently, neither locally nor on the server - as said, the hashes of the temp files created by ownCloud were identical to the original files. Actully there was no "conflict" in the filename, but a random 4-letter extension was appended to the filename, if I remember correctly.

**Comment by ogoffart** [comment] 2018-04-09 12:58
The log shows message such as "Datei ist seit der Entdeckung geändert worden" which seems to indicate that files were indeed modified.

**Comment by sagamusix** [comment] 2018-04-09 12:59
Which is really strange, because I can be very very sure that I didn't touch anything inside that folder, I just moved it. :)

**Comment by ckamm** [comment] 2018-04-10 08:57
I'm also baffled
* "Datei ist seit der Entdeckung geändert worden" should only appear if the size or mtime of the file disagrees with what's in the database (or filesystem)
* Creating conflict files that are identical with the local file should *never* happen, there's a check for whether the two files have identical contents right in front of the conflict file creation code

Possibly this has something to do with skipping local discovery? If one moved `a/foo` to `a/bar` and the file watcher only fired for the latter or there was some other problem with the former (unexpandable windows short filename?), then `a/foo` would be inserted into local discovery from the database? But the symptoms I imagine don't match what happens here.

**Comment by ckamm** [comment] 2018-04-19 10:12
@sagamusix If you're using a recent master build, make sure to enable the new rolling log option (https://github.com/owncloud/client/issues/6442, F12 and then "Permanent save logs") - that way, if something like this happens again, we'll have logs and a better chance of fixing these problems. Thank you for you detailed reports!

**Comment by sagamusix** [comment] 2018-04-19 12:09
> "Permanent save logs"

Would that be "Fehlermeldungen aufzeichnen" in the German localization? Because that doesn't show a tooltip.

Probably off-topic but that dialog is almost unusable here while a scan is running. I tried opening it but it would just completely freeze ownCloud within mere seconds. Then sometimes it would become responsive again for a second, just to freeze again. Opening it while no synchronization is running helped avoiding that problem.

**Comment by ckamm** [comment] 2018-04-19 15:15
@sagamusix No, I think that's the German equivalent for "Capture debug messages". There will be a second checkbox in that dialog in newer versions. 

And yeah, the log window isn't very functional. Personally, I'd drop the live view and just keep the "capture logs" checkbox along with a button that can open the folder that contains the files. But that doesn't make it for 2.5.

**Comment by sagamusix** [comment] 2018-04-19 15:16
Oh, oops, I sorted the folder the wrong way around and downloaded the earliest rather than the latest test build... that explains the missing option. :)

**Comment by ckamm** [comment] 2018-04-24 06:01
Moved since we currently have no idea for what to do :/

**Comment by ogoffart** [comment] 2018-12-04 12:36
@sagamusix have you been able to reproduce this problem?

**Comment by sagamusix** [comment] 2018-12-04 21:41
I'm not sure, but I have run into a similar situation recently - I had to recreate my ownCloud storage and after re-uploading all the files on client A, client B on a second system was run and claimed that there were conflicted copies of some files - however, it did not create a conflicted copy and just kept one file as expected (I don't know if it downloaded the server copy, though). Unfortunately I had no debug logs enabled on that client.

**Comment by ogoffart** [comment] 2019-03-15 09:14
Closing issue we cannot reproduce.

**Closed by ogoffart** 2019-03-15 09:14 UTC
Labels: Needs info, bug
