### ISSUE TITLE
Systray shows sync icon even though server is in maintenance mode

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#3392] opened 2015-07-01 16:51 UTC
### Steps
1. Set ownCloud server to maintenance mode
2. Start sync client
3. Observe system try icon

### Expected result
System tray grayed out / transparent, tooltip saying "Server not available"

### Actual result
System tray shows the blue sync icon, tooltip says "Waits to start syncing"

Is this a regression or is it intended ?

I find the permanent sync icon confusing from a user's point of view, as if the sync client was stuck.

### Versions
ownCloud server 8.1.0RC1 or 8.1.0RC2 in maintenance mode
owncloud-client-1.8.3-2.1.x86_64

**Comment by ckamm** [comment] 2015-07-02 07:53
For 2.0 this was fixed in #3200 - I thought it was a regression due to multiaccount being added. Will check out the same behavior in 1.8.

**Comment by ckamm** [comment] 2015-07-02 12:37
It's fixed in the 1.8 branch by d1e0fbe

**Comment by ogoffart** [comment] 2015-07-07 13:17
@ckamm  I had conflicts when trying to merge this to master.   Should this commit not be part of master at all?

**Comment by ckamm** [comment] 2015-07-08 09:18
@ogoffart feel free to drop it for now and I'll look at it later. I'm not sure right now whether I already did a similar change in master.

**Comment by ckamm** [comment] 2015-07-15 07:42
Yes, I double checked. It's fine in master: it will display the disconnection icon if any account isn't connected.

**Comment by Dianafg76** [comment] 2015-07-30 07:15
I test this issue, and is working fine. Now when you have a server in maintenance mode, and you go to the Desktop,  System tray appears grayed out / transparent, tooltip saying "Server not available".
I close this issue. Thanks

**Closed by Dianafg76** 2015-07-30 07:15 UTC
Labels: bug, ReadyToTest

**Comment by PVince81** [comment] 2015-08-04 05:10
I still see this with 1.8.4 so I guess it will be fixed in 1.8.5 ?

**Comment by danimo** [comment] 2015-08-04 09:40
@PVince81 if there is going to be a 1.8.5. There is none scheduled atm.
