### ISSUE TITLE
The blue (i) icon doesn't disappear even after all resources sync successfully

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9529] opened 2022-03-21 06:52 UTC
### Expected behavior
After successful syncing of resources, the client is expected to show a green checkmark icon. 

### Actual behavior
But the client shows the blue (i) instead of the green checkmark icon.

### Steps to reproduce
1. Create a file with the '.owncloud' extension in the local sync directory.
2. Open ownCloud desktop application
3. Try to sync the file, click on the three-dotted icon and click on `force sync now`
4. Delete the files with the `.owncloud` extension
5. Again Create a file with an extension other than `.owncloud`
6. Open ownCloud desktop application
7. Click on the three-dotted icon and click on `force sync now`

### Screenshots
![sync](https://user-images.githubusercontent.com/66173400/159217545-b99e7ac8-ab78-4203-b481-f70b55166dbe.gif)

**Comment by TheOneRing** [comment] 2022-03-21 11:30
My assumption is that the I is caused by one of the other sync issues.
Please share the resulting table after the .owncloud issue was resolved. (Select all and copy using the context menu)

**Comment by TheOneRing** [comment] 2022-03-21 11:32
(I've seen multiple currently in use messages in there)

Also why is there an SFTP folder, external storage providers are know to behave poorly with the client and should not be used in regular tests.

**Comment by sushmita56** [comment] 2022-03-23 11:17
The green checkmark icon is seen after the `.owncloud` issue gets resolved.
![sync2](https://user-images.githubusercontent.com/66173400/159686424-0d6474d4-65b8-44c5-8b86-a2e095d09d4a.gif)

But a file `New Text Document.txt` and a folder `New folder` that doesn't even exist in the system is also shown in the synced tab.

**Comment by sushmita56** [comment] 2022-03-23 11:20
The green checkmark icon is seen after the `.owncloud` issue gets resolved.
![sync2](https://user-images.githubusercontent.com/66173400/159686424-0d6474d4-65b8-44c5-8b86-a2e095d09d4a.gif)

But a file `New Text Document.txt` and a folder `New folder` that doesn't even exist in the system are also shown in the synced tab. Is it as expected?

**Comment by TheOneRing** [comment] 2022-03-23 11:31
The protocol lists all actions performed, so that looks correct-

**Comment by sushmita56** [comment] 2022-03-23 11:32
And I think the folders `SFTP` `Photos` and `Documents` are there by default.

**Comment by TheOneRing** [comment] 2022-03-23 11:37
Ok thx for the info.
So https://github.com/owncloud/client/issues/9529#issuecomment-1076253746 everything is fine? Can we close the issue?

**Comment by jnweiger** [comment] 2022-03-23 11:43
> And I think the folders `SFTP` `Photos` and `Documents` are there by default.

SFTP is not really a system default, that is something I add automatically in my test systems. Often issues appear just because of that. I am evil :smiling_imp:

**Comment by gabi18** [comment] 2022-03-23 11:46
> > And I think the folders `SFTP` `Photos` and `Documents` are there by default.
> 
> SFTP is not really a system default, that is something I add automatically in my test systems. Often issues appear just because of that. I am evil smiling_imp

The external storage can be disabled: login as 'admin' go to 'Settings', to 'Storage' (in Admin section) and disable "Enable external storage"

**Comment by TheOneRing** [comment] 2022-03-23 12:00
No need to disable it. Just ignore it's presence.

**Closed** 2022-03-23 12:56 UTC

**Comment by sushmita56** [comment] 2022-03-29 10:51
This issue can't be reproduced be in RC2.
