### ISSUE TITLE
Certificate Warning

### ISSUE THREAD

**Issue by adi-dev** [owncloud/client#4953] opened 2016-06-08 12:04 UTC
It's not a big deal, but would be possible to have a checkbox somewhere in settings like what to do if the server certificate is changed. My problem is the ISP box crashes sometimes and when it does it redirects all traffic to maintenance page (https), immediately I have a warning message from OwnCloud Desktop Client saying the certificate has changed but I do not want to accept the new certificate. It would be nice if the client could just act as the connection is broken if the certificate is wrong or missing and only have information on the settings/network page showing that the cert is changed/new. Once the connection returns valid, previously accepted certificate resume sync.

**Comment by danimo** [comment] 2016-06-09 08:21
Semantic duplicate of #3731. Let's fix this there.

**Closed by danimo** 2016-06-09 08:21 UTC
Labels: Discussion

**Comment by adi-dev** [comment] 2016-06-09 09:50
@danimo are you sure it's a duplicate, there is a mention to fall into http, here, what I would like to see is just status 'disconnected' and show somewhere in options that the certificate has changed.I'm trying to do a try deploy in my office but modem is on the same line where the fax is and popup warning message about certificate causes from panic to pressing accept.
