### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by jonathanernst** [owncloud/client#8328] opened 2020-12-26 23:59 UTC
### Expected behaviour
Running owncloud client under wayland should be possible. 

### Actual behaviour
Owncloud client crashes.

export QT_QPA_PLATFORM=wayland
owncloud
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Abandon (core dumped)

### Steps to reproduce
1. Force wayland platform usage with export QT_QPA_PLATFORM=wayland 
2. Run owncloud
3. Crash 

### Client configuration
Client version:
2.7.4

Operating system:
Ubuntu 20.04

OS language:
French

Qt version used by client package (Linux only, see also Settings dialog):
5.12.9

Client package (From ownCloud or distro) (Linux only):
From owncloud

**Comment by jnweiger** [comment] 2021-01-04 16:00
On my ubuntu 20.4 box:
Looks like we simply do not ship a wayland plugin @gabi18 
```
ls -la /opt/ownCloud/qt-5.12.9/lib/x86_64-linux-gnu/qt5/plugins/platforms/
total 1108
drwxr-xr-x 2 root root   4096 Nov 16 16:59 ./
drwxr-xr-x 8 root root   4096 Nov 15 10:41 ../
-rw-r--r-- 1 root root 496240 Jul  7 20:04 libqlinuxfb.so
-rw-r--r-- 1 root root 149104 Jul  7 20:04 libqminimal.so
-rw-r--r-- 1 root root 174352 Jul  7 20:04 libqoffscreen.so
-rw-r--r-- 1 root root 286064 Jul  7 20:04 libqvnc.so
-rw-r--r-- 1 root root  10864 Jul  7 20:04 libqxcb.so

**Comment by TheOneRing** [comment] 2021-01-04 16:42
Its a separate module https://github.com/qt/qtwayland

**Comment by gabi18** [comment] 2021-01-05 15:59
Reproducible on openSUSE Leap 15.2:

export QT_QPA_PLATFORM=wayland
owncloud
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)

**Comment by jnweiger** [comment] 2021-01-07 01:20
Wayland module coming up in https://build.opensuse.org/package/show/isv:ownCloud:Qt51210/ocqt51210-qt5-qtwayland

**Comment by jnweiger** [comment] 2021-01-08 09:42
Testing needed:

* today's 2.7 daily is built with qt-5.12.10 and wayland support
* the wayland module can be added manually from the above repo

On a Mint Linux machine (without wayland) I get
```
echo >> /etc/apt/sources.list.d/owncloud-test.list "deb https://download.owncloud.com/desktop/testpilotcloud/daily/2.7/linux/Ubuntu_20.04/ /"
echo >> /etc/apt/sources.list.d/owncloud-test.list "deb http://download.opensuse.org/repositories/isv:/ownCloud:/Qt51210/Ubuntu_20.04/ /"
apt update
apt install testpilotcloud-client
apt install ocqt51210-qtwayland5
testpilotcloud --version
```
testpilotcloud 2.7.5daily20210108 (build 3012) Jan  6 2021 01:33:14
https://github.com/owncloud/client/commit/4ab81e903f83f9720e82dddadb939d9952ed8cd6
Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
Using virtual files plugin: suffix
```
env XDG_SESSION_TYPE=wayland QT_QPA_PLATFORM=wayland testpilotcloud
```
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, wayland, xcb.

Aborted (core dumped)

**Comment by jnweiger** [comment] 2021-01-08 13:29
Logged in with the "Ubuntu on wayland" option selected, when the login manager asks for password:
![image](https://user-images.githubusercontent.com/1108546/104020617-c9b9d500-51bd-11eb-8f13-f757ce60f7c2.png)

It somewhat runs, but no window decoration and cannot be moved or minified.

**Comment by jonathanernst** [comment] 2021-01-12 10:10
@jnweiger first of all thanks a lot for your interest in this feature! Owncloud is one of the last application I use that is not wayland aware and look ugly with fractional scaling on my screen :-)

I've tried your test version in both Ubuntu 20.04 et 20.10 and get the same results as you. I can confirm that it's using wayland with xeyes and can see that the fonts are now perfect but I have no decorations. Unfortunately as I don't have this issue with other wayland-compatible apps I have currently no idea why you don't have decorations.

It might well come from the fact that with wayland the client (owncloud in this instance) is responsible for the window decoration by default. It seems also possible to have server side decorations though. Maybe this is relevant :-1: 

- https://www.qt.io/blog/2018/12/14/whats-new-wayland-platform-plugin-qt-5-12
"Furthermore, we've now also added support for support for the Wayland extension, xdg-decoration unstable v1. Compositors implementing this extension can now tell Qt clients that decorations will be drawn server-side instead of client-side. I.e. the decorations for Qt applications and other toolkits can be identical after all. This is also good news for people running tiling compositors. It's no longer needed to set the environment variable QT_WAYLAND_DISABLE_WINDOWDECORATION on compositors that implement this extension. Toggling window decorations at runtime is now also possible."

=> maybe we need this xdg-decoration extension or a runtime ?


- https://doc-snapshots.qt.io/qt5-5.12/qtwaylandcompositor-server-side-decoration-example.html

Hope it helps and thanks again!

**Comment by jnweiger** [comment] 2021-01-13 17:39
Probably very relevant pointers! Afaik, our desktop client currently does not know about client side decorations. At least to me, that is a new concept.
Thank you so much for these hints! I am glad to test any progress we make or help with packaging.

In the meantime, I can only report: Same issue reproduced on Debian-10.7.0 with gnome3.

**Comment by michaelstingl** [comment] 2021-01-14 09:22
Testing Wayland support is part of the 2.7.5 release testing: https://github.com/owncloud/client/issues/8349

**Comment by jnweiger** [comment] 2021-01-14 19:59
> Testing Wayland support is part of the 2.7.5 release testing: #8349

Prvoiding a missing dependency was part of the release preparations. But there is no more wayland testing planned for the release on top of what we discuss here.

@michaelstingl Do you want wayland support as a release blocker? I'd suggest to keep that independant of the release until you have a developer to look into that.

**Comment by michaelstingl** [comment] 2021-01-14 21:36
No, not a blocker for 2.7.5. in case it’s not solved, we should mention it in the release communication and in the supported platform docs.

**Comment by fmoc** [comment] 2021-04-15 15:37
I built the current master in a VM running an openSUSE Leap 15.2 live image with KDE, in a "full wayland" session. Everything looks fine in there:

![screenshot_2021-04-15_17-34-52](https://user-images.githubusercontent.com/80399010/114896892-3f0df500-9e00-11eb-9406-e9481d6a4eef.png)

For distribution, we probably just have to ship the wayland platform plugin(s). That's a little complex, but I'm sure we'll figure it out. Other than that, I think the client supports Wayland properly already.

**Comment by jonathanernst** [comment] 2021-04-15 16:50
@fmoc unfortunately to support GNOME/Mutter we still miss client side decoration

**Comment by fmoc** [comment] 2021-04-17 12:58
![screenshot_2021-04-17_14-55-52](https://user-images.githubusercontent.com/80399010/115113975-6d184400-9f7c-11eb-879d-2054f912ce8b.png)

This is openSUSE Leap 15.2 Live with a Wayland session, using `QT_QPA_PLATFORM=wayland`. I haven't tried Ubuntu with Mutter yet, but I presume any kind of issue is not caused by ownCloud.

**Comment by fmoc** [comment] 2021-04-17 16:05
Tested on Ubuntu 20.04.2 with GNOME.

XWayland:

![screenshot_2021-04-17_17-59-22](https://user-images.githubusercontent.com/80399010/115119047-fb4cf400-9f95-11eb-807b-3f3f684ced45.png)

Native Wayland:

![screenshot_2021-04-17_17-58-52](https://user-images.githubusercontent.com/80399010/115119049-fdaf4e00-9f95-11eb-94ef-b9ce343e98c8.png)

Built against system packages. I'm relatively confident that the ugly look is caused by Qt5, and there's nothing we can do about it. At least I couldn't find any fix while doing a bit of research on the issue...

**Comment by fmoc** [comment] 2021-04-17 16:13
![screenshot_2021-04-17_18-12-55](https://user-images.githubusercontent.com/80399010/115119409-cb065500-9f97-11eb-95a2-6e14432e096f.png)

Problem apparently solved by enforcing the Gtk3 platform theme. The environment variables to set:

```sh
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=gtk3

**Comment by TheOneRing** [comment] 2021-04-17 21:01
We might not have enabled building the gtk Plugin.

**Comment by fmoc** [comment] 2021-04-22 06:44
@jonathanernst could you please check whether setting that second environment variable solves the issue on your end as well?

**Comment by fmoc** [comment] 2021-05-05 18:07
2.8 RC AppImage works fine on Leap 15.2 wand Ubuntu 20.04.2, both with GNOME. I had to set only `QT_QPA_PLATFORM` with it, since linuxdeploy-plugin-qt sets the `QT_QPA_PLATFORMTHEME=gtk3` in a script in `apprun-hooks` already. I think we can close this issue.

**Comment by ik8ozv** [comment] 2021-07-24 10:43
Please Since i upgraded Ubuntu to version 21.04, i have the same issue with gnuradio running any GRC file.
Please any Help to avoid the problem?
Thanks
Enzo

**Comment by michaelstingl** [comment] 2021-07-24 11:19
@ik8ozv please open a new issue and provide the full context.

**Comment by mcsmurf** [comment] 2021-08-11 15:11
@ik8ozv I had the same issue on Ubuntu 21.04 for a different application. Changing to `xcb` solved it for me. I had to add the dependencies as highlighted here: https://forum.qt.io/topic/126864/how-to-resolve-qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found-error/3:

1.  `sudo apt install libxcb-icccm4 libxcb-xkb1 libxcb-icccm4 libxcb-image0 libxcb-render-util0 libxcb-randr0 libxcb-keysyms1 libxcb-xinerama0`
2. `echo "export QT_QPA_PLATFORM=xcb" >> ~/.bash_profile && source ~/.bash_profile`

**Comment by jnweiger** [comment] 2021-08-31 08:09
Retested with 2.9.0 RC1

``` env QT_QPA_PLATFORM=wayland testpilotcloud
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```
![image](https://user-images.githubusercontent.com/1108546/131466019-30fa8b00-e24a-4201-b4fd-2999ec4cae06.png)

The mentioned workaround, of using xcb instead of native wayland also works with 2.9.0

**Comment by TheOneRing** [comment] 2021-09-06 13:03
The warning is issued by Qt so we can ignore that part.
So the remaining issue is again a lack of window decorations.

**Comment by jnweiger** [comment] 2021-09-08 13:51
@fmoc would you share your secrets? :roll_eyes:

**Comment by jnweiger** [comment] 2022-01-13 19:25
Same with 10.9.1-rc4: the client runs fine, but I still miss the secret how to get window decorations on my ubuntu-20.04 wayland test system.

I suggest to re-open here and find document (or implement) the remaining steps.

**Comment by PVahr** [comment] 2022-08-10 06:59
Thanks a lot! 
This works for me, I can finally sync my stuff.

My problem was then not in the graphical engine, but - I guess - in some repository setting.
Shall I open a new issue?

**Comment by fmoc** [comment] 2022-08-10 10:24
@PVahr the version shipped by Debian is _really_ old, there's no point in debugging those old versions, really. Our repositories use a much, much more recent Qt version and other up-to-date dependencies.

Since cannot provide support for these distro packages and your issue is clearly unrelated to the issue originally described, I'm hiding our comments as off topic.

**Comment by kuateric** [comment] 2022-10-15 10:59
owncloud on Ubuntu 22.04 with Wayland still crashes. 
We use this routine for installing https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/ 
and we tried on 10 machines. Always the same behaviour. 
Ubuntu 22.04 is already a while there, there is still no proper fix for wayland. It is very frustrating. We are about to migrating to a differen platform

**Comment by kuateric** [comment] 2022-10-17 16:39
Thank you for taking a look. Which on of these should i delete in order to get it work. 
![grafik](https://user-images.githubusercontent.com/22998049/196231571-1aaf1bf2-b26c-4e4a-87cb-9b3d2f816d63.png)

Is it possible to set QT_QPA_PLATFORM=wayland permanently? if so how ? 

> Note that this is unrelated to packaging as an AppImage, apparently. 

the problem is then related to the native packages here https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/? Is it not better to fix the issue and make it easy for us to install it properly ? 

Thanks

**Comment by kuateric** [comment] 2022-10-17 17:12
i just set up a server on aws to test again.
I installed owncloud following the link below. 
I applied QT_QPA_PLATFORM=wayland 
owncloud opens but it is not possible to go further than this. The next button somehow does not respond. 
![image](https://user-images.githubusercontent.com/22998049/196240579-de8719c0-ee35-430c-9987-925af5537cb6.png)

**Comment by kuateric** [comment] 2022-10-17 17:13
same behaviour without QT_QPA_PLATFORM=wayland

![image](https://user-images.githubusercontent.com/22998049/196241003-e390ce73-2f96-4f1b-8d17-f0cc8d1c7640.png)

**Comment by kuateric** [comment] 2022-10-17 17:30
now i deleted libwayland-client.so.0 and owncloud does not open anymore. 
![image](https://user-images.githubusercontent.com/22998049/196243580-e0b60c2e-2f6c-488f-87f9-4ea1f19a483e.png)

I think that the installation procedure becomes too complicated for the everyday users. a more simple and functional installation routine would be great to have

**Comment by fmoc** [comment] 2022-10-17 19:02
Seems like you've been busy, and may have damaged your system. I think we can repair it with reasonable effort, though. Next time, please wait for instructions explicitly. I'll respond to all your comments in a single post.

By the way, I am not sure whether a language barrier is causing problems here. If so, please let me know. We do not want you to understand us wrongly (and vice versa).

> Which on of these should i delete in order to get it work.

None. I was discussing the contents of the AppImage. You're looking at system files. Please do not delete any files from your system randomly. (See below.)

> Is it possible to set QT_QPA_PLATFORM=wayland permanently? if so how ?

I did not say you should use that. I was asking whether this is already set. To check, please open a terminal and type the following code snippet:

```sh
> echo "$QT_QPA_PLATFORM"
```
If it shows no output, you can assume it is not set. If there is any output, please post it here.

> the problem is then related to the native packages here https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/? Is it not better to fix the issue in the native packages and make it easier for us to install it properly ?

Native packages are under investigation right now. Unfortunately, Ubuntu has made debugging in live CD VMs extremely hard with its snap stuff. I need to set up a proper VM.

> i just set up a server on aws to test again.

For future tests, feel free to use https://demo.owncloud.org, https://demo.owncloud.com or https://ocis.owncloud.com.

> owncloud opens but it is not possible to go further than this. The next button somehow does not respond.
> same behaviour without QT_QPA_PLATFORM=wayland

This is unexpected, and I cannot reproduce this on a vanilla (that means, freshly set up) system. It may be related to changes you performed on your system. Of course, I cannot tell which one exactly led to the problem. As long as I cannot reproduce the issue, I cannot tell you how to fix it.

> now i deleted libwayland-client.so.0 and owncloud does not open anymore.

Again, nobody instructed you to delete this file from your system. You just broke your system to some extent.

Since you seem kind of unexperienced, I'd like to try to help you, though. Try running the following commands in a terminal to reinstall the library:

```sh
sudo apt-get update
sudo apt-get install --reinstall libwayland-client0
```
`sudo` might prompt you for your password, please enter it as instructed.

***Generally, please never just randomly delete files from your system if you do not know what you're doing.***

> I think that the installation procedure becomes too complicated for the everyday users. a more simple and functional installation routine would be great to have

This is what our AppImage is for. It doesn't require root permissions, and is easier to use in general. The incompatibility with Wayland seems unrelated to the packaging format anyway.

**Comment by kuateric** [comment] 2022-10-18 06:50
here is a typical behaviour we have on our ubuntu servers beside the "next button issue"
![grafik](https://user-images.githubusercontent.com/22998049/196356026-98169fab-c0c5-4c12-87e9-d7c08469fe1d.png)

**Comment by fmoc** [comment] 2022-10-18 07:45
@kuateric please open your own issue(s).

**Comment by TheOneRing** [comment] 2023-09-08 10:42
With Qt6 and egl support in qtwayland I get.
![thumb-Clipboard - September 8, 2023 12 35](https://github.com/owncloud/client/assets/200626/bba47f01-1d7d-471c-b439-aef468753e79)
However it appears egl support is not possible with our currently used centos image.
I'll disable qtwayland for 5.0, in Qt6 in with our sles15 based builds we should re enable it.
Taskbar and window title are still an issue we need to solve.

**Comment by TheOneRing** [comment] 2024-08-20 07:26
With https://github.com/owncloud/client/issues/11625 I think we can close this issue 🥳

**Closed by TheOneRing** 2024-08-20 07:26 UTC
Labels: p2-high, Linux, Early-Adopter:CERN
