### ISSUE TITLE
Server activty tab shows HTML entities

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#6433] opened 2018-04-06 11:00 UTC
### Expected behaviour
Filenames should be displayed correctly.

### Actual behaviour
When a synced filename contains an apostrophe, it shows up as ```&#039;``` in the server activity tab.

### Steps to reproduce
1. Upload a file containing an apostrophe in the filename.
2. Watch the server activity tab

### Server configuration
Operating system: Debian Jessie (Bananian)

Web server: Apache 2.4

Database: MySQL

PHP version: 5.6

ownCloud version: 10.0.7

Storage backend (external storage): Local

### Client configuration
Client version: 2.5.0-daily20180216 build 9245

Operating system: Windows 7

OS language: German

Installation path of client: Default

**Comment by ogoffart** [comment] 2018-04-09 06:27
Thanks for your bug report.
This is a duplicate of https://github.com/owncloud/client/issues/5576

(And it is actually a server bug.)

**Closed by ogoffart** 2018-04-09 06:27 UTC
Labels: bug
