### ISSUE TITLE
selective sync: renaming an unselected folder deletes the folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7438] opened 2019-08-28 14:01 UTC
Reproduce a potential data loss with 2.6.0 beta1

* connect to demo.owncloud.org as demo/demo
* deselect Photos in the selective sync list
![image](https://user-images.githubusercontent.com/1108546/63861716-aff26600-c9ab-11e9-9248-1a4e108ba257.png)
* log in to the web interface of demo.owncloud.org as demo/demo
* rename Photos to Danger
* wait and watch the client discover the change: Danger is being downloaded:
![image](https://user-images.githubusercontent.com/1108546/63861891-052e7780-c9ac-11e9-9b65-7f7024514e36.png)
* click open the sync folder a local file browser appears.
* In a local file browser rename Danger to Photos
* a notification appears, 
![image](https://user-images.githubusercontent.com/1108546/63862239-900f7200-c9ac-11e9-8ef7-92cf9bc0b69d.png)
* the selective sync list no longer has Danger or Photos
![image](https://user-images.githubusercontent.com/1108546/63862333-b3d2b800-c9ac-11e9-91d9-9e6b7f72fe09.png)
* the server no longer has Danger or Photos
![image](https://user-images.githubusercontent.com/1108546/63862419-d4027700-c9ac-11e9-98a4-d6f7a210c11e.png)
* all other connected clients also loose the Folder and all its contents.

(There is still a local copy of the Photos folder with all contents on the client that caused the delete. But this copy is not even shown as deselected in the selective sync list.

Expected result: The server is not affected and the client would show the reappearing Photos folder as unselected in the list.

Workaround: Restart the client. This brings back the deselected entry in the selective sync list. Select. It will be re-uploaded.

**Comment by jnweiger** [comment] 2019-08-28 14:31
The client does something stupid here:
```
08-28 16:12:03:084 [ info sync.propagator ]:    Starting INSTRUCTION_REMOVE propagation of "Danger" by OCC::PropagateRemoteDelete(0x556c463efa40)
08-28 16:12:03:084 [ info sync.accessmanager ]: 5 "" "https://demo.owncloud.org/remote.php/dav/files/demo/Danger" has X-Request-ID "6598a0fa-1744-4df6-866d-d83035fca4c3"
08-28 16:12:03:085 [ info sync.networkjob ]:    OCC::DeleteJob created for "https://demo.owncloud.org" + "/Danger" "OCC::PropagateRemoteDelete"
08-28 16:12:03:085 [ info sync.propagator ]:    Starting INSTRUCTION_IGNORE propagation of "Photos" by OCC::PropagateIgnoreJob(0x556c464cb080)
08-28 16:12:03:627 [ info sync.networkjob.delete ]:     DELETE of QUrl("https://demo.owncloud.org/remote.php/dav/files/demo/Danger") FINISHED WITH STATUS "OK"
```
[clientlog.zip](https://github.com/owncloud/client/files/3551395/clientlog.zip)

**Comment by jnweiger** [comment] 2019-08-29 12:29
https://testlink.owncloud.team/linkto.php?tprojectPrefix=desktop&item=testcase&id=desktop-122

**Comment by ogoffart** [comment] 2019-10-07 14:36
The problem is the same as if we move in a ignored directory.  Since we do not recurse in them, we also do not try to detect moves.  That would be inefficient (that's the whole point of ignoring)
So as far as the client is concerned, the directory was not "Renamed", it was simply "removed"  (and another new directory with the same inode was added in an ignored path, but that we don't even look at them)

**Comment by ogoffart** [comment] 2019-10-07 14:37
Note to self: test

```cpp
    void testMoveToSelectedSync() {
        // Test that moving things in something that is disabled, does not remove the local part

        FakeFolder fakeFolder { FileInfo::A12_B12_C12_S12() };
        fakeFolder.syncEngine().journal()->setSelectiveSyncList(SyncJournalDb::SelectiveSyncBlackList,
            QStringList() << QLatin1String("C") << QLatin1String("S"));
        ItemCompletedSpy completeSpy(fakeFolder);
        QVERIFY(fakeFolder.syncOnce());
        FileInfo aState = *fakeFolder.currentLocalState().find("A");
        FileInfo bState = *fakeFolder.currentLocalState().find("B");
        QCOMPARE(fakeFolder.currentRemoteState(), FileInfo::A12_B12_C12_S12()); // on the server, nothing changed
        QCOMPARE(*fakeFolder.currentRemoteState().find("A"), aState);
        QCOMPARE(*fakeFolder.currentRemoteState().find("B"), bState);
        QVERIFY(!fakeFolder.currentLocalState().find("S"));
        QVERIFY(!fakeFolder.currentLocalState().find("C"));

        // Move A to C
        fakeFolder.localModifier().rename("A", "C");
        // Move B to some folder inside S
        fakeFolder.localModifier().mkdir("S");
        fakeFolder.localModifier().rename("B", "S/B");

        completeSpy.clear();
        QVERIFY(fakeFolder.syncOnce());
        QCOMPARE(completeSpy.findItem("S")->_instruction, CSYNC_INSTRUCTION_IGNORE);
        QCOMPARE(completeSpy.findItem("S")->_errorString, "Ignored because of the \"choose what to sync\" blacklist");
        QCOMPARE(completeSpy.findItem("C")->_instruction, CSYNC_INSTRUCTION_IGNORE);
        QCOMPARE(completeSpy.findItem("C")->_errorString, "Ignored because of the \"choose what to sync\" blacklist");
        QCOMPARE(fakeFolder.currentRemoteState(), FileInfo::A12_B12_C12_S12()); // on the server, nothing changed

        // further sync should also change nothing
        QVERIFY(!fakeFolder.syncOnce());
        QCOMPARE(fakeFolder.currentRemoteState(), FileInfo::A12_B12_C12_S12());
        completeSpy.clear();
        QVERIFY(!fakeFolder.syncOnce());
        QCOMPARE(fakeFolder.currentRemoteState(), FileInfo::A12_B12_C12_S12());

        QCOMPARE(*fakeFolder.currentLocalState().find("C"), aState);
        QCOMPARE(*fakeFolder.currentLocalState().find("S/B"), bState);

        QCOMPARE(completeSpy.findItem("S")->_instruction, CSYNC_INSTRUCTION_IGNORE);
        QCOMPARE(completeSpy.findItem("S")->_errorString, "Ignored because of the \"choose what to sync\" blacklist");
        QCOMPARE(completeSpy.findItem("C")->_instruction, CSYNC_INSTRUCTION_IGNORE);
        QCOMPARE(completeSpy.findItem("C")->_errorString, "Ignored because of the \"choose what to sync\" blacklist");
    }
```

**Comment by ogoffart** [comment] 2019-10-14 10:41
I'm tempted to rule this as a WONTFIX.

Moves detection is just heuristic based. Moving is just a special case of deleting and re-creating.  When moving cross boundaries visible by the client, this is not moving anymore.

**Comment by ogoffart** [comment] 2020-03-05 10:31
Won't fix

**Closed by ogoffart** 2020-03-05 10:31 UTC
Labels: bug
