### ISSUE TITLE
Crash in findAndCancelDeletedJob

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7725] opened 2020-02-06 09:36 UTC
Investigate frequent crash in findAndCancelDeletedJob (the ENFORCE statement is crashing) (26 occurences)

Next steps: Patch release if needed, stop auto updater if needed, stop branded release if needed

**Comment by ogoffart** [comment] 2020-02-06 09:40
Duplicate of https://github.com/owncloud/client/issues/7722

**Closed by ogoffart** 2020-02-06 09:40 UTC
Labels: bug, p2-high
