### ISSUE TITLE
Sync client unable to start on Windows 10 Pro Insider Preview

### ISSUE THREAD

**Issue by mrneilsy** [owncloud/client#4411] opened 2016-01-31 04:05 UTC
owncloud.exe - The application was unable to start correctly (0xc0000142) Click OK to close the application.

Windows 10 Pro Insider Preview - Build 14251.rs1_release.160124-1059

**Comment by RealRancor** [comment] 2016-01-31 18:55
Very likely a duplicate of https://github.com/owncloud/client/issues/4405 and https://github.com/owncloud/client/issues/4413

**Closed** 2016-01-31 21:22 UTC
