### ISSUE TITLE
Windows xp client don't respond after adding new folder

### ISSUE THREAD

**Issue by nekoal** [owncloud/client#2828] opened 2015-02-11 23:04 UTC
### Expected behaviour
Client shows progress of analyzing files and subfolders then syncronize folder.

### Actual behaviour
In 5-10 seconds client stops to show information about analyzing folders and don't respond. Log window also don't respond. No new records in logfile or sometimes records about changes of other folder. CPU loads 40-50% from owncloud.exe
If do nothing in 1-2 hours client crash. Simular to https://github.com/owncloud/client/issues/2648 . 
If restart client or after crash, in some seconds client don't respond or return in normal state and start slow syncrun.

### Steps to reproduce
1. Configure local path to folder with large amount of small files, never syncronized before. (For me 1019 files and 30 subfolders, total size 38 MiB)
2. Create folder on server and select it as remote path
3. Get "No subfolders currently on server" (untranslated) on next screen and press AddFolder.
4. Wait before syncronization new folder runs

### Server configuration
Operating system: Windows XP SP3
Web server: Apache 2.0 
Database: MySQL
PHP version: 5.3.5
ownCloud version: 7.0.4
Storage backend: NTFS

### Client configuration
Client version: 1.8.0-nigntly20150207 (4697)
Operating system: Windows XP SP3
OS language: Russian
Installation path of client: D:\Program Files\ownCloud

### Logs
ownCloud log (data/owncloud.log):
No records after 05:03 until crash

Apache error log has no records at this time.
Apache access log about new folder:
* - bertix [12/Feb/2015:05:04:50 +0800] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 489
* - bertix [12/Feb/2015:05:04:55 +0800] "PROPFIND /owncloud/remote.php/webdav/wwwroot/resheniya01 HTTP/1.1" 207 723
* - bertix [12/Feb/2015:05:04:23 +0800] "MKCOL /owncloud/remote.php/webdav/wwwroot/resheniya01 HTTP/1.1" 201 -
* - bertix [12/Feb/2015:05:04:57 +0800] "MKCOL /owncloud/remote.php/webdav/wwwroot/resheniya01/2006 HTTP/1.1" 201 -

Modification of .csync_journal.db: 12/Feb/2015 05:04:36

Output of owncloud --logwindow: no avaiable
--logfile Last records:
02-12 05:04:57:414 0x57c7fc8 syncengine.cpp:680 Permissions of the root folder:  "RDNVCK"
02-12 05:04:57:430 0x57c7fc8 syncjournaldb.cpp:1274 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post treewalk" and starting new transaction
02-12 05:04:57:430 0x57c7fc8 syncjournaldb.cpp:1274 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post stale entry removal" and starting new transaction
02-12 05:04:57:445 0x57c7fc8 owncloudpropagator.cpp:334 Using QNAM/HTTP parallel code path
02-12 05:04:57:445 0x57c7fc8 socketapi.cpp:377 void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, OCC::SocketType*) "F:\wwwroot\resheniya0\2008\2\21.300 reshenie o zhalobah.rar"
02-12 05:04:57:445 0x57c7fc8 syncengine.cpp:1130 bool OCC::SyncEngine::estimateState(QString, csync_ftw_type_e, OCC::SyncFileStatus*) Setting "2008/2/21.300 reshenie o zhalobah.rar"  to STATUS_EVAL
02-12 05:04:57:445 0x57c7fc8 socketapi.cpp:563 OCC::SyncFileStatus OCC::SocketApi::fileStatus(OCC::Folder*, const QString&, c_strlist_t*) Folder estimated status for "2008/2/21.300 reshenie o zhalobah.rar" to "SYNC"
02-12 05:04:57:445 0x57c7fc8 socketapi.cpp:324 SocketApi:  Sending message:  "STATUS:SYNC:F:\wwwroot\resheniya0\2008\2\21.300 reshenie o zhalobah.rar"
02-12 05:04:57:445 0x57c7fc8 folder.cpp:861 #### Propagation start #################################################### >>
02-12 05:04:57:445 0x57c7fc8 socketapi.cpp:274 Not sending UPDATE_VIEW for "resheniya0" because status() is 3
02-12 05:04:57:445 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x61627b0)  with name  "dbases"
02-12 05:04:57:445 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x616cd90)  with name  "resheniya"
02-12 05:04:57:445 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x6163d38)  with name  "OST"
02-12 05:04:57:445 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x62264e0)  with name  "resheniya0"
02-12 05:04:57:445 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x6173088)  with name  "files"
02-12 05:04:57:445 0x57c7fc8 owncloudgui.cpp:182 Sync state changed for folder  "resheniya0" :  "Sync Running"
02-12 05:04:57:445 0x57c7fc8 propagateremotemkdir.cpp:28 virtual void OCC::PropagateRemoteMkdir::start() "2006"
02-12 05:04:57:445 0x57c7fc8 networkjobs.cpp:228 !!! OCC::MkColJob created for  QUrl( "**" )  querying "wwwroot/resheniya01/2006"
02-12 05:04:57:445 0x57c7fc8 socketapi.cpp:377 void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, OCC::SocketType*) "F:\wwwroot\resheniya0\2010\2\81.832_O predsedatelyah uik po okrugu 8.rar"
02-12 05:04:57:461 0x57c7fc8 syncengine.cpp:1130 bool OCC::SyncEngine::estimateState(QString, csync_ftw_type_e, OCC::SyncFileStatus*) Setting "2010/2/81.832_O predsedatelyah uik po okrugu 8.rar"  to STATUS_EVAL
02-12 05:04:57:461 0x57c7fc8 socketapi.cpp:563 OCC::SyncFileStatus OCC::SocketApi::fileStatus(OCC::Folder*, const QString&, c_strlist_t*) Folder estimated status for "2010/2/81.832_O predsedatelyah uik po okrugu 8.rar" to "SYNC"
02-12 05:04:57:461 0x57c7fc8 socketapi.cpp:324 SocketApi:  Sending message:  "STATUS:SYNC:F:\wwwroot\resheniya0\2010\2\81.832_O predsedatelyah uik po okrugu 8.rar"
02-12 05:14:58:570 0x615f7b0 folderwatcher_win.cpp:88 void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "E:/dbases/Tik.mdb" action: 3
02-12 05:14:58:570 0x615f7b0 folderwatcher_win.cpp:88 void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "E:/dbases/Tik.ldb" action: 2
02-12 06:18:21:586 0x57c7fc8 :0 QWindowsXPStylePrivate::buffer(w,h), failed to create dibsection ()

After crash:
02-12 06:32:32:836 0x57c7fc8 application.cpp:332 "################## ownCloud ru_RU () 1.8.0"
...
02-12 06:33:28:898 0x57c7fc8 owncloudpropagator.cpp:334 Using QNAM/HTTP parallel code path
02-12 06:33:28:898 0x57c7fc8 folder.cpp:861 #### Propagation start #################################################### >>
02-12 06:33:28:898 0x57c7fc8 socketapi.cpp:274 Not sending UPDATE_VIEW for "resheniya0" because status() is 3
02-12 06:33:28:898 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x61619a0)  with name  "files"
02-12 06:33:28:898 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x6167fd0)  with name  "OST"
02-12 06:33:28:898 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x6162a10)  with name  "dbases"
02-12 06:33:28:898 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x6168e60)  with name  "resheniya0"
02-12 06:33:28:898 0x57c7fc8 owncloudgui.cpp:257 Folder in overallStatus Message:  OCC::Folder(0x6164030)  with name  "resheniya"
02-12 06:33:28:898 0x57c7fc8 :0 QString::arg: Argument missing: %! (????????????? ??????????????), ????????????? ??????????????.
02-12 06:33:28:914 0x57c7fc8 owncloudgui.cpp:182 Sync state changed for folder  "resheniya0" :  "Sync Running"
02-12 06:33:28:914 0x57c7fc8 propagateremotemkdir.cpp:28 virtual void OCC::PropagateRemoteMkdir::start() "2006/1"
02-12 06:33:28:914 0x57c7fc8 networkjobs.cpp:228 !!! OCC::MkColJob created for  QUrl( "**" )  querying "wwwroot/resheniya01/2006/1"

Local path: F:\wwwroot\resheniya0
Remote path: /wwwroot/resheniya01
On server exists subfolder 2006, subfolders for other years not exist. After crash/restart also 2006/1 exists. Something about subfolders?

**Comment by nekoal** [comment] 2015-02-12 03:21
When Accounts tab inactive in 5 seconds syncronization begun. Another case of https://github.com/owncloud/client/issues/2648

**Comment by ckamm** [comment] 2015-02-12 07:18
I think I saw similar symptoms yesterday before I applied the fix to discovery phase destruction (89c69250eff3f2cf5f8b7c7b0d09cccc61e3160b). Does it still happen with today's nightly? (>=20150212)

**Comment by nekoal** [comment] 2015-02-12 07:55
1.8.0-nightly20150212 (4712) latest I can see now - don't respond, syncrun if Account tab inactive. About crash needs wait.

**Comment by ckamm** [comment] 2015-02-12 08:31
@nekoal You're saying the problem still occurs. I'll try to reproduce it.

**Comment by ckamm** [comment] 2015-02-12 08:55
I can't reproduce it on Win7 - and as you said, the log line

    QWindowsXPStylePrivate::buffer(w,h), failed to create dibsection ()

indicates that this is indeed a duplicate of #2648. Thanks for the extra info, let's close this issue and track it over there.

**Closed by ckamm** 2015-02-12 08:55 UTC
Labels: bug, sev1-critical

**Comment by nekoal** [comment] 2015-02-12 09:18
Thanks. Yes, I can't reproduce it on Win7 too. But on Win XP problem still occurs. It's strange client crashes in a hour in non-respond state without records in logs. I wonder may be it's different problem from crash. At least, in logging. First 3-4 minutes client created 11MB log file, then 3 lines in a hour.
