### ISSUE TITLE
testpilotcloud nsis installer is not properly branded

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6010] opened 2017-09-08 12:43 UTC
![testpilotcloud-syncclient-installer-nsi-page_header](https://user-images.githubusercontent.com/1108546/30211976-529fcec8-94a3-11e7-86f3-a57edd0def3c.png)

This logo should show nice golden testpilot colors.

(.. and hey, also for the unbranded client: this logo looks like a trademark variation when compared with 
[Logo Usage Requirements](https://owncloud.org/trademarks) )

**Comment by guruz** [comment] 2017-09-08 13:05
Is this a duplicate of https://github.com/owncloud/client/issues/6006 ?

**Comment by guruz** [comment] 2017-09-08 13:05
I'd consider this urgent if it impacts branding in general..

**Comment by michaelstingl** [comment] 2017-09-08 16:21
No, it's only a testpilotcloud image missing in the testpilotcloud theming.

**Comment by ogoffart** [comment] 2017-10-17 10:48
Where are the source of the testpilotcloud theme?  
They are not in this repository so the issue does not belong here.

**Comment by michaelstingl** [comment] 2017-10-18 16:31
It would be cool to have the testpilotcloud theme in this repo.

**Comment by michaelstingl** [comment] 2018-02-05 13:50
Tasks to improve here with the future MSI installer (2.5.0+):

- [ ] Fix ownCloud icon in unbranded installer /cc @ChrisEdS @hurradieweltgehtunter 
- [ ] Add a proper testpilotcloud logo to the testpilotcloud branding ==> @ChrisEdS

**Comment by ChrisEdS** [comment] 2018-02-06 17:20
@jnweiger @michaelstingl Should the testpilot logo differs from the one used in our unbranded installer?

**Comment by michaelstingl** [comment] 2018-02-06 17:23
Yes, testpilotcloud uses different icons. Should use logos in the same style.

**Comment by ChrisEdS** [comment] 2018-02-07 13:25
Done. Changed the page_header.bmp in testpilotcloud to match our design guidelines.
I didn't take the gradient. It's only one color now: #ddd333

![monosnap 2018-02-07 14-24-58](https://user-images.githubusercontent.com/33026403/35918619-b8cebc54-0c12-11e8-8c01-0d0778936776.png)

**Comment by jnweiger** [comment] 2018-02-11 17:51
testpilotcloud-client for Linux still has the gradient. I suppose that is okay. Right?
![shaded](https://user-images.githubusercontent.com/1108546/36076447-87ac3974-0f5c-11e8-9e3c-0db958d2882e.png)

**Comment by michaelstingl** [comment] 2018-02-11 19:26
Okay for now. @ChrisEdS only changed the logo of the Win Installer.

**Comment by ChrisEdS** [comment] 2018-02-11 21:29
I think this testpilot-client Linux logo is acceptable - the problem on Windows installer was that there was used the completely wrong CI

**Comment by hurradieweltgehtunter** [comment] 2018-02-12 19:29
I think it's not acceptable. Not only have I never heard of gold/yellowish in our CI nor have I heard about the gradient green. But if we will use this, we should use it consistently (Both yellow/goldish)

**Comment by ChrisEdS** [comment] 2018-02-12 19:36
Good. We have to decide then which one we want to use.

**Comment by michaelstingl** [comment] 2018-02-12 21:14
I like the gradient one because it looks extra-cheesy. Also on white background. This makes it pretty  clear it's not the official thing.

**Comment by hurradieweltgehtunter** [comment] 2018-02-14 19:32
We do not use gradients anywhere and we shouldn't start here. 
Proposals:
![image](https://user-images.githubusercontent.com/16665512/36223812-971710a8-1193-11e8-81df-05de58bd5fda.png)

![image](https://user-images.githubusercontent.com/16665512/36223832-a7b555c8-1193-11e8-9942-7595c8ecf33f.png)

![image](https://user-images.githubusercontent.com/16665512/36223841-b040d4ba-1193-11e8-84a1-11620898d6b4.png)

Colors are generated by using a color palette using oc dark blue as base. I'm fine with all of them.

**Comment by michaelstingl** [comment] 2018-02-14 22:10
Okay, looks like a quick fix isn't enough. We need a proper solution. I opened a new issue: https://github.com/owncloud/client/issues/6359

**Closed by michaelstingl** 2018-02-14 22:10 UTC
Labels: Design & UX, p3-medium
