### ISSUE TITLE
[Menu] Owncloud client Siggev

### ISSUE THREAD

**Issue by pollend** [owncloud/client#3734] opened 2015-09-02 15:03 UTC
here is the stack-trace from valgrind

==5002== Jump to the invalid address stated on the next line
==5002==    at 0x0: ???
==5002==    by 0x5D4DFC5: QMenu::actionEvent(QActionEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5C115D7: QWidget::event(QEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5D54022: QMenu::event(QEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5BCE4AB: QApplicationPrivate::notify_helper(QObject*, QEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5BD3975: QApplication::notify(QObject*, QEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x98A261A: QCoreApplication::notifyInternal(QObject*, QEvent*) (in /usr/lib64/libQt5Core.so.5.5.0)
==5002==    by 0x5C08854: QWidget::insertAction(QAction*, QAction*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5D49DC8: QMenu::addSeparator() (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x4AFBE2: OCC::ownCloudGui::setupContextMenu() (in /usr/bin/owncloud)
==5002==    by 0x4B06FA: OCC::ownCloudGui::ownCloudGui(OCC::Application*) (in /usr/bin/owncloud)
==5002==    by 0x46B5DC: OCC::Application::Application(int&, char**) (in /usr/bin/owncloud)
==5002==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==5002== 
==5002== 
==5002== Process terminating with default action of signal 11 (SIGSEGV)
==5002==  Bad permissions for mapped region at address 0x0
==5002==    at 0x0: ???
==5002==    by 0x5D4DFC5: QMenu::actionEvent(QActionEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5C115D7: QWidget::event(QEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5D54022: QMenu::event(QEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5BCE4AB: QApplicationPrivate::notify_helper(QObject*, QEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5BD3975: QApplication::notify(QObject*, QEvent*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x98A261A: QCoreApplication::notifyInternal(QObject*, QEvent*) (in /usr/lib64/libQt5Core.so.5.5.0)
==5002==    by 0x5C08854: QWidget::insertAction(QAction*, QAction*) (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x5D49DC8: QMenu::addSeparator() (in /usr/lib64/libQt5Widgets.so.5.5.0)
==5002==    by 0x4AFBE2: OCC::ownCloudGui::setupContextMenu() (in /usr/bin/owncloud)
==5002==    by 0x4B06FA: OCC::ownCloudGui::ownCloudGui(OCC::Application*) (in /usr/bin/owncloud)
==5002==    by 0x46B5DC: OCC::Application::Application(int&, char**) (in /usr/bin/owncloud)

**Comment by guruz** [comment] 2015-09-03 08:26
Please also give us your distribution and exact Qt version, thanks.

**Comment by pollend** [comment] 2015-09-03 13:46
Qt version 5.5.0
Fedora 22
Kde 5.3

**Comment by ckamm** [comment] 2015-09-04 06:02
Thanks @pollend! It's a duplicate of #3672, a fix to kf5-frameworkintegration is on its way.

**Closed by ckamm** 2015-09-04 06:02 UTC
