### ISSUE TITLE
[Qt] [OS X] [SSL] client doesn't find CA trusted by user

### ISSUE THREAD

**Issue by p-blomberg** [owncloud/client#2964] opened 2015-03-15 17:34 UTC
### Expected behaviour
The client connects without asking any SSL-related questions, because the CA is trusted in Keychain Access. 

### Actual behaviour
After entering the server address, I get this:

---

Warnings about current SSL Connection:
The issuer certificate of a locally looked up certificate could not be found
The root CA certificate is not trusted for this purpose
No certificates could be verified

---

Safari connects to the web GUI without any problems, and I have _not_ trusted the certificate, only the CA.

### Screenshot
https://gist.github.com/p-blomberg/8528ac70c4bea0af1a2a#file-screenshot-2015-03-15-18-13-41-png

### Steps to reproduce
1. Set up your own CA
2. Import the CA certificate in Keychain Access
3. Open the certificate in keychain access, and set trust to "Always trust"
4. Set up the owncloud server and use the CA to sign the certificate
5. Try to connect to the server and get the errors above

### Server configuration
Operating system: Debian 7.8
Web server: Apache 2.2 with SNI
Database: MySQL 5.5.41
PHP version: 5.4.36
ownCloud version: 7.0.4
Storage backend: ext4 file system

### Client configuration
Client version: 1.7.1 (build 1655)
Operating system: OSX 10.9.5
OS language: English
Installation path of client: /Applications/owncloud.app

### Logs
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
https://gist.github.com/p-blomberg/8528ac70c4bea0af1a2a

2. Web server error log:
Does not contain a single line about this connection attempt

3. ownCloud log (data/owncloud.log):
There is no file with that name :(

**Comment by guruz** [comment] 2015-03-16 09:13
Please try 1.8rc1

**Comment by petrindade** [comment] 2015-03-16 11:58
Hi all!

I just reported the same problem on a similar issue ( #510 )
(Same problem when running latest client, ownCloud and OS X)

Best regards

**Comment by boltronics** [comment] 2015-03-18 03:35
I just got this after a client update on Debian (owncloud-client:amd64, 1.8.0). The weird thing: I actually do own have a certificate and this has always worked fine with ownCloud until today.

You can see my certificate here: https://systemsaviour.com/ Is everyone else with this issue also using a wildcard cert? That's the only interesting thing I can think of. Otherwise, happy to open another bug report.

**Comment by danimo** [comment] 2015-03-18 05:54
@boltronics I just tested connecting to the owncloud instance mentioned in your Multidomain certificate. I do not receive any warning (using Ubuntu 14.04, though that should not be a problem).

**Comment by boltronics** [comment] 2015-03-18 06:46
@danimo Thanks for checking. In that case, I'll open another ticket.

**Comment by oascn-petrindade** [comment] 2015-03-18 09:49
@boltronics In my case, the CN is not wildcard but the DNS name is wildcard (in the  Subject Alternative Name (2.5.29.17) extension).

**Comment by boltronics** [comment] 2015-03-18 14:14
@oascn-petrindade I just remembered I had an owncloud-specific SAN entry in my cert as well.

I've now opened a separate ticket (#2979) for my issue. It could be a duplicate of this (the same root cause), but this ticket specifically refers to OSX so have erred on the safe side.

**Comment by p-blomberg** [comment] 2015-03-20 18:41
@guruz, I have now tried 1.8.0 build 2139 without any difference.
@boltronics, no, my certificate is only for my owncloud subdomain, nothing else.

**Comment by p-blomberg** [comment] 2015-03-20 19:03
@guruz, is there any way to get a more verbose log from QSslCertificate?

**Comment by guruz** [comment] 2015-03-26 16:16
> is there any way to get a more verbose log from QSslCertificate?

I checked your log, what info are you missing?

Does checking the checkbox allow you to connect permanentely?

@danimo I guess this happened when switching to non-system OpenSSL?
I thought Qt would load the system stuff..
Or maybe we need a ```setCaCertificates(QSslSocket::systemCaCertificates());``` somewhere..

**Comment by guruz** [comment] 2015-03-26 16:21
Is it in the "login" keychain?

**Comment by p-blomberg** [comment] 2015-03-29 20:46
> I checked your log, what info are you missing?

Something to help figure out why QSslCertificate doesn't find the CA. I don't know :)

> Does checking the checkbox allow you to connect permanentely?

Yes, but that's not good enough as I want to connect many computers to my owncloud and checking the certificate manually is really.. not fun. And when the certificate is renewed, I'll have to do it all over again, on every computer.

> Is it in the "login" keychain?

I have imported it to both the "login" and the "system" keychains, that makes no difference.

**Comment by guruz** [comment] 2015-04-15 13:32
The mumble guys have the same problem: https://github.com/mumble-voip/mumble/issues/1483#issuecomment-64168983

http://code.woboq.org/qt5/qtbase/src/network/ssl/qsslsocket_openssl.cpp.html#_ZN17QSslSocketPrivate20systemCaCertificatesEv

https://developer.apple.com/library/mac/documentation/Security/Reference/certifkeytrustservices/index.html#//apple_ref/c/func/SecTrustSettingsCopyCertificates

**Comment by rbarlow** [comment] 2015-04-26 01:19
Hello!

I too have been experiencing this issue, but I wanted to add a tiny bit of info I learned about it tonight. It had seemed like openssl was also not trusting the certificate, until I learned a funny thing about openssl on OSX. I'm a Linux user, so this was weird to me: openssl s_connect will not use the system certificate store unless you pass something to its -CApath flag. Before I knew this, I thought openssl also wasn't trusting my certificate, but if I invoke openssl like this, everything works:

```
openssl s_connect -connect owncloud.example.com:443 -verify 5 -CApath \? 
```

Like others have pointed out, Safari and Firefox are also both happy with the certificate. I just wanted to add that openssl, which is the library used by QT, is also happy with the certificate when invoked correctly. Perhaps the way that OwnCloud is using the QT library in OSX is the issue? I spoke with one of the QT SSL developers in #qt on Freenode today and he suggested that it sounded likely to be an OwnCloud issue. I'm willing to assist in further communications with the QT team if that would be helpful to you!

OwnCloud worked for me in July 2014 on this same computer, but sometime in the early fall (perhaps September or October) it started experiencing this issue. Sadly, I did not record the specific time that the issue appeared, or what changed on the computer at the time. This is OSX Mavericks.

**Comment by porjo** [comment] 2015-05-06 06:19
I'm getting this error with Linux desktop client (Fedora 20) and a Geotrust RapidSSL cert:

<img src="https://cloud.githubusercontent.com/assets/1296987/7488252/f4b17040-f40a-11e4-97ac-da46add72b4b.png" width="300">

**Comment by danimo** [comment] 2015-05-06 07:37
@porjo Different issue, please open a new one. But before you do, please make sure that the GeoTrust Global CA cert is part of Fedora's root certificate list.

**Comment by porjo** [comment] 2015-05-07 09:35
@danimo sorry, I'm not entirely sure how I'd do that. I've tested with `openssl` from the command line and it seems ok - see here: http://pastebin.com/iG2Ne551

**Comment by guruz** [comment] 2015-05-12 09:35
@porjo This issue is about OS X.

**Comment by porjo** [comment] 2015-05-13 03:29
I've created a new issue now - #3231 . Sorry for the noise.

**Comment by nebukadnezar** [comment] 2015-09-07 00:18
This is still happening on OSX, see attached screenshots. The SSL Cert is fine with Safari/Firefox/Chrome but the ownCloud OSX Client is not trusting it. #3231  

![screen shot 2015-09-07 at 10 05 13](https://cloud.githubusercontent.com/assets/5976813/9707371/adb2abf0-5549-11e5-9bfc-ab818fa183dc.png)
![screen shot 2015-09-07 at 10 06 10](https://cloud.githubusercontent.com/assets/5976813/9707372/adb5ae2c-5549-11e5-9a6c-da68fd2c5f76.png)

**Comment by danimo** [comment] 2015-09-07 05:27
@nebukadnezar That's because you did not deploy the intermediate certificate, so the client cannot establish the trust chain. Browsers tend to download it silently, resulting in an extra delay when contacting the server at the first time, but that cannot be expected generally. See https://www.ssllabs.com/ssltest/analyze.html?d=cloud.inside.net&latest. Check your certificate issuers documentation for details on how to deploy intermediates with your webservers.

**Comment by nebukadnezar** [comment] 2015-09-08 12:57
@danimo thanks! that helped getting me on the right track - I never even realised I didn't install SSL certs correctly all these years. I'm tempted to be embarrassed about that.

**Comment by danimo** [comment] 2015-11-17 12:12
Qt upstream bug: https://bugreports.qt.io/browse/QTBUG-32898, fix in https://codereview.qt-project.org/#/c/140966/

**Comment by guruz** [comment] 2015-11-29 15:15
@danimo This is fixed in 2.1rc1 right?

**Comment by danimo** [comment] 2015-11-30 21:38
Yes, http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.2922-nightly20151130.pkg should do.

**Comment by Dianafg76** [comment] 2015-12-02 11:42
@danimo I tested this issue, and I see my certificate this way:
![screen shot 2015-12-02 at 12 40 53](https://cloud.githubusercontent.com/assets/12032058/11530096/f9e5f6e4-98f1-11e5-813e-fe2cfe41a8c3.png)

**Comment by Dianafg76** [comment] 2015-12-02 12:18
@p-blomberg Could Have you tried 2.1.0 RC1?

**Comment by danimo** [comment] 2015-12-02 13:58
@Dianafg76 it works for me. Please provide the exactly that you used to test the issue.

**Comment by danimo** [comment] 2015-12-02 15:33
@michaelstingl can you provide feedback until EoD today?

**Comment by michaelstingl** [comment] 2015-12-02 15:48
@danimo I tested with ``mitmproxy-ca-cert.pem`` and proxy configured in the System Preferences. Works for me without errors!

**Comment by danimo** [comment] 2015-12-02 16:56
Ok, what seems to be happening is that diana tried to add the cert for the SG docker setup. This one is invalid on a lot of other ways. We'll sort this out separately.

**Closed by danimo** 2015-12-02 16:56 UTC
Labels: bug, Needs info, ReadyToTest
