### ISSUE TITLE
LibreOffice *.ods files not syncing due to "Hard links are not supported"

### ISSUE THREAD

**Issue by masscream** [owncloud/client#3078] opened 2015-04-08 08:28 UTC
Hello,

I decided to switch from MO to LO lately so I started converting my documents from xlsx to .ods format for better compatibility. When I firstly created a document in OC folder (PC1), it was uploaded with all the changes. On another PC(PC2) later I decided to continue working on that document and saved changes. They were uploaded on OC. Now I am trying to continue working on the PC1, but OC client refuses to download these files from my server due to "Hard links are not supported in syncing" error. If I download it manually from OC site, the changes from yesterday are all there, otherwise the changes done from PC2 are not there. I was searching on the internet how exactly hard links work, but these files are not any links, they are originals. I tried both client versions - Windows and Linux, at Windows I don't even see the error message but after Sync done successfully, the changes are still not loaded at the file. Linux client is giving me this "Info" message. Does anybody have similar experience, please?

**Comment by ckamm** [comment] 2015-04-09 09:08
@masscream PC1 is running Windows and PC2 is running Linux?

On the linux PC, try

    ls -l my.ods

It will print something like

    -rw-rw-r-- 5

And the 5 is the number of hard links the file has. Is it 1?

If it isn't one, you can try finding the other linked files with something like

    find ~ -samefile path/to/my.ods

**Comment by masscream** [comment] 2015-04-09 10:07
Actually, it is a little bit more complicated, I've got Windows & Linux on both PCs, the command shows 2 next to file's access rights, but when I try to execute find / -samefile path/to/my.ods (because I don't store my files only in Home folder), it finds nothing except that file. Bus as you asked me about the OS of the PC, I think I'm starting to suspect the W/L conflict, it would not be the first time they made a war about accessing files. I will disable sync in windows and rewrite the file in OC folder. If it works next few sync sessions, I have the cause.

**Comment by ckamm** [comment] 2015-04-09 12:09
@masscream I think there was a problem with the NTFS filesystem driver on linux using hardlinks to map the 8.3 filename format to the long file names windows uses normally. I'll look for the old ticket.

**Comment by ckamm** [comment] 2015-04-09 12:10
Duplicate of #1143

**Closed by ckamm** 2015-04-09 12:10 UTC
Labels: Needs info
