### ISSUE TITLE
ownCloud Client fails to retrieve password, when KWallet isn't open

### ISSUE THREAD

**Issue by Aentfs** [owncloud/client#1570] opened 2014-03-14 15:10 UTC
### Expected behaviour
ownCloud Client should open KWallet, if it isn't already open, so that the user can type in its password.

### Actual behaviour
ownCloud Client fails to open KWallet, when it's closed, but works after manually opening the wallet.

### Steps to reproduce
1. Close the ownCloud Client
2. Close all open wallets
3. Start ownCloud Client
4. ownCloud Client asks for password itself, instead of opening the wallet
5. Close ownCloud Client
6. Open wallets manually
7. Start ownCloud Client
8. ownCloud Client doesn't ask for password and syncs

### Server configuration
Operating system: [will be provided if necessary]

Web server: [will be provided if necessary]

Database: [will be provided if necessary]

PHP version: [will be provided if necessary]

ownCloud version: ```ownCloud 6.0.2 (stable)``` 

Storage backend: [will be provided if necessary]

### Client configuration
Client version: 
* ```Version 1.5.3 (Git revision c8a8eb; OCsync 0.19.5; Qt 4.8.5)```
* ```qtkeychain-git: 0.1.0.58.gc130727-1```
* ```qtwebkit: 2.3.3-1```
* ```neon: 0.30.0-1```

Operating system: ```Linux 3.13.6-1-ARCH #1 SMP PREEMPT Fri Mar 7 22:47:48 CET 2014 x86_64 GNU/Linux```

OS language: ```de_DE.UTF-8``` (generated locals: ```de_DE.UTF-8``` ```en_US.UTF-8```)

Installation path of client: ```$ whereis owncloud
owncloud: /usr/bin/owncloud [binary] /usr/share/owncloud [folder with l10n inside]```

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

https://gist.github.com/Aentfs/cd7d5b7fdaf410ea3af0

2. Web server error log: [will be provided if necessary]

3. ownCloud log (data/owncloud.log): [will be provided if necessary]

**Comment by ogoffart** [comment] 2015-02-02 16:24
Closing as duplicate of #1902

**Closed by ogoffart** 2015-02-02 16:24 UTC
Labels: bug
