### ISSUE TITLE
Thousands of files deleted

### ISSUE THREAD

**Issue by Sqwrly** [owncloud/client#3131] opened 2015-04-19 17:46 UTC
This isn't the same issue I see other people talking about where the files are still on the web interface.

I store a bunch of portable apps and their configs on my owncloud. Today I went to start one and it wasn't found, I looked in my bin folder in owncloud and it only had 2 folders. So I go into the web interface and it showed a ton of deleted files in the last 48 hours, which I didn't delete. I proceeded to restore them and it restored pretty much every folder and file right into the root of my owncloud. All subfolders and everything all in the root, totally disorganized and just screwed everything up.

**Comment by guruz** [comment] 2015-04-20 08:33
This sounds very unfortunate. 
Can you use the template please https://raw.githubusercontent.com/owncloud/client/master/issue_template.md
This is all very dependant on versions.

Also logs much appreciated.

**Comment by rbahassine** [comment] 2015-04-22 16:09
Hi all,

I have the same issue !
When I grep for "DELETE" in the access log, it return me the list of all deleted files, here an extract (*more than 100 lines of DELETE*) :
```shell
root@BOCC7-1-WEB-01:/var/log/apache2/boccloud# grep DELETE boccloud_access.22-04-2015.log
192.168.16.139 - JCMA [22/Apr/2015:17:42:32 +0200] "DELETE /remote.php/webdav/Projet%20Magellan/4-DELIVRABLES_Echanges_IFS/2-Conception/Achat/BOC-ODJ_ACHAT_20150113.docx HTTP/1.1" 204 695 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
192.168.16.139 - JCMA [22/Apr/2015:17:42:44 +0200] "DELETE /remote.php/webdav/Projet%20Magellan/4-DELIVRABLES_Echanges_IFS/2-Conception/Achat/BOC-ODJ_ACH_20141120.docx HTTP/1.1" 204 696 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
192.168.16.139 - JCMA [22/Apr/2015:17:42:44 +0200] "DELETE /remote.php/webdav/Projet%20Magellan/4-DELIVRABLES_Echanges_IFS/2-Conception/Achat/BOC-RF_ACHAT_2015011415-V1.docx HTTP/1.1" 204 695 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
192.168.16.139 - JCMA [22/Apr/2015:17:42:45 +0200] "DELETE /remote.php/webdav/Projet%20Magellan/4-DELIVRABLES_Echanges_IFS/2-Conception/Achat/BOC-RF_ACHAT_2015011415-V2.docx HTTP/1.1" 204 695 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
```

Nothing in my error.log.

This happend 2 times / week and randomly! Unable to reproduce!
All client have 1.8.0 desktop client and the server is 7.0.4.
**Web Server** : Apache/2.2.22
**MySQL version** : 5.5.35
**PHP Version** : PHP 5.3.10

I have one folder that is shared with more than 30 users and they all have full access except sharing.

The bug appears with users that have slow connexion. And the files are available in their trash. I can see the files in oc_filecache table with PHPMYADMIN.

Any Idea? May I help with some specific tests?

**Comment by rbahassine** [comment] 2015-04-22 16:21
Other informations : files are in the filetrash of the user that called the "DELETE" request (user JCMA) and in my filetrash (maybe, because I am the owner of this folder and I share it with JCMA)

**Comment by rbahassine** [comment] 2015-04-23 08:14
Hi,

This morning we got an other folders deletion.. more than 200Mo of data deleted!
Strange, when I grep for one of the deleted file in the apache access log I get this : 
```shell
root@BOCC7-1-WEB-01:~# grep BOC-RF_REU_20150306_revGF%20revu%20Boccard.docx  /var/log/apache2/boccloud/boccloud_access.23-04-2015.log
192.168.41.106 - JCMA [23/Apr/2015:09:01:07 +0200] "DELETE /remote.php/webdav/Projet%20Magellan/4-DELIVRABLES_Echanges_IFS/2-Conception/Finance/BOC-RF_REU_20150306_revGF%20revu%20Boccard.docx HTTP/1.1" 204 695 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
192.168.16.137 - LBE [23/Apr/2015:09:33:33 +0200] "GET /remote.php/webdav/Projet%20Magellan/4-DELIVRABLES_Echanges_IFS/2-Conception/Finance/BOC-RF_REU_20150306_revGF%20revu%20Boccard.docx HTTP/1.1" 404 1064 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
```

Regarding Apache access log, user **JCMA** send a DELETE request at **09:01:07** and user **LBE** send a GET request **09:33:33** (30 minutes later!) How could LBE request for a deleted file 30 min earlier?

**Comment by alexpyattaev** [comment] 2015-04-23 18:21
Confirming again, with no reason whatsoever, owncloud client 1.8.0 on Suse linux 64 bit, official build, decided it is a good idea to delete a directory (only one out of many), together with its contents. The only thing that I did is saved one of the files in the directory, causing an upload sync. This is how the log looked like (documents is the folder name, file names not relevant to the crash are redacted, log truncated since there was an entry for every object in the documents directory):          
>4/23/15 7:45 innocent file 3           documents      Deleted                  
>4/23/15 7:45 PM innocent file 2                        documents      Deleted                  
>4/23/15 7:45 PM innocent file 1                      documents      Deleted                  
>4/23/15 7:45 PM.directory                                                      documents      Deleted                  
>4/23/15 7:39 PM univer/antennas/paper/main.lyx                                  documents      Uploaded       12 KiB    
>4/23/15 7:38 PM univer/antennas/paper/#main.lyx#                                documents      Uploaded       12 KiB    
>4/23/15 7:28 PM univer/antennas/paper/#main.lyx#                                documents      Uploaded       11 KiB    
>4/23/15 7:23 PM univer/antennas/paper/#main.lyx#                                documents      Uploaded       11 KiB    

As if nothing is happening!  By pure miracle I noticed that something fishy is happening and prevented the upload of changes to the server. 
There were no errors reported. Given how shitty my connection is right now, my first suspicion is race conditions somewhere in the sync code. Sadly, I can not provide much more info than that, but if bad links/terminated and timeouted sockets could be a problem they definitely are here in China thanks to the great firewall. 
This bug is not new at all, similar things have been noticed since 2012, please look at the race conditions/unhandled socket exceptions, maybe that is the key.

**Comment by lopezmts** [comment] 2015-04-29 16:49
I have about 250 users. I have seen this problem about 10 times already. For some reason owncloud Desktop client deletes files without a reason or user intervention. owncloud client 1.8.0 running on Windows.

**Comment by danimo** [comment] 2015-04-29 16:55
This should be fixed in 1.8.1rc1, please try https://owncloud.org/install/#testing. We'll release it asap, after we've gathered sufficient results.

**Comment by Sqwrly** [comment] 2015-04-29 17:34
That link takes me to the normal download page with no test builds. DL links are all 1.8.0.

**Comment by danimo** [comment] 2015-04-29 17:36
@Sqwrly it should highlight the "testing" section though, which is where the RC builds are located.

**Comment by Sqwrly** [comment] 2015-04-29 17:40
Nope: http://i.imgur.com/xsV4ek3.png

I see the "testing packages" link now and grabbed the test build, but that said the page is no different than the normal download page. Tried in Chrome and FF.

**Comment by alexpyattaev** [comment] 2015-04-29 17:51
Just a small remark - what was the problem? was there something on the
user's side that triggers this?

**Comment by Ultra2D** [comment] 2015-04-30 10:58
@danimo could you please explain what caused this, as @alexpyattaev also requested? How has it been fixed?

**Comment by danimo** [comment] 2015-04-30 11:06
@Sqwrly Click on "testing package". It will open a box with the download links.

**Comment by danimo** [comment] 2015-04-30 11:08
@alexpyattaev @Ultra2D Insufficient handling of invalid error responses. See

https://mailman.owncloud.org/pipermail/devel/2015-April/001215.html:
```
 * Discovery: Fix parsing of broken XML replies (avoids local file deletion)
```

We've since improved the robustness of the XML parser, which was rewritten for 1.8, and added more tests.

**Comment by jondo** [comment] 2015-07-22 12:55
Can this issue be closed?

**Comment by guruz** [comment] 2015-07-22 14:22
Indeed, closing this.
If you get this with 1.8.4 and a 8.1.x server please open a new issue with logs and help us to find the cause.

**Closed by guruz** 2015-07-22 14:22 UTC
Labels: Needs info
