### ISSUE TITLE
reproducible data loss when file is renamed and virtual file suffix is added at the same time

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#7001] opened 2019-01-24 16:10 UTC
Hi there ,

operating system  : Ubuntu 18.10;  client 2.5.2rc2

i think title says a lot , simply follow the steps to reproduce the data loss : 
- enable virtual-files Feature
- delete all files in sync-folder then a message pops up ,please select keep files
- let's suppose we have 2 files with following extensions : 
something.txt.owncloud_virtual
something.pdf.owncloud_virtual
- please download the files (listed above) over owncloud-menu
- files are now  so : something.pdf  and something.txt
-now rename files to something.owncloud_virutal   (please delete the extensions .pdf and .txt )
- force sync
-files are not existing any more on the server 

regards

**Comment by jnweiger** [comment] 2019-01-24 17:02
Also reproducable with a windows client. Ouch!

**Comment by lazawan** [comment] 2019-01-25 09:51
reproducible with Macos client as well , i have just tested it

**Comment by ckamm** [comment] 2019-01-28 09:19
Yes, simpler reproduction:
- have test.txt synced
- rename to other.txt.owncloud
test.txt will be deleted and other.txt.owncloud will be ignored.

The sync engine sees this as a deletion of test.txt and the creation of an erroneous placeholder file other.txt.owncloud.

What's the expected behavior? Renaming test.txt to other.txt on the remote and dehydrating other.txt.owncloud?

I expect a similar problem to occur if one renamed test.txt.owncloud to other.txt: test.txt.owncloud would be recreated and a silly other.txt would be uploaded.

**Comment by guruz** [comment] 2019-01-31 11:31
(Issue moved per @ckamm internal comment)

**Comment by ckamm** [comment] 2019-01-31 11:35
Reasons: This is complicated to fix. A fix would take a bit and probably not be in time for 2.5.3. Also, a fix in 2.5 would need to be redone against the new discovery code in 2.6, doubling the work. I think moving to 2.6 is acceptable since the feature is experimental.

**Comment by lazawan** [comment] 2019-05-10 12:24
@ckamm unfortunately it's still reproducible with  ownCloud-2.6.0.11958.11762-daily20190510.msi
and there is another thing : build number in the link is 11762 and when one shows General settings ---> build number is 11713

![Screenshot from 2019-05-10 14-16-46](https://user-images.githubusercontent.com/44814084/57527021-3e74a600-732f-11e9-9503-076115a47bc7.png)

**Comment by ckamm** [comment] 2019-05-16 06:13
@lazawan On Windows with cfapi based vfs .owncloud files should have no special behavior at all. What exactly are you seeing?

**Comment by lazawan** [comment] 2019-05-16 09:07
@ckamm i added extension .ownCloud to virtual file (a pdf file in virtual mode with Cloud sign ) and then this file was ignored from client and disappeared from server

**Comment by ckamm** [comment] 2019-05-20 10:42
Interesting, looks like .owncloud is in the ignore list? I'll try to reproduce.

**Comment by lazawan** [comment] 2019-05-20 11:50
@ckamm i have just checked the ignore list  ,   .ownCloud ist not in the list
and i could reproduce it again :'(

**Comment by ckamm** [comment] 2019-06-04 08:49
@lazawan I've not been able to reproduce the problem with ownCloud-2.6.0.12048.11850-daily20190530.msi. When I rename to .ownCloud in my wincfapi vfs folder the rename gets propagated to the server.

The behavior you describe would happen for ignored files. Could you double check your `C:\Users\$USER\AppData\Roaming\ownCloud\sync-exclude.lst`. Some in-between test versions when we started working on vfs added the .ownCloud extension there.

If it's not there: could you get me some logs?

**Comment by HanaGemela** [comment] 2019-07-19 14:38
1. have test.txt synced
2. rename to other.txt.owncloud
Actual result: This keeps only one file -> OK

1. have virtual file test.txt.owncloud 
2. rename to other.txt
Actual result: This keeps both copies -> Not OK

**Comment by ckamm** [comment] 2019-07-24 09:52
I can reproduce the issue in scenario 2 - which is odd because there's an explicit autotest for it and that passes.

**Comment by HanaGemela** [comment] 2019-08-05 12:33
Works as expected on macOS 10.14.6, client 2.6.0beta1 (build 12241)

**Closed by HanaGemela** 2019-08-05 12:33 UTC
Labels: ReadyToTest, Virtual Files, bug, p2-high
