### ISSUE TITLE
All files disappeared from sync client and web server over 2 hours

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#2579] opened 2014-12-04 14:47 UTC
### Actual behaviour
All files disappeared from sync client and web server over 2 hours.

### Step by step

User updates Windows Desktop Client to 1.7.0 from 1.6.4. 
Sync had been run **10:56-11:09** and finished. 

"delete all files?" dialog popup on **11:10** suddenly. User selected "Keep". 

**Log:**
````
11-28 11:10:21:013 0x796eb10 syncengine.cpp:628 <<#### Discovery end 
#################################################### 582 
11-28 11:10:21:014 0x796eb10 csync_statedb_load: sqlite3 version "3.8.6" 
11-28 11:10:21:015 0x796eb10 csync_statedb_load: Success 
11-28 11:10:21:015 0x796eb10 _csync_merge_algorithm_visitor:
INSTRUCTION_REMOVE dir: MyDataFiles 
11-28 11:10:21:016 0x796eb10 _csync_merge_algorithm_visitor:
INSTRUCTION_REMOVE file: file1.key/Data/mt5@2x-90.jpg 
| 
11-28 11:10:21:040 0x796eb10 syncengine.cpp:685 void 
Mirall::SyncEngine::slotDiscoveryJobFinished(int) All the files are going 
to be changed, asking the user 
````

"delete all files?" dialog popup again on **11:33**. 
Sync Activity Logs show files was already deleted.

**Log:**
````
11:33 2gb.under 
IIC Storage Deleted 
11:33 2gb.2 
IIC Storage Deleted 
11:33 2gb.1 
IIC Storage Deleted 
```

All files was disappeared on sync client and web server at that time. 

2 hours after, all files was downloaded again automatically on **13:34**. 
Date Last Modified is original but Date Created is **13:34**. 

**What happened on this client?**
- What's the trigger of the popup of "delete all files?"? 
- Why Sync Client was trying to delete all files? 
- In which case is this situation occur?

### Full Logs
S3-ownCloud/Shared/owncloud/support/github-issues/mirall/2579


@MorrisJobke @dragotin 

00002217

**Comment by cdamken** [comment] 2015-01-31 14:14
Any news?

**Comment by PVince81** [comment] 2015-02-06 11:07
I remember people having issues with NFS + backend object storage.
The problem was that whenever a file was written locally, it would take about 60s for the network to sync the file to the object storage. At the time NFS<->object store sync was done, the mtime of the file was changed to a future value. Having the mtime change automatically like this would disturb the file scanner, and it will believe that the file is new and might cause redownloads. Not sure if it could also cause files to disappear.

At least this is something that could be checked:
1) upload a big file "test.dat" with the sync client
2) as soon as the upload is done, close the sync client
3) observe the mtime of "test.dat" inside the data folder by doing a "stat test.dat" several times for 1-2 minutes and see whether the mtime changes automatically after a while (which would be the NFS<->object store sync).

If that's the case, then it might explain the issue.
If not, then it's probably another issue.

**Comment by cdamken** [comment] 2015-02-09 10:19
@PVince81 I see some similitude with https://github.com/owncloud/core/issues/13734 and I think is the same server. I will ask for the test.dat and I write you again.

**Comment by ogoffart** [comment] 2015-02-17 15:01
Most likely a problem on the server.

**Comment by cdamken** [comment] 2015-04-16 11:40
@ogoffart It's a possibility, can you see the new logs

@PVince81 It's only a server problem?

S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2579\new information.txt

**Comment by PVince81** [comment] 2015-04-16 12:18
What server version is this ?
Please always include the server version in bug reports.

**Comment by PVince81** [comment] 2015-04-16 12:22
Okay, so the "new information.txt" file seem to imply that the mtime of the file automatically changed inside the "data" folder after 10 seconds ? The mtime seems to have changed to 7 seconds later.
It is likely that this is caused by the NFS backend messing up with the mtime ?

Such change will make the server believe that the file has changed and could cause conflicts during the next sync. But I don't see how this could cause automatic file deletion.

**Comment by PVince81** [comment] 2015-04-16 12:25
About the "delete all files" popup, I sometimes see it appearing when there are only 1-2 files left on the server for that user (not completely empty), not sure if this is by design.

**Comment by PVince81** [comment] 2015-04-16 12:29
@michaelstingl 
>    Package and Internal storage use NFS mounted volume.
>   External storage use kind of NFS server. Its backend is object storage.

Ok, so this is not a real external storage. With external storage I meant anything configured using the "External Storage" ownCloud application (ex: SMB, SFTP, etc).

Where did they mount the NFS volume ? Did they mount it on "data" or on subdirs ?

If mounted on "data", ownCloud should detect when NFS is gone by checking for the ".ocdata" hidden file existence. If the file is gone, it will return 503 Service not available.
Since it didn't do that here, it is likely that they mounted NFS on subdirectories, maybe on a user-level ?

AFAIK there is no mechanism to detect if these folders / mount points become unavailable. What would happen is the server would see that the user's home ("data/someuser/") is suddenly empty.

If you can confirm that they mounted it that way, we could look into also adding a ".ocdata" file in these directories to accomodate for this use case.

**Comment by cdamken** [comment] 2015-04-17 08:32
@PVince81 
>What server version is this ?

{"installed":"true","version":"6.0.6.1","versionstring":"6.0.6","edition":"enterprise"}

The other information I will confirm

**Comment by cdamken** [comment] 2015-04-17 10:45
@PVince81 

The extra information is as follow:

We mount it as follows.
```
grids22:/mnt/wd_system/owncloud-enterprise  161061273600  235061248  160826212352   1% /var/www/html/owncloud-enterprise
woscld25:/wosshare                         1378727404544 3027083264 1375700321280   1% /oc_data

grids22:/mnt/wd_system/owncloud-enterprise on /var/www/html/owncloud-enterprise type nfs (rw,vers=3,hard,intr,rsize=1048576,wsize=1048576,addr=192.168.1.42)
woscld25:/wosshare on /oc_data type nfs (rw,vers=3,hard,intr,rsize=1048576,wsize=1048576,addr=192.168.1.40)
```
No, we are not using ownCloud tool.  We are not mounting it in subdirectory as above.  .ocdata file exist as follows.
```
[root@owncld01 oc_data]# pwd
/oc_data
[root@owncld01 oc_data]# ls -la .ocdata
-rw-r--r-- 1 apache apache 0  3?  2 14:05 2015 .ocdata
```

**Comment by PVince81** [comment] 2015-04-17 11:08
Ok, so they mounted NFS directly on the data dir. Then if NFS becomes unavailable, OC detects that the file ".ocdata" is missing due to the missing mount and will return 503 Service Unavailable. This is unlikely to be the cause of the deletion.

**Comment by cdamken** [comment] 2015-04-17 11:14
@PVince81 If it helps the same/similar behavior happens when uploading big files: https://github.com/owncloud/core/issues/13734

The file was uploaded and after that was immediately after it was finish then was downloaded to the client again

**Comment by PVince81** [comment] 2015-04-17 11:26
I think they should try and find out why the mtime of the file changes on disk.
Does NFS automatically changes the mtime after having "synced" to the network ? Maybe there's an option to disable this behavior ? I'm not familiar enough with NFS to know whether there is such option/behavior.

**Comment by PVince81** [comment] 2015-04-17 14:19
To confirm if it's a NFS issue: create a file manually inside the data dir and check its mtime, wait, check again.  If the mtime does change, it's a NFS issue, because OC was not involved.

**Comment by cdamken** [comment] 2015-04-17 14:43
@PVince81 I will come with an answer soon. Thanks for the extra explanation. In my opinion, it looks like an Object Storage behind the NFS.

**Comment by cdamken** [comment] 2015-04-24 14:13
I have just received update.  They said the issue like this (disappearance of files and reappear) was reproduced.
This time, it looks like mtime is not updated on the servers, but the files were disappeared on the servers.
Can you please take a look on the logs?

S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2579\New Info

The user was creating 2GB file every 10 mins in sync folder.  This was a test to see if the "re-download” issue by mtime change can occur with oC 6.0.6.

Aa far as we see the sync client log, files (file name indicates created time and file size) are uploaded to the servers, but after a while it disappeared on the server and local files were removed, then files 
re-appear on the servers, and the files were re-downloaded to the local.

There are no NFS related errors in /var/log/messages on ownCloud servers.
We also cannot find related errors in ownCkoud server log

**Comment by PVince81** [comment] 2015-04-24 14:20
@cdamken how about https://github.com/owncloud/client/issues/2579#issuecomment-93994921 ?
Because if NFS is acting like I said above, anything can happen. Would be good to first check that.

The mtime not updated on server reminds me of https://github.com/owncloud/core/issues/13498

**Comment by cdamken** [comment] 2015-04-28 08:45
@PVince81 

>Because if NFS is acting like I said above, anything can happen. Would be good to first check that.

I did a test to create a file manually on ownCloud data storage.  
I created a file on ownCloud server and monitored the file with ‘stat’ every 10 seconds.  Attached is the operation log.  
The behavior is a bit tricky, but MTIME did not change.  
Mili seconds of the files are not kept because of the limitation in the back-end storage.  
Also ATIME is set to the same value with MTIME.  

Anyway, it looks like MTIME (etag) had not changed in the case we sent in the previous email.  
The test are here:
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2579\New Info\operation.log

**Comment by PVince81** [comment] 2015-04-28 08:51
@cdamken ok thanks.

Now I also wonder whether the milliseconds limitation could affect ownCloud in some way. From what I remember there are two columns "mtime" and "storage_mtime". The "storage_mtime" is supposed to be the value that is actually on the storage and "mtime" the value that we show in ownCloud. So it should work, but might need to double check.

**Comment by PVince81** [comment] 2015-04-28 11:25
Just had a look and it looks like our "mtime" values are always in seconds, not milliseconds. So the millisecond being set to zero by the backend should be irrelevant.

**Comment by dragotin** [comment] 2015-04-30 12:36
Please see http://www.time-travellers.org/shane/papers/NFS_considered_harmful.html

Read "III. List of Concerns" paragraph a. and f. especially.

It might be worth to ask the user to mount the nfs share with the *sync* option, as described here: http://linux.die.net/man/5/nfs in chapter *Data And Metadata Coherence*

**Comment by cdamken** [comment] 2015-06-10 19:53
NFS sync option will impact the performance, and as the system has already been in production, we have not had a chance to try it.

Since we have not found an evidence that this is NFS issue, we are still suspecting this might be a ownCloud issue. Assuming there was a some kind of NFS issue, we believe instability on ownCloud behavior in such situation should be improved. 

Can you provide a comment from ownCloud against this?

**Comment by cdamken** [comment] 2015-06-24 10:50
@dragotin @PVince81
>Can you provide a comment from ownCloud against this?

**Comment by dragotin** [comment] 2015-06-24 15:10
@cdamken well, if there is no will to debug with us, what can we say? Maybe an update to the latest desktop client (1.8.3 just was released) helps, other than that I have no idea any more.

Suggesting to close this one.

**Comment by PVince81** [comment] 2015-06-24 15:16
Thing is, as long as we don't know what the exact problem is with NFS, there is nothing that can be done to make OC more robust on NFS

**Comment by PVince81** [comment] 2015-06-26 08:23
If the NFS mount is used exclusively for OC (no outside change), update detection can be disabling by setting this to 0: https://github.com/owncloud/core/blob/master/config/config.sample.php#L899

**Comment by bboule** [comment] 2015-07-24 11:31
@cdamken where do we stand here this seems stale?  is there anything more for us to do?

**Comment by cdamken** [comment] 2015-08-05 10:09
@bboule The customer has to upgrade, he is still in 6.0.6!, sofar I proposed to do https://github.com/owncloud/client/issues/2579#issuecomment-115572793

**Comment by cdamken** [comment] 2015-08-06 10:41
The customer refuse to upgrade because of the ZIP problem. I will reopen this issue after the customer upgrades.

**Closed by cdamken** 2015-08-06 10:41 UTC
Labels: blue-ticket, bug, Server Involved

**Comment by cdamken** [comment] 2015-08-07 10:55
Thanks @PVince81 for your extra explanation and examples in IRC!
