### ISSUE TITLE
Ubuntu (14.04) client 1.8.0 does not detect file changes

### ISSUE THREAD

**Issue by pmalek** [owncloud/client#3119] opened 2015-04-15 21:12 UTC
I have an owncloud server (8.0.2-8) on Ubuntu 14.10 and a client on Ubuntu 14.04 (1.8.0-2) from 

```
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/ /
deb-src http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/ /
```

Now I have found out that when I launch the client it will sync the files but when I do changes to files inside the ownlcloud dir it won't sync. I have to restart the client to pick up those changes and sync.

It will also detect and sync the changes when I stop and resume the syncing from settings menu.

I have launched the client with logging and there is no entry when I change a file inside owncloud dir.

Owncloud directory is located on a second drive mounted under `/mnt/sdb2` with following fstab:

```
/dev/sdb2 /mnt/sdb2 ext4 defaults,noatime,nosuid,nodev,nofail 0 0
```

but that shouldn't be a problem right?

**Comment by patrickschaffner** [comment] 2015-05-12 19:39
I can confirm the issue on Kubuntu 14.04 and 14.10 with client version 1.8.0. The ownCloud directory is located on the primary drive. The server runs version 7.0.4.2 hosted on a RaspberryPi.

**Comment by shadowwa** [comment] 2015-08-27 08:59
I also got the same problem on Kubuntu 15.04 with client version 2.0.0 from opensuse repository.
The server is a 8.1.1

**Comment by tflidd** [comment] 2015-09-13 14:52
I have seen the same on Ubuntu 14.04 with unity desktop, that changes to files were not recognized by the client (SuSE repo, version 2.0.1, server: 8.0.6). Pausing the account and restarting will sync all changes. I haven't checked the client logfiles so far...

**Comment by tflidd** [comment] 2015-09-13 21:58
I followed the server error message, and I found this patch: https://github.com/owncloud/core/pull/18124
It was not back-ported to OC 8.0. This is a one-line fix, so I just applied it to my view.php-file and now the client syncs again! A coincidence?

**Comment by tflidd** [comment] 2015-10-24 11:03
Just a short update, my problems two posts above (https://github.com/owncloud/client/issues/3119#issuecomment-139884784) have been solved in the mean time. Running 2.0.2 on the client and 8.0.8 on the server.

Does this problem still exist for you? @patrickschaffner @pmalek @shadowwa

**Comment by pmalek** [comment] 2015-10-24 14:21
I cannot confirm it now because I don't have that owncloud server anymore :/

**Comment by guruz** [comment] 2015-11-10 15:52
Linux: If you have a lot of sync dirs and things get only synced on client start, you might want to look into https://github.com/owncloud/client/issues/4107

**Comment by ckamm** [comment] 2015-12-09 13:55
I think it's fine to close this. @tflidd reported that his problems are solved, pmalek can't reproduce and the others didn't comment. Please reopen if you still notice your client not syncing even though there were local changes.

Note that this is independent of the server used.

**Closed by ckamm** 2015-12-09 13:55 UTC
Labels: bug
