### ISSUE TITLE
Shortcut file (extension .lnk) cannot be deleted from the client PC's

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/client#1938] opened 2014-07-05 14:05 UTC
### Description

In ownCloud Windows shortcut files get the extension .lnk.
At another synced PC the ownCloud client software reports the deletion of such a file, but the Windows Explorer still shows the shortcut file and Windows did not actually delete that file.
After a while the file will be synced back to the PC where the file was deleted.

Note:
This issue was also reported as https://github.com/owncloud/mirall/issues/1307 and was closed (!?).
On Feb 4, 2014 ogoffart commented:
"We were able to reproduce this problem when syncing with two windows computers.
Will be fixed in next release. Thanks for reporting!"
The issue was coupled to v1.5.1 while we are now at v1.6.1. 
So #1307 was closed, but not solved.

### Steps to reproduce

1. Have 2 PC's synced with r/w rights in ownCloud
2. Put a simple .exe file in the shared folder at PC1 and create a shortcut file.
3. Wait until these 2 files are synced to PC2 and delete them at PC1.

### Expected behaviour

Both files should be deleted and stay deleted at PC1 and PC2.

### Actual behaviour

At PC1 the deletion will be performed immediately.
At PC2 the deletion will be confirmed later and it can be seen reported in activity log.
However, the shortcut file will actually not be deleted.
After a while the non-deleted shortcut file will be copied back from PC2 to the cloud and to PC1.

## Server configuration

ownCloud version: 6.0.4 (stable)
encryption: yes

### Client configuration

Win XP, Win7 or Win8
IE11, Firefox, Google Chrome
ownCloud version: 1.6.1 or 1.5.4

### Temporary workaround

Most often it has not so much sense to copy shortcut files. The file paths will probably not be correct for the other connected PC's.
But as it is now, the system can be contaminated with non-removable shortcut files.
I now use the Ignored Files list to exclude shortcut .lnk files from being synced.
![setting lnk file exclusion](https://cloud.githubusercontent.com/assets/7522929/3874635/6ce2804e-2144-11e4-93e9-eaac119b280a.jpg)

As a quick solution for next ownCloud versions the exclusion of .lnk files could be a default setting with the option to change it and get the problem back as long as it is not fundamentally solved.

**Comment by maituikas** [comment] 2015-02-12 12:11
Hi, this .ink deletion problem is so annoying that I am going crazy. There is no way I can delete .ink files. They just keep coming back after few minutes. Using the latest (8.0) version and still no solution to this problem? I have tried everything, nothing helps...
Is there any change someone could suggest their solution or workaround besides "exclude list"?

**Comment by ckamm** [comment] 2015-02-12 12:29
I fixed something that's likely the same issue or closely related today: #2792

lnk files now sync correctly for me. Could you check whether you can still reproduce the problem with tomorrow's nightly build? (http://download.owncloud.com/desktop/daily/ use one >=20150213 - tomorrow)

**Comment by maituikas** [comment] 2015-02-12 13:46
Hi, thanks for the reply but unfortunately I am not in total control of the server environment where the 8.0 version is currently sitting so I cannot test this with your build... Any other suggestions?

**Comment by ckamm** [comment] 2015-02-12 13:51
@maituikas This is purely a client-side fix - it should work with the latest testing client and be fixed with the 1.8.0 release.

**Comment by maituikas** [comment] 2015-02-12 13:53
ooh, ok, sorry I did not notice that. I will test out this tomorrow, thanks!

**Comment by maituikas** [comment] 2015-02-13 10:03
This package is for linux?

**Comment by ckamm** [comment] 2015-02-13 10:05
@maituikas There are packages for windows (exe), linux (tar.bz2) and mac (pkg) there.

**Comment by maituikas** [comment] 2015-02-13 10:21
yeah sorry, did not pay too much attention to sorting order. Well, tried it out (uninstalled the previous version and installed ownCloud-1.8.0.4715-nightly20150213) and after removing the *.lnk from the exclude list unfortunately all the damn shortcuts were synced right back after few minutes so this did not help... :( Any other ideas?

**Comment by ckamm** [comment] 2015-02-13 10:50
@maituikas You're saying that after you used the new client, the lnk files were uploaded, you deleted them locally, and then they were downloaded again from the server?

**Comment by maituikas** [comment] 2015-02-13 10:57
The scenario was this: I uninstalled the previous version and installed the version you recommended. In the older version the exclusion list had *.lnk and the new version kept it the same so I removed the *.lnk from the exclusion list and voilaa. after 30 seconds the previously locally deleted shortcut files we donwloaded back.

**Comment by ckamm** [comment] 2015-02-13 11:14
@maituikas These files were probably still on the server. If you delete them now, does it stick?

**Comment by maituikas** [comment] 2015-02-13 13:09
Tried again. This time created a new shortucut from one pc which has regular oc installation and a minute later the same new shortcut was downloaded to the pc where your version of the oc is installed.Also tried to delete the existing shortcut from the new client and a minute later the shortcut was back again so no luck either way...

**Comment by maituikas** [comment] 2015-02-13 13:14
Although I don´t have full control over the hosting server then I still have possibility to get on hold of the files of the 8.0 installation incl. the logs if you should need these. I have root access to my part of the cluster that I rent from the hosting partner.

**Comment by ckamm** [comment] 2015-03-12 05:26
@maituikas In #2792 @nekoal suggests that htis bug is fixed with 1.8.0-beta2 and later. Can you confirm?

**Comment by nekoal** [comment] 2015-03-12 06:15
@maituikas For correct test you need update all clients which using this folder with shortcut and delete old unneed shortcuts over owncloud web interface on your server. If updated only one client of two clients new shortcut must be created then deleted on old client 'cause it test other side client. (on old client you delete it manually then new client delete it on sync).

**Comment by lmaestro** [comment] 2015-03-12 08:43
@maituikas Please reopen if you can reproduce the problem . Thx

**Comment by maituikas** [comment] 2015-03-12 12:42
Hi, thanks for the reply! As I am unable to update all the clients at once that use the fileserver then I tried the scenario that nekoal suggested: Updated one of the clients to 1.8.0 (downloaded ownCloud-1.8.0.4806beta2-setup.exe from oc official page), then created a new shortcut file in an old client which was then synced to the new client file source, then deleted the same file through the old client and the deletion was synced with the new client and the file disappeared..... for a minute and then was synced back to both of the clients :( Both clients - updated one v1.8.0 beta2 and the old v1.7.1  btw sit on a completely different locations/endpoints...

**Comment by maituikas** [comment] 2015-03-12 14:57
btw, how can I reopen the issue here...

**Comment by nekoal** [comment] 2015-03-12 15:39
@maituikas It look for me as third old client upload it back after delete on first and second clients. Suggested scenario work for only one old client. I think updating other clients help you.

**Comment by maituikas** [comment] 2015-03-23 16:02
I have no possibility to force update every client to the latest version so I have no way to test this within my organization. I assume I will find out in the coming months. Anybody else who can confirm the issue is fixed/not fixed?

**Comment by nekoal** [comment] 2015-03-24 03:51
May be @VincentvgNn  @RalfWW  @psxnight can confirm about multiple clients?

**Comment by VincentvgNn** [comment] 2015-03-24 11:51
@nekoal @ckamm 
I have now server 8.0.2 and client 1.8.0 installed.
Transferring *.link files is absolutely not useful for me. So normally I exclude *.lnk files as described at the beginning under "Temporary workaround". For this test I removed that exclusion.
I cannot reproduce the original problem, so it seems that the recently introduced fix in client 1.8.0 solves the problem.

@maituikas
Your clients will sooner or later receive the automatic updates. They should accept these updates.
A way to find the client that is uploading the same file again and again, is by temporary giving no r/w permission to some clients or groups.

**Comment by VincentvgNn** [comment] 2015-03-24 12:08
@maituikas 
I forgot the Activity app which is available on the webinterface.
There you can immediately see who is doing the re-upload.

**Comment by ckamm** [comment] 2015-03-25 08:58
As @VincentvgNn confirmed (thanks!) I'm closing this issue again.

**Closed by ckamm** 2015-03-25 08:58 UTC
Labels: bug
