### ISSUE TITLE
Store checksum in journal and verifiy upload for eml-files and others

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3235] opened 2015-05-13 12:47 UTC
Once #2542 is implement, the checksum should be stored in local sync journal. We could use it to verify if an upload is needed, or if just the files metadata (mtime specifically) has changed. This would solve trouble we have with eml files on windows, and this could be a nice first usage case.

Problems: If we detect that only the mtime has changed, we could propagate the new mtime to the server, using PROPPATCH (needs to be verified). But that will probably not change the ETag of the file and also not the ETags of the parent directories. If it would, a client seeing a changed ETag would not understand that only the mtime has changed, and not the content of the file. 

Note to self: If the server could do file checksums as well, it should also maintain directory checksums. The checksums only would change if the file **contents** or the **contents** of files within a directory changes. The ETag would just be an indication that **something** changed, either content or metadata. The client would need to consider the checksum to find that out.

**Comment by guruz** [comment] 2015-05-15 10:58
It would be good in a way to have it support multiple checksum algos at the same time.
For example Adler32 is only good for error or change detection but not for deduplication (e.g. for #230)

**Comment by MTRichards** [comment] 2015-06-19 18:34
Moving to 2.1 to keep 2.0 reasonable size.

**Comment by cdamken** [comment] 2015-06-26 07:53
@MorrisJobke 

00002839

**Comment by dragotin** [comment] 2015-06-26 08:12
@cdamken please elaborate. Pasting numbers and adding people is not enough.

**Comment by MorrisJobke** [comment] 2015-06-26 08:18
> @cdamken please elaborate. Pasting numbers and adding people is not enough.

I think this is just for reference. I was mentioned, because it became a blue ticket and the number is the backlink to their system ;)

**Comment by dragotin** [comment] 2015-06-26 08:23
@MorrisJobke yes, I know, but I would like to know the content of the blue-ticket as well.

**Comment by cdamken** [comment] 2015-06-29 12:20
@dragotin  The content of the ticket: *.EML files can't be deleted, even they are deleted in one client will reappear again and again, additionally generates a lot of network traffic.

**Comment by guruz** [comment] 2015-10-02 15:41
@dragotin @ogoffart @ckamm @moscicki  I was in general wondering if we should have a ```csync_journal``` table
```phash, mtime, checksumtype, checksum``` that is only lazily filled.
Else we risk taking a lot of time to checksum everything..

**Comment by ckamm** [comment] 2015-10-14 13:33
Storing the checksums in the DB will be part of #3735, this ticket can then be about using them to avoid unnecessary uploads.

**Comment by ckamm** [comment] 2015-11-11 15:40
This has a couple of steps
* Calculate checksums on upload even if the server doesn't support them, store them in the local db
* If the new checksum is the same as the old one, assume the content is the same.
  * This could either be done while reconciling the local and db trees or in the upload propagation job.
* Do a remote metadata update instead of a full upload.
  * Check that PROPPATCH works

**Comment by moscicki** [comment] 2015-11-11 16:01
I would guess you'd want md5 for that. The interesting bit is to see if it
is possible to marry it with adler32 in the server used to check the
transfers.

On Wed, Nov 11, 2015 at 4:40 PM, ckamm <notifications@github.com> wrote:

> This has a couple of steps
>
>    - Calculate checksums on upload even if the server doesn't support
>    them, store them in the local db
>    - If the new checksum is the same as the old one, assume the content
>    is the same.
>       - This could either be done while reconciling the local and db
>       trees or in the upload propagation job.
>    - Do a remote metadata update instead of a full upload.
>       - Check that PROPPATCH works
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/3235#issuecomment-155820427>.
>



-- 
---
Best regards,
Kuba

**Comment by ckamm** [comment] 2015-11-12 10:30
I've tested PROPPATCH for updating file mtimes on the server, but it currently makes the file etag change (owncloud/core#20474).

@dragotin and @ogoffart agree that in that case we are better off not telling the server about the new mtime, as it'd cause all other clients to re-download the unchanged file.

**Comment by ckamm** [comment] 2015-11-12 14:13
My wip branch for this is at https://github.com/ckamm/owncloud-client/commits/eml-checksum

**Comment by ckamm** [comment] 2015-11-23 10:44
Current pull request is #4180

**Comment by Dianafg76** [comment] 2015-11-25 10:07
@ckamm what are the steps to reproduce this issue?

**Comment by ckamm** [comment] 2015-11-25 10:44
@Dianafg76 

* Create a new `.eml` file locally, wait for it to upload
* Update the mtime of the file without changing the contents (`touch` command)
* Verify that the client does not re-upload the file. (log file or activity log)
* Verify that the client still uploads the file if the content changes.

**Comment by Dianafg76** [comment] 2015-11-27 10:24
I tested this issue and is working OK
Desktop v ownCloud-2.1.0.5655-nightly20151126-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed

**Closed by Dianafg76** 2015-11-27 10:24 UTC
Labels: approved by QA, Discussion, Feature, gold-ticket, resolves-blue-ticket

**Comment by mocolini** [comment] 2016-01-19 11:15
It seems that this bug affects owncloud-client yet.
If I don't remove ".eml" in "HKEY_LOCAL_MACHINESOFTWAREMicrosoftWindowsCurrentVersionPropertySystemPropertyHandlers" the client keep uploading (unchanged) *.eml files.
So, every time windows update itself (and so the ".eml" registry key is set back to default), hundred of .eml files (and MB) are re-uploaded to the server.

**Comment by guruz** [comment] 2016-01-19 11:28
@mocolini Are you saying the content of those .eml files does not change but they are still reuploaded?

**Comment by mocolini** [comment] 2016-01-19 11:41
@guruz exactly.
Today windows 10 upgrade itserlf and re-set the ".eml" key in the register (the one I've removed days ago), after that owncloud-client has begun to re-upload all the (unchanged) *.eml files.

**Comment by ogoffart** [comment] 2016-01-19 12:52
I think it needs to  be uploaded at least once after upgrading before the checksum are stored in the databse and are compared.

Does it re-upload several time the same file?

**Comment by mocolini** [comment] 2016-01-19 14:45
To be onest I don't know, 'cause I suddenly remove the ".eml" key .
So the upload is performed just one time to "populate" the db? Am 'I right?
And this happen for each windows PC, right?

**Comment by ogoffart** [comment] 2016-01-19 16:46
yes, previous version of the client did not store the checksum in the database. and we only store it after we complete an upload or a download.

**Comment by mocolini** [comment] 2016-01-19 16:49
Ok, perfect, I misunderstood the client behavior.
I'll check if the problem persist after complete upload/download, in that case I'll bother you again!
:-)

Cheers 
Michelino

**Comment by guruz** [comment] 2016-01-19 16:50
Sounds good :)
If you re-added the registry key, you can also try to remove it..

**Comment by mocolini** [comment] 2016-01-19 16:51
Sure, I'll let you know
