### ISSUE TITLE
406 Not Acceptable

### ISSUE THREAD

**Issue by querolus** [owncloud/client#6418] opened 2018-04-01 15:12 UTC
### Expected behaviour
Synchronize files properly.

### Actual behaviour
Some files are not synced using the Windows Desktop client. It seems related to filesize because small files sync perfectly. It all started to happen after the last upgrade. The client does not upload any big file (checked files over 8Mb) and does not download some big files (some files are downloaded and some not). Before upgrading to latest versions everything worked fine. It is not a matter of the server because files of any size can be uploded through the web uploader or through the Android App.

I tried to find help in the forum and found another guy with same problem. There was not any change in the Bluehost server and, as mentioned, everything started after the latest upgrades. Hope you can help.

### Steps to reproduce
1. Explained above
2. 
3. 

### Server configuration
Operating system: Windows 10.0 Pro

Web server: Shared Server (Bluehost)

Database:  MySQL 5.6

PHP version: 5.4

ownCloud version: 10.0.7.2

Storage backend (external storage): no

### Client configuration
Client version: 2.4.1

Operating system: Windows

OS language: Spanish

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
[owncloud_client_log.txt](https://github.com/owncloud/client/files/1866438/owncloud_client_log.txt)

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):
[owncloud.log](https://github.com/owncloud/client/files/1866426/owncloud.log)

**Comment by SamuAlfageme** [comment] 2018-04-02 12:29
Hey @querolus thanks for your report! Which version of the client were you using before the upgrade to 2.4.1? The only thing that rings a bell for me on your report is:

> Web server: Shared Server (Bluehost) 

We don't currently support shared hosters since they're quite painful to deal with. Your problem might be related to limited/shared access to a DB/permanent storage when using chunking. However, there's a way to force the client to use the old algorithm and endpoint. Can you give a try switching the  [`OWNCLOUD_CHUNKING_NG`](https://github.com/owncloud/client/blob/92027e869230d82de1bbbd0d486ebf14bfc471f7/src/libsync/owncloudpropagator.cpp#L274-L280) env.var. and restart the client? (i.e. launch the client with this variable set to 0 on cmd)

**Comment by SamuAlfageme** [comment] 2018-04-02 13:27
Possible duplicate of https://github.com/owncloud/client/issues/6171

**Comment by querolus** [comment] 2018-04-02 13:45
Solved

Changed the env.var as suggested and now it works as it used to... You are correct, it has been proposed before and solved but i did not see any 406 error when searching here.

Anyway, thank you again

**Comment by SamuAlfageme** [comment] 2018-04-03 09:48
@querolus awesome! Glad it worked out! I'm closing here as it was the shared hoster's fault.

**Closed by SamuAlfageme** 2018-04-03 09:48 UTC
Labels: Needs info, Server Involved

**Comment by ultradyran** [comment] 2019-02-02 07:36
> @querolus awesome! Glad it worked out! I'm closing here as it was the shared hoster's fault.



> Solved
> 
> Changed the env.var as suggested and now it works as it used to... You are correct, it has been proposed before and solved but i did not see any 406 error when searching here.
> 
> Anyway, thank you again

hi i am newbie here, how exactly do i change the env.var on my PC????

**Comment by michaelstingl** [comment] 2019-02-02 15:04
> hi i am newbie here, how exactly do i change the env.var on my PC????

This is an issue tracker. For support, please use https://central.owncloud.org/c/desktop
