### ISSUE TITLE
[Win] No `New ownCloud Update Ready` dialog if there is new update available

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11257] opened 2023-10-03 05:10 UTC
### Describe the bug

No update available dialog

### Steps to reproduce the issue

1. Setup [auto-updater](https://github.com/owncloud/client-updater-server)
2. Install client [one of daily build](https://download.owncloud.com/desktop/ownCloud/daily/5.0/win/)
3. Open client
4. Update notification :heavy_check_mark: 
5. Update in the Settings tab :heavy_check_mark: 
6. Update dialog :x: :question: (we expected to see dialog in the test case)

### Screenshots

![Screenshot from 2023-10-03 10-37-44](https://github.com/owncloud/client/assets/52366632/4f60e398-2785-4bc1-b21c-9c99b5f3bb08) | ![Screenshot from 2023-10-03 10-16-09](https://github.com/owncloud/client/assets/52366632/a3bd9d66-48b1-4aa1-91ad-7abb5274a96d)
--|--

### Expected behavior

Expected to see something like:

![Screenshot from 2023-10-03 10-53-18](https://github.com/owncloud/client/assets/52366632/189122e3-bbb5-4d4f-b7d0-8746605647f9) 

### Client version number

ownCloud 5.0.0.12163-daily20230920 4b266c
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.22621
QPA: windows

### Installation path (Windows only)

Windows 11

**Comment by TheOneRing** [comment] 2023-10-04 08:27
There never was one for windows but we have it on the roadmap for 6

**Comment by saw-jan** [comment] 2023-10-04 08:46
So should we close this ticket?

**Comment by TheOneRing** [comment] 2023-10-04 08:58
Duplicate of https://github.com/owncloud/client/issues/10980#issuecomment-1731214534

**Closed by TheOneRing** 2023-10-04 08:58 UTC
Labels: bug
