### ISSUE TITLE
Missing detail information in tray icon hover info on Windows

### ISSUE THREAD

**Issue by sfadschm** [owncloud/client#8505] opened 2021-03-21 15:34 UTC
Not sure if this is a bug or intended difference between different OS, but I noticed that apparently on Linux systems, the hover info of the OwnCloud tray icon is much more detailed compared to the Windows client.

For example on Linux, see https://github.com/owncloud/client/issues/7365#issuecomment-749520839.
Example on Windows:
![Unbenannt](https://user-images.githubusercontent.com/40514119/111910675-aaafad00-8a62-11eb-9c7f-55d2c8a86b52.png)

This is on Windows with 2 Accounts and several sync folders setup in the client.

### Expected behaviour
The Windows client tray icon should also provide status information about the different folder's sync status like the Linux client does apparently.

### Actual behaviour
It does not seem to do that 😆 
On Windows, only a single line message about the overall syncing status is displayed (during sync as well as after all syncs have finished).

### Steps to reproduce
1. Install client on Windows.
2. Add multiple accounts and sync folders.
3. Sync and hover the mouse over the client tray icon.

### Server configuration
Not relevant here.

### Client configuration
Client version: 2.7.6

Operating system: Windows 10

OS language: German

**Comment by sfadschm** [comment] 2021-04-22 07:30
Remove stale.

**Comment by fmoc** [comment] 2021-04-22 08:04
I quickly had a look at the relevant code file, `owncloudgui.cpp`. The main reason the tooltip is different on Windows appears to be a limitation of that platform: the tooltip length may not exceed 128 characters. Therefore, one can't fit the same amount of details into the tooltip as on other platforms like Linux.

I'll quickly check whether we can work around this in some way. But if that should not be possible, there is nothing we can do about it.

**Comment by fmoc** [comment] 2021-04-22 08:20
Original issue leading to shorter tooltips on Windows: https://github.com/owncloud/client/issues/3412

According to https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataa, the limit of 128 characters has been in place ever since Windows 2000. I can't imagine it was increased in the last 6 years without updating the Win32 API docs.

There are four "solutions" to this issue, as far as I can see:

1. leave everything as it is
2. use a short string on all platforms to keep everything in sync (implementing the Win32 API limit everywhere, as it's the least common denominator)
3. calculate a long string like on the non-Win platforms, check if it fits the tooltip, use it if it does, and use the current fallback if it doesn't (to avoid truncation)
4. use some other form of notification, e.g., balloon popups on click, making things even less consistent on all platforms

I personally tend to 1 or 2. 3 doesn't seem like a good idea, as it introduces non-deterministic behavior (at least from the average user's point of view).

**Comment by TheOneRing** [comment] 2021-04-22 08:31
Thanks for looking into this, I'll close the issue as we can't do anything right now.
The short tooltip is a feature and not a bug, lets see what a future version of Windows brings.

**Comment by fmoc** [comment] 2021-04-22 08:32
Another reference: https://doc.qt.io/qt-5/qsystemtrayicon.html#toolTip-prop

> On some systems, the tooltip's length is limited. The tooltip will be truncated if necessary.

**Closed by TheOneRing** 2021-04-22 08:31 UTC

**Comment by sfadschm** [comment] 2021-04-22 09:05
Alright, thanks for elaborating!
I didn't think Windows also enforces its length limits on tooltips...
Guess we just keep it the current way then 😄
