### ISSUE TITLE
crash on remove account

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9367] opened 2022-01-17 03:49 UTC
We have seen this error message before, and haven't seen it in a while. However, we need to investigate why it is failing. Since no changes has been merged, and it failed in only one of the nightly build during the weekend, **it clearly is a flaky test.** 

The error details filtered by our log parser is as follows: 
```json
{
        "Error Details": "LookupError: Lost connection to AUT",
        "Feature": "remove account connection",
        "Feature File": "tst_removeAccountConnection",
        "Scenario": "remove an account connection",
        "Test Step": "Then an account should be displayed with the displayname Alice Hansen and host %local_server_hostname%"
}
```

Related drone run (failing): https://drone.owncloud.com/owncloud/client/10363/3/14

**Comment by individual-it** [comment] 2022-01-17 08:54
from the logs:
`02:23:39:023 Info: AUT process '/drone/src/build-GUI-tests/bin/owncloud OWNCLOUD_CORE_DUMP=1 -s --logfile - --logdebug --logflush --confdir /tmp/bdd-tests-owncloud-client/' (PID 5279) finished with exit status -1: Received signal number 11.`

**Comment by TheOneRing** [comment] 2022-01-17 10:35
Yay a crash, shouldn't we get a backtrace?

**Comment by Talank** [comment] 2022-01-19 04:11
Yup. It was a crash. AUT coredump is still not printed in the log because of https://github.com/owncloud/client/issues/9259. I will look into the fixing apport problem so that this unavailability of AUT crash log does not happen again.
![Screenshot from 2022-01-19 09-52-11](https://user-images.githubusercontent.com/27364813/150062282-ba7967e7-c5b1-473f-9d74-61b81b6de52b.png)

**Comment by individual-it** [comment] 2022-01-20 03:33
happened again today https://drone.owncloud.com/owncloud/client/10411/3/14

**Comment by Talank** [comment] 2022-02-01 04:05
Failed again today https://drone.owncloud.com/owncloud/client/10514/3/14

**Comment by individual-it** [comment] 2022-02-01 04:17
@Talank Any idea what happens here and what we could do?

**Comment by Talank** [comment] 2022-02-01 04:24
Well, we do have the squish backtrace in the log. But clearly it is an AUT crash causing the connection lost error. We can start investigating from the log that we already have, but I highly doubt that there will be any other outcomes from that investigation. The backtracking works perfectly in local test runs so we can try to reproduce it locally, which might give us some additional idea (if we can reproduce it).

**Comment by Talank** [comment] 2022-02-04 17:41
@TheOneRing I reproduced the issue locally. Here is thefull  backtrace in this file 
[backtrace.txt](https://github.com/owncloud/client/files/8005114/backtrace.txt)

**Comment by TheOneRing** [comment] 2022-02-21 08:11
The crash seems to occur in line 166.
https://github.com/owncloud/client/blob/105d39c19a986164b9c0de6697babd6c3ce7cb8b/src/gui/activitywidget.cpp#L164-L168

**Comment by individual-it** [comment] 2022-02-21 08:48
@TheOneRing I took off the QA-team label. Please reach out if you need more help here

**Comment by Talank** [comment] 2022-03-01 07:33
I reproduced the crash by running the automated test `remove an account connection` several times (about 20 times). The steps in the scenario is as follows:
```
    - Create an user "Alice"
    - Create an user "Brian"
    - set up client for user "Alice" with default settings
    - add user "Brian" to client, also with default settings
    - remove the connection for user "Brian"
    - Then "Brain" should be removed and "Alice" should not be affected
```

**Comment by TheOneRing** [comment] 2022-03-01 08:53
A change was merged and the issue is hopefully fixed.

**Comment by Talank** [comment] 2022-03-02 04:38
I ran the test (more than 20 times) that reproduced the crash. And I am not being able to reproduce it anymore in 2.10 branch. So I agree that the issue is hopefully fixed.

**Comment by TheOneRing** [comment] 2022-03-02 07:31
Thx

**Comment by Talank** [comment] 2022-03-19 03:32
I noticed the crash again in https://github.com/owncloud/client/pull/9518#issuecomment-1072118187

**Comment by fmoc** [comment] 2022-03-21 11:22
I just tried to reproduce the issue and capture it with a debugger following the steps listed in https://github.com/owncloud/client/issues/9367#issuecomment-1055112285. In over 40 repetitions, I couldn't produce a crash, thus I cannot tell where the crash occurs. How should we proceed with this issue?

**Comment by Talank** [comment] 2022-03-21 11:42
Earlier, in https://github.com/owncloud/client/issues/9367#issuecomment-1030208120 I reproduced it by running the automated test (that captured the crash) more than 20 times continuously.

**Comment by jnweiger** [comment] 2022-03-22 11:48
I have a 100% reproducable crash with remove accounts: #9533

**Comment by TheOneRing** [comment] 2022-03-22 11:51
> Earlier, in [#9367 (comment)](https://github.com/owncloud/client/issues/9367#issuecomment-1030208120) I reproduced it by running the automated test (that captured the crash) more than 20 times continuously.

That was remove account.
Now we are talking about removing a broken sync folder.

**Comment by individual-it** [comment] 2022-05-16 04:07
happened again on 14.05 
Stacktrace: https://cache.owncloud.com/public/owncloud/client/11763/guiReportUpload/stacktrace.log

**Comment by TheOneRing** [comment] 2022-05-18 14:44
Please retest on master, we don't expect another 2.10 release

**Comment by TheOneRing** [comment] 2022-06-29 10:42
fixed on master

**Closed by TheOneRing** 2022-06-29 10:42 UTC
Labels: p2-high
