### ISSUE TITLE
owncloudcmd.exe (and owncloud.exe) terminate unexpectedly:  'std::bad_alloc'

### ISSUE THREAD

**Issue by TerryHewitt** [owncloud/client#4867] opened 2016-05-19 14:39 UTC
### Expected behaviour
Tell us what should happen

Owncloud client should work in the background, syncing files!

### Actual behaviour
Tell us what happens instead

This seems to have started happenning after upgradeing to 2.2.0, though I think its worked for a while without issue.

Owncloud.exe AND owncloudcmd.exe  both terminate with an error report.

### Steps to reproduce

Owncloud.exe terminates unexpectedly.
In trying to find the source of the problem, I've re-structured directories, and in an attempt to locate the bug run 

owncloudcmd.exe -u Photography -p "Password" --trust --silent "I:\My Pictures" "https://owncloud.wthassociates.com/remote.php/webdav/My Pictures"

The log is attached with the  final line showing the errior 'std::bad_alloc"

My Pictures has 692 GB in 43,801 files in 703 folders.

In this --silent version it still takes 20 minutes to get to the fall over point.

I need some help to provide the correct information for debugging
Best wishes

Terry

### Server configuration
Operating system: Liunx 14.04

Web server:  Apache 2

Database: MySQL

PHP version: PHP 5.5.9-1ubuntu4.16 

ownCloud version: 9.0.2.2

Storage backend: ZFS

### Client configuration
Client version: 2.2.0

Operating system: Windwos 10

OS language: English

Installation path of client: c:\program files (x86)\owncloud

### Logs

void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "SPS Archive" INSTRUCTION_IGNORE 6 "Ignored because of the "choose what to sync" blacklist"
OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "i:\My Pictures/SPS Competitions" Retrieved inode  30003 (previous item inode:  30003 )
"INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);" -7722514477477280350 16 "SPS Competitions" 30003 "1450562285" "2" "5675d3428adf4" "00856898ocyuenq2nfhj" "RDNVCK" 0 0 "" "" 0
void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "SPS Competitions" INSTRUCTION_CONFLICT 4 ""
Upload chunk 0 of 2 transferid(remote)= 198330967
!!! OCC::PUTFileJob created for "https://owncloud.wthassociates.com/" + "My Pictures/AAA-RJH/2011/2011-11-12/2011-November-12-untitled_074.dng-chunking-198330967-2-0" ""
Upload chunk 0 of 2 transferid(remote)= 3800310362

---load of similar lines for different files----------

Upload chunk 0 of 2 transferid(remote)= 3308604
!!! OCC::PUTFileJob created for "https://owncloud.wthassociates.com/" + "My Pictures/AAA-RJH/2011/kaiser Tethered/2011-November-22-Kaiser-Tethered_017.dng-chunking-3308604-2-0" ""
Upload chunk 0 of 2 transferid(remote)= 4092992549
!!! OCC::PUTFileJob created for "https://owncloud.wthassociates.com/" + "My Pictures/AAA-RJH/2011/kaiser Tethered/2011-November-22-Kaiser-Tethered_027.dng-chunking-4092992549-2-0" ""
Upload chunk 0 of 2 transferid(remote)= 4098515061
!!! OCC::PUTFileJob created for "https://owncloud.wthassociates.com/" + "My Pictures/AAA-RJH/2011/kaiser Tethered/2011-November-22-Kaiser-Tethered_028.dng-chunking-4098515061-2-0" ""
Upload chunk 0 of 2 transferid(remote)= 3259111548
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
                                                                              
Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment] 2016-05-19 15:41
@ogoffart @dragotin @jturcotte  I think this might be what @jospoortvliet had seen and what we have on https://github.com/owncloud/client/issues/4611 ?

@TerryHewitt Could you also Task Manager or similar to check the memory usage? https://github.com/owncloud/client/issues/4611#issuecomment-220077157

**Comment by TerryHewitt** [comment] 2016-05-19 17:00
I too see a big jump in memory used in the last few seconds before it crashes. Something around 2GB jump shown in Task Manager.

 

Best wishes

 

Terry

 

Professor W T Hewitt

WTH Associates Ltd

 

Telephone: +44 7905 759 003

 

Company registration number:7336226

HMRC VAT Registration number: 998 8457 23

 

Company Registered Address

St George's House  | 215 - 219 Chester Road | Manchester | M15 4JE

**Comment by jturcotte** [comment] 2016-05-20 22:20
Closing as a duplicate of #4611.

**Closed by jturcotte** 2016-05-20 22:20 UTC
Labels: bug, sev2-high
