### ISSUE TITLE
Windows 8 high contrast is unreadable

### ISSUE THREAD

**Issue by stonewareslord** [owncloud/client#2654] opened 2014-12-30 03:24 UTC
### Actual behavior
When using the high contrast themes in Windows, the ownCloud sync client is unreadable: 
![high contrast](https://cloud.githubusercontent.com/assets/7482347/5575364/83987d9e-8fa7-11e4-9a2d-78e6793be180.png)
And when switching back to Aero Lite, the Storage Usage bar doesn't change:
![aero lite](https://cloud.githubusercontent.com/assets/7482347/5575365/870d00b2-8fa7-11e4-89e0-d7a8e334724f.png)

### Steps to reproduce
1. Switch to high contrast mode

### Client configuration
Operating system:
Windows 8
OS language:
English
Installation path of client:
Default

**Comment by lmaestro** [comment] 2015-01-08 16:45
I can't reproduce it, when I use high contrast mode I see this: 
![contrast-mode-1 7](https://cloud.githubusercontent.com/assets/4689430/5666160/ebd90802-975d-11e4-8c37-53aecbbcc743.png)
Can you test it in the latest build? http://download.owncloud.com/desktop/daily/
If it is still happening please reopen it. Thx

**Comment by stonewareslord** [comment] 2015-01-08 19:24
I will test it in a few hours, but did you try selecting the folder?

**Comment by stonewareslord** [comment] 2015-01-08 20:20
Ok. I created another folder. The wallpaper folder looks like yours and isn't selected. The one below it is selected (I left clicked it). 
![capture](https://cloud.githubusercontent.com/assets/7482347/5669892/616534ac-9730-11e4-922d-427fb6b674f0.PNG)
I'm using 1.8.0-nightly 20150108 (build 4536)

**Comment by jturcotte** [comment] 2015-08-06 15:10
This seems to have magically been fixed by the multiaccount UI update.

**Comment by phil-davis** [comment] 2015-08-06 15:31
I tried theme "High Contrast #1" on Windows 10. I can read everything and see the storage usage bar - good.
The only missing component I noticed is that the file download progress bar is all black. There is no visual of the download progress (the text of what is downloading is seen and works).
I guess this is a "black-on-black" rendering somewhere caused by whatever is mapping the normal green-on-white to black-on-black.

**Comment by jturcotte** [comment] 2015-08-06 18:11
Oh man, you're thorough! :)
I'm trying to find out why and I can't see anything wrong. We don't give any specific color to Qt for this widget and it also works well with "-style windowsxp" and I can't see anything that we could set better in QStyleOptionProgressBarV2. Could this be a bug in the Qt windowsvista style?

If I use the High Contrast White theme I can see that the Vista theme renders the progress as grey, while the XP one renders it properly with dark purple.

But, if I run the the progressdialog example, both style work well, so we must be doing something different than QProgressBar.

@ogoffart Can you think of anything?

**Comment by jturcotte** [comment] 2015-08-06 18:18
Ah, if I remove the line "pBarOpt.palette = palette;" it works well.

**Comment by phil-davis** [comment] 2015-08-07 11:16
Let me know if/when there is anything in a build and I can easily test.

**Comment by jturcotte** [comment] 2015-08-07 11:26
Yes not yet, I'll push the fix once we released beta1 just to possibly get in the way of higher priority stuff.

**Comment by guruz** [comment] 2015-08-10 10:46
ownCloud-2.0.0.5381-nightly20150810-setup.exe	should have this.

**Comment by phil-davis** [comment] 2015-08-10 11:22
I tried 2.0.0.5381 on Windows 10 with High Contract Theme 1. Yes the progress bar is displayed and changes during upload/download - good.
On the top section of the UI the words cannot be seen - names of the accounts, "Activity", "General", "Network".
Personally I have no need for high contrast theme, but maybe somebody cares?
![highcontrast](https://cloud.githubusercontent.com/assets/1535615/9170420/52bb3fb4-3f82-11e5-9fa1-4dc92b829985.png)

**Comment by phil-davis** [comment] 2015-08-11 08:52
Just documenting here that there is no change in behaviour with build 2.0.0.5384
Need to wait for the next build to see the effect of the changes made to try and also address #3582

**Comment by guruz** [comment] 2015-08-11 10:44
New nightly for Windows http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5388-nightly20150811-setup.exe

**Comment by phil-davis** [comment] 2015-08-11 11:14
Windows ownClient 2.0.0.5388 still has the same behaviour. The currently highlighted icon is now blue, OK.The text of the non-highlighted icons is not visible. I guess it is white-on-white - like trying to find a polar bear in a snowstorm.
![highcontrast1](https://cloud.githubusercontent.com/assets/1535615/9196347/37e31e46-404a-11e5-97a1-b17526321537.png)
How much time is this worth?

**Comment by danimo** [comment] 2015-08-11 11:16
@phil-davis It works now, but it doesn't change when the color theme is getting changed (i.e. you need to close and reopen). I am still not too happy because the icons are dark, and therefore almost not visible in high-contrast mode.

**Comment by phil-davis** [comment] 2015-08-11 11:37
You are right - after "Quit ownCloud" and start it again then I can see the text. But the icons for each are not visible (black-on-black). I guess these themes with nasty mixes of colours are a pain. I certainly switch straight back after a 30 second test.
![highcontrast2](https://cloud.githubusercontent.com/assets/1535615/9196657/2ec98572-404d-11e5-810a-6b6cbb169c25.png)
Just as an aside, when I switch the themes back and forth my Firefox stop working properly - it gives up being able to resolve DNS! I exit completely, saving my tabs, and restart and it is fine. So ownCloud is not the only app that does weird stuff when already running and the theme changes.

**Comment by danimo** [comment] 2015-08-11 16:27
![image](https://cloud.githubusercontent.com/assets/1315934/9203282/81f2b918-4056-11e5-8a98-373c1782d755.png)

This is the best I can do for 2.0 (includes switching on the fly as the theme changes!). I think that's ok for now.

**Closed** 2015-08-11 16:58 UTC
Labels: bug, Platform Specific, sev3-medium

**Comment by phil-davis** [comment] 2015-08-11 17:13
ownCloud client 2.0.0.5390 works well for me. I tried High Contrast 1, Black and White. And it all switched back and forth on-the-fly without me ever needing to do a full restart of the app.
