### ISSUE TITLE
Share of a file in a directory creates the directory and the file followed by share of directory creates second copy of directory

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/client#2768] opened 2015-02-02 22:01 UTC
(I thought I already filed this but can't seem to find it)

### Steps to reproduce

1. Install owncloud server on box 1 (eitehr CentOS or ubuntu; I don't believe the OS matters - these are the two I tested with)
2. Install owncloud client on box 2 (ubuntu)
3. Create three users on the server
4. From the client, user 1 shares a directory with user 2 - user 2 syncs and validates the directory is locally present
5. user 2 shares the directory with user 3 (I don't think this step matters but it's part of my test, so I'm adding it here) - user 3 syncs and validates the directory is locally present
6. user 1 unshares the directory
7. user 2 syncs and validates the directory is not locally present

### Expected behaviour

At step 7, the directory and its contents should not be locally present

### Actual behaviour

At step 7, the directory is locally present, though the contents are not

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (testing)

### Client Configuration

owncloudcmd version 1.7.1

**Comment by ogoffart** [comment] 2015-02-03 08:05
Is the directory gone in the server web interface?
If not, then it is likely to be a server problem.

Is the directory empty or is there still possibly hidden files.  Some ignored files may prevent the removal of the directory, this is on purpose.

Is the directory open with some program which would prevent the deletion. in that case it should be removed on the next sync after it is closed.

Otherwise i would need to logs to know why the directory is not removed.

**Comment by jnfrmarks** [comment] 2015-02-03 11:53
Yes, the file is gone from the server web interface.  I will double check on the hidden files.  This is on linux so there shouldn't be anything holding the directory open.  Where can I find the client log files and are there any debugging switches I should enable to get more info?

**Comment by ogoffart** [comment] 2015-02-04 12:36
you can start the client with  `--logfile /tmp/owncloudlog.txt`
Then the log will be saved in that file

**Comment by ogoffart** [comment] 2015-02-05 14:45
(I could not reproduce the problem)

**Comment by jnfrmarks** [comment] 2015-02-05 15:33
I should have info on this by the end of the week

**Comment by lmaestro** [comment] 2015-03-02 10:21
@jnfrmarks  Can you verify it?

**Comment by jnfrmarks** [comment] 2015-03-04 19:04
This seems intermittent - sometimes I see it and other times I don't.  My script that isolates the behavior isn't showing it soooo, for now, I'll close this and then reopen if  I can get a better reproducer.

**Comment by jnfrmarks** [comment] 2015-03-04 21:43
ok - I finally have this figured out.

This is what I'm doing:

1: user 1 creates a directory and some files in the directory.
2: user 1 shares the directory with user 2
3: user 2 share a file in the directory with user 3
4: user 3 syncs, the directory and the file are created locally
5: user 2 shares the directory with user 3
6: user 3 syncs, the directory is created a second time locally

So, when I was unsharing, the directory created in step 6 is the one being deleted.

Now comes the question:  should the directory be created a second time in step 6?

**Comment by dragotin** [comment] 2015-03-11 16:36
I think this should rather go to the core repo, to the sharing experts. Does not seem to be a client problem.

**Comment by jnfrmarks** [comment] 2015-03-11 19:23
I'm not sure this is a server problem.  

I see different behavior when I do all the sharing via the webUI.  Specifically, at step 3, the file shows up in user3's root folder; the folder containing the shared file is not created when I run the test via the webUI.

**Comment by dragotin** [comment] 2015-03-16 14:12
tried on stable8, and it works: when user3 syncs in step 4, I get only the shared file. Not the directory. Once user 2 has shared the dir, I get the directory and the file in root.

**Comment by jnfrmarks** [comment] 2015-03-30 19:06
@dragotin 

I am still seeing this.  Can we set up some time to screen share and go over what I'm seeing?

**Comment by ogoffart** [comment] 2015-04-06 14:42
I tried to reproduce all the steps with owncloud 8.0.2 and it works as expected: In step3, the file appears in the root directory both in the web ui and in the client that is sync'ed.

Since the client does not know much about sharing, it must be something comming from the server anyway.
If you can provide the log  (running with --logwindow) we could verify that.

**Comment by ogoffart** [comment] 2015-04-08 14:56
I am closing this issue because it works for me and I believe that if there is a problem, it must be a server problem.

**Comment by jnfrmarks** [comment] 2015-04-08 15:24
I still see this (please @mention me when you need info from me - I missed your request)

**Comment by ogoffart** [comment] 2015-04-09 07:52
@jnfrmarks  and you are saying the file is on a folder in the client, but not in the web interface?

**Comment by ogoffart** [comment] 2015-04-09 07:53
@jnfrmarks  Can you please provide the log (running owncloud with --logfile and --logwindow)

**Comment by jnfrmarks** [comment] 2015-04-09 12:00
@ogoffart 

Will do.

**Comment by jnfrmarks** [comment] 2015-04-09 14:31
I believe that this will end up as user error but before I close it, here is more accurate info:

1: user 1 creates a directory "localDir" and some files in the directory.
2: user 1 shares the directory with user 2
2a: user3 creates a local directory "localDir"
3: user 2 shares a file in the directory with user 3
4: user 3 syncs, and the file is created locally
5: user 2 shares the directory with user 3
6: user 3 syncs, the directory"localDir" is created a second time locally
7: user 1 unshsare the directory

So, the question now becomes: what is the expected behavior when a user has a local directory that is the same name as a remote share directory?  Are they considered different directories or the same directory?

**Comment by jnfrmarks** [comment] 2015-04-09 14:44
Conversed via IRC; closing as user error/works as designed.

The client syncs as directed by the server.  In this case there's a conflict (two directories with the same name) so the client creates a second directory.

**Comment by dragotin** [comment] 2015-04-09 14:45
They are considered the same. How can the client create a second dir?

**Comment by jnfrmarks** [comment] 2015-04-09 14:48
Let me try to pare down the test case more.  I'll update with my findings.  Re-opening since I'm still working on it.

**Comment by jnfrmarks** [comment] 2015-04-09 15:05
I adjusted the test case some to get to the heart of the issue:

1.  user 1 creates a local directory "localDir" and copies in some files
2.  user 2 creates an empty local directory "localDir"
3.  Both users sync to the server
4.  user 1 shares "localDir" with user2
5.  user 2 syncs.  There are now two localDirs: "localDir" and "localDir (2)"

Is this the expected behavior?

**Closed** 2015-04-09 15:10 UTC
Labels: bug, Needs info, Server Involved
