### ISSUE TITLE
Renaming folder to same name but different case causes folder to be deleted from server when others try to sync

### ISSUE THREAD

**Issue by Havenard** [owncloud/client#2706] opened 2015-01-14 22:04 UTC
I had a folder named "Clientes" inside a shared folder and it was renamed to "CLIENTES", when other users I share with tried to sync, the folder was deleted for everyone.

Aparently the other users' clients were trying to sync still using the old folder name.

Now I have peers that insist the folder "Clientes" or "CLIENTES" both still exist [not mutually in the same client of course] even though none is in the server, and if I try and create them again it is soon deleted by someone trying to sync.

I couldn't isolate any data/owncloud.log recording the event, but I'm having shitloads of this:

    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:21:22+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:21:27+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:21:30+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:21:40+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:21:43+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:21:52+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:21:54+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:22:08+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:22:08+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:22:16+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:22:18+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:22:31+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:22:32+01:00"}
    {"app":"hook","message":"error while running hook (OCA\\Search_Lucene\\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)':\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1","level":3,"time":"2015-01-07T20:22:33+01:00"}

**Comment by guruz** [comment] 2015-01-22 17:55
@Havenard Which version of client and server are you using?

**Comment by ogoffart** [comment] 2015-01-26 17:29
Can you be specific about what exactly need to be done, on which platform, and what are the version of the clients and the server? Which database is in use on the server?
Was there a client that was older than 1.6 involved?

Do you see error in the activity tab saying that there are a name clash?
Or was there 500 Internal Server Error?
Is it also gone in the web interface?

I tried to reproduce the problem, but everything worked fine for me doing some renames and syncing with windows and linux.

**Comment by ogoffart** [comment] 2015-02-05 16:24
I could not reproduce the problem.

**Comment by lmaestro** [comment] 2015-02-16 08:21
I can't reproduce it so i close this issue. 
@Havenard Can you try to reproduce it beta1 https://owncloud.org/install/#testing? If it is still happening please reopen it.

**Closed by lmaestro** 2015-02-16 08:21 UTC
Labels: bug, gold-ticket, Needs info, ReadyToTest
