### ISSUE TITLE
[Ubuntu 16.04] Packaging "Bug":  Signature by key F9EA4996747310AE79474F44977C43A8BA684223 uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by sukramblak** [owncloud/client#4964] opened 2016-06-14 15:28 UTC
### Expected behaviour
Installation with gpg verify 

### Actual behaviour
Installation only possible without gpg verification. Reason: ubuntu enforces SHA265 since march 2016. 

WARNING: The following packages cannot be authenticated!
  libqt5keychain1 owncloud-client-l10n owncloud-client libowncloudsync0

### Steps to reproduce
1. Add OpenSuse repo to ubuntu 
2. Add Release.gpg with apt-key
3. apt-get update (result W: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/Release.gpg: Signature by key F9EA4996747310AE79474F44977C43A8BA684223 uses weak digest algorithm (SHA1)
4. apt-get install owncloud-client (result: 

### Server configuration
Operating system:
ubuntu 16.04

Web server: 
client packaging problem 

Database:
client packaging problem 

PHP version:
client packaging problem 

ownCloud version:
client packaging problem 

Storage backend:

### Client configuration
Client version:
2.2.1-13.1

Operating system:
ubuntu 16.04 

OS language:
german 

Installation path of client:
/usr/bin

### Logs

client packaging problem -> no owncloud logs

### Solution 
enable gpg SHA256 digest for repo keys.

**Comment by RealRancor** [comment] 2016-06-17 21:39
@sukramblak @guruz  Duplicate of https://github.com/owncloud/client/issues/4596

**Closed** 2016-06-21 10:09 UTC
Labels: packaging
