### ISSUE TITLE
2.5.4: Data loss on renaming folder (which was partially synced)

### ISSUE THREAD

**Issue by labkode** [owncloud/client#7773] opened 2020-02-26 10:16 UTC
One of our users has experienced data loss, see details below:

User system:
Fedora 31 on a Thinkpad E495 AMD rhyzen 5
Cernbox: 2.5.4 (build 2625)

User renamed the local folder `Experiment` to `4 -Experiment` using the Dolphin file browser.
After performing the rename, the sync client issued a DELETE operation that failed server side with 504. Afterwards, the client issued a MOVE to actually rename the folder, however the folder server side was gone due to previous DELETE, therefore the MOVE failed with 409. Client then issues a `MKCOL` to create the target folder, however, this folder was only partially synced (folders where unchecked) so the folder contents were not complete in server side and previous server-side data which was not synced to the local client was erased.

These are the relevant log lines from the server:

```
13:39:14 "DELETE /cernbox/desktop/remote.php/webdav/eos/project/s/scion/Experiment HTTP/1.1" 504 182
13:39:14 method=DELETE path=//eos/project/s/scion/Experiment
13:42:10 "PROPFIND /cernbox/desktop/remote.php/webdav/eos/project/s/scion/Experiment HTTP/1.1" 207 6356
13:42:10 "PROPFIND /cernbox/desktop/remote.php/webdav/eos/project/s/scion/Experiment/Measurements HTTP/1.1" 207 9703
13:42:10 "PROPFIND /cernbox/desktop/remote.php/webdav/eos/project/s/scion/Experiment/ScriptOutputFiles HTTP/1.1" 207 9905
13:42:10 "PROPFIND /cernbox/desktop/remote.php/webdav/eos/project/s/scion/Experiment/ScriptOutputFiles/Magnetization HTTP/1.1" 207 32625
13:45:52 method=MOVE src="//eos/project/s/scion/Experiment", dest="//eos/project/s/scion/4 - Experiment"
13:45:52 "MOVE /cernbox/desktop/remote.php/webdav/eos/project/s/scion/Experiment HTTP/1.1" 409 3846
13:55:54 method=MKCOL path=//eos/project/s/scion/4 - Experiment
13:55:54 method=MKCOL path=//eos/project/s/scion/4 - Experiment/Measurements
13:55:54 method=MKCOL path=//eos/project/s/scion/4 - Experiment/Measurements/Magnetization
13:55:54 method=MKCOL path=//eos/project/s/scion/4 - Experiment/Measurements/Magnetization/Nb-Ti
13:55:54 "MKCOL /cernbox/desktop/remote.php/webdav/eos/project/s/scion/4%20-%20Experiment HTTP/1.1" 201 0
13:55:54 "MKCOL /cernbox/desktop/remote.php/webdav/eos/project/s/scion/4%20-%20Experiment/Measurements HTTP/1.1" 201 0
```

These are the relevant log lines from the sync client:

```
12:40:44||Experiment|INST_REMOVE|Up|1533711000|150cf:1579216400.531|0|86223|2|Server replied "504 Gateway Timeout" to "DELETE https://example.cern.ch/cernbox/desktop/remote.php/webdav/eos/project/s/scion/Experiment"|504|0|0|5788e5cb-9612-41b6-9dd8-6e1826d8c815|
12:45:52||Experiment -> 4 - Experiment|INST_RENAME|Up|1579009463|150cf:1581511325.710|0|86223|2|Server replied "409 Conflict" to "MOVE https://example.cern.ch/cernbox/desktop/remote.php/webdav/eos/project/s/scion/Experiment"|409|0|0|3b1450e6-4a0f-4e80-9755-e115451db59a|
12:55:54||4 - Experiment|INST_NEW|Up|1579009463||4096|3865760|4||201|0|0|98654805-1bd9-4f45-9e67-e284d3f0b6df|
```

**Comment by voroyam** [comment] 2020-02-26 10:49
@labkode 

Can you reproduce it with the new client?

**Comment by labkode** [comment] 2020-02-26 11:12
> Can you reproduce it with the new client?

We got the new client just yesterday and we are testing it before giving it to our users. You should be able to use the CERNBox sync client to test.


> can yo show us this folder in the client tree structure? I am interested in the partially checked part of your description.

After the incident the user cleaned the setup of the sync client to avoid any further damage to the data so the quick answer is no.

From the user:

```
I re-named folders, whose content was partially unchecked in the synchronize menu.
After the re-naming, the online version contains now only the stuff that I had synchronized.
```

Such folder contained more than 1TB of data, hence the reason the user only synchronized part of the three.

To help you in the debugging, we should understand the following conditions a part from the fact that the client triggered the DELETE/MOVE/MKCOL sequence:

* What is the behaviour of the client when a DELETE fails with 504 and if behaviour is affected by the contents of the HTTP response body.
* What is the behaviour of the client when a MOVE fails with 409 and if behaviour is affected by the contents of the HTTP response body.

**Comment by voroyam** [comment] 2020-02-26 11:44
> We got the new client just yesterday and we are testing it before giving it to our users. You should be able to use the CERNBox sync client to test.

since you are testing it - can you reproduce it? :)

**Comment by labkode** [comment] 2020-02-26 11:52
@voroyam we have done tests on a Centos7 machine with the old and with the new client and we have not reproduced the issue.

The user renamed many folders and of those this bad behaviour happened only in one folder.

**Comment by voroyam** [comment] 2020-02-26 12:04
Okay, can you ask the user for a screen shot of the sync client tree? It's okay if it looks different now, we can reconstruct and test it when we see it.

So the error is not reproducible with the new client.

**Comment by labkode** [comment] 2020-02-26 12:09
@voroyam as I said the user cleaned his local configuration after experiencing the problem, is not possible to obtain the state of the tree.

I will ask the user if it still has the original desktop configuration (the one stored under /home/user/.local/share/data/CERNBox), however we'll use the official support channel, not here.

**Comment by jnweiger** [comment] 2020-02-26 12:26
The sequence DELETE MOVE MKCOL is odd. The client normally decides if it can do either MOVE or if it has to do DELETE MKCOL. There is also a fallback case: MOVE (fails) DELETE MKCOL.

@labkode do we know that this is sequence was initiated from one client? 
On a first glance, it might be multiple clients involved? ...

**Comment by labkode** [comment] 2020-02-26 12:30
@jnweiger that is the first assumption I had but I can confirm this sequence is coming from one single client as you can see from the .owncloudsync.log file in the description of the issue. I also had the impression that it could be related to the Dolphin file browser but after testing we could not reproduce it so my feeling is that is caused by some exotic condition on the logic of the sync client.

Could it be that the operations of the fallback scenario have been mixed in time: 

instead of MOVE (fails) DELETE MKCOL 
the client actually did DELETE MOVE MKCOL

**Comment by jnweiger** [comment] 2020-02-26 13:36
When you say Dolphin: do you have Dolphin connected via webdav? That could also explain the DELETE before MOVE.

**Comment by ogoffart** [comment] 2020-02-26 13:58
Here is one possibility that would explain what we see.

1. The user moves the `Experiment` folder outside of the outcloud folder entierly (or to a path which is ignred) =>  The client issue a DELETE as it does not see the new folder.
2. The user moves back the folder to `4 -Experiment`  At this point, the client issue a `MOVE`
3. The files are now removed on the server (it just took time) so the client does not see them on the server and that's why the client issue a `MKCOL`

> this folder was only partially synced (folders where unchecked) so the folder contents were not complete in server side and previous server-side data which was not synced to the local client was erased.

Normally, when a folder is partially checked, it means files are on the server, but not on the client. Not the other way around.
And the client should not delete files which are not sync'ed, in any case.
In fact, the files should still be in the moved folder, and even uploaded to the server.

**Comment by jnweiger** [comment] 2020-02-27 10:25
>     2\. The user moves back the folder to `4 -Experiment`  At this point, the client issue a `MOVE`

Shouldn't that issue MKCOL or PUT?

**Comment by labkode** [comment] 2020-02-28 14:45
@ogoffart @jnweiger I agree with @jnweiger, in the case the folder has been deleted the client should not try to MOVE already deleted folders.

**Comment by ogoffart** [comment] 2020-03-05 09:13
> > 2\. The user moves back the folder to `4 -Experiment`  At this point, the client issue a `MOVE`
>
> Shouldn't that issue MKCOL or PUT? 

Since the folder was not deleted after all (since we got an error), it is still in the local DB as being on the server.  So if the user restores it with another name, if the folder still has the same inode, it will be detected as a MOVE. Anyway, I don't think that's a problem at all. As the MOVE will fail, the client will then recover on the next sync.

 >  in the case the folder has been deleted  the client should not try to MOVE already deleted folders.

That assumes that the client knows that the folder was deleted (on the server). In this case, the client did not know as the server would still advertise them when the client did a PROPFIND.
The client only do a MOVE if the files are still on the server (as told by the PROPFIND) 
If the files are actually removed (on the server) between the PROPFIND and the MOVE, then the server will reply with a 409 conflict error (this is the case here) and the client will recover from there.

**Comment by TheOneRing** [comment] 2021-03-02 13:02
Hmm could the cause of this issue been https://github.com/owncloud/client/blob/master/changelog/unreleased/7838

**Comment by dragotin** [comment] 2022-04-27 11:39
I'll close this as it is probably not longer relevant.

**Closed by dragotin** 2022-04-27 11:39 UTC
