### ISSUE TITLE
"Delete" button misleading if conenction error

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/client#3792] opened 2015-09-09 15:23 UTC
Today I had a connection error which is shown to the left of the "Delete" button. I thought that the delete button will actually delete/vanishes this notification, but instead it deletes the account.

This button should be properly labeled or be put in the correct context

cc @jancborchardt

**Comment by dragotin** [comment] 2015-09-09 15:40
duplicate of #3793

**Closed by dragotin** 2015-09-09 15:40 UTC
