### ISSUE TITLE
[Xubuntu 16.04.1] [2.3] Systray icon disappear briefly when a file or icon changes state, tray menu opens and dissapears instantly

### ISSUE THREAD

**Issue by babs** [owncloud/client#5164] opened 2016-09-09 16:17 UTC
### Expected behaviour
Systray icon to stay steady and be right clickable to open owncloud's menu

### Actual behaviour (on the packaged version)
Systray icon disappear briefly when it changes state making the whole systray to flickers.
Icon menu opens as expected.

### Actual behaviour (on the master commit 524220d0907713408298a36df18bd04635ce5563)
Systray icon stay steady as expected but unable to has access to right click menu.
Whe the icon is clicked, the menu show up an instant and disappear instantaneously.

### Steps to reproduce
1. install the client on a 64bit xunbutu
2. update or touch a file in a monitored directory 

### Client configuration
Client version: ownCloud version 2.2.3 Using Qt 5.5.1

Operating system: Xubuntu 16.04.1 LTS amd64

Window manager: Xfce 4.12

OS language: fr_FR.UTF-8

Installation path of client: packaged version or run from source dir

**Comment by ckamm** [comment] 2016-09-12 13:29
@babs Thanks for the nice report. The difference on master is probably due to 88cd5421bfcfafa9f4aaa46cff6166dfce1f516d, which intended to work around flickering and unreasonable resource usage by updating the tray menu only on demand. Apparently that somehow breaks with your setup :/

**Comment by ckamm** [comment] 2016-09-12 13:30
A fix to this would also address or change #5158

**Comment by babs** [comment] 2016-09-12 14:53
Ok, tag me if you want me to pull/compile/check anything on my setup.

**Comment by ckamm** [comment] 2016-09-13 08:29
@babs I assume you do see the string "Enabled QDBusPlatformMenu workaround" in your log output? (--logfile)

**Comment by babs** [comment] 2016-09-13 09:09
@ckamm yes, on both versions.

**Comment by ckamm** [comment] 2016-09-13 11:32
@babs Are you up to compiling the client from source to test something?

**Comment by babs** [comment] 2016-09-13 12:09
@ckamm Of course, give me a branch or commit :)

**Comment by ckamm** [comment] 2016-09-13 12:16
@babs at owncloudgui.cpp:477 in the master branch, comment out `_qdbusmenuWorkaround = true;` - does it work then?

Can you still click the tray menu to show the settings dialog? Does it still update when you add an account?

**Comment by babs** [comment] 2016-09-13 12:35
Menu is available and doesn't even close when icon change.
No flicker

**Comment by guruz** [comment] 2016-09-13 12:48
@nazar-pc has the same symptom with the nightlies..
https://github.com/owncloud/client/issues/4985#issuecomment-246185323
And also memory growing? (because of menu changing constantly?)

**Comment by ckamm** [comment] 2016-09-13 12:52
@babs I'm glad to hear it. The problem is that we added this workaround because there were bugs in Qt 5.5.0 regarding the tray menu. And it is unclear whether we can disable it for 5.5.1 generally or whether there are other circumstances that make you not have the original problems.

I tentatively assume that 5.5.1 doesn't need the workaround.

**Comment by babs** [comment] 2016-09-13 13:45
@ckamm , I can quickly bootstrap a VM with xubuntu 14.04 on it to check the issue
I was affected by the previous bug when I was running 14.04, if you are referring to systray icon that don't shows up after a previous update. I updated my distro last week :)

**Comment by babs** [comment] 2016-09-13 15:19
@ckamm in b7809ded23fdba6aa50b6d834b5bd5fc16865eea it fails:
 - xubuntu 14.04: no menu and flickers
 - xubuntu 16.04: no menu and flickers

**Comment by guruz** [comment] 2016-09-13 16:15
@babs Hmm have you seen the PR in https://github.com/owncloud/client/pull/5179 ?
Maybe some combination of the env variables there..

**Comment by babs** [comment] 2016-09-13 17:07
@guruz none of the env combination make it working on 16.04 
It flickers and no menu. The only way to have the menu and the not flickering behavior is to use OWNCLOUD_MINIMAL_TRAY_MENU.

That said the previous build (master + owncloudgui.cpp:477) worked at all level (menu, sync icon and no flickers :/)

**Comment by ckamm** [comment] 2016-09-14 13:51
@babs You are saying you applied 150e7f6bcb5e77f15edd4da3902fc120b0bbfcf9 and that didn't help?

**Comment by babs** [comment] 2016-09-14 14:07
@ckamm Oops, on witch branch is it ?

**Comment by ckamm** [comment] 2016-09-14 14:18
@babs The pull request is based on https://github.com/ckamm/owncloud-client/tree/trayagain

**Comment by babs** [comment] 2016-09-14 14:58
@ckamm works like a charm on both Xubuntu 16.04 and Xubuntu 14.04 even without having to set any env :)
Clickable, no flickers on both :)

**Comment by ckamm** [comment] 2016-09-14 15:04
@babs Thanks for testing, I'm glad to hear it!

**Comment by babs** [comment] 2016-09-15 10:37
No problem, the VM is still there.
Just tag me and I'll test :)

**Comment by ckamm** [comment] 2016-09-23 08:45
@babs It was now merged to master. Would you test once more?

**Comment by babs** [comment] 2016-09-23 09:08
@ckamm tested and approved :)
Works on both 14.04 and 16.04. No flickers and menu is available.
Thanks

**Comment by ckamm** [comment] 2016-09-23 09:58
@babs Thanks for testing, I'm glad that worked!

**Closed** 2016-09-23 09:58 UTC
Labels: bug, ReadyToTest, sev2-high

**Comment by armaccloud** [comment] 2016-10-19 20:35
Hi,
What does this mean? Will be fixed in a new release of owncloud-client from the ubuntu repositories?
I am on Ubuntu 16.10 and this issue us eating away my memory.
Thanks.
