### ISSUE TITLE
Linux: Missing window decoration, icon and title with wayland

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11163] opened 2023-08-31 07:48 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Modal windows don't have black framing on Ubuntu 22.04

Ubuntu 22.04
Client 5.0.0 daily 20230830

### Steps to reproduce the issue

e.g. Click the Quit button

### Screenshots

<img width="868" alt="Screenshot 2023-08-30 at 21 48 48" src="https://github.com/owncloud/client/assets/49001702/5e0f51e6-e889-49e2-b447-8a1dd7689f56">

### Expected behavior

Modal window is nicely framed 

### Actual behavior

No framing, looking bad

**Comment by HanaGemela** [comment] 2023-09-07 11:19
Works when starting the client like this:

`QT_QPA_PLATFORM=xcb owncloud`

That fixes also 
https://github.com/owncloud/client/issues/11164
https://github.com/owncloud/client/issues/11165

**Comment by TheOneRing** [comment] 2023-09-07 16:20
The experience in a KDE Plasma session(wayland) looks much better.

**Comment by TheOneRing** [comment] 2023-09-07 16:27
Duplicate of: https://github.com/owncloud/client/issues/8328

**Closed by TheOneRing** 2023-09-07 16:27 UTC
Labels: bug, p3-medium, Linux, QA:team
