### ISSUE TITLE
[Overlays][OSX] Overlays don't appear on folders and documents whose names contain umlaut characters

### ISSUE THREAD

**Issue by r-r-liu** [owncloud/client#4884] opened 2016-05-21 14:33 UTC
### Expected behaviour
Overlays should appear on all folders and documents.

### Actual behaviour
On folders and documents whose names contain an umlaut character (ä ö ü), but perhaps other foreign language characters as well, no overlay appears.

### Steps to reproduce
1. Create a folder with name Einbürgerung.
2. In the desktop client it should appear with an overlay.
3. It does not.

### Server configuration -- Sorry, I'm a customer of Wyffy and don't know the details.

Web server: 

Database:

PHP version:

ownCloud version:  ownCloud V. 8.2

Storage backend:

### Client configuration
Client version: 2.2.0 (build 3358)

Operating system:  OS X 10.10.5

OS language:  English

Installation path of client: /Applications

### Logs -- Sorry, I've tried getting the log and evidently don't know how.

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by danimo** [comment] 2016-05-27 09:55
I cannot reproduce this here. Where were those files created? On the same machine? Through the web interface? Non-Mac machine?

I suspect this happens due to unicode normalization issues. If nothing helps please get in touch with your provider and ask them to ensure that their ownCloud setup has unicode normalization enabled. If they do, this issue should not be visible.

**Comment by r-r-liu** [comment] 2016-05-27 11:00
Daniel,

See replies inline.

Regards,
Richard

Richard R. Liu
Hebelstr. 136
CH-4056 Basel
Switzerland

Tel.:  +41 61 321 66 00
Mobil: +41 79 708 67 66
Email:  richard.liu@pueo-owl.ch

> On 27 May 2016, at 11:55 , Daniel Molkentin <notifications@github.com> wrote:
> 
> I cannot reproduce this here. Where were those files created? On the same machine? Through the web interface? Non-Mac machine?

The files were created on the MacBook Pro on which the ownCloud desktop client is running.  I am actually syncing a .sparsebundle that is mounted when I login to my account on the MacBook Pro.  Once it is mounted, I see the names of files and folders including umlauts.

> 
> I suspect this happens due to unicode normalization issues. If nothing helps please get in touch with your provider and ask them to ensure that their ownCloud setup has unicode normalization enabled. If they do, this issue should not be visible.

Thanks for the tip, I will contact Wyffy.  Question in this regard:  When I connect to my ownCloud through the web interface the names appear normal and I can share the affected items as expected.  Would that indicate anything about whether or not Wyffy has enabled unicode normalization?  I’ve never seen the issue before and tend to believe that it was not present.  I understand that overlays support under OS X has changed over the last few versions.

**Comment by Marvo2011** [comment] 2016-05-27 11:54
Same Issue on OS X 10.11.2
Real MacBook Pro 8,2

Files in a folder with ä,ü,ö have no overlay too.

**Comment by r-r-liu** [comment] 2016-05-27 11:58
Yes, I can in the meantime confirm that upgrading from OS X 10.10.5 to 10.11.5 doesn't solve the problem ... but then I didn't expect that it would.

**Comment by Marvo2011** [comment] 2016-05-27 12:05
On Client Version 2.1.1 is no overlay issue.

**Comment by danimo** [comment] 2016-05-27 12:07
@jturcotte any idea about what changes coul have changed this?

@Marvo2011 Are you sure you didn't upgrade the server as well?

**Comment by Marvo2011** [comment] 2016-05-27 12:10
OwnCloud Server Verison: 9.0.2.2

I'm sure there is no Server update.
On Client 2.1.1 is no issue.
With Client >= 2.2.0 there is this issue.

**Comment by danimo** [comment] 2016-05-27 12:12
How were the files create?

**Comment by Marvo2011** [comment] 2016-05-27 12:13
Simply right click new Folder in the OS X Finder.

**Comment by jturcotte** [comment] 2016-05-27 12:19
It could be a `QString::normalize` call missing somewhere. I tried with some accents during development but some codepaths might have slipped.

**Comment by Marvo2011** [comment] 2016-05-27 12:20
There is a second issue... With Client >= 2.2.0 folders with an ö,ü,ä can't shared with right click "Via ownCloud teilen".

**Comment by r-r-liu** [comment] 2016-05-27 12:28
Yes, I mentioned that in a report to the Desktop Client forum but not here.  In the web interface there is no problem.  Folders and files with umlauts in their names are there and can be shared.

**Comment by Marvo2011** [comment] 2016-05-27 12:31
`05-27 14:29:51:238 0x7fae3a904210 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString &, QIODevice *) "/Users/medeler/ownCloud/Dokumente"
05-27 14:29:51:238 0x7fae3a904210 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/medeler/ownCloud/Dokumente"
05-27 14:29:51:244 0x7fae3a904210 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString &, QIODevice *) "/Users/myMacUser/ownCloud/ö"
05-27 14:29:51:245 0x7fae3a904210 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:NOP:/Users/myMacUser/ownCloud/ö"`

Here is a Log with a folder name ö.

**Comment by mcastroSG** [comment] 2016-05-27 12:57
@danimo I´m able to reproduce it

Shell integration seems to fail as [@Marvo2011](https://github.com/owncloud/client/issues/4884#issuecomment-222131141) says on refresh.

**Steps Executed**

1.- Create a file or folder on finder that contains  ö,ü,ä 
2.- On finder window navigate to other location and then press back.

**Results**

Shell integration is not working for that file or folder, no overlay o share with owncloud option, @Marvo2011  there is no two issues, just one  shell extension does not work.

For any file or folder: its the same , in case it includes any ö the same log:

`"STATUS:NOP:/Users/XXXX/versiones/öa.pkg"`

ClientOS : OSX El capitán 10.11.4
Client version: Version 2.2.1-nightly20160527 (build 3400).

Server OS: Ubuntu
Server Version: 9.1.0 Alpha

**Comment by Marvo2011** [comment] 2016-05-27 13:34
Is the issue generated by [this commit](https://github.com/owncloud/client/commit/727e73d6401737a6b6814dab49095d7a722cc821) ?

**Comment by jturcotte** [comment] 2016-05-27 13:44
@Marvo2011 @danimo Yes it could be the removed `normalized` call from https://github.com/owncloud/client/commit/727e73d6401737a6b6814dab49095d7a722cc821

I was assuming that both the OS X filesystem watcher and the socket API would take care of normalizing it first, but I might have been wrong.

**Comment by danimo** [comment] 2016-05-27 14:07
@jturcotte thanks, I've reverted this part of the patch with a2b238e2e52c0006554e64973c84b5e01d7ae8b0 in the `normalize_name_in_filestatus` branch. I'll build a nightly from that and merge it on success.

**Comment by danimo** [comment] 2016-05-27 14:22
@Marvo2011 Please try https://download.owncloud.com/desktop/daily/ownCloud-2.2.1.3401-nightly20160527.pkg (and only this one!) and report back. It has been built from aforementioned branch.

**Comment by Marvo2011** [comment] 2016-05-27 14:29
Yes it's works! Thanks 
![bildschirmfoto 2016-05-27 um 16 27 43](https://cloud.githubusercontent.com/assets/6094055/15610925/2bcd98ee-2428-11e6-8f49-83d168cd670c.png)

**Comment by r-r-liu** [comment] 2016-05-27 14:32
Excellent work, thanks to all!  Should I wait for an official release?

**Comment by danimo** [comment] 2016-05-27 14:33
Up to you. We will have an official release of 2.2.1 during next week.

**Comment by r-r-liu** [comment] 2016-05-27 14:47
Couldn't wait :)  I can also confirm that it works.  Again, thanks to all.

**Comment by danimo** [comment] 2016-05-27 16:08
Merged. The next nightly build will have it.

**Comment by mcastroSG** [comment] 2016-05-30 06:29
It´s working fine with Version 2.2.1-nightly20160527 (build 3401) and Version 2.2.1-nightly20160530 (build 3407) 😄

**Closed by mcastroSG** 2016-05-30 06:29 UTC

**Comment by rperezb** [comment] 2016-05-30 10:21
@mcastroSG just curious, is this working fine on Windows and Linux?

**Comment by mcastroSG** [comment] 2016-05-30 10:23
@rperezb tested on OSX , on linux or windows the error does not appear 😄

**Comment by danimo** [comment] 2016-05-30 10:23
@rperezb Neither of those have the Unicode normalization problem.
