### ISSUE TITLE
Google Drive files without an extension not synced 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7837] opened 2020-04-03 09:04 UTC
Server 10.4.1 RC1
Client 2.6.1 (build 13096)
macOS 10.15.3

Steps to recreate: 
1) Sync a Google Drive file without an extension to the client (get in touch I can provide the test environment) 

Expected result: File has been synced
Actual result: File has not been synced. No mention of the file in the logs

Found when testing https://github.com/owncloud/core/issues/37044

**Comment by michaelstingl** [comment] 2020-04-03 09:12
@HanaGemela please provide server log, client log and please capture the http requests and responses from the time of the incident. (`mitmproxy` / `mitmdump` etc)

**Comment by HanaGemela** [comment] 2020-04-03 15:38
Logs for `file500` shared

**Comment by michaelstingl** [comment] 2020-04-06 05:57
@HanaGemela this is definitely not a client issues. Desktop sync client always `PROPFIND` the root directory for changed `etag`. Only if `etag` changes, the desktop client also `PROPFIND` to subdirectories. All my changes in the Google web UI made it to the ownCloud web UI, but the `etag`  was never propagated up to the root directory, so the desktop client can't do anything. Only initial discovery worked fine.

**Comment by micbar** [comment] 2020-04-06 06:33
@HanaGemela @michaelstingl Are you using external storage?

In this case, this behaviour is expected-

**Comment by jvillafanez** [comment] 2020-04-06 11:43
There might be something wrong with the GDrive ownCloud's app, but the problem isn't related with the ticket.

Somehow, adding a file inside a folder directly in GDrive does NOT update the mtime of the folder, which makes ownCloud to not change the etag and propagate upwards. As far as I know, this happens with any file, not just files without extensions.
Note that this happens in GDrive, and it isn't ownCloud's fault, at least directly.

Regarding the specific problem with the files without extensions, the file is synced as soon as the client detects the change. This happens when the mtime of the folder is changed (which, as said, it doesn't happen when a file is added directly)

**Comment by jvillafanez** [comment] 2020-04-06 13:23
It seems core doesn't see the need to change the etag if the mtime of the folder isn't changed.

I think what's happening is:
1. Add new file in "gdrive/test2/file.txt"
2. GDrive ownCloud's connector detects the change and reports it (once the user enters in the "gdrive/test2" folder; this is "normal" behaviour)
3. core rescan the folder "gdrive/test2" folder, but due to the mtime of the folder didn't change, the etag of the folder doesn't change neither.
4. the change is propagated upwards. Etag of the "gdrive" folder is changed. (I haven't checked the etag of the root folder, but it's expected it changes too)
5. desktop client tracks the etag changes from the root folder. However, the problem that the desktop client has is that "gdrive/test2" folder's etag didn't change, so the track is lost there and doesn't update the folder.

The result is that, even though the web UI updates the the contents correctly (the folder was rescanned), the desktop client doesn't update the folder because the etag of the "gdrive/test2" folder didn't change.

**Comment by micbar** [comment] 2020-04-20 09:07
@HanaGemela Fix is merged

**Closed** 2020-09-16 12:29 UTC
Labels: Server Involved
