### ISSUE TITLE
No overlay icons with 1.7.0 on Win7 32bit if drive letter not CAPITALIZED

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2591] opened 2014-12-08 06:38 UTC
In two machine with similar configurations. I do not see any oc overlay icons on either of them. (Tortoise overlay works fine.) Are there any requirements to be fulfilled?

Windows 7 Prof, SP1, 32bit, German/English

For testing I just installed http://download.owncloud.com/desktop/daily/ownCloud-1.7.0.4317-nightly20141205-setup.exe (before I used the official 1.7.0 version - no difference).
During installation "Status icons for Windows Explorer" was checked. There were no errors.

I do have these registry entries (and others):

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers\  OCOK]
@="{0960F092-F328-48A3-B746-276B1E3C3722}"
```

Note: The subkeys of ShellIconOverlayIdentifiers begin with two spaces.

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F092-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F092-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files\\ownCloud\\shellext\\OCOverlays_x86.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
```

The DLL does exist. I rebooted the machine.

In the log there is no mentioning of "overlay" or "icons".

Any ideas? Any more input needed?

**Comment by lmaestro** [comment] 2015-02-05 09:13
@LukeOwncloud Can you test using the latest build http://download.owncloud.com/desktop/daily/??
(Make sure to have backups.. it is a development version)

**Comment by lmaestro** [comment] 2015-02-11 16:49
I am not able to reproduce so I close this issue, if anyone is able to reproduce please reopen it, thx.

**Closed by lmaestro** 2015-02-11 16:49 UTC
Labels: bug, Needs info, ReadyToTest
