### ISSUE TITLE
Clients stops working after Windows Update (0xc0000142)

### ISSUE THREAD

**Issue by Lenny-Hai** [owncloud/client#4413] opened 2016-01-31 09:43 UTC
Trying to open owncloud on a Windows 10 Insider Preview (14251.1000.amd64fre.rs1_release.160124-1059) breaks with an Error  "Die Anwedung konnte nicht korrekt gestartet werden (0xc0000142)". I tried the Client Version 2.1.0.5683 and 2.1.1.5799rc1.

**Comment by RealRancor** [comment] 2016-01-31 10:05
Might be a duplicate of https://github.com/owncloud/client/issues/4405

**Closed** 2016-01-31 11:52 UTC
