### ISSUE TITLE
Ubuntu 20.10 client not available

### ISSUE THREAD

**Issue by akemper** [owncloud/client#8195] opened 2020-10-23 21:49 UTC
Neither can find a repo for the latest Ubuntu version nor the 20.04 version can be used, due to library conflicts.

Please help
Andreas

**Comment by michaelstingl** [comment] 2020-10-24 07:57
2.7.0-rc2 will be released the next few days with support for Ubuntu 20.10

**Comment by akemper** [comment] 2020-10-24 08:55
Thanks a lot for the quick response and much appreciated! Obviously I had been a bit too fast with the 20.10 upgrade ;-)

**Comment by Collin8000** [comment] 2020-10-29 01:33
Hey can someone help me install Owncloud Client on Ubuntu 20.10 like instructions. I'm asking because i saw you made 2.70-RC2 and you said it would have Ubuntu 20.10 support.

**Comment by michaelstingl** [comment] 2020-10-29 06:25
RC2 wasn’t built yet. Only the source was tagged.

Builds will be available here:
https://download.owncloud.com/desktop/ownCloud/testing/?sort=time&order=desc

**Comment by Collin8000** [comment] 2020-10-29 12:32
how do you install from source code? Is that possible because i just saw the tag and i wanted to install.

**Comment by CrazySky2121** [comment] 2020-10-29 12:38
I'm updated to Ubuntu 20.10 several days ago and can't using owncloud. It's very sad.

Do you have any ETA for building new version with Ubuntu 20.10?

**Comment by CrazySky2121** [comment] 2020-10-29 12:40
Also I think we need snap version of owncloud client. This will allow not building for a specific version of the Ubuntu or any other distros.

**Comment by Collin8000** [comment] 2020-10-29 12:41
I see they have made a tag for RC2 i can give you the link but i dont know how to build it or like build it by sourcecode or something.

**Comment by Collin8000** [comment] 2020-10-29 12:42
https://github.com/owncloud/client/releases/tag/v2.7.0-rc2

**Comment by CrazySky2121** [comment] 2020-10-29 12:51
@Collin8000 I think this doc will be useful: https://doc.owncloud.org/desktop/building.html

**Comment by Collin8000** [comment] 2020-10-29 12:56
i looked at that but like im still having trouble i get this: fatal: "not a git repository (or any of the parent directories): .git
"

**Comment by Collin8000** [comment] 2020-10-30 12:40
Michael i tried the script but connection refused

**Comment by Collin8000** [comment] 2020-10-30 12:40
is it updating or is that old?

**Comment by michaelstingl** [comment] 2020-10-30 12:45
RC2 got skipped. Will be RC3 early next week.

**Comment by Collin8000** [comment] 2020-10-31 01:10
so No support for 20.10 for now?

**Comment by michaelstingl** [comment] 2020-10-31 15:21
> So no support for 20.10 for now?

Yes, exactly. No builds with support for 20.10 yet. I’m confident this can be fixed this week.

**Comment by TheOneRing** [comment] 2020-11-05 15:20
Fixed, next nightly will have ubuntu 20.10

**Closed by TheOneRing** 2020-11-05 15:20 UTC

**Comment by pschuele** [comment] 2020-11-10 11:38
thanks for fixing it - but how do I get the nightly build? I could not find a package link on https://software.opensuse.org/

**Comment by michaelstingl** [comment] 2020-11-10 11:41
RC3:
https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/download/

Daily builds:
https://download.owncloud.com/desktop/ownCloud/daily/2.7/linux/download/

**Comment by pschuele** [comment] 2020-11-10 13:01
thanks @michaelstingl :)

**Comment by bernb** [comment] 2020-11-13 09:54
Do you know when a Ubuntu 20.10 release will be available? Could you elaborate where the delay comes from?
I feel like I had this problem several times in the last years, is there an ongoing problem?

**Comment by michaelstingl** [comment] 2020-11-13 10:02
> Do you know when a Ubuntu 20.10 release will be available?

@bernb Ubuntu 20.10 is already available in 2.7.0-RC3 and in the daily builds. (see https://github.com/owncloud/client/issues/8195#issuecomment-724648993). It will be of course also supported in the upcoming final 2.7.0 release.

> I feel like I had this problem several times in the last years, is there an ongoing problem?

I see no ongoing problem. But in this case, we had major rework of the build systems between 2.6.x and 2.7.0, and we weren't able to add Ubuntu 20.10 to the outdated 2.6.x build system.

**Comment by d4nrc** [comment] 2020-11-14 13:18
> RC3:
> https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/download/
> 
> Daily builds:
> https://download.owncloud.com/desktop/ownCloud/daily/2.7/linux/download/
> 
> (links from https://owncloud.com/beta-testing/)

Thank you! However a got a gpg issue on Ubuntu 20.10 so i can't install the RC client.
I got this error:
W: Erro GPG: https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10  InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 0700205DFD41A71A
E: The repository 'https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Can you halp me guys?

**Comment by TheOneRing** [comment] 2020-11-16 08:21
@jnweiger @dschmidt

**Comment by michaelstingl** [comment] 2020-11-16 08:58
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Please post all the steps you performed.

I wasn't able to reproduce in my Docker environment:

```
docker run --rm -ti ubuntu:20.10
```

Here you can find the steps that worked for me:

```
root@2cd63718c352:/# owncloudcmd --version
ownCloud 2.7.0rc3 (build 2413) Nov  6 2020 09:36:47
https://github.com/owncloud/client/commit/e9136f38878b9b3b879247f92812b2ac2cc3670a
Libraries Qt 5.12.9, OpenSSL 1.1.1f  31 Mar 2020
Using virtual files plugin: offroot@2cd63718c352:/# history
    1  apt update && apt install wget sudo gnupg -y
    2  wget -nv https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/Release.key -O - | sudo apt-key add -
    3  echo 'deb https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list
    4  sudo apt update
    5  sudo apt install owncloud-client
    6  owncloudcmd --version
    7  history
```

**Comment by d4nrc** [comment] 2020-11-16 13:46
These are the steps I followed:

1- $ uname -r
5.8.0-28-generic

2- $ sudo apt install gnupg
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
gnupg is already the newest version (2.2.20-1ubuntu1).
gnupg configurado para instalar manualmente.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.

3- $ sudo apt install wget
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
wget is already the newest version (1.20.3-1ubuntu1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.

4- $ wget -nv https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/Release.key -O - | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
2020-11-16 10:39:37 URL:https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/Release.key [963/963] -> "-" [1]
gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg'
gpg: keyblock resource '(null)': Erro geral
gpg: key 7721F63BD38B4796: 2 signatures not checked due to missing keys
gpg: key 4ABE1AC7557BEFF9: 1 signature not checked due to a missing key
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Número total processado: 11
gpg:       novas subchaves ignoradas: 11

5- $  echo 'deb https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list
deb https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/ /

6- $ sudo apt update
[…]
Obter:11 https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10  InRelease [1.495 B]
Err:11 https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10  InRelease
  As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 0700205DFD41A71A
Lendo listas de pacotes... Pronto
W: Erro GPG: https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10  InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 0700205DFD41A71A
E: The repository 'https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

7- $ sudo apt install owncloud-client
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
E: Impossível encontrar o pacote owncloud-client

**Comment by dschmidt** [comment] 2020-11-16 16:32
Please check that 
` wget -nv https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/Release.key -O - ` shows you a GPG key.
It should be this one:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFYJTDIBCADJdpbbm2tgRTIRtZ7TUEtg/0ozeLY05au8JbGtFFO9Kh1T8vSn
8lfmsXAjfGcCfvMTASkRNcTw+0QdU4otsaBs2sHxBdPZf0fDaF8jAf7lFXhO1Wli
SGSZ22cmN/bapendHJMIOFckSJA0de9I17a251Y/aMfm6y24whico4DNn4b1Cpui
1pefYMGKO7LHKZr4HqjQza/4BMteo6iMZJnlDK98Uvjv43YQ5R3cXRN7xpb/0qpV
/uvsKvtEAedG2QfF1lJnZE6/MY0VXH4ktfBVgsLHnE3ZDTX0oB/b7xVzCAYiYJeA
MCEIH+sTLCz6O1JInP2EDiII2F89aKF1VdhDABEBAAG0KWRldmVsIE9CUyBQcm9q
ZWN0IDxkZXZlbEBzMi5vd25jbG91ZC5jb20+iQE/BBMBAgApAhsDBwsJCAcDAgEG
FQgCCQoLBBYCAwECHgECF4AFAl+lUhoFCQt9OWgACgkQBwAgXf1BpxqZggf/XwbC
mnf/OkrTeGdu1jSPn7wpW+7OW1+BZagOQq9Mtv7QvnikNU+hd/vBKZtfqUXCA7aY
6LBURuHi/0RHC3F3rAeU6VF/fUWJWdJhSZSELVlsOIK5g7ESaSTrRW1Eu7B7MkpY
8yBBeoa3R97KlmIovwSQygp5Legb1kETVEItETnU2iAeSDMq3BPwiuRNe5xnCbkr
RAWRXPrOExZXZ6Fd031rqbjcseWxT0MfKv0H7O/qvyNRKBZoq7WSRaowS9FPxESs
wllHSdSFKZQjYwlDeUUHNoqh+k5oQDwcdxOBlwJi9wDvdS2NkTcD8gd5OGEeUIpM
pMPmlyj95mvF+FpZww==
=9uRF
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by dmark04** [comment] 2020-11-16 23:40
> These are the steps I followed:
> 
> 1- $ uname -r
> 5.8.0-28-generic
> 
> 2- $ sudo apt install gnupg
> Lendo listas de pacotes... Pronto
> Construindo árvore de dependências
> Lendo informação de estado... Pronto
> gnupg is already the newest version (2.2.20-1ubuntu1).
> gnupg configurado para instalar manualmente.
> 0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
> 
> 3- $ sudo apt install wget
> Lendo listas de pacotes... Pronto
> Construindo árvore de dependências
> Lendo informação de estado... Pronto
> wget is already the newest version (1.20.3-1ubuntu1).
> 0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
> 
> 4- $ wget -nv https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/Release.key -O - | sudo apt-key add -
> Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
> 2020-11-16 10:39:37 URL:https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/Release.key [963/963] -> "-" [1]
> gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg'
> gpg: keyblock resource '(null)': Erro geral
> gpg: key 7721F63BD38B4796: 2 signatures not checked due to missing keys
> gpg: key 4ABE1AC7557BEFF9: 1 signature not checked due to a missing key
> gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
> gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
> gpg: Número total processado: 11
> gpg: novas subchaves ignoradas: 11
> 
> 5- $ echo 'deb https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list
> deb https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10/ /
> 
> 6- $ sudo apt update
> […]
> Obter:11 https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10 InRelease [1.495 B]
> Err:11 https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10 InRelease
> As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 0700205DFD41A71A
> Lendo listas de pacotes... Pronto
> W: Erro GPG: https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10 InRelease: As assinaturas a seguir não puderam ser verificadas devido à chave pública não estar disponível: NO_PUBKEY 0700205DFD41A71A
> E: The repository 'https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10 InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> 
> 7- $ sudo apt install owncloud-client
> Lendo listas de pacotes... Pronto
> Construindo árvore de dependências
> Lendo informação de estado... Pronto
> E: Impossível encontrar o pacote owncloud-client

Your problem is the old key:

to fix your issue do:
1. through terminal or GUI remove the repository you added ( 'https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/Ubuntu_20.10 InRelease' )
(you can check if you removed the correct one if you can run `sudo apt upgrade` again without the error popping up)
 2. remove the old key  with `sudo rm /etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg`
3. repeat the steps you tried before (steps 4-7 in your list)

**Comment by jnweiger** [comment] 2020-11-17 00:48
You have an error message there: `gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg'` -> that is from a a previous attempt. Remove that file.

**Comment by d4nrc** [comment] 2020-11-17 11:59
Thank you a lot!!!!!! 
Installed. Works fine.

**Comment by CrazySky2121** [comment] 2020-11-17 12:28
Guys, do you have any ETA for prod version?

**Comment by dschmidt** [comment] 2020-11-17 13:27
Soon. We're working on it at full steam.

**Comment by d4nrc** [comment] 2020-11-19 18:42
Guys, another point: after installed that client i observed a sync issue: "could not read system exclude file”. So i can't sync files.
I copyed /etc/owncloud/sync-exclude.lst and /etc/owncloud-client/sync-exclude.lst from 6.3 client files and works fine.

**Comment by TheOneRing** [comment] 2020-11-19 19:43
@jnweiger

**Comment by CrazySky2121** [comment] 2020-12-03 17:34
Still no prod version...

**Comment by michaelstingl** [comment] 2020-12-03 18:10
> Still no prod version...

What do you mean? Check here:
https://owncloud.com/desktop-app/

**Comment by CrazySky2121** [comment] 2020-12-04 07:08
@michaelstingl Oh thanks! Previously I checked this page https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client and there no version for Ubuntu 20.10
