### ISSUE TITLE
Inconsistent Quota displayed

### ISSUE THREAD

**Issue by a-schild** [owncloud/client#3790] opened 2015-09-09 10:11 UTC
Server: 8.1.1 on Debian 8.0
MySQL Storage

Client: 2.0.1 Build 5446 on Windows 7 64Bit

The user has a default quota of 50GB set.
On serverside in the personal page, the correct 50GB are displayed.
In the 2.0.1 Windows client, it shows 54GB as quota.

Perhaps the windows client uses a 1000 instead of 1024 calculation for KB/MB/GB calculations?

![greenshot editor_2015-09-09_11-51-07](https://cloud.githubusercontent.com/assets/1441009/9759197/b3b115de-56eb-11e5-880a-33d0bd9c6b93.png)

**Comment by LukasReschke** [comment] 2015-09-09 10:22
Duplicate of https://github.com/owncloud/core/issues/18852

**Closed by LukasReschke** 2015-09-09 10:22 UTC
