### ISSUE TITLE
[Linux] Dont Reconnect When The Network Changed

### ISSUE THREAD

**Issue by cleocir** [owncloud/client#4051] opened 2015-10-31 15:17 UTC
When i change the network connection or still a long time without a network access the client stops sync and never try again.

Client version 2.0.2 (Linux)

**Comment by cleocir** [comment] 2015-10-31 15:25
Client version 2.0.2

**Comment by josh4trunks** [comment] 2015-11-01 15:55
I'm guessing you are hitting the same issue as I am. This happens nearly every time I resume my Arch Linux desktop or laptop from suspend since the update to 2.0.2. Quitting the client and launching it again fixes the problem temporarily until I resume from suspend again.
![screenshot from 2015-11-01 07-50-47](https://cloud.githubusercontent.com/assets/1018807/10869756/701216a6-806d-11e5-9fe5-ce0c811df0da.png)

Notice the "Retry Sync" button is greyed out and syncing icon is as well.
![screenshot from 2015-11-01 07-51-17](https://cloud.githubusercontent.com/assets/1018807/10869757/8c1aedaa-806d-11e5-8e22-51cec40c4f65.png)

**Comment by KloolK** [comment] 2015-11-01 16:02
Exactly the same for me. Also on Arch after resuming from suspend.

**Comment by josh4trunks** [comment] 2015-11-01 16:07
maybe we can try the following to help diagnose this further..
* enable debug and post logs from owncloud client
* see if we can reproduce this with just cutting off the network (unpluging ethernet cable / disabling network interface)

**Comment by josh4trunks** [comment] 2015-11-01 16:13
Disabling the network interface then creating a folder (to force the client to try to sync) also stops owncloud client from working.

```
11-01 08:11:50:900 7287 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
11-01 08:11:50:901 7287 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
11-01 08:11:50:902 7435 OCC::SystemProxyRunnable::run: virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup
11-01 08:11:50:909 7287 OCC::ConnectionValidator::systemProxyLookupDone: void OCC::ConnectionValidator::systemProxyLookupDone(const QNetworkProxy&) Setting QNAM proxy to be system proxy "2://:0"
11-01 08:11:50:911 7287 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://www.jruehlig.com/owncloud" + "status.php"
11-01 08:11:50:912 7287 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled." QVariant(Invalid)
11-01 08:11:50:913 7287 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply*) QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled."
11-01 08:11:50:914 7287 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href=\"https://www.jruehlig.com/owncloud\">https://www.jruehlig.com/owncloud</a>.\nNetwork access is disabled."
11-01 08:11:50:915 7287 OCC::FolderMan::slotAccountStateChanged: Account "josh4trunks@www.jruehlig.com" disconnected, terminating or descheduling sync folders
11-01 08:11:50:916 7287 unknown: QIODevice::read (QDisabledNetworkReply): device not open
11-01 08:11:50:917 7287 OCC::CheckServerJob::finished: error: status.php replied  0 ""
```

**Comment by guruz** [comment] 2015-11-02 08:22
Could you look into the client's settings dialog and tell us which version of Qt you all are using?

I think there were bugs regarding "Network access is disabled" in Qt

**Comment by cleocir** [comment] 2015-11-02 15:34
Versão 2.0.2. Para mais informações visiteowncloud.com
Por Klaas Freitag, Daniel Molkentin, Jan-Christoph Borchardt, Olivier Goffart, Markus Götz e outros.
Copyright ownCloud, Inc.
Licenciado sob a GNU General Public License (GPL) Versão 2.0
ownCloud e o logotipo ownCloud são marcas registradas da ownCloud, Inc. nos Estados Unidos, outros países, ou ambos.
Construído a partir de revisão Git 78d782 em Oct 23 2015, 06:13:12 usando Qt 5.5.1, OpenSSL 1.0.2d 9 Jul 2015

**Comment by cleocir** [comment] 2015-11-02 15:38
#samehere @KloolK .... "Also on Arch after resuming from suspend"

**Comment by Xenopathic** [comment] 2015-11-02 16:43
I'm seeing this too. Qt version 5.5.1

**Comment by KloolK** [comment] 2015-11-02 16:45
Same here:

Built from Git revision 78d782 
<https://github.com/owncloud/client/commit/78d782601e4afb9130cd8b4e214b56bbe0d1c39a>on 
Oct 23 2015, 06:13:12 using Qt 5.5.1, OpenSSL 1.0.2d 9 Jul 2015

**Comment by dragotin** [comment] 2015-11-02 16:57
Qt 5.5.1 seems to be a pattern here.

**Comment by josh4trunks** [comment] 2015-11-03 18:04
By the way, I built the owncloud-client-git from the AUR and also recieved this error.

I'm guessing this needs to be fixed in upstream Qt or the Arch package needs to be built on a different version?

**Comment by guruz** [comment] 2015-11-03 21:15
For the ones compiling Qt themselves or having easy possibility to add a patch to their Qt package compile: 
https://codereview.qt-project.org/#/c/121724/ and see if that fixes it? 
This is not in Qt 5.5.1 but in the Qt 5.5 branch.

Patch also here: https://gist.github.com/guruz/47d5e9d47c76f1e6d371

**Comment by PVince81** [comment] 2015-11-06 07:43
I applied the patch to my local Qt5.5.1 and then copied over libQt5Network.so.5.5.1 to /usr/lib64/ (I didn't want a full install).

After this, if I disable the network radio the sync client first says "No connection to host" as before, and when a reenable the network, after a minute or so the sync client resumes !

=> the patch works for me!

**Comment by guruz** [comment] 2015-11-06 09:24
@PVince81 thanks for testing :)
@ogoffart Do you have a way to influence ArchLinux to always have that patch inside their Qt?

**Comment by bwildenhain** [comment] 2015-11-06 09:32
@guruz Why should the patch only go to Arch? The same problem occurs in Debian, so this should probably fixed upstream at Qt.

**Comment by guruz** [comment] 2015-11-06 09:35
@bwildenhain It is upstreamed (and unreleased so far) in Qt, see my comment above https://github.com/owncloud/client/issues/4051#issuecomment-153491392

**Comment by guruz** [comment] 2015-11-06 09:36
@hefee ^^ Qt Debian

**Comment by RalfJung** [comment] 2015-11-16 10:09
I've had this issue already with the 2.0.0 client. I'm on Qt 5.5.X for quite a while though, so that may be it.

**Comment by guruz** [comment] 2015-11-19 15:24
@bwildenhain https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804883

**Comment by RalfJung** [comment] 2015-11-22 20:55
The patch landed in Debian, and I installed the appropriate version of Qt5Base. However, the issue is persisting: When I switched from Wired to WiFi, ownCloud stopped syncing soon thereafter and cannot be convinced to resume. (Except for a restart.)

**Comment by guruz** [comment] 2015-11-23 17:14
@RalfJung Do you have a part of the log? Starting from the last successful request to the WiFi change to the end.

```owncloud --logfile -```

**Comment by RalfJung** [comment] 2015-11-23 18:45
No, I don't have a log right now I'm afraid.

I also now saw ownCloud survive a few network changes with associated suspend without trouble - so there definitely has been some improvement. I didn't yet have the time to try and reproduce the failure, but one part that was different there is that I never was actually without network: I started with wired network, I enabled WiFi, it connected, and only then I unplugged. So if there is only a signal for when the "am I connected" status changed, it wouldn't have been triggered. Of course, my local IP changed during this procedure, so ownCloud would have to reconnect the moment the wired connection breaks down.

**Comment by rasusmilch** [comment] 2015-12-04 03:20
I also have the same issue since a recent update to owncloud on a Fedora 22 laptop. Owncloud client states version 2.1.0.
Built from Git revision c0c9fb on Dec 3 2015, 15:31:27 using Qt 5.4.1, OpenSSL 1.0.1k-fips 8 Jan 2015.

**Comment by josh4trunks** [comment] 2015-12-08 01:36
this hasn't been seeming to happen to me anymore (Arch). instead after resuming from suspend/connecting to WiFi the client just doesn't sync for a minute+. but it does eventually pull down changes as normal

**Comment by gaudenz** [comment] 2015-12-08 09:47
Here is the log of my owncloud client after disabling and reenabling the network with network-manager. This is with the Debian QT5 package which has the patches for QT bugs QTBUG-46323 and QTBUG-47471 applied. 

Owncloud client stays in the "Network access is disabled" state and does not reconnect. I'm happy to do further tests if necessary.
```
12-08 10:36:34:330 21805 unknown: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
12-08 10:36:36:923 21805 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
12-08 10:36:36:923 21805 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
12-08 10:36:36:923 1061 OCC::SystemProxyRunnable::run: virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup
12-08 10:36:36:924 21805 OCC::ConnectionValidator::systemProxyLookupDone: void OCC::ConnectionValidator::systemProxyLookupDone(const QNetworkProxy&) Setting QNAM proxy to be system proxy "2://:0"
12-08 10:36:36:924 21805 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://XXXXXX" + "status.php"
12-08 10:36:36:924 21805 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled." QVariant(Invalid)
12-08 10:36:36:924 21805 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply*) QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled."
12-08 10:36:36:924 21805 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Timeout" -> "Status not found"
12-08 10:36:36:924 21805 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href=\"https://XXXX\">https://XXXX</a>.\nNetwork access is disabled."
12-08 10:36:36:924 21805 OCC::FolderMan::slotAccountStateChanged: Account "XXXXX@XXXX" disconnected, terminating or descheduling sync folders
12-08 10:36:36:924 21805 unknown: QIODevice::read (QDisabledNetworkReply): device not open
12-08 10:36:36:924 21805 OCC::CheckServerJob::finished: error: status.php replied  0 ""
12-08 10:36:40:361 21805 unknown: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
12-08 10:36:44:651 21808 unknown: "Method \"GetAll\" with signature \"s\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n"
12-08 10:36:46:086 21805 unknown: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
12-08 10:37:08:924 21805 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
12-08 10:37:08:924 21805 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
12-08 10:37:08:924 10884 OCC::SystemProxyRunnable::run: virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup
12-08 10:37:08:925 21805 OCC::ConnectionValidator::systemProxyLookupDone: void OCC::ConnectionValidator::systemProxyLookupDone(const QNetworkProxy&) Setting QNAM proxy to be system proxy "2://:0"
12-08 10:37:08:925 21805 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://XXXX" + "status.php"
12-08 10:37:08:925 21805 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled." QVariant(Invalid)
12-08 10:37:08:925 21805 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply*) QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled."
12-08 10:37:08:925 21805 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href=\"https://XXXX\">https://XXXX</a>.\nNetwork access is disabled."
12-08 10:37:08:926 21805 OCC::FolderMan::slotAccountStateChanged: Account "XXXX@XXXX" disconnected, terminating or descheduling sync folders
12-08 10:37:08:926 21805 unknown: QIODevice::read (QDisabledNetworkReply): device not open
12-08 10:37:08:926 21805 OCC::CheckServerJob::finished: error: status.php replied  0 ""
12-08 10:37:40:923 21805 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
12-08 10:37:40:923 21805 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
12-08 10:37:40:923 12838 OCC::SystemProxyRunnable::run: virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup
12-08 10:37:40:923 21805 OCC::ConnectionValidator::systemProxyLookupDone: void OCC::ConnectionValidator::systemProxyLookupDone(const QNetworkProxy&) Setting QNAM proxy to be system proxy "2://:0"
12-08 10:37:40:924 21805 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "XXXXXXXX" + "status.php"
12-08 10:37:40:924 21805 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled." QVariant(Invalid)
12-08 10:37:40:924 21805 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply*) QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled."
12-08 10:37:40:924 21805 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href=\"https://XXXXX\">https://XXXXXX</a>.\nNetwork access is disabled."
12-08 10:37:40:924 21805 OCC::FolderMan::slotAccountStateChanged: Account "XXXX@XXXX" disconnected, terminating or descheduling sync folders
12-08 10:37:40:924 21805 unknown: QIODevice::read (QDisabledNetworkReply): device not open
12-08 10:37:40:924 21805 OCC::CheckServerJob::finished: error: status.php replied  0 ""
```

**Comment by guruz** [comment] 2015-12-14 16:57
Please also see discussion in https://github.com/owncloud/client/issues/3888

**Comment by itorres** [comment] 2016-03-16 23:12
I reproduce this error in FreeBSD with a huge (82467 files) sync. 

OCC dies with this in the logfile:
```
magellan:ownCloud$ owncloud --logfile -
03-17 00:00:25:862 101358 OCC::Application::setupLogging: "################## ownCloud ca_ES () 2.1.1"
03-17 00:00:25:862 101358 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "ca_ES" translation
03-17 00:00:25:864 101358 unknown: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-itorres'
03-17 00:00:25:864 101358 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "/tmp/runtime-itorres/ownCloud/socket"
03-17 00:00:25:864 101358 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
03-17 00:00:25:945 101358 OCC::FolderMan::setupFolders: * Setup folders from settings file
03-17 00:00:25:945 101358 OCC::Folder::checkLocalPath: Checked local path ok
03-17 00:00:25:946 101358 OCC::FolderMan::addFolderInternal: Adding folder to Folder Map  OCC::Folder(0x812677c00)
03-17 00:00:25:946 101358 OCC::FolderWatcherPrivate::slotAddFolderRecursive: (+) Watcher: "/usr/home/itorres/ownCloud/"
03-17 00:00:27:709 101358 OCC::FolderWatcherPrivate::slotAddFolderRecursive:     `-> and 4582 subdirectories
03-17 00:00:27:710 101358 OCC::FolderMan::slotScheduleSync: Schedule folder  "ownCloud"  to sync!
03-17 00:00:27:710 101358 OCC::FolderMan::slotScheduleSync: Folder is not ready to sync, not scheduled!
03-17 00:00:27:711 101358 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration
03-17 00:00:27:755 101358 OCC::SqlQuery::prepare: Sqlite prepare statement error: "unable to open database file" in "PRAGMA quick_check;"
03-17 00:00:27:755 101358 OCC::SqlDatabase::checkDb: quick_check returned failure: ""
03-17 00:00:27:755 101358 OCC::SqlDatabase::openOrCreateReadWrite: Consistency check failed, removing broken db "/usr/home/itorres/ownCloud/.csync_journal.db"
03-17 00:00:27:756 101358 OCC::SqlDatabase::openHelper: Error: "unable to open database file" for "/usr/home/itorres/ownCloud/.csync_journal.db"
03-17 00:00:27:756 101358 OCC::SyncJournalDb::checkConnect: Error opening the db:  "unable to open database file"
03-17 00:00:27:955 101358 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-17 00:00:27:956 101358 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-17 00:00:27:956 101400 OCC::SystemProxyRunnable::run: virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup
03-17 00:00:27:960 101358 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-17 00:00:27:961 101358 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)

(process:45473): GLib-ERROR **: Creating pipes for GWakeup: Too many open files in system

Trace/BPT trap
```

After I modify the kern.maxfiles with `sudo sysctl -w kern.maxfiles=90000` the error changes to the one referred in this issue:

```
magellan:~$ owncloud --logfile -
03-17 00:04:41:709 101382 OCC::Application::setupLogging: "################## ownCloud ca_ES () 2.1.1"
03-17 00:04:41:709 101382 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "ca_ES" translation
03-17 00:04:41:711 101382 unknown: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-itorres'
03-17 00:04:41:712 101382 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "/tmp/runtime-itorres/ownCloud/socket"
03-17 00:04:41:712 101382 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
03-17 00:04:41:841 101382 OCC::FolderMan::setupFolders: * Setup folders from settings file
03-17 00:04:41:841 101382 OCC::Folder::checkLocalPath: Checked local path ok
03-17 00:04:41:842 101382 OCC::FolderMan::addFolderInternal: Adding folder to Folder Map  OCC::Folder(0x812677c00)
03-17 00:04:41:842 101382 OCC::FolderWatcherPrivate::slotAddFolderRecursive: (+) Watcher: "/usr/home/itorres/ownCloud/"
03-17 00:04:43:677 101382 OCC::FolderWatcherPrivate::slotAddFolderRecursive:     `-> and 4582 subdirectories
03-17 00:04:43:677 101382 OCC::FolderMan::slotScheduleSync: Schedule folder  "ownCloud"  to sync!
03-17 00:04:43:677 101382 OCC::FolderMan::slotScheduleSync: Folder is not ready to sync, not scheduled!
03-17 00:04:43:678 101382 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration
03-17 00:04:43:723 101382 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.10.2"
03-17 00:04:43:723 101382 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
03-17 00:04:43:723 101382 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "checkConnect" and starting new transaction
03-17 00:04:43:723 101382 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
03-17 00:04:43:723 101382 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "update database structure: add inode index" and starting new transaction
03-17 00:04:43:723 101382 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "update database structure: add path index" and starting new transaction
03-17 00:04:43:723 101382 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration")
03-17 00:04:43:724 101382 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "checkConnect End" 
03-17 00:04:43:898 101382 unknown: XmbTextListToTextProperty result code -2
03-17 00:04:43:900 101382 unknown: XmbTextListToTextProperty result code -2
03-17 00:04:43:931 101382 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-17 00:04:43:931 101382 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-17 00:04:43:932 101432 OCC::SystemProxyRunnable::run: virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup
03-17 00:04:43:934 101382 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-17 00:04:43:935 101382 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
03-17 00:04:43:935 101382 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://server/owncloud/" + "status.php" "OCC::ConnectionValidator"
03-17 00:04:43:937 101382 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(HostNotFoundError) "Host server not found" QVariant(Invalid)
03-17 00:04:43:937 101382 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply *) QNetworkReply::NetworkError(HostNotFoundError) "Host server not found"
03-17 00:04:43:937 101382 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Undefined" -> "Status not found"
03-17 00:04:43:937 101382 OCC::AccountState::setState: AccountState state change:  "Desconnectat" -> "Error de xarxa"
03-17 00:04:43:937 101382 OCC::AccountSettings::showConnectionLabel: "No hi ha connexió amb ownCloud a <a href=\"https://server/owncloud/\">https://server/owncloud/</a>.\nHost server not found"
03-17 00:04:43:938 101382 OCC::FolderMan::slotAccountStateChanged: Account "itorres@server" disconnected, terminating or descheduling sync folders
03-17 00:04:43:938 101382 OCC::CheckServerJob::finished: error: status.php replied  0 ""
03-17 00:04:47:080 101382 OCC::UpdaterScheduler::slotTimerFired: void OCC::UpdaterScheduler::slotTimerFired() Skipping update check because of config file
  C-c C-c
magellan:~$ 
```

I then tried configuring a sync folder in another server and the error is the same.

If I delete the configured sync folder with a vast amount of files then the client works finely.

Maybe there's some QT limit besides the system ulimit/maxfiles that interferes with QNAM name resolution.

**Comment by Paviluf** [comment] 2016-03-26 13:56
If I understand correctly [that](https://codereview.qt-project.org/#/c/121724/) and [that](https://bugreports.qt.io/browse/QTBUG-46323) the ownCloud client reconnection after suspend will be fixed with Qt 5.6 ?

**Comment by guruz** [comment] 2016-06-07 05:57
We pushed a possible workaround. Could you please test 2.2.1 and report back if it works? Thanks

**Comment by kas70** [comment] 2016-06-07 09:27
Hey there, i'm on Version 2.1.1+dfsg-1ubuntu1.1 and still affected by this issue

**Comment by guruz** [comment] 2016-06-07 09:49
@kas70 You need to be on 2.2.1.. possibly the Linux packages are not rolled out yet

**Comment by guruz** [comment] 2016-09-06 13:08
Let's close this. If you experience this with 2.2.3 or later please create a new issue.

**Closed by guruz** 2016-09-06 13:08 UTC
Labels: Known Issue / Workaround
