### ISSUE TITLE
[Windows] Progress display: MB pixels cropped during upload

### ISSUE THREAD

**Issue by calis2002** [owncloud/client#4562] opened 2016-03-10 05:39 UTC
As seen on the screenshot the first digit of uploaded MB is overlapped by the upload bar.
It's just on Windows, on Linux everything is ok.
![2016-03-10__06_31_49](https://cloud.githubusercontent.com/assets/4539953/13660478/97953e3c-e68a-11e5-9a70-278c1ff75197.png)

### Client configuration
Client version: ownCloud-2.2.0.5891-nightly20160310

Operating system: Windows 10 fully patched

**Comment by michaelstingl** [comment] 2016-03-14 15:55
This happens when "Total time left" is less than 1 Minute. It seems the progress bar jumps depending on the length of the 2nd line.

![jumping_progressbar](https://cloud.githubusercontent.com/assets/214010/13750245/f6dc2ff4-ea04-11e5-8543-7a1872ec46aa.gif)

### Client configuration
Client version:
8.2.2

Operating system:
Win 10

OS language:
DE

00005022

**Comment by ckamm** [comment] 2016-03-15 14:41
Thanks @michaelstingl, the animation was very helpful!

**Comment by ckamm** [comment] 2016-03-15 15:31
I can reproduce this on Windows and not on Linux. Unfortunately it looks like a Qt bug. The value returned from
```
progressFm.boundingRect(QRect(), 0, overallString );
```
is simply not big enough to cover the space needed for `overallString`. The bug is unrelated to the "\n" in the string - a similar problem appears with a long single-line string. The size of the error depends on the size of the text. Examples:
```
"Very long first line, maybe overly long even" -> "Ver" is cut off
"Very long first line, maybe overly long even, now even longer, what happens?" - > "Very l" is cut off
```

I found https://bugreports.qt.io/browse/QTBUG-15974 which indicates this might be related to font hinting. Using `setHintingPreference` doesn't remove the problem though.

**Comment by ckamm** [comment] 2016-03-15 15:40
I tried a workaround where I draw the text to a `QPainterPath` and then render that. The size of `boundingRect` is correct in that case, but the text is nearly unreadable (small and no hinting...).

**Comment by ckamm** [comment] 2016-03-15 15:46
The problem also has an open issue in Qt at https://bugreports.qt.io/browse/QTBUG-51024

**Comment by ckamm** [comment] 2016-03-17 08:37
I couldn't find any workarounds. @guruz @ogoffart any ideas? We may have to switch to a layout that's not dependent on the width of a text.

Can one test-draw text to a hidden surface and check the actual size?

**Comment by ckamm** [comment] 2016-03-30 07:23
Addressed by changing the progress layout

**Comment by calis2002** [comment] 2016-04-01 07:37
Looks good for me now. No problem anymore.

**Closed** 2016-04-03 09:39 UTC
Labels: blue-ticket, Design & UX, ReadyToTest
