### ISSUE TITLE
[QA] Flaky GUI test

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10908] opened 2023-06-05 04:32 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue
`Scenario: Syncing a file from the server and creating a conflict`
Build: https://drone.owncloud.com/owncloud/client/15614
Report: https://cache.owncloud.com/public/owncloud/client/15614/ocis/guiReportUpload/index.html

### Steps to reproduce the issue

.

### Screenshots

![Screenshot from 2023-06-05 10-16-32](https://github.com/owncloud/client/assets/52366632/5acaeafa-049c-4922-9bb4-a16668799bed)

![Screenshot from 2023-06-05 10-17-20](https://github.com/owncloud/client/assets/52366632/4be5f995-a832-44d4-a7b0-9df4b063d971)

**Comment by Salipa-Gurung** [comment] 2023-06-12 11:33
Could not reproduce locally

**Comment by grgprarup** [comment] 2023-06-27 07:06
The issue cannot reproduce locally and is not appearing in recent CI. So closing this. It can be reopened and investigated thoroughly if fail again.

**Closed by grgprarup** 2023-06-27 07:06 UTC
Labels: QA:team
