### ISSUE TITLE
[Qt] TLS certificate error with valid certificate

### ISSUE THREAD

**Issue by ogasser** [owncloud/client#5572] opened 2017-03-01 14:17 UTC
### Expected behaviour
* I expect to being able to connect securely to my host: `https://www.isas-münchen.de/nextcloud`
* Connecting via the web browser works correctly
* The certificate includes both domains (with and without www.) in *Certificate Subject Alt Name*

### Actual behaviour
* Cannot connect securely to www.isas-münchen.de:
The host name did not match any of the valid hosts for this certificate

### Steps to reproduce
1. Connect to `https://www.isas-münchen.de/nextcloud` with Deskopt client
2. Connection TLS certificate error

Is the *Certificate Subject Alt Name* in certificates not checked? Are XN-Domains not correctly compared in *Certificate Subject Alt Name*?

**Comment by ogoffart** [comment] 2017-03-02 09:05
I can reproduce the issue.  It seems to be a problem with the punicode 
Related to issue #5530

**Comment by ogoffart** [comment] 2017-03-06 18:34
Problem was in Qt, we are fixing it upstream: https://codereview.qt-project.org/187378/
The fix will be in the next version of Qt.

**Comment by SamuAlfageme** [comment] 2017-04-12 11:45
Woops, just saw the fix was scheduled for 5.8; removing the RTT tag.

**Comment by ogoffart** [comment] 2017-04-12 12:58
Closing as this is fixed upstream in Qt.

**Closed by ogoffart** 2017-04-12 12:58 UTC
Labels: bug
