### ISSUE TITLE
Upload speed has incorrect value when resuming a folder with chunks

### ISSUE THREAD

**Issue by stephane84** [owncloud/client#2609] opened 2014-12-11 20:58 UTC
When I **resume** a folder that is uploading chunks of 20Mo to upload a huge file, the estimation of the bitrate seems incorrect : 

![printscreen](http://s30.postimg.org/yfvpz098x/owncloud3.png)

The value is very big (33 Mbps !) and descrease slowly in time... (from 47Mbps to 2Mpbs)

I think the computation takes the "total already uploaded data" / "current elaped time".... while it should be "the current uploaded data (current chunk)" / "current elapsed time", resulting in a lower final value for the bitrate

Owncloud client 1.7.0 nightly build 04/12/14. Owncloud Server 7.0.3.4

Steps to reproduce : 

* synchronize a file > 100Mo
* pause the sync after the first chunk (20Mo)
* resume the sync and check directly the estimated bitrate
* the bitrate is very high, bigger than the real bitrate

**Comment by get2him** [comment] 2015-03-21 14:52
I observed the same issue with Windows OwnCloud Client 1.80.
My ISP upload speed is 1Mbit/s. 
The client reports a wrong speed. Sometime too much. Sometimes a lower speed then the actual upload speed.

![owncloud win client 1 80](https://cloud.githubusercontent.com/assets/11586377/6765477/32a7b17c-cfe2-11e4-97c5-f2d2e84e73de.jpg)

**Comment by ogoffart** [comment] 2015-03-24 14:38
Duplicate of #2328

**Closed by ogoffart** 2015-03-24 14:38 UTC
Labels: bug
