### ISSUE TITLE
Desktop Client deleted non-synced folders from Server 

### ISSUE THREAD

**Issue by haukman** [owncloud/client#7128] opened 2019-04-03 11:28 UTC
### Expected behaviour
Desktop Client doesn´t sync folders that are not selected for sync 

### Actual behaviour
ownCloud deleted the folder on the server

### Steps to reproduce
1. Integrity check error occurred in the desktop client 
2. I removed the affected folder from the sync via selective sync
3. Integrity check error still occurred, although the folder was not in sync 
4. Waited for several days (including OS restarts etc.)
5. Integrity check error still occurred
6. Checked again if the folder is unselected (which it was)
7. Found out that the affected folder is still on my disk
8. Deleted the folder
9. Folder also deleted from server

Integrity error:

<img width="772" alt="grafik" src="https://user-images.githubusercontent.com/25486818/55475317-e5b93b80-5613-11e9-82d9-93d0ddaf2681.png">

My assumption was, that the Desktop Client didn´t finish the sync of this specific folder because of the integrity error. Therefore this folder was still present on my disk and somehow still connected to the sync.

### Client configuration
Client version:
2.5.4
<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/25486818/55475249-b0145280-5613-11e9-98f7-ed7f77911b68.png">

Operating system:
<img width="328" alt="grafik" src="https://user-images.githubusercontent.com/25486818/55475260-ba365100-5613-11e9-8e5d-1a5e09b37ed7.png">

OS language:
Englisch
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ckamm** [comment] 2019-04-12 09:39
The client deleting a selective-sync excluded folder on the remote would be an important issue. Will investigate.

**Comment by ckamm** [comment] 2019-04-12 10:11
@haukman Did you by any chance have several similarly named directories? Particularly, if the folder you excluded was called "foo" was there another folder "foo bar"?

**Comment by haukman** [comment] 2019-04-12 10:38
> @haukman Did you by any chance have several similarly named directories? Particularly, if the folder you excluded was called "foo" was there another folder "foo bar"?
> 


The folder I excluded is called "marketing", there are no other folders in the next level that are called "marketing"-something. 

> Also, can you confirm the folder itself was removed on the server, and not just contents inside it?

Can´t tell, but @jnweiger should have the answer, as he was the one who recovered it :) I was out for lunch during that time.

**Comment by ckamm** [comment] 2019-04-12 10:40
I've not yet been able to reproduce anything like it while experimenting with a folder that contains files that had errors during download.

**Comment by ckamm** [comment] 2019-06-05 09:06
@ogoffart Maybe you have an idea? Without logs or being able to reproduce this remains a mystery issue.

**Comment by ogoffart** [comment] 2019-06-05 09:55
> 8. Deleted the folder

You mean you deleted the folder yourself?  
If you delete the folder, the change will be propagated to the server, i think

**Comment by haukman** [comment] 2019-06-05 10:08
> > 1. Deleted the folder
> 
> You mean you deleted the folder yourself?
> If you delete the folder, the change will be propagated to the server, i think

I deleted the folder on my disk, because  (I thought) it was already ignored by the desktop client as it was not selected anymore

**Comment by michaelstingl** [comment] 2019-09-23 15:05
@HanaGemela Please check with 2.6

**Comment by HanaGemela** [comment] 2019-09-24 14:16
Maybe the folder shouldn't be removed locally in step number 4 because it might include local changes that have not been synced to the server yet. So maybe just remove the sync connection and keep the files locally. Once they will be synced from the server again, they will create conflict files

**Comment by ogoffart** [comment] 2019-10-09 15:12
> Maybe the folder shouldn't be removed locally in step number 4 because it might include local changes that have not been synced to the server due to the error yet.

That's correct:  This is the reason why we do not remove the files in the "The server reported the following error"
But that's unrelated to the original issue.

The original issue was about the client propagating changes (in this case deletion) inside the folder which is unchecked from selective sync.

This should be fixed in 2.6, as the new discovery has a new special code path for selective sync that can only issue local remove or ignore. 

@haukman can you still reproduce with 2.6 rc ?

**Comment by ogoffart** [comment] 2020-02-06 15:52
Closing old issue.

**Closed by ogoffart** 2020-02-06 15:52 UTC
Labels: Needs info, bug, p2-high
