### ISSUE TITLE
delete stale chunked upload transfers more aggresively

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5344] opened 2016-11-29 17:19 UTC
This is about the current major flow of the V1 chunking algorithm which we need to fix in V1 because of deployment reasons (cannot wait for full NG support).

Currently when an upload of a file fails, it is blacklisted after 3 retries and removed from blacklist and tried again after some time. This is good for plain PUT but not for chunked PUT. If the chunk fails consistently (*), this process will never stop and the client will try indefinitely (I see in the logs 100s of failed PUTs over and over again for several users). What is needed in this case is resetting of the entire chunked transfer from scratch. Manually I can achieve this by: 

    sqlite> delete from uploadinfo where path="xxx";

But I cannot ask users to do it manually.

Looking into the source code, the cleanup of stale upload transfers is already implemented in src/libsync/syncengine.cpp as deleteStaleUploadInfos(). However it will not cleanup such failed chunk transfers in a way which allows the client to restart the whole chunked upload.

Could we declare that after 3 (or more) failed retries the entire chunk transfer is reset, gets the new transfer id and is retried from scratch? Alternatively, at client startup, can we remove all entries for chunked transfers from uploadinfo? At least this would give us a clear operational procedure to restart the client (not as nice as automatic handling of the error but still workable for the time being)? 

(*) consistent chunk failing may happen when the server enters into a bad state for the particular transfer id. In the case of our storage it could happen that chunks came out of order at some point and our server which does not support out-of-order chunk currently will always fail for this transfer id. What needs to be done is to start the transfer from scratch with a new transfer id.

**Comment by Kawohl** [comment] 2016-11-29 18:07
@guruz @ogoffart

**Comment by ogoffart** [comment] 2016-11-30 09:25
This should have been fixed a year ago as part of issue #3934

**Comment by ogoffart** [comment] 2016-11-30 09:25
What is the version of the client with this problem?

**Comment by ogoffart** [comment] 2016-11-30 09:30
Ah ok, i think i misunderstood the problem.  This was another issue.

**Comment by moscicki** [comment] 2016-12-01 20:29
Cool. Could I try it out with some nightly?

**Comment by guruz** [comment] 2016-12-05 16:21
@moscicki Should be in tomorrow morning's nightly

**Comment by glpatcern** [comment] 2016-12-07 09:29
Hi,

We (I and @moscicki) have tested the fix, but it seems that it unveiled another issue. The commit correctly assumes that the retryCount is updated, but this does not seem to be the case as the uploadinfo.errorcount field stays at 0:
```
$ sqlite3 --header ._sync_985a2109c4ff.db 'select * from uploadinfo;'
path|chunk|transferid|errorcount|size|modtime
test100M|1|948631710|0|0|1481102151
```
As a result, the client is still looping forever. Any clue? Is my guess about the errorcount field correct?

**Comment by ogoffart** [comment] 2016-12-08 08:44
What is causing the error?  which call?  Is there chunks succeeding in the mean time?

**Comment by moscicki** [comment] 2016-12-10 07:54
To reproduce this problem it you should trigger unrecoverable error state on the server while the chunked upload is in progress. Such that subsequent chunked PUT requests will fail forever.

What we is the following: generate a file sufficiently large, say 20 chunks. Quit the client after a few chunks, say 10, have been uploaded correctly.  Change the transfer id in csync db in uploadinfo. Restart the client. The client will try to resume from the chunk number 11. Our server will refuse this PUT because it knows nothing about this file. Hence the PUT will fail and it will keep on failing forever.

I guess in case of owncloud server you may try remove write access on the chunked folder, the folder itself or the so-far uploaded chunks if you want to reproduce this error.

The client is not capable of getting unstuck from this situation and it insists on the PUT number 11 even if it failed large number of times. The way to manually recover from this is to delete the transfer from uploadinfo. The client should do the same after it had seen that a chunk failed several times. Since this kind of error condition is rare, you may set the retry number higher than 3 such that it will not affect the ususal client behaviour for "normal" error conditions (such as shaky network).

**Comment by ckamm** [comment] 2016-12-13 08:27
@moscicki 

@ogoffart's implementation ties to the blacklist's retryCount, not the uploadInfo's error count. I think the idea was that that is how we already track repeated errors and that we can use the functionality to wipe uploadinfos on transfers that fail the same way several times.

Does your log file contain any "blacklisting " entries for the transfer? I'll also try reproducing this.

**Comment by ckamm** [comment] 2016-12-13 09:00
I've also tested this locally and @ogoffart's patch works in the following way for me:
* A chunk PUT is consistently failing (I made the user-data/cache folder that stores chunks read-only on the server). Note that it's actually a series of 3 parallel chunk uploads failing and that any of them succeeding will reset the blacklist entry.
* The file gets put on the error blacklist and is only retried after increasing amounts of delays.
* Eventually the uploadinfo is reset and the whole upload is restarted from chunk 0 with a new transfer id.

I was testing the old chunked upload codepath here.

**Comment by moscicki** [comment] 2016-12-13 14:59
Hello,

Thank you for testing. In our test described previously we triggered 503 error on subsequent PUTs from the server. Is it possible that the blacklisting code does not take this class of errors (Service Unavailable) into account? 

What error response from the server did you get in your test? 

Would the recovery mechanism that @ogoffart implemented work correctly with 412 error responses?

**Comment by ckamm** [comment] 2016-12-14 09:07
@moscicki Yes, 503 is treated as a fatal error that doesn't get blacklisted. 

A 412 error would also not trigger @ogoffart's new code since a precondition failure is treated as a soft error and never blacklisted. (and the recovery process is to ensure the server data is read from the server instead of from the db on the next sync; guaranteeing that we get the correct etag)

Are you saying you're seeing persistent 412s in the wild? We could start putting them on the blacklist I suppose, it'd only change behavior if the recovery process fails - and something odd is going on server side if that's the case.

**Comment by ckamm** [comment] 2016-12-20 08:38
@moscicki I'd expect it would but haven't tested it. I'll check about using the retry count on the transfer.

**Comment by ckamm** [comment] 2016-12-20 09:58
@moscicki @ogoffart There's a potential patch that tracks 503 and 412 errors in a way that allows @ogoffart's transaction reset code to work. I'll be testing it locally now.

**Comment by moscicki** [comment] 2016-12-20 10:03
Okey, please let us know if you patch passes your initial tests. Then we will test it in our setup.

**Comment by ckamm** [comment] 2016-12-20 10:20
@moscicki I've tested with 503 and 412 errors and it does eventually abort the transfer and start a new one now (I didn't change any other error behavior, so 503 is still loud and red, while 412 is essentially silent).

I'm wondering if this is something that the client should only do for CERN's server.

**Comment by michaelstingl** [comment] 2016-12-22 19:28
> I'm wondering if this is something that the client should only do for CERN's server.

Using server capabilities to trigger this?

**Comment by ckamm** [comment] 2017-01-03 10:02
@moscicki Did you get a chance to test the patch? 

Also, could you remind me how to detect your server? I don't think we have existing code for that yet.

**Comment by michaelstingl** [comment] 2017-01-03 10:26
As far as I know, client already detects @moscicki 's server to enable checksumming. This also make use of server capabilities.

**Comment by ckamm** [comment] 2017-01-04 13:10
@michaelstingl That uses the server-independent checksumming capability. We probably don't want to add a "replying 503 or 412 might indicate being permanently stuck" capability. Huh, though there could be a "please reset uploads eventually when these error codes are seen" capability. @moscicki?

**Comment by moscicki** [comment] 2017-01-06 17:21
It is for me completely OK to enable it via server-side capability, something like "reset stale chunked uploads" sounds good to me.

Here is more input from me on this which you may consider:

412 may actually be returned on checksum errors (c.f.: https://github.com/cernbox/smashbox/blob/master/protocol/checksum.md). It is not unreasonable to assume that stale chunked uploads could have permanent checksumming errors. So you may consider that resetting the upload on 412 code is not CERN specific. However, thinking about this, 412 also indicated mismatching ETAG. Would it be a problem? I do not think so, but this part is not very well specified and the meaning of 412 is overloaded. Could someone please give a thought on this?

503 is a clear bug in our server implementation and as such should be enabled as a temporary workaround (I am completely OKey also to enable it via additional capability if you prefer if you decided that you want to have more flexibility).

**Comment by ckamm** [comment] 2017-01-10 12:57
@moscicki Thanks for the reminder about 412 also relating to checksums! I agree that resetting stale uploads makes a lot of sense in that case. The ETAG error coinciding shouldn't be a problem because that shouldn't happen several times in a row as the client has a clear resolution process for it.

I'll add this as a capability - primarily so other error codes can be added at a later point if necessary.

**Comment by ckamm** [comment] 2017-01-10 15:17
@moscicki Pull request is at https://github.com/owncloud/client/pull/5443

**Comment by ckamm** [comment] 2017-01-11 14:35
@moscicki @ogoffart has approved. You'd need to add a capability like `dav/httpErrorCodesThatResetFailingChunkedUploads = [513]` - does that look good to you?

**Comment by moscicki** [comment] 2017-01-12 15:34
Thanks, we will give a try and report back.

**Comment by glpatcern** [comment] 2017-01-20 11:25
Hi all, with @moscicki  we tested the patch and we found a critical bug:

The mechanism works well (both for HTTP 412 and any code specified in the server capability), but only if there is a previous uploadinfo record.

This means that if the first chunked PUT request fails, the uploadinfo is not even created: the line https://github.com/owncloud/client/blob/master/src/libsync/propagateupload.cpp#L501 creates a new uploadinfo record, which eventually is not saved in the database.

This may lead sometimes to "false negatives", in the sense that the client gets an error but actually says everything is OK (and the uploadinfo table is empty).

**Comment by moscicki** [comment] 2017-01-23 09:12
If someone needs an account and a test procedure to reproduce this problem -- let me know via private email.

**Comment by ckamm** [comment] 2017-01-24 10:05
@moscicki @glpatcern I don't understand the problem you describe.

Yes, when the first chunk fails to upload, no uploadInfo will be created. That is correct, no partial transaction exists. Each following attempt will create a new transaction id. Whatever problem exists should be unrelated to this ticket.

When I make my server return 503 on the first PUT of a chunked upload, an error message is displayed in the client. The only case I can imagine where you would see the "false negative" you mention, is if your server replies 412 Precondition Failed on the first PUT: Then the client typically doesn't notify the user, and just reruns the sync with an etag error recovery mode for the file (see earlier comment).

Can you describe the problem you're seeing in more detail?

**Comment by glpatcern** [comment] 2017-01-24 17:10
OK, the "false negative" was actually due to blacklisting, so we confirm the logic works. And yes, on first failed chunk there's no uploadinfo and each attempt generates a new transferid.

An additional question would be: which are the conditions for the file to be blacklisted? I.e. how many attempts and which error codes?

**Comment by ckamm** [comment] 2017-01-25 09:24
@glpatcern Currently every error that has a http response code and is considered a "normal error" by the client will be blacklisted. Blacklisting means temporarily ignoring the file during sync, it starts at 25s and scales up to 1 day after 6 failed attempts. Files with 403s are never ignored for more than a minute, files with 413 or 415 are ignored for a day after the first attempt.

(I think no one is very happy with the blacklisting logic. We've talked about just muting errors instead of completely ignoring files for some time, but worry about situations where we would repeatedly try to upload a huge file that always fails with something like a 413, and thereby waste large amounts of time and bandwidth)

**Comment by ogoffart** [comment] 2017-01-31 12:29
Can we now close this issue?

**Comment by glpatcern** [comment] 2017-02-07 09:02
Hi, thanks to @ckamm for the information - we share the same feeling actually - and yes, you can close this issue. With @moscicki we've done enough tests so far and it works as expected. We'll do more tests once we're ready to deploy the new clients.

**Comment by ckamm** [comment] 2017-02-07 09:03
@glpatcern Thank you for the confirmation!

**Closed by ckamm** 2017-02-07 09:03 UTC
Labels: blue-ticket
