### ISSUE TITLE
ownCloud Desktop client 2.5.1 for MacOS: unable to configure client-side certificates

### ISSUE THREAD

**Issue by eelmasllari** [owncloud/client#6940] opened 2018-12-23 11:00 UTC
### Expected behaviour
Client side certificates are configured and used to connect to the server

### Actual behaviour
I can choose client-side certificates in the configuration dialog, but they do not get used; The server rejects the connection with a 400 error, "no SSL certificates sent", and the configuration dialog says "Could not load certificate", similar to the issue in https://github.com/owncloud/client/issues/6128

The difference to that issue is that i am typing the password correctly  (verified multiple times). Also the certificate works and is not expired.
![image](https://user-images.githubusercontent.com/3466670/50382965-ce7cc080-06aa-11e9-8937-ca1d743f3c3d.png)

### Steps to reproduce
1. install oc desktop client 2.5.1 (clean install, not update from previous client! see below "Workaround")
2. Configure a new account
3. Input server URL. When server rejects connection without client certificates, choose to configure client side certificates
4. choose certificate, enter password
5. Click OK. Server will reject with code 400, "no SSL certificates sent", and configuration dialog will say "Could not load certificate"

### Server configuration
Operating system: Debian Jessie
Web server: Nginx
Database: MariaDB
PHP version: 5.6
ownCloud version: 10.0.10.4

### Client configuration
Client version: 2.5.1
Operating system: macOS High Sierra 10.13.6
OS language: en-US
Installation path of client: /Applications

### Logs
Client Log: https://gist.github.com/eelmasllari/e901fd6605779705ae10eab53807e4de

### Partial Workaround
1. Install desktop client v 2.3.3
2. Configure the connection there
3. Update to desktop client v2.5.1
Now everything works, except that you cannot add new accounts to the 2.5.1 installation; the same problem will appear and only the accounts that were configured with 2.3.3 will continue working

**Comment by michaelstingl** [comment] 2018-12-24 09:56
Related to https://github.com/owncloud/client/issues/6911 ? If this is the same issue, we could close this duplicate and provide missing information in https://github.com/owncloud/client/issues/6911

**Comment by ogoffart** [comment] 2018-12-29 09:48
closing as duplicate of #6911

**Closed by ogoffart** 2018-12-29 09:48 UTC
