### ISSUE TITLE
client crashed OCC::AccountSettings::addModalWidget at `accountsettings.cpp:843`

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11496] opened 2024-01-29 05:51 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Build: https://drone.owncloud.com/owncloud/client/17596

```c
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fd705b1b844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7fd702448f00 (LWP 2432))]
#0  0x00007fd705b1b844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007fd705acaabe in raise () at /lib64/libc.so.6
#2  0x00007fd705ab390f in abort () at /lib64/libc.so.6
#3  0x00007fd7060970eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007fd706097b7f in  () at /lib64/libQt6Core.so.6
#5  0x00007fd706097083 in qt_assert_x(char const*, char const*, char const*, int) () at /lib64/libQt6Core.so.6
#6  0x00000000004be198 in OCC::AccountSettings::addModalWidget(QWidget*, OCC::AccountSettings::ModalWidgetSizePolicy) (this=0xc324a0, widget=0x1623980, sizePolicy=OCC::AccountSettings::ModalWidgetSizePolicy::Expanding) at /drone/src/src/gui/accountsettings.cpp:843
        outerWidget = 0x15f5770
        groupBox = 0x16de4c0
#7  0x000000000054023b in OCC::ownCloudGui::slotShowShareDialog(QString const&, QString const&, OCC::ShareDialogStartPage) (this=0xa5f7a0, sharePath=..., localPath=..., startPage=OCC::ShareDialogStartPage::UsersAndGroups) at /drone/src/src/gui/owncloudgui.cpp:1072
        accountState = {wp = {d = 0x9f9120, value = 0x9f7540}}
        w = 0x1623980
        fileRecord = {_path = {d = {d = 0x163a160, ptr = 0x163a170 "textfile0.txt", size = 13}, static _empty = 0 '\000'}, _inode = 4253289, _modtime = 1706490098, _type = CSyncEnums::ItemTypeFile, _etag = {d = {d = 0x16bbbf0, ptr = 0x16bbc00 "2fa6ffbe8e02fec162a83ed4c4763f0b", size = 32}, static _empty = 0 '\000'}, _fileId = {d = {d = 0x7fd6fc00b810, ptr = 0x7fd6fc00b820 "00000340oclqt3mbpjw5", size = 20}, static _empty = 0 '\000'}, _fileSize = 25, _remotePerm = {_value = 415, static notNullMask = 1}, _serverHasIgnoredFiles = false, _hasDirtyPlaceholder = false, _checksumHeader = {d = {d = 0x167a780, ptr = 0x167a790 "SHA1:2052377dec0724bda0d57aeab67fa819278b7f74", size = 45}, static _empty = 0 '\000'}}
        resharingAllowed = true
        maxSharingPermissions = {i = 31}
        file = {d = {d = 0x15f97b0, ptr = 0x15f97c0 u"textfile0.txt", size = 13}, static _empty = 0 u'\000'}
        folder = 0xa0dc70
```

### Logs

[stacktrace.log](https://github.com/owncloud/client/files/14080078/stacktrace.log)
[clientlog.log](https://github.com/owncloud/client/files/14080088/serverlog.log)

### Client version number

6.0.0.git (master)

### Server information

ownCloud 10.13.4

**Comment by TheOneRing** [comment] 2024-05-28 11:16
Duplicate off: https://github.com/owncloud/client/issues/11515

**Closed by TheOneRing** 2024-05-28 11:16 UTC
Labels: bug
