### ISSUE TITLE
[2.1.1] ownCloud freezes on El Capitan

### ISSUE THREAD

**Issue by donnoc** [owncloud/client#4500] opened 2016-02-23 08:10 UTC
### Expected behaviour
Run smooth when it starts to sync

### Actual behaviour
ownCloud freezes every time it starts to sync for a few seconds and syncs smooth afterwards

### Steps to reproduce
1. Start ownCloud
2. Let it sync
3. 

### Server configuration
Operating system: Ubuntu 

Web server: Apache/2.4.7 (Ubuntu)

Database: Ver 14.14 Distrib 5.5.46

PHP version: PHP 5.6.14-1+deb.sury.org~trusty+1 (cli)

ownCloud version: ownCloud 8.1.1 (stable)

Storage backend:

### Client configuration
Client version: 2.1.1 (but happened since every 2.*.* Version)

Operating system: 10.11.3

OS language: german

Installation path of client: /Applications

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
02-23 09:09:39:708 0x7fc0a842adb0 OCC::Application::setupLogging: "################## ownCloud de_DE (de) 2.1.1 (build 3107)"
02-23 09:09:39:709 0x7fc0a842adb0 OCC::Application::slotParseMessage: Running for 13317.4 sec
02-23 09:09:39:709 0x7fc0a842adb0 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
02-23 09:09:39:924 0x7fc0a842adb0 OCC::Folder::slotRunEtagJob: * Trying to check "https://drsdrive.anevay.de/owncloud/remote.php/webdav/" for changes via ETag check. (time since last sync: 153 s)
02-23 09:09:39:924 0x7fc0a842adb0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "https://drsdrive.anevay.de/owncloud/remote.php/webdav/" to check remote ETag
02-23 09:09:39:925 0x7fc0a842adb0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://drsdrive.anevay.de/owncloud" + "" "OCC::Folder"

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment] 2016-02-23 08:23
How many files/folders?
I'm assuming duplicate of https://github.com/owncloud/client/issues/3064

**Closed by guruz** 2016-02-23 08:23 UTC

**Comment by donnoc** [comment] 2016-02-23 08:49
Oh, there are a lot of folders. Maybe it’s the same.


Mit freundlichen Grüßen
Artur Hübert
