### ISSUE TITLE
Files shared read-only are not marked read-only on the filesystem

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3244] opened 2015-05-19 07:35 UTC
### Steps to reproduce
1. Open your Owncloud Web client, with the user1
2. Create a new File, called aaa
3. Share the Folder aaa with other user (user2)
4. Unchecked the option 'Edit'
5. Open your Owncloud Desktop client, with the user2
6. Go to Open Folder "ownCloud"
7. Wait for it to sync
8. Open the File aaa Edit and Write something
9. Save the File aaa
10. Wait for it to sync 

### Expected behaviour
You can't Edit and Write the File aaa because you have unchecked the opcion Edit

### Actual behaviour
When you Edit and Write the File aaa with the user2, Is not sync, it is appears an error
![screen shot 2015-05-19 at 09 41 14](https://cloud.githubusercontent.com/assets/12032058/7697820/770ba600-fe0b-11e4-8ae6-ceec44933a45.png)

![screen shot 2015-05-19 at 09 27 12](https://cloud.githubusercontent.com/assets/12032058/7697600/73efbf12-fe09-11e4-9915-c4a2bdf4b6ff.png)

### Server configuration
Version Desktop:
Version 1.8.2 (build 2369)

Web server: 
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Comment by Dianafg76** [comment] 2015-05-19 07:48
LOGS

```05-19 09:41:10:106 0x7ffdc340f580 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 202 "Error downloading http://XXX/remote.php/webdav/aaa.txt - server replied: Forbidden"
05-19 09:41:10:106 0x7ffdc340f580 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished() QUrl( "http://XXX/remote.php/webdav/aaa.txt" ) FINISHED WITH STATUS 202 "Error downloading http://XXX/remote.php/webdav/aaa.txt - server replied: Forbidden" QVariant(int, 403) QVariant(QString, "Forbidden")
05-19 09:41:10:106 0x7ffdc340f580 OCC::PropagateUploadFileQNAM::slotPutFinished: "<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
<s:message/>
</d:error>
"
05-19 09:41:10:107 0x7ffdc340f580 OCC::SyncJournalErrorBlacklistRecord::update: Fatal Error condition 403 , maximum blacklist ignore time!
05-19 09:41:10:107 0x7ffdc340f580 OCC::SyncJournalErrorBlacklistRecord::update: blacklisting "aaa.txt" for 86400 , retry count 1
05-19 09:41:10:107 0x7ffdc340f580 OCC::SyncJournalDb::updateErrorBlacklistEntry: set blacklist entry for "aaa.txt" 1 "Error downloading http://XXX/remote.php/webdav/aaa.txt - server replied: Forbidden" 1432021270 86400 1432021267 "937910ba40172b396ea26dd4e7169609"
05-19 09:41:10:108 0x7ffdc340f580 OCC::SyncEngine::slotJobCompleted: void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem &) "aaa.txt" INSTRUCTION_SYNC 2 "Error downloading http://XXX/remote.php/webdav/aaa.txt - server replied: Forbidden"
05-19 09:41:10:112 0x7ffdc340f580 OCC::SocketApi::sendMessage: SocketApi: Sending message: "STATUS:ERROR:/Users/Diana/ownCloud/aaa.txt"
05-19 09:41:10:116 0x7ffdc340f580 OCC::SyncJournalDb::walCheckpoint: void OCC::SyncJournalDb::walCheckpoint() took 0 msec
05-19 09:41:10:116 0x7ffdc340f580 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit "All Finished." 
05-19 09:41:10:117 0x7ffdc340f580 OCC::SyncEngine::finalize: CSync run took 558
05-19 09:41:10:117 0x7ffdc340f580 OCC::BandwidthManager::~BandwidthManager: virtual OCC::BandwidthManager::~BandwidthManager()
05-19 09:41:10:117 0x7ffdc340f580 OCC::Folder::slotSyncFinished: -> SyncEngine finished without problem.
05-19 09:41:10:118 0x7ffdc340f580 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took 0 Milliseconds.
05-19 09:41:10:118 0x7ffdc340f580 OCC::sendOsXUserNotification: void OCC::sendOsXUserNotification(const QString &, const QString &) "Sync Activity" "aaa.txt could not be synced due to an error. See the log for details."
05-19 09:41:10:118 0x7ffdc340f580 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result: 3
05-19 09:41:10:118 0x7ffdc340f580 OCC::Folder::slotSyncFinished: ** error Strings: ("aaa.txt: Error downloading http://XXX/remote.php/webdav/aaa.txt - server replied: Forbidden")
05-19 09:41:10:119 0x7ffdc340f580 OCC::Folder::slotSyncFinished: * owncloud csync thread finished with error
05-19 09:41:10:119 0x7ffdc340f580 OCC::Folder::slotSyncFinished: the last 1 syncs failed
05-19 09:41:10:119 0x7ffdc340f580 OCC::SocketApi::sendMessage: SocketApi: Sending message: "STATUS:ERROR:/Users/Diana/ownCloud/"
05-19 09:41:10:119 0x7ffdc340f580 OCC::SocketApi::sendMessage: SocketApi: Sending message: "UPDATE_VIEW:/Users/Diana/ownCloud/"
05-19 09:41:10:120 0x7ffdc340f580 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message: OCC::Folder(0x7ffdc5961580) with name "ownCloud"
05-19 09:41:10:120 0x7ffdc340f580 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder "ownCloud" : "Error"
05-19 09:41:10:145 0x7ffdc340f580 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString &, QLocalSocket *) "/Users/Diana/ownCloud/.owncloudsync.log"
05-19 09:41:10:145 0x7ffdc340f580 OCC::SocketApi::sendMessage: SocketApi: Sending message: "STATUS:IGNORE:/Users/Diana/ownCloud/.owncloudsync.log"
05-19 09:41:10:322 0x7ffdc340f580 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for "ownCloud"```

**Comment by dragotin** [comment] 2015-05-19 08:49
This sounds like a regression. The wanted behaviour is: The file coming from a non editable share should be set to read only on the harddisk of the client. If that is changed manually to rw again (which is of course possible) the client should not even try to upload it, but  report that the change can not be uploaded, restore the original file and move the local change to a conflict file.

**Comment by ckamm** [comment] 2015-05-20 08:04
@dragotin I don't think we set non-editable shares to read-only on the local file system yet. Is this something that'd be ok to add to 1.8?

I'll try to reproduce the problem with the rename-to-conflict-and-revert behavior. That one should definitely exist.

**Comment by ckamm** [comment] 2015-05-21 07:42
I could reproduce the problem with the client trying to upload new data to a read-only share.

**Comment by ckamm** [comment] 2015-05-21 07:55
In my reproduction with server 8.0.2, it's caused by a server issue: it reports the read-only share's permissions as `<oc:permissions>SRDNVW</oc:permissions>`, including the W. I'll now retry with 8.0.3.

**Comment by ckamm** [comment] 2015-05-21 08:04
Same response with server 8.0.3.

**Comment by ckamm** [comment] 2015-05-21 08:57
I've moved the server part to owncloud/core#16492.

**Comment by ckamm** [comment] 2015-05-27 13:38
A discussion with @guruz @ogoffart @PVince81 has shown that changing local file permissions based on server permissions has several complications:
* Changes in share permission need to be propagated to the client so it can adjust the file permissions. Currently changing share permissions does not trigger an etag change. This requires a server change.
* When a file that used to be read-only becomes writable, we need to be careful about which write permissions are added. Enabling the write permissions that are in umask could be the right approach.

**Comment by MTRichards** [comment] 2015-06-19 20:33
Same issue:
https://github.com/owncloud/client/issues/3137

**Comment by ckamm** [comment] 2015-07-01 08:59
Moved to 2.1 because the server dependencies will be in 8.2.

**Comment by MTRichards** [comment] 2015-08-10 13:48
>Changes in share permission need to be propagated to the client so it can adjust the file permissions. Currently changing share permissions does not trigger an etag change. This requires a server change.

If we have a true dependency on the server side, not sure this can be added for 2.1.

**Comment by ckamm** [comment] 2015-10-29 09:25
I've tested this on 8.2 and it does indeed work, the etag changes on share-permission change and the client notices and updates the permissions stored in the database.

* 'can share': +R on file and folder
* 'create': +CK on folder
* 'change': +W on file
* 'delete': +DNV on file

That means we can now watch the W permission of a file and adjust the local permissions to reflect that.

**Comment by ogoffart** [comment] 2015-10-29 10:42
maybe iff account()->serverVersionInt >= 0x080200

**Comment by ckamm** [comment] 2015-11-04 14:56
@ogoffart Excellent point!

**Comment by ckamm** [comment] 2015-11-10 10:06
Current status:
* Files shared read-only are correctly marked as such in the filesystem
* Permission updates on the server are reflected in the local permissions
* There's a server bug that causes file-shares to not update their permissions correctly owncloud/core#20426
* We should also adjust the permissions of shared directories where possible

**Comment by ckamm** [comment] 2015-11-10 10:31
Setting shared-folder permissions:
* Windows has no equivalent
* With unix-like permissions 'w' on folders is equivalent to CK on the folder and DNV on each contained file. So a correct solution would need to check the permissions of all contained files. It also introduces problems with downloads, as we can no longer create files in the folder.

**Comment by Dianafg76** [comment] 2015-11-11 09:23
I tested this issue and appears the same error: 
![screen shot 2015-11-11 at 10 19 22](https://cloud.githubusercontent.com/assets/12032058/11087822/ca68a104-885d-11e5-8bb4-3beb2f176945.png)

LOG:
```
11-11 10:14:37:623 0x7fde1cd57cf0 csync_walker: file: ownclouds://docker.oc.solidgear.es:xxx/remote.php/webdav/aaafile.txt [file_id=00005266ocmfgtuqq44w size=5]
11-11 10:14:37:624 0x7fde1cd57cf0 _csync_detect_update: Database entry found, compare: 1447233195 <-> 1447233195, etag: 19fa12fa522bcb02963945aec77de120 <-> 19fa12fa522bcb02963945aec77de120, inode: 0 <-> 4767171, size: 5 <-> 5, perms: SRDNVW <-> SRDNVW, ignore: 0
```
```
11-11 10:14:37:657 0x7fde1a5318c0 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud1" :  "Sync Running"
11-11 10:14:37:657 0x7fde1a5318c0 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem &, const OCC::PropagatorJob &) "aaafile.txt" INSTRUCTION_ERROR 6 "The item is not synced because of previous errors: Error downloading https://docker.oc.solidgear.es:53166/remote.php/webdav/aaafile.txt - server replied: Forbidden (Sabre\DAV\Exception\Forbidden)"
```

Desktop v ownCloud-2.1.0.2865-nightly20151110.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by Dianafg76** [comment] 2015-11-11 10:29
With Dektop v ownCloud-2.1.0.2871-nightly20151111.pkg I can see the same error

**Comment by ckamm** [comment] 2015-11-11 13:44
@Dianafg76 You are running into the server problem owncloud/core#20426 of the permissions not being advertised correctly. Try sharing a directory instead.

**Closed** 2015-11-19 16:15 UTC
Labels: bug, sev2-high, Sharing

**Comment by KUTlime** [comment] 2016-01-11 23:26
I believe that I have an opposite issue with version 2.1.0 build 5683.
Recently, I receive many sync error because Owncloud marks the file with read only permission and after that it cause the sync error. For example:
PC 1 - I open some PDF file.
PC 2 - Owncloud reports the sync error because it can't synchronize the PDF file which is already present on PC 2, but not it have a read-only permission.
Similar problems with files with codes. Really annoying.

It is related or it is some other bug?
