### ISSUE TITLE
Unselected folder content is synced if child folder is selected to be synced

### ISSUE THREAD

**Issue by sanquarius** [owncloud/client#4594] opened 2016-03-22 07:39 UTC
### Expected behaviour
As an owncloud user I would like to sync a child folder of an unselected folder without the parents folder content beeing synced.

### Actual behaviour
If I have a sync config where a folder's child folder is configured to be synced, the content (files) of the not selected folder is also synced

### Steps to reproduce
1 create the following structure 

/folder a
/folder a/file a
/folder a/folder b
/folder a/folder b/file b

2 select folder b to be synced, but folder a is unselected (folder a should not be synced)

3 sync will sync folder b, file b and file a (file a should not be synced at all)

### Server configuration
Operating system:
Debian 7

Web server: 
Apache 2.4

Database:
Mysql 

PHP version:
5.4

ownCloud version:
8.2.2

Storage backend:
Flat filesystem

### Client configuration
Client version:
2.1.1

Operating system:
Windows/Mac

OS language:
German/English

Installation path of client:
not relevant

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment] 2016-03-23 14:14
Thanks. Looks like a duplicate of https://github.com/owncloud/client/issues/3632 

Idea to remove this confusion: https://github.com/owncloud/client/issues/3840
Another research state fix: https://github.com/owncloud/client/issues/4341

FYI @MTRichards

**Closed by guruz** 2016-03-23 14:14 UTC
