### ISSUE TITLE
[Windows] Problems syncing folders with space at end

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#3286] opened 2015-05-27 13:20 UTC
### Steps to reproduce:

1.- Create a folder over the webUI and at the end leave an empty space.
2.- Sync with the Windows Client  1.8.1
3.- Folder will be shown in the selective sync, but wont be downloaded.

@MorrisJobke @dragotin @danimo

**Comment by Kawohl** [comment] 2015-05-28 07:56
I was able to reproduce this Error with the Windows Client. I produced two Folders with space at the end. So don´t get confused. 

05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK+SWM:C:\Users\John\ownCloud\Photos (2)"
05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QLocalSocket*) "C:\Users\John\ownCloud\space at the end"
05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::fileStatus: OO File  "C:/Users/John/ownCloud/space at the end"  is not existing
05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\John\ownCloud\space at the end"
05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QLocalSocket*) "C:\Users\John\ownCloud"
05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\John\ownCloud"
05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QLocalSocket*) "C:\Users\John\ownCloud\SPace at the end2 \"
05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::fileStatus: OO File  "C:/Users/John/ownCloud/SPace at the end2 "  is not existing
05-28 09:48:47:808 0x67e7b0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\John\ownCloud\SPace at the end2 \"
05-28 09:48:47:823 0x67e7b0 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, QLocalSocket*) "C:\Users\John\ownCloud\SPace at the end2"
05-28 09:48:47:823 0x67e7b0 OCC::SocketApi::fileStatus: OO File  "C:/Users/John/ownCloud/SPace at the end2"  is not existing
05-28 09:48:47:823 0x67e7b0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\John\ownCloud\SPace at the end2"

**Comment by ogoffart** [comment] 2015-06-01 08:35
The windows operating system do not allow folder with trailing spaces. Such folder cannot be downloaded on windows and there should be an error explaining it.

**Comment by Dianafg76** [comment] 2015-06-03 07:41
@cdamken 
Could try the with the latest client version, v 1.8.2?
You may download it from:
http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5138-nightly20150603-setup.exe

Thanks!!

**Comment by cmarrero** [comment] 2015-07-08 19:56
Hi,
Same error with version 1.8.3 and owncloud 8.0.4, if the folder name ends with space the windows client does not synchronize the folder, it works well in mac .

From the log:
07-08 14:39:42:174 0x3d5cb40 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: operaciones/TMP 2015/BOC TMP 2015/Cronograma Cronograma Sistema Ground BOC.xlsx

Note the space between Cronograma Cronograma

It should be   file: operaciones/TMP 2015/BOC TMP 2015/Cronograma /Cronograma Sistema Ground BOC.xlsx


Regards

**Comment by guruz** [comment] 2015-10-02 15:38
Let's have this show up in the activity log (sync protocol) then..

**Comment by ogoffart** [comment] 2015-10-26 15:14
It shows as ignored in the acrivity log on windows:   `Filename contains invalid characters that can not be synced cross platform.`

@cmarrero  Version 1.8.3 is outdated, please update to 2.0.2

Windows do not allow files with spaces at the end so it is normal that you get error when syncing these.

It should not appear in the selective sync anymore because it is ignored.
The SocketAPI bug should also be fixed in 2.1.
So this issue should be fixed.

**Comment by Dianafg76** [comment] 2015-10-27 12:32
I tested this issue, and for my is working OK
Desktop v ownCloud-2.1.0.5584-nightly20151027-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed

**Closed by Dianafg76** 2015-10-27 12:32 UTC
Labels: approved by QA, bug
