### ISSUE TITLE
[OS X] GUI not show Chinese (Taiwan) language. ver 1.7.1

### ISSUE THREAD

**Issue by mktsai** [owncloud/client#2716] opened 2015-01-19 13:55 UTC
I remove ver 1.6.3 of client app, then install ver 1.7.1(build 1655).

All Chinese font look like block(screenshot below). but 1.6.3 was works great for me.

screenshot:
http://i.imgur.com/0v2UjX1.png

Operating system:
Mac OS X 10.10.1

ownCloud version:
ownCloud 7.0.2 (stable)

Client version:
1.7.1

Operating system:
Mac OS X 10.10.1

OS language:
Traditional Chinese

Installation path of client:
Default

**Comment by guruz** [comment] 2015-01-19 15:43
Thanks!

@danimo why could this regress?

closing because duplicate of https://github.com/owncloud/client/issues/2640

**Closed by guruz** 2015-01-19 15:43 UTC
