### ISSUE TITLE
Sync Client: Trying to continuously upload read only files...Read only folder troubles?

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#2942] opened 2015-03-11 02:16 UTC
Now I have an interesting problem syncing with ownCloud 8.0.2.

Windows 7
1.7.1

Nothing new here, this is just an ordinary sync run with the client. It seems the read only is being respected because the files don't write, but the files should be the same, since they were just downloaded.

The sync client is eternally telling me "Not allowed to upload because it is read only on the server". Which is fine, but why isn't it keeping itself from syncing, since these files all came from the server?

It comes through like this:
![untitled](https://cloud.githubusercontent.com/assets/1818977/6589213/c9727a10-c772-11e4-8009-5813452f545a.png)

and
![untitled](https://cloud.githubusercontent.com/assets/1818977/6589185/79016a96-c772-11e4-8adc-0a40ff514034.png)

**Comment by dragotin** [comment] 2015-03-11 10:50
@ckamm could you doublecheck with 1.8.0?

**Comment by ckamm** [comment] 2015-03-11 11:42
@MTRichards Can you give me more info? Here's what I tried with the 1.8 branch and server 8.0.2:
* Share a folder readonly with another user
* Sync that as the other user

And that worked fine. If I touch a file in that folder, I get the "Not allowed to upload this file..." message and the file is restored.

Could it be that this is DST related and something makes the client think there are local changes?

**Comment by ckamm** [comment] 2015-03-11 11:44
Ooh, I tried on linux, will try again on windows 7.

**Comment by ckamm** [comment] 2015-03-11 11:52
Also works on Windows 7 for me.

**Comment by ckamm** [comment] 2015-03-11 12:00
And I can't reproduce it even if I set my clock to eastern time without DST, download files, switch to DST and try to sync again. @MTRichards what filesystem are you syncing to? Is it regular NTFS?

**Comment by ckamm** [comment] 2015-03-11 12:06
Since 1.7.1 didn't have the 'ignore one hour differences' hack and 1.8 does. There's a good chance this has been addressed.

**Comment by ckamm** [comment] 2015-03-11 12:54
But I can also not reproduce the problem in 1.7.1 by downloading, toggling DST, and syncing again.

**Comment by dragotin** [comment] 2015-03-18 10:50
I think this is the result of the DST problem, which means: Windows changes the mod time on the DST change, the client thinks the file has changed and tries to upload, which fails because of the read only flag. 
The root cause is fixed in 1.8.0, we wont consider the modtime change that has exactly one hour difference NOT longer as change reason, unless the size of the file has changed.

Closing this here.

**Closed by dragotin** 2015-03-18 10:50 UTC
Labels: bug, Needs info
