### ISSUE TITLE
Sending User Asynchronous Notifications from the Admin

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#3733] opened 2015-09-02 15:03 UTC
Notifications
As an admin, I want to be able to send notifications from the server to any owncloud client (desktop, client, mobile) so that I can send messages, and receive confirmation, from users of the ownCloud system

Note: this has several parts: desktop, server, web and mobile

Acceptance Criteria:
- A new app on the server (system notifications) can be enabled by the administrator
- When this app is enabled, the clients ping the server on every sync run to see if a new system wide notification is waiting
- If a new notification is waiting, the client downloads the message XML, parses the error, and displays it in a window for the desktop client
- Notifications can be of 2 types initially: those requiring acceptance and those that are simply push notifications
- A simple push notification simply displays the message set by the administrator
- A request for yes / no response is not necessary in this version of ownCloud client, but will be needed at a later date
- If the web client, it is posted in a new popup; if mobile, a new message tag is added to a new system messages view.

**Comment by guruz** [comment] 2015-09-06 18:54
FYI @nickvergessen

**Comment by nickvergessen** [comment] 2015-09-07 06:53
The server side will be done with https://github.com/owncloud/notifications and https://github.com/nickv-oc/announcementcenter
So nothing special needs to be done on the client. Just display and have the actions of the normal notifications.

**Comment by ogoffart** [comment] 2015-10-21 16:23
Is there any documentation of the API?
A running server with that installed so we can test would be nice.

**Comment by nickvergessen** [comment] 2015-10-21 19:01
This is currently on hold, until the activity API is settled, ref https://github.com/owncloud/activity/issues/405 . Notifications will mostlikly use a similar mechanism.

**Comment by nickvergessen** [comment] 2015-11-25 07:32
The docs for the OCS API endpoint for 9.0 are now done and settled:
https://github.com/owncloud/notifications/blob/master/docs/ocs-endpoint-v1.md

Master branch of the notifications app already gives that output.
As described above it can be used together with the announcement center app.
Just enable both in the apps, make an announcement as an admin and then
read from the OCS endpoint as a different user.

**Comment by dragotin** [comment] 2016-03-03 07:23
Affected by owncloud/core/22786

**Comment by dragotin** [comment] 2016-04-04 14:15
pull request #4567 was merged.

@carlaschroder we need documentation about that, just as a reminder. I will provide input in the wiki.

**Comment by SergioBertolinSG** [comment] 2016-04-08 10:44
Works in OS X (10.11). Version 2.2.0-nightly20160408 (build 3250)
Works in Windows 10. 2.2.0-nightly20160408 (build 5980)

Not sure if checking this on mobile has been done before, has it @jesmrec ?

**Comment by SergioBertolinSG** [comment] 2016-04-08 11:35
Notifications from experimental app 'announcements' are not being shown by the desktop client (both windows & mac). @dragotin are this expected to appear?

**Comment by nickvergessen** [comment] 2016-04-08 11:45
Well it worked for me when I tested it two days ago

**Comment by SergioBertolinSG** [comment] 2016-04-08 12:31
Ok, sorry, notifications appeared after a while in mac os, in windows it need a restart. But activity app was required to read those notifications. Filed here: https://github.com/owncloud/client/issues/4651

**Comment by dragotin** [comment] 2016-04-08 14:13
Yes, the notifications from the announcements app need to show up. Probably they did not for you because activities were disabled. I need to address that.

**Comment by carlaschroder** [comment] 2016-04-12 23:08
Thanks @dragotin.

**Comment by ckamm** [comment] 2016-04-14 08:49
Testing on linux: Works!

I got a tray message about a new remote share, but when I opened owncloud I had to manually navigate to Activity/Server Activity. If I hadn't known where to find it, I might have been confused.

I couldn't get the announcement center notifications to work server-side, unfortunately.

**Comment by mcastroSG** [comment] 2016-05-05 12:46
##Notifications

<br>
 
Hi hi:

Test Case ID | Test case     | Steps   | Expected behaviour | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Notifications - Remote share | 1.- As user1 share a folder with user2 using federated sharing <br> | At desktop client connected as user2 a new notification is shown at server activity tab and we are able to select Accept or Decline shared file.<br> A bubble alert appears including notification.<br> | ✅ 
2 | Notifications - Announcement | 1.- As admin enable Announcement Center App <br> 2.- As admin access to Announcements menu and write a new announcement.<br>| At any client desktop connected to this sever a new notification is shown at server activity tab that could be removed clicking OK button <br> A bubble alert appears including notification.<br>| ✅ 

OSX:

Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0-nightly20160504 (build 3331)

OSW:

Client OS: W81
Client Version: Version 2.2.0-nightly20160505 (build 6054)
OSLinux

Client OS: Ubuntu 14.04 LTE
Client Version: Version 2.2.0nightly201654 (build 1587)

**Closed by mcastroSG** 2016-05-05 12:46 UTC
Labels: enhancement - proposed, gold-ticket, ReadyToTest
