### ISSUE TITLE
sync everything is less than selected sync

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3469] opened 2015-07-16 20:55 UTC
The download estimate near the 'Sync everything ...' button is too low.
It shows me 514MB, but there are several GB that I know of, on this server.
After using 'Choose what to sync' and disabling ca 2 GB worth of subfolders, 
The estimate near 'Choose what to sync' shows 1.8GB -- that seems to be accurate.

Still there is a total of 514 MB shown.

Seen with 1.8.3, if that matters.

**Comment by ogoffart** [comment] 2015-07-17 12:30
I think the problem is what the server reports.  The server does not always reports the right results for folders in external storage.

**Comment by danimo** [comment] 2015-07-17 12:34
@ogoffart Then let's file an issue in core about it. Either this gets fixed in core, or we get guidiance on how to deal with it. Can you create that issue and explain the situations in which you think it miscalculates? I remember problems with shared folders not being accounted for properly.

**Comment by jnweiger** [comment] 2015-07-17 12:40
I believe it is about how to count shared data. 
My quota report says that I am using 514MB out of 1024MB, which matches the 'sync everything' value.
This seems to exclude anything that was shared with me.

**Comment by dragotin** [comment] 2015-07-20 08:37
Was'nt there a server setting to either include the shared data in quota or not? @DeepDiver1975 can you enlighten us?

**Comment by dragotin** [comment] 2015-07-29 10:02
Moving since server involved and no progress.

**Comment by ogoffart** [comment] 2015-08-31 16:12
Closing since server invloved and no progress

**Closed by ogoffart** 2015-08-31 16:12 UTC
Labels: bug, Server Involved
