### ISSUE TITLE
Shared folder deleted when ldap server is down

### ISSUE THREAD

**Issue by frankuit** [owncloud/client#2516] opened 2014-11-19 09:37 UTC
Hi All,

server: Debian wheezy 64 bit, running apache, owncloud 7.0.2 and mysql
clients affected: mirall windows 1.6.4.

last week I've had an ldap server outage, so some users got a popup asking for their password.
the ones that entered their password and that had access to shared folders from other users, lost the content of those folders.

workaround seems to be: 
close owncloud client
move owncloud data folder to owncloud-old
create new empty owncloud data folder
start owncloud client
let it all dload.

Any thoughts ?
Thanks,
Frank

**Comment by guruz** [comment] 2015-06-24 15:23
@blizzz @PVince81 What's the state of this? Are newer oC server versions running a proper HTTP code to make the sync client ignore the specific folder in discovery?

**Comment by PVince81** [comment] 2015-06-24 15:26
I'm not aware of any such change.
The only cases where 503 is returned is for federated shares.

**Comment by PVince81** [comment] 2015-06-24 15:28
So if I understand well this is about shares.

Is this "ldap_user1" shares with "ldap_user2" or rather "ldap_user1" shares with "local_user2" ?
Because as @blizzz said if LDAP is down, authentication would fail anyway.

But if another local (non-LDAP) user can authenticate, not sure what happens for folder that were shared from a LDAP user. I'd expect it to work still, as no authentication is needed for the LDAP user.

Then there's the race condition possibility: what if sync/discovery has already started, and in the middle of the PHP request, the LDAP server goes down ?

**Comment by blizzz** [comment] 2015-06-24 16:54
> Is this "ldap_user1" shares with "ldap_user2" or rather "ldap_user1" shares with "local_user2" ?
Because as @blizzz said if LDAP is down, authentication would fail anyway.

Meanwhile we had the cases that  LDAP connections got lost in-between (shaky proxies). That could have been a problem, when attempting to read more information from LDAP. Latest point releases are safe and die with some 5xx.

> But if another local (non-LDAP) user can authenticate, not sure what happens for folder that were shared from a LDAP user. I'd expect it to work still, as no authentication is needed for the LDAP user. 

Throws 5xx now as well, if the user's file sys cannot be mounted. If it can, no problem.

> Then there's the race condition possibility: what if sync/discovery has already started, and in the middle of the PHP request, the LDAP server goes down ?

Either works thanks to caching for a while, otherwise 5xx, also by now.

**Comment by dragotin** [comment] 2015-06-25 07:26
@Dianafg76 do you think you can re-test this issue?

**Comment by Dianafg76** [comment] 2015-06-25 09:47
@dragotin I tested this issue, and now happen
### Steps to reproduce
1. I have an LDAP server, with some user
2. Entered with the user1 in Oc server (with Ldap)
3. The user 1 create a new folder, call "New folder for share"
4. Go to the folder "New folder for share", and download some files
5. Share this folder with other user (user2) with Ldap
6. throw down the Ldap server

### Expected behaviour
Tell us what should happen

### Actual behaviour
I have two errors:
1. If you go to the user1, and click in the "New folder for share", the name of the folder doubles and does nothing

![screen shot 2015-06-25 at 11 40 07](https://cloud.githubusercontent.com/assets/12032058/8351614/fd6486f0-1b2e-11e5-9917-b37d88e21afa.png)

2. And appears the error 500 
![screen shot 2015-06-25 at 11 44 53](https://cloud.githubusercontent.com/assets/12032058/8351717/b4fba370-1b2f-11e5-8356-a00be3c518f3.png)


### Server configuration
DESKTOP v ownCloud-1.8.3.2465-nightly20150625.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.7","versionstring":"8.1 RC1","edition":"Enterprise"}

**Comment by dragotin** [comment] 2015-06-25 09:56
wow, @blizzz help us please.

**Comment by blizzz** [comment] 2015-06-25 14:39
Waiting for test with master branch as announced in  https://github.com/owncloud/core/issues/17170#issuecomment-115273334

**Comment by Dianafg76** [comment] 2015-08-05 08:09
@blizzz Hello, I teste this issue again, and now happen
### Steps to reproduce
1. I have an LDAP server, with some user
2. Entered with the user1 in Oc server (with Ldap)
3. The user 1 create a new folder, call "New folder for share"
4. Go to the folder "New folder for share", and download some files
5. Share this folder with other user (user2) with Ldap
6. throw down the Ldap server


### Actual behaviour
1. If you go to the user1, and click in the "New folder for share", appears error in the SERVER
![screen shot 2015-08-05 at 10 01 56](https://cloud.githubusercontent.com/assets/12032058/9081009/23aa3266-3b59-11e5-9e66-01a45d3e8222.png)
2. In DESKTOP client, appears this error:

![screen shot 2015-08-05 at 09 56 51](https://cloud.githubusercontent.com/assets/12032058/9081034/4cc9f9e2-3b59-11e5-925d-062ad983c10f.png)

3. And then press F5 in the SERVER, is happening:

![screen shot 2015-08-05 at 10 06 02](https://cloud.githubusercontent.com/assets/12032058/9081082/ab57d0b0-3b59-11e5-8716-eca4af9ed7aa.png)


### Server configuration
DESKTOP vownCloud-1.8.4.2598-nightly20150805.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1","edition":""}

**Comment by ogoffart** [comment] 2016-01-19 10:53
Closing old bug.
This seems to be a server bug, so if this is still relevant, please open in the server bug tracker.

**Closed by ogoffart** 2016-01-19 10:53 UTC
Labels: Server Involved
