### ISSUE TITLE
Desktop client 1.7.1 crash on Windows Server 2012R2

### ISSUE THREAD

**Issue by esosan** [owncloud/client#2883] opened 2015-02-24 10:56 UTC
Hi All!
I have a strange problem on desktop client installed on Windows Server 2012: once a day the client crashes with a generic message "Runtime Error". Between the crashes the client works properly.

On the OC server I have no problem or error.

I already googled but I found nothing about. Any idea about on how to solve or some workaround?

The client is a 1.7.(14382) running on windows server 2012 R2.
The server is OC8 on linux.

thank you in advance, Davide

**Comment by jturcotte** [comment] 2015-02-25 16:38
@esosan Thanks for the report, in order to trying finding the cause, could you try two things?

- Could you try with the 1.8-beta version of the client and say if you also get the error? You can get it from https://owncloud.org/install/#testing
- Please try giving us more info about the runtime error. It might be slightly different on Server 2012 but you should be able to find a summary afterward by doing:
    - Go in ControlPanel/AdministrativeTools/EventViewer
    - Try to find an event related to the error, possibly in "Windows Log/System" and with an Information or Warning level
    - Right click on the event from the list, and do Copy/Copy Details as Text
    - Paste it here as a comment

If you can't find the summary there, a screenshot of the error message would also be helpful.

**Comment by esosan** [comment] 2015-02-25 17:41
@jturcotte Hi, thank you for the supporting.

Below the only entry which I think is related to the crash (the time matches). this one is for version 1.7.1.

Now I will install the new version, I will send you the new log entry soon as possible.

```Log Name:      System
Source:        Service Control Manager
Date:          25.02.2015 09:56:55
Event ID:      7036
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      SERVER.xxx.lan
Description:
The Windows Error Reporting Service service entered the stopped state.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="16384">7036</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2015-02-25T08:56:55.383647300Z" />
    <EventRecordID>10789</EventRecordID>
    <Correlation />
    <Execution ProcessID="576" ThreadID="2632" />
    <Channel>System</Channel>
    <Computer>SERVER.xxx.lan</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">Windows Error Reporting Service</Data>
    <Data Name="param2">stopped</Data>
    <Binary>5700650072005300760063002F0031000000</Binary>
  </EventData>
</Event>```

**Comment by jturcotte** [comment] 2015-02-25 18:40
@esosan Thank you, that error: "The Windows Error Reporting Service service entered the stopped state" means that the crash happened somewhat 2 minutes before that event, when the Error Reporting Service was automatically started, possibly to look at the ownCloud failure.

If you can't see any event 1-2 minutes before this one (maybe in other panes of the event viewer) then it would be great if you could take a screenshot so that we can have some details about the error.

**Comment by esosan** [comment] 2015-02-26 07:41
@jturcotte , I found another entry much more relevant to the problem (client v1.7.1).
Yesterday I installed version 1.8 and up to now I have not had crash...


```- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2015-02-25T08:54:55.000000000Z" /> 
  <EventRecordID>4156</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>SERVER.bgnt.lan</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>owncloud.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5492c052</Data> 
  <Data>libstdc++-6.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>392a391b</Data> 
  <Data>40000015</Data> 
  <Data>0001bfc8</Data> 
  <Data>584</Data> 
  <Data>01d05008becdf6d0</Data> 
  <Data>C:\Program Files (x86)\ownCloud\owncloud.exe</Data> 
  <Data>C:\Program Files (x86)\ownCloud\libstdc++-6.dll</Data> 
  <Data>f77302cb-bccb-11e4-80c4-645106f90069</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event> ```

**Comment by jturcotte** [comment] 2015-02-26 15:32
That looks much better thanks, unfortunately we don't have debug symbols for libstdc++-6.dll so I can't extract anything from those offsets.

Let me know first if you can reproduce the crash with 1.8 as well.
Then we can see if you could try to keep ownCloud running in MinGW's gdb to get a proper stack trace of the crash.

**Comment by guruz** [comment] 2015-03-13 15:46
@esosan With 1.8rc1 being out I'm going to close this.
Please comment if the bug re-appears.

**Closed by guruz** 2015-03-13 15:46 UTC
Labels: bug, Needs info
