### ISSUE TITLE
Windows client crash if sync folder not found

### ISSUE THREAD

**Issue by atomiful** [owncloud/client#8370] opened 2021-01-18 13:55 UTC
### Expected behaviour
Owncloud Windows client starts normally on Windows startup even if sync folder is not available on startup.

### Actual behaviour
Owncloud Windows client crashes if sync folder is not available.

### Steps to reproduce
1. Create a virtual disk .vhdx and enable Bitlocker
2. Create virtual file sync on that mounted virtual disk
3. Close Owncloud + Unmount virtual disk OR reboot computer
4. Start Computer OR Start Owncloud client
5. The application crashes until I mount the sync folder (virtual drive in my case)

### Client configuration
Client version:
2.7.4 (build 2934)
Operating system:
Windows 10 20H2
OS language:
French

### Logs
01-18 14:31:15:080 [ info gui.application ]:	"################## ownCloud locale:[fr_FR] ui_lang:[] version:[2.7.4 (build 2934)] os:[Windows 10 (10.0)]"
01-18 14:31:15:080 [ info gui.application ]:	Using "fr_FR" translation
01-18 14:31:15:080 [ info gui.application ]:	VFS windows plugin is available
01-18 14:31:15:080 [ info gui.application ]:	VFS suffix plugin is available
01-18 14:31:15:080 [ debug gui.socketapi ]	[ OCC::SocketApi::SocketApi ]:	creating "//./pipe" true
01-18 14:31:15:080 [ info gui.socketapi ]:	server started, listening at  "\\\\.\\pipe\\ownCloud-myuser"
01-18 14:31:15:080 [ info gui.folder.manager ]:	setting remote poll timer interval to 30000 msec
01-18 14:31:15:096 [ info gui.account.manager ]:	Restored:  0  unknown certs.
01-18 14:31:15:475 [ debug gui.activity ]	[ OCC::ActivitySettings::setNotificationRefreshInterval ]:	Starting Notification refresh timer with  300  sec interval
01-18 14:31:15:490 [ debug gui.updater ]	[ OCC::Updater::create ]:	QUrl("https://updates.owncloud.com/client/?version=2.7.4.2934&platform=win32&oem=ownCloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=&msi=true")
01-18 14:31:15:505 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
01-18 14:31:15:512 [ info gui.folder.manager ]:	Setup folders from settings file
01-18 14:31:15:513 [ warning sync.database ]:	Could not find a writable database path "O:/OWNCLOUD/.sync_c398303c13ec.db" "Le chemin d’accès spécifié est introuvable."
01-18 14:31:15:514 [ info plugins ]:	Created VFS instance from plugin "owncloudsync_vfs_win"
01-18 14:31:15:515 [ info sync.database ]:	Detected filesystem "" for "O:/OWNCLOUD/.sync_c398303c13ec.db"
01-18 14:31:15:515 [ warning gui.folder ]:	Broken symlink: "O:/OWNCLOUD/"
01-18 14:31:15:516 [ info sync.configfile ]:	Adding system ignore list to csync: "C:/Program Files/ownCloud/sync-exclude.lst"
01-18 14:31:15:540 [ warning sync.vfs.win ]:	Could not find StorageFolder for "O:\\OWNCLOUD" error: "WindowsError: ffffffff8007000f: Le lecteur spécifié est introuvable."
01-18 14:31:16:529 [ fatal default ]:	CfConnectSyncRoot: O:\OWNCLOUD error: WindowsError: ffffffff80070003: Le chemin d?acc?s sp?cifi? est introuvable.

**Comment by TheOneRing** [comment] 2021-01-18 14:05
Duplicate of https://github.com/owncloud/client/issues/8321

**Closed by TheOneRing** 2021-01-18 14:05 UTC
