### ISSUE TITLE
[Windows] Configuration assistant window doesn't adapt to Windows screen zoom

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/client#2587] opened 2014-12-06 07:59 UTC
### Expected behaviour
Configuration assistant should look fine no matter what overall screen scale I use.

### Actual behaviour
Configuration assistant cuts off text elements:
![owncloud-client-200percent](https://cloud.githubusercontent.com/assets/2631274/5326682/a8a00e98-7d25-11e4-9d96-72e081baaf01.png)
Just a side note: The general configuration dialog seems to do some adaptation to scale already - it looks fine.

### Steps to reproduce
1. On Windows 8.1 operating system, go to control panel, under Display choose to change size of text and other elements (not sure about exact wording, I have a german version running - there it's "Text und weitere Elemente vergrößern oder verkleinern") 
2. Set overall size to 200%
3. Start owncloud configuration assistant. It will look like in the picture shown above

### Server configuration
not relevant

### Client configuration
Client version: 1.7.0 build 4162
Operating system: Windows 8.1
OS language: German
Installation path of client: C:\Program Files (x86)\ownCloud

### Logs
not relevant

**Comment by guruz** [comment] 2015-07-29 11:17
Possibly related: https://github.com/owncloud/client/issues/3414

**Comment by guruz** [comment] 2016-01-04 11:45
@danimo With the commits you just pushed, is this fixed?
https://github.com/owncloud/client/commit/16030a61eb055733c5da1cf6c1bad4caef10a7f8

**Comment by jturcotte** [comment] 2016-01-14 12:54
Duplicate of #3414

**Closed by jturcotte** 2016-01-14 12:54 UTC
Labels: bug, Design & UX, sev3-medium
