### ISSUE TITLE
Changing %1 %2 in translations

### ISSUE THREAD

**Issue by vgezer** [owncloud/client#1696] opened 2014-04-18 21:27 UTC
Isn't it possible to replace the %1 and %2 in ts files?

I need to translate the following string as follows (percentage is before number and all available space is in the beginning):
~~~
<source>%1% of %2 in use</source>
<translation>%2&apos;ın %%1 kısmı kullanımda</translation>
~~~

But on Mirall I get something like:

`%2'ın 1 GB,5 kısmı kullanımda`

which should actually give:

`1 GB'ın %5 kısmı kullanımda` (5 percent)

How can I fix it?

**Comment by DeepDiver1975** [comment] 2015-12-07 11:33
@ogoffart is this issue still valid?

**Comment by ogoffart** [comment] 2015-12-07 13:22
I don't know.   @vgezer   IS that still an issue?

In any case i'm closing this issue because this is not a bug in the client, but a problem with transifex.

**Closed by ogoffart** 2015-12-07 13:22 UTC
Labels: L18n
