### ISSUE TITLE
[1.8.0] Window, Mac and Linux sync client: synchronisation error

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#2689] opened 2015-01-09 19:17 UTC
when I start the sync client (1.7.1 and 1.8.0)  for the first time on a Linux machine, I always get: "connection closed" and "operation canceled".

After some seconds it starts again, but fails two or three times before it synchronize everything. 

It suppose to be solved in https://github.com/owncloud/client/issues/2155 and https://github.com/owncloud/core/pull/11153

Tested with RHEL 6, oC 6.0.6 and Client 1.7.1

@MorrisJobke @dragotin @DeepDiver1975 

### Logs
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689

00001912

**Comment by dragotin** [comment] 2015-01-10 11:45
The client tries to download .zip or .ipa files (no idea what that is) and the connection is immediately closed. This is done by the server, so please investigate the server and proxy setup. We saw cases of nginx proxies that show this behaviour.

**Comment by danimo** [comment] 2015-01-10 11:56
@dragotin `.ipa` files are iOS files, stored in zip containers (renamed extension), so it's the same problem.

**Comment by cdamken** [comment] 2015-02-04 09:57
@danimo @dragotin Any news?

**Comment by cdamken** [comment] 2015-02-04 09:58
@MorrisJobke  Server involved, can you help me?

**Comment by MorrisJobke** [comment] 2015-02-04 14:15
@cdamken I just have the client log.


```
01-07 08:19:11:400 0x16a6820   ** error Strings:  ("Connection closed", "Operation canceled", "Operation canceled", "163 error/gca4ea-polybox-sync-error.log: Operation canceled", "CentOS-6.5-x86_64-minimal - Copy.iso: Operation canceled", "CentOS-6.5-x86_64-minimal.iso: Connection closed") 
01-07 08:19:11:401 0x16a6820     * owncloud csync thread finished with error 
01-07 08:19:11:401 0x16a6820 the last 1 syncs failed 
```

Server owncloud.log, apache log (error and access) would be nice. Also maybe the sever architecture is of interest.

**Comment by cdamken** [comment] 2015-02-05 14:34
@MorrisJobke I will ask for the logs

**Comment by dragotin** [comment] 2015-02-17 13:55
Looks like this problem is not longer hot. Closing here, please either reopen here or in the server repo (if turns out that its a server problem). Thanks.

**Comment by cdamken** [comment] 2015-03-10 11:56
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago)
PHP: PHP 5.3.3
HTTP: Apache/2.2.15 (Unix)
MySQL: 5.1.73 Source distribution

### LOG:
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689\New Log File.txt

**Comment by MorrisJobke** [comment] 2015-03-10 12:11
There are plenty of Sabre_DAV_Exception_NotFound, Sabre_DAV_Exception_Conflict, Sabre_DAV_Exception_UnsupportedMediaType, Sabre_DAV_Exception_Forbidden, Sabre_DAV_Exception_PreconditionFailed, Sabre_DAV_Exception_InsufficientStorage

144 Bind failed: 49: Invalid credentials
54 Sabre_DAV_Exception_InsufficientStorage
31 Sabre_DAV_Exception_PreconditionFailed
241 Sabre_DAV_Exception_Forbidden
109 Sabre_DAV_Exception_UnsupportedMediaType
447 Sabre_DAV_Exception_Conflict
1069 Sabre_DAV_Exception_NotFound
5 Sabre_DAV_Exception_BadRequest

Then just 6 lines left with some rename and access issues (nothing we should focus now)

@icewind1991 @DeepDiver1975 @PVince81 Which of the above are worth to look into?

**Comment by PVince81** [comment] 2015-03-10 13:32
Possibly all of them... some might be related to cancelled uploads though.

**Comment by cdamken** [comment] 2015-04-15 08:49
@DeepDiver1975 @icewind1991 @PVince81 @MorrisJobke could be a problem with the Storage?

I see in other logs a lot of errors like: 
```
[Sun Mar 29 17:10:35 2015] [error] [client X.X.X.X] File does not exist: /var/www/html/owncloud/img, referer: https://XXXX(Server)/index.php/settings/personal
```

**Comment by PVince81** [comment] 2015-04-15 08:58
@cdamken this errors seems to come from the "personal" page which is the settings page, so unlikely to be related. Maybe some app is trying to display an icon/image that is missing.

**Comment by cdamken** [comment] 2015-04-15 09:08
@PVince81 Ok, thanks

BTW the problem still happens with 1.8.0
Any clue?

**Comment by caratsch** [comment] 2015-04-16 10:56
@cdamken @PVince81 The new sync client fails more often with this error. I tried now a completely different instance with oC 7 and normal storage (not an NFS share like our productive system). The sync client fails with "connection closed" and "operation canceled" and doesn't automatically start again on OS X and Linux. On Windows 7 it fails, but it automatically continues after some seconds.

**Comment by cdamken** [comment] 2015-04-17 09:54
I tested with Ubuntu and after it crash sometimes does continue and sometimes stops until you press pause and resume.

![screenshot](https://cloud.githubusercontent.com/assets/7264495/7199870/4e638b68-e4f8-11e4-80fb-d550064045e8.jpg)


Log files from Ubuntu: S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689\download.zip

**Comment by moscicki** [comment] 2015-04-17 09:58
@cdamken: I also see this against our server (which is a completely difference implementation). Is this a problem of the server closing connections or is this induced by the client? On the other hand, in all cases I witnessed, the client resumes after this error.

**Comment by cdamken** [comment] 2015-04-17 10:03
@moscicki Which version of server and clients do you have?

I saw the problem with 6.0.6 and 7.0.5

With Windows Clients it resumes and continue until sometime it finish, but OsX and Linux, as @caratsch described above it stops syncing.

**Comment by dragotin** [comment] 2015-04-17 10:05
@moscicki can you try to catch a wireshark protocol when that happens? Or mitmproxy? It would be great to see what actually happens on the wire.

**Comment by cdamken** [comment] 2015-04-17 11:05
@dragotin I added in:
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689\

The following files:
sync_client_180_connection_closed.log
sync_client_180_connection_closed.tcpdump

 that @caratsch provided me.

**Comment by danimo** [comment] 2015-04-17 11:36
@cdamken If possible, make sure to ask for tcpdump output as pcap files. the tcpdump file does not provide the information we are looking for.

**Comment by cdamken** [comment] 2015-04-17 12:08
@danimo wireshark_sync_client_180_error.log and wireshark_sync_client_180_error.pcapng
on S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689\

**Comment by cdamken** [comment] 2015-04-22 14:36
@danimo Are those files right? do you need something more?

**Comment by dragotin** [comment] 2015-04-23 15:27
@DeepDiver1975 this is exactly the same effect we saw on the test system yesterday:
```
04-17 13:49:31:420 0x1fb6470 !!! OCC::GETFileJob created for  QUrl( "https://polybox.ethz.ch" )  querying "/163 error/gca4ea-polybox-sync-error.log" 
04-17 13:49:31:510 0x1fb6470 void OCC::AbstractNetworkJob::slotFinished() 2 "Connection closed" 
04-17 13:49:31:513 0x1fb6470 void OCC::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://polybox.ethz.ch/remote.php/webdav/1.7.1-sync-error-fedora20.txt" )  FINISHED WITH STATUS 2 "Connection closed" 
04-17 13:49:31:514 0x1fb6470 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "1.7.1-sync-error-fedora20.txt" INSTRUCTION_NEW 1 "Connection closed" 
04-17 13:49:31:519 0x1fb6470 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" 
```
do you have any idea meantime?

**Comment by moscicki** [comment] 2015-04-23 15:31
@dragotin, @DeepDiver1975 : I still owe you the wireshark analysis. But... I also see it on our server. So it may be a problem in the client networking stack and not necessarily a server problem?

**Comment by dragotin** [comment] 2015-04-30 11:59
@jnfrmarks This problem is still fishy. Please, if you do smashbox tests, keep the eyes open for this problem, thanks.

**Comment by craigpg** [comment] 2015-05-04 20:39
@DeepDiver1975, @dragotin - Trying to see if we have next steps on this one.  Are we waiting for additional log files or to somehow reproduce this in our test environment?  Some logs have been posted above (e.g. wireshark) but it's not clear we've gone through them.  Please clarify if you can.  Thx.

**Comment by cdamken** [comment] 2015-05-05 13:57
@craigpg  I can reproduce it in S3 today:

![s3 error](https://cloud.githubusercontent.com/assets/7264495/7474046/47c99e28-f33f-11e4-863e-5c6a0cf4c8a0.png)

**Comment by dragotin** [comment] 2015-05-05 15:43
Can somebody please check the logs on s3: Check if there is an entry in owncloud.log at the time where this connection close happens in access_log. @danimo

**Comment by cdamken** [comment] 2015-05-11 08:33
@dragotin @danimo testing 1.8.1 in mac happens the same error, now doesn't hang out anymore, it restarts after 30 seconds.

### New Log
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689\sync_client_181_connection_closed.log

**Comment by dragotin** [comment] 2015-05-11 08:53
Please check apache access_log and owncloud.log from server for file
```
test-cyberduck/A.C.N. Vs Double Amp ft. Veela - Im A Liar (Nick Bounce Remix).mp3
```
at time 10:20:05:701

**Comment by cdamken** [comment] 2015-05-11 09:22
@dragotin 

### Logs:

S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689\connection_error_181_logs.zip

**Comment by dragotin** [comment] 2015-05-11 14:48
The server log shows tons of entries like 
```
{"app":"PHP","message":"Undefined property: OCA\\user_ldap\\USER_LDAP::$connection at \/var\/www\/html\/owncloud\/apps\/user_ldap\/user_ldap.php#173","level":3,"time":"2015-05-11T08:20:04+00:00"}
```
at the time in question. Can it be that LDAP was not available and the server can not validate the user or such? @blizzz your input welcome!

**Comment by blizzz** [comment] 2015-05-11 15:02
What ownCloud version is it? I guessed 6.0.6, but at the line mentioned there is no $connection used at all. Also connection is never a property of USER_LDAP, but the Access class.

**Comment by dragotin** [comment] 2015-05-11 15:06
@cdamken your turn again.

**Comment by caratsch** [comment] 2015-05-12 08:17
@dragotin @blizzz yes, it's version 6.0.6. If I'm not wrong, this error messages are created by the "second user display name field"-patch provided by you.

**Comment by cdamken** [comment] 2015-05-12 08:22
@dragotin how about S3? there is no LDAP there.

@danimo Did you see anything in the logs?

**Comment by blizzz** [comment] 2015-05-12 09:30
@caratsch ok, i see it. Bummer, but this will not lead to sync errors or lead to unavailability of LDAP server or service.

**Comment by dragotin** [comment] 2015-05-13 12:10
Ok, I do understand that the LDAP logs are about some unrelated problem and do not cause the *connection close* problems in the logfile.

To be honest, I can't find any more hints what happens. Connection close is something the server is doing to an existing connection, there is no reason reported. 
I saw that happening for the following reasons
- the server tried to send a file with size X but the actual file was smaller, because of an inconsistency of between real and cached size.
- database lockups

Both could be the reason, but this is just speculation. Maybe its worth to check again if the server log is at the highest level, so that we do not miss server log entries?

**Comment by PVince81** [comment] 2015-05-13 12:30
I think in general the server never explicitly closes the connection without giving a response or error response. So it is likely to be a timeout of some sorts where the PHP code didn't get a chance to return anything.

**Comment by dragotin** [comment] 2015-05-13 15:13
@PVince81 right. Hard to debug now...

**Comment by cdamken** [comment] 2015-05-19 08:15
@dragotin with 1.8.1 happens too, the only advantage is that it restart the search again and again.

**Comment by dragotin** [comment] 2015-05-19 08:44
Yes, please ask the user to collect server logs with having logging switched on. The best would be a wireshark recording of one of these failing requests. Maybe that is possible?

**Comment by cdamken** [comment] 2015-05-19 09:00
I will ask again,

but you can see some prevous wireshark recordings here: https://github.com/owncloud/client/issues/2689#issuecomment-93965636

**Comment by dragotin** [comment] 2015-05-19 09:36
@cdamken the link to the wiresharks on  s3 is dead.

**Comment by ckamm** [comment] 2015-05-21 09:10
@cdamken I have been using your test account to try to reproduce the problem, but haven't encountered it yet. Can I provoke the error somehow? Does it usually happen at specific times?

You said it happened when you start the client for the first time on a Linux machine" - does that mean quitting and restarting the client will not produce the problem again?

**Comment by caratsch** [comment] 2015-05-21 10:23
@ckamm You can try to reset the sync client and start a clean sync. The error normally shows up when you download from the server.

**Comment by guruz** [comment] 2015-05-22 12:51
(Windows only) This is an updated ```Qt5Network.dll``` with a small patch that fixes this for me. Could you please test? It should match the DLLs shipped with 1.8.1

https://cloud.molkentin.net/index.php/s/LUPHW89fEBPZpTA

**Comment by guruz** [comment] 2015-05-22 13:31
(Please ignore previous comment, my patch only makes it less likely by ~50%.)

**Comment by zambaraa** [comment] 2015-05-25 09:12
I have the exact same issue on multiple machines. The server is installed on CentOS 6.6 (openvz vps) Server 8.0.3 (stable) (mysql+apache) - I have problems even with a newaccount uploads.

**Comment by cdamken** [comment] 2015-05-26 08:22
@dragotin 
> @cdamken the link to the wiresharks on s3 is dead.

S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689

MIRALL folder not Client

**Comment by cdamken** [comment] 2015-05-27 12:24
@dragotin @guruz The new log files are here:

S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2689\New

**Comment by guruz** [comment] 2015-05-27 13:41
@zambaraa Which client OS?

**Comment by guruz** [comment] 2015-05-29 11:44
For Windows, please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5124-nightly20150529-setup.exe and report back :)

**Comment by caratsch** [comment] 2015-05-29 13:16
@guruz I tried a clean sync and the error did not show up. I now have very bad performance with this client. The speed was never over 0.5 MB/s. With 1.7.1 I was able to upload and download with a speed of ~25 MB/s (same computer). I crated a log file you can download it here: https://polybox.ethz.ch/public.php?service=files&t=5bfd34be3abf5bc5999f729cb0af7e4e

**Comment by guruz** [comment] 2015-06-02 15:28
I tried syncing to polybox again using http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5135-nightly20150602-setup.exe (Apparantly there were some issues with the build server using another Qt with some nightlies but this one has the correct one) and I seem to have no speed problems with it.

**Comment by guruz** [comment] 2015-06-03 10:39
@caratsch Did you manage to try with the one above?
Is your Windows machine a real one or virtualized?

**Comment by Dianafg76** [comment] 2015-06-03 15:38
I tested this issue in:
.- MAC:
 . DESKTOP: 1.8.2 (build 2400)
 . SERVER: {"installed":"true","version":"6.0.6.1","versionstring":"6.0.6","edition":"enterprise"}

.- WINDOWS: 
 . DESKTOP: 1.8.2 (build 5138)
 . SERVER: {"installed":"true","version":"6.0.6.1","versionstring":"6.0.6","edition":"enterprise"}

And has not appeared to me at any time , " Connection closed " and " Operation canceled " .

**Comment by caratsch** [comment] 2015-06-03 18:52
@guruz Sorry, I'm currently in military and I don't have much time. I tested the sync client you provided and I now have "Connection Closed" & "Operation canceled" errors again. Do you want a new log file for debug? I tested the sync client in Windows 7.

@Dianafg76 Did you test a clean sync with many files (big files and small files)? I also have a big shared folder that I synchronize. The errors appear every time with my account.

**Comment by Dianafg76** [comment] 2015-06-04 06:44
@caratsch I tested with a small file, I'll try with large and small files

**Comment by Dianafg76** [comment] 2015-06-04 08:47
@caratsch I tested with a small and large files and happend the same with you. Appears 'Operation canceled'
I tested in Windows
. DESKTOP: 1.8.2 (build 5147)
. SERVER: {"installed":"true","version":"6.0.6.1","versionstring":"6.0.6","edition":"enterprise"}.

So I reopen the issue

**Comment by guruz** [comment] 2015-06-04 11:01
@caratsch Yes a log file would be nice. Also important what is the size (in bytes) and timestamp of ```Qt5Network.dll```?

**Comment by Dianafg76** [comment] 2015-06-04 11:31
@guruz my Qt5Network.dll is the timestamp 29/05/2015 20:58. Is immediately when starting, and the file size is 1 MB, and next is with the file size (200KB) or 23 B.
if you need more information tell me
Thanks

**Comment by Dianafg76** [comment] 2015-06-04 15:32
@guruz I tested in two different version for the SERVER:
.- Server v. {"installed":true,"maintenance":false,"version":"8.0.4.1","versionstring":"8.0.4 RC2","edition":"Enterprise"}, and not appears 'Operation canceled'

.- Server v. {"installed":"true","version":"7.0.6.1","versionstring":"7.0.6 RC2","edition":"enterprise"}, and not appears 'Operation canceled'

**Comment by danimo** [comment] 2015-06-05 08:20
@Dianafg76 @dragotin So we document that as a known issue for ownCloud 6 and close the issue?

**Comment by dragotin** [comment] 2015-06-05 08:21
Yes, lets close this.

**Comment by cdamken** [comment] 2015-06-08 15:55
@danimo @dragotin 

I'm disagree: 

https://github.com/owncloud/client/issues/2689#issuecomment-99084995

{"installed":true,"maintenance":false,"version":"8.0.2.0","versionstring":"8.0.2","edition":"Enterprise"}

Same problem I had with 1.8.1

**Comment by Dianafg76** [comment] 2015-06-09 08:01
@cdamken For Windows, please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5167-nightly20150609-setup.exe
Server v: {"installed":true,"maintenance":false,"version":"8.0.4.0","versionstring":"8.0.4RC1","edition":"Enterprise"}
Because, with this in my WINDOWS not more appers 'Operation canceled' and  " Connection closed "

**Comment by guruz** [comment] 2015-06-13 08:23
We have a new nightly for OS X:
http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.2430-nightly20150612.pkg

And windows:
http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.5188-nightly20150612-setup.exe

**Comment by bboule** [comment] 2015-06-15 09:37
Guys... I was able to address this issue (in my case) by simply bumping up the client side time out in the owncloud client config file C:\Users\xxx\AppData\Local\ownCloud and add timeout=xxx (I think the default is 300)  I have found that is the file you are trying to sync is large or on the file sits on external storage (where network congestion can impact the sync) this will help

**Comment by Dianafg76** [comment] 2015-06-16 11:13
I tested with http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.5188-nightly20150612-setup.exe, and reappears "Operation canceled" and " Connection closed "

**Comment by PVince81** [comment] 2015-06-17 08:57
Similar error messages have been observed here https://github.com/owncloud/core/issues/12193

**Comment by Dianafg76** [comment] 2015-06-22 11:05
I tested with DESKTOP v ownCloud-1.8.3.5212rc3-setup.exe
Server v: {"installed":true,"maintenance":false,"version":"8.0.4.0","versionstring":"8.0.4RC1","edition":"Enterprise"}
Because, with this in my WINDOWS not more appers 'Operation canceled' and " Connection closed "

**Comment by caratsch** [comment] 2015-06-22 12:26
I tested 1.8.3rc3 (build 5212) on Windows 7 and I now had no errors. It seems that the problem is fixed. I hope the final release (branded) will also run like this!

**Closed** 2015-06-22 12:58 UTC
Labels: blue-ticket, Clarification request, Needs info, Server Involved
