### ISSUE TITLE
Default windows installer path on c:

### ISSUE THREAD

**Issue by Jisagi** [owncloud/client#8297] opened 2020-12-12 10:27 UTC
### Expected behaviour
The installation should install owncloud into the already existing directory or at least offer c:\Program Files\ownCloud as default.

### Actual behaviour
The installer, be it the auto updater or the one downloaded one from the website, defaults to c:\. When manually installing it, this isn't that big of a deal, but the auto update, which cannot be disabled, installs the new verstion directly onto the c:\ drive. No subfolder, nothing. The pain to manually find and delete the correct files/dirs and not either miss or accidentally delete the wrong ones is high.

### Steps to reproduce
1. Download the installer
2. Install it and see what default installation destination he selects
or
1. Wait for an autoupdate 

### Client configuration
Client version: Latest version 2.7.3 build 2877

Operating system: Windows 10, latest patch 20H2

OS language: German

Installation path of client: Usually C:\Program Files\ownCloud

**Comment by jnweiger** [comment] 2020-12-13 15:12
## Tested in win10 20H2 v2

* Client 2.6.3 was installed under c:\Program Files (x86)\ownCloud
* Inspect the file owncloud.exe there: Size 2.374.872 bytes, Created: Frida, June 12, 2020, 10:29:20 AM
* Wait until there is an update notification for owncloud 2.7.3
* Go to the general page, the same is reported there. Click on `Restart & Update`
* The user is not asked any questions, the client updates.
* The installation in C:\Program Files (x86)\ownCloud now has an updated owncloud.exe: 2.142.936 bytes, Created: Friday, December 11, 2020, 7:21:54 AM
* Windows search does not find anything outside C:\Program Files (x86)
![image](https://user-images.githubusercontent.com/1108546/102015762-bf8eed00-3d5d-11eb-9eaa-300f9cb03320.png)

I reproduce the issue here. For me it uses the same subfolder that the previous install used.

**Comment by EstebanSalpeter** [comment] 2020-12-14 13:40
Hello people! I had the same issue when automatically updated 
FROM Client version: ownCloud-2.7.2.2626.x64
TO Client version: Latest version 2.7.3 build 2877 ### x86 ###
running Windows10.
I think this issue resides mostly in the auto update bringing an x86 version, coming from x64.
Hope this helps.
I've manually uninstalled, downloaded the x64 version, and then reinstalled it correctly.
Best regards and keep safe!

**Comment by TheOneRing** [comment] 2020-12-15 13:14
Our auto updater will provide 64bit updates for platforms supporting it later today.

**Comment by dschmidt** [comment] 2020-12-15 16:55
The auto updater now provides 64bit updates for 64bit clients, we are not (yet - tbd) upgrading clients to 64bit automatically.

**Comment by dschmidt** [comment] 2020-12-15 22:18
Next daily will fallback to `%ProgramFiles%/ownCloud` when `INSTALLDIR` has been set to `ROOTDRIVE` automatically because of a Win64 to Win32 downgrade. Fix will be in 2.7.4.

**Comment by dschmidt** [comment] 2020-12-15 22:19
Closing, feel free to reopen should the problem remain.

**Closed by dschmidt** 2020-12-15 22:19 UTC
Labels: p2-high
