### ISSUE TITLE
[QtKeychain] Make sure kwallet and friends are started

### ISSUE THREAD

**Issue by kay-inge** [owncloud/client#2532] opened 2014-11-21 21:22 UTC
Like in http://forum.owncloud.org/viewtopic.php?f=14&t=24443 , the ownCloud Sync Client asks for password every start. I did the things, which are described in the other thread, but the password-dialog still remains. It's very annoying. Is there any solution for the problem?

I also tried to set the envirnoment-variable like https://github.com/owncloud/mirall/issues/1590 , but the client still asks for passwort every time.

libqtkeychain0 V0.4 amd64
owncloud-client V1.7.0 amd64

I'm running Kubuntu 14.10 Utopic with KDE 4.14.2, on my notebook with nearly the same installation, the sync client works like a charm and there's no password dialog after system start.

Regards,
Kay

**Comment by Nowaker** [comment] 2015-02-01 15:53
Well, why does owncloud depend on kwallet at all? If there's no kwallet, then let owncloud remember the password directly. Dropbox doesn't use kwallet. This issue kills usability.

**Comment by sybrenstuvel** [comment] 2015-02-25 09:44
I also suffer from this issue. When the owncloud sync client (version 1.6.3+dfsg-0ubuntu1) starts, it always asks for a password. When I manually open the KWallet, and then start the owncloud client, it works just fine.

This is with:

- Kubuntu 14.10
- owncloud-client 1.6.3+dfsg-0ubuntu1
- libqtkeychain0 0.3.0-2

**Comment by danimo** [comment] 2015-02-25 09:46
@sybrenstuvel There have been a lot of fixes that are not reflected in the Ubuntu repository. Please try with our official packages: https://owncloud.org/install/#desktop

**Comment by sybrenstuvel** [comment] 2015-02-26 14:17
@danimo I've re-tested with the official package (version 1.7.1), and can confirm that this issue still persists.

**Comment by kay-inge** [comment] 2015-02-26 14:45
Issue still present, V1.7.1, too. Like reported before, it depends of kwallet. If kwallet is started manually, the oc-Client just starts fine.

**Comment by kay-inge** [comment] 2015-03-19 14:57
Same behavior in V1.8.0

I wonder why this issue is labeled as discussion, in my opinion this is a bug. I'm willing to test or give informations, but I'm not a developer and I don't know what's relevant.

**Comment by danimo** [comment] 2015-03-19 15:00
@kay-inge yes, it's an upstream bug.

**Comment by guruz** [comment] 2015-03-26 14:01
@danimo has a pending patch on his hd for this.

**Comment by ogoffart** [comment] 2015-04-08 15:06
Duplicate of #1902

**Closed by ogoffart** 2015-04-08 15:06 UTC
Labels: bug
