### ISSUE TITLE
An icon is shown in the file/ folder which is shared by link 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2822] opened 2015-02-11 12:21 UTC
### Expected behavior
When you share by link a file or folder, an icon shows that this file or folder is shared by link

### Actual behavior
There are no icon when you share by link

### Steps to reproduce
1. Launch the app.
2. Share a file or folder by link

### Client configuration
version 1.8.0-nightly20150211 (build 2007)

**Comment by ogoffart** [comment] 2015-04-08 15:14
Sunds like duplicate of #3043

**Closed by ogoffart** 2015-04-08 15:14 UTC
Labels: enhancement - proposed
