### ISSUE TITLE
Activity View

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3728] opened 2015-09-02 12:58 UTC
The current sync activity will be renamed to be a pure sync log. A new view called Activity will display the servers activity stream. The local sync results will be added to the activity, so that it can be seen if a file that was shared for example was already synced successfully. 

@jancborchardt please scetch the gui layout 
@karlitschek where is API documentation?
@jturcotte fyi

**Comment by dragotin** [comment] 2015-09-02 12:58
More information: https://github.com/owncloud/activity/issues/349

**Comment by karlitschek** [comment] 2015-09-02 13:43
@nickvergessen for the activity api information

**Comment by nickvergessen** [comment] 2015-09-02 13:54
For the notifications the information can be found here:
https://github.com/owncloud/notifications/wiki/Reading-and-deleting-notifications-as-a-Client

for the activity app stuff is not done properly yet I think and needs some more thoughts, but if enough, I will add a page to the wiki similar to the notification one. Or do you need more information?

**Comment by karlitschek** [comment] 2015-09-02 13:58
@nickvergessen there should be an ocs api for that since years. we should use this

**Comment by jancborchardt** [comment] 2015-09-08 10:23
For the layout, refer to the Activity app on the server:
![capture du 2015-09-08 12-22-39](https://cloud.githubusercontent.com/assets/925062/9732464/5bc5f776-5624-11e5-9d64-6ee0d4b3586b.png)
Let me know if that’s possible or not. If not, we should probably sit together and sketch in person.

**Comment by ogoffart** [comment] 2015-10-27 10:39
Duplicate of #3732

**Closed by ogoffart** 2015-10-27 10:39 UTC
Labels: Enhancement
