### ISSUE TITLE
client update

### ISSUE THREAD

**Issue by Blisk** [owncloud/client#2231] opened 2014-09-22 06:14 UTC
Server configuration

I'm running the desktop client on Centos 6.5 x64.
The ownCloud sync client version is 1.6.3
Owncloud version 7.0.2

I hope clien soon will be changed to make a unattended or silent installation.
Or, to update it withouth entering administrator credentials when update.
I have 15 users and when client update I need to go to each one and put in the admin username and password to update. That is really annoying.
And it can be solved by unattended installation/update from server.

**Comment by danimo** [comment] 2015-03-31 13:49
This now is dupe of #2231.

**Closed by danimo** 2015-03-31 13:49 UTC
Labels: Enhancement
