### ISSUE TITLE
Feature request: ask for password at start

### ISSUE THREAD

**Issue by bluecola** [owncloud/client#2238] opened 2014-09-23 17:31 UTC
Hi,

I always used the ownCloud desktop client 1.2.5 for Windows 7, with the feature to ask everytime for my password when the client starts. Today, I updated to the latest version and I saw that this feature is gone.

This is really a pitty since I store very sensitive information on our server. I save all data on an encrypted partition. However, this is useless when my ownCloud account signs in without a password, since you can simply change the sync folder then.

So, a feature request: bring back the 'ask for password at start' feature!

Looking forward to hear your thoughts.

Regards,
BlueCola

**Comment by ignacioinnovo** [comment] 2016-01-12 13:08
Dear ownCloud team,

Let me congratulate you all for the job done! OwnCloud is getting better release by release.

I´m now testing the 7 version and the last version of the sync client for Windows.

I´ve posted a message in the forum and RealRancor ask me to post it here. So, I find this and another thread for the same thing. The other one is this: https://github.com/owncloud/client/issues/2631

Let me explain my situation:

What I need is that the client asks for password in every reboot. In some previous versions there were a checkbox that specified if we wanted to store or not the pass. But as you have encrypt it now it stores it everytime. Except in the case where yo Exit the client. I´ve seen that the password is erased from the owncloud.cfg. But, if the computer restarts the password remain there.

What I want to do is to store the ownCloud contents in an encrypted volume (by TrueCrypt) and when the user restarts the PC she has to enter the password of the encrypted container and then the password for the owncloud client in order to synchronize. In that way I keep the data safe in each computer. In the owncloud server (my own server) the files stay unencrypted because I want to access them by web and is more easy if they are not contained in an encrypted volume. The security issu comes in the Windows clients where the files can be stored in a notebook or desktop PC.

I´m a C# developer, do you think I can help in any way? I saw that the client is developed in C++...

Thank you very much in advanced,
Ignacio.

**Comment by ignacioinnovo** [comment] 2016-08-15 11:17
Hi OwnCloud Team!

Do we have any update on this?

If you could just add that checkbox not to save password would be a wonderful solution for this issue!

Thank you very much,
Ignacio.

**Comment by ImTheLe** [comment] 2016-12-14 00:05
I also really need this feature. It's annoying to have to log out every time before putting away your laptop. Thanks.

**Comment by guruz** [comment] 2017-07-03 12:49
You could configure your keychain storage to not store the password.

**Comment by ignacioinnovo** [comment] 2017-07-03 12:53
Hi Guruz! Excuse me, but can you explain me how can I do that? Are you talking about Windows environment?

**Comment by ogoffart** [comment] 2018-11-27 17:45
Closing as duplicate of https://github.com/owncloud/client/issues/2631

**Comment by dschmidt** [comment] 2018-11-27 20:30
@ogoffart you did not actually close this issue.

**Closed** 2018-11-27 22:31 UTC
Labels: Enhancement
