### ISSUE TITLE
The path is not synchronized because of errors

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/client#2681] opened 2015-01-08 14:17 UTC
### Expected behaviour
No errors in log file

### Actual behaviour
Errors:
```
|0|cscms.org/www/test|INST_REMOVE|Up|1420491451|54aafaca0f24b|9|01024243oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/1.install/install.diff|INST_REMOVE|Up|1420495665|54ab0b6b2fd22|0|01024406oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/1.install/install.exp|INST_REMOVE|Up|1420495665|54ab0b6b2fd31|0|01024405oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/1.install/install.log|INST_REMOVE|Up|1420495665|54ab0b6b29d95|0|01024407oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/1.install/install.out|INST_REMOVE|Up|1420495665|54ab0b6d1905a|0|01024409oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/1.install/install.php|INST_REMOVE|Up|1420495664|54ab0b6d0dce9|0|01024408oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/1.install/install.sh|INST_REMOVE|Up|1420495665|54ab0b6d18ff2|0|01024410oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/Language/fixed_language.diff|INST_REMOVE|Up|1420495884|54ab0deda9f10|0|01024413oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/Language/fixed_language.exp|INST_REMOVE|Up|1420495884|54ab0dedcbc50|0|01024412oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/Language/fixed_language.log|INST_REMOVE|Up|1420495884|54ab0dedcbc2a|0|01024411oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/Language/fixed_language.out|INST_REMOVE|Up|1420495884|54ab0df09daab|0|01024414oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/Language/fixed_language.php|INST_REMOVE|Up|1420495883|54ab0df0c6424|0|01024415oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
|0|cscms.org/www/tests/Language/fixed_language.sh|INST_REMOVE|Up|1420495884|54ab0df3cf7bb|0|01024416oc5ccb4a7b3c|6|Шлях не синхронізується через помилки: 504 Gateway Time-out|0|0|0|||INST_NONE|
```

There are much more of such lines in log file, also files are not present locally (deleted few days ago), but still present on server. I do not know, whose error is this (client or server), but log on server is empty.

### Steps to reproduce
1. Use ownCloud regularly and work with source files through IDE PhpStorm
2. Error will happen by its own

### Server configuration
**Operating system**: Ubuntu 14.04 with latest updates (Docker container)

**Web server:** Nginx 1.4.6

**Database:** MariaDB 10.0.15

**PHP version:** PHP-FPM 5.5.9

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** most likely updated from 7.x (do not remember exactly)

**List of activated apps:**
> Activity
ATNotes
Calendar
Contacts
Deleted files
Documents
External storage support
First Run Wizard
Full Text Search
Mail Template Editor
ocSafe
ownCloud dependencies info
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer
Diagram Editor (3rd Party)
Files Counter (3rd Party)
Files move (3rd Party)
Music (3rd Party)
ocPassman (3rd Party)

**The content of config/config.php:**

```
  'instanceid' => '****',
  'passwordsalt' => '****',
  'trusted_domains' => 
  array (
    0 => '****',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '****',
  'dbuser' => '****',
  'dbpassword' => '****',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '****',
  'mail_domain' => '****',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => '****',
  'mail_smtpport' => '587',
  'mail_smtpname' => '*****',
  'mail_smtppassword' => '****',
  'forcessl' => true,
  'loglevel' => '1',
  'blacklisted_files' => 
  array (
  ),
  'theme' => '',
  'maintenance' => false,
  'secret' => '****',
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** Forced HTTPS

### Client configuration
Client version: 1.7.1

Operating system: Ubuntu 15.04 x64 (I know, unstable, but was the same on 14.10 also before upgrade)

OS language: Ukrainian (uk_UA)

Installation path of client: as default in Ubuntu, from repository on download.opensuse.org

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
```
~$ owncloud --logwindow
SocketApi:  server started, listening at  "/run/user/1000/ownCloud/socket" 
==== added system ignore list to socketapi: "/etc/ownCloud/sync-exclude.lst" 
==== added user defined ignore list to csync: "/home/nazar-pc/.local/share/data/ownCloud/sync-exclude.lst" 
setting remote poll timer interval to 30000 msec 
Sys Info size:  108 
int main(int, char**) Already running, exiting... 
SocketApi:  dtor 
```

**Comment by ogoffart** [comment] 2015-01-08 15:37
The cause of the errors should be in the log. So please provide the log client log.  (The snipet you pasted is only the one shown when running owncloud while it is already running)

"504 Gateway Time-out" seems to indicate perhaps a proxy problem.

**Comment by nazar-pc** [comment] 2015-01-08 15:45
> The snipet you pasted is only the one shown when running owncloud while it is already running
I do not understand what do you mean by this, which exactly log file you need?
> "504 Gateway Time-out" seems to indicate perhaps a proxy problem.
My network connection to ownCloud server is like `me > ... > CloudFlare > Docker host with Nginx > Docker container with Nginx (here is ownCloud)`
CloudFlare work properly for sure, Nginx on Docker host also (there are many more websites working through the same Nginx instance, and they all work fine, just like ownCloud web interface and synchronization of other files). Also, there are the same 504 errors from Nginx, so, the problem is on PHP-FPM side, namely PHP, namely ownCloud.

**Comment by ogoffart** [comment] 2015-01-08 15:59
If you run owncloud with `--logfile -` you should see the log.  But it has to be run while no instance of owncloud is currently running.  
An alternative is to press F12 from the settings window.

But the problem is then probably on the ownCloud server.  In that case you should report the bug on the server's bug tracker.

**Comment by guruz** [comment] 2015-03-26 15:50
Server configuration issue, closing.

**Closed by guruz** 2015-03-26 15:50 UTC
Labels: Needs info
