### ISSUE TITLE
Mac client does not detect changes in local files

### ISSUE THREAD

**Issue by josemaX** [owncloud/client#4424] opened 2016-02-02 18:10 UTC
I have a Mac (OSX: 10.11.3, Clients tested 2.1.0, 2.1.1-Beta1 and 2.1.1-RC1) that does not detect when a local file has changed to update it at server (OC 8.2.2 Linux, CentOS6 from RPM/YUM)

Other Macs works without problem and sees the changes to the same file inmediately. This only happens in a machine, but if i pause the sync and restart, then does it (also if i exit the client and start again).

I've restarted/updated the client/checked disk with first aid...

Note: Others in the same server, same network, same OS and same client, works as expected.

**Comment by guruz** [comment] 2016-02-03 10:02
Is there anything special about the local sync dir? (network drive? USB stick?)
Have you tried running the client with 
```
/Applications/owncloud.app/Contents/MacOS/owncloud --logfile - 
```
to dig out more info?

**Comment by josemaX** [comment] 2016-02-03 10:23
No, it is in the local hard drive a file in a folder in Desktop. I change it with an editor and save it. Then it not syncs.

In a few hours i'll try what you say and will update this.

**Comment by josemaX** [comment] 2016-02-03 17:01
At start it logs:

m_crashReporterChar:  /Applications/owncloud.app/Contents/MacOS/owncloud_crash_reporter
02-03 17:32:50:239 0x7fc348449510 OCC::Application::setupLogging: "################## ownCloud es_ES () 2.1.1rc1 (build 3069)"
02-03 17:32:50:239 0x7fc348449510 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "es" translation
02-03 17:32:50:241 0x7fc348449510 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "9B5WD74GWJ.com.owncloud.desktopclient.socketApi"
02-03 17:32:50:242 0x7fc348449510 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
02-03 17:32:50:296 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:297 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:298 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:299 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:300 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:808 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:812 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:815 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:818 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:50:821 0x7fc348449510 unknown: Error receiving trust for a CA certificate
02-03 17:32:51:692 0x7fc348449510 OCC::FolderMan::setupFolders: * Setup folders from settings file
02-03 17:32:51:693 0x7fc348449510 OCC::Folder::checkLocalPath: Checked local path ok
02-03 17:32:51:693 0x7fc348449510 OCC::FolderMan::addFolderInternal: Adding folder to Folder Map  OCC::Folder(0x7fc34a9920d0)
02-03 17:32:51:693 0x7fc348449510 OCC::FolderWatcherPrivate::startWatching: FolderWatcherPrivate::startWatching() "/Users/jose/Desktop/Programación/"
02-03 17:32:51:694 0x7fc348449510 OCC::FolderMan::slotScheduleSync: Schedule folder  "Programación"  to sync!
02-03 17:32:51:694 0x7fc348449510 OCC::FolderMan::slotScheduleSync: Folder is not ready to sync, not scheduled!
02-03 17:32:51:694 0x7fc348449510 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use NO proxy
02-03 17:32:51:794 0x7fc348449510 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.9.1"
02-03 17:32:51:794 0x7fc348449510 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
02-03 17:32:51:794 0x7fc348449510 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "checkConnect" and starting new transaction
02-03 17:32:51:794 0x7fc348449510 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
02-03 17:32:51:794 0x7fc348449510 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "update database structure: add inode index" and starting new transaction
02-03 17:32:51:794 0x7fc348449510 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "update database structure: add path index" and starting new transaction
02-03 17:32:51:794 0x7fc348449510 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration")
02-03 17:32:51:795 0x7fc348449510 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "checkConnect End" 
02-03 17:32:51:923 0x7fc348449510 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
02-03 17:32:51:936 0x7fc348449510 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://owncloudserver/owncloud" + "status.php" "OCC::ConnectionValidator"
02-03 17:32:51:948 0x7fc348449510 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fc34a9ae7a0)
02-03 17:32:51:948 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:/Users/jose/Desktop/Programación/"
02-03 17:32:51:949 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Compartir con ownCloud"
2016-02-03 17:32:51.973 owncloud[8160:879363] Sparkle: ===== owncloud =====
02-03 17:32:51:974 0x7fc348449510 -[DelegateObject updaterMayCheckForUpdates:]: -[DelegateObject updaterMayCheckForUpdates:] may check: YES
02-03 17:32:51:980 0x7fc348449510 OCC::AccountManager::wantsAccountSavedSlot: Saving account "https://owncloudserver/owncloud"
02-03 17:32:51:981 0x7fc348449510 OCC::AccountManager::save: Saving  1  unknown certs.
02-03 17:32:51:981 0x7fc348449510 OCC::AccountManager::save: Saving cookies.
02-03 17:32:51:982 0x7fc348449510 OCC::CookieJar::save: "/Users/jose/Library/Application Support/ownCloud//cookies.db"
02-03 17:32:51:983 0x7fc348449510 OCC::AccountManager::wantsAccountSavedSlot: Saved account settings, status: 0
02-03 17:32:52:053 0x7fc348449510 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.2.2.2") ) ( "versionstring" ,  QVariant(QString, "8.2.2") ) )    0  Reply:  QNetworkReplyHttpImpl(0x7fc34a9ccb80)
02-03 17:32:52:053 0x7fc348449510 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:   QUrl( "https://owncloudserver/owncloud/status.php" )   with version  "8.2.2" ( "8.2.2.2" )
02-03 17:32:52:053 0x7fc348449510 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Undefined" -> "Credentials Wrong"
02-03 17:32:52:054 0x7fc348449510 OCC::AccountState::setState: AccountState state change:  "Desconectado" -> "Error en la configuración"
02-03 17:32:52:055 0x7fc348449510 OCC::FolderMan::slotAccountStateChanged: Account "jose@owncloudserver" disconnected, terminating or descheduling sync folders
02-03 17:32:52:078 0x7fc348449510 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
02-03 17:32:52:078 0x7fc348449510 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://owncloudserver/owncloud" + "status.php" "OCC::ConnectionValidator"
02-03 17:32:52:079 0x7fc348449510 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fc34ab3a1b0)
02-03 17:32:52:079 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:/Users/jose/Desktop/Programación/"
02-03 17:32:52:080 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Compartir con ownCloud"
02-03 17:32:52:083 0x7fc348449510 OCC::AccountManager::wantsAccountSavedSlot: Saving account "https://owncloudserver/owncloud"
02-03 17:32:52:083 0x7fc348449510 OCC::AccountManager::save: Saving  1  unknown certs.
02-03 17:32:52:083 0x7fc348449510 OCC::AccountManager::save: Saving cookies.
02-03 17:32:52:084 0x7fc348449510 OCC::CookieJar::save: "/Users/jose/Library/Application Support/ownCloud//cookies.db"
02-03 17:32:52:084 0x7fc348449510 OCC::AccountManager::wantsAccountSavedSlot: Saved account settings, status: 0
02-03 17:32:52:085 0x7fc348449510 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fc348411b20)
02-03 17:32:52:085 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:/Users/jose/Desktop/Programación/"
02-03 17:32:52:086 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Compartir con ownCloud"
02-03 17:32:52:088 0x7fc348449510 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fc34ac26e00)
02-03 17:32:52:088 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:/Users/jose/Desktop/Programación/"
02-03 17:32:52:089 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Compartir con ownCloud"
02-03 17:32:52:091 0x7fc348449510 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fc34a9d1030)
02-03 17:32:52:091 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:/Users/jose/Desktop/Programación/"
02-03 17:32:52:091 0x7fc348449510 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Compartir con ownCloud"
02-03 17:32:52:136 0x7fc348449510 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.2.2.2") ) ( "versionstring" ,  QVariant(QString, "8.2.2") ) )    0  Reply:  QNetworkReplyHttpImpl(0x7fc34845e040)
02-03 17:32:52:136 0x7fc348449510 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:   QUrl( "https://owncloudserver/owncloud/status.php" )   with version  "8.2.2" ( "8.2.2.2" )


When i save the changed file it logs:

02-03 17:37:58:946 0x7fc348449510 OCC::callback: FolderWatcherPrivate::callback by OS X
02-03 17:37:58:946 0x7fc348449510 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/Users/jose/Desktop/Programación/Enlaces por ver.txt"

Then i exited the client, started again and the file was synced

**Comment by dragotin** [comment] 2016-02-04 09:51
the log line 
```
02-03 17:37:58:946 0x7fc348449510 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/Users/jose/Desktop/Programación/Enlaces por ver.txt"
```
shows the problem: The file is ignored by the clients ignore list. Please check your custom ignore patterns in the client, see https://doc.owncloud.com/desktop/2.1/navigating.html#using-the-ignored-files-editor for details.

**Comment by josemaX** [comment] 2016-02-04 10:07
I double checked this when i saw the line, but no entry that could cause this.

Also, if i pause the sync and restart it or close the client and start it again then is synced. I think if a ignore entry matched it, then it not be synced anyway, no?

This afternoon i'll check the sync-exclude.lst as that article explains. Not sure but i think does not sync any file when changed.

Thanks

**Comment by hobla** [comment] 2016-02-04 14:26
Accented characters in the path are causing the problem - in my case it was an ö (o-umlaut), I see an ó (accented o) in your path.

This bug was fixed a long time ago but resurrected somehow in a recent update. I suspect on the server side, not in the client.

Workaround: quit the client, rename the folder, change the path in the settings file, restart the client.

**Comment by josemaX** [comment] 2016-02-04 16:49
Yes, that was. Renaming Programación to Programacion (in the client) and deleting/creating the sync it works as expected. In the server the folder is called Programación but seems not be a problem.

Thanks!

**Comment by hobla** [comment] 2016-02-04 21:04
Cool, so that's pretty much confirmed. As this is a bigger thing for us european users: Admins/Mods, should this be filed as a separate bug?

**Comment by guruz** [comment] 2016-02-06 11:20
@ogoffart Your recent optimizations in the exclude list might be related?

**Comment by ogoffart** [comment] 2016-02-06 12:11
What is in the ignore list?

**Comment by ogoffart** [comment] 2016-02-06 12:17
Maybe something to do with normalisation?

Folder::isFileExcludedAbsolute  do `if (!fullPath.startsWith(path())`  So maybe if both path don't have the same normalization that might be a problem.

folderwatcher_mac.cpp does:  

```
 qstring.resize(pathLength);
        CFStringGetCharacters(path, CFRangeMake(0, pathLength), reinterpret_cast<UniChar *>(qstring.data()));
```

To get the filename. That might not be the same normalisation as the one we except elsewhere.

Someone with a mac need to check that.

**Comment by josemaX** [comment] 2016-02-06 15:22
This is my sync-exclude.lst:

cat Library/Application\ Support/ownCloud/sync-exclude.lst 
.AppleDouble
]:2eDS_Store
]*.debug

**Comment by jturcotte** [comment] 2016-02-08 12:31
This was indeed caused by the accent in "Programación".

**Comment by Dianafg76** [comment] 2016-02-09 07:43
I tested this issue and is working OK
Desktop v ownCloud-2.1.1.3104-nightly20160209.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by josemaX** [comment] 2018-01-20 23:23
This problem (accented chars in the local folder name) appears again at least with client 2.3.4 and 2.4.0-8836. 
I powered today a notebook (MBPro) after some time and found it. Renaming the folder to no accented chars, removing the sync in client, and adding again make it work.
The behavior is the same that before, if i change a file is not detected. If i pause and start the sync then it's synced.
Best,

**Comment by guruz** [comment] 2018-02-12 15:52
@josemaX  Works for me... macOS 10.13.3 with APFS. 


Can you run the client with logging and show what happens when you create a file?

Can you also paste the folder name here?


Both my configured sync folder and the filename contain an accent:
```
./bin/owncloud.app/Contents/MacOS/owncloud --logfile - --logdebug
...
02-12 16:43:47:404 [ debug gui.folderwatcher ]	[ OCC::callback ]:	FolderWatcherPrivate::callback by OS X
02-12 16:43:47:405 [ info gui.folderwatcher ]:	Detected changes in paths: QSet("/Users/guruz/Programación/Programación.txt")
```

**Comment by guruz** [comment] 2018-02-12 16:27
Is your sync dir on some external or network drive?

**Comment by guruz** [comment] 2018-02-12 16:29
Does it work if you use a similar folder name and re-type the folder name? (don't cut/paste)

**Comment by josemaX** [comment] 2018-02-15 11:32
Hello @guruz sorry by delay replying

I've created a new folder called "Solución" (just to try) in my desktop (10.13.3 - APFS) and the same "Solución" in my account in the server

Client: 2.4.0 (8836)

Then added the sync between both and dragged some files an directories to Solución in my desktop. Nothing was synced. Edited a text file with Sublime Text and saved. Not synced. Paused the sync and started again an it uploaded all files/folders and the updated file.

Edited the file again an saved. No sync happened.

I'll try the logging mode in a while and post.

Best

**Comment by josemaX** [comment] 2018-02-15 18:18
Here is some from logs, i trimmed or faked info as servername or users. Hope helps:

`
****************************************************************
*** When I paste the file (mantisbt...gz) into Solución fldr ***
****************************************************************



02-15 12:40:10:670 [ debug gui.folderwatcher ]	[ OCC::callback ]:	FolderWatcherPrivate::callback by OS X
02-15 12:40:10:670 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/Users/userName/Desktop/Solución/mantisbt-2.11.0.tar.gz"
02-15 12:40:11:659 [ debug gui.folderwatcher ]	[ OCC::callback ]:	FolderWatcherPrivate::callback by OS X



02-15 12:42:16:241 [ info gui.folder ]:	Trying to check "https://my-server.tld/owncloud/remote.php/dav/files/userName/Solución" for changes via ETag check. (time since last sync: 359 s)



****************************************************************
*** When uncompress the tar.gz file (inside Solución folder) ***
****************************************************************

02-15 12:42:16:905 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/Users/userName/Desktop/Solución/.BAH.he5t9"
02-15 12:42:17:124 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::RequestEtagJob finished for "/"
02-15 12:42:17:129 [ debug gui.folder.manager ]	[ OCC::FolderMan::slotRunOneEtagJob ]:	Scheduling "https://my-server.tld/owncloud/remote.php/dav/files/userName/Solución" to check remote ETag
02-15 12:42:17:130 [ info sync.accessmanager ]:	6 "PROPFIND" "https://my-server.tld/owncloud/remote.php/dav/files/userName/Solución" has X-Request-ID "e91c7eef-[TRIMMED]-051fe7fc051d"
02-15 12:42:17:130 [ debug sync.cookiejar ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://my-server.tld/owncloud/remote.php/dav/files/userName/Solución") requests: (QNetworkCookie("oc_sessionPassphrase=v8ylP31vcnN3rCE395dHJU9tShBu7GJ[TRIMMED]fzKxVBGf4QNT6; secure; HttpOnly; domain=my-server.tld; path=/owncloud"), QNetworkCookie("51630e[TRIMMED]jb5vgnas13; secure; HttpOnly; domain=my-server.tld; path=/owncloud"))
02-15 12:42:17:131 [ info sync.networkjob ]:	OCC::RequestEtagJob created for "https://my-server.tld/owncloud" + "/Solución" "OCC::Folder"
02-15 12:42:17:145 [ info gui.account.manager ]:	Saving account "https://my-server.tld/owncloud"
02-15 12:42:17:145 [ info gui.account.manager ]:	Saving  1  unknown certs.
02-15 12:42:17:148 [ info gui.account.manager ]:	Saving cookies. "/Users/userName/Library/Application Support/ownCloud//cookies3.db"
02-15 12:42:17:148 [ debug sync.cookiejar ]	[ OCC::CookieJar::save ]:	"/Users/userName/Library/Application Support/ownCloud//cookies3.db"
02-15 12:42:17:149 [ info gui.account.manager ]:	Saved account settings, status: 0
02-15 12:42:17:280 [ debug gui.folderwatcher ]	[ OCC::callback ]:	FolderWatcherPrivate::callback by OS X
02-15 12:42:17:281 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/Users/userName/Desktop/Solución/.DS_Store"
02-15 12:42:17:337 [ info sync.networkjob.etag ]:	Request Etag of QUrl("https://my-server.tld/owncloud/remote.php/dav/files/userName/Solución") FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) ""
02-15 12:42:17:340 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::RequestEtagJob finished for "/Solución"
02-15 12:42:17:360 [ info gui.account.manager ]:	Saving account "https://my-server.tld/owncloud"
02-15 12:42:17:360 [ info gui.account.manager ]:	Saving  1  unknown certs.
02-15 12:42:17:363 [ info gui.account.manager ]:	Saving cookies. "/Users/userName/Library/Application Support/ownCloud//cookies0.db"
02-15 12:42:17:363 [ debug sync.cookiejar ]	[ OCC::CookieJar::save ]:	"/Users/userName/Library/Application Support/ownCloud//cookies0.db"
02-15 12:42:17:364 [ info gui.account.manager ]:	Saved account settings, status: 0
02-15 12:42:18:104 [ debug gui.folderwatcher ]	[ OCC::callback ]:	FolderWatcherPrivate::callback by OS X
02-15 12:42:18:105 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/Users/userName/Desktop/Solución/mantisbt-2.11.0"
02-15 12:42:22:896 [ debug qt.qpa.input.gestures ]	[ unknown ]:	beginGestureWithEvent @ QPointF(301.867,151.996)
02-15 12:42:22:967 [ debug qt.qpa.input.gestures ]	[ unknown ]:	endGestureWithEvent
02-15 12:42:23:131 [ debug gui.folderwatcher ]	[ OCC::callback ]:	FolderWatcherPrivate::callback by OS X
02-15 12:42:23:131 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/Users/userName/Desktop/Solución/.DS_Store"
02-15 12:42:23:338 [ debug qt.qpa.input.gestures ]	[ unknown ]:	beginGestureWithEvent @ QPointF(301.867,151.996)
02-15 12:42:23:431 [ debug qt.qpa.input.gestures ]	[ unknown ]:	endGestureWithEvent
02-15 12:42:23:794 [ debug qt.qpa.input.gestures ]	[ unknown ]:	beginGestureWithEvent @ QPointF(301.867,151.996)
02-15 12:42:23:921 [ debug qt.qpa.input.gestures ]	[ unknown ]:	endGestureWithEvent`

**Comment by ogoffart** [comment] 2018-02-20 11:19
```
[OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/Users/userName/Desktop/Solución/mantisbt-2.11.0.tar.gz"
```

I guess this happens because the folowing condition in `ExcludedFiles::isExcluded` fails.

```
    if (!filePath.startsWith(basePath, Utility::fsCasePreserving() ? Qt::CaseInsensitive : Qt::CaseSensitive)) {
```

And this is again the a similar problem as in two years ago. Maybe either `filePath` or `basePath`  is not normalized

**Comment by guruz** [comment] 2018-02-20 11:20
Sorry, have to move this to 2.4.2.

Maybe we can fix this and then give @josemaX a daily/test build to verify.

**Comment by ogoffart** [comment] 2018-02-20 11:37
Normally this should be fixed by https://github.com/owncloud/client/pull/6370

**Comment by guruz** [comment] 2018-03-29 12:24
I'm sorry, that was a 2.5.0 build.
I meant: https://download.owncloud.com/desktop/daily/ownCloud-qt5.6.2-2.4.2.9538-daily20180329.pkg

**Comment by josemaX** [comment] 2018-03-29 13:26
Sure, i'll do it tonight.

**Comment by josemaX** [comment] 2018-03-30 09:37
Hello

I did the same as in https://github.com/owncloud/client/issues/4424#issuecomment-365900903

It works well, in both directions, if i add some file to "Solución" in Desktop is synced immediately, if i drop a file with name matching exclusions is not synced (as must be), but if i rename is synced immediately again, so think works perfect.

And from Web interface, i delete a file and after a couple of seconds, is deleted from desktop.

Thanks!

**Comment by guruz** [comment] 2018-04-03 13:13
Great, thank you for testing @josemaX

**Closed by guruz** 2018-04-03 13:13 UTC
Labels: ReadyToTest, bug
