### ISSUE TITLE
nemo shell integration should not generate usless share links

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6642] opened 2018-07-11 13:44 UTC
Testing with 2.4.2rc1
The the right click menue in nemo  allows sending liinks per mail and pasting links to the clipboard, even when the folder or file is not shared with anybody.
This should not be allowed. The expectation is "but I sent you the link!" -- and it still does not work.

See also https://cloud.owncloud.com/index.php/f/4377067

**Comment by michaelstingl** [comment] 2018-07-12 12:56
@ckamm @ogoffart Is there an easy way to improve here?

**Comment by guruz** [comment] 2018-07-12 14:22
> https://cloud.owncloud.com/index.php/f/4377067
"You don't have permissions to access this file/folder - Please contact the owner to share it with you."

**Comment by ogoffart** [comment] 2018-07-13 07:10
The mail option is gone in 2.5  (removed in https://github.com/owncloud/client/pull/6434 )

The mail option say "Send **private** link by email..." so it mention it is private; That's how it also was in 2.4.0 and 2.4.2 is just a patch release with a couple of bugfixes but no UI changes. 

So i'm closing this issue since it is not a regression from 2.4.1, and it is already fixed in 2.5

**Closed by ogoffart** 2018-07-13 07:10 UTC
Labels: Needs info

**Comment by michaelstingl** [comment] 2018-07-13 08:35
Fine for me
