### ISSUE TITLE
[2.0.2] Windows cause crash to Chrome 64bit

### ISSUE THREAD

**Issue by simbus82** [owncloud/client#4061] opened 2015-11-02 23:00 UTC
After upgrade to owncloud windows client 2.0.2 (without choice!!!) i have a crash of Google Chrome every time i open a dialog with windows folder or file browser (for example when from web i click to some "browse" or "upload" button).

The client is on a Windows 10 Pro laptop, Owncloud server is 8.0.2, Chrome is v46 64 bit.

Then i have installed Chrome v46 32bit over the 64bit version and with owncloud client enabled i have no problem.

PS: obviously if i uninstall owncloud client, i see no crash in chrome 64bit.

**Comment by guruz** [comment] 2015-11-03 08:57
What's the uptime of your system? Does it get permanently fixed when rebooting?
I'm asking because the Explorer.exe integration might use some old DLL?

**Comment by simbus82** [comment] 2015-11-03 09:06
I give to you more spec:

Owncloud Dedicated Server:
Debian 7.4
Linux 3.10.23-xxxx-std-ipv6-64 su x86_64
Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz, 8 core
Owncloud 8.0.2

Owncloud Client on personal PC/Laptops:
Windows 10 Pro - Owncloud client 2.0.2
Chrome v46 64bit

The Laptops and Desktops show the problem after a reboot too. 
The downgrade is not possible, so i have not tested what happen if i use Owncloud client 2.0.1 in same conditions.

What i see and is replicable on my two machine is:
- Under Windows 10 Pro if i have Chrome v46 64bit and Owncloud Client 2.0.2, Chrome crash always when is opened a dialog to access file system, Owncloud Client search forever and never syncronize.

**Comment by guruz** [comment] 2016-01-04 11:59
@jturcotte Does this 32 vs 64 bit ring a bell for you?

**Comment by jturcotte** [comment] 2016-01-04 12:13
You won't get the integration at all in a 32bit application on a 64bit system, that's mainly the difference. The question is why is it crashing in Chrome 64bit while it doesn't in other 64bit application.

**Comment by danimo** [comment] 2016-01-07 13:28
I have installed ownCloud Client on a Windows 10 VM and installed Chrome (Version 48.0.2564.48 beta-m (64-bit)) next to it. I cannot reproduce any kind of crash. I highly suspect an edge-case which allowed your OS to keep an inconsistent state. I am hence closing this report as "cannot reproduce".

Please:
 - Remove ownCloud Client entirely
 - Reboot
 - Reinstall the latest ownCloud Client version (2.1 at this time)
 - Reboot again
 - If you can still reproduce the issue now, please report back.

Should you still be able to reproduce the crash, please get back to us in the comments. I'll be happy to reopen the report.

**Closed by danimo** 2016-01-07 13:28 UTC
Labels: bug
