### ISSUE TITLE
Linux: Wrong application name displayed

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11164] opened 2023-08-31 07:53 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The desktop client is called desktopclient.owncloud.com.owncloud

Ubuntu 22.04
Client 5.0.0 daily 20230830

### Steps to reproduce the issue

1. Open the client
2. Look at the top bar

### Screenshots

<img width="868" alt="Screenshot 2023-08-30 at 21 48 48" src="https://github.com/owncloud/client/assets/49001702/a3e6c221-7540-43df-b6a4-646ec9a02f57">

### Expected behavior

The client is called just ownCloud client
@michaelstingl please confirm the exact name

### Actual behavior

The desktop client is called desktopclient.owncloud.com.owncloud

**Comment by HanaGemela** [comment] 2023-09-07 11:19
Works when starting the client like this:

QT_QPA_PLATFORM=xcb owncloud

That fixes also
https://github.com/owncloud/client/issues/11163
https://github.com/owncloud/client/issues/11165

**Comment by TheOneRing** [comment] 2023-09-07 11:23
Duplicate of : #11163

**Closed by TheOneRing** 2023-09-07 11:23 UTC
Labels: bug, p2-high, Linux, QA:team
