### ISSUE TITLE
[2.0 nightly] remotePollInterval no effect on connectivity-polls?

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#3677] opened 2015-08-24 23:16 UTC
OS: Win 7 home premium 64 bit
client: 2.0.0-nightly20150824 (build 5421)
only /music-folder is synced.
OC 8.1.1 (SuSE repo on debian 8.1.1, without SSL, without encryption)
my testpilotcloud.cfg (was changed when the client was not running):
````
[General]
optionalDesktopNotifications=true

[ActivityListHeader]
geometry=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\xbc\0\0\0\x5\x1\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x5\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\xb4\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\xdc\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\x3\xe8)

[Settings]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x4s\0\0\0^\0\0\a7\0\0\x3\x5\0\0\x4{\0\0\0|\0\0\a/\0\0\x2\xfd\0\0\0\0\0\0\0\0\a\x80)

[testpilotcloud]
admin%3Ahttp%3A\myhost\owncloud="@ByteArray(\x1\0\0\0\xd0\x8c\x9d\xdf\x1\x15\xd1\x11\x8cz\0\xc0O\xc2\x97\xeb\x1\0\0\0\xdbT='.\x94\xd0N\xa5\x2\xd1y\t\xae\x1b\xd4\0\0\0\0\x32\0\0\0Q\0K\0\x65\0y\0\x63\0h\0\x61\0i\0n\0-\0\x65\0n\0\x63\0r\0y\0p\0t\0\x65\0\x64\0 \0\x64\0\x61\0t\0\x61\0\0\0\x10\x66\0\0\0\x1\0\0 \0\0\0,\xbd\xfa\xbfqO5\xf1\xf1Tcs=\xefv\xfaQ\x81\xbe\xe9\x9a\xea(2\xf2\x91\x38r\xb1\an\x3\0\0\0\0\xe\x80\0\0\0\x2\0\0 \0\0\0\xa3\xf7\xf5\x45\x13\xf3\x35\x46S\xba\x10\x83\xca*\xf8\xbbGU\x1d\x8d\xb3\xbc\x9dQ!\xc8{Po`\x8a!\x10\0\0\0\x30K\x8c>\xd7\xda\xec\xc3\x89\xb5#<\x11 \xfei@\0\0\0\xa5Zb\xd4j?\x1c\x82\xb2\x80\xae\xe7\xe3\xb1\xf7\x94,=\xe3{\xf\xd6\x32R\xe6\x89\x1aKk\xda\xa4\xec\xa8.\x12\x42\xbfTR\x97\f\xf6\x42k\xcd\0\xb7\x11\x15%\xfb\x88\x8f\x9b}\x8bW]\x1dJ&F\x98\xd1)"
remotePollInterval=300000

[LogBrowser]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\xf5\0\0\x1:\0\0\x4\\\0\0\x2o\0\0\x1\xfd\0\0\x1X\0\0\x4T\0\0\x2g\0\0\0\0\0\0\0\0\a\x80)

[Accounts]
0\Folders\testpilotcloud\localPath=C:\\Users\\admin\\testpilotcloud
0\Folders\testpilotcloud\targetPath=/music
0\Folders\testpilotcloud\paused=false
0\Folders\testpilotcloud\ignoreHiddenFiles=true
0\url=http://myhost/owncloud
0\http_certificatePasswd=
0\http_certificatePath=
0\http_user=admin
0\authType=http
0\user=admin
````
The client is minimized, so there should be no polls regarding the quota (https://github.com/owncloud/client/issues/1470). But there are queries approx. every 30s:
````
ip - admin [24/Aug/2015:22:57:09 +0000] "PROPFIND /owncloud/remote.php/webdav/music HTTP/1.1" 207 4278 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:22:57:10 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1152 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:22:57:38 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:22:58:10 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:22:58:42 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:22:59:14 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:22:59:46 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:00:18 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:00:50 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:01:22 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:01:54 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:02:26 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:02:58 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:03:30 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:04:02 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:04:34 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:05:06 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:05:21 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1153 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:05:38 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:06:10 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:06:42 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:07:05 +0000] "PROPFIND /owncloud/remote.php/webdav/music HTTP/1.1" 207 2292 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
ip - admin [24/Aug/2015:23:07:14 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1111 "-" "Mozilla/5.0 (Windows) mirall/2.0.0 (testpilotcloud)"
````
and the client logfile:
````
08-25 01:12:07:149 0x4331f58 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-25 01:12:12:139 0x73d5d80 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QTcpSocket(0x73d5e20) QObject(0x0)  0 false 3 0 QAbstractSocket::UnconnectedState
08-25 01:12:35:809 0x4331f58 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-25 01:12:35:809 0x4331f58 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "http://myhost/owncloud" + "/"
08-25 01:12:41:109 0x73d5d80 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QTcpSocket(0x73d5e20) QObject(0x0)  0 false 3 0 QAbstractSocket::UnconnectedState
08-25 01:13:07:821 0x4331f58 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-25 01:13:07:821 0x4331f58 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "http://myhost/owncloud" + "/"
````
There was a similar behavior reported with the 1.8.4 version: https://forum.owncloud.org/viewtopic.php?f=14&t=29932

**Comment by guruz** [comment] 2015-08-25 09:50
> The client is minimized, so there should be no polls regarding the quota (#1470). But there are queries approx. every 30s:

That's a different thing. It checks for remote changes, not quota. But I guess you are wondering why it is not every 300sec?

**Comment by guruz** [comment] 2015-08-25 09:56
I meant: it checks the connectivity.
@ckamm Maybe we need to re-think that a bit.

Although I wonder if this is relevant given that maybe 0.01% of users ever touch ```remotePollInterval```

**Comment by tflidd** [comment] 2015-08-25 09:59
Me neither, I mostly stop the syncing process when I don't want to push changes constantly. Some people are worried by the noise in their logfiles.

**Comment by ogoffart** [comment] 2015-08-28 13:24
the quota check is done every 30 seconds if the account tab is visible.

**Comment by cdamken** [comment] 2015-10-14 16:06
Hi Guys, Setting remotePollInterval to a higher value doesn't change anything. I tried The Windows client and the Linux client in Version 2.0.1. 

@MorrisJobke 

00003982

**Comment by dragotin** [comment] 2015-10-19 13:52
true, the remotePollInterval() has only an effect on the ETag poll job. But not on the connectivity check. The PR above will help for that.

**Comment by LeCoyote** [comment] 2015-11-03 17:19
Question: why has the frequency increased so drastically in the recent versions? With only 2 users using the desktop client, nearly 10% of the (recent, quad-core) CPU goes into IO tasks, and that's ONLY with PROPFINDs (not syncing anything at all)
I guess I'm saying the problem is not with the poll interval but with the client doing stuff way too often for its own good.

Also:
> the quota check is done every 30 seconds if the account tab is visible
Well, even if the client is left in the background (as only an icon in the taskbar), I currently get 2 PROPFINDs per client every 30 seconds.

This seems to me like some new behaviour is now a major performance issue and drawback from previous versions. Also, apologies if this is already reported somewhere else!

**Comment by guruz** [comment] 2015-11-03 20:58
@LeCoyote We'll ping you when https://github.com/owncloud/client/pull/3964 is merged for that-will-be 2.1.
There's some improvements in the 2.1 branch.

**Comment by LeCoyote** [comment] 2015-11-03 21:13
@guruz Thanks for the info. Still, something bothers me: these PROPFIND calls have a much bigger performance hit than before. I believe it might be Owncloud's fault, namely 8.2.0. I'll look it up in the proper tracker.

**Comment by guruz** [comment] 2015-11-03 21:37
@LeCoyote Ah you mean on the server. I suggest to look into 
https://github.com/owncloud/core/issues/19888
https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html

**Comment by LeCoyote** [comment] 2015-11-04 09:01
I have now, thanks for the pointers :)

**Comment by guruz** [comment] 2015-11-18 14:47
https://github.com/owncloud/client/pull/3964

This is done and will be in the nightlies for tomorrow morning. The number of requests should be reduced and the poll interval respected.
It unfortunately did not make it into 2.1beta1.

**Closed by guruz** 2015-11-18 14:47 UTC
Labels: blue-ticket, Discussion, Performance

**Comment by tncxrb** [comment] 2015-11-29 04:17
I am having same issues but my client is: 
Linux 2.0.2
and Server is:
Ubuntu Server 15.10 OC 8.2.1
I am just closing the sync client after file sync, It has been happening for a while I didnt see it until I stumbled upon a 3GB logfile.

**Comment by guruz** [comment] 2015-11-29 12:28
@tncxrb https://owncloud.org/install/#testing-development Try 2.1rc1

**Comment by david-wolf** [comment] 2016-02-27 23:38
What is the purpose of remotePollInterval?  Should it not increase the sync speed?  It doesn't seem to do anything with version 2.1.
