### ISSUE TITLE
[Ubuntu 16.04] slide-out menus not working

### ISSUE THREAD

**Issue by mlujr** [owncloud/client#5114] opened 2016-08-09 10:07 UTC
### Expected behaviour
If you hover over "Last Changes" in owncloud client context menu a slide-out/submenu should appear.

### Actual behaviour
No slide-out/submenus appearing on accounts (if multiple accounts are used) nor on "Last Changes"

### Steps to reproduce
1. Click on owncloud tray icon 
2. Hover over the menu entries

### Client configuration
Client version: 2.2.2 or 2.2.3

Operating system: Ubuntu 16.04

OS language: German

**Comment by ckamm** [comment] 2016-08-15 08:25
Duplicate of #4135, see there for the upstream bug. We don't know of a workaround, unfortunately.

**Closed by ckamm** 2016-08-15 08:25 UTC
Labels: bug

**Comment by mlujr** [comment] 2016-08-26 12:45
There is a simple workaround:

Uncomment the single line in /etc/profile.d/appmenu-qt5.sh:
#export QT_QPA_PLATFORMTHEME=appmenu-qt5
