### ISSUE TITLE
File lost if created before rename of containing directory is finished sync

### ISSUE THREAD

**Issue by expertmm** [owncloud/client#4148] opened 2015-11-16 16:08 UTC
(was in core bug tracker at https://github.com/owncloud/core/issues/20483#issuecomment-156424578 but MorrisJobke requested moving it to here)

### Steps to reproduce
1. Create a folder
2. Put some files in it
3. Allow them to sync on two clients (such as Windows computers)
4. Turn off sync on client A, update a file
5. On client B, rename the folder (from a third computer [client C] without ownCloud client via Samba) and while sync is happening rename again to a third name, then allow sync to complete
6. Turn on sync on client A

### Expected behaviour
Client A should upload the file since it is newer than the deleted file
ownCloud should detect the rename operation

### Actual behaviour
Client A deletes all of the files and uploads the version from client B, even the old copy of the changed file (and sometimes leaves the folder empty--this was done with several folders containing several hundered megabytes, but only one folder was changed so everything was recoverable from recent backup except the one file that changed). The folder was empty for a while, but after client A synced again later, the added files came back, but the new file was overwritten with the older file.

Client A deletes all of the files in d.cpp and leaves it empty (renamed from Projects-cpp to dcpp then not long after renamed to d.cpp), however the files from d.cpp were in Trash and platformy.py was not.

### Server configuration
Ubuntu 14.04 Trusty Tahr
default database (sqlite ??)
fresh install of ownCloud server
ownCloud addons: none

NOTE: the server was upgraded to 8.1.4 before I could get the following data:
ownCloud server 8.0.9 (recently installed, so I must assume this. Whatever version was in trusty repo when ownCloud was installed at:
owner@login:/var/www$ stat -c "%y" owncloud
2015-11-12 09:18:58.777508869 -0500
)

Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth

config.php:
<?php
$CONFIG = array (
  'instanceid' => 'oclftpsqz8qq',
  'passwordsalt' => '5kB7Hqkcs+rVSd7UF9a0026+9+y3xS',
  'secret' => 'MjFonazIK/bbqWBE1NKfpmUOaeRknLtUDd4viw7DW2lOtGiC',
  'trusted_domains' =>
  array (
    0 => 'login.axlemedia.net',
  ),
  'datadirectory' => '/tank/cloud/own',
  'overwrite.cli.url' => 'http://login.axlemedia.net/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.4.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);

I will post logs if needed, but they are huge (14000 files or so) and the issue seems pretty clear

### Client configuration
**Operating system:**
client A: Windows 10 (ownCloud desktop client, turned off from Nov 7 evening to Nov 9 morning)
client B: Windows 7 (ownCloud desktop client)
client C: Windows 7 (accessed client B via Samba--mounted ownCloud folder to network drive letter)
**Browser:**
(did not use browser, only ownCloud desktop client)

#### ownCloud log (data/owncloud.log)
the file lost was ownCloud/d.kivy/1.Examples/GREAT-Pygame-master/platformy.py
after renaming
Projects-kivy to dkivy then shortly after that renaming it again to d.kivy, all from Client C via samba
[owncloud.log (server).txt](https://github.com/owncloud/core/files/33479/owncloud.log.server.txt)

the file was modified Nov 7 on Client A, but next sync of Client A wasn't done until Nov 16. The log doesn't seem to have anything about that file (when searching for platformy.py in the log)

**Comment by ogoffart** [comment] 2015-11-18 15:57
I cannot reproduce the problem.   Here, when i rename a directory on computer A and modify a file within that (not-yet-renamed) folder on computer B.  then start the sync,  computer B rename the local directory, and upload the content of the file to the server.

Note that the local directory is renamed. (not deleted.)
But if i also delete a directory on computer A, and then change a file within this directory on computer B,  when i enable the sync on computer B, the directory contents are removed, except for the modified file which is uploaded.

So no bug here.

Can you please provide the client log?  (or the content of the activity tabs)

**Comment by phil-davis** [comment] 2015-11-18 17:11
In the steps to reproduce item 5 the OP renames the folder twice and lets it all get synced up to the server. Then the client that has the file change is woken again and needs to realise that its local folder is really 2 renames out-of-date compared to the server.
Perhaps it is the double-renaming that makes the system "forget" the renaming trail and treat the multi-renamed folder on the server as if it is new?

**Comment by ogoffart** [comment] 2015-11-19 07:43
The double renaming should not make it loose its trail.  And even if it did, and that the client should delete the folder, it would still not delete any files that was modified.

**Comment by guruz** [comment] 2015-11-30 17:22
(Also try with a recent server version)

**Comment by ogoffart** [comment] 2015-12-21 14:48
Closing old bug due to lack of information.

**Closed by ogoffart** 2015-12-21 14:48 UTC
Labels: Needs info
