### ISSUE TITLE
Assertion Failed - OCContextMenu - windows

### ISSUE THREAD

**Issue by trampi** [owncloud/client#2995] opened 2015-03-22 09:57 UTC
### Expected behaviour
Rightclick on a file opens the context menu.

### Actual behaviour
It gives the following error:
![oc1](https://cloud.githubusercontent.com/assets/4292951/6768847/d075c660-d081-11e4-98a8-c8f184456f0f.PNG)
![oc2](https://cloud.githubusercontent.com/assets/4292951/6768848/d0792f58-d081-11e4-85cd-3ab01757a969.PNG)

### Steps to reproduce
Right click on a file that is ignored according to the OCC.

### Server configuration
Operating system: CentOS 7

Web server: Apache2

Database: MariaDB 10

PHP version: 5.6

ownCloud version: 8.0.2

Storage backend: filesystem

### Client configuration
Client version: 1.8.0 (build 4847)

Operating system: Windows 7 x64

OS language: German

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

I can not reproduce this issue anymore as i have deleted the tmp files - sorry.

**Comment by jturcotte** [comment] 2015-03-23 13:01
Should be fixed by ad5620efb5dbd2d78e39d1bf31abb7eea16557f8 to be released in 1.8.1.

Since the fix is obvious and that the issue is difficult to reproduce, I'll close the issue directly. Please reopen if you can reproduce it.

**Closed by jturcotte** 2015-03-23 13:01 UTC
