### ISSUE TITLE
client should prevent data loss when excluding a folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6716] opened 2018-08-15 18:57 UTC
A prerequisite for https://github.com/owncloud/client/issues/6715
Here is a case where a 2.5.0 desktop client deletes a file from the local folder that was never synced to the server:
* Connect to demo.owncloud.org
* Wait until sync finishes. One of the folders is called 'Photos'.
* Pause sync. click open the folder tree, remove the checkmark of 'Photos'.
* Hit 'Apply' nothing gets removed despite the warning, as the sync is still paused.
* Delete the folder Photos on the server. Nothing gets deleted locally, the sync is paused.
* Wait some time, forget about any potential traps here.
* Add a new file 'DoNotRemove.txt' to the local Photos folder.
* Resume syncing. 
* The new file DoNotRemove.txt gets deleted. (together with the entire Photos folder).

Leave out any of the above steps, and the DoNotRemove.txt file is either preserved locally or even uploaded to the server.

**Comment by ogoffart** [comment] 2018-08-17 09:36
(Moving to 2.6 as this is not a regression, and the quite complicated steps necessary to get the file deleted, which includes warning that the file will get deleted)

In theory, DoNotRemove.txt should keep the file from being deleted.

**Comment by ckamm** [comment] 2019-04-17 10:42
I've tested this with 2.6's new discovery and can no longer reproduce the problem. The DoNotRemove.txt file is retained.

**Comment by ckamm** [comment] 2019-04-17 10:45
I do however see a problem where the folder no longer shows up in the selective sync folder list, even if the contents are ignored "because of the selective sync blacklist".

**Comment by HanaGemela** [comment] 2019-07-16 14:55
I also cannot reproduce the issue in 2.6.0alpha2 (build 12128) macOS 10.14.5.

> I do however see a problem where the folder no longer shows up in the selective sync folder list, even if the contents are ignored "because of the selective sync blacklist".

@pmaier1 Please specify the correct behaviour. What should we see in the in the selective sync folder list?

**Comment by ckamm** [comment] 2019-07-17 05:55
@HanaGemela Let's make it into a new 2.6.1 issue. It's separate from what this ticket was originally about.

**Comment by HanaGemela** [comment] 2019-07-17 07:21
@ckamm Done. https://github.com/owncloud/client/issues/7316

**Closed by HanaGemela** 2019-07-17 07:21 UTC
