### ISSUE TITLE
Basic auth screen layout

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/client#11934] opened 2024-10-16 09:58 UTC
MacOS qt 6.7.3 ...
![Screenshot 2024-10-15 at 23 23 17](https://github.com/user-attachments/assets/2a579d0f-64fe-4539-9a91-fb08677b480e)

_Originally posted by @DeepDiver1975 in https://github.com/owncloud/client/issues/11932#issuecomment-2415199203_

**Comment by erikjv** [comment] 2024-10-16 12:07
This is a duplicate of #11913

**Closed** 2024-10-16 12:07 UTC
