### ISSUE TITLE
[oCIS] Respect Capability "privateLinks": false

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9573] opened 2022-04-07 16:44 UTC
oCIS doesn't have the oC10-style private links. It's also announced as `false` in the capabilities:

```
% cat ocis.capabilities | jq .ocs.data.capabilities.files
{
  "privateLinks": false,
  "bigfilechunking": false,
  "undelete": true,
  "versioning": true,
  "favorites": false,
  "blacklisted_files": [],
  "tus_support": {
    "version": "1.0.0",
    "resumable": "1.0.0",
    "extension": "creation,creation-with-upload",
    "max_chunk_size": 100000000,
    "http_method_override": ""
  },
  "archivers": [
    {
      "enabled": true,
      "version": "2.0.0",
      "formats": [
        "tar",
        "zip"
      ],
      "archiver_url": "/archiver",
      "max_num_files": "10000",
      "max_size": "1073741824"
    }
  ],
  "app_providers": [
    {
      "enabled": true,
      "version": "1.0.0",
      "apps_url": "/app/list",
      "open_url": "/app/open",
      "new_url": "/app/new"
    }
  ]
}
```

Desktop clients should respect `"privateLinks": false` capability for the specific account.

**Comment by TheOneRing** [comment] 2022-07-20 10:56
Duplicate of: https://github.com/owncloud/client/issues/8998

**Closed by TheOneRing** 2022-07-20 10:56 UTC
Labels: oCIS
