### ISSUE TITLE
[OS X, Linux] Improve UNIX permissions for created sync folder

### ISSUE THREAD

**Issue by schnellschnell** [owncloud/client#3280] opened 2015-05-26 12:37 UTC
### Expected behaviour
At setup (for example first install).
The mac client creates a folder ~/ownCloud with permissions 700.
Only the user can access the files in the ownCloud folder as for example Documents/ or Music/.

### Actual behaviour
At setup (for example first install).
The mac client creates a default folder ~/ownCloud with permissions 755.
Everybody with access to the computer (other usere or even the guest user) can read all documents in the (private) oneCloud folder.

### Steps to reproduce
1. Set-up mac client with default values

### Server configuration
n/a

### Client configuration
Client version:
<= 1.8.1

Operating system:
- 10.8
- 10.9.5

OS language:

Installation path of client:
/Applications/onecloud.app

### Logs
Client installation (not very informative)

```05-26 16:28:26:200 0x7faa205150a0 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  3
05-26 16:28:29:095 0x7faa205150a0 OCC::OwncloudSetupWizard::slotCreateLocalAndRemoteFolders: Setup local sync folder for new oC connection  "/Users/admin/ownCloud"
05-26 16:28:29:100 0x7faa205150a0 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "Lokaler Synchronisations-Ordner /Users/admin/ownCloud wird erstellt ...ok"
05-26 16:28:29:101 0x7faa205150a0 OCC::AbstractNetworkJob::start: !!! OCC::EntityExistsJob created for "https://my_server/owncloud" + "remote.php/webdav//"
05-26 16:28:29:175 0x7faa205150a0 OCC::OwncloudSetupWizard::slotRemoteFolderExists: ******** Remote folder found, all cool!```

**Comment by Kawohl** [comment] 2015-05-28 06:47
I was not able to reproduce this on osx 10.10.3

**Comment by cmonteroluque** [comment] 2015-06-19 18:19
Closing it as not reproducible in 10.10.3

**Closed by cmonteroluque** 2015-06-19 18:19 UTC
Labels: Enhancement
