### ISSUE TITLE
Rewrite the Wizard

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9249] opened 2021-11-30 11:40 UTC
# Missing
- [x] App passwords

Its time to rewrite redesign the wizard.

In https://github.com/owncloud/client/issues/5030 we got  a proposal design for the wizard.
Lacking in the proposal are oauth and webfinger.

# Webfing:
Either an additional page after the server is selected or  an input field on the initial server page.

# Fixed url
If the url is branded we currently directly continue to the login, using oauth or basic auth.
If no account is present yet we will open the wizard on start, which with oauth will directly open the browser with out any guidance of the user.
- Provide a "Start" button and a description on what will happen after the wizard process stats.

# Advances setup
The selection of the default folder, the syncing mechanism, selective sync, or manual sync are all advanced features.
- I'd suggest to a "Show advanced settings" checkbox on all pages, only if the the option is selected the advanced page is displayed, else we end after authentication. (What to do when the default folder already exists)
  - There will only be one advanced page with settings, the option won't enable additional settings on the other pages. 
- Customers already requested to disable the advanced step, in this case we would just hide that checkbox

# TODO
- How to display errors

---
Related:
- https://github.com/owncloud/client/issues/5064
- https://github.com/owncloud/client/issues/5030

**Comment by TheOneRing** [comment] 2021-12-02 15:21
@tbsbdr While looking deeper I had the idea of using setup page in between the pages, this page then would display a spinner/error.

**Comment by tbsbdr** [comment] 2021-12-02 20:01
Not sure if I understood you - what problem would a in-between page solve?

**Comment by TheOneRing** [comment] 2022-03-24 10:35
Current todos:
- VFS
- Changing target dir
- Integrate webfinger https://github.com/owncloud/client/pull/9366
- Selective sync?

**Comment by fmoc** [comment] 2022-05-31 14:15
What needs to be done regarding app passwords? They work just fine already, it seems.

**Comment by TheOneRing** [comment] 2022-05-31 15:05
> What needs to be done regarding app passwords? They work just fine already, it seems.

We used to display a url to the app password settings in oc10 and mention the existance of app passwords.

**Comment by fmoc** [comment] 2022-07-29 10:02
Looks like we finished all the TODOs. Closing therefore.

**Closed by fmoc** 2022-07-29 10:02 UTC

**Comment by HanaGemela** [comment] 2022-11-11 10:23
Test:
Regression test that no features are missing in comparison with 2.11 client

**Comment by HanaGemela** [comment] 2022-11-11 10:39
Some features missing - will be fixed in https://github.com/owncloud/client/issues/10266
