### ISSUE TITLE
Add "New account" button in tab bar in settings

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5307] opened 2016-11-09 17:13 UTC
### Actual behaviour
There's no possible way to add an account until the you quit OwnCloud app, relaunch it and the wizard is shown again.

### Expected behaviour
One of the following:

1. The client is completely closed until at least one successful connection has been set
2. The Settings view allows to add a new connection (I think this one is preferred)

### Steps to reproduce
1. Install OwnCloud Desktop Client and launch it for the first time 
2. Close the Connection Wizard.
3. Open OwnCloud Settings from menu bar.

![no_accounts](https://cloud.githubusercontent.com/assets/2644445/20147359/16391ece-a6a8-11e6-8e88-34924d7150d9.png)

The same happens if you delete all the accounts on your client and continue on step 2.

### Client configuration
Client version:
2.3.0.3806-nightly20161109 (build 3806)

Operating system:
OS X 10.11.6

OS language:
English

Installation path of client: 
`/Applications/owncloud.app`

**Comment by guruz** [comment] 2016-11-10 14:57
Actually the connection wizard will re-open if there is no accounts. Maybe another Window in OS X is hiding the wizard?
Do you see the wizard in OS X Exposé?

**Comment by SamuAlfageme** [comment] 2016-11-10 15:23
@guruz In Windows it does reopen when you left-click on the OC icon in the notification area.

In OS X and Ubuntu 16.10 it's not shown until you quit the program and reopen it.

**Comment by guruz** [comment] 2016-11-15 08:48
@ogoffart says there used to be a 10 second timer that re-opens the wizard

**Comment by ogoffart** [comment] 2016-11-15 10:51
Once upon a time, the connection validator job was opening the wizard if there was account. (that was 30s by default).

For me on linux, deleting the last opens the wizard.  if one close the wizard and click on the systemtray icon, this open the wizard.
If one right click on the systemtray icon and open the settings, the settings ope, then there seem to be no way to open the wizard again

**Comment by SamuAlfageme** [comment] 2016-11-15 12:41
Fist scenario I'm trying is the user closing the wizard even before successfully setting an account. It does not trigger a new wizard. I made a [**video** on Ubuntu](http://webmshare.com/play/3w4GX) pointing this out.

Then, as @ogoffart pointed, if you delete the only account, eventually after some time, a single wizard is shown, but closing this one leaves you in the same state as the first scenario.

Again, I think instead time-triggering a new wizard the option to add an account within the settings screen is preferred.

**Comment by guruz** [comment] 2016-11-15 17:39
For the sake of simplicity and congruence between OSes I'll look why it does not re-open on tray click. Users will intuitively click the tray.

Adding buttons etc to settings is overkill.

**Comment by ckamm** [comment] 2016-11-18 11:09
@SamuAlfageme I can reproduce it. For me, on ubuntu with kde, clicking the tray icon opens the wizard while right-clicking and choosing settings opens the settings dialog.

I think it's necessary to allow opening the settings dialog without an account configured, because maybe proxy settings need to be adjusted before the account wizard can work. I'll add "New account..." to the tray context menu in cases where no account is configured to make it reachable when Unity is the WM.

@guruz I don't think this os OSX-only but would appreciate your testing.

**Comment by SamuAlfageme** [comment] 2016-11-29 15:47
So, after adding this option in the tray icon dropdown, what should we do with the time-triggered wizard? 

I'd say adding a button in the tab area to create a `New account...` is not that overkill and makes sense with the rest of the interface:

![no_account](https://cloud.githubusercontent.com/assets/2644445/20716728/7d49809e-b653-11e6-9f79-97c687c285c7.png)

**Comment by guruz** [comment] 2017-01-05 12:18
Considerung as good enough for 2.3, we can follow up with your idea later.

**Comment by TheOneRing** [comment] 2020-03-18 11:05
Lets move the "Add account" action from the "Account" menu to a separate button.
![image](https://user-images.githubusercontent.com/200626/76954461-ab25dd00-6910-11ea-9ac0-b18694bd6443.png)

**Comment by TheOneRing** [comment] 2020-09-10 11:14
Fixed in: https://github.com/owncloud/client/pull/8031

**Closed by TheOneRing** 2020-09-10 11:14 UTC
Labels: Design & UX, bug, good first issue, p4-low
