### ISSUE TITLE
[Feature Request] intranet sharing between clients like with dropbox client

### ISSUE THREAD

**Issue by mightyBroccoli** [owncloud/client#5374] opened 2016-12-10 16:51 UTC
If have many clients connected to the same instance. What I would like is a feature that if one clients syncs a big data package from the server from a shared folder, if another one also requests that file the intranet connection would be used to share it between the clients and not a new connection to the server.

is that possible? Or am I describing the whole process wrong?

**Comment by RealRancor** [comment] 2016-12-11 17:50
Duplicate of https://github.com/owncloud/client/issues/230 and https://github.com/owncloud/core/issues/26752

**Closed** 2016-12-13 12:11 UTC
