### ISSUE TITLE
owncloud Client crashes as soon as started

### ISSUE THREAD

**Issue by hernandezac** [owncloud/client#8069] opened 2020-09-10 08:45 UTC
### Expected behaviour
The client should start, run and update files appropriately

### Actual behaviour
The client starts and tries to update files, then crashes

### Steps to reproduce
1. Start Client
2. Client tries to update files
3. Client crashes

### Client configuration
Client version: 2.6.3

Operating system: macOS Catalina 10.15.6

OS language: German

Installation path of client: /Applications/owncloud.app

CrashID: 8283f0b7-3a1e-4968-815c-88a7c9623beb

**Comment by TheOneRing** [comment] 2020-09-10 11:17
Duplicate of: https://github.com/owncloud/client/issues/7967
Could you try the beta4 which will appear today, it should fix the issue :)

**Comment by TheOneRing** [comment] 2020-09-10 12:14
https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.2072-v270beta4/
https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.0.2074-v270beta4/

**Comment by hernandezac** [comment] 2020-09-10 12:23
Unfortunately it does not fix the issue. I tried both versions :( 

Crash ID: 9a46a5ac-532c-48ba-9043-4e039f899f42

**Comment by TheOneRing** [comment] 2020-09-10 12:32
Could you please run the client with `--logfile - --logdebug` I'll need about the last 20 line before the crash.

**Comment by TheOneRing** [comment] 2020-09-10 13:10
Maybe a full log could be handy....

**Comment by hernandezac** [comment] 2020-09-11 09:59
[logfile.txt](https://github.com/owncloud/client/files/5208177/logfile.txt)

**Comment by TheOneRing** [comment] 2020-09-11 11:21
Hi thx to the crash I'd I already had a crash log that pointed me to `OCC::DiscoveryPhase::findAndCancelDeletedJob (discoveryphase.cpp:185)` 
I already know that location, but your log file would tell me more, see https://github.com/owncloud/client/issues/8069#issuecomment-690250590 .

Could you send a full log, created that way to: `apps-<at>-owncloud.com`

**Comment by hernandezac** [comment] 2020-09-11 11:26
It would be awesome if you could tell me how to exactly run that command on a Mac terminal. Thank you in advance.

**Comment by TheOneRing** [comment] 2020-09-11 11:58
`/Applications/owncloud.app/Contents/MacOS/owncloud --logfile - --logdebug --logflush`

**Comment by hernandezac** [comment] 2020-10-28 13:24
I executed that command a few times getting the following error message:

qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen.

Abort trap: 6

Also reinstalled Qt but still getting the same error

**Comment by TheOneRing** [comment] 2020-10-28 13:32
I can't see how reinstalling Qt should be related to ownCloud.
Are you in a terminal with a Qt dev environment?

**Comment by hernandezac** [comment] 2020-10-28 13:44
I am using the regular terminal on mac. After executing the command:

/Applications/owncloud.app/Contents/MacOS/owncloud --logfile - --logdebug --logflush

I received the error: qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" ....
I dont know how to fix this issue

**Comment by phschaer** [comment] 2021-01-15 07:52
Sorry to say,  but this seems still unfixed in ownCloud-2.7.4.2934. Same behaviour as described before, same fatal error in `discoveryphase.cpp line 185`:

```
01-15 08:45:07:654 [ fatal default ]:	ENFORCE: "false" in file /tmp/drone-30Fn7JV6x3dZnIPo/drone/src/src/macos-64-clang/ownCloud-2.7.4.2934/src/libsync/discoveryphase.cpp, line 185
01-15 08:45:07:654 [ fatal default ]:	ENFORCE: "false" in file /tmp/drone-30Fn7JV6x3dZnIPo/drone/src/src/macos-64-clang/ownCloud-2.7.4.2934/src/libsync/discoveryphase.cpp, line 185
Dump file was written to: /private/var/folders/dw/q_d1pp6s3h75xpz7q4xmh2lc0000gn/T/A17A2ACD-7560-4B8A-A97B-20A8AB033DF3.dmp
```

CrashID is 83b26758-79e4-47be-9030-25eedb3b3b39

**Comment by TheOneRing** [comment] 2021-01-15 09:39
Would be awesome if you could also share the lines in front of the enforce.
And while we fixed some conditions that could lead to the crash, it seems there are more.
Your log might help us to fix some more.

**Comment by phschaer** [comment] 2021-01-15 09:55
I created a full debug log (more than 100 MByte):
```
$ ~ /Applications/owncloud.app/Contents/MacOS/owncloud --logfile owncloud-client.log --logdebug --logflush
01-15 10:45:54:173 [ fatal default ]:	ENFORCE: "false" in file /tmp/drone-30Fn7JV6x3dZnIPo/drone/src/src/macos-64-clang/ownCloud-2.7.4.2934/src/libsync/discoveryphase.cpp, line 185
Dump file was written to: /private/var/folders/dw/q_d1pp6s3h75xpz7q4xmh2lc0000gn/T/B86B7416-C1C6-40BB-98E2-E5E757AC44E7.dmp
```

Here are the last 20 lines of the log:
``` 
$ ~ tail -n 20 owncloud-client.log
01-15 10:45:54:171 [ info sync.discovery ]:	Discovered "DATA/GIRT-misc/temp/iz-solis_97.xml" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
01-15 10:45:54:171 [ info sync.discovery ]:	Processing "DATA/GIRT-misc/temp/iz-solis_98.xml" | valid: true/true/db | mtime: 1342021680/1342021680/0 | size: 2606494/2606494/0 | etag: "21cb6102a59f2e482729b818f7405708"//"" | checksum: "SHA1:cec02ad5e46249b7b739505cf901345febdd30ea"//"" | perm: 0x7fb574efa5a8//0x1116faf88 | fileid: "110099177occ7e8b30cf0"//"" | inode: 2035738/2035738/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
01-15 10:45:54:171 [ info sync.discovery ]:	Discovered "DATA/GIRT-misc/temp/iz-solis_98.xml" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
01-15 10:45:54:171 [ info sync.discovery ]:	Processing "DATA/GIRT-misc/temp/iz-solis_99.xml" | valid: true/true/db | mtime: 1342021680/1342021680/0 | size: 2718736/2718736/0 | etag: "ddae54e2e36c324606f3d9a4faf8b243"//"" | checksum: "SHA1:4ae37bae6ea1f015680675526ee333a276d14617"//"" | perm: 0x7fb574effa28//0x1116faf88 | fileid: "110099181occ7e8b30cf0"//"" | inode: 2035750/2035750/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
01-15 10:45:54:171 [ info sync.discovery ]:	Discovered "DATA/GIRT-misc/temp/iz-solis_99.xml" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
01-15 10:45:54:171 [ info sync.discovery ]:	STARTING "DATA/GIRT-misc/jte/c/ferro_build" OCC::ProcessDirectoryJob::ParentNotChanged "DATA/GIRT-misc/jte/c/ferro_build" OCC::ProcessDirectoryJob::NormalQuery
01-15 10:45:54:172 [ info sync.discovery ]:	STARTING "DATA/GIRT-misc/jte/c/include" OCC::ProcessDirectoryJob::ParentNotChanged "DATA/GIRT-misc/jte/c/include" OCC::ProcessDirectoryJob::NormalQuery
01-15 10:45:54:172 [ info sync.discovery ]:	STARTING "DATA/GIRT-misc/jte/java/build" OCC::ProcessDirectoryJob::ParentNotChanged "DATA/GIRT-misc/jte/java/build" OCC::ProcessDirectoryJob::NormalQuery
01-15 10:45:54:172 [ info sync.discovery ]:	STARTING "DATA/GIRT-misc/jte/java/doc" OCC::ProcessDirectoryJob::ParentNotChanged "DATA/GIRT-misc/jte/java/doc" OCC::ProcessDirectoryJob::NormalQuery
01-15 10:45:54:172 [ info sync.discovery ]:	STARTING "DATA/GIRT-misc/jte/java/src" OCC::ProcessDirectoryJob::ParentNotChanged "DATA/GIRT-misc/jte/java/src" OCC::ProcessDirectoryJob::NormalQuery
01-15 10:45:54:172 [ info sync.discovery ]:	STARTING "DATA/GIRT-misc/jte/java/test" OCC::ProcessDirectoryJob::ParentNotChanged "DATA/GIRT-misc/jte/java/test" OCC::ProcessDirectoryJob::NormalQuery
01-15 10:45:54:172 [ info sync.networkjob.etag ]:	Request Etag of QUrl("https://xxx/remote.php/dav/files/xxx/03-MSc_DigitalScience/IT Architecture/Stellenangebote/txt-Dateien SAR/Accenture.txt") FINISHED WITH STATUS "OK"
01-15 10:45:54:173 [ warning sync.discovery ]:	OC_ENFORCE(FAILING) "03-MSc_DigitalScience/IT Architecture/Stellenangebote/txt-Dateien SAR/Accenture.txt"
01-15 10:45:54:173 [ warning sync.discovery ]:	instruction == CSYNC_INSTRUCTION_REMOVE false
01-15 10:45:54:173 [ warning sync.discovery ]:	((*it)->_type == ItemTypeVirtualFile && instruction == CSYNC_INSTRUCTION_NEW) false
01-15 10:45:54:173 [ warning sync.discovery ]:	((*it)->_isRestoration && instruction == CSYNC_INSTRUCTION_NEW)) false
01-15 10:45:54:173 [ warning sync.discovery ]:	instruction CSyncEnums::CSYNC_INSTRUCTION_IGNORE
01-15 10:45:54:173 [ warning sync.discovery ]:	(*it)->_type CSyncEnums::ItemTypeFile
01-15 10:45:54:173 [ warning sync.discovery ]:	(*it)->_isRestoration  true
01-15 10:45:54:173 [ fatal default ]:	ENFORCE: "false" in file /tmp/drone-30Fn7JV6x3dZnIPo/drone/src/src/macos-64-clang/ownCloud-2.7.4.2934/src/libsync/discoveryphase.cpp, line 185
```

**Comment by TheOneRing** [comment] 2021-01-15 11:49
Thx that looks more helpful.
Btw could you also share your server version?

**Comment by phschaer** [comment] 2021-01-15 12:50
The server seems to be running on 10.5.0 ("10.5.0.10-sciebo"), see https://th-koeln.sciebo.de/status.php

**Comment by TheOneRing** [comment] 2021-01-15 12:55
Ok hopefully the last, question, is the affected file "03-MSc_DigitalScience/IT Architecture/Stellenangebote/txt-Dateien SAR/Accenture.txt" in a shared folder, and if so what are the permissions.

**Comment by phschaer** [comment] 2021-01-15 13:05
Yes, this is a file that is located in a folder that was shared with me by somebody else. 

It's a private link, but I don't know where to check on the specific access permissions...

**Comment by phschaer** [comment] 2021-01-28 13:47
Is there anything else, I can do to help? The issue still persists.

**Comment by TheOneRing** [comment] 2021-01-28 14:49
Not really I prepared some changes that are supposed the prevent this from happening but they will go to 2.8 so it will still take some time...

**Comment by hernandezac** [comment] 2021-04-27 09:57
Hi everyone,

I hope I found something that might be relevant. I checked the log provided by @phschaer and compared it to mine. It seems that I had the same problem with a shared folder that had spaces in its name
(/IT Architecture/):

OC_ENFORCE(FAILING) "03-MSc_DigitalScience/IT Architecture/Stellenangebote/txt-Dateien SAR/Accenture.txt"

After removing the spaces and rebooting it seems to work ... at least until now.

**Comment by michaelstingl** [comment] 2021-06-24 12:46
Potentially related issue on Central:
- https://central.owncloud.org/t/crash-on-startup/31909
- https://central.owncloud.org/t/owncloud-client-for-windows-crashes-after-first-boot/32539
- https://central.owncloud.org/t/owncloud-is-crashing/32586
- https://central.owncloud.org/t/owncloud-crashed/32733
([Search query](https://central.owncloud.org/search?q=Crash%20category%3A59%20order%3Alatest_topic))

**Comment by michaelstingl** [comment] 2021-07-14 14:56
I just had a quick conversation with the development team. This is our current understanding:

- Older and current client versions wrote entries with inconsistent permissions to the sync journal (SQLite database in every sync folder)
- 2.9 pre-release client no longer creates entries with inconsistent permissions
- But there are often old entries that are still invalid (no auto-healing yet)

Workaround:
- Update to latest 2.9 daily build:
 https://download.owncloud.com/desktop/ownCloud/daily/2.9/
- Close the client
- Delete the hidden SQLite files in every sync folder
- When you start the client, it will re-index all data and will re-create the sync journal / SQLite database

2.9 beta in the next few days will behave better. 

I’ll update the post with more detailed instructions later tonight when I’m back at my desk.

**Comment by michaelstingl** [comment] 2021-08-12 14:25
We think we have a fix in the latest dailies:
- https://download.owncloud.com/desktop/ownCloud/daily/2.9/mac/?sort=time&order=desc
- https://download.owncloud.com/desktop/ownCloud/daily/2.9/win/?sort=time&order=desc

I would be very grateful if anyone could test-drive and verify.

**Comment by Belhorus** [comment] 2021-09-07 08:24
We are getting the same issue with the most recent public build - attached log.
I have tried to use command line to install somewhere else and used the GUI as well.
If you think the most recent daily could fix this, I'd be happy to try it, but wanted a touch of advise on this
- Delete the hidden SQLite files in every sync folder (How would i do this?)

09-07 16:39:11:551 [ info gui.application ]:"################## ownCloud locale:[en_US] ui_lang:[] version:[2.8.2 (build 4246)] os:[Windows 10 (10.0)]"
09-07 16:39:11:551 [ info gui.application ]:Using "en_US" translation
09-07 16:39:11:556 [ info gui.application ]:VFS windows plugin is available
09-07 16:39:11:557 [ info gui.application ]:VFS suffix plugin is available
09-07 16:39:11:557 [ info gui.socketapi ]:server started, listening at  "\\\\.\\pipe\\ownCloud-Profile"
09-07 16:39:11:558 [ info gui.folder.manager ]:setting remote poll timer interval to 30000 msec
09-07 16:39:11:584 [ info gui.account.manager ]:Restored:  0  unknown certs.
09-07 16:39:12:109 [ info gui.application ]:Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
09-07 16:39:12:184 [ info gui.folder.manager ]:Setup folders from settings file
09-07 16:39:12:185 [ warning sync.database ]:Could not find a writable database path "C:/Users/Profile/ownCloud/.sync_8f80b72c718e.db" "The system cannot find the path specified."
09-07 16:39:12:186 [ info plugins ]:Created VFS instance from plugin "owncloudsync_vfs_win"
09-07 16:39:12:186 [ info sync.database ]:Detected filesystem "NTFS" for "C:/Users/Profile/ownCloud/.sync_8f80b72c718e.db"
09-07 16:39:12:186 [ warning gui.folder ]:Broken symlink: "C:/Users/Profile/ownCloud/"
09-07 16:39:12:187 [ info sync.configfile ]:Adding system ignore list to csync: "C:/Program Files (x86)/owncloud/sync-exclude.lst"
09-07 16:39:12:218 [ warning sync.vfs.win ]:Could not find StorageFolder for "C:\\Users\\Profile\\ownCloud" error: "WindowsError: ffffffff80070002: The system cannot find the file specified."
09-07 16:39:13:202 [ fatal default ]:CfConnectSyncRoot: C:\Users\Profile\ownCloud error: WindowsError: ffffffff80070002: The system cannot find the file specified.

**Comment by TheOneRing** [comment] 2021-09-07 09:16
> We are getting the same issue with the most recent public build - attached log.
> I have tried to use command line to install somewhere else and used the GUI as well.
> If you think the most recent daily could fix this, I'd be happy to try it, but wanted a touch of advise on this
> 
> * Delete the hidden SQLite files in every sync folder (How would i do this?)
> 
> 09-07 16:39:11:551 [ info gui.application ]:"################## ownCloud locale:[en_US] ui_lang:[] version:[2.8.2 (build 4246)] os:[Windows 10 (10.0)]"
> 09-07 16:39:11:551 [ info gui.application ]:Using "en_US" translation
> 09-07 16:39:11:556 [ info gui.application ]:VFS windows plugin is available
> 09-07 16:39:11:557 [ info gui.application ]:VFS suffix plugin is available
> 09-07 16:39:11:557 [ info gui.socketapi ]:server started, listening at "\\.\pipe\ownCloud-Profile"
> 09-07 16:39:11:558 [ info gui.folder.manager ]:setting remote poll timer interval to 30000 msec
> 09-07 16:39:11:584 [ info gui.account.manager ]:Restored: 0 unknown certs.
> 09-07 16:39:12:109 [ info gui.application ]:Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
> 09-07 16:39:12:184 [ info gui.folder.manager ]:Setup folders from settings file
> 09-07 16:39:12:185 [ warning sync.database ]:Could not find a writable database path "C:/Users/Profile/ownCloud/.sync_8f80b72c718e.db" "The system cannot find the path specified."
> 09-07 16:39:12:186 [ info plugins ]:Created VFS instance from plugin "owncloudsync_vfs_win"
> 09-07 16:39:12:186 [ info sync.database ]:Detected filesystem "NTFS" for "C:/Users/Profile/ownCloud/.sync_8f80b72c718e.db"
> 09-07 16:39:12:186 [ warning gui.folder ]:Broken symlink: "C:/Users/Profile/ownCloud/"
> 09-07 16:39:12:187 [ info sync.configfile ]:Adding system ignore list to csync: "C:/Program Files (x86)/owncloud/sync-exclude.lst"
> 09-07 16:39:12:218 [ warning sync.vfs.win ]:Could not find StorageFolder for "C:\Users\Profile\ownCloud" error: "WindowsError: ffffffff80070002: The system cannot find the file specified."
> 09-07 16:39:13:202 [ fatal default ]:CfConnectSyncRoot: C:\Users\Profile\ownCloud error: WindowsError: ffffffff80070002: The system cannot find the file specified.

You deleted the folder C:\Users\Profile\ownCloud please create a new one.

**Comment by Belhorus** [comment] 2021-09-08 06:40
Hi, I tried that, 
After creating it and running the Owncloud, we still had near instant crash. It mentions the owncloud2 folder now, does that one have to be created as well?

New Log:
09-08 16:35:29:778 [ info gui.application ]:"################## ownCloud locale:[en_US] ui_lang:[] version:[2.8.2 (build 4246)] os:[Windows 10 (10.0)]"
09-08 16:35:29:778 [ info gui.application ]:Using "en_US" translation
09-08 16:35:29:794 [ info gui.application ]:VFS windows plugin is available
09-08 16:35:29:794 [ info gui.application ]:VFS suffix plugin is available
09-08 16:35:29:794 [ info gui.socketapi ]:server started, listening at  "\\\\.\\pipe\\ownCloud-Profile"
09-08 16:35:29:794 [ info gui.folder.manager ]:setting remote poll timer interval to 30000 msec
09-08 16:35:29:828 [ info gui.account.manager ]:Restored:  0  unknown certs.
09-08 16:35:32:722 [ info gui.application ]:Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
09-08 16:35:32:814 [ info gui.folder.manager ]:Setup folders from settings file
09-08 16:35:32:815 [ info plugins ]:Created VFS instance from plugin "owncloudsync_vfs_win"
09-08 16:35:32:815 [ info sync.database ]:Detected filesystem "NTFS" for "C:/Users/Profile/ownCloud/.sync_8f80b72c718e.db"
09-08 16:35:32:816 [ info sync.configfile ]:Adding system ignore list to csync: "C:/Program Files (x86)/owncloud/sync-exclude.lst"
09-08 16:35:32:890 [ warning sync.vfs.win ]:Could not check for or unregister previous StorageFolder for "C:\\Users\\Profile\\ownCloud" "Element not found."
09-08 16:35:33:882 [ info sync.database ]:sqlite3 version "3.31.1"
09-08 16:35:33:882 [ info sync.database ]:sqlite3 locking_mode= "exclusive"
09-08 16:35:33:884 [ info sync.database ]:sqlite3 journal_mode= "wal"
09-08 16:35:33:898 [ info sync.database ]:sqlite3 synchronous= "NORMAL"
09-08 16:35:33:921 [ info sync.database ]:Forcing remote re-discovery by deleting folder Etags
09-08 16:35:33:924 [ info gui.folder.manager ]:Adding folder to Folder Map  OCC::Folder(0x197db065ef0) "1"
09-08 16:35:33:927 [ info gui.folder.manager ]:Schedule folder  "1"  to sync!
09-08 16:35:33:927 [ info gui.folder.manager ]:Folder is not ready to sync, not scheduled!
09-08 16:35:33:937 [ info gui.application ]:Sync state changed for folder  "https://box.kapani.com.au/owncloud/remote.php/webdav/" :  "Not yet Started"
09-08 16:35:33:938 [ warning sync.database ]:Could not find a writable database path "C:/Users/Profile/ownCloud2/.sync_36913b68f2c9.db" "The system cannot find the path specified."
09-08 16:35:33:938 [ info plugins ]:Created VFS instance from plugin "owncloudsync_vfs_win"
09-08 16:35:33:938 [ info sync.database ]:Detected filesystem "NTFS" for "C:/Users/Profile/ownCloud2/.sync_36913b68f2c9.db"
09-08 16:35:33:938 [ warning gui.folder ]:Broken symlink: "C:/Users/Profile/ownCloud2/"
09-08 16:35:33:939 [ info sync.configfile ]:Adding system ignore list to csync: "C:/Program Files (x86)/owncloud/sync-exclude.lst"
09-08 16:35:33:947 [ warning sync.vfs.win ]:Could not find StorageFolder for "C:\\Users\\Profile\\ownCloud2" error: "WindowsError: ffffffff80070002: The system cannot find the file specified."
09-08 16:35:34:940 [ fatal default ]:CfConnectSyncRoot: C:\Users\Profile\ownCloud2 error: WindowsError: ffffffff80070002: The system cannot find the file specified.

**Comment by michaelstingl** [comment] 2021-09-08 08:28
> 09-08 16:35:29:778 [ info gui.application ]:"################## ownCloud locale:[en_US] ui_lang:[] version:[2.8.2 (build 4246)] os:[Windows 10 (10.0)]"

Please use 2.9.0-rc2:
https://github.com/owncloud/client/releases/tag/v2.9.0-rc2

**Comment by TheOneRing** [comment] 2021-09-08 09:05
Yes removing the snyc root is not supported, either create all needed folders or remove your config https://doc.owncloud.com/desktop/advanced_usage/configuration_file.html

**Comment by Belhorus** [comment] 2021-09-13 09:07
> Yes removing the snyc root is not supported, either create all needed folders or remove your config https://doc.owncloud.com/desktop/advanced_usage/configuration_file.html

Thanks, I just had to remove the config files and it worked. Cheers,

**Closed** 2021-09-13 09:15 UTC
