### ISSUE TITLE
[1.8.0] Client crashing when not connected (for example password invalid) and sharing file

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#2811] opened 2015-02-10 11:55 UTC
1. Login to an oC instance
2. Move the ownCloud instance away to another subfolder
3. Start the client again – get asked for the password
4. Ignore the prompt
5. Share a file => Client crashes

**Comment by LukasReschke** [comment] 2015-02-10 11:58
(in my case the server returned a fatal error since I was refactoring some other stuff)

**Comment by LukasReschke** [comment] 2015-02-10 12:06
Should also be reproducible by changing the password of an user account

**Comment by lmaestro** [comment] 2015-02-11 13:05
I have tested it and I am able to reproduce the crash.
Steps to reproduce:
1. Sync the account in the your local folder
2. change the password from the server 
3. Restart the client -> Because if you tried to share by link before restart there are no problem 
4. Start the client again – get asked for the password, ignore it
5. Go to the local folder and share by link 

Logs : https://gist.github.com/lmaestro/3affad88d862f042fc4a

**Comment by lmaestro** [comment] 2015-02-12 14:28
Fixed in version 1.8.0-nightly20150212(build 2010)

**Closed** 2015-02-12 15:51 UTC
Labels: approved by qa, bug, gold-ticket, sev2-high
