### ISSUE TITLE
[QA] renaming a dehydrated folder to an excluded name leads to data loss

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8217] opened 2020-11-09 21:02 UTC
Seen with ownCloud client 2.7.0 RC3 on windows 10 or Linux using VFS.

  *  With the web UI on the server create a folder 'Music', with a few files in them. (PNG files in my case)
  *  wait until sync finishes.
  * make sure the status column shows a cloud icon. If needed click and choose 'Free up space'
  *  on the client rename the folder to one of the excluded filenames. e.g. Music~
  *  the folder gets removed from the server.

On Linux, the local files are placeholders only.
On windows the local files are broken. See #8216 
Other clients will also delete their copy, as the copy on the server is deleted. Thus no copy remains.

Expected behaviour: Do not delete on the server. Details to be determined. (so that windows could actually succeed downloading.)

**Comment by TheOneRing** [comment] 2020-11-10 14:42
Duplicate of https://github.com/owncloud/client/issues/8216

**Closed by TheOneRing** 2020-11-10 14:42 UTC
Labels: p2-high
