### ISSUE TITLE
Forbidden .bat file sync

### ISSUE THREAD

**Issue by MU7L3Y** [owncloud/client#4904] opened 2016-05-26 04:38 UTC
### Expected behaviour
I should be allowed to sync .bat files between the server and client.

### Actual behaviour
All bat files get blacklisted as forbidden.

### Steps to reproduce
Place a .bat file in a sync folder to upload and the error will appear.

### Server configuration
Operating system: Linux Shared Hosting

Web server: Apache

Database: MySQL

PHP version: 5.5.32

ownCloud version: 8.2.5

Storage backend:

### Client configuration
Client version: 2.2.0

Operating system: Windows Server 2012 or Window 7 Pro

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
```|0|Tekla_Model_Startup/152602.BAT|INST_NEW|Up|1464227312||208||2|Error downloading http://website/cloud/remote.php/webdav/17/Tekla_Model_Startup/152602.BAT - server replied: Forbidden|403|0|0|||INST_NONE|
|0|Tekla_Model_Startup/152602.BAT|INST_NEW|Up|1464227312||208||6|Continue blacklisting: Error downloading http://website/cloud/remote.php/webdav/17/Tekla_Model_Startup/152602.BAT - server replied: Forbidden|403|0|0|||INST_NONE|```

2. Web server error log:
```[19-May-2016 06:17:07 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Error 47 interacting with memcached : SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY' in /home/website/public_html/cloud/lib/private/memcache/memcached.php:187
Stack trace:
#0 /home/website/public_html/cloud/lib/private/memcache/memcached.php(80): OC\Memcache\Memcached->verifyReturnCode()
#1 /home/website/public_html/cloud/lib/autoloader.php(178): OC\Memcache\Memcached->set('OCP\\Util', Array, 60)
#2 [internal function]: OC\Autoloader->load('OCP\\Util')
#3 /home/website/public_html/cloud/index.php(51): spl_autoload_call('OCP\\Util')
#4 {main}
  thrown in /home/website/public_html/cloud/lib/private/memcache/memcached.php on line 187```

3. ownCloud log (data/owncloud.log):
empty

**Comment by RealRancor** [comment] 2016-05-26 11:30
@MU7L3Y Try to contact the support of your shared hoster and ask them if they have any security mechanisms running which disallows such .bat files.

**Comment by MU7L3Y** [comment] 2016-05-26 11:32
I can upload/download them through ftp just fine though?

**Comment by MU7L3Y** [comment] 2016-05-26 11:32
I can upload/download them through ftp just fine though?
On 26 May 2016 9:30 pm, "RealRancor" <notifications@github.com> wrote:

@MU7L3Y <https://github.com/MU7L3Y> Try to contact the support of your
shared hoster and ask them if they have any security mechanisms running
which disallows such .bat files.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/owncloud/client/issues/4904#issuecomment-221846353>

**Comment by RealRancor** [comment] 2016-05-26 11:33
FTP is not equal WebDAV via HTTP.

**Comment by MU7L3Y** [comment] 2016-05-26 11:35
Ok I will ask them thanks.

**Comment by RealRancor** [comment] 2016-05-26 11:44
Might be caused by a mod_security rule for example:

https://sourceforge.net/p/mod-security/mailman/message/18648527/

**Comment by danimo** [comment] 2016-05-26 12:14
Not a Client issue anyway. Closing.

**Closed by danimo** 2016-05-26 12:14 UTC
