### ISSUE TITLE
[Windows] Enhancement: Use a nice foldericon for local ownCloud folder

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2874] opened 2015-02-21 11:16 UTC
Under windows (7 in my case) it would be nice to have an own foldericon for the local storage of ownCloud. I did not like the standard icon of the folder, so i assigned the oc-program icon to it:
![2015-02-21 12_11_43-favoriten](https://cloud.githubusercontent.com/assets/2804301/6313904/39b337dc-b9c3-11e4-907f-f3bfe6d33263.jpg)

So a icon like the other folders (eg DropBox) would be realy nice. Are there any plans for that?

**Comment by danimo** [comment] 2015-02-21 13:11
Duplicate of #455

**Closed** 2015-02-21 13:11 UTC
