### ISSUE TITLE
Moving then immediately renaming a large folder results in a reupload

### ISSUE THREAD

**Issue by strugee** [owncloud/client#4370] opened 2016-01-19 05:16 UTC
I just put a huge (3+ GB with ~20 MB files) folder in my ownCloud, and it uploaded to the server. Then I moved it to another folder in my ownCloud and immediately renamed it. This resulted in the entire 3 GB being uploaded again, which is obviously unideal.

I'm on version 2.1.0 of the client.

**Comment by guruz** [comment] 2016-01-19 09:03
@ogoffart I think this would not have happened if there was another sync in between which refreshes the FileIDs and ETags?

**Comment by ogoffart** [comment] 2016-01-19 09:35
Please use the issue template:  https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

Normaly this should not happen as we do move dectection.

Was the upload completed?
Can you provide log files and exact steps to reproduce?

thanks.

**Comment by strugee** [comment] 2016-01-19 18:40
Whoops, my apologies. Forgot that you guys want extra info. Here it is:

### Expected behaviour

When I move a large folder and then immediately rename it, the client should recognize this.

### Actual behaviour

When I moved a large folder with many files and then renamed it, the client reuploaded the folder.

### Steps to reproduce

1. Create a folder in the ownCloud directory
2. Fill it with several hundred ~20MB files
3. Move the folder to a different location in the ownCloud directory
4. Immediately rename the folder

### Server configuration

Operating system: Debian Jessie

Web server: Apache

Database: MySQL

PHP version: 5.6.14-0+deb8u1

ownCloud version: 8.2.2 Community Edition

Storage backend: btrfs on a local (SATA) disk array

### Client configuration

Client version: 2.1.0

Operating system: Mac OS X El Capitan

OS language: en-US

Installation path of client: `/Applications/owncloud.app`

**Comment by strugee** [comment] 2016-01-19 18:40
I'll have to provide logs when I get home and am in front of the relevant machine.

**Comment by strugee** [comment] 2016-01-19 18:58
[Here][1] are the webserver logs. Note I've grepped for the relevant IP address so this includes *only* the requests related to this bug.

 [1]: http://sprunge.us/JUDA

**Comment by strugee** [comment] 2016-01-19 19:00
I should also explain: `/scratch` is the folder originally being uploaded to. Then `/scratch` was moved to `/photos/scratch`, followed by an immediate rename to `/photos/Interleague 2016`.

**Comment by ogoffart** [comment] 2016-01-20 10:02
I was able to reproduce the bug.  I'll try to see what causes it

**Comment by ogoffart** [comment] 2016-01-20 10:24
I found a way to reproduce the problem:

1) have lots of files in directory "dir1"
2) do  `mkdir dir2 && mv dir1/* dir2`
3) DURING the sync (which takes time because of the many moves) do `mkdir dir3 && mv dir2/* dir3/`
4) observe that files are PUT in the next sync:

The reason, we try to get the inode in SyncJournalFileRecord::SyncJournalFileRecord to save in the database after the MOVE.   But unfortunately, the files where already moved somewhere else on the file system at this point

**Comment by ogoffart** [comment] 2016-01-20 13:06
Should be fixed in 2.1.1

**Comment by Dianafg76** [comment] 2016-01-27 08:37
I tested this issue, and it is working OK
Desktop Version 2.1.1rc1 (build 3069)
Server v 8.2.2

**Closed by Dianafg76** 2016-01-27 08:37 UTC
Labels: approved by QA, Performance, sev4-low
