### ISSUE TITLE
owncloudcmd is too verbose

### ISSUE THREAD

**Issue by guettli** [owncloud/client#5517] opened 2017-02-06 06:19 UTC
I am running `owncloudcmd version 2.2.3`

Even with "--silent" option, the command line tool is way to verbose.

Here is an example. This is the output of the start of a call. 

My problem: If there is an error. It is very hard for the human eye to find the relevant error message.

It would be very nice to introduce log-levels. I guess most of the current output is of level "debug". 

One "info" message per file transfer would be nice. Sometimes "less is more".

```
===> owncloudcmd --silent --non-interactive -u bilder -n  Bilder http://om/owncloud/remote.php/webdav
Set proxy configuration to use system configuration 
sqlite3 version "3.11.0" 
sqlite3 journal_mode= "wal" 
void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect" and starting new transaction 
Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId") 
void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add inode index" and starting new transaction 
void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add path index" and starting new transaction 
Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration", "renameTarget") 
void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect End"  
There are 73334968320 bytes available at "Bilder/" and at least 50000000 are required 
=====sync with existing DB 
=====Using Qt 4.8.7 
void OCC::SyncEngine::startSync() ====NOT Using Selective Sync 
#### Discovery start #################################################### >> 
=====Server "" "rootEtagChangesNotOnlySubFolderEtags=0" 
void OCC::SyncEngine::startSync() ""  QUrl( "owncloud://om/owncloud/remote.php/webdav/" )  
```

**Comment by ogoffart** [comment] 2017-02-06 15:20
Duplicate of Issue #5196
(Fixed in 2.3)

**Closed by ogoffart** 2017-02-06 15:20 UTC
Labels: Design & UX, Enhancement
