### ISSUE TITLE
Windows: Changing time zone changes timestamp in the sync journal

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4439] opened 2016-02-05 16:25 UTC
@msrex had an alarming finding on his windows installation: For some reason the client tried to re-upload a lot of data.

I was debugging and found out that the sync journal contains a last-modified timestamp that is exactly fife hours away from the real UTC timestamp. The time zone of the windows machine is set to ETC, which exactly is fife hours away from UTC. 

The header that is written to the sync journal is taken from the HTTP last-modified header during download job. I tunneled that through mitmproxy and it shows that the Last-modified header is correctly on UTC. 

The problem disappeared when we rebooted the windows machine. However, if the timezone is changed on windows, the timestamps are changed again. That is also visible in the Activity Tab which also uses parsed timestamps, in that case from JSON format.

The suspicion is that the `QVariant::toDateTime` function is malfunctioning somehow.

I suggest to keep this as a gold ticket for 2.1.1 until we know if that is a regression and how this is triggered. 

@ogoffart for help please.

@cmonteroluque and @MTRichards FYI.

**Comment by dragotin** [comment] 2016-02-05 17:02
maybe related: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/792

Maybe we also need to add the _tzset() when stat'ing?

**Comment by ogoffart** [comment] 2016-02-05 17:29
> The header that is written to the sync journal is taken from the HTTP last-modified header during download job

And then we set the modtime to this file, and then we check again what is the modtime.  (in PropagateDownloadFileQNAM::downloadFinished)

```
    FileSystem::setModTime(_tmpFile.fileName(), _item->_modtime);
    // We need to fetch the time again because some file systems such as FAT have worse than a second
    // Accuracy, and we really need the time from the file system. (#3103)
    _item->_modtime = FileSystem::getModTime(_tmpFile.fileName());

```

What was the version and the build of the client? 
Do we have any logs?
How does the file system time compare to the server time and to the database time? Where did it go wrong?
Was the timezone changed while the program was running?

The `Activity Tab`  issue  might be totally unrelated

**Comment by ogoffart** [comment] 2016-02-05 17:41
Note that there was a bug in FileSystem::getModTime on windows in 2.1.0 which was fixed shortly after the release in (fixed in commit cf5b1e401c0e0c8284bcfd8c12721a09175ed1b4 )

**Comment by dragotin** [comment] 2016-02-06 09:19
Hm, indeed I tested with nightly build http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.5824-nightly20160206-setup.exe now and was not able to reproduce a problem by switching time zones around.

@msrex could you please give the link above a test to see if that works for you?

**Comment by Dianafg76** [comment] 2016-02-08 09:47
@dragotin I tested this issue and I can't reproduce
.- WINDOWS 10: Desktop v 1.8.4, 2.1.0 (build 5683), 2.1.1RC1
.- WINDOWS 2008 R2 Enterprise: Desktop v 2.1.0 (build 5683)

### Steps to reproduce
1. Intall Desktop v 2.1.0 with Admin
2. All folders / files are synchronized
3. Go to Settings/Date&Time
4. e.g Time zone (UTC +12:00 Fiji)
5. Go to the Desktop Client
6. Go to Activity Tab and the client don't tried to re-upload

**Comment by ogoffart** [comment] 2016-02-08 10:11
@Dianafg76 did you make sure that a sync was trigered?  (i.e. modifying a single file, only this file should be uploaded)

**Comment by Dianafg76** [comment] 2016-02-08 10:12
@ogoffart Yes

**Comment by dragotin** [comment] 2016-02-08 11:51
I also tested again with 2.1.1 RC and it is not longer reproduceable for me (Win7).

Moving to next milestone as this should not longer block 2.1.1

**Comment by msrex** [comment] 2016-02-08 15:25
I tried with the Feb 8, 2016 nightly on Windows.

The activity tab is still reproducible the same way it was last Thursday in Nbg:
- install the client
- Connect to server with an account that has some activity in it
- Select a folder to sync (can be small)
- Start sync
- At any time during the discovery phase, the sync phase or just while waiting: changing the timezone changes the time in the Activity tab

Another scenario:
- Stop the client after the sync is completed
- Change the timezone
- Start the client
-> the activity tab shows correct time. Change the timezone again, it shows incorrect times.
Is a different codepath used during the initial time conversion for the activity tab vs during a later update?

Another scenario:
- Trigger a sync by changing a file without restarting the client after a successful sync
-> sync works as expected

- Change the timezone (during sync or while paused or while waiting):
-> sync works as expected

Good news is: I have with a quick test been unable to reproduce the re-upload of files. Only the activity tab conversion seems to be affected. 

I will try the full sync of a huge folder next and see what happens.

**Comment by msrex** [comment] 2016-02-09 13:39
The full sync of all 57k files went well and no re-sync (which happens with the 2.1.0 released client) took place. So for syncing the patch mentioned above seems to fix the issue.

**Comment by dragotin** [comment] 2016-02-09 16:16
I tested again syncing to a NTFS formatted SD-Card with 2.1.1. RC2 and sync works. The activity tab display is confused by changing the time zone. Maybe that is a bug in the activity view however.

**Comment by dragotin** [comment] 2016-02-15 17:00
@Dianafg76 to test this, please check the activity view on Windows. During the client runs, change the windows timezone setting. The display of the timespan when the activity happened must not change.

**Comment by Dianafg76** [comment] 2016-02-16 08:01
I tested this issue and is working OK. When the client is running , I can change the time zone setting screens, and the activity view is no change
Desktop v ownCloud-2.2.0.5855-nightly20160216-setup.exe (WIN 10)
Server v 8.2.2

**Closed by Dianafg76** 2016-02-16 08:01 UTC
Labels: approved by QA, bug
