### ISSUE TITLE
[QA] Selective sync dropdown gets confused with multiple servers/multiple sync connetions

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10051] opened 2022-08-22 13:37 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen while reproducing https://central.owncloud.org/t/no-more-possibility-to-select-subfolders-for-sync-with-last-release-2-11-0-build-8354/38857 on Win10_21H1

* Connect to two different serves, one with VFS, one without.
* On the server with VFS, add another sync folder connection for the Documents folder, this time without VFS
* The dropdown triangle for the selective sync subfolder tree appears. OK
* When clicking on the dropdown triangle, it disappears, after a few seconds. (Documents has no subfolders)
* While the sync is still running, add a subfolder to the Documents folder via web UI. Hit 'Restart Sync'
  - the ongoing sync restarts, but
  - no dropdown triangle appears.  BAD.
* While that is still syncing, hit 'Force sync' on the other sync folder connection (with VFS)  of this server.
  - The client aborts the ongoing sync, and starts a sync run there.
  - A dropdown triangle for selective sync appears, although this is a VFS connection. BAD.
  - The dropdown triangle can be clicked, it toggles between pointing downwards and rightwards. BAD.
![image](https://user-images.githubusercontent.com/1108546/185933335-391d91d6-e218-43ef-8f2e-f9f3e19ce353.png)
![image](https://user-images.githubusercontent.com/1108546/185933354-a7d92644-6db9-4401-bc9e-4b6953cafd91.png)

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

Selective sync dropdowns are available, when there is no VFS and vice versa.

### Actual behavior

Not random.

**Comment by jnweiger** [comment] 2022-08-22 14:15
Not reproducable. Happened only once.
Wild guess: Maybe it is something similar like https://github.com/owncloud/client/issues/9954

**Comment by fmoc** [comment] 2022-08-25 12:13
May be fixed with upcoming RC release. Since you can't even reproduce it yourself, I think we can close this issue for now.

**Closed by fmoc** 2022-08-25 12:13 UTC
Labels: QA:team

**Comment by michaelstingl** [comment] 2022-08-26 07:28
Please test with the 2.11.1 RC:
https://download.owncloud.com/desktop/ownCloud/testing/2.11.1-rc1.8388/
