### ISSUE TITLE
OC Client crashes when new certificate is rejected (wifi hotspot)

### ISSUE THREAD

**Issue by giovi321** [owncloud/client#4898] opened 2016-05-24 13:57 UTC
### Expected behaviour
When owncloud client asks me whether to accept or not a new certificate from the server (it happens every time I connect to a wifi hotspot that requires authentication in the browser) and I answer no (reject the certificate), it should either wait to get a new certificate (the original one from the server and not the one from the wifi hotspot) and ask me again if I accept (if it is a new certificate) or just wait for the new certificate to arrive and start automatically syncing.

### Actual behaviour
When I connect to a wifi hotspot that requires a login, owncloud client prompts me whether to accept or not the new ssl certificate (the wifi hotspot sends its own ssl certificate). If I click no (ie: I reject the certificate), after I login in the wifi hotspot, owncloud needs to be restarted to make sure syncing begins again.

### Steps to reproduce
1. Connect to a wifi hotspot which requires authentication
2. OC Client asks whether to accept or not the new certificate
3. Click no
4. Log in the wifi hotspot
5. Oc doesn't begin to sync again until restarted (and sometimes crashes)

### Server configuration
Operating system:
Debian 8
Web server: 
Apache
Database:
MySql
PHP version:
5.6.20-0+deb8u1
ownCloud version:
9.0.2
Storage backend:

### Client configuration
Client version:
2.1.1 (build 5837)
Operating system:
Windows 7
OS language:
Italian
Installation path of client:
C:\Program Files (x86)\ownCloud\

**Comment by guruz** [comment] 2016-05-25 05:58
Did it ask you to send this to the crash reporter?

FYI @danimo

**Comment by guruz** [comment] 2016-05-25 05:59
@giovi321 I just noticed you are on 2.1.1.
Would you please try a 2.2.1 nightly? We're about to release 2.2.1, but want to be sure this crash is fixed.
http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6112-nightly20160525-setup.exe

**Comment by giovi321** [comment] 2016-05-25 06:41
Well, it doesn't actually crash every time. Sometimes it just stops syncing and the program has to be restarted. I'll download and try it anyway.                                                                                                                                                                                                                                                                                                                                                        From:notifications@github.comSent:25 May 2016 7:59 amTo:client@noreply.github.comReply to:reply@reply.github.comCc:write@giovi.cr; mention@noreply.github.comSubject:Re: [owncloud/client] OC Client crashes when new certificate is rejected (wifi hotspot) (#4898)  @giovi321 I just noticed you are on 2.1.1.
Would you please try a 2.2.1 nightly? We're about to release 2.2.1, but want to be sure this crash is fixed.
http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6112-nightly20160525-setup.exe

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by ckamm** [comment] 2016-05-27 09:26
I don't have enough info to look at the crash, but will look at the client getting permanently stuck when rejecting a certificate.

**Comment by ckamm** [comment] 2016-05-27 09:54
@danimo Could you review the pull request at https://github.com/owncloud/client/pull/4911 ?

**Comment by ckamm** [comment] 2016-05-27 10:09
@giovi321 The patch is merged, could you test once a new nightly becomes available at http://download.owncloud.com/desktop/daily/ ?

Note that I did **not** address the crash that was also reported! I can't reproduce it.

**Comment by giovi321** [comment] 2016-05-27 12:14
@ckamm I just downloaded the new version, on monday I will be able to check if I can reproduce the problem of the syncing getting stuck when certificate is rejected.
However, I cannot reproduce the crash when the certificate is rejected as it doesn't happen every time, but only every now and then.

**Comment by ckamm** [comment] 2016-05-27 12:19
@giovi321 Thanks for testing! Occasional crashes are the hardest to track down - if you figure out anything else about it, let us know. :)

**Comment by guruz** [comment] 2016-05-27 12:44
@giovi321 You need to download the new version on monday (or earliest tomorrow), the ones there currently are created this morning, so without this fix. thanks.

**Comment by guruz** [comment] 2016-06-01 07:25
@giovi321 Any news from you? :)

**Comment by guruz** [comment] 2016-06-03 11:11
@giovi321 Did you have a chance to test the nightly builds of 2.2.1?
http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6135-nightly20160603-setup.exe

**Comment by giovi321** [comment] 2016-06-06 11:29
I'm sorry for the delay. I was abroad and had no chances to test it. I 
tested it today and the version 
testpilotcloud-2.2.1.6124-nightly20160530-setup works perfectly! the 
problem is solved.

Excuse me again for the delay, and thank you for fixing it.


On 01/06/2016 09:25, Markus Goetz wrote:
>
> @giovi321 <https://github.com/giovi321> Any news from you? :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/owncloud/client/issues/4898#issuecomment-222913924>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGJR-7h5IA2oqJ-ybBhqJVuEAgsUqrKjks5qHTPZgaJpZM4Ilg6A>.
>

-- 
Giovanni Crapelli

**Comment by guruz** [comment] 2016-06-06 12:04
Great to hear :-)

**Closed by guruz** 2016-06-06 12:04 UTC
Labels: bug, Needs info, ReadyToTest, sev2-high
