### ISSUE TITLE
ConnectionValidator hangs, does not complete.  Client does not reconnect.

### ISSUE THREAD

**Issue by georgebarnett** [owncloud/client#11454] opened 2023-12-29 15:40 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The own cloud client loses connection to the upstream server when a configured VPN goes away (expected).  

When the VPN comes back own cloud does not ever reconnect.  

I haven't been able to find anything in the logs as to why reconnect isn't attempted, but the end result is that the client hangs in a state of 'reconnecting'.

I've seen this in the logs:

```
23-12-29 17:01:54:539 [ info gui.account.state ]:       checkConnectivity blocking: false "YY@ocis:9200"
23-12-29 17:01:54:542 [ warning gui.account.state ]:    ConnectionValidator already running, ignoring "YY@ocis:9200" Queue is blocked: false
23-12-29 17:02:08:540 [ info sync.connectionvalidator ]:        ConnectionValidator "YY@ocis:9200" still running after duration(190h, 27min, 1
6s, 360ms)
```

There's some other logs about instantiation of a `Created OCC::SimpleNetworkJob` which completed with the response being served from the cache, but nothing about ever retrying to connect.

There are logs of the above message about the `ConnectionValidator` already running.

### Expected behavior

When the VPN restarts and DNS resolves, own cloud client should reconnect.

I've confirmed that connectivity to the server (both dns lookups and an actual connection) is present and working during this issue.  

Its only the OC client that hangs.

### Steps to reproduce the issue

I'm using the most recent client with OCIS 4 with a tailscale VPN that comes and goes as my internet does.

### Logs

```
23-12-29 07:44:49:798 [ debug sync.networkjob ] [ OCC::AbstractNetworkJob::slotFinished ]:      Network job finished OCC::PropfindJob(OCC::Account("YY@ocis:9200"), "https://ocis:9200/dav/spaces/xx/", "PROPFIND", Original-Request-ID: "7d01e5ea-9c34-45f1-b20a-41aa3e733cd7", X-Request-ID: "7d01e5ea-9c34-45f1-b20a-41aa3e733cd7")
23-12-29 07:44:49:799 [ info sync.engine ]:     #### Discovery end ####################################################  404 ms
23-12-29 07:44:49:800 [ info sync.engine ]:     #### Reconcile (aboutToPropagate) ####################################################  405 ms
23-12-29 07:44:49:800 [ info gui.socketapi ]:   Sending SocketAPI message --> "STATUS:IGNORE:/Users/YY/owncloud Shares/.owncloudsync.log" to SocketApiSocket(0x6000025a3a80)
23-12-29 07:44:49:802 [ info gui.socketapi ]:   Sending SocketAPI message --> "STATUS:IGNORE:/Users/YY/owncloud Shares/.sync_journal.db" to SocketApiSocket(0x6000025a3a80)
23-12-29 07:44:49:802 [ info gui.socketapi ]:   Sending SocketAPI message --> "STATUS:IGNORE:/Users/YY/owncloud Shares/.sync_journal.db-shm" to SocketApiSocket(0x6000025a3a80)
23-12-29 07:44:49:804 [ info gui.socketapi ]:   Sending SocketAPI message --> "STATUS:IGNORE:/Users/YY/owncloud Shares/.sync_journal.db-wal" to SocketApiSocket(0x6000025a3a80)
23-12-29 07:44:49:805 [ info sync.engine ]:     #### Reconcile (aboutToPropagate OK) ####################################################  410 ms
23-12-29 07:44:49:806 [ debug sync.propagator ] [ OCC::OwncloudPropagator::createJob ]: Propagating: OCC::SyncFileItem(file="/", type=CSyncEnums::ItemTypeSkip, instruction=CSyncEnums::CSYNC_INSTRUCTION_NONE, status=OCC::SyncFileItem::NoStatus)
23-12-29 07:44:49:806 [ info sync.engine ]:     #### Post-Reconcile end ####################################################  411 ms
23-12-29 07:44:49:810 [ info sync.engine ]:     Updating files marked as dirty
23-12-29 07:44:49:813 [ info sync.engine ]:     Sync run took  418 ms
23-12-29 07:44:49:813 [ info gui.socketapi ]:   Sending SocketAPI message --> "STATUS:OK:/Users/YY/owncloud Shares" to SocketApiSocket(0x6000025a3a80)
23-12-29 07:44:49:814 [ debug sync.localdiscoverytracker ]      [ OCC::LocalDiscoveryTracker::slotSyncFinished ]:       sync success, forgetting last sync's local discovery path list
23-12-29 07:44:49:814 [ info gui.folder ]:      Client version "ownCloud 5.2.0.12726 f6cca1 Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023 Using virtual files plugin: suffix OS: macos-23.2.0 QPA: cocoa"
23-12-29 07:44:49:814 [ info gui.folder ]:      SyncEngine finished without problem.
23-12-29 07:44:49:815 [ info gui.folder ]:      Folder "/Users/YY/owncloud Shares/" sync result:  OCC::SyncResult::Undefined
23-12-29 07:44:49:816 [ info gui.socketapi ]:   Sending SocketAPI message -→ "STATUS:OK:/Users/YY/owncloud Shares" to SocketApiSocket(0x6000025a3a80)
23-12-29 07:44:49:817 [ info gui.socketapi ]:   Sending SocketAPI message -→ "UPDATE_VIEW:/Users/YY/owncloud Shares" to SocketApiSocket(0x6000025a3a80)
23-12-29 07:44:49:821 [ info gui.application ]: Sync state changed for folder  "https://ocis:9200/dav/spaces/xxxx/" :  "Success"
23-12-29 07:44:49:824 [ info gui.folder.manager ]:      <========== Sync finished for folder [ "owncloud Shares" ] of account [ "YY@ocis:9200" ] with remote [ "https://ocis:9200/dav/spaces/xxxx/" ]
23-12-29 07:44:49:824 [ info gui.scheduler.syncscheduler ]:     Sync finished for "/Users/YY/owncloud Shares/" with status OCC::SyncResult::Success
23-12-29 07:44:55:077 [ info sync.connectionvalidator ]:        ConnectionValidator "YY@ocis:9200" still running after duration(181h, 10min, 2s, 107ms)

```
### Client version number

ownCloud 5.2.0.12726 f6cca1 Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023 Using virtual files plugin: suffix OS: macos-23.2.0 QPA: cocoa

### Server information

OCIS 4

**Comment by michaelstingl** [comment] 2024-01-02 07:36
Maybe related to:
- https://github.com/owncloud/client/issues/11447
- https://github.com/owncloud/client/issues/11274

**Comment by TheOneRing** [comment] 2024-01-02 10:47
Duplicate off: https://github.com/owncloud/client/issues/11274

**Closed by TheOneRing** 2024-01-02 10:47 UTC
Labels: bug

**Comment by michaelstingl** [comment] 2024-01-03 08:53
You can test-drive the fix with the latest 5.x dailies:
- https://download.owncloud.com/desktop/ownCloud/daily/5.2/?sort=time&order=desc
- https://download.owncloud.com/desktop/testpilotcloud/daily/5.2/?sort=time&order=desc

Final 5.2.1 planned the next few days…
