### ISSUE TITLE
Branded clients should not show experimental options

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7756] opened 2020-02-21 11:45 UTC
Only "ownCloud" and "testpilotcloud" should show experimental features.

We already have a config setting showExperimentalOptions=false, which is used in two places

    in the wizard to advertise vfs or not.
    in theme.cpp as a default in showVirtualFilesOption()

Both cases don't cover what we need here. showExperimentalOptions seems to be a misnomer. It is rather a showVirtualFilesOption only.

**Comment by jnweiger** [comment] 2020-02-21 11:46
quick'n'dirty fix: https://github.com/owncloud/client/pull/7754

**Comment by TheOneRing** [comment] 2020-02-21 12:02
Duplicate of #7756

**Closed by TheOneRing** 2020-02-21 12:02 UTC

**Comment by jnweiger** [comment] 2020-02-21 12:04
Actually a duplicate of #7755 -- sorry for the confusion.
