### ISSUE TITLE
Don't autoselect any button in "keep files" dialog

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#5931] opened 2017-07-31 15:21 UTC
### Steps:

1. Setup sync client
1. Let it upload some files
1. Close sync client
1. Reset ownCloud instances with new account with same credentials
1. Open sync client
1. Now quickly type some text somewhere and make sure to use a lot of spaces

### Expected result
Whenever the "keep files" popup appears, it must stay and I need to explicitly choose to "keep files" or "delete". Don't auto-focus on any of the buttons.

### Actual result
While typing long sentences, the dialog appears just at the moment I hit the spacebar. And at this time, one of the buttons (not sure which) was focused so hitting the spacebar selects it.

### Versions
OC master
owncloud-client-2.3.2-1.5.x86_64

Minor issue since this doesn't happen often.

**Comment by PVince81** [comment] 2017-08-02 09:43
I had a quick look at tried to set `setDefaultButton(0)` but it doesn't disable the default button. I suppose there might be a more hacky way to do it but it somehow feels wrong.

This reminds me a bit of some dialogs (was it Firefox?) where the OK button is disabled until the window is actually focussed. This lead me to think that it is probably wrong to have this one window automatically focused. It seems the flag `WindowStaysOnTopHint` is set which, from my understanding, would make it stay on top of any other windows on the desktop.

A possible alternative for this would be to just remove this flag and let the window manager prompt the user as it would do for any other popup dialog. And/or use the system's notification system to display a notification with buttons (this is possible on Plasma 5 at least), which would integrate better.

Thoughts ?

**Comment by guruz** [comment] 2017-08-03 15:51
Ouch. i think this was reported before and is indeed annoying.

**Comment by TheOneRing** [comment] 2020-03-17 11:17
Duplicate of #5931

**Closed by TheOneRing** 2020-03-17 11:17 UTC
Labels: Design & UX, Enhancement, good first issue
