### ISSUE TITLE
You should see a notification to accept / reject actions.

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4480] opened 2016-02-17 09:27 UTC
### Steps to reproduce
1. You need 2 users on 2 differents servers
2. Go to Desktop client with user1, with the server1
3. Create a new folder
4. Share with onwCloud
5. Share this folder with user2 (on the server 2)

### Expected behaviour
Tell us what should happen

### Actual behaviour
You should see a notification to accept / reject actions.

### Server configuration
On the Desktop client you can't see a notification to accept/reject shares.

### Server configuration
Desktop v 2.2.0
Server v 8.2.2 and 9.0

**Comment by nickvergessen** [comment] 2016-02-17 11:28
Should be covered with https://github.com/owncloud/client/issues/3733 since the server creates notifications for fed. shares in 9.0+

**Comment by dragotin** [comment] 2016-03-09 08:50
duplicate of #3733

**Closed by dragotin** 2016-03-09 08:50 UTC
Labels: Enhancement, Sharing
