### ISSUE TITLE
Link in sync app to errors and help doesn't work

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/client#5983] opened 2017-08-29 14:38 UTC
This link button doesn't work, currently:
![image](https://user-images.githubusercontent.com/3033827/29826661-285724e0-8cd8-11e7-8090-a2ffd256aa71.png)

It opens https://central.owncloud.org/c/help/desktop-file-sync which has got a 404 error:
![image](https://user-images.githubusercontent.com/3033827/29826680-3a55caac-8cd8-11e7-954b-d5b8fdbaa956.png)

Possible solutions might be to update the link button to the right location (e.g. github issues list https://github.com/owncloud/client/issues/ ) or to provide some page content at https://central.owncloud.org/c/help/desktop-file-sync

**Comment by michaelstingl** [comment] 2017-08-29 15:57
@lefherz please make sure https://central.owncloud.org/c/help/desktop-file-sync exists-

**Comment by jnweiger** [comment] 2017-08-29 16:03
In upcoming client-2.3.3 the link goes to https://central.owncloud.org/c/desktop-client
But please also maintain the older landing pages for a while.

**Comment by SamuAlfageme** [comment] 2017-08-30 07:25
As @jnweiger says, was fixed in https://github.com/owncloud/client/pull/5869 and consequence of https://central.owncloud.org/t/new-central-categories-you-decide - closing here

**Comment by lefherz** [comment] 2017-08-30 08:26
actually, it should direct to https://central.owncloud.org/c/desktop-client/help instead. I commented in the original issue - if this can still go to 2.3.3 before release, we should direct there. If not, it's not that important, we can leave the link at https://central.owncloud.org/c/desktop-client.

Either way, tell me, when you have decided, and I will ask for a 301 redirect from the old category to the new one.

@SamuAlfageme

**Comment by SamuAlfageme** [comment] 2017-08-30 08:55
@lefherz almost all the posts in https://central.owncloud.org/c/desktop-client are actually "support"/help requests, so I think this is rather confusing for central users (as it was for me when I did #5869) - I don't think pointing it to the subcategory is that important. 

Redirection for older clients would be cool.

**Comment by guruz** [comment] 2017-09-06 15:14
Please don't break links :-(

CC also @settermjd who i complained to the same about doc links ;-)

**Comment by guruz** [comment] 2017-09-06 15:15
I somehow can't assign an issue to @lefherz here..

@lefherz the problem is the already released clients must not break.

**Comment by lefherz** [comment] 2017-09-06 21:37
o.0 I already opened a ticket at sysadmin@owncloud.com.... but they somehow don't seem to answer it, or any of my other tickets o.0

**Comment by jnweiger** [comment] 2017-09-07 12:54
client-2.3.3 opens https://central.owncloud.org/c/desktop-client -- this is a working URL. please let me know if there is a better place to point to.
As we cannot fix clients-2.3.2 that are already out there, the old urls should remain. Why were they removed?

**Comment by michaelstingl** [comment] 2017-09-07 13:38
@lefherz Could you re-create the missing URL's?

**Comment by jnweiger** [comment] 2017-09-08 11:41
we need a 301 redirect from
https://central.owncloud.org/c/help/desktop-file-sync
to https://central.owncloud.org/c/desktop-client/help

suggest to use a https://central.owncloud.org/go/.... schema for general redirectors...?

**Comment by jnweiger** [comment] 2018-04-13 11:13
long time no action here. Sorry. Assigned myself now and added the redirect according to my own description above. If there is a better way meanwhile using this /go/ routing, please reopen.

**Closed by jnweiger** 2018-04-13 11:13 UTC
Labels: Documentation
