### ISSUE TITLE
"Open ownCloud in browser" should login automatically

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#3085] opened 2015-04-09 15:09 UTC
### Expected behaviour
When I klick "Open ownCloud in browser" from menu bar icon of the desktop sync client, my browser should login automatically.

### Actual behaviour
I have to login again on the website.

### Steps to reproduce
1. install desktop sync client
2. login with user credentials
3. klick "Open ownCloud in browser" from menu bar icon
4. system browser starts and I have to login again

### Server configuration
ownCloud version: 8.0.2

### Client configuration
Client version: 1.8.0

Operating system: Mac OS X 10.10.2

OS language: german

Installation path of client: /Volumes/Macintosh HD/Applications/owncloud.app

@dragotin Why can't I use my valid client session on the website (with token)?

**Comment by danimo** [comment] 2015-04-09 15:16
Duplicate of #633.

**Closed by danimo** 2015-04-09 15:16 UTC

**Comment by dragotin** [comment] 2015-04-09 16:04
sorry @michaelstingl I didn't remember that there is already an issue report...
