### ISSUE TITLE
Linux desktop client fails to sync

### ISSUE THREAD

**Issue by DonHugo69** [owncloud/client#3477] opened 2015-07-19 09:26 UTC
### Expected behaviour
Sync should work properly and synchronize files from desktop to server. 

### Actual behaviour
Upon pasting new files into the sync directory, upload begins and fails after 2-3 files with unknown error ("unbekannter Fehler"). Sync continues after rediscovery. However, it fails again and sync becomes nearly impossible for larger numbers of files. 

### Steps to reproduce
1. Just copy&paste new data into the sync directory.

### Server configuration
Web server: Apache

Database: MySQL 5.6.24

PHP version: 5.5.26

ownCloud version: 8.0.4

### Client configuration
Client version: 1.8.4

Operating system: Manjaro Linux KDE 0.8.13, testing branch

OS language: German

### Logs

https://gist.github.com/DonHugo69/3ceb4ba2c52ea2f5a117#file-gistfile1-txt

**Comment by ogoffart** [comment] 2015-07-20 08:19
Probably caused by https://bugreports.qt.io/browse/QTBUG-47048
@gutuz: can you confirm?

**Comment by guruz** [comment] 2015-07-20 11:58
@DonHugo69 Can you check which Qt version is used? (in client settings dialog)

@DonHugo69 If you increment in your ownCloud web server the values for Keep Alive Requests and Keep Alive Timeout to big values, does it work?

**Comment by ogoffart** [comment] 2015-07-20 12:31
@guruz the version is Qt 5.5.0   (I deduced that from the log)

**Comment by guruz** [comment] 2015-07-20 12:33
@DonHugo69 (If you compile Qt from git, you might give 5.5 branch a shot..)

**Comment by DonHugo69** [comment] 2015-07-20 12:47
According to the client settings dialog it was compiled with Qt 5.5.0, OpenSSL 1.0.2d (9 Jul 2015), build from GIT Revision 419d9b (15 Jul 2015).

Due to being on a shared hoster, i cannot edit the server settings directly. Can I change them via .htaccess?

**Comment by guruz** [comment] 2015-08-03 08:34
@DonHugo69 Did you manage to try?

**Comment by DonHugo69** [comment] 2015-08-03 09:06
@guruz Sorry, I had no success so far. I searched a little bit if I can change these settings via the htaccess. However, what I tried had no impact. I am not sure if this is due to my hoster or owncloud. 
If you can provide me some further information what to try exactly (I don't have that much knowledge about servers), I could do some more tests.

**Comment by guruz** [comment] 2015-08-04 13:16
If you ```export OWNCLOUD_MAX_PARALLEL=1``` in the shell before running ```owncloud``` do things improve or get worse?

**Comment by DonHugo69** [comment] 2015-08-06 13:45
@guruz Thank you very much! Sync seems to work now. I used the same files as last time and created a new log file https://gist.github.com/DonHugo69/19d6c350e49bded69100

However, when start to sync more files, the connection drops at some point and the client reconnects to the server. But it does continue to sync without the unkown error seen before.

Can I make that option permanent (e.g. in the ~/.profile?)

**Comment by guruz** [comment] 2015-08-06 13:52
@DonHugo69 thanks :) You should be able to put it in ~/.profile yes.
The logfile wouldn't help now since it does not fail..
In the 2.0 client you will be able to set a bandwidth limit which has a side effect of disabling parallelism.

@ogoffart What about having a checkbox after all and call it ```Compatibility mode``` (related #3382 ..)

Not closing but moving milestone so we can re-discuss.

**Comment by DonHugo69** [comment] 2015-08-07 12:53
Sorry to disturb again, but the error is still there, however it appears much later than before. 
https://gist.github.com/DonHugo69/dfd25cc7fd2978ef854a
Thus the client is in principle usable but from time to time the error appears and the client needs start to sync again.

**Comment by guruz** [comment] 2015-08-18 14:11
@DonHugo69 Sorry, somehow forgot about this issue.
Do you have more log context (from before that problem)?
It would be relevant to see which request fails and why.. it should actually never throw an _Unknown_ error, we should always be able to display something nice to the user.
(again with ```OWNCLOUD_MAX_PARALLEL=1```)

Also interesting would be if 2.0 changes anything. The rc1 will come out today..

**Comment by DonHugo69** [comment] 2015-08-20 17:56
Currently I only have the ones posted here. Would it be helpful for you to create a new one from a current session? If yes, anything I would need to take care about or something you want to see?

**Comment by DonHugo69** [comment] 2015-08-30 06:14
I juste wanted to give a small update: I have updated the client to V 2 and created a new logfile. The problem still exists.
https://gist.github.com/DonHugo69/780c5d7e9ab810f63eff

**Comment by guruz** [comment] 2015-08-30 10:34
```
08-30 08:07:10:944 27867 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) OCC::DiscoveryJob(0x2a13980) docear_workspace/projects/Chemical Society Review/_data/14B7CEB388EEXM03YRXPUWL5I64T8CYXNXPX/default_files Calling into main thread...
08-30 08:07:10:948 27728 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://ssl-account.com/owncloud.rgoers.biz" + "/docear_workspace/projects/Chemical Society Review/_data/14B7CEB388EEXM03YRXPUWL5I64T8CYXNXPX/default_files"
08-30 08:07:10:986 27740 unknown: QIODevice::write (QTcpSocket): device not open
08-30 08:07:10:987 27728 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Unknown error" QVariant(Invalid)
08-30 08:07:10:988 27728 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
08-30 08:07:10:988 27728 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Unknown error" QVariant(Invalid)
08-30 08:07:10:989 27728 OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot: void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply*) "Unknown error" 0 QNetworkReply::NetworkError(UnknownNetworkError)
08-30 08:07:10:989 27728 OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot: void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, QString) 5 "Unknown error"
08-30 08:07:10:990 27867 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) OCC::DiscoveryJob(0x2a13980) docear_workspace/projects/Chemical Society Review/_data/14B7CEB388EEXM03YRXPUWL5I64T8CYXNXPX/default_files ...Returned from main thread
08-30 08:07:10:990 27867 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) 5 when opening docear_workspace/projects/Chemical Society Review/_data/14B7CEB388EEXM03YRXPUWL5I64T8CYXNXPX/default_files msg= "Unknown error"
08-30 08:07:10:990 0x2dbb6d0 csync_ftw: opendir failed for ownclouds://ssl-account.com/owncloud.rgoers.biz/remote.php/webdav/docear_workspace/projects/Chemical Society Review/_data/14B7CEB388EEXM03YRXPUWL5I64T8CYXNXPX/default_files - errno 5
```

Does not look good... 

Your Qt version is still missing some network patches which are to become Qt 5.5.1..
I wonder if using that (or Qt git 5.5 branch since 5.5.1 is not released yet) would help

**Comment by ogoffart** [comment] 2015-08-31 16:19
Yes, this is bcause of https://bugreports.qt.io/browse/QTBUG-47048

**Closed by ogoffart** 2015-08-31 16:19 UTC
Labels: bug
