### ISSUE TITLE
Translation issue feature "confirm larger downloads"

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#3814] opened 2015-09-11 11:58 UTC
This is how the German translation looks like:

![oc](https://cloud.githubusercontent.com/assets/2737900/9814263/eb1a9fe8-588c-11e5-924f-9fe21363824f.png)

From https://github.com/owncloud/client/blob/master/translations/client_de.ts:
```
    <message>
        <location filename="../src/gui/generalsettings.ui" line="61"/>
        <source>Ask confirmation before downloading folders larger than</source>
        <translation>Bestätigung abfragen, bevor Ordner mit einer Größe über %1 heruntergeladen werden.</translation>
    </message>
```

No placeholder in English language...

**Comment by danimo** [comment] 2015-09-11 12:00
Duplicate of #3717, which has already been resolved.

**Closed by danimo** 2015-09-11 12:00 UTC

**Comment by LukeOwncloud** [comment] 2015-09-11 12:16
Perfect!

That issue does not contain any keywords concerning the actual problem. So I could find it...

**Comment by phil-davis** [comment] 2015-09-11 12:17
Not an issue right now, but interestingly in Nepali I cannot think of a way to write this sentence so that the nnn MB comes naturally at the end. Actually the most natural way to write it has nnn MB at or near the start. That can make some tricky multilingual UI design.

**Comment by danimo** [comment] 2015-09-11 12:23
@phil-davis This is merely a workaround The real solution is to use <label><spinbox><label>. Qt's tr mechanism can only fill in text for %x, not widgets like the spin box. On the other hand, it's very tricky to make it transparent to transifex users that the two labels and the spinbox belong together an form a sentence. Clever ideas appreciated...
