### ISSUE TITLE
prevent large data from being automatically deleted during sync if it was deleted on server

### ISSUE THREAD

**Issue by umlaeute** [owncloud/client#4464] opened 2016-02-11 09:27 UTC
sometimes large data gets removed on the oc-server.
when the client syncs the data vanishes from the client-machine (this is obviously expected behaviour).
however, sometimes the data on the server is removed *accidentally* (or temporarily), leading to (temporary) data-loss.

while the data-loss is temporary, the time it takes to re-sync can be considerably long (e.g. when we are talking about several gigabytes of data).

## use case
- 2 people are working on a joint project, involving several gigabyte of video material.
- userA is preparing a presentation relying on that data, the presentation is due tomorrow, so userA is working on it from home late night.
- userB doesn't know about userA's presentation and deletes the data on their client.
- while userA is going to the loo, the oc-client has deleted all their files.
even if there was a backup on the server, restoring that (through the home ADSL-line) will take hours. therefore the presentation has to be cancelled :-(

NOTE: our real-world use-case that triggered this report included a problem on the server side (which i'm going to report separately) that would lead to data-loss without user interaction.

## affected systems
the problem exists at least in the client `2.1.0` running W7; 

## proposal
i therefore propose a feature-request, to *ask for confirmation* if the client is going to delete a (configurable) amount of data.

something like a new configuration option (along the lines of the *confirmation for downloading large folders*):

> [ ] Ask confirmation before deleting folder larger than [  500 ] MB.

## reasoning
- downloading large data files takes time (and money)
- removing large data files on the client is instantaneous
- therefore an overly fast deletion of data can interrupt workflows considerably.

**Comment by guruz** [comment] 2016-02-11 10:23
I think this is a duplicate of an issue we have somewhere in the tracker already..

In any case FYI @MTRichards @jospoortvliet

**Comment by MTRichards** [comment] 2016-02-11 13:24
Hm. What happens if the client asks and the answer is "no, don't delete this data?" then we have sync errors because now files exist on the desktop, and not on the server...

Or, are we saying we should put the files back on the server, or that the server is asking for confirmation via the client to delete these files, before the server deletes them?

**Comment by umlaeute** [comment] 2016-02-11 13:33
i guess the option would be to (either "go ahead and remove") or to exclude those (local) directories from synching with the server.

**Comment by dragotin** [comment] 2016-02-18 11:52
We have the server trashbin to restore the file. That exactly helps with this problem.

**Closed by dragotin** 2016-02-18 11:52 UTC
Labels: Discussion

**Comment by umlaeute** [comment] 2016-02-18 12:34
@dragotin could you please explain?

**Comment by umlaeute** [comment] 2016-02-18 12:50
esp, i don't see a "Server Trashbin" on my client (neither on the filesystem nor anywhere in the configuration options).

if the client deletes the data locally, it doesn't help much if the server can easily restore them (on the server side) - it still takes hours to synchronize the GB of data...

**Comment by dragotin** [comment] 2016-02-18 13:04
@umlaeute yes, the file has to be resynced, that is true. But OTOH, it should not be a common case that something is deleted on the server by accident. But if, it should be acceptable to resync.

**Comment by umlaeute** [comment] 2016-02-18 13:42
hmm, for my users re-synching 15GB was not acceptable in the hot phase of a project, so they switched to a some commercial filesync provider :cry:
