### ISSUE TITLE
Error on sharing file or folder that is not synced

### ISSUE THREAD

**Issue by cburnard** [owncloud/client#4108] opened 2015-11-10 13:49 UTC
**Steps to reproduce:**

1.  Create a file or folder under the directory that the oC Windows Sync Client Version 2.0.2 (build 5569) is syncing.
2. Before the client syncs the file or folder, right click on the file and select "Share with ownCloud".

**Expected behavior**   
Something other then the error message produced. 

**Actual  behavior**  
![image](https://cloud.githubusercontent.com/assets/12254958/11063944/d98632cc-8787-11e5-8a63-8cb0970b902d.png)

**Comment by rullzer** [comment] 2015-11-20 08:27
Duplicate of https://github.com/owncloud/client/issues/3985. Lets track it there.

**Closed by rullzer** 2015-11-20 08:27 UTC
