### ISSUE TITLE
[2.x Windows] After Hibernating - Always checks for client software update and never finishes

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#3933] opened 2015-10-08 12:34 UTC
Win Client does always check for update but never finishing the task. See Screenshot:
https://db.tt/1M7dwUzY

**Comment by dragotin** [comment] 2015-10-28 13:03
that looks like as if the request timed out during the hibernation and that does not get reflected to the UI.

**Comment by MegaV0lt** [comment] 2015-10-28 13:12
Same effect with current 2.02 version after some days... this does not happen every time hibernating...

**Comment by MegaV0lt** [comment] 2015-11-18 07:33
still with 5632
![2015-11-18 08_27_41-owncloud](https://cloud.githubusercontent.com/assets/2804301/11235145/15cd1bfe-8dcf-11e5-8278-1b02153f4c28.png)

**Comment by MegaV0lt** [comment] 2015-12-07 14:01
Problem still exist in 2.1
![2015-12-07 15_00_33-owncloud](https://cloud.githubusercontent.com/assets/2804301/11628659/65d73764-9cf3-11e5-86a5-d309d1e5469d.png)

**Comment by MegaV0lt** [comment] 2016-01-21 09:01
Still the same with 5785...
![2016-01-21 09_56_21-owncloud](https://cloud.githubusercontent.com/assets/2804301/12475833/db488bba-c025-11e5-85b4-e744118857d0.png)

**Comment by MegaV0lt** [comment] 2016-02-10 08:19
Problem still with #5833

**Comment by hodyroff** [comment] 2017-03-10 11:14
please reproduce with 2.3

**Comment by MegaV0lt** [comment] 2017-03-11 07:55
In the meantime i am at nextcloud client, but still the same. Today after the first wakeup after hibernation i have the same issue:
![Screenshot](https://i.imgur.com/qcC3vG4.png)

git from 6 mar 2017

**Comment by guruz** [comment] 2017-04-24 13:33
From looking at the code, there should be a 30 sec timeout when checking for updates..
```OCUpdater::checkForUpdate()```

**Comment by MegaV0lt** [comment] 2017-04-25 12:34
Was never working in Windows... Meanwhile i switched to Linux Mint. I will watch if there is the same effect.

**Comment by guruz** [comment] 2018-06-27 11:13
Will be fixed in 2.5.0 @MegaV0lt

**Closed by guruz** 2018-06-27 11:13 UTC
Labels: ReadyToTest, bug, p4-low
