### ISSUE TITLE
UI: allow sorting columns in Not Synced Activity Tab

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#6086] opened 2017-10-09 12:32 UTC
Wouldn't it be useful to allow sorting of columns when clicked on the header? We have got such suggestions from our users.

![image](https://user-images.githubusercontent.com/621965/31338174-7b043d4a-acfe-11e7-9e40-463c8e6b3253.png)

**Comment by hodyroff** [comment] 2017-10-12 06:08
Yes! Not sure if we can still make this happen quickly for 2.4.0 @ckamm @michaelstingl the heavy users will like it a lot.

**Comment by ckamm** [comment] 2017-10-12 11:33
I see that sorting would be nice sometimes but there is a complication: We've recently started having a category of "overall" issues (like insufficent remote or local storage) that have no "File" entry and are always sorted to the top. Enabling column sorting (which is easy) would break that.

To avoid users accidentally breaking their error view I'd suggest we encode that "native" sorting into the "Time" row and switch back to that sorting on restart or on window-hide.

Note that newer versions already provide filters by account/folder as well as for warnings or ignored files that should help a bit with locating the relevant issues.

**Comment by ckamm** [comment] 2017-10-12 12:41
PR: https://github.com/owncloud/client/pull/6093

**Comment by guruz** [comment] 2017-10-17 15:20
@hodyroff @moscicki please test with tomorrow's 2.4 nightly and report back here to close issue.

**Comment by guruz** [comment] 2017-10-18 06:45
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client

**Comment by michaelstingl** [comment] 2017-10-19 17:01
@SamuAlfageme please check

**Comment by ckamm** [comment] 2017-10-20 05:41
@moscicki Yes, probably a regression due to https://github.com/owncloud/client/issues/5954 - a patch to fix it is currently in review.

**Comment by ckamm** [comment] 2017-10-24 07:43
The PR is merged now and the next nightly will contain the patch.

**Comment by guruz** [comment] 2017-11-03 10:41
@moscicki Works?

**Comment by moscicki** [comment] 2017-11-04 06:19
Sorting works OK. @giorgosalex was testing it. 

The status of connection wizard fix - I don't know. @giorgosalex could you re-check/comment on this?

**Comment by guruz** [comment] 2017-11-06 12:34
About the connection wizard: Please try with a nightly from TOMORROW, we have/had some things open with regards to redirects, auth detection and wizard.

Then, open a **new issue** and assign 2.4.0 milestone to it.

**Closed by guruz** 2017-11-06 12:34 UTC
Labels: Design & UX, Enhancement, p3-medium, ReadyToTest, sev4-low
