### ISSUE TITLE
No conflict when a file is changed on 2 locations at the same time

### ISSUE THREAD

**Issue by weha** [owncloud/client#2824] opened 2015-02-11 15:35 UTC
Expected behavior
edit the same file on 2 pc's at the same time should create a conflict

Actual behavior
Newest sync wins and oldest sync is lost

It seems that when the sync is initiated the original etag is not compared
Example: 
- 2 people change something in the same file on the same time while the sync clients are idle
-The sync client sees a change on PC-A and syncs the file
- the client on PC-B sees a changed file and sync those changes and the change from PC-A is lost.

Server configuration
Operating system: Synology NAS
Web server: Apache
Database: MariaDB
PHP version: 5.5.12
ownCloud version: 7.0.4

Client configuration
Client version: 1.7.1 4382
Operating system: Windows 8.1 x64
OS language: English
Installation path of client: C:\Program Files (x86)\ownCloud

there was no mention of syncing in the logging

**Comment by ogoffart** [comment] 2015-02-11 16:08
Do you have the client log?

Normaly in this case there should be a precondition failed error and the next sync should create a conflict file

**Comment by weha** [comment] 2015-02-12 08:59
Just made a new test, log here: https://gist.github.com/weha/32f5c036c0d4a9d8bb35

**Comment by weha** [comment] 2015-02-12 09:32
os_activity: https://gist.github.com/weha/18ab75e9e3336ba82686

**Comment by ckamm** [comment] 2015-02-13 12:10
@weha From your logs:
```
                                                        etag
PC A: 08:51:31|37900|file|INST_SYNC|Up  |1423731086|54db7766b77b7|35192|                    |4||0|    0|1423669059|54db7766b77b7|00000179oc945e7ad472|INST_NONE|
PC B: 08:51:47|26590|file|INST_SYNC|Up  |1423731105|54db7766b77b7|35360|                    |4||0|33848|1423669059|54db7766b77b7|00000179oc945e7ad472|INST_NONE|
PC A: 08:53:04|1226 |file|INST_SYNC|Down|1423731105|54dc69be05bf8|35360|00000179oc945e7ad472|4||0|35192|1423731086|54dc69b8dc59f||INST_NONE|
```

So it does really look like both of the uploads succeeded, when the second one should have failed. Can you reproduce this reliably? Maybe the server doesn't check-and-update the etag atomically and that allows two parallel PUT requests for the same etag to succeed?

**Comment by ckamm** [comment] 2015-02-13 12:41
As far as I can tell from reading the sabre-dav version owncloud uses (and sabre-dav master), there's no lock that covers the precondition check and the subsequent file update. @ogoffart points to owncloud/core#4511

**Comment by weha** [comment] 2015-02-13 19:04
I've tested this 2 times in total with the same result and a different PC-B
This might occur more on slow server systems, like a NAS, where it takes longer to process the sync (very slow comparing to cloudstation running on the same system, but that's a different topic)

**Comment by ogoffart** [comment] 2015-03-03 13:33
Closing this as a duplicate of owncloud/core#4511

**Closed** 2015-10-27 11:20 UTC
Labels: bug, Server Involved, sev2-high
