### ISSUE TITLE
Cannot see which folders are synced (column width)

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#3429] opened 2015-07-09 12:11 UTC
The column width in the "choose what to sync" dialog is way to small.
I've set it owncloud on quite a few ubuntu computers now and they all look something like this
![image](https://cloud.githubusercontent.com/assets/639487/8594732/f716bcb2-2643-11e5-9b36-4c1fe57b8ece.png)
That is pretty useless and you have to drag the columns manually to see the names of the folders.
Please adjust the column width when the folder list is updated.

**Comment by guruz** [comment] 2015-07-10 19:35
Thanks, duplicate of https://github.com/owncloud/client/issues/3239

**Closed by guruz** 2015-07-10 19:35 UTC
