### ISSUE TITLE
Request for manual sync button.

### ISSUE THREAD

**Issue by acekrystal** [owncloud/client#4800] opened 2016-05-06 10:39 UTC
I often run against the inconvenience of not yet being synced with the latest files. (Often happens when someone just uploaded something so I can look at it, or when I uploaded something on PC 1, so I can use it on PC 2.)

I then normally pause the sync and then resume the sync in the owncloud window. 

I would like to request a more easy way to force a sync. By adding an option "sync now!" in the quick menu of owncloud in the task bar. Or by adding an option in the quick menu of an owncloud folder (just like the "share with owncloud" option.

I'm running windows 10, but I guess everyone would like this =^.^=

**Comment by danimo** [comment] 2016-05-06 10:42
Duplicate of #4800

**Closed by danimo** 2016-05-06 10:42 UTC
