### ISSUE TITLE
[Fedora 27] window too tall on small screens

### ISSUE THREAD

**Issue by porjo** [owncloud/client#6215] opened 2017-12-05 02:38 UTC
(`owncloud-client-2.4.0-0.8802.1.rc1.x86_64` on Fedora 27)

On my  1366x1280 laptop screen, the Owncloud window disappears off the bottom and can't be resized such that the whole window is visible, or moved such that the bottom of the window is visible. This makes it hard to select the buttons along the bottom row.

This screenshot shows the full height of my desktop:
![screenshot from 2017-12-05 10-31-01](https://user-images.githubusercontent.com/1296987/33587124-9962f080-d9a7-11e7-8754-112acc2ffe41.png)

**Comment by guruz** [comment] 2017-12-05 05:33
Thank you @porjo .

This had been reported for Windows already (https://github.com/owncloud/client/issues/6215) , we did not think this is a problem on Linux too.

@porjo If you switch to any other tab, can you resize the window?

**Comment by porjo** [comment] 2017-12-05 07:20
> If you switch to any other tab, can you resize the window?

No, other tabs have the same issue. The window will resize horizontally but not vertically.

**Comment by ogoffart** [comment] 2017-12-05 09:04
This is a duplicate of #6075  

(@guruz: linux and windows have the same settings dialog, mac has a different one: only on mac you can resize the window depending on the tab, while on linux/window, changing tab does not change the size, so the biggest tab dictates the minimum size)

**Closed by ogoffart** 2017-12-05 09:04 UTC
Labels: bug, Design & UX
