### ISSUE TITLE
Tray status icon and client status icon differ

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/client#2432] opened 2014-10-30 20:17 UTC
### Steps to reproduce

1. Upgrading from 1.6.3 (or maybe 1.6.4) to 1.7
2. The status icon on the tray shows a green check mark
3. If I open up the client, the status icon is blue for syncing

### Expected behaviour

Status icons are the same

### Actual behaviour

Status icons are different

![p196](https://cloud.githubusercontent.com/assets/8480343/4851340/94845f02-6071-11e4-940f-bc0018bef411.PNG)

### Client configuration
**Operating system**:

Windows

**Comment by strugee** [comment] 2015-03-18 18:04
It's worth noting that should the green checks be changed (instead of the blue sync icon), in addition to the status bar icon, we'd also need to change the icon on the "account" tab on the left of the client settings.

**Comment by strugee** [comment] 2015-03-18 18:06
> I think that is intentional because @jancborchardt didn't want us to disturb the user when he doesnt have the window open.

How is the blue icon "disturbing the user"? It's an ambient indicator and doesn't really get in anyone's way. And I'm worried that some users won't think to check the settings before assuming that the client isn't doing anything.

**Comment by jancborchardt** [comment] 2015-03-18 21:42
@strugee the blue arrow icon stands for »syncing«. If there is nothing syncing, but only checking if there’s something to sync, the icon should not show. If it shows when you know that you didn’t change anything, it would lead to confusion.

**Comment by dragotin** [comment] 2015-03-19 07:12
Sorry, confusion! What we agreed on was: For the discovery phase, we show the blue sync icon along the "discovering... " message in the settings dialog, becasue that is only opened for users who wanna know the details. 
The tray icon will not change to the sync icon for the discovery phase to not to disturb the user. That is exactly what the screenshot shows: The tray is green, but the one in the settings dialog shows activity. 

I'd suggest to close this as "works as designed" by @jancborchardt .

**Comment by strugee** [comment] 2015-03-26 05:22
> @strugee the blue arrow icon stands for »syncing«. If there is nothing syncing, but only checking if there’s something to sync, the icon should not show. If it shows when you know that you didn’t change anything, it would lead to confusion.

The problem with this approach is that if the discovery phase takes a long time, and you have files to sync, then it will appear as if the client is doing nothing even though you know that your files haven't been uploaded. Very frustrating unless you know what's going on. (Also, I'd argue that "syncing" with the server would include the discovery phase, where the client isn't necessarily uploading or downloading files, but instead is synchronizing state. FWIW I believe both Dropbox and Google Drive show syncing indications upon startup.)

**Comment by guruz** [comment] 2015-03-26 06:24
> The tray icon will not change to the sync icon for the discovery phase to not to disturb the user. 

btw, since 1.8 the discovery (if there is no local change notification or no updated server ETag) will only happen every 2h. So maybe we ( @jancborchardt @dragotin ) should change the opinion again on this case.

> Very frustrating unless you know what's going on.

Although then you're probably tempted to open the settings dialog and then you see the discovery..

**Comment by strugee** [comment] 2015-03-26 06:32
> Although then you're probably tempted to open the settings dialog and then you see the discovery..

Yes, of course. But (speaking now as someone who semi-regularly opens the settings dialog for this very reason), it still feels frustrating to have had to open the settings dialog trying to find out what's wrong, only to be told that everything's fine, even though the status bar makes it seem like it isn't. It's simply an unnecessary step, IMHO.

**Comment by jancborchardt** [comment] 2015-03-26 21:55
What I said back then was that for the _initial_ discovery phase (on startup) can show the blue arrows. And that is what @strugee is referring to here, right?

What should _not_ show the blue arrows is any subsequent discovery phase.

**Comment by strugee** [comment] 2015-03-28 05:00
> And that is what @strugee is referring to here, right?

Yes.

**Comment by MorrisJobke** [comment] 2016-02-05 08:27
@gig13 Also noticed this issue.

**Comment by dragotin** [comment] 2016-02-05 09:24
Closing this, as it is *works as designed*

**Closed by dragotin** 2016-02-05 09:24 UTC
Labels: blue-ticket, bug, Design & UX, sev4-low

**Comment by MorrisJobke** [comment] 2016-02-05 09:39
> Closing this, as it is works as designed

Could you elaborate on this? For me is "the one icon says syncing and the other icon not-syncing" is a quite weird behavior.

**Comment by dragotin** [comment] 2016-02-05 09:40
@MorrisJobke see above, and @jancborchardt

**Comment by burner1024** [comment] 2017-06-27 23:02
@dragotin this is bad design. When the icon show "green/OK", I expect that client and server are in sync **for sure**. I think I am not alone in that.

If a user doesn't have a clear indicator that all is good and files are in sync, that may and eventually will (and in my case, did) lead to data loss. And data loss is the absolute worse case scenario for a file sync solution. It means that the application cannot be relied upon, and as such is dangerous to use.

Maybe introducing other icons for "checking" and whatever other statuses there are is an option.

**Comment by guruz** [comment] 2017-07-04 11:10
I agree with @burner1024 

If the sync-trigger is a _local_ file change, then the tray icon should switch immediately so that the user is aware that the client is working on syncing this.
