### ISSUE TITLE
[OS X] [Finder] Add icon to the Finder context menu

### ISSUE THREAD

**Issue by gig13** [owncloud/client#4472] opened 2016-02-12 20:56 UTC
In Finder, the Share with ownCloud contextual menu item can get lost in the mass of options. Dropbox has an icon appear next to their menu items to make sure they stand out. I think it would be good to add that to the Mac contextual menu for ownCloud so that your eye is quickly drawn to the place you need to go when you're wanting to access that option, rather than needing to search for it. 

@MTRichards @dragotin

**Comment by danimo** [comment] 2016-02-15 15:01
Dupe of #296

**Comment by danimo** [comment] 2016-02-15 15:01
Moved blue ticket label there, removing here.

**Comment by scolebrook** [comment] 2016-02-15 15:25
@danimo That's related to the Finder sidebar. This is related to the contextual menu for the share with ownCloud menu item.

**Comment by guruz** [comment] 2016-03-04 12:09
Related comment about implementation: https://github.com/owncloud/client/issues/296#issuecomment-113544584

**Comment by scolebrook** [comment] 2016-03-04 14:43
@guruz That linked comment is related to customizing the icon of the ownCloud folder in the Finder sidebar. This issue is about the contextual menu and the Share with ownCloud menu item. It's the same situation for Windows. Dropbox has an icon next to it's menu item which makes it stand out from the clutter. If our users actually read/watched/listened to the training material we've provided for them I'd be twice as productive, but an icon in this menu would catch their eye and bring awareness of this feature. I've had numerous requests to add the ability to share a link from the desktop just like Dropbox when it's been there for ages and they just haven't seen the menu item.

The sidebar icon would be nice. But I feel this icon would not only be easier (adding an icon to a menu item is a fully supported thing) but it would have much more bang for the buck in highlighting a very useful feature. Even for those who know it's there, having the icon would make identifying the correct menu item to click on that much quicker because it'd stand out.

**Comment by guruz** [comment] 2016-03-04 14:45
@scolebrook No worries I understood what you had said and was happy you reopened the issue. I more meant then part where @jturcotte explained that it might be tricky to get the themed icons into the Finder extension. We'll see :)

**Comment by scolebrook** [comment] 2016-03-04 15:26
@guruz I see. Yes. The icons for the plugin don't look like they're themed at all. Getting a themed icon available may well be harder than attaching it to the menu item. I wish I new more about cmake :confused:.

**Comment by guruz** [comment] 2016-03-30 15:08
@MTRichards @scolebrook 

> How hard is this to do for Windows?

I did not investigate. I guess we can just link the app icon as resource into the OCContextMenu DLL. 
AFAIK Note that on Windows we use 1 DLL for _all_ brandings so they'd fight for which icon to use.
FYI @ogoffart @jturcotte (on OS X, each branding can have a separate icon) 

> Then ownBrander needs an update to make this work...

We automatically use the app icon on OS X, for Windows we should do the same.

**Comment by jturcotte** [comment] 2016-03-30 15:16
We currently don't build the shell extension as part of the build on windows since we need MinGW for ownCloud but MSVC for the shell extension. The binaries are therefore pre-built and can't be customized at all by ownBrander.

Officially building binaries with MSVC would make it possible to solve it the same way as OS X, but this is not trivial to do.

**Comment by guruz** [comment] 2016-03-30 19:00
Windows discussion --> https://github.com/owncloud/client/issues/4627

**Comment by guruz** [comment] 2016-03-30 19:03
Closing as @scolebrook confirmed this works for him for OS X for 2.2.x

**Closed by guruz** 2016-03-30 19:03 UTC
Labels: blue-ticket, Design & UX, enhancement - proposed, ReadyToTest
