### ISSUE TITLE
nextcloud client 2.3.1 100%CPU each day on openSuSE 42.1 x86_64

### ISSUE THREAD

**Issue by rainer042** [owncloud/client#5839] opened 2017-06-14 15:12 UTC
### Expected behaviour
nextcloud client should run without noticeable cpu load when there is nothing to do.

### Actual behaviour
Usually once a day the current 2.3.1 version suddenly uses 100% of one CPU until I quit the client (no killing needed, jut exit the client) and then restart it. Then it behaves just nice until some hours later it suddenly again eats 100% CPU. Up to now I was unable to detect any dependencies of what I do and the occurrence of the high CPU load. I noticed the same behaviour already with 2.3.0 but it was less often, perhaps once a couple of days.

The client has two nextcloud accounts configured. One is for a nextcloud with version 12.0 the other is for a nextcloud version 11.0.3. My client is running on a openSuSE 42.2 x86_64 system. Both nextclouds are not busy, some files are synced during the day but the client does not have much to do.
 

### Steps to reproduce
1. Just start nextcloud client 
2. wait several hours
3. Watch CPU load

### Server configuration
Operating system:

nextcloud version: 12.0 + 11.0.3

### Client configuration
Client version: 2.3.1

Operating system: Linux, openSuSE 42.2, x86_64

Client package (From ownCloud or distro) (Linux only): Distro openSuSE

Installation path of client: /usr/bin/nextcloud

Thanks
Rainer

**Comment by guruz** [comment] 2017-06-14 19:47
Closing as duplicate of https://github.com/owncloud/client/issues/5074

**Comment by guruz** [comment] 2017-06-14 19:47
(Please read the issue there and try to contribute more info if you have.. :)

**Closed by guruz** 2017-06-14 19:47 UTC

**Comment by guruz** [comment] 2017-06-14 19:48
And did you check your settings dialogue about which Qt version the client is using?

**Comment by rainer042** [comment] 2017-06-15 06:38
Ok, Ill read the issue and try to contribute more information there. However my client does not show any qt version in the settings dialog:
![nextcloud-settings](https://user-images.githubusercontent.com/19302310/27168337-8db592ae-51a5-11e7-9995-6e9058ea4c7d.png)

I'll start nextcloud now with log window and will wait until the cpu load goes up....

**Comment by guruz** [comment] 2017-06-15 07:35
@rainer042 We have a funny bug there, if you drag the dialog to be higher you can see the version.. :-)

(The log should also show the Qt version)

**Comment by SamuAlfageme** [comment] 2017-06-15 07:36
@rainer042 @guruz see: https://github.com/owncloud/client/issues/5760#issuecomment-300086638
