### ISSUE TITLE
Unable to modify autostart on mac

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9800] opened 2022-06-15 11:46 UTC
Launch on login seems to be active on mac independent of the user settings/ disabling has no effect.

**Comment by TheOneRing** [comment] 2022-06-15 11:46
The client restarted again and again after a crash.

**Comment by erikjv** [comment] 2022-06-17 16:23
Temporary work-around: edit `~/Library/LaunchAgents/com.owncloud.desktopclient.plist` and change the value for `RunAtLoad` to false like this:
```
        <key>RunAtLoad</key>
        <false/>
```

> The client restarted again and again after a crash.

Yes, on purpose. But we can turn this off in the launchd plist file. Currently it's set as:
```
        <key>KeepAlive</key>
        <dict>
                <key>Crashed</key>
                <true/>
                <key>SuccessfulExit</key>
                <false/>
        </dict>
```


> Launch on login seems to be active on mac independent of the user settings/ disabling has no effect.

**Comment by erikjv** [comment] 2022-06-17 16:26
I tried to reproduce this with my own build of master (not installed, but run from QtCreator), and I cannot reproduce this. Which build should I use, or do I need to install it into `/Applications`?

**Comment by TheOneRing** [comment] 2022-06-21 09:17
> Temporary work-around: edit `~/Library/LaunchAgents/com.owncloud.desktopclient.plist` and change the value for `RunAtLoad` to false like this:
> 
> ```
>         <key>RunAtLoad</key>
>         <false/>
> ```
> 
> > The client restarted again and again after a crash.
> 
> Yes, on purpose. But we can turn this off in the launchd plist file. Currently it's set as:
> 
> ```
>         <key>KeepAlive</key>
>         <dict>
>                 <key>Crashed</key>
>                 <true/>
>                 <key>SuccessfulExit</key>
>                 <false/>
>         </dict>
> ```
> 
> > Launch on login seems to be active on mac independent of the user settings/ disabling has no effect.

The issue was a crash on startup and no chance to kill it...

**Comment by TheOneRing** [comment] 2022-06-21 09:19
Hmm it was auto starting the client in my dev env. 
Changes to
![image](https://user-images.githubusercontent.com/200626/174764662-ad22d192-c77c-44f2-adaa-293b4667f659.png)
Had no effect the client was started again after login.

**Comment by TheOneRing** [comment] 2022-07-01 08:20
```
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<dict>
		<key>Crashed</key>
		<true/>
		<key>SuccessfulExit</key>
		<false/>
	</dict>
	<key>Label</key>
	<string>com.owncloud.desktopclient</string>
	<key>Program</key>
	<string>/Users/hannah/ownbuild/master/downloads/git/owncloud/build-owncloud-client-ownBuild-Debug/bin/owncloud.app/Contents/MacOS/owncloud</string>
	<key>RunAtLoad</key>
	<false/>
</dict>
</plist>                                                                    
```

As it fails to load a lib it will try to restart again and again and again.
All the time the checkbox for start at launch isn't even checked.

**Comment by TheOneRing** [comment] 2022-08-10 13:01
With a fresh install it is also impossible to enable autostart.

**Comment by erikjv** [comment] 2022-09-13 11:26
Once that PR is merged, remove `~/Library/LaunchAgents/com.owncloud.desktopclient.plist`, then it will get re-created at the next start.

**Comment by TheOneRing** [comment] 2022-09-13 11:36
Enabling also doesn't work :P

**Comment by erikjv** [comment] 2022-11-04 16:59
This was fixed after merging 245047d40b40260c1c7dcbfe8bb48a4a848ab2b1

**Closed by erikjv** 2022-11-04 16:59 UTC
Labels: Needs info, ReadyToTest, p1-urgent

**Comment by HanaGemela** [comment] 2022-11-11 11:08
Test steps:
1. enable autostart, then restart your Mac:
Should start automatically

2. disable autostart, then restart your Mac:
Should not start automatically

**Comment by HanaGemela** [comment] 2022-11-11 11:25
Passed on mac 3.0.0 beta1

**Comment by HanaGemela** [comment] 2022-11-14 08:16
we also need to test migration
clean mac, install 2.11
update to 3.0
see wheter autostart persisted

**Comment by HanaGemela** [comment] 2022-11-22 10:53
Test failed

1. Install 2.11.1, make sure Start on login is checked 
2. Update to 3.0.0.9153-daily20221122

Start on login is not checked after the update.
