### ISSUE TITLE
Don't force deletion on exclusion of single folders

### ISSUE THREAD

**Issue by androos** [owncloud/client#6305] opened 2018-01-14 18:37 UTC
You can exclude folders from sync. But these files would be forcefully deleted from local disk. Because you have no other option. 
But you should have an option to just exclude files without any deletion on any side. 
It depends on the reason why you exclude files, you may want them to exists on both sides. 
Basically you -exclude- folders so there is no reason to check whether the files are in sync or not. 
Just give an option to not delete and just exclude from folders sync. 
when the folders is added again for sync, it should be synced everything in both directions, just like if you add a new sync.

**Comment by SamuAlfageme** [comment] 2018-01-15 08:28
Hey @androos, I believe this is a duplicate of https://github.com/owncloud/client/issues/2502 - you can comment and upvote there yo show your support for this feature! 

Thanks for reporting!

**Closed by SamuAlfageme** 2018-01-15 08:28 UTC
