### ISSUE TITLE
Special characters in password give "Access forbidden by server." for owncloud-client on Ubuntu

### ISSUE THREAD

**Issue by tombrossman** [owncloud/client#4540] opened 2016-03-04 20:15 UTC
### Expected behaviour
Successful login via desktop client using strong password as per the documentation.
_(actual pass which caused login failure: S5J!xES}&QkXq+Lq/TB`*h$Q<F]DCZNg but now changed, obviously)_
Also expected meaningful error messages from server or desktop, unfortunately none were produced. Apache auth.log and error.log remained empty during testing.

### Actual behaviour

1. Logging in via web browser works perfectly

2. Login via desktop client fails. Error message displayed "Access forbidden by server. To verify that you have proper access, click here to access the service with your browser" (note 'click here' is not clickable but right-click & copy works).

### Steps to reproduce
1. Install & configure ownCloud on a server, using a password with special characters
2. Install desktop client on Ubuntu and start configuration
3. Attempt login using password with special characters

### Server configuration
Operating system: 64-bit Ubuntu 14.04

Web server: Apache 2.4.7

Database: MariaDB 5.5.47

PHP version: PHP 5.5.9-1ubuntu4.14

ownCloud version: 8.2.2

Storage backend: local disk

### Client configuration
Client version: 1.8.1+dfsg-1ubuntu1

Operating system: 64-bit Ubuntu 15.10

OS language: EN

Installation path of client: default location

### Logs

```
Warning  core  Login failed: 'user' (Remote IP: 'XX.XX.XX.XX')  2016-03-04T19:13:37+00:00
Warning  core  Login failed: 'user' (Remote IP: 'XX.XX.XX.XX')  2016-03-04T19:13:00+00:00
Warning  core  Login failed: 'user' (Remote IP: 'XX.XX.XX.XX')  2016-03-04T19:12:19+00:00
```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
Sys Info size:  79
int main(int, char**) Already running, exiting...

2. Web server error log: Nothing, no errors

3. ownCloud log (data/owncloud.log): Probably not useful, here it is anyway:
```
{"reqId":"Ct5TuCDN7ZiYHqOi5\/L8","remoteAddr":"XX.XX.XX.XX","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-03-04T15:27:39+00:00"}

{"reqId":"Ct5TuCDN7ZiYHqOi5\/L8","remoteAddr":"XX.XX.XX.XX","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2016-03-04T15:27:39+00:00"}

{"reqId":"3p8YtSLy8GYnQCjr3290","remoteAddr":"XX.XX.XX.XX","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-03-04T15:34:01+00:00"}
```

### Workaround

Use password consisting of only upper and lower case letters plus numbers, NO punctuation marks...

**Comment by RealRancor** [comment] 2016-03-05 12:15
@tombrossman Might be related or a duplicate of https://github.com/owncloud/core/issues/7894, https://github.com/owncloud/core/issues/1986#issuecomment-14232839

**Comment by tombrossman** [comment] 2016-03-05 12:43
@RealRancor Interesting, but those are about WebDAV connections and my issue is with the official Linux client. The WebDAV documentation says _["If you prefer, you may also connect your desktop PC to your ownCloud server by using the WebDAV protocol rather than using a special client application."](https://doc.owncloud.org/server/8.2/user_manual/files/access_webdav.html#webdav-configuration)_ which implies different protocols are used.

Does the Linux client use WebDAV? If yes, this is a dupe and apologies for not making that connection (no pun intended...). Users would be helped by a message at account creation telling them to never use special characters in passwords though, if this issue cannot be fixed.

**Comment by RealRancor** [comment] 2016-03-05 12:49
@tombrossman No need to apologize :-)

To answer your question: Yes, the sync client is using WebDAV for its connection to ownCloud. Seems the quoted documentation is a bit misleading here.

But yes, this is probably something which should be fixed in ownCloud or at least warn users.

**Closed** 2016-03-05 12:50 UTC
