### ISSUE TITLE
[OS X] Shorten the name of the accounts in the toolbar.

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#3516] opened 2015-07-29 16:18 UTC
@jancborchardt   So we will do it by elliding, then?

**Comment by jancborchardt** [comment] 2015-07-30 12:57
@ogoffart I thought as @guruz suggested in another issue: 2 lines, first line username, second line server domain (without http and subdomains etc).

But there yes, for wide URLs or names we still need to use ellipsis. Let’s say the max-width should be 3 times the width of the account logo – does that work?

**Comment by guruz** [comment] 2015-07-31 13:00
I pushed something for OS X only (because of different codebase). @ogoffart ?

**Comment by guruz** [comment] 2015-07-31 14:57
I http://download.owncloud.com/desktop/daily/ownCloud%20Testpilot%20Edition-2.0.0.2586-nightly20150731.pkg

Maybe we need to add the \n also to the other tab titles to make it look in a straight line.

**Comment by guruz** [comment] 2015-08-05 09:24
Nothing from @jancborchardt ?

**Comment by jancborchardt** [comment] 2015-08-05 09:55
@guruz I don’t have an OS X machine for testing, so review via screenshot will need to do. Can you take some screenshots?

**Comment by jancborchardt** [comment] 2015-08-05 22:37
@ogoffart @guruz I assume it looks like the screenshot at https://github.com/owncloud/client/issues/3559 then?

It still needs to be ellipsized though – when the name or the server address is too long. Is that in place as well? max-width should be around 3 times the width of the account icon, as said. :)

**Comment by guruz** [comment] 2015-08-06 09:01
Yes, it looks like that screenshot.

Moving this to 2.1.

People actually having issues with the width: Please comment on this bug.

**Comment by phil-davis** [comment] 2015-08-06 09:32
I think I am the worst case my organization will have, so I will put a sample screenshot here.
We use our organization email addresses (authenticated from our mail server) as the ownCloud user names. I happen to have 2 jobs, so 2 work email addresses, my personal email address within the organization (so 3 organization ownCloud accounts to keep my 3 heads separated :) ) and then I have my own family ownCloud that I connect to also. The names end up like:
hospital.support@district.organization.org@theorg.blaucloud.de
info.systems.advisor@organization.org@theorg.blaucloud.de
phil.davis@organization.org@theorg.blaucloud.de
phil.davis@myfamily.blaucloud.de
So the 4 account names spread out a long way across the screen, as in the screen shot.
When I right-click the tool box icon to get the "Open in browser", "Sign out"... options for each account, those become quite wide also. But it seems reasonable and works.
![owncloud-sample-multi-account-client](https://cloud.githubusercontent.com/assets/1535615/9108478/218e3cd4-3c4e-11e5-8425-65133f6b4fed.png)

**Comment by jancborchardt** [comment] 2015-08-06 12:55
So pretty clear the issue is there already. @guruz @ogoffart every string which can potentially be really long needs to be ellipsized at some point

**Comment by ogoffart** [comment] 2015-08-06 15:29
the last build should make it better

**Comment by phil-davis** [comment] 2015-08-06 15:42
Yes, that is much better:
![owncloud-4-accounts](https://cloud.githubusercontent.com/assets/1535615/9115913/3c6ffde8-3c81-11e5-885f-0cb06668cb8d.png)
1) In my case our user names are email addresses, where it has "hospital.support" the actual full user name is like "hospital.support@mycompany.org" - I guess that the parsing to split the line takes everything up to the first "@" sign.
For me it is no problem, the "@mycompany.org" bit would be repetitive anyway.
2) The "blaucloud" part is missing the ".de" - is that intentional to not show the last part of the FQDN?
Again for me it is no problem and is a potential screen-space saver.

**Comment by guruz** [comment] 2015-08-06 15:45
> The "blaucloud" part is missing the ".de" - is that intentional to not show the last part of the FQDN? 

Yes :)

**Comment by guruz** [comment] 2015-08-11 10:13
Just had another idea.. maybe the server admin could define a display name that we deliver to the client as part of the capabilities API..

**Comment by jancborchardt** [comment] 2015-08-11 11:40
@guruz you're kidding, right? Defining an alias is way too much overhead, and doesn't solve the problem.

Ellipsize and that's it.

**Comment by ogoffart** [comment] 2015-08-30 13:36
Done on linux/windows.
Need to still be done on mac.

**Closed** 2016-01-11 11:38 UTC
Labels: Design & UX
