### ISSUE TITLE
[SMB External Storage] File structure messed up in client, online is ok

### ISSUE THREAD

**Issue by MrJackJonesIII** [owncloud/client#4675] opened 2016-04-13 13:08 UTC
### Expected behaviour
When connecting the client to the server fpr the first time I should see the same folder structure as on the server. At the point where you're supposed to chose which folders to sync.

### Actual behaviour
Contents of folder b are shown in folder a. Folder b is not accesible. 

### Steps to reproduce
1. Add an account in windows client
2. Try to choose sync folders from external storage (smb)
3.

### Server configuration
Operating system: Raspian Jessy
Web server: Apache
Database: MariaDB
PHP version: 5.6
ownCloud version (see ownCloud admin page): 9.1
Updated from an older ownCloud or fresh install: fresh
ownCloud log (data/owncloud.log):

Special configuration (external storage, external authentication, reverse proxy, server-side-encryption): external storage on win server via smb

### Client configuration
Client version: 2.1.1
Operating system: Win 10
OS language: German
Installation path of client: "C:\Program Files (x86)\ownCloud\owncloud.exe"

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
https://gist.github.com/MrJackJonesIII/f3ec8eab36d641c3001c5a99502fe753#file-owncloud-client-log

2. Web server error log: Empty

3. ownCloud log (data/owncloud.log):
https://gist.github.com/MrJackJonesIII/d22268633dd959c173657656413cf0f2#file-owncloud-log

![screen_2016-04-13 08-47-42](https://cloud.githubusercontent.com/assets/1665937/14494141/913c02c2-0189-11e6-858a-b346ba167ca2.jpg)
![screen_2016-04-13 08-46-16](https://cloud.githubusercontent.com/assets/1665937/14494142/913ca952-0189-11e6-88c3-709132c24f10.jpg)

**Comment by guruz** [comment] 2016-04-13 13:18
FYI @PVince81 looks like a server issue?

**Comment by MrJackJonesIII** [comment] 2016-04-13 13:25
Ok, should I move the issue to the server section?
I posted it here because the webclient is showing the files correctly.

**Comment by MrJackJonesIII** [comment] 2016-04-13 13:44
I just found out that the issue is present on mac clients as well.

**Comment by guruz** [comment] 2016-04-14 13:54
@MrJackJonesIII Yes, please create a server issue and link it here.
You can also help the people there debugging by listing the "wrong" directory with curl to see what it gives you (the exclude the client from being the reason).
(There is curl on OS X, either pre-installed or via homebrew)

http://stackoverflow.com/a/26676902/2941

**Comment by PVince81** [comment] 2016-04-18 13:28
This looks strange, but not sure if related:
```
{"reqId":"ETS4auffFWflt\/p13Oet","remoteAddr":"88.111.200.208","app":"PHP","message":"array_map(): Argument #2 should be an array at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#75","level":3,"time":"2016-04-12T22:44:50+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"michael"}
{"reqId":"ETS4auffFWflt\/p13Oet","remoteAddr":"88.111.200.208","app":"PHP","message":"array_filter() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps\/files_external\/service\/storagesservice.php#79","level":3,"time":"2016-04-12T22:44:50+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"michael"}
```

@MrJackJonesIII do you have multiple SMB storages, each user with their own ?
Are you sure the user you used in the sync client is the same ? (just to make sure)

So far this kind of result shouldn't technically be possible because what the web UI shows is using the same API/interface like the desktop client do, since ownCloud 9.0.0

Your report mentions that you use ownCloud 9.1, however that version was not released yet.
Did you mean ownCloud 9.0.1 ?

**Comment by MrJackJonesIII** [comment] 2016-04-18 14:01
> do you have multiple SMB storages, each user with their own ?
I have two smb shares set up. Both run on the same machine. All users have the same full access on these shares.

> Are you sure the user you used in the sync client is the same ? 
Yes, absolutely.

> Your report mentions that you use ownCloud 9.1
Yes, I'm sorry, this is just a typo. Installed is 9.0.1

I noticed something else on a second test install in a virtual machine I did today: Some files will not be scaned/recognized properly. They show up as 1KB files even though they have several MBs on the windows machine. maybe that's related?

**Comment by PVince81** [comment] 2016-04-18 14:18
I don't think it's related.

From your screenshots it looks like the web UI shows the folder "001_Kunden" with entries like "001_VORLAGE_ORDER" while the desktop client shows "001_icons".

How do these two subfolders related to your SMB mounts ? Is "001_VORLAGE_ORDER" in the first SMB storage and "001_icons" on the second one ? I'm trying to figure out at which level the mix up is happening.

It could also help if you could run curl:
`% curl -X PROPFIND -u user "http://yourserver.com/owncloud/remote.php/webdav/"` (it will prompt you for the password)
and post the result.

**Comment by PVince81** [comment] 2016-04-18 14:19
One theory is that you maybe somehow managed to have both mount points overlap for that user, and sometimes it returns the files from one and sometimes from another (to be confirmed)

**Comment by MrJackJonesIII** [comment] 2016-04-18 20:30
> From your screenshots it looks like the web UI shows the folder "001_Kunden" with entries like "001_VORLAGE_ORDER" while the desktop client shows "001_icons".

Yes, that's the situation.

> How do these two subfolders related to your SMB mounts ?
There are two smb mounts. One is 001_Kunden, second one is 002_Materialsammlung. 
001_Vorlage_Ordner is the first folder inside of 001_Kunden. Same with 001_icons in 002_Materialsammlung. 

The result of the curl propfind
https://gist.github.com/MrJackJonesIII/279ef0898beeb91c3c4bbd2eecefb8a0#file-curl_propfind

> One theory is that you maybe somehow managed to have both mount points overlap for that user, and sometimes it returns the files from one and sometimes from another (to be confirmed)

I can't think of any setting where I could have achieved that. But... As I said before I managed to set up an other test install. I have it scanning the second share right now and come back to you with the results...

**Comment by PVince81** [comment] 2016-04-19 08:21
> I have two smb shares set up. Both run on the same machine. All users have the same full access on these shares.

Mind posting a screenshot of your external storage config ?
I wonder if you setup two entries, both pointing to "/smb" but with different SMB credentials/shares, and having "All users" as applicable there. If that's the case, then there's an overlap. It shouldn't be an issue but the symptoms you describe would imply that there is a bug in the code that makes it sometimes reverse the order of the overlap.

**Comment by MrJackJonesIII** [comment] 2016-04-19 08:58
![screen_2016-04-19 10-57-05](https://cloud.githubusercontent.com/assets/1665937/14633365/91c1d148-061d-11e6-9cdc-be9d8974027a.jpg)

the unc pathes for those shares are
\\192.168.188.5\001_Kunden
\\192.168.188.5\002_Materialsammlung

**Comment by PVince81** [comment] 2016-04-19 09:25
Hmmm... no overlap here. Are all your affected users in the "admin" group then ?

Can you check your `oc_storages` table and also matching `oc_external_config` ? Goal is to find out that you don't have ghost/hidden/invalid extra entries.

**Comment by MrJackJonesIII** [comment] 2016-04-19 10:15
I had some additional users set up in their own group. I tested them all and it's the same for all of them.

> Can you check your oc_storages table and also matching oc_external_config ?

Please explain a bit what you mean by that. Seems to pay above my paygrade...

**Comment by MrJackJonesIII** [comment] 2016-04-19 11:36
I just finished my alternative setup with the virtual ubuntu server and everything is fine there...
![screen_2016-04-19 13-33-24](https://cloud.githubusercontent.com/assets/1665937/14637729/846445e2-0633-11e6-9f9b-781fd60b1eec.jpg)
So it might just have been a corrupted db or anything. 
If you want to investigate further I'm happy to assist with my broken setup. If not I'm fine with closing here.

**Comment by PVince81** [comment] 2016-04-19 12:42
@MrJackJonesIII use a Mysql/Mariadb client:
- `select * from oc_storages`
- `select * from oc_external_config`

then post the result (make sure to hide confidential info).

**Comment by MrJackJonesIII** [comment] 2016-04-20 16:13
select * from oc_storages:
`+-----------------------------------------------------+------------+-----------+--------------+
| id                                                  | numeric_id | available | last_checked |
+-----------------------------------------------------+------------+-----------+--------------+
| home::baladmin                                      |          1 |         1 |         NULL |
| home::felix                                         |          2 |         1 |         NULL |
| home::manuel                                        |          3 |         1 |         NULL |
| home::michael                                       |          4 |         1 |         NULL |
| smb::owncloud@192.168.188.5//001_Kunden//           |          5 |         1 |   1460648526 |
| failedstorage                                       |          6 |         1 |         NULL |
| smb::owncloud@192.168.188.5//002_Materialsammlung// |          8 |         1 |   1460648525 |
+-----------------------------------------------------+------------+-----------+--------------+`

**Comment by MrJackJonesIII** [comment] 2016-04-20 16:14
select * from oc_external_config
+-----------+----------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| config_id | mount_id | key      | value                                                                                                                                                                              |
+-----------+----------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|         1 |        1 | host     | 192.168.188.5                                                                                                                                                                      |
|         2 |        1 | share    | 001_Kunden                                                                                                                                                                         |
|         3 |        1 | root     |                                                                                                                                                                                    |
|         4 |        1 | domain   |                                                                                                                                                                                    |
|         5 |        1 | user     | owncloud                                                                                                                                                                           |
|         6 |        1 | password | xxx |
|        13 |        3 | host     | 192.168.188.5                                                                                                                                                                      |
|        14 |        3 | share    | 002_Materialsammlung                                                                                                                                                               |
|        15 |        3 | root     |                                                                                                                                                                                    |
|        16 |        3 | domain   |                                                                                                                                                                                    |
|        17 |        3 | user     | owncloud                                                                                                                                                                           |
|        18 |        3 | password | xxx |
+-----------+----------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by PVince81** [comment] 2016-04-20 16:24
Hmmm... all seem fine here. No overlap.
Like you said maybe it was a corrupted DB of some sorts or code mix up during an update.

If the problem is fixed for you now then let's close this.

**Closed by PVince81** 2016-04-20 16:24 UTC
Labels: Server Involved

**Comment by PVince81** [comment] 2016-04-21 10:27
Seems something similar was observed by someone else too: https://github.com/owncloud/core/issues/23771
