### ISSUE TITLE
Local ignore list file like ".gitignore"

### ISSUE THREAD

**Issue by oruchreis** [owncloud/client#4068] opened 2015-11-04 07:44 UTC
We can set ignore patterns through global ignore list. But it will be useful if we can create ignore lists per directory like .gitignore files. For instance, we can put an ignore list file per project directory that includes patterns for bin folder, so if we add a new project directory to the cloud, we simply copy this ignore list file to new project directory.

**Comment by guruz** [comment] 2015-11-04 08:28
Thanks, duplicate of https://github.com/owncloud/client/issues/1558

**Closed by guruz** 2015-11-04 08:28 UTC
