### ISSUE TITLE
Desktop Sharing / Desktop Overlay Icons - show shared by me files

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#3043] opened 2015-03-30 09:17 UTC
When a file is shared to me by another user, the file-manager (e.g. Finder on OS X) indicates this by "extending" the overlay with the sharing icon.
![screen shot 2015-03-30 at 11 03 48](https://cloud.githubusercontent.com/assets/2091312/6893463/751dd1de-d6cd-11e4-86b0-6c45503a34b3.png)
But files I shared with other users or by link are not indicated at all (the upper file in the picture). Would it make sense to add such overlay icons?

Furthermore since desktop sharing has been introduced, imho it would be quite handy to have the possibility to see the shares in the desktop client as it can be on the server (Shared with you / Shared with others / Shared by link).

**Comment by guruz** [comment] 2015-03-31 08:51
This might actually a server bug..
Which server version do you use? I remember there was something related to "Shared" flag being sent down to client as file permission.

CC @icewind1991 @PVince81

**Comment by stonerl** [comment] 2015-03-31 08:54
1.8.0 stable

**Comment by guruz** [comment] 2015-03-31 09:10
@stonerl Server, not client :)

**Comment by stonerl** [comment] 2015-03-31 10:39
@guruz Sorry :-). 8.0.2

**Comment by mihaig11** [comment] 2015-04-07 12:17
I have exactly the same problem with the linux 1.8.0 client and 7.0.5 server.

**Comment by danimo** [comment] 2015-04-07 12:20
@guruz This is not a server bug. It's a true limitation. Problem is again how to reflect it on Windows. All other OSes can have those icons easily I think.

**Comment by guruz** [comment] 2015-04-08 14:21
@danimo This is about 

> But files I shared with other users or by link are not indicated at all (the upper file in the picture). 

_with other_ vs _from other_

@icewind1991 @PVince81 Any comment? :)

**Comment by ogoffart** [comment] 2015-04-08 15:03
We are showing the icon if the server report a "S" bit in the permission field.
Most likely the server don't report the right sharing state.

**Comment by Dianafg76** [comment] 2015-06-02 12:06
I tried the problem in Windows, desktop v 1.8.2 (build 5133 ), Server v{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"} and passes the same

**Comment by dragotin** [comment] 2015-06-02 14:35
Yes, that works as designed: Files that are shared **by me** are not marked as shares. There have been discussions earlier, but that is the status quo IIRC.

**Comment by rullzer** [comment] 2016-03-24 09:00
Now that https://github.com/owncloud/core/pull/22789 is in (and backported to 9.0.1). We could implement this on the client.

Basically ask for the webdav property `share-types` and you get the info you want.

**Comment by guruz** [comment] 2016-04-26 11:38
@rullzer @icewind1991 This means during discovery we always need to ask 1 more property. Which is OK but not nice.
I'm curious, what was the reason for not supplying this info also via ```S``` permission?

**Comment by rullzer** [comment] 2016-04-26 11:53
Well `S` was defined to be shared with you as far as I know.
We could extend this to also include yet another letter to indicated shared by the current user. The new property was chosen because it is cleaner. And we can directly indicate how a file was shared. Which is something clients can chose to do.

**Comment by dragotin** [comment] 2016-05-20 15:04
duplicate of #4788

**Closed by dragotin** 2016-05-20 15:04 UTC
Labels: enhancement - proposed
