### ISSUE TITLE
[OS X/Windows] When the overlay icon is not green, you can't share by link from desktop 

### ISSUE THREAD

**Issue by luciamaestro** [owncloud/client#2775] opened 2015-02-04 09:27 UTC
### Expected behavior

You can't share by link a file or folder which not shown a green overlay icon  
### Actual behavior

We don't have into account he state of the file, if it shows red/yellow/ or even blue overlay icon, you  have the option to share it by link but it keeps loading and it never works 

![captura de pantalla 2015-02-04 a las 8 50 04 am](https://cloud.githubusercontent.com/assets/4689430/6036914/123b4d6c-ac4d-11e4-8e35-4de739b29e96.png)
### Steps to reproduce
1. Click on share by link in a file/folder with red/yellow/ or blue overlay icon 
### Client configuration

Version 1.8.0-nightly20150204(build 1971)

Operating system: OS X 10.10.1

**Comment by rullzer** [comment] 2015-02-04 10:26
This should be solved in the filebrowser plugins but also in the sharedialog. If we try to fetchs the share and get a 404 w should display an error and close the share dialog. I'll prepare a patch for the sharedialog.

**Comment by rullzer** [comment] 2015-02-04 10:33
Ah this is less trivial than expected to fix in the sharedialog! The OCS API returns a 404 is the share does not exist, which is fine since we also want to be able to share non pre-shared files. We should probably file bug against the server to return a different error code if the file/dir we request is not present.

**Comment by guruz** [comment] 2015-02-04 13:10
There is the ```PropfindRequest``` that can be used to check for existance of a remote file.

**Comment by dragotin** [comment] 2015-02-04 14:36
@rullzer the 404 problem is already fixed through 2cee591b0ed01c62635aa61d1b94453794c4e823

**Comment by rullzer** [comment] 2015-02-04 14:40
@dragotin no it is not. The problem is that the server returns 404. So if a share does not exist it return a 404. However we have no way of knowing the difference between:

-- Getting the shares for a valid file/dir but there are none
-- Getting the shares for an invalid file/dir for which there are none

Which makes adding an extra check into the Shardialog harder.

**Comment by dragotin** [comment] 2015-02-04 14:41
@rullzer yes, true. I just realized that and removed my previous comment. Sorry.

I think we can not fix this problem for 1.8.0. I'd vote for moving it to a later milestone.

**Comment by dragotin** [comment] 2015-02-05 11:26
We know the status of each file in the file manager plugins. So it should be possible to first check if the file is ok before giving the option to share. But currently the data is not available to the code to display the context menu, so we need to postpoine this.

**Comment by ckamm** [comment] 2015-04-09 08:48
With @rullzer's patch 5a83636f81dfa28aae5099f1050cf603d43ee47e, the share dialog no longer pops up when the account isn't connected.

Ideally the menu entry wouldn't be shown. Also, you can still open the share dialog while connected, sign out and then get errors when trying to use it.

**Comment by ckamm** [comment] 2015-04-22 10:15
I'm moving this to 1.9 since it's not critical and involves a significant change to all shell integrations.

**Comment by dragotin** [comment] 2015-07-29 09:50
Fixed for the nautilus plugin with https://github.com/owncloud/client/pull/3513

Still needs fixing on Mac and Windows; @jturcotte @guruz pls.

**Comment by rullzer** [comment] 2015-07-31 14:48
Reopening since mac and windows still need fixes.

**Comment by phil-davis** [comment] 2015-07-31 15:09
The nautilus fix #3513 looks a good way to fix this, including the issue as I noticed it in #3527 - simply do not even give the context menu until the file is properly synced. That saves any bother of needing to give the user a message about what is (not) going on.
I guess there might be the odd support query about why "Share with ownCloud" is not in the context menu, so it would be worth pointing out in the documentation somewhere in the documentation that the context menu entry is only available for files/folders that have finished sync to the server.

**Comment by SamuAlfageme** [comment] 2016-12-14 09:02
The State of the Issue™:
* [x] Fixed in OS X (>10.10 at least)
* [ ] Fixed in Windows

**Closed** 2016-12-14 09:10 UTC
Labels: bug, Design & UX, sev2-high
