### ISSUE TITLE
 Desktop Client doesn’t move files rather then download them 

### ISSUE THREAD

**Issue by exzel123** [owncloud/client#6096] opened 2017-10-14 17:30 UTC
### Expected behaviour
Files should be correctly moved by the sync client.

### Actual behaviour
In some cases the files appear again in the original folder

### Steps to reproduce
User 1 creates a folder in the root directory named AAA.
User 1 creates a subfolder in AAA named BBB.

User 1 shares AAA with user 2.
User 1 shares BBB with user 2 and 3.
User 3 creates a subfolder in BBB.
In folder BBB are some files.

If user 3 moves the files from folder BBB to the subfolder in BBB then the sync client makes a mistake with the syncronization.
The files in the folder BBB at user 2 are not moved. They are uploaded again at the original folder in the cloud by user 2. 

And after a while they appear at the folder BBB and the subfolder at user 3. 

### Server configuration
Operating system:

CloudLinux

Web server: 
Apache
Database:
mysql

PHP version:
?
ownCloud version:
10.0.3
Storage backend (external storage):

### Client configuration
Client version:
2.3.3 (build) 8250. Also tested with the 2.4 Alpha.

Operating system:
Windows 7 64bit

OS language:
German

**Comment by hodyroff** [comment] 2017-10-15 20:44
Can you reproduce it with logfiles from user 2 and user 3 as well as the server side?

**Comment by exzel123** [comment] 2017-10-15 21:00
I can sent the logfile from the server. But it's almost impossible for me to get the protokoll from the clients because the owncloud client freezes if I open the logfile windows.

**Comment by exzel123** [comment] 2017-10-16 06:59
But it works correctly in the WebClient. The SyncClient did cause this error.

**Comment by PVince81** [comment] 2017-10-17 08:57
@exzel123 you should be able to open the log file directly from disk instead of looking at the OC client.

Does any of the involved folders (source/target) look weird in the UI, like some appearing twice ? (in case of filecache breakages)

Check owncloud.log from the time of the MOVE for errors.

**Comment by guruz** [comment] 2017-10-17 15:29
What @PVince81 meant is https://doc.owncloud.org/desktop/2.3/troubleshooting.html#saving-files-directly for the client log files to be saved in a file instead of our log window.

(owncloud.log is server side)

**Comment by exzel123** [comment] 2017-10-18 09:09
I replaced the domain in the logfiles but the rest is the same.

Thank you.

[Clientlog.txt](https://github.com/owncloud/client/files/1394035/Clientlog.txt)
[Serverlog.log](https://github.com/owncloud/client/files/1394036/Serverlog.log)

**Comment by exzel123** [comment] 2017-10-18 09:11
And the file which was moved and appeard at the original directory is called "Neues Textdokument"

**Comment by ckamm** [comment] 2017-10-18 09:29
Interesting case! Maybe since both AAA and AAA/BBB are shared with user 2 the client only applies the move to one of them? I'll try to reproduce.

**Comment by ckamm** [comment] 2017-10-18 10:05
Here are some odd log excerpts:
```
INSTRUCTION_REMOVE             client file: B/file
INSTRUCTION_REMOVE             client file: A/B/file

Finding opposite temp through file ID 00000120oc0b5d4d4284: true
Temporary opposite (B/file) found
INSTRUCTION_NONE               server file: B/C/file

Finding opposite temp through file ID 00000120oc0b5d4d4284: true
Temporary opposite (B/file) found
INSTRUCTION_NONE               server file: A/B/C/file

Starting INSTRUCTION_REMOVE propagation of "A/B/file"
Starting INSTRUCTION_SYNC propagation of "B/file"
```
Then the second sync detects A/B/file as new, and downloads it again.

**Comment by exzel123** [comment] 2017-10-18 12:38
Correct. And if you don't share A anymore the sync should be done correctly.

**Comment by ckamm** [comment] 2017-10-18 13:12
The issue is that in `csync_reconcile` when we process an EVAL_RENAME, we don't mark files we've transformed into a RENAME instruction. So the first one sets local B/file to RENAME and server B/C/file to NONE, as expected. But the second one gets into a branch where it'll switch B/file to SYNC and A/B/C/file to NONE.

It seems `getFileRecordByFileId` should be able to return multiple matches and during reconcile we should track which source files have already been consumed (maybe simply by checking for the RENAME instruction).

**Comment by exzel123** [comment] 2017-10-18 13:20
I don't understand what you mean because I'm just an ownCloud user. But it could be solved, correct?

**Comment by ckamm** [comment] 2017-10-19 08:14
@exzel123 Yes, sorry - I was thinking out loud in case other devs want to jump in with gotchas or potential issues.

**Comment by PVince81** [comment] 2017-10-19 08:29
> getFileRecordByFileId

Note that in the event where a user is receiving the same share multiple times through different ways, the file id of the contents would be the same for the same files. Could this cause any confusion in syncing ?

Here is how to create such share:

1. user1 creates a folder "test/sub"
1. user1 creates a file "test/sub/contents.txt"
1. user1 shares "test" with user2 and user3
1. user2 shares the received "test/sub" with user3
1. user3 logs in: two folders "test" and "sub" have been received, and the fileid of "test/sub/contents.txt" and "sub/contents.txt" is the same

@ckamm could this cause any client side issues ?

**Comment by ckamm** [comment] 2017-10-19 08:31
@PVince81 Yes, having multiple items with the same fileid is exactly the problem. See https://github.com/owncloud/client/issues/6096#issuecomment-337585700

**Comment by PVince81** [comment] 2017-10-19 08:41
Note that such sharing scenarios are by design on the server side especially when dealing with different permissions for the two shares. Such shares cannot be cleverly be merged by the server. See https://github.com/owncloud/core/issues/14724

**Comment by exzel123** [comment] 2017-10-19 12:53
@ckamm No problem. I just wanted to say that I can't help anymore. Thank you.

**Closed** 2018-02-08 16:05 UTC
Labels: ReadyToTest, bug
