### ISSUE TITLE
User unable to redownload folder after deleting it.

### ISSUE THREAD

**Issue by MiragePV** [owncloud/client#4321] opened 2015-12-27 17:23 UTC
Using OC 8.2, Windows 7, client 2.1.0

Real scenario:
- An admin shares a folder to a user, specifies access rights.
- User syncs the folder to his machine.
- User opens parent directory and deletes the shared folder.
- The folder becomes "unshared" on server, disappears from user's client sync possibilities, can't be accessed by user anymore, admin has to share it again.

Expected scenario:
- After deleting the folder, it should be redownloaded automatically, as long as the folder is ticked in the client, or the user should be prompted if he wants to disable syncing of the recently-deleted folder. It should definitely not lose its "shared" status regarding the specific user, so he is able to sync it again.

**Comment by rullzer** [comment] 2015-12-28 13:09
This is actually expected behaviour. And not a client issue at all.

If a user deletes a file/folder it is expected to be deleted. If this is a file/folder owned by the user then it will be deleted. If this is a file/folder that is shared with the user it will be unshared.

The same happens when you just use the webdav endpoint. Or the webinterface for that matter. Else a share would only disappear if the owner of the share unshares it. Which is weird since you can't force somebody to have data shared with you.

I'm closing this since it is expected behavour and certainly not a client issue. Feel free to open a ticket in the https://github.com/owncloud/core/issues/ to discuss your usecase.

**Closed by rullzer** 2015-12-28 13:09 UTC
Labels: Discussion

**Comment by gandalf-der-graue** [comment] 2015-12-29 21:17
Thanks @rullzer, exactly true...
