### ISSUE TITLE
[Linux] [Ubuntu 16.04] No tray icon in Xenial

### ISSUE THREAD

**Issue by stephen-d-hill** [owncloud/client#4693] opened 2016-04-17 09:34 UTC
### Expected behaviour
To see icon

### Actual behaviour
No icon

### Steps to reproduce
Install owncloud client

### Client configuration
Client version: 2.1.1+dfsg-1ubuntu1

Operating system: Xubuntu 16.04

OS language: English UK

**Comment by guruz** [comment] 2016-04-18 07:30
What do you see instead?
Can you run the client as ```owncloud --logfile -``` and paste the output?
Which Qt version?

**Comment by stephen-d-hill** [comment] 2016-04-18 09:30
The owncloud main window works fine, just no notification icon.
I am unsure how to find out my QT version.

logfile - 
[owncloud_logfile.txt](https://github.com/owncloud/client/files/223431/owncloud_logfile.txt)

**Comment by guruz** [comment] 2016-04-18 09:44
Thanks, the logfile mentioned it.. ```Using Qt 5.5.1```

Is there nothing before that in the log?

@ckamm @danimo maybe you know more about those tray issues..

**Comment by stephen-d-hill** [comment] 2016-04-18 10:07
Used --logfile instead of --logwindow this time - 
[owncloud_logfile1.txt](https://github.com/owncloud/client/files/223508/owncloud_logfile1.txt)

**Comment by guruz** [comment] 2016-04-18 14:15
Maybe this in Qt 5.6 helps..

```
commit f156c33c2739d84b97cdedf6ae9568b9cea728d5
Author: Dmitry Shachnev <mitya57@gmail.com>
Date:   Fri Apr 1 21:28:00 2016 +0200

    dbustray: Implement better detection of indicator-application
    
    We need to do the icon cache trick all desktops using indicator-application,
    these are not limited to Unity. For example, the default Xubuntu and Lubuntu
    desktops use indicator-application too.
    
    Without this, tray icons will be improperly shown on these desktops.
    
    Change-Id: Id397bbe9b594152d7c3a29c36c853e928af7dde4
    Reviewed-by: Shawn Rutledge <shawn.rutledge@theqtcompany.com>
```

**Comment by guruz** [comment] 2016-04-18 14:16
Some more changes from that Qt branch.. FYI @ckamm 

```
commit a4fac65938fdee74c07d34727920fb74087f82c6
Author: Dmitry Shachnev <mitya57@gmail.com>
Date:   Sat Feb 6 14:42:39 2016 +0300

    dbustray: Support late registering of tray icon menu
    
    If a menu is added to the tray icon after the icon itself has been registered,
    we need to register the menu properly.
    
    Change-Id: I19a6d78848142d66c2cd882746d8d55c0b9a2818
    Reviewed-by: Błażej Szczygieł <spaz16@wp.pl>
    Reviewed-by: Shawn Rutledge <shawn.rutledge@theqtcompany.com>

commit 7ad930987da7bb1d9aed17f25a1d99eeb5574a42
Author: Dmitry Shachnev <mitya57@gmail.com>
Date:   Sat Feb 6 19:12:52 2016 +0300

    dbustray: Do not change m_menu in QDBusTrayIcon::createMenu()
    
    This method can be called for a submenu after it's called for the top-level
    menu, and we should not replace it with a submenu.
    
    Change-Id: I8e180ee074287cfcdc76dfe77c6c7aa7d5891741
    Reviewed-by: Błażej Szczygieł <spaz16@wp.pl>
    Reviewed-by: Shawn Rutledge <shawn.rutledge@theqtcompany.com>
```

**Comment by scroom** [comment] 2016-04-22 11:11
Can I provide more info? I'm as well experiencing this bug.

**Comment by danimo** [comment] 2016-04-22 14:09
I now upgraded to 16.04 and the packages and I can confirm above findings. The workaround for now is to use the Ubuntu 15.10 packages provided by us. Those still are Qt4 based but solve the problem.

**Comment by danimo** [comment] 2016-04-22 14:22
I filed https://bugs.launchpad.net/ubuntu/+source/owncloud-client/+bug/1573639 with Ubuntu.

**Comment by danimo** [comment] 2016-04-22 14:37
This must be a special bug related to the way we rebuild the System tray. A trivial example works just fine.

```
#include <QApplication>
#include <QSystemTrayIcon>
#include <QImage>
#include <QPixmap>
#include <QMenu>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    QImage img(64,64, QImage::Format_ARGB32);
    img.fill(Qt::red);
    QSystemTrayIcon sti(QIcon(QPixmap::fromImage(img)));
    QMenu *menu = new QMenu();
    menu->addAction("Foo");
    menu->addAction("Bar");
    menu->addSeparator();
    QMenu *submenu = new QMenu("Sub Menu");
    submenu->addAction("Bleh");
    menu->addMenu(submenu);
    menu->addSeparator();
    QObject::connect(menu->addAction("Quit"), SIGNAL(triggered(bool)), &a, SLOT(quit()));
    sti.setContextMenu(menu);
    sti.show();

    return a.exec();
}
```

**Comment by Mustangman1966** [comment] 2016-04-24 12:18
Expected behaviour

To see icon

Actual behaviour

No icon

Steps to reproduce

Install owncloud client

Client configuration

Client version: 2.1.1+dfsg-1ubuntu1

Operating system: ubuntu 16.04

OS language: Dutch

**Comment by danimo** [comment] 2016-04-24 18:06
We know, please do not post any +1's. We are working on a solution to the problem.

**Comment by ogoffart** [comment] 2016-04-25 14:42
I was able to locate the problem.  The problem is in ubuntu's "appmenu-qt5" and is a bug that cause our call to QSystemTrayIcon::isSystemTrayAvailable()  to remove the icon.

That's because appmenu-qt5 seems to assume there is only one QPlatformSystemTrayIcon while there can be one per QSystemTrayIcon.  in particular, QSystemTrayIcon::isSystemTrayAvailable creates a temporary one, and when it gets distroyed, it unregister the dbus object for the existing systray.

**Comment by guruz** [comment] 2016-04-25 14:47
FYI @mitya57

**Comment by mitya57** [comment] 2016-04-25 14:57
Thanks @guruz for pointing me to this, and thanks to @ogoffart for narrowing down the problem.

Appmenu-qt5 is dead, and we want to remove it from Ubuntu as soon as our Qt is updated to 5.6 (which has native support for D-Bus trays and global menus). However, provided that 16.04 is an LTS release, it may make sense to get the appmenu-qt5 bug fixed there. I will add it to my list, however I have very few time, so I don't know when I will be able to get to it. Merge proposals against lp:appmenu-qt5 welcome, of course :)

**Comment by guruz** [comment] 2016-04-25 15:01
@mitya57 thanks for the reply :) Then we need to workaround it from our side. ```XDG_CURRENT_DESKTOP``` should be ```Unity``` on 16.04?

**Comment by nazar-pc** [comment] 2016-04-25 15:04
Yes
```
~>  echo $XDG_CURRENT_DESKTOP 
Unity
```

**Comment by mitya57** [comment] 2016-04-25 15:04
`$XDG_CURRENT_DESKTOP` depends on environment, but it's not related to this bug.

For workaround on your side, try checking for `$QT_QPA_PLATFORMTHEME` and unsetting it if it's equal to `appmenu-qt5` (before constructing the QGuiApplication).

**Comment by ogoffart** [comment] 2016-04-25 15:11
I reported the bug to appmenu-qt5:   https://bugs.launchpad.net/appmenu-qt5/+bug/1574699

**Comment by Arrakeen** [comment] 2016-04-26 10:01
A temporary workaround for those who can't live without that precious little icon. A `sudo apt-get remove appmenu-qt5` resolves the issue. If you use qt applications and you need to see them appear in your app menus, you might better wait for an official fix.

**Comment by ogoffart** [comment] 2016-04-26 10:30
Also another way to workaround the problem is to run owncloud with `--platformtheme=generic`  command line option

**Comment by dragotin** [comment] 2016-04-26 11:47
Ok, I think we can live with the workaround mentioned by @ogoffart and document that very prominentely. 

We should continue to work with Ubuntu to help them fixing that as good as we can, @ogoffart already created the bug report. 

@jnweiger could we add a start script that calls owncloud with parameter `--platform=generic`  with affordable effort to the package?

**Comment by rhersel** [comment] 2016-04-26 21:46
@ogoffart This workaround does not work for me: --platformtheme is an unknown option for /usr/bin/owncloud on Ubuntu 16.04 with owncloud-client installed from Gnome-Software.

**Comment by ogoffart** [comment] 2016-04-27 07:53
@rhersel works fine here with the owncloud client installed from whatever `apt-get install owncloud`  does.
If --platformtheme is an unkown option that might mean that owncloud was compiled with Qt4 instead of Qt5?

**Comment by ogoffart** [comment] 2016-04-27 08:13
Workaround pull request for 2.2: https://github.com/owncloud/client/pull/4747

**Comment by ogoffart** [comment] 2016-04-27 16:30
I tested the qt4 version on ubuntu, and it works well.

**Comment by stephen-d-hill** [comment] 2016-04-27 18:08
Performing

   sudo apt-get remove appmenu-qt5

works for me :)

**Comment by step4wd** [comment] 2016-04-29 10:21
Running `owncloud --platformtheme=generic` gives the following output:
```
Unrecognized option '--platformtheme=generic'
Try 'owncloud --help' for more information
```

I tried `sudo apt-get remove appmenu-qt5` also but didn't help.

**Comment by ogoffart** [comment] 2016-04-29 10:32
@step4wd then you are using the Qt4 version.  The Qt4 version works for me. What is your problem exactly? Which owncloud package are you using?

**Comment by step4wd** [comment] 2016-04-29 10:35
@ogoffart I installed owncloud-client which comes with Ubuntu 16.04 as it is.

**Comment by oserban** [comment] 2016-04-29 10:38
The default owncloud client on Ubuntu Xenial (as returned by owncloud --version) is:
ownCloud version 2.1.1
Using Qt 5.5.1

**Comment by s-light** [comment] 2016-04-29 11:01
for me its the same:
```
stefan@stefan-latitude:~$ owncloud --platformtheme=generic
Unrecognized option '--platformtheme=generic'
Try 'owncloud --help' for more information
stefan@stefan-latitude:~$ owncloud --version
ownCloud version 2.1.1
Using Qt 5.5.1
stefan@stefan-latitude:~$ owncloud --help
ownCloud version 2.1.1
File synchronisation desktop utility.

Options:
  -h --help            : show this help screen.
  --logwindow          : open a window to show log output.
  --logfile <filename> : write log output to file <filename>.
  --logdir <name>      : write each sync log output in a new file
                         in folder <name>.
  --logexpire <hours>  : removes logs older than <hours> hours.
                         (to be used with --logdir)
  --logflush           : flush the log file after every write.
  --confdir <dirname>  : Use the given configuration folder.

For more information, see http://www.owncloud.org
```
my system is an Kubuntu 16.04 64bit

**Comment by jmfrappier** [comment] 2016-04-29 17:57
Same thing as @oserban and @step4wd with version and error launching owncloud --platformtheme=generic
Just launching owncloud still works as i sometimes get a notification that some files have been copied.

**Comment by Steve-3d** [comment] 2016-04-29 21:53
I got the error with the unsupported command line option, too - but doing
export QT_QPA_PLATFORMTHEME=generic
before starting owncloud as usual works now and I get the icon back.

**Comment by step4wd** [comment] 2016-04-30 03:30
@Steve-3d it worked for me. Now how to make owncloud always launch this way on startup? This is changing an environment variable which assume will effect other apps also.

**Comment by Steve-3d** [comment] 2016-04-30 07:43
I created a little script for this:

    #!/bin/bash  
    QT_QPA_PLATFORMTHEME=generic  
    /usr/bin/owncloud

This sets the variable only for the current shell process and does not modify anything else. 
Then I did a `chmod +x ownCloudScript.sh` and added it with full absolute path into the 
start programs tool to let it always run on login.
I hope this helps :)

**Comment by rhersel** [comment] 2016-04-30 16:35
The above script works perfectly for me. Thank you

**Comment by frederikbosch** [comment] 2016-05-02 09:59
And modify your startup file.

```sh
sudo nano /usr/bin/owncloud-tray-fix
sudo chmod +x /usr/bin/owncloud-tray-fix
nano ~/.config/autostart/owncloud.desktop
```

Modify the Exec line as foloows.
```
Exec=owncloud-tray-fix
```

**Comment by VNovotna** [comment] 2016-05-02 10:16
Running owncloud like this `env QT_QPA_PLATFORMTHEME=generic owncloud` is even easier.

**Comment by didubu-fr** [comment] 2016-05-03 06:23
Hello,
They solved the problem at Ubuntu, a new package was released in Yakkety and Xenial proposed : https://bugs.launchpad.net/ubuntu/+source/owncloud-client/+bug/1573639/comments/11
Thanks !

**Closed** 2016-05-03 07:48 UTC
Labels: bug, Platform Specific, sev2-high

**Comment by geez0x1** [comment] 2016-05-12 16:12
Has anybody tested this on Debian 8 (stable/jessie)? I just installed client 2.2.0 and the icon has disappeared, it seems.

**Comment by nazar-pc** [comment] 2016-05-12 16:17
Funny, but it just appeared with 2.2.0 update on Ubuntu:)

**Comment by etamme** [comment] 2016-05-12 17:48
I am not sure ... but this may have broken the system tray icon for my 14.04 installation.  Here is a gist of my apt-history for the day:

https://gist.github.com/etamme/9e547c536b44f7a3f2b0998b8765bd94

Basically now the systray icon is in the very top left of my screen and appears "on top" of any window.

**Comment by nazar-pc** [comment] 2016-05-12 17:49
There was such bug some long time ago, like 1.5 years or so.

**Comment by etamme** [comment] 2016-05-12 17:50
So yea I saw that when I was searching, but this morning my systray icon was fine, but after I installed the updates in the linked gist, the owncloud systray icon got messed up.

**Comment by K0sme** [comment] 2016-05-13 15:15
In Debian 8 (Jessie) missing tray icon after update to the 2.2.0 version :(

**Comment by cmburg** [comment] 2016-05-14 03:33
Same in elementary OS 0.3 (64bit) (32 bit not tested yet but had not problems at all IIRC)

**Comment by DroWnThePoor** [comment] 2016-05-14 07:15
I'm having this problem as well.No tray icon at all since last 2 updates.
I have another machine running the client before the updates and it works perfectly.
I was wondering what exactly I'd need to do to transfer that version of the client from one 
Ubuntu install to another?
Can anyone advise me?

**Comment by tony5** [comment] 2016-05-14 12:50
It has already been acknowledged that there is a bug and a work around has been posted.

The client still works with out the tray icon but if you need it then the commands posted above will work.

You can adjust the program startup or manually run the bellow command in a terminal. 

~$ killall owncloud && nohup env QT_QPA_PLATFORMTHEME=generic owncloud >/dev/null &

**Comment by mitya57** [comment] 2016-05-14 17:24
I have created a proper fix for this bug in appmenu-qt5. While I'm waiting for [a review](https://code.launchpad.net/~mitya57/appmenu-qt5/lp1574699/+merge/294381) I have uploaded the package with this fix to my [PPA](https://launchpad.net/~mitya57/+archive/ubuntu/ppa) so that you can test it.

Commands to get the package from my PPA are:

    sudo add-apt-repository ppa:mitya57/ppa
    sudo apt-get update
    sudo apt-get install appmenu-qt5

Please test and give your feedback.

**Comment by tony5** [comment] 2016-05-14 21:31
@mitya57 
did not work for me, maybe I did it wrong. I did not add the ppa but installed 
appmenu-qt5_0.3.0+16.04.20151130-0ubuntu1+ppa1_amd64.deb from your link
removing appmenu-qt5 all together will work
or 
adjust start up
~$ killall owncloud && nohup env QT_QPA_PLATFORMTHEME=generic owncloud >/dev/null &

**Comment by mitya57** [comment] 2016-05-16 13:24
Can somebody else try that PPA? It is quite strange it did not work for you @tony5…

**Comment by robmi77** [comment] 2016-05-18 05:39
same as mitya57. Did not work for me either. add the ppa, update and installed appmenu-qt5.
"Setting up appmenu-qt5 (0.3.0+16.04.20151130-0ubuntu1+ppa1)"
running ubuntu 16.04 lts with xfce4-panel and owncloud 2.2.0. No icon tray.
If I remove the the newly installed appmenu.qt5 the owncloud icon appears in the systray.

**Comment by nickvergessen** [comment] 2016-05-18 08:38
The workaround from https://github.com/owncloud/client/issues/4693#issuecomment-215944779 also helped on Linux Mint 17.3 (based on Ubuntu 14.04) using Qt 5.2.1

**Comment by detly** [comment] 2016-11-26 02:56
Still have this bug on Ubuntu 16.04.1 LTS. @tony5's PPA didn't change it.

`appmenu-qt5: 0.3.0+16.04.20151130-0ubuntu1`
`owncloud-client: 2.2.4-1.3` (from OwnCloud PPA)

The workaround of changing `Exec=owncloud` to `Exec=env QT_QPA_PLATFORMTHEME=generic owncloud` does not make the tray icon appear, even after reboot.

**Comment by detly** [comment] 2016-11-26 05:01
Turns out I had to change the entry in Gnome's startup applications (from `/usr/bin/owncloud` to `/usr/bin/env QT_QPA_PLATFORMTHEME=generic owncloud`).

**Comment by christiandreher** [comment] 2016-12-18 16:40
I also have this issue on Ubunu 16.10. The icon disappears a few minutes after owncloud launches. Do I really have to apply some hacks to get it to work? The issue indicates that this was fixed, so I don't know whether this is considered already fixed or there was some regression or so...

**Comment by mitya57** [comment] 2016-12-19 19:00
@christiandreher You have not specified which version of owncloud are you using, and whether or not you have appmenu-qt5 installed.

Anyway, today I have uploaded a new version of owncloud-client package to Ubuntu 16.10, with #5072 backported, which should make it a bit better. It should be ready for testing in proposed pocket in a couple of days. This is tracked in [LP: #1635577](https://launchpad.net/bugs/1635577).

**Comment by christiandreher** [comment] 2016-12-20 13:51
@mitya57 sorry for the lack of information. When I wrote this, I was on the lastest release which was available in the 16_10 repository. I also found out that the icon disappears whenever I suspend my laptop. So after a reboot it works, but when I suspend it and wake it up again the icon will look like on this screenshot (the one in the middle with the red crossed circle)

<img src="https://ubuntu-mate.community/uploads/default/original/2X/7/73d122d2055d5bde53a1f4cf9fa18a272bc70d55.png" />

As soon as I am back on the machine I will try the updated version and let you know whether it helped or not. Thanks for the heads up :)

**Comment by mitya57** [comment] 2017-01-04 22:17
@christiandreher A [new version](https://launchpad.net/ubuntu/+source/owncloud-client/2.2.2+dfsg-1ubuntu0.2) was accepted into Ubuntu 16.10 Proposed repository today, please try it.

**Comment by mitya57** [comment] 2017-01-05 10:08
@guruz All right, Ubuntu 16.10 shipped with 2.2.2, I backported some fixes to that version. Ubuntu 17.04 has 2.2.4.

**Comment by yendar28** [comment] 2017-01-12 19:52
Hi, since some days I have the same problem and found an easy workaround for me. There were some qt5 files in the last update using Xubuntu.

Workaround: Right-Click on Start Icon in Systray -> Properties -> Edit the currently selected Item -> Then activate "Use startup notification"

After some tries the systray-icon vanished again. So I deactivated "Use startup notification" this time and the icon appeared again after owncloud start. Do not ask me why. ;-)
Starting owncloud from terminal also works.

My System:
Xubuntu 14.04 (xfce)
owncloud client 2.2.4
using Qt 5.2.1

**Comment by FlorianFranzen** [comment] 2017-07-10 09:38
@stephen-d-hill solutions works well, which is uninstall ```appmenu-qt5```.
