### ISSUE TITLE
Internal Error 1062

### ISSUE THREAD

**Issue by mydpy** [owncloud/client#3128] opened 2015-04-18 11:34 UTC
I am having a problem syncing a large folder to ownCloud (4GB). Using the Mac desktop client I am get a 1062 internal error (log attached). I fixed this issue in the immediate-term by removing the synced folder and adding a new one on my local machine. 

### Expected behaviour
1. Establish local folder to sync with remote ownCloud directory(ies)
2. Add files, retrieve files, etc.; normal use
3. Add time and unknown variables (server upgrades, internals, etc.) between use
4. Add files, retrieve files, etc. 

### Actual behaviour
1. Establish local folder to sync with remote ownCloud directory(ies)
2. Add files, retrieve files, etc.; normal use
3. Add time and unknown variables (server upgrades, internals, etc.) between use
4. Try to add files. Cannot establish a connection. Try to reconnect, get an internal server error (1062)
5. Delete the local folder
6. Repeat step 1
7. Normal use resumes

### Steps to reproduce
(See above)

### Server configuration
Operating system: RHEL6.6, Fully Patched.
Web server: Apache/2.2.15
Database: MySQL 5.1.73
PHP version: 5.3.3
ownCloud version: 7.0.4
Storage backend: local storage (EXT4)

### Client configuration
Client version: Version 1.8.0 Build 2139 
Operating system: MacOSX 10.10.2
Installation path of client: /Applications/owncloud.app

### Logs
Gist: https://gist.github.com/mydpy/15ed1f97545db36dc270

**Comment by RealRancor** [comment] 2015-04-19 17:41
Hi,

for internal server error you should check the error log of your server. The best is also to fill out the issue template provided here:

https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

as requested in the "guidelines for contributing" (linked in the yellow box when creating a new issue).

**Comment by guruz** [comment] 2015-04-20 08:39
@mydpy btw, you can use https://gist.github.com for text files

**Comment by guruz** [comment] 2015-05-05 16:20
Please try with 1.8.1rc2 and a current server version

**Comment by mydpy** [comment] 2015-05-05 19:15
@guruz I edited my original post with information to better document the environment the issue was created in. I will update my client and try to recreate the issue tomorrow and report back. Thanks!

**Comment by cdamken** [comment] 2015-08-03 11:17
@mydpy Is solved with the upgrade?

I also see that your php is 5.3: https://doc.owncloud.com/server/7.0EE/admin_manual/oCEE_release_notes.html#recommend-php-5-4-and-up

@guruz  Could that be the problem?

**Comment by guruz** [comment] 2015-08-03 11:20
Thanks for pointing out @cdamken 

Indeed, please try with newer PHP and a recent 2.x nightly release http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.2592-nightly20150803.pkg

If it persists, we can re-open:)

**Comment by Toffe87** [comment] 2015-08-04 10:42
Hi.

Think this should be reopened, have this problem on the latest version myself. Its during "Discovery" it yelds the error, so not yet connected to the "internet". Cant really seem to find out what the error means? Can someone browse the source and figure it out maybe? 1062 seems to be kinda random, not yet found an answere on what to look for. Is it file naming? File too big? File not accessible? e.t.c.


--
08-04 12:33:20:256 0x7fd333cc8ad0 _csync_detect_update: Checking for rename based on inode # 944736
08-04 12:33:20:256 0x7fd333cc8ad0 _csync_detect_update: file: Usortert/mP3/Stafford Brothers feat. Ollie James - Falling (Starkillers Remix) [facebook_Stomp's Playlist].mp3, instruction: INSTRUCTION_NEW <<=
08-04 12:33:20:256 0x7fd333cc8ad0 csync_walker: file: /Users/toffe/Private/Usortert/mP3/The Wanted - Chasing the Sun (Mario Larrea Club Mix).mp3 [inode=944738 size=5495223]
08-04 12:33:20:256 0x7fd333cc8ad0 _csync_detect_update: Checking for rename based on inode # 944738
08-04 12:33:20:256 0x7fd333cc8ad0 _csync_detect_update: file: Usortert/mP3/The Wanted - Chasing the Sun (Mario Larrea Club Mix).mp3, instruction: INSTRUCTION_NEW <<=
08-04 12:33:20:256 0x7fd333cc8ad0 csync_statedb_close: sqlite3_close=0
08-04 12:33:20:257 0x7fd331711cf0 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "An internal error number 1062 occurred."
08-04 12:33:20:260 0x7fd331711cf0 OCC::SyncEngine::finalize: CSync run took  4054
08-04 12:33:20:261 0x7fd331711cf0 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
08-04 12:33:20:261 0x7fd331711cf0 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  0  Milliseconds.
08-04 12:33:20:261 0x7fd331711cf0 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  2
08-04 12:33:20:261 0x7fd331711cf0 OCC::Folder::slotSyncFinished:   ** error Strings:  ("An internal error number 1062 occurred.")
08-04 12:33:20:261 0x7fd331711cf0 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
08-04 12:33:20:261 0x7fd331711cf0 OCC::Folder::slotSyncFinished: the last 1 syncs failed
08-04 12:33:20:262 0x7fd331711cf0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/toffe/Private/"
08-04 12:33:20:262 0x7fd331711cf0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:/Users/toffe/Private/"

**Comment by guruz** [comment] 2015-08-04 10:50
@Toffe87 What is "latest version"? You're on OS X?

**Comment by Toffe87** [comment] 2015-08-04 10:54
Hi, latest version is the version which is current out there. Yes for OSX :) I get this error on OSX 1.8.4 Client

Latest stable version: 1.8.4

**Comment by guruz** [comment] 2015-08-04 11:03
Hmm that's a ```CSYNC_STATUS_READDIR_ERROR``` if ```csync_vio_readdir``` returns 0.

**Comment by guruz** [comment] 2015-08-04 11:07
If you check ```Usortert/mP3/``` is there a file with an unusual name? 

CC @ogoffart

**Comment by guruz** [comment] 2015-08-04 11:15
@mydpy Btw, judging from your log it is NOT an internal _server_ error :-) 

>  I fixed this issue in the immediate-term by removing the synced folder and adding a new one on my local machine.

You did not change/rename any local file, you just removed the folder from the configuration and added it again then it worked? That's quite weird..

**Comment by Toffe87** [comment] 2015-08-04 11:16
https://gist.github.com/Toffe87/154a15d7ab85548c9c6e

This is the mP3 (ls -lah > list.txt)

**Comment by Toffe87** [comment] 2015-08-04 11:18
Update: i tried adding ONLY the mp3 folder to sync, now atleast i get that error really fast. I'll try removing some of the shady characters.

**Comment by Toffe87** [comment] 2015-08-04 11:26
Removed one and one mp3 and resynced the folder. Found out that the file which makes 1062 error is:

The Wanted - Glad You﻿ Came (DJ Marley D Club Mix).mp3 

Terminal shows: 
-rwxrwxrwx   1 toffe  staff   6.0M May 18  2012 The Wanted - Glad You? Came (DJ Marley D Club Mix).mp3

There is a special "character" after "You" there which cant be seen. And creates 1062 error. That should be fixed in owncloud somehow.

**Comment by ogoffart** [comment] 2015-08-04 11:37
Looks like a duplicate of #2777

**Comment by Toffe87** [comment] 2015-08-04 11:40
Debugging:

Filename: The Wanted - Glad You﻿ Came (DJ Marley D Club Mix).mp3
Strlen: 56
Fetching part after 'U' in You and befoce 'C' in Come
Troubled part: ﻿ 
Strlen of that: 4 characters between U and C.. Wierd..
1: ? ASCII: 239
2: ? ASCII: 187
3: ? ASCII: 191
4:   ASCII: 32
The last one are a regulare space, so 3 characters between 'U' and the space shown before 'C'

**Comment by guruz** [comment] 2015-08-04 16:16
Dup of #2777 let's talk there. Thanks @Toffe87

**Closed by guruz** 2015-08-04 16:16 UTC
Labels: bug, Needs info

**Comment by guruz** [comment] 2015-08-05 16:44
We have a 2.0 nightly available that should show a nice error with the failing filename
http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.2602-nightly20150805.pkg

Please test..
