### ISSUE TITLE
[OS X] New folder created locally isn't being synced - file name case issue?

### ISSUE THREAD

**Issue by conradhagemans** [owncloud/client#4296] opened 2015-12-17 13:52 UTC
I am on client 2.1.0 on OS X 10.11.2. Owncloud 8.2.1 (Ubuntu Linux)

I created a new local share on the linux machine. Added it to the client sync list.

If a put files on my mac into the folder they are not synced to the server.
If I open the client, pause sync and resume sync. The client noticed that there are new/changed files and will sync them succesfull to the server.

Only manualy pause/resume will sync the files.

**Comment by conradhagemans** [comment] 2015-12-17 13:54
If I however add a new file to the server folder via the webclient the sync client on OS X is being informed a will nicely sync and update the local folder on my mac.

So it looks like that the os X client cannot see that there are any changes localy.

**Comment by guruz** [comment] 2015-12-18 14:21
Do you use any special drive configuration on your Mac?

You could use ```Terminal.app``` to run the client like this and see if it creates a lot output (of the file watcher) when running ```/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -``` (including the ```-```)

**Comment by conradhagemans** [comment] 2015-12-18 14:35
Thanks for the reply.
I tested this via the terminal window.

If I drop a new file into this folder I see the following message in the terminal window:

12-18 15:29:08:975 0x7fb25ac332f0 OCC::FolderWatcher::pathIsIgnored: * Ignoring file "/Users/conradhagemans/Owncloud/gen2/Screen Shot 2015-12-09 at 11.22.03.png"

This is strange? Why is this folder ignored?

![screen shot 2015-12-18 at 15 35 03](https://cloud.githubusercontent.com/assets/9007177/11899075/f0d1d714-a59c-11e5-96a6-e8dea0debd58.png)

**Comment by guruz** [comment] 2015-12-18 14:39
@ogoffart Can it be that @conradhagemans unchecked the root in the setup wizard now and new subdirs are always unselected?

**Comment by conradhagemans** [comment] 2015-12-18 14:45
Hmm. I do not have a root check-box as you can see. I have 5 links to my server.

![screen shot 2015-12-18 at 15 44 24](https://cloud.githubusercontent.com/assets/9007177/11899292/433547e2-a59e-11e5-80cb-b7340b98e72e.png)

Extra info.

I did not create this folder localy initialy. But used the web-frontend to create a new share to a existing folder on the linux server.
![screen shot 2015-12-18 at 15 41 23](https://cloud.githubusercontent.com/assets/9007177/11899226/daaaf8a2-a59d-11e5-89e0-7b582627fe46.png)

**Comment by ogoffart** [comment] 2015-12-19 11:17
one cannot uncheck the root, that's impossible.

Maybe the threshold for new folder is too low?

**Comment by guruz** [comment] 2015-12-19 18:39
@conradhagemans At your screenshot you pasted later you have all checkboxes [x] checked. Then it should work?

**Comment by conradhagemans** [comment] 2015-12-19 20:12
Exactly. But it doesn't. Thats why I raised this issue.

**Comment by conradhagemans** [comment] 2015-12-19 20:17
The problem occurs with files I place/remove in the /gen2 folder. I will do some checking if the same problem occurs in it's sub-folders like /gen2/tests/

**Comment by conradhagemans** [comment] 2015-12-20 00:37
I decided to delete the local folder on my mac and removed the sync in the client.
I then created the folder again and added to the sync list in the client.
Client started to download all the files from the server.
Now the sync runs fine. I can delete/add new files and they are uploaded instandly.

Thank for all the help.
Looks like the problem solved itself.
I will close the issue. Reopen it if it occurs again.

**Comment by 1Fopresta** [comment] 2016-03-16 08:48
Hi. I think this issue can be re-open : i have the same problem.
The new folders are not sync, except if i restart desktop client.
System : OS X 10.11.3
Desktop client : 2.1.1
The log tell me that the folders are ignored. The ignore list is the default list.
Example name folder : /Users/toto/Desktop/cloud/test (/Users/toto/Desktop/cloud/ is the root folder for Owncloud)

I have delete and re-create the root folder : all files and folders are download but when i create a new folder : same problem.
I uninstall and re-install the desktop client : same problem.

**Comment by guruz** [comment] 2016-03-16 09:05
Are you sure the folder is checked [X] in the UI?

**Comment by 1Fopresta** [comment] 2016-03-16 09:09
Yes. And the folder not sync can be /Users/toto/Desktop/cloud/work/pictures (with other folders in /Users/toto/Desktop/cloud/work/ that are sync)

**Comment by guruz** [comment] 2016-03-16 09:15
Could you make a screenshot how this shows up in the UI?
Could you attach a log?

**Comment by 1Fopresta** [comment] 2016-03-16 14:28
Ok, i found the problem.
In the filesystem, the path is : /Users/toto/Desktop/CLOUD
In desktop client, the path is : /Users/toto/Desktop/cloud
The filesystem on this Mac is not case sensitive. I think it is the reason why desktop client can access to the path but the detection of a new folder not work because CLOUD is not equual to cloud in case sensitive.
I renamed /Users/toto/Desktop/CLOUD in /Users/toto/Desktop/cloud and now it works fine !

**Comment by guruz** [comment] 2016-03-16 14:49
@1Fopresta thanks, interesting.. 
What do you mean by filesystem? On the server? Or your local file system?
And by desktop client you mean the UI?
Maybe there is still something we're doing wrong..

**Comment by 1Fopresta** [comment] 2016-03-16 15:31
The local file system (HFS+).
For the desktop client yes i mean the UI.
I don't know where is the real problem with Mac OS and HFS+ in non-sensitive case mode : Onwcloud UI ? Csync ? The "inotify" of Mac OS ?

**Comment by guruz** [comment] 2016-03-16 15:36
And did you do things like create the two folders with different casing on oC web and desktop?

Let's re-open this to evaluate..
@ogoffart @dragotin

**Comment by dragotin** [comment] 2016-03-16 15:57
Remember that HFS+ is case **in**sensitive by default, as windows is. What happened here is intended and prevents data loss.

**Comment by dragotin** [comment] 2016-03-16 15:58
Read rants about that for example by linus torwalds: http://www.cio.com/article/2868393/linus-torvalds-apples-hfs-is-probably-the-worst-file-system-ever.html

**Comment by dragotin** [comment] 2016-04-22 06:04
Please see my last two comments. I think we can close this. @ogoffart ?

**Comment by ogoffart** [comment] 2016-04-22 08:18
yes, it's the expected behavior:  we don't sync folder that have a case conflict and it should be shown in the error tab of the activities.

**Closed by ogoffart** 2016-04-22 08:18 UTC
Labels: bug, sev2-high
