### ISSUE TITLE
Client not always stops when requested by Windows

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8979] opened 2021-09-07 11:30 UTC
Seen (again) with 2.9.0-rc2

* run any older version of the owncloud client
* Download the msi installer of an update
* click start the install.
* It announces, it needs to shutdown `owncloud` and sometimes also `explorer`
* when the user confirms. It usually fails to shut down one of the two.

![image](https://user-images.githubusercontent.com/1108546/132337510-6b513671-d689-4c85-8635-a95cb813c947.png)

After a second round it normally succeeds.

**Comment by michaelstingl** [comment] 2021-09-07 14:32
Anything in the MSI log?
https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/enable-windows-installer-logging

**Comment by TheOneRing** [comment] 2021-10-08 07:02
TODO: Test how the client reacts to WM_CLOSE
@dschmidt I assume WM_CLOSE is what msi sends to the client?

**Comment by TheOneRing** [comment] 2021-10-11 09:35
See: 
https://www.advancedinstaller.com/user-guide/qa-vista-restart-manager.html
https://wixtoolset.org/documentation/manual/v3/xsd/util/restartresource.html

looks like we can add code to better handle this

Also see:
https://docs.microsoft.com/en-us/windows/win32/shutdown/wm-queryendsession
https://docs.microsoft.com/en-us/windows/win32/shutdown/wm-endsession

**Comment by TheOneRing** [comment] 2021-11-16 15:06
The issue still occurs, in order to be able to receive  the message, it appears that the window needs to shown at least once.

**Comment by TheOneRing** [comment] 2021-11-17 12:07
Please test with [close_window.zip](https://github.com/owncloud/client/files/7554448/close_window.zip).
`close_window owncloud.exe` 

With older clients the expected behaviour is that the client keeps running, independent if the settings ui was shown or not.
Once https://github.com/owncloud/client/pull/9220 was merged the client should shutdown cleanly.

Additionally please check whether the client closes cleanly when the user logs off, with an old client and a new client.
Please test what happens when the client is updated by the installer, does the running owncloud.exe close as expected?

A clean shutdown should look similar to:
```
11-17 13:06:38:279 [ info sync.utility ]:	Received WM_ENDSESSION quitting
11-17 13:06:39:143 [ info gui.account.manager ]:	Saving  0  unknown certs.
11-17 13:06:39:143 [ info gui.account.manager ]:	Saving cookies. "C:/Users/hanna/AppData/Local/ownCloud/cookies0.db"
11-17 13:06:39:360 [ info sync.credentials.manager ]:	set "ownCloud_credentials:demo.owncloud.com:6c982360-b627-4cad-9196-41d7fba841a9:http/oauthtoken"
11-17 13:06:39:361 [ info gui.account.manager ]:	Saving  0  unknown certs.
11-17 13:06:39:361 [ info gui.account.manager ]:	Saving cookies. "C:/Users/hanna/AppData/Local/ownCloud/cookies0.db"
11-17 13:06:39:576 [ info gui.account.manager ]:	Saved all account settings, status: QSettings::NoError
11-17 13:06:39:578 [ info sync.database ]:	Closing DB "C:/Users/hanna/ownCloud25/.sync_journal.db"
```

**Comment by gabi18** [comment] 2021-11-18 09:12
Tested testpilotcloud-2.9.2-rc3 on Windows 10 Version 20H2 (Build 19042.1348) VirtualBox VM:
as expected, ``close_window testpilotcloud.exe`` doesn't shutdown the client reliable (first attempt always fails, second attempt sometimes is successful)

**Comment by gabi18** [comment] 2021-11-18 11:27
Tested testpilotcloud-2.9.2-rc4.6086.x64 on Windows 10 Version 20H2 (Build 19042.1348) VirtualBox VM:
- on ``close_window testpilotcloud.exe``, a clean, reliable shutdown is done, the DB is closed correctly
``
11-18 12:12:10:700 [ info sync.utility ]:	Received WM_ENDSESSION quitting
11-18 12:12:10:746 [ debug gui.account.manager ]	[ OCC::AccountManager::saveAccount ]:	Saving account "https://gm-owncloud-1080-test-server.owncloud.works/"
11-18 12:12:10:761 [ info gui.account.manager ]:	Saving  0  unknown certs.
11-18 12:12:10:761 [ info gui.account.manager ]:	Saving cookies. "C:/Users/gabi/AppData/Local/testpilotcloud/cookies0.db"
11-18 12:12:10:761 [ debug sync.cookiejar ]	[ OCC::CookieJar::save ]:	"C:/Users/gabi/AppData/Local/testpilotcloud/cookies0.db"
11-18 12:12:10:784 [ debug gui.account.manager ]	[ OCC::AccountManager::saveAccount ]:	Saved account settings, status: QSettings::NoError
11-18 12:12:10:784 [ info sync.credentials.manager ]:	set "testpilotcloud_credentials:gm-owncloud-1080-test-server.owncloud.works:b9a0fd8b-c797-460b-86b5-03f6133aa287:http/password"
11-18 12:12:10:784 [ info gui.account.manager ]:	Saving  0  unknown certs.
11-18 12:12:10:784 [ info gui.account.manager ]:	Saving cookies. "C:/Users/gabi/AppData/Local/testpilotcloud/cookies0.db"
11-18 12:12:10:784 [ debug sync.cookiejar ]	[ OCC::CookieJar::save ]:	"C:/Users/gabi/AppData/Local/testpilotcloud/cookies0.db"
11-18 12:12:10:784 [ info gui.account.manager ]:	Saved all account settings, status: QSettings::NoError
11-18 12:12:10:784 [ debug gui.folderwatcher ]	[ OCC::WatcherThread::watchChanges ]:	Received stop event, aborting folder watcher thread
11-18 12:12:10:784 [ info sync.database ]:	Closing DB "C:/Users/gabi/testpilotcloud/.sync_journal.db"
11-18 12:12:10:817 [ debug gui.socketapi ]	[ OCC::SocketApi::~SocketApi ]:	dtor
``

**Comment by gabi18** [comment] 2021-11-22 12:01
Tested update from testpilotcloud-2.9.2-rc4.6086.x64 to testpilotcloud-2.9.2-rc4.6087.x64 on Windows 10 Version 20H2 (Build 19042.1348) VirtualBox VM

The testpilot-client is shutdown correctly when requested from msi installer:
```
12:51:41:907 [ info sync.utility ]:       Received WM_ENDSESSION quitting
11-22 12:51:41:955 [ debug gui.account.manager ]        [ OCC::AccountManager::saveAccount ]:   Saving account "https://gm-owncloud-1080-test-server.owncloud.works/"
11-22 12:51:41:970 [ info gui.account.manager ]:        Saving  0  unknown certs.
11-22 12:51:41:970 [ info gui.account.manager ]:        Saving cookies. "C:/Users/gabi/AppData/Local/testpilotcloud/cookies0.db"
11-22 12:51:41:970 [ debug sync.cookiejar ]     [ OCC::CookieJar::save ]:       "C:/Users/gabi/AppData/Local/testpilotcloud/cookies0.db"
11-22 12:51:41:970 [ debug gui.account.manager ]        [ OCC::AccountManager::saveAccount ]:   Saved account settings, status: QSettings::NoError
11-22 12:51:41:970 [ info sync.credentials.manager ]:   set "testpilotcloud_credentials:gm-owncloud-1080-test-server.owncloud.works:b9a0fd8b-c797-460b-86b5-03f6133aa287:http/password"
11-22 12:51:41:970 [ info gui.account.manager ]:        Saving  0  unknown certs.
11-22 12:51:41:970 [ info gui.account.manager ]:        Saving cookies. "C:/Users/gabi/AppData/Local/testpilotcloud/cookies0.db"
11-22 12:51:41:970 [ debug sync.cookiejar ]     [ OCC::CookieJar::save ]:       "C:/Users/gabi/AppData/Local/testpilotcloud/cookies0.db"
11-22 12:51:42:002 [ info gui.account.manager ]:        Saved all account settings, status: QSettings::NoError
11-22 12:51:42:002 [ debug gui.folderwatcher ]  [ OCC::WatcherThread::watchChanges ]:   Received stop event, aborting folder watcher thread
11-22 12:51:42:002 [ info sync.database ]:      Closing DB "C:/Users/gabi/testpilotcloud/.sync_journal.db"
11-22 12:51:42:017 [ debug gui.socketapi ]      [ OCC::SocketApi::~SocketApi ]: dtor
11-22 12:51:42:017 [ info gui.socketapi ]:      Lost connection  QLocalSocket(0x11fdc4b0d30)
```

**Comment by gabi18** [comment] 2021-11-23 09:28
Confirmed that testpilot is shutdown correctly when updating testpilotcloud-2.9.2-rc4 -> testpilotcloud-2.9.2-rc5.6114.x64.msi

**Comment by gabi18** [comment] 2021-11-23 10:57
Scenario user logout with testpilotcloud-2.9.2-rc5.6114.x64.msi:
- after user logout and login in again there isn't a logline "Closing DB ..." in the logs. 
- sometimes the db is closed 
- but also occured that it remains open:

![NO_Closing-2 9 2-rc5](https://user-images.githubusercontent.com/75983861/143012275-7efc049c-67d1-493e-85cb-7327b7955572.png)

**Comment by TheOneRing** [comment] 2021-11-23 11:56
In that scenario using --logfile won't work as expected as the console process might get killed before us.
Please use the internal log file.

**Comment by gabi18** [comment] 2021-11-23 13:03
Internal logfile when the db is closed after user logout/login also has no line "Closing DB ..."
[20211122_1047_owncloud.log.zip](https://github.com/owncloud/client/files/7588107/20211122_1047_owncloud.log.zip)
 
but the db is closed:

**Comment by gabi18** [comment] 2021-11-23 13:28
Testscenario "User logout" testpilotcloud-2.9.2-rc5.6114.x64.msi on Windows 10 Version 20H2 (Build 19042.1348) VirtualBox VM:
- works almost reliable, https://github.com/owncloud/client/issues/8979#issuecomment-976400745 is not reproducible
- logfile doesn't contain "Closing DB..."
[20211123_1414_owncloud.log.zip](https://github.com/owncloud/client/files/7588268/20211123_1414_owncloud.log.zip)

**Comment by gabi18** [comment] 2021-11-23 14:09
Finally got a logfile with "Closing DB..." (--logflush was missing)

```
11-23 14:50:47:743 [ debug gui.folderwatcher ]  [ OCC::WatcherThread::watchChanges ]:   Received stop event, aborting folder watcher thread
11-23 14:50:47:743 [ info sync.database ]:      Closing DB "C:/Users/gabi/testpilotcloud/.sync_journal.db"
11-23 14:50:47:758 [ debug gui.socketapi ]      [ OCC::SocketApi::~SocketApi ]: dtor
11-23 14:50:47:758 [ info gui.socketapi ]:      Lost connection  QLocalSocket(0x1cdca7022f0)
11-23 14:50:47:773 [ debug sync.utility ]       [ `anonymous-namespace'::startShutdownWatcher::::operator() ]:  app closed
11-23 14:50:47:773 [ info sync.utility ]:       WM_ENDSESSION successfully shut down 28472197
```
[20211123_1448_owncloud.log.zip](https://github.com/owncloud/client/files/7588574/20211123_1448_owncloud.log.zip)

**Comment by TheOneRing** [comment] 2021-11-25 09:44
@gabi18 Can we close this one?

**Comment by gabi18** [comment] 2021-11-25 13:12
Yes, I think so.
I have just retested update 2.9.2 rc5 to v2.9.2, the msi installer shutdown works reliable.
Also on system shutdown the db is closed successfully.
```
11-25 13:46:45:370 [ info sync.database ]:      Closing DB "C:/Users/gabi/testpilotcloud/.sync_journal.db"
11-25 13:46:45:430 [ debug gui.socketapi ]      [ OCC::SocketApi::~SocketApi ]: dtor
11-25 13:46:45:430 [ info gui.socketapi ]:      Lost connection  QLocalSocket(0x21f53cf49a0)
11-25 13:46:45:430 [ debug sync.utility ]       [ `anonymous-namespace'::startShutdownWatcher::::operator() ]:  app closed
11-25 13:46:45:430 [ info sync.utility ]:       WM_ENDSESSION successfully shut down 3292762
```

**Closed** 2021-11-25 13:13 UTC
Labels: Windows
