### ISSUE TITLE
[2.10.0] Can not connect to oCIS

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#9324] opened 2022-01-03 14:43 UTC
With the client version 2.10.0 rc2 and also 2.11.0-git it is not possible to connect a new account to oCIS. The same setup works with client version 2.9.2.

The client opens the browser with this URL:
```
http://127.0.0.1:35619/?code=QuOxd7Kn10pIf9oEPsY5S0rXXXn-hgrC&scope=profile%20openid%20offline_access%20email&session_state=4bXXXXb7373c63a1e95a07bc7949e0afd5d80d0ea637c761dde60546e5b5baf3.yvhihIZJcp02lGGL0IX1PB-oVi3VsHUO9ltxpVYUkp8%3D&state=QBxRZrrE8SSSUPbie5VImhCR-Y4agUbCY8_n-NFRJcQ%3D
```
and after allowing access the browser reports
![grafik](https://user-images.githubusercontent.com/1070214/147943731-211044e0-5099-4668-a94f-ed4dc234cfef.png)

The OIDC redirect url seems empty.

**Comment by dragotin** [comment] 2022-01-03 14:44
Maybe patches around https://github.com/owncloud/client/issues/9196 had some side effects?

**Comment by michaelstingl** [comment] 2022-01-03 14:52
Can be reproduced with those instances:

- ocis.ocis-traefik.latest.owncloud.works
- ocis.ocis-traefik.released.owncloud.works
- ocis.ocis-keycloak.latest.owncloud.works
- ocis.ocis-keycloak.released.owncloud.works

user: einstein
pw: relativity

Can't be reproduced with the oC10 OAuth 2.0 app:

- demo.owncloud.com

**Comment by fmoc** [comment] 2022-01-04 01:02
```
https://ocis.ocis-traefik.latest.owncloud.works/signin/v1/identifier
?client_id=<censored>
&code_challenge=<censored>
&code_challenge_method=S256
&flow=oidc
&prompt=select_account+consent
&redirect_uri=http%3A%2F%2F127.0.0.1%3A36629
&response_type=code
&scope=openid+offline_access+email+profile
&state=<censored>
```

This is what the URL opened in the browser looks like on both the `master` and `2.10` branch (similar results for a local oCIS instance and the other ones listed by @michaelstingl). I'm not entirely sure at this point why there are so many more arguments in my test than in your URL, I do not have too much experience with the OIDC implementation in oC (yet).

I see two possible causes: either the redirect after a successful authorization on the server is not working (i.e., the redirect URL generated by the server from the information we send to it initially is incorrect), or some state in the client goes missing in the meantime. I'll `git bisect` the client, I suppose the issue is on our side.

**Comment by fmoc** [comment] 2022-01-04 01:22
@dragotin's guessed right that https://github.com/owncloud/client/commit/4ba37025f4b5ac4a2a6cde6aac7d4a5896cfbac1 (mentioned in https://github.com/owncloud/client/issues/9196) broke the behavior, the commit before works as expected. Will have a look tomorrow.

**Comment by michaelstingl** [comment] 2022-01-04 08:09
> 'm not entirely sure at this point why there are so many more arguments in my test than in your URL

The URL @dragotin posted, is a different one. It's the one where the browser redirects to the webserver in the client running/listening on `127.0.0.1:35619`.

![CleanShot 2022-01-04 at 09 07 33@2x](https://user-images.githubusercontent.com/214010/148028326-3d5e8f1a-f4cb-46f3-8b7e-b40ab26b605d.png)

(Source: https://github.com/owncloud/oauth2/wiki/OAuth-code-Flow-Sequence-Diagram)

**Comment by fmoc** [comment] 2022-01-04 08:18
Noticed that in the meantime. I found another issue in the workflow, where the relevant error message gets lost in the process:

```
"\tError: Missing field access_token\n\tError: Missing field refresh_token\n\tError: Missing field token_type\n"
```

Due to the lack of comments within the code, I am not sure whether it is by design that this error message is superseded by the less helpful `redirect_uri mismatch`, or whether it's considered a feature not to expose details of the validation (but hiding does not really make sense).

**Comment by TheOneRing** [comment] 2022-01-04 08:21
> Noticed that in the meantime. I found another issue in the workflow, where the relevant error message gets lost in the process:
> 
> ```
> "\tError: Missing field access_token\n\tError: Missing field refresh_token\n\tError: Missing field token_type\n"
> ```
> 
> Due to the lack of comments within the code, I am not sure whether it is by design that this error message is superseded by the less helpful `redirect_uri mismatch`, or whether it's considered a feature not to expose details of the validation (but hiding does not really make sense).

Lets have a short call.

**Comment by michaelstingl** [comment] 2022-01-04 08:24
> error message is superseded by the less helpful `redirect_uri mismatch`

this is the error message from the IdP:

```
01-03 15:37:36:846 [ info sync.httplogger ]:	"7c9d6d7d-706d-4b90-b652-2f9c0de3016e: 
Request: POST https://ocis.ocis-traefik.latest.owncloud.works/konnect/v1/token 
Header: { Authorization: Basic [redacted], Content-Type: application/x-www-form-urlencoded; charset=UTF-8, User-Agent: Mozilla/5.0 (Macintosh) mirall/2.10.0rc2 (build 6347) (testpilotcloud, osx-21.2.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: 7c9d6d7d-706d-4b90-b652-2f9c0de3016e, Original-Request-ID: 7c9d6d7d-706d-4b90-b652-2f9c0de3016e, Content-Length: 444, } 
Data: [client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&client_secret=UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh&scope=openid%20offline_access%20email%20profile&grant_type=authorization_code&code=MFKOGdli1O63BIv2GfOYwI-OoW9Sqysp&redirect_uri=http://127.0.0.1:0&code_verifier=KjTvJoEqf31I30mUb4rxPmOjlWXZ7O5XIfgj73LrcktLKF-d7zq5HVqp9-aZlo1B6aUjnEAZFBkGVJoEVq80_ohSRFSBTsMNU9s-PGy-_xp6lBcqA47BxVvOvBTe1cNe]"


01-03 15:37:36:933 [ info sync.httplogger ]:	"7c9d6d7d-706d-4b90-b652-2f9c0de3016e: 
Response: POST 400 https://ocis.ocis-traefik.latest.owncloud.works/konnect/v1/token 
Header: { Cache-Control: no-store, Content-Length: 79, Content-Security-Policy: frame-ancestors 'none', Content-Type: application/json; encoding=utf-8, Date: Mon, 03 Jan 2022 14:37:36 GMT, Expires: Thu, 01 Jan 1970 00:00:00 GMT, Last-Modified: Mon, 03 Jan 2022 14:37:36 GMT, Pragma: no-cache, Vary: Origin, X-Content-Type-Options: nosniff, X-Frame-Options: DENY, X-Idp-Version: 4537d0ed, } 
Data: [{\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"redirect_uri mismatch\"\n}\n]"
```

**Comment by fmoc** [comment] 2022-01-04 10:28
Closed by #9328.

**Closed by fmoc** 2022-01-04 10:28 UTC
Labels: p2-high

**Comment by gabi18** [comment] 2022-01-05 10:00
Confirmed fixed with ownCloud-2.10.0-rc3

**Comment by fmoc** [comment] 2022-01-11 08:27
@gabi18 please open a new issue.

**Comment by TheOneRing** [comment] 2022-01-11 09:12
The issue is already known https://github.com/owncloud/client/issues/9330

**Comment by TheOneRing** [comment] 2022-01-11 09:15
Ok I'm wrong different error I guess

**Comment by gabi18** [comment] 2022-01-11 10:16
Yes, I think it's different than #9330, there is still a problem with authentication. Is a new issue required or reopen this?
