### ISSUE TITLE
[Linux/Zorin OS] light tray icon in light theme

### ISSUE THREAD

**Issue by dominikwelke** [owncloud/client#10738] opened 2023-04-20 18:47 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

first of all thanks for the great work!

Bug description:
In Zorin OS 16 with light appearance theme the bright tray icon of the OC client is barely visible.

this seems to be a regular topic?
e.g. https://github.com/owncloud/client/issues/7780

### Expected behavior

A dark(er) tray icon should be displayed.
either automatically, or a tickbox choice for dark icons could be offered

### Steps to reproduce the issue

1) choose light desktop theme in Zorin Appearance
2) check out OC tray icon

### Screenshots

![image](https://user-images.githubusercontent.com/33089761/233457519-b2b52d44-abdb-4937-90c2-4924fbc912eb.png)

### Client version number

Client version: owncloud 3.2.1.10355
OS: Zorin OS 16.2 (based on Ubuntu 20.04 LTS)

### Desktop environment (Linux only)

Zorin Os 16.2 with Gnome shell 3.38.4

### Client package version and origin (Linux only)

apt install as described on the client website

**Comment by TheOneRing** [comment] 2023-04-21 07:44
Duplicate of https://github.com/owncloud/client/issues/8618
We don't have theme detection for gtk (yet)

**Closed** 2023-04-21 07:44 UTC
Labels: bug
