### ISSUE TITLE
Warning when the servers datafolder is empty should change

### ISSUE THREAD

**Issue by enoch85** [owncloud/client#3271] opened 2015-05-22 19:44 UTC
You *could* say that the data on the clients local machines is their own backup. But the problem is that when the server data is wiped, and the clients want to sync, it asks the user with an option to delete the files locally. This will then start a new sync, and wipe the local files. So, when the rootuser put all the files back on the server, they are already synced with wiped data = dataloss on clients end.

#### Negative because

- Takes extra unnecessary bandwidth.
- There is a big risk for data loss when the client starts to upload things to the new sync.

The clients data should always stay on the clients computers and it should be up to the admin to decide whether that data would be wiped or not.

Could this be implemented in a good way?

CC @danimo @jancborchardt @dragotin

**Comment by guruz** [comment] 2015-09-04 07:25
Semi-related: https://github.com/owncloud/client/issues/3742
Although in the case here the data folder's ```FileId``` would not change?

CC @icewind1991 @PVince81

**Comment by ogoffart** [comment] 2015-10-28 13:07
We already Have a check when the server is empty. with a warning and question to the user if he really wants to delete all the files.
Otherwise this is a duplicate of #2325

**Closed by ogoffart** 2015-10-28 13:07 UTC
Labels: Discussion, Enhancement, enhancement - needs design
