### ISSUE TITLE
icons inconsistency

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6714] opened 2018-08-15 11:18 UTC
Started with a missing sqlite database, but sync folder and server mostly in sync.
The client takes a while to rebuild its sqlite database. During this time the icon in the settings dialog is blue and indicates syncing, while the icon in the task bar is green and indicates idle.

I am not aware that the two icons should carry different meanings (at least, when there is exactly one sync connection, they should be in sync)
![grafik](https://user-images.githubusercontent.com/1108546/44145902-92316a00-a08d-11e8-8e53-a62605a4738e.png)

This was not seen in 2.4.1

**Comment by michaelstingl** [comment] 2018-08-15 12:57
@jnweiger In some cases "works as designed". Also tray bar icon is green while in-app icon is blue during discovery. (I think explanation was, no files are transferred during this time)

I'd like to change this with 2.6.

**Comment by ogoffart** [comment] 2018-08-17 10:12
> (I think explanation was, no files are transferred during this time)

Right,  since the discovery was done at frequent interval, regardless of modifications on the FS, users were wondering why it became blue for no apparent reason.

**Closed** 2018-12-01 18:30 UTC
