### ISSUE TITLE
[2.0.0] Show at least 1 decimal point when displaying sizes

### ISSUE THREAD

**Issue by tessus** [owncloud/client#3689] opened 2015-08-28 00:06 UTC
The change to use SI units is utterly confusing.

On the server I set the quota for my user to 10GB and the client shows 11GB. Huh? What? Even in SI units 10,737,418,240 bytes are not 11 GB. At least one decimal should be shown.

Either we use SI units on the server and the client, or we have a choice what to use on the client. But using one unit on the server and another one on the client is confusing.

**Comment by danimo** [comment] 2015-08-28 00:36
@jancborchardt

**Comment by BenS89** [comment] 2015-08-28 08:55
I can confirm that. Concerning the used space, Server says 2.7 GB in use. Client says 2,9 GB in use.

**Comment by danimo** [comment] 2015-08-28 09:07
I understand that the plan is the change the server to 1000-base, too.

**Comment by jancborchardt** [comment] 2015-08-28 09:30
cc @DeepDiver1975 @schiesbn then. We should change it for 8.2 because the client already switched.

**Comment by ogoffart** [comment] 2015-08-28 10:14
See https://github.com/owncloud/core/issues/13386

In the discussion there we agreed to use the SI unit, so i'm closing this issue and the server issue can be followed.

**Comment by ogoffart** [comment] 2015-08-28 10:16
As for the number of significatn digit, we use 2 significant digit for the decimal.
But it is true that i think there should probably be at least one decimal point.

**Comment by jancborchardt** [comment] 2015-08-28 10:21
Only one decimal point please (for GB and up), and no decimal points for MB and KB.

**Comment by ogoffart** [comment] 2015-08-28 13:14
It's the same function which is used anywhere we display a size. So the same is used for the quota and the size in the progress or in the activity tab or in the selective sync dialog.

@jancborchardt  So you are saying that if the size is 1.49 MB, we should show "1 MB"?   But if it is 765.43 GB,  then we should show "765.4 GB" ?

Currently we show 2 significant number, or more if it is an integer.  
Which mean we would have "9.5 MB"  or "9.5 GB"   but if we have, say, 10.7 MB or 10.7 GB,  we show  "10 MB" or "10 GB"  (10 is two significant number)
123.4 GB will be shown as "123 GB"  (that's 3 significant number but it is integer).

**Comment by phil-davis** [comment] 2015-08-28 13:31
Maybe a rule that works out nicely would be:
a) Show 1 decimal place by default
b) When the integer part is already 3 digits or more (>=100) then show no decimal places, rounding to the nearest integer.
That results in stuff like:
4.5 KB
23.4 KB
99.9 KB
100 KB
9.9 MB
10.0 MB
99.9 MB
256 MB
1.1 GB
15.6 GB
123 GB

**Comment by jancborchardt** [comment] 2015-08-28 15:20
@ogoffart sorry, I meant to say both MB, GB and everything up should have 1 decimal place. It doesn’t make sense though for small stuff like kB and B. Ok?

**Comment by tessus** [comment] 2015-08-28 16:31
@DeepDiver1975 @schiesbn @danimo any chance that people can choose between GiB and GB?

Over 20 years ago I learned that a MB is 1024 kb and so forth. Then the HD vendors came along and found it better to say 200 GB = 200,000 MB to make more money and the mess was born.

These days nobody really knows anymore what 1 GB stands for. According to specifications GB is 1000-based and GiB is 1024-based. But many people still use GB for GiB. So although a label says GB, it's actually 1024-based, and unless it is stated somewhere what the base actually is, you can't be sure.

Please, give people a choice.

**Comment by jancborchardt** [comment] 2015-08-28 18:12
Me right now: :smile::gun: 

No but seriously … we should not introduce a setting for something like this but rather do it how we deem correctly. As @ogoffart said and how it’s done in the client is how we should also adjust the server.

**Comment by tessus** [comment] 2015-08-28 18:36
I still don't get it.
Why is 1000-based better than 1024-based? Who decided that? Why do you deem 1000-based the correct way? This is nothing more than a personal preference. Until now owncloud used 1024-based. All of a sudden somebody thinks/believes that 1000-based is better. Why?

pages (SSD) and sectors (HD) are still not using a 10-based system. Neither do any of the Unix filesystems. So what's up with this change?

**Comment by jancborchardt** [comment] 2015-08-28 18:48
@ogoffart & @tessus you discuss this out please.

But the important thing here is that client and server need to work in unison here. Going rogue on one side is bad for everyone and especially confusing for the people using our software.

**Comment by tessus** [comment] 2015-08-28 18:56
@jancborchardt I agree. but the server uses 1024 based, which means the client is out of sync. pun intended.

but, also for the server it should be a choice. in IT, the binary unit sizes make more sense. just because a few end user file manager GUIs show different values doesn't make it right. in most of the file managers you can choose the unit sizes anyway.

**Comment by jancborchardt** [comment] 2015-08-28 19:06
Yeah, that’s what I was referring to. The desktop client changed without coordination with the server, I agree that that’s not good.

> most of the file managers

I doubt that. Dropbox, OS X Finder, Google Drive, which ones?

**Comment by tessus** [comment] 2015-08-28 19:23
Dropbox and Google Drive are not file managers but web interfaces. Google Drive uses the 1024 based values, but the wrong units.
OSX Finder - yes, you are right. That's 10-based, and you cannot change it, but we all know how Apple always thinks to make the right decision and that Apple doesn't care what their customers think.
Path Finder on OSX - you can change the unit sizes.
On Linux I know several file managers were you can change the unit sizes.
Windows - I believe - uses 1024 based.

**Comment by ogoffart** [comment] 2015-08-31 16:35
After discussion with @jancborchardt  we decided that the current behaviour of the client is good enough.

**Closed by ogoffart** 2015-08-31 16:35 UTC
Labels: Design & UX

**Comment by dragotin** [comment] 2015-09-10 10:12
Changed the display of the units again in commit 995b42d0fc31bee5882b2f6a704400f4f221c192 to return to consistency with the server.

**Comment by jancborchardt** [comment] 2015-09-10 10:23
@ogoffart @dragotin thanks!
