### ISSUE TITLE
[QA] Scenarios failing with the same error `KeyError: 'Brian'`

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9866] opened 2022-07-06 08:05 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The following four scenarios from `tst_sharing` suite 
```
Scenario: User (non-author) can not share to a group to which the file/folder is already shared
Scenario: sharee edits content of files shared by sharer
Scenario: reshare a file/folder
Scenario: try to reshare a file/folder shared without share permission
```
are failing locally with the following error while running the test from the terminal but it passes while running using the squish ide.
 ```
2022-07-06T11:37:03	ERROR     	/home/sushmita/www/client/test/gui/shared/steps/steps.py:112: Script Error	KeyError: 'Brian'
```

### Steps to reproduce the issue

NA

### Screenshots

![Screenshot from 2022-07-06 13-49-40](https://user-images.githubusercontent.com/66173400/177501367-951817f8-8101-4ed1-afa3-95ab0d033a5c.png)

**Comment by saw-jan** [comment] 2022-07-25 07:04
I was not able to reproduce this one.

**Comment by amrita-shrestha** [comment] 2022-07-27 09:34
This could be the reason: `missing Brain data in the dictionary that contain user information from middleware`.

Closing this issue because can't reproduce locally.

**Comment by saw-jan** [comment] 2022-09-05 03:45
This error happens to be a legit one. We can reproduce this by putting a scenario that creates only one user at the very first. Because if the first scenario only creates user Alice then in the second scenario where Alice and Brian are created, KeyError will be thrown.

**Closed** 2022-09-05 08:57 UTC
Labels: QA:team
