### ISSUE TITLE
Updating to version 2.0.2.5569 cleared config file

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/client#4015] opened 2015-10-28 08:10 UTC
The automatic update just installed `ownCloud-2.0.2.5569-setup.exe`. After the installation all configured folders for syncing where gone (section [Accounts], rest of `owncloud.cfg` was still fine).

Possible cause:
I previously installed a 2.0.2 nightly version + I deleted the now redundant folder containing the old configuration files within the config folder (there is just `owncloud.cfg`, `owncloud.lst`, and `cookies.db` in my config folder).

**Comment by RealRancor** [comment] 2015-10-28 08:53
@LukeOwncloud 

Seems that was "unavoidable" for some users according to @danimo at https://github.com/owncloud/client/issues/4012#issuecomment-151545491

**Comment by tfboy** [comment] 2015-10-28 09:00
In addition to losing the settings (which I noticed), my client is now wanting to download everything off the server all over again, and that's a hell of a lot of data!

**Comment by tflidd** [comment] 2015-10-28 09:34
I put a sticky-thread on the forum: https://forum.owncloud.org/viewtopic.php?f=14&t=31191
I hope that I got everything right.

@danimo @guruz : Shouldn't this be mentioned in the changelogs (some kind of warning)?
https://owncloud.org/changelog/desktop/

**Comment by phil-davis** [comment] 2015-10-28 10:25
On forum post;
"The problem is due to a bug in client versions 8.0.0/8.0.1"
The versions should be 2.0/2.0.1

**Comment by tflidd** [comment] 2015-10-28 10:29
It was too early in the morning ;-)

**Comment by ogoffart** [comment] 2015-10-29 13:39
@danimo: is it still possible to change the release notes?  Or is there something we can do?

**Comment by RealRancor** [comment] 2015-10-31 09:17
@ogoffart Disabling the autoupdate from 2.0.0/2.0.1 to 2.0.2 and a blogpost / mailinglist post to warn users could make sense. But its probably "too late" for most people.

**Comment by frankuit** [comment] 2015-11-02 14:10
I've had 4 users now with the same problem.
The client (stable version) wants to update, user lets it update itself, and the problem above happens.
users only see : (screenshot below)
![owncloud_no_sync_folders](https://cloud.githubusercontent.com/assets/3750583/10883629/914996e4-8173-11e5-8554-1ff720b8fe3a.png)

i don't quite understand the thing said earlier in this thread:
"Seems that was "unavoidable" for some users according to @danimo at #4012 (comment)"

does this mean that someone knew this would happen ? that would not be very professional imo.

Just my 2 cents,
Frank

**Comment by phil-davis** [comment] 2015-11-02 15:29
Nobody knew it would happen when 2.0 and 2.0.1 were released. But since then the problem has been reported and fixed in 2.0.2. The trouble is for people who already have 2.0 or 2.0.1 installed. The problem code is in the auto-update process of the already-installed 2.0 or 2.0.1. Nobody has thought of a trick for a provided "fixed" upgrade that can avoid or reverse the damage that is done by the already-installed version's built-in upgrade code.
The workaround is to do a manual install of 2.0.2 - avoiding running the problem code in the earlier versions. But of course people have to somehow know to do that.
If anyone has a good idea how something somewhere could be patched up to avoid this, I'm sure it will be listened to!

**Comment by RealRancor** [comment] 2015-11-04 08:58
@phil-davis 
> But of course people have to somehow know to do that.

Yes, i think that was the main problem. Up to now there was only a forums thread of a contributor to make the users aware of this issue: https://forum.owncloud.org/viewtopic.php?f=14&t=31191

**Comment by zephyrus00jp** [comment] 2015-11-06 14:47
Hi,

I got bitten by this issue, and it seems that the workaround mentioned did not seem to work:

The details of my experience of having config blown away on THREE different PC (all windows)
is in https://forum.owncloud.org/viewtopic.php?f=14&t=31191&p=100722#p100688

Basically, I lost config files three times: the first time I did not know about the bug.
The second time I lost the config file although I had read the warnings and workaround posted.
The third time I was really careful to follow the workaround procedure, but still I lost the config file!

Please see my post and the response I got:

>    tflidd wrote:
>   Closing the client means, to close the client-sync-programme (right click on the oc-symbol in task >manager -> close owncloud). If the workaround doesn't work, please report this to the developers.

> I am fairly certain that I exit the client-sync-programme in the list of running tasks (or whatever is 
> called)
> using right click and "exit" after the first two failure cases.
I will report it just in case.

So here it goes. I wonder what can explain my third case when I *THINK* I followed the
workaround procedure and still lost config.

TIA

**Comment by ogoffart** [comment] 2018-08-07 06:16
Closing old issue. 2.0.2 is really old now.

**Closed by ogoffart** 2018-08-07 06:16 UTC
Labels: Known Issue / Workaround
