### ISSUE TITLE
[Mac] Folder with (white)space at end: Files get deleted soon after creation

### ISSUE THREAD

**Issue by dhjdhj** [owncloud/client#2685] opened 2015-01-09 12:26 UTC
I had created a new folder under my OwnCloud folder on my Mac and dropped some files into it. After a minute or so, they just disappeared.

I've done a few experiments and discovered that I can  reproduce 100% this problem by

A) Make a copy of a folder that already contains files
B) Rename the folder so as to add a space at the end (that's the critical bit)
C) Wait a minute or two
D) Files get deleted

Using latest available versions.
OwnCloud server is running on a Fedora Linux server.
Client is running on Yosemite.

**Comment by moscicki** [comment] 2015-01-09 12:58
I guess this is due to special handling of cases of filenames forbidden on Windows (which includes the trailing space in the file name). The client cannot properly distinguish between the two directories and gets confused. Obviously there is something very wrong in this implementation that needs fixing. 

However, this also shows a more general problem that many others already pointed at: it would be best to keep the Windows problems limited to the Windows clients only (or any OS-specific problems for that matter too).  I think it is really a much better design to allow two linux clients sync files without restrictions, rather than imposing a restriction coming from an OS that this particular user may never use.

And I would also think that it is a much better strategy to have a simpler algorithm that avoids any data loss on all platforms even at the expense of some filename clashes not being synced to platforms which impose limitations.

**Comment by dhjdhj** [comment] 2015-01-09 13:03
I don't know about Windows but as I pointed out, my client is running Yoseimite (Mac OS 10.10) and my server is Linux

But yes, no matter the limitations on particular systems, files need to not disappear! It may be that the clients need to do some name validation and/or simply replace bad characters with underscores or something.

**Comment by tflidd** [comment] 2015-01-09 13:40
@dhjdhj : Can you fill out the template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md. These information are probably important (more about your system, do you use external storage, which apps are enabled, ...).

The original topic on the forum was: https://forum.owncloud.org/viewtopic.php?f=14&t=19138

I tried to reproduce it in OS X Mavericks. But it works, only thing is that the folder doesn't sync on Windows 7 because it contains invalid characters (but it is still on the server and visible on the web-interface).

**Comment by guruz** [comment] 2015-01-09 13:41
> B) Rename the folder so as to add a space at the end (that's the critical bit)

@danimo I remember a patch by you that disallows folders with space(s) at end?

**Comment by dhjdhj** [comment] 2015-01-09 14:14
### Steps to reproduce

On a Mac, 
1) Make a copy of a folder that already contains files
2) Rename the folder so as to add a space at the end (that's the critical bit)
3) Wait a minute or two
4) Files get deleted


### Expected behaviour
Tell us what should happen: Files should not disappear

### Actual behaviour
Tell us what happens instead: Files disappear!

### Server configuration
**Operating system**: Linux - Fedora 17

**Web server: Apache version 2.2.23 

**Database:** MySQL 5.5.32

**PHP version:**  5.4.17

**ownCloud version:** ownCloud 7.0.4 (stable) 

**Updated from an older ownCloud or fresh install:** updated from older

**List of activated apps:** Just the defaults already activated

**The content of config/config.php:**

```

<?php
$CONFIG = array (
  'instanceid' => '5256e29242ea0',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/home/OwnCloud/Data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'OwnCloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'numeric IP address here',
    1 => 'domainname changed',
  ),
  'secret' => 'xxx',
  'mail_from_address' => 'david',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'deskew.com',
  'loglevel' => '0',
);
```

**Are you using external storage:** no

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox --- but not using browser for this issue

**Operating system:**  OS X   (10.10)

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
There's 1/2 Mb of data here --- how much do you need?
```

#### Browser log
```
N/A
```

**Comment by MTRichards** [comment] 2015-01-19 14:33
No matter what the cause, losing data is a significant problem. We need to at least preserve the data and recognize the case, and then fix it.

**Comment by rullzer** [comment] 2015-01-20 13:50
I just tested this on linux (with the server also running linux) and there the problem does not happen. So it seems to be related to OS X

**Comment by MTRichards** [comment] 2015-01-20 13:55
It could be related to being cross platform
@dragotin @guruz @ogoffart @danimo for reference.

**Comment by ckamm** [comment] 2015-01-28 08:46
@guruz I think danimo's change was 2dfbc2058fe172eb8abc96b71da33031fdc5adc1 but applied to Windows only. I'll mark this as [Mac] since it's been explicitly fixed on windows and @rullzer confirmed it doesn't happen on linux.

**Comment by guruz** [comment] 2015-01-29 20:39
I tried reproducing this with a 1.8.x client and 7.0.4.2 server on OS X 10.9.5.
It's fine, no problem
(Instead of waiting for the next sync to happen I have to restart the client as 1.8 clients don't sync that often anymore).

@dhjdhj Can you try reproducing with the latest nightly release from http://download.owncloud.com/desktop/daily/
If you can't reproduce it, I'm assuming it is fixed in 1.8.0.

**Comment by dhjdhj** [comment] 2015-01-29 20:42
Unfortunately I'm out of town for the next month or so so won't be able to look at this until March


D

----------------
David H. Jameson, Ph.D
Co-founder
Deskew Technologies, LLC

www.deskew.com

**Comment by guruz** [comment] 2015-01-29 20:43
@dhjdhj Do you remember if the folder was inside a shared folder? Do you remember if you used 1.7.0 or 1.7.1?

@lmaestro Could you also try to reproduce but using 10.10 ? Can you also compare 1.7.1 with 1.8.x ?

**Comment by dhjdhj** [comment] 2015-01-29 21:04
It was inside a shared folder, I believe.

**Comment by ckamm** [comment] 2015-01-30 07:14
@guruz "Instead of waiting for the next sync to happen I have to restart the client as 1.8 clients don't sync that often anymore" -> Bug with the file watcher??

**Comment by guruz** [comment] 2015-01-30 08:38
@dhjdhj Was it inside a shared folder in the old-style ```/Shared/......``` hierarchy?

@ckamm Not waiting for a sync triggered by a watch, but waiting for the next normal (interval) sync.

**Comment by lmaestro** [comment] 2015-01-30 08:41
I can't reproduce it on Yosemite (10.10.1) with version 1.7.1 neither 1.8.0.

**Comment by ogoffart** [comment] 2015-01-30 09:51
Is it possible that this folder was shared with someone still having the 1.6 client on windows? 
Because the 1.6 client had that bug: https://github.com/owncloud/client/issues/1439

**Comment by guruz** [comment] 2015-01-30 09:59
@dhjdhj Sorry, I'm closing this for now. If you remember more info (like the question above about the ```Shared``` or @ogoffart 's question) or get more Information in March then please comment & reopen.

**Closed by guruz** 2015-01-30 09:59 UTC
Labels: bug, gold-ticket, Needs info

**Comment by nunomazer** [comment] 2015-04-07 11:51
Just to inform, I'm having this problem right now, Server: Debian Wheezy with OC 8.0.1 - clientes Windows 7 with OC Client last version.

Searching in logs nothing seems to happens  ... so ... I'm thinking in give up the OC for now

**Comment by rbahassine** [comment] 2015-04-10 14:09
Hi, 
I have the same problem too. I have :
one Server : Owncloud 7.0.4 running on Ubuntu 12.04.4 LTS
approx 31 Clients : Owncloud Desktop 1.7.1 on Windows 7 (except me I am on 1.8.0)

**Web Server** : Apache/2.2.22
**MySQL version** : 5.5.35
**PHP Version** : PHP 5.3.10
**Fresh Install **
**List of applications** : Deleted Files, Documents, External sites, Full Text Search, LDAP User and group backend, Mail template editor, PDF viewer, Share Files, Text Editor, Versions

**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'instanceid' => 'ocd23b2055f1',
  'passwordsalt' => 'f6d4dc09aa6c33033a8fd0789d7105',
  'trusted_domains' => 
  array (
    0 => 'owncloud-dev.*******.fr',
  ),
  'datadirectory' => '/files/owncloud/data',
  'overwrite.cli.url' => 'http://owncloud-dev.******.fr',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud7',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud7',
  'dbpassword' => '*******',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud-dev',
  'mail_domain' => '*****.fr',
  'mail_smtphost' => '******',
  'mail_smtpport' => '25',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'theme' => 'owncloud7',
  'ldapIgnoreNamingRules' => false,
  'maintenance' => false,
  'secret' => 'ea9c25094a9ff0841f494f427662e87083794d510605a0f27285cb496f54eb081523f9c3a9f767798feacf04cfb83de4',
  'loglevel' => '4',
);
```
**Are you using external storage:** no
**Are you using encryption:** no

**Comment by dragotin** [comment] 2015-04-10 14:10
@rbahassine are you able to reproduce this and provide us with a client logfile?

**Comment by rbahassine** [comment] 2015-04-10 14:11
Yes I am but the client logfile is more than 123Mb

**Comment by DavidJameson** [comment] 2015-04-10 14:14
I forgot to mention this, but recently I was doing some cleanup on a Windows VM that has ownCloud installed and while the ownCloud folder contained the folders with spaces, I couldn't remove them. Finally I figured out that I could remove them by referring to their 8x3 short names. Not sure if that's a clue to anything.

**Comment by rbahassine** [comment] 2015-04-10 14:46
Extract from the log file : 

**Note that "GUE" is the username of the person that shares files with other users.**

```log
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/BOC_Reunion_20140924.pptx.d1428508092 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:19+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/BOC_Solution Magellan_Architecture_20140925 - V2.pptx.d1428508093 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:22+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/LECTURE RC FINANCE.xls.d1428508094 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:25+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/SUIVI DES ETATS FINANCE.xlsx.d1428508096 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:28+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/ODJ_Conception.xlsx.d1428508097 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:31+00:00"}
{"app":"PHP","message":"unlink(\/files\/owncloud\/data\/GUE\/files_trashbin\/files\/Planning_Projet.mpp.d1428508097): No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#167","level":3,"time":"2015-04-09T13:26:32+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/Puce.jpg.d1428508098 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:35+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/BOC-RF_ACHAT_2015020405-V2.d1428508427 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:38+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/Key users Achat.d1428508428 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:41+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/RC.d1428508429 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:43+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/Annexes.d1428508431 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:45+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/files\/owncloud\/data\/GUE\/files_trashbin\/files\/Familiarisation.d1428508434 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#117","level":3,"time":"2015-04-09T13:26:47+00:00"}
{"app":"PHP","message":"Call to a member function getSize() on a non-object at \/var\/www\/owncloud\/lib\/private\/helper.php#981","level":3,"time":"2015-04-09T13:29:43+00:00"}
{"app":"PHP","message":"Call to a member function getSize() on a non-object at \/var\/www\/owncloud\/lib\/private\/helper.php#981","level":3,"time":"2015-04-09T13:29:50+00:00"}
