### ISSUE TITLE
Client stop syncing, wrong fieles counting

### ISSUE THREAD

**Issue by JohannesKleine** [owncloud/client#4897] opened 2016-05-24 13:34 UTC
### Expected behaviour
Schould sync without interruption.

### Actual behaviour
351 files stored on server, with no changes on serverside. After syncing few files the client stop with "operation abgebrochen" and "verbindung beendet". And then the client starts again. The fist sync shows 371 files and 371MB to sync, the second sync shows 735 and 742MB, the third sync 1095 files and 1,1GB to sync. Why shows the client first the correct sum of files and after it shows first sum multiplied with sync tryes.

Same OwnCloud instance snyncing fine with Windows client.

### Steps to reproduce
1. using Debian Jessie with all updates and your stable client
2. few hundred files stored on server, no changes to this files
3. lounch the client and add syncronisation

### Server configuration
Operating system: Cent OS 6 (shared hoster)

Web server: 
Apache
Database:
MySql
PHP version:
7.0.6 
ownCloud version:
8.2.5
Storage backend:

### Client configuration
Client version:
Version 2.2.0%nil (build 1605)
GIT-Revision 49a678 auf May 14 2016, 13:16:11 verwendet Qt 5.3.2, OpenSSL 1.0.1k 8 Jan 2015
Operating system:
Debian Jessie
OS language:
de-de
Installation path of client:
standard
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

https://gist.github.com/JohannesKleine/053b608c76fd48ff2854729635d9b6b4

2. Web server error log:
no errors at the same time interval

3. ownCloud log (data/owncloud.log):

[2016-05-24_server-logfile.txt](https://github.com/owncloud/client/files/279568/2016-05-24_server-logfile.txt)

**Comment by danimo** [comment] 2016-05-27 11:39
Duplicate of #4832

**Closed by danimo** 2016-05-27 11:39 UTC
