### ISSUE TITLE
[QA] Linux client breaks move into delete+create

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8458] opened 2021-02-26 08:47 UTC
Using an idea and examples seen in #7838 I was able to create a 100% reliable reproducer with a 2.7.6 client on Ubuntu 20.04.

```
#! /bin/sh
#
# reproduce a similar situation as discussed in https://github.com/owncloud/client/issues/7838
# Differences are
# - here it is done on Linux
# - we don't see a 404 from the server, and 'etag has changed'
# - instead we see 'Not a move, ' messages.
#
# Requires:
# sudo apt-get install docker.io netcat testpilotcloud-client


docker run --rm --name repr-7838 -d -p 7788:8080 owncloud/server:10.6.0
sleep 5 # wait docker startup

dir=/tmp/repr-7838
rm -rf $dir

env HOME=$dir testpilotcloud --showsettings --logdebug --logfile $dir/client.log &
sleep 5

test -z "$UID" && UID=$(id -u)
send() { echo "$@" | netcat -U -w 1 /run/user/$UID/testpilotcloud/socket; }
settext() { send "ASYNC_SET_WIDGET_PROPERTY:42|{\"objectName\":\"#$1\", \"property\":\"text\",\"value\":\"$2\"}"; }
click() { sleep 1; send "ASYNC_INVOKE_WIDGET_METHOD:42|{\"objectName\":\"#$1\", \"method\":\"click\"}"; sleep 1; }

send VERSION
settext leUrl http://localhost:7788
click __qt__passive_wizardbutton1
settext leUsername admin
settext lePassword admin
click __qt__passive_wizardbutton1
click __qt__passive_wizardbutton1
click __qt__passive_wizardbutton1
click __qt__passive_wizardbutton1

checksync() { sleep 1; grep 'Not a move' $dir/client.log; }


for r in 0 1 2 3 4 5 6 7 8 9 10; do
  for i in 0 1 2 3 4 5 6 7 8 9 10; do
    echo $r.$i
    mv $dir/testpilotcloud/Photos/Portugal.jpg $dir/testpilotcloud/Portugal.jpg
    checksync && break
    mv $dir/testpilotcloud/Portugal.jpg $dir/testpilotcloud/Photos/Portugal.jpg
    checksync && break
  done
  checksync && break
done

echo "Review the client debug log at $dir/client.log"
echo ""
echo "Press ENTER to kill server and client. CTRL-C to keep them."; read a
killall testpilotcloud
docker kill repr-7838
```

Wait ca 20 sec. until the client UI is fully initialized, and the shell starts counting loop numbers.
Then you may click to the activity page and watch the client's sync protocol.
It should show repeated move operations, ca. one per second. The timing intentionally provokes race conditions.
After ca 10 to 20 iterations, delete+create should occur instead, and the script stops.

I've seen two new types of errors in the logs:
```
02-25 03:21:34:562 [ info sync.discovery ]:     Processing "Photos/Portugal.jpg" | valid: false/true/db | mtime: 0/1614219677/0 | size: 0/243733/0 | etag: ""//"" | checksum: ""//"" | perm: 0x7f161e4cdd58//0x7f161e4cdd58 | fileid: ""//"" | inode: 0/657847/ | type: CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
02-25 03:21:34:562 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 1 657847
02-25 03:21:34:562 [ debug sync.database.sql ]  [ OCC::SqlQuery::exec ]:        SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE inode=?1"
02-25 03:21:34:562 [ info sync.discovery ]:     Not a move, no item in db with inode 657847
02-25 03:21:34:562 [ info sync.discovery ]:     Discovered "Photos/Portugal.jpg" CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Up CSyncEnums::ItemTypeFile
```

and 

```
02-25 03:18:53:592 [ info sync.discovery ]:     Processing "Portugal.jpg" | valid: false/true/false | mtime: 0/1614219503/0 | size: 0/243733/0 | etag: ""//"" | checksum: ""//"" | perm: 0x7f72fcb4bd58//0x7f72fcb4bd58 | fileid: ""//"" | inode: 0/657848/ | type: CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
02-25 03:18:53:592 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 1 657848
02-25 03:18:53:592 [ debug sync.database.sql ]  [ OCC::SqlQuery::exec ]:        SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE inode=?1"
02-25 03:18:53:592 [ info sync.discovery ]:     Not a move, base file still exists at "Photos/Portugal.jpg"
02-25 03:18:53:592 [ info sync.discovery ]:     Discovered "Portugal.jpg" CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Up CSyncEnums::ItemTypeFile
```

If you remove the `&& break` clauses from the loops, then you should see move operations again after a while, followed by another round of delete+create, and so on ...

**Comment by sfadschm** [comment] 2021-02-26 16:34
Like @TheOneRing mentioned in the 7838, can you try to add some waiting time in between move operations to make sure we always only look at single transactions?

**Comment by TheOneRing** [comment] 2021-03-02 13:04
As @ogoffart mentioned in https://github.com/owncloud/client/issues/7658 you should probably wait at least 2 seconds to simulate the normal behavior.

**Comment by TheOneRing** [comment] 2021-03-17 15:12
Duplicate of https://github.com/owncloud/client/issues/7077

**Closed by TheOneRing** 2021-03-17 15:12 UTC
