### ISSUE TITLE
Opening the Sharing Dialog while Settings window is in the foreground replaces one with the other

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6185] opened 2017-11-23 09:56 UTC
### Steps to reproduce
1. Open the Settings window
2. Open the Sharing Dialog from the context menu

### Actual Behavior
The settings window is replaced by the sharing dialog. 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/33167120-d4f69b5c-d03c-11e7-97d1-7a95be5eb0aa.gif"/>
</p>

Note: on windows, with also means that the dialog is created without focus:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/33166963-514abbee-d03c-11e7-9049-3f973d2165e8.gif"/>
</p>

cc/ @michaelstingl this is the one we mentioned yesterday on the demo.

**Comment by ogoffart** [comment] 2017-11-23 22:31
I think this is intentional.  We do the same with the add account wizard.

**Comment by ogoffart** [comment] 2017-11-23 22:32
```
void ownCloudGui::slotShowShareDialog(const QString &sharePath, const QString &localPath)
{
  [...]
    // For https://github.com/owncloud/client/issues/3783
    _settingsDialog->hide();
```

**Comment by ckamm** [comment] 2017-11-29 13:23
So #3783 was exactly the "share dialog has no focus" issue on OSX and hiding the settings window was done to make it work there.

**Comment by ckamm** [comment] 2018-04-10 07:11
See also #3015. Any change here must be tested on Windows and OSX in particular. On linux hiding the settings window is unnecessary in my tests.

**Comment by ckamm** [comment] 2018-04-12 09:08
Win10 experiments:
* If the account dialog is open, clicking "Share..." will close it and show the share dialog *under* the explorer window
* But if the account dialog is closed, clicking "Share..." will open the share dialog above the explorer window

If hiding the account dialog is disabled, the share dialog still pops up under the explorer window.

**Comment by ckamm** [comment] 2018-04-12 09:45
@SamuAlfageme To summarize: I couldn't do anything about the "pops up under explorer without focus" problem. :(

**Comment by guruz** [comment] 2018-04-13 14:08
@ckamm I wonder if you can launch the client from the shell extension and windows would take this as a hint..

**Comment by ckamm** [comment] 2018-04-16 06:41
@guruz Possibly, but I'd guess not. Since the behavior is correct when the client window is closed I tried workarounds like "close the client, after 2s open the share dialog" but couldn't get it to pop up over the explorer window. :/

**Comment by ckamm** [comment] 2018-04-24 08:10
The closing of the settings dialog no longer happens on linux and windows. We keep it on osx because it presumably helps put the share dialog on top.

**Closed by ckamm** 2018-04-24 08:10 UTC
Labels: Design & UX, PR available, Sharing

**Comment by guruz** [comment] 2018-04-25 17:25
I've checked macOS and at least with recent macOS and recent Qt we don't need the macOS workaround anymore with the sharedialog while there are other windows on top of the main dialog.

I'll remove the behaviour for macoS too.

**Comment by jnweiger** [comment] 2018-08-09 19:13
### linux mint tara 
250beta1, nautilus
OK the settings dialog remains open, the share dialog opens ontop.

###win10
250beta1
OK the settings dialog remains open, the share dialog opens ontop
BUT windows explorer window covers all (often, but not always! could not find a pattern)
OK the trayicon flashes in orange, so that users feel an urge to click it and bring owncloud to the front.

**Comment by guruz** [comment] 2018-08-10 17:28
Regarding win10: I think that's the expected behaviour :/ Windows is a popup blocker these days.
We were thinking of showing a desktop notification in this case, but it's OK with the flashing too. (Create an issue if you feel otherwise)
