### ISSUE TITLE
"Choose what to sync" also on computer hard drive

### ISSUE THREAD

**Issue by bartatgithub** [owncloud/client#3488] opened 2015-07-22 09:19 UTC
Dear 

After long time and happy using Owncloud on my server in combination with Owncloud iOS, i have started to use the MacOS Owncloud client application. Also very happy and lucky that this exists. 

But i have a request and i don't understand why it's not yet implemented: 
"Choose what to sync" is an important function but it's only possible on the server side. 
Why is there not a possibility to switch to "Choose what to sync" function for files on the computer hard drive? 

Example: 
Because it's more clear and a better way of working for me, i want to choose my MacOS user "Documents" folder as sync folder. 
But i wan't only to sync the folders i need in the cloud, not all of them. 

Could this be a future function or not? 

Regards

**Comment by guruz** [comment] 2015-07-22 14:45
Hi, this is a duplicate of https://github.com/owncloud/client/issues/2465
Could you please comment there so this gets counted as a feature request?

**Closed by guruz** 2015-07-22 14:45 UTC
