### ISSUE TITLE
Client 2.6 cannot upload files larger 2.1 GB

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7506] opened 2019-10-08 14:40 UTC
* Start client 2.6.0daily20190923 or client-2.6.0daily20191008 using Qt-5.12.4 on Windows 10
* connect to a 10.3 alpha server,
* wait until the initial sync finishes.
* move a 2.5 GB file into the local sync folder of the client.
* After the next sync run, this file is flagged with a red (X) and the 'not synced' tab says 'An attempt was made to move the file pointer before the beginning of the file.'
![image](https://user-images.githubusercontent.com/1108546/66405243-242c1a80-e9ea-11e9-9c99-bc3e5a50e80a.png)

Expected behaviour: It uploads.

**Comment by jnweiger** [comment] 2019-10-08 15:34
Client 2.5.4 can upload the same file with the same server:
![image](https://user-images.githubusercontent.com/1108546/66410093-d4e9e800-e9f1-11e9-980c-fb3b4a1fa4ff.png)

It is a regression.

**Comment by HanaGemela** [comment] 2019-10-08 16:33
The same happens on macOS 10.14.6, client 2.6.0 RC1, server 10.3.0 RC1
Works with client 2.5.4

Steps to recreate: 
1) Upload a 6GB file from the client to the server

Actual result: Unknown error

`10-08 18:00:48:342 [ info sync.propagator.upload ]:	Resuming  "dvd1.iso" ; sent = 2210000000 ; total= 7135559680
10-08 18:00:48:342 [ warning sync.propagator.upload ]:	Could not prepare upload device:  "Unknown error"
10-08 18:00:48:342 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 QVariant(QString, "dvd1.iso")
10-08 18:00:48:342 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT lastTryEtag, lastTryModtime, retrycount, errorstring, lastTryTime, ignoreDuration, renameTarget, errorCategory, requestId FROM blacklist WHERE path=?1 COLLATE NOCASE"
10-08 18:00:48:342 [ warning sync.propagator ]:	Could not complete propagation of "dvd1.iso" by OCC::PropagateUploadFileNG(0x600002173de0) with status OCC::SyncFileItem::SoftError and error: "Unknown error"
10-08 18:00:48:342 [ debug sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotItemCompleted ]:	Item completed "dvd1.iso" OCC::SyncFileItem::SoftError 8`

**Comment by jnweiger** [comment] 2019-10-08 16:40
Reprodced also in Linux with client 2.6.0daily20190922

![image](https://user-images.githubusercontent.com/1108546/66414947-bc320000-e9fa-11e9-8d69-b2bb20db7c4c.png)

We have different error messages on Linux and Mac now, but probably the same bug than on Windows.

It's a platform-independent regression now. Sigh.

**Comment by jnweiger** [comment] 2019-10-08 16:55
Download into the Linux client works fine. 
Download into the Windows client works fine.

**Comment by ogoffart** [comment] 2019-10-09 07:34
The regression was caused by the delta sync patch.
Fix in https://github.com/owncloud/client/pull/7508

**Comment by jnweiger** [comment] 2019-10-09 10:59
Retested on Linux with testpilotcloud version 2.6.0pr7508 (build 1563)
Git revision 8353d09314aa7afc348ae0b7dcb7ea870a776d72

2.5 GB upload works like a charm. Thank you!

**Comment by mrow4a** [comment] 2019-10-09 11:30
@ogoffart @jnweiger @guruz probably would be good to add 1 more scenario in https://github.com/owncloud/smashbox/blob/master/lib/owncloud/test_chunking.py to test chunking also for very large file over integer range. Makes sense?

**Comment by mrow4a** [comment] 2019-10-09 11:33
actually, it should go in https://github.com/owncloud/smashbox/blob/master/lib/test_nplusone.py

**Comment by ogoffart** [comment] 2019-10-09 11:56
PR merged.
Yes, i guess a smashbox test for much larger files would make a lot of sense.

**Closed by ogoffart** 2019-10-09 11:56 UTC
Labels: p2-high, regression
