### ISSUE TITLE
renaming a changing file results in two files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6862] opened 2018-11-05 18:40 UTC
Seen with owncloud-client 2.5.1 rc2 on linux mint tara running a ubuntu 18.04 build.

Reproduce:
* connect to demo.owncloud.org, create a file hello.txt with some contents, wait until sync is done.
* pause the sync
* in the client sync folder, append more text to hello.txt, e.g. with `echo huhu >> hello.txt`
* in the server web interface rename hello.txt to foo.txt
* resume sync
* Both client and server now have two files: hello.txt and foo.txt

There should be either a conflict or a renamed file with changed contents.  
(Asuming we use etags to track files. are we?)

**Comment by ogoffart** [comment] 2018-11-06 06:51
That's been the behavior for ever.  In case of "conflicts" while renaming, any renaming detection is aborted, and files are considered on their own.

Changing this could be possible, but should we do it? Then we need to define the behavior when this happen.

**Comment by ckamm** [comment] 2019-03-13 13:46
#7077 Is also about extending rename detection to more cases. This issue might be more tricky to get right though.

**Comment by TheOneRing** [comment] 2021-03-17 15:11
Duplicate of #7077

**Closed by TheOneRing** 2021-03-17 15:11 UTC
Labels: Discussion, Known Issue / Workaround
