### ISSUE TITLE
Display "0 octets" in 2.2 version

### ISSUE THREAD

**Issue by glannes31** [owncloud/client#5026] opened 2016-07-01 08:15 UTC
Hello ,
In 2.2.x version , the displaying size is equal to 0 octets.

Everything is Okay on 2.1.1 version.

**Comment by glannes31** [comment] 2016-07-01 08:17
![github](https://cloud.githubusercontent.com/assets/20032648/16515881/f33dd256-3f74-11e6-95da-5a529d04d6e3.PNG)

**Comment by mcastroSG** [comment] 2016-07-01 08:20
Hi @glannes31  may you use template defined to open this issue giving some extra info ¿?

**Comment by glannes31** [comment] 2016-07-01 08:33
### Server configuration

ownCloud version: 7.0.0.5

### Client configuration

Client version: 2.1.1

Operating system:Windows

OS language: French

Installation path of client:C:\Program Files (x86)\ownCloud

### Logs

3. ownCloud log 

[log.txt](https://github.com/owncloud/client/files/343094/log.txt)

**Comment by glannes31** [comment] 2016-07-01 08:38
More precision : the problem is on Windows, MacOsx and linux distribution

**Comment by danimo** [comment] 2016-07-01 08:45
>ownCloud version: 7.0.0.5

ownCloyd 7.0 has reached its end of life (EoL). Please update to a later version before we spend time debugging, as some of the size related issues were indeed caused by the servers & the clients are no longer validated against EoL server versions.

**Comment by danimo** [comment] 2016-07-01 08:52
I'll close this report for now. If you can still reproduce this with a more recent version, please ping us or re-open.

**Closed by danimo** 2016-07-01 08:52 UTC
Labels: bug, Needs info

**Comment by glannes31** [comment] 2017-02-02 10:47
Hello , Why i have the size displayed on the linux  client ?   My Oc server is always in 7.0.5

![image](https://cloud.githubusercontent.com/assets/20032648/22546451/6614bf70-e93d-11e6-814b-35b08f2b52a5.png)

**Comment by glannes31** [comment] 2017-02-02 11:21
Sorry , for the ping . I realize that linux is on 2.1.1 and windows 2.2.4.
