### ISSUE TITLE
[Windows] client crashes after changing Proxy

### ISSUE THREAD

**Issue by OleAlbers** [owncloud/client#4386] opened 2016-01-22 08:06 UTC
I had this error today after my company changed the proxy (using a pac-script).
Our proxy requires username/password 

Most current nightly build (ownCloud-2.1.1.5790-nightly20160121-setup.exe ) did NOT fix it: Log is attached (hostname removed)

I already started with a fresh config. It did work before with another proxy I used. (Sadly I cannot tell the technical differences between those proxys)

[log.txt](https://files.zenhub.io/56a0f64360957af771a53acb)

**Comment by ckamm** [comment] 2016-01-22 09:51
@OleAlbers Thanks for the report and the log file!
* In what way was the proxy changed? Did the url or port change?
* Did you configure the proxy explicitly in the owncloud client or is it system-wide?

Does it crash every time now? If so, a backtrace would be super-helpful.

**Comment by OleAlbers** [comment] 2016-01-22 13:36
It was a complete new URL. I switched from one proxy to another. (We have multiple proxys in our company) The proxy is used system-wide

It does crash every time. I first enter the host address of my owncloud, than the credentials for my proxy pop up. I enter those, owncloud crashes.

**Comment by ckamm** [comment] 2016-01-22 13:48
@OleAlbers Thank you. A backtrace of the crash would make the problem way easier to find. If you have any questions about it, let me know!

**Comment by OleAlbers** [comment] 2016-01-22 13:59
Did that, but after "thread apply all bt" no output is generated. Is it logged into a logfile somewhere?

**Comment by OleAlbers** [comment] 2016-01-22 14:07
Did work when run as admin. 
This was a bit different. I have a "send crash report" window when I call it directly, that one is not displayed when using gdb. It hangs completely then. gdb-output is attached
[error.log](https://files.zenhub.io/56a237a2bb42157e137dd14a)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by ckamm** [comment] 2016-01-22 14:16
@OleAlbers Unfortunately the backtrace doesn't have any symbols. Did you click 'send' in the "send crash report" dialog?

**Comment by OleAlbers** [comment] 2016-01-22 14:17
@ckamm  Did that, but this fails, too "Failed to send crash info"

**Comment by OleAlbers** [comment] 2016-01-22 14:30
What might be of interest is that my website uses an "unsafe" https-Certificate. (Did not have any affect when the old proxy was used)

**Comment by guruz** [comment] 2016-01-25 13:33
@jturcotte @danimo "Failed to send crash info".

**Comment by dragotin** [comment] 2016-01-27 15:46
Maybe mitmproxy can help: http://docs.mitmproxy.org/en/stable/features/proxyauth.html

**Comment by dragotin** [comment] 2016-01-27 16:43
Tried with authenticated mitmproxy and http server, worked here. How can I simulate a pac-script? @danimo

**Comment by OleAlbers** [comment] 2016-01-27 16:46
@dragotin For me, PAC has not to be simulated. I can read the IP-Adress out of the pac (its just a simple textfile) and try that. Will try tomorrow. Currently not at office.

**Comment by OleAlbers** [comment] 2016-01-28 08:02
Just checked. AFAIK mtmproxy does not work on Windows? I will look for another solution

**Comment by OleAlbers** [comment] 2016-01-28 08:26
I found a workaround:
1. Save the credentials in Fiddler through sniffing the traffic like described here: http://stackoverflow.com/questions/2989466/configuring-fiddler-to-use-company-networks-proxy
2. When the Owncloud-Wizard pops up, ignore it and right click onto the task icon.
3. Click onto settings
4. Change the Proxy settings to the local Fiddler
5. close and restart owncloud

You have to use fiddler, but thats fine with me. As a dev I already have it running most of the time

**Comment by guruz** [comment] 2016-02-07 11:34
@OleAlbers We had issues with the crash reporter server which should be fixed now. Would you have the time and patience to try again sending it?

FYI @danimo

**Comment by dragotin** [comment] 2016-02-08 12:57
Workaround exists, and the problem is hard to reproduce. Moving to next release.

**Comment by OleAlbers** [comment] 2016-02-09 08:20
@guruz  Still "failed to send crash info", I am not very surprised, though as this error  is about connection.

**Comment by guruz** [comment] 2017-04-26 15:14
@ckamm Is it this one you fixed recently?

**Comment by ckamm** [comment] 2017-04-27 09:24
@guruz That's quite likely, but we can't be sure since we had no backtrace here. 
@OleAlbers Could you try reproducing with a 2.3.2 build from http://download.owncloud.com/desktop/daily/ ? (or the RC)

**Closed** 2017-07-11 09:26 UTC
Labels: bug, sev2-high
