### ISSUE TITLE
[macOS] [6.0] Modal "cancel account setup" missing, client unresponsive

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11304] opened 2023-10-23 09:57 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Client becomes unresponsive when account setup is canceled in the 6.0 daily builds.

```
testpilotcloud 6.0.0.12460-daily20231023 86bbc6
Libraries Qt 6.5.3, OpenSSL 3.1.3 19 Sep 2023
Using virtual files plugin: suffix
OS: macos-23.0.0
QPA: cocoa
```

### Steps to reproduce the issue

1. Click "Add account"
2. Cancel account setup

### Screenshots

![CleanShot 2023-10-23 at 11 52 07](https://github.com/owncloud/client/assets/214010/65d7e43f-8ea8-49f3-954b-61ca2dba1c93) | ![CleanShot 2023-10-23 at 11 52 26](https://github.com/owncloud/client/assets/214010/eaa5bb87-9022-4dd8-9775-a16757ca7fd3)
-- | --
`ownCloud 5.1.0.12434-rc.1 77a8ee` 👍 | `testpilotcloud 6.0.0.12460-daily20231023 86bbc6` :warn

**Comment by erikjv** [comment] 2023-10-23 13:40
I do not have the problem with Qt 6.4.3, but I will test with a newer version.

**Comment by erikjv** [comment] 2023-10-23 14:27
It is a Qt problem. After upgrading to 6.5.3 I can reproduce it.

**Comment by michaelstingl** [comment] 2023-10-23 14:28
> I do not have the problem with Qt 6.4.3, but I will test with a newer version.

Yes, works with `Qt 6.4.3` and fails with `Qt 6.5.3`

**Comment by erikjv** [comment] 2023-10-24 14:58
Qt 6.6 has been released, we should re-test with that.

**Comment by TheOneRing** [comment] 2023-11-02 13:11
Currently waiting for craft to get Qt6.6 ready

**Comment by TheOneRing** [comment] 2023-11-16 10:14
Appears still to be an issue in Qt6.6

**Comment by TheOneRing** [comment] 2023-11-16 10:15
Possible duplicate of: https://github.com/owncloud/client/issues/11208

**Comment by michaelstingl** [comment] 2023-11-16 10:26
> Possible duplicate of: #11208

I don't think so.

This problem doesn't happen with the current stable releases, only with pre-release builds from the master branch. https://github.com/owncloud/client/issues/11208 also happens with the stable releases 5.0.0, 5.1.0, 5.1.2 etc

**Comment by TheOneRing** [comment] 2023-11-16 12:47
Its a regression in Qt 6.5+ .
But have a similar issue on some linux desktops.
In the wizard we could use a special wizard page instead of yet another modal dialog.
@fmoc ^ what do you think?

**Comment by fmoc** [comment] 2023-11-17 14:37
We consider removing that dialog entirely. It does not add a lot of value but causes problems. Users can easily re-type their few information again. @michaelstingl what do you think?

**Comment by michaelstingl** [comment] 2023-11-17 14:47
> We consider removing that dialog entirely. It does not add a lot of value but causes problems. Users can easily re-type their few information again. @michaelstingl what do you think?

Works for me 👍  Change in the 6.0-alpha1 ?

**Closed** 2024-01-17 16:50 UTC
Labels: Discussion, p2-high, Upstream issue, macOS, Qt6
