### ISSUE TITLE
Overlay icons with: Owncloud, Dropbox and Synology Cloud Station in Windows 10

### ISSUE THREAD

**Issue by mbs1337** [owncloud/client#6637] opened 2018-07-05 19:06 UTC
According to some threads around here on github about problems with the sync icons in Windows 10 

There is a solution here thanks to: https://www.garethjmsaunders.co.uk/2015/03/22/managing-overlay-icons-for-dropbox-and-tortoisesvn-and-tortoisegit/

**I have manage to get it to work with 14 items + the 1 default below:** 

Go into Regedit in ADMIN mode: 

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers`

![image](https://user-images.githubusercontent.com/3889166/42342688-1e80146e-8097-11e8-874c-246a526cb760.png)

**Comment by ogoffart** [comment] 2018-07-09 07:01
I don't understand this issue.
Is this a duplicate of #6203
What do we have to fix?  I guess we could change the names of our icons to prioritize them more...

**Comment by guruz** [comment] 2018-07-09 11:00
@mbs1337 Thanks for the link. I think we can close this issue here as you commented on the other issues already:)
https://github.com/owncloud/client/issues/6203#issuecomment-402822053
https://github.com/owncloud/client/issues/6139#issuecomment-402821951

**Closed by guruz** 2018-07-09 11:00 UTC
Labels: Known Issue / Workaround
