### ISSUE TITLE
Desktop client causing Active Directory account lockouts

### ISSUE THREAD

**Issue by techjordan** [owncloud/client#2186] opened 2014-09-09 17:42 UTC
### Expected behaviour
The user's AD password is changed and the client prompts for the updated password. If the client is left without updating the password the AD account remains unlocked.

### Actual behaviour
The user's AD password is changed but the client does not prompt for the updated password. The client indicates that the credentials are incorrect and the AD account becomes locked. The AD account remains unlocked once the client is not running. Rolling back to version 1.6.0 stopped the lockouts.

### Steps to reproduce
1. Exit the client
2. Unlock the AD account
3. Load the client

### Server configuration
Operating system: Server 2008 R2 SP1

Web server: IIS 7.5

Database: mySQL 5.5.30

PHP version: 5.3.18

ownCloud version: 4.5.7

Storage backend: SAN

### Client configuration
Client version: 1.6.3

Operating system: Windows 8

OS language: English

Installation path of client: default

**Comment by guruz** [comment] 2015-03-26 06:20
@ckamm This issue is a reason to not re-try auth (https://github.com/ckamm/mirall/commit/194ace7f4a385a963c9c6e6cdb8cf86a9674b66d) and just show the dialog (https://github.com/ckamm/mirall/commit/cc4c40d4427753916987328fda492483e53570f6)

**Comment by ckamm** [comment] 2015-03-26 08:23
This has several conflicting points of view:

1) The account locks after a couple of failed webdav queries with wrong password, please never retry if auth failed!
2) Sometimes the LDAP auth backend restarts and authed requests fail, please don't bother our users about it! #2848 
3) The client does many parallel requests during sync.

1) and 2) obviously conflict. 
1) and 3) also conflict, because if the AD password changed during a sync it's likely that we'd query the server with several parallel requests using the old password before getting the first 'auth failed' reply back, locking the account.

The only reasonable solution I can see right now is having a separate, explicit authentication request that results in a session cookie the client can use for further requests. Effectively logging in anew with each request just can't work with 1).

@PVince81 I don't know much about authentication in the server, is there a way we could do it with the existing API?

**Comment by guruz** [comment] 2015-03-26 08:42
> 3) The client does many parallel requests during sync.

IMHO we need to remove the user:password base64 from the WebDAV requests, then only the session cookie is used (which does not do any re-login by itself). Then only ```checkServerAndAuth``` (or whatever it is called) does actual authentication.

**Comment by danimo** [comment] 2015-03-26 08:45
@guruz Too much speculation here, the last time we checked this, the session took precedence. Let's analyze this today.

**Comment by ckamm** [comment] 2015-03-26 10:22
We talked about the issue in detail. Currently each request usually has a session cookie as well as the user and password. So each request could be considered a possible login. But the user/pw will only be used if the session cookie is invalid. That means this ticket is probably not due to parallel request with outdated credentials.

I've looked at @tomswartz07's comment and implemented a fix for deleting the old registry key in 6b1ba78 that will likely end up in 1.8.1.

Could anyone experience account lockouts that were unrelated to upgrading from old owncloud clients?

**Comment by guruz** [comment] 2015-05-05 16:24
> IMHO we need to remove the user:password base64 from the WebDAV requests, then only the session cookie is used

For the record @ogoffart has done this for 2.0 https://github.com/owncloud/client/commit/ae17f58b80208df0e6318dbabbfabd7ae842332e

**Comment by moscicki** [comment] 2015-05-05 19:00
For the root cause of this problem: isn't this the owncloud server problem/limitation that it tries to authenticate against AD too often with the basic auth instead of properly caching this for some time (as for the cookies)? And if the owncloud server notices that they can implement a policy of not trying to contact AD with invalid password.

As per removing basic authentication: unfortunately this change breaks cernbox as our server does not support cookie authentication. I don't think this works for us now and I do not know if this ever will.

**Comment by Dianafg76** [comment] 2015-05-15 07:37
I tested the issue, and the password is change and the password the AD account is not unlocked.
Desktop v1.8.2 (build 2362)
So I close the Issue

**Closed by Dianafg76** 2015-05-15 07:37 UTC
Labels: bug, Needs info, ReadyToTest, sev3-medium
