### ISSUE TITLE
Docs are missed for 2.7 version

### ISSUE THREAD

**Issue by davitol** [owncloud/client#8081] opened 2020-09-14 12:06 UTC
Built from Git revision 4cb5cf on Sep 14 2020, 02:12:32 using Qt 5.12.9, OpenSSL 1.1.1g 21 Apr 2020 using Mac Client

<img width="976" alt="Screenshot 2020-09-14 at 14 04 14" src="https://user-images.githubusercontent.com/10596560/93083730-5383e680-f693-11ea-8662-2caf2cdee9b0.png">

<img width="1279" alt="Screenshot 2020-09-14 at 14 05 37" src="https://user-images.githubusercontent.com/10596560/93083783-672f4d00-f693-11ea-820b-401fdceac727.png">

**Comment by michaelstingl** [comment] 2020-09-14 12:20
@TheOneRing please remove version string:
https://doc.owncloud.org/desktop/

**Comment by TheOneRing** [comment] 2020-09-14 12:26
We have versioned docs https://doc.owncloud.org/desktop/2.6/ , but the 2.7 docs are not generated yet, part of the release process?
@jnweiger

**Comment by jnweiger** [comment] 2020-09-15 10:31
https://confluence.owncloud.com/display/OG/Documentation

**Comment by TheOneRing** [comment] 2020-09-15 11:00
It is step two in the ticket https://github.com/owncloud/client/issues/7966 so it is covered by the release ticket.
Duplicate of https://github.com/owncloud/client/issues/7966

**Comment by TheOneRing** [comment] 2020-09-15 13:20
As mentioned by @jnweiger , this is not about maintaining multiple versions of the doc, but keeping the old one but also providing the new ones.
@michaelstingl

**Comment by TheOneRing** [comment] 2020-09-17 11:42
https://github.com/owncloud/docs/pull/2788

**Closed by TheOneRing** 2020-09-17 11:42 UTC
