### ISSUE TITLE
CSync failed to access

### ISSUE THREAD

**Issue by TinusS1** [owncloud/client#5712] opened 2017-04-19 12:21 UTC
### Expected behaviour
Normal sync behaviour.

### Actual behaviour
CSync error for one specific folder, all the other shares dont synchronize too. 

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system: CentOS 6.1

Web server: nginx

Database: mysql 5.5.54

PHP version:  5.6.30

ownCloud version: 9.1.3 (stable)

### Client configuration
Client version:  2.2.4 build 6408

Operating system: Windows 10 + Windows 2012 R2

OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

![afbeelding](https://cloud.githubusercontent.com/assets/27768676/25179792/aa1be4d2-250b-11e7-8fea-434a6742adec.png)

When looking directly on the server in the storage folder i cannot find the specific folder however in the webinterface the folder is still there and cannot be removed or renamed.

**occ files:scan doesn't solve this issue.**

My workaround is to create a directory with the same name so that the clients can synchronize again.

![afbeelding](https://cloud.githubusercontent.com/assets/27768676/25179555/b7f00fb2-250a-11e7-902d-dfbc11c98b44.png)

I have similar behaviour in a different folder but then with files that cannot me removed/renamed  and the files are not visible on the server.

Any ideas on how i can solve this issue?

**Comment by guruz** [comment] 2017-04-19 13:34
@TinusS1 How is your server configured? You are using sharing (Who to who etc), external storages, encryption etc?

@PVince81 Can you help?

**Comment by TinusS1** [comment] 2017-04-19 13:39
@guruz

**Comment by TinusS1** [comment] 2017-04-19 13:41
@guruz No external storages, no encryption, We are using AD/LDAP(groups) to share in between users (i hope this is what you meant.)

**Comment by TinusS1** [comment] 2017-04-23 15:58
Anyone?

**Comment by guruz** [comment] 2017-04-23 16:07
@TinusS1 Maybe @PVince81 has an idea on monday.
But I'd possibly try to get on 9.1.5, maybe that helps
(This is probably a server issue..)

**Comment by PVince81** [comment] 2017-04-24 19:19
> create a directory with the same name

How are you creating the second directory ? The screenshots seems to show two identical directories in the same folder. This is impossible.

The database wouldn't allow for this. `select * from oc_filecache where path like '%yourfolder%'` replace "yourfolder" with your folder name.

I suspect that the name might not be 100% the same. Maybe some weird variant of UTF-8 characters.

Were any Macs involved ?

**Comment by TinusS1** [comment] 2017-04-25 07:51
@guruz 
Thanks, i have updated to 9.1.5 last night and ran another filescan, the problems didn't get solved.

@PVince81 Thanks for your reply, Some macs do have access to this share, but this specific folder should only be managed/accessed by a Windows user.

I have ran the query and it only returns the one folder I have created in order to solve the sync issues.
![afbeelding](https://cloud.githubusercontent.com/assets/27768676/25374199/b22e33d8-299c-11e7-9d8b-e1949306e445.png)

**Comment by PVince81** [comment] 2017-04-25 14:14
`occ files:scan --all -vvvvvvv`
or
`occ files:scan affecteduser -vvvvvv`

It should output all folders it's scanning, check whether it goes into that specific one.

**Comment by guruz** [comment] 2017-04-26 13:15
@TinusS1 Any news?

**Comment by TinusS1** [comment] 2017-04-26 13:19
@PVince81 @guruz 
Thanks guys, i ran occ files:scan affecteduser -vvvvvv. It scans the folder in which this "Oud" folder is located but it doesn't scan the Oud folder. So to answer your question, no it doesn't go into this specific one.

**Comment by guruz** [comment] 2017-04-26 13:29
And how does this look on the server's directory? Is there one Oud or two? (with similar utf8)

**Comment by wuppel** [comment] 2017-05-02 12:53
Hello, we have the same problem with our owncloud Instance. In our case there ist only one "xyz" folder at the server; At the desktop-client-Sync-List - you see both folders (with the same name); via Webbrowser you also see the two folders with the same same.

**Comment by wuppel** [comment] 2017-05-02 12:55
Oh - sorry, we have the server version: ownCloud 9.1.4 (production) - community edition; an the mac client version: 2.3.1 build 4139

**Comment by guruz** [comment] 2017-05-03 08:24
>  only one "xyz" folder at the server

> via Webbrowser you also see the two folders with the same same.

Humm... @PVince81 ?

> At the desktop-client-Sync-List - you see both folders (with the same name)

Would you have a screenshot? If you don't want to disclose the filenames here you can write me privately $my_nickname_at_github at owncloud.com

@TinusS1 Maybe you also can answer still the question above, thanks:)

**Comment by TinusS1** [comment] 2017-05-03 08:37
@PVince81 @guruz 

Sorry due to holidays i wasn't able to reply any quicker. sorry!

On the server directory there is only one 'Oud' folder and nothing similar.
The second 'Oud' folder I created in order to solve the sync issues is located in the storage folder.

**Comment by TinusS1** [comment] 2017-05-03 08:41
After some further research i found out that the conflicting folder was created from a mac.

**Comment by guruz** [comment] 2017-05-03 08:59
@TinusS1 @wuppel Would you say this is a regression? E.g. something that happend after/only when you updated the client or server?

**Comment by wuppel** [comment] 2017-05-03 09:17
no, our update (client/server) is some weeks ago. We have >400 User; and this happens only at one share/folder/user. So there is no pattern ... as I know.

**Comment by guruz** [comment] 2017-05-03 09:18
@wuppel And you see the error on a Mac?
But @TinusS1 sees it on Windows?

**Comment by TinusS1** [comment] 2017-05-03 10:01
I see the error on Windows, and it blocks all synchronisation activity **i'm not sure** if i remove the 'Oud' file I created as temporary solution I would have the error on Mac’s too.

**Comment by wuppel** [comment] 2017-05-03 11:25
yes, I see the error on Mac an Windows Desktop Client; I also see the "invalid/double" folders at the browser!!! ; if I go directly to the server via terminal/console - I see only one folder - so there is the only correct place.

**Comment by TinusS1** [comment] 2017-05-09 13:06
@guruz  Sorry, just to be clear. Does the milestone mean this will be looked at and perhaps addressed in 2.4.0?

**Comment by guruz** [comment] 2017-05-10 13:38
@TinusS1 It means that yes. However we need a way to reproduce this or more information for that.. So I can't guarantee it.

@PVince81 is there any helpful SQL query on the shares tables that you'd need to get more info?
Or any logs?

**Comment by PVince81** [comment] 2017-05-17 14:55
If the files:scan command doesn't scan this folder then it's very weird... and doesn't even report an exception. As if the folder wouldn't even exist ? Is that folder a symbolic link or hard link maybe ?

**Comment by TinusS1** [comment] 2017-05-19 09:17
No symbolic link or hard link.

**Comment by TinusS1** [comment] 2017-05-19 09:20
We just had the same issue on a **different** owncloud server 9.1.3

Csync error's upon further investigation it is because of two excel files.
Had to apply the same workaround again, creating two files with the same name in order to get the clients working again:

![afbeelding](https://cloud.githubusercontent.com/assets/27768676/26241478/1f1742f0-3c85-11e7-81e2-02abec6d0713.png)

macs and windows devices involved.

**Comment by guruz** [comment] 2017-05-22 10:15
@butonic Any idea?

**Comment by felixboehm** [comment] 2017-06-08 11:04
- Can you reproduce with the same file in another folder?
- Are you interested in a screenshare for some pairing on bug analysis?

Milestone makes no sense as long as we have no understanding of the root cause.

**Comment by guruz** [comment] 2017-06-20 10:37
@SergioBertolinSG Would you say this is related to https://github.com/owncloud/core/issues/28018 ?

**Comment by SergioBertolinSG** [comment] 2017-06-20 12:06
Not sure, maybe. That issue is not fixed yet, the PR is still pending to be reviewed and merged https://github.com/owncloud/core/pull/28022 .

**Comment by guruz** [comment] 2017-06-20 14:16
@TinusS1  @wuppel Was it file/directory moves between different received shares for you?

**Comment by jlord87** [comment] 2017-06-22 10:15
I can confirm this bug (or something really similar):
In my environment a mac user created "folder a" inside a shared folder called "root" (so it was in his mac something like "/Users/name/owncloud/root/folder a")

a windows user (who was in the group of users whom the "root" folder was shared to) moved (or copied, she can't remember) the "folder a" into her owncloud folder and then shared again.

Now from the web interface she sees almost every folder in "folder a" duplicated, while in the server there are no duplicate.
She was receiving the csync error in her client.
I tried with an "occ scan etc." but it didn't work.

Having to solve the problem I removed from the server the "folder a" from her user, rescan her files and everything seems now working.

btw: owncloud 9.1.5 community, ubuntu 16.04; clients updated on windows (2.3.2 if I'm not wrong), not really sure on mac...

**Comment by TinusS1** [comment] 2017-06-22 10:32
@guruz 
I believe every single time the issues did start when a user moved the files/directories 
yes.

**Comment by PVince81** [comment] 2017-06-26 11:25
can you guys check whether your filecache looks like this https://github.com/owncloud/core/issues/28018#issuecomment-304270786. In your case, replace "two" with the name of the entry that appears twice. Basically the "path" value doesn't match the parent-child relationship.

**Comment by PVince81** [comment] 2017-06-26 11:26
https://github.com/owncloud/core/issues/22866#issuecomment-253213394

**Comment by PVince81** [comment] 2017-06-26 11:29
you can try this query to find broken entries: https://github.com/owncloud/core/issues/28018#issuecomment-311033479

**Comment by PVince81** [comment] 2017-06-26 12:38
If the query from https://github.com/owncloud/core/issues/28018#issuecomment-311033479 provide results. And if you have a **backup** and are **feeling adventurous**, you could try this experimental repair step https://github.com/owncloud/core/pull/28217 which resets the path to the correct value.

I have only tested this in my local env and it works, but there is no guarantee yet that it will work in other scenarios. Would be good to see the broken entries from everyone to be able to evaluate.

**Comment by PVince81** [comment] 2017-07-03 10:48
I've refined the repair steps and one other bug reporter (https://github.com/owncloud/core/issues/28277) already confirmed that it fixes the issue for him. I'd appreciate if you guys could also confirm that this https://github.com/owncloud/core/pull/28253 fixes the filecache inconsistency for you. To prevent further inconsistencies you'll also need https://github.com/owncloud/core/pull/28022 (9.1 patch here https://github.com/owncloud/core/pull/28238).

**Comment by PVince81** [comment] 2017-07-03 10:49
I'm closing this as duplicate of https://github.com/owncloud/core/issues/28018 as it's highly likely to be that server bug.

**Closed by PVince81** 2017-07-03 10:49 UTC
Labels: bug, Server Involved
