### ISSUE TITLE
1.7.0rc1: (multiple folder pairs) spurious "no connection" when one of the sync folder pairs ceased to exist on the server

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2411] opened 2014-10-27 15:23 UTC
I have a setup with 4 sync folder pairs. One is paused, the other two are fine and the 4th folder has been removed on the server. Client reports it like that:

![image](https://cloud.githubusercontent.com/assets/621965/4792922/28318ec6-5dea-11e4-84b1-8577d5b4ed13.png)

In the logs this is 

```
10-27 16:15:13:836 0x7fe1d190c830 networkjobs.cpp:208 !!! Mirall::RequestEtagJob created for  QUrl( "https://devbox.cern.ch" )  querying "FOLDER_TEST"
10-27 16:15:13:973 0x7fe1d190c830 networkjobs.cpp:153 void Mirall::AbstractNetworkJob::slotFinished() 203 "Error downloading https://server.com/remote.php/webdav/FOLDER_TEST - server replied: Not Found"
```
This shows in the Mac's top bar like this:

![image](https://cloud.githubusercontent.com/assets/621965/4792830/7efdcb4e-5de9-11e4-9a55-def26c1390a6.png)

First, I think that this error condition should not necessarily result in this status in the top bar. 

But most importantly, now periodically the client reports "No connection" to the server (even though there is a perfect connection to the server).

So regularly (apparently in a  loop) the client reports like this:

![image](https://cloud.githubusercontent.com/assets/621965/4792769/35095ddc-5de9-11e4-9a10-984f5243d80a.png)

And the top bar becomes: 
![image](https://cloud.githubusercontent.com/assets/621965/4792902/0334bfee-5dea-11e4-8912-30643543e1c7.png)

I think this is because the client interprets the inaccesible fodler as a server connection problem. This logic is applied in turns for each folder, so every four sync runs or so. 

```
10-27 16:15:50:937 0x7fe1d3301cb8 oc_module: Call the csync callback for SSL problems
10-27 16:15:50:937 0x7fe1d3301cb8 credentialscommon.cpp:58 SSL Fingerprint from neon:  "28:8f:05:fa:c5:d7:a3:97:22:69:b7:c1:ab:95:68:5f:a9:e4:d5:85"  compared to verif
ied:  "28:8f:05:fa:c5:d7:a3:97:22:69:b7:c1:ab:95:68:5f:a9:e4:d5:85"
10-27 16:15:50:937 0x7fe1d3301cb8 oc_module: ## VERIFY_SSL CERT: 0
10-27 16:15:51:090 0x7fe1d3301cb8 oc_module: Authentication required 
10-27 16:15:51:090 0x7fe1d3301cb8 oc_module: Call the csync callback for Please provide your account information here:
10-27 16:15:51:269 0x7fe1d3301cb8 oc_module: Neon error code was 1
10-27 16:15:51:269 0x7fe1d3301cb8 oc_module: WRN: propfind named failed with 1, request error: 404 Not Found
10-27 16:15:51:269 0x7fe1d3301cb8 oc_module: Errno set to 2
10-27 16:15:51:269 0x7fe1d3301cb8 csync_statedb_close: sqlite3_close=0
10-27 16:15:51:270 0x7fe1d190c830 syncengine.cpp:502  #### ERROR during  csync_update :  "CSync failed to access https://server.com/remote.php/webdav/FOLDER_TEST"
10-27 16:15:51:271 0x7fe1d190c830 syncengine.cpp:800 CSync run took  750
```

The size of log file pattern also seems to confirm this (the paused folder is very big):

```
-rw-r--r--  1 moscicki  wheel     849 Oct 27 16:21 /tmp/log/owncloud.log.40
-rw-r--r--  1 moscicki  wheel   22081 Oct 27 16:21 /tmp/log/owncloud.log.39
-rw-r--r--  1 moscicki  wheel  141836 Oct 27 16:21 /tmp/log/owncloud.log.38
-rw-r--r--  1 moscicki  wheel   27094 Oct 27 16:21 /tmp/log/owncloud.log.37
-rw-r--r--  1 moscicki  wheel    3209 Oct 27 16:20 /tmp/log/owncloud.log.36
-rw-r--r--  1 moscicki  wheel   22081 Oct 27 16:20 /tmp/log/owncloud.log.35
-rw-r--r--  1 moscicki  wheel  141836 Oct 27 16:20 /tmp/log/owncloud.log.34
-rw-r--r--  1 moscicki  wheel   27094 Oct 27 16:20 /tmp/log/owncloud.log.33
-rw-r--r--  1 moscicki  wheel    3209 Oct 27 16:19 /tmp/log/owncloud.log.32
-rw-r--r--  1 moscicki  wheel   22081 Oct 27 16:19 /tmp/log/owncloud.log.31
-rw-r--r--  1 moscicki  wheel  141835 Oct 27 16:19 /tmp/log/owncloud.log.30
-rw-r--r--  1 moscicki  wheel   27094 Oct 27 16:19 /tmp/log/owncloud.log.29
-rw-r--r--  1 moscicki  wheel    3209 Oct 27 16:18 /tmp/log/owncloud.log.28
-rw-r--r--  1 moscicki  wheel   22081 Oct 27 16:18 /tmp/log/owncloud.log.27
-rw-r--r--  1 moscicki  wheel  142521 Oct 27 16:18 /tmp/log/owncloud.log.26
-rw-r--r--  1 moscicki  wheel   27288 Oct 27 16:18 /tmp/log/owncloud.log.25
-rw-r--r--  1 moscicki  wheel    3209 Oct 27 16:17 /tmp/log/owncloud.log.24
-rw-r--r--  1 moscicki  wheel   22083 Oct 27 16:17 /tmp/log/owncloud.log.23
-rw-r--r--  1 moscicki  wheel  141836 Oct 27 16:17 /tmp/log/owncloud.log.22
-rw-r--r--  1 moscicki  wheel   27096 Oct 27 16:17 /tmp/log/owncloud.log.21
-rw-r--r--  1 moscicki  wheel    3209 Oct 27 16:16 /tmp/log/owncloud.log.20
-rw-r--r--  1 moscicki  wheel   22081 Oct 27 16:15 /tmp/log/owncloud.log.19
-rw-r--r--  1 moscicki  wheel  141835 Oct 27 16:15 /tmp/log/owncloud.log.18
-rw-r--r--  1 moscicki  wheel   27096 Oct 27 16:15 /tmp/log/owncloud.log.17
-rw-r--r--  1 moscicki  wheel    3209 Oct 27 16:15 /tmp/log/owncloud.log.16
-rw-r--r--  1 moscicki  wheel   22081 Oct 27 16:14 /tmp/log/owncloud.log.15
-rw-r--r--  1 moscicki  wheel  141835 Oct 27 16:14 /tmp/log/owncloud.log.14
-rw-r--r--  1 moscicki  wheel   27094 Oct 27 16:14 /tmp/log/owncloud.log.13
-rw-r--r--  1 moscicki  wheel    3209 Oct 27 16:14 /tmp/log/owncloud.log.12
-rw-r--r--  1 moscicki  wheel   22081 Oct 27 16:13 /tmp/log/owncloud.log.11
-rw-r--r--  1 moscicki  wheel  141835 Oct 27 16:13 /tmp/log/owncloud.log.10
-rw-r--r--  1 moscicki  wheel   27006 Oct 27 16:13 /tmp/log/owncloud.log.9
-rw-r--r--  1 moscicki  wheel    4307 Oct 27 16:13 /tmp/log/owncloud.log.8
-rw-r--r--  1 moscicki  wheel  145783 Oct 27 16:12 /tmp/log/owncloud.log.7
-rw-r--r--  1 moscicki  wheel   19775 Oct 27 16:11 /tmp/log/owncloud.log.6
-rw-r--r--  1 moscicki  wheel   24288 Oct 27 16:11 /tmp/log/owncloud.log.5
-rw-r--r--  1 moscicki  wheel  145616 Oct 27 16:11 /tmp/log/owncloud.log.4
-rw-r--r--  1 moscicki  wheel   19657 Oct 27 16:11 /tmp/log/owncloud.log.3
-rw-r--r--  1 moscicki  wheel   22870 Oct 27 16:11 /tmp/log/owncloud.log.2
-rw-r--r--  1 moscicki  wheel  153396 Oct 27 16:11 /tmp/log/owncloud.log.1
```

**Comment by guruz** [comment] 2015-03-26 14:43
@ckamm I believe you might have fixed this already implicitly

**Comment by ckamm** [comment] 2015-03-27 07:37
I'll try to reproduce with 1.8

**Comment by ckamm** [comment] 2015-03-27 07:46
I set up three folders in a similar way: one paused, one ok, and one where the folder has been deleted on the server.

The overall status has the red x. I think that's fine: one of the folders failed to sync completely.

I did not observe the problem where the full account enters a disconnected state. It's indeed likely that this was implicitly fixed with the AccountState refactoring.

@moscicki It seems to work fine for me, can you confirm it works for you with 1.8?

**Comment by Dianafg76** [comment] 2015-04-21 12:41
Hey, checking this.

I have not able to reproduce the non-conection to the server error.  Checked on ownCloud-1.8.1.2292-nightly20150418

However, not sure that the overall status as error for the desktop client is fine, it's confusing. The error is failed, the folder does not exist any longer on the server, cc/ @MTRichards what do you think?

Clossing this ticket since its main aim is fixed, @moscicki please reopen if this didn't work for you

**Closed by Dianafg76** 2015-04-21 12:41 UTC
Labels: bug, ReadyToTest
