### ISSUE TITLE
Windows owncloud resync issue

### ISSUE THREAD

**Issue by sivabizruntime** [owncloud/client#3630] opened 2015-08-14 13:08 UTC
![owncloud windows client sync 1](https://cloud.githubusercontent.com/assets/13331461/9274477/d8ebd9ac-42b3-11e5-889e-106523944ad9.jpg)
I am using OwnCloud from windows client most days. From time to time, I see a big amount of data re synced, that I did not expect to be candidate of changes.

plz give me solution 

thanks in advance

**Comment by tflidd** [comment] 2015-08-14 15:06
Related to this one: https://github.com/owncloud/client/issues/3530 ?
Some more information will be needed: https://github.com/owncloud/client/blob/master/issue_template.md

**Comment by danimo** [comment] 2015-08-15 01:04
Duplicate of #3530. Please add your finding here as described by @tflidd

**Closed by danimo** 2015-08-15 01:04 UTC

**Comment by sivabizruntime** [comment] 2015-08-20 12:36
Operating system: Windows 7

Web server: apache2

PHP version: 5

ownCloud version: 8.1

Client configuration

Client version: 1.8.4


Log File details:


08-20 11:58:39:458 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 11:58:39:463 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1394 s)
08-20 11:58:39:476 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 11:58:39:477 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 11:58:42:673 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 11:58:42:674 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 11:58:43:586 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 11:58:43:586 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 11:58:43:591 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 11:58:48:585 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:58:48:585 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:58:48:585 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 11:58:52:508 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:58:52:508 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:58:52:508 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0
08-20 11:58:57:572 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://example.com" + "/"
08-20 11:59:06:740 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:06:740 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:06:740 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 11:59:09:475 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 11:59:09:475 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1424 s)
08-20 11:59:09:476 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 11:59:09:477 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 11:59:13:739 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 11:59:13:739 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 11:59:13:743 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 11:59:14:685 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 11:59:14:685 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 11:59:23:741 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:23:741 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:23:741 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 11:59:31:737 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://example.com" + "/"
08-20 11:59:39:490 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 11:59:39:490 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1454 s)
08-20 11:59:39:491 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 11:59:39:491 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 11:59:43:483 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 11:59:43:484 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 11:59:43:486 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 11:59:46:698 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 11:59:46:698 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 11:59:55:724 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:55:724 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:55:724 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 12:00:06:027 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://example.com" + "/"
08-20 12:00:09:506 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 12:00:09:507 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1484 s)
08-20 12:00:09:509 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 12:00:09:510 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 12:00:14:147 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 12:00:14:148 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 12:00:14:152 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 12:00:15:233 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:15:233 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:15:233 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 12:00:18:710 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 12:00:18:711 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 12:00:27:707 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:27:707 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:27:707 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0
08-20 12:00:39:522 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 12:00:39:523 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1514 s)
08-20 12:00:39:524 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 12:00:39:524 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 12:00:40:086 0x7b8ab0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
08-20 12:00:40:088 0x7b8ab0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

08-20 12:00:40:088 0x7b8ab0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
08-20 12:00:40:506 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://example.com" + "/"
08-20 12:00:43:740 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 12:00:43:740 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 12:00:43:743 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 12:00:48:742 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:48:743 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:48:743 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 12:00:50:725 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 12:00:50:725 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 12:00:59:713 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:59:713 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:59:713 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0
