### ISSUE TITLE
Mac OS X client: Unable to share documents without password

### ISSUE THREAD

**Issue by nebukadnezar** [owncloud/client#3762] opened 2015-09-05 07:53 UTC
Right click on a document or folder inside an ownCloud folder, select "share in ownCloud" and I am unable to share files or folders without having to enter a password. 
This has been like that with the last two versions of the OS X client, don't know about previous releases.

See: https://forum.owncloud.org/viewtopic.php?f=14&t=30261

**Comment by guruz** [comment] 2015-09-06 21:20
Which version?
Could you make a screenshot to explain what you mean by saving "unable to share"..

**Comment by gsosna** [comment] 2015-09-06 21:23
Actually, I'm on windows version 2.0.1 (build 5446), and have the same problem. And if I untick the "share" tickbox, I get OCS API error code: 404.

I'm currently using server version 
![snag-0005](https://cloud.githubusercontent.com/assets/7143973/9706694/08d5bf3e-5542-11e5-80b3-ace8ce3368d7.jpg)
![snag-0006](https://cloud.githubusercontent.com/assets/7143973/9706693/08d34830-5542-11e5-99f9-88bc4f67b18c.jpg)

8.1.0 (stable)

**Comment by nebukadnezar** [comment] 2015-09-06 22:14
Client version 2.0.1 (build 2694), Server version 8.1.1

I used to get "OCS API Error code: 404" as well when unticking the password
checkmark, but that went away in this latest client version: the password
checkmark is greyed out (but checked) so it's not possible to share a link
without entering a password. The "share" button cannot be clicked until a
password is entered. I'll send a screenshot next time I'm at my computer.

**Comment by gsosna** [comment] 2015-09-06 22:21
It's only affecting the clients. Sharing publicly without password works fine via web interface.

**Comment by nebukadnezar** [comment] 2015-09-07 00:09
Here's a screenshot for the sharing dialog with the greyed out but selected
"require password" checkmark:

[image: Inline images 1]

**Comment by guruz** [comment] 2015-09-07 00:26
Could you have a look at https://github.com/owncloud/core/pull/18274  and check if that helps?

**Comment by rullzer** [comment] 2015-09-07 06:44
@nebukadnezar yes please toggle all the share options on the server. The problem is I used the wrong defaults. It is fixed in the next server release. But that should fix your problem.

**Comment by tony5** [comment] 2015-09-09 13:10
I have the same problem with Ubuntu 14.04/nautilus, the issue is not specific to mac.
I tried to toggle share options but that did not seem to help.

**Comment by guruz** [comment] 2015-09-11 00:13
@nebukadnezar @gsosna Have you tried the workaround described in https://github.com/owncloud/client/issues/3703#issuecomment-136152864 ?

**Comment by gsosna** [comment] 2015-09-11 04:18
Hello @guruz. Sorry for the delay. Yes, the workaround described in #3703 has fixed my issue after restarting the client.

**Comment by cluelessperson** [comment] 2015-09-11 13:45
I believe this is a duplication of https://github.com/owncloud/client/issues/3760

In Windows, you cannot share without setting a password.

**Comment by guruz** [comment] 2015-09-13 21:53
Great, let's close this and keep https://github.com/owncloud/client/issues/3760 open so people find the workaround there

**Closed by guruz** 2015-09-13 21:53 UTC
Labels: Needs info

**Comment by nebukadnezar** [comment] 2015-09-13 21:54
Yah sorry for the late reply, workaround works.
